Text_SwordsDanceTeach_IT::
    .string "Che posto tranquillo, vero? È\n"
    .string "perfetto per allenarsi.\p"
    .string "E a furia di combattere, sto\n"
    .string "diventando sempre più forte, sai?\p"
    .string "A proposito di aumento di forza,\n"
    .string "vuoi che insegni DANZASPADA\l"
    .string "ad uno dei tuoi POKéMON?$"

Text_SwordsDanceDeclined_IT::
    .string "Beh, come vuoi.$"

Text_SwordsDanceWhichMon_IT::
    .string "E a quale POKéMON vuoi che\n"
    .string "insegni questa mossa?$"

Text_SwordsDanceTaught_IT::
    .string "Sarebbe bello poter diventare\n"
    .string "sempre più forti, all'infinito!$"

SevenIsland_Text_IslandSign_IT::
    .string "SETTIMISOLA\n"
    .string "L'isola dell'avventura infinita$"

SevenIsland_Text_IslandsMadeInSevenDays_IT::
    .string "Questo arcipelago si chiama\n"
    .string "SETTIPELAGO perché è formato\l"
    .string "da sette isole.\p"
    .string "…Beh, questo è ciò che fanno\n"
    .string "credere a voi giovani.\p"
    .string "Il vero motivo è che queste isole\n"
    .string "sono nate in sette giorni.$"

SevenIsland_Text_IslandVirtuallyUntouched_IT::
    .string "Su quest'isola, la natura è rimasta\n"
    .string "assolutamente intatta.\p"
    .string "Per questo motivo non è così\n"
    .string "facile da esplorare.$"

