Text_SwordsDanceTeach_ES::
    .string "Son pocos los que vienen\n"
    .string "a esta zona.\p"
    .string "Si me pusiera a entrenar aquí,\n"
    .string "seguro que me haría superfuerte.\p"
    .string "Sí, requetefuerte-fortísimo.\p"
    .string "¿Quieres aprender el movimiento\n"
    .string "DANZA ESPADA?$"

Text_SwordsDanceDeclined_ES::
    .string "Bueno, como quieras.$"

Text_SwordsDanceWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "se lo enseñe?$"

Text_SwordsDanceTaught_ES::
    .string "Lo suyo sería que cada vez nos\n"
    .string "hiciéramos más y más fuertes, ¿eh?$"

SevenIsland_Text_IslandSign_ES::
    .string "ISLA SÉTIMA\n"
    .string "Isla de aventura infinita.$"

SevenIsland_Text_IslandsMadeInSevenDays_ES::
    .string "A estas islas las llamamos ARCHI7\n"
    .string "porque son siete, je.\p"
    .string "O, por lo menos, es lo que la\n"
    .string "gente joven cree.\p"
    .string "Pero en realidad es porque las\n"
    .string "islas se crearon en siete días.$"

SevenIsland_Text_IslandVirtuallyUntouched_ES::
    .string "Esta isla es prácticamente virgen,\n"
    .string "apenas ha sufrido modificaciones.\p"
    .string "Por ello, es peligroso y difícil\n"
    .string "hacer escalada por aquí.$"
