OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio_IT::
    .string "BILL: Ehi, CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut_IT::
    .string "CELIO: BILL!\n"
    .string "Non posso credere che tu sia\l"
    .string "venuto fin qui!$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing_IT::
    .string "BILL: Alla fine ce l'ho fatta, hai\n"
    .string "visto? Come vanno le ricerche?\p"
    .string "…Ah, aspetta un attimo!$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio_IT::
    .string "{PLAYER}, ti presento il mio amico\n"
    .string "CELIO. È un grande ESPERTO di PC!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp_IT::
    .string "CELIO, ti presento {PLAYER}!\n"
    .string "Diventerà presto CAMPIONE\l"
    .string "di POKéMON!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp_IT::
    .string "CELIO, ti presento {PLAYER}!\n"
    .string "È CAMPIONE di POKéMON in\l"
    .string "carica!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive_IT::
    .string "CELIO: Ah, davvero? Complimenti!\p"
    .string "Me ne vergogno un po', ma sono\n"
    .string "proprio una frana a lottare!\p"
    .string "Felice di conoscerti!$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed_IT::
    .string "BILL: Allora, CELIO, aggiornami:\n"
    .string "come va con il tuo macchinario?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours_IT::
    .string "CELIO: Per funzionare funziona,\n"
    .string "ma siamo troppo isolati.\p"
    .string "Il PC dell'isola è troppo distante\n"
    .string "dal tuo, BILL, per poter stabilire\l"
    .string "un collegamento.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou_IT::
    .string "BILL: Ah, davvero?\n"
    .string "Fammi dare un'occhiata.\p"
    .string "Dammi un po' di tempo…\n"
    .string "Mi è venuta un'idea…\l"
    .string "Forse posso aiutarti…$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer_IT::
    .string "{PLAYER}, puoi aspettare un attimo?\p"
    .string "…Anzi, nel frattempo posso\n"
    .string "chiederti un favore?\p"
    .string "L'isola vicino a questa è chiamata\n"
    .string "SECONDISOLA.\p"
    .string "Là troverai un ragazzo che dirige\n"
    .string "l'ARENA GIOCHI.\p"
    .string "È un grande appassionato di gemme\n"
    .string "e antiche rocce.\p"
    .string "Dato che lo sono anch'io, ci\n"
    .string "teniamo in contatto, scambiandoci\l"
    .string "informazioni.\p"
    .string "Posso chiederti di consegnargli\n"
    .string "questo METEORITE?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill_IT::
    .string "{PLAYER} accetta il METEORITE\n"
    .string "da BILL.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis_IT::
    .string "CELIO: {PLAYER}, se vai a\n"
    .string "SECONDISOLA, prendi questo.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands_IT::
    .string "È un PASS che permette di\n"
    .string "accedere al servizio navale per\l"
    .string "tre isole del SETTIPELAGO.\p"
    .string "Con questo PASS, puoi viaggiare\n"
    .string "tra PRIMISOLA, SECONDISOLA e\l"
    .string "TERZISOLA.\p"
    .string "Aspetta, prendi anche questo!$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap_IT::
    .string "{PLAYER} riceve un'altra pagina\n"
    .string "della MAPPA CITTÀ.$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap_IT::
    .string "{PLAYER} riceve la\n"
    .string "MAPPA CITTÀ.$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater_IT::
    .string "BILL: Beh, ci vediamo dopo.\n"
    .string "Salutami il mio amico!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis_IT::
    .string "Vediamo…\p"
    .string "Se mettiamo questo in questa\n"
    .string "posizione…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore_IT::
    .string "Ehi, {PLAYER}!\p"
    .string "Hai visto? Stiamo riuscendo\n"
    .string "a far funzionare il PC!\p"
    .string "Ascolta, ho ancora qualcosa da\n"
    .string "mostrare a CELIO.\p"
    .string "Potresti andare a fare una\n"
    .string "passeggiata e tornare fra un po'?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost_IT::
    .string "Mi dispiace di far perdere tanto\n"
    .string "tempo a BILL.\p"
    .string "Mi piacerebbe anche avere un po'\n"
    .string "di tempo per mostrarti l'isola,\l"
    .string "ma come faccio?!$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable_IT::
    .string "I normali servizi del PC non sono\n"
    .string "accessibili.$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer_IT::
    .string "BILL: Ehi, {PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone_IT::
    .string "BILL: Ce ne hai messo di tempo!\n"
    .string "Hai fatto un bel giro?\p"
    .string "Ce l'abbiamo fatta. Il PC funziona\n"
    .string "perfettamente!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick_IT::
    .string "CELIO: Ci abbiamo messo\n"
    .string "pochissimo!\p"
    .string "BILL è davvero un genio!$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot_IT::
    .string "BILL: Beh, in realtà ho dovuto\n"
    .string "fare pochissimo, il PC era già\l"
    .string "quasi perfetto.\p"
    .string "CELIO, devo riconoscere che hai\n"
    .string "fatto grandi progressi.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe_IT::
    .string "CELIO: Dici davvero?\n"
    .string "Grazie!$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto_IT::
    .string "BILL: Beh, qui abbiamo finito.\n"
    .string "Si torna a KANTO.\p"
    .string "CELIO, ci vediamo presto!$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime_IT::
    .string "CELIO: {PLAYER}, mi dispiace di non\n"
    .string "averti potuto mostrare l'isola.\p"
    .string "Ma ti prometto che un giorno ti\n"
    .string "farò fare una bella visita guidata!$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine_IT::
    .string "CELIO: Ciao!\n"
    .string "Come va? Sempre in giro, eh?\p"
    .string "Io sto benone, grazie. Sto\n"
    .string "modificando la Centralina\l"
    .string "Network.\p"
    .string "Appena ho finito, spero che tu\n"
    .string "sia la prima persona ad usare\l"
    .string "la Centralina Network modificata!$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful_IT::
    .string "CELIO: {PLAYER}, va tutto bene?\p"
    .string "Hai catturato altri POKéMON?\p"
    .string "Ah, devo dirti una cosa che\n"
    .string "potrebbe esserti utile.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway_IT::
    .string "Sto facendo una modifica alla\n"
    .string "Centralina Network.\p"
    .string "Quando avrò finito, sarà possibile\n"
    .string "scambiare POKéMON con\l"
    .string "ALLENATORI distantissimi.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone_IT::
    .string "C'è un problema, però.\p"
    .string "Per funzionare, la Centralina\n"
    .string "ha bisogno di una gemma\l"
    .string "speciale.\p"
    .string "Pare che si trovi a PRIMISOLA,\n"
    .string "ma non l'ho ancora trovata.\p"
    .string "Chissà dov'è!$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem_IT::
    .string "Per la ricerca della gemma ho\n"
    .string "persino trascurato i miei studi!\p"
    .string "Sono certo che con l'aiuto di\n"
    .string "BILL, le mie ricerche\l"
    .string "procederebbero meglio.\p"
    .string "Questa volta, però, voglio farcela\n"
    .string "con le mie sole forze.$"

OneIsland_PokemonCenter_1F_Text_OhThats_IT::
    .string "Ah!\n"
    .string "Ma quello è…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio_IT::
    .string "{PLAYER} dà il RUBINO\n"
    .string "a CELIO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor_IT::
    .string "Grazie, {PLAYER}!\n"
    .string "Sei semplicemente incredibile!\p"
    .string "Posso chiederti un altro piacere?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp_IT::
    .string "Ti prego! Ho bisogno del\n"
    .string "tuo aiuto!$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands_IT::
    .string "Studiando le gemme ho fatto una\n"
    .string "scoperta importantissima.\p"
    .string "Esiste un'altra gemma, che va\n"
    .string "riunita a questo RUBINO.\p"
    .string "L'altra gemma si deve trovare da\n"
    .string "qualche parte nel SETTIPELAGO.\p"
    .string "{PLAYER}, vai a cercarla, ti prego!\p"
    .string "Prima, però, posso vedere il tuo\n"
    .string "PASS e la tua MAPPA CITTÀ?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass_IT::
    .string "{PLAYER} restituisce il TRIS PASS e\n"
    .string "riceve il SETTE PASS.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage_IT::
    .string "Ricevuta un'altra pagina della\n"
    .string "MAPPA CITTÀ.$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands_IT::
    .string "Questo è il mio PASS personale\n"
    .string "per il POKéSCAFO.\p"
    .string "Con questo potrai spostarti\n"
    .string "liberamente in tutto il\l"
    .string "SETTIPELAGO.\p"
    .string "{PLAYER}, ti prego! Non posso\n"
    .string "farcela senza il tuo aiuto!$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio_IT::
    .string "{PLAYER} dà lo ZAFFIRO\n"
    .string "a CELIO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime_IT::
    .string "CELIO: Bene! Ora le due gemme\n"
    .string "RUBINO e ZAFFIRO sono state\l"
    .string "riunite!\p"
    .string "{PLAYER}, è stata dura, vero?\p"
    .string "Non hai bisogno di dirmelo, lo so\n"
    .string "benissimo!\p"
    .string "Ora sarò io a lavorare per te.\n"
    .string "Dammi solo un po' di tempo!$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood_IT::
    .string "Ecco, vediamo…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette_IT::
    .string "Ce l'ho fatta! Mi sono collegato\n"
    .string "con LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou_IT::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, ce l'ho fatta!\p"
    .string "Sono riuscito a stabilire un\n"
    .string "collegamento con gli ALLENATORI\l"
    .string "di HOENN!\p"
    .string "Finalmente, la Centralina Network\n"
    .string "funziona al massimo delle\l"
    .string "potenzialità!\p"
    .string "{PLAYER}, grazie! Devo a te tutto\n"
    .string "questo!$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck_IT::
    .string "No, non sto piangendo…\n"
    .string "È solo… una lacrima…\p"
    .string "Non puoi immaginare quanto sia\n"
    .string "felice di ciò che siamo riusciti\l"
    .string "a realizzare!\p"
    .string "{PLAYER}, continua a catturare\n"
    .string "POKéMON di terre lontane,\l"
    .string "mi raccomando!\p"
    .string "In bocca al lupo!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou_IT::
    .string "CELIO: Ciao!\p"
    .string "In giro si parla molto di te!$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra_IT::
    .string "{PLAYER}, qual è il tuo POKéMON\n"
    .string "preferito?\p"
    .string "BILL, da buon POKéFANATICO,\n"
    .string "va pazzo per tutti i POKéMON.\p"
    .string "Ma sai qual è il primo che ha\n"
    .string "catturato? Un ABRA!$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod_IT::
    .string "A proposito, {PLAYER}!\n"
    .string "Sei di BIANCAVILLA, vero?\l"
    .string "Dev'essere un bel posto.\p"
    .string "BILL viene da FIORDOROPOLI.\p"
    .string "Ho sentito dire che è una città\n"
    .string "molto allegra, vitale.\p"
    .string "Mi piacerebbe andarci un giorno.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk_IT::
    .string "{PLAYER}, c'è un cibo che proprio\n"
    .string "non puoi sopportare?\p"
    .string "BILL non beve latte. Non gli\n"
    .string "piace proprio.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt_IT::
    .string "Tu non sei di qui, vero?\n"
    .string "Da dove vieni?\p"
    .string "Da BIANCAVILLA? Mai\n"
    .string "sentita nominare…$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland_IT::
    .string "Su quest'isola c'è un enorme\n"
    .string "vulcano.\p"
    .string "Non è più attivo da tempo. Quindi,\n"
    .string "se vuoi, puoi tranquillamente\l"
    .string "andare a farci un giro.$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend_IT::
    .string "Vorrei poter scambiare POKéMON con\n"
    .string "il mio ragazzo, che abita lontano!$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend_IT::
    .string "Ora posso scambiare POKéMON con il\n"
    .string "mio ragazzo che abita lontano!\p"
    .string "Ho sentito che è merito tuo e di\n"
    .string "CELIO!\p"
    .string "Beh, grazie mille!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment_IT::
    .string "Centralina Network\n"
    .string "Livello collegamento 0\p"
    .string "Sistema Memoria POKéMON in\n"
    .string "riparazione.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto_IT::
    .string "Centralina Network\n"
    .string "Livello collegamento 1\p"
    .string "È attivo il collegamento con la\n"
    .string "regione di KANTO.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn_IT::
    .string "Centralina Network\n"
    .string "Livello collegamento 2\p"
    .string "Sono attivi i collegamenti con le\n"
    .string "regioni di KANTO e HOENN.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass_IT::
    .string "Ottenuto TRIS PASS!$"

