SilphCo_4F_Text_CantYouSeeImHiding_IT::
    .string "Ssh!\n"
    .string "Non vedi che mi sto nascondendo?$"

SilphCo_4F_Text_TeamRocketIsGone_IT::
    .string "Cosa?\n"
    .string "TEAM ROCKET se n'è andato?$"

SilphCo_4F_Text_Grunt1Intro_IT::
    .string "TEAM ROCKET si è impadronito della\n"
    .string "SILPH SpA!!!$"

SilphCo_4F_Text_Grunt1Defeat_IT::
    .string "Grrr!$"

SilphCo_4F_Text_Grunt1PostBattle_IT::
    .string "Ihahah!!! Il mio CAPO aspettava\n"
    .string "questo momento!$"

SilphCo_4F_Text_RodneyIntro_IT::
    .string "I miei POKéMON sono i miei fedeli\n"
    .string "guerrieri!$"

SilphCo_4F_Text_RodneyDefeat_IT::
    .string "Accidenti!\n"
    .string "Metti i POKéMON KO!$"

SilphCo_4F_Text_RodneyPostBattle_IT::
    .string "Le porte si chiudono\n"
    .string "elettronicamente!\p"
    .string "Si aprono solo con l'APRIPORTA!$"

SilphCo_4F_Text_Grunt2Intro_IT::
    .string "Si segnala un'intrusione!$"

SilphCo_4F_Text_Grunt2Defeat_IT::
    .string "Chi sei?$"

SilphCo_4F_Text_Grunt2PostBattle_IT::
    .string "Lo dirò al CAPO al 10º piano!$"

SilphCo_4F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "3ºP$"

