SilphCo_4F_Text_CantYouSeeImHiding_DE::
	.string "Pst! Siehst du nicht, dass\n"
	.string "ich mich verstecke?$"

SilphCo_4F_Text_TeamRocketIsGone_DE::
	.string "Das TEAM ROCKET ist verschwunden?$"

SilphCo_4F_Text_Grunt1Intro_DE::
	.string "Das TEAM ROCKET hat die Kontrolle\n"
	.string "über SILPH CO. übernommen!!!$"

SilphCo_4F_Text_Grunt1Defeat_DE::
	.string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle_DE::
	.string "Auf diesen Moment hat der Boss\n"
	.string "sehr lange gewartet!$"

SilphCo_4F_Text_RodneyIntro_DE::
	.string "Mein POKéMON erwartet dich!!!$"

SilphCo_4F_Text_RodneyDefeat_DE::
	.string "Du schwächliches POKéMON! Mist!$"

SilphCo_4F_Text_RodneyPostBattle_DE::
	.string "Die Türen sind elektronisch\n"
	.string "verriegelt! Ohne TÜRÖFFNER kommt\l"
	.string "man nicht durch!$"

SilphCo_4F_Text_Grunt2Intro_DE::
	.string "Eindringling gesichtet!$"

SilphCo_4F_Text_Grunt2Defeat_DE::
	.string "Wer oder was bist du?$"

SilphCo_4F_Text_Grunt2PostBattle_DE::
	.string "Ich muss den BOSS im 10.\n"
	.string "Stock warnen!$"

SilphCo_4F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "3 OG$"

