SilphCo_4F_Text_CantYouSeeImHiding_ES::
    .string "¡Sssh! ¿Acaso no ves que me estoy\n"
    .string "escondiendo?$"

SilphCo_4F_Text_TeamRocketIsGone_ES::
    .string "¿Eh?\n"
    .string "¿Que el TEAM ROCKET se ha ido?$"

SilphCo_4F_Text_Grunt1Intro_ES::
    .string "¡El TEAM ROCKET se ha apoderado\n"
    .string "de SILPH S.A.!$"

SilphCo_4F_Text_Grunt1Defeat_ES::
    .string "¡Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle_ES::
    .string "¡Ja, ja, ja!\n"
    .string "¡Mi JEFE buscaba este lugar!$"

SilphCo_4F_Text_RodneyIntro_ES::
    .string "¡Mi POKéMON es mi fiel defensor!$"

SilphCo_4F_Text_RodneyDefeat_ES::
    .string "¡Has debilitado a mi POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle_ES::
    .string "¡Las puertas están cerradas\n"
    .string "electrónicamente!\p"
    .string "¡Las abre una LLAVE MAGNÉTICA!$"

SilphCo_4F_Text_Grunt2Intro_ES::
    .string "¡Nos invaden!$"

SilphCo_4F_Text_Grunt2Defeat_ES::
    .string "¿Quién eres tú?$"

SilphCo_4F_Text_Grunt2PostBattle_ES::
    .string "¡Será mejor que se lo diga\n"
    .string "al JEFE del décimo piso!$"

SilphCo_4F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P3$"
