PokemonMansion_1F_Text_TedIntro_ES::
    .string "¿Y tú quién eres?\n"
    .string "Aquí no debería haber nadie.$"

PokemonMansion_1F_Text_TedDefeat_ES::
    .string "¡Auh!$"

PokemonMansion_1F_Text_TedPostBattle_ES::
    .string "¿Una llave? ¡Ni idea de lo que me\n"
    .string "estás hablando!$"

PokemonMansion_1F_Text_JohnsonIntro_ES::
    .string "¡Aaaaaaaaaah! ¡Qué susto!\n"
    .string "¡Pensaba que eras un fantasma!$"

PokemonMansion_1F_Text_JohnsonDefeat_ES::
    .string "¡Uf, no hay forma de que gane!$"

PokemonMansion_1F_Text_JohnsonPostBattle_ES::
    .string "Yo estaba aquí tranquilamente\n"
    .string "curioseando un poco, pero creo\l"
    .string "que voy a irme.\p"
    .string "Tengo un poco de miedo.$"
