PokemonMansion_1F_Text_TedIntro_DE::
	.string "Wer bist du?\n"
	.string "Hier hat niemand etwas zu suchen!$"

PokemonMansion_1F_Text_TedDefeat_DE::
	.string "Autsch!$"

PokemonMansion_1F_Text_TedPostBattle_DE::
	.string "Ein Schlüssel?\n"
	.string "Keine Ahnung, wovon du redest!$"

PokemonMansion_1F_Text_JohnsonIntro_DE::
	.string "Oh! Du hast mich überrascht!\n"
	.string "Ich dachte, du wärst ein Geist.$"

PokemonMansion_1F_Text_JohnsonDefeat_DE::
	.string "Ts!\n"
	.string "Ich kann nicht gewinnen!$"

PokemonMansion_1F_Text_JohnsonPostBattle_DE::
	.string "Ich habe das Gebiet hier auf\n"
	.string "eigene Faust erforscht, aber es\l"
	.string "ist so gruselig.\p"
	.string "Ich muss bald weg!$"

