PokemonMansion_1F_Text_TedIntro_IT::
    .string "Chi sei?\n"
    .string "Nessuno può stare qui!$"

PokemonMansion_1F_Text_TedDefeat_IT::
    .string "Ahi!$"

PokemonMansion_1F_Text_TedPostBattle_IT::
    .string "Una chiave?\n"
    .string "Non so di cosa stai parlando!$"

PokemonMansion_1F_Text_JohnsonIntro_IT::
    .string "Mi hai messo paura!\n"
    .string "Credevo che fossi un fantasma!$"

PokemonMansion_1F_Text_JohnsonDefeat_IT::
    .string "Non riesco proprio a vincere!$"

PokemonMansion_1F_Text_JohnsonPostBattle_IT::
    .string "Sono venuto a farmi un giro, ma\n"
    .string "mi è presa una paura…\p"
    .string "Forse è meglio che me ne vada…$"

