PokemonMansion_1F_Text_TedIntro_FR::
	.string "Qui es-tu?\n"
	.string "C'est interdit de se balader ici.$"

PokemonMansion_1F_Text_TedDefeat_FR::
	.string "Aïe!$"

PokemonMansion_1F_Text_TedPostBattle_FR::
	.string "Une clé? Je ne sais pas d'quoi tu\n"
	.string "parles.$"

PokemonMansion_1F_Text_JohnsonIntro_FR::
	.string "Waaah! J'ai eu peur!!\n"
	.string "J'ai cru que c'était un fantôme!$"

PokemonMansion_1F_Text_JohnsonDefeat_FR::
	.string "Pffff!\n"
	.string "J'arrive jamais à gagner!$"

PokemonMansion_1F_Text_JohnsonPostBattle_FR::
	.string "Je suis venu en exploration.\n"
	.string "Mais je me sens épié.\p"
	.string "Faut que je parte vite d'ici.$"

