Aide_Text_HaventCaughtEnoughMonsForItem_ES::
	.string "Veamos...\n"
	.string "¡Oh! ¡Atrapaste solamente {STR_VAR_3} tipos\l"
	.string "de POKéMON!\p"
	.string "Necesitas {STR_VAR_1} tipos si quieres\n"
	.string "{STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem_ES::
	.string "¡Ah! Ya veo.\p"
	.string "Cuando tengas {STR_VAR_1} tipos, vuelve\n"
	.string "a por {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem_ES::
	.string "¡Oh! Ya veo que no tienes sitio\n"
	.string "para {STR_VAR_2}.$"
