Braille_Text_Up_ES::
	.braille "ARRIBA$"

Braille_Text_Down_ES::
	.braille "ABAJO$"

Braille_Text_Right_ES::
	.braille "DERECHA$"

Braille_Text_Left_ES::
	.braille "IZQUIERDA$"

Braille_Text_Cut_ES::
	.braille "CORTE$"

Braille_Text_ABC_ES::
	.braille "ABC$"

Braille_Text_GHI_ES::
	.braille "GHI$"

Braille_Text_MNO_ES::
	.braille "MNO$"

Braille_Text_TUV_ES::
	.braille "TUV$"

Braille_Text_DEF_ES::
	.braille "DEF$"

Braille_Text_JKL_ES::
	.braille "JKL$"

Braille_Text_PQRS_ES::
	.braille "PQRS$"

Braille_Text_WXYZ_ES::
	.braille "WXYZ$"

Braille_Text_Period_ES::
	.braille "=*$"

Braille_Text_Comma_ES::
	.braille "=,$"

Braille_Text_Everything_ES::
	.braille "TODO$"

Braille_Text_HasMeaning1_ES::
	.braille "IMPORTA$"

Braille_Text_Existence_ES::
	.braille "EXISTENCIA$"

Braille_Text_HasMeaning2_ES::
	.braille "IMPORTA$"

Braille_Text_BeingAlive_ES::
	.braille "ESTAR VIVO$"

Braille_Text_HasMeaning3_ES::
	.braille "IMPORTA$"

Braille_Text_HaveDreams_ES::
	.braille "DESEAR$"

Braille_Text_UsePower_ES::
	.braille "USA FUERZA$"

Braille_Text_LetTheTwo_ES::
	.braille "DEJA A DOS$"

Braille_Text_Glittering_ES::
	.braille "BRILLANTES$"

Braille_Text_Stones_ES::
	.braille "PIEDRAS$"

Braille_Text_OneInRed_ES::
	.braille "UNA ROJA$"

Braille_Text_OneInBlue_ES::
	.braille "UNA AZUL$"

Braille_Text_ConnectThe_ES::
	.braille "CONECTAR$"

Braille_Text_Past_ES::
	.braille "CON PASADO$"

Braille_Text_TwoFriends_ES::
	.braille "AMIGOS$"

Braille_Text_Sharing_ES::
	.braille "COMPARTIR$"

Braille_Text_PowerOpen_ES::
	.braille "FUERZA$"

Braille_Text_AWindowTo_ES::
	.braille "ABRE PUERTA$"

Braille_Text_ANewWorld_ES::
	.braille "A MUNDO$"

Braille_Text_ThatGlows_ES::
	.braille "POR EXPLORAR$"

Braille_Text_TheNext_ES::
	.braille "NUEVO MUNDO$"

Braille_Text_WorldWaits_ES::
	.braille "OS$"

Braille_Text_ForYou_ES::
	.braille "ESPERA$"
