@ Unused
Text_WelcomeTradeCenter_ES::
	.string "Hola. Éste es el CENTRO de CAMBIO\n"
	.string "del CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeColosseum_ES::
	.string "Hola. Éste es el COLISEO del\n"
	.string "CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule_ES::
	.string "Hola. Ésta es la CÁPSULA del\n"
	.string "TIEMPO del CLUB del CABLE\l"
	.string "POKéMON.$"

Text_PleaseComeAgain_ES::
	.string "¡Vuelve cuando quieras!$"

@ Unused
Text_HavingDiscountSaleToday_ES::
	.string "¡Hola!\p"
	.string "¡Hoy tenemos rebajas!$"

@ Unused
Text_PlayerWhatCanIDoForYou_ES::
	.string "¡Hola, {PLAYER}{KUN}!\p"
	.string "¿En qué puedo ayudarte?$"
