@ Unused
Text_WelcomeTradeCenter_ES::
	.string "Hola. Éste es el CENTRO de CAMBIO\n"
	.string "del CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeColosseum_ES::
	.string "Hola. Éste es el COLISEO del\n"
	.string "CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule_ES::
	.string "Hola. Ésta es la CÁPSULA del\n"
	.string "TIEMPO del CLUB del CABLE\l"
	.string "POKéMON.$"

Text_PleaseComeAgain_ES::
	.string "¡Vuelve cuando quieras!$"

@ Unused
Text_HavingDiscountSaleToday_ES::
	.string "¡Hola!\p"
	.string "¡Hoy tenemos rebajas!$"

@ Unused
Text_PlayerWhatCanIDoForYou_ES::
	.string "¡Hola, {PLAYER}{KUN}!\p"
	.string "¿En qué puedo ayudarte?$"

CableClub_Text_WelcomeWhichCableClubService_ES::
	.string "Éste es el CLUB del CABLE\n"
	.string "POKéMON.\p"
	.string "¿Qué podemos hacer por ti?$"

CableClub_Text_WhichService_ES::
	.string "¿Qué podemos hacer por ti?$"

CableClub_Text_TradeMonsUsingLinkCable_ES::
	.string "Intercambiar PKMN con otro jugador\n"
	.string "usando el cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable_ES::
	.string "Usando el cable Game Link de GBA,\n"
	.string "podrás luchar contra alguien.$"

@ Unused, translated in Emerald
CableClub_Text_CloseThisMenu_ES::
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle_ES::
	.string "Para un COMBATE DOBLE, necesitas\n"
	.string "tener al menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade_ES::
	.string "Para intercambiar POKéMON,\n"
	.string "necesitas tener al menos dos.$"

CableClub_Text_CantTradeEnigmaBerry_ES::
	.string "Los POKéMON que tengan BAYAS\n"
	.string "{STR_VAR_1} no se pueden intercambiar.$"

CableClub_Text_PleaseWaitBCancel_ES::
	.string "Espera unos instantes.\n"
	.string "Pulsa el Botón B para cancelar.$"

CableClub_Text_WhenAllPlayersReadyAConfirmBCancel_ES::
	.string "Cuando todos estén listos...\n"
	.string "Botón A: confirmar\l"
	.string "Botón B: cancelar$"

CableClub_Text_StartLinkWithXPlayersAConfirmBCancel_ES::
	.string "Comenzar la conexión con los\n"
	.string "siguientes jugadores: {STR_VAR_1}...\l"
	.string "Botón A: confirmar\l"
	.string "Botón B: cancelar$"

CableClub_Text_AwaitingLinkupBCancel_ES::
	.string "Esperando conexión...\n"
	.string "Botón B: cancelar$"

@ Unused, translated in Emerald
CableClub_Text_OkayToSaveProgress_ES::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter_ES::
	.string "Adelante.$"

CableClub_Text_DirectYouToYourRoom_ES::
	.string "Te voy a llevar a tu sala.$"

CableClub_Text_SomeoneIsNotReadyToLink_ES::
	.string "Uno de los jugadores no está listo\n"
	.string "para realizar la conexión.\p"
	.string "Vuelve cuando todos estéis listos.$"

CableClub_Text_LinkErrorPleaseReset_ES::
	.string "Error de conexión... Comprueba el\n"
	.string "cable Game Link, apaga la consola\l"
	.string "(OFF) y vuelve a encenderla (ON).$"

CableClub_Text_PlayersMadeDifferentSelections_ES::
	.string "Los demás jugadores parecen haber\n"
	.string "seleccionado opciones diferentes.$"

CableClub_Text_PleaseVisitAgain_ES::
	.string "Vuelve cuando quieras.$"

CableClub_Text_IncorrectNumberOfParticipants_ES::
	.string "El número de jugadores no es\n"
	.string "correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers_ES::
	.string "No se puede jugar al modo de\n"
	.string "combate INDIVIDUAL con {STR_VAR_1}\l"
	.string "jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers_ES::
	.string "No se puede jugar al modo de\n"
	.string "combate DOBLE con {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers_ES::
	.string "Se necesitan cuatro jugadores para\n"
	.string "jugar a este modo de combate.$"

CableClub_Text_PleaseConfirmNumberAndRestart_ES::
	.string "Confirma el número de jugadores\n"
	.string "y vuelve a empezar.$"

Text_TerminateLinkIfYouLeaveRoom_ES::
	.string "Si sales de la sala, se pondrá fin\n"
	.string "a la conexión. ¿Estás de acuerdo?$"

Text_TerminateLinkConfirmation_ES::
	.string "Finalizando conexión... \n"
	.string "Te acompañamos fuera de la sala.\l"
	.string "Espera un momento.$"

Text_TrainerTooBusyToNotice_ES::
	.string "Este ENTRENADOR no te hace\n"
	.string "ni caso...$"

Text_LookedAtPlayersTrainerCard_ES::
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!$"

Text_LookedAtPlayersTrainerCardColored_ES::
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!\p"
	.string "¡Es de color {STR_VAR_2}!$"

Text_TakeSeatStartBattle_ES::
	.string "Puedes comenzar el combate.$"

Text_TakeSeatStartTrade_ES::
	.string "Puedes comenzar el intercambio.$"

@ Unused, leftover from RS
RecordCorner_Text_ThanksForComing_ES::
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten_ES::
	.string "Se van a sobrescribir los datos\n"
	.string "de la FICHA de ENTRENADOR.$"

CableClub_Text_HopeToSeeYouAgain_ES::
	.string "¡Vuelve cuando quieras!$"

CableClub_Text_NotSetUpForFarAwayRegion_ES::
	.string "Lo siento mucho.\p"
	.string "Aún no podemos realizar\n"
	.string "intercambios con ENTRENADORES\l"
	.string "de otra región...$"

CableClub_Text_OtherTrainerNotReady_ES::
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken_ES::
	.string "Tienes al menos un POKéMON\n"
	.string "que no se puede enviar.$"

CableClub_Text_AdapterNotConnected_ES::
	.string "El Conector inalámbrico de GBA\n"
	.string "no está bien conectado.$"

CableClub_Text_ParticipantsStepUpToCounter_ES::
	.string "Los principiantes deben pasar\n"
	.string "por el mostrador de recepción.$"

@ Unused, translated in Emerald
CableClub_Text_Hello_ES::
	.string "こんにちは！$"

@ Unused, translated in Emerald
CableClub_Text_PleaseWait_ES::
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere_ES::
	.string "Aquí puedes intercambiar POKéMON\n"
	.string "con un amigo.$"

CableClub_Text_YouMayBattleHere_ES::
	.string "Aquí puedes luchar contra tus\n"
	.string "amigos.$"

CableClub_Text_CanMakeBerryPowder_ES::
	.string "Para hacer POLVO de BAYA, hacen\n"
	.string "falta de dos a cinco ENTRENADORES.$"

@ Unused, Record Mix nopped
CableClub_Text_CanMixRecords_ES::
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem_ES::
	.string "Cancelar la selección.$"

@ Unused, translated in Emerald
CableClub_Text_WhichBattleMode_ES::
	.string "どちらの　しょうぶに　しますか？$"

@ Unused, translated in Emerald
CableClub_Text_ReturnsToPreviousStep_ES::
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush_ES::
	.string "Para usar el MACHACABAYAS,\n"
	.string "necesitas al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom_ES::
	.string "Para entrar en la SALA UNIÓN,\n"
	.string "debes tener al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom_ES::
	.string "Los POKéMON que tienen BAYAS\n"
	.string "{STR_VAR_1} no pueden entrar en la\l"
	.string "SALA UNIÓN.$"

CableClub_Text_UnionRoomAdapterNotConnected_ES::
	.string "Ésta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Vaya, tu Conector inalámbrico\n"
	.string "de GBA no está bien conectado...\p"
	.string "Vuelve más tarde.$"

@ Unused, translated in Emerald
CableClub_Text_OhExcuseMe_ES::
	.string "あ‥‥\n"
	.string "おきゃくさま！$"

Text_PlayerIsPlayingRightNowGoForIt_ES::
	.string "¡Parece que {STR_VAR_1} está jugando\n"
	.string "ahora mismo! ¡Conéctate!$"

Text_DescribeWhichGame_ES::
	.string "Si quieres te explico las reglas.\p"
	.string "¿De qué juego te hablo?$"

Text_PokemonJumpInfo_ES::
	.string "“SALTO POKéMON”\p"
	.string "Consigue que a tus POKéMON no les\n"
	.string "atrape la LIANA usando el Botón A.\p"
	.string "Sólo pueden participar los POKéMON\n"
	.string "que midan unos 70 cm o menos.\p"
	.string "A los POKéMON que naden despacio,\n"
	.string "caven o vuelen no se les dará muy\l"
	.string "bien lo de saltar.\p"
	.string "Por ello, estos POKéMON no deben\n"
	.string "participar.\p"
	.string "Si todos saltan a la vez,\n"
	.string "pueden ocurrir cosas estupendas.$"

Text_DodrioBerryPickingInfo_ES::
	.string "“DODRIO A POR BAYAS”\p"
	.string "Dile a DODRIO que pille las BAYAS\n"
	.string "que pueda con los tres picos que\l"
	.string "tiene.\p"
	.string "Pulsa derecha, izquierda o arriba\n"
	.string "en el {PLUS} Panel de Control para\l"
	.string "que se mueva.\p"
	.string "Para poder jugar a este juego,\n"
	.string "hay que tener un DODRIO.$"

Text_TalkToManToPlay_ES::
	.string "Si quieres jugar a un juego,\n"
	.string "díselo a mi compañero.$"

Text_WelcomeCanYouWait_ES::
	.string "¡Hola! ¡Gracias al sistema de\n"
	.string "comunicación inalámbrica,\l"
	.string "podrás jugar a juegos!\p"
	.string "¿Puedes esperar un segundo?$"

CableClub_Text_ComeAgain_ES::
	.string "¡Bueno, hasta otra!$"

Text_AdapterNotConnectedMinigame_ES::
	.string "El Conector inalámbrico de GBA\n"
	.string "no está conectado.\p"
	.string "¡Vuelve cuando lo tengas!$"

Text_PlayWhichGame_ES::
	.string "¿A qué juego quieres jugar?$"

Text_EnterWhichPokemon_ES::
	.string "¿Con qué POKéMON quieres\n"
	.string "participar?$"

Text_AllGoodToGo_ES::
	.string "¡Muy bien! ¡Pues adelante!\n"
	.string "¡A por todas!$"

@ Unused, translated in Emerald
Text_LeavingDoComeAgain_ES::
	.string "きょうは　けえるのか？\n"
	.string "またこいよ！$"

EventScript_ExplainPokemonJumpRequirements_ES::
	.string "Creo que no tienes POKéMON\n"
	.string "aptos para participar...\p"
	.string "¿Quieres que te diga cuáles son\n"
	.string "los que pueden participar?$"

Text_ShortJumpingPokemonAllowed_ES::
	.string "En “SALTO POKéMON” pueden\n"
	.string "participar los POKéMON que midan\l"
	.string "unos 70 cm o menos.\p"
	.string "Tampoco pueden participar los\n"
	.string "POKéMON que no pueden saltar.\p"
	.string "Es decir, los POKéMON que sólo\n"
	.string "nadan, cavan o vuelan.\p"
	.string "Bueno, pues ya lo sabes.$"

Text_OnlyDodrioAllowed_ES::
	.string "“DODRIO A POR BAYAS”...\n"
	.string "Yo creo que el nombre lo explica\l"
	.string "todo, ¿no?\p"
	.string "Para jugar a este juego debes\n"
	.string "tener al menos un DODRIO.$"

@ Unused, translated in Emerald
Text_RetryFromStartPlease_ES::
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれ$"

CableClub_Text_WelcomeWhichDirectCornerRoom_ES::
	.string "Ésta es la ZONA DIRECTA del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con tus amigos.\p"
	.string "¿En qué sala quieres entrar?$"

CableClub_Text_TradePokemon_ES::
	.string "¿Quieres cambiar POKéMON?$"

CableClub_Text_PlayWhichBattleMode_ES::
	.string "¿Qué modo de combate quieres?$"

CableClub_Text_UseBerryCrush_ES::
	.string "¿Quieres usar el MACHACABAYAS?$"

CableClub_Text_ExplainBattleModes_ES::
	.string "Hay tres modos de combate.\p"
	.string "El COMBATE INDIVIDUAL es para dos\n"
	.string "ENTRENADORES con uno o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR puede usar un\n"
	.string "POKéMON cada vez.\p"
	.string "El COMBATE DOBLE es para dos\n"
	.string "ENTRENADORES con dos o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR usará dos\n"
	.string "POKéMON cada vez.\p"
	.string "El COMBATE MULTIJUGADOR es para\n"
	.string "cuatro ENTRENADORES con uno o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR puede usar un\n"
	.string "POKéMON cada vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo_ES::
	.string "Un jugador debe ser LÍDER.\p"
	.string "Y el otro, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_ChooseGroupLeaderOfFour_ES::
	.string "Un jugador debe ser LÍDER\n"
	.string "del GRUPO.\p"
	.string "Y los otros, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_ChooseGroupLeader_ES::
	.string "Un jugador debe ser LÍDER\n"
	.string "del GRUPO.\p"
	.string "Y los otros, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_WelcomeUnionRoomEnter_ES::
	.string "Ésta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con ENTRENADORES\l"
	.string "a los que puede que no conozcas.\p"
	.string "¿Quieres entrar en la SALA?$"

CableClub_Text_UnionRoomInfo_ES::
	.string "Los ENTRENADORES de la SALA UNIÓN\n"
	.string "serán los jugadores que tengas\l"
	.string "cerca y hayan entrado en la SALA.\p"
	.string "¡Aquí se pueden hacer muchas\n"
	.string "cosas, empezando por saludarse\l"
	.string "y celebrar el encuentro!\p"
	.string "Puedes registrar dos POKéMON\n"
	.string "de nivel no superior a 30 para\l"
	.string "entablar combates de 1 contra 1.\p"
	.string "También puedes participar en chats;\n"
	.string "podéis ser de 2 a 5 jugadores.\p"
	.string "Y, por supuesto, puedes registrar\n"
	.string "POKéMON para realizar intercambios.\p"
	.string "¿Quieres entrar en la SALA?$"

CableClub_Text_EnjoyUnionRoom_ES::
	.string "Espero que disfrutes en la SALA\n"
	.string "UNIÓN.$"

CableClub_Text_FirstTimeRightThisWay_ES::
	.string "¡Hola!\n"
	.string "Me llamo TEALA.\p"
	.string "Es la primera vez que vienes, ¿no?\p"
	.string "Te voy a explicar cómo funciona\n"
	.string "el sistema de comunicación\l"
	.string "inalámbrica.\p"
	.string "Primero, te enseñaré esta planta\n"
	.string "de nuestro CENTRO POKéMON.\p"
	.string "Por aquí, por favor.$"

CableClub_Text_ExplainWirelessClubFirstTime_ES::
	.string "En el primer piso de los CENTROS\n"
	.string "POKéMON hay dos salas.\p"
	.string "Primero te hablaré de la sala de\n"
	.string "la izquierda: la SALA UNIÓN.\p"
	.string "En ella puedes conectarte con los\n"
	.string "ENTRENADORES que también\p"
	.string "hayan entrado en la SALA UNIÓN\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear, luchar\n"
	.string "y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la ZONA DIRECTA.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates POKéMON.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la ZONA\n"
	.string "DIRECTA.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_AskAboutLinking_ES::
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy yo, TEALA, la recepcionista\n"
	.string "del 1.{SUPER_ER} Piso del CENTRO POKéMON.\p"
	.string "¿Necesitas información sobre\n"
	.string "cómo realizar la conexión?$"

CableClub_Text_ExplainWirelessClub_ES::
	.string "Te voy a explicar cómo funciona\n"
	.string "el CLUB INALÁMBRICO POKéMON.\p"
	.string "Éste es el piso de arriba y tiene\n"
	.string "dos salas.\p"
	.string "Primero te hablaré de la sala de\n"
	.string "la izquierda: la SALA UNIÓN.\p"
	.string "En ella puedes conectarte con los\n"
	.string "ENTRENADORES que también\p"
	.string "hayan entrado en la SALA UNIÓN\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear, luchar\n"
	.string "y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la ZONA DIRECTA.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates POKéMON.\p"
	.string "Si no encontraras a tus amigos\n"
	.string "en la SALA UNIÓN ni en la ZONA\l"
	.string "DIRECTA, acercad las consolas.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la ZONA\n"
	.string "DIRECTA.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_HopeYouEnjoyWirelessSystem_ES::
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"
