@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife_ES::
	.string "Soy el ENCARGADO de la GUARDERÍA.\p"
	.string "Ayudo a los ENTRENADORES a cuidar\n"
	.string "de sus preciosos POKéMON.\p"
	.string "Si quieres que me encargue del\n"
	.string "tuyo, ve a hablar con mi mujer.$"

DayCare_Text_DoYouWantEgg_ES::
	.string "¡Ah, eres tú!\p"
	.string "¡Hemos cuidado de tu POKéMON\n"
	.string "y vaya sorpresa que nos hemos\l"
	.string "llevado!\p"
	.string "¡Tu POKéMON ha tenido un HUEVO!\p"
	.string "No sabemos cómo ha sucedido,\n"
	.string "pero es de tu POKéMON, seguro.\p"
	.string "¿Lo quieres?$"

DayCare_Text_YourMonIsDoingFine_ES::
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Tu {STR_VAR_1} está estupendamente.$"

DayCare_Text_IllKeepIt_ES::
	.string "Muy bien, entonces me seguiré\n"
	.string "ocupando de él. ¡Gracias!$"

DayCare_Text_YouHaveNoRoomForIt_ES::
	.string "No tienes sitio para él...\n"
	.string "Vuelve cuando lo tengas.$"

DayCare_Text_ReceivedEgg_ES::
	.string "¡El ENCARGADO de la GUARDERÍA\n"
	.string "le dio el HUEVO a {PLAYER}!$"

DayCare_Text_TakeGoodCareOfIt_ES::
	.string "Cuídalo bien.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon_ES::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine_ES::
	.string "¡Ah, eres tú! Tu {STR_VAR_1} y el\n"
	.string "{STR_VAR_2} están muy bien.$"

DayCare_Text_IWillKeepDoYouWantIt_ES::
	.string "Yo me lo quedaría, pero\n"
	.string "tú lo quieres, ¿verdad?$"

DayCare_Text_WouldYouLikeUsToRaiseMon_ES::
	.string "Soy la ENCARGADA de la GUARDERÍA.\p"
	.string "Podemos ocuparnos de tus POKéMON.\p"
	.string "¿Quieres que cuidemos de alguno?$"

DayCare_Text_WhichMonShouldWeRaise_ES::
	.string "¿Qué POKéMON quieres que\n"
	.string "cuidemos?$"

DayCare_Text_WellRaiseYourMon_ES::
	.string "Estupendo, nos ocuparemos de tu\n"
	.string "{STR_VAR_1} cuanto sea necesario.\p"
	.string "Vuelve cuando quieras.$"

DayCare_Text_WeCanRaiseOneMore_ES::
	.string "Podemos cuidar a dos de tus\n"
	.string "POKéMON.\p"
	.string "¿Quieres que cuidemos de otro más?$"

DayCare_Text_HusbandWasLookingForYou_ES::
	.string "Mi marido te estaba buscando.$"

DayCare_Text_FineThenComeAgain_ES::
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

DayCare_Text_NotEnoughMoney_ES::
	.string "No tienes bastante dinero.$"

DayCare_Text_TakeOtherOneBackToo_ES::
	.string "¿Quieres llevarte el otro también?$"

DayCare_Text_ComeAgain_ES::
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

DayCare_Text_GoodToSeeYou_ES::
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Todo ha ido de maravilla...$"

DayCare_Text_YourMonHasGrownXLevels_ES::
	.string "Tu {STR_VAR_1} ha crecido\n"
	.string "estos niveles: ¡{STR_VAR_2}!$"

DayCare_Text_YourPartyIsFull_ES::
	.string "Tu equipo POKéMON está lleno.\n"
	.string "Haz un hueco y vuelve a verme.$"

DayCare_Text_TakeBackWhichMon_ES::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX_ES::
	.string "Si quieres llevarte a tu\n"
	.string "{STR_VAR_1}, tendrás que pagar\l"
	.string "{STR_VAR_2}¥.$"

DayCare_Text_HeresYourMon_ES::
	.string "¡Perfecto!\n"
	.string "Aquí tienes a tu POKéMON.$"

DayCare_Text_TookBackMon_ES::
	.string "{PLAYER} recogió a {STR_VAR_1} de\n"
	.string "la GUARDERÍA POKéMON.$"

DayCare_Text_YouHaveJustOneMon_ES::
	.string "Anda, pero si sólo tienes un\n"
	.string "POKéMON...\p"
	.string "Vuelve cuando tengas alguno más.$"

DayCare_Text_TakeYourMonBack_ES::
	.string "¿Quieres recoger un POKéMON?$"

DayCare_Text_WhatWillYouBattleWith_ES::
	.string "Si me dejas ese POKéMON, no\n"
	.string "podrás entablar combates.\p"
	.string "Vuelve en otra ocasión.$"

DayCare_Text_Huh_ES::
	.string "¿Y esto?$"
