Text_CutTreeDown_ES::
	.string "Parece que puedes CORTAR\n"
	.string "este árbol.\p"
	.string "¿Usas CORTE?$"

Text_MonUsedMove_ES::
	.string "{STR_VAR_1} usó {STR_VAR_2}.$"

Text_TreeCanBeCutDown_ES::
	.string "Parece que puedes CORTAR\n"
	.string "este árbol.$"

Text_UseRockSmash_ES::
	.string "Parece que se puede romper esta\n"
	.string "roca. ¿Usas GOLPE ROCA?$"

Text_MonMaySmashRock_ES::
	.string "Es una roca muy dura, pero un\n"
	.string "POKéMON podría hacerla añicos.$"

Text_UseStrength_ES::
	.string "Es una roca enorme, pero un\n"
	.string "POKéMON podría moverla.\p"
	.string "¿Usas FUERZA?$"

Text_MonUsedStrengthCanMoveBoulders_ES::
	.string "{STR_VAR_1} usó FUERZA.\p"
	.string "La FUERZA de {STR_VAR_1} logró\n"
	.string "desplazar la roca a un lado.$"

Text_MonMayPushBoulder_ES::
	.string "Es una roca enorme, pero un\n"
	.string "POKéMON podría apartarla.$"

Text_StrengthMadeMovingBouldersPossible_ES::
	.string "Usar FUERZA ha permitido desplazar\n"
	.string "la roca a un lado.$"

Text_WallOfWaterCrashingDown_ES::
	.string "Un muro de agua cae con un\n"
	.string "estruendo estremecedor...$"

Text_UseWaterfall_ES::
	.string "Es una gran catarata.\n"
	.string "¿Usas CASCADA?$"

Text_MonUsedWaterfall_ES::
	.string "{STR_VAR_1} usó CASCADA.$"

Text_MonMayGoUnderwater_ES::
	.string "El mar es muy profundo en esta\n"
	.string "zona.\l"
	.string "Un POKéMON podría bucear aquí.$"

Text_SeaIsDeepUseDive_ES::
	.string "El mar es muy profundo en esta\n"
	.string "zona. ¿Usas BUCEO?$"

Text_MonUsedDive_ES::
	.string "{STR_VAR_1} usó BUCEO.$"

Text_MonMaySurface_ES::
	.string "La luz se filtra desde la\n"
	.string "superficie.\l"
	.string "Un POKéMON puede emerger aquí.$"

Text_LightFilteringUseDive_ES::
	.string "La luz se filtra desde la\n"
	.string "superficie. ¿Usas BUCEO?$"

Text_DiveCantBeUsedHere_ES::
	.string "Hay algún obstáculo en la\n"
	.string "superficie.\l"
	.string "No se puede usar BUCEO.$"

Text_LooksLikeNothingHere_ES::
	.string "Parece que aquí no hay nada...$"
