@ Flavor text for interacting with various background objects

Text_Bookshelf_ES::
	.string "¡Totalmente lleno de libros sobre\n"
	.string "los POKéMON!$"

Text_NothingButPokemonBooks_ES::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap_ES::
	.string "MAPA$"

Text_PokeMartShelf_ES::
	.string "¡Uauu!\n"
	.string "¡Cantidad de artículos de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp_ES::
	.string "Hay un montón de platos y bandejas\n"
	.string "muy bien colocados.$"

Text_Kitchen_ES::
	.string "¡Mmm, huele que alimenta!\n"
	.string "Aquí han debido de cocinar algo...$"

Text_Dresser_ES::
	.string "Qué mueble más estupendo...\n"
	.string "Aquí caben un montón de cosas.$"

Text_Snacks_ES::
	.string "Mmm, cuántas cosas ricas...$"

Text_PokemartSign_ES::
	.string "TIENDAS POKéMON\n"
	.string "¡Compra aquí todos tus objetos!$"

Text_PokecenterSign_ES::
	.string "CENTRO POKéMON\n"
	.string "¡Cura a tus POKéMON!$"

Text_Indigo_UltimateGoal_ES::
	.string "MESETA AÑIL\p"
	.string "¡El objetivo de todo ENTRENADOR:\n"
	.string "El CG de la LIGA POKéMON!$"

Text_Indigo_HighestAuthority_ES::
	.string "MESETA AÑIL\p"
	.string "La máxima autoridad POKéMON\n"
	.string "del CG de la LIGA POKéMON.$"

Text_Food_ES::
	.string "Seguramente está lleno de cosas\n"
	.string "de lo más apetecibles.$"

Text_Blueprints_ES::
	.string "Y este plano... ¿de dónde será?\p"
	.string "Tiene gráficos y anotaciones\n"
	.string "rarísimas.$"

Text_Painting_ES::
	.string "Qué foto más bonita.\n"
	.string "El POKéMON parece estar encantado.$"

Text_PowerPlantMachine_ES::
	.string "¿Para qué servirá?\n"
	.string "Prefiero no tocar, por si acaso...$"

Text_Telephone_ES::
	.string "Anda, un teléfono.\n"
	.string "Paso de usarlo.$"

Text_Computer_ES::
	.string "Qué combinación de números\n"
	.string "y letras más complicada...$"

Text_AdvertisingPoster_ES::
	.string "Es un póster promocional\n"
	.string "con todo tipo de productos.$"

Text_TastyFood_ES::
	.string "Mmm, ¡qué bien huele!\n"
	.string "¡Se me hace la boca agua!$"

Text_TrashBin_ES::
	.string "A ver...\n"
	.string "... ...\p"
	.string "¡Pero si no hay nada!$"

Text_Cup_ES::
	.string "¡Qué taza más guay!\n"
	.string "¡Tiene la huella de un POKéMON!$"

Text_PolishedWindow_ES::
	.string "La ventana está requetelimpia.$"

Text_BeautifulSkyWindow_ES::
	.string "Da gusto mirar por la ventana...\p"
	.string "El cielo está impresionante.$"

Text_BlinkingLights_ES::
	.string "Cuántas lucecitas de colores\n"
	.string "que se encienden y se apagan...$"

Text_NeatlyLinedUpTools_ES::
	.string "Hay un montón de relucientes\n"
	.string "herramientas muy bien ordenadas.$"

Text_ImpressiveMachine_ES::
	.string "No sé qué será esta máquina,\n"
	.string "pero es impresionante.$"

Text_VideoGame_ES::
	.string "¡Lo último en videojuegos!\n"
	.string "¡Qué guay!$"

Text_Burglary_ES::
	.string "Salta a la vista que han entrado\n"
	.string "a robar...$"

Text_PlayerFacingTVScreen_ES::
	.string "¡Está saliendo un POKéMON\n"
	.string "por la tele! Se le ve encantado...$"
