Help_Text_WhatShouldIDo_ES::
	.string "¿Qué debo hacer ahora?$"

Help_Text_HowDoIDoThis_ES::
	.string "¿Cómo lo hago?$"

Help_Text_WhatDoesThisTermMean_ES::
	.string "¿Qué significa esto?$"

Help_Text_AboutThisGame_ES::
	.string "¿Y este juego?$"

Help_Text_TypeMatchupList_ES::
	.string "Combinaciones de los tipos$"

Help_Text_Exit_ES::
	.string "SALIR$"

Help_Text_Cancel_ES::
	.string "ATRÁS$"

Help_Text_TryDoingItOnYourOwn_ES::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo_ES::
	.string "Información útil para salir\n"
	.string "de ciertas situaciones.$"

Help_Text_DescHowDoIDoThis_ES::
	.string "Instrucciones para realizar\n"
	.string "distintas cosas.$"

Help_Text_DescWhatDoesThisTermMean_ES::
	.string "Descripciones detalladas\n"
	.string "de términos del juego.$"

Help_Text_DescAboutThisGame_ES::
	.string "Descripciones detalladas\n"
	.string "del juego.$"

Help_Text_DescTypeMatchupList_ES::
	.string "Lista en la que se ve cómo se\n"
	.string "combinan los tipos y los ataques.$"

Help_Text_DescExit_ES::
	.string "Salir del sistema de AYUDA.$"

Help_Text_Greetings_ES::
	.string "¡Hola! Éste es el sistema de\n"
	.string "AYUDA. Cuando no sepas qué hacer,\l"
	.string "basta con pulsar el Botón L o R.\l"
	.string "Las cuestiones variarán según\l"
	.string "la situación, ¡así que conviene que\l"
	.string "lo consultes con frecuencia!$"

Help_Text_PlayingForFirstTime_ES::
	.string "¡Es la primera vez que juego!$"

Help_Text_WhatShouldIBeDoing_ES::
	.string "¿Qué tengo que hacer?$"

Help_Text_CantGetOutOfRoom_ES::
	.string "¿Por dónde salgo?$"

Help_Text_CantFindPersonIWant_ES::
	.string "¡No encuentro a quien busco!$"

Help_Text_TalkedToEveryoneNowWhat_ES::
	.string "¡Ya he hablado con todos!$"

Help_Text_SomeoneBlockingMyWay_ES::
	.string "¡No me dejan pasar!$"

Help_Text_ICantGoOn_ES::
	.string "¡No puedo avanzar!$"

Help_Text_OutOfThingsToDo_ES::
	.string "¡Ya no sé qué hacer!$"

Help_Text_WhatHappenedToItemIGot_ES::
	.string "¿Y el objeto que me han dado?$"

Help_Text_WhatAreMyAdventureBasics_ES::
	.string "¿Algún consejo importante?$"

Help_Text_HowAreRoadsForestsDifferent_ES::
	.string "Una ruta y un bosque, ¿son iguales?$"

Help_Text_HowAreCavesDifferent_ES::
	.string "¿Cómo son las cuevas?$"

Help_Text_HowDoIProgress_ES::
	.string "¿Cuál es mi objetivo?$"

Help_Text_WhenCanIUseItem_ES::
	.string "¿Cuándo puedo usar objetos?$"

Help_Text_WhatsABattle_ES::
	.string "¿Qué es un combate?$"

Help_Text_HowDoIPrepareForBattle_ES::
	.string "¿Cómo me preparo para luchar?$"

Help_Text_WhatIsAMonsVitality_ES::
	.string "¿Qué es la energía de un POKéMON?$"

Help_Text_MyMonsAreHurt_ES::
	.string "¡Mis POKéMON están heridos!$"

Help_Text_WhatIsStatusProblem_ES::
	.string "¿Qué son los problemas de estado?$"

Help_Text_WhatHappensIfAllMyMonsFaint_ES::
	.string "¿Qué pasa si se debilitan mis PKMN?$"

Help_Text_CantCatchMons_ES::
	.string "¡No puedo atrapar POKéMON!$"

Help_Text_RanOutOfPotions_ES::
	.string "¡Me he quedado sin POCIONES!$"

Help_Text_CanIBuyPokeBalls_ES::
	.string "¿Puedo comprar POKé BALLS?$"

Help_Text_WhatsATrainer_ES::
	.string "¿Qué es un ENTRENADOR?$"

Help_Text_HowDoIWinAgainstTrainer_ES::
	.string "¿Cómo se le gana a un ENTRENADOR?$"

Help_Text_WhereDoMonsAppear_ES::
	.string "¿Dónde hay POKéMON salvajes?$"

Help_Text_WhatAreMoves_ES::
	.string "¿Qué son los movimientos POKéMON?$"

Help_Text_WhatAreHiddenMoves_ES::
	.string "¿Qué son los movimientos OCULTOS?$"

Help_Text_WhatMovesShouldIUse_ES::
	.string "¿Qué movimientos debería usar?$"

Help_Text_WantToAddMoreMoves_ES::
	.string "¿Puedo añadir más movimientos?$"

Help_Text_WantToMakeMonStronger_ES::
	.string "¿Cómo fortalezco a mis POKéMON?$"

Help_Text_FoeMonsTooStrong_ES::
	.string "¡Mi rival es demasiado fuerte!$"

Help_Text_WhatDoIDoInCave_ES::
	.string "¿Qué hago con las cuevas?$"

Help_Text_NothingIWantToKnow_ES::
	.string "No tengo ninguna pregunta.$"

Help_Text_WhatsPokemonCenter_ES::
	.string "¿Qué es un CENTRO POKéMON?$"

Help_Text_WhatsPokemonMart_ES::
	.string "¿Qué es una TIENDA POKéMON?$"

Help_Text_WantToEndGame_ES::
	.string "Quiero acabar la partida.$"

Help_Text_WhatsAMon_ES::
	.string "¿Qué es un POKéMON?$"

Help_Text_WhatIsThatPersonLike_ES::
	.string "¿Qué sé de esta persona?$"

Help_Text_WhatDoesHiddenMoveDo_ES::
	.string "¿Qué hace un movimiento OCULTO?$"

Help_Text_WhatDoIDoInSafari_ES::
	.string "¿Qué se hace en el SAFARI?$"

Help_Text_WhatAreSafariRules_ES::
	.string "¿Cuáles son las reglas del SAFARI?$"

Help_Text_WantToEndSafari_ES::
	.string "Quiero salir del SAFARI.$"

Help_Text_WhatIsAGym_ES::
	.string "¿Qué es un GIMNASIO?$"

Help_Text_AnswerPlayingForFirstTime_ES::
	.string "Acabas de convertirte en\n"
	.string "protagonista de esta historia.\l"
	.string "Estás en el mundo POKéMON. Tienes\l"
	.string "que hablar con la gente y resolver\l"
	.string "los misterios que se te presenten.\l"
	.string "Ábrete camino para llegar al final\l"
	.string "junto a tus maravillosos POKéMON.$"

Help_Text_AnswerWhatShouldIBeDoing_ES::
	.string "Cuando te cruces con alguien,\n"
	.string "acércate y pulsa el Botón A para\l"
	.string "hablar. Haz lo mismo cuando veas\l"
	.string "algo interesante y llévatelo.\l"
	.string "Son las mejores formas de obtener\l"
	.string "información.$"

Help_Text_AnswerCantGetOutOfRoom_ES::
	.string "En las escaleras o a la salida de\n"
	.string "un edificio, encontrarás un felpudo\l"
	.string "rojo. Haz que tu personaje se\l"
	.string "ponga encima y pulsa la dirección\l"
	.string "que quieras en el {PLUS} Panel de\l"
	.string "Control para avanzar.$"

Help_Text_AnswerCantFindPersonIWant_ES::
	.string "No te preocupes, habla con otra\n"
	.string "gente, lee los carteles, curiosea\l"
	.string "cosas...\l"
	.string "En ocasiones, tendrás que ir a\l"
	.string "otros sitios.$"

Help_Text_AnswerTalkedToEveryoneNowWhat_ES::
	.string "Ve por otros caminos, pueblos\n"
	.string "o zonas.$"

Help_Text_AnswerSomeoneBlockingMyWay_ES::
	.string "Quizá la causa esté dentro del\n"
	.string "pueblo o en un edificio... Habla\l"
	.string "de nuevo con la gente. Igual\l"
	.string "alguien necesita que le ayudes\l"
	.string "con algo. Vuelve entonces a hablar\l"
	.string "con quien bloquea el camino.$"

Help_Text_AnswerICantGoOn_ES::
	.string "Cuando te cruces con alguien,\n"
	.string "acércate y pulsa el Botón A para\l"
	.string "hablar. Haz lo mismo cuando veas\l"
	.string "rocas y árboles raros y curiosea\l"
	.string "un poco. Usa el {PLUS} Panel de Control\l"
	.string "para acceder a sitios que parezcan\l"
	.string "inaccesibles.$"

Help_Text_AnswerOutOfThingsToDo_ES::
	.string "Ve a sitios en los que aún no\n"
	.string "has estado y curiosea todo lo que\l"
	.string "te parezca sospechoso pulsando\l"
	.string "el Botón A.$"

Help_Text_AnswerWhatHappenedToItemIGot_ES::
	.string "Los objetos que te den irán a tu\n"
	.string "MOCHILA directamente. Cada cosa\l"
	.string "se colocará de forma ordenada\l"
	.string "en el bolsillo que le corresponda.\l"
	.string "Para usar la MOCHILA, echa un ojo\l"
	.string "a la pregunta del sistema de AYUDA\l"
	.string "“¿Cómo lo hago?”.$"

Help_Text_AnswerWhatAreMyAdventureBasics_ES::
	.string "Si los POKéMON resultan heridos\n"
	.string "en combate, llévalos a un CENTRO\l"
	.string "POKéMON para que los curen. Es\l"
	.string "bueno que guardes la partida y que\l"
	.string "compres objetos curativos en las\l"
	.string "TIENDAS POKéMON cuando vayas\l"
	.string "a hacer largas distancias.$"

Help_Text_AnswerHowAreRoadsForestsDifferent_ES::
	.string "Básicamente no hay diferencia, pero\n"
	.string "los bosques son algo laberínticos.\l"
	.string "De todas formas, siempre tienen\l"
	.string "una salida, así que no desesperes\l"
	.string "si te pierdes.$"

Help_Text_AnswerHowAreCavesDifferent_ES::
	.string "Las cuevas son oscuras y\n"
	.string "peligrosas y están llenas de\l"
	.string "POKéMON salvajes. En caso de\l"
	.string "emergencia, corre a un CENTRO\l"
	.string "POKéMON o usa los objetos que\l"
	.string "tengas. Recupérate y llega hasta\l"
	.string "el otro lado; merece la pena.$"

Help_Text_AnswerHowDoIProgress_ES::
	.string "El objetivo del juego es entrenar\n"
	.string "a tus POKéMON y avanzar. Debes\l"
	.string "conseguir información y resolver\l"
	.string "situaciones. Tendrás que buscar la\l"
	.string "forma de esquivar un obstáculo o\l"
	.string "de conseguir que alguien se quite\l"
	.string "de tu camino, entre otras cosas.$"

Help_Text_AnswerWhenCanIUseItem_ES::
	.string "Depende del tipo. Algunos puedes\n"
	.string "usarlos durante el viaje; y otros,\l"
	.string "en combate. Tú, inténtalo siempre,\l"
	.string "si no está permitido, se te dirá.$"

Help_Text_AnswerWhatsABattle_ES::
	.string "El encuentro en el que debes\n"
	.string "tratar de reducir la energía del\l"
	.string "rival, los PS, a cero. Cuando tu\l"
	.string "contrario se debilite, ganarás y\l"
	.string "obtendrás puntos de EXP. Cuantos\l"
	.string "más puntos de EXP. tengan tus\l"
	.string "POKéMON, antes evolucionarán.$"

Help_Text_AnswerHowDoIPrepareForBattle_ES::
	.string "En primer lugar, los miembros de\n"
	.string "tu equipo (los POKéMON que te\l"
	.string "acompañan) deben estar en forma.\l"
	.string "Cúralos en un CENTRO POKéMON.\l"
	.string "Y lleva siempre encima objetos\l"
	.string "curativos de los que encontrarás\l"
	.string "en las TIENDAS POKéMON.$"

Help_Text_AnswerWhatIsAMonsVitality_ES::
	.string "Es la fuerza que le queda, y se\n"
	.string "expresa en PS. Si un POKéMON\l"
	.string "resulta herido en combate, sus PS\l"
	.string "bajan. Si éstos llegaran a cero, se\l"
	.string "debilitará. Cura a los POKéMON\l"
	.string "heridos o debilitados en un CENTRO\l"
	.string "POKéMON o usando objetos.$"

Help_Text_AnswerMyMonsAreHurt_ES::
	.string "Ve a un CENTRO POKéMON.\n"
	.string "Es un lugar de recuperación para\l"
	.string "los POKéMON. A través de un\l"
	.string "proceso mecánico, recuperan los PS\l"
	.string "y eliminan los problemas de estado.\l"
	.string "Es un servicio gratuito, así que\l"
	.string "úsalo con frecuencia.$"

Help_Text_AnswerWhatIsStatusProblem_ES::
	.string "Son las alteraciones que sufre un\n"
	.string "POKéMON tras recibir un ataque.\l"
	.string "Puede ser quemadura, parálisis,\l"
	.string "envenenamiento, sueño profundo\l"
	.string "y congelamiento. Pero se pueden\l"
	.string "eliminar en un CENTRO POKéMON\l"
	.string "o con el objeto adecuado.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint_ES::
	.string "Si los POKéMON de tu equipo (los\n"
	.string "que te acompañan) se debilitan,\l"
	.string "pierdes DINERO y vuelves a casa\l"
	.string "o a un CENTRO POKéMON. Para\l"
	.string "intentar que no ocurra, ve a los\l"
	.string "CENTROS POKéMON con frecuencia.\l"
	.string "¡Y no te olvides de guardar!$"

Help_Text_AnswerCantCatchMons_ES::
	.string "Si un POKéMON salvaje se escapa\n"
	.string "de una POKé BALL, es que aún\l"
	.string "tiene ganas de luchar. Intenta\l"
	.string "reducir más sus PS y paralizarlo o\l"
	.string "dejarlo dormido antes de atraparlo.\l"
	.string "Si ves que la POKé BALL se mueve\l"
	.string "durante un rato, ¡es casi tuyo!$"

Help_Text_AnswerRanOutOfPotions_ES::
	.string "Hay establecimientos, llamados\n"
	.string "TIENDAS POKéMON, en los que venden\l"
	.string "objetos. Pero ten en cuenta que en\l"
	.string "rutas, bosques y cuevas no hay.\l"
	.string "Aprovecha cuando estés en algún\l"
	.string "pueblo y compra lo que necesites.$"

Help_Text_AnswerCanIBuyPokeBalls_ES::
	.string "Podrás comprar POKé BALLS\n"
	.string "en cualquier TIENDA POKéMON.\l"
	.string "Pero ten en cuenta que en\l"
	.string "rutas, bosques y cuevas no hay.\l"
	.string "Aprovecha cuando estés en algún\l"
	.string "pueblo y compra lo que necesites.$"

Help_Text_AnswerWhatsATrainer_ES::
	.string "Un ENTRENADOR es alguien que cría\n"
	.string "POKéMON luchando. Siempre desafía\l"
	.string "a quien se encuentra, esté donde\l"
	.string "esté. Como cruces la mirada con\l"
	.string "alguno, tendrás que luchar.\l"
	.string "¡Mucho ojo!$"

Help_Text_AnswerHowDoIWinAgainstTrainer_ES::
	.string "Para ganar a un ENTRENADOR, usa\n"
	.string "POKéMON que tengan tipos a los que\l"
	.string "les puedas sacar ventaja. Los\l"
	.string "que estén más entrenados te serán\l"
	.string "muy útiles, igual que los de nivel\l"
	.string "superior a los de tu rival.$"

Help_Text_AnswerWhereDoMonsAppear_ES::
	.string "Los POKéMON salvajes suelen salir\n"
	.string "de las zonas de hierba alta de las\l"
	.string "rutas y los bosques. En las cuevas\l"
	.string "aparecen en cualquier lugar.\l"
	.string "En los pueblos no hay POKéMON\l"
	.string "salvajes ni ENTRENADORES, así\l"
	.string "que son sitios seguros.$"

Help_Text_AnswerWhatAreMoves_ES::
	.string "Son las técnicas que aprenden.\n"
	.string "Hay muchas e incluyen ataques\l"
	.string "y movimientos que tienen efectos\l"
	.string "especiales. Según sea el tipo del\l"
	.string "POKéMON, así serán los movimientos\l"
	.string "que pueda aprender. Algunos se\l"
	.string "aprenden a través de máquinas.$"

Help_Text_AnswerWhatAreHiddenMoves_ES::
	.string "Los movimientos OCULTOS son los\n"
	.string "más importantes para tu aventura.\l"
	.string "Para usar uno fuera de combate,\l"
	.string "tienes que abrir el menú POKéMON\l"
	.string "y hacer que el POKéMON que conoce\l"
	.string "la técnica la use. Esto funcionará\l"
	.string "aunque el POKéMON esté debilitado.$"

Help_Text_AnswerWhatMovesShouldIUse_ES::
	.string "Selecciona LUCHA para ver el\n"
	.string "menú de los movimientos. Fíjate en\l"
	.string "la combinación de los tipos. Para\l"
	.string "ver qué efecto tiene un movimiento,\l"
	.string "elige POKéMON, selecciona uno,\l"
	.string "entra en DATOS y después en\l"
	.string "MOV. CONOCIDOS.$"

Help_Text_AnswerWantToAddMoreMoves_ES::
	.string "Un POKéMON aprende cuatro\n"
	.string "movimientos al ir subiendo de nivel.\l"
	.string "Pero se le puede enseñar otros\l"
	.string "usando MT (Máquinas Técnicas)\l"
	.string "o MO (Máquinas Ocultas).\l"
	.string "Además, hay mucha gente\l"
	.string "que enseña movimientos.$"

Help_Text_AnswerWantToMakeMonStronger_ES::
	.string "Para fortalecer a tus POKéMON\n"
	.string "debes luchar y ganar a menudo. Los\l"
	.string "puntos de EXP. se repartirán entre\l"
	.string "los miembros de tu equipo que\l"
	.string "entraron en combate, y harán que\l"
	.string "suban de nivel. Con los POKéMON\l"
	.string "salvajes se puede entrenar bien.$"

Help_Text_AnswerFoeMonsTooStrong_ES::
	.string "Si tu rival es demasiado fuerte,\n"
	.string "sube más el nivel de tus POKéMON.\l"
	.string "Busca POKéMON salvajes con los\l"
	.string "que entrenarte para que mejore el\l"
	.string "nivel de tu equipo. También puedes\l"
	.string "enfrentarte a ENTRENADORES con\l"
	.string "los que no hayas luchado todavía.$"

Help_Text_AnswerWhatDoIDoInCave_ES::
	.string "Ten mucho cuidado cuando vayas\n"
	.string "a atravesar una. No son como los\l"
	.string "bosques y las rutas; aquí salen\l"
	.string "POKéMON salvajes por todos lados.\l"
	.string "Si tus POKéMON resultaran heridos,\l"
	.string "llévalos a un CENTRO POKéMON o\l"
	.string "cúralos corriendo con algún objeto.$"

Help_Text_AnswerNothingIWantToKnow_ES::
	.string "Confía en lo que sabes y en tu\n"
	.string "fuerza.\l"
	.string "¡Podrás hacer lo que te propongas!$"

Help_Text_AnswerWhatsPokemonCenter_ES::
	.string "Es la casa en la que pone “POKé”.\n"
	.string "En todos curan a los POKéMON, y\l"
	.string "hay acceso a PC, lo que es básico\l"
	.string "durante el viaje. El piso de arriba\l"
	.string "está preparado para que te\l"
	.string "conectes con tus amigos.$"

Help_Text_AnswerWhatsPokemonMart_ES::
	.string "Es la casa del tejado azul en la\n"
	.string "que pone “SHOP”. En ellas se\l"
	.string "pueden comprar o vender objetos, y\l"
	.string "algunas tienen objetos exclusivos.$"

Help_Text_AnswerWantToEndGame_ES::
	.string "Cuando quieras, podrás seleccionar\n"
	.string "“GUARDAR” en el menú.\l"
	.string "Cuando hayas guardado la partida,\l"
	.string "podrás apagar la consola (OFF),\l"
	.string "así podrás continuar cuando quieras\l"
	.string "desde el mismo lugar en el que\l"
	.string "te quedaste al guardar la partida.$"

Help_Text_AnswerWhatsAMon_ES::
	.string "Los POKéMON son unas criaturas\n"
	.string "de las que aún no se sabe todo.\l"
	.string "Es fácil verlas entre la hierba,\l"
	.string "en el mar, y en las cuevas.\l"
	.string "En general, suelen obedecer\l"
	.string "los deseos de su ENTRENADOR.$"

Help_Text_AnswerWhatIsThatPersonLike_ES::
	.string "Usa el MEMORÍN que tienes en el\n"
	.string "BOLSILLO de los OBJETOS CLAVES\l"
	.string "de la MOCHILA. Seguro que te da\l"
	.string "información muy útil.$"

Help_Text_AnswerWhatDoesHiddenMoveDo_ES::
	.string "Los movimientos OCULTOS se enseñan\n"
	.string "usando una MO (Máquina Oculta).\l"
	.string "Son muy importantes para tu viaje.\l"
	.string "Por ejemplo, con uno iluminas\l"
	.string "cuevas oscuras, y con otro, cortas\l"
	.string "árboles pequeños. También hay uno\l"
	.string "para desplazarse por el agua...$"

Help_Text_AnswerWhatDoIDoInSafari_ES::
	.string "Intenta atrapar POKéMON salvajes\n"
	.string "lanzando las especiales SAFARI\l"
	.string "BALLS. ¡Y guarda los objetos\l"
	.string "que encuentres!$"

Help_Text_AnswerWhatAreSafariRules_ES::
	.string "Tu estancia en el SAFARI acaba al\n"
	.string "recorrer cierta distancia o quedarte\l"
	.string "sin SAFARI BALLS. Abre el menú\l"
	.string "para ver cuántos pasos has dado\l"
	.string "y las SAFARI BALLS que te quedan.$"

Help_Text_AnswerWantToEndSafari_ES::
	.string "Si quieres retirarte del SAFARI,\n"
	.string "abre el menú y selecciona RETIR.$"

Help_Text_AnswerWhatIsAGym_ES::
	.string "Un GIMNASIO POKéMON es el lugar\n"
	.string "en el que luchan los ENTRENADORES\l"
	.string "de la LIGA POKéMON. Hay por toda\l"
	.string "la zona y los dirigen LÍDERES muy\l"
	.string "experimentados. Para ganar la\l"
	.string "MEDALLA del GIMNASIO, hay que\l"
	.string "vencer al LÍDER.$"

Help_Text_UsingPokedex_ES::
	.string "Usando POKéDEX.$"

Help_Text_UsingPokemon_ES::
	.string "Usando POKéMON.$"

Help_Text_UsingSummary_ES::
	.string "  Usando DATOS.$"

Help_Text_UsingSwitch_ES::
	.string "  Usando CAMBIO.$"

Help_Text_UsingItem_ES::
	.string "  Usando OBJETO.$"

Help_Text_UsingBag_ES::
	.string "Usando MOCHILA.$"

Help_Text_UsingAnItem_ES::
	.string "  Usando un objeto.$"

Help_Text_UsingKeyItem_ES::
	.string "  Usando un objeto clave.$"

Help_Text_UsingPokeBall_ES::
	.string "  Usando una POKé BALL.$"

Help_Text_UsingPlayer_ES::
	.string "Usando {PLAYER}.$"

Help_Text_UsingSave_ES::
	.string "Usando GUARDAR.$"

Help_Text_UsingOption_ES::
	.string "Usando OPCIONES.$"

Help_Text_UsingPotion_ES::
	.string "    Usando una POCIÓN.$"

Help_Text_UsingTownMap_ES::
	.string "    Usando el MAPA.$"

Help_Text_UsingTM_ES::
	.string "    Usando una MT.$"

Help_Text_UsingHM_ES::
	.string "    Usando una MO.$"

Help_Text_UsingMoveOutsideOfBattle_ES::
	.string "Usando un ataque fuera de combate.$"

Help_Text_RidingBicycle_ES::
	.string "    Usando la BICI.$"

Help_Text_EnteringName_ES::
	.string "Escribiendo un nombre.$"

Help_Text_UsingPC_ES::
	.string "Usando un PC.$"

Help_Text_UsingBillsPC_ES::
	.string "Usando el PC de {STR_VAR_1}.$"

Help_Text_UsingWithdraw_ES::
	.string "  Usando SACAR.$"

Help_Text_UsingDeposit_ES::
	.string "  Usando DEJAR.$"

Help_Text_UsingMove_ES::
	.string "  Usando MOVER.$"

Help_Text_MovingItems_ES::
	.string "  Moviendo objetos.$"

Help_Text_UsingPlayersPC_ES::
	.string " Usando el PC de {PLAYER}.$"

Help_Text_UsingWithdrawItem_ES::
	.string "  Usando SACAR OBJETO.$"

Help_Text_UsingDepositItem_ES::
	.string "  Usando DEJAR OBJETO.$"

Help_Text_UsingMailbox_ES::
	.string "  Usando BUZÓN.$"

Help_Text_UsingProfOaksPC_ES::
	.string " Usando el PC del PROF. OAK.$"

Help_Text_OpeningMenu_ES::
	.string "Abriendo el menú.$"

Help_Text_UsingFight_ES::
	.string " Usando LUCHA.$"

Help_Text_UsingPokemon2_ES::
	.string " Usando POKéMON.$"

Help_Text_UsingShift_ES::
	.string "  Usando CAMBIO.$"

Help_Text_UsingSummary2_ES::
	.string "  Usando DATOS.$"

Help_Text_UsingBag2_ES::
	.string " Usando MOCHILA.$"

Help_Text_ReadingPokedex_ES::
	.string " Leyendo la POKéDEX.$"

Help_Text_UsingHomePC_ES::
	.string "Usando el PC de casa.$"

Help_Text_UsingItemStorage_ES::
	.string "Usando el Sist. de Almacenamiento.$"

Help_Text_UsingWithdrawItem2_ES::
	.string "  Usando SACAR OBJETO.$"

Help_Text_UsingDepositItem2_ES::
	.string "  Usando DEJAR OBJETO.$"

Help_Text_UsingMailbox2_ES::
	.string "Usando el BUZÓN.$"

Help_Text_UsingRun_ES::
	.string "Usando HUIDA.$"

Help_Text_RegisterKeyItem_ES::
	.string "  ASIGNANDO un objeto clave.$"

Help_Text_UsingBall_ES::
	.string "Usando BALL.$"

Help_Text_UsingBait_ES::
	.string "Usando CEBO.$"

Help_Text_UsingRock_ES::
	.string "Usando ROCA.$"

Help_Text_UsingHallOfFame_ES::
	.string "Usando HALL FAMA.$"

Help_Text_HowToUsePokedex_ES::
	.string "{CIRCLE_1} Selecciona POKéDEX en el menú.\n"
	.string "{CIRCLE_2} Busca POKéMON según criterios\n"
	.string "   como LAS POKéDEX o POKéMON\n"
	.string "   SEGÚN SU HÁBITAT.\n"
	.string "{CIRCLE_3} Selecciona el POKéMON que\n"
	.string "   quieras para ver los detalles.$"

Help_Text_HowToUsePokemon_ES::
	.string "{CIRCLE_1} Selecciona POKéMON en el menú.\n"
	.string "{CIRCLE_2} Elige un POKéMON de tu equipo.\n"
	.string "{CIRCLE_3} Selecciona DATOS, CAMBIO\n"
	.string "   u OBJETO.$"

Help_Text_HowToUseSummary_ES::
	.string "{CIRCLE_1} Selecciona DATOS.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   INFO. POKéMON,\n"
	.string "   HABIL. POKéMON\n"
	.string "   o MOV. CONOCIDOS.$"

Help_Text_HowToUseSwitch_ES::
	.string "{CIRCLE_1} Elige el POKéMON que quieras\n"
	.string "   cambiar de posición.\n"
	.string "{CIRCLE_2} Selecciona CAMBIO.\n"
	.string "{CIRCLE_3} Selecciona el POKéMON con el\n"
	.string "   que quieras cambiar al primero.\n"
	.string "El que aparezca en la parte izqda\n"
	.string "será el primero en luchar.$"

Help_Text_HowToUseItem_ES::
	.string "{CIRCLE_1} Selecciona OBJETO.\n"
	.string "{CIRCLE_2} Decide si quieres DAR un objeto\n"
	.string "   a un POKéMON,\n"
	.string "   o QUITAR un objeto que lleve.\n"
	.string "¡Los POKéMON no pueden llevar más\n"
	.string "de un objeto!$"

Help_Text_HowToUseBag_ES::
	.string "{CIRCLE_1} Selecciona MOCHILA en el menú.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   OBJETOS, OBJ. CLAVE\n"
	.string "   o POKé BALLS.\n"
	.string "   Pulsa arriba o abajo para\n"
	.string "   seleccionar un objeto.$"

Help_Text_HowToUseAnItem_ES::
	.string "{CIRCLE_1} Selecciona el BOLSILLO de los\n"
	.string "OBJETOS.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir uno.\n"
	.string "{CIRCLE_3} Selecciona USAR para usarlo.\n"
	.string "Habrá objetos que no puedas usar\n"
	.string "según el sitio y la situación.$"

Help_Text_HowToUseKeyItem_ES::
	.string "{CIRCLE_1} Selecciona el BOLSILLO de los\n"
	.string "OBJ. CLAVE.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir uno.\n"
	.string "{CIRCLE_3} Selecciona USAR para usarlo.$"

Help_Text_HowToUsePokeBall_ES::
	.string "{CIRCLE_1} Cuando luches con un POKéMON\n"
	.string "   salvaje, selecciona el BOLSILLO\n"
	.string "   de las POKé BALLS.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir una\n"
	.string "   POKé BALL.\n"
	.string "{CIRCLE_3} Selecciona USAR para lanzarla.$"

Help_Text_HowToUsePlayer_ES::
	.string "{CIRCLE_1} Selecciona {PLAYER} en el menú.\n"
	.string "{CIRCLE_2} Aparecerá boca arriba tu FICHA\n"
	.string "   de ENTRENADOR con información\n"
	.string "   básica. Pulsa el Botón A para\n"
	.string "   darle la vuelta.\n"
	.string "{CIRCLE_3} Verás los distintos datos\n"
	.string "   que hay.$"

Help_Text_HowToUseSave_ES::
	.string "{CIRCLE_1} Selecciona GUARDAR en el menú.\n"
	.string "{CIRCLE_2} Selecciona SÍ para guardar\n"
	.string "   la partida.\n"
	.string "Cuando guardes, puedes apagar\n"
	.string "(OFF) la consola. Cuando quieras\n"
	.string "jugar de nuevo, podrás continuar\n"
	.string "desde donde lo dejaste.$"

Help_Text_HowToUseOption_ES::
	.string "{CIRCLE_1} Selecciona OPCIONES en el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir\n"
	.string "   lo que quieras cambiar y hazlo\n"
	.string "   pulsando izquierda o derecha.\n"
	.string "{CIRCLE_3} Selecciona SALIR o pulsa el\n"
	.string "   Botón B cuando hayas acabado.$"

Help_Text_HowToUsePotion_ES::
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control y elige MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona POCIÓN en el\n"
	.string "   BOLSILLO de los OBJETOS.\n"
	.string "{CIRCLE_4} Selecciona USAR.\n"
	.string "{CIRCLE_5} Selecciona qué POKéMON curas.$"

Help_Text_HowToUseTownMap_ES::
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control y elige MOCHILA.\n"
	.string "{CIRCLE_3} Pulsa izqda o dcha para abrir\n"
	.string "   el BOLSILLO de los OBJ. CLAVE, y\n"
	.string "   arriba y abajo para elegir MAPA.\n"
	.string "{CIRCLE_4} Selecciona USAR para abrirlo.$"

Help_Text_HowToUseTM_ES::
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Abre el BOLSILLO de los OBJ.\n"
	.string "   CLAVE de la MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona TUBO MT-MO y ABRIR.\n"
	.string "{CIRCLE_4} Selecciona una MT y elige USAR.\n"
	.string "{CIRCLE_5} Elige qué POKéMON la aprenderá.$"

Help_Text_HowToUseHM_ES::
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Abre el BOLSILLO de los OBJ.\n"
	.string "   CLAVE de la MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona TUBO MT-MO y ABRIR.\n"
	.string "{CIRCLE_4} Selecciona una MO y elige USAR.\n"
	.string "{CIRCLE_5} Elige qué POKéMON la aprenderá.\n"
	.string "   ¡Recuerda que cuesta olvidarlas!$"

Help_Text_HowToUseMoveOutsideOfBattle_ES::
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Selecciona POKéMON.\n"
	.string "{CIRCLE_3} Selecciona uno que sepa usar\n"
	.string "   una MO, aparecerán en azul.\n"
	.string "   Elige la que quieras y destruye\n"
	.string "   obstáculos, vuela, haz surf...$"

Help_Text_HowToRideBicycle_ES::
	.string "{CIRCLE_1} Abre el menú. Abre el BOLSILLO\n"
	.string "   de los OBJ. CLAVE de la\n"
	.string "   MOCHILA. Selecciona la BICI.\n"
	.string "{CIRCLE_2} Selecciona USAR para montarte o\n"
	.string "   ASIGNAR para usarla al instante\n"
	.string "   pulsando SELECT.$"

Help_Text_HowToEnterName_ES::
	.string "{CIRCLE_1} Coloca el cursor en la letra que\n"
	.string "   quieras con el {PLUS} Panel de Control\n"
	.string "   y escríbela pulsando el Botón A.\n"
	.string "{CIRCLE_2} Pulsa el Botón B para borrarla.\n"
	.string "{CIRCLE_3} Pulsa SELECT para elegir entre\n"
	.string "   mayúsculas y minúsculas.\n"
	.string "{CIRCLE_4} Elige FIN y pulsa el Botón A.$"

Help_Text_HowToUsePC_ES::
	.string "{CIRCLE_1} Ve a un CENTRO POKéMON,\n"
	.string "   acércate al PC y pulsa el Botón\n"
	.string "   A.$"

Help_Text_HowToUseBillsPC_ES::
	.string "{CIRCLE_1} Selecciona PC de {STR_VAR_1}.\n"
	.string "{CIRCLE_2} Selecciona una de las opciones\n"
	.string "   para acceder al Sistema de\n"
	.string "   Almacenamiento POKéMON.\n"
	.string "Si atrapas algún POKéMON cuando\n"
	.string "ya tienes seis en tu equipo, irá de\n"
	.string "forma automática a una CAJA.$"

Help_Text_HowToUseWithdraw_ES::
	.string "{CIRCLE_1} Selecciona un POKéMON de la\n"
	.string "   CAJA con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_2} Selecciona SACAR para retirarlo\n"
	.string "   de la CAJA y añadirlo al equipo.\n"
	.string "Si ya tienes los seis POKéMON de\n"
	.string "tu equipo, ¡no podrás sacar más!$"

Help_Text_HowToUseDeposit_ES::
	.string "{CIRCLE_1} Selecciona un POKéMON de tu\n"
	.string "   equipo con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_2} Selecciona DEJAR.\n"
	.string "{CIRCLE_3} Selecciona una CAJA y pulsa\n"
	.string "   el Botón A para colocarlo.\n"
	.string "Si sólo tienes un POKéMON contigo,\n"
	.string "¡no podrás dejarlo!$"

Help_Text_HowToUseMove_ES::
	.string "{CIRCLE_1} Selecciona un POKéMON.\n"
	.string "{CIRCLE_2} Elige un POKéMON seleccionando\n"
	.string "   MOVER y colócalo donde quieras\n"
	.string "   con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_3} Pon al POKéMON sobre el nombre\n"
	.string "   de una CAJA y pulsa izqda o dcha\n"
	.string "   para elegir dónde lo dejas.$"

Help_Text_HowToMoveItems_ES::
	.string "{CIRCLE_1} Los POKéMON que no salen nítidos\n"
	.string "   pueden llevar objetos. Elige uno\n"
	.string "   y confirma con el Botón A.\n"
	.string "{CIRCLE_2} Los POKéMON que salen nítidos\n"
	.string "   pueden darle a otro POKéMON\n"
	.string "   el objeto que lleven o devolverlo\n"
	.string "   a la MOCHILA con el Botón A.$"

Help_Text_HowToUsePlayersPC_ES::
	.string "{CIRCLE_1} Selecciona el PC de {PLAYER}.\n"
	.string "{CIRCLE_2} Selecciona ALMACÉN OBJ. o\n"
	.string "   BUZÓN.\n"
	.string "Cuando tengas llena la MOCHILA,\n"
	.string "podrás guardar cosas en el PC.\n"
	.string "Si quieres sacar objetos, podrás\n"
	.string "hacerlo también.$"

Help_Text_HowToUseWithdrawItem_ES::
	.string "{CIRCLE_1} Selecciona SACAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   sacar.\n"
	.string "{CIRCLE_3} Cuando lo saques, podrás\n"
	.string "   colocarlo en el BOLSILLO de\n"
	.string "   los OBJETOS de la MOCHILA o\n"
	.string "   dárselo sin más a un POKéMON.$"

Help_Text_HowToUseDepositItem_ES::
	.string "{CIRCLE_1} Selecciona DEJAR OBJETO.\n"
	.string "{CIRCLE_2} Elige con el {PLUS} Panel de\n"
	.string "   Control el que quieras dejar.\n"
	.string "{CIRCLE_3} Si quieres dejar más de uno,\n"
	.string "   decide la cantidad con el {PLUS}\n"
	.string "   Panel de Control y confirma con\n"
	.string "   el Botón A.$"

Help_Text_HowToUseMailbox_ES::
	.string "Cuando retires una CARTA de un\n"
	.string "POKéMON, irá al BUZÓN. Sólo podrás\n"
	.string "usar el BUZÓN cuando haya CARTAS.\n"
	.string "{CIRCLE_1} Selecciona el PC de {PLAYER}.\n"
	.string "{CIRCLE_2} Selecciona BUZÓN para leer\n"
	.string "   la CARTA o para dársela a un\n"
	.string "   POKéMON.$"

Help_Text_HowToUseProfOaksPC_ES::
	.string "{CIRCLE_1} Selecciona el PC del PROF. OAK.\n"
	.string "{CIRCLE_2} El PROF. OAK le echará un ojo\n"
	.string "   a tu POKéDEX.\n"
	.string "Presta atención a lo que te diga\n"
	.string "para completarla.$"

Help_Text_HowToOpenMenu_ES::
	.string "{CIRCLE_1} Pulsa START.\n"
	.string "{CIRCLE_2} A la derecha, aparecerá el menú.\n"
	.string "{CIRCLE_3} Las opciones variarán dependiendo\n"
	.string "   de la situación en la que estés.\n"
	.string "Habrá momentos en los que el menú\n"
	.string "no se abrirá: cuando hables con\n"
	.string "alguien, hagas algo, luches, etc.$"

Help_Text_HowToUseFight_ES::
	.string "{CIRCLE_1} Selecciona LUCHA.\n"
	.string "{CIRCLE_2} Selecciona uno de los\n"
	.string "movimientos que aparezcan para\n"
	.string "usarlo.$"

Help_Text_HowToUsePokemon2_ES::
	.string "{CIRCLE_1} Selecciona POKéMON.\n"
	.string "{CIRCLE_2} Selecciona al POKéMON de tu\n"
	.string "   equipo que quieras.\n"
	.string "{CIRCLE_3} Si tienes dos o más, podrás\n"
	.string "   cambiarlos de sitio eligiendo\n"
	.string "   CAMBIO. Para ver datos de los\n"
	.string "   POKéMON, selecciona DATOS.$"

Help_Text_HowToUseShift_ES::
	.string "Podrás sustituir al POKéMON que\n"
	.string "está luchando por otro de tu equipo.\n"
	.string "{CIRCLE_1} Selecciona al POKéMON que\n"
	.string "quieres que salga.\n"
	.string "{CIRCLE_2} Selecciona CAMBIAR.\n"
	.string "{CIRCLE_3} El POKéMON elegido sustituirá\n"
	.string "   al POKéMON que está en combate.$"

Help_Text_HowToUseSummary2_ES::
	.string "{CIRCLE_1} Selecciona DATOS.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   INFO. POKéMON\n"
	.string "   HABIL. POKéMON\n"
	.string "   o MOV. CONOCIDOS.$"

Help_Text_HowToUseBag2_ES::
	.string "{CIRCLE_1} Selecciona MOCHILA en el menú.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   OBJETOS, OBJ. CLAVE\n"
	.string "   o POKé BALLS.\n"
	.string "   Pulsa arriba o abajo para\n"
	.string "   seleccionar un objeto.$"

Help_Text_HowToReadPokedex_ES::
	.string "{CIRCLE_1} Cuando atrapes un POKéMON,\n"
	.string "   aparecerá una POKé BALL junto\n"
	.string "   a su nombre en LAS POKéDEX.\n"
	.string "{CIRCLE_2} Atrapar POKéMON proporciona\n"
	.string "   mucha información.\n"
	.string "{CIRCLE_3} Selecciona MÁS DATOS para ver\n"
	.string "   el MAPA y las zonas que habita.$"

Help_Text_HowToUseHomePC_ES::
	.string "{CIRCLE_1} Acércate al PC que hay arriba\n"
	.string "   y pulsa el Botón A.\n"
	.string "{CIRCLE_2} El PC se encenderá.\n"
	.string "{CIRCLE_3} Selecciona ALMACÉN OBJ. o\n"
	.string "   BUZÓN.$"

Help_Text_HowToUseItemStorage_ES::
	.string "{CIRCLE_1} Selecciona SACAR OBJETO\n"
	.string "   para sacar del PC un objeto\n"
	.string "   de los que salgan.\n"
	.string "{CIRCLE_2} Selecciona DEJAR OBJETO \n"
	.string "   para dejar en el PC un objeto\n"
	.string "   de los que salgan.$"

Help_Text_HowToUseWithdrawItem2_ES::
	.string "{CIRCLE_1} Selecciona SACAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   sacar.\n"
	.string "{CIRCLE_3} Cuando lo saques, podrás\n"
	.string "   colocarlo en el BOLSILLO de\n"
	.string "   los OBJETOS de la MOCHILA o\n"
	.string "   dárselo sin más a un POKéMON.$"

Help_Text_HowToUseDepositItem2_ES::
	.string "{CIRCLE_1} Selecciona DEJAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   dejar con el {PLUS} Panel de\n"
	.string "   Control.\n"
	.string "{CIRCLE_3} Si no hay nada en la MOCHILA,\n"
	.string "   ¡no podrás usar esta opción!$"

Help_Text_HowToUseMailbox2_ES::
	.string "Cuando retires una CARTA de un\n"
	.string "POKéMON, irá a parar al BUZÓN.\n"
	.string "Sólo podrás usar el BUZÓN cuando\n"
	.string "haya CARTAS.\n"
	.string "{CIRCLE_1} Selecciona la CARTA que quieras\n"
	.string "   para leerla o para dársela a un\n"
	.string "   POKéMON.$"

Help_Text_HowToUseRun_ES::
	.string "¡Si luchas contra ENTRENADORES\n"
	.string "no puedes usar HUIDA!\n"
	.string "{CIRCLE_1} Sólo podrás usarla cuando\n"
	.string "   luches contra POKéMON salvajes.\n"
	.string "{CIRCLE_2} Cuanto más rápido sea tu\n"
	.string "   POKéMON, más fácil te resultará\n"
	.string "   huir.$"

Help_Text_HowToRegisterKeyItem_ES::
	.string "Podrás ASIGNAR objetos clave para\n"
	.string "usarlos al instante pulsando SELECT.\n"
	.string "{CIRCLE_1} Abre el BOLSILLO de los\n"
	.string "   OBJ. CLAVE .\n"
	.string "{CIRCLE_2} Selecciona un objeto clave; y,\n"
	.string "   a continuación, ASIGNAR.$"

Help_Text_HowToUseBall_ES::
	.string "   Con esta opción, podrás lanzar\n"
	.string "   SAFARI BALLS, que sólo se usan\n"
	.string "   en la ZONA del SAFARI.\n"
	.string "Cuando veas POKéMON salvajes,\n"
	.string "lánzales muchas SAFARI BALLS\n"
	.string "para hacerte con ellos.$"

Help_Text_HowToUseBait_ES::
	.string "   Con esta opción, podrás echar\n"
	.string "   comida especial, que sólo se\n"
	.string "   usa en la ZONA del SAFARI.\n"
	.string "La comida POKéMON está hecha una\n"
	.string "bola para facilitar la ingestión. Si\n"
	.string "tiras CEBO, atraerás a los POKéMON\n"
	.string "salvajes y puede que no huyan.$"

Help_Text_HowToUseRock_ES::
	.string "   Con esta opción, podrás lanzar\n"
	.string "   una roca en la ZONA del SAFARI.\n"
	.string "Si le tiras una roca a un POKéMON,\n"
	.string "puede que huya, pero si no lo\n"
	.string "hace, te será más fácil atraparlo.$"

Help_Text_HowToUseHallOfFame_ES::
	.string "{CIRCLE_1} Selecciona HALL FAMA.\n"
	.string "{CIRCLE_2} Podrás echar un vistazo a los\n"
	.string "   POKéMON que estén en él.$"

Help_Text_HP_ES::
	.string "PS$"

Help_Text_EXP_ES::
	.string "EXP. {LEFT_PAREN}Puntos de EXP.{RIGHT_PAREN}$"

Help_Text_Moves_ES::
	.string "MOVIMIENTOS$"

Help_Text_Attack_ES::
	.string "ATAQUE$"

Help_Text_Defense_ES::
	.string "DEFENSA$"

Help_Text_SpAtk_ES::
	.string "AT. ESP.$"

Help_Text_SpDef_ES::
	.string "DEF. ESP.$"

Help_Text_Speed_ES::
	.string "VELOCID.$"

Help_Text_Level_ES::
	.string "Nv. {LEFT_PAREN}Nivel{RIGHT_PAREN}$"

Help_Text_Type_ES::
	.string "TIPO$"

Help_Text_OT_ES::
	.string "EO$"

Help_Text_Item_ES::
	.string "OBJETO$"

Help_Text_Ability_ES::
	.string "HABILIDAD$"

Help_Text_Money_ES::
	.string "DINERO$"

Help_Text_MoveType_ES::
	.string "TIPO de MOVIMIENTO$"

Help_Text_Nature_ES::
	.string "NATURALEZA$"

Help_Text_IDNo_ES::
	.string "N.ºID.$"

Help_Text_PP_ES::
	.string "PP$"

Help_Text_Power_ES::
	.string "POTENC.$"

Help_Text_Accuracy_ES::
	.string "PRECIS.$"

Help_Text_FNT_ES::
	.string "DEB$"

Help_Text_Items_ES::
	.string "OBJETOS$"

Help_Text_KeyItems_ES::
	.string "OBJ. CLAVE$"

Help_Text_PokeBalls_ES::
	.string "POKé BALLS$"

Help_Text_Pokedex_ES::
	.string "POKéDEX$"

Help_Text_PlayTime_ES::
	.string "TIEMPO J.$"

Help_Text_Badges_ES::
	.string "MEDALLAS$"

Help_Text_TextSpeed_ES::
	.string "VELOC. TEXTO$"

Help_Text_BattleScene_ES::
	.string "ANIM. COMBATE$"

Help_Text_BattleStyle_ES::
	.string "TIPO COMBATE$"

Help_Text_Sound_ES::
	.string "SONIDO$"

Help_Text_ButtonMode_ES::
	.string "CONTROLES$"

Help_Text_Frame_ES::
	.string "IMAGEN$"

Help_Text_Cancel2_ES::
	.string "SALIR$"

Help_Text_TM_ES::
	.string "MT$"

Help_Text_HM_ES::
	.string "MO$"

Help_Text_HMMove_ES::
	.string "MOVIMIENTO MO$"

Help_Text_Evolution_ES::
	.string "EVOLUCIÓN$"

Help_Text_StatusProblem_ES::
	.string "PROBLEMA de ESTADO$"

Help_Text_Pokemon_ES::
	.string "POKéMON$"

Help_Text_IDNo2_ES::
	.string "N.ºID.$"

Help_Text_Money2_ES::
	.string "DINERO$"

Help_Text_Badges2_ES::
	.string "MEDALLAS$"

Help_Text_DefineHP_ES::
	.string "Los PS indican la fuerza que le\n"
	.string "queda a un POKéMON. Si llegan a\l"
	.string "cero, éste se debilita y no puede\l"
	.string "seguir luchando. ¡Intenta que el\l"
	.string "rival se quede sin PS! Si tus\l"
	.string "POKéMON están heridos, cúralos en\l"
	.string "un CENTRO POKéMON o con objetos.$"

Help_Text_DefineEXP_ES::
	.string "Los puntos de EXP. representan\n"
	.string "la experiencia que va ganando un\l"
	.string "POKéMON al vencer en combate.\l"
	.string "Al alcanzar un número determinado,\l"
	.string "sube de nivel. La barra de EXP. \l"
	.string "muestra los puntos acumulados, y\l"
	.string "vuelve a 0 cuando se sube un nivel.$"

Help_Text_DefineMoves_ES::
	.string "Los POKéMON pueden aprender hasta\n"
	.string "cuatro movimientos diferentes. Hay\l"
	.string "varios tipos incluyendo los ataques\l"
	.string "y los que tienen efectos especiales.\l"
	.string "Cada POKéMON aprende distintos\l"
	.string "movimientos. Hay algunos que se\l"
	.string "aprenden gracias a ciertos objetos.$"

Help_Text_DefineAttack_ES::
	.string "El ATAQUE indica la potencia de un\n"
	.string "ataque. Cuanto mayor sea, más\l"
	.string "potencia tendrá el ataque. Va con\l"
	.string "los siguientes tipos: NORMAL,\l"
	.string "VENENO, TIERRA, VOLADOR, BICHO,\l"
	.string "LUCHA, ROCA, FANTASMA y ACERO.$"

Help_Text_DefineDefense_ES::
	.string "La DEFENSA indica la resistencia\n"
	.string "que tiene un POKéMON contra los\l"
	.string "ataques físicos. Cuanto mayor sea,\l"
	.string "menor será el daño infligido por el\l"
	.string "ataque físico del enemigo.$"

Help_Text_DefineSpAtk_ES::
	.string "El AT. ESP. (Ataque Especial)\n"
	.string "indica la potencia de un ataque\l"
	.string "especial. Cuanto mayor sea, más\l"
	.string "potencia tendrá el ataque.\l"
	.string "Va con los siguientes tipos: FUEGO,\l"
	.string "AGUA, ELÉCTRICO, PLANTA, HIELO,\l"
	.string "PSÍQUICO, DRAGÓN y SINIESTRO.$"

Help_Text_DefineSpDef_ES::
	.string "La DEF. ESP. (Defensa Especial)\n"
	.string "indica la resistencia contra los\l"
	.string "ataques especiales. Cuanto mayor\l"
	.string "sea, menor será el daño infligido\l"
	.string "por el at. especial del enemigo.$"

Help_Text_DefineSpeed_ES::
	.string "La VELOCIDAD indica la agilidad de\n"
	.string "un POKéMON. Si supera la del rival\l"
	.string "en combate, el POKéMON podrá usar\l"
	.string "un movimiento antes que él.$"

Help_Text_DefineLevel_ES::
	.string "El Nv. (Nivel) indica el momento\n"
	.string "de crecimiento y la fuerza de un\l"
	.string "POKéMON. Normalmente, al subir\l"
	.string "de nivel, aumentan PS, ATAQUE y\l"
	.string "DEFENSA, con lo que el POKéMON\l"
	.string "se hace más fuerte. Además, puede\l"
	.string "que aprenda otro movimiento.$"

Help_Text_DefineType_ES::
	.string "Los POKéMON y sus movimientos\n"
	.string "se clasifican por tipos. Según se\l"
	.string "combinen, así será el resultado. La\l"
	.string "mecánica es igual que la del juego\l"
	.string "“Piedra, papel, tijera”; el tipo\l"
	.string "AGUA sería fuerte frente al FUEGO,\l"
	.string "pero débil frente al tipo PLANTA.$"

Help_Text_DefineOT_ES::
	.string "EO es la sigla de ENTRENADOR\n"
	.string "Original. Hace referencia al primer\l"
	.string "ENTRENADOR que atrapó a un\l"
	.string "POKéMON determinado. El nombre del\l"
	.string "EO no se puede cambiar, aunque se\l"
	.string "envíe al POKéMON a otro cartucho.$"

Help_Text_DefineItem_ES::
	.string "Todos los POKéMON pueden llevar un\n"
	.string "objeto y algunos podrás usarlos de\l"
	.string "forma automática en determinadas\l"
	.string "situaciones. Para darles un objeto,\l"
	.string "selecciona el que quieras de la\l"
	.string "MOCHILA y, a continuación, DAR.$"

Help_Text_DefineAbility_ES::
	.string "Todos los POKéMON tienen una\n"
	.string "HABILIDAD especial. Algunas pueden\l"
	.string "usarse en combate; y otras, fuera.\l"
	.string "Las habilidades varían según la\l"
	.string "especie. Hay especies que tienen\l"
	.string "más de una habilidad.$"

Help_Text_DefineMoney_ES::
	.string "Cuando vences a un ENTRENADOR,\n"
	.string "ganas un premio en metálico.\l"
	.string "¡Ahorra para poder comprar útiles\l"
	.string "artículos en las TIENDAS POKéMON!$"

Help_Text_DefineMoveType_ES::
	.string "Los movimientos también se\n"
	.string "clasifican por tipos. Si un POKéMON\l"
	.string "usa uno de su tipo, tendrá mayor\l"
	.string "efecto. Si no es del mismo tipo,\l"
	.string "pero es una buena combinación,\l"
	.string "también tendrá mayor efecto.$"

Help_Text_DefineNature_ES::
	.string "Todos los POKéMON tienen cierta\n"
	.string "personalidad o NATURALEZA, que\l"
	.string "influye en la forma de crecer del\l"
	.string "POKéMON a medida que va subiendo\l"
	.string "de nivel.$"

Help_Text_DefineIDNo_ES::
	.string "El N.º es un número único que se\n"
	.string "te asigna como ENTRENADOR. Junto\l"
	.string "con el nombre de EO, el N.º se usa\l"
	.string "para identificar al ENTRENADOR\l"
	.string "Original. El N.º no se puede\l"
	.string "cambiar, aunque se envíe al\l"
	.string "POKéMON a otro cartucho.$"

Help_Text_DefinePP_ES::
	.string "PP es la sigla de PUNTOS de\n"
	.string "POTENCIA. Indican las veces que se\l"
	.string "ha usado un movimiento en combate.\l"
	.string "Podrás recuperar PP igual que\l"
	.string "restauras PS: en los CENTROS\l"
	.string "POKéMON o usando determinados\l"
	.string "objetos.$"

Help_Text_DefinePower_ES::
	.string "La POTENCIA indica la fuerza que\n"
	.string "tiene un ataque. Cuanto mayor sea,\l"
	.string "mayor será el daño causado al\l"
	.string "enemigo.$"

Help_Text_DefineAccuracy_ES::
	.string "La PRECISIÓN indica la\n"
	.string "probabilidad de alcanzar al rival.\l"
	.string "Cuanto mayor sea, mayor será\l"
	.string "la posibilidad de que el ataque\l"
	.string "alcance al enemigo.$"

Help_Text_DefineFNT_ES::
	.string "DEB indica que un POKéMON está\n"
	.string "debilitado. Un POKéMON se debilita\l"
	.string "cuando sus PS llegan a cero. Si\l"
	.string "esto ocurre, no puede participar\l"
	.string "en combate. Para restaurar a tus\l"
	.string "POKéMON debilitados, ve a un\l"
	.string "CENTRO POKéMON o usa un objeto.$"

Help_Text_DefineItems_ES::
	.string "Los objetos comunes comprados en\n"
	.string "las TIENDAS POKéMON se colocan\l"
	.string "en el BOLSILLO de los OBJETOS.\l"
	.string "Podrás usarlos, dárselos a tus\l"
	.string "POKéMON o tirarlos si no los\l"
	.string "quieres.$"

Help_Text_DefineKeyItems_ES::
	.string "Los objetos importantes que\n"
	.string "encuentres o recibas se ponen en el\l"
	.string "BOLSILLO de OBJETOS CLAVE, donde\l"
	.string "podrás acceder para usarlos. Con\l"
	.string "todo, puedes elegir uno y asignarlo\l"
	.string "a SELECT para no tener que abrir\l"
	.string "la MOCHILA, y usarlo de inmediato.$"

Help_Text_DefinePokeBalls_ES::
	.string "Las POKé BALLS se usan para atrapar\n"
	.string "POKéMON salvajes, y se colocan\l"
	.string "en el BOLSILLO de las POKé BALLS.\l"
	.string "Podrás comprarlas en las TIENDAS\l"
	.string "POKéMON y usarlas, dárselas a tus\l"
	.string "POKéMON o tirarlas cuando no las\l"
	.string "quieras.$"

Help_Text_DefinePokedex_ES::
	.string "Es el registro de las especies de\n"
	.string "POKéMON que has visto y atrapado.\l"
	.string "¡Hazte con todos los que puedas!$"

Help_Text_DefinePlayTime_ES::
	.string "Es el total del tiempo que has\n"
	.string "pasado jugando al juego.$"

Help_Text_DefineBadges_ES::
	.string "Son las MEDALLAS de la LIGA\n"
	.string "POKéMON que llevas conseguidas.\l"
	.string "Para ganar las MEDALLAS, deberás\l"
	.string "vencer a los LÍDERES de los\l"
	.string "GIMNASIOS de las ciudades\l"
	.string "y los pueblos que hay.$"

Help_Text_DefineTextSpeed_ES::
	.string "Puedes cambiarla para que los\n"
	.string "mensajes salgan a velocidad\l"
	.string "LENTA, MEDIA o RÁPIDA.$"

Help_Text_DefineBattleScene_ES::
	.string "Sirve para activar o desactivar\n"
	.string "la animación de los combates.$"

Help_Text_DefineBattleStyle_ES::
	.string "Decide si quieres tener la opción\n"
	.string "de cambiar de POKéMON cada vez\l"
	.string "que se debilita uno de tus POKéMON\l"
	.string "en combate.\l"
	.string "De ser así, selecciona CAMBIAR.$"

Help_Text_DefineSound_ES::
	.string "Elige entre MONO o ESTÉREO.$"

Help_Text_DefineButtonMode_ES::
	.string "Con AYUDA, al pulsar los Botones L\n"
	.string "o R saldrá la ayuda. Si dejas LR,\l"
	.string "pasarás las páginas de la POKéDEX\l"
	.string "y los BOLSILLOS de la MOCHILA con\l"
	.string "los Botones L y R. Si dejas L=A,\l"
	.string "el Botón L tendrá las mismas\l"
	.string "funciones que el Botón A.$"

Help_Text_DefineFrame_ES::
	.string "Echa un vistazo a los bordes que\n"
	.string "les puedes poner a algunos menús.$"

Help_Text_DefineCancel2_ES::
	.string "Con esta opción, dejarás los\n"
	.string "valores que aparecen en rojo\l"
	.string "y volverás al menú.$"

Help_Text_DefineTM_ES::
	.string "Las MT (Maquinas Técnicas) se usan\n"
	.string "para enseñar movimientos a los\l"
	.string "POKéMON capaces de usarlos.\l"
	.string "Hay muchos tipos, y al usarlas\l"
	.string "una vez, se rompen.$"

Help_Text_DefineHM_ES::
	.string "Las MO (Maquinas Ocultas) se usan\n"
	.string "para enseñar movimientos OCULTOS\l"
	.string "a los POKéMON capaces de usarlos.\l"
	.string "A diferencia de las MT, se pueden\l"
	.string "usar más de una vez y los\l"
	.string "movimientos se pueden olvidar.$"

Help_Text_DefineHMMove_ES::
	.string "Los movimientos OCULTOS son los\n"
	.string "más importantes para tu aventura.\l"
	.string "Para usar uno fuera de combate,\l"
	.string "tienes que abrir el menú POKéMON\l"
	.string "y hacer que el POKéMON que conoce\l"
	.string "la técnica la use. Esto funcionará\l"
	.string "aunque el POKéMON esté debilitado.$"

Help_Text_DefineEvolution_ES::
	.string "Algunos POKéMON sufren cambios\n"
	.string "cuando van subiendo de nivel, y\l"
	.string "evolucionan. Pueden cambiar de\l"
	.string "forma, de nombre y hasta pueden\l"
	.string "aprender nuevos movimientos.\l"
	.string "Otros, evolucionan por razones\l"
	.string "ajenas al aumento de nivel.$"

Help_Text_DefineStatusProblem_ES::
	.string "Los problemas de estado incluyen:\n"
	.string "Dormido: no puedes usar mov.\l"
	.string "Envenenado: reduce PS.\l"
	.string "Paralizado: difícil usar mov.\l"
	.string "Quemado: reduce PS y baja ATAQUE.\l"
	.string "Congelado: imposible usar mov.\l"
	.string "Tienen solución con objetos, etc.$"

Help_Text_DefinePokemon_ES::
	.string "POKéMON es el nombre que reciben\n"
	.string "las extraordinarias criaturas que\l"
	.string "habitan este mundo. La gente los\l"
	.string "cría a modo de mascota, para\l"
	.string "luchar, etc.$"

Help_Text_DefineIDNo2_ES::
	.string "El N.º es un número único que se\n"
	.string "te asigna como ENTRENADOR. Junto\l"
	.string "con el nombre de EO, el N.º se usa\l"
	.string "para identificar al ENTRENADOR\l"
	.string "Original. El N.º no se puede\l"
	.string "cambiar, aunque se envíe al\l"
	.string "POKéMON a otro cartucho.$"

Help_Text_DefineMoney2_ES::
	.string "Cuando vences a un ENTRENADOR,\n"
	.string "ganas un premio en metálico.\l"
	.string "¡Ahorra para poder comprar útiles\l"
	.string "artículos en las TIENDAS POKéMON!$"

Help_Text_DefineBadges2_ES::
	.string "Son las MEDALLAS de la LIGA\n"
	.string "POKéMON que llevas conseguidas.\l"
	.string "Para ganar las MEDALLAS, deberás\l"
	.string "vencer a los LÍDERES de los\l"
	.string "GIMNASIOS de las ciudades\l"
	.string "y los pueblos que hay.$"

Help_Text_TheHelpSystem_ES::
	.string "El sistema de AYUDA.$"

Help_Text_TheGame_ES::
	.string "El juego.$"

Help_Text_WirelessAdapter_ES::
	.string "El Conector inalámbrico de GBA.$"

Help_Text_GameFundamentals1_ES::
	.string "Nociones básicas 1.$"

Help_Text_GameFundamentals2_ES::
	.string "Nociones básicas 2.$"

Help_Text_GameFundamentals3_ES::
	.string "Nociones básicas 3.$"

Help_Text_WhatArePokemon_ES::
	.string "¿Qué son los POKéMON?$"

Help_Text_DescTheHelpSystem_ES::
	.string "Los mensajes de ayuda cambian\n"
	.string "según tu progreso. Están pensados\l"
	.string "para ayudarte cuando te hagan\l"
	.string "falta. Si no entiendes algo, ¡echa\l"
	.string "un vistazo al sistema de AYUDA!$"

Help_Text_DescTheGame_ES::
	.string "Acabas de convertirte en\n"
	.string "protagonista de esta historia.\l"
	.string "Estás en el mundo POKéMON. Tienes\l"
	.string "que hablar con la gente y resolver\l"
	.string "los misterios que se te presenten.\l"
	.string "Ábrete camino para llegar al final\l"
	.string "junto a tus maravillosos POKéMON.$"

Help_Text_DescWirelessAdapter_ES::
	.string "Este juego ofrece la posibilidad\n"
	.string "de conexión inalámbrica usando\l"
	.string "el Conector inalámbrico de GBA.\p"
	.string "¡Conéctate sin cables donde,\n"
	.string "cuando y con quien quieras!\p"
	.string "¡Juega con el Conector inalámbrico\n"
	.string "de GBA siempre conectado!$"

Help_Text_DescGameFundamentals1_ES::
	.string "No te pierdas nada, visita pueblos,\n"
	.string "ciudades, pasa por rutas, cuevas...\l"
	.string "¡Cada rincón supone un paso en tu\l"
	.string "carrera hacia el éxito entrenando\l"
	.string "POKéMON!$"

Help_Text_DescGameFundamentals2_ES::
	.string "Durante tu aventura, tendrás que\n"
	.string "hacer frente a muchos obstáculos.\l"
	.string "Deberás hacer distintas cosas y\l"
	.string "resolver diferentes enigmas para\l"
	.string "superarlos. Habrá obstáculos que\l"
	.string "haya que salvar a mucha distancia\l"
	.string "de su auténtico escenario...$"

Help_Text_DescGameFundamentals3_ES::
	.string "Habrá obstáculos que deberás\n"
	.string "salvar usando determinados\l"
	.string "movimientos de los que pueden\l"
	.string "aprender tus POKéMON.$"

Help_Text_DescWhatArePokemon_ES::
	.string "Los POKéMON son unas maravillosas\n"
	.string "y misteriosas criaturas. Los verás\l"
	.string "por todos los sitios de este mundo...\l"
	.string "entre la hierba, en las cuevas, en\l"
	.string "el agua... Son muy obedientes\l"
	.string "con su ENTRENADOR.$"

Help_Text_UsingTypeMatchupList_ES::
	.string "Usando la tabla de combinaciones.$"

Help_Text_OwnMoveDark_ES::
	.string "Tipo mov. propio: SINIESTRO.$"

Help_Text_OwnPokemonDark_ES::
	.string "Tipo PKMN propio: SINIESTRO.$"

Help_Text_OwnMoveRock_ES::
	.string "Tipo mov. propio: ROCA.$"

Help_Text_OwnPokemonRock_ES::
	.string "Tipo PKMN propio: ROCA.$"

Help_Text_OwnMovePsychic_ES::
	.string "Tipo mov. propio: PSÍQUICO.$"

Help_Text_OwnPokemonPsychic_ES::
	.string "Tipo PKMN propio: PSÍQUICO.$"

Help_Text_OwnMoveFighting_ES::
	.string "Tipo mov. propio: LUCHA.$"

Help_Text_OwnPokemonFighting_ES::
	.string "Tipo PKMN propio: LUCHA.$"

Help_Text_OwnMoveGrass_ES::
	.string "Tipo mov. propio: PLANTA.$"

Help_Text_OwnPokemonGrass_ES::
	.string "Tipo PKMN propio: PLANTA.$"

Help_Text_OwnMoveGhost_ES::
	.string "Tipo mov. propio: FANTASMA.$"

Help_Text_OwnPokemonGhost_ES::
	.string "Tipo PKMN propio: FANTASMA.$"

Help_Text_OwnMoveIce_ES::
	.string "Tipo mov. propio: HIELO.$"

Help_Text_OwnPokemonIce_ES::
	.string "Tipo PKMN propio: HIELO.$"

Help_Text_OwnMoveGround_ES::
	.string "Tipo mov. propio: TIERRA.$"

Help_Text_OwnPokemonGround_ES::
	.string "Tipo PKMN propio: TIERRA.$"

Help_Text_OwnMoveElectric_ES::
	.string "Tipo mov. propio: ELÉCTRICO.$"

Help_Text_OwnPokemonElectric_ES::
	.string "Tipo PKMN propio: ELÉCTRICO.$"

Help_Text_OwnMovePoison_ES::
	.string "Tipo mov. propio: VENENO.$"

Help_Text_OwnPokemonPoison_ES::
	.string "Tipo PKMN propio: VENENO.$"

Help_Text_OwnMoveDragon_ES::
	.string "Tipo mov. propio: DRAGÓN.$"

Help_Text_OwnPokemonDragon_ES::
	.string "Tipo PKMN propio: DRAGÓN.$"

Help_Text_OwnMoveNormal_ES::
	.string "Tipo mov. propio: NORMAL.$"

Help_Text_OwnPokemonNormal_ES::
	.string "Tipo PKMN propio: NORMAL.$"

Help_Text_OwnMoveSteel_ES::
	.string "Tipo mov. propio: ACERO.$"

Help_Text_OwnPokemonSteel_ES::
	.string "Tipo PKMN propio: ACERO.$"

Help_Text_OwnMoveFlying_ES::
	.string "Tipo mov. propio: VOLADOR.$"

Help_Text_OwnPokemonFlying_ES::
	.string "Tipo PKMN propio: VOLADOR.$"

Help_Text_OwnMoveFire_ES::
	.string "Tipo mov. propio: FUEGO.$"

Help_Text_OwnPokemonFire_ES::
	.string "Tipo PKMN propio: FUEGO.$"

Help_Text_OwnMoveWater_ES::
	.string "Tipo mov. propio: AGUA.$"

Help_Text_OwnPokemonWater_ES::
	.string "Tipo PKMN propio: AGUA.$"

Help_Text_OwnMoveBug_ES::
	.string "Tipo mov. propio: BICHO.$"

Help_Text_OwnPokemonBug_ES::
	.string "Tipo PKMN propio: BICHO.$"

Help_Text_HowToUseTypeMatchupList_ES::
	.string "Según sea la combinación del tipo\n"
	.string "del movimiento y el tipo del\l"
	.string "POKéMON rival, variará la eficacia:\l"
	.string "{CIRCLE_DOT}: ¡Es muy eficaz!\l"
	.string "{TRIANGLE}: No es muy eficaz...\l"
	.string "{BIG_MULT_X}: No es nada eficaz...\l"
	.string "(Común a las otras combinaciones).$"

Help_Text_TypeMatchupOwnMoveDark_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PSÍQUICO, FANTASMA\p"
	.string "   {TRIANGLE}: LUCHA, SINIESTRO, ACERO$"

Help_Text_TypeMatchupOwnPokemonDark_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: LUCHA, BICHO\p"
	.string "   {TRIANGLE}: FANTASMA, SINIESTRO\p"
	.string "   {BIG_MULT_X}: PSÍQUICO$"

Help_Text_TypeMatchupOwnMoveRock_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, HIELO, VOLADOR,\n"
	.string "       BICHO\p"
	.string "   {TRIANGLE}: LUCHA, TIERRA, ACERO$"

Help_Text_TypeMatchupOwnPokemonRock_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, PLANTA, LUCHA,\n"
	.string "       TIERRA, ACERO\p"
	.string "   {TRIANGLE}: NORMAL, FUEGO, VENENO,\n"
	.string "       VOLADOR$"

Help_Text_TypeMatchupOwnMovePsychic_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: LUCHA, VENENO\p"
	.string "   {TRIANGLE}: PSÍQUICO, ACERO\p"
	.string "   {BIG_MULT_X}: SINIESTRO$"

Help_Text_TypeMatchupOwnPokemonPsychic_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: BICHO, FANTASMA, SINIESTRO\p"
	.string "   {TRIANGLE}: LUCHA, PSÍQUICO$"

Help_Text_TypeMatchupOwnMoveFighting_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: NORMAL, HIELO, ROCA,\n"
	.string "       SINIESTRO, ACERO\p"
	.string "   {TRIANGLE}: VENENO, VOLADOR, PSÍQUICO,\n"
	.string "       BICHO\p"
	.string "   {BIG_MULT_X}: FANTASMA$"

Help_Text_TypeMatchupOwnPokemonFighting_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: VOLADOR, PSÍQUICO\p"
	.string "   {TRIANGLE}: BICHO, ROCA, SINIESTRO$"

Help_Text_TypeMatchupOwnMoveGrass_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: AGUA, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, PLANTA, VENENO,\n"
	.string "       BICHO, DRAGÓN, ACERO$"

Help_Text_TypeMatchupOwnPokemonGrass_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, HIELO, VENENO,\n"
	.string "       VOLADOR, BICHO\p"
	.string "   {TRIANGLE}: AGUA, ELÉCTRICO, PLANTA,\n"
	.string "       TIERRA$"

Help_Text_TypeMatchupOwnMoveGhost_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PSÍQUICO, FANTASMA\p"
	.string "   {TRIANGLE}: SINIESTRO, ACERO\p"
	.string "   {BIG_MULT_X}: NORMAL$"

Help_Text_TypeMatchupOwnPokemonGhost_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FANTASMA, SINIESTRO\p"
	.string "   {TRIANGLE}: VENENO, BICHO\p"
	.string "   {BIG_MULT_X}: NORMAL, LUCHA$"

Help_Text_TypeMatchupOwnMoveIce_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, TIERRA, VOLADOR\n"
	.string "       DRAGÓN\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, HIELO, ACERO$"

Help_Text_TypeMatchupOwnPokemonIce_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, LUCHA, ROCA, ACERO\p"
	.string "   {TRIANGLE}: HIELO$"

Help_Text_TypeMatchupOwnMoveGround_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, ELÉCTRICO, VENENO,\n"
	.string "       ROCA, ACERO\p"
	.string "   {TRIANGLE}: PLANTA, BICHO\n"
	.string "   {BIG_MULT_X}: VOLADOR$"

Help_Text_TypeMatchupOwnPokemonGround_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, PLANTA, HIELO\p"
	.string "   {TRIANGLE}: VENENO, ROCA\p"
	.string "   {BIG_MULT_X}: ELÉCTRICO$"

Help_Text_TypeMatchupOwnMoveElectric_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: AGUA, VOLADOR\p"
	.string "   {TRIANGLE}: ELÉCTRICO, PLANTA, DRAGÓN\p"
	.string "   {BIG_MULT_X}: TIERRA$"

Help_Text_TypeMatchupOwnPokemonElectric_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: TIERRA\p"
	.string "   {TRIANGLE}: ELÉCTRICO, VOLADOR, ACERO$"

Help_Text_TypeMatchupOwnMovePoison_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA\p"
	.string "   {TRIANGLE}: VENENO, TIERRA, ROCA,\n"
	.string "       FANTASMA\p"
	.string "   {BIG_MULT_X}: ACERO$"

Help_Text_TypeMatchupOwnPokemonPoison_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: TIERRA, PSÍQUICO\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, VENENO,\n"
	.string "       BICHO$"

Help_Text_TypeMatchupOwnMoveDragon_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: DRAGÓN\p"
	.string "   {TRIANGLE}: ACERO$"

Help_Text_TypeMatchupOwnPokemonDragon_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: HIELO, DRAGÓN\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ELÉCTRICO,\n"
	.string "       PLANTA$"

Help_Text_TypeMatchupOwnMoveNormal_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {TRIANGLE}: ROCA, ACERO\p"
	.string "   {BIG_MULT_X}: FANTASMA$"

Help_Text_TypeMatchupOwnPokemonNormal_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: LUCHA\p"
	.string "   {BIG_MULT_X}: FANTASMA$"

Help_Text_TypeMatchupOwnMoveSteel_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: HIELO, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ELÉCTRICO,\n"
	.string "       ACERO$"

Help_Text_TypeMatchupOwnPokemonSteel_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, LUCHA, TIERRA\n"
	.string "   {TRIANGLE}: NORMAL, PLANTA, HIELO,\l"
	.string "       VOL., PSÍQ., BICHO, ROCA,\l"
	.string "       FANT., DRAG., SINI., ACERO\l"
	.string "   {BIG_MULT_X}: VENENO$"

Help_Text_TypeMatchupOwnMoveFlying_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, LUCHA, BICHO\p"
	.string "   {TRIANGLE}: ELÉCTRICO, ROCA, ACERO$"

Help_Text_TypeMatchupOwnPokemonFlying_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: ELÉCTRICO, HIELO, ROCA\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, BICHO\p"
	.string "   {BIG_MULT_X}: TIERRA$"

Help_Text_TypeMatchupOwnMoveFire_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, HIELO, BICHO,\n"
	.string "       ACERO\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ROCA,\n"
	.string "       DRAGÓN$"

Help_Text_TypeMatchupOwnPokemonFire_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, PLANTA, HIELO,\n"
	.string "       BICHO, ACERO$"

Help_Text_TypeMatchupOwnMoveWater_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: AGUA, PLANTA, DRAGÓN$"

Help_Text_TypeMatchupOwnPokemonWater_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: ELÉCTRICO, PLANTA\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, HIELO, ACERO$"

Help_Text_TypeMatchupOwnMoveBug_ES::
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, PSÍQUICO, SINIESTRO\p"
	.string "   {TRIANGLE}: FUEGO, LUCHA, VENENO,\n"
	.string "       VOLADOR, FANTASMA, ACERO$"

Help_Text_TypeMatchupOwnPokemonBug_ES::
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, VOLADOR, ROCA\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, TIERRA$"

