Trade_Text_LookingForMonWannaTradeForMon_ES::
	.string "¡Busco un {STR_VAR_1}!\p"
	.string "¿Quieres cambiarlo por\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell_ES::
	.string "¿No?\n"
	.string "Pues vale...$"

Trade_Text_WhatThatsNoMon_ES::
	.string "¿Qué?\n"
	.string "¡Ése no es {STR_VAR_1}!$"

Trade_Text_HeyThanks_ES::
	.string "¡Muchas gracias!$"

Trade_Text_IsntMyOldMonGreat_ES::
	.string "¿No es estupendo mi {STR_VAR_2}?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon_ES::
	.string "¡Hola!\p"
	.string "¿Quieres cambiar tu {STR_VAR_1}\n"
	.string "por {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo_ES::
	.string "Vale, si no quieres...$"

Trade_Text_ThisIsntMon_ES::
	.string "¿Qué?\n"
	.string "Éste no es {STR_VAR_1}.\p"
	.string "Cuando tengas uno piensa en mí.$"

Trade_Text_Thanks_ES::
	.string "¡Gracias!$"

Trade_Text_HasTradedMonGrownStronger_ES::
	.string "¿Qué tal va el {STR_VAR_2} que te\n"
	.string "envié, más fuerte?$"

Trade_Text_DoYouHaveMonWantToTradeForMon_ES::
	.string "¡Hola!\n"
	.string "¿Tienes un {STR_VAR_1}?\p"
	.string "¿Quieres cambiarlo\n"
	.string "por {STR_VAR_2}?$"

Trade_Text_ThatsTooBad_ES::
	.string "¡Qué pena!$"

Trade_Text_ThisIsNoMon_ES::
	.string "Éste no es un {STR_VAR_1}.\p"
	.string "¡Si consigues uno, te lo cambio!$"

Trade_Text_ThanksYoureAPal_ES::
	.string "¡Gracias, contigo da gusto!$"

Trade_Text_HowIsMyOldMon_ES::
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡Mi {STR_VAR_1} está fenomenal!$"
