Text_IdLoveToHearYourProfile_ES:
	.string "Hola, me alegro de verte.\p"
	.string "Eh, he dicho hola...\n"
	.string "Qué borde... ya podrías\l"
	.string "contestar.\p"
	.string "Venga, cuéntame algo, anda.\p"
	.string "¡Dime al menos cuál es tu perfil!$"

Text_TellMeWhatsYourProfile_ES:
	.string "Cuéntame alguna cosa sobre ti.\n"
	.string "Dime cuál es tu perfil.$"

Text_ExplainProfile_ES:
	.string "El perfil puede hacerse con\n"
	.string "palabras o frases.\p"
	.string "Hay muchas palabras y frases\n"
	.string "para elegir, y están divididas\l"
	.string "por grupos.\p"
	.string "Selecciona primero un grupo\n"
	.string "y después el elemento que quieras.\p"
	.string "Es mucho más fácil de lo que\n"
	.string "parece. Inténtalo, anda.$"

Text_WhatsYourProfile_ES:
	.string "¿Cuál es tu perfil?$"

Text_DontBeLikeThat_ES:
	.string "Venga, anda, enséñame tu perfil...$"

Text_DecidedNotTo_ES:
	.string "Ah, ¿y no lo cambias?\n"
	.string "¡Pues hay que ver cómo eres!$"

Text_HiWeMeetAgain_ES:
	.string "¡Hola otra vez!$"

Text_ChangeYourProfile_ES:
	.string "¿Quieres cambiar tu perfil?$"

Text_WhatAreYouLikeNow_ES:
	.string "Me gustaría saber cuál tienes\n"
	.string "ahora.$"

Text_LikeProfileWayItIs_ES:
	.string "Vale, pues déjalo como está.\p"
	.string "A mí también me gusta.$"

Text_ProfileSaysSomethingAboutYou_ES:
	.string "Mmmm...\p"
	.string "La verdad es que te pega, da idea\n"
	.string "de cómo eres.\p"
	.string "¡Ahora nos conocemos mejor!\n"
	.string "¡Vamos a llevarnos bien siempre!$"

Text_HeardThatBefore_ES:
	.string "Eso ya lo he oído antes...\p"
	.string "Mi primo, que vive lejos de aquí,\n"
	.string "lo decía con frecuencia, creo.$"

Text_TellMoreNextTime_ES:
	.string "¡A ver si la próxima vez\n"
	.string "me cuentas más sobre ti!$"
