gOtherText_NewName_ES::
	.string "OTRO NOMBRE$"

gNameChoice_Green_ES::
	.string "VERTE$"

gNameChoice_Red_ES::
	.string "JORO$"

gNameChoice_Leaf_ES::
	.string "JAHO$"

gNameChoice_Fire_ES::
	.string "GUEFO$"

gNameChoice_Gary_ES::
	.string "BOSCO$"

gNameChoice_Kaz_ES::
	.string "FLOREN$"

gNameChoice_Toru_ES::
	.string "SILVIO$"

gNameChoice_Ash_ES::
	.string "FURIO$"

gNameChoice_Kene_ES::
	.string "LLAMÍN$"

gNameChoice_Geki_ES::
	.string "CANDEL$"

gNameChoice_Jak_ES::
	.string "JUNO$"

gNameChoice_Janne_ES::
	.string "JUAN$"

gNameChoice_Jonn_ES::
	.string "JUANMA$"

gNameChoice_Kamon_ES::
	.string "ÁLVARO$"

gNameChoice_Karl_ES::
	.string "RAL$"

gNameChoice_Taylor_ES::
	.string "MARINO$"

gNameChoice_Oscar_ES::
	.string "TOILO$"

gNameChoice_Hiro_ES::
	.string "NER$"

gNameChoice_Max_ES::
	.string "MAX$"

gNameChoice_Jon_ES::
	.string "MOREL$"

gNameChoice_Ralph_ES::
	.string "RAFA$"

gNameChoice_Kay_ES::
	.string "VER$"

gNameChoice_Tosh_ES::
	.string "LERIO$"

gNameChoice_Roak_ES::
	.string "RODI$"

gNameChoice_Omi_ES::
	.string "MENA$"

gNameChoice_Jodi_ES::
	.string "CIRA$"

gNameChoice_Amanda_ES::
	.string "MARÍA$"

gNameChoice_Hillary_ES::
	.string "MINA$"

gNameChoice_Makey_ES::
	.string "NENA$"

gNameChoice_Michi_ES::
	.string "LUNA$"

gNameChoice_Paula_ES::
	.string "BRUNA$"

gNameChoice_June_ES::
	.string "CLAUDIA$"

gNameChoice_Cassie_ES::
	.string "CASILDA$"

gNameChoice_Rey_ES::
	.string "RITA$"

gNameChoice_Seda_ES::
	.string "SELENA$"

gNameChoice_Kiko_ES::
	.string "MATILDE$"

gNameChoice_Mina_ES::
	.string "NURIA$"

gNameChoice_Norie_ES::
	.string "MARINA$"

gNameChoice_Sai_ES::
	.string "SALIA$"

gNameChoice_Momo_ES::
	.string "MIRTA$"

gNameChoice_Suzi_ES::
	.string "SUSA$"

gControlsGuide_Text_Intro_ES::
	.string "La explicación de los botones\n"
	.string "se hará por orden de importancia.$"

gControlsGuide_Text_DPad_ES::
	.string "Mover al protagonista de la\n"
	.string "historia. Seleccionar opciones.$"

gControlsGuide_Text_AButton_ES::
	.string "Confirmar opciones, curiosear\n"
	.string "cosas, chatear y leer texto.$"

gControlsGuide_Text_BButton_ES::
	.string "Retroceder, cancelar opciones\n"
	.string "y salir de distintos menús.$"

gControlsGuide_Text_StartButton_ES::
	.string "Abrir el menú.$"

gControlsGuide_Text_SelectButton_ES::
	.string "Cambiar objetos de lugar y usar\n"
	.string "el que haya registrado.$"

gControlsGuide_Text_LRButtons_ES::
	.string "Acceder al sistema de AYUDA.$"

gOakSpeech_Text_AskPlayerGender_ES::
	.string "Hola, ¿eres chico o chica?$"

gPikachuIntro_Text_Page1_ES::
	.string "Estás a punto de sumergirte en un\n"
	.string "mundo lleno de aventuras de las\n"
	.string "que vas a ser protagonista.\n"
	.string "\n"
	.string "Habla con la gente y curiosea todo\n"
	.string "lo que te llame la atención, estés\n"
	.string "donde estés. Consigue información\n"
	.string "y pistas de todo lo que te rodee.$"

gPikachuIntro_Text_Page2_ES::
	.string "Durante el largo camino, tendrás\n"
	.string "que ayudar a gente, enfrentarte\n"
	.string "a desafíos y resolver misterios.\n"
	.string "\n"
	.string "Te cruzarás con rivales y criaturas\n"
	.string "salvajes que querrán luchar\n"
	.string "contigo, pero ¡ánimo, tú puedes!$"

gPikachuIntro_Text_Page3_ES::
	.string "Recuerda, habla con todo el mundo;\n"
	.string "crecerás como persona, y ése es\n"
	.string "tu principal objetivo.\n"
	.string "\n"
	.string "Pulsa el Botón A, ¡que comience\n"
	.string "la aventura!$"

gOakSpeech_Text_WelcomeToTheWorld_ES::
	.string "¡Hola!\n"
	.string "¡Éste es el mundo de POKéMON!\p"
	.string "¡Me llamo OAK!\p"
	.string "¡Pero la gente me llama\n"
	.string "PROFESOR POKéMON!\p"
	.string "$"

gOakSpeech_Text_ThisWorld_ES::
	.string "¡Este mundo está$"

gOakSpeech_Text_IsInhabitedFarAndWide_ES::
	.string "habitado por unas criaturas\n"
	.string "llamadas POKéMON!\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon_ES::
	.string "Para algunos, los POKéMON son\n"
	.string "mascotas. Pero otros los usan\l"
	.string "para pelear.\p"
	.string "En cuanto a mí...\p"
	.string "Estudio a los POKéMON como\n"
	.string "profesión.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself_ES::
	.string "Bueno, cuéntame algo de ti.\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt_ES::
	.string "Pero primero dime cómo te llamas.\p"
	.string "\n"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer_ES::
	.string "¡Bien!\n"
	.string "¡Así que te llamas {PLAYER}!$"

gOakSpeech_Text_WhatWasHisName_ES::
	.string "Éste es mi nieto.\p"
	.string "Ha sido tu rival desde que erais\n"
	.string "pequeños.\p"
	.string "Mmm... ¿podrías decirme cómo\n"
	.string "se llama?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt_ES::
	.string "¿Cómo era el nombre de tu rival?$"

gOakSpeech_Text_ConfirmRivalName_ES::
	.string "Eh..., ¿era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName_ES::
	.string "¡Ah, sí! ¡Es verdad!\n"
	.string "¡Se llamaba {RIVAL}!\p"
	.string "$"

gOakSpeech_Text_LetsGo_ES::
	.string "¡{PLAYER}!\p"
	.string "¡Tu propia leyenda POKéMON está\n"
	.string "a punto de comenzar!\p"
	.string "¡Te espera un mundo de sueños y\n"
	.string "aventuras con los POKéMON!\l"
	.string "¡Adelante!$"
