Text_ObtainedTheX_ES::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_BagIsFull_ES::
	.string "La MOCHILA está llena...$"

Text_PutItemAway_ES::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el {STR_VAR_3}.$"

Text_FoundOneItem_ES::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

Text_TooBadBagFull_ES::
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena...$"

Text_FoundXCoins_ES::
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase_ES::
	.string "{PLAYER} puso las FICHAS\n"
	.string "en el MONEDERO.$"

Text_CoinCaseIsFull_ES::
	.string "¡Vaya!\n"
	.string "¡Tienes el MONEDERO lleno!...$"

Text_NothingToPutThemIn_ES::
	.string "¡Vaya!\n"
	.string "¡No tienes MONEDERO!...$"

Text_FoundXItems_ES::
	.string "{PLAYER} encontró estas unidades\n"
	.string "de {STR_VAR_2}: ¡{STR_VAR_1}!$"

Text_ObtainedTheDecor_ES::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor_ES::
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}...$"

Text_DecorTransferredToPC_ES::
	.string "Se envió {STR_VAR_2} al PC.$"
