Text_BootedUpPC_ES::
	.string "{PLAYER} encendió el PC.$"

Text_AccessWhichPC_ES::
	.string "¿A qué PC quieres acceder?$"

Text_AccessedSomeonesPC_ES::
	.string "Accedió al PC de alguien.$"

Text_OpenedPkmnStorage_ES::
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de POKéMON\l"
	.string "concedido.$"

Text_AccessedPlayersPC_ES::
	.string "Accedió al PC de {PLAYER}.$"

Text_AccessedBillsPC_ES::
	.string "Accedió al PC de BILL.$"
