PokedexRating_Text_HowIsPokedexComingAlong_ES::
	.string "OAK: ¡Encantado de verte!\n"
	.string "¿Cómo va tu POKéDEX?\p"
	.string "¡Déjame que le eche un vistazo!$"

PokedexRating_Text_SeenXOwnedY_ES::
	.string "Nivel POKéDEX:\p"
	.string "Has visto {STR_VAR_1} POKéMON\n"
	.string "Tienes {STR_VAR_2} POKéMON\p"
	.string "Evaluación del PROF. OAK:$"

PokedexRating_Text_LessThan10_ES::
	.string "Te queda mucho por hacer.\p"
	.string "¡Busca a los POKéMON en las zonas\n"
	.string "de hierba!$"

PokedexRating_Text_LessThan20_ES::
	.string "¡Estás en buen camino!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "la MO DESTELLO que le\l"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan30_ES::
	.string "¡Necesitas más POKéMON!\n"
	.string "¡Intenta capturar otras especies!$"

PokedexRating_Text_LessThan40_ES::
	.string "¡Muy bien!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "un BUSCAOBJETOS que le\l"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan50_ES::
	.string "¡Tu POKéDEX va de maravilla!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "la MONEDA AMULETO que le\l"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan60_ES::
	.string "¡Ya has conseguido 50 especies!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "el REPARTIR EXP. que le he dado\l"
	.string "para ti!$"

PokedexRating_Text_LessThan70_ES::
	.string "¡Oh!\n"
	.string "¡Lo estás haciendo genial!$"

PokedexRating_Text_LessThan80_ES::
	.string "¡Excelente!\p"
	.string "¡Ve a pescar algunos POKéMON\n"
	.string "del mar!$"

PokedexRating_Text_LessThan90_ES::
	.string "¡Magnífico!\n"
	.string "Te encanta coleccionar cosas, ¿eh?$"

PokedexRating_Text_LessThan100_ES::
	.string "¡Impresionante!\n"
	.string "¡Debe de haber sido muy difícil!$"

PokedexRating_Text_LessThan110_ES::
	.string "¡Por fin tienes 100 especies!\n"
	.string "¡Se te da genial!$"

PokedexRating_Text_LessThan120_ES::
	.string "¡Y has conseguido hasta transformar\n"
	.string "a tus POKéMON! ¡Eres genial!$"

PokedexRating_Text_LessThan130_ES::
	.string "¡Excelente! ¡Intercambia con tus\n"
	.string "amigos y tendrás más!$"

PokedexRating_Text_LessThan140_ES::
	.string "¡Impresionante!\n"
	.string "¡Eres muy profesional!$"

PokedexRating_Text_LessThan150_ES::
	.string "¡No tengo nada más que decir!\n"
	.string "¡Ahora eres una eminencia!$"

PokedexRating_Text_Complete_ES::
	.string "¡Tu POKéDEX está completa!\n"
	.string "¡Enhorabuena!$"

PokedexRating_Text_NationalDexSeenXOwnedY_ES::
	.string "A ver cómo llevas la POKéDEX\n"
	.string "NACIONAL:\p"
	.string "POKéMON avistados: {STR_VAR_1}\n"
	.string "POKéMON atrapados: {STR_VAR_2}$"

PokedexRating_Text_LookForwardToFilledNationalDex_ES::
	.string "¡Estoy deseando ver cómo completas\n"
	.string "la POKéDEX NACIONAL!$"

PokedexRating_Text_YouveCompletedDex_ES::
	.string "¡Por fin!\p"
	.string "¡Ya has completado la POKéDEX!\p"
	.string "¡Magnífico!\n"
	.string "¡De verdad, no era tarea fácil!$"

PokedexRating_Text_Wroooaaarrr_ES::
	.string "¡Guuuaaaaauuuuu!$"

PokedexRating_Text_HaHa_ES::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality_ES::
	.string "¡Gracias, {PLAYER}!\n"
	.string "Gracias de verdad.\l"
	.string "¡Has hecho mi sueño realidad!$"

PokedexRating_Text_LoveSeeingYourPokedex_ES::
	.string "OAK: ¡Hola!\p"
	.string "¿Qué tal llevas la POKéDEX?\p"
	.string "A ver...\p"
	.string "La verdad es que sé cómo es, pero\n"
	.string "me gusta verla de todas formas.\p"
	.string "A ver, a ver...$"
