Text_CardKeyOpenedDoor_ES::
	.string "¡Bingo! ¡La LLAVE MAGNÉTICA\n"
	.string "abrió la puerta!$"

Text_ItNeedsCardKey_ES::
	.string "¡Caray!\n"
	.string "¡Necesito una LLAVE MAGNÉTICA!$"

Text_AccessedProfOaksPC_ES::
	.string "Accedes al PC del PROF. OAK.\p"
	.string "Accedes al Sistema de Evaluación\n"
	.string "de la POKéDEX.$"

Text_HavePokedexRated_ES::
	.string "¿Quieres evaluar tu POKéDEX?$"

Text_ClosedLinkToProfOaksPC_ES::
	.string "Cerrado el enlace al PC del PROF.\n"
	.string "OAK.$"

Text_VoiceRangOutDontRunAway_ES::
	.string "Alguien ha dicho:\n"
	.string "“¡No huyas!”$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest_ES::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe_ES::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight_ES::
	.string "それっ　ちがうよー！$"

Text_ISee_ES::
	.string "そっか‥$"

Text_TheDoorIsClosed_ES::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen_ES::
	.string "La puerta está abierta...$"
