Text_OnlySkilledTrainersAllowedThrough_ES::
	.string "Sólo pueden pasar los\n"
	.string "ENTRENADORES expertos.\p"
	.string "¡Aún no tienes la {STR_VAR_1}!$"

Text_CantLetYouPass_ES::
	.string "Las reglas son las reglas.\n"
	.string "¡No puedes pasar!$"

Text_OhThatsBadgeGoRightAhead_ES::
	.string "¡Oh! ¡Ésa es la {STR_VAR_1}!\n"
	.string "¡Puedes pasar!$"

Text_OnlyPassWithBadgeDontHaveYet_ES::
	.string "¡Sólo podrás entrar aquí si tienes\n"
	.string "la {STR_VAR_1}!\p"
	.string "¡Aún no tienes la {STR_VAR_1}!\p"
	.string "¡Debes tenerla para acceder\n"
	.string "a la LIGA POKéMON!$"

Text_OnlyPassWithBadgeOhGoAhead_ES::
	.string "¡Sólo podrás entrar aquí si tienes\n"
	.string "la {STR_VAR_1}!\p"
	.string "¡Anda! ¡Ésa es la {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "¡Muy bien!\n"
	.string "¡Puedes pasar!$"
