Text_FirstShouldRestoreMonsHealth_ES::
	.string "Primero, deberías devolverles\n"
	.string "la forma a tus POKéMON.$"

Text_MonsHealedShouldBuyPotions_ES::
	.string "Tus POKéMON están de nuevo\n"
	.string "en forma.\p"
	.string "Ven a vernos cuando la energía\n"
	.string "de tus POKéMON, los PS, estén\l"
	.string "bajos de nivel.\p"
	.string "Cuando vayas a hacer un largo\n"
	.string "viaje, conviene que compres\l"
	.string "POCIONES en la TIENDA POKéMON.\p"
	.string "¡Demuestra lo que vales!$"

Text_MonsHealed_ES::
	.string "Tus POKéMON están de nuevo\n"
	.string "en forma.\p"
	.string "¡Esperamos que te vaya bien!$"

Text_HadQuiteAnExperienceTakeRest_ES::
	.string "MAMÁ: ¡{PLAYER}!\n"
	.string "¡Hola, cielo!\p"
	.string "¡Tienes cara de haber aprendido\n"
	.string "bastante!\p"
	.string "¡Descansa un poco, criatura!$"

Text_MomExplainHPGetPotions_ES::
	.string "MAMÁ: ¡Muy bien! ¡Tú y tus\n"
	.string "POKéMON estáis en plena forma!\p"
	.string "Me ha dicho el PROF. OAK que la\n"
	.string "energía de los POKéMON se mide\l"
	.string "por PS.\p"
	.string "Si tus POKéMON pierden los PS,\n"
	.string "puedes recuperarlos en cualquier\l"
	.string "CENTRO POKéMON.\p"
	.string "Para viajes largos, los ENTRENA-\n"
	.string "DORES más espabilados compran\p"
	.string "unas cuantas POCIONES en la\n"
	.string "TIENDA POKéMON.\p"
	.string "¡Demuestra a todos quien eres,\n"
	.string "cariño! ¡Cuídate mucho, tesoro!$"

Text_WhitedOutLostMoney_ES::
	.string "¡A {PLAYER} no le quedan\n"
	.string "más POKéMON!\p"
	.string "¡{PLAYER} se ha asustado\n"
	.string "y ha perdido {STR_VAR_1}¥!...\p"
	.string "... ... ... ...\p"
	.string "¡{PLAYER} está fuera de combate!$"

Text_WhitedOut_ES::
	.string "¡A {PLAYER} no le quedan\n"
	.string "más POKéMON!\p"
	.string "¡{PLAYER} está fuera de combate!$"
