
@ Unused, from R/S
Text_DoorOpenedFarAway_ES::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall_ES::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments_ES::
	.string "Lo siento, pero el CLUB\n"
	.string "INALÁMBRICO POKéMON no está\l"
	.string "disponible todavía.$"

Text_AppearsToBeUndergoingAdjustments_ES::
	.string "Se ve que están dándole\n"
	.string "los últimos retoques...$"

Text_HandedOverItem_ES::
	.string "¡{PLAYER} entregó\n"
	.string "{STR_VAR_1}!$"

Text_GiveNicknameToThisMon_ES::
	.string "¿Quieres darle un mote a tu\n"
	.string "{STR_VAR_1}?$"
