SixIsland_GreenPath_Text_JaclynIntro_DE::
	.string "… häh?\p"
	.string "Ich sah mein Haus, aber TELEPORT\n"
	.string "brachte mich hierher?$"

SixIsland_GreenPath_Text_JaclynDefeat_DE::
	.string "Jippie!$"

SixIsland_GreenPath_Text_JaclynPostBattle_DE::
	.string "Ich bin so kopflos!\p"
	.string "Ich muss mich konzentrieren, um\n"
	.string "mit TELEPORT zu meinem\l"
	.string "Haus zu gelangen!$"

SixIsland_GreenPath_Text_LeftRouteSign_DE::
	.string "GRÜNER PFAD\n"
	.string "MUSTERBUSCHWALD VORAUS$"

SixIsland_GreenPath_Text_RightRouteSign_DE::
	.string "GRÜNER PFAD\n"
	.string "Sei umweltbewusst!$"

