SixIsland_GreenPath_Text_JaclynIntro_FR::
	.string "… Quoi?\p"
	.string "Je voulais arriver chez moi, mais\n"
	.string "le TELEPORT m'a amenée ici.$"

SixIsland_GreenPath_Text_JaclynDefeat_FR::
	.string "Noooon!$"

SixIsland_GreenPath_Text_JaclynPostBattle_FR::
	.string "J'suis trop stressée du cerveau!\p"
	.string "Je dois me concentrer correctement\n"
	.string "pour me TELEPORTER chez moi.$"

SixIsland_GreenPath_Text_LeftRouteSign_FR::
	.string "CHEMIN VERT\n"
	.string "FORBUISSONS DROIT DEVANT$"

SixIsland_GreenPath_Text_RightRouteSign_FR::
	.string "CHEMIN VERT\n"
	.string "Respectez la nature!$"

