SixIsland_GreenPath_Text_JaclynIntro_IT::
    .string "Ma come?\p"
    .string "Volevo TELESTRASPORTarmi a casa,\n"
    .string "e sono finita qui?!$"

SixIsland_GreenPath_Text_JaclynDefeat_IT::
    .string "Buuu!!!$"

SixIsland_GreenPath_Text_JaclynPostBattle_IT::
    .string "Devo concentrarmi!\p"
    .string "Altrimenti non riuscirò mai a\n"
    .string "TELETRASPORTarmi a casa!$"

SixIsland_GreenPath_Text_LeftRouteSign_IT::
    .string "VIA VERDE\n"
    .string "Per il BOSCO DISEGNATO$"

SixIsland_GreenPath_Text_RightRouteSign_IT::
    .string "VIA VERDE\n"
    .string "Ambiente pulito, futuro garantito!$"

