FuchsiaCity_WardensHouse_Text_HifFuffHefifoo_ES::
    .string "GUARDA: ¡Fii, fuff, fefifu!\p"
    .string "A fof, a fif ee afahi fo.\n"
    .string "¡Eeff fi fui!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo_ES::
    .string "¡Ah fafee, oo foo!\n"
    .string "¡Eef ee afafi fo!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo_ES::
    .string "¿Ah?\n"
    .string "¡Fai fou fee, fa foo if afee!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden_ES::
    .string "¡{PLAYER} le dio los DIENTES\n"
    .string "de ORO al GUARDA!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth_ES::
    .string "¡El GUARDA se puso los dientes!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething_ES::
    .string "GUARDA: ¡Gracias, majo!\n"
    .string "¡Menos mal!\p"
    .string "No había quien me entendiera,\n"
    .string "vamos, ¡no me entendía ni yo!\p"
    .string "¡Me daba vergüenza hasta ir\n"
    .string "a trabajar!\p"
    .string "¡Te daré algo por las molestias!$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething_ES::
    .string "GUARDA: ¡Gracias, maja!\n"
    .string "¡Menos mal!\p"
    .string "No había quien me entendiera,\n"
    .string "vamos, ¡no me entendía ni yo!\p"
    .string "¡Me daba vergüenza hasta ir\n"
    .string "a trabajar!\p"
    .string "¡Te daré algo por las molestias!$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden_ES::
    .string "¡{PLAYER} recibió la MO04\n"
    .string "de manos del GUARDA!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength_ES::
    .string "GUARDA: ¡La MO04 enseña FUERZA!\p"
    .string "Tus POKéMON podrán mover rocas\n"
    .string "siempre que quieras.\p"
    .string "¿Encontraste la CASA SECRETA\n"
    .string "en la ZONA del SAFARI?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff_ES::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay_ES::
    .string "Fotos y fósiles de POKéMON.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay_ES::
    .string "¡Viejos objetos de los POKéMON!$"
