FuchsiaCity_WardensHouse_Text_HifFuffHefifoo_IT::
    .string "GUARDIANO: Fii fuf fefifu!\p"
    .string "A fof a fif ee afahi fo.\n"
    .string "Eeff fi fui!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo_IT::
    .string "Ah fafee oo foo!\n"
    .string "Eef ee afafi fo!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo_IT::
    .string "Ah?\n"
    .string "Fai fou fee fa foo if afee!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden_IT::
    .string "{PLAYER} dà i DENTI D'ORO al\n"
    .string "GUARDIANO!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth_IT::
    .string "Il GUARDIANO si mette i denti!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething_IT::
    .string "GUARDIANO: Grazie!\n"
    .string "Nessuno capiva niente di quello che\l"
    .string "dicevo.\p"
    .string "In quello stato non potevo\n"
    .string "lavorare.\p"
    .string "Ti darò qualcosa per ricompensarti!$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething_IT::
    .string "GUARDIANO: Grazie!\n"
    .string "Nessuno capiva niente di quello che\l"
    .string "dicevo.\p"
    .string "In quello stato non potevo\n"
    .string "lavorare.\p"
    .string "Ti darò qualcosa per ricompensarti!$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden_IT::
    .string "{PLAYER} riceve\n"
    .string "la MN04!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength_IT::
    .string "GUARDIANO: La MN04 insegna la\n"
    .string "FORZA!\p"
    .string "I tuoi POKéMON potranno muovere\n"
    .string "i massi fuori dalla lotta.\p"
    .string "Hai trovato la CASA SEGRETA in\n"
    .string "ZONA SAFARI?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff_IT::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay_IT::
    .string "Foto e fossili di POKéMON.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay_IT::
    .string "Vecchi oggetti POKéMON!$"

