FuchsiaCity_WardensHouse_Text_HifFuffHefifoo_FR::
	.string "GARDIEN: Hif fuff hefifou!\p"
	.string "Ha fof ha fif eu hafahi ho.\n"
	.string "Heff hi fwi!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo_FR::
	.string "Ah hahee ho hoo!\n"
	.string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo_FR::
	.string "Ha?\n"
	.string "Hai fou heh ha hoo ih haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden_FR::
	.string "{PLAYER} donne la DENT D'OR au\n"
	.string "GARDIEN!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth_FR::
	.string "Le GARDIEN peut remettre son\n"
	.string "dentier!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething_FR::
	.string "GARDIEN: Merci, gamin! C'était un\n"
	.string "peu dur de me faire comprendre.\p"
	.string "J'pouvais plus travailler!\n"
	.string "Quelle horreur!\p"
	.string "Tiens, voilà pour te remercier.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething_FR::
	.string "GARDIEN: Merci, gamine! C'était un\n"
	.string "peu dur de me faire comprendre.\p"
	.string "J'pouvais plus travailler!\n"
	.string "Quelle horreur!\p"
	.string "Tiens, voilà pour te remercier.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden_FR::
	.string "{PLAYER} reçoit la\n"
	.string "CS04!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength_FR::
	.string "GARDIEN: la CS04 contient FORCE!\p"
	.string "Tes POKéMON pourront déplacer des\n"
	.string "rochers.\p"
	.string "Au fait, as-tu trouvé la CABANE\n"
	.string "SECRETE dans le PARC SAFARI?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff_FR::
	.string "なんや　にもつ\n"
	.string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay_FR::
	.string "Photos et fossiles de POKéMON.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay_FR::
	.string "Tout plein de trucs POKéMON!$"

