SaffronCity_MrPsychicsHouse_Text_YouWantedThis_IT::
    .string "…Alt! Non dire una parola!\p"
    .string "Volevi questo!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic_IT::
    .string "{PLAYER} riceve\n"
    .string "la MT29!$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29_IT::
    .string "MT29 è PSICHICO.\p"
    .string "Riduce le statistiche SPECIALI\n"
    .string "dell'avversario!$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom_IT::
    .string "Non vedi che non hai spazio?$"

