RockTunnel_B1F_Text_SofiaIntro_ES::
    .string "Los montañeros marcan el camino\n"
    .string "con ramitas.\p"
    .string "Es la mejor forma de no perderse.$"

RockTunnel_B1F_Text_SofiaDefeat_ES::
    .string "¡Ohhh!\n"
    .string "¡He hecho todo lo posible!$"

RockTunnel_B1F_Text_SofiaPostBattle_ES::
    .string "¡Quiero volver a mi casa!$"

RockTunnel_B1F_Text_DudleyIntro_ES::
    .string "¡Ja, ja, ja!\n"
    .string "¿Crees que puedes ganarme?$"

RockTunnel_B1F_Text_DudleyDefeat_ES::
    .string "¡Vaya!\nQué ridículo...$"

RockTunnel_B1F_Text_DudleyPostBattle_ES::
    .string "¡Prefiero la fuerza, porque no\n"
    .string "me gusta pensar!$"

RockTunnel_B1F_Text_CooperIntro_ES::
    .string "¿Tienes una POKéDEX?\n"
    .string "¡Yo también quiero una!$"

RockTunnel_B1F_Text_CooperDefeat_ES::
    .string "¡Brgg!\n"
    .string "¡Me das tanta envidia!$"

RockTunnel_B1F_Text_CooperPostBattle_ES::
    .string "Cuando termines con tu POKéDEX\n"
    .string "¿me la dejarás?$"

RockTunnel_B1F_Text_SteveIntro_ES::
    .string "¿Qué sabes de esos jugadores\n"
    .string "disfrazados?$"

RockTunnel_B1F_Text_SteveDefeat_ES::
    .string "Pues eso es todo.$"

RockTunnel_B1F_Text_StevePostBattle_ES::
    .string "No hay nada como disfrazarse\n"
    .string "de POKéMON para divertirse.\p"
    .string "El mejor es CLEFAIRY.$"

RockTunnel_B1F_Text_AllenIntro_ES::
    .string "¡Mis técnicas de POKéMON te harán\n"
    .string "llorar!$"

RockTunnel_B1F_Text_AllenDefeat_ES::
    .string "¡Me rindo!\n"
    .string "¡Tus técnicas son mejores!$"

RockTunnel_B1F_Text_AllenPostBattle_ES::
    .string "En las montañas suele haber\n"
    .string "POKéMON del tipo ROCA.$"

RockTunnel_B1F_Text_MarthaIntro_ES::
    .string "¡No suelo venir por aquí, pero\n"
    .string "lucharé contigo!$"

RockTunnel_B1F_Text_MarthaDefeat_ES::
    .string "¡Oh! ¡He perdido!$"

RockTunnel_B1F_Text_MarthaPostBattle_ES::
    .string "¡Me gustan los POKéMON pequeños!\n"
    .string "¡Los grandes son horribles!$"

RockTunnel_B1F_Text_EricIntro_ES::
    .string "¡Lánzame tu mejor ataque!$"

RockTunnel_B1F_Text_EricDefeat_ES::
    .string "¡Vamos, adelante!$"

RockTunnel_B1F_Text_EricPostBattle_ES::
    .string "¡Criaré a mis POKéMON para que\n"
    .string "venzan a los tuyos!$"

RockTunnel_B1F_Text_WinstonIntro_ES::
    .string "Cuando estoy en casa, dibujo a los\n"
    .string "POKéMON.$"

RockTunnel_B1F_Text_WinstonDefeat_ES::
    .string "¡Uf!\n"
    .string "¡Estoy agotado!$"

RockTunnel_B1F_Text_WinstonPostBattle_ES::
    .string "Soy un artista, no un guerrero.$"
