RockTunnel_B1F_Text_SofiaIntro_IT::
    .string "Sai come si fa a non perdersi in\n"
    .string "montagna? Basta segnare il\l"
    .string "percorso con dei rametti!$"

RockTunnel_B1F_Text_SofiaDefeat_IT::
    .string "Oho!\n"
    .string "Ho fatto del mio meglio!$"

RockTunnel_B1F_Text_SofiaPostBattle_IT::
    .string "Voglio andare a casa mia!$"

RockTunnel_B1F_Text_DudleyIntro_IT::
    .string "Ahahah!\n"
    .string "Credi di potermi battere?$"

RockTunnel_B1F_Text_DudleyDefeat_IT::
    .string "Ups!\n"
    .string "Livello muscolare: zero!$"

RockTunnel_B1F_Text_DudleyPostBattle_IT::
    .string "Uso i muscoli perché odio pensare!$"

RockTunnel_B1F_Text_CooperIntro_IT::
    .string "Hai un POKéDEX?\n"
    .string "Ne voglio uno anch'io!$"

RockTunnel_B1F_Text_CooperDefeat_IT::
    .string "Grr!\n"
    .string "Crepo d'invidia!$"

RockTunnel_B1F_Text_CooperPostBattle_IT::
    .string "Quando hai completato il tuo\n"
    .string "POKéDEX, me lo daresti?$"

RockTunnel_B1F_Text_SteveIntro_IT::
    .string "Mai sentito dei giocatori in\n"
    .string "costume?$"

RockTunnel_B1F_Text_SteveDefeat_IT::
    .string "Bene, questo è quanto.$"

RockTunnel_B1F_Text_StevePostBattle_IT::
    .string "Ci sono persone che si travestono\n"
    .string "da POKéMON per divertimento.\p"
    .string "CLEFAIRY è la maschera preferita.$"

RockTunnel_B1F_Text_AllenIntro_IT::
    .string "Le mie tecniche POKéMON ti\n"
    .string "distruggeranno!$"

RockTunnel_B1F_Text_AllenDefeat_IT::
    .string "Mi arrendo!\n"
    .string "Le tue tecniche sono migliori!$"

RockTunnel_B1F_Text_AllenPostBattle_IT::
    .string "In montagna si trovano spesso\n"
    .string "POKéMON di tipo ROCCIA.$"

RockTunnel_B1F_Text_MarthaIntro_IT::
    .string "Non mi sento molto sicura, ma\n"
    .string "lotterò!$"

RockTunnel_B1F_Text_MarthaDefeat_IT::
    .string "Oh!\n"
    .string "Ho perso!$"

RockTunnel_B1F_Text_MarthaPostBattle_IT::
    .string "Mi piacciono i POKéMON piccoli,\n"
    .string "quelli grandi sono spaventosi!$"

RockTunnel_B1F_Text_EricIntro_IT::
    .string "Sferra il tuo attacco migliore!$"

RockTunnel_B1F_Text_EricDefeat_IT::
    .string "Bruciato in un soffio!$"

RockTunnel_B1F_Text_EricPostBattle_IT::
    .string "Allenerò i miei POKéMON per\n"
    .string "battere i tuoi!$"

RockTunnel_B1F_Text_WinstonIntro_IT::
    .string "Quando sono a casa disegno\n"
    .string "POKéMON.$"

RockTunnel_B1F_Text_WinstonDefeat_IT::
    .string "Uff!\n"
    .string "Che stanchezza!$"

RockTunnel_B1F_Text_WinstonPostBattle_IT::
    .string "Sono un artista, non un lottatore.$"

