RockTunnel_B1F_Text_SofiaIntro_DE::
	.string "Weißt du wie man es vermeidet,\n"
	.string "sich im Gebirge zu verlaufen?\p"
	.string "Wanderer knicken Zweige, um ihren\n"
	.string "Weg zu markieren.$"

RockTunnel_B1F_Text_SofiaDefeat_DE::
	.string "Ich habe mein Bestes gegeben!$"

RockTunnel_B1F_Text_SofiaPostBattle_DE::
	.string "Ich will nach Hause!$"

RockTunnel_B1F_Text_DudleyIntro_DE::
	.string "Haha!\n"
	.string "Kannst du mich besiegen?$"

RockTunnel_B1F_Text_DudleyDefeat_DE::
	.string "Hups!\n"
	.string "Das war zu viel des Guten!$"

RockTunnel_B1F_Text_DudleyPostBattle_DE::
	.string "Ich trainiere lieber meine Muskeln\n"
	.string "als mein Gehirn!!!$"

RockTunnel_B1F_Text_CooperIntro_DE::
	.string "Du besitzt einen POKéDEX? Cool!\n"
	.string "Ich möchte auch einen haben!$"

RockTunnel_B1F_Text_CooperDefeat_DE::
	.string "Ach, ich bin ja so neidisch!!!$"

RockTunnel_B1F_Text_CooperPostBattle_DE::
	.string "Gibst du mir den POKéDEX, wenn er\n"
	.string "fertig ist?$"

RockTunnel_B1F_Text_SteveIntro_DE::
	.string "Möchtest du etwas über Spaßvögel\n"
	.string "erfahren?$"

RockTunnel_B1F_Text_SteveDefeat_DE::
	.string "So weit, so gut.$"

RockTunnel_B1F_Text_StevePostBattle_DE::
	.string "Spaßvögel verkleiden sich gerne als\n"
	.string "POKéMON.\p"
	.string "Als PIEPI gehe ich am liebsten!$"

RockTunnel_B1F_Text_AllenIntro_DE::
	.string "Mein POKéMON wird dich das\n"
	.string "Fürchten lehren!$"

RockTunnel_B1F_Text_AllenDefeat_DE::
	.string "Ich gebe auf!\n"
	.string "Du bist besser!$"

RockTunnel_B1F_Text_AllenPostBattle_DE::
	.string "In den Bergen findet man viele\n"
	.string "STEIN-POKéMON.$"

RockTunnel_B1F_Text_MarthaIntro_DE::
	.string "Ich komme nicht oft hierher.\n"
	.string "Aber ich will kämpfen!$"

RockTunnel_B1F_Text_MarthaDefeat_DE::
	.string "Oh!\n"
	.string "Ich habe verloren!$"

RockTunnel_B1F_Text_MarthaPostBattle_DE::
	.string "Ich mag nur kleine POKéMON, die\n"
	.string "großen jagen mir Angst ein!$"

RockTunnel_B1F_Text_EricIntro_DE::
	.string "Zeig mir, was du drauf hast!$"

RockTunnel_B1F_Text_EricDefeat_DE::
	.string "Du bist gut!$"

RockTunnel_B1F_Text_EricPostBattle_DE::
	.string "Ich werde mit meinen POKéMON\n"
	.string "trainieren!$"

RockTunnel_B1F_Text_WinstonIntro_DE::
	.string "Zuhause zeichne ich gerne POKéMON.$"

RockTunnel_B1F_Text_WinstonDefeat_DE::
	.string "Ich bin erschöpft!$"

RockTunnel_B1F_Text_WinstonPostBattle_DE::
	.string "Ich liebe die Kunst, nicht den\n"
	.string "Kampf!$"

