CeladonCity_Condominiums_1F_Text_Meowth_DE::
	.string "MAUZI: Miau!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead_DE::
	.string "Du solltest dein ganzes Geld\n"
	.string "nicht für Getränke ausgeben!\p"
	.string "Versuch das hier!$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea_DE::
	.string "Gegen Durst ist nichts besser als\n"
	.string "heißer TEE.\p"
	.string "Er ist einfach am besten!$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany_DE::
	.string "Meine treuen POKéMON leisten mir\n"
	.string "Gesellschaft.\p"
	.string "MAUZI bringt sogar Geld mit nach\n"
	.string "Hause!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea_DE::
	.string "Oh, hallo!\n"
	.string "Hat dir mein TEE geschmeckt?\p"
	.string "Apropos, bist du zufällig aus\n"
	.string "ALABASTIA?\p"
	.string "Ein Mädchen aus ALABASTIA\n"
	.string "namens SARAH trinkt jeden Tag\l"
	.string "TEE.\l"
	.string "Sie kommt ins EINKAUFSZENTRUM\l"
	.string "von PRISMANIA CITY, um TEE\l"
	.string "zu kaufen!$"

CeladonCity_Condominiums_1F_Text_Clefairy_DE::
	.string "PIEPI: Pi pippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran_DE::
	.string "NIDORAN♀: NIDORAN!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite_DE::
	.string "PRISMANIA-VILLA\n"
	.string "Manager Suite$"

