CeladonCity_Condominiums_1F_Text_Meowth_IT::
    .string "MEOWTH: Miao!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead_IT::
    .string "Le bevande ghiacciate sono care,\n"
    .string "e non dissetano.\p"
    .string "Prova questo, invece!$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea_IT::
    .string "Quando si ha sete, non c'è niente\n"
    .string "di meglio di una tazza di TÈ\l"
    .string "bollente.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany_IT::
    .string "Il mio caro POKéMON mi fa\n"
    .string "compagnia!\p"
    .string "Pensa che MEOWTH contribuisce\n"
    .string "persino alle spese domestiche!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea_IT::
    .string "Ciao! Ti è piaciuto il TÈ?\p"
    .string "A proposito, vieni per caso da\n"
    .string "BIANCAVILLA?\p"
    .string "Conosci una certa MARGI?\p"
    .string "È di BIANCAVILLA e beve TÈ\n"
    .string "tutti i giorni.\p"
    .string "Va spesso a comprare TÈ\n"
    .string "al CENTRO COMMERCIALE\l"
    .string "di AZZURROPOLI.$"

CeladonCity_Condominiums_1F_Text_Clefairy_IT::
    .string "CLEFAIRY: Cle cleclecle!$"

CeladonCity_Condominiums_1F_Text_Nidoran_IT::
    .string "NIDORAN♀: Nidoor! Nidoorr!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite_IT::
    .string "VILLAZZURRA\n"
    .string "La suite presidenziale$"

