CeladonCity_Condominiums_1F_Text_Meowth_ES::
    .string "MEOWTH: ¡Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead_ES::
    .string "No deberías gastarte el dinero\n"
    .string "en latas.\p"
    .string "Toma, prueba esto.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea_ES::
    .string "No hay nada que calme la sed\n"
    .string "mejor que el TÉ.\p"
    .string "Es lo mejor que hay.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany_ES::
    .string "¡Mis queridos POKéMON me\n"
    .string "acompañan!\p"
    .string "¡Y MEOWTH hasta trae dinero a\n"
    .string "casa!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea_ES::
    .string "Hola, encanto.\n"
    .string "¿Te gustó el TÉ?\p"
    .string "Ah, te quería preguntar si eres\n"
    .string "de PUEBLO PALETA.\p"
    .string "Es que allí hay una chica, DALIA,\n"
    .string "que toma TÉ a diario.\p"
    .string "Suele comprarlo en el CENTRO\n"
    .string "COMERCIAL de AZULONA.$"

CeladonCity_Condominiums_1F_Text_Clefairy_ES::
    .string "CLEFAIRY: ¡Iry! ¡Cleclecle!$"

CeladonCity_Condominiums_1F_Text_Nidoran_ES::
    .string "NIDORAN♀: ¡Nidor! ¡Nidoorr!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite_ES::
    .string "MANSIÓN AZULONA\n"
    .string "Suite presidencial$"
