CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons_ES::
    .string "¡La POKé FLAUTA despierta a los\n"
    .string "POKéMON con un sonido que sólo\l"
    .string "ellos pueden oír!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia_ES::
    .string "¡He pedaleado cuesta arriba por el\n"
    .string "CAMINO de BICIS desde FUCSIA!\p"
    .string "¡Qué agotamiento!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike_ES::
    .string "¡Si tuviera una BICICLETA,\n"
    .string "iría por el CAMINO de BICIS!$"
