CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons_IT::
    .string "Il POKé FLAUTO sveglia i POKéMON\n"
    .string "con un suono che possono sentire\l"
    .string "solo loro!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia_IT::
    .string "Sono venuta da FUCSIAPOLI per la\n"
    .string "PISTA CICLABILE, che salita!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike_IT::
    .string "Se avessi una BICICLETTA\n"
    .string "andrei sulla PISTA CICLABILE!$"

