Aide_Text_HaventCaughtEnoughMonsForItem_IT::
	.string "Vediamo…\n"
	.string "Oh! Hai raccolto dati solo su\l{STR_VAR_3} specie di POKéMON!\p"
	.string "Ti servono {STR_VAR_1} specie, se vuoi\n"
	.string "{STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem_IT::
	.string "Oh! Allora…\p"
	.string "Quando avrai {STR_VAR_1} specie di POKéMON\n"
	.string "torna qui e ti darò {STR_VAR_2}\lin regalo!$"

Aide_Text_DontHaveAnyRoomForItem_IT::
	.string "Vedo che non hai più spazio per\n"
	.string "{STR_VAR_2}!$"
