Braille_Text_Up_IT::
	.braille "IN ALTO$"

Braille_Text_Down_IT::
	.braille "IN BASSO$"

Braille_Text_Right_IT::
	.braille "A DESTRA$"

Braille_Text_Left_IT::
	.braille "A SINISTRA$"

Braille_Text_Cut_IT::
	.braille "TAGLIO$"

Braille_Text_ABC_IT::
	.braille "ABC$"

Braille_Text_GHI_IT::
	.braille "GHI$"

Braille_Text_MNO_IT::
	.braille "MNO$"

Braille_Text_TUV_IT::
	.braille "TUV$"

Braille_Text_DEF_IT::
	.braille "DEF$"

Braille_Text_JKL_IT::
	.braille "JKL$"

Braille_Text_PQRS_IT::
	.braille "PQRS$"

Braille_Text_WXYZ_IT::
	.braille "WXYZ$"

Braille_Text_Period_IT::
	.braille ".$"

Braille_Text_Comma_IT::
	.braille "'$"

Braille_Text_Everything_IT::
	.braille "TUTTO$"

Braille_Text_HasMeaning1_IT::
	.braille "HA UN SENSO$"

Braille_Text_Existence_IT::
	.braille "LA VITA$"

Braille_Text_HasMeaning2_IT::
	.braille "HA UN SENSO$"

Braille_Text_BeingAlive_IT::
	.braille "ESSERE VIVI$"

Braille_Text_HasMeaning3_IT::
	.braille "HA UN SENSO$"

Braille_Text_HaveDreams_IT::
	.braille "SOGNA E USA$"

Braille_Text_UsePower_IT::
	.braille "LA TUA FORZA$"

Braille_Text_LetTheTwo_IT::
	.braille "LE DUE$"

Braille_Text_Glittering_IT::
	.braille "PIETRE$"

Braille_Text_Stones_IT::
	.braille "SCINTILLANTI$"

Braille_Text_OneInRed_IT::
	.braille "UNA ROSSA$"

Braille_Text_OneInBlue_IT::
	.braille "UNA BLU$"

Braille_Text_ConnectThe_IT::
	.braille "TI COLLEGANO$"

Braille_Text_Past_IT::
	.braille "AL PASSATO.$"

Braille_Text_TwoFriends_IT::
	.braille "DUE AMICI$"

Braille_Text_Sharing_IT::
	.braille "UNENDO LE$"

Braille_Text_PowerOpen_IT::
	.braille "FORZE APRONO$"

Braille_Text_AWindowTo_IT::
	.braille "UNA FINESTRA$"

Braille_Text_ANewWorld_IT::
	.braille "SU UN NUOVO$"

Braille_Text_ThatGlows_IT::
	.braille "MONDO.$"

Braille_Text_TheNext_IT::
	.braille "IL PROSSIMO$"

Braille_Text_WorldWaits_IT::
	.braille "MONDO$"

Braille_Text_ForYou_IT::
	.braille "TI ATTENDE.$"
