@ Unused
Text_WelcomeTradeCenter_IT::
    .string "Ti do il benvenuto al CENTRO\n"
    .string "SCAMBI del CLUB VIA CAVO POKéMON.$"

@ Unused
Text_WelcomeColosseum_IT::
    .string "Ti do il benvenuto al COLOSSEO del\n"
    .string "CLUB VIA CAVO POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule_IT::
    .string "Ti do il benvenuto alla\n"
    .string "TEMPOCAPSULA del CLUB VIA CAVO\lPOKéMON.$"

Text_PleaseComeAgain_IT::
    .string "Torna a trovarmi!$"

@ Unused
Text_HavingDiscountSaleToday_IT::
    .string "Salve!\p"
    .string "Oggi ci sono le offerte speciali!$"

@ Unused
Text_PlayerWhatCanIDoForYou_IT::
    .string "{PLAYER}{KUN}, salve!\p"
    .string "Che cosa posso fare per te?$"
