@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife_IT::
	.string "Sono il PADRONE della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Aiutiamo gli ALLENATORI a prendersi\n"
	.string "cura dei loro preziosi amici.\p"
	.string "Se vuoi che alleviamo anche i tuoi\n"
	.string "POKéMON, rivolgiti a mia moglie.$"

DayCare_Text_DoYouWantEgg_IT::
	.string "Ah, sei tu!\p"
	.string "Stavamo allevando i tuoi POKéMON\n"
	.string "e, mamma mia, che sorpresa!!!\p"
	.string "Hanno avuto un UOVO!\p"
	.string "Non sappiamo come sia finito lì, ma\n"
	.string "sta di fatto che c'è!\p"
	.string "Vuoi ritirarlo, vero?$"

DayCare_Text_YourMonIsDoingFine_IT::
	.string "Ah, sei tu! Hai fatto bene a\n"
	.string "passare. Il tuo {STR_VAR_1} sta\l"
	.string "crescendo bene.$"

DayCare_Text_IllKeepIt_IT::
	.string "Va bene, allora lo tengo io.\n"
	.string "Grazie!$"

DayCare_Text_YouHaveNoRoomForIt_IT::
	.string "La tua squadra è al completo…\n"
	.string "Torna quando hai un po' più di\l"
	.string "spazio.$"

DayCare_Text_ReceivedEgg_IT::
	.string "{PLAYER} riceve l'UOVO dalla\n"
	.string "PENSIONE POKéMON.$"

DayCare_Text_TakeGoodCareOfIt_IT::
	.string "Abbine cura!$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon_IT::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine_IT::
	.string "Ah, sei tu! I tuoi {STR_VAR_1} e\n"
	.string "{STR_VAR_2} stanno crescendo bene.$"

DayCare_Text_IWillKeepDoYouWantIt_IT::
	.string "Vorrei tenerlo io.\n"
	.string "Ma tu lo rivuoi indietro, vero?$"

DayCare_Text_WouldYouLikeUsToRaiseMon_IT::
	.string "Sono la PADRONA della PENSIONE\n"
	.string "POKéMON.\p"
	.string "Possiamo allevare i tuoi POKéMON!\p"
	.string "Vuoi affidarcene uno?$"

DayCare_Text_WhichMonShouldWeRaise_IT::
	.string "Che POKéMON vuoi che alleviamo?$"

DayCare_Text_WellRaiseYourMon_IT::
	.string "Perfetto, alleveremo il tuo\n"
	.string "{STR_VAR_1} per un po'.\p"
	.string "Torna a prenderlo più tardi.$"

DayCare_Text_WeCanRaiseOneMore_IT::
	.string "Possiamo allevare due dei tuoi\n"
	.string "POKéMON. Vuoi lasciarcene un\l"
	.string "altro?$"

DayCare_Text_HusbandWasLookingForYou_IT::
	.string "Mio marito ti stava cercando.$"

DayCare_Text_FineThenComeAgain_IT::
	.string "Oh, come vuoi.\n"
	.string "Torna a trovarci.$"

DayCare_Text_NotEnoughMoney_IT::
	.string "Non hai abbastanza soldi…$"

DayCare_Text_TakeOtherOneBackToo_IT::
	.string "Vuoi ritirare anche l'altro?$"

DayCare_Text_ComeAgain_IT::
	.string "Va bene.\n"
	.string "Torna quando vuoi.$"

DayCare_Text_GoodToSeeYou_IT::
	.string "Ah, sei tu! Hai fatto bene a\n"
	.string "passare. Stiamo ottenendo ottimi\l"
	.string "risultati!$"

DayCare_Text_YourMonHasGrownXLevels_IT::
	.string "Il livello del tuo {STR_VAR_1} è\n"
	.string "cresciuto di {STR_VAR_2}!$"

DayCare_Text_YourPartyIsFull_IT::
	.string "La tua squadra POKéMON è\n"
	.string "completa. Torna quando hai qualche\l"
	.string "posto libero.$"

DayCare_Text_TakeBackWhichMon_IT::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX_IT::
	.string "Per ritirare il tuo {STR_VAR_1},\n"
	.string "devi pagare ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon_IT::
	.string "Perfetto!\n"
	.string "Eccoti il POKéMON.$"

DayCare_Text_TookBackMon_IT::
	.string "{PLAYER} ritira {STR_VAR_1} dalla\n"
	.string "PENSIONE POKéMON.$"

DayCare_Text_YouHaveJustOneMon_IT::
	.string "Eh? Ma tu hai soltanto un POKéMON.\p"
	.string "Torna un'altra volta.$"

DayCare_Text_TakeYourMonBack_IT::
	.string "Sei qui per ritirare un POKéMON?$"

DayCare_Text_WhatWillYouBattleWith_IT::
	.string "Se mi affidi quel POKéMON,\n"
	.string "non potrai più lottare.\p"
	.string "Torna un'altra volta.$"

DayCare_Text_Huh_IT::
	.string "Eh?$"
