Text_CutTreeDown_IT::
    .string "L'albero si può abbattere con\n"
    .string "TAGLIO.\p"
    .string "Vuoi usare TAGLIO?$"

Text_MonUsedMove_IT::
    .string "{STR_VAR_1} usa {STR_VAR_2}.$"

Text_TreeCanBeCutDown_IT::
    .string "L'albero si può abbattere con\n"
    .string "TAGLIO.$"

Text_UseRockSmash_IT::
    .string "Questa roccia si può frantumare.\n"
    .string "Vuoi usare SPACCAROCCIA?$"

Text_MonMaySmashRock_IT::
    .string "È una roccia dura, ma un POKéMON\n"
    .string "dovrebbe poterla frantumare.$"

Text_UseStrength_IT::
    .string "È un masso enorme, ma un POKéMON\n"
    .string "dovrebbe poterlo spostare.\p"
    .string "Vuoi usare FORZA?$"

Text_MonUsedStrengthCanMoveBoulders_IT::
    .string "{STR_VAR_1} usa FORZA.\p"
    .string "La FORZA di {STR_VAR_1} riesce a\n"
    .string "spostare i massi.$"

Text_MonMayPushBoulder_IT::
    .string "È un masso enorme, ma un POKéMON\n"
    .string "dovrebbe poterlo spostare.$"

Text_StrengthMadeMovingBouldersPossible_IT::
    .string "FORZA ha reso possibile spostare\n"
    .string "i massi.$"

Text_WallOfWaterCrashingDown_IT::
    .string "Una parete d'acqua che si schianta\n"
    .string "con un potente fragore…$"

Text_UseWaterfall_IT::
    .string "C'è un'enorme cascata.\n"
    .string "Vuoi usare CASCATA?$"

Text_MonUsedWaterfall_IT::
    .string "{STR_VAR_1} usa CASCATA.$"

Text_MonMayGoUnderwater_IT::
    .string "Il mare è profondo qui. Ci si\n"
    .string "potrebbe immergere anche un\l"
    .string "POKéMON.$"

Text_SeaIsDeepUseDive_IT::
    .string "Il mare è profondo qui.\n"
    .string "Vuoi usare SUB?$"

Text_MonUsedDive_IT::
    .string "{STR_VAR_1} usa SUB.$"

Text_MonMaySurface_IT::
    .string "Una luce illumina l'acqua dall'alto.\n"
    .string "Da qui un POKéMON potrebbe\l"
    .string "riemergere.$"

Text_LightFilteringUseDive_IT::
    .string "Una luce illumina l'acqua dall'alto.\n"
    .string "Vuoi usare SUB?$"

Text_DiveCantBeUsedHere_IT::
    .string "C'è qualcosa che blocca in\n"
    .string "superficie. Non puoi usare SUB qui.$"

Text_LooksLikeNothingHere_IT::
    .string "Pare non ci sia nulla qui…$"
