@ Flavor text for interacting with various background objects

Text_Bookshelf_IT::
	.string "Pieno zeppo di libri POKéMON!$"

Text_NothingButPokemonBooks_IT::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap_IT::
	.string "Una MAPPA CITTÀ.$"

Text_PokeMartShelf_IT::
	.string "Wow!\n"
	.string "Montagne di oggetti POKéMON!$"

Text_DishesPlatesNeatlyLinedUp_IT::
	.string "Ci sono piatti e vassoi in perfetto\n"
	.string "ordine.$"

Text_Kitchen_IT::
	.string "Che profumino… C'è qualcosa sul\n"
	.string "fuoco…$"

Text_Dresser_IT::
	.string "È una bella credenza. Sembra\n"
	.string "molto capiente.$"

Text_Snacks_IT::
	.string "Ci sono parecchi snack.$"

Text_PokemartSign_IT::
	.string "Abbiamo tutti gli strumenti per te!\n"
	.string "POKéMON-MARKET$"

Text_PokecenterSign_IT::
	.string "Rimetti in sesto i tuoi POKéMON!\n"
	.string "CENTRO POKéMON$"

Text_Indigo_UltimateGoal_IT::
	.string "ALTOPIANO BLU\p"
	.string "La grande meta degli ALLENATORI!\n"
	.string "SEDE CENTRALE LEGA POKéMON.$"

Text_Indigo_HighestAuthority_IT::
	.string "ALTOPIANO BLU\p"
	.string "La massima autorità POKéMON:\n"
	.string "SEDE CENTRALE LEGA POKéMON.$"

Text_Food_IT::
	.string "Dev'essere pieno di cibi\n"
	.string "deliziosi.$"

Text_Blueprints_IT::
	.string "Sembra un progetto. Le pagine sono\n"
	.string "piene di testi e diagrammi.$"

Text_Painting_IT::
	.string "È una bella immagine di un\n"
	.string "POKéMON. Sembra contento.$"

Text_PowerPlantMachine_IT::
	.string "Uno strano macchinario. Meglio\n"
	.string "stargli alla larga…$"

Text_Telephone_IT::
	.string "È un telefono. Meglio non usarlo…$"

Text_Computer_IT::
	.string "È pieno di parole e numeri\n"
	.string "incomprensibili…$"

Text_AdvertisingPoster_IT::
	.string "È un cartellone pubblicitario con\n"
	.string "prodotti di ogni tipo.$"

Text_TastyFood_IT::
	.string "Che profumino!\n"
	.string "Fa venire l'acquolina in bocca!$"

Text_TrashBin_IT::
	.string "Qui dentro…\n"
	.string "……\p"
	.string "…non c'è niente!$"

Text_Cup_IT::
	.string "È una tazza con un POKéMON\n"
	.string "disegnato.$"

Text_PolishedWindow_IT::
	.string "I vetri della finestra sembrano\n"
	.string "appena stati lavati.$"

Text_BeautifulSkyWindow_IT::
	.string "Dalla finestra…\p"
	.string "…si vede un cielo terso,\n"
	.string "magnifico.$"

Text_BlinkingLights_IT::
	.string "Ci sono luci lampeggianti di vario\n"
	.string "colore.$"

Text_NeatlyLinedUpTools_IT::
	.string "Vi sono oggetti di ogni tipo.$"

Text_ImpressiveMachine_IT::
	.string "È uno strano macchinario,\n"
	.string "impressionante.$"

Text_VideoGame_IT::
	.string "È un videogioco appena uscito.\n"
	.string "Dev'essere divertente!$"

Text_Burglary_IT::
	.string "I ladri hanno lasciato chiari segni\n"
	.string "del loro passaggio.$"

Text_PlayerFacingTVScreen_IT::
	.string "C'è un POKéMON in TV! Sembra\n"
	.string "divertirsi un mondo!$"

