Trade_Text_LookingForMonWannaTradeForMon_IT::
	.string "Cerco {STR_VAR_1}!\n"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"

Trade_Text_AwwOhWell_IT::
	.string "Oh!\n"
	.string "Vabbè!$"

Trade_Text_WhatThatsNoMon_IT::
	.string "Questo non è {STR_VAR_1}!$"

Trade_Text_HeyThanks_IT::
	.string "Grazie mille!$"

Trade_Text_IsntMyOldMonGreat_IT::
	.string "Visto com'è forte il mio vecchio\n"
	.string "{STR_VAR_2}?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon_IT::
	.string "Ciao! Vuoi scambiare il tuo\n"
	.string "{STR_VAR_1} con {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo_IT::
	.string "Vabbè! Se non vuoi…$"

Trade_Text_ThisIsntMon_IT::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno torna a\n"
	.string "trovarmi!$"

Trade_Text_Thanks_IT::
	.string "Grazie!$"

Trade_Text_HasTradedMonGrownStronger_IT::
	.string "Come sta l'esemplare di\n"
	.string "{STR_VAR_2} che ti ho dato nello\lscambio? Si è rafforzato?$"

Trade_Text_DoYouHaveMonWantToTradeForMon_IT::
	.string "Ciao!\n"
	.string "Hai {STR_VAR_1}?\p"
	.string "Vuoi scambiarlo con {STR_VAR_2}?$"

Trade_Text_ThatsTooBad_IT::
	.string "Che sfortuna!$"

Trade_Text_ThisIsNoMon_IT::
	.string "Questo non è {STR_VAR_1}.\p"
	.string "Quando ne hai uno, scambialo con\n"
	.string "me!$"

Trade_Text_ThanksYoureAPal_IT::
	.string "Grazie mille!$"

Trade_Text_HowIsMyOldMon_IT::
	.string "Come sta il mio vecchio\n"
	.string "{STR_VAR_2}?\p"
	.string "Il mio caro {STR_VAR_1} sta\n"
	.string "divinamente!$"
