Text_IdLoveToHearYourProfile_IT::
    .string "Ciao, che piacere vederti!\p"
    .string "…Beh, potresti almeno\n"
    .string "salutare!\p"
    .string "Dimmi qualcosa di te!\p"
    .string "Mi piacerebbe conoscere il tuo\n"
    .string "profilo.$"

Text_TellMeWhatsYourProfile_IT::
    .string "Dimmi qualcosa di te!\n"
    .string "Qual è il tuo profilo?$"

Text_ExplainProfile_IT::
    .string "Il profilo è composto da quattro\n"
    .string "parole o espressioni.\p"
    .string "Per crearlo, devi combinare le\n"
    .string "parole e le espressioni che trovi\l"
    .string "nella lista sotto varie categorie.\p"
    .string "Scegli una categoria, poi\n"
    .string "seleziona una parola o\l"
    .string "un'espressione al suo interno.\p"
    .string "Prova! È più facile a dirsi\n"
    .string "che a farsi!$"

Text_WhatsYourProfile_IT::
    .string "Qual è il tuo profilo?$"

Text_DontBeLikeThat_IT::
    .string "Non fare così…\n"
    .string "Dimmi il tuo profilo, dai!$"

Text_DecidedNotTo_IT::
    .string "Ah, hai cambiato idea?\n"
    .string "Beh, deciditi…$"

Text_HiWeMeetAgain_IT::
    .string "Ehi, ci si rincontra!$"

Text_ChangeYourProfile_IT::
    .string "Vuoi cambiare il tuo profilo?$"

Text_WhatAreYouLikeNow_IT::
    .string "Qual è il tuo profilo attuale?$"

Text_LikeProfileWayItIs_IT::
    .string "Ah, quindi il tuo profilo ti piace\n"
    .string "così com'è… \p"
    .string "Anche secondo me non è male.$"

Text_ProfileSaysSomethingAboutYou_IT::
    .string "Hmhm…\p"
    .string "Il tuo profilo parla un po'\n"
    .string "di te.\p"
    .string "E ora che ti ho conosciuto\n"
    .string "meglio, possiamo diventare\l"
    .string "grandi amici!$"

Text_HeardThatBefore_IT::
    .string "L'ho già sentito dire…\p"
    .string "Mi sembra che lo dicesse sempre\n"
    .string "mio cugino, che abita lontano.$"

Text_TellMoreNextTime_IT::
    .string "La prossima volta mi dirai\n"
    .string "qualcos'altro di te, OK?$"
