gOtherText_NewName_IT::
	.string "NUOVO$"

gNameChoice_Green_IT::
	.string "VERDE$"

gNameChoice_Red_IT::
	.string "ROSSO$"

gNameChoice_Leaf_IT::
	.string "GREEN$"

gNameChoice_Fire_IT::
	.string "RED$"

gNameChoice_Gary_IT::
	.string "GARY$"

gNameChoice_Kaz_IT::
	.string "DAMIANO$"

gNameChoice_Toru_IT::
	.string "FABIO$"

gNameChoice_Ash_IT::
	.string "ASH$"

gNameChoice_Kene_IT::
	.string "DIMITRI$"

gNameChoice_Geki_IT::
	.string "ATTILIO$"

gNameChoice_Jak_IT::
	.string "MATTIA$"

gNameChoice_Janne_IT::
	.string "SILVANO$"

gNameChoice_Jonn_IT::
	.string "LUCIO$"

gNameChoice_Kamon_IT::
	.string "KAMON$"

gNameChoice_Karl_IT::
	.string "KARL$"

gNameChoice_Taylor_IT::
	.string "GABRY$"

gNameChoice_Oscar_IT::
	.string "OSCAR$"

gNameChoice_Hiro_IT::
	.string "DINO$"

gNameChoice_Max_IT::
	.string "DANIEL$"

gNameChoice_Jon_IT::
	.string "MANUELE$"

gNameChoice_Ralph_IT::
	.string "RALPH$"

gNameChoice_Kay_IT::
	.string "IVANO$"

gNameChoice_Tosh_IT::
	.string "PAOLO$"

gNameChoice_Roak_IT::
	.string "ENZO$"

gNameChoice_Omi_IT::
	.string "CINZIA$"

gNameChoice_Jodi_IT::
	.string "LUISA$"

gNameChoice_Amanda_IT::
	.string "AMANDA$"

gNameChoice_Hillary_IT::
	.string "ROSSANA$"

gNameChoice_Makey_IT::
	.string "RITA$"

gNameChoice_Michi_IT::
	.string "LORENZA$"

gNameChoice_Paula_IT::
	.string "PAOLA$"

gNameChoice_June_IT::
	.string "GAIA$"

gNameChoice_Cassie_IT::
	.string "OLGA$"

gNameChoice_Rey_IT::
	.string "WILMA$"

gNameChoice_Seda_IT::
	.string "IVANA$"

gNameChoice_Kiko_IT::
	.string "MONIA$"

gNameChoice_Mina_IT::
	.string "LETIZIA$"

gNameChoice_Norie_IT::
	.string "LILIANA$"

gNameChoice_Sai_IT::
	.string "ILARIA$"

gNameChoice_Momo_IT::
	.string "ISOTTA$"

gNameChoice_Suzi_IT::
	.string "VIVIANA$"

gControlsGuide_Text_Intro_IT::
	.string "Prima di iniziare, ecco una breve\n"
	.string "spiegazione dei comandi di gioco.$"

gControlsGuide_Text_DPad_IT::
	.string "Per spostare il personaggio\n"
	.string "nel gioco e per scegliere tra le\n"
	.string "varie opzioni dei menu.$"

gControlsGuide_Text_AButton_IT::
	.string "Per confermare le selezioni,\n"
	.string "parlare e far scorrere il testo.$"

gControlsGuide_Text_BButton_IT::
	.string "Per uscire da un menu, annullare\n"
	.string "una scelta o una modalità.$"

gControlsGuide_Text_StartButton_IT::
	.string "Per aprire il MENU.$"

gControlsGuide_Text_SelectButton_IT::
	.string "Per spostare strumenti e usare\n"
	.string "quello assegnato a SELECT.$"

gControlsGuide_Text_LRButtons_IT::
	.string "Premi il pulsante L o R per\n"
	.string "richiamare la GUIDA nel gioco.$"

gOakSpeech_Text_AskPlayerGender_IT::
	.string "Dimmi un po': sei un bimbo\n"
	.string "o una bimba?$"

gPikachuIntro_Text_Page1_IT::
	.string "Stai per diventare il personaggio\n"
	.string "principale di una grande avventura\n"
	.string "nel mondo dei POKéMON!\n"
	.string "\n"
	.string "Sul tuo cammino, controlla gli oggetti\n"
	.string "e parla con tutte le persone che\n"
	.string "incontri, raccogliendo più informazioni\n"
	.string "possibile.$"

gPikachuIntro_Text_Page2_IT::
	.string "Aiutando chi è in difficoltà, superando\n"
	.string "sfide e risolvendo misteri ti si\n"
	.string "apriranno nuove strade.\n"
	.string "\n"
	.string "Sfidando tutti gli ALLENATORI e i\n"
	.string "POKéMON che incontrerai, la tua\n"
	.string "squadra diventerà sempre più forte!$"

gPikachuIntro_Text_Page3_IT::
	.string "Ci auguriamo che questo gioco ti aiuti\n"
	.string "a comunicare con tante persone e che\n"
	.string "sia per te un'esperienza importante.\n"
	.string "È questo il nostro più grande obiettivo.\n"
	.string "\n"
	.string "Ora, premi il pulsante A e dai inizio\n"
	.string "alla tua grande avventura!$"

gOakSpeech_Text_WelcomeToTheWorld_IT::
	.string "Ciao!\n"
	.string "Ti trovi nel mondo dei POKéMON!\p"
	.string "Mi chiamo OAK!\p"
	.string "Tutti mi conoscono come il\n"
	.string "PROFESSORE dei POKéMON!\p"
	.string "$"

gOakSpeech_Text_ThisWorld_IT::
	.string "Questo mondo…$"

gOakSpeech_Text_IsInhabitedFarAndWide_IT::
	.string "…è abitato da creature chiamate\n"
	.string "POKéMON!\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon_IT::
	.string "Per alcuni i POKéMON sono piccoli\n"
	.string "amici, altri li usano per lottare.\p"
	.string "In quanto a me…\p"
	.string "…lo studio dei POKéMON è il mio\n"
	.string "lavoro.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself_IT::
	.string "Prima di tutto, parlami un po'\n"
	.string "di te!\l"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt_IT::
	.string "Dimmi come ti chiami.\p"
	.string "\n"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer_IT::
	.string "Bene…\n"
	.string "Allora ti chiami {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName_IT::
	.string "Questo è mio nipote. È da sempre\n"
	.string "il tuo rivale.\p"
	.string "…Mmm, potresti ricordarmi come\n"
	.string "si chiama?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt_IT::
	.string "Si chiama…$"

gOakSpeech_Text_ConfirmRivalName_IT::
	.string "…{RIVAL}, per caso?$"

gOakSpeech_Text_RememberRivalsName_IT::
	.string "Sì, sì! Ora ricordo!\n"
	.string "Si chiama {RIVAL}!\p"
	.string "$"

gOakSpeech_Text_LetsGo_IT::
	.string "{PLAYER}!\p"
	.string "Stai per essere protagonista di\n"
	.string "una grande storia nel mondo dei\l"
	.string "POKéMON!\p"
	.string "Andiamo! Ti aspetta un mondo di\n"
	.string "sogni e avventure!$"
