Text_ObtainedTheX_IT::
    .string "Hai ottenuto {STR_VAR_2}!$"

Text_BagIsFull_IT::
    .string "Lo ZAINO è pieno…$"

Text_PutItemAway_IT::
    .string "Strumento sistemato nello scomparto\n"
    .string "{STR_VAR_3} dello ZAINO.$"

Text_FoundOneItem_IT::
    .string "{PLAYER} trova {STR_VAR_2}!{PAUSE 64}$"

Text_TooBadBagFull_IT::
    .string "Che peccato!\n"
    .string "Hai lo ZAINO troppo pieno…$"

Text_FoundXCoins_IT::
    .string "{PLAYER} trova\n"
    .string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase_IT::
    .string "{PLAYER} mette via i GETTONI\n"
    .string "nel SALVADANAIO.$"

Text_CoinCaseIsFull_IT::
    .string "Che peccato!\n"
    .string "Il tuo SALVADANAIO è pieno!$"

Text_NothingToPutThemIn_IT::
    .string "Che peccato!\n"
    .string "Non hai un contenitore in cui\lraccoglierli!$"

Text_FoundXItems_IT::
    .string "{PLAYER} ha trovato {STR_VAR_1} unità\n"
    .string "di {STR_VAR_2}!$"

Text_ObtainedTheDecor_IT::
    .string "Hai ottenuto {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor_IT::
    .string "Non hai spazio per {STR_VAR_2}? \n"
    .string "È un peccato…$"

Text_DecorTransferredToPC_IT::
    .string "{STR_VAR_2} è nel tuo PC.$"
