Text_BootedUpPC_IT::
    .string "{PLAYER} accende il PC.$"

Text_AccessWhichPC_IT::
    .string "A quale PC vuoi accedere?$"

Text_AccessedSomeonesPC_IT::
    .string "Accesso al PC di ???.$"

Text_OpenedPkmnStorage_IT::
    .string "Sistema Memoria POKéMON aperto.$"

Text_AccessedPlayersPC_IT::
    .string "Accesso al PC di {PLAYER}.$"

Text_AccessedBillsPC_IT::
    .string "Accesso al PC di BILL.$"
