Text_MonSentToBoxInSomeonesPC_IT::
	.string "{STR_VAR_2} è stato trasferito\n"
	.string "al PC di ???.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxInBillsPC_IT::
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "PC di BILL.\p"
	.string "È nel BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxSomeonesBoxFull_IT::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di ??? è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"

Text_MonSentToBoxBillsBoxFull_IT::
	.string "Il BOX chiamato “{STR_VAR_3}” nel\n"
	.string "PC di BILL è pieno.\p"
	.string "{STR_VAR_2} è stato inviato al\n"
	.string "BOX chiamato “{STR_VAR_1}”.$"

Text_PlayerObtainedTheMon_IT::
	.string "{PLAYER} riceve\n"
	.string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC_IT::
	.string "ポケモンを　もちきれないので\n"
	.string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
	.string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon_IT::
	.string "Non c'è spazio per altri POKéMON!\n"
	.string "I BOX POKéMON sono pieni!$"
