Pokedude_Text_SpeedierBattlerGoesFirst_IT::
	.string "GUIDO: L'avversario\n"
	.string "più veloce attacca per primo.$"

Pokedude_Text_MyRattataFasterThanPidgey_IT::
	.string "Pare che il mio RATTATA sia\n"
	.string "stato più rapido del PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking_IT::
	.string "A turno, i contendenti si attaccano\n"
	.string "cercando di ridurre i PS\l"
	.string "del nemico.$"

Pokedude_Text_MyRattataWonGetsEXP_IT::
	.string "Visto? Il mio RATTATA è riuscito\n"
	.string "a ridurre a zero i PS\l"
	.string "dell'avversario, vincendo!\p"
	.string "I POKéMON che hanno preso parte\n"
	.string "alla lotta guadagnano punti ESP.\p"
	.string "Dopo aver ottenuto un numero\n"
	.string "sufficiente di punti ESP., il\l"
	.string "POKéMON sale di un livello.\p"
	.string "Crescere di livello rende i vostri\n"
	.string "POKéMON più forti!$"

Pokedude_Text_UhOhRattataPoisoned_IT::
	.string "GUIDO: Il mio RATTATA è stato\n"
	.string "avvelenato!\p"
	.string "Un POKéMON avvelenato perde\n"
	.string "costantemente PS.$"

Pokedude_Text_HealStatusRightAway_IT::
	.string "Cercate sempre di risolvere\n"
	.string "immediatamente i problemi di stato\l"
	.string "dei vostri POKéMON!$"

Pokedude_Text_UsingItemTakesTurn_IT::
	.string "Tuttavia, per l'uso di uno\n"
	.string "strumento su un proprio\l"
	.string "POKéMON si utilizza un turno.\p"
	.string "Ora, è il turno dell'avversario.$"

Pokedude_Text_YayWeManagedToWin_IT::
	.string "Wow!\n"
	.string "Abbiamo vinto!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass_IT::
	.string "GUIDO: BOLLA è una mossa di tipo\n"
	.string "ACQUA.\p"
	.string "ODDISH è un POKéMON di tipo\n"
	.string "ERBA/VELENO.\p"
	.string "L'attacco di tipo ACQUA è\n"
	.string "attutito dal tipo ERBA del\l"
	.string "POKéMON.\p"
	.string "Così, la mossa diventa non molto\n"
	.string "efficace e arreca solo metà del\l"
	.string "danno normale.$"

Pokedude_Text_GrassEffectiveAgainstWater_IT::
	.string "Questo fa male!\p"
	.string "L'attacco che avete appena visto\n"
	.string "è ASSORBIMENTO, di tipo ERBA.\p"
	.string "POLIWAG è un POKéMON di tipo\n"
	.string "ACQUA.\p"
	.string "Così, ASSORBIMENTO diventa\n"
	.string "superefficace, arrecando danno\l"
	.string "doppio.$"

Pokedude_Text_LetsTryShiftingMons_IT::
	.string "Non è facile vincere con una\n"
	.string "combinazione così negativa.\p"
	.string "Meglio sostituire il POKéMON.$"

Pokedude_Text_ShiftingUsesTurn_IT::
	.string "Per la sostituzione di un POKéMON\n"
	.string "si utilizza un turno.\p"
	.string "Ora è il turno dell'avversario!$"

Pokedude_Text_ButterfreeDoubleResistsGrass_IT::
	.string "BUTTERFREE è un POKéMON di tipo\n"
	.string "COLEOTTERO/VOLANTE.\p"
	.string "Contro un POKéMON COLEOTTERO,\n"
	.string "un attacco di tipo ERBA causa\l"
	.string "solo 1/2 del danno normale.\p"
	.string "Anche contro un POKéMON di tipo\n"
	.string "VOLANTE, un attacco di tipo ERBA\l"
	.string "provoca solo 1/2 del danno.\p"
	.string "Quindi BUTTERFREE di tipo\n"
	.string "COLEOTTERO/VOLANTE, subisce\l"
	.string "solo 1/4 del danno normale!$"

Pokedude_Text_ButterfreeGoodAgainstOddish_IT::
	.string "ODDISH è un POKéMON di tipo\n"
	.string "ERBA/VELENO.\p"
	.string "Contro di lui, un attacco di tipo\n"
	.string "VOLANTE o PSICO è\l"
	.string "superefficace.\p"
	.string "Quindi, un attacco di uno di questi\n"
	.string "due tipi infligge il doppio del\l"
	.string "danno normale.\p"
	.string "Ecco qui!$"

Pokedude_Text_YeahWeWon_IT::
	.string "Grandioso!\n"
	.string "Abbiamo vinto!$"

Pokedude_Text_WeakenMonBeforeCatching_IT::
	.string "GUIDO: Quando volete catturare un\n"
	.string "POKéMON, non vi conviene lanciare\l"
	.string "immediatamente una POKé BALL.\p"
	.string "Prima, cercate di indebolirlo\n"
	.string "riducendo i suoi PS.$"

Pokedude_Text_BestIfTargetStatused_IT::
	.string "Ancora meglio se il POKéMON che\n"
	.string "volete catturare ha un problema\l"
	.string "di stato.\p"
	.string "Per esempio, un POKéMON\n"
	.string "addormentato o paralizzato è più\l"
	.string "facilmente catturabile.$"

Pokedude_Text_CantDoubleUpOnStatus_IT::
	.string "Ricordate, però: i problemi di\n"
	.string "stato non si possono accumulare.\p"
	.string "Non potete far addormentare un\n"
	.string "POKéMON che è già paralizzato,\l"
	.string "per esempio.$"

Pokedude_Text_LetMeThrowBall_IT::
	.string "Bene!\n"
	.string "Ora tiro la mia bella POKé BALL!$"

Pokedude_Text_PickBestKindOfBall_IT::
	.string "Ci sono diversi tipi di POKé BALL.\p"
	.string "Cercate sempre di usare quella più\n"
	.string "adatta alle condizioni e al\l"
	.string "tipo del POKéMON avversario.$"
