Text_CardKeyOpenedDoor_IT::
	.string "Evviva!\n"
	.string "L'APRIPORTA ha funzionato!$"

Text_ItNeedsCardKey_IT::
	.string "Oh, no!\n"
	.string "Ci vuole l'APRIPORTA!$"

Text_AccessedProfOaksPC_IT::
	.string "Accesso al PC del PROF. OAK.\p"
	.string "Accesso al Sistema Valutazione\n"
	.string "POKéDEX.$"

Text_HavePokedexRated_IT::
	.string "Vuoi far valutare il tuo POKéDEX?$"

Text_ClosedLinkToProfOaksPC_IT::
	.string "Fine collegamento con il PC del\n"
	.string "PROF. OAK.$"

Text_VoiceRangOutDontRunAway_IT::
	.string "Si sente una voce:\n"
	.string "“Non scappare!”.$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest_IT::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe_IT::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight_IT::
	.string "それっ　ちがうよー！$"

Text_ISee_IT::
	.string "そっか‥$"

Text_TheDoorIsClosed_IT::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen_IT::
	.string "La porta è aperta…$"
