Text_MayIHelpYou_IT::
	.string "Salve!\n"
	.string "Posso essere d'aiuto?$"

Text_FillOutQuestionnaire_IT::
	.string "C'è un questionario.\n"
	.string "Vuoi compilarlo?$"

Text_QuestionnaireThankYou_IT::
	.string "Grazie per aver compilato\n"
	.string "il questionario.\p"
	.string "Le tue risposte saranno\n"
	.string "molto utili.$"

Text_YouKnowThoseWords_IT::
	.string "Ciao!\n"
	.string "Ah, conosci le parole segrete?\p"
	.string "Quindi, sai anche cos'è\n"
	.string "il DONO SEGRETO!\p"
	.string "Da questo momento puoi\n"
	.string "ricevere DONI SEGRETI!$"

Text_YouCanAccessMysteryGift_IT::
	.string "Dopo aver salvato il gioco, potrai\n"
	.string "accedere all'opzione DONO SEGRETO.$"

Text_ThankYouForAccessingMysteryGift_IT::
	.string "Grazie per usufruire del servizio\n"
	.string "DONO SEGRETO!$"
