Text_MakingPreparations_IT::
	.string "じゅんびちゅうです！$"

Text_WantWhichFloor_IT::
	.string "A che piano vuoi andare?$"

Text_BagItemCanBeRegistered_IT::
	.string "Puoi assegnare uno strumento dello\n"
	.string "ZAINO a SELECT.$"

@ Unused (email from R/S Rivals computer)
Text_TrainerSchoolEmail_IT::
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

Text_PlayerBootedUpPC_IT::
	.string "{PLAYER} accende il PC.$"

@ Unused
Text_LinkWasCanceled_IT::
	.string "つうしんは　キャンセルされました$"

@ Unused
Text_GiveNicknameToReceivedMon_IT::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_2}?$"

gText_PkmnFainted3_IT::
	.string "{STR_VAR_1} è esausto…\p"
	.string "$"

Text_WelcomeWantToHealPkmn_IT::
	.string "Sei in un CENTRO POKéMON.\p"
	.string "Rimettiamo in sesto i POKéMON\n"
	.string "stanchi.\p"
	.string "Vuoi far riposare la tua squadra?$"

Text_TakeYourPkmnForFewSeconds_IT::
	.string "OK, mi prendo la tua squadra di\n"
	.string "POKéMON per qualche secondo.$"

Text_WeHopeToSeeYouAgain_IT::
	.string "Arrivederci!$"

Text_RestoredPkmnToFullHealth_IT::
	.string "Grazie per l'attesa.\n"
	.string "Ora la tua squadra di POKéMON è in\lperfetta forma.$"
