@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight_IT::
	.string "Hmmm…\n"
	.string "È quello giusto…$"

PalletTown_Text_OhLookLook_IT::
	.string "Oh!\n"
	.string "Guarda, guarda!$"

PalletTown_Text_ReadItReadIt_IT::
	.string "Leggi, leggi!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu_IT::
	.string "CONSIGLI UTILI\p"
	.string "Premi START per aprire il MENU!$"

PalletTown_Text_SignsAreUsefulArentThey_IT::
	.string "Sono utili i cartelli, vero?$"

PalletTown_Text_LookCopiedTrainerTipsSign_IT::
	.string "Guarda qui!\p"
	.string "Ho copiato una frase scritta su\n"
	.string "un cartello di CONSIGLI UTILI.$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy_IT::
	.string "CONSIGLI UTILI\p"
	.string "Premi START per aprire il MENU!$"
