CeladonCity_GameCorner_Text_TryPokemonPrinter_IT::
	.string "È una POKéSTAMPANTE!\p"
	.string "Con questa, puoi applicare sul\n"
	.string "retro della SCHEDA ALLENATORE\l"
	.string "le immagini dei tuoi POKéMON.\p"
	.string "Usarla costa ¥50.\n"
	.string "Vuoi provare?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney_IT::
	.string "Non hai denaro sufficiente…$"

CeladonCity_GameCorner_Text_ChoosePrintType_IT::
	.string "Scegli il tipo di stampa.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto_IT::
	.string "Fai un bel sorriso!\n"
	.string "Tre… due… uno…\p"
	.string "Flash!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard_IT::
	.string "La tua stampa è pronta.\n"
	.string "Controlla la SCHEDA ALLENATORE.$"

FourIsland_House2_Text_WishICouldShowOffStickers_IT::
	.string "Ho tantissimi ADESIVI!\n"
	.string "Mi piacerebbe poterli mostrare\l"
	.string "a qualcuno!$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag_IT::
	.string "Sei nel posto giusto!\p"
	.string "Guarda quanti ADESIVI ho raccolto!\p"
	.string "Scommetto che ne vuoi un po'\n"
	.string "anche tu!\p"
	.string "Ti do un adesivo se mi racconti\n"
	.string "qualcosa di incredibile su di te.\p"
	.string "Dai, su! Vantati un po' delle tue\n"
	.string "gesta!$"

FourIsland_House2_Text_BragAboutSomethingForMe_IT::
	.string "Dai! Vantati un po' delle tue\n"
	.string "gesta!\l"
	.string "In cambio, ti do un ADESIVO!$"

FourIsland_House2_Text_BragAboutWhatToday_IT::
	.string "Ah eccoti!\p"
	.string "Cosa mi racconti, oggi?\n"
	.string "Di quali gesta ti vanterai?$"

FourIsland_House2_Text_WowHoFLowest_IT::
	.string "Ah, davvero hai avuto accesso\n"
	.string "alla SALA d'ONORE?\p"
	.string "Grandioso! Per avermelo\n"
	.string "raccontato, meriti uno di\l"
	.string "questi!$"

FourIsland_House2_Text_WowHoFLow_IT::
	.string "Ah, davvero hai avuto accesso alla\n"
	.string "SALA d'ONORE più di una volta?\p"
	.string "Straordinario! Per quello che mi\n"
	.string "hai raccontato, ti darò uno di\l"
	.string "questi!$"

FourIsland_House2_Text_WowHoFHigh_IT::
	.string "Ah, hai avuto accesso alla SALA\n"
	.string "d'ONORE per così tante volte?\p"
	.string "Incredibile! Grazie per avermelo\n"
	.string "raccontato! Tieni questo in cambio!$"

FourIsland_House2_Text_WowHoFHighest_IT::
	.string "Non posso credere che tu abbia\n"
	.string "avuto accesso alla SALA d'ONORE\l"
	.string "così spesso!\p"
	.string "Sei spaventosamente eccezionale!\n"
	.string "Tieni questo, per avermelo\l"
	.string "raccontato!$"

FourIsland_House2_Text_HoFStickerApplied_IT::
	.string "L'ADESIVO SALA d'ONORE è\n"
	.string "stato applicato alla SCHEDA\l"
	.string "ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF_IT::
	.string "Hmmm…\p"
	.string "La prossima volta, torna con una\n"
	.string "storia migliore, OK?$"

FourIsland_House2_Text_LivingLegendHoF_IT::
	.string "Ma tu sei una leggenda vivente!\p"
	.string "Non ho più ADESIVI da darti!$"

FourIsland_House2_Text_WowEggsLowest_IT::
	.string "Davvero esistono le UOVA\n"
	.string "POKéMON? Non lo sapevo!\p"
	.string "Per avermelo detto, ti darò uno\n"
	.string "di questi!$"

FourIsland_House2_Text_WowEggsLow_IT::
	.string "Davvero hai fatto schiudere\n"
	.string "parecchie UOVA?\p"
	.string "Tieni, per avermelo detto ti do\n"
	.string "uno di questi.$"

FourIsland_House2_Text_WowEggsHigh_IT::
	.string "Hai fatto schiudere moltissime\n"
	.string "UOVA!\p"
	.string "Devo darti questo, allora!$"

FourIsland_House2_Text_WowEggsHighest_IT::
	.string "Hai fatto schiudere un numero\n"
	.string "incredibile di UOVA!\p"
	.string "Sei davvero impressionante!\n"
	.string "Tieni, questo è per te!$"


FourIsland_House2_Text_EggStickerApplied_IT::
	.string "L'ADESIVO UOVA è stato\n"
	.string "applicato alla SCHEDA\l"
	.string "ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs_IT::
	.string "Hmmm…\p"
	.string "La prossima volta, torna con una\n"
	.string "storia migliore, OK?$"

FourIsland_House2_Text_LivingLegendEggs_IT::
	.string "Ma tu sei una leggenda vivente!\p"
	.string "Non ho più ADESIVI da darti!$"

FourIsland_House2_Text_WowLinkWinsLowest_IT::
	.string "Davvero hai lottato in\n"
	.string "collegamento? E hai anche vinto?\p"
	.string "Tieni, meriti questo!$"

FourIsland_House2_Text_WowLinkWinsLow_IT::
	.string "Hai battuto i tuoi amici in una\n"
	.string "lunga serie di lotte in\l"
	.string "collegamento!\p"
	.string "Bene bene! Meriti questo, allora!$"

FourIsland_House2_Text_WowLinkWinsHigh_IT::
	.string "Wow! Hai battuto i tuoi amici in\n"
	.string "lotte in collegamento un'incredibile\l"
	.string "numero di volte!\p"
	.string "Beh, meriti proprio questo!$"

FourIsland_House2_Text_WowLinkWinsHighest_IT::
	.string "Ehi, ma quante lotte in\n"
	.string "collegamento hai vinto?!\p"
	.string "Non ci posso credere!\p"
	.string "Tieni, devo assolutamente\n"
	.string "darti questo!$"

FourIsland_House2_Text_VictoryStickerApplied_IT::
	.string "L'ADESIVO LOTTE LINK è stato\n"
	.string "applicato alla SCHEDA\l"
	.string "ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins_IT::
	.string "Hmmm…\p"
	.string "La prossima volta, torna con una\n"
	.string "storia migliore, OK?$"

FourIsland_House2_Text_LivingLegendLinkWins_IT::
	.string "Ma tu sei una leggenda vivente!\p"
	.string "Non ho più ADESIVI da darti!$"
