VSSeeker_Text_BatteryNotChargedNeedXSteps_IT::
	.string "Non è sufficientemente caricato.\p"
	.string "Passi necessari per caricarlo\n"
	.string "completamente: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange_IT::
	.string "Non ci sono ALLENATORI pronti\n"
	.string "a combattere nell'area…\p"
	.string "Il CERCASFIDE è stato spento.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady_IT::
	.string "Gli altri ALLENATORI non sono\n"
	.string "pronti per lottare.\p"
	.string "Dovrai aspettare un po'.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro_IT::
	.string "Ci siamo già visti a\n"
	.string "BOSCO SMERALDO!$"

Route3_Text_BenRematchIntro_IT::
	.string "Ciao!\n"
	.string "Mi piacciono i pantaloncini corti!\p"
	.string "Sono molto comodi!$"

Route3_Text_JaniceRematchIntro_IT::
	.string "Mi stavi guardando, vero?$"

Route3_Text_GregRematchIntro_IT::
	.string "Sei un ALLENATORE?\n"
	.string "Lottiamo, forza!$"

Route3_Text_SallyRematchIntro_IT::
	.string "Quel tuo sguardo è così intrigante!$"

Route3_Text_CalvinRematchIntro_IT::
	.string "Ehi! Continui a non indossare\n"
	.string "pantaloncini!$"

Route3_Text_JamesRematchIntro_IT::
	.string "Dai, rilottiamo! Così ti faccio\n"
	.string "vedere quanto sono migliorato!$"

Route3_Text_RobinRematchIntro_IT::
	.string "Ehi, mi hai spinto?!$"

Route4_Text_CrissyRematchIntro_IT::
	.string "Il MONTE LUNA è un buon posto per\n"
	.string "catturare POKéMON simili a funghi.$"

Route6_Text_RickyRematchIntro_IT::
	.string "Ah, sei quella mosca fastidiosa che\n"
	.string "origliava i nostri discorsi!$"

Route6_Text_NancyRematchIntro_IT::
	.string "Scusa, non ti avevo detto che\n"
	.string "questa è una conversazione\l"
	.string "privata?!\p"
	.string "Quindi non dovresti origliare,\n"
	.string "giusto?$"

Route6_Text_KeigoRematchIntro_IT::
	.string "Ho provato ad allenare anche altri\n"
	.string "POKéMON, ma alla fine i POKéMON\l"
	.string "COLEOTTERO sono i migliori!$"

Route6_Text_JeffRematchIntro_IT::
	.string "Vuoi lottare di nuovo?$"

Route6_Text_IsabelleRematchIntro_IT::
	.string "Dici a me?\n"
	.string "Bene! Giochiamo!$"

Route6_Text_ElijahRematchIntro_IT::
	.string "Ehi, è un po' che non ci vediamo!\n"
	.string "Hai migliorato la tua tecnica?$"

Route8_Text_AidanRematchIntro_IT::
	.string "Sembri forte con i POKéMON,\n"
	.string "l'ho già notato, ma come vai\l"
	.string "in chimica?$"

Route8_Text_StanRematchIntro_IT::
	.string "Benissimo!\n"
	.string "Il dado è tratto nuovamente!$"

Route8_Text_GlennRematchIntro_IT::
	.string "Ti serve una tattica migliore!\n"
	.string "Segui i miei consigli?$"

Route8_Text_PaigeRematchIntro_IT::
	.string "Ho catturato parecchi NIDORAN.\n"
	.string "Sto pensando di non farli evolvere.$"

Route8_Text_LeslieRematchIntro_IT::
	.string "Mi piace la scuola, ma anche i\n"
	.string "POKéMON!$"

Route8_Text_AndreaRematchIntro_IT::
	.string "MEOWTH e PERSIAN sono così carini!\n"
	.string "Miao!$"

Route8_Text_MeganRematchIntro_IT::
	.string "Ti sembra stupido che ce ne stiamo\n"
	.string "qui in piedi a non fare niente?\p"
	.string "Perché non rilottiamo, allora?$"

Route8_Text_RichRematchIntro_IT::
	.string "Sono un errante RISCHIATUTTO!$"

Route8_Text_JuliaRematchIntro_IT::
	.string "Qual è il POKéMON tondo e morbido?\n"
	.string "Te l'ho già chiesto, vero?$"

Route8_Text_RicardoRematchIntro_IT::
	.string "La mia moto è sempre eccezionale,\n"
	.string "sai?$"

Route8_Text_JarenRematchIntro_IT::
	.string "E va bene, rilottiamo!\n"
	.string "E questa volta, non avrò pietà!$"

Route8_Text_EliRematchIntro_IT::
	.string "ELI: Siamo diventate ancora più\n"
	.string "forti!$"

Route8_Text_AnneRematchIntro_IT::
	.string "ANNE: Siamo ancora più\n"
	.string "affiatate di prima!$"

Route9_Text_AliciaRematchIntro_IT::
	.string "Sei qui per un'altra sfida?\n"
	.string "Questa volta ti batterò!$"

Route9_Text_ChrisRematchIntro_IT::
	.string "Non vi ho dimenticato, tu e la\n"
	.string "tua potente squadra di POKéMON!$"

Route9_Text_DrewRematchIntro_IT::
	.string "Vado a LAVANDONIA attraverso il\n"
	.string "TUNNEL ROCCIOSO.\p"
	.string "Conto di fermarmi a lottare con\n"
	.string "tutti quelli che incontro!$"

Route9_Text_CaitlinRematchIntro_IT::
	.string "Questa volta non mi batterai!$"

Route9_Text_JeremyRematchIntro_IT::
	.string "Ahaha! Che bello!\n"
	.string "Stavo iniziando ad annoiarmi!$"

Route9_Text_BriceRematchIntro_IT::
	.string "Ahaha!\n"
	.string "Ma chi ti credi di essere?!$"

Route9_Text_BrentRematchIntro_IT::
	.string "Mi sveglio presto ogni mattina per\n"
	.string "allenare i miei POKéMON\l"
	.string "COLEOTTERO!$"

Route9_Text_AlanRematchIntro_IT::
	.string "Questa volta vinco io!$"

Route9_Text_ConnerRematchIntro_IT::
	.string "Forza, miei POKéMON COLEOTTERO!\n"
	.string "Questa volta dovete vincere!$"

Route10_Text_MarkRematchIntro_IT::
	.string "Ehi, guarda chi si rivede!\p"
	.string "Vuoi vedere la mia collezione?$"

Route10_Text_ClarkRematchIntro_IT::
	.string "Eccì! Eccì!\p"
	.string "Non riesco a smettere di\n"
	.string "starnutire!$"

Route10_Text_HermanRematchIntro_IT::
	.string "Ehi!\n"
	.string "Ti mostro i miei POKéMON!$"

Route10_Text_HeidiRematchIntro_IT::
	.string "Sono tornata un'altra volta alla\n"
	.string "PALESTRA POKéMON… e ho perso\l"
	.string "di nuovo!$"

Route10_Text_TrentRematchIntro_IT::
	.string "Ah!\n"
	.string "Quest'aria di montagna!$"

Route10_Text_CarolRematchIntro_IT::
	.string "Inizia a girarmi la testa: oggi\n"
	.string "ho scarpinato troppo!$"

Route11_Text_HugoRematchIntro_IT::
	.string "Scommettiamo sulla tua\n"
	.string "sconfitta?\l"
	.string "Dai, inizia la rivincita!$"

Route11_Text_JasperRematchIntro_IT::
	.string "Sfide!\p"
	.string "Non ne ho mai abbastanza, anche\n"
	.string "se l'ultima volta ho perso contro\l"
	.string "di te!$"

Route11_Text_EddieRematchIntro_IT::
	.string "OK, lottiamo!\n"
	.string "Ma non imbrogliare!$"

Route11_Text_BraxtonRematchIntro_IT::
	.string "Attento!\n"
	.string "Sto posando dei cavi!$"

Route11_Text_DillonRematchIntro_IT::
	.string "Sono ALLENATORE da poco!\n"
	.string "Ma penso di poter vincere!$"

Route11_Text_DirkRematchIntro_IT::
	.string "Ihaha!\n"
	.string "Non ho mai perso!$"

Route11_Text_DarianRematchIntro_IT::
	.string "Non ho ancora mai vinto…$"

Route11_Text_YasuRematchIntro_IT::
	.string "Sono il primo della classe!$"

Route11_Text_BernieRematchIntro_IT::
	.string "Attento ai cavi scoperti!$"

Route11_Text_DaveRematchIntro_IT::
	.string "I miei POKéMON dovrebbero essere\n"
	.string "pronti ormai!$"

Route12_Text_NedRematchIntro_IT::
	.string "Sìì! Ha abboccato!$"

Route12_Text_ChipRematchIntro_IT::
	.string "Ci vuole pazienza!\n"
	.string "La pesca richiede tempo!$"

Route12_Text_JustinRematchIntro_IT::
	.string "Hai trovato la PIETRALUNARE?$"

Route12_Text_LucaRematchIntro_IT::
	.string "L'elettricità è la mia specialità!$"

Route12_Text_HankRematchIntro_IT::
	.string "Il PESCATORE PAZZO contro\n"
	.string "l'ALLENATORE in ERBA!$"

Route12_Text_ElliotRematchIntro_IT::
	.string "Preferirei lavorare!\n"
	.string "Te l'ho già detto, forse?$"

Route12_Text_AndrewRematchIntro_IT::
	.string "Cosa sto pescando?\n"
	.string "Se mi batti, potrei dirtelo.$"

Route12_Text_JesRematchIntro_IT::
	.string "JES: Facciamo così: se ti batto,\n"
	.string "chiedo a GIA di sposarmi!$"

Route12_Text_GiaRematchIntro_IT::
	.string "GIA: JES… ormai usciamo insieme\n"
	.string "da così tanto tempo…\p"
	.string "Che ne dici? Se vinciamo questa\n"
	.string "lotta, ci sposiamo!$"

Route13_Text_SebastianRematchIntro_IT::
	.string "I miei POKéMON uccello vogliono\n"
	.string "divertirsi!$"

Route13_Text_SusieRematchIntro_IT::
	.string "Voglio diventare il miglior\n"
	.string "ALLENATORE mentre sono ancora\l"
	.string "una bambina!$"

Route13_Text_ValerieRematchIntro_IT::
	.string "Che belle MEDAGLIE che hai!$"

Route13_Text_GwenRematchIntro_IT::
	.string "I miei cari POKéMON vogliono\n"
	.string "conoscerti.$"

Route13_Text_AlmaRematchIntro_IT::
	.string "Con i miei risparmi, ho un altro\n"
	.string "po' di CARBURANTE!$"

Route13_Text_PerryRematchIntro_IT::
	.string "Ho il vento a favore!\n"
	.string "Questa volta, per davvero!$"

Route13_Text_LolaRematchIntro_IT::
	.string "Ah, sei di nuovo qui!\n"
	.string "Certo che ho voglia di risfidarti!$"

Route13_Text_SheilaRematchIntro_IT::
	.string "Certo che mi ricordo di te!$"

Route13_Text_JaredRematchIntro_IT::
	.string "Cos'hai da guardare?!$"

Route13_Text_RobertRematchIntro_IT::
	.string "Tengo i POKéMON uccello sempre con\n"
	.string "me! Come vedi, non è cambiato\l"
	.string "niente dall'ultima volta!$"

Route14_Text_CarterRematchIntro_IT::
	.string "Ho usato delle MT per insegnare\n"
	.string "buone mosse ai miei POKéMON.$"

Route14_Text_MitchRematchIntro_IT::
	.string "I miei POKéMON uccello sono pronti\n"
	.string "a lottare.$"

Route14_Text_BeckRematchIntro_IT::
	.string "Stai usando le MT sui tuoi\n"
	.string "POKéMON?\p"
	.string "Averle e non usarle non serve\n"
	.string "a niente!$"

Route14_Text_MarlonRematchIntro_IT::
	.string "Hai insegnato il VOLO ai tuoi\n"
	.string "POKéMON uccello?$"

Route14_Text_DonaldRematchIntro_IT::
	.string "La leggenda dei miraggi alati…\p"
	.string "Non dirmi che non ne hai sentito\n"
	.string "parlare?!$"

Route14_Text_BennyRematchIntro_IT::
	.string "Non sono un grande esperto,\n"
	.string "però lottare continua a piacermi!$"

Route14_Text_LukasRematchIntro_IT::
	.string "Ehi!\n"
	.string "Mi ricordo di te!\p"
	.string "Forza! Forza!\n"
	.string "Avanti, andiamo, sottoooo!$"

Route14_Text_IsaacRematchIntro_IT::
	.string "Devo ingannare il tempo, a volte!$"

Route14_Text_GeraldRematchIntro_IT::
	.string "Veniamo qui con la moto perché c'è\n"
	.string "più spazio!$"

Route14_Text_MalikRematchIntro_IT::
	.string "Lotta POKéMON?\n"
	.string "Eccome no!$"

Route14_Text_KiriRematchIntro_IT::
	.string "KIRI: JAN, oggi dobbiamo vincere!$"

Route14_Text_JanRematchIntro_IT::
	.string "JAN: Dai, KIRI!\n"
	.string "Questa volta si vince di sicuro!$"

Route15_Text_KindraRematchIntro_IT::
	.string "Voglio provare i POKéMON che ho\n"
	.string "appena scambiato!$"

Route15_Text_BeckyRematchIntro_IT::
	.string "Sembri debole!\n"
	.string "Penso di poterti vincere\l"
	.string "questa volta!$"

Route15_Text_EdwinRematchIntro_IT::
	.string "Quando fischio, chiamo a raccolta\n"
	.string "i POKéMON uccello!\p"
	.string "Devi vedere che spettacolo!$"

Route15_Text_ChesterRematchIntro_IT::
	.string "I miei uccellini tremano di paura!\n"
	.string "Sei forte, vero?$"

Route15_Text_GraceRematchIntro_IT::
	.string "Oh!\n"
	.string "Sei un tipo simpatico!\l"
	.string "Mi ricordo di te!$"

Route15_Text_OliviaRematchIntro_IT::
	.string "Allevo POKéMON per non sentirmi\n"
	.string "sola.\p"
	.string "Come vedi non ho ancora trovato\n"
	.string "l'anima gemella!$"

Route15_Text_ErnestRematchIntro_IT::
	.string "Ehi tu! Coraggio!\n"
	.string "Guarda cos'ho!$"

Route15_Text_AlexRematchIntro_IT::
	.string "O la borsa, o la vita!$"

Route15_Text_CeliaRematchIntro_IT::
	.string "Cos'è bello?\n"
	.string "Scambiar POKéMON!$"

Route15_Text_YazminRematchIntro_IT::
	.string "Vuoi giocare con i miei POKéMON\n"
	.string "ancora una volta?$"

Route15_Text_MyaRematchIntro_IT::
	.string "MYA: Ehi, ci si rincontra!\p"
	.string "Vuoi aiutarmi di nuovo ad\n"
	.string "allenare il mio fratellino?$"

Route15_Text_RonRematchIntro_IT::
	.string "RON: Mia sorella è diventata\n"
	.string "ancora più forte!$"

Route16_Text_LaoRematchIntro_IT::
	.string "Che vuoi?$"

Route16_Text_KojiRematchIntro_IT::
	.string "Bella BICICLETTA!\n"
	.string "Da' qua!$"

Route16_Text_LukeRematchIntro_IT::
	.string "Vieni a giocare, pulce!\n"
	.string "Questa volta ti concio per le\l"
	.string "feste!$"

Route16_Text_HideoRematchIntro_IT::
	.string "Ehi!\n"
	.string "Mi hai urtato un'altra volta!$"

Route16_Text_CamronRematchIntro_IT::
	.string "Ho fame e mi sto arrabbiando\n"
	.string "sul serio, questa volta!$"

Route16_Text_RubenRematchIntro_IT::
	.string "Ehi, divertiamoci con un'altra\n"
	.string "bella lotta!$"

Route16_Text_JedRematchIntro_IT::
	.string "JED: Sei qui per contemplare\n"
	.string "la grandezza sconfinata del\l"
	.string "nostro amore?$"

Route16_Text_LeaRematchIntro_IT::
	.string "LEA: A volte sono spaventata\n"
	.string "dall'intensità del nostro amore.$"

Route17_Text_RaulRematchIntro_IT::
	.string "Non vale la pena lottare con i\n"
	.string "bambini!\l"
	.string "Mi sembra di avertelo già detto!$"

Route17_Text_IsaiahRematchIntro_IT::
	.string "Che vuoi, pulce? Di nuovo qui?$"

Route17_Text_VirgilRematchIntro_IT::
	.string "Ti stai facendo un giretto?$"

Route17_Text_BillyRematchIntro_IT::
	.string "Siamo CENTAURI!\n"
	.string "Dei campioni!$"

Route17_Text_NikolasRematchIntro_IT::
	.string "Oggi VOLTORB ti elettrizzerà, sul\n"
	.string "serio!$"

Route17_Text_ZeekRematchIntro_IT::
	.string "I miei POKéMON non si evolvono!\n"
	.string "Perché? Te l'ho già chiesto?$"

Route17_Text_JamalRematchIntro_IT::
	.string "Ho bisogno di un po' d'esercizio!$"

Route17_Text_CoreyRematchIntro_IT::
	.string "Sii ribelle!$"

Route17_Text_JaxonRematchIntro_IT::
	.string "Bella BICICLETTA!\n"
	.string "Come funziona?$"

Route17_Text_WilliamRematchIntro_IT::
	.string "Sparisci, pulce!\n"
	.string "Sono esausto!$"

Route18_Text_WiltonRematchIntro_IT::
	.string "Ho setacciato tutte le zone\n"
	.string "erbose alla ricerca di nuove\l"
	.string "specie di POKéMON!\p"
	.string "Ma non è così facile!$"

Route18_Text_RamiroRematchIntro_IT::
	.string "Cu cu cu!\n"
	.string "Il mio richiamo è un po'\l"
	.string "migliorato?$"

Route18_Text_JacobRematchIntro_IT::
	.string "Questo è il mio territorio!\n"
	.string "Ti avevo già avvertito!\l"
	.string "Via!$"

Route19_Text_RichardRematchIntro_IT::
	.string "Sto finendo il riscaldamento, prima\n"
	.string "di nuotare.$"

Route19_Text_ReeceRematchIntro_IT::
	.string "Aspetta!\n"
	.string "Ti verrà un accidente!$"

Route19_Text_MatthewRematchIntro_IT::
	.string "Mi piace nuotare!\n"
	.string "E a te?$"

Route19_Text_DouglasRematchIntro_IT::
	.string "Che c'è oltre l'orizzonte?$"

Route19_Text_DavidRematchIntro_IT::
	.string "Mi sono tuffato per prendere dei\n"
	.string "POKéMON, ma zero come sempre!$"

Route19_Text_TonyRematchIntro_IT::
	.string "Guardo il mare per dimenticare,\n"
	.string "soprattutto la sconfitta di prima!$"

Route19_Text_AnyaRematchIntro_IT::
	.string "Dev'essere rilassante fare SURF sul\n"
	.string "tuo POKéMON.\l"
	.string "Se vinco, me lo presti?$"

Route19_Text_AliceRematchIntro_IT::
	.string "Nuotare è bello!\n"
	.string "Scottarsi al sole invece no!$"

Route19_Text_AxleRematchIntro_IT::
	.string "Cosa ci fai di nuovo qui?\n"
	.string "Queste acque sono pericolose!$"

Route19_Text_ConnieRematchIntro_IT::
	.string "Ho nuotato fin qui con i miei\n"
	.string "POKéMON e adesso sono stanca!\p"
	.string "Vuoi proprio sfidarmi di nuovo?$"

Route19_Text_LiaRematchIntro_IT::
	.string "LIA: Ti ricordi che mio fratello è\n"
	.string "appena diventato ALLENATORE, vero?\p"
	.string "Lo sto allenando, e ho di nuovo\n"
	.string "bisogno del tuo aiuto!$"

Route19_Text_LucRematchIntro_IT::
	.string "SAM: La mia sorellona mi ha\n"
	.string "insegnato tutto sui POKéMON.\p"
	.string "Forse ora sono persino più forte\n"
	.string "di lei!$"

Route20_Text_BarryRematchIntro_IT::
	.string "Qui l'acqua non è profonda.$"

Route20_Text_ShirleyRematchIntro_IT::
	.string "Sono in vacanza alle ISOLE\n"
	.string "SPUMARINE!$"

Route20_Text_TiffanyRematchIntro_IT::
	.string "Nuotare con i pesci!\n"
	.string "Mi piace sempre di più!$"

Route20_Text_IreneRematchIntro_IT::
	.string "Sei qui in vacanza anche tu?$"

Route20_Text_DeanRematchIntro_IT::
	.string "Guarda che fisico che ho!\p"
	.string "Non ti sembra ancora più\n"
	.string "possente dell'altra volta?$"

Route20_Text_DarrinRematchIntro_IT::
	.string "Perché fai SURF su di un POKéMON?\n"
	.string "Non hai ancora imparato a nuotare?$"

Route20_Text_RogerRematchIntro_IT::
	.string "Sono arrivato a dorso del mio\n"
	.string "POKéMON uccello!$"

Route20_Text_NoraRematchIntro_IT::
	.string "Il mio ragazzo mi ha dato delle\n"
	.string "grandi perle, che sono diventate\l"
	.string "ancora più grosse!$"

Route20_Text_MissyRematchIntro_IT::
	.string "Sono venuta a nuoto dall'ISOLA\n"
	.string "CANNELLA!\p"
	.string "Te l'ho già detto?\n"
	.string "Lo so, sono ripetitiva!$"

Route20_Text_MelissaRematchIntro_IT::
	.string "C'è un LABORATORIO POKéMON a\n"
	.string "ovest, sull'ISOLA CANNELLA.\p"
	.string "Mio papà lavora lì!$"

Route21_North_Text_RonaldRematchIntro_IT::
	.string "Vuoi sapere se i pesci abboccano?$"

Route21_North_Text_WadeRematchIntro_IT::
	.string "Ho pescato dei bei POKéMON!\n"
	.string "Vuoi lottare di nuovo?$"

Route21_North_Text_SpencerRematchIntro_IT::
	.string "Il mare pulisce il corpo e l'anima!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro_IT::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro_IT::
	.string "Ho catturato i miei POKéMON in\n"
	.string "mare, ed è qui che li alleno.$"

Route21_South_Text_JeromeRematchIntro_IT::
	.string "Sto andando a fare un'altra gara\n"
	.string "di triathlon!$"

Route21_South_Text_RolandRematchIntro_IT::
	.string "Ah!\n"
	.string "Senti il sole e il vento!$"

Route21_South_Text_ClaudeRematchIntro_IT::
	.string "Ehi, ci hai preso proprio gusto a\n"
	.string "spaventarmi i pesci!$"

Route21_South_Text_NolanRematchIntro_IT::
	.string "Fammi compagnia finché non prendo\n"
	.string "qualcosa!$"

Route21_North_Text_LilRematchIntro_IT::
	.string "LIL: Un'altra lotta? IAN, non ce\n"
	.string "la fai a combattere da solo?$"

Route21_North_Text_IanRematchIntro_IT::
	.string "IAN: Mia sorella continua a essere\n"
	.string "una pigrona!\p"
	.string "Aiutami a farla diventare un po'\n"
	.string "più attiva, altrimenti non dimagrirà\l"
	.string "mai!$"

Route25_Text_JoeyRematchIntro_IT::
	.string "Non credere di battermi di nuovo!$"

Route25_Text_DanRematchIntro_IT::
	.string "Papà mi ha portato a una bella\n"
	.string "festa sulla M/N ANNA ad\l"
	.string "ARANCIOPOLI!$"

Route25_Text_FlintRematchIntro_IT::
	.string "Sono un tipo giusto, io!\n"
	.string "Ho la ragazza!\p"
	.string "Sempre la stessa di prima!$"

Route25_Text_KelseyRematchIntro_IT::
	.string "Ciao!\n"
	.string "Il mio ragazzo è forte!\p"
	.string "E oggi anch'io sono al top!$"

Route25_Text_ChadRematchIntro_IT::
	.string "Lo sapevo che ci saremmo\n"
	.string "scontrati ancora una volta!$"

Route25_Text_HaleyRematchIntro_IT::
	.string "Il mio amico ha un POKéMON così\n"
	.string "dolce…\p"
	.string "Crepo dall'invidia!$"

Route25_Text_FranklinRematchIntro_IT::
	.string "Ho appena lottato sul MONTE LUNA,\n"
	.string "ma non mi è certo passata la\l"
	.string "voglia!$"

Route25_Text_NobRematchIntro_IT::
	.string "Vado al capo a trovare un\n"
	.string "collezionista di POKéMON!\p"
	.string "Hai visto la sua collezione?$"

Route25_Text_WayneRematchIntro_IT::
	.string "Stai andando da BILL?\n"
	.string "Prima però in guardia!$"

Route24_Text_ShaneRematchIntro_IT::
	.string "Ti ho visto tra l'erba!\n"
	.string "Di nuovo!$"

Route24_Text_EthanRematchIntro_IT::
	.string "OK!\n"
	.string "Ti polverizzerò!$"

Route24_Text_ReliRematchIntro_IT::
	.string "Hai sempre così tanta energia!\n"
	.string "Non ti stanchi mai?$"

Route24_Text_TimmyRematchIntro_IT::
	.string "Ti piace venire al PONTE PEPITA,\n"
	.string "eh?$"

Route24_Text_AliRematchIntro_IT::
	.string "È vero che ho perso, prima, ma\n"
	.string "sono comunque la vincitrice morale,\l"
	.string "vero?$"

Route24_Text_CaleRematchIntro_IT::
	.string "Questo è il PONTE PEPITA.\p"
	.string "Ci hai già battuto prima, però\n"
	.string "possiamo lottare di nuovo, se\l"
	.string "vuoi!$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro_IT::
	.string "Galleggiando sul dorso, cullata\n"
	.string "dalle onde, non mi accorgo del\l"
	.string "tempo che passa!$"

OneIsland_KindleRoad_Text_MariaRematchIntro_IT::
	.string "Che tempo magnifico!\n"
	.string "Il tempo perfetto per una\l"
	.string "vittoria!$"

OneIsland_KindleRoad_Text_AbigailRematchIntro_IT::
	.string "La mia scottatura inizia a fare\n"
	.string "male!$"

OneIsland_KindleRoad_Text_FinnRematchIntro_IT::
	.string "La montagna dell'uccello di fuoco\n"
	.string "proietta un'ombra mastodontica!$"

OneIsland_KindleRoad_Text_GarrettRematchIntro_IT::
	.string "Questa volta penso proprio di poter\n"
	.string "vincere!$"

OneIsland_KindleRoad_Text_TommyRematchIntro_IT::
	.string "Aspetta! Aspetta un secondo!\n"
	.string "Sono sicuro che ha abboccato\l"
	.string "un pesce enorme!$"

OneIsland_KindleRoad_Text_SharonRematchIntro_IT::
	.string "Sei qui per aiutarmi di nuovo\n"
	.string "ad allenarmi?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro_IT::
	.string "Finora non abbiamo perso un solo\n"
	.string "giorno di allenamento!$"

OneIsland_KindleRoad_Text_SheaRematchIntro_IT::
	.string "Ogni mattina, prima di colazione,\n"
	.string "faccio tre giri intorno all'isola!$"

OneIsland_KindleRoad_Text_HughRematchIntro_IT::
	.string "Non ti ho già detto che devi\n"
	.string "vestirti in modo appropriato\l"
	.string "per lottare?$"

OneIsland_KindleRoad_Text_BryceRematchIntro_IT::
	.string "In mezzo alla natura, il cibo ha\n"
	.string "un sapore più intenso.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro_IT::
	.string "Ho di nuovo mangiato troppo!\n"
	.string "Lottiamo un po', così smaltisco!$"

OneIsland_KindleRoad_Text_KiaRematchIntro_IT::
	.string "KIA: Io e il mio fratellone siamo\n"
	.string "una coppia fantastica!\p"
	.string "Questa volta non perderemo!$"

OneIsland_KindleRoad_Text_MikRematchIntro_IT::
	.string "MIK: Insieme a KIA, niente mi fa\n"
	.string "paura!\p"
	.string "E questa volta, te lo\n"
	.string "dimostreremo!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro_IT::
	.string "Lottiamo di nuovo?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro_IT::
	.string "Da dove vieni, e dov'è diretto il\n"
	.string "tuo cammino?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro_IT::
	.string "Presto saprò nuotare senza\n"
	.string "salvagente!$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro_IT::
	.string "Yuppi, yuppi, POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro_IT::
	.string "Non ti avevo già detto di stare\n"
	.string "alla larga?$"

ThreeIsland_BondBridge_Text_JoyRematchIntro_IT::
	.string "JOY: Ora siamo più forti, ma di\n"
	.string "molto!$"

ThreeIsland_BondBridge_Text_MegRematchIntro_IT::
	.string "IDA: Oggi non potrai batterci!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro_IT::
	.string "Stai allenando i tuoi POKéMON\n"
	.string "in un ambiente salutare?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro_IT::
	.string "Oggi costruirò la vittoria con le\n"
	.string "mie stesse mani!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro_IT::
	.string "Non farmi ripetere sempre le stesse\n"
	.string "cose: sto dipingendo e non voglio\l"
	.string "essere disturbata!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro_IT::
	.string "Non ho fatto progressi. Continuo a\n"
	.string "sbagliare la prospettiva.$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro_IT::
	.string "Hai deciso di concedermi la\n"
	.string "rivincita?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro_IT::
	.string "La piscina per i miei POKéMON è\n"
	.string "quasi terminata.\p"
	.string "Appena è pronta ti invito a casa\n"
	.string "mia!$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro_IT::
	.string "Sono un buon corridore! Ora\n"
	.string "sono ancora più veloce!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro_IT::
	.string "Io e te siamo amici, vero?\n"
	.string "E allora, lottiamo!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro_IT::
	.string "Sono il più vecchio dei FRATELLI\n"
	.string "VOLANTI. Ti ricordi di me?\p"
	.string "Sì, sono quello che dei volatili\n"
	.string "apprezza soprattutto il becco!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro_IT::
	.string "Dei FRATELLI VOLANTI, sono quello\n"
	.string "di mezzo.\p"
	.string "Sono quello che degli uccelli\n"
	.string "apprezza soprattutto le ali!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro_IT::
	.string "Sono il più giovane dei FRATELLI\n"
	.string "VOLANTI.\p"
	.string "Sono quello che ama i volatili\n"
	.string "soprattutto per le piume.\l"
	.string "Non pensavo di rivederti qui!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro_IT::
	.string "Continuo a non avere nessuna\n"
	.string "fortuna.\p"
	.string "Mi ci vorrebbe una vittoria, per\n"
	.string "risollevarmi il morale!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro_IT::
	.string "Gasp… Gasp…\p"
	.string "Ho di nuovo nuotato fin qui da\n"
	.string "SESTISOLA senza mai fermarmi!$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro_IT::
	.string "Arrivi sempre quando sto nuotando!$"

SixIsland_OutcastIsland_Text_AvaRematchIntro_IT::
	.string "AVA: Facciamoci un'altra lotta\n"
	.string "2 contro 2 in mezzo al mare!$"

SixIsland_OutcastIsland_Text_GebRematchIntro_IT::
	.string "GEB: Io e la mia sorellona non\n"
	.string "siamo mai stati così forti!$"

SixIsland_GreenPath_Text_JaclynRematchIntro_IT::
	.string "…Huh?\p"
	.string "Non capisco: mi concentro su casa\n"
	.string "mia, però TELETRASPORTO mi porta\l"
	.string "sempre qui!$"

SixIsland_WaterPath_Text_RoseRematchIntro_IT::
	.string "Ah, ciao!\n"
	.string "Soffia di nuovo una dolce\l"
	.string "brezza, come l'altra volta!$"

SixIsland_WaterPath_Text_EdwardRematchIntro_IT::
	.string "Mi sto di nuovo allenando\n"
	.string "in segreto!$"

SixIsland_WaterPath_Text_SamirRematchIntro_IT::
	.string "Davvero non ce la fai più\n"
	.string "a vedere NUOTATORI come me?\p"
	.string "E dai, non te la prendere!\n"
	.string "Lottiamo un po', su!$"

SixIsland_WaterPath_Text_DeniseRematchIntro_IT::
	.string "Sigh…\n"
	.string "Il mio ragazzo è di nuovo\l"
	.string "occupatissimo…$"

SixIsland_WaterPath_Text_EarlRematchIntro_IT::
	.string "Scusa, sai se ci sono montagne\n"
	.string "da queste parti?$"

SixIsland_WaterPath_Text_MiuRematchIntro_IT::
	.string "MIU: POKéMON, è di nuovo il\n"
	.string "momento di giocare!$"

SixIsland_WaterPath_Text_MiaRematchIntro_IT::
	.string "MIA: POKéMON, è di nuovo il\n"
	.string "momento di lottare!$"

SixIsland_RuinValley_Text_StanlyRematchIntro_IT::
	.string "In questo mondo ci sono ancora\n"
	.string "così tanti segreti da scoprire!$"

SixIsland_RuinValley_Text_FosterRematchIntro_IT::
	.string "Non ci siamo già incontrati?\n"
	.string "Cosa ti ha spinto a ritornare?$"

SixIsland_RuinValley_Text_LarryRematchIntro_IT::
	.string "Pare che ci siano strane pietre su\n"
	.string "quest'isola.\p"
	.string "Hai scoperto qualcosa dall'ultima\n"
	.string "volta che ci siamo visti?$"

SixIsland_RuinValley_Text_DarylRematchIntro_IT::
	.string "Vuoi lottare di nuovo?\n"
	.string "E perché no?$"

SixIsland_RuinValley_Text_HectorRematchIntro_IT::
	.string "Conosco molto bene questi posti.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro_IT::
	.string "Ho presagito il tuo arrivo!$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro_IT::
	.string "Da qualche parte sull'isola, ci\n"
	.string "sono POKéMON che dormono.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro_IT::
	.string "Non so se hai fatto bene a\n"
	.string "tornare! Sto per distruggerti!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro_IT::
	.string "Ciao! Hai la tessera del mio\n"
	.string "fan club, vero?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro_IT::
	.string "Quest'isola è troppo grande!\n"
	.string "Continuo ad avere problemi\l"
	.string "a pattugliarla!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro_IT::
	.string "Non perdono chi fa male ai miei\n"
	.string "POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro_IT::
	.string "EVE: Io e JON vogliamo la\n"
	.string "rivincita!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro_IT::
	.string "JON: Con EVE, è come se non\n"
	.string "potessimo mai perdere.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro_IT::
	.string "Dai lottiamo! Ero già in forma,\n"
	.string "ma ora lo sono ancora di più!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro_IT::
	.string "Non importa che tu abbia i POKéMON\n"
	.string "migliori.\p"
	.string "Se non sai utilizzarli al meglio,\n"
	.string "perdi comunque.\l"
	.string "Te l'avevo già detto?$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro_IT::
	.string "Lavoro per proteggere l'ambiente. E\n"
	.string "l'ambiente mi protegge a sua volta.\p"
	.string "Dico sempre le stesse cose, lo so.$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro_IT::
	.string "Ogni volta che ci incontriamo\n"
	.string "indossi sempre quelle scarpe\l"
	.string "stupende!$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro_IT::
	.string "Chissà come sei forte ora!\n"
	.string "Dai, lottiamo! Voglio vedere!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro_IT::
	.string "Ho ricevuto i migliori insegnamenti\n"
	.string "per giungere a questi livelli.\p"
	.string "Non perderò un'altra volta!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro_IT::
	.string "PAUL: YUKI, mia cara, insieme non\n"
	.string "possiamo proprio perdere!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro_IT::
	.string "YUKI: Non farò certamente perdere\n"
	.string "il mio maestro, PAUL!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro_IT::
	.string "Hai scoperto qualcosa sulla\n"
	.string "sala di pietra?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro_IT::
	.string "Pare che qui dentro dorma un\n"
	.string "POKéMON speciale!$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro_IT::
	.string "Il mio maestro mi sta dando altre\n"
	.string "lezioni di pittura.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro_IT::
	.string "Oggi, oltre alla lezione, torneremo\n"
	.string "a vedere la cripta!$"
