Text_FirstShouldRestoreMonsHealth_IT::
	.string "Ora rimetterò in sesto la tua\n"
	.string "squadra di POKéMON.$"

Text_MonsHealedShouldBuyPotions_IT::
	.string "Bene, ora la tua squadra di\n"
	.string "POKéMON è in perfetta forma.\p"
	.string "Se i tuoi POKéMON perdono PS,\n"
	.string "torna a trovarmi!\p"
	.string "Parti per un lungo viaggio? Allora,\n"
	.string "passa dal POKéMON-MARKET a\lcomprare qualche POZIONE!$"

Text_MonsHealed_IT::
	.string "Ora la tua squadra di POKéMON\n"
	.string "è in perfetta forma!\p"
	.string "In bocca al lupo!$"

Text_HadQuiteAnExperienceTakeRest_IT::
	.string "MAMMA: {PLAYER}!\p"
	.string "Sembra proprio che tu stia\n"
	.string "vivendo una grande avventura!\p"
	.string "Ora, però, dovresti riposarti un\n"
	.string "po'.$"

Text_MomExplainHPGetPotions_IT::
	.string "MAMMA: Perfetto!\n"
	.string "Ora tu e i tuoi POKéMON siete in\lgran forma!\p"
	.string "Ho appena sentito il PROF. OAK.\p"
	.string "Mi ha detto che l'energia dei\n"
	.string "POKéMON si misura in PS.\p"
	.string "Se i tuoi POKéMON perdono PS,\n"
	.string "possono recuperarli in un CENTRO\lPOKéMON.\p"
	.string "Un buon ALLENATORE ha sempre con\n"
	.string "sé qualche POZIONE: si possono\lacquistare in un POKéMON-MARKET.\p"
	.string "Mi aspetto grandi cose da te!\p"
	.string "Fai attenzione!$"

Text_WhitedOutLostMoney_IT::
	.string "{PLAYER} non ha più POKéMON utili!\p"
	.string "{PLAYER}, nel panico, ha perso\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} è fuori combattimento!$"

Text_WhitedOut_IT::
	.string "{PLAYER} non ha più POKéMON utili!\p"
	.string "{PLAYER} è fuori gioco!$"
