
@ Unused, from R/S
Text_DoorOpenedFarAway_IT::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall_IT::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments_IT::
	.string "Sono spiacente.\n"
	.string "Il CLUB WIRELESS POKéMON\lè chiuso per lavori.$"

Text_AppearsToBeUndergoingAdjustments_IT::
	.string "Sembra che sia chiuso per lavori.$"

Text_HandedOverItem_IT::
	.string "{PLAYER} cede\n"
	.string "{STR_VAR_1}.$"

Text_GiveNicknameToThisMon_IT::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_1}?$"
