Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend_ES::
    .string "¡Voy a darme una vuelta con mi\n"
    .string "novia!$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes_ES::
    .string "¡Vamos a pedalear juntos!$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Es el CENTRO COMERCIAL\n"
    .string "de CIUDAD AZULONA!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Hay un largo camino sobre\n"
    .string "el agua!$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40_ES::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si atrapaste 40 tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "MON. AMULETO!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "40 tipos de POKéMON?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo_ES::
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide_ES::
    .string "¡{PLAYER} obtuvo MON. AMULETO\n"
    .string "de manos del AYUDANTE!$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin_ES::
    .string "Una MONEDA AMULETO es un objeto\n"
    .string "que puede llevar un POKéMON.\p"
    .string "Si gana el POKéMON que la tenga,\n"
    .string "conseguirás más dinero.$"
