Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend_FR::
	.string "Je vais me faire une virée avec ma\n"
	.string "p'tite copine!$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes_FR::
	.string "On va pédaler ensemble!$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore_FR::
	.string "Vous regardez dans les jumelles…\p"
	.string "Vous voyez le CENTRE COMMERCIAL\n"
	.string "de CELADOPOLE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater_FR::
	.string "Vous regardez dans les jumelles…\p"
	.string "Vous voyez un grand ponton!$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40_FR::
	.string "Salut! Tu te rappelles?\n"
	.string "Je suis un assistant du PROF. CHEN!\p"
	.string "Si tu attrapes 40 POKéMON\n"
	.string "différents, je suis censé\l"
	.string "t'offrir cette PIECE RUNE!\p"
	.string "Alors {PLAYER}, as-tu attrapé au\n"
	.string "moins 40 POKéMON différents?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo_FR::
	.string "Super! Tu as {STR_VAR_3} POKéMON\n"
	.string "différents!\p"
	.string "Félicitations!\n"
	.string "Voici ta récompense!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide_FR::
	.string "{PLAYER} obtient une\n"
	.string "PIECE RUNE!$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin_FR::
	.string "Une PIECE RUNE doit être tenue\n"
	.string "par un POKéMON.\p"
	.string "Si ce POKéMON apparaît dans une\n"
	.string "victoire, tu reçois plus d'argent.$"

