SafariZone_East_Text_HowManyDidYouCatch_ES::
    .string "¿Cuántos has capturado? ¡Yo estoy\n"
    .string "agotado de tanto trabajar!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile_ES::
    .string "¡Capturé un CHANSEY!\p"
    .string "¡Y por eso todos mis esfuerzos\n"
    .string "han merecido la pena!$"

SafariZone_East_Text_TiredFromAllTheFun_ES::
    .string "¡Ufff!\n"
    .string "¡Estoy agotado de tanta diversión!$"
