FuchsiaCity_Text_DidYouTrySafariGame_ES::
    .string "¿Has probado el JUEGO del SAFARI?\p"
    .string "Algunos POKéMON sólo pueden ser\n"
    .string "atrapados allí.$"

FuchsiaCity_Text_SafariZoneZooInFront_ES::
    .string "En la ZONA del SAFARI hay un zoo\n"
    .string "delante de la entrada.\p"
    .string "¡En su interior está el JUEGO del\n"
    .string "SAFARI, para atrapar POKéMON!$"

FuchsiaCity_Text_WheresSara_ES::
    .string "ENRIQUE: ¿Dónde estará SARA?\n"
    .string "Quedamos en vernos aquí.$"

FuchsiaCity_Text_ItemBallInThere_ES::
    .string "Ese objeto redondo de ahí...\n"
    .string "¿Lo quieres?\p"
    .string "¡Yo también! ¡Anda, es un POKéMON!$"

FuchsiaCity_Text_CitySign_ES::
    .string "¡Mirad CIUDAD FUCSIA!\n"
    .string "¡La pasión rosa!$"

FuchsiaCity_Text_SafariZoneSign_ES::
    .string "ZONA SAFARI:\n"
    .string "PARAÍSO-POKéMON$"

FuchsiaCity_Text_SafariGameSign_ES::
    .string "JUEGO DEL SAFARI:\n"
    .string "¡ATRAPA-POKéMON!$"

FuchsiaCity_Text_WardensHomeSign_ES::
    .string "CASA DEL GUARDA\n"
    .string "DEL SAFARI$"

FuchsiaCity_Text_SafariZoneOfficeSign_ES::
    .string "ZONA SAFARI:\n"
    .string "PARAÍSO-POKéMON\l"
    .string "OFICINA ZONA SAFARI$"

FuchsiaCity_Text_GymSign_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\l"
    .string "El venenoso maestro ninja.$"

FuchsiaCity_Text_ChanseySign_ES::
    .string "Nombre: CHANSEY\n"
    .string "¡Atrapar uno es una cuestión\l"
    .string "de suerte!$"

FuchsiaCity_Text_VoltorbSign_ES::
    .string "Nombre: VOLTORB\n"
    .string "La viva imagen de una POKé BALL.$"

FuchsiaCity_Text_KangaskhanSign_ES::
    .string "Nombre: KANGASKHAN\n"
    .string "Un POKéMON maternal que cría a sus\l"
    .string "hijos en una bolsa de su barriga.$"

FuchsiaCity_Text_SlowpokeSign_ES::
    .string "Nombre: SLOWPOKE\n"
    .string "Simpático y de movimientos\l"
    .string "muy lentos.$"

FuchsiaCity_Text_LaprasSign_ES::
    .string "Nombre: LAPRAS\n"
    .string "También conocido como el rey\l"
    .string "de los mares.$"

FuchsiaCity_Text_OmanyteSign_ES::
    .string "Nombre: OMANYTE\n"
    .string "Un POKéMON que fue regenerado\l"
    .string "a partir de un fósil.$"

FuchsiaCity_Text_KabutoSign_ES::
    .string "Nombre: KABUTO\n"
    .string "Un POKéMON que fue regenerado\l"
    .string "a partir de un fósil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis_ES::
    .string "……$"

Text_SubstituteTeach_ES::
    .string "Me encantaría ser el bebé\n"
    .string "de un KANGASKHAN.\p"
    .string "No me importaría nada ocupar\n"
    .string "el lugar del bebé...\p"
    .string "Y acurrucarme en la bolsa de la\n"
    .string "barriga de KANGASKHAN.\p"
    .string "Pero los POKéMON son los únicos\n"
    .string "que pueden usar SUSTITUTO...\p"
    .string "¿Quieres que le enseñe SUSTITUTO\n"
    .string "a uno de tus POKéMON?$"

Text_SubstituteDeclined_ES::
    .string "¿En serio?\n"
    .string "¡Pero si SUSTITUTO está genial!$"

Text_SubstituteWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe SUSTITUTO?$"

Text_SubstituteTaught_ES::
    .string "¡Ay, lo que daría por acurrucarme\n"
    .string "en la panza de un KANGASKHAN!$"

FuchsiaCity_Text_MyFatherIsGymLeader_ES::
    .string "Mi padre es el LÍDER del GIMNASIO\n"
    .string "de este pueblo.\p"
    .string "Yo me estoy entrenando para usar\n"
    .string "POKéMON del tipo VENENO igual\l"
    .string "que hace mi padre.$"
