FuchsiaCity_Text_DidYouTrySafariGame_IT::
    .string "Hai provato il GIOCO SAFARI?\p"
    .string "Alcuni POKéMON possono essere presi\n"
    .string "solo là.$"

FuchsiaCity_Text_SafariZoneZooInFront_IT::
    .string "Dietro lo zoo si trova la ZONA\n"
    .string "SAFARI.\p"
    .string "Lì si svolge il GIOCO SAFARI per\n"
    .string "catturare POKéMON!$"

FuchsiaCity_Text_WheresSara_IT::
    .string "ERIK: Dov'è SARA?\n"
    .string "Dovevamo incontrarci qui.$"

FuchsiaCity_Text_ItemBallInThere_IT::
    .string "Se da una palla esce un\n"
    .string "POKéMON, è una POKé BALL!$"

FuchsiaCity_Text_CitySign_IT::
    .string "FUCSIAPOLI\n"
    .string "Passione Rosa!$"

FuchsiaCity_Text_SafariZoneSign_IT::
    .string "ZONA SAFARI\n"
    .string "PARADISO POKéMON!$"

FuchsiaCity_Text_SafariGameSign_IT::
    .string "GIOCO SAFARI\n"
    .string "ACCHIAPPAPOKéMON!$"

FuchsiaCity_Text_WardensHomeSign_IT::
    .string "CASA del GUARDIANO\n"
    .string "della ZONA SAFARI$"

FuchsiaCity_Text_SafariZoneOfficeSign_IT::
    .string "ZONA SAFARI\n"
    .string "PARADISO POKéMON!\l"
    .string "UFFICIO$"

FuchsiaCity_Text_GymSign_IT::
    .string "CAPOPALESTRA di FUCSIAPOLI:\n"
    .string "KOGA\l"
    .string "Il velenoso maestro ninja$"

FuchsiaCity_Text_ChanseySign_IT::
    .string "Nome: CHANSEY\p"
    .string "Prenderne uno è tutta questione di\n"
    .string "fortuna!$"

FuchsiaCity_Text_VoltorbSign_IT::
    .string "Nome: VOLTORB\n"
    .string "Proprio come una POKé BALL.$"

FuchsiaCity_Text_KangaskhanSign_IT::
    .string "Nome: KANGASKHAN\p"
    .string "Un POKéMON materno che tiene il\n"
    .string "suo cucciolo nel marsupio.$"

FuchsiaCity_Text_SlowpokeSign_IT::
    .string "Nome: SLOWPOKE\n"
    .string "Amichevole, dai movimenti lenti.$"

FuchsiaCity_Text_LaprasSign_IT::
    .string "Nome: LAPRAS\n"
    .string "Detto anche il re dei mari.$"

FuchsiaCity_Text_OmanyteSign_IT::
    .string "Nome: OMANYTE\p"
    .string "Un POKéMON rarissimo, risuscitato\n"
    .string "da un fossile.$"

FuchsiaCity_Text_KabutoSign_IT::
    .string "Nome: KABUTO\p"
    .string "Un POKéMON rarissimo, risuscitato\n"
    .string "da un fossile.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis_IT::
    .string "……$"

Text_SubstituteTeach_IT::
    .string "Come mi piacerebbe essere un\n"
    .string "cucciolo di KANGASKHAN!\p"
    .string "Vorrei sostituirmi al suo piccolo,\n"
    .string "anche solo per cinque minuti!\p"
    .string "Ma devo smettere di fantasticare!\p"
    .string "Ah, a proposito di sostituzioni:\n"
    .string "vuoi che insegni SOSTITUTO ad\l"
    .string "uno dei tuoi POKéMON?$"

Text_SubstituteDeclined_IT::
    .string "Davvero non vuoi?\n"
    .string "Guarda che è divertente!$"

Text_SubstituteWhichMon_IT::
    .string "A quale POKéMON vuoi che insegni\n"
    .string "SOSTITUTO?$"

Text_SubstituteTaught_IT::
    .string "Non sai quanto darei per entrare\n"
    .string "nel marsupio di un KANGASKHAN!$"

FuchsiaCity_Text_MyFatherIsGymLeader_IT::
    .string "Mio padre è il CAPOPALESTRA\n"
    .string "di questa città.\p"
    .string "Anch'io mi alleno con i POKéMON\n"
    .string "di tipo VELENO, proprio come lui!$"

