ThreeIsland_DunsparceTunnel_Text_ProspectingForGold_DE::
	.string "Heh, du!\n"
	.string "Wie geht es dir?\p"
	.string "Du fragst, was ich hier mache?\n"
	.string "Warum? Ich suche nach Gold!\p"
	.string "Wenn ich reich bin, kaufe ich\n"
	.string "ein Haus in KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou_DE::
	.string "Heh, du! Wie geht es dir?\n"
	.string "Hast du schon gehört? Ich habe\l"
	.string "Gold gefunden!\l"
	.string "Erinnerst du dich, dass ich danach\l"
	.string "gesucht habe?\p"
	.string "Du kannst dir gar nicht vorstellen,\n"
	.string "wie glücklich ich bin.\p"
	.string "Ich zeig es dir!\n"
	.string "Das ist für dich!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget_DE::
	.string "Ich kann dir keine weisen\n"
	.string "Ratschläge mitgeben, das hier muss\l"
	.string "ausreichen!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull_DE::
	.string "Ups! Dein BEUTEL ist voll!\n"
	.string "Ich gebe es dir später!$"

