ThreeIsland_DunsparceTunnel_Text_ProspectingForGold_IT::
    .string "Ciao, come va?\p"
    .string "Vuoi sapere cosa ci faccio qui?\n"
    .string "Beh, cerco l'oro!\p"
    .string "Quando ne avrò trovato abbastanza,\n"
    .string "comprerò casa a KANTO!$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou_IT::
    .string "Ehi, ciao!\n"
    .string "Non ci crederai, ma ho trovato\l"
    .string "l'oro!!!\p"
    .string "Non so se ti avevo detto che lo\n"
    .string "stavo cercando!\p"
    .string "Sono al settimo cielo!\n"
    .string "Ecco, questa è per te!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget_IT::
    .string "È una PEPITA!\p"
    .string "Spero che ti piaccia!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull_IT::
    .string "Ehi, il tuo ZAINO è pieno!\n"
    .string "Ti darò più tardi il mio regalo!$"

