ThreeIsland_DunsparceTunnel_Text_ProspectingForGold_ES::
    .string "Eh, ¿qué tal?\p"
    .string "¿Que qué hago aquí?\n"
    .string "Pues estoy buscando oro.\p"
    .string "Cuando consiga una fortuna,\n"
    .string "me compraré una casita en KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou_ES::
    .string "Eh, ¿cómo lo llevas?\n"
    .string "¿Sabes qué? ¡He encontrado oro!\p"
    .string "¿Recuerdas que te dije que estaba\n"
    .string "buscando?\p"
    .string "¡No te puedes ni imaginar lo feliz\n"
    .string "que soy!\p"
    .string "Toma, anda.\n"
    .string "Compartiré un poco contigo.$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget_ES::
    .string "Es una PEPITA.\p"
    .string "No puedo darte pepitas de la\n"
    .string "sabiduría, ¡sólo esto!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull_ES::
    .string "Vaya, tienes la MOCHILA hasta\n"
    .string "arriba... Bueno, otra vez será.$"
