ThreeIsland_Text_IslandSign_ES::
    .string "ISLA TERA\n"
    .string "Isla familiar para familiares.$"

ThreeIsland_Text_IslandBelongsToUs_ES::
    .string "¡Eeeeeh!\p"
    .string "¡A partir de hoy, esta isla\n"
    .string "nos pertenece!$"

ThreeIsland_Text_GoBackToKanto_ES::
    .string "¡Aquí no queremos a nadie que nos\n"
    .string "moleste y nos traiga problemas!\p"
    .string "¡MARCHAOS A KANTO!$"

ThreeIsland_Text_BossIsOnHisWay_ES::
    .string "Vete a chillar a otra parte,\n"
    .string "nuestro jefe está en camino.\p"
    .string "¡Cuando llegue, vas a ver de lo\n"
    .string "que somos capaces con las motos!\p"
    .string "¡Vas a flipar!$"

ThreeIsland_Text_GetOffIslandNow_ES::
    .string "¿Cómo? ¡Ni se os ocurra!\n"
    .string "¡FUERA DE LA ISLA AHORA MISMO!$"

ThreeIsland_Text_WhosGonnaMakeMe_ES::
    .string "¿Porque tú lo digas?$"

ThreeIsland_Text_AreYouBossGoBackToKanto_ES::
    .string "¿Eres tú el jefe?\n"
    .string "¡A KANTO ahora mismo!$"

ThreeIsland_Text_JustGotHerePal_ES::
    .string "Eh, que yo acabo de llegar,\n"
    .string "colega.\p"
    .string "No entiendo por qué te pones tan\n"
    .string "borde. ¡Menuda bienvenida, majo!$"

ThreeIsland_Text_FollowersRaisingHavoc_ES::
    .string "Tu pandillita se ha puesto en plan\n"
    .string "chulo con las motos y se ha pasado\l"
    .string "un pelín.\p"
    .string "Y a la gente de la isla no le ha\n"
    .string "hecho nada de gracia.$"

ThreeIsland_Text_OughtToBeThankingUs_ES::
    .string "Me dejas a cuadros.\p"
    .string "¡Pero si aquí se aburren hasta\n"
    .string "las piedras!\p"
    .string "Deberíais estar agradecidos de\n"
    .string "que hayamos dado vidilla a este\l"
    .string "muermo de isla.\p"
    .string "Pero bueno, si insistes en que\n"
    .string "nos vayamos...$"

ThreeIsland_Text_YouCowardsToughInPack_ES::
    .string "Grrrr... Sois unos cobardes...\n"
    .string "Y unos pesados...$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring_ES::
    .string "Pero ¿qué miras? ¿Nunca te han\n"
    .string "dicho que no se debe mirar tan\l"
    .string "descaradamente a nadie?\p"
    .string "¿Quieres algo o qué?$"

ThreeIsland_Text_ThatsSmart_ES::
    .string "Estupendo. Así me gusta, que\n"
    .string "te mantengas al margen de esto.$"

ThreeIsland_Text_Biker1Intro_ES::
    .string "Eh, eres muy valiente.\n"
    .string "Vas a salir perdiendo, pero...$"

ThreeIsland_Text_Biker1Defeat_ES::
    .string "¡¿Qué?!...\n"
    .string "Pero ¿tú de dónde sales?$"

ThreeIsland_Text_Biker1PostBattle_ES::
    .string "¡Que no se te ocurra reírte!$"

ThreeIsland_Text_Biker2Intro_ES::
    .string "Pero ¿tú no eres de KANTO?\n"
    .string "¡Pues deberías estar de nuestro\l"
    .string "lado!$"

ThreeIsland_Text_Biker2Defeat_ES::
    .string "Bueno, ¡ya está bien!$"

ThreeIsland_Text_Biker2PostBattle_ES::
    .string "Pero ¿a ti qué te pasa?\n"
    .string "¡Ya te vale!$"

ThreeIsland_Text_Biker3Intro_ES::
    .string "Le dijimos a nuestro jefe que\n"
    .string "viniera ¡y tú incordiando!\p"
    .string "¡Eres un petardo!$"

ThreeIsland_Text_Biker3Defeat_ES::
    .string "Ufff...$"

ThreeIsland_Text_Biker3PostBattle_ES::
    .string "Jefe, ¡no podemos dejar que\n"
    .string "nos saquen los colores!$"

ThreeIsland_Text_PaxtonIntro_ES::
    .string "He estado observándote y creo que\n"
    .string "te has pasado.\p"
    .string "¿Pero tú, de parte de quién estás?\p"
    .string "Ahora te las quieres ver conmigo,\n"
    .string "¿no?$"

ThreeIsland_Text_PaxtonDefeat_ES::
    .string "Mira, ya me tienes harto.\n"
    .string "¡Nos piramos!\p"
    .string "¡Estábamos deseando\n"
    .string "marcharnos!$"

ThreeIsland_Text_PaxtonPostBattle_ES::
    .string "¡Hala, que te lo pases bien\n"
    .string "en este petardo de isla!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt_ES::
    .string "¡Muchas gracias! ¡La gentuza esa\n"
    .string "ha revolucionado al personal!\p"
    .string "Anda, tus POKéMON están heridos\n"
    .string "por mi culpa...$"

ThreeIsland_Text_GivenFullRestore_ES::
    .string "{PLAYER} recibió un RESTAU. TODO.$"

ThreeIsland_Text_OhYourBagIsFull_ES::
    .string "Vaya...\n"
    .string "La MOCHILA está llena...$"

ThreeIsland_Text_YouveGotImpressiveMons_ES::
    .string "Tienes unos POKéMON\n"
    .string "espectaculares.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge_ES::
    .string "Sería estupendo que alguien como\n"
    .string "tú viviera aquí.\p"
    .string "Espero que te quedes un tiempo\n"
    .string "al menos.\p"
    .string "¿Cómo?\n"
    .string "¿Que estás buscando a PEDRITA?\p"
    .string "PEDRITA se fue en dirección al\n"
    .string "PUENTE UNIÓN hace un rato...$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain_ES::
    .string "ISLA TERA es la isla más poblada\n"
    .string "de esta zona.\p"
    .string "Vale que no sea la más animada,\n"
    .string "pero mejor así que tener a los\l"
    .string "salvajes de las motos por aquí.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame_ES::
    .string "Voy a entrenar a mi DODUO en el\n"
    .string "BOSQUE BAYA.\p"
    .string "Cuando evolucione, participaré\n"
    .string "en algún juego en ISLA SECUNDA.$"

ThreeIsland_Text_Doduo_ES::
    .string "DODUO: ¡Dodu, odudodu!$"
