CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji_FR::
	.string "C'est une photo d'AUGUSTE\n"
	.string "et de MR. FUJI.\p"
	.string "Ils sont côte à côte en souriant.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively_FR::
	.string "Ici on étudie les POKéMON.\p"
	.string "On nous amène souvent des POKéMON\n"
	.string "rares pour les étudier.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji_FR::
	.string "Voici une photo du créateur de ce\n"
	.string "LABO: Le DR FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign_FR::
	.string "LABO POKéMON\n"
	.string "Salle de réunion$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign_FR::
	.string "Département Recherche et\n"
	.string "Développement du LABO POKéMON$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign_FR::
	.string "LABO POKéMON\n"
	.string "Salle de test$"

