CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji_DE::
	.string "Ein Foto von PYRO und MR. FUJI!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively_DE::
	.string "Wir erforschen hier POKéMON.\p"
	.string "Wir erstellen oft Gutachten über\n"
	.string "seltene POKéMON.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji_DE::
	.string "Der Gründer des LABORATORIUMS,\n"
	.string "DR. FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign_DE::
	.string "POKéMON-LABOR\n"
	.string "Konferenzraum$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign_DE::
	.string "POKéMON-LABOR\n"
	.string "Forschung und Entwicklung$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign_DE::
	.string "POKéMON-LABOR\n"
	.string "Versuchsabteilung$"

