CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji_ES::
    .string "Una foto de BLAINE\n"
    .string "y el SR. FUJI...\p"
    .string "Aparecen juntos con una sonrisa\n"
    .string "de oreja a oreja.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively_ES::
    .string "Aquí estudiamos a los POKéMON.\p"
    .string "La gente suele traernos POKéMON\n"
    .string "raros para analizarlos.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji_ES::
    .string "¡Una foto del fundador del\n"
    .string "LABORATORIO, el DR. FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign_ES::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de reuniones$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign_ES::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de I + D$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign_ES::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de pruebas$"
