MtMoon_1F_Text_MarcosIntro_IT::
    .string "WOW!\n"
    .string "Mi hai spaventato!$"

MtMoon_1F_Text_MarcosDefeat_IT::
    .string "Wow!\n"
    .string "Mi hai spaventato di nuovo!$"

MtMoon_1F_Text_MarcosPostBattle_IT::
    .string "Questo non è posto per bambini!$"

MtMoon_1F_Text_JoshIntro_IT::
    .string "Anche tu qui per esplorare?$"

MtMoon_1F_Text_JoshDefeat_IT::
    .string "Perdere fa male!$"

MtMoon_1F_Text_JoshPostBattle_IT::
    .string "Sono qui per far colpo sulle\n"
    .string "ragazze!$"

MtMoon_1F_Text_MiriamIntro_IT::
    .string "Wow! È molto più grande di quanto\n"
    .string "pensassi!$"

MtMoon_1F_Text_MiriamDefeat_IT::
    .string "Oh no!\n"
    .string "Ho perso!$"

MtMoon_1F_Text_MiriamPostBattle_IT::
    .string "Come si esce di qui?$"

MtMoon_1F_Text_JovanIntro_IT::
    .string "Osi strisciarmi accanto?!$"

MtMoon_1F_Text_JovanDefeat_IT::
    .string "I miei POKéMON non ce l'hanno\n"
    .string "fatta!$"

MtMoon_1F_Text_JovanPostBattle_IT::
    .string "Devo catturare POKéMON più forti!$"

MtMoon_1F_Text_IrisIntro_IT::
    .string "Che?\n"
    .string "Aspetto che arrivino i miei amici.$"

MtMoon_1F_Text_IrisDefeat_IT::
    .string "Ho perso?$"

MtMoon_1F_Text_IrisPostBattle_IT::
    .string "Si dice che qui ci siano dei fossili\n"
    .string "molto rari.$"

MtMoon_1F_Text_KentIntro_IT::
    .string "Nella grotta ci sono tipi loschi.\n"
    .string "Tu, chi sei?$"

MtMoon_1F_Text_KentDefeat_IT::
    .string "Ehi, mi hai beccato!$"

MtMoon_1F_Text_KentPostBattle_IT::
    .string "Li ho visti!\n"
    .string "Sono quelli di TEAM ROCKET!\l"
    .string "È certo!$"

MtMoon_1F_Text_RobbyIntro_IT::
    .string "Passa per questa grotta e sarai a\n"
    .string "CELESTOPOLI!$"

MtMoon_1F_Text_RobbyDefeat_IT::
    .string "Ah!\n"
    .string "Ho perso!$"

MtMoon_1F_Text_RobbyPostBattle_IT::
    .string "ZUBAT è tosto!\n"
    .string "Catturarne uno ti sarà molto utile!$"

MtMoon_1F_Text_ZubatIsABloodsucker_IT::
    .string "Attento!\n"
    .string "ZUBAT è una sanguisuga!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils_IT::
    .string "Ciao, sono venuto sul MONTE LUNA\n"
    .string "per cercare fossili sottoterra.\p"
    .string "A volte viene ad aiutarmi BROCK \n"
    .string "da PLUMBEOPOLI.$"

