MtMoon_1F_Text_MarcosIntro_ES::
    .string "¡GUAU!\n¡Me has impresionado!\l"
    .string "¡Pero si eres muy joven!$"

MtMoon_1F_Text_MarcosDefeat_ES::
    .string "¡Uau!\n"
    .string "¡Has vuelto a impresionarme!$"

MtMoon_1F_Text_MarcosPostBattle_ES::
    .string "¡No tienes edad para estar aquí!$"

MtMoon_1F_Text_JoshIntro_ES::
    .string "¿Estás aquí para explorar?$"

MtMoon_1F_Text_JoshDefeat_ES::
    .string "¡Perder es lo peor!$"

MtMoon_1F_Text_JoshPostBattle_ES::
    .string "¡Vine aquí para impresionar\n"
    .string "a las chicas!$"

MtMoon_1F_Text_MiriamIntro_ES::
    .string "¡Uau! ¡Esto es mucho más grande\n"
    .string "de lo que creía!$"

MtMoon_1F_Text_MiriamDefeat_ES::
    .string "¡Oh!\n¡He perdido!$"

MtMoon_1F_Text_MiriamPostBattle_ES::
    .string "¿Cómo se sale de aquí?$"

MtMoon_1F_Text_JovanIntro_ES::
    .string "¡Eh!\n"
    .string "¡No te pases conmigo!$"

MtMoon_1F_Text_JovanDefeat_ES::
    .string "¡Mis POKéMON no lo han conseguido!$"

MtMoon_1F_Text_JovanPostBattle_ES::
    .string "¡Debo encontrar POKéMON\n"
    .string "más fuertes!$"

MtMoon_1F_Text_IrisIntro_ES::
    .string "¿Qué?\n"
    .string "Estoy esperando aquí a mis amigos.$"

MtMoon_1F_Text_IrisDefeat_ES::
    .string "¿He perdido?$"

MtMoon_1F_Text_IrisPostBattle_ES::
    .string "Dicen que aquí hay unos fósiles\n"
    .string "muy raros.$"

MtMoon_1F_Text_KentIntro_ES::
    .string "En la cueva hay unos hombres\n"
    .string "muy sospechosos. ¿Y tú, qué?$"

MtMoon_1F_Text_KentDefeat_ES::
    .string "¡Me has ganado!$"

MtMoon_1F_Text_KentPostBattle_ES::
    .string "¡Los he visto!\n"
    .string "¡Son del TEAM ROCKET! ¡Seguro!$"

MtMoon_1F_Text_RobbyIntro_ES::
    .string "¡Cruza esta cueva y llegarás\n"
    .string "a CIUDAD CELESTE!$"

MtMoon_1F_Text_RobbyDefeat_ES::
    .string "He perdido.$"

MtMoon_1F_Text_RobbyPostBattle_ES::
    .string "¡ZUBAT es muy fuerte!\n"
    .string "¡Atrapar uno sería muy útil!$"

MtMoon_1F_Text_ZubatIsABloodsucker_ES::
    .string "¡Cuidado!\n"
    .string "¡Los ZUBAT son unos chupasangre!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils_ES::
    .string "Estoy buscando fósiles en las\n"
    .string "entrañas del MT. MOON.\p"
    .string "A veces me ayuda BROCK,\n"
    .string "del GIMNASIO de PLATEADA.$"
