MtMoon_1F_Text_MarcosIntro_DE::
	.string "Hilfe! Überfall!\n"
	.string "Ach, du bist ja nur ein Kind!$"

MtMoon_1F_Text_MarcosDefeat_DE::
	.string "Wow!\n"
	.string "Du hast mich total überrumpelt!!!$"

MtMoon_1F_Text_MarcosPostBattle_DE::
	.string "Hier ist kein Spielplatz.\n"
	.string "Zieh Leine, Kiddie!$"

MtMoon_1F_Text_JoshIntro_DE::
	.string "Bist du auch auf Forschungsreise?$"

MtMoon_1F_Text_JoshDefeat_DE::
	.string "So ein Mist!\n"
	.string "Verloren!$"

MtMoon_1F_Text_JoshPostBattle_DE::
	.string "Ich bin hier, weil die Mädchen auf\n"
	.string "harte Kerle wie mich stehen!$"

MtMoon_1F_Text_MiriamIntro_DE::
	.string "Wow, hier drinnen kann man sich\n"
	.string "leicht verlaufen!$"

MtMoon_1F_Text_MiriamDefeat_DE::
	.string "Nein!\n"
	.string "Ich habe verloren!$"

MtMoon_1F_Text_MiriamPostBattle_DE::
	.string "Wie kommt man hier bloß wieder\n"
	.string "heraus?$"

MtMoon_1F_Text_JovanIntro_DE::
	.string "Heh!\n"
	.string "Schleich nicht so herum!$"

MtMoon_1F_Text_JovanDefeat_DE::
	.string "Meine POKéMON bringen es nicht!$"

MtMoon_1F_Text_JovanPostBattle_DE::
	.string "Ich muss stärkere POKéMON fangen!$"

MtMoon_1F_Text_IrisIntro_DE::
	.string "Was gibt's? Meine Kumpels müssten\n"
	.string "gleich hier sein.$"

MtMoon_1F_Text_IrisDefeat_DE::
	.string "Ich hab verloren?$"

MtMoon_1F_Text_IrisPostBattle_DE::
	.string "Gerüchten zufolge soll es hier sehr\n"
	.string "seltene Fossilien geben.$"

MtMoon_1F_Text_KentIntro_DE::
	.string "Wer da? Wohin man schaut: Überall\n"
	.string "nur zwielichtige Gestalten!$"

MtMoon_1F_Text_KentDefeat_DE::
	.string "Du hast mich eiskalt erwischt!$"

MtMoon_1F_Text_KentPostBattle_DE::
	.string "Ohne Zweifel!\n"
	.string "Die Typen waren vom TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro_DE::
	.string "Du erreichst AZURIA CITY, wenn du\n"
	.string "es durch diese Höhle schaffst!$"

MtMoon_1F_Text_RobbyDefeat_DE::
	.string "Ich hab verloren...$"

MtMoon_1F_Text_RobbyPostBattle_DE::
	.string "ZUBAT ist recht widerspenstig, kann\n"
	.string "im Kampf jedoch sehr nützlich sein!$"

MtMoon_1F_Text_ZubatIsABloodsucker_DE::
	.string "Sei vorsichtig!\n"
	.string "ZUBAT ist ein Blutsauger!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils_DE::
	.string "Hallo! Ich grabe Fossilien hier am\n"
	.string "MONDBERG aus.\p"
	.string "Manchmal hilft mir ROCKO, der\n"
	.string "ARENALEITER von MARMORIA CITY.$"

