MtMoon_1F_Text_MarcosIntro_FR::
	.string "YAHA!\n"
	.string "Tu m'as fait peur! Quoi?\l"
	.string "Mais t'es super jeune!$"

MtMoon_1F_Text_MarcosDefeat_FR::
	.string "Whoa!\n"
	.string "Tu m'as encore fait peur!!!$"

MtMoon_1F_Text_MarcosPostBattle_FR::
	.string "Cet endroit n'est pas pour les\n"
	.string "mioches comme toi!$"

MtMoon_1F_Text_JoshIntro_FR::
	.string "Tu es aussi ici pour explorer?$"

MtMoon_1F_Text_JoshDefeat_FR::
	.string "Hmm! Perdre, ça craint\n"
	.string "vraiment!$"

MtMoon_1F_Text_JoshPostBattle_FR::
	.string "J'suis venu jusque-là pour\n"
	.string "impressionner les filles!$"

MtMoon_1F_Text_MiriamIntro_FR::
	.string "Houlà! C'est plus balèze que\n"
	.string "j'croyais, ici!$"

MtMoon_1F_Text_MiriamDefeat_FR::
	.string "RHAA!\n"
	.string "J'ai perdu!$"

MtMoon_1F_Text_MiriamPostBattle_FR::
	.string "Comment on fait pour sortir d'ici?$"

MtMoon_1F_Text_JovanIntro_FR::
	.string "Oh!\n"
	.string "Tu m'cherches ou quoi?$"

MtMoon_1F_Text_JovanDefeat_FR::
	.string "Mes POKéMON sont nuls!$"

MtMoon_1F_Text_JovanPostBattle_FR::
	.string "J'dois m'trouver des POKéMON\n"
	.string "plus costauds!$"

MtMoon_1F_Text_IrisIntro_FR::
	.string "De quoi?\n"
	.string "J'attends mes potes ici.$"

MtMoon_1F_Text_IrisDefeat_FR::
	.string "Nan!\n"
	.string "J'ai perdu?$"

MtMoon_1F_Text_IrisPostBattle_FR::
	.string "Y paraît qu'il y a des fossiles\n"
	.string "très anciens dans le coin.$"

MtMoon_1F_Text_KentIntro_FR::
	.string "Dans les grottes, on trouve de\n"
	.string "la racaille. T'es qui toi?$"

MtMoon_1F_Text_KentDefeat_FR::
	.string "Ha!\n"
	.string "Tu m'as eu!$"

MtMoon_1F_Text_KentPostBattle_FR::
	.string "Je les ai vus!\n"
	.string "C'était la TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro_FR::
	.string "Je traverse ces grottes pour aller\n"
	.string "à AZURIA!$"

MtMoon_1F_Text_RobbyDefeat_FR::
	.string "J'ai…\n"
	.string "Perdu…$"

MtMoon_1F_Text_RobbyPostBattle_FR::
	.string "Les NOSFERAPTI sont puissants!\n"
	.string "En attraper peut être utile!$"

MtMoon_1F_Text_ZubatIsABloodsucker_FR::
	.string "Attention! Les NOSFERAPTI sont\n"
	.string "des suceurs de sang!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils_FR::
	.string "Salut! Je cherche des fossiles ici,\n"
	.string "sous le MONT SELENITE.\p"
	.string "PIERRE de l'ARENE d'ARGENTA\n"
	.string "vient souvent m'aider.$"

