PokemonMansion_B1F_Text_LewisIntro_ES::
    .string "¡Oh, oh!\n"
    .string "¿Dónde estoy ahora?$"

PokemonMansion_B1F_Text_LewisDefeat_ES::
    .string "¡Vaya!$"

PokemonMansion_B1F_Text_LewisPostBattle_ES::
    .string "Puedes recoger cosas del suelo.$"

PokemonMansion_B1F_Text_IvanIntro_ES::
    .string "Este lugar es ideal para un\n"
    .string "laboratorio.$"

PokemonMansion_B1F_Text_IvanDefeat_ES::
    .string "¿Era esto lo que querías?$"

PokemonMansion_B1F_Text_IvanPostBattle_ES::
    .string "¡Me encanta este sitio! ¡Es muy\n"
    .string "apropiado para mis estudios!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful_ES::
    .string "Diario: 1 de septiembre.\n"
    .string "MEWTWO es demasiado poderoso.\p"
    .string "No hemos sabido contener sus malos\n"
    .string "instintos.$"
