PokemonMansion_B1F_Text_LewisIntro_IT::
    .string "Ohoh!\n"
    .string "E adesso, dove sono?$"

PokemonMansion_B1F_Text_LewisDefeat_IT::
    .string "Ahi!$"

PokemonMansion_B1F_Text_LewisPostBattle_IT::
    .string "Puoi trovare oggetti sparsi\n"
    .string "ovunque, lasciati da chi\l"
    .string "abitava in questa villa.$"

PokemonMansion_B1F_Text_IvanIntro_IT::
    .string "Questo dev'essere stato\n"
    .string "un laboratorio.$"

PokemonMansion_B1F_Text_IvanDefeat_IT::
    .string "A cosa serviva quello?$"

PokemonMansion_B1F_Text_IvanPostBattle_IT::
    .string "Mi piace venire a studiare qui!\n"
    .string "Mi concentro meglio!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful_IT::
    .string "Diario: 1 settembre\n"
    .string "MEWTWO è davvero potente.\p"
    .string "Non riusciamo a contenere i suoi\n"
    .string "istinti feroci.$"

