PokemonMansion_B1F_Text_LewisIntro_DE::
	.string "Wo bin ich hier gelandet?$"

PokemonMansion_B1F_Text_LewisDefeat_DE::
	.string "Autsch!$"

PokemonMansion_B1F_Text_LewisPostBattle_DE::
	.string "Hier liegt viel nützliches Zeug\n"
	.string "herum!$"

PokemonMansion_B1F_Text_IvanIntro_DE::
	.string "Hier wäre der ideale Platz für ein\n"
	.string "Labor!$"

PokemonMansion_B1F_Text_IvanDefeat_DE::
	.string "Was hab ich nur falsch gemacht?$"

PokemonMansion_B1F_Text_IvanPostBattle_DE::
	.string "Hier gefällt es mir!\n"
	.string "Man kann prima forschen!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful_DE::
	.string "TAGEBUCH: 1. SEPTEMBER\n"
	.string "MEWTU wird immer stärker.\p"
	.string "Wir konnten die unkontrollierten\n"
	.string "Wutausbrüche nicht eindämmen!$"

