SevenIsland_TrainerTower_Text_DarioIntro_ES::
    .string "He notado que te acercabas.$"

SevenIsland_TrainerTower_Text_DarioDefeat_ES::
    .string "Me rindo...$"

SevenIsland_TrainerTower_Text_DarioPostBattle_ES::
    .string "Siento que te vas a encontrar\n"
    .string "con mucha gente.\p"
    .string "Establecerás cierta conexión\n"
    .string "mediante una extraña fuerza.$"

SevenIsland_TrainerTower_Text_RodetteIntro_ES::
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.$"

SevenIsland_TrainerTower_Text_RodetteDefeat_ES::
    .string "¡Tú sí que sabes entrenar POKéMON!$"

SevenIsland_TrainerTower_Text_RodettePostBattle_ES::
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.\p"
    .string "¿Te estarán esperando?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign_ES::
    .string "ENTRADA A LA TORRE DESAFÍO\n"
    .string "¡A por todas, ENTRENADORES!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead_ES::
    .string "HACIA LA TORRE DESAFÍO$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed_ES::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn_ES::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"
