SevenIsland_TrainerTower_Text_DarioIntro_FR::
	.string "Je savais que tu viendrais.$"

SevenIsland_TrainerTower_Text_DarioDefeat_FR::
	.string "Abandonne…$"

SevenIsland_TrainerTower_Text_DarioPostBattle_FR::
	.string "Dans le futur, je pressens que tu\n"
	.string "affronteras de nombreux DRESSEURS.\p"
	.string "Un lien étrange et invisible te\n"
	.string "reliera à eux.$"

SevenIsland_TrainerTower_Text_RodetteIntro_FR::
	.string "Quelque part sur cette île, des\n"
	.string "POKéMON spéciaux se reposent.$"

SevenIsland_TrainerTower_Text_RodetteDefeat_FR::
	.string "Je sens une grande force en toi!$"

SevenIsland_TrainerTower_Text_RodettePostBattle_FR::
	.string "Quelque part sur cette île, des\n"
	.string "POKéMON spéciaux se reposent.\p"
	.string "Se pourrait-il qu'ils attendent\n"
	.string "ta venue?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign_FR::
	.string "ENTREE de la TOUR DRESSEURS\n"
	.string "Relevez le défi!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead_FR::
	.string "TOUR DRESSEURS DROIT DEVANT$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed_FR::
	.string "トレーナータワーには\n"
	.string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn_FR::
	.string "トレーナータワーが　あいてる！\n"
	.string "さっそく　はいってみよう！$"

