SevenIsland_TrainerTower_Text_DarioIntro_IT::
    .string "Ho presagito il tuo arrivo!$"

SevenIsland_TrainerTower_Text_DarioDefeat_IT::
    .string "Mi arrendo…$"

SevenIsland_TrainerTower_Text_DarioPostBattle_IT::
    .string "Incontrerai molte persone sul\n"
    .string "tuo cammino.\p"
    .string "E ti collegherai con loro grazie\n"
    .string "ad uno strano potere!$"

SevenIsland_TrainerTower_Text_RodetteIntro_IT::
    .string "Ci sono POKéMON speciali che\n"
    .string "dormono su quest'isola.$"

SevenIsland_TrainerTower_Text_RodetteDefeat_IT::
    .string "Che ALLENATORE eccezionale!$"

SevenIsland_TrainerTower_Text_RodettePostBattle_IT::
    .string "Ci sono POKéMON speciali che\n"
    .string "dormono su quest'isola.\p"
    .string "Credi che ti stiano aspettando?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign_IT::
    .string "TORRE ALLENATORI\n"
    .string "Siete pronti per la sfida?$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead_IT::
    .string "Per la TORRE ALLENATORI$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed_IT::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn_IT::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

