SevenIsland_TrainerTower_Text_DarioIntro_DE::
	.string "Ich spürte, dass du kommst!$"

SevenIsland_TrainerTower_Text_DarioDefeat_DE::
	.string "Gib auf…$"

SevenIsland_TrainerTower_Text_DarioPostBattle_DE::
	.string "Ich sage dir voraus, dass du\n"
	.string "viele andere Leute triffst.\p"
	.string "Ich sehe, dass du durch eine\n"
	.string "merkwürdige Kraft mit ihnen\l"
	.string "verbunden bist.$"

SevenIsland_TrainerTower_Text_RodetteIntro_DE::
	.string "Irgendwo auf dieser Insel schlafen\n"
	.string "besondere POKéMON.$"

SevenIsland_TrainerTower_Text_RodetteDefeat_DE::
	.string "Was für ein TRAINER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle_DE::
	.string "Irgendwo auf dieser Insel schlafen\n"
	.string "besondere POKéMON.\p"
	.string "Kann es sein, dass sie auf dich\n"
	.string "warten?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign_DE::
	.string "EINGANG des TRAINERTURMs\n"
	.string "Fordere andere TRAINER heraus!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead_DE::
	.string "TRAINERTURM VORAUS$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed_DE::
	.string "トレーナータワーには\n"
	.string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn_DE::
	.string "トレーナータワーが　あいてる！\n"
	.string "さっそく　はいってみよう！$"

