VermilionCity_PokemonFanClub_Text_AdmirePikachusTail_ES::
    .string "¿No te gusta la adorable cola\n"
    .string "de mi PIKACHU?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute_ES::
    .string "¡Mi PIKACHU es el doble\n"
    .string "de gracioso que ése!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel_ES::
    .string "¡Me encanta mi SEEL!\p"
    .string "¡Chilla cuando lo abrazo!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive_ES::
    .string "¡Por favor!\p"
    .string "¡Mi SEEL es mucho más atractivo!\n"
    .string "¡El doble de atractivo!$"

VermilionCity_PokemonFanClub_Text_Pikachu_ES::
    .string "PIKACHU: ¡Chu! ¡Pika, pika!$"

VermilionCity_PokemonFanClub_Text_Seel_ES::
    .string "SEEL: ¡Eeel!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons_ES::
    .string "¡Yo presido el Club de Fans de los\n"
    .string "POKéMON!\p"
    .string "¡Tengo más de 100 POKéMON!\p"
    .string "¡Soy muy exigente en todo lo que\n"
    .string "se refiere a los POKéMON!\p"
    .string "Bueno...\p"
    .string "¿Has venido para saber más cosas\n"
    .string "de mis POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory_ES::
    .string "¡Muy bien!\n"
    .string "¡Pues escucha!\p"
    .string "Mi preferido es RAPIDASH...\p"
    .string "Es... gracioso... cariñoso... veloz\n"
    .string "e increíble... ¿No crees?...\l"
    .string "Es sorprendente... simpático...\l"
    .string "¡Yo lo adoro!\p"
    .string "Si lo abrazas... cuando duerme...\n"
    .string "es tan cálido... y mimoso... es\l"
    .string "espectacular... encantador...\l"
    .string "¡Hala, mira qué hora es!\l"
    .string "¡Hablo demasiado!\p"
    .string "¡Gracias por escucharme!\n"
    .string "¡Toma esto!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman_ES::
    .string "¡{PLAYER} recibió el BONO BICI\n"
    .string "de manos del PRESIDENTE!$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher_ES::
    .string "¡Cámbialo por una BICICLETA\n"
    .string "en la TIENDA de BICIS de CIUDAD\l"
    .string "CELESTE!\p"
    .string "¡Es gratis!\p"
    .string "¡No te apures por mí, mi FEAROW\n"
    .string "me lleva VOLANDO a donde sea!\p"
    .string "¡No necesito BICICLETA!\p"
    .string "¡Espero que te guste pedalear!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory_ES::
    .string "¡Oh! ¡Pues vuelve cuando quieras\n"
    .string "oír mi historia!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain_ES::
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Has vuelto para saber más cosas\n"
    .string "de mi POKéMON?\p"
    .string "¿No?\n"
    .string "¡Qué pena!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis_ES::
    .string "¡No tienes sitio para esto!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon_ES::
    .string "El PRESIDENTE habla mucho\n"
    .string "de los POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers_ES::
    .string "¡Escuchemos con atención a otros\n"
    .string "ENTRENADORES!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack_ES::
    .string "¡Si presumen, haz tú lo mismo!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons_ES::
    .string "A nuestro PRESIDENTE le encantan\n"
    .string "sus POKéMON.\p"
    .string "Pero los POKéMON a quien más\n"
    .string "quieren es a DALIA, creo.$"
