VermilionCity_PokemonFanClub_Text_AdmirePikachusTail_IT::
    .string "Non è bella la coda del mio\n"
    .string "PIKACHU?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute_IT::
    .string "Il mio PIKACHU è molto più carino\n"
    .string "di questo!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel_IT::
    .string "Io adoooro il mio SEEL!\p"
    .string "Devi vedere com'è contento\n"
    .string "quando l'abbraccio!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive_IT::
    .string "Perbacco!\p"
    .string "Il mio SEEL è molto più bello!$"

VermilionCity_PokemonFanClub_Text_Pikachu_IT::
    .string "PIKACHU: Pika! Pikaciu!$"

VermilionCity_PokemonFanClub_Text_Seel_IT::
    .string "SEEL: Eeel!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons_IT::
    .string "Sono il presidente del POKéMON FAN\n"
    .string "CLUB!\p"
    .string "Ho più di 100 POKéMON!\p"
    .string "Sono molto pignolo in fatto di\n"
    .string "POKéMON!\p"
    .string "Bene…\p"
    .string "Vuoi sapere tutto sui miei POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory_IT::
    .string "Stupendo, allora ascolta…!\p"
    .string "Il mio preferito è RAPIDASH…\p"
    .string "È… grazioso… carino… veloce\n"
    .string "e incredibile…\l"
    .string "Non trovi?…\l"
    .string "È sorprendente… simpatico…\l"
    .string "Mi piace tanto!\p"
    .string "Se lo abbraccio… quando dorme…\n"
    .string "è così caldo e morbido… è\l"
    .string "spettacolare… fantastico…\l"
    .string "Ops! Guarda che ora è!\l"
    .string "Ti faccio fare tardi!\p"
    .string "Grazie per l'attenzione!\n"
    .string "Prendi questo!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman_IT::
    .string "{PLAYER} riceve\n"
    .string "il BUONO BICI!$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher_IT::
    .string "Con quel BUONO puoi avere una\n"
    .string "BICI al NEGOZIO di BICI di\l"
    .string "CELESTOPOLI.\p"
    .string "Non ti preoccupare per me, il mio\n"
    .string "FEAROW mi porterà in VOLO\l"
    .string "ovunque voglia!\p"
    .string "Non ho bisogno di una BICICLETTA!\p"
    .string "Spero che ti piaccia pedalare!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory_IT::
    .string "Torna quando hai voglia di sentire\n"
    .string "le mie storie!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain_IT::
    .string "Ciao, {PLAYER}!\p"
    .string "Sei qui per sentir parlare dei miei\n"
    .string "POKéMON?\p"
    .string "No?\n"
    .string "Che peccato!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis_IT::
    .string "Fai spazio per questo!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon_IT::
    .string "Il presidente è un po' logorroico\n"
    .string "sui POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers_IT::
    .string "Ascoltiamo gli altri ALLENATORI!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack_IT::
    .string "Se uno si vanta, fallo anche tu!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons_IT::
    .string "Il nostro PRESIDENTE adora i suoi\n"
    .string "POKéMON. \p"
    .string "Ma la persona che in assoluto è\n"
    .string "più amata dai POKéMON è MARGI,\l"
    .string "credo.$"

