VermilionCity_PokemonFanClub_Text_AdmirePikachusTail_FR::
	.string "Mon PIKACHU est le plus beau de\n"
	.string "tous les PIKACHU!$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute_FR::
	.string "Hmm!\p"
	.string "Mon PIKACHU est deux fois plus\n"
	.string "mignon que celui-ci!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel_FR::
	.string "Moi, celui que j'aime c'est OTARIA!\p"
	.string "Il fait squitch quand je lui fais\n"
	.string "un câlin!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive_FR::
	.string "Oh!\p"
	.string "Mon OTARIA est beaucoup plus\n"
	.string "élégant!$"

VermilionCity_PokemonFanClub_Text_Pikachu_FR::
	.string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel_FR::
	.string "OTARIA: Riaaa!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons_FR::
	.string "Je suis le président du Fan Club\n"
	.string "des POKéMON!\p"
	.string "J'ai plus de 100 POKéMON!\p"
	.string "Je suis trop méga tatillon quand on\n"
	.string "parle de POKéMON!\p"
	.string "Alors…\p"
	.string "Tu veux encore savoir des trucs\n"
	.string "sur mes POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory_FR::
	.string "Bien!\n"
	.string "Ecoute!\p"
	.string "Mon préféré c'est GALOPA…\p"
	.string "Il est… mignon… adorable…\n"
	.string "intelligent… et… incroyable…\l"
	.string "Tu crois pas?\l"
	.string "Oh oui… simplement…\l"
	.string "incroyable…\l"
	.string "Je… l'adore!\p"
	.string "Il est tout doux… quand…\n"
	.string "je lui… fais des câlins…\l"
	.string "et puis…\l"
	.string "et aussi…\l"
	.string "… Oups! Regarde l'heure!\l"
	.string "J'arrête pas de parler!\p"
	.string "Merci de m'avoir écouté!\n"
	.string "Tiens, c'est pour toi!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman_FR::
	.string "{PLAYER} reçoit le\n"
	.string "BON COMMANDE!$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher_FR::
	.string "Echange-le contre une BICYCLETTE\n"
	.string "aux CYCLES A GOGO d'AZURIA!\p"
	.string "Moi, c'est mon RAPASDEPIC qui me\n"
	.string "transporte n'importe où!\p"
	.string "Je n'ai plus besoin de\n"
	.string "BICYCLETTE!\p"
	.string "J'espère que tu aimes pédaler!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory_FR::
	.string "Reviens quand tu veux. Je te\n"
	.string "raconterai mes histoires!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain_FR::
	.string "Salut, {PLAYER}!\p"
	.string "Tu es là pour écouter mes\n"
	.string "histoires de POKéMON?\p"
	.string "Non? Dommage!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis_FR::
	.string "Ton inventaire est plein!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon_FR::
	.string "Le PRESIDENT est très bavard en\n"
	.string "ce qui concerne les POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers_FR::
	.string "Ecoutons donc l'avis des autres\n"
	.string "DRESSEURS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack_FR::
	.string "Si on te nargue, nargue en retour!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons_FR::
	.string "Notre PRESIDENT aime beaucoup\n"
	.string "ses POKéMON.\p"
	.string "Mais c'est NINA que les POKéMON\n"
	.string "préfèrent, je crois.$"

