FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth_DE::
	.string "Der WÄRTER der SAFARI-ZONE ist\n"
	.string "sehr alt! Aber er ist noch immer im\l"
	.string "Dienst!\p"
	.string "Allerdings trägt er ein Gebiss!$"

FuchsiaCity_House1_Text_BillIsMyGrandson_DE::
	.string "Hast du schon BILL getroffen?\p"
	.string "Er ist mein Enkel!\p"
	.string "Schon als kleines Kind hat er gerne\n"
	.string "alles Mögliche gesammelt!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData_DE::
	.string "BILL sammelt auf seinem PC Daten\n"
	.string "über POKéMON!\p"
	.string "Hat er sie dir gezeigt?$"

