FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth_FR::
	.string "Le GARDIEN du PARC SAFARI est\n"
	.string "vieux mais trop cool!\p"
	.string "Ses dents sont fausses par contre.$"

FuchsiaCity_House1_Text_BillIsMyGrandson_FR::
	.string "Hmm?\n"
	.string "Tu connais LEO?\p"
	.string "C'est mon petit-fils!\p"
	.string "Il souffre de collectionnite\n"
	.string "depuis tout petit!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData_FR::
	.string "LEO enregistre ses données sur les\n"
	.string "POKéMON sur son PC!\p"
	.string "Il t'a déjà montré tout ça?$"

