SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered_IT::
    .string "Mia figlia è molto egocentrica e ha\n"
    .string "pochi amici!$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople_IT::
    .string "Si diverte a imitare la gente.\p"
    .string "Per questo ha il soprannome di\n"
    .string "COPIONA!$"

SaffronCity_CopycatsHouse_1F_Text_Chansey_IT::
    .string "CHANSEY: Ciaan! Ciaan!$"

