SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered_ES::
    .string "¡Mi hija está tan metida en sí\n"
    .string "misma que tiene muy pocos amigos!$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople_ES::
    .string "A mi hija le gusta imitar a la\n"
    .string "gente.\p"
    .string "¡Y por eso la gente de por aquí\n"
    .string "le llama la COPIONA!$"

SaffronCity_CopycatsHouse_1F_Text_Chansey_ES::
    .string "CHANSEY: ¡Chaan! ¡Chaan!$"
