SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered_FR::
	.string "Ma fille est très égocentrique!\n"
	.string "Elle n'a pas beaucoup d'amis.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople_FR::
	.string "Ma fille adore imiter les gens.\p"
	.string "Elle imite si bien qu'on l'appelle\n"
	.string "la COPIEUSE dans le coin!$"

SaffronCity_CopycatsHouse_1F_Text_Chansey_FR::
	.string "LEVEINARD : Vénar! Vénar!$"

