PokemonTower_7F_Text_Grunt1Intro_ES::
    .string "¿Qué quieres?\n"
    .string "¿Qué haces aquí?$"

PokemonTower_7F_Text_Grunt1Defeat_ES::
    .string "¡Me rindo!$"

PokemonTower_7F_Text_Grunt1PostBattle_ES::
    .string "¡Voy a olvidar todo esto!$"

PokemonTower_7F_Text_Grunt2Intro_ES::
    .string "El tipo, que ya tiene unos años,\n"
    .string "se plantó en nuestra GUARIDA.\p"
    .string "Y empezó a decir que estábamos\n"
    .string "haciendo daño a los POKéMON.\p"
    .string "¡La cosa es más que seria!$"

PokemonTower_7F_Text_Grunt2Defeat_ES::
    .string "¡Por favor!\n¡Basta!$"

PokemonTower_7F_Text_Grunt2PostBattle_ES::
    .string "¡Los POKéMON sólo sirven para\n"
    .string "ganar dinero!\p"
    .string "¡No te metas en nuestros asuntos!$"

PokemonTower_7F_Text_Grunt3Intro_ES::
    .string "¡No vas a salvar a nadie!$"

PokemonTower_7F_Text_Grunt3Defeat_ES::
    .string "¡No luches contra nosotros,\n"
    .string "el TEAM ROCKET!$"

PokemonTower_7F_Text_Grunt3PostBattle_ES::
    .string "¡No te saldrás con la tuya así\n"
    .string "como así!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe_ES::
    .string "SR. FUJI: ¿Qué?\n"
    .string "¿Has venido a salvarme?\p"
    .string "¡Gracias! Pero estoy aquí por mi\n"
    .string "propia voluntad.\p"
    .string "Vine a calmar el espíritu de la\n"
    .string "madre de CUBONE.\p"
    .string "Creo que el espíritu de MAROWAK\n"
    .string "ya está tranquilo.\p"
    .string "¡Agradezco tu interés!\p"
    .string "Acompáñame a mi casa, a la CASA\n"
    .string "POKéMON, que hay al pie de esta\l"
    .string "torre.$"
