PokemonTower_7F_Text_Grunt1Intro_FR::
	.string "Que veux-tu?\n"
	.string "Que cherches-tu?$"

PokemonTower_7F_Text_Grunt1Defeat_FR::
	.string "Rhaaaa!\n"
	.string "J'abandonne!$"

PokemonTower_7F_Text_Grunt1PostBattle_FR::
	.string "Je ne t'oublierai pas!$"

PokemonTower_7F_Text_Grunt2Intro_FR::
	.string "Ce vieil homme est venu nous\n"
	.string "demander de ne plus troubler les\l"
	.string "gentils POKéMON!\p"
	.string "Alors on a discuté tranquillement\n"
	.string "entre adultes.$"

PokemonTower_7F_Text_Grunt2Defeat_FR::
	.string "Argh!\n"
	.string "Assez!$"

PokemonTower_7F_Text_Grunt2PostBattle_FR::
	.string "Les POKéMON ne servent qu'à\n"
	.string "gagner de l'argent!\p"
	.string "Reste en dehors de nos affaires!$"

PokemonTower_7F_Text_Grunt3Intro_FR::
	.string "Y'a personne à sauver ici!$"

PokemonTower_7F_Text_Grunt3Defeat_FR::
	.string "Hmm!\n"
	.string "N'affronte pas la TEAM ROCKET!$"

PokemonTower_7F_Text_Grunt3PostBattle_FR::
	.string "Tu ne t'en sortiras pas comme ça!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe_FR::
	.string "MR. FUJI: Hé?\n"
	.string "Tu es là pour me sauver?\p"
	.string "Merci! Mais je suis venu ici de\n"
	.string "mon plein gré.\p"
	.string "Je voulais apaiser l'esprit\n"
	.string "de la mère d'OSSELAIT.\p"
	.string "Je pense que l'esprit\n"
	.string "d'OSSATUEUR s'en est allé\l"
	.string "vers les cieux.\p"
	.string "Je dois te remercier pour\n"
	.string "ton attention.\p"
	.string "Viens avec moi dans ma maison,\n"
	.string "la MAISON POKéMON au pied de\l"
	.string "cette tour.$"

