PewterCity_Museum_1F_Text_Its50YForChildsTicket_ES::
    .string "Los niños pagan 50¥.\p"
    .string "¿Te gustaría entrar?$"

PewterCity_Museum_1F_Text_ComeAgain_ES::
    .string "¡Hasta pronto!$"

PewterCity_Museum_1F_Text_Right50YThankYou_ES::
    .string "¡50¥! ¡Vale!\n"
    .string "¡Gracias!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney_ES::
    .string "No tienes suficiente dinero.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself_ES::
    .string "Disfruta de la visita.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs_ES::
    .string "¡No puedes entrar por detrás!\p"
    .string "¡Bueno, da igual!\n"
    .string "¿Sabes qué es el ÁMBAR?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter_ES::
    .string "¿Y sabías que el ÁMBAR contiene\n"
    .string "material genético de los POKéMON?\p"
    .string "Dicen que hay un LABORATORIO\n"
    .string "donde intentan revivir a viejos\l"
    .string "POKéMON a partir del ÁMBAR.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap_ES::
    .string "El ÁMBAR es, en realidad, savia\n"
    .string "de árbol fosilizada.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround_ES::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife_ES::
    .string "¡Qué golpe de suerte!\p"
    .string "¡Nunca pensé que conseguiría\n"
    .string "ver huesos de dragón!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined_ES::
    .string "¡Ssh! Voy a contarte un secreto.\p"
    .string "¡Creo que este trozo de ÁMBAR\n"
    .string "contiene ADN de POKéMON!\p"
    .string "¡Sería un descubrimiento científico\n"
    .string "increíble si se pudiera revivir a\l"
    .string "los POKéMON con esto!\p"
    .string "¡Pero mis colegas no me hacen\n"
    .string "ni caso! ¡Por eso te voy a pedir\l"
    .string "un favor!\p"
    .string "¡Lleva esto al LABORATORIO\n"
    .string "POKéMON para que lo analicen!$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan_ES::
    .string "¡{PLAYER} recibió el ÁMBAR VIEJO\n"
    .string "de manos del hombre!$"

PewterCity_Museum_1F_Text_GetOldAmberChecked_ES::
    .string "¡Ssh!\n"
    .string "¡Haz que analicen el ÁMBAR VIEJO!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis_ES::
    .string "¡No tienes sitio para esto!$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit_ES::
    .string "¡Tenemos dos fósiles de unos\n"
    .string "POKéMON muy raros y prehistóricos!$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber_ES::
    .string "¡El ÁMBAR es transparente y de\n"
    .string "color oro!$"

PewterCity_Museum_1F_Text_AerodactylFossil_ES::
    .string "Fósil AERODACTYL.\n"
    .string "Un primitivo y raro POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil_ES::
    .string "Fósil KABUTOPS.\n"
    .string "Un primitivo y raro POKéMON.$"
