PewterCity_Museum_1F_Text_Its50YForChildsTicket_DE::
	.string "Für Kinder kostet der Eintritt 50¥!\p"
	.string "Möchtest du hinein?$"

PewterCity_Museum_1F_Text_ComeAgain_DE::
	.string "Komm bald wieder!$"

PewterCity_Museum_1F_Text_Right50YThankYou_DE::
	.string "O.K., das sind 50¥!\n"
	.string "Vielen Dank!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney_DE::
	.string "Du hast nicht genug Geld.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself_DE::
	.string "Viel Vergnügen!$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs_DE::
	.string "Du hast hinter dem Tresen nichts zu\n"
	.string "suchen!\p"
	.string "Na ja, egal!\n"
	.string "Weißt du, was BERNSTEIN ist?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter_DE::
	.string "Es soll ein LABOR geben, in dem\n"
	.string "man versucht, aus altem BERNSTEIN\l"
	.string "URZEIT-POKéMON wiederauferstehen\l"
	.string "zu lassen!$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap_DE::
	.string "BERNSTEIN ist versteinertes\n"
	.string "Baumharz.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround_DE::
	.string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife_DE::
	.string "Dies ist ein außergewöhnliches\n"
	.string "Fossil!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined_DE::
	.string "Pst! Ich glaube, in diesem Stück\n"
	.string "BERNSTEIN ist POKéMON-DNS\l"
	.string "enthalten!\p"
	.string "Es wäre grandios, wenn man daraus\n"
	.string "ein POKéMON wiederauferstehen\l"
	.string "lassen könnte!\p"
	.string "Doch meine Kollegen nehmen mich\n"
	.string "nicht ernst!\p"
	.string "Könntest du etwas für mich\n"
	.string "erledigen?\p"
	.string "Lass das im POKéMON-LABOR\n"
	.string "untersuchen!$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan_DE::
	.string "{PLAYER} erhält\n"
	.string "einen ALTBERNSTEIN!$"

PewterCity_Museum_1F_Text_GetOldAmberChecked_DE::
	.string "Pst!\n"
	.string "Lass den ALTBERNSTEIN untersuchen!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis_DE::
	.string "Du hast keinen Platz für weitere\n"
	.string "Items!$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit_DE::
	.string "Unser besonderer Stolz sind zwei\n"
	.string "Fossilien von äußerst seltenen,\l"
	.string "prähistorischen POKéMON!$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber_DE::
	.string "Der BERNSTEIN schimmert goldbraun\n"
	.string "und ist durchsichtig!$"

PewterCity_Museum_1F_Text_AerodactylFossil_DE::
	.string "AERODACTYL-Fossil\n"
	.string "Ein urzeitliches und seltenes\l"
	.string "POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil_DE::
	.string "KABUTOPS-Fossil\n"
	.string "Ein urzeitliches und seltenes\l"
	.string "POKéMON.$"

