PewterCity_Museum_1F_Text_Its50YForChildsTicket_IT::
    .string "I bambini pagano ¥50!\p"
    .string "Vuoi entrare?$"

PewterCity_Museum_1F_Text_ComeAgain_IT::
    .string "Torna presto!$"

PewterCity_Museum_1F_Text_Right50YThankYou_IT::
    .string "Bene, sono ¥50!\n"
    .string "Grazie!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney_IT::
    .string "Non hai abbastanza soldi.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself_IT::
    .string "Buon divertimento.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs_IT::
    .string "Non puoi entrare dal retro!\p"
    .string "Oh! Fa lo stesso!\n"
    .string "Sai che cos'è l'AMBRA?!$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter_IT::
    .string "Non so dove c'è un LABORATORIO\n"
    .string "dove fanno risuscitare i\l"
    .string "POKéMON antichi!\p"
    .string "Utilizzano dell'AMBRA contenente\n"
    .string "materiale genetico di quei\l"
    .string "POKéMON!$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap_IT::
    .string "L'AMBRA è resina fossilizzata.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround_IT::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife_IT::
    .string "Questo fossile è magnifico!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined_IT::
    .string "Pss! Credo che questo pezzo di\n"
    .string "AMBRA contenga DNA di POKéMON!\p"
    .string "Sarebbe magnifico se con questo si\n"
    .string "potesse ridare vita ai POKéMON!\p"
    .string "Ma i miei colleghi non mi credono!\p"
    .string "Quindi ti chiedo un grosso favore!\p"
    .string "Fallo esaminare in un LABORATORIO\n"
    .string "POKéMON!$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan_IT::
    .string "{PLAYER} riceve\n"
    .string "l'AMBRA ANTICA!$"

PewterCity_Museum_1F_Text_GetOldAmberChecked_IT::
    .string "Pss!\n"
    .string "Fa analizzare l'AMBRA ANTICA!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis_IT::
    .string "Non hai più spazio per questo!$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit_IT::
    .string "Siamo orgogliosi di poter mostrare\n"
    .string "due fossili di POKéMON preistorici\l"
    .string "molto rari!$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber_IT::
    .string "L'AMBRA è dorata e trasparente!$"

PewterCity_Museum_1F_Text_AerodactylFossil_IT::
    .string "Fossile AERODACTYL, un raro\n"
    .string "POKéMON primitivo.$"

PewterCity_Museum_1F_Text_KabutopsFossil_IT::
    .string "Fossile KABUTOPS, un raro POKéMON\n"
    .string "primitivo.$"

