SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn_ES::
    .string "¡A bailar el baile de CHANSEY,\n"
    .string "a bailar!\p"
    .string "¡Baila tú también!\n"
    .string "¡A bailar, a bailar!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance_ES::
    .string "¿Quieres bailar?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance_ES::
    .string "¡Venga, baila!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance_ES::
    .string "{PLAYER} bailó el baile de CHANSEY.$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow_ES::
    .string "¡Ja, ja, ja!\p"
    .string "¡Ahora estáis más animados!\n"
    .string "¡Qué bien!$"

SevenIsland_SevaultCanyon_House_Text_Chansey_ES::
    .string "CHANSEY: ¡Chansi, chansi!$"
