SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn_FR::
	.string "Danse, danse!\n"
	.string "Danse LEVEINARD!\p"
	.string "Tu te joins à nous?\n"
	.string "Allez, danse, danse!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance_FR::
	.string "Tu veux danser?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance_FR::
	.string "Allez, sois pas timide!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance_FR::
	.string "{PLAYER} exécute la\n"
	.string "danse de LEVEINARD!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow_FR::
	.string "Ahahahaha!\p"
	.string "Je suis content que ça te\n"
	.string "plaise!$"

SevenIsland_SevaultCanyon_House_Text_Chansey_FR::
	.string "LEVEINARD: LEVEEEE!$"

