SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn_IT::
    .string "Dance, dance!\n"
    .string "CHANSEY Dance!\p"
    .string "Ehi, balla con me!\n"
    .string "Dance, dance!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance_IT::
    .string "Ti va di ballare?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance_IT::
    .string "Dai, vieni a ballare!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance_IT::
    .string "{PLAYER} balla la CHANSEY Dance!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow_IT::
    .string "Ahahahaha!\p"
    .string "Guarda come siete di buon umore\n"
    .string "adesso, tu e la tua squadra!$"

SevenIsland_SevaultCanyon_House_Text_Chansey_IT::
    .string "CHANSEY: Chansi! Chansi!$"

