SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn_DE::
	.string "Tanze, tanze!\n"
	.string "CHANEIRA tanze!\p"
	.string "Mach auch mit!\n"
	.string "Tanze, tanze!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance_DE::
	.string "Möchtest du tanzen?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance_DE::
	.string "Komm schon, tanze!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance_DE::
	.string "{PLAYER} tanzt den CHANEIRA-Tanz!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow_DE::
	.string "Ahahahaha!\p"
	.string "Jetzt geht es dir gut!\n"
	.string "Hast du ein Glück!$"

SevenIsland_SevaultCanyon_House_Text_Chansey_DE::
	.string "CHANEIRA: Eira, Eira!$"

