VermilionCity_House3_Text_PidgeyFlyLetterToSaffron_ES::
    .string "¡Mi PIDGEY volará al norte,\n"
    .string "a CIUDAD AZAFRÁN, para llevar\l"
    .string "una carta!$"

VermilionCity_House3_Text_Pidgey_ES::
    .string "PIDGEY: ¡Pid, pid!$"

VermilionCity_House3_Text_DearPippiLetter_ES::
    .string "Querido PIPPI:\n"
    .string "Espero verte pronto.\p"
    .string "Dicen que en CIUDAD AZAFRÁN\n"
    .string "tienen problemas con el TEAM\l"
    .string "ROCKET.\p"
    .string "La CIUDAD CARMÍN parece segura.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom_ES::
    .string "Me gustaría mandarme CARTAS\n"
    .string "con mucha gente.\p"
    .string "He mandado a mi PIDGEY a la\n"
    .string "SALA UNIÓN para que intercambie\l"
    .string "CARTAS por mí.$"
