VermilionCity_House3_Text_PidgeyFlyLetterToSaffron_DE::
	.string "Ich lasse TAUBSI einen Brief nach\n"
	.string "SAFFRONIA CITY im Norden bringen!$"

VermilionCity_House3_Text_Pidgey_DE::
	.string "TAUBSI: TAUBSI!$"

VermilionCity_House3_Text_DearPippiLetter_DE::
	.string "Liebe NIKKI! Ich hoffe, wir sehen\n"
	.string "uns bald wieder!\p"
	.string "Wie ich höre, stiftet das TEAM\n"
	.string "ROCKET in SAFFRONIA CITY Unruhe!\p"
	.string "In ORANIA CITY scheint es sicher\n"
	.string "zu sein.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom_DE::
	.string "Ich möchte mit allen Menschen\n"
	.string "BRIEFE austauschen.\p"
	.string "Ich schicke mein TAUBSI in einen\n"
	.string "KONNEX-KLUB, um BRIEFE\l"
	.string "für mich auszutauschen.$"

