VermilionCity_House3_Text_PidgeyFlyLetterToSaffron_IT::
    .string "Il mio PIDGEY volerà a nord, per\n"
    .string "portare una lettera a\l"
    .string "ZAFFERANOPOLI!$"

VermilionCity_House3_Text_Pidgey_IT::
    .string "PIDGEY: pig pig!$"

VermilionCity_House3_Text_DearPippiLetter_IT::
    .string "Caro PIPPI,\n"
    .string "spero di vederti presto.\p"
    .string "Ho saputo che ZAFFERANOPOLI ha\n"
    .string "problemi con TEAM ROCKET.\p"
    .string "ARANCIOPOLI sembra salva per ora.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom_IT::
    .string "Voglio scambiare MESSAGGI con\n"
    .string "chiunque.\p"
    .string "Manderò il mio PIDGEY in una SALA\n"
    .string "CONTATTO a scambiare MESSAGGI\l"
    .string "per me!$"

