Route18_Text_WiltonIntro_DE::
	.string "Ich laufe überall durch hohes\n"
	.string "Gras, um POKéMON aufzuspüren!$"

Route18_Text_WiltonDefeat_DE::
	.string "Also so was!$"

Route18_Text_WiltonPostBattle_DE::
	.string "Wenn ich nur ein FAHRRAD hätte!$"

Route18_Text_RamiroIntro_DE::
	.string "Guruguu!\n"
	.string "Wie klingt mein Vogellockruf?$"

Route18_Text_RamiroDefeat_DE::
	.string "Ich musste mit dir kämpfen!$"

Route18_Text_RamiroPostBattle_DE::
	.string "Am Wochenende sammle ich immer\n"
	.string "WASSER-POKéMON!$"

Route18_Text_JacobIntro_DE::
	.string "Das hier ist mein Gebiet!\n"
	.string "Sieh zu, dass du Land gewinnst!$"

Route18_Text_JacobDefeat_DE::
	.string "Verdammt!$"

Route18_Text_JacobPostBattle_DE::
	.string "Hier habe ich sehr gerne POKéMON\n"
	.string "gejagt!$"

Route18_Text_RouteSign_DE::
	.string "ROUTE 18\n"
	.string "PRISMANIA CITY - FUCHSANIA CITY$"

Route18_Text_CyclingRoadSign_DE::
	.string "Das Betreten des RADWEGES ist\n"
	.string "Fußgängern untersagt!$"

