Route18_Text_WiltonIntro_FR::
	.string "Je fouille les hautes herbes pour\n"
	.string "y trouver des POKéMON.$"

Route18_Text_WiltonDefeat_FR::
	.string "Oh!$"

Route18_Text_WiltonPostBattle_FR::
	.string "Ah, si j'avais un VELO!$"

Route18_Text_RamiroIntro_FR::
	.string "Cui cui cui!\n"
	.string "J'fais l'oiseau, ça ressemble?$"

Route18_Text_RamiroDefeat_FR::
	.string "…\n"
	.string "J'suis cuit!$"

Route18_Text_RamiroPostBattle_FR::
	.string "Le week-end, je collectionne les\n"
	.string "POKéMON EAU!$"

Route18_Text_JacobIntro_FR::
	.string "T'es sur mon gazon, dégage!$"

Route18_Text_JacobDefeat_FR::
	.string "Ah?$"

Route18_Text_JacobPostBattle_FR::
	.string "C'est mon endroit préféré pour\n"
	.string "chasser les POKéMON!$"

Route18_Text_RouteSign_FR::
	.string "ROUTE 18\n"
	.string "CELADOPOLE - PARMANIE$"

Route18_Text_CyclingRoadSign_FR::
	.string "PISTE CYCLABLE\n"
	.string "Interdite aux piétons!$"

