Route18_Text_WiltonIntro_IT::
    .string "Cerco sempre nuovi POKéMON\n"
    .string "nell'erba alta.$"

Route18_Text_WiltonDefeat_IT::
    .string "Ohi!$"

Route18_Text_WiltonPostBattle_IT::
    .string "Mi piacerebbe avere una\n"
    .string "BICICLETTA!$"

Route18_Text_RamiroIntro_IT::
    .string "Cu cu cu!\n"
    .string "Ti piace questo richiamo?$"

Route18_Text_RamiroDefeat_IT::
    .string "Volevo darti fastidio!$"

Route18_Text_RamiroPostBattle_IT::
    .string "Il fine settimana prendo anche\n"
    .string "POKéMON di mare!$"

Route18_Text_JacobIntro_IT::
    .string "Questo è il mio territorio!\n"
    .string "Via!$"

Route18_Text_JacobDefeat_IT::
    .string "Maledizione!$"

Route18_Text_JacobPostBattle_IT::
    .string "Questa è la zona che preferisco\n"
    .string "per catturare i POKéMON!$"

Route18_Text_RouteSign_IT::
    .string "PERCORSO 18\n"
    .string "AZZURROPOLI - FUCSIAPOLI$"

Route18_Text_CyclingRoadSign_IT::
    .string "PISTA CICLABILE\n"
    .string "Vietata ai pedoni!$"

