Route18_Text_WiltonIntro_ES::
    .string "Compruebo siempre las zonas de\n"
    .string "hierba en busca de nuevos POKéMON.$"

Route18_Text_WiltonDefeat_ES::
    .string "¡Tch!$"

Route18_Text_WiltonPostBattle_ES::
    .string "¡Ojalá tuviera una BICICLETA!$"

Route18_Text_RamiroIntro_ES::
    .string "¡Cucu, cucu!\n"
    .string "¿Te gusta el reclamo de mi pájaro?$"

Route18_Text_RamiroDefeat_ES::
    .string "¡No he podido contigo!$"

Route18_Text_RamiroPostBattle_ES::
    .string "¡También recojo POKéMON del mar\n"
    .string "los fines de semana!$"

Route18_Text_JacobIntro_ES::
    .string "¡Es mi césped!\n"
    .string "¡Fuera de aquí!$"

Route18_Text_JacobDefeat_ES::
    .string "¡Qué rabia!$"

Route18_Text_JacobPostBattle_ES::
    .string "¡Es mi zona preferida para atrapar\n"
    .string "POKéMON!$"

Route18_Text_RouteSign_ES::
    .string "RUTA 18:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"

Route18_Text_CyclingRoadSign_ES::
    .string "CAMINO DE BICIS\n"
    .string "¡Prohibido el paso a los peatones!$"
