Text_SeismicTossTeach_DE::
	.string "Das Geheimnis des Raumes…\n"
	.string "Die Rätsel des Planeten…\p"
	.string "Es gibt so vieles, worüber wir so\n"
	.string "wenig wissen!\p"
	.string "Aber was treibt uns an, noch mehr\n"
	.string "zu hinterfragen und nicht das\l"
	.string "Handtuch zu werfen?\l"
	.string "Der einzige erlaubte Wurf…\p"
	.string "Wie wäre es mit GEOWURF?\n"
	.string "Soll ich das einem POKéMON\l"
	.string "beibringen?$"

Text_SeismicTossDeclined_DE::
	.string "So ist das also!\n"
	.string "Ich bin sicher, du kommst zurück!$"

Text_SeismicTossWhichMon_DE::
	.string "Welches POKéMON soll die\n"
	.string "Attacke erlernen?$"

Text_SeismicTossTaught_DE::
	.string "Ich hoffe, du wirfst nicht das\n"
	.string "Handtuch! Mach weiter so!$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone_DE::
	.string "MONDSTEIN?\p"
	.string "Was ist daran so einzigartig?$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding_DE::
	.string "Der 20. Juli 1969!\p"
	.string "Die erste Mondlandung!\p"
	.string "Für die Fernsehübertragung hatte\n"
	.string "ich extra einen Farbfernseher\l"
	.string "gekauft!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth_DE::
	.string "Momentan haben wir eine\n"
	.string "Raumfahrt-Ausstellung.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu_DE::
	.string "Ich hätte gerne ein PIKACHU!\n"
	.string "Es ist so furchtbar süß!\p"
	.string "Mein Papa soll mir eines fangen!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise_DE::
	.string "Ja, ein PIKACHU!\n"
	.string "Ich verspreche, ich fange eins!$"

PewterCity_Museum_1F_Text_SpaceShuttle_DE::
	.string "SPACE SHUTTLE$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon_DE::
	.string "Auf dem MONDBERG gefundenes\n"
	.string "Meteoritengestein (MONDSTEIN?)$"

