Text_SeismicTossTeach_IT::
    .string "I misteri dello spazio…\n"
    .string "I misteri della terra…\p"
    .string "A volte, concentrarmi sull'immensità\n"
    .string "dell'universo mi scuote come un\l"
    .string "terremoto.\p"
    .string "A proposito di terremoti…\p"
    .string "Vuoi che insegni MOV. SISMICO\n"
    .string "ad uno dei tuoi POKéMON?$"

Text_SeismicTossDeclined_IT::
    .string "Davvero? Tornerai per chiedermelo,\n"
    .string "ne sono certo.$"

Text_SeismicTossWhichMon_IT::
    .string "Che POKéMON vuoi istruire?$"

Text_SeismicTossTaught_IT::
    .string "Spero che scuota anche te!$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone_IT::
    .string "PIETRALUNARE?\p"
    .string "Cosa c'è di tanto speciale?$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding_IT::
    .string "21 luglio 1969!\p"
    .string "Il primo uomo sulla luna!\p"
    .string "Mi sono comprato una TV a colori\n"
    .string "per guardarlo!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth_IT::
    .string "Ora c'è una mostra sullo spazio.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu_IT::
    .string "Voglio un PIKACHU!\n"
    .string "È così carino!\p"
    .string "Ho chiesto a papà di prenderne\n"
    .string "uno!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise_IT::
    .string "Sì promesso, avrai il tuo PIKACHU!$"

PewterCity_Museum_1F_Text_SpaceShuttle_IT::
    .string "SPACE SHUTTLE$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon_IT::
    .string "Meteorite caduto sul MONTE LUNA.\n"
    .string "Pare si tratti di PIETRALUNARE.$"

