Text_SeismicTossTeach_ES::
    .string "Los secretos del espacio...\n"
    .string "Los misterios de la tierra...\p"
    .string "Hay tantas cosas de las que\n"
    .string "sabemos tan poco...\p"
    .string "Pero eso debería movernos a\n"
    .string "investigar más y no tirar la toalla.\p"
    .string "Y hablando de movimiento...\p"
    .string "¿Conoces el MOV. SÍSMICO?\n"
    .string "¿Quieres que se lo enseñe a algún\l"
    .string "POKéMON?$"

Text_SeismicTossDeclined_ES::
    .string "¿Ah, no?\n"
    .string "Seguro que vuelves a pedírmelo.$"

Text_SeismicTossWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe MOV. SÍSMICO?$"

Text_SeismicTossTaught_ES::
    .string "Espero que no tires la toalla.\n"
    .string "Sigue así.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone_ES::
    .string "¿La PIEDRA LUNAR?\p"
    .string "¿Por qué es tan especial?\n"
    .string "Yo no le veo nada del otro mundo.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding_ES::
    .string "¡20 de julio de 1969!\p"
    .string "¡1.{SUPER_ER} alunizaje!\p"
    .string "¡Compré una tele en color para\n"
    .string "verlo!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth_ES::
    .string "Ahora tenemos una exposición sobre\n"
    .string "el espacio.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu_ES::
    .string "¡Quiero un PIKACHU!\n"
    .string "¡Es tan mono!\p"
    .string "¡Le pedí a mi padre que me\n"
    .string "atrapara uno!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise_ES::
    .string "¡Sí, pronto tendrás a tu\n"
    .string "PIKACHU!... $"

PewterCity_Museum_1F_Text_SpaceShuttle_ES::
    .string "NAVE ESPACIAL$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon_ES::
    .string "Meteorito caído en el MT. MOON.\n"
    .string "(¿PIEDRA LUNAR?)$"
