Text_SeismicTossTeach_FR::
	.string "Les secrets de l'espace…\n"
	.string "Les mystères de la terre…\p"
	.string "Il y a tant de choses que nous\n"
	.string "ne comprenons pas encore.\p"
	.string "Mais cela doit nous motiver à\n"
	.string "apprendre davantage.\p"
	.string "D'ailleurs, désires-tu que\n"
	.string "j'apprenne FRAPPE ATLAS\p"
	.string "à un de tes POKéMON?$"

Text_SeismicTossDeclined_FR::
	.string "Vraiment?\n"
	.string "Tu me déçois.$"

Text_SeismicTossWhichMon_FR::
	.string "A quel POKéMON dois-je l'enseigner?$"

Text_SeismicTossTaught_FR::
	.string "Je suis sûr que ça te sera\n"
	.string "utile. Bon courage.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone_FR::
	.string "PIERRE LUNE?\p"
	.string "Ouais? Et alors?$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding_FR::
	.string "20 Juillet 1969!\p"
	.string "L'homme a marché sur la lune!\p"
	.string "J'ai acheté une télé couleur pour\n"
	.string "voir toutes les nuances de la lune!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth_FR::
	.string "Nous faisons une exposition sur\n"
	.string "l'espace.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu_FR::
	.string "Je veux un PIKACHU!\p"
	.string "Papa va m'en trouver un!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise_FR::
	.string "Oui, oui, tu vas l'avoir ton\n"
	.string "PIKACHU… C'est ça.$"

PewterCity_Museum_1F_Text_SpaceShuttle_FR::
	.string "NAVETTE SPATIALE$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon_FR::
	.string "Un météore du MONT SELENITE.\n"
	.string "Serait-ce une PIERRE LUNE?$"

