SafariZone_SecretHouse_Text_CongratsYouveWon_ES::
    .string "¡Ah! ¡Por fin!\p"
    .string "¡Eres la primera persona que llega\n"
    .string "a la CASA SECRETA!\p"
    .string "He organizado un concurso con\n"
    .string "motivo de nuestra inauguración.\p"
    .string "Y estaba empezando a preocuparme\n"
    .string "que nadie ganara nuestro premio.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Has ganado!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant_ES::
    .string "¡{PLAYER} recibió una MO03\n"
    .string "del empleado!$"

SafariZone_SecretHouse_Text_ExplainSurf_ES::
    .string "¡La MO03 es SURF!\p"
    .string "¡Un POKéMON podrá llevarte\n"
    .string "por el agua!\p"
    .string "¡Y esta MO puede ser utilizada\n"
    .string "una y otra vez!\p"
    .string "¡Tienes muchísima suerte!\n"
    .string "¡Te llevas un fabuloso premio!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize_ES::
    .string "¡No tienes sitio para este premio\n"
    .string "tan fabuloso!$"
