SafariZone_SecretHouse_Text_CongratsYouveWon_IT::
    .string "Ah! Finalmente!\p"
    .string "Sei la prima persona che\n"
    .string "raggiunge la CASA SEGRETA!\p"
    .string "Ormai pensavo che nessuno avrebbe\n"
    .string "vinto il nostro premio.\p"
    .string "Congratulazioni!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant_IT::
    .string "{PLAYER} riceve\n"
    .string "la MN03!$"

SafariZone_SecretHouse_Text_ExplainSurf_IT::
    .string "La MN03 è SURF!\p"
    .string "Con SURF, un POKéMON ti\n"
    .string "potrà trasportare sull'acqua!\p"
    .string "Essendo una MN, non si esaurisce!\n"
    .string "Potrai usarla quante volte vorrai!\p"
    .string "È un gran bel premio, sai?$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize_IT::
    .string "Non hai spazio per questo premio\n"
    .string "favoloso!$"

