SafariZone_SecretHouse_Text_CongratsYouveWon_DE::
	.string "Ah! Endlich!\p"
	.string "Du bist der Erste, der das\n"
	.string "GEHEIME HAUS gefunden hat!\p"
	.string "Ich dachte schon, niemand würde\n"
	.string "den großen Preis jemals gewinnen!\p"
	.string "Glückwunsch!\n"
	.string "Du hast gewonnen!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant_DE::
	.string "{PLAYER} erhält\n"
	.string "VM03!$"

SafariZone_SecretHouse_Text_ExplainSurf_DE::
	.string "VM03 ist SURFER!\p"
	.string "Lernt ein POKéMON diese Technik,\n"
	.string "dann kann es dich über das Wasser\l"
	.string "transportieren!\p"
	.string "Das BESTE ist aber, dass du diese\n"
	.string "VM benutzen kannst, so oft du\l"
	.string "möchtest!\p"
	.string "Ist das nicht irre?\n"
	.string "Du bist ein Glückspilz!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize_DE::
	.string "Oh! Du kannst keine weiteren Items\n"
	.string "tragen!$"

