SafariZone_SecretHouse_Text_CongratsYouveWon_FR::
	.string "Ah! Quand même!\p"
	.string "Enfin quelqu'un qui découvre\n"
	.string "la CABANE SECRETE!\p"
	.string "J'avais peur que personne ne\n"
	.string "gagne notre prix.\p"
	.string "Félicitations!\n"
	.string "Tu as gagné!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant_FR::
	.string "{PLAYER} obtient la CS03\n"
	.string "de l'intendant!$"

SafariZone_SecretHouse_Text_ExplainSurf_FR::
	.string "CS03 contient SURF!\p"
	.string "Un POKéMON pourra te faire\n"
	.string "naviguer sur les flots!\p"
	.string "En plus, cette CS peut s'utiliser à\n"
	.string "l'infini!\p"
	.string "T'en as de la chance!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize_FR::
	.string "Heu… Tu n'as pas assez de place\n"
	.string "pour recevoir ce prix fabuleux!$"

