Route19_Text_RichardIntro_FR::
	.string "Je m'échauffe avant de piquer\n"
	.string "une tête!$"

Route19_Text_RichardDefeat_FR::
	.string "J'suis tout chaud, là!$"

Route19_Text_RichardPostBattle_FR::
	.string "OK, prêt à plonger!$"

Route19_Text_ReeceIntro_FR::
	.string "Attends! Mouille-toi la nuque avant\n"
	.string "de plonger!$"

Route19_Text_ReeceDefeat_FR::
	.string "Ha! J'suis bien refroidi, là!$"

Route19_Text_ReecePostBattle_FR::
	.string "Fais gaffe aux TENTACOOL!$"

Route19_Text_MatthewIntro_FR::
	.string "J'aime nager!\n"
	.string "Et toi?$"

Route19_Text_MatthewDefeat_FR::
	.string "Plaouff!\n"
	.string "T'es dans la vague!$"

Route19_Text_MatthewPostBattle_FR::
	.string "Je nage plus vite que les POKéMON!$"

Route19_Text_DouglasIntro_FR::
	.string "D'où vient le vent?$"

Route19_Text_DouglasDefeat_FR::
	.string "Glargh! OK, j'poserai plus de\n"
	.string "questions idiotes!$"

Route19_Text_DouglasPostBattle_FR::
	.string "Je vois des îles au loin!$"

Route19_Text_DavidIntro_FR::
	.string "Je cherche des POKéMON dans les\n"
	.string "grands fonds!$"

Route19_Text_DavidDefeat_FR::
	.string "Glubb!\n"
	.string "J'me noie!$"

Route19_Text_DavidPostBattle_FR::
	.string "C'est en pêchant que tu attraperas\n"
	.string "des POKéMON EAU!$"

Route19_Text_TonyIntro_FR::
	.string "La mer, l'écume, les vagues…\n"
	.string "C'est beau!!!$"

Route19_Text_TonyDefeat_FR::
	.string "Aïe!\n"
	.string "T'es pas poète!$"

Route19_Text_TonyPostBattle_FR::
	.string "Je cherche la paix intérieure dans\n"
	.string "la mer!$"

Route19_Text_AnyaIntro_FR::
	.string "Ah, j'en ai marre de nager!$"

Route19_Text_AnyaDefeat_FR::
	.string "Oh!\n"
	.string "J'ai perdu!$"

Route19_Text_AnyaPostBattle_FR::
	.string "C'est vraiment loin les\n"
	.string "ILES ECUME!\p"
	.string "Je vais retourner à PARMANIE.$"

Route19_Text_AliceIntro_FR::
	.string "Nager c'est cool!\n"
	.string "Faut juste éviter de couler!$"

Route19_Text_AliceDefeat_FR::
	.string "Plaouff!$"

Route19_Text_AlicePostBattle_FR::
	.string "Mon p'tit copain veut nager\n"
	.string "jusqu'aux ILES ECUME.$"

Route19_Text_AxleIntro_FR::
	.string "Ces eaux sont dangereuses!$"

Route19_Text_AxleDefeat_FR::
	.string "Argh!\n"
	.string "Dangereux!$"

Route19_Text_AxlePostBattle_FR::
	.string "J'ai une crampe!\n"
	.string "Gloup! Argl!$"

Route19_Text_ConnieIntro_FR::
	.string "Je nage, mais j'en ai marre!$"

Route19_Text_ConnieDefeat_FR::
	.string "J'en peux plus…$"

Route19_Text_ConniePostBattle_FR::
	.string "Un LOKHLASS, c'est grand et gros!\p"
	.string "Si je montes sur son dos,\n"
	.string "je ne serai pas mouillée!$"

Route19_Text_RouteSign_FR::
	.string "ROUTE 19\n"
	.string "PARMANIE - ILES ECUME$"

Route19_Text_LiaIntro_FR::
	.string "VIVI: Je recherche mon frère.\n"
	.string "Il vient de devenir DRESSEUR.$"

Route19_Text_LiaDefeat_FR::
	.string "VIVI: C'est pas une façon de\n"
	.string "traiter mon petit frère!$"

Route19_Text_LiaPostBattle_FR::
	.string "VIVI: Tu as un petit frère toi\n"
	.string "aussi?\p"
	.string "J'espère que tu lui apprends tout\n"
	.string "plein de trucs.$"

Route19_Text_LiaNotEnoughMons_FR::
	.string "VIVI: Je veux me battre aux côtés\n"
	.string "de mon frère.\p"
	.string "Bah, t'as pas deux POKéMON?$"

Route19_Text_LucIntro_FR::
	.string "SAM: Ma grande sœur m'a tout\n"
	.string "appris sur les POKéMON.$"

Route19_Text_LucDefeat_FR::
	.string "SAM: Oh, wow! J'ai trouvé quelqu'un\n"
	.string "de plus fort que ma sœur.$"

Route19_Text_LucPostBattle_FR::
	.string "SAM: Ma grande sœur est balèze\n"
	.string "et sympa. Je l'adore.$"

Route19_Text_LucNotEnoughMons_FR::
	.string "SAM: On s'battra que si j'suis\n"
	.string "avec ma sœur.\p"
	.string "T'as pas deux POKéMON?$"

