Route19_Text_RichardIntro_DE::
	.string "Vor dem Schwimmen muss ich mich\n"
	.string "noch aufwärmen!$"

Route19_Text_RichardDefeat_DE::
	.string "Wunderbar, jetzt ist mir warm!$"

Route19_Text_RichardPostBattle_DE::
	.string "Danke!\n"
	.string "Jetzt kann ich schwimmen gehen!$"

Route19_Text_ReeceIntro_DE::
	.string "Warte! Sonst bekommst du einen\n"
	.string "Herzinfarkt!$"

Route19_Text_ReeceDefeat_DE::
	.string "Wuah!\n"
	.string "Mir ist kalt!$"

Route19_Text_ReecePostBattle_DE::
	.string "Nimm dich vor TENTACHA in Acht!$"

Route19_Text_MatthewIntro_DE::
	.string "Ich gehe gerne schwimmen!\n"
	.string "Du auch?$"

Route19_Text_MatthewDefeat_DE::
	.string "Man, war das ein Bauchplatscher!$"

Route19_Text_MatthewPostBattle_DE::
	.string "Ich kann POKéMON besiegen, während\n"
	.string "ich schwimme!$"

Route19_Text_DouglasIntro_DE::
	.string "Was mag sich hinter dem Horizont\n"
	.string "verbergen?$"

Route19_Text_DouglasDefeat_DE::
	.string "Blubber! Gluck!$"

Route19_Text_DouglasPostBattle_DE::
	.string "Ich sehe eine Inselgruppe!$"

Route19_Text_DavidIntro_DE::
	.string "Ich wollte nach POKéMON tauchen,\n"
	.string "doch das war keine gute Idee!$"

Route19_Text_DavidDefeat_DE::
	.string "Hilfe!$"

Route19_Text_DavidPostBattle_DE::
	.string "Nach WASSER-POKéMON sollte man\n"
	.string "lieber angeln!$"

Route19_Text_TonyIntro_DE::
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"

Route19_Text_TonyDefeat_DE::
	.string "Nein!\n"
	.string "Ein traumatisches Erlebnis!$"

Route19_Text_TonyPostBattle_DE::
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"

Route19_Text_AnyaIntro_DE::
	.string "Gibst du mir das POKéMON, auf dem\n"
	.string "du stehst, wenn ich gewinne?$"

Route19_Text_AnyaDefeat_DE::
	.string "Oh! Ich habe verloren!$"

Route19_Text_AnyaPostBattle_DE::
	.string "Bis zu den SEESCHAUMINSELN ist es\n"
	.string "noch ein weiter Weg!$"

Route19_Text_AliceIntro_DE::
	.string "Schwimmen macht Spaß, aber man\n"
	.string "holt sich schnell einen\l"
	.string "Sonnenbrand!$"

Route19_Text_AliceDefeat_DE::
	.string "Du bist ein ganz schlimmer Finger!$"

Route19_Text_AlicePostBattle_DE::
	.string "Mein Freund wollte zu den\n"
	.string "SEESCHAUMINSELN schwimmen.$"

Route19_Text_AxleIntro_DE::
	.string "Diese Gewässer sind trügerisch!$"

Route19_Text_AxleDefeat_DE::
	.string "Das war gefährlich!$"

Route19_Text_AxlePostBattle_DE::
	.string "Ich habe einen Krampf!\n"
	.string "Blubber, gluck...$"

Route19_Text_ConnieIntro_DE::
	.string "Ich bin hierher geschwommen und\n"
	.string "nun bin ich müde!$"

Route19_Text_ConnieDefeat_DE::
	.string "Ich bin am Ende meiner Kraft...$"

Route19_Text_ConniePostBattle_DE::
	.string "LAPRAS ist so groß, dass es dich\n"
	.string "trockenen Fußes über das Wasser\l"
	.string "tragen kann!$"

Route19_Text_RouteSign_DE::
	.string "SEE-ROUTE 19\n"
	.string "FUCHSANIA CITY - SEESCHAUMINSELN$"

Route19_Text_LiaIntro_DE::
	.string "NORA: Ich kümmere mich um\n"
	.string "meinen Bruder. Er ist vor\l"
	.string "kurzem ein TRAINER geworden.$"

Route19_Text_LiaDefeat_DE::
	.string "NORA: Das ist keine Art meinen\n"
	.string "kleinen Bruder zu behandeln.$"

Route19_Text_LiaPostBattle_DE::
	.string "NORA: Hast du einen kleinen Bruder?\p"
	.string "Ich hoffe, du bringst ihm alles\n"
	.string "Mögliche bei.$"

Route19_Text_LiaNotEnoughMons_DE::
	.string "NORA: Ich möchte mit meinem kleinen\n"
	.string "Bruder zusammen kämpfen.\p"
	.string "Hast du keine zwei POKéMON?$"

Route19_Text_LucIntro_DE::
	.string "TOM: Meine große Schwester hat\n"
	.string "mir das Schwimmen beigebracht\l"
	.string "und mir gezeigt, wie man\l"
	.string "POKéMON trainiert.$"

Route19_Text_LucDefeat_DE::
	.string "TOM: Oh, wow!\n"
	.string "Es gibt jemand, der stärker als\l"
	.string "meine Schwester ist!$"

Route19_Text_LucPostBattle_DE::
	.string "TOM: Meine große Schwester ist\n"
	.string "stark und nett. Sie ist wundervoll.$"

Route19_Text_LucNotEnoughMons_DE::
	.string "TOM: Ich will nicht ohne meine\n"
	.string "Schwester gegen dich kämpfen.\p"
	.string "Hast du keine zwei POKéMON?$"

