Route19_Text_RichardIntro_ES::
    .string "¡Tengo que calentar antes\n"
    .string "de nadar!$"

Route19_Text_RichardDefeat_ES::
    .string "¡Ahora es cuando me encuentro\n"
    .string "en forma!$"

Route19_Text_RichardPostBattle_ES::
    .string "¡Gracias!\n"
    .string "¡Ya puedo nadar!$"

Route19_Text_ReeceIntro_ES::
    .string "¡Alto!\n"
    .string "¡Te va a dar algo!$"

Route19_Text_ReeceDefeat_ES::
    .string "¡¡Auuu!!\n"
    .string "¡Cómo me has dejado!$"

Route19_Text_ReecePostBattle_ES::
    .string "¡Cuidado con TENTACOOL!\n"
    .string "¡Como te pique, no veas!$"

Route19_Text_MatthewIntro_ES::
    .string "¡Me gusta nadar!\n"
    .string "¿Y a ti?$"

Route19_Text_MatthewDefeat_ES::
    .string "¡Vaya planchazo!$"

Route19_Text_MatthewPostBattle_ES::
    .string "¡Puedo ganar a los POKéMON\n"
    .string "nadando!$"

Route19_Text_DouglasIntro_ES::
    .string "¿Qué habrá más allá del horizonte?$"

Route19_Text_DouglasDefeat_ES::
    .string "¡Glup!$"

Route19_Text_DouglasPostBattle_ES::
    .string "¡Veo un par de islas!$"

Route19_Text_DavidIntro_ES::
    .string "¡He buceado en busca de POKéMON,\n"
    .string "pero no he visto nada!$"

Route19_Text_DavidDefeat_ES::
    .string "¡Socorro!$"

Route19_Text_DavidPostBattle_ES::
    .string "¡Tienes que pescar a los POKéMON\n"
    .string "del mar!$"

Route19_Text_TonyIntro_ES::
    .string "¡Miro al mar para olvidar!$"

Route19_Text_TonyDefeat_ES::
    .string "¡Oooooh!\n"
    .string "¡Qué humillación!$"

Route19_Text_TonyPostBattle_ES::
    .string "¡Miro al mar para olvidar!$"

Route19_Text_AnyaIntro_ES::
    .string "¡Qué POKéMON tan guay!\n"
    .string "¿Me lo darás si gano?$"

Route19_Text_AnyaDefeat_ES::
    .string "¡Oh! ¡He perdido!$"

Route19_Text_AnyaPostBattle_ES::
    .string "Queda un largo camino hasta\n"
    .string "las ISLAS ESPUMA...\p"
    .string "Yo quiero volver a FUCSIA...$"

Route19_Text_AliceIntro_ES::
    .string "¡Nadar es genial! ¡Pero no me\n"
    .string "gusta quemarme al sol!$"

Route19_Text_AliceDefeat_ES::
    .string "¡Qué horror!$"

Route19_Text_AlicePostBattle_ES::
    .string "Mi novio quería nadar hasta\n"
    .string "las ISLAS ESPUMA.$"

Route19_Text_AxleIntro_ES::
    .string "¡Estas aguas son traicioneras!$"

Route19_Text_AxleDefeat_ES::
    .string "¡Qué peligro!$"

Route19_Text_AxlePostBattle_ES::
    .string "¡Me ha dado un calambre! ¡Glup!$"

Route19_Text_ConnieIntro_ES::
    .string "He venido nadando hasta aquí,\n"
    .string "pero ya me he cansado.$"

Route19_Text_ConnieDefeat_ES::
    .string "Estoy agotada...$"

Route19_Text_ConniePostBattle_ES::
    .string "Si tuviera que montarme en un\n"
    .string "POKéMON para surcar el mar,\l"
    .string "elegiría a LAPRAS.\p"
    .string "LAPRAS es enorme, si te subes\n"
    .string "encima, seguro que no te mojas.$"

Route19_Text_RouteSign_ES::
    .string "RUTA MARINA 19:\n"
    .string "CIUDAD FUCSIA - ISLAS ESPUMA$"

Route19_Text_LiaIntro_ES::
    .string "CATI: Yo cuido de mi hermano.\n"
    .string "Acaba de hacerse ENTRENADOR.$"

Route19_Text_LiaDefeat_ES::
    .string "CATI: ¡Ésa no es forma de tratar\n"
    .string "a mi hermanito!$"

Route19_Text_LiaPostBattle_ES::
    .string "CATI: ¿Tienes un hermano pequeño?\p"
    .string "Espero que le enseñes cosas.$"

Route19_Text_LiaNotEnoughMons_ES::
    .string "CATI: A mi hermano y a mí nos\n"
    .string "gustaría luchar contigo.\p"
    .string "¿Tienes dos POKéMON?$"

Route19_Text_LucIntro_ES::
    .string "TEC: Mi hermana mayor me ha\n"
    .string "enseñado a nadar y a entrenar\l"
    .string "POKéMON.$"

Route19_Text_LucDefeat_ES::
    .string "TEC: ¡Hala, alguien más fuerte\n"
    .string "que mi hermana!$"

Route19_Text_LucPostBattle_ES::
    .string "TEC: ¡Mi hermana mayor es muy\n"
    .string "fuerte y simpática! ¡Es guay!$"

Route19_Text_LucNotEnoughMons_ES::
    .string "TEC: Si no es con mi hermana,\n"
    .string "no lucharé contigo.\p"
    .string "Además, necesitas dos POKéMON.$"
