Route19_Text_RichardIntro_IT::
    .string "Prima di nuotare bisogna fare\n"
    .string "riscaldamento!$"

Route19_Text_RichardDefeat_IT::
    .string "Ora sì che mi sono riscaldato!$"

Route19_Text_RichardPostBattle_IT::
    .string "Grazie!\n"
    .string "Ora posso tuffarmi!$"

Route19_Text_ReeceIntro_IT::
    .string "Aspetta!\n"
    .string "Ti verrà un accidente!$"

Route19_Text_ReeceDefeat_IT::
    .string "Oooh!!\n"
    .string "Che doccia fredda!$"

Route19_Text_ReecePostBattle_IT::
    .string "Attenzione a TENTACOOL!$"

Route19_Text_MatthewIntro_IT::
    .string "Mi piace nuotare!\n"
    .string "E a te?$"

Route19_Text_MatthewDefeat_IT::
    .string "Che spanciata!$"

Route19_Text_MatthewPostBattle_IT::
    .string "Nuoto meglio dei POKéMON!$"

Route19_Text_DouglasIntro_IT::
    .string "Che c'è oltre l'orizzonte?$"

Route19_Text_DouglasDefeat_IT::
    .string "Glu! Glu!$"

Route19_Text_DouglasPostBattle_IT::
    .string "Vedo un paio di isole!$"

Route19_Text_DavidIntro_IT::
    .string "Mi sono tuffato per prendere dei\n"
    .string "POKéMON, ma zero!$"

Route19_Text_DavidDefeat_IT::
    .string "Aiuto!$"

Route19_Text_DavidPostBattle_IT::
    .string "Cerca di pescare POKéMON di mare!$"

Route19_Text_TonyIntro_IT::
    .string "Guardo il mare per dimenticare!$"

Route19_Text_TonyDefeat_IT::
    .string "Oh!\n"
    .string "Che trauma!$"

Route19_Text_TonyPostBattle_IT::
    .string "Quando sono triste, guardo il mare!$"

Route19_Text_AnyaIntro_IT::
    .string "Ah, usi un POKéMON per spostarti\n"
    .string "sull'acqua!\l"
    .string "Se vinco, me lo dai?$"

Route19_Text_AnyaDefeat_IT::
    .string "Ho perso!\n"
    .string "Peccato!$"

Route19_Text_AnyaPostBattle_IT::
    .string "La via per le ISOLE SPUMARINE è\n"
    .string "ancora lunga!$"

Route19_Text_AliceIntro_IT::
    .string "Nuotare è bello!\n"
    .string "Scottarsi al sole invece no!$"

Route19_Text_AliceDefeat_IT::
    .string "Che orrore!$"

Route19_Text_AlicePostBattle_IT::
    .string "Il mio ragazzo voleva nuotare fino\n"
    .string "alle ISOLE SPUMARINE.$"

Route19_Text_AxleIntro_IT::
    .string "Queste sono acque traditrici!$"

Route19_Text_AxleDefeat_IT::
    .string "Oh!\n"
    .string "È pericoloso!$"

Route19_Text_AxlePostBattle_IT::
    .string "Mi è venuto un crampo!\n"
    .string "Gulp!$"

Route19_Text_ConnieIntro_IT::
    .string "Sono venuta a nuoto.\n"
    .string "Ma ora sono stanca!$"

Route19_Text_ConnieDefeat_IT::
    .string "Sono sfinita!$"

Route19_Text_ConniePostBattle_IT::
    .string "LAPRAS è enorme, su di lui non ti\n"
    .string "bagni di sicuro.$"

Route19_Text_RouteSign_IT::
    .string "PERCORSO MARINO 19\n"
    .string "FUCSIAPOLI - ISOLE SPUMARINE$"

Route19_Text_LiaIntro_IT::
    .string "KATE: Sto aiutando il mio\n"
    .string "fratellino a diventare un bravo\l"
    .string "ALLENATORE.$"

Route19_Text_LiaDefeat_IT::
    .string "KATE: Vacci piano con mio fratello,\n"
    .string "è ancora inesperto.$"

Route19_Text_LiaPostBattle_IT::
    .string "KATE: Anche tu hai un fratellino?\p"
    .string "Se è così, stagli vicino.\n"
    .string "Ha bisogno di te.$"

Route19_Text_LiaNotEnoughMons_IT::
    .string "KATE: Io lotto solo al fianco di\n"
    .string "mio fratello.\p"
    .string "Se non hai almeno due POKéMON,\n"
    .string "non puoi sfidarci.$"

Route19_Text_LucIntro_IT::
    .string "SAM: La mia sorellona mi ha\n"
    .string "insegnato ad allenare i POKéMON!$"

Route19_Text_LucDefeat_IT::
    .string "SAM: Ehi! Tu sei più forte\n"
    .string "della mia sorellona!$"

Route19_Text_LucPostBattle_IT::
    .string "SAM: La mia sorellona è bella e\n"
    .string "forte! È il mio idolo!$"

Route19_Text_LucNotEnoughMons_IT::
    .string "SAM: Senza mia sorella, non\n"
    .string "mi diverto.\p"
    .string "Non hai un altro POKéMON per\n"
    .string "poterci sfidare entrambi?$"

