VictoryRoad_1F_Text_NaomiIntro_IT::
    .string "Mi chiedo se sei all'altezza di\n"
    .string "lottare con me!$"

VictoryRoad_1F_Text_NaomiDefeat_IT::
    .string "Ho perso tutto!$"

VictoryRoad_1F_Text_NaomiPostBattle_IT::
    .string "Non sopporto le sconfitte!$"

VictoryRoad_1F_Text_RolandoIntro_IT::
    .string "Mi sembri forte!\n"
    .string "Dimostramelo!$"

VictoryRoad_1F_Text_RolandoDefeat_IT::
    .string "Ho avuto la mia possibilità!$"

VictoryRoad_1F_Text_RolandoPostBattle_IT::
    .string "Lo ammetto!\n"
    .string "Sei più forte di me!$"

