VictoryRoad_1F_Text_NaomiIntro_ES::
    .string "¡Me pregunto si eres lo bastante\n"
    .string "fuerte para mí!$"

VictoryRoad_1F_Text_NaomiDefeat_ES::
    .string "¡He perdido!$"

VictoryRoad_1F_Text_NaomiPostBattle_ES::
    .string "¡A mí no me gusta perder, y mucho\n"
    .string "menos contra alguien tan joven!$"

VictoryRoad_1F_Text_RolandoIntro_ES::
    .string "¡Ya veo que eres fuerte!\n"
    .string "¡Veamos exactamente cuánto!$"

VictoryRoad_1F_Text_RolandoDefeat_ES::
    .string "He perdido la oportunidad...$"

VictoryRoad_1F_Text_RolandoPostBattle_ES::
    .string "¡Lo admito, eres mejor que yo!$"
