VictoryRoad_1F_Text_NaomiIntro_DE::
	.string "Glaubst du etwa, du kannst es mit\n"
	.string "mir aufnehmen?$"

VictoryRoad_1F_Text_NaomiDefeat_DE::
	.string "Ich bin raus!$"

VictoryRoad_1F_Text_NaomiPostBattle_DE::
	.string "Dabei wollte ich nie verlieren,\n"
	.string "schon gar nicht gegen\l"
	.string "ein kleines Kind…$"

VictoryRoad_1F_Text_RolandoIntro_DE::
	.string "Ich glaube, du bist gut! Gut\n"
	.string "genug, um mich zu schlagen?$"

VictoryRoad_1F_Text_RolandoDefeat_DE::
	.string "Immerhin hatte ich eine Chance!$"

VictoryRoad_1F_Text_RolandoPostBattle_DE::
	.string "Ich muss gestehen, du bist besser!$"

