SevenIsland_TanobyRuins_Text_BrandonIntro_ES::
    .string "¿Sabes algo de esta cámara\n"
    .string "de piedra?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat_ES::
    .string "Oye, tampoco había que recurrir\n"
    .string "a la fuerza.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle_ES::
    .string "Las RUINAS SETE tienen unos\n"
    .string "1.500 años.\p"
    .string "Pero nadie ha conseguido averiguar\n"
    .string "cuál es su razón de ser.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro_ES::
    .string "Dicen que aquí dentro duerme\n"
    .string "un mítico POKéMON.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat_ES::
    .string "A mí lo de los combates no se me\n"
    .string "da bien.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle_ES::
    .string "Yo he oído que hay otras ruinas\n"
    .string "como éstas.\p"
    .string "¿Serán lugares de descanso de\n"
    .string "otros míticos POKéMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro_ES::
    .string "CLEN está enseñándome a pintar.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat_ES::
    .string "Igual nos llaman la atención\n"
    .string "por haber hecho tanto ruido.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle_ES::
    .string "Yo quería pintar un edificio\n"
    .string "antiguo.\p"
    .string "Por eso me trajo CLEN hasta aquí.$"

SevenIsland_TanobyRuins_Text_CliffordIntro_ES::
    .string "Hoy, como complemento a la clase,\n"
    .string "hemos venido a visitar la cámara.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat_ES::
    .string "Qué barbaridad...$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle_ES::
    .string "Así que tú estudias a los POKéMON\n"
    .string "por tu cuenta...\p"
    .string "La verdad es que es digno\n"
    .string "de admiración...$"
