SevenIsland_TanobyRuins_Text_BrandonIntro_DE::
	.string "Weißt du irgendetwas über diese\n"
	.string "Steinkammer?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat_DE::
	.string "Das war überraschend. Du\n"
	.string "hättest nicht so grob sein müssen.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle_DE::
	.string "Die TANIBO-RUINEN sind mindestens\n"
	.string "1500 Jahre alt.\p"
	.string "Aber zunächst ist es ein Geheimnis,\n"
	.string "warum sie überhaupt gebaut wurden.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro_DE::
	.string "Man sagt, dass hier ein mystisches\n"
	.string "POKéMON schlafen soll.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat_DE::
	.string "Ich bin nicht gut beim Kämpfen.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle_DE::
	.string "Ich habe gehört, dass es noch\n"
	.string "andere Ruinen wie diese geben\l"
	.string "soll.\l"
	.string "Vielleicht sind sie die Ruhestätten\l"
	.string "anderer, mystischer POKéMON.$"

SevenIsland_TanobyRuins_Text_EdnaIntro_DE::
	.string "TOM bringt mir das Malen bei!$"

SevenIsland_TanobyRuins_Text_EdnaDefeat_DE::
	.string "Wir könnten Ärger bekommen, wenn\n"
	.string "wir hier so viel Lärm machen.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle_DE::
	.string "Ich sagte, dass ich ein altes\n"
	.string "Gebäude malen wollte.\p"
	.string "Also hat TOM mich hierher\n"
	.string "gebracht.$"

SevenIsland_TanobyRuins_Text_CliffordIntro_DE::
	.string "Heute hat er mir im Anschluss an\n"
	.string "die Unterrichtsstunde die Kammer\l"
	.string "gezeigt.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat_DE::
	.string "Oh, wie außergewöhnlich.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle_DE::
	.string "Ah, du studierst also ganz alleine\n"
	.string "POKéMON…\p"
	.string "Ja, du bist wirklich eine außer-\n"
	.string "ordentliche Persönlichkeit.$"

