SevenIsland_TanobyRuins_Text_BrandonIntro_IT::
    .string "Sai qualcosa su questa sala di\n"
    .string "pietra?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat_IT::
    .string "Ehi, ti avevo solo fatto una\n"
    .string "domanda!!!$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle_IT::
    .string "Le ROVINE risalgono a 1500 anni\n"
    .string "or sono.\p"
    .string "Nessuno sa a cosa servisse\n"
    .string "quell'edificio.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro_IT::
    .string "Pare che lì dentro dorma un\n"
    .string "POKéMON mistico.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat_IT::
    .string "Non sono così bravo a combattere.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle_IT::
    .string "So che ci sono altre rovine come\n"
    .string "questa.\p"
    .string "Chissà se anche le altre rovine\n"
    .string "ospitano POKéMON mistici?$"

SevenIsland_TanobyRuins_Text_EdnaIntro_IT::
    .string "AUGUSTO mi sta insegnando a\n"
    .string "dipingere.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat_IT::
    .string "In questi posti bisogna parlare a\n"
    .string "bassa voce.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle_IT::
    .string "Ho detto ad AUGUSTO che volevo\n"
    .string "dipingere un'antica costruzione.\p"
    .string "Così mi ha portato qui!$"

SevenIsland_TanobyRuins_Text_CliffordIntro_IT::
    .string "Oggi siamo venuti a visitare\n"
    .string "l'antica sala, come parte della\l"
    .string "lezione.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat_IT::
    .string "Straordinario!$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle_IT::
    .string "Vedo che stai studiando i POKéMON\n"
    .string "per conto tuo.\p"
    .string "Beh, sei senz'altro una persona\n"
    .string "eccezionale.$"

