CeruleanCity_House1_Text_AnyInterestInBerries_IT::
    .string "Posso ricavare diversi medicamenti\n"
    .string "dalla FARINA di BACCHE, sai?\p"
    .string "Medicamenti di tutti i tipi!\p"
    .string "Ti interessano le BACCHE?$"

CeruleanCity_House1_Text_HaveJustTheThing_IT::
    .string "Beh, allora ho proprio ciò che\n"
    .string "fa per te!$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner_IT::
    .string "Sai che c'è una novità nei CENTRI\n"
    .string "POKéMON?\p"
    .string "Se vai al primo piano, nella SALA\n"
    .string "DIRETTA, ci trovi un apparecchio\l"
    .string "per macinare le BACCHE.\p"
    .string "Ascolta, posso chiederti un\n"
    .string "piacere?\p"
    .string "Potresti fare un po' di FARINA di\n"
    .string "BACCHE usando quel macchinario?\p"
    .string "Con quella FARINA potrò preparare\n"
    .string "un medicamento formidabile per i\l"
    .string "tuoi POKéMON!\p"
    .string "Ricorda: la macchina MACINABACCHE\n"
    .string "è al primo piano dei CENTRI\l"
    .string "POKéMON, nella SALA DIRETTA.\p"
    .string "So di poter contare su di te!$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries_IT::
    .string "Perché mi racconti bugie?\p"
    .string "Quante BACCHE hai?\n"
    .string "Cosa?! Neanche una?!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings_IT::
    .string "Non ti interessano le BACCHE?\p"
    .string "Guarda che è importante\n"
    .string "interessarsi un po' a tutto, nella\l"
    .string "vita!$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder_IT::
    .string "Allora? Mi hai portato della\n"
    .string "FARINA di BACCHE?$"

CeruleanCity_House5_Text_ExchangeWithWhat_IT::
    .string "Cosa vuoi in cambio?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem_IT::
    .string "Bene: vuoi scambiare la tua FARINA\n"
    .string "di BACCHE con 1 {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder_IT::
    .string "Ehi, non hai abbastanza FARINA di\n"
    .string "BACCHE!$"

CeruleanCity_House1_Text_TradeMoreBerryPowder_IT::
    .string "Questa FARINA di BACCHE è\n"
    .string "eccellente.\p"
    .string "Ne ricaverò degli ottimi\n"
    .string "medicamenti.\p"
    .string "Vuoi scambiare dell'altra FARINA\n"
    .string "di BACCHE per qualcos'altro?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain_IT::
    .string "Bene, come vuoi. Spero di\n"
    .string "rivederti presto!$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder_IT::
    .string "Torna a trovarmi quando vuoi\n"
    .string "scambiare la tua FARINA di BACCHE!$"

