CeruleanCity_House1_Text_AnyInterestInBerries_DE::
	.string "Ich stelle eine Vielzahl\n"
	.string "Medikamente aus BEERENPUDER\l"
	.string "her.\l"
	.string "Mit gutem BEERENPUDER kann\l"
	.string "ich jedes Medikament herstellen!\p"
	.string "Hast du Interesse an BEEREN?$"

CeruleanCity_House1_Text_HaveJustTheThing_DE::
	.string "Schön! Dann habe ich genau\n"
	.string "das Richtige für dich!$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner_DE::
	.string "Im POKéMON-CENTER gibt es im\n"
	.string "oberen Stockwerk beim\l"
	.string "DIREKTKLUB etwas Neues.\l"
	.string "Der Drahtlose GBA-Adapter zum\l"
	.string "BEEREN mahlen wurde\l"
	.string "eingerichtet.\l"
	.string "Da kommst du ins Spiel.\p"
	.string "Du bist der Einzige, den ich\n"
	.string "um diesen Gefallen bitten kann.\p"
	.string "Kannst du mit dieser Maschine\n"
	.string "BEERENPUDER für mich\l"
	.string "herstellen?\l"
	.string "Sie steht im DIREKTKLUB des\l"
	.string "POKéMON-CENTERs.\p"
	.string "Ich werde Medizin herstellen,\n"
	.string "wenn du mir BEERENPUDER\l"
	.string "bringst.\l"
	.string "Mahle BEEREN und bring mir\l"
	.string "BEERENPUDER.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries_DE::
	.string "Warum lügst du mich an?\p"
	.string "Wie viele BEEREN hast du?\n"
	.string "Keine einzige!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings_DE::
	.string "Du interessierst dich nicht für\n"
	.string "BEEREN?\l"
	.string "Auch als Kind sollte man sich\l"
	.string "für alle möglichen Dinge\l"
	.string "interessieren.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder_DE::
	.string "Ähm! Hast du mir BEERENPUDER\n"
	.string "gebracht?$"

CeruleanCity_House5_Text_ExchangeWithWhat_DE::
	.string "Wogegen möchtest du es tauschen?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem_DE::
	.string "Gut, ich gebe dir {STR_VAR_1} im\n"
	.string "Austausch für deinen\l"
	.string "BEERENPUDER!$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder_DE::
	.string "Hm? Du hast nicht genügend\n"
	.string "BEERENPUDER!$"

CeruleanCity_House1_Text_TradeMoreBerryPowder_DE::
	.string "Das ist wirklich erstklassiger\n"
	.string "BEERENPUDER! Daraus lässt\l"
	.string "sich gute Medizin herstellen.\l"
	.string "Möchtest du noch mehr\l"
	.string "BEERENPUDER tauschen?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain_DE::
	.string "Das ist in Ordnung!\n"
	.string "Ich hoffe, wir sehen uns!$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder_DE::
	.string "Komm einfach vorbei, wenn du\n"
	.string "BEERENPUDER tauschen möchtest!$"

