Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests_DE::
	.string "Viele POKéMON leben in Höhlen und\n"
	.string "Wäldern.\p"
	.string "Du solltest dich überall umsehen,\n"
	.string "um verschiedene zu finden!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees_DE::
	.string "Achte auf Büsche am Wegesrand.\p"
	.string "POKéMON können sie mit einer\n"
	.string "Spezial-Technik klein hacken.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution_DE::
	.string "Man kann die Entwicklung eines\n"
	.string "POKéMON stoppen.\p"
	.string "Bricht man sie ab, dann bleibt das\n"
	.string "POKéMON, wie es ist.$"

