Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests_FR::
	.string "De nombreux POKéMON vivent\n"
	.string "uniquement dans les forêts ou les\l"
	.string "cavernes.\p"
	.string "Cherche bien partout pour tous\n"
	.string "les attraper!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees_FR::
	.string "As-tu remarqué les buissons sur la\n"
	.string "route?\p"
	.string "Une technique secrète de POKéMON\n"
	.string "peut les couper.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution_FR::
	.string "Tu peux empêcher un POKéMON\n"
	.string "d'évoluer.\p"
	.string "Quand un POKéMON évolue, tu peux\n"
	.string "stopper le processus.\p"
	.string "C'est une technique pour qu'ils\n"
	.string "restent comme ils sont.$"

