Route20_Text_BarryIntro_DE::
	.string "Das Wasser ist hier sehr flach.$"

Route20_Text_BarryDefeat_DE::
	.string "Platsch!$"

Route20_Text_BarryPostBattle_DE::
	.string "Ich wünschte, ich könnte auf einem\n"
	.string "POKéMON reiten.$"

Route20_Text_ShirleyIntro_DE::
	.string "Die SEESCHAUMINSELN sind ein\n"
	.string "stiller Zufluchtsort!$"

Route20_Text_ShirleyDefeat_DE::
	.string "Schluss damit!$"

Route20_Text_ShirleyPostBattle_DE::
	.string "Unter dieser Insel befindet sich\n"
	.string "eine riesige Höhle!$"

Route20_Text_TiffanyIntro_DE::
	.string "Ich lasse mich gerne mit den\n"
	.string "Fischen treiben!$"

Route20_Text_TiffanyDefeat_DE::
	.string "Autsch!$"

Route20_Text_TiffanyPostBattle_DE::
	.string "Möchtest du mir Gesellschaft\n"
	.string "leisten?$"

Route20_Text_IreneIntro_DE::
	.string "Machst du auch gerade Urlaub?$"

Route20_Text_IreneDefeat_DE::
	.string "Du kennst keine Gnade!$"

Route20_Text_IrenePostBattle_DE::
	.string "Die SEESCHAUMINSELN waren einmal\n"
	.string "EINE große Insel!$"

Route20_Text_DeanIntro_DE::
	.string "Schau dir meinen gestählten Körper\n"
	.string "ruhig an!$"

Route20_Text_DeanDefeat_DE::
	.string "Waschlappen!$"

Route20_Text_DeanPostBattle_DE::
	.string "Ich hätte meine POKéMON stählen\n"
	.string "sollen, nicht meinen Körper!$"

Route20_Text_DarrinIntro_DE::
	.string "Warum reitest du auf dem POKéMON?\n"
	.string "Kannst du nicht schwimmen?$"

Route20_Text_DarrinDefeat_DE::
	.string "Ich wurde torpediert!$"

Route20_Text_DarrinPostBattle_DE::
	.string "Es dürfte Spaß machen, auf einem\n"
	.string "POKéMON zu reiten!$"

Route20_Text_RogerIntro_DE::
	.string "Mein Vogel-POKéMON hat mich\n"
	.string "hierher getragen!$"

Route20_Text_RogerDefeat_DE::
	.string "Oh nein!$"

Route20_Text_RogerPostBattle_DE::
	.string "Kann ich mit meinen Vogel-POKéMON\n"
	.string "noch zurückfliegen?$"

Route20_Text_NoraIntro_DE::
	.string "Mein Freund hat mir eine große\n"
	.string "Perle geschenkt!$"

Route20_Text_NoraDefeat_DE::
	.string "Lass die Finger von meiner Perle!$"

Route20_Text_NoraPostBattle_DE::
	.string "Ob meine Perle in einem AUSTOS\n"
	.string "größer werden würde?$"

Route20_Text_MissyIntro_DE::
	.string "Ich bin von der ZINNOBERINSEL\n"
	.string "herübergeschwommen!$"

Route20_Text_MissyDefeat_DE::
	.string "Ich bin enttäuscht!$"

Route20_Text_MissyPostBattle_DE::
	.string "Auf der ZINNOBERINSEL haben\n"
	.string "POKéMON eine verlassene Villa\l"
	.string "besiedelt!$"

Route20_Text_MelissaIntro_DE::
	.string "Auf der ZINNOBERINSEL befindet\n"
	.string "sich ein POKéMON-LABOR.$"

Route20_Text_MelissaDefeat_DE::
	.string "Warte!$"

Route20_Text_MelissaPostBattle_DE::
	.string "Die ZINNOBERINSEL ist ein\n"
	.string "vulkanisches Eiland!$"

Route20_Text_SeafoamIslands_DE::
	.string "SEESCHAUMINSELN$"

Route20_Text_MistyTrainsHere_DE::
	.string "Starke TRAINER und WASSER-\n"
	.string "POKéMON sind hier weit verbreitet.\p"
	.string "Man sagt, dass MISTY aus der\n"
	.string "ARENA von AZURIA CITY\l"
	.string "hier häufig trainiert.$"

