Route20_Text_BarryIntro_IT::
    .string "Qui l'acqua non è profonda.$"

Route20_Text_BarryDefeat_IT::
    .string "Splash!$"

Route20_Text_BarryPostBattle_IT::
    .string "Vorrei potermi spostare sull'acqua\n"
    .string "sopra uno dei miei POKéMON!$"

Route20_Text_ShirleyIntro_IT::
    .string "Le ISOLE SPUMARINE sono un\n"
    .string "posto tranquillo!$"

Route20_Text_ShirleyDefeat_IT::
    .string "Finiscila!$"

Route20_Text_ShirleyPostBattle_IT::
    .string "C'è un'enorme grotta sotto\n"
    .string "quest'isola.$"

Route20_Text_TiffanyIntro_IT::
    .string "Nuotare con i pesci!\n"
    .string "Che bello!$"

Route20_Text_TiffanyDefeat_IT::
    .string "Ahiahi!$"

Route20_Text_TiffanyPostBattle_IT::
    .string "Vuoi nuotare con me?$"

Route20_Text_IreneIntro_IT::
    .string "Anche tu in vacanza?$"

Route20_Text_IreneDefeat_IT::
    .string "Nessuna pietà!$"

Route20_Text_IrenePostBattle_IT::
    .string "Le ISOLE SPUMARINE una volta\n"
    .string "erano una sola isola!$"

Route20_Text_DeanIntro_IT::
    .string "Guarda che fisico che ho!$"

Route20_Text_DeanDefeat_IT::
    .string "Che imbranato!$"

Route20_Text_DeanPostBattle_IT::
    .string "Avrei dovuto rafforzare i miei\n"
    .string "POKéMON, invece di pensare\l"
    .string "tanto a farmi il fisico!$"

Route20_Text_DarrinIntro_IT::
    .string "Perché ti sposti su di un POKéMON?\n"
    .string "Non sai nuotare?$"

Route20_Text_DarrinDefeat_IT::
    .string "Ahi!\n"
    .string "Silurato!$"

Route20_Text_DarrinPostBattle_IT::
    .string "Spostarsi sull'acqua su di un\n"
    .string "POKéMON! Che trovata!$"

Route20_Text_RogerIntro_IT::
    .string "Sono arrivato a dorso del mio\n"
    .string "POKéMON uccello!$"

Route20_Text_RogerDefeat_IT::
    .string "Oh no!$"

Route20_Text_RogerPostBattle_IT::
    .string "I miei POKéMON uccello sono\n"
    .string "esausti, ora!$"

Route20_Text_NoraIntro_IT::
    .string "Il mio ragazzo mi ha dato delle\n"
    .string "perle giganti!$"

Route20_Text_NoraDefeat_IT::
    .string "Non toccare le mie perle!$"

Route20_Text_NoraPostBattle_IT::
    .string "Cresceranno le mie perle dentro a\n"
    .string "CLOYSTER?$"

Route20_Text_MissyIntro_IT::
    .string "Sono venuta a nuoto dall'ISOLA\n"
    .string "CANNELLA!$"

Route20_Text_MissyDefeat_IT::
    .string "Che delusione!$"

Route20_Text_MissyPostBattle_IT::
    .string "I POKéMON hanno occupato una villa\n"
    .string "abbandonata sull'ISOLA CANNELLA!$"

Route20_Text_MelissaIntro_IT::
    .string "C'è un LABORATORIO POKéMON a\n"
    .string "ovest, sull'ISOLA CANNELLA\p"
    .string "Mio papà lavora lì!$"

Route20_Text_MelissaDefeat_IT::
    .string "Aspetta!$"

Route20_Text_MelissaPostBattle_IT::
    .string "L'ISOLA CANNELLA è di origine\n"
    .string "vulcanica!$"

Route20_Text_SeafoamIslands_IT::
    .string "ISOLE SPUMARINE$"

Route20_Text_MistyTrainsHere_IT::
    .string "Questi posti sono frequentati da\n"
    .string "forti ALLENATORI e POKéMON di\l"
    .string "tipo ACQUA.\p"
    .string "Pare che MISTY di CELESTOPOLI\n"
    .string "si alleni da queste parti.$"

