Route20_Text_BarryIntro_ES::
    .string "El agua es poco profunda aquí.\n"
    .string "Hay mucha gente nadando.$"

Route20_Text_BarryDefeat_ES::
    .string "¡Splash!$"

Route20_Text_BarryPostBattle_ES::
    .string "¡Ojalá pudiera subirme a mi\n"
    .string "POKéMON!$"

Route20_Text_ShirleyIntro_ES::
    .string "¡Las ISLAS ESPUMA son una fácil\n"
    .string "salida!$"

Route20_Text_ShirleyDefeat_ES::
    .string "¡Déjalo ya!$"

Route20_Text_ShirleyPostBattle_ES::
    .string "Hay una enorme caverna debajo\n"
    .string "de esta isla.$"

Route20_Text_TiffanyIntro_ES::
    .string "¡Me gusta flotar en el agua\n"
    .string "rodeada de peces!$"

Route20_Text_TiffanyDefeat_ES::
    .string "¡Auchh!$"

Route20_Text_TiffanyPostBattle_ES::
    .string "¿Quieres flotar conmigo?$"

Route20_Text_IreneIntro_ES::
    .string "¿También estás de vacaciones?$"

Route20_Text_IreneDefeat_ES::
    .string "¡Qué insensible eres!$"

Route20_Text_IrenePostBattle_ES::
    .string "¡Las ISLAS ESPUMA eran antes\n"
    .string "una sola isla!$"

Route20_Text_DeanIntro_ES::
    .string "¡Mira que cuerpazo tengo!$"

Route20_Text_DeanDefeat_ES::
    .string "¡Qué ridículo!$"

Route20_Text_DeanPostBattle_ES::
    .string "¡No debería haber presumido tanto!$"

Route20_Text_DarrinIntro_ES::
    .string "¿Por qué te has subido a un\n"
    .string "POKéMON? ¿No sabes nadar?$"

Route20_Text_DarrinDefeat_ES::
    .string "¡Auch!\n"
    .string "¡Qué fracaso!$"

Route20_Text_DarrinPostBattle_ES::
    .string "¡Subirse a un POKéMON es muy\n"
    .string "divertido!$"

Route20_Text_RogerIntro_ES::
    .string "¡He venido sobre uno de mis\n"
    .string "pájaros POKéMON!$"

Route20_Text_RogerDefeat_ES::
    .string "¡Oh, no!$"

Route20_Text_RogerPostBattle_ES::
    .string "¡Mis pájaros están hechos polvo\n"
    .string "para VOLAR de nuevo!$"

Route20_Text_NoraIntro_ES::
    .string "¡Mi novio me dio unas perlas\n"
    .string "muy grandes!$"

Route20_Text_NoraDefeat_ES::
    .string "¡Ni te acerques a mis perlas!$"

Route20_Text_NoraPostBattle_ES::
    .string "¿Crecerán más mis perlas dentro\n"
    .string "de un CLOYSTER?$"

Route20_Text_MissyIntro_ES::
    .string "¡Vengo nadando desde ISLA\n"
    .string "CANELA! ¡Qué paliza!$"

Route20_Text_MissyDefeat_ES::
    .string "¡Estoy tan decepcionada!$"

Route20_Text_MissyPostBattle_ES::
    .string "¡Los POKéMON invadieron una casa\n"
    .string "abandonada en ISLA CANELA!\p"
    .string "Es la que llaman MANSIÓN\n"
    .string "POKéMON.$"

Route20_Text_MelissaIntro_ES::
    .string "En ISLA CANELA, al oeste, hay\n"
    .string "un LABORATORIO POKéMON.\p"
    .string "Mi papi trabaja allí.$"

Route20_Text_MelissaDefeat_ES::
    .string "¡Espera!\n"
    .string "¡Vas demasiado deprisa!$"

Route20_Text_MelissaPostBattle_ES::
    .string "¡ISLA CANELA es volcánica!\p"
    .string "Dicen que surgió tras la erupción\n"
    .string "de un volcán.$"

Route20_Text_SeafoamIslands_ES::
    .string "ISLAS ESPUMA$"

Route20_Text_MistyTrainsHere_ES::
    .string "Por aquí hay muchos ENTRENADORES\n"
    .string "fuertes y POKéMON del tipo AGUA.\p"
    .string "Dicen que MISTY, del GIMNASIO\n"
    .string "de CELESTE, se entrena por aquí.$"
