Route20_Text_BarryIntro_FR::
	.string "La mer est peu profonde ici,\n"
	.string "n'est-ce pas?$"

Route20_Text_BarryDefeat_FR::
	.string "Splash!$"

Route20_Text_BarryPostBattle_FR::
	.string "Ah, si je pouvais monter sur mes\n"
	.string "POKéMON.$"

Route20_Text_ShirleyIntro_FR::
	.string "Les ILES ECUME sont tranquilles!$"

Route20_Text_ShirleyDefeat_FR::
	.string "Nyann!$"

Route20_Text_ShirleyPostBattle_FR::
	.string "Il y a une grande caverne sous\n"
	.string "cette île.$"

Route20_Text_TiffanyIntro_FR::
	.string "J'aime faire la planche avec les\n"
	.string "poissons!$"

Route20_Text_TiffanyDefeat_FR::
	.string "Glargh!$"

Route20_Text_TiffanyPostBattle_FR::
	.string "Tu veux nager avec moi?$"

Route20_Text_IreneIntro_FR::
	.string "T'es en vacances toi aussi?$"

Route20_Text_IreneDefeat_FR::
	.string "Non!\n"
	.string "Pas de pitié!$"

Route20_Text_IrenePostBattle_FR::
	.string "Avant, ben, les ILES ECUMES ne\n"
	.string "formaient qu'une seule île!$"

Route20_Text_DeanIntro_FR::
	.string "Mate un peu mon corps de rêve!\n"
	.string "C'est beau hein?$"

Route20_Text_DeanDefeat_FR::
	.string "Aïeu!$"

Route20_Text_DeanPostBattle_FR::
	.string "J'aurais dû entraîner un peu\n"
	.string "plus mes POKéMON!$"

Route20_Text_DarrinIntro_FR::
	.string "Ben, t'es sur un POKéMON, tu sais\n"
	.string "pas nager?$"

Route20_Text_DarrinDefeat_FR::
	.string "Ouch!\n"
	.string "Je coule!$"

Route20_Text_DarrinPostBattle_FR::
	.string "Surfer sur un POKéMON, c'est cool!$"

Route20_Text_RogerIntro_FR::
	.string "Mes POKéMON oiseau m'ont\n"
	.string "déposé ici!$"

Route20_Text_RogerDefeat_FR::
	.string "Oh!\n"
	.string "NOoOoOon!$"

Route20_Text_RogerPostBattle_FR::
	.string "Mes oiseaux sont trop fatigués\n"
	.string "pour utiliser VOL!$"

Route20_Text_NoraIntro_FR::
	.string "Mon p'tit copain m'a offert des\n"
	.string "perles sublimes!$"

Route20_Text_NoraDefeat_FR::
	.string "Non!\n"
	.string "Mes perles étaient dedans!$"

Route20_Text_NoraPostBattle_FR::
	.string "Et si je mettais mes perles dans un\n"
	.string "CRUSTABRI?$"

Route20_Text_MissyIntro_FR::
	.string "J'ai nagé depuis CRAMOIS'ILE!$"

Route20_Text_MissyDefeat_FR::
	.string "J'ai bu la tasse!$"

Route20_Text_MissyPostBattle_FR::
	.string "Des POKéMON infestent un vieux\n"
	.string "manoir de CRAMOIS'ILE!\p"
	.string "On l'appelle le MANOIR POKéMON.$"

Route20_Text_MelissaIntro_FR::
	.string "Il y a un LABO POKéMON à\n"
	.string "CRAMOIS'ILE.$"

Route20_Text_MelissaDefeat_FR::
	.string "Attends!$"

Route20_Text_MelissaPostBattle_FR::
	.string "CRAMOIS'ILE est une île\n"
	.string "volcanique!$"

Route20_Text_SeafoamIslands_FR::
	.string "ILES ECUME$"

Route20_Text_MistyTrainsHere_FR::
	.string "On voit souvent des DRESSEURS\n"
	.string "avec des POKéMON EAU par ici.\p"
	.string "Ils disent qu'ONDINE de l'ARENE\n"
	.string "d'AZURIA s'entraîne dans le coin.$"

