SSAnne_Kitchen_Text_BusyOutOfTheWay_FR::
	.string "Hé! Toi là! Y'en a qui bossent\n"
	.string "dur ici! Alors dégage!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash_FR::
	.string "Y'avait une BAIE bizarre dans la\n"
	.string "poubelle. Tu sais ce que c'est?$"

SSAnne_Kitchen_Text_SoBusyImDizzy_FR::
	.string "J'ai trop de boulot! J'en ai \n"
	.string "des vertiges!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay_FR::
	.string "Pourquoi?\n"
	.string "Pourquoi moi?\p"
	.string "J'suis tout l'temps d'corvée\n"
	.string "d'patates…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton_FR::
	.string "Tu connais RONFLEX?\p"
	.string "Il passe ses journées à manger\n"
	.string "et à dormir!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions_FR::
	.string "Sniff…\n"
	.string "… sniff…\p"
	.string "J'épluche des oignons…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs_FR::
	.string "Hm, hm!\n"
	.string "Je suis le chef cuistot!\p"
	.string "Voilà le menu:$"

SSAnne_Kitchen_Text_SalmonDuSalad_FR::
	.string "Salade de saumon!\p"
	.string "Pour ceux qui ne sont pas contents\n"
	.string "c'est la même chose!$"

SSAnne_Kitchen_Text_EelsAuBarbecue_FR::
	.string "Pâté d'anguilles!\p"
	.string "De quoi donner des envies de\n"
	.string "mutinerie!$"

SSAnne_Kitchen_Text_PrimeBeefsteak_FR::
	.string "Côtes de bœuf!\p"
	.string "Mais je crois que je n'ai plus de\n"
	.string "viande?!$"

