SSAnne_Kitchen_Text_BusyOutOfTheWay_ES::
    .string "¡Hola, peque!\n"
    .string "¡Ahora estamos ocupados!\l"
    .string "¡Fuera de aquí!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash_ES::
    .string "He visto una BAYA muy rara en la\n"
    .string "basura. No sé de qué tipo será...$"

SSAnne_Kitchen_Text_SoBusyImDizzy_ES::
    .string "¡Estoy tan ocupado que me estoy\n"
    .string "mareando!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay_ES::
    .string "¿Por qué? ¿Por qué yo?\p"
    .string "¡Me paso todo el día pelando\n"
    .string "patatas!$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton_ES::
    .string "¿Has oído hablar de SNORLAX?\p"
    .string "¡Se pasa todo el día comiendo\n"
    .string "y durmiendo!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions_ES::
    .string "Sniff...sniff...\p"
    .string "Yo sólo pelo cebollas...\n"
    .string "Sniff...$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs_ES::
    .string "¡Ejem!\n"
    .string "¡Por algo soy el CHEF!\p"
    .string "El menú es:$"

SSAnne_Kitchen_Text_SalmonDuSalad_ES::
    .string "¡Ensalada de salmón!\p"
    .string "¡Pero puede que los clientes se\n"
    .string "quejen de tanto repetir pescado!$"

SSAnne_Kitchen_Text_EelsAuBarbecue_ES::
    .string "¡Anguilas a la barbacoa!\p"
    .string "¡Me temo que los clientes se van\n"
    .string "a amotinar!$"

SSAnne_Kitchen_Text_PrimeBeefsteak_ES::
    .string "¡Filetes de ternera!\p"
    .string "Pero ¡¿tengo bastantes filetes\n"
    .string "para todos?!$"
