SSAnne_Kitchen_Text_BusyOutOfTheWay_IT::
    .string "Ehi tu! Abbiamo da fare!\n"
    .string "Fuori dai piedi!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash_IT::
    .string "Ho visto una strana BACCA nella\n"
    .string "spazzatura. Cosa sarà mai?$"

SSAnne_Kitchen_Text_SoBusyImDizzy_IT::
    .string "Sono così occupato che mi gira la\n"
    .string "testa!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay_IT::
    .string "Perché capitano tutte a me?\p"
    .string "Tutti i giorni qui a pelar patate!\n"
    .string "Che penitenza!$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton_IT::
    .string "Hai sentito parlare di SNORLAX?\p"
    .string "Non fa altro che mangiare e\n"
    .string "dormire!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions_IT::
    .string "Uffa!!! Uff!!!\p"
    .string "Sempre io a sbucciar cipolle!\n"
    .string "Uffa!!!$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs_IT::
    .string "Allora!\n"
    .string "Le CHEF c'est moi!\p"
    .string "Voilà le menu!$"

SSAnne_Kitchen_Text_SalmonDuSalad_IT::
    .string "Salade de Saumon!\p"
    .string "Forse gli ospiti diranno\n"
    .string "“Uff, sempre pesce!”$"

SSAnne_Kitchen_Text_EelsAuBarbecue_IT::
    .string "Anguille au Barbecue!\p"
    .string "Penso che ci sarà un\n"
    .string "ammutinamento!$"

SSAnne_Kitchen_Text_PrimeBeefsteak_IT::
    .string "Bistecca ai ferri!\p"
    .string "Ma avrò abbastanza filetti di\n"
    .string "manzo?$"

