SilphCo_2F_Text_ConnorIntro_ES::
    .string "¡Socorro!\n"
    .string "¡Soy un empleado de SILPH S.A.!$"

SilphCo_2F_Text_ConnorDefeat_ES::
    .string "¿Cómo sabías que yo era un\n"
    .string "ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle_ES::
    .string "¡Trabajo para SILPH S.A. y para\n"
    .string "el TEAM ROCKET!$"

SilphCo_2F_Text_JerryIntro_ES::
    .string "¡Estás en zona prohibida!\n"
    .string "¡Vuelve a casa!$"

SilphCo_2F_Text_JerryDefeat_ES::
    .string "¡Eres genial!$"

SilphCo_2F_Text_JerryPostBattle_ES::
    .string "¿Puedes resolver este laberinto?$"

SilphCo_2F_Text_Grunt1Intro_ES::
    .string "¡Aquí no pueden entrar los niños!$"

SilphCo_2F_Text_Grunt1Defeat_ES::
    .string "¡Muy fuerte!$"

SilphCo_2F_Text_Grunt1PostBattle_ES::
    .string "¡Las baldosas con forma\n"
    .string "de diamante son puntos\l"
    .string "de teletransporte!\p"
    .string "¡Son medios de transporte\n"
    .string "de alta tecnología!$"

SilphCo_2F_Text_Grunt2Intro_ES::
    .string "¡Oye, tú!\n"
    .string "¿Qué haces aquí?$"

SilphCo_2F_Text_Grunt2Defeat_ES::
    .string "¡He metido la pata!$"

SilphCo_2F_Text_Grunt2PostBattle_ES::
    .string "¡SILPH S.A. va a fusionarse\n"
    .string "con el TEAM ROCKET!$"

Text_ThunderWaveTeach_ES::
    .string "¡Socorro!\n"
    .string "¡No! ¡Alto!\p"
    .string "¿No perteneces al TEAM ROCKET?\n"
    .string "Yo pensaba...\p"
    .string "Lo siento...\n"
    .string "Eh... ¿te enseño ONDA TRUENO?$"

Text_ThunderWaveDeclined_ES::
    .string "Eh...\n"
    .string "ONDA TRUENO es muy útil...$"

Text_ThunderWaveWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe ONDA TRUENO?$"

Text_ThunderWaveTaught_ES::
    .string "ONDA TRUENO puede paralizar\n"
    .string "al POKéMON que sufre el ataque.\p"
    .string "Y cuando un POKéMON está\n"
    .string "paralizado en combate es posible\l"
    .string "que no se mueva.\p"
    .string "Es un ataque del tipo ELÉCTRICO,\n"
    .string "así que no funcionará contra\l"
    .string "algunos POKéMON.$"

SilphCo_2F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P1$"
