Route21_South_Text_JackIntro_ES::
    .string "¡He conseguido a mi POKéMON\n"
    .string "en el mar, y aquí lo entreno!$"

Route21_South_Text_JackDefeat_ES::
    .string "¡Splash!$"

Route21_South_Text_JackPostBattle_ES::
    .string "¿Dónde atrapaste tus POKéMON?$"

Route21_South_Text_JeromeIntro_ES::
    .string "¡Ahora estoy en un encuentro\n"
    .string "de triatlón!$"

Route21_South_Text_JeromeDefeat_ES::
    .string "Ufff...\n"
    .string "Ufff... Ufff...$"

Route21_South_Text_JeromePostBattle_ES::
    .string "¡Me has ganado! ¡Pero aún falta\n"
    .string "el ciclismo y la maratón!$"

Route21_South_Text_RolandIntro_ES::
    .string "¡Ah!\n"
    .string "¡Siente el sol y el viento!$"

Route21_South_Text_RolandDefeat_ES::
    .string "¡Auuu!\n"
    .string "¡He perdido!$"

Route21_South_Text_RolandPostBattle_ES::
    .string "¡Estoy totalmente quemado!$"

Route21_South_Text_ClaudeIntro_ES::
    .string "¡Eh!\n"
    .string "¡No asustes a los peces!$"

Route21_South_Text_ClaudeDefeat_ES::
    .string "¡Perdona!\n"
    .string "¡No lo hice adrede!$"

Route21_South_Text_ClaudePostBattle_ES::
    .string "¡Estaba enfadado porque no\n"
    .string "había pescado nada!$"

Route21_South_Text_NolanIntro_ES::
    .string "¡Quédate conmigo hasta que lo\n"
    .string "consiga!$"

Route21_South_Text_NolanDefeat_ES::
    .string "Qué forma de matar el tiempo...$"

Route21_South_Text_NolanPostBattle_ES::
    .string "¡Eh!\n"
    .string "¡Algo ha picado! ¡Sí!$"

Route21_North_Text_LilIntro_ES::
    .string "ÍA: ¿Cómo, que quieres luchar?\n"
    .string "IGOR, ¿cómo lo ves?$"

Route21_North_Text_LilDefeat_ES::
    .string "ÍA: ¿Eso es lo que querías,\n"
    .string "que perdiéramos?$"

Route21_North_Text_LilPostBattle_ES::
    .string "ÍA: Estoy cansada, ¿nos vamos ya\n"
    .string "a casa?$"

Route21_North_Text_LilNotEnoughMons_ES::
    .string "ÍA: ¿Luchar? Con sólo un POKéMON\n"
    .string "no nos vamos a tomar la molestia.$"

Route21_North_Text_IanIntro_ES::
    .string "IGOR: Mi hermana no se cansa\n"
    .string "de hacer ejercicio, por eso viene.$"

Route21_North_Text_IanDefeat_ES::
    .string "IGOR: ¡Hermanita, no pasa nada!$"

Route21_North_Text_IanPostBattle_ES::
    .string "IGOR: ¡Hermanita, así no hay forma\n"
    .string "de perder peso!$"

Route21_North_Text_IanNotEnoughMons_ES::
    .string "IGOR: ¡A nosotros nos gusta luchar\n"
    .string "con dos POKéMON, así que...!$"
