Route21_South_Text_JackIntro_DE::
	.string "Ich habe alle meine POKéMON auf\n"
	.string "See gefangen!$"

Route21_South_Text_JackDefeat_DE::
	.string "Platsch!$"

Route21_South_Text_JackPostBattle_DE::
	.string "Wo hast du deine POKéMON gefangen?$"

Route21_South_Text_JeromeIntro_DE::
	.string "Ich nehme an einem Triathlon teil!$"

Route21_South_Text_JeromeDefeat_DE::
	.string "Ächz, schnauf...$"

Route21_South_Text_JeromePostBattle_DE::
	.string "Du hast gewonnen!\n"
	.string "Aber ich kann noch beim Marathon\l"
	.string "und im Radrennen siegen!$"

Route21_South_Text_RolandIntro_DE::
	.string "Ahh!\n"
	.string "Genieße die Sonne und den Wind!$"

Route21_South_Text_RolandDefeat_DE::
	.string "Ups!\n"
	.string "Ich hab verloren!$"

Route21_South_Text_RolandPostBattle_DE::
	.string "Die Sonne hat mich wie ein\n"
	.string "Hähnchen geröstet!$"

Route21_South_Text_ClaudeIntro_DE::
	.string "Heh, du verjagst die Fische!$"

Route21_South_Text_ClaudeDefeat_DE::
	.string "Entschuldigung, ich wollte nicht so\n"
	.string "barsch sein!$"

Route21_South_Text_ClaudePostBattle_DE::
	.string "Ich war nur sauer, weil ich noch\n"
	.string "nichts gefangen habe.$"

Route21_South_Text_NolanIntro_DE::
	.string "Leiste mir Gesellschaft, bis etwas\n"
	.string "anbeißt!$"

Route21_South_Text_NolanDefeat_DE::
	.string "Na ja, wenigstens ist etwas Zeit\n"
	.string "vergangen!$"

Route21_South_Text_NolanPostBattle_DE::
	.string "Juchhu!\n"
	.string "Etwas hat angebissen!$"

Route21_North_Text_LilIntro_DE::
	.string "EWE: Häh? Ein Kampf? TOBI,\n"
	.string "schaffst du das nicht alleine?$"

Route21_North_Text_LilDefeat_DE::
	.string "EWE: Oh, na ja!\n"
	.string "Wir haben verloren. Zufrieden?$"

Route21_North_Text_LilPostBattle_DE::
	.string "EWE: Ich bin müde.\n"
	.string "Können wir nicht schon nach Hause?$"

Route21_North_Text_LilNotEnoughMons_DE::
	.string "EWE: Häh? Ein Kampf? Ich kann\n"
	.string "ihn nicht alleine bestreiten.\l"
	.string "Bring zwei POKéMON, o.k.?$"

Route21_North_Text_IanIntro_DE::
	.string "TOBI: Meine Schwester trainiert\n"
	.string "nicht genug, daher habe ich sie\l"
	.string "gezwungen hierher zu kommen.$"

Route21_North_Text_IanDefeat_DE::
	.string "TOBI: Argh, Schwesterherz!\n"
	.string "Bemüh dich doch!$"

Route21_North_Text_IanPostBattle_DE::
	.string "TOBI: Komm schon, Schwesterlein!\p"
	.string "So wirst du nie Gewicht verlieren!$"

Route21_North_Text_IanNotEnoughMons_DE::
	.string "TOBI: Wir verlangen einen Zwei-\n"
	.string "gegen-Zwei-Kampf. Bring doch zwei\l"
	.string "POKéMON mit!$"

