FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons_FR::
	.string "Tu voyages dans le coin, non?\p"
	.string "J'espère que tu traites tes POKéMON\n"
	.string "avec beaucoup d'amour.\p"
	.string "Laisse-moi voir.\n"
	.string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee_FR::
	.string "Ah, hmm…\n"
	.string "Je vois, je vois…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis_FR::
	.string "Oh, impressionnant.\n"
	.string "Tu t'occupes bien de tes POKéMON.\p"
	.string "Je crois que je peux te faire\n"
	.string "confiance.\p"
	.string "Tiens, je voudrais te donner ceci.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan_FR::
	.string "{PLAYER} reçoit l'OEUF.$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty_FR::
	.string "Malheureusement, il n'y a plus de\n"
	.string "place dans ton équipe.\p"
	.string "Tu devrais repasser me voir\n"
	.string "plus tard.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg_FR::
	.string "やあ\n"
	.string "タマゴを　もらいに\l"
	.string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou_FR::
	.string "J'ai reçu cet OEUF pendant un de\n"
	.string "mes voyages.\p"
	.string "Je suis content de rencontrer\n"
	.string "quelqu'un comme toi.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy_FR::
	.string "Oh, bonjour.\n"
	.string "Il est mignon ton {STR_VAR_2}.\p"
	.string "Il me rappelle une petite fille que\n"
	.string "j'ai rencontrée pendant un voyage.\p"
	.string "Elle adorait ses POKéMON et les\n"
	.string "traitait avec beaucoup d'amour.\p"
	.string "Le nom de cette petite fille, je\n"
	.string "crois que c'est NINA.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro_FR::
	.string "C'est un endroit parfait pour\n"
	.string "élever les POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat_FR::
	.string "Tes POKéMON semblent être\n"
	.string "en pleine forme.$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle_FR::
	.string "Tu sais, je crois que tu feras\n"
	.string "un très bon DRESSEUR.$"

