FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons_ES::
    .string "Vas de aquí para allá, ¿no?\p"
    .string "¿Y no es mucha paliza para\n"
    .string "tus POKéMON?\p"
    .string "Voy a echarles un vistazo.\n"
    .string "... ... ... ... ... ...$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee_ES::
    .string "Mmm...\n"
    .string "Ya veo...$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis_ES::
    .string "Impresionante.\n"
    .string "Tratas muy bien a los POKéMON.\p"
    .string "No hace falta que te diga nada.\p"
    .string "Toma, quiero darte esto.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan_ES::
    .string "¡{PLAYER} recibió un HUEVO!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty_ES::
    .string "Vaya, qué lástima..., tu equipo\n"
    .string "está completo.\p"
    .string "Vuelve a recogerlo en otro\n"
    .string "momento.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg_ES::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou_ES::
    .string "A mí me dieron ese HUEVO cuando\n"
    .string "estuve fuera.\p"
    .string "Me alegro de haber encontrado\n"
    .string "a alguien como tú.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy_ES::
    .string "Hola, ¿qué tal?\n"
    .string "¡Qué {STR_VAR_2} tan mono!\p"
    .string "Al verlo me acuerdo de una niña a\n"
    .string "la que vi cuando estaba de viaje.\p"
    .string "La chiquilla cuidaba con mimo a un\n"
    .string "POKéMON. Era un angelito, la cría.\p"
    .string "Lo que no recuerdo es el nombre...\n"
    .string "Bueno, creo que era DALIA.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro_ES::
    .string "Éste es un sitio estupendo\n"
    .string "para criar POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat_ES::
    .string "¡Tus POKéMON van de maravilla!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle_ES::
    .string "Creo que eres genial criando\n"
    .string "POKéMON.$"
