FuchsiaCity_Gym_Text_KogaIntro_ES::
    .string "KOGA: ¡Uajajaja!\p"
    .string "¿Alguien tan enclenque como tú\n"
    .string "se atreve a desafiarme?\p"
    .string "¡Me parto de la risa!\p"
    .string "¡Como maestro ninja, te enseñaré\n"
    .string "qué es el miedo!\p"
    .string "¡Sentirás la desesperación de las\n"
    .string "técnicas del envenenamiento y del\l"
    .string "sueño!\p"
    .string "¡Adoro a mis temidos POKéMON\n"
    .string "del tipo VENENO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat_ES::
    .string "¡Ejem!\n"
    .string "¡Has demostrado tu valor!\p"
    .string "¡Aquí tienes la MEDALLA ALMA!$"

FuchsiaCity_Gym_Text_KogaPostBattle_ES::
    .string "¡Si los POKéMON son INTOXICADOS\n"
    .string "sufrirán más y más durante el\l"
    .string "combate!\p"
    .string "¡Y lo seguirán haciendo una vez\n"
    .string "que acabe la lucha!\p"
    .string "¡El veneno aterroriza a todo\n"
    .string "el mundo!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge_ES::
    .string "¡Ahora que tienes la MEDALLA ALMA,\n"
    .string "la DEFENSA de tus POKéMON\l"
    .string "aumentará!\p"
    .string "¡Y podrás hacer SURF siempre\n"
    .string "que quieras!\p"
    .string "¡Ah!\n"
    .string "¡Llévate esto también!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga_ES::
    .string "¡{PLAYER} obtuvo la MT06\n"
    .string "de manos de KOGA!$"

FuchsiaCity_Gym_Text_KogaExplainTM06_ES::
    .string "¡La MT06 contiene TÓXICO!\p"
    .string "¡Es una técnica secreta de hace\n"
    .string "más de 400 años!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis_ES::
    .string "¡Hazle sitio a esto!$"

FuchsiaCity_Gym_Text_KaydenIntro_ES::
    .string "La fuerza no es la clave con los\n"
    .string "POKéMON, ¿sabes?\p"
    .string "¡La estrategia es lo importante!\p"
    .string "¡Te enseñaré cómo la estrategia\n"
    .string "puede vencer a la fuerza!$"

FuchsiaCity_Gym_Text_KaydenDefeat_ES::
    .string "¡Extraordinario!$"

FuchsiaCity_Gym_Text_KaydenPostBattle_ES::
    .string "¿Mezclarás fuerza e inteligencia?\n"
    .string "¡Buena táctica!\p"
    .string "¡Es asombroso lo que sabes\n"
    .string "con lo joven que eres!$"

FuchsiaCity_Gym_Text_KirkIntro_ES::
    .string "¡Quería ser un ninja y por eso\n"
    .string "vine a este GIMNASIO!$"

FuchsiaCity_Gym_Text_KirkDefeat_ES::
    .string "¡Vaya, he perdido!$"

FuchsiaCity_Gym_Text_KirkPostBattle_ES::
    .string "¡Seguiré entrenándome con KOGA,\n"
    .string "mi maestro ninja!$"

FuchsiaCity_Gym_Text_NateIntro_ES::
    .string "¡A ver si superas mis técnicas\n"
    .string "especiales!$"

FuchsiaCity_Gym_Text_NateDefeat_ES::
    .string "¡Me has dejado alucinado!$"

FuchsiaCity_Gym_Text_NatePostBattle_ES::
    .string "¡Me gustan los ataques de sueño\n"
    .string "y veneno porque perduran tras\l"
    .string "el combate!$"

FuchsiaCity_Gym_Text_PhilIntro_ES::
    .string "¡Alto ahí!\p"
    .string "¿Te han agobiado nuestros muros\n"
    .string "invisibles?$"

FuchsiaCity_Gym_Text_PhilDefeat_ES::
    .string "¡Buaaa!\n"
    .string "¡Qué bien luchas!$"

FuchsiaCity_Gym_Text_PhilPostBattle_ES::
    .string "¡Impresionante!\p"
    .string "Oye, una cosa: mira bien entre\n"
    .string "los huecos de los muros invisibles.$"

FuchsiaCity_Gym_Text_EdgarIntro_ES::
    .string "¡También estudio técnicas ninja\n"
    .string "con el maestro KOGA!\p"
    .string "¡Los ninja llevan mucho tiempo\n"
    .string "usando animales!$"

FuchsiaCity_Gym_Text_EdgarDefeat_ES::
    .string "¡Auuuu!$"

FuchsiaCity_Gym_Text_EdgarPostBattle_ES::
    .string "¡Me queda mucho por aprender!$"

FuchsiaCity_Gym_Text_ShawnIntro_ES::
    .string "¡El maestro KOGA desciende\n"
    .string "de una gran familia de ninjas!\p"
    .string "¿Y tú de qué familia desciendes?$"

FuchsiaCity_Gym_Text_ShawnDefeat_ES::
    .string "Eres más fuerte de lo que\n"
    .string "pensaba...$"

FuchsiaCity_Gym_Text_ShawnPostBattle_ES::
    .string "¡Donde hay luz hay sombras!\p"
    .string "¡Luz o sombra!\n"
    .string "¿Cuál eliges?$"

FuchsiaCity_Gym_Text_GymGuyAdvice_ES::
    .string "¡Hola, aspirante al título!\p"
    .string "¡El GIMNASIO FUCSIA está lleno de\n"
    .string "muros invisibles!\p"
    .string "¡Podría parecer que KOGA está\n"
    .string "cerca, pero hay muros invisibles\l"
    .string "que lo protegen!\p"
    .string "¡Busca huecos entre los muros\n"
    .string "para llegar hasta él!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory_ES::
    .string "¡Es increíble lo terribles que\n"
    .string "pueden ser los ninjas!$"

FuchsiaCity_Gym_Text_GymStatue_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
