FuchsiaCity_Gym_Text_KogaIntro_DE::
	.string "KOGA: Hahaha!\p"
	.string "Ein Kind fordert einen Ninja-\n"
	.string "Meister zum Kampf heraus?\p"
	.string "Wie du willst! Erlebe eine Welt des\n"
	.string "Schreckens, bevor ich dich\l"
	.string "besiege!\p"
	.string "An meinen Schlaf- und Gift-\n"
	.string "Attacken sollst du verzweifeln!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat_DE::
	.string "Na so was!\n"
	.string "Du bist ein würdiger Kämpfer!\p"
	.string "Ich reiche dir den SEELENORDEN!$"

FuchsiaCity_Gym_Text_KogaPostBattle_DE::
	.string "Wirkt das TOXIN erst einmal,\n"
	.string "leiden POKéMON umso mehr, je\l"
	.string "länger der Kampf dauert!\p"
	.string "Ein wahrer Alptraum für den\n"
	.string "Gegner!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge_DE::
	.string "Nun, da du Träger des\n"
	.string "SEELENORDENS bist, wird die\l"
	.string "ABWEHR deiner POKéMON steigen!\p"
	.string "Ferner kannst du SURFER nun auch\n"
	.string "außerhalb von Kämpfen nutzen!\p"
	.string "Bitte nimm auch dieses Geschenk!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga_DE::
	.string "{PLAYER} erhält\n"
	.string "TM06!$"

FuchsiaCity_Gym_Text_KogaExplainTM06_DE::
	.string "TM06 ist TOXIN!\p"
	.string "Es ist eine mehr als 400 Jahre alte\n"
	.string "Technik!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis_DE::
	.string "Du hast keinen Platz für dieses\n"
	.string "Item!$"

FuchsiaCity_Gym_Text_KaydenIntro_DE::
	.string "Der Erfolg hängt nicht von der\n"
	.string "Stärke deiner POKéMON ab!\p"
	.string "Es kommt auf die Strategie an!\p"
	.string "Intelligenz obsiegt über rohe\n"
	.string "Kraft!$"

FuchsiaCity_Gym_Text_KaydenDefeat_DE::
	.string "Was?\n"
	.string "Außerordentlich!$"

FuchsiaCity_Gym_Text_KaydenPostBattle_DE::
	.string "Du setzt deine Muskeln mit Köpfchen\n"
	.string "ein! Gute Strategie!$"

FuchsiaCity_Gym_Text_KirkIntro_DE::
	.string "Ich möchte später einmal ein Ninja\n"
	.string "werden!$"

FuchsiaCity_Gym_Text_KirkDefeat_DE::
	.string "Ich habe verloren!$"

FuchsiaCity_Gym_Text_KirkPostBattle_DE::
	.string "Ich muss noch eine Menge von KOGA,\n"
	.string "meinem Ninja-Meister, lernen!$"

FuchsiaCity_Gym_Text_NateIntro_DE::
	.string "Kannst du gegen meine SPEZIAL-\n"
	.string "Techniken bestehen?$"

FuchsiaCity_Gym_Text_NateDefeat_DE::
	.string "Du hast mich hereingelegt!$"

FuchsiaCity_Gym_Text_NatePostBattle_DE::
	.string "Ich bevorzuge Schlaf- und Gift-\n"
	.string "Attacken. Ihre Wirkung dauert auch\l"
	.string "nach dem Kampf an!$"

FuchsiaCity_Gym_Text_PhilIntro_DE::
	.string "Bleib stehen!\p"
	.string "Frustrieren dich die unsichtbaren\n"
	.string "Mauern?$"

FuchsiaCity_Gym_Text_PhilDefeat_DE::
	.string "Oh!\n"
	.string "Er hat mich besiegt!$"

FuchsiaCity_Gym_Text_PhilPostBattle_DE::
	.string "Ich bin schwer beeindruckt!\p"
	.string "Ein Tipp: Taste die unsichtbaren\n"
	.string "Mauern nach Durchgängen ab!$"

FuchsiaCity_Gym_Text_EdgarIntro_DE::
	.string "Meister KOGA unterweist mich in der\n"
	.string "Kunst des Ninja-Kampfes!\p"
	.string "Der Einsatz von POKéMON ist eine\n"
	.string "sehr alte Ninja-Tradition!$"

FuchsiaCity_Gym_Text_EdgarDefeat_DE::
	.string "Autsch!$"

FuchsiaCity_Gym_Text_EdgarPostBattle_DE::
	.string "Ich muss noch viel lernen!$"

FuchsiaCity_Gym_Text_ShawnIntro_DE::
	.string "KOGA ist der Nachfahre einer Reihe\n"
	.string "legendärer Ninja-Kämpfer!\p"
	.string "Wer sind deine Vorfahren?$"

FuchsiaCity_Gym_Text_ShawnDefeat_DE::
	.string "Ich habe es vermasselt!$"

FuchsiaCity_Gym_Text_ShawnPostBattle_DE::
	.string "Wo Licht ist, ist auch Schatten!\p"
	.string "Licht oder Schatten!\n"
	.string "Wähle einen Weg!$"

FuchsiaCity_Gym_Text_GymGuyAdvice_DE::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Die ARENA von FUCHSANIA CITY ist\n"
	.string "voller unsichtbarer Mauern!\p"
	.string "Du kannst KOGA sehen, ihn aber\n"
	.string "nicht erreichen!\p"
	.string "Du musst nach Lücken in den\n"
	.string "unsichtbaren Mauern suchen!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory_DE::
	.string "Selbst wenn man sie besiegt hat,\n"
	.string "wirken die Ninjas noch bedrohlich!$"

FuchsiaCity_Gym_Text_GymStatue_DE::
	.string "FUCHSANIA POKéMON-ARENA\n"
	.string "LEITUNG: KOGA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon_DE::
	.string "FUCHSANIA POKéMON-ARENA\n"
	.string "LEITUNG: KOGA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

