FuchsiaCity_Gym_Text_KogaIntro_FR::
	.string "KOGA: Gwahahaha!\p"
	.string "Tu oses me défier? Moi, le\n"
	.string "grand, le beau, le terrible KOGA?\p"
	.string "Par l'enfer, par le sang, par\n"
	.string "l'acier, j'vais gagner!\p"
	.string "Prépare-toi à affronter mes\n"
	.string "terribles POKéMON POISON!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat_FR::
	.string "… heu?\n"
	.string "Tu as prouvé ta valeur!\p"
	.string "Ouvre ta main, car voici…\n"
	.string "le BADGE AME!$"

FuchsiaCity_Gym_Text_KogaPostBattle_FR::
	.string "TOXIK fera souffrir de plus en plus\n"
	.string "un POKéMON pendant un combat!\p"
	.string "Les dégâts augmentent si le\n"
	.string "combat se prolonge!\p"
	.string "De quoi terroriser ses ennemis.$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge_FR::
	.string "Le BADGE AME fera monter la\n"
	.string "DEFENSE de tes POKéMON!\p"
	.string "Il te permettra aussi d'utiliser\n"
	.string "SURF hors des combats!\p"
	.string "Attends!\n"
	.string "Prends aussi ceci!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga_FR::
	.string "{PLAYER} reçoit la\n"
	.string "CT06!$"

FuchsiaCity_Gym_Text_KogaExplainTM06_FR::
	.string "CT06: TOXIK!\p"
	.string "Cette technique secrète et sacrée\n"
	.string "est vieille d'au moins 400 ans.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis_FR::
	.string "Ton inventaire est plein!$"

FuchsiaCity_Gym_Text_KaydenIntro_FR::
	.string "La force ne fait pas tout.\p"
	.string "Avec les POKéMON, l'important\n"
	.string "est d'avoir une bonne stratégie.\p"
	.string "Je te prouverai que la stratégie\n"
	.string "peut vaincre la force.$"

FuchsiaCity_Gym_Text_KaydenDefeat_FR::
	.string "Que?\n"
	.string "Que quoi?$"

FuchsiaCity_Gym_Text_KaydenPostBattle_FR::
	.string "Alors tu mélanges la force\n"
	.string "et l'esprit.\p"
	.string "C'est remarquable pour un DRESSEUR\n"
	.string "de ton âge.$"

FuchsiaCity_Gym_Text_KirkIntro_FR::
	.string "Avant, j'étais magicien.\p"
	.string "Mais j'veux devenir ninja, alors\n"
	.string "j'ai rejoint cette ARENE!$"

FuchsiaCity_Gym_Text_KirkDefeat_FR::
	.string "…\n"
	.string "C'est fini pour moi!$"

FuchsiaCity_Gym_Text_KirkPostBattle_FR::
	.string "Je garderai espoir même dans la\n"
	.string "défaite, selon l'enseignement de\p"
	.string "KOGA, mon maître ninja.$"

FuchsiaCity_Gym_Text_NateIntro_FR::
	.string "Crois-tu pouvoir me battre? Haha!\n"
	.string "Voyons ta technique!$"

FuchsiaCity_Gym_Text_NateDefeat_FR::
	.string "Quoi?\n"
	.string "Tu m'as trompé!$"

FuchsiaCity_Gym_Text_NatePostBattle_FR::
	.string "Les attaques de poison et de\n"
	.string "sommeil sont très puissantes! Oui!$"

FuchsiaCity_Gym_Text_PhilIntro_FR::
	.string "Ne bouge plus!\p"
	.string "Nos fameux murs invisibles sont\n"
	.string "sympas, non? Ça t'énerve?$"

FuchsiaCity_Gym_Text_PhilDefeat_FR::
	.string "Whoa!\n"
	.string "Tu m'as eu!$"

FuchsiaCity_Gym_Text_PhilPostBattle_FR::
	.string "Tu m'as impressionné.\n"
	.string "Voilà un conseil!\p"
	.string "Cherche bien les espaces entre\n"
	.string "les murs…$"

FuchsiaCity_Gym_Text_EdgarIntro_FR::
	.string "J'veux devenir un ninja en\n"
	.string "m'entraînant avec MAITRE KOGA!\p"
	.string "Rien de mieux qu'un ninja pour\n"
	.string "gagner un combat.$"

FuchsiaCity_Gym_Text_EdgarDefeat_FR::
	.string "Aïe!$"

FuchsiaCity_Gym_Text_EdgarPostBattle_FR::
	.string "J'suis nul!$"

FuchsiaCity_Gym_Text_ShawnIntro_FR::
	.string "KOGA fait partie d'une grande\n"
	.string "famille de terribles ninjas!\p"
	.string "Et toi? D'où viens-tu?\n"
	.string "Qui es-tu?$"

FuchsiaCity_Gym_Text_ShawnDefeat_FR::
	.string "…\n"
	.string "Bien plus coriace que je pensais.$"

FuchsiaCity_Gym_Text_ShawnPostBattle_FR::
	.string "Là où il y a de la lumière,\n"
	.string "il y a de l'ombre.\p"
	.string "Que choisis-tu?\n"
	.string "L'ombre ou la lumière?$"

FuchsiaCity_Gym_Text_GymGuyAdvice_FR::
	.string "Hop là!\n"
	.string "Graine de CHAMPION!\p"
	.string "L'ARENE de PARMANIE est un vrai\n"
	.string "casse-tête!\p"
	.string "KOGA te semblera proche, mais de\n"
	.string "nombreux murs le protégeront!\p"
	.string "Trouve les espaces entre les murs\n"
	.string "pour l'atteindre!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory_FR::
	.string "C'est incroyable de voir comme\n"
	.string "les ninjas peuvent faire peur.$"

FuchsiaCity_Gym_Text_GymStatue_FR::
	.string "ARENE POKéMON de PARMANIE\n"
	.string "CHAMPION: KOGA\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon_FR::
	.string "ARENE POKéMON de PARMANIE\n"
	.string "CHAMPION: KOGA\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}, {PLAYER}$"

