#ifndef GUARD_CONSTANTS_LANGUAGE_SELECTOR_H
#define GUARD_CONSTANTS_LANGUAGE_SELECTOR_H

// Core-series language
enum PlayerLanguage
{
    LANG_EN,
    LANG_DE,
    LANG_FR,
    LANG_ES,
    LANG_IT
};

#endif  // GUARD_CONSTANTS_LANGUAGE_SELECTOR_H
