SafariZone_West_Text_RestHouse_IT::
    .string "OSTELLO$"

SafariZone_West_Text_PleaseFindWardensLostTeeth_IT::
    .string "AVVISO\p"
    .string "Chi trova i DENTI D'ORO persi dal\n"
    .string "GUARDIANO della ZONA SAFARI…\p"
    .string "…riceverà una ricompensa!\n"
    .string "Contattare il GUARDIANO!$"

SafariZone_West_Text_SearchForSecretHouse_IT::
    .string "CONSIGLI UTILI\p"
    .string "Operazione esplorazione zona!\n"
    .string "Ricerca della CASA SEGRETA!$"

SafariZone_West_Text_AreaSign_IT::
    .string "ZONA 3 - EST:\n"
    .string "AREA CENTRALE$"

