VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish_ES::
    .string "¡Yo soy el GURÚ PESCADOR!\p"
    .string "¡Me encanta pescar!\n"
    .string "¡Es lo más!\p"
    .string "Y a ti, ¿te gusta pescar?$"

VermilionCity_House1_Text_TakeThisAndFish_ES::
    .string "¡Fenomenal!\n"
    .string "¡Me gusta tu estilo!\p"
    .string "¡Toma esto y pesca, anda!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru_ES::
    .string "¡{PLAYER} recibió una CAÑA VIEJA\n"
    .string "de manos del GURÚ PESCADOR!$"

VermilionCity_House1_Text_FishingIsAWayOfLife_ES::
    .string "¡La pesca es una forma de vida!\n"
    .string "¡Es un arte!\p"
    .string "¡En el mar, en los ríos, da igual,\n"
    .string "hay que pescar el más grande!$"

VermilionCity_House1_Text_OhThatsSoDisappointing_ES::
    .string "Oh...\n"
    .string "Estoy tan decepcionado...$"

VermilionCity_House1_Text_HowAreTheFishBiting_ES::
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Cómo va esa pesca?$"

VermilionCity_House1_Text_NoRoomForNiceGift_ES::
    .string "¡Oh, no!\p"
    .string "¡Tenía un regalo para ti, pero no\n"
    .string "tienes sitio!$"
