VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish_IT::
    .string "Sono il GURU PESCATORE!\p"
    .string "Adoooro pescare!\p"
    .string "E a te piace la pesca?$"

VermilionCity_House1_Text_TakeThisAndFish_IT::
    .string "Ottimo!\n"
    .string "Mi piace il tuo stile!\p"
    .string "Prendi questo e pesca, coraggio!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru_IT::
    .string "{PLAYER} riceve\n"
    .string "l'AMO VECCHIO!$"

VermilionCity_House1_Text_FishingIsAWayOfLife_IT::
    .string "La pesca è uno stile di vita!\p"
    .string "Dai fiumi al mare, pesca il pesce\n"
    .string "più grosso!$"

VermilionCity_House1_Text_OhThatsSoDisappointing_IT::
    .string "Oh!…\n"
    .string "Ma che delusione…$"

VermilionCity_House1_Text_HowAreTheFishBiting_IT::
    .string "Salve, {PLAYER}!\p"
    .string "Come va?\n"
    .string "Abboccano i pesci?$"

VermilionCity_House1_Text_NoRoomForNiceGift_IT::
    .string "Oh no!\p"
    .string "Avevo un regalo per te, ma tu non\n"
    .string "hai più spazio!$"

