SSAnne_1F_Room6_Text_TakeAShortRest_IT::
    .string "Tu e la tua squadra avete\n"
    .string "l'aspetto stanco. Volete fare un\l"
    .string "riposino?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed_IT::
    .string "Vedo che tu e la tua squadra\n"
    .string "siete in piena forma, ora!$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother_IT::
    .string "OK, scusa se mi sono permessa…\n"
    .string "…È che mi ricordi mio fratello.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister_IT::
    .string "OK, scusa se mi sono permessa…\n"
    .string "…È che mi ricordi mia sorella.$"

