SSAnne_1F_Room6_Text_TakeAShortRest_ES::
    .string "¡Tienes una cara de agotamiento!\n"
    .string "¿Quieres descansar un ratito?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed_ES::
    .string "¡Eso ya es otra cosa! ¡Me encanta\n"
    .string "ver a todo el mundo descansado!$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother_ES::
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermano\l"
    .string "pequeño...$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister_ES::
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermana\l"
    .string "pequeña...$"
