CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons_IT::
    .string "EEVEE si evolve in una fra tre\n"
    .string "diverse specie di POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail_IT::
    .string "C'è un messaggio e-mail!\p"
    .string "…\p"
    .string "I tre POKéMON uccelli leggendari\n"
    .string "sono ARTICUNO, ZAPDOS e MOLTRES.\p"
    .string "Localizzazione ignota.\p"
    .string "Esploreremo la grotta vicino a\n"
    .string "CELESTOPOLI.\p"
    .string "Da: SQUADRA RICERCA POKéMON\p"
    .string "…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe_IT::
    .string "Una pipa d'ambra!$"

