CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons_FR::
	.string "EVOLI peut évoluer en un type\n"
	.string "de POKéMON parmi trois différents.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail_FR::
	.string "Il y a un e-mail!\p"
	.string "… … …\p"
	.string "Il existe trois POKéMON oiseau \n"
	.string "légendaires.\p"
	.string "Ce sont ARTIKODIN, ELECTHOR\n"
	.string "et SULFURA.\p"
	.string "On ne sait rien d'eux.\p"
	.string "Nous pensons aller explorer les\n"
	.string "grottes près d'AZURIA.\p"
	.string "De : L'EQUIPE DE RECHERCHE\n"
	.string "POKéMON …$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe_FR::
	.string "Une pipe en ambre!$"

