Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou_IT::
    .string "Ho 6 POKé BALL nella cintura…\p"
    .string "Dovrebbero bastare: al massimo si\n"
    .string "possono avere 6 POKéMON in\l"
    .string "squadra!$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean_IT::
    .string "TEAM ROCKET attacca i cittadini di\n"
    .string "CELESTOPOLI…\p"
    .string "TEAM ROCKET è sempre in prima\n"
    .string "pagina!$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500_IT::
    .string "Ehilà, ciao ragazzino!\n"
    .string "Avrei un'offerta esclusiva per te!\p"
    .string "Ti do un MAGIKARP bello grasso per\n"
    .string "soli ¥500! Che ne dici?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500_IT::
    .string "Ehilà, ciao ragazzina!\n"
    .string "Avrei un'offerta esclusiva per te!\p"
    .string "Ti do un MAGIKARP bello grasso per\n"
    .string "soli ¥500! Che ne dici?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp_IT::
    .string "{PLAYER} ha acquistato MAGIKARP al\n"
    .string "prezzo esorbitante di ¥500!$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou_IT::
    .string "No? Stavo solo cercando di farti\n"
    .string "un favore!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon_IT::
    .string "Pare che non ci sia più spazio\n"
    .string "per nessun altro POKéMON.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney_IT::
    .string "Ti ci vogliono più soldi!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds_IT::
    .string "UOMO: La merce non si cambia!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC_IT::
    .string "Se hai troppi POKéMON, riponili\n"
    .string "nel PC!$"

Route4_PokemonCenter_1F_Text_ItsANewspaper_IT::
    .string "È un giornale!$"

