Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou_FR::
	.string "J'ai 6 POKé BALLS à ma ceinture.\p"
	.string "On ne peut transporter que 6\n"
	.string "POKéMON.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean_FR::
	.string "La TEAM ROCKET a encore attaqué\n"
	.string "les habitants d'AZURIA…\p"
	.string "Pas une journée sans qu'on\n"
	.string "parle d'eux.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500_FR::
	.string "Bonjour l'ami! J'ai une super\n"
	.string "affaire à te proposer!\p"
	.string "Je t'offre un MAGICARPE pour\n"
	.string "juste 500¥! Qu'en dis-tu?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500_FR::
	.string "Bonjour l'amie! J'ai une super\n"
	.string "affaire à te proposer!\p"
	.string "Je t'offre un MAGICARPE pour\n"
	.string "juste 500¥! Qu'en dis-tu?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp_FR::
	.string "{PLAYER} se fait avoir et achète\n"
	.string "le MAGICARPE…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou_FR::
	.string "Non? Allez!\n"
	.string "C'est un service que j'te rends!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon_FR::
	.string "Plus de place pour un POKéMON!$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney_FR::
	.string "T'es à sec, c'est trop dommage!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds_FR::
	.string "Ni repris, ni échangé!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC_FR::
	.string "Tu devrais ranger tes POKéMON en\n"
	.string "trop en utilisant un PC!$"

Route4_PokemonCenter_1F_Text_ItsANewspaper_FR::
	.string "C'est un journal.$"

