Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou_DE::
	.string "An meinem Gürtel hängen sechs\n"
	.string "POKéBÄLLE.\p"
	.string "Man kann maximal sechs POKéMON mit\n"
	.string "sich führen.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean_DE::
	.string "Das TEAM ROCKET terrorisiert die\n"
	.string "Einwohner von AZURIA CITY!\p"
	.string "Kein Tag vergeht ohne Meldungen\n"
	.string "über TEAM ROCKETs Schandtaten!$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500_DE::
	.string "MANN: Hallo! Möchtest du ein\n"
	.string "Geschäft machen?\p"
	.string "Ich gebe dir ein exzellentes\n"
	.string "KARPADOR für läppische 500¥!\p"
	.string "Interessiert?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500_DE::
	.string "MANN: Hallo! Möchtest du ein\n"
	.string "Geschäft machen?\p"
	.string "Ich gebe dir ein exzellentes\n"
	.string "KARPADOR für läppische 500¥!\p"
	.string "Interessiert?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp_DE::
	.string "{PLAYER} bezahlte den Wucherpreis\n"
	.string "von 500¥ für ein KARPADOR…\l"
	.string "$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou_DE::
	.string "Nein? Ich wollte dir doch einen\n"
	.string "Gefallen tun!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon_DE::
	.string "Du hast keinen Platz mehr\n"
	.string "für weitere POKéMON!$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney_DE::
	.string "Schade, du hast nicht genug Geld!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds_DE::
	.string "MANN: Der Umtausch ist\n"
	.string "ausgeschlossen!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC_DE::
	.string "Wenn du keine weiteren POKéMON\n"
	.string "tragen kannst, solltest du einige\l"
	.string "via PC ablegen!$"

Route4_PokemonCenter_1F_Text_ItsANewspaper_DE::
	.string "Eine Zeitung!$"

