PokemonLeague_BrunosRoom_Text_Intro_ES::
    .string "¡Yo soy BRUNO, del ALTO MANDO!\p"
    .string "¡Con un riguroso entrenamiento,\n"
    .string "la gente y los POKéMON pueden\l"
    .string "fortalecerse!\p"
    .string "¡Siempre he vivido con mis POKéMON\n"
    .string "del tipo LUCHA y los he entrenado\l"
    .string "yo mismo!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Os machacaremos con nuestra\n"
    .string "gran fuerza!\p"
    .string "¡Ja, ja, ja!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro_ES::
    .string "¡Yo soy BRUNO, del ALTO MANDO!\p"
    .string "¡Con un riguroso entrenamiento,\n"
    .string "la gente y los POKéMON pueden\l"
    .string "fortalecerse!\p"
    .string "¡Siempre he vivido con mis POKéMON\n"
    .string "del tipo LUCHA y los he entrenado\l"
    .string "yo mismo!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Os machacaremos con nuestra\n"
    .string "gran fuerza!\p"
    .string "¡Ja, ja, ja!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat_ES::
    .string "¿Qué?\n¿Cómo he podido perder?$"

PokemonLeague_BrunosRoom_Text_PostBattle_ES::
    .string "¡Yo ya he hecho mi trabajo!\n"
    .string "¡Te espera tu próximo desafío!$"
