SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick_FR::
	.string "CAPITAINE: Blorf.\n"
	.string "J'suis pas bien.\l"
	.string "Beurp…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack_FR::
	.string "{PLAYER} tape dans le dos\n"
	.string "du CAPITAINE!\p"
	.string "Tap tap…\n"
	.string "Tap tap…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut_FR::
	.string "CAPITAINE: Merci moussaillon!\n"
	.string "Ça va beaucoup mieux…\p"
	.string "Mille sabords! Tu veux voir la\n"
	.string "capacité COUPE?\p"
	.string "Je pourrais te la montrer, mais\n"
	.string "j'suis malade.\p"
	.string "Je sais! Prends ça!\n"
	.string "C'est une CAPSULE SECRETE!\p"
	.string "Elle contient la capacité COUPE.\n"
	.string "Enseigne-la à tes POKéMON\p"
	.string "pour l'utiliser quand tu veux!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain_FR::
	.string "{PLAYER} obtient\n"
	.string "CS01!$"

SSAnne_CaptainsOffice_Text_ExplainCut_FR::
	.string "Avec COUPE, tu peux abattre\n"
	.string "les petits arbres.\p"
	.string "Tu devrais essayer sur les arbres\n"
	.string "près de CARMIN SUR MER.$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon_FR::
	.string "CAPITAINE: Haaaa!\p"
	.string "Maintenant que je suis guéri, on va\n"
	.string "lever l'ancre!\p"
	.string "L'OCEANE va bientôt partir!\p"
	.string "Bon vent! Nous reviendrons\n"
	.string "bientôt à CARMIN SUR MER!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis_FR::
	.string "Ha zut! Tu n'as plus de place pour\n"
	.string "cet objet!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked_FR::
	.string "Quoi?!?\n"
	.string "Il a mangé ça???$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness_FR::
	.string "Comment guérir le mal de mer…\n"
	.string "Le CAPITAINE lit le manuel!$"

