PalletTown_RivalsHouse_Text_HiBrothersAtLab_DE::
	.string "SARAH: Hallo {PLAYER}!\p"
	.string "{RIVAL} wartet in Opas LABOR.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival_DE::
	.string "SARAH: Hallo {PLAYER}! Ich hörte,\n"
	.string "dass du gegen {RIVAL} \l"
	.string "gekämpft hast.\l"
	.string "Das hätte ich gerne gesehen!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp_DE::
	.string "Opa hat dich um einen Botengang\n"
	.string "gebeten?\p"
	.string "Hier, das wird dir weiterhelfen!$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy_DE::
	.string "{PLAYER} erhält\n"
	.string "eine KARTE!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis_DE::
	.string "Du trägst zu viele Dinge mit dir\n"
	.string "herum!$"

PalletTown_RivalsHouse_Text_ExplainTownMap_DE::
	.string "Benutze die KARTE, um deinen\n"
	.string "Standort zu bestimmen.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest_DE::
	.string "SARAH: Wie Menschen sind\n"
	.string "POKéMON Lebewesen!\p"
	.string "Wenn sie erschöpft sind,\n"
	.string "brauchen sie eine Pause!$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto_DE::
	.string "Eine große Karte!\n"
	.string "Sie ist nützlich!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks_DE::
	.string "Wow! Unmengen von Büchern über\n"
	.string "POKéMON!$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon_DE::
	.string "SARAH: Hi! Gutes Timing. Ich war\n"
	.string "gerade dabei, Tee zu machen.\p"
	.string "Hättest du auch gern eine Tasse\n"
	.string "Tee?\p"
	.string "Oh, deine POKéMON sehen ein\n"
	.string "bisschen mitgenommen aus.\p"
	.string "Möchtest du, dass ich eines für\n"
	.string "dich verschönere?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming_DE::
	.string "Möchtest du keines deiner POKéMON\n"
	.string "verschönern lassen?\l"
	.string "Gut, dann trinken wir eben nur Tee.$"

PalletTown_RivalsHouse_Text_GroomWhichOne_DE::
	.string "Welches soll ich verschönern?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime_DE::
	.string "SARAH: Gut. In kürzester Zeit wird\n"
	.string "es hübsch und adrett aussehen.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone_DE::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
	.string "{COLOR DARK_GRAY}{STR_VAR_1} sieht zufrieden aus.\p"
	.string "{COLOR RED}SARAH: Hier bitte. Schon fertig.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
	.string "{FONT_NORMAL}{STR_VAR_1} sieht zufrieden aus.\p"
	.string "SARAH: Hier bitte. Schon fertig.\n"
#endif
	.string "Siehst du? Ist es jetzt nicht\l"
	.string "wunderschön?\p"
	.string "Es ist so ein süßes POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg_DE::
	.string "Es tut mir Leid, aber ich kann\n"
	.string "wirklich kein EI verschönern.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon_DE::
	.string "SARAH: Deine POKéMON werden dich\n"
	.string "lieben, wenn du sie mit Liebe\l"
	.string "trainierst.\l"
	.string "{PLAYER}, darf ich dein erstes\l"
	.string "POKéMON sehen?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore_DE::
	.string "Es liebt dich über alles! Das ist\n"
	.string "so wunderbar und toll!\p"
	.string "Dein POKéMON könnte nicht\n"
	.string "glücklicher sein!$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy_DE::
	.string "Es ist sehr glücklich!\p"
	.string "Ich wünschte, {RIVAL} könnte das\n"
	.string "sehen und etwas daraus lernen.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly_DE::
	.string "Es ist ein guter Freund von dir!\n"
	.string "Behandle es weiterhin gut!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou_DE::
	.string "Es nähert sich dir an! Euer gegen-\n"
	.string "seitiges Vertrauen muss noch\l"
	.string "besser werden!$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet_DE::
	.string "Es kennt dich noch nicht gut!\p"
	.string "POKéMON sind zunächst skeptisch,\n"
	.string "wenn man sie fängt!$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou_DE::
	.string "{PLAYER}, ich mag gar nicht, wie es\n"
	.string "dich anschaut!\p"
	.string "Du solltest etwas liebevoller mit\n"
	.string "ihm umgehen!$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch_DE::
	.string "… äh, ich weiß nicht wie ich\n"
	.string "es sagen soll, aber…\p"
	.string "Gibt es einen Grund, warum dich\n"
	.string "dein POKéMON so abgrundtief hasst?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy_DE::
	.string "Das liebliche, zuckersüße\n"
	.string "PIEPI.$"

