PalletTown_RivalsHouse_Text_HiBrothersAtLab_IT::
    .string "MARGI: Ciao {PLAYER}!\p"
    .string "Mio fratello {RIVAL} è al\n"
    .string "LABORATORIO del nonno.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival_IT::
    .string "MARGI: {PLAYER}, ho sentito che\n"
    .string "hai lottato contro {RIVAL}.\p"
    .string "Peccato che non vi ho visto\n"
    .string "combattere!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp_IT::
    .string "Il nonno ti ha chiesto di fargli un\n"
    .string "favore? Tieni, ti sarà d'aiuto!$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy_IT::
    .string "{PLAYER} riceve la\n"
    .string "MAPPA CITTÀ.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis_IT::
    .string "Ti porti troppe cose addosso!$"

PalletTown_RivalsHouse_Text_ExplainTownMap_IT::
    .string "Usa la MAPPA CITTÀ per\n"
    .string "vedere dove sei.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest_IT::
    .string "MARGI: I POKéMON, come gli uomini,\n"
    .string "sono esseri viventi.\p"
    .string "Quando sono stanchi, bisogna farli\n"
    .string "riposare.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto_IT::
    .string "È una mappa enorme e utile!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks_IT::
    .string "È pieno zeppo di libri POKéMON!$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon_IT::
    .string "MARGI: Ciao, capiti a fagiolo: sto\n"
    .string "facendo il tè.\p"
    .string "Vuoi favorire?\p"
    .string "I tuoi POKéMON sono stanchi.\n"
    .string "Vuoi che te ne spazzoli uno?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming_IT::
    .string "MARGI: Non vuoi che te ne spazzoli\n"
    .string "uno? OK, beviamo soltanto.$"

PalletTown_RivalsHouse_Text_GroomWhichOne_IT::
    .string "MARGI: Quale vuoi far spazzolare?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime_IT::
    .string "MARGI: In un minuto diventerà\n"
    .string "splendido.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone_IT::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
	.string "{COLOR DARK_GRAY}{STR_VAR_1} ha un aspetto felice.\p"
    .string "{COLOR RED}MARGI: Ecco qui, ho finito!\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} ha un aspetto felice.\p"
    .string "{FONT_FEMALE}MARGI: Ecco qui, ho finito!\n"
#endif
    .string "È bello, non credi?\p"
    .string "È un POKéMON così carino!$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg_IT::
    .string "Mi spiace, ma non posso proprio\n"
    .string "spazzolare un UOVO!$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon_IT::
    .string "MARGI: Se allevi i tuoi POKéMON\n"
    .string "con amore, ti vorranno bene.\p"
    .string "Per esempio, {PLAYER}, posso vedere\n"
    .string "il tuo primo POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore_IT::
    .string "Ti vuole un bene enorme!\p"
    .string "Non potrebbe esserti più\n"
    .string "affezionato di così!\p"
    .string "Il tuo POKéMON è al settimo\n"
    .string "cielo!$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy_IT::
    .string "È molto felice!\p"
    .string "Vorrei che {RIVAL} lo vedesse,\n"
    .string "così imparerebbe qualcosa.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly_IT::
    .string "Questo POKéMON ti è amico.\n"
    .string "Continua a trattarlo bene!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou_IT::
    .string "Questo POKéMON non si\n"
    .string "fida ancora molto di te.\p"
    .string "Il vostro rapporto deve\n"
    .string "ancora migliorare.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet_IT::
    .string "Questo POKéMON non si\n"
    .string "fida ancora di te.\p"
    .string "Appena li catturi, i POKéMON\n"
    .string "sono piuttosto diffidenti.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou_IT::
    .string "{PLAYER}, non mi piace il modo\n"
    .string "in cui ti guarda.\p"
    .string "Cerca di trattarlo un po' meglio.$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch_IT::
    .string "È un po' difficile… come dire…\p"
    .string "Questo POKéMON ti detesta proprio!\n"
    .string "Non è imbarazzante?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy_IT::
    .string "Il tenero e dolce\n"
    .string "CLEFAIRY.$"

