SilphCo_8F_Text_WonderIfSilphIsFinished_IT::
    .string "Chissà se per la SILPH è finita.$"

SilphCo_8F_Text_ThanksForSavingUs_IT::
    .string "Grazie per averci salvato!$"

SilphCo_8F_Text_Grunt1Intro_IT::
    .string "Non potrai andare oltre!$"

SilphCo_8F_Text_Grunt1Defeat_IT::
    .string "Non sono stato abbastanza\n"
    .string "grintoso!$"

SilphCo_8F_Text_Grunt1PostBattle_IT::
    .string "Gira i tacchi o chiamo rinforzi!$"

SilphCo_8F_Text_ParkerIntro_IT::
    .string "Ci stai dando un sacco di problemi!$"

SilphCo_8F_Text_ParkerDefeat_IT::
    .string "Cosa?\n"
    .string "Ho perso?$"

SilphCo_8F_Text_ParkerPostBattle_IT::
    .string "Cosa pensi della SILPH?\n"
    .string "Un vero labirinto, eh?$"

SilphCo_8F_Text_Grunt2Intro_IT::
    .string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat_IT::
    .string "Che botta, fratelli miei!$"

SilphCo_8F_Text_Grunt2PostBattle_IT::
    .string "Ti lascio nelle mani dei miei\n"
    .string "fratelli!$"

SilphCo_8F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "7ºP$"

SilphCo_8F_Text_ToRocketBossMonsAreTools_IT::
    .string "Il CAPO di TEAM ROCKET\n"
    .string "è orribilmente crudele!\p"
    .string "Per lui, i POKéMON sono\n"
    .string "solo strumenti.\p"
    .string "Se quel furfante si impossessasse\n"
    .string "dell'azienda, sarebbe tremendo…$"

