SilphCo_8F_Text_WonderIfSilphIsFinished_FR::
	.string "Mmm… La SYLPHE va-t-elle faire\n"
	.string "faillite?$"

SilphCo_8F_Text_ThanksForSavingUs_FR::
	.string "Merci de nous avoir sauvés!$"

SilphCo_8F_Text_Grunt1Intro_FR::
	.string "Hop hop hop!\n"
	.string "On ne bouge plus!$"

SilphCo_8F_Text_Grunt1Defeat_FR::
	.string "Je suis faible!$"

SilphCo_8F_Text_Grunt1PostBattle_FR::
	.string "Va-t-en ou j'appelle du renfort!$"

SilphCo_8F_Text_ParkerIntro_FR::
	.string "Tu nous casses les pieds!$"

SilphCo_8F_Text_ParkerDefeat_FR::
	.string "Heu?\n"
	.string "J'ai perdu?$"

SilphCo_8F_Text_ParkerPostBattle_FR::
	.string "La SYLPHE est un vrai labyrinthe,\n"
	.string "hein?$"

SilphCo_8F_Text_Grunt2Intro_FR::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat_FR::
	.string "Whoo!\n"
	.string "Frèèèères!$"

SilphCo_8F_Text_Grunt2PostBattle_FR::
	.string "Mes frères te dégommeront!$"

SilphCo_8F_Text_FloorSign_FR::
	.string "SYLPHE SARL.\n"
	.string "7ème étage.$"

SilphCo_8F_Text_ToRocketBossMonsAreTools_FR::
	.string "Le chef de la TEAM ROCKET est\n"
	.string "incroyablement cruel.\p"
	.string "Pour lui, les POKéMON ne sont que\n"
	.string "des outils.\p"
	.string "Qu'arrivera-t-il s'il arrive à\n"
	.string "s'emparer de notre compagnie?$"

