SilphCo_8F_Text_WonderIfSilphIsFinished_ES::
    .string "Me pregunto si SILPH estará\n"
    .string "acabada.$"

SilphCo_8F_Text_ThanksForSavingUs_ES::
    .string "¡Gracias por salvarnos!$"

SilphCo_8F_Text_Grunt1Intro_ES::
    .string "¡No podrás ir más lejos!$"

SilphCo_8F_Text_Grunt1Defeat_ES::
    .string "¡No eres tan valiente!$"

SilphCo_8F_Text_Grunt1PostBattle_ES::
    .string "¡Si no retrocedes, pediré\n"
    .string "refuerzos!$"

SilphCo_8F_Text_ParkerIntro_ES::
    .string "¡Nos estás dando muchos problemas!$"

SilphCo_8F_Text_ParkerDefeat_ES::
    .string "¿Qué?\n"
    .string "¿He perdido?$"

SilphCo_8F_Text_ParkerPostBattle_ES::
    .string "¿Qué opinas del laberinto del\n"
    .string "EDIFICIO SILPH?$"

SilphCo_8F_Text_Grunt2Intro_ES::
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat_ES::
    .string "¡Ahhhg!\n"
    .string "¡Hermanos! ¡Tenéis que vengarme!$"

SilphCo_8F_Text_Grunt2PostBattle_ES::
    .string "¡Mis hermanos se encargarán de ti!$"

SilphCo_8F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P7$"

SilphCo_8F_Text_ToRocketBossMonsAreTools_ES::
    .string "¡El JEFE del TEAM ROCKET es muy\n"
    .string "cruel!\p"
    .string "Sólo quiere a los POKéMON para\n"
    .string "luchar.\p"
    .string "No quiero ni pensar lo que podría\n"
    .string "ocurrir si se hiciera con el mando\l"
    .string "de la compañía...$"
