SSAnne_2F_Room4_Text_LamarIntro_IT::
    .string "Cosa preferisci?\n"
    .string "Un POKéMON forte o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat_IT::
    .string "Tanto di cappello!$"

SSAnne_2F_Room4_Text_LamarPostBattle_IT::
    .string "Io preferisco quelli forti e rari!$"

SSAnne_2F_Room4_Text_DawnIntro_IT::
    .string "Non mi pare di averti visto alla\n"
    .string "festa.$"

SSAnne_2F_Room4_Text_DawnDefeat_IT::
    .string "Vacci piano!$"

SSAnne_2F_Room4_Text_DawnPostBattle_IT::
    .string "Oh, i tuoi POKéMON sono fantastici!$"

