SSAnne_2F_Room4_Text_LamarIntro_ES::
    .string "¿Qué prefieres, un POKéMON fuerte\n"
    .string "o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat_ES::
    .string "¡Debo felicitarte!$"

SSAnne_2F_Room4_Text_LamarPostBattle_ES::
    .string "¡Prefiero los POKéMON fuertes\n"
    .string "y raros!$"

SSAnne_2F_Room4_Text_DawnIntro_ES::
    .string "No te he visto en la fiesta.$"

SSAnne_2F_Room4_Text_DawnDefeat_ES::
    .string "¡Oye!\n"
    .string "¡¡¡No había que ponerse así!!!$"

SSAnne_2F_Room4_Text_DawnPostBattle_ES::
    .string "¡Oh!\n"
    .string "¡Adoro a tus fuertes POKéMON!$"
