SSAnne_2F_Room4_Text_LamarIntro_DE::
	.string "Was magst du lieber?\n"
	.string "Starke oder seltene POKéMON?$"

SSAnne_2F_Room4_Text_LamarDefeat_DE::
	.string "Ich ziehe meinen Hut vor dir! Wow!$"

SSAnne_2F_Room4_Text_LamarPostBattle_DE::
	.string "Ich mag POKéMON, die stark und\n"
	.string "selten sind!$"

SSAnne_2F_Room4_Text_DawnIntro_DE::
	.string "Wo warst du, als die Party lief?$"

SSAnne_2F_Room4_Text_DawnDefeat_DE::
	.string "Mach langsam!!!$"

SSAnne_2F_Room4_Text_DawnPostBattle_DE::
	.string "Ich bewundere die Stärke deiner\n"
	.string "POKéMON!$"

