SSAnne_2F_Room4_Text_LamarIntro_FR::
	.string "Qu'est-ce que tu préfères?\n"
	.string "Un POKéMON costaud ou rare?$"

SSAnne_2F_Room4_Text_LamarDefeat_FR::
	.string "Bravo!\n"
	.string "Tu es plutôt balèze!$"

SSAnne_2F_Room4_Text_LamarPostBattle_FR::
	.string "Je préfère les POKéMON rares\n"
	.string "et costauds!$"

SSAnne_2F_Room4_Text_DawnIntro_FR::
	.string "Je ne crois pas que tu étais \n"
	.string "à la fête.$"

SSAnne_2F_Room4_Text_DawnDefeat_FR::
	.string "Relax!\n"
	.string "T'énerve pas!!!$"

SSAnne_2F_Room4_Text_DawnPostBattle_FR::
	.string "Woah! Tes POKéMON sont super\n"
	.string "forts! Je les adore!$"

