SafariZone_East_Text_KeepAnyItemFoundOnSafari_FR::
	.string "Tu peux garder tous les objets\n"
	.string "trouvés dans le coin.\p"
	.string "Mais ne perds pas de temps à tous\n"
	.string "les essayer!$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone_FR::
	.string "Le coin le plus reculé du PARC\n"
	.string "SAFARI cache un prix spécial!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon_FR::
	.string "Mon EVOLI s'est transformé en\n"
	.string "PYROLI!\p"
	.string "Mais celui d'un ami s'est changé\n"
	.string "en AQUALI! Bah pourquoi?$"

