ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto_ES::
    .string "Eh, ¿te has enterado?\p"
    .string "Ahora podemos estar en red\n"
    .string "con los PCs de KANTO.\p"
    .string "¡No sé quién lo habrá organizado,\n"
    .string "pero me parece una idea estupenda!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands_ES::
    .string "Es imposible hacer SURF\n"
    .string "entre las islas de esta zona.\p"
    .string "Hay corrientes y remolinos.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest_ES::
    .string "¡Vamos a MACHACAR BAYAS!\n"
    .string "¿Que sería un desperdicio de BAYAS\l"
    .string "dices?...\p"
    .string "¡Pero si el BOSQUE BAYA está hasta\n"
    .string "arriba!$"
