ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto_IT::
    .string "Ehi, hai sentito?\p"
    .string "Ora la Centralina Network è in\n"
    .string "grado di collegarsi con i PC di\l"
    .string "KANTO!\p"
    .string "Non so come sia possibile,\n"
    .string "ma è fantastico!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands_IT::
    .string "Non si può usare SURF per andare\n"
    .string "da un'isola all'altra.\p"
    .string "Le maree sono troppo rapide e\n"
    .string "pericolose.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest_IT::
    .string "Maciniamo le BACCHE!\n"
    .string "Non c'è pericolo che finiscano!\p"
    .string "Ne puoi sempre trovare tantissime\n"
    .string "sul terreno del BOSCO BACCOSO!$"

