OneIsland_KindleRoad_Text_MariaIntro_IT::
    .string "Che bella giornata!\n"
    .string "Perfetta per una lotta!$"

OneIsland_KindleRoad_Text_MariaDefeat_IT::
    .string "No, ti prego!$"

OneIsland_KindleRoad_Text_MariaPostBattle_IT::
    .string "Non spruzzarmi l'acqua in faccia!$"

OneIsland_KindleRoad_Text_AbigailIntro_IT::
    .string "Sento che sto per scottarmi!\n"
    .string "Userò la protezione solare!$"

OneIsland_KindleRoad_Text_AbigailDefeat_IT::
    .string "Sei terribile!$"

OneIsland_KindleRoad_Text_AbigailPostBattle_IT::
    .string "Mi piace il tuo berretto, dovrei\n"
    .string "comprarne uno così anch'io.$"

OneIsland_KindleRoad_Text_FinnIntro_IT::
    .string "Visto com'è imperioso da qui\n"
    .string "il MONTE BRACE?$"

OneIsland_KindleRoad_Text_FinnDefeat_IT::
    .string "Sai che sei proprio forte?$"

OneIsland_KindleRoad_Text_FinnPostBattle_IT::
    .string "Il cielo è stupendo da queste\n"
    .string "parti.$"

OneIsland_KindleRoad_Text_GarrettIntro_IT::
    .string "Non dirmi che ho interrotto la mia\n"
    .string "nuotata soltanto per sfidarti!$"

OneIsland_KindleRoad_Text_GarrettDefeat_IT::
    .string "Ehi, non sei così male!$"

OneIsland_KindleRoad_Text_GarrettPostBattle_IT::
    .string "SURF è comodo, ma preferisco\n"
    .string "nuotare.$"

OneIsland_KindleRoad_Text_TommyIntro_IT::
    .string "Aspetta! Questa volta deve aver\n"
    .string "abboccato un pesce enorme!$"

OneIsland_KindleRoad_Text_TommyDefeat_IT::
    .string "Oggi mi vanno tutte storte.$"

OneIsland_KindleRoad_Text_TommyPostBattle_IT::
    .string "Ho perso sia la sfida che il\n"
    .string "pesce che aveva abboccato!$"

OneIsland_KindleRoad_Text_SharonIntro_IT::
    .string "Ti alleni un po' con me?$"

OneIsland_KindleRoad_Text_SharonDefeat_IT::
    .string "Sei più forte, non c'è dubbio.$"

OneIsland_KindleRoad_Text_SharonPostBattle_IT::
    .string "Hai stoffa, si vede!$"

OneIsland_KindleRoad_Text_TanyaIntro_IT::
    .string "Mi alleno tutti i giorni con i miei\n"
    .string "POKéMON!$"

OneIsland_KindleRoad_Text_TanyaDefeat_IT::
    .string "L'allenamento non è bastato…$"

OneIsland_KindleRoad_Text_TanyaPostBattle_IT::
    .string "È chiaro che devo allenarmi\n"
    .string "di più!$"

OneIsland_KindleRoad_Text_SheaIntro_IT::
    .string "Ogni giorno, prima di colazione,\n"
    .string "nuoto intorno all'isola.$"

OneIsland_KindleRoad_Text_SheaDefeat_IT::
    .string "Gasp…\n"
    .string "Gasp…$"

OneIsland_KindleRoad_Text_SheaPostBattle_IT::
    .string "Forse ho perso perché mi alleno\n"
    .string "troppo.$"

OneIsland_KindleRoad_Text_HughIntro_IT::
    .string "Ti sembra di avere un abbigliamento\n"
    .string "appropriato per lottare?$"

OneIsland_KindleRoad_Text_HughDefeat_IT::
    .string "Perché?$"

OneIsland_KindleRoad_Text_HughPostBattle_IT::
    .string "I cultori di arti marziali curano\n"
    .string "sempre di più il proprio aspetto.$"

OneIsland_KindleRoad_Text_BryceIntro_IT::
    .string "Tutto sembra più saporito quando\n"
    .string "ti trovi a contatto con la natura!$"

OneIsland_KindleRoad_Text_BryceDefeat_IT::
    .string "Che peccato!$"

OneIsland_KindleRoad_Text_BrycePostBattle_IT::
    .string "Nelle aree vulcaniche l'acqua è\n"
    .string "ricca di minerali.$"

OneIsland_KindleRoad_Text_ClaireIntro_IT::
    .string "Ora che ho mangiato, ho proprio\n"
    .string "voglia di una bella lotta!$"

OneIsland_KindleRoad_Text_ClaireDefeat_IT::
    .string "Che sudata!$"

OneIsland_KindleRoad_Text_ClairePostBattle_IT::
    .string "Dopo aver lottato mi è venuta\n"
    .string "di nuovo fame!$"

OneIsland_KindleRoad_Text_KiaIntro_IT::
    .string "KIA: Io e il mio fratellone siamo\n"
    .string "una forza!$"

OneIsland_KindleRoad_Text_KiaDefeat_IT::
    .string "KIA: Non ci posso credere!$"

OneIsland_KindleRoad_Text_KiaPostBattle_IT::
    .string "KIA: Non posso credere che tu\n"
    .string "sia più in gamba di mio fratello!$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons_IT::
    .string "KIA: Per lottare con noi, devi\n"
    .string "avere con te almeno due\l"
    .string "POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro_IT::
    .string "MIK: Con KIA al mio fianco,\n"
    .string "niente mi fa paura!$"

OneIsland_KindleRoad_Text_MikDefeat_IT::
    .string "MIK: Ehi, ma questo è\n"
    .string "davvero troppo!$"

OneIsland_KindleRoad_Text_MikPostBattle_IT::
    .string "MIK: Credevo che io e KIA,\n"
    .string "insieme, fossimo imbattibili!$"

OneIsland_KindleRoad_Text_MikNotEnoughMons_IT::
    .string "MIK: Ehi, vuoi lottare contro\n"
    .string "di noi?\p"
    .string "Allora ritorna con almeno due\n"
    .string "POKéMON in squadra.$"

OneIsland_KindleRoad_Text_RouteSign_IT::
    .string "Questa è la VIA VULCANICA.\p"
    .string "Per di qui si arriva al\n"
    .string "MONTE BRACE.$"

OneIsland_KindleRoad_Text_EmberSpaSign_IT::
    .string "TERME LAVICHE\n"
    .string "Ti riscaldano il cuore!$"

