OneIsland_KindleRoad_Text_MariaIntro_ES::
    .string "¡Hace un día espléndido!\n"
    .string "¡El tiempo ideal para luchar!$"

OneIsland_KindleRoad_Text_MariaDefeat_ES::
    .string "¡Ayyyyyy!$"

OneIsland_KindleRoad_Text_MariaPostBattle_ES::
    .string "¡Bueno, por lo menos no me\n"
    .string "has quitado el maquillaje!$"

OneIsland_KindleRoad_Text_AbigailIntro_ES::
    .string "Me estoy empezando a quemar...$"

OneIsland_KindleRoad_Text_AbigailDefeat_ES::
    .string "¡Eres lo peor!$"

OneIsland_KindleRoad_Text_AbigailPostBattle_ES::
    .string "Me gusta la ropa que llevas. Igual\n"
    .string "me convendría ponerme algo...$"

OneIsland_KindleRoad_Text_FinnIntro_ES::
    .string "Si lo miras desde aquí, parece\n"
    .string "que el MT. ASCUAS toca el cielo.$"

OneIsland_KindleRoad_Text_FinnDefeat_ES::
    .string "¡Ufff, eres fuerte!$"

OneIsland_KindleRoad_Text_FinnPostBattle_ES::
    .string "El cielo se puede observar muy\n"
    .string "bien en esta zona.$"

OneIsland_KindleRoad_Text_GarrettIntro_ES::
    .string "¿Y he dejado de nadar para\n"
    .string "enfrentarme contigo?$"

OneIsland_KindleRoad_Text_GarrettDefeat_ES::
    .string "¡Oye, oye, realmente eres\n"
    .string "impresionante!$"

OneIsland_KindleRoad_Text_GarrettPostBattle_ES::
    .string "Te recomiendo que nades de vez en\n"
    .string "cuando y que no uses tanto SURF.$"

OneIsland_KindleRoad_Text_TommyIntro_ES::
    .string "¡Eh, un momento!\n"
    .string "¡Acaba de picar uno enorme!$"

OneIsland_KindleRoad_Text_TommyDefeat_ES::
    .string "¡Lo he vuelto a perder!$"

OneIsland_KindleRoad_Text_TommyPostBattle_ES::
    .string "¡No sólo he perdido, también me he\n"
    .string "quedado sin el ejemplar de antes!$"

OneIsland_KindleRoad_Text_SharonIntro_ES::
    .string "¿Me echas una mano con mi\n"
    .string "entrenamiento?$"

OneIsland_KindleRoad_Text_SharonDefeat_ES::
    .string "Me has ganado por muy poco.$"

OneIsland_KindleRoad_Text_SharonPostBattle_ES::
    .string "Está claro que sabes lo que haces.\n"
    .string "¡Te admiro!$"

OneIsland_KindleRoad_Text_TanyaIntro_ES::
    .string "No hay un solo día en el que no\n"
    .string "me entrene.$"

OneIsland_KindleRoad_Text_TanyaDefeat_ES::
    .string "¡Qué forma tan tonta de perder!$"

OneIsland_KindleRoad_Text_TanyaPostBattle_ES::
    .string "¡A partir de ahora me entrenaré\n"
    .string "más!$"

OneIsland_KindleRoad_Text_SheaIntro_ES::
    .string "Cada mañana, antes de desayunar,\n"
    .string "rodeo a nado la isla.$"

OneIsland_KindleRoad_Text_SheaDefeat_ES::
    .string "Agggg...\n"
    .string "Agggg...$"

OneIsland_KindleRoad_Text_SheaPostBattle_ES::
    .string "He perdido porque esta mañana\n"
    .string "corrí mucho y estoy cansado.$"

OneIsland_KindleRoad_Text_HughIntro_ES::
    .string "Para luchar hay que ir vestido\n"
    .string "en condiciones, ¡y no como tú!$"

OneIsland_KindleRoad_Text_HughDefeat_ES::
    .string "¡¿Por qué?!$"

OneIsland_KindleRoad_Text_HughPostBattle_ES::
    .string "Hasta los profesionales de las\n"
    .string "artes marciales nos preocupamos\l"
    .string "de la moda últimamente.$"

OneIsland_KindleRoad_Text_BryceIntro_ES::
    .string "Cuando se está al aire libre,\n"
    .string "todo sabe mucho mejor.$"

OneIsland_KindleRoad_Text_BryceDefeat_ES::
    .string "¡Hala!$"

OneIsland_KindleRoad_Text_BrycePostBattle_ES::
    .string "¿Sabías que el agua de las zonas\n"
    .string "volcánicas es muy buena?$"

OneIsland_KindleRoad_Text_ClaireIntro_ES::
    .string "La comida ha sido demasiado\n"
    .string "abundante. ¿Luchamos?$"

OneIsland_KindleRoad_Text_ClaireDefeat_ES::
    .string "¡Sí que he quemado calorías!$"

OneIsland_KindleRoad_Text_ClairePostBattle_ES::
    .string "¿Qué hago?\n"
    .string "¡Otra vez tengo hambre!$"

OneIsland_KindleRoad_Text_KiaIntro_ES::
    .string "PÍA: ¡Mi hermano mayor y yo\n"
    .string "hacemos un equipo increíble!$"

OneIsland_KindleRoad_Text_KiaDefeat_ES::
    .string "PÍA: ¡No me lo puedo creer!$"

OneIsland_KindleRoad_Text_KiaPostBattle_ES::
    .string "PÍA: ¿Cómo puede haber alguien\n"
    .string "mejor que mi hermano?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons_ES::
    .string "PÍA: Para luchar con nosotros,\n"
    .string "necesitas al menos dos POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro_ES::
    .string "FER: ¡Junto a PÍA no tengo miedo\n"
    .string "de nada!$"

OneIsland_KindleRoad_Text_MikDefeat_ES::
    .string "FER: ¡Buaaaah, eres demasiado!$"

OneIsland_KindleRoad_Text_MikPostBattle_ES::
    .string "FER: ¿Cómo ha podido fallar\n"
    .string "nuestro equipo?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons_ES::
    .string "FER: ¿Quieres luchar con nosotros?\p"
    .string "Pues vuelve con dos POKéMON\n"
    .string "por lo menos.$"

OneIsland_KindleRoad_Text_RouteSign_ES::
    .string "Éste es el CAMINO CANDENTE.\p"
    .string "Conduce al MT. ASCUAS.$"

OneIsland_KindleRoad_Text_EmberSpaSign_ES::
    .string "BALNEARIO ASCUAS\n"
    .string "Enciende la llama que hay en ti.$"
