OneIsland_KindleRoad_Text_MariaIntro_FR::
	.string "Le temps est parfait. Rien de\n"
	.string "mieux pour un combat.$"

OneIsland_KindleRoad_Text_MariaDefeat_FR::
	.string "Aiyeeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle_FR::
	.string "Non, pas le visage!! Je ne veux\n"
	.string "pas abîmer mon maquillage.$"

OneIsland_KindleRoad_Text_AbigailIntro_FR::
	.string "Je vais finir par attraper un coup\n"
	.string "de soleil…$"

OneIsland_KindleRoad_Text_AbigailDefeat_FR::
	.string "Oh, tu sais te battre toi!$"

OneIsland_KindleRoad_Text_AbigailPostBattle_FR::
	.string "J'aime beaucoup ta casquette.\n"
	.string "Je m'en achèterais bien une…$"

OneIsland_KindleRoad_Text_FinnIntro_FR::
	.string "D'ici, on peut voir les tours du\n"
	.string "MONT BRAISE aller jusqu'au ciel.$"

OneIsland_KindleRoad_Text_FinnDefeat_FR::
	.string "J'en tombe à la renverse!$"

OneIsland_KindleRoad_Text_FinnPostBattle_FR::
	.string "Le ciel est vraiment immense.$"

OneIsland_KindleRoad_Text_GarrettIntro_FR::
	.string "Il fallait que je tombe sur toi\n"
	.string "juste pendant ma pause.$"

OneIsland_KindleRoad_Text_GarrettDefeat_FR::
	.string "Hein? Que…\n"
	.string "Quelle claque!$"

OneIsland_KindleRoad_Text_GarrettPostBattle_FR::
	.string "Au lieu d'utiliser SURF tout le\n"
	.string "temps, tu ferais bien de nager.$"

OneIsland_KindleRoad_Text_TommyIntro_FR::
	.string "Attends! Bouge pas!\n"
	.string "J'en tiens un gros!$"

OneIsland_KindleRoad_Text_TommyDefeat_FR::
	.string "Je l'ai encore laissé filer!$"

OneIsland_KindleRoad_Text_TommyPostBattle_FR::
	.string "Non seulement je perds, mais en\n"
	.string "plus je laisse filer ma prise!$"

OneIsland_KindleRoad_Text_SharonIntro_FR::
	.string "Tu pourrais pas m'aider un peu\n"
	.string "avec mon entraînement?$"

OneIsland_KindleRoad_Text_SharonDefeat_FR::
	.string "J'y étais presque.$"

OneIsland_KindleRoad_Text_SharonPostBattle_FR::
	.string "Hum, tu mérites tout mon respect.$"

OneIsland_KindleRoad_Text_TanyaIntro_FR::
	.string "Il ne se passe pas une journée\n"
	.string "sans qu'on s'entraîne.$"

OneIsland_KindleRoad_Text_TanyaDefeat_FR::
	.string "Quelle idiote je fais!$"

OneIsland_KindleRoad_Text_TanyaPostBattle_FR::
	.string "A partir de maintenant, je vais\n"
	.string "m'entraîner encore plus!$"

OneIsland_KindleRoad_Text_SheaIntro_FR::
	.string "Tous les jours avant le pt'it déj,\n"
	.string "je fais le tour de l'île à la nage.$"

OneIsland_KindleRoad_Text_SheaDefeat_FR::
	.string "Gasp…\n"
	.string "Gasp…$"

OneIsland_KindleRoad_Text_SheaPostBattle_FR::
	.string "J'ai perdu parce que j'ai\n"
	.string "trop couru avant.$"

OneIsland_KindleRoad_Text_HughIntro_FR::
	.string "C'est pas une tenue pour le\n"
	.string "combat, ça!! Tu me fais honte!$"

OneIsland_KindleRoad_Text_HughDefeat_FR::
	.string "Pourquoi??$"

OneIsland_KindleRoad_Text_HughPostBattle_FR::
	.string "Même les vrais guerriers font\n"
	.string "attention à leur tenue aujourd'hui.$"

OneIsland_KindleRoad_Text_BryceIntro_FR::
	.string "Tu sais, rien de mieux que de\n"
	.string "se retrouver en pleine nature.$"

OneIsland_KindleRoad_Text_BryceDefeat_FR::
	.string "Aïe! Ça fait mal!$"

OneIsland_KindleRoad_Text_BrycePostBattle_FR::
	.string "L'eau des régions volcaniques\n"
	.string "est très bonne pour la santé.$"

OneIsland_KindleRoad_Text_ClaireIntro_FR::
	.string "Après un petit repas, rien de tel\n"
	.string "qu'un combat pour digérer.$"

OneIsland_KindleRoad_Text_ClaireDefeat_FR::
	.string "Ça donne soif tout ça.$"

OneIsland_KindleRoad_Text_ClairePostBattle_FR::
	.string "Qu'est-ce que je dois faire?\n"
	.string "Je suis morte de faim.$"

OneIsland_KindleRoad_Text_KiaIntro_FR::
	.string "KIA: Mon grand frère et moi, on\n"
	.string "fait une super équipe.$"

OneIsland_KindleRoad_Text_KiaDefeat_FR::
	.string "KIA: Hein?!\n"
	.string "J'arrive pas à le croire!$"

OneIsland_KindleRoad_Text_KiaPostBattle_FR::
	.string "KIA: Je ne pensais pas que mon\n"
	.string "frère pouvait se faire battre.$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons_FR::
	.string "KIA: Si tu veux te battre contre\n"
	.string "nous, alors il te faut au moins\l"
	.string "deux POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro_FR::
	.string "MIK: Avec ma sœur à mes côtés,\n"
	.string "je n'ai peur de rien!$"

OneIsland_KindleRoad_Text_MikDefeat_FR::
	.string "MIK: Wouah!\n"
	.string "Trop fort!$"

OneIsland_KindleRoad_Text_MikPostBattle_FR::
	.string "MIK: Comment as-tu fait pour\n"
	.string "battre notre super duo?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons_FR::
	.string "MIK: Hé, tu veux vraiment te\n"
	.string "battre contre nous?\p"
	.string "Alors tu vas devoir revenir\n"
	.string "avec au moins deux POKéMON.$"

OneIsland_KindleRoad_Text_RouteSign_FR::
	.string "C'est la ROUTE TISON.\p"
	.string "Le MONT BRAISE se trouve\n"
	.string "au bout.$"

OneIsland_KindleRoad_Text_EmberSpaSign_FR::
	.string "Enflammez votre cœur!\n"
	.string "SOURCE BRAISE$"

