OneIsland_KindleRoad_Text_MariaIntro_DE::
	.string "Das Wetter ist wunderbar!\n"
	.string "Perfekt für einen Kampf!$"

OneIsland_KindleRoad_Text_MariaDefeat_DE::
	.string "Uhhhhhhhhh!$"

OneIsland_KindleRoad_Text_MariaPostBattle_DE::
	.string "Bitte bespritze nicht mein Gesicht!\n"
	.string "Du ruinierst mein Makeup!$"

OneIsland_KindleRoad_Text_AbigailIntro_DE::
	.string "Ich bekomme langsam einen\n"
	.string "Sonnenbrand…$"

OneIsland_KindleRoad_Text_AbigailDefeat_DE::
	.string "Oh, du bist schrecklich!$"

OneIsland_KindleRoad_Text_AbigailPostBattle_DE::
	.string "Ich mag deinen Hut. Vielleicht\n"
	.string "sollte ich auch einen tragen…$"

OneIsland_KindleRoad_Text_FinnIntro_DE::
	.string "Von hier kann man den GLUTBERG\n"
	.string "in den Himmel ragen sehen.$"

OneIsland_KindleRoad_Text_FinnDefeat_DE::
	.string "Hm, du bist stark, oder?$"

OneIsland_KindleRoad_Text_FinnPostBattle_DE::
	.string "Der Himmel ist hier immens!$"

OneIsland_KindleRoad_Text_GarrettIntro_DE::
	.string "Habe ich beim Schwimmen nur eine\n"
	.string "Pause gemacht, um von dir\l"
	.string "herausgefordert zu werden?$"

OneIsland_KindleRoad_Text_GarrettDefeat_DE::
	.string "Heh, was…\n"
	.string "Du bist wirklich gut!$"

OneIsland_KindleRoad_Text_GarrettPostBattle_DE::
	.string "Anstatt SURFER ständig ein-\n"
	.string "zusetzen, solltest du ein wenig\l"
	.string "schwimmen.$"

OneIsland_KindleRoad_Text_TommyIntro_DE::
	.string "Warte! Warte einen Moment!\n"
	.string "Ich habe einen Großen am Haken!$"

OneIsland_KindleRoad_Text_TommyDefeat_DE::
	.string "Ich habe erneut verloren…$"

OneIsland_KindleRoad_Text_TommyPostBattle_DE::
	.string "Ich habe nicht nur den Kampf,\n"
	.string "sondern auch den Fisch\l"
	.string "verloren!$"

OneIsland_KindleRoad_Text_SharonIntro_DE::
	.string "Könntest du mir beim\n"
	.string "Training aushelfen?$"

OneIsland_KindleRoad_Text_SharonDefeat_DE::
	.string "Du bist mir eine Nummer zu groß!$"

OneIsland_KindleRoad_Text_SharonPostBattle_DE::
	.string "Es ist offensichtlich, dass du\n"
	.string "Talent hast! Ich mag dich!$"

OneIsland_KindleRoad_Text_TanyaIntro_DE::
	.string "Es gibt keinen Tag, an dem\n"
	.string "wir nicht trainieren!$"

OneIsland_KindleRoad_Text_TanyaDefeat_DE::
	.string "Ich bin so doof!$"

OneIsland_KindleRoad_Text_TanyaPostBattle_DE::
	.string "Von jetzt an werde ich noch\n"
	.string "härter trainieren.$"

OneIsland_KindleRoad_Text_SheaIntro_DE::
	.string "Jeden Morgen vorm Frühstück\n"
	.string "schwimme ich um diese Insel.$"

OneIsland_KindleRoad_Text_SheaDefeat_DE::
	.string "Schnauf…\n"
	.string "Schnauf…$"

OneIsland_KindleRoad_Text_SheaPostBattle_DE::
	.string "Ich habe verloren, weil ich\n"
	.string "wegen der Rennerei außer\l"
	.string "Puste war…$"

OneIsland_KindleRoad_Text_HughIntro_DE::
	.string "Kleide dich für einen Kampf!\n"
	.string "Wechsle dieses unwürdige Outfit!$"

OneIsland_KindleRoad_Text_HughDefeat_DE::
	.string "Warum gerade ich?!?$"

OneIsland_KindleRoad_Text_HughPostBattle_DE::
	.string "Sogar Kampfsportler sind heut-\n"
	.string "zutage modebewusst…$"

OneIsland_KindleRoad_Text_BryceIntro_DE::
	.string "Alles schmeckt großartig, wenn\n"
	.string "du in der Natur bist!$"

OneIsland_KindleRoad_Text_BryceDefeat_DE::
	.string "Ugh! Vergeigt!$"

OneIsland_KindleRoad_Text_BrycePostBattle_DE::
	.string "Das Wasser in Gebieten mit\n"
	.string "Vulkanen ist köstlich!$"

OneIsland_KindleRoad_Text_ClaireIntro_DE::
	.string "Mein Mittagessen hat uns gesättigt!\n"
	.string "Kämpfst du gegen uns, damit wir\l"
	.string "ein wenig Bewegung bekommen?$"

OneIsland_KindleRoad_Text_ClaireDefeat_DE::
	.string "Das brachte mich ins Schwitzen!$"

OneIsland_KindleRoad_Text_ClairePostBattle_DE::
	.string "Was soll ich tun?\n"
	.string "Ich sterbe vor Hunger!$"

OneIsland_KindleRoad_Text_KiaIntro_DE::
	.string "HEIDI: Mein großer Bruder und ich\n"
	.string "sind ein grandioses Gespann!$"

OneIsland_KindleRoad_Text_KiaDefeat_DE::
	.string "HEIDI: Häh!?!\n"
	.string "Ich kann es nicht glauben!$"

OneIsland_KindleRoad_Text_KiaPostBattle_DE::
	.string "HEIDI: Wie kann jemand besser\n"
	.string "als mein Bruder sein?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons_DE::
	.string "HEIDI: Wenn du gegen uns kämpfen\n"
	.string "möchtest, musst du mindestens\l"
	.string "zwei POKéMON mitbringen!$"

OneIsland_KindleRoad_Text_MikIntro_DE::
	.string "DIRK: An der Seite von HEIDI\n"
	.string "habe ich vor nichts Angst!$"

OneIsland_KindleRoad_Text_MikDefeat_DE::
	.string "DIRK: Wow!\n"
	.string "Das ist zu viel!$"

OneIsland_KindleRoad_Text_MikPostBattle_DE::
	.string "DIRK: Wie kann ich an der\n"
	.string "Seite von HEIDI verlieren?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons_DE::
	.string "DIRK: Möchtest du gegen uns beide\n"
	.string "kämpfen?$"

OneIsland_KindleRoad_Text_RouteSign_DE::
	.string "Das ist der GLÜHWEG.\p"
	.string "Zum GLUTBERG geradeaus.$"

OneIsland_KindleRoad_Text_EmberSpaSign_DE::
	.string "Entfache das Feuer in dir!\n"
	.string "GLUTTHERME$"

