PokemonTower_4F_Text_PaulaIntro_ES::
    .string "¡Un GHOST!\n¡No! ¡Guaaah!$"

PokemonTower_4F_Text_PaulaDefeat_ES::
    .string "¿Dónde está GHOST?$"

PokemonTower_4F_Text_PaulaPostBattle_ES::
    .string "Debo de haberlo soñado...$"

PokemonTower_4F_Text_LaurelIntro_ES::
    .string "¡Te vas a enterar!\n"
    .string "¡Guaaah!$"

PokemonTower_4F_Text_LaurelDefeat_ES::
    .string "¿Qué?$"

PokemonTower_4F_Text_LaurelPostBattle_ES::
    .string "¡No podemos desvelar la identidad\n"
    .string "de los GHOST!$"

PokemonTower_4F_Text_JodyIntro_ES::
    .string "Uuuuuu...\n"
    .string "¡Vencerme no, tú a mí!$"

PokemonTower_4F_Text_JodyDefeat_ES::
    .string "¿Eh?\n"
    .string "¿Quién? ¿Qué?$"

PokemonTower_4F_Text_JodyPostBattle_ES::
    .string "¡Que descansen los POKéMON\n"
    .string "debilitados!$"
