PokemonTower_4F_Text_PaulaIntro_FR::
	.string "Un SPECTRE!\n"
	.string "Rhaaaaaa!$"

PokemonTower_4F_Text_PaulaDefeat_FR::
	.string "Ben!\n"
	.string "Où est le SPECTRE?$"

PokemonTower_4F_Text_PaulaPostBattle_FR::
	.string "J'ai dû rêver…$"

PokemonTower_4F_Text_LaurelIntro_FR::
	.string "Sois maudit!!!!\n"
	.string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat_FR::
	.string "QUOI!$"

PokemonTower_4F_Text_LaurelPostBattle_FR::
	.string "Nous ne pouvons pas identifier\n"
	.string "les SPECTRES.$"

PokemonTower_4F_Text_JodyIntro_FR::
	.string "Huhuhu…\n"
	.string "Ne me frappe pas!$"

PokemonTower_4F_Text_JodyDefeat_FR::
	.string "Hein?\n"
	.string "Qui? Quoi?$"

PokemonTower_4F_Text_JodyPostBattle_FR::
	.string "Que les âmes des POKéMON\n"
	.string "disparus reposent en paix!$"

