PokemonTower_4F_Text_PaulaIntro_IT::
    .string "Uno spettro!\n"
    .string "Nooo! Guaaah!$"

PokemonTower_4F_Text_PaulaDefeat_IT::
    .string "Dov'è lo spettro?$"

PokemonTower_4F_Text_PaulaPostBattle_IT::
    .string "Devo aver fatto un brutto sogno…$"

PokemonTower_4F_Text_LaurelIntro_IT::
    .string "Ti maledico!\n"
    .string "Guaaah!$"

PokemonTower_4F_Text_LaurelDefeat_IT::
    .string "Cosa?!$"

PokemonTower_4F_Text_LaurelPostBattle_IT::
    .string "Non sappiamo dire l'identità degli\n"
    .string "spettri!$"

PokemonTower_4F_Text_JodyIntro_IT::
    .string "Uu Uu Uu…\n"
    .string "Ti ho beccato!$"

PokemonTower_4F_Text_JodyDefeat_IT::
    .string "Eh?\n"
    .string "Chi? Cosa?$"

PokemonTower_4F_Text_JodyPostBattle_IT::
    .string "Che le anime dei POKéMON riposino\n"
    .string "in pace!$"

