PokemonTower_4F_Text_PaulaIntro_DE::
	.string "Ein GEIST! Nein!\n"
	.string "Ahhhhh!$"

PokemonTower_4F_Text_PaulaDefeat_DE::
	.string "Wohin ist der GEIST gegangen?$"

PokemonTower_4F_Text_PaulaPostBattle_DE::
	.string "Ich bin sicher, ich träume das\n"
	.string "alles nur...$"

PokemonTower_4F_Text_LaurelIntro_DE::
	.string "Ich verfluche dich!\n"
	.string "Buuuh!$"

PokemonTower_4F_Text_LaurelDefeat_DE::
	.string "Was ist passiert?$"

PokemonTower_4F_Text_LaurelPostBattle_DE::
	.string "Wir können die Identität der\n"
	.string "GEISTER nicht ermitteln!$"

PokemonTower_4F_Text_JodyIntro_DE::
	.string "Buuh... buhuhu...\n"
	.string "Lass mich in Ruhe!$"

PokemonTower_4F_Text_JodyDefeat_DE::
	.string "Wer?\n"
	.string "Was? Wo?$"

PokemonTower_4F_Text_JodyPostBattle_DE::
	.string "Mögen die verlorenen Seelen der\n"
	.string "POKéMON in Frieden ruhen...$"

