CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel_DE::
	.string "SUPERSCHUTZ hält POKéMON auf\n"
	.string "Distanz...\p"
	.string "Es ist besser als normaler SCHUTZ!$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings_DE::
	.string "Vor längeren Ausflügen solltest du\n"
	.string "BELEBER kaufen.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign_DE::
	.string "Nützliche Items für TRAINER!\p"
	.string "1S: ZUBEHÖR FÜR TRAINER$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes_DE::
	.string "Es gibt einen Kunden namens\n"
	.string "SIEGFRIED, der gelegentlich\l"
	.string "vorbeikommt.\l"
	.string "Er kauft stets Umhänge.\p"
	.string "Ich frage mich, ob er\n"
	.string "viele gleiche Umhänge zu\l"
	.string "Hause hat.$"

