CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel_FR::
	.string "Le SUPEREPOUSSE tient les\n"
	.string "POKéMON faibles à l'écart…\p"
	.string "C'est un REPOUSSE plus puissant!$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings_FR::
	.string "Equipe-toi de RAPPELS avant de\n"
	.string "partir à l'aventure.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign_FR::
	.string "Les objets de premier choix!\p"
	.string "1er: MARCHE DES DRESSEURS$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes_FR::
	.string "PETER vient souvent ici pour\n"
	.string "acheter des capes.\p"
	.string "Je me demande combien de capes\n"
	.string "identiques il peut avoir chez lui.$"

