SilphCo_5F_Text_RocketsInUproarAboutIntruder_DE::
	.string "Ein Eindringling mischt das TEAM\n"
	.string "ROCKET auf...  das bist du, oder?$"

SilphCo_5F_Text_YoureOurHeroThankYou_DE::
	.string "Das TEAM ROCKET ist geflüchtet!\n"
	.string "Du bist ein Held!$"

SilphCo_5F_Text_Grunt1Intro_DE::
	.string "Ich hörte, ein Kind läuft im\n"
	.string "Gebäude herum...$"

SilphCo_5F_Text_Grunt1Defeat_DE::
	.string "Schluss! Aus!$"

SilphCo_5F_Text_Grunt1PostBattle_DE::
	.string "Es war sehr dumm, sich mit dem\n"
	.string "TEAM ROCKET anzulegen!$"

SilphCo_5F_Text_BeauIntro_DE::
	.string "Wir entwickeln in diesen Labors\n"
	.string "neue POKéBÄLLE!$"

SilphCo_5F_Text_BeauDefeat_DE::
	.string "Finito!\n"
	.string "Aus und vorbei!$"

SilphCo_5F_Text_BeauPostBattle_DE::
	.string "Unsere neueste Entwicklung ist ein\n"
	.string "POKéBALL, der alles fängt!$"

SilphCo_5F_Text_DaltonIntro_DE::
	.string "Waaas?\p"
	.string "Wer hat denn das Kind reingelassen?$"

SilphCo_5F_Text_DaltonDefeat_DE::
	.string "Nein!\n"
	.string "Das Kind hat mich besiegt!$"

SilphCo_5F_Text_DaltonPostBattle_DE::
	.string "Es ist ein weiter Weg zum BOSS! Du\n"
	.string "bist hier erst im 4. Stock!$"

SilphCo_5F_Text_Grunt2Intro_DE::
	.string "Zolle dem TEAM ROCKET gefälligst\n"
	.string "mehr Respekt!!!$"

SilphCo_5F_Text_Grunt2Defeat_DE::
	.string "Hust...\n"
	.string "Hust...$"

SilphCo_5F_Text_Grunt2PostBattle_DE::
	.string "Da fällt mir ein, SMOGON entwickelt\n"
	.string "sich zu SMOGMOG!$"

SilphCo_5F_Text_PorygonFirstVRMon_DE::
	.string "Ein ARTIKEL über POKéMON!\p"
	.string "PORYGON! POKéMON-LABOR ERZEUGT\n"
	.string "VIRTUELLES POKéMON!$"

SilphCo_5F_Text_Over350TechniquesConfirmed_DE::
	.string "Eine Studie über POKéMON!\p"
	.string "Es gibt mehr als 350 POKéMON-\n"
	.string "Kampftechniken!$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded_DE::
	.string "Ein POKéMON-BERICHT!\p"
	.string "Einige POKéMON entwickeln sich\n"
	.string "erst beim Tausch.$"

SilphCo_5F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "4 OG$"

SilphCo_5F_Text_RocketBossLookingForStrongMons_DE::
	.string "Diese Rüpel haben die Kontrolle in\n"
	.string "diesem Gebäude übernommen…\p"
	.string "Der BOSS sagte, dass er nach\n"
	.string "starken POKéMON sucht.\p"
	.string "Ich hoffe, dass unser PRÄSIDENT\n"
	.string "Ärger vermeiden konnte…$"

