SilphCo_5F_Text_RocketsInUproarAboutIntruder_IT::
    .string "TEAM ROCKET è in subbuglio per\n"
    .string "la presenza di un intruso. Sei\l"
    .string "tu, vero?$"

SilphCo_5F_Text_YoureOurHeroThankYou_IT::
    .string "TEAM ROCKET è fuggito!\n"
    .string "Grazie! Sei eccezionale!$"

SilphCo_5F_Text_Grunt1Intro_IT::
    .string "Pare che ci sia un intruso!$"

SilphCo_5F_Text_Grunt1Defeat_IT::
    .string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle_IT::
    .string "Non è molto intelligente provocare\n"
    .string "TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro_IT::
    .string "A questo piano si studia la\n"
    .string "tecnologia delle POKé BALL!$"

SilphCo_5F_Text_BeauDefeat_IT::
    .string "Uffa!\n"
    .string "Che disdetta!$"

SilphCo_5F_Text_BeauPostBattle_IT::
    .string "Lavoriamo ad una nuova POKé BALL\n"
    .string "catturatutto!!!$"

SilphCo_5F_Text_DaltonIntro_IT::
    .string "Eh?!\n"
    .string "Da dove sbuchi?$"

SilphCo_5F_Text_DaltonDefeat_IT::
    .string "Oh no!\n"
    .string "Che disdetta!$"

SilphCo_5F_Text_DaltonPostBattle_IT::
    .string "Sei solo al 4ºP! Ne hai di strada\n"
    .string "da fare prima di arrivare al CAPO!$"

SilphCo_5F_Text_Grunt2Intro_IT::
    .string "Porta un po' di rispetto a TEAM\n"
    .string "ROCKET!!!$"

SilphCo_5F_Text_Grunt2Defeat_IT::
    .string "Hm hm…\n"
    .string "Hm hm…$"

SilphCo_5F_Text_Grunt2PostBattle_IT::
    .string "Ora mi ricordo…\p"
    .string "KOFFING diventa WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon_IT::
    .string "Una RELAZIONE sui POKéMON!\p"
    .string "PORYGON, il primo POKéMON\n"
    .string "virtuale, è stato creato nel\l"
    .string "LABORATORIO POKéMON!!!$"

SilphCo_5F_Text_Over350TechniquesConfirmed_IT::
    .string "Una RELAZIONE sui POKéMON!\p"
    .string "Confermate più di 350 tecniche di\n"
    .string "attacco POKéMON!$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded_IT::
    .string "Una RELAZIONE sui POKéMON!\p"
    .string "Alcuni POKéMON si evolvono\n"
    .string "con lo scambio.$"

SilphCo_5F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "4ºP$"

SilphCo_5F_Text_RocketBossLookingForStrongMons_IT::
    .string "Quei furfanti che hanno\n"
    .string "occupato l'edificio…\p"
    .string "Pare che il loro CAPO stia\n"
    .string "cercando dei POKéMON forti.\p"
    .string "Speriamo che il nostro PRESIDENTE\n"
    .string "non sia in pericolo.$"

