LavenderTown_Mart_Text_SearchingForStatRaiseItems_ES::
    .string "Estoy buscando algunos objetos que\n"
    .string "aumenten las habilidades de los\l"
    .string "POKéMON en un sólo combate.\p"
    .string "Estoy buscando ATAQUE X,\n"
    .string "DEFENSA X, VELOCIDAD X y\l"
    .string "ESPECIAL X.\p"
    .string "¿Sabes dónde encontrarlos?$"

LavenderTown_Mart_Text_DidYouBuyRevives_ES::
    .string "¿Conoces REVIVIR?\n"
    .string "Devuelve la energía a los POKéMON\l"
    .string "debilitados.$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou_ES::
    .string "A veces, coincidirás con parejas\n"
    .string "de ENTRENADORES que te retarán\l"
    .string "con dos POKéMON a la vez.\p"
    .string "Cuando esto ocurra, para luchar\n"
    .string "tú también necesitarás dos POKéMON.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000_ES::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
