SaffronCity_Dojo_Text_MasterKoichiIntro_DE::
	.string "Willkommen!\p"
	.string "Ich bin der KARATE-MEISTER!\n"
	.string "Ich leite diese POKéMON-ARENA!\p"
	.string "Du forderst mich heraus? Also gut!\n"
	.string "Ich kenne keine Gnade!\p"
	.string "Los!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat_DE::
	.string "Arrgh!\n"
	.string "Ich wurde geschlagen!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon_DE::
	.string "Ich bin deiner Gnade unwürdig!\p"
	.string "Trotzdem flehe ich dich an, unser\n"
	.string "Emblem nicht als Trophäe\l"
	.string "mitzunehmen!\p"
	.string "Zum Ersatz gebe ich dir ein\n"
	.string "preisgekröntes KAMPF-POKéMON!\p"
	.string "Wähle eines von beiden aus!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs_DE::
	.string "Hi!\p"
	.string "Bleibe doch hier und trainiere\n"
	.string "Karate mit uns!$"

SaffronCity_Dojo_Text_MikeIntro_DE::
	.string "Stopp!\n"
	.string "Ziehe deine Schuhe aus!$"

SaffronCity_Dojo_Text_MikeDefeat_DE::
	.string "Ich gebe auf!$"

SaffronCity_Dojo_Text_MikePostBattle_DE::
	.string "Warte nur, bis du unseren Meister\n"
	.string "triffst!\p"
	.string "Verglichen mit ihm bin ich ein\n"
	.string "kleiner Fisch!$"

SaffronCity_Dojo_Text_HidekiIntro_DE::
	.string "Du sollst sehr gut sein!\n"
	.string "Beweise es mir!$"

SaffronCity_Dojo_Text_HidekiDefeat_DE::
	.string "Schiedsrichter!\n"
	.string "1 Punkt!$"

SaffronCity_Dojo_Text_HidekiPostBattle_DE::
	.string "Unser Meister ist ein echter Profi!$"

SaffronCity_Dojo_Text_AaronIntro_DE::
	.string "Keine Herausforderung ist mir zu\n"
	.string "hart!\p"
	.string "Ich zertrümmere Steine mit bloßen\n"
	.string "Händen!$"

SaffronCity_Dojo_Text_AaronDefeat_DE::
	.string "Autsch!\n"
	.string "Ich habe eine Prellung!$"

SaffronCity_Dojo_Text_AaronPostBattle_DE::
	.string "Die einzige Sache, vor der wir uns\n"
	.string "fürchten, ist PSYCHOKINESE!$"

SaffronCity_Dojo_Text_HitoshiIntro_DE::
	.string "Haii-ia!\p"
	.string "Unbefugten ist der Zutritt zu\n"
	.string "unserem KAMPF-DOJO verboten!$"

SaffronCity_Dojo_Text_HitoshiDefeat_DE::
	.string "Uff!\n"
	.string "Ich gebe auf!$"

SaffronCity_Dojo_Text_HitoshiPostBattle_DE::
	.string "Die allerbesten Kämpfer des Landes\n"
	.string "trainieren hier!$"

SaffronCity_Dojo_Text_YouWantHitmonlee_DE::
	.string "Möchtest du KICKLEE, das\n"
	.string "trittstarke POKéMON?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster_DE::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}.$"

SaffronCity_Dojo_Text_YouWantHitmonchan_DE::
	.string "Möchtest du NOCKCHAN, den Meister\n"
	.string "des Boxkampfs?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2_DE::
	.string "{PLAYER}は　カラテ　だいおう　から\n"
	.string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy_DE::
	.string "Er sagte EIN POKéMON...$"

SaffronCity_Dojo_Text_EnemiesOnEverySide_DE::
	.string "Überall Gegner!$"

SaffronCity_Dojo_Text_GoesAroundComesAround_DE::
	.string "Wie die Saat, so die Ernte!$"

SaffronCity_Dojo_Text_FightingDojo_DE::
	.string "KAMPFARENA$"

