SaffronCity_Dojo_Text_MasterKoichiIntro_FR::
	.string "Jeune DRESSEUR!\p"
	.string "Je suis le GRAND MAITRE de\n"
	.string "KARATE! Je suis le CHAMPION!\p"
	.string "Tu me provoques?\n"
	.string "Tu veux m'affronter?\p"
	.string "Je n'aurai aucune pitié!\n"
	.string "HAHAHA! Ayaaaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat_FR::
	.string "STOP!\n"
	.string "Tu m'as battu! J'ai honte!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon_FR::
	.string "OK, tu as gagné!\p"
	.string "Mais ne va pas le crier sur tous\n"
	.string "les toits! Tu sais te battre, on a\l"
	.string "compris!\p"
	.string "Tiens, prends ça!\n"
	.string "Tu as gagné un POKéMON COMBAT!\p"
	.string "Choisis celui que tu veux!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs_FR::
	.string "Reste avec nous pour faire du\n"
	.string "KARATE!$"

SaffronCity_Dojo_Text_MikeIntro_FR::
	.string "Roooh!\n"
	.string "Enlève tes chaussures!$"

SaffronCity_Dojo_Text_MikeDefeat_FR::
	.string "J'abandonne!$"

SaffronCity_Dojo_Text_MikePostBattle_FR::
	.string "Tu te tais, tu t'assois et tu\n"
	.string "attends le grand maître!\p"
	.string "Tu vas comprendre ta douleur!\n"
	.string "Il est invincible.$"

SaffronCity_Dojo_Text_HidekiIntro_FR::
	.string "T'as des prétentions?\n"
	.string "Montre-moi!$"

SaffronCity_Dojo_Text_HidekiDefeat_FR::
	.string "Un point pour toi!$"

SaffronCity_Dojo_Text_HidekiPostBattle_FR::
	.string "Notre maître est un pro.\n"
	.string "Prépare-toi à perdre!$"

SaffronCity_Dojo_Text_AaronIntro_FR::
	.string "J'ai peur de rien!\p"
	.string "Le matin, j'casse des pierres\n"
	.string "pour m'entraîner!$"

SaffronCity_Dojo_Text_AaronDefeat_FR::
	.string "Woaa! Les pierres, ça rend pas\n"
	.string "les coups!$"

SaffronCity_Dojo_Text_AaronPostBattle_FR::
	.string "La seule chose qui nous fait peur\n"
	.string "c'est les pouvoirs psy!$"

SaffronCity_Dojo_Text_HitoshiIntro_FR::
	.string "Ayah!\p"
	.string "Tu joues avec ta vie!\n"
	.string "Ce DOJO, c'est pour les balèzes!$"

SaffronCity_Dojo_Text_HitoshiDefeat_FR::
	.string "Ouille!\n"
	.string "J'suis KO!$"

SaffronCity_Dojo_Text_HitoshiPostBattle_FR::
	.string "Les meilleurs combattants\n"
	.string "du pays sont ici!$"

SaffronCity_Dojo_Text_YouWantHitmonlee_FR::
	.string "Tu veux KICKLEE, l'expert\n"
	.string "en coups de pied?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster_FR::
	.string "{PLAYER} reçoit un\n"
	.string "{STR_VAR_1}!$"

SaffronCity_Dojo_Text_YouWantHitmonchan_FR::
	.string "Tu veux TYGNON, le puncheur?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2_FR::
	.string "{PLAYER}は　カラテ　だいおう　から\n"
	.string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy_FR::
	.string "Tss tss tss!\n"
	.string "Faut pas être trop gourmand…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide_FR::
	.string "Ne compte que sur toi!$"

SaffronCity_Dojo_Text_GoesAroundComesAround_FR::
	.string "Respecte ton ennemi!$"

SaffronCity_Dojo_Text_FightingDojo_FR::
	.string "DOJO$"

