SaffronCity_Dojo_Text_MasterKoichiIntro_IT::
    .string "Grrr!\p"
    .string "Sono il MAESTRO di KARATE! Sono il\n"
    .string "CAPO qui!\p"
    .string "Vuoi sfidarci?\n"
    .string "Non avremo pietà!\p"
    .string "Fuaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat_IT::
    .string "Hua!\n"
    .string "Mi hai battuto!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon_IT::
    .string "Ebbene sì, ho perso!\p"
    .string "Ma ti supplico di non prendere il\n"
    .string "nostro emblema come trofeo!\p"
    .string "In cambio ti darò un potente\n"
    .string "POKéMON di tipo LOTTA!\p"
    .string "Scegli quello che preferisci!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs_IT::
    .string "Ehi!\n"
    .string "Allenati a karate con noi!$"

SaffronCity_Dojo_Text_MikeIntro_IT::
    .string "Urgg!\n"
    .string "Togliti le scarpe!$"

SaffronCity_Dojo_Text_MikeDefeat_IT::
    .string "Mi arrendo!$"

SaffronCity_Dojo_Text_MikePostBattle_IT::
    .string "Aspetta di vedere il Maestro!\n"
    .string "Non sono niente rispetto a lui!$"

SaffronCity_Dojo_Text_HidekiIntro_IT::
    .string "Mi dicono che sei in gamba.\n"
    .string "Allora dimostralo!$"

SaffronCity_Dojo_Text_HidekiDefeat_IT::
    .string "Ti darei 1 punto!$"

SaffronCity_Dojo_Text_HidekiPostBattle_IT::
    .string "Il nostro Maestro è un lottatore\n"
    .string "professionista!$"

SaffronCity_Dojo_Text_AaronIntro_IT::
    .string "Non mi spaventa proprio niente!\p"
    .string "Mi alleno spaccando rocce!$"

SaffronCity_Dojo_Text_AaronDefeat_IT::
    .string "Ahi!\n"
    .string "Che male!$"

SaffronCity_Dojo_Text_AaronPostBattle_IT::
    .string "L'unica cosa che temiamo è il\n"
    .string "potere psichico!$"

SaffronCity_Dojo_Text_HitoshiIntro_IT::
    .string "Ehi!\p"
    .string "Stai varcando il nostro DOJO\n"
    .string "KARATE!$"

SaffronCity_Dojo_Text_HitoshiDefeat_IT::
    .string "Uff!\n"
    .string "Mi arrendo!$"

SaffronCity_Dojo_Text_HitoshiPostBattle_IT::
    .string "Qui si allenano i lottatori più\n"
    .string "bravi del mondo.$"

SaffronCity_Dojo_Text_YouWantHitmonlee_IT::
    .string "Vuoi HITMONLEE, il tiracalci?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster_IT::
    .string "{PLAYER} riceve\n"
    .string "{STR_VAR_1}!$"

SaffronCity_Dojo_Text_YouWantHitmonchan_IT::
    .string "Vuoi HITMONCHAN, pugno veloce?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2_IT::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy_IT::
    .string "Meglio non essere avidi!$"

SaffronCity_Dojo_Text_EnemiesOnEverySide_IT::
    .string "I nemici! Siamo circondati!$"

SaffronCity_Dojo_Text_GoesAroundComesAround_IT::
    .string "Chi semina, raccoglie!$"

SaffronCity_Dojo_Text_FightingDojo_IT::
    .string "DOJO KARATE$"

