SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections_FR::
	.string "Sur cette île, des évènements\n"
	.string "se produisent selon les connexions.\p"
	.string "Tu me demandes lesquelles?\p"
	.string "Il y en a quatre que tu devras\n"
	.string "découvrir par toi-même.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere_FR::
	.string "Tu as déjà embarqué sur un\n"
	.string "FERRY FLECHE DES MERS?\p"
	.string "Il y en a au moins dix.\p"
	.string "Mais je ne connais malheureusement\n"
	.string "pas toutes leurs destinations.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower_FR::
	.string "Si tu crois en toi, tu devrais aller\n"
	.string "à la TOUR DRESSEURS.$"

