SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections_ES::
    .string "En la isla, ocurren distintas cosas\n"
    .string "según las conexiones.\p"
    .string "¿Que qué son las conexiones?\p"
    .string "Eso tendrás que descubrirlo sin\n"
    .string "ayuda de nadie.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere_ES::
    .string "¿Has venido a bordo del SURCAMAR?\p"
    .string "Creo que en total hay diez barcos\n"
    .string "rápidos de esos.\p"
    .string "Pero no sé las rutas que cubren.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower_ES::
    .string "Si te sientes con fuerzas, deberías\n"
    .string "visitar la TORRE DESAFÍO.$"
