SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections_IT::
    .string "Su quest'isola accadono cose\n"
    .string "differenti, secondo i collegamenti.\p"
    .string "Di cosa sto parlando? Questo lo\n"
    .string "dovrai scoprire da te!$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere_IT::
    .string "Hai viaggiato in POKéSCAFO?\p"
    .string "Ne esistono almeno dieci di quei\n"
    .string "traghetti ad alta velocità.\p"
    .string "Non so esattamente che rotte\n"
    .string "facciano.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower_IT::
    .string "Se pensi di essere abbastanza\n"
    .string "forte, fai un salto alla TORRE\l"
    .string "ALLENATORI.$"

