SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections_DE::
	.string "Auf dieser Insel geschehen unter-\n"
	.string "schiedliche Ereignisse, abhängig\l"
	.string "von den Verbindungen!\l"
	.string "Was diese Verbindungen sind?\p"
	.string "Das musst du alleine herausfinden!$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere_DE::
	.string "Bist du auf einer SEESPRINT-Fähre\n"
	.string "hierhergekommen?\p"
	.string "Es gibt mindestens zehn von diesen\n"
	.string "Hochgeschwindigkeitsbooten.\p"
	.string "Ich weiß nicht, wo sie alle\n"
	.string "abgeblieben sind…$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower_DE::
	.string "Wenn du selbstbewusst bist,\n"
	.string "solltest du im TRAINERTURM\l"
	.string "vorbeischauen!$"

