SevenIsland_SevaultCanyon_Text_CyndyIntro_FR::
	.string "Je suis au top de ma forme.$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat_FR::
	.string "Hein? Quelque chose n'est pas\n"
	.string "normal…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle_FR::
	.string "Après cette défaite, je ferais\n"
	.string "mieux d'éviter la TOUR DRESSEURS…$"

SevenIsland_SevaultCanyon_Text_EvanIntro_FR::
	.string "Même si tu as les POKéMON les plus\n"
	.string "puissants, ça ne m'impressionne pas…\p"
	.string "Ça ne sert à rien si tu ne sais pas\n"
	.string "les utiliser correctement.$"

SevenIsland_SevaultCanyon_Text_EvanDefeat_FR::
	.string "Je suis impressionné.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle_FR::
	.string "Tous les jours, on croise des\n"
	.string "DRESSEURS qui ne savent pas\p"
	.string "utiliser leurs POKéMON.\p"
	.string "Avant de s'occuper de leurs\n"
	.string "POKéMON, les DRESSEURS\p"
	.string "devraient d'abord mûrir\n"
	.string "un peu.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro_FR::
	.string "Mon boulot, c'est de protéger\n"
	.string "l'environnement.\p"
	.string "En retour, la nature me protège.$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat_FR::
	.string "Ouah, tu plaisantes pas!\n"
	.string "Tu voudrais pas me protéger?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle_FR::
	.string "Vue des étoiles, la planète n'est\n"
	.string "pas plus grosse qu'une larme.\p"
	.string "Mais nous la protégeons pour que\n"
	.string "tout le monde en profite.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro_FR::
	.string "Elles en jettent, tes chaussures!$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat_FR::
	.string "Ton apparence est trompeuse.\p"
	.string "Tu es bien plus balèze qu'il\n"
	.string "n'y paraît.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle_FR::
	.string "C'est ta mère qui a acheté ces\n"
	.string "CHAUSSURES DE SPORT?\p"
	.string "Je suis sûre qu'elle doit t'adorer.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro_FR::
	.string "Ça te tente un petit combat?\n"
	.string "Allez, c'est parti!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat_FR::
	.string "Je le savais! On sent ta force\n"
	.string "juste en t'observant.$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle_FR::
	.string "La façon dont tu combats m'a\n"
	.string "donné plein d'idées.\p"
	.string "Merci beaucoup!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro_FR::
	.string "J'ai reçu la meilleure éducation\n"
	.string "possible pour devenir aussi forte.\p"
	.string "Je ne peux perdre contre personne.$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat_FR::
	.string "Merci. Je me sens libérée d'avoir\n"
	.string "perdu contre toi.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle_FR::
	.string "J'ai plutôt tendance à m'énerver\n"
	.string "facilement.\p"
	.string "Je vais respirer profondément pour\n"
	.string "me calmer.$"

SevenIsland_SevaultCanyon_Text_LexIntro_FR::
	.string "PAUL: Avec NYA, on ne connaît\n"
	.string "pas la défaite.$"

SevenIsland_SevaultCanyon_Text_LexDefeat_FR::
	.string "PAUL: J'aurais dû être plus\n"
	.string "prudent…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle_FR::
	.string "PAUL: Je crois que c'était une\n"
	.string "bonne expérience pour NYA.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons_FR::
	.string "PAUL: Puis-je te demander de nous\n"
	.string "affronter tous les deux?\p"
	.string "Mais il te faut au moins deux\n"
	.string "POKéMON pour ça.$"

SevenIsland_SevaultCanyon_Text_NyaIntro_FR::
	.string "NYA: Je vais faire de mon mieux\n"
	.string "pour être digne de PAUL.$"

SevenIsland_SevaultCanyon_Text_NyaDefeat_FR::
	.string "NYA: Oh non…\n"
	.string "Je suis désolée…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle_FR::
	.string "NYA: J'ai encore besoin de passer\n"
	.string "beaucoup de temps à m'entraîner.\p"
	.string "Dis-moi PAUL, tu ne m'en veux\n"
	.string "pas trop?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons_FR::
	.string "NYA: Je suis désolée, mais on ne\n"
	.string "se bat qu'en deux contre deux.$"

SevenIsland_SevaultCanyon_Text_RouteSign_FR::
	.string "CANYON SESOR\n"
	.string "RUINES TANOBY DROIT DEVANT$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly_FR::
	.string "S'entraîner seul a de bons côtés.\p"
	.string "Mais il faut aussi quelquefois\n"
	.string "affronter des adversaires.\p"
	.string "Même ALDO…\p"
	.string "Avant, il s'entraînait avec un\n"
	.string "gars qui s'appelle BASTIEN.$"

