SevenIsland_SevaultCanyon_Text_CyndyIntro_DE::
	.string "Ich bin in Top-Form!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat_DE::
	.string "Häh!\n"
	.string "Ist irgendetwas nicht in Ordnung…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle_DE::
	.string "Bei meiner jetzigen Form sollte ich\n"
	.string "mich vom TRAINERTURM fern halten…$"

SevenIsland_SevaultCanyon_Text_EvanIntro_DE::
	.string "Es macht nichts, dass du zufällig\n"
	.string "die stärksten POKéMON hast…\p"
	.string "Es bedeutet nichts, wenn du nicht\n"
	.string "mit ihnen umgehen kannst…$"

SevenIsland_SevaultCanyon_Text_EvanDefeat_DE::
	.string "Aber du bist ein Meister!$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle_DE::
	.string "Häufig sieht man TRAINER mit\n"
	.string "wunderbaren POKéMON, mit denen\l"
	.string "sie nicht richtig umgehen können.\p"
	.string "Ehe sie POKéMON trainieren, sollten\n"
	.string "sie selbst erst einmal\l"
	.string "erwachsen werden.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro_DE::
	.string "Ich arbeite, um die Umwelt zu\n"
	.string "schützen. Im Gegenzug\l"
	.string "beschützt die Umwelt mich!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat_DE::
	.string "Wow! Du bist stark!\n"
	.string "Möchtest du mich beschützen?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle_DE::
	.string "Von den Sternen aus betrachtet,\n"
	.string "sieht unser Planet aus wie ein\l"
	.string "Tropfen Wasser.\p"
	.string "Aber wir müssen diesen Wasser-\n"
	.string "tropfen für alle bewahren.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro_DE::
	.string "Deine Schuhe sind ziemlich cool!$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat_DE::
	.string "Du bist ganz schön stark, dafür\n"
	.string "dass du so niedlich aussiehst!$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle_DE::
	.string "Deine Mutter hat dir diese coolen\n"
	.string "TURBOTRETER gegeben?\p"
	.string "Sie muss dich lieben!$"

SevenIsland_SevaultCanyon_Text_LeroyIntro_DE::
	.string "Du siehst stark aus.\n"
	.string "Ich will gegen dich kämpfen, bitte!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat_DE::
	.string "Ich wusste es!\n"
	.string "Du bist genauso stark,\l"
	.string "wie ich dachte!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle_DE::
	.string "Deine Art zu kämpfen lieferte\n"
	.string "mir eine Menge nützlicher Daten.\p"
	.string "Vielen Dank!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro_DE::
	.string "Mir wurde die bestmögliche Er-\n"
	.string "ziehung zuteil, damit ich so\l"
	.string "stark werde.\l"
	.string "Ich möchte gegen niemanden\l"
	.string "verlieren!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat_DE::
	.string "Danke! Ich fühle mich durch\n"
	.string "die Niederlage gegen dich\l"
	.string "so befreit!$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle_DE::
	.string "Aus irgendeinem Grund regt mich\n"
	.string "jede Bagatelle auf.\p"
	.string "Ich versuche, mich durch tiefes\n"
	.string "Atmen abzuregen.$"

SevenIsland_SevaultCanyon_Text_LexIntro_DE::
	.string "OLE: GRIT, mein Schatz, zusammen\n"
	.string "werden wir gewinnen!$"

SevenIsland_SevaultCanyon_Text_LexDefeat_DE::
	.string "OLE: Ich war anscheinend zu\n"
	.string "sorglos…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle_DE::
	.string "OLE: Ich denke, es war eine gute\n"
	.string "Erfahrung für GRIT.\p"
	.string "Ich möchte dir danken!$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons_DE::
	.string "OLE: Darf ich dich bitten, gegen\n"
	.string "uns beide gleichzeitig anzutreten?$"

SevenIsland_SevaultCanyon_Text_NyaIntro_DE::
	.string "GRIT: Ich gebe mein Bestes, um\n"
	.string "meinen Mentor nicht zu enttäuschen!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat_DE::
	.string "GRIT: Oh, nein…\n"
	.string "Es tut mir so Leid…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle_DE::
	.string "GRIT: Ich denke, ich brauche noch\n"
	.string "weitere Lehrstunden unter OLE…\p"
	.string "Bitte OLE, darf ich weiter bei\n"
	.string "dir bleiben?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons_DE::
	.string "GRIT: Entschuldigung, aber trittst\n"
	.string "du in einem Zwei-gegen-Zwei-Kampf\l"
	.string "gegen uns an?$"

SevenIsland_SevaultCanyon_Text_RouteSign_DE::
	.string "7-SCHATZSCHLUCHT\n"
	.string "TANIBO-RUINEN VORAUS$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly_DE::
	.string "Für sich alleine trainieren ist mit\n"
	.string "Sicherheit keine schlechte Idee.\p"
	.string "Aber mit einem Partner nach\n"
	.string "den Sternen zu greifen, ist\l"
	.string "auch in Ordnung.\l"
	.string "Auch BRUNO…\l"
	.string "Er hat zuvor mit einem Kumpel\l"
	.string "namens KAMILLO trainiert.$"

