OneIsland_Text_BillLetsGoSeeCelio_DE::
	.string "BILL: Wir sind da!\n"
	.string "Das ist EILAND EINS!\p"
	.string "Hier gibt es mehrere Inseln und\n"
	.string "diese hier ist eine davon.\p"
	.string "Mein Freund CELIO hat das Schiff\n"
	.string "geschickt, um mich abzuholen.\p"
	.string "Er ist ganz alleine für das PC-\n"
	.string "Netzwerk auf der Insel zuständig.\p"
	.string "… warum ich dir das erzähle?\n"
	.string "Lass uns zu CELIO gehen!$"

Text_WhereDoYouWantToSail_DE::
	.string "Ahoi!\n"
	.string "Wohin soll es gehen?$"

OneIsland_Text_LuckyToHaveCelioHere_DE::
	.string "Wir sind hier auf einer Insel mitten\n"
	.string "im Nichts.\p"
	.string "Wir freuen uns, dass ein aufrechter\n"
	.string "junger Mann wie CELIO bei uns ist.\p"
	.string "Meine Enkelin war ob CELIOs neuem\n"
	.string "Freund ganz aufgeregt.\p"
	.string "Irgendetwas über einen berühmten\n"
	.string "POKéMANIAC.\p"
	.string "Ich bin mir nicht sicher, aber\n"
	.string "CELIO ist der Mann dafür!$"

OneIsland_Text_HavePCLinkageWithKanto_DE::
	.string "Meine Enkelin war ob einer neuen\n"
	.string "Erfindung ganz aufgeregt.\p"
	.string "Sie sagte, dass wir jetzt via PC\n"
	.string "mit den Menschen in KANTO\l"
	.string "verbunden sind.\p"
	.string "Ich bin mir nicht sicher, aber\n"
	.string "CELIO ist der Mann dafür!$"

OneIsland_Text_HavePCLinkageWithHoenn_DE::
	.string "Meine Enkelin war ob einer neuen\n"
	.string "Erfindung ganz aufgeregt.\p"
	.string "Sie sagte, dass wir jetzt via PC\n"
	.string "mit den Menschen in HOENN\l"
	.string "verbunden sind.\p"
	.string "Ich bin mir nicht sicher, aber\n"
	.string "CELIO ist der Mann dafür!$"

OneIsland_Text_IslandSign_DE::
	.string "EILAND EINS\n"
	.string "Freunde treffen sich auf der\l"
	.string "Knoteninsel$"

OneIsland_Text_PokemonNetCenterSign_DE::
	.string "Über die POKéMON-Welt hinaus!\n"
	.string "POKéMON NETZWERK-CENTER$"

@ Unused
OneIsland_Text_ReturnToCinnabar_DE::
	.string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat_DE::
	.string "Hallo, auf Besichtigungstour?\n"
	.string "Ist das warme Klima hier nicht\l"
	.string "großartig?$"

