OneIsland_Text_BillLetsGoSeeCelio_ES::
    .string "BILL: Bueno, ya estamos aquí.\n"
    .string "Esto es ISLA PRIMA.\p"
    .string "Como indica su nombre,\n"
    .string "no es la única isla de por aquí.\p"
    .string "Mi amigo CELIO fue el que\n"
    .string "envió el barco.\p"
    .string "Él es el encargado de la red\n"
    .string "local de la isla. Se pasa el día\l"
    .string "con eso.\p"
    .string "Bueno, que me enrollo como las\n"
    .string "persianas, ¡vamos a ver a CELIO!$"

Text_WhereDoYouWantToSail_ES::
    .string "¡Hola, caracola!\n"
    .string "¿Adónde vamos?$"

OneIsland_Text_LuckyToHaveCelioHere_ES::
    .string "La verdad es que esta isla está\n"
    .string "plantada en medio de la nada,\l"
    .string "pero bueno...\p"
    .string "Menos mal que tenemos a un\n"
    .string "chicarrón hecho y derecho como\l"
    .string "CELIO.\p"
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "con la llegada del amigo de CELIO.\p"
    .string "¿Será un POKéMANÍACO?\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.$"

OneIsland_Text_HavePCLinkageWithKanto_ES::
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "por un reciente descubrimiento.\p"
    .string "Según dijo, ahora tenemos conexión\n"
    .string "vía PC con la gente de KANTO.\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.$"

OneIsland_Text_HavePCLinkageWithHoenn_ES::
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "por un reciente descubrimiento.\p"
    .string "Según dijo, ahora tenemos conexión\n"
    .string "vía PC con la gente de HOENN.\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.\p"
    .string "¡La verdad es que sería el marido\n"
    .string "perfecto para mi nieta!$"

OneIsland_Text_IslandSign_ES::
    .string "ISLA PRIMA\n"
    .string "Punto de encuentro para todos.$"

OneIsland_Text_PokemonNetCenterSign_ES::
    .string "CENTRO DE RED POKéMON\n"
    .string "¡Un mundo POKéMON en conexión!$"

@ Unused
OneIsland_Text_ReturnToCinnabar_ES::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat_ES::
    .string "¿Qué? ¿Disfrutando del paisaje?\n"
    .string "El tiempo es fabuloso, ¿eh?$"
