LavenderTown_Text_DoYouBelieveInGhosts_ES::
    .string "¿Crees en los GHOST?$"

LavenderTown_Text_SoThereAreBelievers_ES::
    .string "¿De verdad?\n"
    .string "Hay quien no cree...$"

LavenderTown_Text_JustImaginingWhiteHand_ES::
    .string "¡Jajaja! Yo tampoco.\p"
    .string "Esa mano blanca en tu hombro no es\n"
    .string "real.$"

LavenderTown_Text_TownKnownAsMonGraveSite_ES::
    .string "A este pueblo se lo conoce como\n"
    .string "el lugar de reposo de los POKéMON.\p"
    .string "Los homenajes se celebran en la\n"
    .string "TORRE POKéMON.$"

LavenderTown_Text_GhostsAppearedInTower_ES::
    .string "Los GHOST aparecieron en la TORRE\n"
    .string "POKéMON.\p"
    .string "Creo que son espíritus de POKéMON\n"
    .string "debilitados por los ROCKET.$"

LavenderTown_Text_TownSign_ES::
    .string "PUEBLO LAVANDA\n"
    .string "El noble pueblo púrpura.$"

LavenderTown_Text_SilphScopeNotice_ES::
    .string "SILPH S.A.\p"
    .string "¡El nuevo SCOPE SILPH!\n"
    .string "¡Hace visible lo invisible!$"

LavenderTown_Text_VolunteerPokemonHouse_ES::
    .string "CASA POKéMON DE VOLUNTARIOS\n"
    .string "DE PUEBLO LAVANDA$"

LavenderTown_Text_PokemonTowerSign_ES::
    .string "TORRE POKéMON: Que las almas de\n"
    .string "los POKéMON descansen en paz.$"
