LavenderTown_Text_DoYouBelieveInGhosts_FR::
	.string "Crois-tu aux SPECTRES?$"

LavenderTown_Text_SoThereAreBelievers_FR::
	.string "Vraiment?\n"
	.string "Il en faut…$"

LavenderTown_Text_JustImaginingWhiteHand_FR::
	.string "T'as raison.\p"
	.string "La main toute blanche sur ton\n"
	.string "épaule est fausse alors…$"

LavenderTown_Text_TownKnownAsMonGraveSite_FR::
	.string "Cette ville est le cimetière des\n"
	.string "POKéMON.\p"
	.string "La TOUR POKéMON est le lieu de\n"
	.string "recueillement.$"

LavenderTown_Text_GhostsAppearedInTower_FR::
	.string "Des SPECTRES sont apparus dans la\n"
	.string "TOUR POKéMON.\p"
	.string "Ils doivent être les esprits des\n"
	.string "POKéMON tués par la ROCKET.$"

LavenderTown_Text_TownSign_FR::
	.string "LAVANVILLE\n"
	.string "Le pourpre de la noblesse$"

LavenderTown_Text_SilphScopeNotice_FR::
	.string "Tout nouveau SCOPE SYLPHE!\n"
	.string "Voir l'invisible!\p"
	.string "SYLPHE SARL$"

LavenderTown_Text_VolunteerPokemonHouse_FR::
	.string "BENEVOLAT DE LAVANVILLE\n"
	.string "MAISON POKéMON$"

LavenderTown_Text_PokemonTowerSign_FR::
	.string "Paix à l'âme des POKéMON\n"
	.string "TOUR POKéMON$"

