PokemonMansion_Text_PressSecretSwitchJP_FR::
	.string "ひみつの　スイッチが　ある！\p"
	.string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt_FR::
	.string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch_FR::
	.string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro_FR::
	.string "Fouiii…\n"
	.string "C'est grand ici!$"

PokemonMansion_1F_Text_SimonDefeat_FR::
	.string "Yargl!$"

PokemonMansion_1F_Text_SimonPostBattle_FR::
	.string "Mais où est donc mon complice?$"

PokemonMansion_1F_Text_BraydonIntro_FR::
	.string "Mon mentor vivait ici autrefois.$"

PokemonMansion_1F_Text_BraydonDefeat_FR::
	.string "!!!\n"
	.string "Impressionnant!$"

PokemonMansion_1F_Text_BraydonPostBattle_FR::
	.string "T'as perdu ton chemin?\n"
	.string "Essaie de sauter par là-bas!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo_FR::
	.string "Rapport: 6 Février.\n"
	.string "MEW est papa (ou maman?).\p"
	.string "Le petit a été baptisé MEWTWO.$"

