PokemonMansion_Text_PressSecretSwitchJP_IT::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt_IT::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch_IT::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro_IT::
    .string "Questo posto è gigantesco!$"

PokemonMansion_1F_Text_SimonDefeat_IT::
    .string "Ahi!$"

PokemonMansion_1F_Text_SimonPostBattle_IT::
    .string "Mi domando dove sia il mio amico.$"

PokemonMansion_1F_Text_BraydonIntro_IT::
    .string "Il mio maestro viveva qui.$"

PokemonMansion_1F_Text_BraydonDefeat_IT::
    .string "Wow!\n"
    .string "Impressionante!$"

PokemonMansion_1F_Text_BraydonPostBattle_IT::
    .string "Non riesci a proseguire?\n"
    .string "Prova a saltare da lì!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo_IT::
    .string "Diario: 6 febbraio\n"
    .string "MEW ha dato alla luce\l"
    .string "un nuovo POKéMON.\p"
    .string "Abbiamo chiamato MEWTWO\n"
    .string "il piccolo.$"

