PokemonMansion_Text_PressSecretSwitchJP_DE::
	.string "ひみつの　スイッチが　ある！\p"
	.string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt_DE::
	.string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch_DE::
	.string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro_DE::
	.string "Dieses Gebiet hier ist riesig!$"

PokemonMansion_1F_Text_SimonDefeat_DE::
	.string "Tschüss!$"

PokemonMansion_1F_Text_SimonPostBattle_DE::
	.string "Ich frage mich, wo mein Partner\n"
	.string "wohl sein mag!?$"

PokemonMansion_1F_Text_BraydonIntro_DE::
	.string "Mein Mentor lebte einst hier...$"

PokemonMansion_1F_Text_BraydonDefeat_DE::
	.string "Wow!\n"
	.string "Unglaublich!$"

PokemonMansion_1F_Text_BraydonPostBattle_DE::
	.string "Du kommst nicht weiter? Springe\n"
	.string "einfach da drüben herunter!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo_DE::
	.string "TAGEBUCH: 6. FEBRUAR\n"
	.string "MEW hat ein Junges geboren!\p"
	.string "Wir haben es MEWTU genannt.$"

