PokemonMansion_Text_PressSecretSwitchJP_ES::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt_ES::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch_ES::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro_ES::
    .string "Este lugar es...\n"
    .string "¡Gigantesco!$"

PokemonMansion_1F_Text_SimonDefeat_ES::
    .string "¡Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle_ES::
    .string "Me pregunto adónde habrá ido\n"
    .string "mi compañero.$"

PokemonMansion_1F_Text_BraydonIntro_ES::
    .string "Mi maestro vivió aquí hace tiempo.$"

PokemonMansion_1F_Text_BraydonDefeat_ES::
    .string "¡Uau!\n"
    .string "¡Impresionante!$"

PokemonMansion_1F_Text_BraydonPostBattle_ES::
    .string "¿No sabes por dónde ir?\n"
    .string "¡Tírate por ahí!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo_ES::
    .string "Diario: 6 de febrero.\n"
    .string "MEW dio a luz.\p"
    .string "Llamamos al pequeño: MEWTWO.$"
