LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney_DE::
	.string "Das TEAM ROCKET würde für Gold\n"
	.string "alles tun!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets_DE::
	.string "Ich sah, wie die Mutter eines\n"
	.string "jungen TRAGOSSO vergeblich\l"
	.string "versuchte, dem TEAM ROCKET zu\l"
	.string "entkommen!$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls_DE::
	.string "TRAGOSSO tragen Schädelmasken!\p"
	.string "Man zahlt für sie eine Menge Geld!$"

