LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney_FR::
	.string "La TEAM ROCKET ferait n'importe\n"
	.string "quoi pour de l'argent!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets_FR::
	.string "J'ai vu la mère d'OSSELAIT\n"
	.string "essayer d'échapper à la \l"
	.string "TEAM ROCKET!\p"
	.string "Mais elle n'a pas réussi…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls_FR::
	.string "Les OSSELAIT portent un crâne,\n"
	.string "non?\p"
	.string "Certains seraient prêts à payer\n"
	.string "le prix fort pour en avoir un!$"

