Route2_EastBuilding_Text_GiveHM05IfSeen10Mons_IT::
    .string "Ciao! Ti ricordi di me?\n"
    .string "Sono l'ASSISTENTE del PROF. OAK!\p"
    .string "Se nel POKéDEX hai i dati di\n"
    .string "almeno 10 specie di POKéMON\l"
    .string "posso darti MN05!\p"
    .string "Allora, {PLAYER}, hai raccolto dati\n"
    .string "su almeno 10 specie diverse\l"
    .string "di POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo_IT::
    .string "Bene!\n"
    .string "Hai raccolto dati su {STR_VAR_3} specie\l"
    .string "di POKéMON!\p"
    .string "Congratulazioni!\n"
    .string "Tieni! Te lo sei meritato!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide_IT::
    .string "{PLAYER} riceve\n"
    .string "MN05!$"

Route2_EastBuilding_Text_ExplainHM05_IT::
    .string "La MN FLASH illumina anche i\n"
    .string "cunicoli più bui.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel_IT::
    .string "Se un POKéMON impara FLASH,\n"
    .string "potrai partire alla volta del\l"
    .string "TUNNEL ROCCIOSO senza problemi!$"

