Route2_EastBuilding_Text_GiveHM05IfSeen10Mons_ES::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes 10 tipos de POKéMON,\n"
    .string "se supone que debería darte MO05!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "10 tipos de POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo_ES::
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide_ES::
    .string "¡{PLAYER} obtuvo la MO05\n"
    .string "de manos del AYUDANTE!$"

Route2_EastBuilding_Text_ExplainHM05_ES::
    .string "El DESTELLO de la MO ilumina hasta\n"
    .string "las más oscuras mazmorras.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel_ES::
    .string "Si un POKéMON aprende DESTELLO,\n"
    .string "podrás cruzar el TÚNEL ROCA.$"
