Route17_Text_RaulIntro_IT::
    .string "Non vale la pena lottare con i\n"
    .string "bambini!$"

Route17_Text_RaulDefeat_IT::
    .string "Sono fritto!$"

Route17_Text_RaulPostBattle_IT::
    .string "Lungo la PISTA CICLABILE trovi\n"
    .string "cose utili!$"

Route17_Text_IsaiahIntro_IT::
    .string "Che vuoi, pulce?$"

Route17_Text_IsaiahDefeat_IT::
    .string "Ooohhh!$"

Route17_Text_IsaiahPostBattle_IT::
    .string "Potrei scaraventarti via di qui a\n"
    .string "panciate!$"

Route17_Text_VirgilIntro_IT::
    .string "Vai verso FUCSIAPOLI?$"

Route17_Text_VirgilDefeat_IT::
    .string "Impanato e fritto!$"

Route17_Text_VirgilPostBattle_IT::
    .string "Mi piace correre in discesa.$"

Route17_Text_BillyIntro_IT::
    .string "Siamo CENTAURI!\n"
    .string "Veri campioni!$"

Route17_Text_BillyDefeat_IT::
    .string "Affumicato!$"

Route17_Text_BillyPostBattle_IT::
    .string "Sei in cerca del brivido?$"

Route17_Text_NikolasIntro_IT::
    .string "Troverai VOLTORB elettrizzante!$"

Route17_Text_NikolasDefeat_IT::
    .string "Ridotto in poltiglia!$"

Route17_Text_NikolasPostBattle_IT::
    .string "Ho catturato il mio VOLTORB alla\n"
    .string "CENTRALE ELETTRICA\l"
    .string "abbandonata!$"

Route17_Text_ZeekIntro_IT::
    .string "I miei POKéMON non si evolvono!\n"
    .string "Perché?$"

Route17_Text_ZeekDefeat_IT::
    .string "Tu!\n"
    .string "Cosa hai fatto?!$"

Route17_Text_ZeekPostBattle_IT::
    .string "Alcuni POKéMON hanno bisogno di\n"
    .string "PIETRE elemento per evolversi.$"

Route17_Text_JamalIntro_IT::
    .string "Ho bisogno di un po' d'esercizio!$"

Route17_Text_JamalDefeat_IT::
    .string "Uff!\n"
    .string "Questo sì che è esercizio!$"

Route17_Text_JamalPostBattle_IT::
    .string "Sono sicuramente dimagrito!$"

Route17_Text_CoreyIntro_IT::
    .string "Sii ribelle!$"

Route17_Text_CoreyDefeat_IT::
    .string "Grrr!$"

Route17_Text_CoreyPostBattle_IT::
    .string "Non rinunciare mai a lottare per\n"
    .string "le tue idee!$"

Route17_Text_JaxonIntro_IT::
    .string "Bella BICICLETTA!\n"
    .string "Come funziona?$"

Route17_Text_JaxonDefeat_IT::
    .string "Che schianti!$"

Route17_Text_JaxonPostBattle_IT::
    .string "È difficile sterzare in discesa!$"

Route17_Text_WilliamIntro_IT::
    .string "Sparisci, pulce!\n"
    .string "Sono esausto!$"

Route17_Text_WilliamDefeat_IT::
    .string "Sei felice adesso?$"

Route17_Text_WilliamPostBattle_IT::
    .string "Devo recuperare il sonno perduto!$"

Route17_Text_WatchOutForDiscardedItems_IT::
    .string "Un avviso!\p"
    .string "Attenzione agli strumenti\n"
    .string "abbandonati!$"

Route17_Text_SameSpeciesGrowDifferentRates_IT::
    .string "CONSIGLI UTILI\p"
    .string "Tutti i POKéMON sono diversi.\p"
    .string "POKéMON della stessa specie e\n"
    .string "e di uguale livello crescono a\l"
    .string "ritmi diversi.$"

Route17_Text_PressBToStayInPlace_IT::
    .string "CONSIGLI UTILI\p"
    .string "Premi il pulsante B per restare in\n"
    .string "equilibrio in discesa.$"

Route17_Text_RouteSign_IT::
    .string "PERCORSO 17\n"
    .string "AZZURROPOLI - FUCSIAPOLI$"

Route17_Text_DontThrowGameThrowBalls_IT::
    .string "AVVISO:\p"
    .string "Se perdi le staffe, non buttare\n"
    .string "il gioco contro il muro, ma\l"
    .string "lancia un paio di POKé BALL!$"

Route17_Text_CyclingRoadSign_IT::
    .string "PISTA CICLABILE\n"
    .string "Fine discesa!$"

