Route17_Text_RaulIntro_FR::
	.string "Pff… Un gosse, ça n'a jamais\n"
	.string "d'flouze!$"

Route17_Text_RaulDefeat_FR::
	.string "Nan!!!\n"
	.string "Mon carbure!$"

Route17_Text_RaulPostBattle_FR::
	.string "Y a plein de trucs qui traînent\n"
	.string "sur la PISTE CYCLABLE!$"

Route17_Text_IsaiahIntro_FR::
	.string "Kess tu veux, toi l'mioche?$"

Route17_Text_IsaiahDefeat_FR::
	.string "Whoua!$"

Route17_Text_IsaiahPostBattle_FR::
	.string "Je vais t'éjecter d'ici à coup de\n"
	.string "claques!$"

Route17_Text_VirgilIntro_FR::
	.string "Tu vas à PARMANIE?$"

Route17_Text_VirgilDefeat_FR::
	.string "Argh!\n"
	.string "Fumé!$"

Route17_Text_VirgilPostBattle_FR::
	.string "J'aime pédaler comme un dingue!\n"
	.string "Un giga-dingue!$"

Route17_Text_BillyIntro_FR::
	.string "On est des MOTARDS!\n"
	.string "Des vrais, des purs, des durs,\l"
	.string "des méchants… Et tout et tout!$"

Route17_Text_BillyDefeat_FR::
	.string "Nyargh!\n"
	.string "J'ai crevé une roue!$"

Route17_Text_BillyPostBattle_FR::
	.string "Tu cherches l'aventure?$"

Route17_Text_NikolasIntro_FR::
	.string "Mes VOLTORBE vont t'électrocuter!$"

Route17_Text_NikolasDefeat_FR::
	.string "Arglagh!\n"
	.string "J'me suis fait électrocuter!$"

Route17_Text_NikolasPostBattle_FR::
	.string "J'ai attrapé un VOLTORBE dans la\n"
	.string "CENTRALE.$"

Route17_Text_ZeekIntro_FR::
	.string "Hein? Faire évoluer mes POKéMON?\n"
	.string "Ben pourquoi?$"

Route17_Text_ZeekDefeat_FR::
	.string "Ha…\n"
	.string "OK, OK!$"

Route17_Text_ZeekPostBattle_FR::
	.string "Certains POKéMON ont besoin d'une\n"
	.string "PIERRE pour évoluer.$"

Route17_Text_JamalIntro_FR::
	.string "J'ai besoin d'un peu d'exercice!$"

Route17_Text_JamalDefeat_FR::
	.string "Pfou!\n"
	.string "J'suis épuisé!$"

Route17_Text_JamalPostBattle_FR::
	.string "Cool!\n"
	.string "J'ai perdu du poids!$"

Route17_Text_CoreyIntro_FR::
	.string "No future!$"

Route17_Text_CoreyDefeat_FR::
	.string "Aaaargh!$"

Route17_Text_CoreyPostBattle_FR::
	.string "Prépare-toi à la baston, microbe!$"

Route17_Text_JaxonIntro_FR::
	.string "Mignon le VELO!\n"
	.string "Comment ça se conduit?$"

Route17_Text_JaxonDefeat_FR::
	.string "Pan!\n"
	.string "Dans les dents!$"

Route17_Text_JaxonPostBattle_FR::
	.string "La pente rend la conduite\n"
	.string "difficile!$"

Route17_Text_WilliamIntro_FR::
	.string "Du vent toi!\n"
	.string "J'suis épuisé!$"

Route17_Text_WilliamDefeat_FR::
	.string "Voilà, ça te va?$"

Route17_Text_WilliamPostBattle_FR::
	.string "Je vais aller piquer un somme!$"

Route17_Text_WatchOutForDiscardedItems_FR::
	.string "Un conseil!\p"
	.string "Attention de ne pas jeter un objet\n"
	.string "important!$"

Route17_Text_SameSpeciesGrowDifferentRates_FR::
	.string "ASTUCE\p"
	.string "Chaque POKéMON est unique.\p"
	.string "Des POKéMON de même type et de\n"
	.string "même niveau évoluent différemment.$"

Route17_Text_PressBToStayInPlace_FR::
	.string "ASTUCE\p"
	.string "Appuyez sur le bouton B pour\n"
	.string "vous arrêter dans une descente.$"

Route17_Text_RouteSign_FR::
	.string "ROUTE 17\n"
	.string "CELADOPOLE - PARMANIE$"

Route17_Text_DontThrowGameThrowBalls_FR::
	.string "Un conseil!\p"
	.string "Ne jetez pas la console, jetez\n"
	.string "plutôt des POKé BALLS.$"

Route17_Text_CyclingRoadSign_FR::
	.string "PISTE CYCLABLE\n"
	.string "Fin de la descente!$"

