Route17_Text_RaulIntro_ES::
    .string "¡No compensa luchar con niños!$"

Route17_Text_RaulDefeat_ES::
    .string "¡Qué chasco!$"

Route17_Text_RaulPostBattle_ES::
    .string "¡Por el CAMINO de BICIS\n"
    .string "hay cosas estupendas!\p"
    .string "¡Se puede ganar mucha pasta\n"
    .string "vendiendo lo que se encuentra!$"

Route17_Text_IsaiahIntro_ES::
    .string "¿Y tú qué quieres?$"

Route17_Text_IsaiahDefeat_ES::
    .string "¡Uauuu!$"

Route17_Text_IsaiahPostBattle_ES::
    .string "¡Podría echarte de aquí de\n"
    .string "un barrigazo!$"

Route17_Text_VirgilIntro_ES::
    .string "¿Te diriges a CIUDAD FUCSIA?$"

Route17_Text_VirgilDefeat_ES::
    .string "¡Destrozado y vencido!$"

Route17_Text_VirgilPostBattle_ES::
    .string "Me gusta pedalear cuesta abajo.$"

Route17_Text_BillyIntro_ES::
    .string "¡Somos los MOTORISTAS!\n"
    .string "¡Las estrellas de la autopista!$"

Route17_Text_BillyDefeat_ES::
    .string "¡Qué trompazo!$"

Route17_Text_BillyPostBattle_ES::
    .string "¿Vas en busca de aventuras?$"

Route17_Text_NikolasIntro_ES::
    .string "¡Deja que VOLTORB te dé un poco\n"
    .string "de su energía!$"

Route17_Text_NikolasDefeat_ES::
    .string "¡Qué bajón!$"

Route17_Text_NikolasPostBattle_ES::
    .string "¡Atrapé mis VOLTORB en la\n"
    .string "CENTRAL de ENERGÍA abandonada!$"

Route17_Text_ZeekIntro_ES::
    .string "¡Mi POKéMON no evoluciona!\n"
    .string "¿Por qué será?$"

Route17_Text_ZeekDefeat_ES::
    .string "¡Tú tienes la culpa!$"

Route17_Text_ZeekPostBattle_ES::
    .string "Puede que ciertos POKéMON\n"
    .string "necesiten PIEDRAS para\l"
    .string "evolucionar.$"

Route17_Text_JamalIntro_ES::
    .string "¡Necesito un poco de ejercicio!$"

Route17_Text_JamalDefeat_ES::
    .string "¡Ufff!\n"
    .string "¡Qué buen entrenamiento!$"

Route17_Text_JamalPostBattle_ES::
    .string "¡Seguro que he perdido peso!$"

Route17_Text_CoreyIntro_ES::
    .string "¡Sé rebelde!$"

Route17_Text_CoreyDefeat_ES::
    .string "¡Aaaargh!$"

Route17_Text_CoreyPostBattle_ES::
    .string "¡Prepárate para luchar\n"
    .string "por tus ideas!$"

Route17_Text_JaxonIntro_ES::
    .string "¡Bonita BICI!\n"
    .string "¿Cómo se conduce?$"

Route17_Text_JaxonDefeat_ES::
    .string "¡Me dejas fuera de juego!$"

Route17_Text_JaxonPostBattle_ES::
    .string "¡La pendiente dificulta\n"
    .string "la conducción!$"

Route17_Text_WilliamIntro_ES::
    .string "¡Lárgate!\n"
    .string "¡Estoy agotado!$"

Route17_Text_WilliamDefeat_ES::
    .string "¿Te has quedado a gusto?$"

Route17_Text_WilliamPostBattle_ES::
    .string "¡Tengo que recuperar sueño\n"
    .string "atrasado!$"

Route17_Text_WatchOutForDiscardedItems_ES::
    .string "¡Aviso!\p"
    .string "¡Ojo con las cosas que hay\n"
    .string "por el suelo!$"

Route17_Text_SameSpeciesGrowDifferentRates_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "Todo POKéMON es único.\p"
    .string "Hasta los POKéMON del mismo tipo\n"
    .string "y nivel crecen a diferente ritmo.$"

Route17_Text_PressBToStayInPlace_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "Pulsa el Botón B para no moverte\n"
    .string "sobre una pendiente.$"

Route17_Text_RouteSign_ES::
    .string "RUTA 17:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"

Route17_Text_DontThrowGameThrowBalls_ES::
    .string "¡Aviso!\p"
    .string "¡No tires el juego, mejor tira\n"
    .string "POKé BALLS!$"

Route17_Text_CyclingRoadSign_ES::
    .string "CAMINO DE BICIS\n"
    .string "¡La pendiente termina aquí!$"
