Route17_Text_RaulIntro_DE::
	.string "Es lohnt sich nicht, Kinder\n"
	.string "auszurauben!$"

Route17_Text_RaulDefeat_DE::
	.string "Die Luft ist raus!$"

Route17_Text_RaulPostBattle_DE::
	.string "Auf dem RADWEG liegen nützliche\n"
	.string "Items herum!$"

Route17_Text_IsaiahIntro_DE::
	.string "Was willst du, Tröte?$"

Route17_Text_IsaiahDefeat_DE::
	.string "Hoho!$"

Route17_Text_IsaiahPostBattle_DE::
	.string "Ich könnte dich mit einem\n"
	.string "Bauchplatscher plattmachen!$"

Route17_Text_VirgilIntro_DE::
	.string "Willst du nach FUCHSANIA CITY?$"

Route17_Text_VirgilDefeat_DE::
	.string "Ich habe mein Bestes gegeben!$"

Route17_Text_VirgilPostBattle_DE::
	.string "Ich liebe es, bergab Rennen zu\n"
	.string "fahren!$"

Route17_Text_BillyIntro_DE::
	.string "Wir sind BIKER, Könige des\n"
	.string "Highways!$"

Route17_Text_BillyDefeat_DE::
	.string "Ich bin voll auf die Nase\n"
	.string "gefallen!$"

Route17_Text_BillyPostBattle_DE::
	.string "Suchst du das Abenteuer?$"

Route17_Text_NikolasIntro_DE::
	.string "VOLTOBAL wird dich unter Strom\n"
	.string "setzen!$"

Route17_Text_NikolasDefeat_DE::
	.string "Du hast mich geerdet!$"

Route17_Text_NikolasPostBattle_DE::
	.string "Ich habe VOLTOBAL im verlassenen\n"
	.string "KRAFTWERK gefangen.$"

Route17_Text_ZeekIntro_DE::
	.string "Mein POKéMON entwickelt sich nicht\n"
	.string "weiter!$"

Route17_Text_ZeekDefeat_DE::
	.string "Heh, was sollte das?$"

Route17_Text_ZeekPostBattle_DE::
	.string "Manche POKéMON benötigen\n"
	.string "spezielle STEINE, um sich zu\l"
	.string "entwickeln.$"

Route17_Text_JamalIntro_DE::
	.string "Ich muss ein wenig abnehmen!$"

Route17_Text_JamalDefeat_DE::
	.string "Puh!\n"
	.string "Eine gute Übung!$"

Route17_Text_JamalPostBattle_DE::
	.string "Ich habe sicher an Gewicht\n"
	.string "verloren!$"

Route17_Text_CoreyIntro_DE::
	.string "Sei ein Rebell!$"

Route17_Text_CoreyDefeat_DE::
	.string "Arrrgh!$"

Route17_Text_CoreyPostBattle_DE::
	.string "Setze dich für deine Ideale ein!$"

Route17_Text_JaxonIntro_DE::
	.string "Du besitzt ein schickes FAHRRAD!\n"
	.string "Fährt es sich gut?$"

Route17_Text_JaxonDefeat_DE::
	.string "Mist!$"

Route17_Text_JaxonPostBattle_DE::
	.string "Das Gefälle macht das Lenken sehr\n"
	.string "schwer!$"

Route17_Text_WilliamIntro_DE::
	.string "Zieh Leine!\n"
	.string "Ich bin erschöpft!$"

Route17_Text_WilliamDefeat_DE::
	.string "Bist du nun zufrieden?$"

Route17_Text_WilliamPostBattle_DE::
	.string "Ich muss mich eine Runde aufs Ohr\n"
	.string "legen!$"

Route17_Text_WatchOutForDiscardedItems_DE::
	.string "Ein Hinweis!\p"
	.string "Achte auf weggeworfene Items!$"

Route17_Text_SameSpeciesGrowDifferentRates_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Jedes POKéMON ist einzigartig.\p"
	.string "Selbst gleiche POKéMON mit\n"
	.string "identischem Level unterscheiden\l"
	.string "sich voneinander.$"

Route17_Text_PressBToStayInPlace_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Drücke den B-Knopf, um auch bei\n"
	.string "Gefälle die Position zu halten.$"

Route17_Text_RouteSign_DE::
	.string "ROUTE 17\n"
	.string "PRISMANIA CITY - FUCHSANIA CITY$"

Route17_Text_DontThrowGameThrowBalls_DE::
	.string "Ein Hinweis!\p"
	.string "Gib niemals auf! Versuche dein\n"
	.string "Glück mit POKéBÄLLEN!$"

Route17_Text_CyclingRoadSign_DE::
	.string "Der RADWEG endet hier!$"

