Route5_PokemonDayCare_Text_WantMeToRaiseMon_ES::
    .string "Esta GUARDERÍA es mía.\p"
    .string "¿Quieres que cuide de alguno\n"
    .string "de tus POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain_ES::
    .string "Vuelve en otro momento.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise_ES::
    .string "¿Qué POKéMON quieres que cuide?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike_ES::
    .string "Vale...\n"
    .string "Vuelve cuando quieras.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile_ES::
    .string "Muy bien, cuidaré de {STR_VAR_1}\n"
    .string "un rato.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile_ES::
    .string "Vuelve dentro de un rato.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime_ES::
    .string "¿Ya de vuelta?\p"
    .string "Tu {STR_VAR_1} aún necesita de mis\n"
    .string "cuidados.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn_ES::
    .string "Me debes {STR_VAR_2}¥ por este\n"
    .string "POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon_ES::
    .string "¡Gracias!\n"
    .string "¡Aquí está tu POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack_ES::
    .string "¡{PLAYER} recuperó a {STR_VAR_1}!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou_ES::
    .string "Sólo tienes un POKéMON contigo.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith_ES::
    .string "Si me dejas ese POKéMON, no\n"
    .string "podrás entablar combates.$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels_ES::
    .string "¡Tu {STR_VAR_1} ha crecido mucho!\p"
    .string "¡Su nivel ha subido {STR_VAR_2}!\p"
    .string "¿No soy genial?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt_ES::
    .string "¡No tienes sitio para este POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney_ES::
    .string "¡Oye, no tienes bastante dinero!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours_ES::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM_ES::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"
