Route5_PokemonDayCare_Text_WantMeToRaiseMon_FR::
	.string "Je m'occupe de la PENSION.\p"
	.string "Veux-tu que j'élève un de tes\n"
	.string "POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain_FR::
	.string "A plus tard.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise_FR::
	.string "Quel POKéMON veux-tu me confier?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike_FR::
	.string "Je vois.\n"
	.string "Reviens me voir.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile_FR::
	.string "Très bien, je vais m'occuper de\n"
	.string "{STR_VAR_1}.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile_FR::
	.string "Reviens un peu plus tard.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime_FR::
	.string "Déjà de retour?\p"
	.string "Ton {STR_VAR_1} doit rester encore\n"
	.string "un peu.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn_FR::
	.string "Donne-moi {STR_VAR_2}¥ pour que\n"
	.string "je te rende ton POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon_FR::
	.string "Merci!\n"
	.string "Voilà ton p'tit POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack_FR::
	.string "{PLAYER} récupère\n"
	.string "{STR_VAR_1}!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou_FR::
	.string "Oh!\n"
	.string "Tu n'as qu'un POKéMON sur toi.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith_FR::
	.string "Si tu me le laisses, avec quoi\n"
	.string "vas-tu pouvoir combattre?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels_FR::
	.string "Ton {STR_VAR_1} a bien grandi!\p"
	.string "Il a {STR_VAR_2} niveau(x)\n"
	.string "de plus!\p"
	.string "Merci qui? Hein?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt_FR::
	.string "Tu n'as plus de place pour ce\n"
	.string "POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney_FR::
	.string "Hé! Tu n'as pas assez d'argent!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours_FR::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM_FR::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"

