Route5_PokemonDayCare_Text_WantMeToRaiseMon_DE::
	.string "Ich leite diese PENSION.\p"
	.string "Soll ich eines deiner POKéMON\n"
	.string "großziehen?$"

Route5_PokemonDayCare_Text_ComeAgain_DE::
	.string "Dann bis später.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise_DE::
	.string "Welches POKéMON soll hier bleiben?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike_DE::
	.string "Ich verstehe.\n"
	.string "Komm mich wieder besuchen.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile_DE::
	.string "O.K., ich kümmere mich eine Weile\n"
	.string "um {STR_VAR_1}.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile_DE::
	.string "Komm später wieder vorbei, um es\n"
	.string "abzuholen.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime_DE::
	.string "Du bist schon wieder zurück?\p"
	.string "{STR_VAR_1} sollte noch ein\n"
	.string "bisschen bei mir bleiben.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn_DE::
	.string "Bevor du dein POKéMON wieder\n"
	.string "mitnimmst, bekomme ich noch\l"
	.string "{STR_VAR_2}¥ von dir!$"

Route5_PokemonDayCare_Text_ThankYouHeresMon_DE::
	.string "Vielen Dank!\n"
	.string "Hier ist dein POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack_DE::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1} zurück!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou_DE::
	.string "Du hast nur ein POKéMON dabei!$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith_DE::
	.string "Wenn du mir dieses POKéMON\n"
	.string "überlässt, womit willst du kämpfen?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels_DE::
	.string "{STR_VAR_1} hat sich toll \n"
	.string "entwickelt!\p"
	.string "Es ist um {STR_VAR_2} Level gestiegen!\p"
	.string "Das habe ich gut gemacht, oder?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt_DE::
	.string "Du kannst kein weiteres POKéMON\n"
	.string "mehr tragen!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney_DE::
	.string "Oh, du hast nicht genug Geld!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours_DE::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM_DE::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"

