Route5_PokemonDayCare_Text_WantMeToRaiseMon_IT::
    .string "Questa PENSIONE è mia.\p"
    .string "Vuoi che accudisca uno dei tuoi\n"
    .string "POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain_IT::
    .string "Torna più tardi!$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise_IT::
    .string "Che POKéMON devo allevare?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike_IT::
    .string "Capisco…\n"
    .string "Torna a farmi visita.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile_IT::
    .string "Bene, baderò io a {STR_VAR_1} per\n"
    .string "un po'.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile_IT::
    .string "Torna a trovarmi fra un po'.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime_IT::
    .string "Già di ritorno?\p"
    .string "Il tuo {STR_VAR_1} ha ancora\n"
    .string "bisogno delle mie cure.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn_IT::
    .string "Devi darmi ¥{STR_VAR_2} per riavere\n"
    .string "questo POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon_IT::
    .string "Grazie!\n"
    .string "Ecco il tuo POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack_IT::
    .string "{PLAYER} recupera\n"
    .string "il suo {STR_VAR_1}!$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou_IT::
    .string "Hai un solo POKéMON con te.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith_IT::
    .string "Se mi lasci quel POKéMON,\n"
    .string "come farai a lottare?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels_IT::
    .string "Il tuo {STR_VAR_1} è cresciuto\n"
    .string "bene!\p"
    .string "Il suo livello è salito di {STR_VAR_2}!\n"
    .string "Fantastico, eh?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt_IT::
    .string "Non hai spazio per questo POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney_IT::
    .string "Ehi, non hai abbastanza soldi!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours_IT::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM_IT::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"

