SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro_FR::
	.string "Yahaa!\n"
	.string "Je vais te battre sans efforts.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat_FR::
	.string "Tsss!\n"
	.string "Pas assez forte!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle_FR::
	.string "Comment?\p"
	.string "Mes actes ne collent pas avec\n"
	.string "mon look?\p"
	.string "Hey, ça fait partie de ma\n"
	.string "stratégie.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro_FR::
	.string "Hello!\n"
	.string "T'es membre de mon fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat_FR::
	.string "Non, tu ne dois pas être fan…\p"
	.string "Bon, je peux y remédier. Je vais\n"
	.string "te chanter quelque chose.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle_FR::
	.string "Lalalalaaa…\n"
	.string "Quand j'envoie mes POKéMON,\l"
	.string "les filles se mettent à crier.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro_FR::
	.string "Cette île est trop étendue…\n"
	.string "C'est difficile d'aller partout.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat_FR::
	.string "Oh oh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle_FR::
	.string "Les DRESSEURS de la ville comme\n"
	.string "toi, ils sont tous aussi forts?\p"
	.string "Tu te diriges vers la TOUR, non?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro_FR::
	.string "Je punis les gens qui font\n"
	.string "du mal aux POKéMON.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat_FR::
	.string "Tu ne sembles pas être du genre\n"
	.string "à créer des problèmes.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle_FR::
	.string "Si tu traites tes POKéMON avec\n"
	.string "gentillesse, ils le sentiront.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro_FR::
	.string "EVE: Je vais me joindre à JOE\n"
	.string "pour t'écraser.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat_FR::
	.string "EVE: On a perdu…$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle_FR::
	.string "EVE: On va s'entraîner plus.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons_FR::
	.string "EVE: Je vais me joindre à JOE\n"
	.string "pour t'écraser.\p"
	.string "Mais reviens quand tu auras\n"
	.string "deux POKéMON, OK?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro_FR::
	.string "JOE: Avec EVE, je me sens\n"
	.string "invincible.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat_FR::
	.string "JOE: La défaite ne compte pas tant\n"
	.string "que je suis avec elle.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle_FR::
	.string "JOE: Quand je suis avec elle…\p"
	.string "je me sens bien que je gagne\n"
	.string "ou que je perde.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons_FR::
	.string "JOE: Si c'est avec EVE, je serai\n"
	.string "content de me battre contre toi.\p"
	.string "Si c'était possible, on aurait pu\n"
	.string "faire un deux contre deux.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign_FR::
	.string "ENTREE DU CANYON SESOR\p"
	.string "Evitez de piétiner les plantes\n"
	.string "du canyon.$"

