Route12_Text_MonSprawledOutInSlumber_ES::
    .string "¡Un POKéMON dormido bloquea\n"
    .string "el camino!$"

Text_SnorlaxWokeUp_ES::
    .string "¡SNORLAX se ha despertado!\p"
    .string "¡Se ha enfadado mucho\n"
    .string "y te quiere atacar!$"

Text_SnorlaxReturnedToMountains_ES::
    .string "SNORLAX se ha calmado.\n"
    .string "¡Y tras bostezar se ha marchado\l"
    .string "a las montañas!$"

Text_WantToUsePokeFlute_ES::
    .string "¿Quieres usar la POKé FLAUTA?$"

Text_PlayedPokeFlute_ES::
    .string "{PLAYER} tocó la POKé FLAUTA.$"

Route12_Text_NedIntro_ES::
    .string "¡Bien!\n"
    .string "¡Ha picado algo!$"

Route12_Text_NedDefeat_ES::
    .string "¡Bah!\n"
    .string "¡Era muy pequeñajo!$"

Route12_Text_NedPostBattle_ES::
    .string "¡Alto!\n"
    .string "¡Mi sedal está enganchado!$"

Route12_Text_ChipIntro_ES::
    .string "¡Ten paciencia!\n"
    .string "¡Pescar requiere tiempo!$"

Route12_Text_ChipDefeat_ES::
    .string "¡Ése se escapó!$"

Route12_Text_ChipPostBattle_ES::
    .string "¡Con una CAÑA mejor podría pescar\n"
    .string "mejores POKéMON!$"

Route12_Text_JustinIntro_ES::
    .string "¿Has encontrado una PIEDRA LUNAR?$"

Route12_Text_JustinDefeat_ES::
    .string "¡Auuuu!$"

Route12_Text_JustinPostBattle_ES::
    .string "¡Podría haber transformado a mis\n"
    .string "POKéMON con una PIEDRA LUNAR!\p"
    .string "¡Y podría haber ganado!$"

Route12_Text_LucaIntro_ES::
    .string "¡Soy un experto en electricidad!\p"
    .string "Pero no sé nada sobre los POKéMON\n"
    .string "de mar.$"

Route12_Text_LucaDefeat_ES::
    .string "¡Se acabó!$"

Route12_Text_LucaPostBattle_ES::
    .string "El agua conduce la electricidad.\n"
    .string "¡Deberías poder atrapar a los\l"
    .string "POKéMON de mar!$"

Route12_Text_HankIntro_ES::
    .string "¡El PESCADOR LOCO contra alguien\n"
    .string "que no tiene idea sobre POKéMON!$"

Route12_Text_HankDefeat_ES::
    .string "¡Te has pasado!$"

Route12_Text_HankPostBattle_ES::
    .string "¡Me has ganado con los POKéMON,\n"
    .string "pero yo soy muy bueno pescando!\p"
    .string "Supongo que hay que hacer lo que\n"
    .string "mejor se le da a cada uno...$"

Route12_Text_ElliotIntro_ES::
    .string "A mí me encanta pescar, ¡pero\n"
    .string "es que no pican ni a la de tres!$"

Route12_Text_ElliotDefeat_ES::
    .string "No es fácil...$"

Route12_Text_ElliotPostBattle_ES::
    .string "Está bien.\n"
    .string "Perder ya no me importa.$"

Route12_Text_AndrewIntro_ES::
    .string "¡Nunca se sabe lo que puedes\n"
    .string "pescar!$"

Route12_Text_AndrewDefeat_ES::
    .string "¡He perdido!$"

Route12_Text_AndrewPostBattle_ES::
    .string "Es fácil pescar MAGIKARP,\n"
    .string "¡son tan débiles!$"

Route12_Text_RouteSign_ES::
    .string "RUTA 12:\n"
    .string "LAVANDA, al norte$"

Route12_Text_SportfishingArea_ES::
    .string "ZONA DE PESCA$"

Route12_Text_JesIntro_ES::
    .string "ARE: Si gano, le pediré a AGA\n"
    .string "que se case conmigo.$"

Route12_Text_JesDefeat_ES::
    .string "ARE: ¿Puedes dejarnos ganar,\n"
    .string "por favor?$"

Route12_Text_JesPostBattle_ES::
    .string "ARE: AGA, ¡lo siento, cariño!$"

Route12_Text_JesNotEnoughMons_ES::
    .string "ARE: AGA y yo vamos a estar juntos\n"
    .string "toda la vida.\p"
    .string "¡Y no lucharemos hasta que no\n"
    .string "tengas dos POKéMON!$"

Route12_Text_GiaIntro_ES::
    .string "AGA: Oye, ARE...\p"
    .string "Si ganamos, ¡me caso contigo!$"

Route12_Text_GiaDefeat_ES::
    .string "AGA: Oh... ¿Por qué?$"

Route12_Text_GiaPostBattle_ES::
    .string "AGA: ¡ARE, eres medio lelo! ¡Todo\n"
    .string "se ha fastidiado por tu culpa!$"

Route12_Text_GiaNotEnoughMons_ES::
    .string "AGA: ¡No pienso luchar sin mi ARE!\p"
    .string "¿No tienes dos POKéMON?$"
