Route12_Text_MonSprawledOutInSlumber_DE::
	.string "Ein schlafendes POKéMON\n"
	.string "versperrt den Weg!$"

Text_SnorlaxWokeUp_DE::
	.string "RELAXO ist aufgewacht!\p"
	.string "Es ist brummig und greift\n"
	.string "verschlafen an!$"

Text_SnorlaxReturnedToMountains_DE::
	.string "RELAXO hat sich wieder beruhigt!\n"
	.string "Es gähnt und läuft in die Berge\l"
	.string "zurück!$"

Text_WantToUsePokeFlute_DE::
	.string "Die POKéFLÖTE spielen?$"

Text_PlayedPokeFlute_DE::
	.string "{PLAYER} spielt die POKéFLÖTE.$"

Route12_Text_NedIntro_DE::
	.string "Cool!\n"
	.string "Mir ist etwas ins Netz gegangen!$"

Route12_Text_NedDefeat_DE::
	.string "Mist!\n"
	.string "Bloß ein kleiner Fisch!$"

Route12_Text_NedPostBattle_DE::
	.string "Irgendwann werde ich den großen\n"
	.string "Fang machen!$"

Route12_Text_ChipIntro_DE::
	.string "Nur mit der Ruhe!\n"
	.string "Als Angler muss man geduldig sein!$"

Route12_Text_ChipDefeat_DE::
	.string "Der ist mir entwischt!$"

Route12_Text_ChipPostBattle_DE::
	.string "Hätte ich eine bessere ANGEL,\n"
	.string "würde ich bessere POKéMON fangen!$"

Route12_Text_JustinIntro_DE::
	.string "Besitzt du einen MONDSTEIN?$"

Route12_Text_JustinDefeat_DE::
	.string "Aua!$"

Route12_Text_JustinPostBattle_DE::
	.string "Wenn ich einen MONDSTEIN hätte,\n"
	.string "könnten sich meine POKéMON\l"
	.string "weiterentwickeln!$"

Route12_Text_LucaIntro_DE::
	.string "Elektrizität ist meine Stärke!$"

Route12_Text_LucaDefeat_DE::
	.string "Stromkreis unterbrochen!$"

Route12_Text_LucaPostBattle_DE::
	.string "Wasser leitet Elektrizität. Greife\n"
	.string "WASSER-POKéMON mit Elektrizität an!$"

Route12_Text_HankIntro_DE::
	.string "Der ANGELKÖNIG gegen das POKéMON-\n"
	.string "KIND!$"

Route12_Text_HankDefeat_DE::
	.string "Das war spitze!$"

Route12_Text_HankPostBattle_DE::
	.string "Von POKéMON verstehst du sehr\n"
	.string "viel, doch ich bin der bessere\l"
	.string "Angler!$"

Route12_Text_ElliotIntro_DE::
	.string "Eigentlich würde ich lieber\n"
	.string "arbeiten...$"

Route12_Text_ElliotDefeat_DE::
	.string "Das war wahrlich kein\n"
	.string "Zuckerschlecken!$"

Route12_Text_ElliotPostBattle_DE::
	.string "O.K., mit der Zeit gewöhnt man sich\n"
	.string "daran, zu verlieren!$"

Route12_Text_AndrewIntro_DE::
	.string "Man weiß nie, was der nächste Fang\n"
	.string "sein wird!$"

Route12_Text_AndrewDefeat_DE::
	.string "Ich habe verloren!$"

Route12_Text_AndrewPostBattle_DE::
	.string "Ich fange immer KARPADOR. Doch\n"
	.string "sie sind so schwach!$"

Route12_Text_RouteSign_DE::
	.string "ROUTE 12\n"
	.string "NORDEN: LAVANDIA$"

Route12_Text_SportfishingArea_DE::
	.string "SPORTANGEL-ZONE$"

Route12_Text_JesIntro_DE::
	.string "DENIZ: Falls ich gewinne, mache\n"
	.string "ich SIRA einen Heiratsantrag!$"

Route12_Text_JesDefeat_DE::
	.string "DENIZ: Oh, Mist! Warum konntest du\n"
	.string "uns nicht gewinnen lassen?$"

Route12_Text_JesPostBattle_DE::
	.string "DENIZ: OH, SIRA, meine Liebste,\n"
	.string "verzeih mir!$"

Route12_Text_JesNotEnoughMons_DE::
	.string "DENIZ: SIRA und ich werden für\n"
	.string "immer zusammen sein.\p"
	.string "Wir werden nicht kämpfen, ehe du\n"
	.string "nicht zwei POKéMON mitbringst.$"

Route12_Text_GiaIntro_DE::
	.string "SIRA: HEH, DENIZ…\p"
	.string "wenn wir gewinnen, heiraten wir!$"

Route12_Text_GiaDefeat_DE::
	.string "SIRA: Aber warum nur?$"

Route12_Text_GiaPostBattle_DE::
	.string "SIRA: DENIZ, du Dummerchen!\n"
	.string "Du hast es vermasselt!$"

Route12_Text_GiaNotEnoughMons_DE::
	.string "SIRA: Ich ertrage es nicht, ohne\n"
	.string "meinen DENIZ zu kämpfen.\p"
	.string "Hast du nicht noch ein weiteres\n"
	.string "POKéMON?$"

