Route12_Text_MonSprawledOutInSlumber_FR::
	.string "Un POKéMON endormi bloque le\n"
	.string "chemin!$"

Text_SnorlaxWokeUp_FR::
	.string "RONFLEX se réveille!\p"
	.string "Il est de mauvais poil!\n"
	.string "Il vous attaque!$"

Text_SnorlaxReturnedToMountains_FR::
	.string "RONFLEX, une fois calmé, s'en\n"
	.string "retourne vers la montagne!$"

Text_WantToUsePokeFlute_FR::
	.string "Tu veux utiliser la POKéFLUTE?$"

Text_PlayedPokeFlute_FR::
	.string "Vous jouez de la POKéFLUTE.$"

Route12_Text_NedIntro_FR::
	.string "Ouais! Ça mord dans l'coin!$"

Route12_Text_NedDefeat_FR::
	.string "Tsss!\n"
	.string "Trop p'tit!$"

Route12_Text_NedPostBattle_FR::
	.string "Bouge pas!\n"
	.string "J'ai une touche!$"

Route12_Text_ChipIntro_FR::
	.string "Patience!\n"
	.string "Pour pêcher, faut être tranquille!$"

Route12_Text_ChipDefeat_FR::
	.string "Je l'ai laissé filer!$"

Route12_Text_ChipPostBattle_FR::
	.string "Pour pêcher des POKéMON plus\n"
	.string "gros, il me faut une super CANNE!$"

Route12_Text_JustinIntro_FR::
	.string "As-tu trouvé une PIERRE LUNE?$"

Route12_Text_JustinDefeat_FR::
	.string "Aïe!$"

Route12_Text_JustinPostBattle_FR::
	.string "J'aurais pu faire évoluer mes\n"
	.string "POKéMON avec une PIERRE LUNE!\p"
	.string "Et là, j'aurais gagné, c'est sûr!$"

Route12_Text_LucaIntro_FR::
	.string "L'électricité, c'est ma spécialité!$"

Route12_Text_LucaDefeat_FR::
	.string "Court-jus!$"

Route12_Text_LucaPostBattle_FR::
	.string "L'eau conduit l'électricité. Planque\n"
	.string "tous tes POKéMON aquatiques!$"

Route12_Text_HankIntro_FR::
	.string "Le PECHEUR FOU contre le KID des\n"
	.string "POKéMON!$"

Route12_Text_HankDefeat_FR::
	.string "T'as gagné!$"

Route12_Text_HankPostBattle_FR::
	.string "Tu m'as battu, mais…\n"
	.string "j'suis plus fort à la pêche!$"

Route12_Text_ElliotIntro_FR::
	.string "Bon, j'ai du pain sur la planche!$"

Route12_Text_ElliotDefeat_FR::
	.string "C'est pas facile…$"

Route12_Text_ElliotPostBattle_FR::
	.string "C'est bon.\n"
	.string "Perdre ne me fait plus peur.$"

Route12_Text_AndrewIntro_FR::
	.string "On ne sait jamais ce que l'on peut\n"
	.string "attraper!$"

Route12_Text_AndrewDefeat_FR::
	.string "Hop, perdu!$"

Route12_Text_AndrewPostBattle_FR::
	.string "J'arrête pas d'attraper des\n"
	.string "MAGICARPE, mais ils sont nuls!$"

Route12_Text_RouteSign_FR::
	.string "ROUTE 12 \n"
	.string "LAVANVILLE au Nord$"

Route12_Text_SportfishingArea_FR::
	.string "ZONE DE PECHE$"

Route12_Text_JesIntro_FR::
	.string "JES: Si je gagne, je demande à\n"
	.string "GIA de m'épouser.$"

Route12_Text_JesDefeat_FR::
	.string "JES: Tu aurais au moins pu faire\n"
	.string "semblant de perdre.$"

Route12_Text_JesPostBattle_FR::
	.string "JES: Oh, GIA, pardonne-moi!$"

Route12_Text_JesNotEnoughMons_FR::
	.string "JES: GIA et moi, on est ensemble\n"
	.string "pour la vie.\p"
	.string "On ne se battra pas avant que\n"
	.string "tu ramènes deux POKéMON.$"

Route12_Text_GiaIntro_FR::
	.string "GIA: JES…\n"
	.string "Si on gagne, je t'épouse!$"

Route12_Text_GiaDefeat_FR::
	.string "GIA: Oh… Mais pourquoi.$"

Route12_Text_GiaPostBattle_FR::
	.string "GIA: JES, t'as fait exprès\n"
	.string "de perdre!$"

Route12_Text_GiaNotEnoughMons_FR::
	.string "GIA: Je ne peux pas me battre\n"
	.string "sans JES!\p"
	.string "Reviens quand tu auras plus\n"
	.string "de POKéMON.$"

