Route12_Text_MonSprawledOutInSlumber_IT::
    .string "Un POKéMON addormentato blocca la\n"
    .string "strada!$"

Text_SnorlaxWokeUp_IT::
    .string "SNORLAX si è svegliato male\n"
    .string "e attacca furioso!$"

Text_SnorlaxReturnedToMountains_IT::
    .string "SNORLAX si calma.\n"
    .string "Sbadiglia e torna sulle montagne!$"

Text_WantToUsePokeFlute_IT::
    .string "Vuoi suonare il POKé FLAUTO?$"

Text_PlayedPokeFlute_IT::
    .string "{PLAYER} suona il POKé FLAUTO.$"

Route12_Text_NedIntro_IT::
    .string "Sì! Ha abboccato!$"

Route12_Text_NedDefeat_IT::
    .string "È solo un pesciolino!$"

Route12_Text_NedPostBattle_IT::
    .string "Un momento!\n"
    .string "Ho preso qualcosa!$"

Route12_Text_ChipIntro_IT::
    .string "Ci vuole pazienza!\n"
    .string "La pesca richiede tempo!$"

Route12_Text_ChipDefeat_IT::
    .string "Mi è scappato!$"

Route12_Text_ChipPostBattle_IT::
    .string "Con un AMO migliore potrei pescare\n"
    .string "POKéMON migliori!$"

Route12_Text_JustinIntro_IT::
    .string "Hai trovato la PIETRALUNARE?$"

Route12_Text_JustinDefeat_IT::
    .string "Ahi ahi!$"

Route12_Text_JustinPostBattle_IT::
    .string "Avrei potuto far evolvere i miei\n"
    .string "POKéMON con la PIETRALUNARE!$"

Route12_Text_LucaIntro_IT::
    .string "L'elettricità è la mia specialità!\p"
    .string "Però non chiedermi niente sui\n"
    .string "POKéMON acquatici!$"

Route12_Text_LucaDefeat_IT::
    .string "Mi hai staccato la spina!$"

Route12_Text_LucaPostBattle_IT::
    .string "L'acqua conduce elettricità!\n"
    .string "Prendi dei POKéMON di mare!$"

Route12_Text_HankIntro_IT::
    .string "Mi chiamano il PESCATORE PAZZO!\n"
    .string "Hai paura?$"

Route12_Text_HankDefeat_IT::
    .string "È troppo per me!$"

Route12_Text_HankPostBattle_IT::
    .string "Mi batti in fatto di POKéMON, ma\n"
    .string "sono un bravo pescatore!$"

Route12_Text_ElliotIntro_IT::
    .string "Preferirei lavorare!$"

Route12_Text_ElliotDefeat_IT::
    .string "Non è facile…$"

Route12_Text_ElliotPostBattle_IT::
    .string "Va bene.\n"
    .string "Non mi importa più di perdere.$"

Route12_Text_AndrewIntro_IT::
    .string "Non si sa mai cosa può abboccare!$"

Route12_Text_AndrewDefeat_IT::
    .string "Ho perso! Perso!$"

Route12_Text_AndrewPostBattle_IT::
    .string "Abboccano un sacco di MAGIKARP,\n"
    .string "ma sono debolissimi!$"

Route12_Text_RouteSign_IT::
    .string "PERCORSO 12\n"
    .string "LAVANDONIA a nord$"

Route12_Text_SportfishingArea_IT::
    .string "PESCA SPORTIVA$"

Route12_Text_JesIntro_IT::
    .string "JES: Se vinco, chiedo a GIA\n"
    .string "di sposarmi.$"

Route12_Text_JesDefeat_IT::
    .string "JES: Vedi, così hai rovinato il\n"
    .string "mio sogno romantico!$"

Route12_Text_JesPostBattle_IT::
    .string "JES: GIA, amore mio, perdonami!$"

Route12_Text_JesNotEnoughMons_IT::
    .string "JES: Io e GIA lottiamo solo in\n"
    .string "squadra.\p"
    .string "Se non hai almeno due POKéMON,\n"
    .string "non possiamo sfidarti.$"

Route12_Text_GiaIntro_IT::
    .string "GIA: JES, se vinciamo, ci sposiamo!\n"
    .string "Pensi che sia troppo precipitosa?$"

Route12_Text_GiaDefeat_IT::
    .string "GIA: Perché?$"

Route12_Text_GiaPostBattle_IT::
    .string "GIA: JES, hai rovinato tutto!\n"
    .string "Non ti sposerò mai!$"

Route12_Text_GiaNotEnoughMons_IT::
    .string "GIA: Non posso lottare senza il\n"
    .string "mio JES!\p"
    .string "Torna con almeno due POKéMON.$"

