SaffronCity_Gym_Text_SabrinaIntro_IT::
    .string "Ho avuto la visione del tuo arrivo.\p"
    .string "Già da bambina avevo poteri\n"
    .string "paranormali!\p"
    .string "Tutto è iniziato quando ho imparato\n"
    .string "a piegare i cucchiai col pensiero.\p"
    .string "Odio lottare ma se vuoi ti mostrerò\n"
    .string "i miei poteri!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat_IT::
    .string "Non ci credo!\n"
    .string "Ma non nego la disfatta.\p"
    .string "Non mi sono data molto da fare per\n"
    .string "vincere!\p"
    .string "Ti conferisco la MEDAGLIA PALUDE!$"

SaffronCity_Gym_Text_SabrinaPostBattle_IT::
    .string "Tutti hanno poteri paranormali, ma\n"
    .string "non lo sanno!$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis_IT::
    .string "Con la MEDAGLIA PALUDE, tutti i\n"
    .string "POKéMON fino al livello 70 ti\l"
    .string "obbediranno!\p"
    .string "Quelli più forti ignoreranno gli\n"
    .string "ordini in battaglia!\p"
    .string "Non far salire troppo il livello dei\n"
    .string "tuoi POKéMON prima di avere\l"
    .string "le medaglie adeguate!\p"
    .string "Aspetta, prendi questa MT!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina_IT::
    .string "{PLAYER} riceve\n"
    .string "la MT04!$"

SaffronCity_Gym_Text_ExplainTM04_IT::
    .string "La MT04 è CALMAMENTE!\p"
    .string "Serve a potenziare la DIF. SPEC. e\n"
    .string "l'ATT. SPEC. dei tuoi POKéMON.$"

SaffronCity_Gym_Text_BagFullOfOtherItems_IT::
    .string "Lo ZAINO è già pieno!$"

SaffronCity_Gym_Text_AmandaIntro_IT::
    .string "SABRINA è più giovane di me, ma la\n"
    .string "rispetto!$"

SaffronCity_Gym_Text_AmandaDefeat_IT::
    .string "Non sono all'altezza!$"

SaffronCity_Gym_Text_AmandaPostBattle_IT::
    .string "In una lotta tra pari vince chi ha\n"
    .string "più volontà!\p"
    .string "Se vuoi battere SABRINA, pensa a\n"
    .string "vincere!$"

SaffronCity_Gym_Text_JohanIntro_IT::
    .string "Temi il nostro potere nascosto?$"

SaffronCity_Gym_Text_JohanDefeat_IT::
    .string "Non l'avevo previsto!$"

SaffronCity_Gym_Text_JohanPostBattle_IT::
    .string "I POKéMON del tipo PSICO temono\n"
    .string "solo i POKéMON di tipo SPETTRO\l"
    .string "e COLEOTTERO.$"

SaffronCity_Gym_Text_StacyIntro_IT::
    .string "I POKéMON tendono ad assomigliare\n"
    .string "ai loro ALLENATORI.\p"
    .string "I tuoi devono essere davvero\n"
    .string "forti!$"

SaffronCity_Gym_Text_StacyDefeat_IT::
    .string "Lo sapevo!$"

SaffronCity_Gym_Text_StacyPostBattle_IT::
    .string "Devo insegnare migliori tecniche\n"
    .string "PSICO ai miei POKéMON!$"

SaffronCity_Gym_Text_TyronIntro_IT::
    .string "Il potere da solo non basta!$"

SaffronCity_Gym_Text_TyronDefeat_IT::
    .string "Non ci credo!$"

SaffronCity_Gym_Text_TyronPostBattle_IT::
    .string "SABRINA ha battuto il MAESTRO di\n"
    .string "KARATE qui accanto!$"

SaffronCity_Gym_Text_TashaIntro_IT::
    .string "Ehi tu, facciamo lottare i nostri\n"
    .string "POKéMON!$"

SaffronCity_Gym_Text_TashaDefeat_IT::
    .string "Ho perso, nonostante i miei sforzi!$"

SaffronCity_Gym_Text_TashaPostBattle_IT::
    .string "Sapevo che sarebbe successo.$"

SaffronCity_Gym_Text_CameronIntro_IT::
    .string "SABRINA è giovane ma è già il\n"
    .string "nostro CAPO!\p"
    .string "Non arriverai a lei facilmente!$"

SaffronCity_Gym_Text_CameronDefeat_IT::
    .string "Mi sono distratto!$"

SaffronCity_Gym_Text_CameronPostBattle_IT::
    .string "A ZAFFERANOPOLI una volta c'erano\n"
    .string "2 PALESTRE.\p"
    .string "Il DOJO KARATE accanto ha perso\n"
    .string "il suo status di PALESTRA dopo che\l"
    .string "li abbiamo sconfitti!$"

SaffronCity_Gym_Text_PrestonIntro_IT::
    .string "La PALESTRA di ZAFFERANOPOLI è\n"
    .string "famosa per il paranormale!\p"
    .string "Vuoi vedere SABRINA! Lo so!$"

SaffronCity_Gym_Text_PrestonDefeat_IT::
    .string "Grrr!$"

SaffronCity_Gym_Text_PrestonPostBattle_IT::
    .string "Ti ho letto il pensiero con la\n"
    .string "telepatia!$"

SaffronCity_Gym_Text_GymGuyAdvice_IT::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "I POKéMON di SABRINA non usano\n"
    .string "la forza fisica, ma poteri\l"
    .string "paranormali!\p"
    .string "I POKéMON di tipo LOTTA sono\n"
    .string "deboli contro quelli tipo PSICO!\p"
    .string "Il potere psichico li sfianca prima\n"
    .string "ancora che possano sferrare\l"
    .string "un pugno!$"

SaffronCity_Gym_Text_GymGuyPostVictory_IT::
    .string "Poteri psichici, io?\p"
    .string "Se li avessi, sbancherei le slot\n"
    .string "machine!$"

SaffronCity_Gym_Text_GymStatue_IT::
    .string "CAPOPALESTRA di ZAFFERANOPOLI:\n"
    .string "SABRINA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon_IT::
    .string "CAPOPALESTRA di ZAFFERANOPOLI:\n"
    .string "SABRINA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

