SaffronCity_Gym_Text_SabrinaIntro_FR::
	.string "J'avais prédit ton arrivée!\p"
	.string "J'ai des pouvoirs psychiques depuis\n"
	.string "l'enfance.\p"
	.string "J'ai appris à plier des cuillères\n"
	.string "par la force de l'esprit. C'est\l"
	.string "pas super utile, mais ça en jette!\p"
	.string "Je n'aime pas les combats, mais si\n"
	.string "tu insistes, je vais te montrer mes\l"
	.string "pouvoirs!$"

SaffronCity_Gym_Text_SabrinaDefeat_FR::
	.string "Ha! Je suis surprise!\n"
	.string "Tu as gagné.\p"
	.string "C'est vrai, je n'ai pas fait de mon\n"
	.string "mieux! Tu mérites ta victoire!\p"
	.string "Tu gagnes le BADGE MARAIS!$"

SaffronCity_Gym_Text_SabrinaPostBattle_FR::
	.string "Tout le monde est un peu médium!\n"
	.string "Il faut juste travailler ses dons!$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis_FR::
	.string "Avec le BADGE MARAIS, les POKéMON\n"
	.string "de niveau 70 t'obéiront!\p"
	.string "Les POKéMON plus puissants seront\n"
	.string "incontrôlables lors des combats!\p"
	.string "Fais en sorte que tes POKéMON ne\n"
	.string "dépassent pas cette limite!\p"
	.string "Tiens! Prends ça aussi!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina_FR::
	.string "{PLAYER} reçoit la CT04\n"
	.string "de MORGANE.$"

SaffronCity_Gym_Text_ExplainTM04_FR::
	.string "C'est PLENITUDE.\p"
	.string "Avec cette capacité, les POKéMON\n"
	.string "se concentrent et augmentent leur\p"
	.string "ATQ. SPE. et leur DEF. SPE.$"

SaffronCity_Gym_Text_BagFullOfOtherItems_FR::
	.string "Ton inventaire est plein!$"

SaffronCity_Gym_Text_AmandaIntro_FR::
	.string "MORGANE est une petite parvenue!\n"
	.string "Mais je l'aime bien!$"

SaffronCity_Gym_Text_AmandaDefeat_FR::
	.string "Rhhâ!\n"
	.string "J'suis nulle!$"

SaffronCity_Gym_Text_AmandaPostBattle_FR::
	.string "Dans une baston, ce qui est\n"
	.string "important, c'est la volonté de\l"
	.string "gagner!\p"
	.string "Si tu veux gagner face à MORGANE,\n"
	.string "concentre-toi sur la victoire!$"

SaffronCity_Gym_Text_JohanIntro_FR::
	.string "Nos pouvoirs occultes te font\n"
	.string "peur?$"

SaffronCity_Gym_Text_JohanDefeat_FR::
	.string "Nyan!\n"
	.string "T'as pas l'air effrayé!$"

SaffronCity_Gym_Text_JohanPostBattle_FR::
	.string "Les POKéMON PSY craignent les\n"
	.string "INSECTES et les SPECTRES!$"

SaffronCity_Gym_Text_StacyIntro_FR::
	.string "L'aura du maître déteint sur ses\n"
	.string "POKéMON.\p"
	.string "Tes POKéMON doivent être\n"
	.string "forts alors!$"

SaffronCity_Gym_Text_StacyDefeat_FR::
	.string "Argh!\n"
	.string "Je l'savais!$"

SaffronCity_Gym_Text_StacyPostBattle_FR::
	.string "J'ai encore beaucoup à apprendre…\p"
	.string "Je dois maîtriser PSYKO et\n"
	.string "l'enseigner à mes POKéMON.$"

SaffronCity_Gym_Text_TyronIntro_FR::
	.string "Tu comprends hein?\p"
	.string "La puissance seule sans la\n"
	.string "maîtrise ne sert à rien!$"

SaffronCity_Gym_Text_TyronDefeat_FR::
	.string "Huh!\n"
	.string "J'appelle pas ça rien!$"

SaffronCity_Gym_Text_TyronPostBattle_FR::
	.string "MORGANE a pulvérisé le grand\n"
	.string "MAITRE de KARATE!$"

SaffronCity_Gym_Text_TashaIntro_FR::
	.string "Toi… Moi… Nos POKéMON…\n"
	.string "FIGHT!$"

SaffronCity_Gym_Text_TashaDefeat_FR::
	.string "Puff!\n"
	.string "J'ai perdu!$"

SaffronCity_Gym_Text_TashaPostBattle_FR::
	.string "J'avais prévu ce qui s'est passé.$"

SaffronCity_Gym_Text_CameronIntro_FR::
	.string "MORGANE est jeune mais c'est\n"
	.string "aussi notre CHAMPION!\p"
	.string "Tu vas en baver avant\n"
	.string "de l'atteindre!$"

SaffronCity_Gym_Text_CameronDefeat_FR::
	.string "Oups!\n"
	.string "J'ai rien capté!$"

SaffronCity_Gym_Text_CameronPostBattle_FR::
	.string "Il y avait deux ARENES POKéMON à\n"
	.string "SAFRANIA.\p"
	.string "Le DOJO KARATE a perdu son titre\n"
	.string "d'ARENE le jour où nous l'avons\l"
	.string "pulvérisé!\p"
	.string "Il ne pouvait pas y avoir deux\n"
	.string "ARENES ici.$"

SaffronCity_Gym_Text_PrestonIntro_FR::
	.string "Le CHAMPION de l'ARENE POKéMON\n"
	.string "de SAFRANIA est une médium psy!\p"
	.string "Tu veux voir MORGANE, hein?\n"
	.string "Je lis tes pensées, ne mens pas!$"

SaffronCity_Gym_Text_PrestonDefeat_FR::
	.string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle_FR::
	.string "J'ai lu dans ton esprit! C'est pas\n"
	.string "très clair dedans!$"

SaffronCity_Gym_Text_GymGuyAdvice_FR::
	.string "Salut!\n"
	.string "Graine de CHAMPION!\p"
	.string "Les POKéMON de MORGANE sont\n"
	.string "des POKéMON PSY!\p"
	.string "Les POKéMON COMBAT sont\n"
	.string "désavantagés!\p"
	.string "Ils deviennent dingues avant de\n"
	.string "pouvoir porter un coup!$"

SaffronCity_Gym_Text_GymGuyPostVictory_FR::
	.string "Pouvoirs psy? Hmmm…\n"
	.string "Si j'en avais, je gagnerais!$"

SaffronCity_Gym_Text_GymStatue_FR::
	.string "ARENE POKéMON de SAFRANIA\n"
	.string "CHAMPION: MORGANE\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon_FR::
	.string "ARENE POKéMON de SAFRANIA\n"
	.string "CHAMPION: MORGANE\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}, {PLAYER}$"

