PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy_DE::
	.string "Ein zwielichtiger, alter Mann hat\n"
	.string "mir dieses seltsame PKMN angedreht!\p"
	.string "Es ist vollkommen schwach und hat\n"
	.string "500¥ gekostet!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently_DE::
	.string "Wenn man seine POKéMON eifrig\n"
	.string "trainiert, können selbst schwächere\l"
	.string "POKéMON für Überraschungen gut\l"
	.string "sein!$"

