PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy_FR::
	.string "Un vieil homme m'a vendu cet\n"
	.string "étrange poisson POKéMON!\p"
	.string "Il est super nul et il m'a coûté\n"
	.string "500¥!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently_FR::
	.string "Si tu élèves bien tes POKéMON,\n"
	.string "même les plus faibles, il se\p"
	.string "passera rien que des bonnes\n"
	.string "choses!$"

