PokemonTower_6F_Text_AngelicaIntro_IT::
    .string "Daaammi… il… saaangue…$"

PokemonTower_6F_Text_AngelicaDefeat_IT::
    .string "Grrrr!$"

PokemonTower_6F_Text_AngelicaPostBattle_IT::
    .string "Mi sento anemica e debole…$"

PokemonTower_6F_Text_EmiliaIntro_IT::
    .string "Uuff… Guaa!$"

PokemonTower_6F_Text_EmiliaDefeat_IT::
    .string "È caduto qualcosa!$"

PokemonTower_6F_Text_EmiliaPostBattle_IT::
    .string "Non ho perso i capelli!\n"
    .string "È stato uno spirito maligno!$"

PokemonTower_6F_Text_JenniferIntro_IT::
    .string "Ki… ki… ki… \n"
    .string "ki… ki… ki!$"

PokemonTower_6F_Text_JenniferDefeat_IT::
    .string "Kiii!$"

PokemonTower_6F_Text_JenniferPostBattle_IT::
    .string "Che succede qui?$"

PokemonTower_6F_Text_BeGoneIntruders_IT::
    .string "Via gli intrusi!$"

PokemonTower_6F_Text_GhostWasCubonesMother_IT::
    .string "Lo spettro era l'anima inquieta\n"
    .string "della madre di CUBONE!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed_IT::
    .string "Adesso l'anima è tranquilla.\p"
    .string "È partita per l'aldilà!$"

