PokemonTower_6F_Text_AngelicaIntro_FR::
	.string "Ton… sang…\n"
	.string "Donne…$"

PokemonTower_6F_Text_AngelicaDefeat_FR::
	.string "Grargh!$"

PokemonTower_6F_Text_AngelicaPostBattle_FR::
	.string "Je me sens faible…$"

PokemonTower_6F_Text_EmiliaIntro_FR::
	.string "Urff… Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat_FR::
	.string "Haaa!\n"
	.string "Je me sens mieux!$"

PokemonTower_6F_Text_EmiliaPostBattle_FR::
	.string "J'étais sous l'emprise d'un\n"
	.string "esprit!$"

PokemonTower_6F_Text_JenniferIntro_FR::
	.string "Ke… ke… ke….\n"
	.string "ke… ke… ke!!$"

PokemonTower_6F_Text_JenniferDefeat_FR::
	.string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle_FR::
	.string "Mais qu'est-ce qui se passe ici?$"

PokemonTower_6F_Text_BeGoneIntruders_FR::
	.string "Fuis…\n"
	.string "Misérable…$"

PokemonTower_6F_Text_GhostWasCubonesMother_FR::
	.string "Le SPECTRE était l'esprit damné de\n"
	.string "la mère d'OSSELAIT!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed_FR::
	.string "L'âme de la mère a été apaisée.\p"
	.string "Elle est partie vers l'autre monde!$"

