PokemonTower_6F_Text_AngelicaIntro_DE::
	.string "Ich... brauche...\n"
	.string "Blut...$"

PokemonTower_6F_Text_AngelicaDefeat_DE::
	.string "Wo bin ich?$"

PokemonTower_6F_Text_AngelicaPostBattle_DE::
	.string "Ich fühle mich so blutleer und\n"
	.string "schwach...$"

PokemonTower_6F_Text_EmiliaIntro_DE::
	.string "Buuh... buhuhu!$"

PokemonTower_6F_Text_EmiliaDefeat_DE::
	.string "Irgendetwas hat mich verlassen!$"

PokemonTower_6F_Text_EmiliaPostBattle_DE::
	.string "Es war ein böser Geist, der Besitz\n"
	.string "von mir ergriffen hatte!$"

PokemonTower_6F_Text_JenniferIntro_DE::
	.string "Buh...\n"
	.string "Buh... buhuhu...$"

PokemonTower_6F_Text_JenniferDefeat_DE::
	.string "Buuh!$"

PokemonTower_6F_Text_JenniferPostBattle_DE::
	.string "Was geht hier vor?$"

PokemonTower_6F_Text_BeGoneIntruders_DE::
	.string "Verschwindet...\n"
	.string "Eindringlinge...$"

PokemonTower_6F_Text_GhostWasCubonesMother_DE::
	.string "Der GEIST war die rastlose Seele\n"
	.string "der Mutter eines TRAGOSSO!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed_DE::
	.string "Ihre Seele hat Frieden gefunden.\p"
	.string "Sie ist in das Jenseits\n"
	.string "eingekehrt...$"

