PokemonTower_6F_Text_AngelicaIntro_ES::
    .string "Da... me...\n"
    .string "tu... ser...$"

PokemonTower_6F_Text_AngelicaDefeat_ES::
    .string "¡Grrr!$"

PokemonTower_6F_Text_AngelicaPostBattle_ES::
    .string "Me siento anémica y débil...$"

PokemonTower_6F_Text_EmiliaIntro_ES::
    .string "Uuff...\n"
    .string "¡Guaa!$"

PokemonTower_6F_Text_EmiliaDefeat_ES::
    .string "¡Algo se ha caído!$"

PokemonTower_6F_Text_EmiliaPostBattle_ES::
    .string "¡No me lo creo!\n"
    .string "¡Era un malvado espíritu!$"

PokemonTower_6F_Text_JenniferIntro_ES::
    .string "¡¡¡Ki...ki...\n"
    .string "ki...ki...ki!!!$"

PokemonTower_6F_Text_JenniferDefeat_ES::
    .string "¡Kiii!$"

PokemonTower_6F_Text_JenniferPostBattle_ES::
    .string "¿Qué está pasando aquí?$"

PokemonTower_6F_Text_BeGoneIntruders_ES::
    .string "Fuera...\n"
    .string "Intrusos...$"

PokemonTower_6F_Text_GhostWasCubonesMother_ES::
    .string "¡Ese GHOST era el inquieto\n"
    .string "espíritu de la madre de CUBONE!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed_ES::
    .string "El espíritu de la madre descansa\n"
    .string "tranquilo.\p"
    .string "¡Y ha partido al más allá!$"
