VermilionCity_Mart_Text_TeamRocketAreWickedPeople_DE::
	.string "Es gibt böse Menschen, die POKéMON\n"
	.string "für Verbrechen missbrauchen.\p"
	.string "Das TEAM ROCKET macht mit seltenen\n"
	.string "POKéMON Geschäfte.\p"
	.string "Die POKéMON, die ihrer Meinung nach\n"
	.string "nicht selten genug sind, werden von\l"
	.string "ihnen ausgesetzt.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer_DE::
	.string "POKéMON können gut oder böse sein.\n"
	.string "Das hängt ganz von ihrem TRAINER\l"
	.string "ab!$"

