VermilionCity_Mart_Text_TeamRocketAreWickedPeople_ES::
    .string "Hay gente mala que utiliza a los\n"
    .string "POKéMON para cometer sus actos\l"
    .string "delictivos.\p"
    .string "El TEAM ROCKET trafica con\n"
    .string "POKéMON raros.\p"
    .string "Y prescinde de aquellos POKéMON\n"
    .string "que no son muy populares o útiles.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer_ES::
    .string "Creo que los POKéMON pueden ser\n"
    .string "buenos o malos. Todo depende del\l"
    .string "ENTRENADOR.$"
