VermilionCity_Mart_Text_TeamRocketAreWickedPeople_FR::
	.string "Il y en a, des très méchants, qui\n"
	.string "utilisent les POKéMON pour\l"
	.string "des actes criminels.\p"
	.string "La TEAM ROCKET fait du trafic de\n"
	.string "POKéMON rares.\p"
	.string "Ils abandonnent sur le bord de la\n"
	.string "route les POKéMON trop faibles!\p"
	.string "Ouais, ils sont comme ça dans\n"
	.string "la TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer_FR::
	.string "Les POKéMON peuvent être gentils\n"
	.string "ou méchants, cela dépend de leur\l"
	.string "DRESSEUR.$"

