Text_ExplosionTeach_FR::
	.string "Tu imagines? Si ce volcan\n"
	.string "se mettait en éruption?\p"
	.string "Ça serait la fin de tout. C'est\n"
	.string "terrible, non?\p"
	.string "Pendant qu'on tremble de peur,\n"
	.string "tu veux apprendre EXPLOSION?$"

Text_ExplosionDeclined_FR::
	.string "Tu as raison, ça fait trop peur.$"

Text_ExplosionWhichMon_FR::
	.string "T'as vraiment du courage!\p"
	.string "A quel POKéMON enseigner\n"
	.string "EXPLOSION?$"

Text_ExplosionTaught_FR::
	.string "Utiliser EXPLOSION sur ce volcan,\n"
	.string "ça serait…\p"
	.string "Je préfère ne pas y penser!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP_FR::
	.string "こ　この　かざんが\n"
	.string "もし　だいばくはつ　したら\l"
	.string "お　おれら　ひとたまりも\l"
	.string "ないなあ　‥ブルブル！\p"
	.string "こ　こわい　ついでに\n"
	.string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP_FR::
	.string "や　やっぱ　こわいもんな\n"
	.string "ブルブル$"

Text_ExplosionWhichMonJP_FR::
	.string "つ　つよきだね！\n"
	.string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP_FR::
	.string "かざんで　だいばくはつを‥\n"
	.string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere_FR::
	.string "Par ici.\n"
	.string "On va essayer de creuser par là.\p"
	.string "Le trésor dont les ADMINS étaient\n"
	.string "en train de parler doit être ici.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost_FR::
	.string "Qu'est-ce que…\n"
	.string "Tu es sur le chemin, dégage!$"

MtEmber_Exterior_Text_PunchedThroughAtLast_FR::
	.string "Ouf, une bonne chose de faite.\n"
	.string "A nous les trésors maintenant!$"

MtEmber_Exterior_Text_WhatsPasswordAgain_FR::
	.string "On ramène tous les trésors qu'on\n"
	.string "trouve à l'ENTREPOT, bien compris?\p"
	.string "…Oh, et pour les mots de\n"
	.string "passe? Ceux de l'ENTREPOT…$"

MtEmber_Exterior_Text_FirstPasswordGoldeen_FR::
	.string "Quoi, tu as oublié les deux mots\n"
	.string "de passe? Imbécile!\p"
	.string "Le premier c'est:\n"
	.string "“ICI, GIRAFARIG, ICI”.\p"
	.string "Et le deuxième…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn_FR::
	.string "Hey!\n"
	.string "Quelqu'un nous écoute!$"

MtEmber_Exterior_Text_Grunt1Intro_FR::
	.string "Tu étais en train de nous\n"
	.string "espionner, hein?$"

MtEmber_Exterior_Text_Grunt1Defeat_FR::
	.string "Hein, quoi?$"

MtEmber_Exterior_Text_Grunt1PostBattle_FR::
	.string "Je comprends pas, comment t'as fait\n"
	.string "pour me battre?$"

MtEmber_Exterior_Text_Grunt2Intro_FR::
	.string "Tu veux nos trésors, hein?\n"
	.string "Ne compte pas là-dessus.$"

MtEmber_Exterior_Text_Grunt2Defeat_FR::
	.string "Attends!\n"
	.string "Mais comment…$"

MtEmber_Exterior_Text_Grunt2PostBattle_FR::
	.string "Je vais développer une amnésie\n"
	.string "sélective et oublier ce combat.$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere_FR::
	.string "Quelle déculottée…\n"
	.string "On doit se replier.\p"
	.string "Toi, n'essaie même pas d'entrer\n"
	.string "là-dedans!\p"
	.string "Si tu tiens à ta peau, je te\n"
	.string "conseille de rester dehors!$"

MtEmber_Exterior_Text_LoganIntro_FR::
	.string "Un volcan actif est un volcan en\n"
	.string "éruption, ou sur le point de l'être.$"

MtEmber_Exterior_Text_LoganDefeat_FR::
	.string "Pfiuu… C'était chaud!\n"
	.string "Je suis tout en sueur.$"

MtEmber_Exterior_Text_LoganPostBattle_FR::
	.string "Il paraît qu'il y a plus de 1 500\n"
	.string "volcans actifs dans le monde.\p"
	.string "Rien que d'y penser, ça me\n"
	.string "donne chaud.$"

MtEmber_Exterior_Text_BethIntro_FR::
	.string "Tu sais comment les grottes se\n"
	.string "forment à l'intérieur des volcans?$"

MtEmber_Exterior_Text_BethDefeat_FR::
	.string "Aaaah!\n"
	.string "C'est pas normal d'être aussi fort!$"

MtEmber_Exterior_Text_BethPostBattle_FR::
	.string "Quand la lave à la surface du\n"
	.string "magma se durcit mais que l'intérieur\p"
	.string "continue de s'écouler,\n"
	.string "cela crée des grottes volcaniques.$"

MtEmber_Exterior_Text_JocelynIntro_FR::
	.string "Je me suis entraînée pour pouvoir\n"
	.string "supporter la défaite…\p"
	.string "En fait, je me suis surtout durcie\n"
	.string "physiquement. A l'attaque!$"

MtEmber_Exterior_Text_JocelynDefeat_FR::
	.string "J'ai dû en faire trop…$"

MtEmber_Exterior_Text_JocelynPostBattle_FR::
	.string "La façon dont tu m'as éliminée…\p"
	.string "Ça me rappelle quand j'ai cassé\n"
	.string "avec mon copain!$"

