Text_ExplosionTeach_ES::
    .string "¿Te imaginas que este volcán\n"
    .string "entrara en erupción?\p"
    .string "Sería nuestro fin. ¡Qué horror!\p"
    .string "A todo esto, ¿quieres aprender\n"
    .string "EXPLOSIÓN?$"

Text_ExplosionDeclined_ES::
    .string "Te entiendo, sólo oír el nombre\n"
    .string "pone los pelos de punta.$"

Text_ExplosionWhichMon_ES::
    .string "¡Sí, señor!\p"
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe EXPLOSIÓN?$"

Text_ExplosionTaught_ES::
    .string "Imagínate lo que tiene que ser\n"
    .string "usar EXPLOSIÓN en este volcán...\p"
    .string "¡Lo pienso y no sé lo que me\n"
    .string "entra!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP_ES::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP_ES::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP_ES::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP_ES::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere_ES::
    .string "Aquí, aquí.\n"
    .string "Vamos a intentar cavar aquí.\p"
    .string "Yo creo que el tesoro del que\n"
    .string "hablaban los ADMINISTRADORES\l"
    .string "está aquí.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost_ES::
    .string "Pero...\n¿Te quieres quitar de aquí?$"

MtEmber_Exterior_Text_PunchedThroughAtLast_ES::
    .string "¡Por fin lo hemos conseguido!\n¡A por el tesoro!$"

MtEmber_Exterior_Text_WhatsPasswordAgain_ES::
    .string "Cosa que encontremos, cosa que\n"
    .string "llevamos al ALMACÉN, ¿eh?\p"
    .string "Eh... ¿y cuáles eran las\n"
    .string "contraseñas?\l"
    .string "Me refiero a las del ALMACÉN...$"

MtEmber_Exterior_Text_FirstPasswordGoldeen_ES::
    .string "¿No te acuerdas de la contraseña?\n"
    .string "Bueno, en realidad son dos.\p"
    .string "La primera es “ARON ama\n"
    .string "a NORA”.\p"
    .string "Y la segunda...$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn_ES::
    .string "¡Eh, que por aquí se están\n"
    .string "quedando con la copla! ¡Cotilla!$"

MtEmber_Exterior_Text_Grunt1Intro_ES::
    .string "Has estado espiándonos, ¿eh?$"

MtEmber_Exterior_Text_Grunt1Defeat_ES::
    .string "¿Qué ha pasado?$"

MtEmber_Exterior_Text_Grunt1PostBattle_ES::
    .string "¿Por qué me has ganado?$"

MtEmber_Exterior_Text_Grunt2Intro_ES::
    .string "¿Te crees que vas a pillar cacho\n"
    .string "de nuestro tesoro? ¡Ni lo sueñes!$"

MtEmber_Exterior_Text_Grunt2Defeat_ES::
    .string "¡Ahora quien está soñando soy yo!$"

MtEmber_Exterior_Text_Grunt2PostBattle_ES::
    .string "Hazme un favorcito, olvídate de lo\n"
    .string "que has oído, anda.$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere_ES::
    .string "¡Menudo revés!...\n"
    .string "¡Vámonos con el resto!\p"
    .string "¡Tú, no te atrevas a entrar!\p"
    .string "¡Te lo digo por tu bien!\n"
    .string "¡Ni te lo plantees!$"

MtEmber_Exterior_Text_LoganIntro_ES::
    .string "Se dice que un volcán está activo,\n"
    .string "cuando entra en erupción o está\l"
    .string "a punto.$"

MtEmber_Exterior_Text_LoganDefeat_ES::
    .string "Guau... ¡qué pasada!\n"
    .string "¡Me ha entrado un calor!$"

MtEmber_Exterior_Text_LoganPostBattle_ES::
    .string "Dicen que hay unos 1.500 volcanes\n"
    .string "activos en todo el mundo.\p"
    .string "Cada vez que lo pienso, ¡me entra\n"
    .string "una cosa!$"

MtEmber_Exterior_Text_BethIntro_ES::
    .string "¿Sabes cómo se forman las cuevas\n"
    .string "en el interior de los volcanes?$"

MtEmber_Exterior_Text_BethDefeat_ES::
    .string "¡Aaaah!\n¡Eres increíble!$"

MtEmber_Exterior_Text_BethPostBattle_ES::
    .string "Cuando la lava de la superficie se\n"
    .string "solidifica, aún puede quedar magma\l"
    .string "por salir.\p"
    .string "Y son los conductos que abre\n"
    .string "en su camino al exterior, los que\l"
    .string "pasan a ser las cuevas.$"

MtEmber_Exterior_Text_JocelynIntro_ES::
    .string "He estado entrenándome para\n"
    .string "recuperar mi fuerza interior...\p"
    .string "¡Y lo que sin duda he conseguido\n"
    .string "ha sido ponerme en forma!$"

MtEmber_Exterior_Text_JocelynDefeat_ES::
    .string "Creo que he exagerado...$"

MtEmber_Exterior_Text_JocelynPostBattle_ES::
    .string "Luchando me recuerdas a mi antiguo\n"
    .string "noviete...$"
