Text_ExplosionTeach_DE::
	.string "Stell dir vor, dieser Vulkan würde\n"
	.string "ausbrechen!\p"
	.string "Die Eruption wäre unser Ende! Ist\n"
	.string "das nicht erschreckend?\p"
	.string "Während uns die Knie schlottern,\n"
	.string "könnte ich einem POKéMON\l"
	.string "EXPLOSION lehren!$"

Text_ExplosionDeclined_DE::
	.string "Ja, genau, du hast Recht!\n"
	.string "Das ist zu erschreckend!$"

Text_ExplosionWhichMon_DE::
	.string "Du bist unheimlich tapfer!\p"
	.string "Welches POKéMON soll\n"
	.string "EXPLOSION erlernen?$"

Text_ExplosionTaught_DE::
	.string "EXPLOSION auf diesem Vulkan\n"
	.string "einzusetzen…\p"
	.string "Was für ein aufreibender\n"
	.string "Nervenkitzel!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP_DE::
	.string "こ　この　かざんが\n"
	.string "もし　だいばくはつ　したら\l"
	.string "お　おれら　ひとたまりも\l"
	.string "ないなあ　‥ブルブル！\p"
	.string "こ　こわい　ついでに\n"
	.string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP_DE::
	.string "や　やっぱ　こわいもんな\n"
	.string "ブルブル$"

Text_ExplosionWhichMonJP_DE::
	.string "つ　つよきだね！\n"
	.string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP_DE::
	.string "かざんで　だいばくはつを‥\n"
	.string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere_DE::
	.string "Hier drüben!\n"
	.string "Wir versuchen, hier zu graben.\p"
	.string "Der Schatz, über den die VORS.\n"
	.string "reden, muss hier irgendwo sein.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost_DE::
	.string "Was zur…?\n"
	.string "Du bist im Weg! Verschwinde!$"

MtEmber_Exterior_Text_PunchedThroughAtLast_DE::
	.string "Wow! Endlich durch! Auf zur\n"
	.string "Schatzsuche!$"

MtEmber_Exterior_Text_WhatsPasswordAgain_DE::
	.string "Wir bringen jeden Schatz, den wir\n"
	.string "finden, ins LAGER, verstanden?\p"
	.string "… und wie lauten die Passwörter?\n"
	.string "Für das LAGER, natürlich!$"

MtEmber_Exterior_Text_FirstPasswordGoldeen_DE::
	.string "Wie?!? Du hast das Passwort \n"
	.string "vergessen? Eigentlich sind es zwei!\p"
	.string "Das erste lautet “ARBOK Kobra”.\p"
	.string "Und das zweite ist…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn_DE::
	.string "Heh!\n"
	.string "Das Balg belauscht uns!$"

MtEmber_Exterior_Text_Grunt1Intro_DE::
	.string "Du hast uns bespitzelt, gib es zu!$"

MtEmber_Exterior_Text_Grunt1Defeat_DE::
	.string "Häh, wie?$"

MtEmber_Exterior_Text_Grunt1PostBattle_DE::
	.string "Warum musstest du gewinnen?$"

MtEmber_Exterior_Text_Grunt2Intro_DE::
	.string "Du willst wohl etwas von unserem\n"
	.string "Schatz? Das kannst du vergessen!$"

MtEmber_Exterior_Text_Grunt2Defeat_DE::
	.string "Warte!\n"
	.string "Wie konnte das geschehen?$"

MtEmber_Exterior_Text_Grunt2PostBattle_DE::
	.string "Fröne der Amnesie und vergiss,\n"
	.string "was du gehört hast!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere_DE::
	.string "Welch Rückschlag…\n"
	.string "Wir müssen uns neu gruppieren.\p"
	.string "Du! Denk nicht einmal daran,\n"
	.string "einzutreten!\p"
	.string "Wenn du weißt, was gut für dich\n"
	.string "ist, denk nicht einmal daran!$"

MtEmber_Exterior_Text_LoganIntro_DE::
	.string "Ein Vulkan gilt als aktiv, wenn er\n"
	.string "ausbricht oder kurz vor dem\l"
	.string "Ausbruch steht.$"

MtEmber_Exterior_Text_LoganDefeat_DE::
	.string "Puh… das war heiß!\n"
	.string "Ich hatte einen Schweißausbruch!$"

MtEmber_Exterior_Text_LoganPostBattle_DE::
	.string "Es soll mehr als 1500 aktive\n"
	.string "Vulkane in der Welt geben.\p"
	.string "Allein beim Gedanken daran wird\n"
	.string "mir heiß und mulmig!$"

MtEmber_Exterior_Text_BethIntro_DE::
	.string "Weißt du, wie in Vulkanen Höhlen\n"
	.string "entstehen?$"

MtEmber_Exterior_Text_BethDefeat_DE::
	.string "AUA!\n"
	.string "Du bist erschreckend gut!$"

MtEmber_Exterior_Text_BethPostBattle_DE::
	.string "Wenn die Lava an der Oberfläche\n"
	.string "des Magmas erhärtet und das Magma\l"
	.string "darunter herausfließt, entsteht\l"
	.string "eine Höhle.$"

MtEmber_Exterior_Text_JocelynIntro_DE::
	.string "Ich habe hart trainiert, damit\n"
	.string "ich meinen Liebeskummer\l"
	.string "überwinde…\l"
	.string "Es hat mich zumindest körperlich\l"
	.string "gestärkt! Hey-Ho!$"

MtEmber_Exterior_Text_JocelynDefeat_DE::
	.string "Ich denke, ich habe es\n"
	.string "übertrieben…$"

MtEmber_Exterior_Text_JocelynPostBattle_DE::
	.string "Deine Art zu kämpfen erinnert mich\n"
	.string "an den Kerl, der mich loswerden\l"
	.string "wollte.$"

