SSAnne_B1F_Room4_Text_LeonardIntro_ES::
    .string "¡Ya sabes lo que dicen sobre\n"
    .string "los marineros y las peleas!$"

SSAnne_B1F_Room4_Text_LeonardDefeat_ES::
    .string "¡Has peleado muy bien, sí, sí!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle_ES::
    .string "¡Ajá!\n"
    .string "¿Quieres unirte a los marineros?$"

SSAnne_B1F_Room4_Text_DuncanIntro_ES::
    .string "¡Está en juego mi fama de\n"
    .string "marinero!$"

SSAnne_B1F_Room4_Text_DuncanDefeat_ES::
    .string "¡Menuda paliza!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle_ES::
    .string "¿Viste al GURÚ de los PESCADORES\n"
    .string "en CIUDAD CARMÍN?$"
