SSAnne_B1F_Room4_Text_LeonardIntro_DE::
	.string "Du weißt, wir Seeleute lieben es zu\n"
	.string "kämpfen!$"

SSAnne_B1F_Room4_Text_LeonardDefeat_DE::
	.string "JA!\n"
	.string "Was für ein Kampf!!!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle_DE::
	.string "Willst du zur See fahren?$"

SSAnne_B1F_Room4_Text_DuncanIntro_DE::
	.string "Mein Ruf als Seebär steht auf dem\n"
	.string "Spiel!!!$"

SSAnne_B1F_Room4_Text_DuncanDefeat_DE::
	.string "Kiel unter!\n"
	.string "Das war es für mich!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle_DE::
	.string "Hast du schon den PROFI-ANGLER in\n"
	.string "ORANIA CITY besucht?$"

