SixIsland_Text_IslandSign_FR::
	.string "ILE 6\n"
	.string "Lîle de la sagesse$"

SixIsland_Text_ThatWayToWaterPathRuinValley_FR::
	.string "En allant par là, tu arriveras\n"
	.string "à AGUALCANAL.\p"
	.string "Continue dessus si tu veux\n"
	.string "voir la VALLEE RUINE.$"

SixIsland_Text_SkyAtNightIsFantastic_FR::
	.string "Quand on est aussi loin des\n"
	.string "lumières de la ville, la nuit,\p"
	.string "on peut voir toutes les étoiles\n"
	.string "dans le ciel.$"

