SixIsland_Text_IslandSign_DE::
	.string "EILAND SECHS\n"
	.string "Schicksalsinsel der Alten Weisheit$"

SixIsland_Text_ThatWayToWaterPathRuinValley_DE::
	.string "Laufe hier weiter und du erreichst\n"
	.string "den WASSERWEG.\p"
	.string "Wenn du dann noch weiter läufst,\n"
	.string "erreichst du das RUINENTAL.$"

SixIsland_Text_SkyAtNightIsFantastic_DE::
	.string "Wenn man so weit weg von der\n"
	.string "Stadt ist, sieht der Himmel\l"
	.string "fantastisch aus.$"

