SixIsland_Text_IslandSign_IT::
    .string "SESTISOLA\n"
    .string "L'isola della saggezza veneranda$"

SixIsland_Text_ThatWayToWaterPathRuinValley_IT::
    .string "Se prosegui in questa direzione\n"
    .string "arrivi alla VIA MARINA.\p"
    .string "La VIA MARINA conduce alla\n"
    .string "VALLE ANTICA!$"

SixIsland_Text_SkyAtNightIsFantastic_IT::
    .string "Così lontano dalle città, il cielo\n"
    .string "stellato è meraviglioso!$"

