SixIsland_Text_IslandSign_ES::
    .string "ISLA EXTA\n"
    .string "Isla de la fortuna y el saber.$"

SixIsland_Text_ThatWayToWaterPathRuinValley_ES::
    .string "Si sigues por aquí, llegarás a la\n"
    .string "VÍA ACUÁTICA.\p"
    .string "Cuando alcances la VÍA,\n"
    .string "ve hacia el sur si quieres ir\l"
    .string "al VALLE de las RUINAS.$"

SixIsland_Text_SkyAtNightIsFantastic_ES::
    .string "Al estar tan lejos de las ciudades,\n"
    .string "por la noche el cielo se ve muy\l"
    .string "despejado.$"
