Text_RockSlideTeach_ES::
    .string "En montañas como ésta, hay peligro\n"
    .string "de desprendimientos.\p"
    .string "Imagínate qué horror que empiecen\n"
    .string "a caerte rocas encima.\p"
    .string "¡Aaaaaaaaaaaaaaah!\n"
    .string "Un horror, vamos.\p"
    .string "¿No te da miedo?\n"
    .string "¿Quieres aprender AVALANCHA?$"

Text_RockSlideDeclined_ES::
    .string "Te da miedo, no lo niegues.$"

Text_RockSlideWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe AVALANCHA?$"

Text_RockSlideTaught_ES::
    .string "Yo no lo usaría en un túnel...$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow_ES::
    .string "¡Las ROCAS pueden cambiar\n"
    .string "el flujo del agua!$"

SeafoamIslands_B4F_Text_DangerFastCurrent_ES::
    .string "¡PELIGRO!\n"
    .string "¡Rápidos!$"
