Text_RockSlideTeach_IT::
    .string "Su queste montagne c'è sempre il\n"
    .string "rischio che cada qualche roccia.\p"
    .string "Te lo immagini? Massi enormi che\n"
    .string "rotolano verso di te?!?\p"
    .string "Come? Non hai paura?\p"
    .string "Allora, non ti piacerebbe provare\n"
    .string "ad usare FRANA?$"

Text_RockSlideDeclined_IT::
    .string "Ah, allora un po' di paura ce\n"
    .string "l'hai, in fin dei conti.$"

Text_RockSlideWhichMon_IT::
    .string "A quale POKéMON vuoi che insegni\n"
    .string "FRANA?$"

Text_RockSlideTaught_IT::
    .string "Usarla qui dentro dev'essere\n"
    .string "terrorizzante.$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow_IT::
    .string "I sassi possono mutare il flusso\n"
    .string "dell'acqua!$"

SeafoamIslands_B4F_Text_DangerFastCurrent_IT::
    .string "PERICOLO!\n"
    .string "Rapide!$"

