CeladonCity_Condominiums_3F_Text_ImTheProgrammer_IT::
    .string "Io?\n"
    .string "Sono il programmatore!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist_IT::
    .string "Sono il grafico che ti ha\n"
    .string "disegnato!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory_IT::
    .string "Ho scritto la storia!\n"
    .string "Non è forte ERIKA?\p"
    .string "Mi piace molto anche MISTY!\n"
    .string "Per non parlare di SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex_IT::
    .string "Va bene?\p"
    .string "Ho progettato questo gioco!\p"
    .string "Completare il tuo POKéDEX è\n"
    .string "difficile, ma non arrenderti!\p"
    .string "Quando hai finito vieni a dirmelo!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations_IT::
    .string "Wow! Eccellente!\n"
    .string "Hai completato il tuo POKéDEX!\l"
    .string "Congratulazioni!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram_IT::
    .string "È il programma del gioco! Non lo\n"
    .string "toccare, potrebbe esplodere!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame_IT::
    .string "Qualcuno sta giocando invece di\n"
    .string "lavorare!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding_IT::
    .string "È il copione!\n"
    .string "Ma non leggere il finale!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom_IT::
    .string "GAME FREAK - Sala sviluppo$"

