CeladonCity_Condominiums_3F_Text_ImTheProgrammer_DE::
	.string "Ich?\n"
	.string "Ich bin der Programmierer!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist_DE::
	.string "Ich bin der Grafiker!\n"
	.string "Ich habe dies alles gezeichnet!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory_DE::
	.string "Die Geschichte stammt von mir!\n"
	.string "Ist ERIKA nicht süß?\p"
	.string "Aber MISTY mag ich auch gerne!\n"
	.string "Und nicht zu vergessen, SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex_DE::
	.string "Gefällt dir das Spiel?\p"
	.string "Ich habe das Spiel gestaltet!\p"
	.string "Auch wenn es sehr mühsam ist, den\n"
	.string "POKéDEX zu erstellen: Gib nicht\l"
	.string "auf!\p"
	.string "Zeige ihn mir, wenn er komplett ist!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations_DE::
	.string "Wow! Fantastisch!\n"
	.string "Dein POKéDEX ist vollständig!\l"
	.string "Herzlichen Glückwunsch!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram_DE::
	.string "Der Programmcode! Davon sollte man\n"
	.string "besser die Finger lassen!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame_DE::
	.string "Dort spielt jemand, anstatt zu\n"
	.string "arbeiten!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding_DE::
	.string "Das Drehbuch! Ich schaue mir das\n"
	.string "Ende besser nicht an!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom_DE::
	.string "GAME FREAK Entwicklungs-Abteilung$"

