CeladonCity_Condominiums_3F_Text_ImTheProgrammer_FR::
	.string "Moi?\n"
	.string "J'suis un programmeur!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist_FR::
	.string "Je fais tous les graphismes!\n"
	.string "J'ai même créé ton personnage!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory_FR::
	.string "J'ai écrit l'histoire!\n"
	.string "ERIKA est belle!\p"
	.string "ONDINE aussi, non?\n"
	.string "Et puis MORGANE! Elle est mimi!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex_FR::
	.string "Je suis le concepteur du jeu!\p"
	.string "Remplir ton POKéDEX est difficile,\n"
	.string "hein?\p"
	.string "Complète-le et reviens me voir!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations_FR::
	.string "Woah! Génial!\n"
	.string "Tu as complété ton POKéDEX!\l"
	.string "Félicitations!\l"
	.string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram_FR::
	.string "Le programme du jeu! Si tu y\n"
	.string "touches, tout va planter!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame_FR::
	.string "Quelqu'un joue au lieu de bosser!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding_FR::
	.string "Le script du jeu!\n"
	.string "Surtout ne pas lire la fin!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom_FR::
	.string "GAME FREAK Développement$"

