CeladonCity_Condominiums_3F_Text_ImTheProgrammer_ES::
    .string "¿Yo?\n"
    .string "¡Soy el programador!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist_ES::
    .string "¡Soy el diseñador gráfico!\n"
    .string "¡Yo te dibujé!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory_ES::
    .string "¡Yo escribí la historia!\n"
    .string "¿A que es guapa ERIKA?\p"
    .string "¡También me gusta mucho MISTY!\n"
    .string "¡Y también me gusta SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex_ES::
    .string "¿Sabes?\p"
    .string "¡Soy el diseñador del juego!\p"
    .string "¡Completar tu POKéDEX es difícil,\n"
    .string "pero no te rindas!\p"
    .string "¡Cuando termines ven a decírmelo!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations_ES::
    .string "¡Uauu! ¡Genial!\n"
    .string "¡Has completado tu POKéDEX!\l"
    .string "¡Enhorabuena!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram_ES::
    .string "¡Es el programa del juego!\n"
    .string "¡No lo toques, no vaya a ser que\l"
    .string "se estropee!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame_ES::
    .string "¡Alguien está jugando en lugar\n"
    .string "de trabajar!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding_ES::
    .string "¡Es el guión del juego!\n"
    .string "¡No leas el final!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom_ES::
    .string "Sala de desarrollo de GAME FREAK$"
