CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers_FR::
	.string "Les accélérateurs de POKéMON sont\n"
	.string "en vente ici.\p"
	.string "PV PLUS augmente les PV\n"
	.string "d'un POKéMON.\p"
	.string "Le CALCIUM augmente les capacités\n"
	.string "SPECIALES.\p"
	.string "Le ZINC booste la DEF. SPE. d'un\n"
	.string "POKéMON.\p"
	.string "Le CARBONE augmente la VITESSE.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers_FR::
	.string "J'veux acheter un accélérateur de\n"
	.string "POKéMON!\p"
	.string "Une PROTEINE augmentera l'ATTAQUE.\p"
	.string "Le FER augmente la DEFENSE.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore_FR::
	.string "4ème: MEDICAMENTS$"

