CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers_DE::
	.string "Nur hier kannst du leistungs-\n"
	.string "fördernde Mittel für deine POKéMON\l"
	.string "kaufen!\p"
	.string "KP-PLUS hebt die Basis-KP eines\n"
	.string "POKéMON.\p"
	.string "KALZIUM steigert die Stärke von\n"
	.string "SPEZIAL-ATTACKEN!\p"
	.string "ZINK hebt den Basis-Wert der\n"
	.string "SP. VER. eines POKéMON.\p"
	.string "CARBON erhöht die INITIATIVE.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers_DE::
	.string "Ich bin wegen der leistungs-\n"
	.string "fördernden Mittel für POKéMON hier.\p"
	.string "PROTEIN steigert die ANGRIFFS-\n"
	.string "STÄRKE.\p"
	.string "EISEN stärkt die ABWEHR!$"

CeladonCity_DepartmentStore_5F_Text_Drugstore_DE::
	.string "4S: DROGERIE$"

