CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers_IT::
    .string "Gli integratori di abilità dei\n"
    .string "POKéMON si vendono solo qui!\p"
    .string "PS-SU aumenta i PS massimi\n"
    .string "di un POKéMON!\p"
    .string "Usa il CALCIO per aumentare\n"
    .string "l'ATTACCO SPECIALE!\p"
    .string "Lo ZINCO migliora la DIF. SPEC. di\n"
    .string "un POKéMON!\p"
    .string "Usa il CARBURANTE per aumentare la\n"
    .string "VELOCITÀ.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers_IT::
    .string "Sono qui per gli integratori di\n"
    .string "abilità dei POKéMON!\p"
    .string "Le PROTEINE potenziano l'ATTACCO.\p"
    .string "Il FERRO aumenta la DIFESA!$"

CeladonCity_DepartmentStore_5F_Text_Drugstore_IT::
    .string "4ºP: FARMACIA$"

