Aide_Text_HaventCaughtEnoughMonsForItem_FR::
	.string "Voyons voir…\p"
	.string "Oh! Tu n'as attrapé que {STR_VAR_3}\n"
	.string "sortes de POKéMON!\p"
	.string "Il t'en faut {STR_VAR_1} différents pour\n"
	.string "mériter un {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem_FR::
	.string "Dans ce cas…\p"
	.string "Reviens avec {STR_VAR_1} sortes de POKéMON\n"
	.string "pour obtenir {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem_FR::
	.string "Oh! Tu n'as plus de place pour\n"
	.string "{STR_VAR_2}.$"
