Braille_Text_Up_FR::
	.braille "HAUT$"

Braille_Text_Down_FR::
	.braille "BAS$"

Braille_Text_Right_FR::
	.braille "DROITE$"

Braille_Text_Left_FR::
	.braille "GAUCHE$"

Braille_Text_Cut_FR::
	.braille "COUPE$"

Braille_Text_ABC_FR::
	.braille "ABC$"

Braille_Text_GHI_FR::
	.braille "GHI$"

Braille_Text_MNO_FR::
	.braille "MNO$"

Braille_Text_TUV_FR::
	.braille "TUV$"

Braille_Text_DEF_FR::
	.braille "DEF$"

Braille_Text_JKL_FR::
	.braille "JKL$"

Braille_Text_PQRS_FR::
	.braille "PQRS$"

Braille_Text_WXYZ_FR::
	.braille "WXYZ$"

Braille_Text_Period_FR::
	.braille "*$"

Braille_Text_Comma_FR::
	.braille ",$"

Braille_Text_Everything_FR::
	.braille "TOUT$"

Braille_Text_HasMeaning1_FR::
	.braille "A UN SENS$"

Braille_Text_Existence_FR::
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2_FR::
	.braille "A UN SENS$"

Braille_Text_BeingAlive_FR::
	.braille "ETRE VIVANT$"

Braille_Text_HasMeaning3_FR::
	.braille "A UN SENS$"

Braille_Text_HaveDreams_FR::
	.braille "CROIS EN TOI$"

Braille_Text_UsePower_FR::
	.braille "BATS TOI*$"

Braille_Text_LetTheTwo_FR::
	.braille "LAISSE LES$"

Braille_Text_Glittering_FR::
	.braille "DEUX PIERRES$"

Braille_Text_Stones_FR::
	.braille "BRILLANTES$"

Braille_Text_OneInRed_FR::
	.braille "UNE EN ROUGE$"

Braille_Text_OneInBlue_FR::
	.braille "UNE EN BLEU$"

Braille_Text_ConnectThe_FR::
	.braille "CONNECTER LE$"

Braille_Text_Past_FR::
	.braille "PASSE*$"

Braille_Text_TwoFriends_FR::
	.braille "PARTAGER LA$"

Braille_Text_Sharing_FR::
	.braille "FORCE A DEUX$"

Braille_Text_PowerOpen_FR::
	.braille "AMIS OUVRE$"

Braille_Text_AWindowTo_FR::
	.braille "LA PORTE$"

Braille_Text_ANewWorld_FR::
	.braille "D UN MONDE$"

Braille_Text_ThatGlows_FR::
	.braille "NOUVEAU*$"

Braille_Text_TheNext_FR::
	.braille "LE MONDE$"

Braille_Text_WorldWaits_FR::
	.braille "SUIVANT$"

Braille_Text_ForYou_FR::
	.braille "T ATTEND*$"
