@ Unused
Text_WelcomeTradeCenter_FR::
	.string "Bienvenue au CENTRE TROC\n"
	.string "du CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeColosseum_FR::
	.string "Bienvenue au COLISEE du\n"
	.string "CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule_FR::
	.string "Bienvenue au BLOC TEMPOREL\n"
	.string "du CLUB LINK POKéMON.$"

Text_PleaseComeAgain_FR::
	.string "A la prochaine!$"

@ Unused
Text_HavingDiscountSaleToday_FR::
	.string "Bienvenue!\p"
	.string "Nous avons une promotion\n"
	.string "aujourd'hui!$"

@ Unused
Text_PlayerWhatCanIDoForYou_FR::
	.string "Bienvenue {PLAYER}{KUN}!\p"
	.string "Que puis-je faire pour vous?$"
