@ Unused
Text_WelcomeTradeCenter_FR::
	.string "Bienvenue au CENTRE TROC\n"
	.string "du CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeColosseum_FR::
	.string "Bienvenue au COLISEE du\n"
	.string "CLUB LINK POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule_FR::
	.string "Bienvenue au BLOC TEMPOREL\n"
	.string "du CLUB LINK POKéMON.$"

Text_PleaseComeAgain_FR::
	.string "A la prochaine!$"

@ Unused
Text_HavingDiscountSaleToday_FR::
	.string "Bienvenue!\p"
	.string "Nous avons une promotion\n"
	.string "aujourd'hui!$"

@ Unused
Text_PlayerWhatCanIDoForYou_FR::
	.string "Bienvenue {PLAYER}{KUN}!\p"
	.string "Que puis-je faire pour vous?$"

CableClub_Text_WelcomeWhichCableClubService_FR::
	.string "Bienvenue au CENTRE TROC\n"
	.string "du CLUB LINK POKéMON.\p"
	.string "Lequel de nos services\n"
	.string "souhaiteriez-vous utiliser?$"

CableClub_Text_WhichService_FR::
	.string "Lequel de nos services\n"
	.string "souhaiteriez-vous utiliser?$"

CableClub_Text_TradeMonsUsingLinkCable_FR::
	.string "Echanger ses POKéMON avec un\n"
	.string "câble GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable_FR::
	.string "Vous pouvez affronter un autre\n"
	.string "joueur avec un câble Game Link.$"

@ Unused, translated in Emerald
CableClub_Text_CloseThisMenu_FR::
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle_FR::
	.string "Pour jouer en COMBAT DUO, il faut\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade_FR::
	.string "Pour un échange, \p"
	.string "il faut avoir au moins deux\n"
	.string "POKéMON en sa possession.$"

CableClub_Text_CantTradeEnigmaBerry_FR::
	.string "Un POKéMON tenant la BAIE\n"
	.string "{STR_VAR_1} ne peut pas être échangé.$"

CableClub_Text_PleaseWaitBCancel_FR::
	.string "Veuillez patienter.\n"
	.string "Bouton B: Annuler$"

CableClub_Text_WhenAllPlayersReadyAConfirmBCancel_FR::
	.string "Quand tous les joueurs sont prêts…\n"
	.string "Bouton A: Confirmer\l"
	.string "Bouton B: Annuler$"

CableClub_Text_StartLinkWithXPlayersAConfirmBCancel_FR::
	.string "Démarrer connexion entre les {STR_VAR_1}\n"
	.string "joueurs.\l"
	.string "Bouton A: Confirmer\l"
	.string "Bouton B: Annuler$"

CableClub_Text_AwaitingLinkupBCancel_FR::
	.string "Connexion en cours…\n"
	.string "Bouton B: Annuler$"

@ Unused, translated in Emerald
CableClub_Text_OkayToSaveProgress_FR::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter_FR::
	.string "Veuillez entrer.$"

CableClub_Text_DirectYouToYourRoom_FR::
	.string "Je vais vous mener à la salle.$"

CableClub_Text_SomeoneIsNotReadyToLink_FR::
	.string "Quelqu'un n'est pas prêt à se\n"
	.string "connecter.\p"
	.string "Veuillez revenir une fois que tous\n"
	.string "les joueurs seront prêts.$"

CableClub_Text_LinkErrorPleaseReset_FR::
	.string "Erreur de connexion…\n"
	.string "Vérifier les branchements et\l"
	.string "réinitialiser les consoles.$"

CableClub_Text_PlayersMadeDifferentSelections_FR::
	.string "Les joueurs connectés semblent\n"
	.string "ne pas avoir fait le même choix.$"

CableClub_Text_PleaseVisitAgain_FR::
	.string "Revenez quand vous voulez.$"

CableClub_Text_IncorrectNumberOfParticipants_FR::
	.string "Le nombre de participants n'est pas\n"
	.string "correct.$"

CableClub_Text_CantSingleBattleWithXPlayers_FR::
	.string "Il est impossible de jouer avec {STR_VAR_1}\n"
	.string "joueurs en mode COMBAT SOLO.$"

CableClub_Text_CantDoubleBattleWithXPlayers_FR::
	.string "Il est impossible de jouer avec {STR_VAR_1}\n"
	.string "joueurs en mode COMBAT DUO.$"

CableClub_Text_NeedFourPlayers_FR::
	.string "Il faut être quatre joueurs pour\n"
	.string "jouer à ce mode de combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart_FR::
	.string "Veuillez confirmer le nombre de\n"
	.string "joueurs et recommencer.$"

Text_TerminateLinkIfYouLeaveRoom_FR::
	.string "La connexion prendra fin si vous\n"
	.string "quittez la pièce. Sortir?$"

Text_TerminateLinkConfirmation_FR::
	.string "Fin de la connexion. On vous\n"
	.string "conduira à la sortie de la pièce.\l"
	.string "Veuillez patienter.$"

Text_TrainerTooBusyToNotice_FR::
	.string "Ce DRESSEUR est trop occupé\n"
	.string "pour vous voir…$"

Text_LookedAtPlayersTrainerCard_FR::
	.string "Bravo! Tu peux regarder la CARTE\n"
	.string "DRESSEUR de {STR_VAR_1}!$"

Text_LookedAtPlayersTrainerCardColored_FR::
	.string "Bravo! Tu peux regarder la CARTE\n"
	.string "DRESSEUR de {STR_VAR_1}!\p"
	.string "C'est une carte en {STR_VAR_2}!$"

Text_TakeSeatStartBattle_FR::
	.string "Veuillez prendre place et\n"
	.string "commencer à combattre.$"

Text_TakeSeatStartTrade_FR::
	.string "Veuillez prendre place et\n"
	.string "commencer l'échange.$"

@ Unused, leftover from RS
RecordCorner_Text_ThanksForComing_FR::
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten_FR::
	.string "Les données sur la CARTE DRESSEUR\n"
	.string "vont être écrasées.$"

CableClub_Text_HopeToSeeYouAgain_FR::
	.string "A une prochaine fois!$"

CableClub_Text_NotSetUpForFarAwayRegion_FR::
	.string "Je suis terriblement désolée.\p"
	.string "Nous ne sommes pas équipés pour\n"
	.string "effectuer des échanges avec des\l"
	.string "DRESSEURS d'une région si lointaine.$"

CableClub_Text_OtherTrainerNotReady_FR::
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken_FR::
	.string "Au moins un POKéMON ne peut\n"
	.string "pas être pris.$"

CableClub_Text_AdapterNotConnected_FR::
	.string "L'adaptateur sans fil GBA n'est pas\n"
	.string "connecté correctement.$"

CableClub_Text_ParticipantsStepUpToCounter_FR::
	.string "Les participants doivent se\n"
	.string "présenter à la réception.$"

@ Unused, translated in Emerald
CableClub_Text_Hello_FR::
	.string "こんにちは！$"

@ Unused, translated in Emerald
CableClub_Text_PleaseWait_FR::
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere_FR::
	.string "Vous pouvez y faire des échanges\n"
	.string "de POKéMON avec un ami.$"

CableClub_Text_YouMayBattleHere_FR::
	.string "Vous pouvez affronter vos amis ici.$"

CableClub_Text_CanMakeBerryPowder_FR::
	.string "De deux à cinq DRESSEURS peuvent\n"
	.string "faire de la POUDRE BAIE ensemble.$"

@ Unused, Record Mix nopped
CableClub_Text_CanMixRecords_FR::
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem_FR::
	.string "Annule le MENU sélectionné.$"

@ Unused, translated in Emerald
CableClub_Text_WhichBattleMode_FR::
	.string "どちらの　しょうぶに　しますか？$"

@ Unused, translated in Emerald
CableClub_Text_ReturnsToPreviousStep_FR::
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush_FR::
	.string "Pour utiliser le BROYEUR DE BAIES,\n"
	.string "il faut avoir au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom_FR::
	.string "Pour entrer dans la SALLE UNION,\n"
	.string "il faut avoir au moins deux PKMN.$"

CableClub_Text_NoEnigmaBerryInUnionRoom_FR::
	.string "Un PKMN tenant la BAIE {STR_VAR_1} ne\n"
	.string "peut entrer dans la SALLE UNION.$"

CableClub_Text_UnionRoomAdapterNotConnected_FR::
	.string "C'est la SALLE UNION du\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Votre adaptateur sans fil GBA\n"
	.string "n'est pas connecté correctement.\p"
	.string "Revenez plus tard.$"

@ Unused, translated in Emerald
CableClub_Text_OhExcuseMe_FR::
	.string "あ‥‥\n"
	.string "おきゃくさま！$"

Text_PlayerIsPlayingRightNowGoForIt_FR::
	.string "On dirait que {STR_VAR_1} est en\n"
	.string "train de jouer.\l"
	.string "Allez-y!$"

Text_DescribeWhichGame_FR::
	.string "Je peux vous expliquer les règles\n"
	.string "du jeu, si vous le souhaitez.\p"
	.string "Vous voulez des infos sur\n"
	.string "quel jeu?$"

Text_PokemonJumpInfo_FR::
	.string "SAUT POKéMON\p"
	.string "Faites sauter votre POKéMON à\n"
	.string "la corde avec le bouton A.\p"
	.string "Seuls les POKéMON jusqu'à\n"
	.string "environ 70 cm peuvent participer.\p"
	.string "Les POKéMON capables seulement\n"
	.string "de nager, creuser ou voler\p"
	.string "ne sont pas vraiment bons au saut\n"
	.string "et ne peuvent donc pas participer.\p"
	.string "Des choses intéressantes arrivent\n"
	.string "si tout le monde saute en rythme.$"

Text_DodrioBerryPickingInfo_FR::
	.string "ATTRAPE-BAIES DODRIO\p"
	.string "Faites bouger les têtes de DODRIO\n"
	.string "pour attraper les BAIES.\p"
	.string "Appuyez sur gauche, haut et droite\n"
	.string "sur la manette {PLUS}.\p"
	.string "Pour jouer à ce jeu, vous devez\n"
	.string "avoir un DODRIO.$"

Text_TalkToManToPlay_FR::
	.string "Si vous voulez commencer un jeu,\n"
	.string "allez voir l'homme à côté.$"

Text_WelcomeCanYouWait_FR::
	.string "Salut! Vous pouvez jouer en\n"
	.string "utilisant le système de\l"
	.string "communication sans fil.\p"
	.string "Vous pouvez patienter encore\n"
	.string "un petit peu? $"

CableClub_Text_ComeAgain_FR::
	.string "Très bien, à bientôt.$"

Text_AdapterNotConnectedMinigame_FR::
	.string "L'adaptateur sans fil GBA n'est\n"
	.string "pas connecté.\p"
	.string "Revenez quand il sera branché!$"

Text_PlayWhichGame_FR::
	.string "Très bien, quel jeu\n"
	.string "voulez-vous commencer?$"

Text_EnterWhichPokemon_FR::
	.string "Quel POKéMON choisissez-vous?$"

Text_AllGoodToGo_FR::
	.string "Parfait, ça va bientôt commencer.\n"
	.string "Ne vous faites pas battre.$"

@ Unused, translated in Emerald
Text_LeavingDoComeAgain_FR::
	.string "きょうは　けえるのか？\n"
	.string "またこいよ！$"

EventScript_ExplainPokemonJumpRequirements_FR::
	.string "Aucun de vos POKéMON ne peut\n"
	.string "participer…\p"
	.string "Voulez-vous savoir quels POKéMON\n"
	.string "peuvent participer?$"

Text_ShortJumpingPokemonAllowed_FR::
	.string "Le SAUT POKéMON est ouvert aux\n"
	.string "POKéMON jusqu'à environ 70 cm.\p"
	.string "Les POKéMON ne pouvant pas sauter\n"
	.string "ne peuvent pas participer.\p"
	.string "Comme ceux qui ne peuvent que\n"
	.string "nager, voler ou creuser.\p"
	.string "Voilà, c'est tout ce qu'il faut\n"
	.string "savoir.$"

Text_OnlyDodrioAllowed_FR::
	.string "ATTRAPE-BAIES DODRIO\n"
	.string "Le nom parle de lui-même.\p"
	.string "Il vous faut un DODRIO pour\n"
	.string "participer.$"

@ Unused, translated in Emerald
Text_RetryFromStartPlease_FR::
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれ$"

CableClub_Text_WelcomeWhichDirectCornerRoom_FR::
	.string "Bienvenue au CLUB SANS FIL\n"
	.string "POKéMON.\p"
	.string "Vous pouvez communiquer avec\n"
	.string "vos amis à partir d'ici.\p"
	.string "A quelle salle voulez-vous\n"
	.string "accéder?$"

CableClub_Text_TradePokemon_FR::
	.string "Voulez-vous échanger un POKéMON?$"

CableClub_Text_PlayWhichBattleMode_FR::
	.string "A quel mode de combat\n"
	.string "voulez-vous jouer?$"

CableClub_Text_UseBerryCrush_FR::
	.string "Voulez-vous utiliser le\n"
	.string "BROYEUR DE BAIES?$"

CableClub_Text_ExplainBattleModes_FR::
	.string "Il existe trois modes de combat.\p"
	.string "En COMBAT SOLO, deux DRESSEURS\n"
	.string "avec au moins un POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR ne peut envoyer\n"
	.string "qu'un seul POKéMON à la fois au\l"
	.string "combat. \p"
	.string "En COMBAT DUO, deux DRESSEURS\n"
	.string "avec au moins deux POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR envoie au combat\n"
	.string "deux POKéMON en même temps.\p"
	.string "En COMBAT MULTI, quatre DRESSEURS\n"
	.string "avec au moins un POKéMON chacun\l"
	.string "combattent.\p"
	.string "Chaque DRESSEUR ne peut envoyer\n"
	.string "qu'un seul POKéMON à la fois au\l"
	.string "combat.$"

CableClub_Text_ChooseGroupLeaderOfTwo_FR::
	.string "Veuillez choisir lequel de vous\n"
	.string "deux sera le MENEUR.\p"
	.string "L'autre joueur devra ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_ChooseGroupLeaderOfFour_FR::
	.string "Veuillez choisir lequel d'entre\n"
	.string "vous sera le MENEUR du GROUPE.\p"
	.string "Les autres joueurs devront ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_ChooseGroupLeader_FR::
	.string "Veuillez choisir lequel d'entre\n"
	.string "vous sera le MENEUR du GROUPE.\p"
	.string "Les autres joueurs devront ensuite\n"
	.string "choisir “JOINDRE”.$"

CableClub_Text_WelcomeUnionRoomEnter_FR::
	.string "Bienvenue à la SALLE UNION du\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Vous pouvez y communiquer avec\n"
	.string "d'autres DRESSEURS. Même avec\l"
	.string "ceux que vous ne connaissez pas.$"

CableClub_Text_UnionRoomInfo_FR::
	.string "Les DRESSEURS dans la SALLE\n"
	.string "UNION sont ceux autour de vous qui\l"
	.string "ont aussi pénétré dans la salle.\p"
	.string "Vous pouvez faire plein de choses\n"
	.string "ici, comme par exemple discuter.\p"
	.string "Vous pouvez faire entrer 2 POKéMON\n"
	.string "jusqu'au niveau 30 pour un combat\p"
	.string "un contre un. Vous pouvez aussi\n"
	.string "participer à des tchats\p"
	.string "réunissant de 2 à 5 personnes.\p"
	.string "Ou vous pouvez encore enregistrer\n"
	.string "un POKéMON pour un échange.\p"
	.string "Voulez-vous entrer dans la SALLE?$"

CableClub_Text_EnjoyUnionRoom_FR::
	.string "J'espère que vous aimerez votre\n"
	.string "visite dans la SALLE UNION.$"

CableClub_Text_FirstTimeRightThisWay_FR::
	.string "Bonjour!\n"
	.string "Je suis ZADIA.\p"
	.string "C'est la première fois que je\n"
	.string "vous vois ici.\p"
	.string "Je vais vous montrer comment le\n"
	.string "système sans fil fonctionne.\p"
	.string "Je dois d'abord vous faire visiter\n"
	.string "cet étage du CENTRE POKéMON.\p"
	.string "Par ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime_FR::
	.string "Au niveau supérieur, il y a\n"
	.string "deux salles.\p"
	.string "Tout d'abord, la salle à gauche\n"
	.string "est la SALLE UNION.\p"
	.string "Vous pouvez vous connecter avec\n"
	.string "les DRESSEURS autour de vous\l"
	.string "qui sont dans la SALLE UNION.\p"
	.string "Vous pouvez parler, faire des\n"
	.string "échanges ou combattre avec eux.\p"
	.string "Ensuite, la salle à droite\n"
	.string "est la SALLE LINK DIRECT. \p"
	.string "Vous pouvez combattre ou faire\n"
	.string "des échanges avec vos amis.\p"
	.string "Si l'adaptateur sans fil n'est pas\n"
	.string "utilisé, vous pouvez toujours vous\l"
	.string "connecter avec un câble Game Link.\p"
	.string "Si c'est le cas, allez directement\n"
	.string "dans la SALLE LINK DIRECT.\p"
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"

CableClub_Text_AskAboutLinking_FR::
	.string "Bonjour {PLAYER}!\p"
	.string "Je suis ZADIA, je m'occupe du 1er\n"
	.string "étage du CENTRE POKéMON.\p"
	.string "Y a-t-il quelque chose que vous\n"
	.string "aimeriez savoir sur la connexion?$"

CableClub_Text_ExplainWirelessClub_FR::
	.string "Laissez-moi vous décrire le\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "Au niveau supérieur, il y a\n"
	.string "deux salles.\p"
	.string "Tout d'abord, la salle à gauche\n"
	.string "est la SALLE UNION.\p"
	.string "Vous pouvez vous connecter avec\n"
	.string "les DRESSEURS autour de vous\l"
	.string "qui sont dans la SALLE UNION.\p"
	.string "Vous pouvez parler, faire des\n"
	.string "échanges ou combattre avec eux.\p"
	.string "Ensuite, la salle à droite\n"
	.string "est la SALLE LINK DIRECT. \p"
	.string "Vous pouvez combattre ou faire\n"
	.string "des échanges avec vos amis.\p"
	.string "Dans certains cas, vous ne\n"
	.string "pourrez vous connecter avec\l"
	.string "vos amis dans aucune des salles.\p"
	.string "Si c'est le cas, rapprochez-vous\n"
	.string "de vos amis.\p"
	.string "Si l'adaptateur sans fil n'est pas\n"
	.string "utilisé, vous pouvez toujours vous\l"
	.string "connecter avec un câble Game Link.\p"
	.string "Si c'est le cas, allez directement\n"
	.string "dans la SALLE LINK DIRECT.\p"
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"

CableClub_Text_HopeYouEnjoyWirelessSystem_FR::
	.string "J'espère que vous apprécierez\n"
	.string "le système sans fil.$"
