@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife_FR::
	.string "Je suis l'HOTE DE LA PENSION.\p"
	.string "Je m'occupe des précieux POKéMON\n"
	.string "des DRESSEURS.\p"
	.string "Si tu veux que je m'occupe d'un de\n"
	.string "tes POKéMON, va parler à ma femme.$"

DayCare_Text_DoYouWantEgg_FR::
	.string "Ah, c'est toi!\p"
	.string "Nous nous occupions de ton POKéMON\n"
	.string "et nous avons eu une énorme\l"
	.string "surprise!\p"
	.string "Ton POKéMON a eu un OEUF!\p"
	.string "On ne sait pas comment il est\n"
	.string "arrivé là, mais ton POKéMON\l"
	.string "l'avait.\p"
	.string "Tu le veux?$"

DayCare_Text_YourMonIsDoingFine_FR::
	.string "Ah, c'est toi! Content de te voir.\n"
	.string "Ton {STR_VAR_1} se porte très bien.$"

DayCare_Text_IllKeepIt_FR::
	.string "Bien, dans ce cas, je vais le\n"
	.string "garder. Merci!$"

DayCare_Text_YouHaveNoRoomForIt_FR::
	.string "Ton équipe est complète… Reviens\n"
	.string "quand tu auras fait de la place.$"

DayCare_Text_ReceivedEgg_FR::
	.string "{PLAYER} reçoit l'OEUF de la part\n"
	.string "de l'HOTE DE LA PENSION.$"

DayCare_Text_TakeGoodCareOfIt_FR::
	.string "Prends-en bien soin.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon_FR::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine_FR::
	.string "Ah, c'est toi! Ton {STR_VAR_1} et\n"
	.string "ton {STR_VAR_2} se portent très\l"
	.string "bien.$"

DayCare_Text_IWillKeepDoYouWantIt_FR::
	.string "Je vais vraiment le garder.\n"
	.string "Tu le veux, ou pas?$"

DayCare_Text_WouldYouLikeUsToRaiseMon_FR::
	.string "Je suis l'HOTESSE DE LA PENSION.\p"
	.string "Nous pouvons élever des POKéMON\n"
	.string "pour toi.\p"
	.string "Tu veux qu'on en élève un?$"

DayCare_Text_WhichMonShouldWeRaise_FR::
	.string "Quel POKéMON veux-tu que l'on\n"
	.string "élève?$"

DayCare_Text_WellRaiseYourMon_FR::
	.string "Très bien, nous allons nous occuper\n"
	.string "de ton {STR_VAR_1} pendant\l"
	.string "un moment.\p"
	.string "Reviens le chercher plus tard.$"

DayCare_Text_WeCanRaiseOneMore_FR::
	.string "Nous pouvons élever deux POKéMON.\n"
	.string "Tu veux qu'on en élève un autre?$"


DayCare_Text_HusbandWasLookingForYou_FR::
	.string "Mon mari te cherchait.$"

DayCare_Text_FineThenComeAgain_FR::
	.string "Oh, très bien.\n"
	.string "Reviens plus tard, dans ce cas.$"

DayCare_Text_NotEnoughMoney_FR::
	.string "Tu n'as pas assez d'argent…$"

DayCare_Text_TakeOtherOneBackToo_FR::
	.string "Veux-tu aussi reprendre le\n"
	.string "deuxième?$"

DayCare_Text_ComeAgain_FR::
	.string "Très bien.\n"
	.string "Reviens plus tard.$"

DayCare_Text_GoodToSeeYou_FR::
	.string "Ah, c'est toi! Contente de te voir.\n"
	.string "Ton POKéMON est sûr d'être bien\l"
	.string "traité!$"

DayCare_Text_YourMonHasGrownXLevels_FR::
	.string "Ton {STR_VAR_1} est monté de\n"
	.string "{STR_VAR_2} niveau(x).$"

DayCare_Text_YourPartyIsFull_FR::
	.string "Ton équipe de POKéMON est au\n"
	.string "complet. Fais de la place et\l"
	.string "reviens me voir.$"

DayCare_Text_TakeBackWhichMon_FR::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX_FR::
	.string "Si tu veux récupérer ton\n"
	.string "{STR_VAR_1}, tu dois payer\l"
	.string "{STR_VAR_2}¥.$"

DayCare_Text_HeresYourMon_FR::
	.string "Parfait!\n"
	.string "Voilà ton POKéMON.$"

DayCare_Text_TookBackMon_FR::
	.string "{PLAYER} reprend le {STR_VAR_1} à\n"
	.string "l'HOTESSE DE LA PENSION.$"

DayCare_Text_YouHaveJustOneMon_FR::
	.string "Oh! Mais tu n'as qu'un seul\n"
	.string "POKéMON.\p"
	.string "Reviens une autre fois.$"

DayCare_Text_TakeYourMonBack_FR::
	.string "Veux-tu reprendre ton POKéMON?$"

DayCare_Text_WhatWillYouBattleWith_FR::
	.string "Si tu me laisses ce POKéMON,\n"
	.string "comment vas-tu faire pour te\l"
	.string "battre?\p"
	.string "Reviens me voir une autre fois.$"

DayCare_Text_Huh_FR::
	.string "Hein?$"
