gFameCheckerFlavorText_ProfOak0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABO POKéMON de CHEN$"

gFameCheckerFlavorText_ProfOak1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Faire un guide complet sur les\n"
	.string "POKéMON du monde entier…\p"
	.string "C'est mon rêve!$"

gFameCheckerFlavorText_ProfOak2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN est une célébrité\n"
	.string "dans le monde des POKéMON.\p"
	.string "Nombreux sont les DRESSEURS qui\n"
	.string "lui portent un grand respect.$"

gFameCheckerFlavorText_ProfOak3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN vit avec sa\n"
	.string "petite-fille NINA et {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît qu'il place de grands\n"
	.string "espoirs en toi. Autrefois, il était\p"
	.string "impressionnant de force et de\n"
	.string "beauté. C'était il y a des\p"
	.string "dizaines d'années, maintenant,\n"
	.string "il se consacre à ses études.$"

gFameCheckerFlavorText_ProfOak5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN va avoir\n"
	.string "sa propre émission de radio.\p"
	.string "Elle s'appellera le SEMINAIRE\n"
	.string "DU PROF. CHEN.$"

gFameCheckerFlavorText_Daisy0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}NINA est capable de dire si\n"
	.string "tes POKéMON t'aiment ou pas.\p"
	.string "A l'occasion, elle peut même s'en\n"
	.string "occuper pour toi.$"

gFameCheckerFlavorText_Daisy1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A mon avis, c'est la personne\n"
	.string "que les POKéMON préfèrent.$"

gFameCheckerFlavorText_Daisy2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Elle adorait ses POKéMON et les\n"
	.string "traitait avec beaucoup d'amour.\p"
	.string "Le nom de cette petite fille, je\n"
	.string "crois que c'est NINA.$"

gFameCheckerFlavorText_Daisy3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PROF. CHEN vit avec sa\n"
	.string "petite-fille NINA et {RIVAL}.$"

gFameCheckerFlavorText_Daisy4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}NINA vient de BOURG PALETTE,\n"
	.string "elle boit du THE tous les jours et\p"
	.string "va souvent au CENTRE COMMERCIAL\n"
	.string "de CELADOPOLE pour en acheter.$"

gFameCheckerFlavorText_Daisy5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le grand champion du concours\n"
	.string "POKéMON de printemps est\l"
	.string "NINA de BOURG PALETTE.$"

gFameCheckerFlavorText_Brock0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHAMPION d'ARENE\n"
	.string "d'ARGENTA: PIERRE\p"
	.string "Le DRESSEUR dur comme la pierre!$"

gFameCheckerFlavorText_Brock1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON sont tous\n"
	.string "durs comme la pierre et mon esprit\p"
	.string "est clair comme de l'eau de roche.\p"
	.string "C'est ça! Mes POKéMON favoris\n"
	.string "sont les POKéMON ROCHE.$"

gFameCheckerFlavorText_Brock2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il n'y a pas vraiment de\n"
	.string "DRESSEURS sérieux par ici.\p"
	.string "Ils s'intéressent surtout aux\n"
	.string "INSECTES, rien de passionnant.\p"
	.string "Mais PIERRE d'ARGENTA n'est\n"
	.string "pas comme ça, pas du tout.$"

gFameCheckerFlavorText_Brock3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En plus d'être cool, PIERRE\n"
	.string "est aussi très fort.\p"
	.string "Je voudrais devenir CHAMPION\n"
	.string "d'ARENE comme lui.$"

gFameCheckerFlavorText_Brock4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je cherche des fossiles ici,\n"
	.string "sous le MONT SELENITE.\p"
	.string "PIERRE de l'ARENE d'ARGENTA\n"
	.string "vient souvent m'aider.$"

gFameCheckerFlavorText_Brock5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PIERRE rigole rarement, mais il\n"
	.string "ne peut pas s'arrêter s'il commence.$"

gFameCheckerFlavorText_Misty0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHAMPION d'ARENE\n"
	.string "d'AZURIA: ONDINE\l"
	.string "La sirène en shorts!$"

gFameCheckerFlavorText_Misty1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma tactique? Attaquer\n"
	.string "avec des POKéMON EAU!$"

gFameCheckerFlavorText_Misty2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ONDINE est un DRESSEUR\n"
	.string "toujours en apprentissage.\p"
	.string "Mais elle ne peut pas perdre\n"
	.string "contre quelqu'un comme toi!$"

gFameCheckerFlavorText_Misty3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On voit souvent des DRESSEURS\n"
	.string "avec des POKéMON EAU par ici.\p"
	.string "Ils disent qu'ONDINE de l'ARENE\n"
	.string "d'AZURIA s'entraîne dans le coin.$"

gFameCheckerFlavorText_Misty4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce cap sert souvent de\n"
	.string "point de rencontre aux amoureux.\p"
	.string "On dit qu'ONDINE y aurait de\n"
	.string "grands espoirs.$"

gFameCheckerFlavorText_Misty5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On raconte qu'elle adore OLGA\n"
	.string "du CONSEIL 4.$"

gFameCheckerFlavorText_LtSurge0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHAMPION d'ARENE de\n"
	.string "CARMIN SUR MER: MAJOR BOB\l"
	.string "L'Américain Survolté!$"

gFameCheckerFlavorText_LtSurge1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je vais t'avouer quelque\n"
	.string "chose, les POKéMON ELECTRIK\p"
	.string "m'ont sauvé pendant la guerre!$"

gFameCheckerFlavorText_LtSurge2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A l'armée, MAJOR BOB\n"
	.string "était mon supérieur.\p"
	.string "C'était très instructif d'être sous\n"
	.string "ses ordres.$"

gFameCheckerFlavorText_LtSurge3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le MAJOR BOB a toujours été\n"
	.string "reconnu pour sa nature prudente$"

gFameCheckerFlavorText_LtSurge4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est le MAJOR BOB\n"
	.string "lui-même qui a installé les pièges\p"
	.string "de cette ARENE. Il a mis des\n"
	.string "double verrous partout.$"

gFameCheckerFlavorText_LtSurge5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il aurait été pilote quand il était\n"
	.string "dans l'armée. Il utilisait\p"
	.string "l'électricité de ses POKéMON\n"
	.string "pour faire voler son avion.$"

gFameCheckerFlavorText_Erika0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CHAMPION d'ARENE de\n"
	.string "CELADOPOLE: ERIKA\l"
	.string "Le combat par les plantes!$"

gFameCheckerFlavorText_Erika1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'étudie l'art des\n"
	.string "bouquets garnis.\p"
	.string "Mes POKéMON sont uniquement\n"
	.string "du type PLANTE.$"

gFameCheckerFlavorText_Erika2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Notre CHAMPION a beau être\n"
	.string "calme, elle fait beaucoup\p"
	.string "parler d'elle.$"

gFameCheckerFlavorText_Erika3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans cette ARENE, on ne se\n"
	.string "bat qu'avec des POKéMON PLANTE.\p"
	.string "En fait, on les utilise aussi pour\n"
	.string "faire des compositions florales!$"

gFameCheckerFlavorText_Erika4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pour ma part, je collectionne les\n"
	.string "plus beaux POKéMON.$"

gFameCheckerFlavorText_Erika5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si vous arrivez sans prévenir à\n"
	.string "l'ARENE de CELADOPOLE, \l"
	.string "vous risquez de la voir dormir.$"

gFameCheckerFlavorText_Koga0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARENE POKéMON de PARMANIE \n"
	.string "CHAMPION: KOGA\l"
	.string "Le ninja aux poisons redoutables$"

gFameCheckerFlavorText_Koga1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prépare-toi à affronter\n"
	.string "mes terribles POKéMON POISON!$"

gFameCheckerFlavorText_Koga2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je garderai espoir même dans la\n"
	.string "défaite, selon l'enseignement de\l"
	.string "KOGA, mon maître ninja.$"

gFameCheckerFlavorText_Koga3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mon père est le\n"
	.string "CHAMPION de cette ville.\p"
	.string "Je m'entraîne pour utiliser des \n"
	.string "POKéMON POISON, comme lui.$"

gFameCheckerFlavorText_Koga4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il est incollable en médecine.\n"
	.string "On dit qu'il prépare lui-même\p"
	.string "ses médicaments pour soigner\n"
	.string "ses POKéMON.$"

gFameCheckerFlavorText_Koga5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le PARC SAFARI est immense,\n"
	.string "tu trouves pas?\p"
	.string "KOGA, le CHAMPION d'ARENE de\n"
	.string "PARMANIE vient souvent ici.\p"
	.string "Grâce à lui, on peut se promener\n"
	.string "en sécurité.$"

gFameCheckerFlavorText_Sabrina0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARENE POKéMON de SAFRANIA \n"
	.string "CHAMPION: MORGANE\l"
	.string "Maîtresse des POKéMON PSY!$"

gFameCheckerFlavorText_Sabrina1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}T'as entendu parler d'une fille\n"
	.string "CHAMPION d'ARENE de SAFRANIA?\p"
	.string "Elle utilise des POKéMON PSY,\n"
	.string "c'est bien ça?$"

gFameCheckerFlavorText_Sabrina2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai des pouvoirs psychiques depuis\n"
	.string "l'enfance.\p"
	.string "J'ai appris à plier des cuillères\n"
	.string "par la force de mon esprit.$"

gFameCheckerFlavorText_Sabrina3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je n'aime pas les combats, mais si\n"
	.string "tu insistes, je vais te montrer mes\l"
	.string "pouvoirs!$"

gFameCheckerFlavorText_Sabrina4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les gens racontent qu'elle peut\n"
	.string "communiquer avec ses POKéMON\p"
	.string "pendant les combats juste par\n"
	.string "la pensée.$"

gFameCheckerFlavorText_Sabrina5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MORGANE a pulvérisé le grand\n"
	.string "MAITRE de KARATE!$"

gFameCheckerFlavorText_Blaine0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ARENE POKéMON de CRAMOIS'ILE \n"
	.string "CHAMPION: AUGUSTE\l"
	.string "Le maître du quiz!$"

gFameCheckerFlavorText_Blaine1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON flamboyants vont te\n"
	.string "réduire en cendres!$"

gFameCheckerFlavorText_Blaine2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tout petit, AUGUSTE aimait se\n"
	.string "promener dans les montagnes.\p"
	.string "Une nuit, il s'est retrouvé\n"
	.string "complètement perdu! Mais un\l"
	.string "POKéMON oiseau apparut…\p"
	.string "La lumière de ses ailes enflammées\n"
	.string "permit à AUGUSTE de retrouver son\p"
	.string "chemin! Depuis il adore les\n"
	.string "POKéMON FEU!$"

gFameCheckerFlavorText_Blaine3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AUGUSTE, de l'ARENE de\n"
	.string "CRAMOIS'ILE est un type étrange.\p"
	.string "Il vit ici depuis bien avant la\n"
	.string "construction du LABORATOIRE.$"

gFameCheckerFlavorText_Blaine4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'AUGUSTE\n"
	.string "et de MR. FUJI.\p"
	.string "Ils sont côte à côte en souriant.$"

gFameCheckerFlavorText_Blaine5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AUGUSTE passe tout son temps à\n"
	.string "créer des questions pour son quiz.$"

gFameCheckerFlavorText_Lorelei0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je zuis OLGA du CONZEIL 4!$"

gFameCheckerFlavorText_Lorelei1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je zuis la maîtrezze des\n"
	.string "POKéMON GLAZE!\p"
	.string "Perzonne ne peut les battre…$"

gFameCheckerFlavorText_Lorelei2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Où est née cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Un DRESSEUR très fort et très\n"
	.string "connu vient de cette île.\p"
	.string "Je suis sûr que même toi tu\n"
	.string "connais son nom.\p"
	.string "C'est OLGA, du CONSEIL 4.$"

gFameCheckerFlavorText_Lorelei3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Connue pour sa logique et son\n"
	.string "style de combat très posé.\p"
	.string "OLGA cache un terrible secret.$"

gFameCheckerFlavorText_Lorelei4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu savais qu'OLGA a une\n"
	.string "collection de poupées?\p"
	.string "Sa collection grandit à chaque fois\n"
	.string "qu'elle revient sur l'ILE 4.$"

gFameCheckerFlavorText_Lorelei5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Son LOKHLASS, ça doit être\n"
	.string "celui qu'elle a depuis son enfance.\p"
	.string "Je crois qu'elle l'avait attrapé\n"
	.string "dans la GROTTE DE GLACE.\p"
	.string "Ce POKéMON a dû passer des\n"
	.string "années avec elle.$"

gFameCheckerFlavorText_Bruno0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis ALDO du CONSEIL 4!$"

gFameCheckerFlavorText_Bruno1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai passé toute ma vie avec mes\n"
	.string "POKéMON COMBAT, et\p"
	.string "ça n'est pas près de changer!$"

gFameCheckerFlavorText_Bruno2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ALDO a rejoint le CONSEIL 4\n"
	.string "pour pouvoir affronter\p"
	.string "les meilleurs DRESSEURS du\n"
	.string "monde.$"

gFameCheckerFlavorText_Bruno3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ALDO va souvent aux\n"
	.string "sources thermales.\p"
	.string "Il y va pour soigner ses blessures\n"
	.string "et celles de ses POKéMON.$"

gFameCheckerFlavorText_Bruno4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il fait partie du CONSEIL 4,\n"
	.string "il s'appelle ALDO.\p"
	.string "Il est reparti très déçu quand\n"
	.string "il a vu que les SUPER BONBONS\p"
	.string "étaient en rupture de stock\n"
	.string "partout.$"

gFameCheckerFlavorText_Bruno5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Même ALDO…\p"
	.string "Avant, il s'entraînait avec un\n"
	.string "gars qui s'appelle BASTIEN.$"

gFameCheckerFlavorText_Agatha0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis AGATHA du CONSEIL 4!$"

gFameCheckerFlavorText_Agatha1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les POKéMON SPECTRE\n"
	.string "d'AGATHA sont terrifiants.$"

gFameCheckerFlavorText_Agatha2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA se met facilement\n"
	.string "en rogne. J'te raconte pas.$"

gFameCheckerFlavorText_Agatha3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans sa jeunesse, AGATHA était\n"
	.string "la rivale du PROF. CHEN.\p"
	.string "Ils s'affrontaient pour obtenir\n"
	.string "le titre du meilleur DRESSEUR.$"

gFameCheckerFlavorText_Agatha4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que CHEN place de\n"
	.string "grands espoirs en toi. Autrefois,\p"
	.string "il était impressionnant de force\n"
	.string "et de beauté. C'était il y a des\p"
	.string "dizaines d'années, maintenant,\n"
	.string "il se consacre à ses études.$"

gFameCheckerFlavorText_Agatha5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prends AGATHA par exemple.\n"
	.string "C'est la personne la plus\p"
	.string "âgée qui ait jamais fait partie\n"
	.string "du CONSEIL 4.$"

gFameCheckerFlavorText_Lance0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je règne sur le CONSEIL 4!\n"
	.string "Mon nom est PETER, le DRESSEUR\l"
	.string "de dragons!$"

gFameCheckerFlavorText_Lance1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les dragons sont des POKéMON\n"
	.string "mythiques!\p"
	.string "Les capturer et les entraîner est\n"
	.string "difficile mais leurs pouvoirs\p"
	.string "sont supérieurs!\n"
	.string "Ils sont presque invincibles!$"

gFameCheckerFlavorText_Lance2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il défend la justice!\n"
	.string "Il est posé et pourtant passionné!\l"
	.string "C'est le plus grand, c'est PETER!$"

gFameCheckerFlavorText_Lance3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PETER vient souvent ici pour\n"
	.string "acheter des capes.\p"
	.string "Je me demande combien de capes\n"
	.string "identiques il peut avoir chez lui.$"

gFameCheckerFlavorText_Lance4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le grand-père de PETER est\n"
	.string "le doyen du célèbre clan\l"
	.string "des maîtres dragon.$"

gFameCheckerFlavorText_Lance5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Y'a un copain d'un cousin d'une\n"
	.string "amie qui dit que PETER\p"
	.string "a un cousin CHAMPION D'ARENE\n"
	.string "quelque part.$"

gFameCheckerFlavorText_Bill0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tout l'monde sait que LEO est\n"
	.string "un POKéMANIAC!\p"
	.string "Il a même inventé le stockage des\n"
	.string "POKéMON sur PC!$"

gFameCheckerFlavorText_Bill1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO a une sacrée collection de\n"
	.string "POKéMON!\p"
	.string "Et des rares, en plus…$"

gFameCheckerFlavorText_Bill2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est mon petit-fils!\p"
	.string "Il souffre de collectionnite\n"
	.string "depuis son enfance!$"

gFameCheckerFlavorText_Bill3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO est un POKéMANIAC,\n"
	.string "il aime tous les types de POKéMON.\p"
	.string "Apparemment, son premier POKéMON\n"
	.string "était un ABRA.$"

gFameCheckerFlavorText_Bill4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LEO vient de GOLDENROD,\n"
	.string "sa famille y habite toujours.\p"
	.string "On raconte que c'est une ville\n"
	.string "qui aime faire la fête.$"

gFameCheckerFlavorText_Bill5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparemment, LEO est allergique\n"
	.string "au lait, c'est dingue.$"

gFameCheckerFlavorText_MrFuji0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est vraiment un chic type!\p"
	.string "Il est à la recherche des POKéMON\n"
	.string "orphelins et abandonnés!$"

gFameCheckerFlavorText_MrFuji1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce vieil homme est venu nous\n"
	.string "demander de ne plus troubler les\l"
	.string "gentils POKéMON!\p"
	.string "Alors on a discuté tranquillement\n"
	.string "entre adultes.$"

gFameCheckerFlavorText_MrFuji2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Grand concours de dessin du\n"
	.string "magazine des fans de POKéMON!\p"
	.string "Le formulaire d'inscription est…\p"
	.string "Il a disparu! Quelqu'un a déjà dû\n"
	.string "l'utiliser.$"

gFameCheckerFlavorText_MrFuji3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que MR. FUJI n'est\n"
	.string "pas non plus du coin.$"

gFameCheckerFlavorText_MrFuji4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'AUGUSTE\n"
	.string "et de MR. FUJI.\p"
	.string "Ils sont côte à côte en souriant.$"

gFameCheckerFlavorText_MrFuji5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le timide MR. FUJI a\n"
	.string "décliné notre demande d'interview.\p"
	.string "Cet homme très gentil est très\n"
	.string "apprécié à LAVANVILLE.$"

gFameCheckerFlavorText_Giovanni0_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pour financer ses plans, la TEAM\n"
	.string "ROCKET a besoin de POKéMON!\p"
	.string "Pour ça, nous en capturons dans le\n"
	.string "monde entier.\p"
	.string "Et je suis le chef, moi…\n"
	.string "GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ces types qui ont pris l'immeuble…\p"
	.string "Leur chef a dit qu'il cherchait des\n"
	.string "POKéMON costauds.$"

gFameCheckerFlavorText_Giovanni2_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le chef de la TEAM ROCKET est\n"
	.string "incroyablement cruel.\p"
	.string "Pour lui, les POKéMON ne sont que\n"
	.string "des outils.$"

gFameCheckerFlavorText_Giovanni3_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Te voici dans mon repaire!\p"
	.string "Je voulais reformer la TEAM\n"
	.string "ROCKET ici!$"

gFameCheckerFlavorText_Giovanni4_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quoi?! C'était GIOVANNI le\n"
	.string "CHAMPION? Ben ça alors!$"

gFameCheckerFlavorText_Giovanni5_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu n'es pas le gamin de GIOVANNI,\n"
	.string "n'est-ce pas?\p"
	.string "Non, impossible! Son gamin a\n"
	.string "les cheveux rouges.$"

gFameCheckerPersonName_ProfOak_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. CHEN$"

gFameCheckerPersonQuote_ProfOak_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PROF. CHEN\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pourquoi les POKéMON se\n"
	.string "battent-ils ainsi pour toi?\p"
	.string "C'est grâce à l'amour et la\n"
	.string "confiance que tu leur portes\p"
	.string "qu'ils acceptent de se battre\n"
	.string "pour toi.\p"
	.string "N'oublie jamais ça.$"

gFameCheckerPersonName_Daisy_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}NINA$"

gFameCheckerPersonQuote_Daisy_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: NINA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu as fait de gros progrès pendant\n"
	.string "que je faisais mes pauses thé.\p"
	.string "J'espère que mon petit frère aimera\n"
	.string "toujours se battre contre toi.$"

gFameCheckerPersonName_Brock_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PIERRE$"

gFameCheckerPersonQuote_Brock_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PIERRE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il doit y avoir beaucoup de\n"
	.string "bons DRESSEURS sur terre.\p"
	.string "Continuons de nous entraîner pour\n"
	.string "être de plus en plus forts.$"

gFameCheckerPersonName_Misty_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ONDINE$"

gFameCheckerPersonQuote_Misty_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ONDINE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je vais continuer de m'entraîner\n"
	.string "dans cette ARENE.\p"
	.string "Quand je serai plus forte, je\n"
	.string "partirai explorer le monde.$"

gFameCheckerPersonName_LtSurge_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MAJOR BOB$"

gFameCheckerPersonQuote_LtSurge_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MAJOR BOB\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hé toi, c'était électrisant\n"
	.string "comme combat!\p"
	.string "Je ne savais pas que des\n"
	.string "DRESSEURS comme toi existaient.\p"
	.string "J'ai complètement changé d'opinion\n"
	.string "sur toi!$"

gFameCheckerPersonName_Erika_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ERIKA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis contente qu'il\n"
	.string "y ait des DRESSEURS comme toi.\p"
	.string "Ça me motive pour m'entraîner\n"
	.string "encore plus.\p"
	.string "Reviens me voir.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: KOGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Toi et moi, nous devons revoir\n"
	.string "nos objectifs à la hausse pour\l"
	.string "nous surpasser encore plus.\p"
	.string "Bien, je pars entraîner ma\n"
	.string "petite fille.$"

gFameCheckerPersonName_Sabrina_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MORGANE$"

gFameCheckerPersonQuote_Sabrina_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MORGANE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}L'amour que tu portes à\n"
	.string "tes POKéMON…\p"
	.string "Mes pouvoirs PSY ne peuvent pas\n"
	.string "rivaliser contre cette force.$"

gFameCheckerPersonName_Blaine_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AUGUSTE$"

gFameCheckerPersonQuote_Blaine_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AUGUSTE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON FEU!\n"
	.string "Ils vont devenir encore plus forts!\p"
	.string "Et maintenant, place au quiz.\n"
	.string "Combien y'a-t-il de types FEU?$"

gFameCheckerPersonName_Lorelei_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}OLGA$"

gFameCheckerPersonQuote_Lorelei_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: OLGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je dois te remerzier\n"
	.string "pour ton aide.\p"
	.string "Mais za n'a rien à voir avec nos\n"
	.string "combats.\p"
	.string "Je ne te ferai pas de cadeau la\n"
	.string "prochaine fois!$"

gFameCheckerPersonName_Bruno_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ALDO$"

gFameCheckerPersonQuote_Bruno_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ALDO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La super puissance de tes POKéMON\n"
	.string "m'a servi de leçon.\p"
	.string "La prochaine fois, ce sera à moi\n"
	.string "de te faire la leçon.$"

gFameCheckerPersonName_Agatha_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AGATHA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En grandissant, ne te\n"
	.string "ramollis pas comme CHEN!\p"
	.string "Reste comme moi et n'hésite pas\n"
	.string "à combattre!$"

gFameCheckerPersonName_Lance_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PETER$"

gFameCheckerPersonQuote_Lance_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PETER\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je songe à retourner dans\n"
	.string "ma ville natale.\p"
	.string "Je veux y entraîner mes POKéMON\n"
	.string "DRAGON pour les endurcir.\p"
	.string "Je voudrais t'y inviter un jour.$"

gFameCheckerPersonName_Bill_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LEO$"

gFameCheckerPersonQuote_Bill_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: LEO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CILEO n'arrête pas de me\n"
	.string "dire du bien sur toi.\p"
	.string "Ça me fait vraiment plaisir.\p"
	.string "N'oublie pas de venir me montrer\n"
	.string "tes POKéMON rares, OK?$"

gFameCheckerPersonName_MrFuji_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MR. FUJI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Plutôt que de souhaiter le\n"
	.string "bonheur de tes POKéMON…\p"
	.string "… Je préfèrerais que tu souhaites\n"
	.string "le bonheur de tous les POKéMON!$"

gFameCheckerPersonName_Giovanni_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni_FR::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: GIOVANNI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je n'ai vraiment rien à\n"
	.string "te dire.\p"
	.string "Je vais me concentrer sur mon\n"
	.string "entraînement, rien d'autre.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0_FR::
	.string "BOURG PALETTE$"

gFameCheckerFlavorTextOriginLocation_ProfOak1_FR::
	.string "LABO POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak2_FR::
	.string "LABO POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak3_FR::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_ProfOak4_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak5_FR::
	.string "LABO POKéMON$"

gFameCheckerFlavorTextOriginLocation_Daisy0_FR::
	.string "LABO POKéMON$"

gFameCheckerFlavorTextOriginLocation_Daisy1_FR::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Daisy2_FR::
	.string "LABYRINTHE D'O$"

gFameCheckerFlavorTextOriginLocation_Daisy3_FR::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Daisy4_FR::
	.string "MANOIR CELADON$"

gFameCheckerFlavorTextOriginLocation_Daisy5_FR::
	.string "ILE 4$"

gFameCheckerFlavorTextOriginLocation_Brock0_FR::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock1_FR::
	.string "ARENE d'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock2_FR::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock3_FR::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4_FR::
	.string "MONT SELENITE$"

gFameCheckerFlavorTextOriginLocation_Brock5_FR::
	.string "MUSEE d'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Misty0_FR::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty1_FR::
	.string "ARENE d'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty2_FR::
	.string "ARENE d'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty3_FR::
	.string "ILES ECUME$"

gFameCheckerFlavorTextOriginLocation_Misty4_FR::
	.string "CAP D'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty5_FR::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge0_FR::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge1_FR::
	.string "ARENE de CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge2_FR::
	.string "ARENE de CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge3_FR::
	.string "ARENE de CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge4_FR::
	.string "ARENE de CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge5_FR::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Erika0_FR::
	.string "CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika1_FR::
	.string "ARENE de CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika2_FR::
	.string "ARENE de CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika3_FR::
	.string "ARENE de CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika4_FR::
	.string "ARENE de CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika5_FR::
	.string "MANOIR CELADON$"

gFameCheckerFlavorTextOriginLocation_Koga0_FR::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga1_FR::
	.string "ARENE de PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga2_FR::
	.string "ARENE de PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga3_FR::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga4_FR::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga5_FR::
	.string "PARC SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0_FR::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina1_FR::
	.string "ILE 3$"

gFameCheckerFlavorTextOriginLocation_Sabrina2_FR::
	.string "ARENE de SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina3_FR::
	.string "ARENE de SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina4_FR::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina5_FR::
	.string "ARENE de SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Blaine0_FR::
	.string "CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Blaine1_FR::
	.string "ARENE de CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Blaine2_FR::
	.string "ARENE de CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Blaine3_FR::
	.string "CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Blaine4_FR::
	.string "ARENE de CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Blaine5_FR::
	.string "CAMP DE VACANCES$"

gFameCheckerFlavorTextOriginLocation_Lorelei0_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei1_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei2_FR::
	.string "ILE 4$"

gFameCheckerFlavorTextOriginLocation_Lorelei3_FR::
	.string "ILE 5$"

gFameCheckerFlavorTextOriginLocation_Lorelei4_FR::
	.string "ILE 4$"

gFameCheckerFlavorTextOriginLocation_Lorelei5_FR::
	.string "ILE 4$"

gFameCheckerFlavorTextOriginLocation_Bruno0_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno1_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno2_FR::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Bruno3_FR::
	.string "SOURCE BRAISE$"

gFameCheckerFlavorTextOriginLocation_Bruno4_FR::
	.string "ILE 2$"

gFameCheckerFlavorTextOriginLocation_Bruno5_FR::
	.string "CANYON SESOR$"

gFameCheckerFlavorTextOriginLocation_Agatha0_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha1_FR::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha2_FR::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha3_FR::
	.string "ILE 7$"

gFameCheckerFlavorTextOriginLocation_Agatha4_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha5_FR::
	.string "ILE 6$"

gFameCheckerFlavorTextOriginLocation_Lance0_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance1_FR::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance2_FR::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Lance3_FR::
	.string "CENT. COMMERCIAL$"

gFameCheckerFlavorTextOriginLocation_Lance4_FR::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Lance5_FR::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Bill0_FR::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill1_FR::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill2_FR::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Bill3_FR::
	.string "ILE 1$"

gFameCheckerFlavorTextOriginLocation_Bill4_FR::
	.string "ILE 1$"

gFameCheckerFlavorTextOriginLocation_Bill5_FR::
	.string "ILE 1$"

gFameCheckerFlavorTextOriginLocation_MrFuji0_FR::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji1_FR::
	.string "TOUR POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2_FR::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji3_FR::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji4_FR::
	.string "ARENE de CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_MrFuji5_FR::
	.string "CRAMOIS'ILE$"

gFameCheckerFlavorTextOriginLocation_Giovanni0_FR::
	.string "REPAIRE ROCKET$"

gFameCheckerFlavorTextOriginLocation_Giovanni1_FR::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni2_FR::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni3_FR::
	.string "ARENE de JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni4_FR::
	.string "ARENE de JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni5_FR::
	.string "ENTREPOT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1_FR::
	.string "PROF. CHEN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2_FR::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4_FR::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5_FR::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy0_FR::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy1_FR::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy2_FR::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy3_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Daisy4_FR::
	.string "VIEILLE FEMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Brock0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Brock1_FR::
	.string "PIERRE$"

gFameCheckerFlavorTextOriginObjectName_Brock2_FR::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock3_FR::
	.string "GARÇON$"

gFameCheckerFlavorTextOriginObjectName_Brock4_FR::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Misty0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Misty1_FR::
	.string "ONDINE$"

gFameCheckerFlavorTextOriginObjectName_Misty2_FR::
	.string "LOUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3_FR::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Misty4_FR::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1_FR::
	.string "MAJOR BOB$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2_FR::
	.string "ANATOLE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3_FR::
	.string "ANATOLE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4_FR::
	.string "HAROLD$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Erika0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Erika1_FR::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2_FR::
	.string "LISA$"

gFameCheckerFlavorTextOriginObjectName_Erika3_FR::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4_FR::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Koga1_FR::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2_FR::
	.string "CHRIS$"

gFameCheckerFlavorTextOriginObjectName_Koga3_FR::
	.string "JEANNINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga5_FR::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1_FR::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2_FR::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3_FR::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5_FR::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0_FR::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Blaine1_FR::
	.string "AUGUSTE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2_FR::
	.string "DIDIER$"

gFameCheckerFlavorTextOriginObjectName_Blaine3_FR::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Blaine4_FR::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0_FR::
	.string "OLGA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1_FR::
	.string "OLGA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2_FR::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4_FR::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5_FR::
	.string "VIEILLE DAME$"

gFameCheckerFlavorTextOriginObjectName_Bruno0_FR::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1_FR::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Bruno3_FR::
	.string "BROYEUR$"

gFameCheckerFlavorTextOriginObjectName_Bruno4_FR::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Bruno5_FR::
	.string "BROYEUR$"

gFameCheckerFlavorTextOriginObjectName_Agatha0_FR::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1_FR::
	.string "BROYEUR$"

gFameCheckerFlavorTextOriginObjectName_Agatha2_FR::
	.string "BROYEUR$"

gFameCheckerFlavorTextOriginObjectName_Agatha3_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Agatha4_FR::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5_FR::
	.string "VIEILLE DAME$"

gFameCheckerFlavorTextOriginObjectName_Lance0_FR::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance1_FR::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance2_FR::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Lance3_FR::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_Lance4_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lance5_FR::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill0_FR::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1_FR::
	.string "PETIT GARÇON$"

gFameCheckerFlavorTextOriginObjectName_Bill2_FR::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill3_FR::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_Bill4_FR::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_Bill5_FR::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0_FR::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1_FR::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2_FR::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3_FR::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4_FR::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5_FR::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0_FR::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1_FR::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2_FR::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3_FR::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4_FR::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5_FR::
	.string "GEDEON$"

PokemonJournal_Text_SpecialFeatureBrock_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec PIERRE, le\n"
	.string "CHAMPION d'ARENE d'ARGENTA!\p"
	.string "PIERRE rigole rarement, mais il\n"
	.string "ne peut pas s'arrêter s'il commence.$"

PokemonJournal_Text_SpecialFeatureMisty_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec ONDINE, le CHAMPION\n"
	.string "d'ARENE d'AZURIA!\p"
	.string "On raconte qu'elle adore OLGA\n"
	.string "du CONSEIL 4.$"

PokemonJournal_Text_SpecialFeatureLtSurge_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec MAJOR BOB, le CHAMPION\n"
	.string "d'ARENE de CARMIN SUR MER!\p"
	.string "Il aurait été pilote quand il était\n"
	.string "dans l'armée.\p"
	.string "Il utilisait l'électricité générée\n"
	.string "par ses POKéMON pour faire\p"
	.string "voler son avion.$"

PokemonJournal_Text_SpecialFeatureErika_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec ERIKA, le CHAMPION\n"
	.string "d'ARENE de CELADOPOLE!\p"
	.string "Si vous arrivez sans prévenir à\n"
	.string "l'ARENE de CELADOPOLE, \p"
	.string "vous risquez de la voir en train\n"
	.string "de piquer un roupillon.$"

PokemonJournal_Text_SpecialFeatureKoga_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec KOGA, le CHAMPION\n"
	.string "d'ARENE de PARMANIE!\p"
	.string "Il est incollable en médecine.\p"
	.string "On dit qu'il prépare lui-même\n"
	.string "ses médicaments pour soigner\p"
	.string "ses POKéMON.$"

PokemonJournal_Text_SpecialFeatureSabrina_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec MORGANE, le CHAMPION\n"
	.string "d'ARENE de SAFRANIA!\p"
	.string "Les gens racontent qu'elle peut\n"
	.string "communiquer avec ses POKéMON\p"
	.string "pendant les combats juste par\n"
	.string "la pensée.$"

PokemonJournal_Text_SpecialFeatureBlaine_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec AUGUSTE, le CHAMPION \n"
	.string "d'ARENE de CRAMOIS'ILE!\p"
	.string "Il passe tout son temps à créer\n"
	.string "des questions pour son quiz.$"

PokemonJournal_Text_SpecialFeatureLorelei_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec OLGA du CONSEIL 4!\p"
	.string "Connue pour sa logique et son\n"
	.string "style de combat très posé.\p"
	.string "OLGA cache un terrible secret.$"

PokemonJournal_Text_SpecialFeatureBruno_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec ALDO du CONSEIL 4!\p"
	.string "ALDO a rejoint le CONSEIL 4\n"
	.string "pour pouvoir affronter\p"
	.string "les meilleurs DRESSEURS du\n"
	.string "monde.$"

PokemonJournal_Text_SpecialFeatureAgatha_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec AGATHA du CONSEIL 4!\p"
	.string "Dans sa jeunesse, AGATHA était\n"
	.string "la rivale du PROF. CHEN.\p"
	.string "Ils s'affrontaient pour obtenir\n"
	.string "le titre du meilleur DRESSEUR.$"

PokemonJournal_Text_SpecialFeatureLance_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec PETER du CONSEIL 4!\p"
	.string "Le grand-père de PETER est\n"
	.string "le doyen du célèbre clan\p"
	.string "des maîtres dragon.$"

PokemonJournal_Text_SpecialFeatureProfOak_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec le PROF. CHEN, \n"
	.string "le chercheur POKéMON!\p"
	.string "Il s'occupe de sa petite-fille NINA\n"
	.string "et de {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak_FR::
	.string "Ce JOURNAL POKéMON date\n"
	.string "de plusieurs années…\p"
	.string "CONCOURS spécial du\n"
	.string "JOURNAL POKéMON.\p"
	.string "Le grand champion du concours\n"
	.string "POKéMON de printemps est\l"
	.string "NINA de BOURG PALETTE.$"

PokemonJournal_Text_SpecialFeatureMrFuji_FR::
	.string "JOURNAL POKéMON\p"
	.string "Avec MR. FUJI de la\n"
	.string "MAISON POKéMON!\p"
	.string "Editeur: Le timide MR. FUJI a\n"
	.string "décliné notre demande d'interview.\p"
	.string "Cet homme très gentil est très\n"
	.string "apprécié à LAVANVILLE.$"

