Text_CutTreeDown_FR::
	.string "Cet arbre semble pouvoir être\n"
	.string "COUPE.\p"
	.string "Voulez-vous utiliser COUPE?$"

Text_MonUsedMove_FR::
	.string "{STR_VAR_1} utilise {STR_VAR_2}.$"

Text_TreeCanBeCutDown_FR::
	.string "Cet arbre semble pouvoir être\n"
	.string "COUPE.$"

Text_UseRockSmash_FR::
	.string "Cette pierre peut être brisée.\n"
	.string "Voulez-vous utiliser ECLATE-ROC?$"

Text_MonMaySmashRock_FR::
	.string "C'est une pierre solide, mais un\n"
	.string "POKéMON pourrait la briser.$"

Text_UseStrength_FR::
	.string "C'est un gros rocher, mais un\n"
	.string "POKéMON peut être apte à le\l"
	.string "déplacer.\p"
	.string "Voulez-vous utiliser FORCE?$"

Text_MonUsedStrengthCanMoveBoulders_FR::
	.string "{STR_VAR_1} utilise FORCE.\p"
	.string "La capacité FORCE de {STR_VAR_1}\n"
	.string "permet de déplacer le rocher.$"

Text_MonMayPushBoulder_FR::
	.string "C'est un gros rocher, mais un\n"
	.string "POKéMON peut être apte à le\l"
	.string "déplacer.$"

Text_StrengthMadeMovingBouldersPossible_FR::
	.string "FORCE permet de déplacer le\n"
	.string "rocher.$"

Text_WallOfWaterCrashingDown_FR::
	.string "Un mur d'eau s'abat dans un vacarme\n"
	.string "assourdissant.$"

Text_UseWaterfall_FR::
	.string "C'est une grande chute d'eau.\n"
	.string "Voulez-vous utiliser CASCADE?$"

Text_MonUsedWaterfall_FR::
	.string "{STR_VAR_1} utilise CASCADE.$"

Text_MonMayGoUnderwater_FR::
	.string "La mer est profonde. Un POKéMON\n"
	.string "doit pouvoir aller sous l'eau ici.$"

Text_SeaIsDeepUseDive_FR::
	.string "La mer est profonde ici.\n"
	.string "Voulez-vous utiliser PLONGEE?$"

Text_MonUsedDive_FR::
	.string "{STR_VAR_1} utilise PLONGEE.$"

Text_MonMaySurface_FR::
	.string "Une lumière vient d'en haut.\n"
	.string "Un POKéMON doit pouvoir remonter\l"
	.string "à la surface.$"

Text_LightFilteringUseDive_FR::
	.string "Une lumière vient d'en haut.\n"
	.string "Voulez-vous utiliser PLONGEE?$"

Text_DiveCantBeUsedHere_FR::
	.string "Quelque chose empêche le retour\n"
	.string "à la surface.\p"
	.string "Il est impossible d'utiliser\n"
	.string "PLONGEE ici.$"

Text_LooksLikeNothingHere_FR::
	.string "Apparemment, il n'y a rien ici…$"
