@ Flavor text for interacting with various background objects

Text_Bookshelf_FR::
	.string "Des bouquins sur les POKéMON!$"

Text_NothingButPokemonBooks_FR::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap_FR::
	.string "Une CARTE.$"

Text_PokeMartShelf_FR::
	.string "Cool! Plein de machins sur les\n"
	.string "POKéMON!$"

Text_DishesPlatesNeatlyLinedUp_FR::
	.string "De la vaisselle est rangée\n"
	.string "dans ce placard.$"

Text_Kitchen_FR::
	.string "Quelqu'un a cuisiné ici,\n"
	.string "ça sent vraiment bon.$"

Text_Dresser_FR::
	.string "C'est une belle commode.\n"
	.string "On peut y ranger plein de trucs.$"

Text_Snacks_FR::
	.string "Il y a plusieurs sandwichs.$"

Text_PokemartSign_FR::
	.string "Faites le plein d'objets!\n"
	.string "BOUTIQUE POKéMON$"

Text_PokecenterSign_FR::
	.string "Soignez vos POKéMON!\n"
	.string "CENTRE POKéMON$"

Text_Indigo_UltimateGoal_FR::
	.string "PLATEAU INDIGO\p"
	.string "Le rêve de tout DRESSEUR!\n"
	.string "Quartier général de la LIGUE\l"
	.string "POKéMON$"

Text_Indigo_HighestAuthority_FR::
	.string "PLATEAU INDIGO\p"
	.string "La plus haute instance POKéMON.\n"
	.string "Quartier général de la LIGUE\l"
	.string "POKéMON$"

Text_Food_FR::
	.string "Il doit y avoir plein de bonnes\n"
	.string "choses à manger.$"

Text_Blueprints_FR::
	.string "C'est une sorte de plan. Il y a\n"
	.string "quelque chose d'écrit dessus.$"

Text_Painting_FR::
	.string "Une belle image d'un POKéMON.\n"
	.string "Il semble heureux.$"

Text_PowerPlantMachine_FR::
	.string "A quoi ça peut bien servir? Mieux\n"
	.string "vaut ne pas y toucher!$"

Text_Telephone_FR::
	.string "C'est un téléphone. Il vaut mieux\n"
	.string "ne pas l'utiliser.$"

Text_Computer_FR::
	.string "C'est rempli de mots et de chiffres\n"
	.string "incompréhensibles.$"

Text_AdvertisingPoster_FR::
	.string "C'est une publicité pour de\n"
	.string "nombreux articles.$"

Text_TastyFood_FR::
	.string "Mmm, quelle bonne odeur.\n"
	.string "Ça donne vraiment faim!$"

Text_TrashBin_FR::
	.string "Alors ici…\n"
	.string "… …\p"
	.string "Il n'y a absolument rien!$"

Text_Cup_FR::
	.string "C'est une tasse avec une\n"
	.string "marque de POKéMON.$"

Text_PolishedWindow_FR::
	.string "La fenêtre est super propre!$"

Text_BeautifulSkyWindow_FR::
	.string "A l'extérieur…\p"
	.string "Il fait un temps magnifique!$"

Text_BlinkingLights_FR::
	.string "Il y a plein de petites lampes\n"
	.string "qui clignotent.$"

Text_NeatlyLinedUpTools_FR::
	.string "Plusieurs outils sont rangés ici.$"

Text_ImpressiveMachine_FR::
	.string "C'est une sorte de machine.\n"
	.string "Elle est vraiment impressionnante.$"

Text_VideoGame_FR::
	.string "Le dernier jeu vidéo qui vient de\n"
	.string "sortir. Ça a l'air génial.$"

Text_Burglary_FR::
	.string "Il y a des signes d'effraction ici…$"

Text_PlayerFacingTVScreen_FR::
	.string "Une émission avec des POKéMON.\n"
	.string "Ça a l'air cool!$"
