Trade_Text_LookingForMonWannaTradeForMon_FR::
	.string "Je cherche un {STR_VAR_1}.\p"
	.string "Tu veux l'échanger\n"
	.string "contre un {STR_VAR_2}?$"

Trade_Text_AwwOhWell_FR::
	.string "Bon…\n"
	.string "Tant pis…$"

Trade_Text_WhatThatsNoMon_FR::
	.string "Mais c'est pas un {STR_VAR_1}!$"

Trade_Text_HeyThanks_FR::
	.string "Merciiii!$"

Trade_Text_IsntMyOldMonGreat_FR::
	.string "Il est cool mon {STR_VAR_2}, hein?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon_FR::
	.string "Bien le bonjour!\n"
	.string "On se fait un échange?\p"
	.string "{STR_VAR_1} contre\n"
	.string "{STR_VAR_2}, OK?$"

Trade_Text_WellIfYouDontWantTo_FR::
	.string "Mmmm…\n"
	.string "Pas cool…$"

Trade_Text_ThisIsntMon_FR::
	.string "Heu? C'est pas un {STR_VAR_1}.\p"
	.string "Essaie pas de m'arnaquer.$"

Trade_Text_Thanks_FR::
	.string "Merci, merci!$"

Trade_Text_HasTradedMonGrownStronger_FR::
	.string "Le {STR_VAR_2} que t'ai échangé,\n"
	.string "il est devenu plus fort?$"

Trade_Text_DoYouHaveMonWantToTradeForMon_FR::
	.string "Salut! T'as un {STR_VAR_1}?\p"
	.string "Contre un joli {STR_VAR_2}, OK?$"

Trade_Text_ThatsTooBad_FR::
	.string "Dommage.$"

Trade_Text_ThisIsNoMon_FR::
	.string "C'est pas un {STR_VAR_1}.\p"
	.string "Reviens me voir si tu\n"
	.string "en trouves un!$"

Trade_Text_ThanksYoureAPal_FR::
	.string "Merci beaucoup!$"

Trade_Text_HowIsMyOldMon_FR::
	.string "Comment va {STR_VAR_2}?\n"
	.string "Mon {STR_VAR_1} est terrible!$"
