Text_IdLoveToHearYourProfile_FR:
	.string "Ravie de te rencontrer!\p"
	.string "C'est pas gentil de ta part, tu\n"
	.string "pourrais au moins me répondre.\p"
	.string "Allez, présente-toi au moins.\n"
	.string "J'aimerais connaître ton profil.$"

Text_TellMeWhatsYourProfile_FR:
	.string "Parle-moi de toi. Tu veux bien\n"
	.string "me donner ton profil?$"

Text_ExplainProfile_FR:
	.string "Un profil s'écrit en utilisant quatre\n"
	.string "mots ou groupes de mots.\p"
	.string "Il y a plein de mots à choisir pour\n"
	.string "écrire ton profil.\p"
	.string "Ils sont tous classés dans des\n"
	.string "groupes différents.\p"
	.string "Tout d'abord, choisis un groupe,\n"
	.string "puis un mot ou un groupe de mots.\p"
	.string "… C'est vraiment pas\n"
	.string "compliqué, tu devrais essayer.$"

Text_WhatsYourProfile_FR:
	.string "Quel est ton profil?$"

Text_DontBeLikeThat_FR:
	.string "Aaah… Ne sois pas comme ça.\p"
	.string "Tu peux quand même me donner\n"
	.string "ton profil, non?$"

Text_DecidedNotTo_FR:
	.string "Oh, tu ne veux vraiment pas alors.\n"
	.string "C'est pas sympa…$"

Text_HiWeMeetAgain_FR:
	.string "Salut!\n"
	.string "On se retrouve encore!$"

Text_ChangeYourProfile_FR:
	.string "Veux-tu changer ton profil?$"

Text_WhatAreYouLikeNow_FR:
	.string "Quoi de neuf?\n"
	.string "J'aimerais vraiment savoir.$"

Text_LikeProfileWayItIs_FR:
	.string "OK, ton profil te convient\n"
	.string "tel quel.\p"
	.string "C'est vrai, j'aime assez aussi.$"

Text_ProfileSaysSomethingAboutYou_FR:
	.string "Mmmh…\p"
	.string "Ton profil en dit vraiment long\n"
	.string "sur toi.\p"
	.string "Maintenant que je te connais mieux,\n"
	.string "on va devenir inséparables!$"

Text_HeardThatBefore_FR:
	.string "Oh, j'ai déjà entendu ça avant…\p"
	.string "Mon cousin, qui habite très loin,\n"
	.string "dit souvent ça aussi.$"

Text_TellMoreNextTime_FR:
	.string "J'espère en apprendre plus sur\n"
	.string "toi la prochaine fois!$"
