Text_ObtainedTheX_FR::
	.string "Obtenu: {STR_VAR_2}!$"

Text_BagIsFull_FR::
	.string "Le SAC est plein…$"

Text_PutItemAway_FR::
	.string "{PLAYER} met {STR_VAR_2} dans\n"
	.string "{STR_VAR_3}.$"

Text_FoundOneItem_FR::
	.string "{PLAYER} trouve {STR_VAR_2}!$"

Text_TooBadBagFull_FR::
	.string "Dommage!\n"
	.string "Le SAC est plein.$"

Text_FoundXCoins_FR::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase_FR::
	.string "{PLAYER} met les JETONS\n"
	.string "dans la BOITE JETONS.$"

Text_CoinCaseIsFull_FR::
	.string "Dommage!\n"
	.string "La BOITE JETONS est pleine.$"

Text_NothingToPutThemIn_FR::
	.string "Dommage!\n"
	.string "Il n'y a rien pour les ranger.$"

Text_FoundXItems_FR::
	.string "{PLAYER} a trouvé\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)$"

Text_ObtainedTheDecor_FR::
	.string "Obtenu: {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor_FR::
	.string "Dommage! Il n'y a plus assez de\n"
	.string "place pour {STR_VAR_2}…$"

Text_DecorTransferredToPC_FR::
	.string "Transfert de {STR_VAR_2} sur\n"
	.string "le PC.$"
