Text_MayIHelpYou_FR::
	.string "Bonjour!\n"
	.string "Je peux vous aider?$"

Text_FillOutQuestionnaire_FR::
	.string "Il y a un questionnaire…\n"
	.string "Voulez-vous y répondre?$"

Text_QuestionnaireThankYou_FR::
	.string "Merci d'avoir pris le temps de\n"
	.string "répondre à notre questionnaire.\p"
	.string "Vos réponses nous permettront\n"
	.string "de mieux vous servir.$"

Text_YouKnowThoseWords_FR::
	.string "Oh, bonjour!\n"
	.string "Vous connaissez ces mots?\p"
	.string "Donc vous devez aussi\n"
	.string "connaître le CADEAU MYST.\p"
	.string "A partir de maintenant, vous allez\n"
	.string "recevoir des CADEAUX MYST.!$"

Text_YouCanAccessMysteryGift_FR::
	.string "Après avoir sauvegardé, vous\n"
	.string "aurez accès aux CADEAUX MYST.!$"

Text_ThankYouForAccessingMysteryGift_FR::
	.string "Merci d'utiliser le système\n"
	.string "CADEAU MYST.$"
