Text_MakingPreparations_FR::
	.string "じゅんびちゅうです！$"

Text_WantWhichFloor_FR::
	.string "Quel étage?$"

Text_BagItemCanBeRegistered_FR::
	.string "Un objet du SAC peut être sauvé\n"
	.string "comme fonction de SELECT.$"

@ Unused (email from R/S Rivals computer)
Text_TrainerSchoolEmail_FR::
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

Text_PlayerBootedUpPC_FR::
	.string "{PLAYER} allume le PC.$"

@ Unused
Text_LinkWasCanceled_FR::
	.string "つうしんは　キャンセルされました$"

@ Unused
Text_GiveNicknameToReceivedMon_FR::
	.string "Donner un surnom au {STR_VAR_2}\n"
	.string "reçu?$"

gText_PkmnFainted3_FR::
	.string "{STR_VAR_1} est KO…\p"
	.string "$"

Text_WelcomeWantToHealPkmn_FR::
	.string "Bienvenue dans notre CENTRE\n"
	.string "POKéMON!\p"
	.string "Voulez-vous que je m'occupe\n"
	.string "de vos POKéMON?$"

Text_TakeYourPkmnForFewSeconds_FR::
	.string "OK, je prends vos POKéMON un\n"
	.string "instant.$"

Text_WeHopeToSeeYouAgain_FR::
	.string "A bientôt!$"

Text_RestoredPkmnToFullHealth_FR::
	.string "Merci d'avoir attendu.\p"
	.string "Vos POKéMON sont en super forme.$"
