PokedexRating_Text_HowIsPokedexComingAlong_FR::
	.string "CHEN: Je suis content de te\n"
	.string "revoir. Où en es-tu avec ton\l"
	.string "POKéDEX?\p"
	.string "Voyons, voyons…$"

PokedexRating_Text_SeenXOwnedY_FR::
	.string "Niveau POKéDEX:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.\p"
	.string "{FONT_NORMAL}Observation du PROF. CHEN:$"

PokedexRating_Text_LessThan10_FR::
	.string "Tu ne vas pas assez dans les\n"
	.string "hautes herbes.\p"
	.string "Il t'en reste beaucoup à trouver!$"

PokedexRating_Text_LessThan20_FR::
	.string "Tu es sur la bonne voie!\p"
	.string "Un de mes ASSISTANTS te donnera\n"
	.string "la CS FLASH!$"

PokedexRating_Text_LessThan30_FR::
	.string "Il t'en reste plein à attraper\n"
	.string "pour remplir ton POKéDEX!\p"
	.string "Essaie d'en capturer d'autres!$"

PokedexRating_Text_LessThan40_FR::
	.string "Très bien! On voit bien que tu te\n"
	.string "donnes du mal.\p"
	.string "Un de mes ASSISTANTS a un\n"
	.string "CHERCH'OBJET pour toi!$"

PokedexRating_Text_LessThan50_FR::
	.string "Ton POKéDEX prend vraiment forme.\p"
	.string "Un de mes ASSISTANTS te donnera\n"
	.string "une PIECE RUNE.$"

PokedexRating_Text_LessThan60_FR::
	.string "Oh, tu as atteint 50 espèces\n"
	.string "différentes.\p"
	.string "Un de mes ASSISTANTS a un\n"
	.string "MULTI EXP pour toi!$"

PokedexRating_Text_LessThan70_FR::
	.string "Oh! C'est de mieux en mieux!$"

PokedexRating_Text_LessThan80_FR::
	.string "Excellent!\p"
	.string "Mais tu devrais aller pêcher plus\n"
	.string "de POKéMON marins!$"

PokedexRating_Text_LessThan90_FR::
	.string "Magnifique! Mais dis-moi, tu aimes\n"
	.string "collectionner, non?$"

PokedexRating_Text_LessThan100_FR::
	.string "Mirobolant!\n"
	.string "Ça n'a pas dû être facile!$"

PokedexRating_Text_LessThan110_FR::
	.string "Tu as atteint 100 espèces\n"
	.string "différentes! Quel talent!$"

PokedexRating_Text_LessThan120_FR::
	.string "Tu as même fait évoluer tes\n"
	.string "POKéMON! Génial!$"

PokedexRating_Text_LessThan130_FR::
	.string "Parfait! Fais des échanges pour\n"
	.string "en avoir encore plus!$"

PokedexRating_Text_LessThan140_FR::
	.string "Impressionnant! On dirait que tu\n"
	.string "as fait ça toute ta vie!$"

PokedexRating_Text_LessThan150_FR::
	.string "Chapeau bas!\n"
	.string "C'est toi le Prof maintenant!$"

PokedexRating_Text_Complete_FR::
	.string "Ton POKéDEX est complet!\n"
	.string "Félicitations!$"

PokedexRating_Text_NationalDexSeenXOwnedY_FR::
	.string "Et ton POKéDEX NATIONAL est:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.$"

PokedexRating_Text_LookForwardToFilledNationalDex_FR::
	.string "J'ai hâte de te voir remplir le\n"
	.string "POKéDEX NATIONAL!$"

PokedexRating_Text_YouveCompletedDex_FR::
	.string "Enfin…\p"
	.string "Tu as rempli le POKéDEX!\p"
	.string "Je suis vraiment impressionné.$"

PokedexRating_Text_Wroooaaarrr_FR::
	.string "Ouaaaaaah!!$"

PokedexRating_Text_HaHa_FR::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality_FR::
	.string "Merci, {PLAYER}!\n"
	.string "Merci de tout cœur!\l"
	.string "Tu as exaucé mon rêve!$"

PokedexRating_Text_LoveSeeingYourPokedex_FR::
	.string "CHEN: Ah, bienvenue!\p"
	.string "Dis-moi, à quoi ressemble ton\n"
	.string "POKéDEX?\p"
	.string "Ahahaha!\p"
	.string "Je sais bien à quoi ça ressemble,\n"
	.string "mais je veux y jeter un œil!\p"
	.string "Voyons voir…$"
