Text_CardKeyOpenedDoor_FR::
	.string "Bingo!\n"
	.string "La CARTE MAGN. a ouvert la porte!$"

Text_ItNeedsCardKey_FR::
	.string "Zut!\n"
	.string "Il faut une CARTE MAGN.!$"

Text_AccessedProfOaksPC_FR::
	.string "Connexion au PC du PROF. CHEN.\p"
	.string "Accès au système d'évaluation\n"
	.string "du POKéDEX.$"

Text_HavePokedexRated_FR::
	.string "Voulez-vous faire évaluer votre\n"
	.string "POKéDEX?$"

Text_ClosedLinkToProfOaksPC_FR::
	.string "PC du PROF. CHEN. Déconnexion…$"

Text_VoiceRangOutDontRunAway_FR::
	.string "Une voix:\n"
	.string "“Ne fuis pas!”$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest_FR::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe_FR::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight_FR::
	.string "それっ　ちがうよー！$"

Text_ISee_FR::
	.string "そっか‥$"

Text_TheDoorIsClosed_FR::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen_FR::
	.string "La porte est ouverte…$"
