gText_WouldYouLikeToSaveTheGame_FR::
	.string "Voulez-vous sauvegarder la partie?$"

gText_AlreadySaveFile_WouldLikeToOverwrite_FR::
	.string "Il y a déjà une sauvegarde.\n"
	.string ""
	.string "Voulez-vous la remplacer?$"

gText_SavingDontTurnOffThePower_FR::
	.string "SAUVEGARDE EN COURS…\n"
	.string ""
	.string "N'ETEIGNEZ PAS LA CONSOLE.$"

gText_PlayerSavedTheGame_FR::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_SaveFailed2_FR::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile_FR::
	.string "ATTENTION!\p"
	.string "Une autre partie est déjà\n"
	.string "sauvegardée.\p"
	.string "Si vous sauvegardez maintenant,\n"
	.string "l'aventure, les objets et les\p"
	.string "POKéMON de l'autre fichier\n"
	.string "seront perdus.\p"
	.string "Etes-vous sûr de vouloir écraser\n"
	.string "l'autre fichier?$"
