@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight_FR::
	.string "Hmm…\nBien sûr…$"

PalletTown_Text_OhLookLook_FR::
	.string "Oh!\nRegarde, regarde!$"

PalletTown_Text_ReadItReadIt_FR::
	.string "Lis-ça!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu_FR::
	.string "ASTUCE\pSTART pour ouvrir le menu.$"

PalletTown_Text_SignsAreUsefulArentThey_FR::
	.string "Les panneaux sont utiles, hein?$"

PalletTown_Text_LookCopiedTrainerTipsSign_FR::
	.string "Regarde, regarde!\p"
	.string "J'ai copié ce qui était écrit sur\n"
	.string "un des panneaux d'ASTUCES.$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy_FR::
	.string "ASTUCE\p"
	.string "START pour ouvrir le menu.$"
