VSSeeker_Text_BatteryNotChargedNeedXSteps_FR::
	.string "La batterie n'est pas assez\n"
	.string "chargée.\p"
	.string "Il faut faire {STR_VAR_1} pas pour\n"
	.string "la recharger complètement.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange_FR::
	.string "Il n'y a pas de DRESSEUR aux\n"
	.string "alentours pour combattre.\p"
	.string "Le CHERCHE VS s'est éteint.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady_FR::
	.string "Les autres DRESSEURS ne sont\n"
	.string "pas prêts à se battre.\p"
	.string "Il va falloir patienter un peu.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro_FR::
	.string "Hé! On s'est déjà vu dans la FORET\n"
	.string "DE JADE!$"

Route3_Text_BenRematchIntro_FR::
	.string "Yahaa!\p"
	.string "J'adore trop les shorts!\n"
	.string "Viens t'battre!$"

Route3_Text_JaniceRematchIntro_FR::
	.string "Excuse-moi!\n"
	.string "Tu me cherches ou quoi?$"

Route3_Text_GregRematchIntro_FR::
	.string "T'es un DRESSEUR toi, hein?\n"
	.string "A l'attaque!$"

Route3_Text_SallyRematchIntro_FR::
	.string "Dis donc toi…\n"
	.string "Tu veux qu'on s'boxe?$"

Route3_Text_CalvinRematchIntro_FR::
	.string "Hé! T'as pas de short!\n"
	.string "T'es vraiment naze!$"

Route3_Text_JamesRematchIntro_FR::
	.string "Je vais te combattre avec les\n"
	.string "POKéMON que j'ai commencé\l"
	.string "à dresser.$"

Route3_Text_RobinRematchIntro_FR::
	.string "Quoi?\n"
	.string "Qu'est-ce que tu me veux?$"

Route4_Text_CrissyRematchIntro_FR::
	.string "J'attrape toujours des POKéMON\n"
	.string "champignon au MONT SELENITE.$"

Route6_Text_RickyRematchIntro_FR::
	.string "Oh! C'est toi qui arrête pas de\n"
	.string "nous espionner, hein?$"

Route6_Text_NancyRematchIntro_FR::
	.string "Excuse-moi!\p"
	.string "Tu vois pas que c'est une\n"
	.string "conversation privée?$"

Route6_Text_KeigoRematchIntro_FR::
	.string "J'essaie de trouver autre chose\n"
	.string "que des POKéMON INSECTE, mais…$"

Route6_Text_JeffRematchIntro_FR::
	.string "Hein?\n"
	.string "Tu veux encore te battre?$"

Route6_Text_IsabelleRematchIntro_FR::
	.string "Qui ça? Moi?\n"
	.string "OK. Tu vas voir!$"

Route6_Text_ElijahRematchIntro_FR::
	.string "Hé, ça faisait longtemps, hein?\p"
	.string "Tu vas voir le résultat de mon\n"
	.string "entraînement.$"

Route8_Text_AidanRematchIntro_FR::
	.string "Tu maîtrises bien tes POKéMON.\n"
	.string "Mais tu bosses tes maths?$"

Route8_Text_StanRematchIntro_FR::
	.string "Une fois encore, le sort en\n"
	.string "est jeté!$"

Route8_Text_GlennRematchIntro_FR::
	.string "Il te faut une bonne stratégie!\n"
	.string "Tu devrais suivre mes conseils.$"

Route8_Text_PaigeRematchIntro_FR::
	.string "J'ai attrapé beaucoup de NIDORAN.\n"
	.string "J'veux pas qu'ils évoluent, mais…$"

Route8_Text_LeslieRematchIntro_FR::
	.string "L'école c'est cool, mais je pense\n"
	.string "toujours que les POKéMON\l"
	.string "c'est mieux!$"

Route8_Text_AndreaRematchIntro_FR::
	.string "MIAOUSS et PERSIAN sont \n"
	.string "si mignons. Miaou!$"

Route8_Text_MeganRematchIntro_FR::
	.string "J'ai l'air idiote à rester debout\n"
	.string "comme ça, mais je peux\p"
	.string "encore me battre.$"

Route8_Text_RichRematchIntro_FR::
	.string "Je suis un joueur errant! Et je\n"
	.string "suis sur la route de la victoire.$"

Route8_Text_JuliaRematchIntro_FR::
	.string "Qu'il est mimi, gentil et trognon ce\n"
	.string "POKéMON! Il est à qui?\l"
	.string "Hein? A qui?\p"
	.string "Tu le sais toujours pas?$"

Route8_Text_RicardoRematchIntro_FR::
	.string "Toujours fidèle à ma bécane,\n"
	.string "ouais!$"

Route8_Text_JarenRematchIntro_FR::
	.string "OK, ne t'attends pas à ce que je\n"
	.string "retienne mes coups.$"

Route8_Text_EliRematchIntro_FR::
	.string "ELI: On est encore plus fortes\n"
	.string "qu'avant! Tu vas voir!$"

Route8_Text_AnneRematchIntro_FR::
	.string "ANNE: Plus rien ne peut nous\n"
	.string "résister!$"

Route9_Text_AliciaRematchIntro_FR::
	.string "Le destin voulait qu'on se\n"
	.string "retrouve. Prépare-toi à perdre!$"

Route9_Text_ChrisRematchIntro_FR::
	.string "T'as toujours les mêmes POKéMON?$"

Route9_Text_DrewRematchIntro_FR::
	.string "Je passe par la GROTTE pour\n"
	.string "aller à LAVANVILLE.\p"
	.string "Mais j'arrête pas de rencontrer du\n"
	.string "monde en chemin.$"

Route9_Text_CaitlinRematchIntro_FR::
	.string "Ne prends pas ce ton avec moi!$"

Route9_Text_JeremyRematchIntro_FR::
	.string "Bwahaha! Allez…\n"
	.string "Je m'ennuyais, ça tombe bien…$"

Route9_Text_BriceRematchIntro_FR::
	.string "T'as du cran toi!$"

Route9_Text_BrentRematchIntro_FR::
	.string "Je me réveille de bonne heure tous\n"
	.string "les matins pour l'entraînement\p"
	.string "depuis notre dernière rencontre.\n"
	.string "Prépare-toi!$"

Route9_Text_AlanRematchIntro_FR::
	.string "Hahahaha!\n"
	.string "Cette fois, je gagnerai!$"

Route9_Text_ConnerRematchIntro_FR::
	.string "En avant! Allez-y mes\n"
	.string "POKéMON INSECTE!$"

Route10_Text_MarkRematchIntro_FR::
	.string "T'es dingue des POKéMON?\n"
	.string "Tu veux voir ma collection?$"

Route10_Text_ClarkRematchIntro_FR::
	.string "Snnnf, j'arrête pas d'éternuer!\n"
	.string "J'ai dû attraper froid!$"

Route10_Text_HermanRematchIntro_FR::
	.string "Hé, toi!\n"
	.string "Tu veux voir mes POKéMON?$"

Route10_Text_HeidiRematchIntro_FR::
	.string "Je suis retournée dans une ARENE.\n"
	.string "Mais j'ai encore perdu…$"

Route10_Text_TrentRematchIntro_FR::
	.string "Ah! L'air de la montagne!\p"
	.string "C'est si bon que je peux\n"
	.string "pas partir!$"

Route10_Text_CarolRematchIntro_FR::
	.string "J'ai la tête qui tourne.\n"
	.string "J'devrais vraiment me reposer…$"

Route11_Text_HugoRematchIntro_FR::
	.string "Tu veux gagner ou perdre?$"

Route11_Text_JasperRematchIntro_FR::
	.string "J'adore les défis!$"

Route11_Text_EddieRematchIntro_FR::
	.string "On y va?\n"
	.string "OK, mais triche pas!$"

Route11_Text_BraxtonRematchIntro_FR::
	.string "Attention!\n"
	.string "Je pose encore des câbles!$"

Route11_Text_DillonRematchIntro_FR::
	.string "Ça fait un bout de temps que\n"
	.string "je suis DRESSEUR.\p"
	.string "Je vais gagner, tu vas voir.$"

Route11_Text_DirkRematchIntro_FR::
	.string "HAHAHA!\n"
	.string "J'ai jamais perdu!\p"
	.string "Enfin, si je me souviens bien.$"

Route11_Text_DarianRematchIntro_FR::
	.string "Je n'ai jamais gagné…\p"
	.string "Ça doit être mon destin.$"

Route11_Text_YasuRematchIntro_FR::
	.string "Je suis le plus fort de ma classe!\n"
	.string "Je m'entraîne nuit et jour.$"

Route11_Text_BernieRematchIntro_FR::
	.string "Fais gaffe aux câbles! Je te\n"
	.string "l'ai pourtant déjà dit.$"

Route11_Text_DaveRematchIntro_FR::
	.string "Mes POKéMON sont prêts!\n"
	.string "Cette fois, on va gagner!$"

Route12_Text_NedRematchIntro_FR::
	.string "Ça mord! Ça doit être une\n"
	.string "grosse prise!$"

Route12_Text_ChipRematchIntro_FR::
	.string "Tu viens d'arriver?\n"
	.string "Pour pêcher, faut être patient!$"

Route12_Text_JustinRematchIntro_FR::
	.string "Je cherche toujours une\n"
	.string "PIERRE LUNE.\p"
	.string "T'en as trouvé une?$"

Route12_Text_LucaRematchIntro_FR::
	.string "L'électricité a toujours été\n"
	.string "ma spécialité!$"

Route12_Text_HankRematchIntro_FR::
	.string "Le PECHEUR FOU contre le KID des\n"
	.string "POKéMON!\p"
	.string "Deuxième round!$"

Route12_Text_ElliotRematchIntro_FR::
	.string "Bon, j'ai du pain sur la planche!$"

Route12_Text_AndrewRematchIntro_FR::
	.string "Si, ça mord?\p"
	.string "Va falloir que tu me battes\n"
	.string "pour savoir!$"

Route12_Text_JesRematchIntro_FR::
	.string "JES: Je gagnerai, et après,\n"
	.string "j'épouse GIA.$"

Route12_Text_GiaRematchIntro_FR::
	.string "GIA: JES! Tu sais depuis quand\n"
	.string "j'attends.\p"
	.string "Si on gagne, on se marie!$"

Route13_Text_SebastianRematchIntro_FR::
	.string "Mes POKéMON oiseau se souviennent\n"
	.string "de toi!$"

Route13_Text_SusieRematchIntro_FR::
	.string "Depuis tout petit, je veux devenir\n"
	.string "le meilleur DRESSEUR!$"

Route13_Text_ValerieRematchIntro_FR::
	.string "Woaa!\n"
	.string "T'as encore plus de BADGES!$"

Route13_Text_GwenRematchIntro_FR::
	.string "Mes POKéMON tout mignons veulent\n"
	.string "encore se battre.$"

Route13_Text_AlmaRematchIntro_FR::
	.string "J'ai éclaté ma tirelire pour\n"
	.string "acheter plus de CARBONE.$"

Route13_Text_PerryRematchIntro_FR::
	.string "Le vent souffle par là.\n"
	.string "Cool! J'perdrai pas cette fois!$"

Route13_Text_LolaRematchIntro_FR::
	.string "Oh, de retour?\p"
	.string "Mais bien sûr que je veux bien\n"
	.string "qu'on s'affronte de nouveau.$"

Route13_Text_SheilaRematchIntro_FR::
	.string "Comment oses-tu? Tu ne te souviens\n"
	.string "pas de ce joli visage?$"

Route13_Text_JaredRematchIntro_FR::
	.string "Kess tu mates?$"

Route13_Text_RobertRematchIntro_FR::
	.string "J'aime bien mes POKéMON oiseau!\n"
	.string "Ouais… Ça change pas.$"

Route14_Text_CarterRematchIntro_FR::
	.string "J'ai utilisé des CT pour apprendre\n"
	.string "plein de capacités à mes POKéMON!$"

Route14_Text_MitchRematchIntro_FR::
	.string "Mes POKéMON oiseau veulent\n"
	.string "se battre. Ils sont prêts.$"

Route14_Text_BeckRematchIntro_FR::
	.string "Tu utilises des CT toi aussi? Ça\n"
	.string "sert à rien de juste les garder.$"

Route14_Text_MarlonRematchIntro_FR::
	.string "As-tu appris à tes POKéMON oiseau\n"
	.string "à voler?$"

Route14_Text_DonaldRematchIntro_FR::
	.string "La légende des mirages ailés…\n"
	.string "T'en as déjà entendu parler, hein?$"

Route14_Text_BennyRematchIntro_FR::
	.string "J'suis pas au jeu!\n"
	.string "Mais bon…$"

Route14_Text_LukasRematchIntro_FR::
	.string "Hé, j'me souviens de toi!\n"
	.string "Allez, viens!\p"
	.string "Tu vas voir la tête de tes\n"
	.string "POKéMON!$"

Route14_Text_IsaacRematchIntro_FR::
	.string "Encore là?\n"
	.string "Tu vas déguster!$"

Route14_Text_GeraldRematchIntro_FR::
	.string "On s'en va, y'a plus de place!$"

Route14_Text_MalikRematchIntro_FR::
	.string "Combat POKéMON?\n"
	.string "Tremble, minus!$"

Route14_Text_KiriRematchIntro_FR::
	.string "JOY: KATE, on va gagner, tu\n"
	.string "vas voir!$"

Route14_Text_JanRematchIntro_FR::
	.string "KATE: Allez JOY, on y va!\n"
	.string "On peut pas perdre encore!$"

Route15_Text_KindraRematchIntro_FR::
	.string "Je vais continuer à tester les\n"
	.string "POKéMON que j'ai échangés!$"

Route15_Text_BeckyRematchIntro_FR::
	.string "Tu fais pas le poids, je devrais\n"
	.string "pouvoir te battre cette fois!$"

Route15_Text_EdwinRematchIntro_FR::
	.string "Quand je sifflote, les POKéMON\n"
	.string "oiseau viennent autour de moi.\p"
	.string "C'est trop mignon.$"

Route15_Text_ChesterRematchIntro_FR::
	.string "Hmm? Mes oiseaux ont peur!\n"
	.string "C'est toi qui leur fais peur?$"

Route15_Text_GraceRematchIntro_FR::
	.string "Oh!\n"
	.string "T'es bien jeune toi!\p"
	.string "Mais…\n"
	.string "Je me souviens de toi!$"

Route15_Text_OliviaRematchIntro_FR::
	.string "J'ai des POKéMON parce que je vis\n"
	.string "toute seule!\p"
	.string "Ça a pas changé.$"

Route15_Text_ErnestRematchIntro_FR::
	.string "Oh, minus!\n"
	.string "Regarde ça!$"

Route15_Text_AlexRematchIntro_FR::
	.string "Rends-moi la thune que tu\n"
	.string "me dois!$"

Route15_Text_CeliaRematchIntro_FR::
	.string "Rien de plus cool que d'échanger\n"
	.string "des POKéMON!\p"
	.string "T'es pas d'accord?$"

Route15_Text_YazminRematchIntro_FR::
	.string "Je veux me battre avec\n"
	.string "mes POKéMON! Encore!$"

Route15_Text_MyaRematchIntro_FR::
	.string "MIA: Comme on se retrouve!\p"
	.string "Tu m'aides encore pour\n"
	.string "l'entraînement de mon frère?$"

Route15_Text_RonRematchIntro_FR::
	.string "RON: Ma sœur est encore plus\n"
	.string "balèze qu'avant…$"

Route16_Text_LaoRematchIntro_FR::
	.string "Kess t'as ta?$"

Route16_Text_KojiRematchIntro_FR::
	.string "Joli vélo!\n"
	.string "Donne-le moi vite!$"

Route16_Text_LukeRematchIntro_FR::
	.string "Viens t'battre!\n"
	.string "P'tit rat!$"

Route16_Text_HideoRematchIntro_FR::
	.string "Hé!\n"
	.string "Ça fait deux fois là!$"

Route16_Text_CamronRematchIntro_FR::
	.string "J'ai faim, j'suis furax et j'vais\n"
	.string "t'exploser!$"

Route16_Text_RubenRematchIntro_FR::
	.string "BASTOONNNN!$"

Route16_Text_JedRematchIntro_FR::
	.string "ALI: T'as déjà vu des amoureux\n"
	.string "comme nous? Moi, j'crois pas!$"

Route16_Text_LeaRematchIntro_FR::
	.string "LISE: Parfois, je suis terrorisée\n"
	.string "par la force de notre amour.$"

Route17_Text_RaulRematchIntro_FR::
	.string "Pff… Un gosse, ça a jamais\n"
	.string "de thunes!$"

Route17_Text_IsaiahRematchIntro_FR::
	.string "Kess tu veux, toi l'mioche?$"

Route17_Text_VirgilRematchIntro_FR::
	.string "Alors, on se balade?$"

Route17_Text_BillyRematchIntro_FR::
	.string "On est des MOTARDS!\n"
	.string "Des vrais, des purs, des durs,\l"
	.string "des méchants… Si si!$"

Route17_Text_NikolasRematchIntro_FR::
	.string "Tu sens pas l'orage venir?$"

Route17_Text_ZeekRematchIntro_FR::
	.string "Mes POKéMON veulent pas évoluer.\n"
	.string "Ben pourquoi?$"

Route17_Text_JamalRematchIntro_FR::
	.string "J'ai vraiment besoin d'un peu\n"
	.string "d'exercice!$"

Route17_Text_CoreyRematchIntro_FR::
	.string "No future!$"

Route17_Text_JaxonRematchIntro_FR::
	.string "Vraiment mignon ce VELO!\n"
	.string "Mais comment ça se conduit?$"

Route17_Text_WilliamRematchIntro_FR::
	.string "Du vent gamin!\n"
	.string "J'suis épuisé!$"

Route18_Text_WiltonRematchIntro_FR::
	.string "Je suis toujours à la recherche de\n"
	.string "POKéMON.\p"
	.string "Mais c'est vraiment pas facile.$"

Route18_Text_RamiroRematchIntro_FR::
	.string "Cui cui cui!\n"
	.string "J'fais l'oiseau, tu reconnais?$"

Route18_Text_JacobRematchIntro_FR::
	.string "T'es sur mon gazon, dégage!\p"
	.string "Je t'ai déjà dit que je voulais\n"
	.string "pas te voir.$"

Route19_Text_RichardRematchIntro_FR::
	.string "On se baigne?$"

Route19_Text_ReeceRematchIntro_FR::
	.string "Attends! Mouille-toi la nuque avant\n"
	.string "de plonger!$"

Route19_Text_MatthewRematchIntro_FR::
	.string "J'aime nager!\p"
	.string "Toi, j'suis sûr que tu préfères\n"
	.string "le SURF, non?$"

Route19_Text_DouglasRematchIntro_FR::
	.string "D'où vient le vent?\n"
	.string "Tu sais pas?$"

Route19_Text_DavidRematchIntro_FR::
	.string "Je cherche toujours des\n"
	.string "POKéMON dans les grands fonds!$"

Route19_Text_TonyRematchIntro_FR::
	.string "La mer, l'écume, les vagues…\n"
	.string "C'est beau!!!\p"
	.string "Et ça fait oublier les défaites.$"

Route19_Text_AnyaRematchIntro_FR::
	.string "J'adorerais nager avec tes\n"
	.string "POKéMON.\p"
	.string "Tu m'en donnes un si je gagne?$"

Route19_Text_AliceRematchIntro_FR::
	.string "Nager c'est cool!\n"
	.string "Faut juste penser à pas couler!$"

Route19_Text_AxleRematchIntro_FR::
	.string "Ces eaux sont très dangereuses.\n"
	.string "Tu devrais pas être là!$"

Route19_Text_ConnieRematchIntro_FR::
	.string "J'ai nagé jusque-là avec mes amis.\n"
	.string "C'est trop crevant…\p"
	.string "Tu tiens vraiment à ce qu'on\n"
	.string "se batte encore?$"

Route19_Text_LiaRematchIntro_FR::
	.string "VIVI: T'es au courant? Mon frère\n"
	.string "est un vrai DRESSEUR!\p"
	.string "Mais il a encore besoin\n"
	.string "d'entraînement!$"

Route19_Text_LucRematchIntro_FR::
	.string "SAM: C'est ma sœur qui m'a\n"
	.string "tout appris.$"

Route20_Text_BarryRematchIntro_FR::
	.string "La mer est peu profonde ici,\n"
	.string "n'est-ce pas?$"

Route20_Text_ShirleyRematchIntro_FR::
	.string "Je suis en vacances ici.\n"
	.string "T'es pas dèg?$"

Route20_Text_TiffanyRematchIntro_FR::
	.string "J'aime faire la planche avec les\n"
	.string "poissons!$"

Route20_Text_IreneRematchIntro_FR::
	.string "Et toi, qu'est-ce que tu fais pour\n"
	.string "les vacances?$"

Route20_Text_DeanRematchIntro_FR::
	.string "Mate un peu mon corps de rêve!\p"
	.string "Il est encore plus parfait\n"
	.string "qu'avant.$"

Route20_Text_DarrinRematchIntro_FR::
	.string "Tu fais quoi sur ce POKéMON?\n"
	.string "Tu sais pas nager?$"

Route20_Text_RogerRematchIntro_FR::
	.string "Mes POKéMON oiseau m'ont\n"
	.string "déposé ici!$"

Route20_Text_NoraRematchIntro_FR::
	.string "Mon frère m'a offert des perles.\n"
	.string "Et t'sais quoi? Elles ont grossi!$"

Route20_Text_MissyRematchIntro_FR::
	.string "J'ai nagé depuis CRAMOIS'ILE!\n"
	.string "Comme je te le dis!$"

Route20_Text_MelissaRematchIntro_FR::
	.string "Il y a un LABO POKéMON à\n"
	.string "CRAMOIS'ILE.\p"
	.string "Mon papa y travaille.$"

Route21_North_Text_RonaldRematchIntro_FR::
	.string "Tu veux savoir s'il y a des\n"
	.string "poissons ici?$"

Route21_North_Text_WadeRematchIntro_FR::
	.string "J'ai eu une belle prise.\n"
	.string "Tu veux voir?$"

Route21_North_Text_SpencerRematchIntro_FR::
	.string "La mer me purifie le corps\n"
	.string "et l'esprit.$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro_FR::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro_FR::
	.string "J'ai attrapé mes POKéMON\n"
	.string "dans l'océan.\p"
	.string "Et c'est là que je les entraîne.$"

Route21_South_Text_JeromeRematchIntro_FR::
	.string "Hop là!\n"
	.string "J'suis encore en plein triathlon!$"

Route21_South_Text_RolandRematchIntro_FR::
	.string "Ah! Le ciel, le soleil et la mer!\n"
	.string "… Ça craint.$"

Route21_South_Text_ClaudeRematchIntro_FR::
	.string "J'le crois pas.\n"
	.string "Tu fais encore peur aux poissons.$"

Route21_South_Text_NolanRematchIntro_FR::
	.string "Reste donc avec moi, le temps\n"
	.string "d'avoir une touche!$"

Route21_North_Text_LilRematchIntro_FR::
	.string "LY: Un autre combat?\n"
	.string "IAN, t'en dis quoi?$"

Route21_North_Text_IanRematchIntro_FR::
	.string "IAN: Ma sœur est une vraie\n"
	.string "feignasse!\p"
	.string "Tu m'aides à la secouer?$"

Route25_Text_JoeyRematchIntro_FR::
	.string "Faudra me passer sur le corps.$"

Route25_Text_DanRematchIntro_FR::
	.string "Je suis allé à une super fête\n"
	.string "avec mon père.\p"
	.string "C'était sur L'OCEANE, à\n"
	.string "CARMIN SUR MER!$"

Route25_Text_FlintRematchIntro_FR::
	.string "J'suis cool.\n"
	.string "Et j'ai une copine aussi!\p"
	.string "Cette fois, elle va vraiment voir\n"
	.string "comme je suis cool.$"

Route25_Text_KelseyRematchIntro_FR::
	.string "Mon p'tit copain, c'est le plus beau\n"
	.string "de tous! J'ai le plus beau de tous\l"
	.string "les copains du monde!$"

Route25_Text_ChadRematchIntro_FR::
	.string "Y'a comme qui dirait un DRESSEUR\n"
	.string "de trop ici!$"

Route25_Text_HaleyRematchIntro_FR::
	.string "Mon copain a des POKéMON trognons!\n"
	.string "Je suis jalouse!$"

Route25_Text_FranklinRematchIntro_FR::
	.string "Je viens du MONT SELENITE, mais\n"
	.string "j'ai encore la force de me battre!$"

Route25_Text_NobRematchIntro_FR::
	.string "Je cherche le collectionneur de\n"
	.string "POKéMON!$"

Route25_Text_WayneRematchIntro_FR::
	.string "Tu cherches encore LEO?\n"
	.string "Ok, mais d'abord, BASTOONNN!$"

Route24_Text_ShaneRematchIntro_FR::
	.string "J'ai suivi tes traces de pas\n"
	.string "dans l'herbe!$"

Route24_Text_EthanRematchIntro_FR::
	.string "OK!\n"
	.string "J'vais te broyer!$"

Route24_Text_ReliRematchIntro_FR::
	.string "Tu fais rien là?\n"
	.string "Un petit combat?$"

Route24_Text_TimmyRematchIntro_FR::
	.string "T'aimes la vue?$"

Route24_Text_AliRematchIntro_FR::
	.string "La dernière fois…\p"
	.string "J'ai perdu mais je suis sûre que\n"
	.string "c'était un manque de pot!$"

Route24_Text_CaleRematchIntro_FR::
	.string "C'est le PONT PEPITE!\p"
	.string "Tu nous as déjà vus. Alors tu peux\n"
	.string "pas relever le défi…\p"
	.string "Mais par contre, j'ai rien contre\n"
	.string "un petit combat.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro_FR::
	.string "Bercée par les vagues, je vois\n"
	.string "même plus le temps passer.$"

OneIsland_KindleRoad_Text_MariaRematchIntro_FR::
	.string "Le temps est super! Je vais pas\n"
	.string "te laisser gâcher cette journée.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro_FR::
	.string "J'aurais dû faire attention aux\n"
	.string "coups de soleil.$"

OneIsland_KindleRoad_Text_FinnRematchIntro_FR::
	.string "La montagne de l'oiseau de feu\n"
	.string "fait de l'ombre.$"

OneIsland_KindleRoad_Text_GarrettRematchIntro_FR::
	.string "J'ai l'impression que je vais\n"
	.string "gagner cette fois.$"

OneIsland_KindleRoad_Text_TommyRematchIntro_FR::
	.string "Attends, attends un peu!\n"
	.string "J'ai une belle prise là!$"

OneIsland_KindleRoad_Text_SharonRematchIntro_FR::
	.string "Un petit match pour pas perdre\n"
	.string "la main?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro_FR::
	.string "On a pas manqué un seul jour\n"
	.string "d'entraînement!$"

OneIsland_KindleRoad_Text_SheaRematchIntro_FR::
	.string "Tous les jours avant le p'tit déj,\n"
	.string "je fais le tour de l'île à la nage…\p"
	.string "Trois fois!$"

OneIsland_KindleRoad_Text_HughRematchIntro_FR::
	.string "Habille-toi un peu mieux pour\n"
	.string "combattre! C'est quoi cette tenue?$"

OneIsland_KindleRoad_Text_BryceRematchIntro_FR::
	.string "Tout semble différent quand on\n"
	.string "est seul en pleine nature.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro_FR::
	.string "J'ai mangé trop de saucisses,\n"
	.string "il me faudrait un peu d'exercice.$"

OneIsland_KindleRoad_Text_KiaRematchIntro_FR::
	.string "KIA: Mon frère et moi, on fait\n"
	.string "vraiment la paire!\p"
	.string "On peut pas perdre…\n"
	.string "Cette fois…$"

OneIsland_KindleRoad_Text_MikRematchIntro_FR::
	.string "MIK: On a vraiment peur de rien!\n"
	.string "Mais frappe pas trop fort…$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro_FR::
	.string "On se bat encore?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro_FR::
	.string "Mais dis-moi, tu vas où\n"
	.string "comme ça?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro_FR::
	.string "Dans pas longtemps, je nagerai\n"
	.string "sans ma bouée. Si, si…$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro_FR::
	.string "Allez mes POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro_FR::
	.string "Combien de fois je dois le répéter.\n"
	.string "Ne t'approche pas!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro_FR::
	.string "BEA: On est encore plus balèzes.\n"
	.string "Beaucoup plus!$"

ThreeIsland_BondBridge_Text_MegRematchIntro_FR::
	.string "EVA: Tu pourras jamais gagner!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro_FR::
	.string "Salut!\p"
	.string "Tu prends bien soin de tes\n"
	.string "POKéMON, j'espère.$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro_FR::
	.string "Ces mains m'apporteront\n"
	.string "la victoire!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro_FR::
	.string "Je dois le répéter?\p"
	.string "J'essaie de peindre. Alors,\n"
	.string "hors de ma vue!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro_FR::
	.string "Aucun progrès…\n"
	.string "Impossible d'avoir le bon angle…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro_FR::
	.string "Tu vas me donner la chance de\n"
	.string "me mesurer à toi?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro_FR::
	.string "La piscine pour mes POKéMON\n"
	.string "est presque prête.\p"
	.string "Faudra passer la voir à l'occasion.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro_FR::
	.string "Je suis un bon sprinter. Et j'ai\n"
	.string "encore progressé.$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro_FR::
	.string "Dis, on se fait un petit combat\n"
	.string "pour passer le temps?$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro_FR::
	.string "Je suis l'aîné des FRERES PIAF.\n"
	.string "Tu te souviens?\p"
	.string "C'est ça, c'est moi qui aime\n"
	.string "les coups de bec!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro_FR::
	.string "Le cadet des FRERES PIAF,\n"
	.string "c'est moi!\p"
	.string "Moi mon truc, c'est les ailes.\n"
	.string "Un petit combat?$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro_FR::
	.string "Je suis le plus jeune des\n"
	.string "FRERES PIAF.\p"
	.string "Je pensais pas qu'on se reverrait.$"

SixIsland_OutcastIsland_Text_TylorRematchIntro_FR::
	.string "Toujours rien. Il me faudrait une\n"
	.string "petite victoire pour changer.$"

SixIsland_OutcastIsland_Text_MymoRematchIntro_FR::
	.string "Pfffff…\p"
	.string "J'arrive du port de l'ILE 6 à la\n"
	.string "nage. J'en peux… plus…$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro_FR::
	.string "Faut toujours que tu te pointes\n"
	.string "quand je nage.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro_FR::
	.string "AVA: Je ferais bien un petit\n"
	.string "deux contre deux! OK?$"

SixIsland_OutcastIsland_Text_GebRematchIntro_FR::
	.string "GED: Avec ma sœur, on a\n"
	.string "peur de rien.$"

SixIsland_GreenPath_Text_JaclynRematchIntro_FR::
	.string "… Hein?\p"
	.string "Je voulais aller chez moi, mais le\n"
	.string "TELEPORT m'a amenée ici!$"

SixIsland_WaterPath_Text_RoseRematchIntro_FR::
	.string "Tiens, bonjour.\n"
	.string "Sens-tu la brise se lever?$"

SixIsland_WaterPath_Text_EdwardRematchIntro_FR::
	.string "Hehehe, je m'entraîne toujours\n"
	.string "en secret.$"

SixIsland_WaterPath_Text_SamirRematchIntro_FR::
	.string "Quoi? T'en as assez de voir des\n"
	.string "NAGEURS comme moi?\p"
	.string "Bah alors faut pas te baigner!$"

SixIsland_WaterPath_Text_DeniseRematchIntro_FR::
	.string "Snnnf…\n"
	.string "Mon copain est encore occupé.$"

SixIsland_WaterPath_Text_EarlRematchIntro_FR::
	.string "Allez, tu veux pas me dire où\n"
	.string "sont les montagnes?$"

SixIsland_WaterPath_Text_MiuRematchIntro_FR::
	.string "MIU: Salut les POKéMON!\n"
	.string "C'est le moment de se battre!$"

SixIsland_WaterPath_Text_MiaRematchIntro_FR::
	.string "MIA: Petits POKéMON…\n"
	.string "On se fait un petit combat?$"

SixIsland_RuinValley_Text_StanlyRematchIntro_FR::
	.string "Il y a toujours des mystères\n"
	.string "inexpliqués dans ce monde.$"

SixIsland_RuinValley_Text_FosterRematchIntro_FR::
	.string "Tiens, on se connaît, non?\n"
	.string "Pourquoi t'es de retour?$"

SixIsland_RuinValley_Text_LarryRematchIntro_FR::
	.string "Il paraît qu'il y a des pierres\n"
	.string "mystérieuses sur l'île.\p"
	.string "Tu me tiens au courant si tu\n"
	.string "découvres un truc, OK?$"

SixIsland_RuinValley_Text_DarylRematchIntro_FR::
	.string "Une revanche?\n"
	.string "Allez, c'est parti!$"

SixIsland_RuinValley_Text_HectorRematchIntro_FR::
	.string "Je connais bien la région, je\n"
	.string "peux pas perdre.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro_FR::
	.string "J'ai senti que tu venais.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro_FR::
	.string "Quelque part sur cette île, un\n"
	.string "POKéMON spécial se repose.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro_FR::
	.string "Hi hi hi!\p"
	.string "Je vais me débarrasser de toi\n"
	.string "sans efforts.$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro_FR::
	.string "YO! T'es membre de mon fan club?\n"
	.string "C'est pour ça que t'es là?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro_FR::
	.string "Cette île est trop vaste… Il\n"
	.string "faut des heures pour patrouiller…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro_FR::
	.string "Je ne pardonne pas à ceux qui\n"
	.string "maltraitent les POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro_FR::
	.string "EVE: Avec JOE, on te laissera\n"
	.string "aucune chance!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro_FR::
	.string "JOE: Avec EVE, j'ai l'impression\n"
	.string "d'être invincible.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro_FR::
	.string "Faisons un combat. Je suis au\n"
	.string "top de ma forme!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro_FR::
	.string "Peu importe que tu aies les\n"
	.string "POKéMON les plus forts…\p"
	.string "Ça ne sert à rien si tu ne sais pas\n"
	.string "les utiliser correctement!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro_FR::
	.string "Je travaille pour protéger\n"
	.string "l'environnement.\p"
	.string "Et toi, tu fais quoi pour protéger\n"
	.string "la nature?$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro_FR::
	.string "T'as toujours cette pauvre paire\n"
	.string "de chaussures?$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro_FR::
	.string "Tu dois être plus coriace, non?\n"
	.string "Allez, montre-moi!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro_FR::
	.string "J'ai reçu la meilleure éducation\n"
	.string "pour être aussi forte.\p"
	.string "Je ne peux pas perdre cette fois!\n"
	.string "Oh que non!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro_FR::
	.string "PAUL: Ma chère NYA, la victoire\n"
	.string "est à nous!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro_FR::
	.string "NYA: Je ne laisserai jamais tomber\n"
	.string "mon mentor. PAUL, on va gagner!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro_FR::
	.string "As-tu découvert quelque chose\n"
	.string "sur cette grotte?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro_FR::
	.string "On raconte qu'un POKéMON\n"
	.string "mystique dort ici.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro_FR::
	.string "Mon prof m'apprend comment\n"
	.string "mieux peindre.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro_FR::
	.string "Aujourd'hui, en plus des leçons,\n"
	.string "nous sommes revenus voir la grotte.$"

