CeladonCity_GameCorner_Text_TryPokemonPrinter_FR::
	.string "C'est une IMPRIMANTE POKéMON!\p"
	.string "Elle peut imprimer des POKéMON\n"
	.string "sur ta CARTE DRESSEUR.\p"
	.string "Ça ne coûte que 50¥.\n"
	.string "On essaie?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney_FR::
	.string "Pas assez d'argent…$"

CeladonCity_GameCorner_Text_ChoosePrintType_FR::
	.string "Veuillez choisir le type\n"
	.string "d'impression.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto_FR::
	.string "Un joli sourire pour la photo!\n"
	.string "Un… Deux… Et trois!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard_FR::
	.string "La CARTE DRESSEUR\n"
	.string "est prête.$"

FourIsland_House2_Text_WishICouldShowOffStickers_FR::
	.string "J'ai réuni des tas de STICKERS.\p"
	.string "J'ai trop envie de les montrer à\n"
	.string "tout le monde…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag_FR::
	.string "Oh, excellent!\n"
	.string "Tu es au bon endroit!\p"
	.string "Regarde! Tu vois, hein?\n"
	.string "Tu vois?\p"
	.string "C'est mes STICKERS!\n"
	.string "J'en ai des tonnes.\p"
	.string "J'suis sûr que tu voudrais\n"
	.string "m'en prendre!\p"
	.string "Je t'en donnerai un si tu\n"
	.string "me racontes un truc\p"
	.string "dingue sur toi.\p"
	.string "Alors, qu'est-ce que tu\n"
	.string "me racontes?$"

FourIsland_House2_Text_BragAboutSomethingForMe_FR::
	.string "Raconte-moi un truc dingue et\n"
	.string "je te donnerai un STICKER.$"

FourIsland_House2_Text_BragAboutWhatToday_FR::
	.string "Oh, Salut!\n"
	.string "Tu viens encore te vanter?\p"
	.string "Qu'est-ce que tu vas me\n"
	.string "raconter aujourd'hui?$"

FourIsland_House2_Text_WowHoFLowest_FR::
	.string "Pfiuu, t'as pu entrer au PANTHEON.\n"
	.string "Pas mal! Tiens, je te donne ça!$"

FourIsland_House2_Text_WowHoFLow_FR::
	.string "Pfiuu, t'as pu entrer au PANTHEON\n"
	.string "plusieurs fois déjà.\p"
	.string "Impressionnant!\n"
	.string "Tiens, je te donne ça!$"

FourIsland_House2_Text_WowHoFHigh_FR::
	.string "Waouh! Tu as pu entrer au\n"
	.string "PANTHEON aussi souvent?\p"
	.string "C'est vraiment incroyable. Ouais!\p"
	.string "La LIGUE POKéMON ne doit plus\n"
	.string "avoir de secrets pour toi.\p"
	.string "Tiens, tu mérites ça!$"

FourIsland_House2_Text_WowHoFHighest_FR::
	.string "J'y crois pas! Personne ne peut\n"
	.string "y entrer aussi souvent!\p"
	.string "T'es vraiment incroyable!\n"
	.string "Tiens, c'est pour toi!$"

FourIsland_House2_Text_HoFStickerApplied_FR::
	.string "Le STICKER PANTHEON a été\n"
	.string "ajouté à la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF_FR::
	.string "Hmm…\p"
	.string "Reviens avec une meilleure\n"
	.string "histoire la prochaine fois.$"

FourIsland_House2_Text_LivingLegendHoF_FR::
	.string "Oh non, ça le fait pas!\p"
	.string "T'es pratiquement une légende\n"
	.string "vivante.\p"
	.string "J'ai pas de STICKER digne de toi.$"

FourIsland_House2_Text_WowEggsLowest_FR::
	.string "Waouh, c'est des OEUFS POKéMON?\n"
	.string "J'en avais jamais vu!\p"
	.string "Pas mal, pas mal!\n"
	.string "Tiens, ça me fait plaisir.$"

FourIsland_House2_Text_WowEggsLow_FR::
	.string "Pfiu, t'as vraiment fait éclore\n"
	.string "autant d'OEUFS?\p"
	.string "C'est impressionnant, ouais!\n"
	.string "Prends ça, tu le vaux bien!$"

FourIsland_House2_Text_WowEggsHigh_FR::
	.string "T'as vraiment fait éclore beaucoup\n"
	.string "d'OEUFS!\p"
	.string "Tu les couves ou quoi?\n"
	.string "Tiens, tu mérites ça.$"

FourIsland_House2_Text_WowEggsHighest_FR::
	.string "… Incroyable!\p"
	.string "Qu'est-ce qui peut bien se\n"
	.string "cacher derrière cet amour pour\p"
	.string "les OEUFS?\n"
	.string "C'est vraiment incroyable!\p"
	.string "Tu m'impressionnes tellement\n"
	.string "que je vais te donner ça.$"

FourIsland_House2_Text_EggStickerApplied_FR::
	.string "Le STICKER OEUF a été ajouté\n"
	.string "à la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs_FR::
	.string "Hum…\p"
	.string "Reviens avec une meilleure\n"
	.string "histoire, OK?$"

FourIsland_House2_Text_LivingLegendEggs_FR::
	.string "Oh non, ça le fait pas!\p"
	.string "T'es pratiquement une légende\n"
	.string "vivante.\p"
	.string "J'ai pas de STICKER digne de toi.$"

FourIsland_House2_Text_WowLinkWinsLowest_FR::
	.string "Hum, tu te défends pas mal en\n"
	.string "combat en link.\p"
	.string "Tiens, je te donne ça pour\n"
	.string "la peine.$"

FourIsland_House2_Text_WowLinkWinsLow_FR::
	.string "Tu as déjà battu pas mal de tes\n"
	.string "amis en combat en link\p"
	.string "à ce que je vois.\p"
	.string "Tu m'impressionnes.\n"
	.string "Tiens, c'est pour toi.$"

FourIsland_House2_Text_WowLinkWinsHigh_FR::
	.string "Waouh, tu as battu tes amis un\n"
	.string "nombre incroyable de fois.\p"
	.string "Ils vont finir par t'en vouloir…\n"
	.string "Tiens, c'est pour toi!$"

FourIsland_House2_Text_WowLinkWinsHighest_FR::
	.string "C'est diiiingue! Comment tu fais\n"
	.string "pour gagner autant?\p"
	.string "J'suis trop fier de connaître\n"
	.string "quelqu'un comme toi!\p"
	.string "Tu dois être un vrai cauchemar\n"
	.string "pour les autres DRESSEURS!\p"
	.string "Tiens, accepte ça de ma part!$"

FourIsland_House2_Text_VictoryStickerApplied_FR::
	.string "Le STICKER VICTOIRE a été\n"
	.string "ajouté à la CARTE DRESSEUR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins_FR::
	.string "Hum…\p"
	.string "Reviens avec une meilleure\n"
	.string "histoire, OK?$"

FourIsland_House2_Text_LivingLegendLinkWins_FR::
	.string "Oh non, ça le fait pas!\p"
	.string "T'es pratiquement une légende\n"
	.string "vivante.\p"
	.string "J'ai pas de STICKER digne de toi.$"
