
@ Unused, from R/S
Text_DoorOpenedFarAway_FR::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall_FR::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments_FR::
	.string "Je suis vraiment désolée.\p"
	.string "Le CLUB SANS FIL POKéMON\n"
	.string "est encore en préparation.$"

Text_AppearsToBeUndergoingAdjustments_FR::
	.string "Ils sont en train d'effectuer\n"
	.string "des réglages…$"

Text_HandedOverItem_FR::
	.string "{PLAYER} remet {STR_VAR_1}.$"

Text_GiveNicknameToThisMon_FR::
	.string "Voulez-vous donner un surnom\n"
	.string "à {STR_VAR_1}?$"
