SilphCo_7F_Text_HaveMonForSavingUs_DE::
	.string "Oh! Du bist kein ROCKET! Kommst\n"
	.string "du, um uns zu retten? Klasse!\l"
	.string "Vielen Dank!\p"
	.string "Nimm dieses POKéMON als\n"
	.string "Dankeschön.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee_DE::
	.string "{PLAYER} erhält ein LAPRAS von\n"
	.string "einem SILPH-Angestellten!$"

SilphCo_7F_Text_ExplainLapras_DE::
	.string "Es heißt LAPRAS und ist sehr\n"
	.string "intelligent.\p"
	.string "Es hat bisher bei uns im Labor\n"
	.string "gelebt. Aber bei dir ist es besser\l"
	.string "aufgehoben!\p"
	.string "Du wirst LAPRAS sicher ein guter\n"
	.string "TRAINER sein!\p"
	.string "Es ist ein guter Schwimmer und\n"
	.string "kann dich übers Wasser tragen!$"

SilphCo_7F_Text_RocketBossWentToBoardroom_DE::
	.string "TEAM ROCKETS BOSS ging in den\n"
	.string "Sitzungssaal!\p"
	.string "Ob unser PRÄSIDENT wohlauf ist?$"

SilphCo_7F_Text_OhNo_DE::
	.string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast_DE::
	.string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall_DE::
	.string "Das TEAM ROCKET ist hinter dem\n"
	.string "MEISTERBALL her, mit dem man\l"
	.string "jedes POKéMON fangen kann!$"

SilphCo_7F_Text_CanceledMasterBallProject_DE::
	.string "Wir haben das Projekt gestoppt.\n"
	.string "Der MEISTERBALL in TEAM ROCKETS\l"
	.string "Händen? Niemals!$"

SilphCo_7F_Text_BadIfTeamRocketTookOver_DE::
	.string "Es wäre fatal, wenn das TEAM\n"
	.string "ROCKET die SILPH CO. oder unsere\l"
	.string "POKéMON übernehmen würde!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket_DE::
	.string "Wow!\p"
	.string "Du bist ganz allein mit dem TEAM\n"
	.string "ROCKET fertig geworden?$"

SilphCo_7F_Text_ReallyDangerousHere_DE::
	.string "Hier ist es sehr gefährlich!\n"
	.string "Du wirst mich nicht retten können!$"

SilphCo_7F_Text_ThankYouSoMuch_DE::
	.string "Endlich gerettet!\n"
	.string "Ich danke dir!$"

SilphCo_7F_Text_Grunt3Intro_DE::
	.string "Du bist ganz schön mutig!$"

SilphCo_7F_Text_Grunt3Defeat_DE::
	.string "Licht aus!$"

SilphCo_7F_Text_Grunt3PostBattle_DE::
	.string "Wenn du nur so durch die Gegend\n"
	.string "läufst, findest du den BOSS nie!$"

SilphCo_7F_Text_JoshuaIntro_DE::
	.string "Haha!\p"
	.string "Du dachtest wohl, ich arbeite für\n"
	.string "die SILPH CO.?$"

SilphCo_7F_Text_JoshuaDefeat_DE::
	.string "Feierabend! Ich geh nach Hause!$"

SilphCo_7F_Text_JoshuaPostBattle_DE::
	.string "Kaum trocken hinter den Ohren, aber\n"
	.string "schon ein begabter TRAINER!$"

SilphCo_7F_Text_Grunt1Intro_DE::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_7F_Text_Grunt1Defeat_DE::
	.string "Tut mir Leid, Brüder...$"

SilphCo_7F_Text_Grunt1PostBattle_DE::
	.string "Warte nur, meine Brüder werden\n"
	.string "mich rächen!!!$"

SilphCo_7F_Text_Grunt2Intro_DE::
	.string "Ein Kind im Gebäude?\n"
	.string "Das musst du sein!$"

SilphCo_7F_Text_Grunt2Defeat_DE::
	.string "Na toll!\n"
	.string "Ich hab verloren!$"

SilphCo_7F_Text_Grunt2PostBattle_DE::
	.string "Geh nach Hause, bevor mein BOSS\n"
	.string "dich in den Boden stampft!$"

SilphCo_7F_Text_RivalWhatKeptYou_DE::
	.string "{RIVAL}: Was hat dich aufgehalten,\n"
	.string "{PLAYER}?$"

SilphCo_7F_Text_RivalIntro_DE::
	.string "{RIVAL}: Hahaha! Ich wusste, du\n"
	.string "würdest hier vorbeikommen!\p"
	.string "Ich schätze, das TEAM ROCKET hat\n"
	.string "dir ganz schön zugesetzt!\p"
	.string "Ich hab dich in SAFFRONIA CITY\n"
	.string "gesehen und mich gefragt, ob du\l"
	.string "seitdem besser geworden bist!$"

SilphCo_7F_Text_RivalDefeat_DE::
	.string "Mann!\n"
	.string "Du bist so gut, dass du gegen den\l"
	.string "ROCKET BOSS antreten kannst!$"

SilphCo_7F_Text_RivalVictory_DE::
	.string "{RIVAL}“おまえなあ‥\p"
	.string "こんな　うでまえじゃ\n"
	.string "まだまだ‥\l"
	.string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle_DE::
	.string "Also, {PLAYER}!\n"
	.string "Ich ziehe dann weiter!\p"
	.string "Wenn ich in den POKéDEX sehe,\n"
	.string "erkenne ich, wie stark die POKéMON\l"
	.string "sind und wie sie sich entwickeln!\p"
	.string "Ich werde zur POKéMON LIGA gehen.\n"
	.string "Dann werde ich die TOP VIER\l"
	.string "ausstechen!\p"
	.string "Bald bin ich der mächtigste\n"
	.string "TRAINER der Welt!\p"
	.string "Viel Glück, {PLAYER}!\n"
	.string "Und trainiere schön weiter!\l"
	.string "Ciao!$"

SilphCo_7F_Text_FloorSign_DE::
	.string "SILPH CO. BÜRO DES PRÄSIDENTEN\n"
	.string "6 OG$"

