Route8_WestEntrance_Text_ThirstyOnGuardDuty_FR::
	.string "Je suis de garde ici…\n"
	.string "Je crève de soif!\p"
	.string "Oh, la route est fermée.\n"
	.string "On ne passe pas!$"

Route8_WestEntrance_Text_ThatTeaLooksTasty_FR::
	.string "Oh, ce THE…\n"
	.string "Il a l'air délicieux…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards_FR::
	.string "Hein? Tu veux bien m'en donner?\n"
	.string "Super, merci!\p"
	.string "… …\n"
	.string "Gloup, gloup… …\p"
	.string "Tu peux passer si tu veux\n"
	.string "aller à SAFRANIA.\p"
	.string "Je vais partager ce THE avec les\n"
	.string "autres gardes!$"

Route8_WestEntrance_Text_HiHowsItGoing_FR::
	.string "Salut! Merci pour le verre!$"

