Route8_WestEntrance_Text_ThirstyOnGuardDuty_DE::
	.string "Ich schiebe hier Wache.\n"
	.string "Ohhh... ich bin so durstig...\p"
	.string "Halt! Stopp!\n"
	.string "Der Durchgang ist gesperrt!$"

Route8_WestEntrance_Text_ThatTeaLooksTasty_DE::
	.string "Oh, dieser TEE…\n"
	.string "Er riecht so lecker…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards_DE::
	.string "Häh? Ich kann ihn haben?\n"
	.string "Wow, das ist nett, danke!\l"
	.string "……\l"
	.string "Gluck, gluck…\l"
	.string "……\l"
	.string "Schluck…\l"
	.string "Falls du nach SAFFRONIA CITY\l"
	.string "möchtest…\l"
	.string "……\l"
	.string "Dann darfst du passieren.\p"
	.string "Ich teile den TEE mit den anderen\n"
	.string "Wächtern!$"

Route8_WestEntrance_Text_HiHowsItGoing_DE::
	.string "Hallo! Danke für die Erfrischung!$"

