SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross_DE::
	.string "Skara, Skara, SKARABORN!\n"
	.string "Unter Käfern hochwohlgeboren!\l"
	.string "Fühle seinen royalen Zorn,\l"
	.string "Skara, Skara, SKARABORN!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross_DE::
	.string "Wow!\n"
	.string "Das ist SKARABORN!\p"
	.string "Darf ich bitte messen, wie groß\n"
	.string "es ist?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward_DE::
	.string "Ui! Es ist {STR_VAR_2} cm lang! So etwas\n"
	.string "habe ich noch nie gesehen!\l"
	.string "Du verdienst eine Belohnung!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne_DE::
	.string "Ich möchte ein noch größeres\n"
	.string "SKARABORN sehen.\p"
	.string "Oh, wie ich sie verehre, die\n"
	.string "großen SKARABORN.$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore_DE::
	.string "Häh? {STR_VAR_2} cm groß…\n"
	.string "Oh, aha! Es ist genauso groß\l"
	.string "wie das zuvor!$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest_DE::
	.string "Oh, es ist nur {STR_VAR_2} cm groß.\n"
	.string "Das SKARABORN zuvor war größer.\p"
	.string "Das größte SKARABORN, das\n"
	.string "du mir gebracht hast, war\l"
	.string "{STR_VAR_3} cm groß.$"

SixIsland_WaterPath_House1_Text_ThisWontDo_DE::
	.string "Oh, nein! Da ist etwas falsch!\p"
	.string "SKARABORN ist mehr ein Macho\n"
	.string "und cool dazu mit einem Horn!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull_DE::
	.string "Dein BEUTEL ist voll.\n"
	.string "Meine Belohnung geht nicht\l"
	.string "mehr hinein!$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches_DE::
	.string "Das größte SKARABORN, das\n"
	.string "ich je sah war\p"
	.string "{STR_VAR_3} cm groß!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort_DE::
	.string "Es ist eine leere Tabelle!\p"
	.string "Man kann darin irgendwelche\n"
	.string "Rekorde auflisten!$"

