SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross_IT::
    .string "Hera, hera, HERACROSS!\n"
    .string "Così splendido e gigante,\l"
    .string "tu sei l'unico, sei il boss!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross_IT::
    .string "Ehi, ma è HERACROSS!\p"
    .string "Ti prego, ti prego, posso\n"
    .string "misurarlo?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward_IT::
    .string "Misura {STR_VAR_2} cm!\n"
    .string "È il più grande che abbia mai\l"
    .string "visto! Meriti un premio!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne_IT::
    .string "Voglio vedere un HERACROSS molto,\n"
    .string "ma molto più grande di questo!\p"
    .string "Gli HERACROSS grandi sono la\n"
    .string "mia passione!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore_IT::
    .string "Questo HERACROSS misura\n"
    .string "{STR_VAR_2} cm, proprio come quello\l"
    .string "di prima! Buuuh!!!$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest_IT::
    .string "Misura soltanto {STR_VAR_2} cm. Non è\n"
    .string "il più grande che abbia mai visto!\p"
    .string "Il più grande che mi hai portato\n"
    .string "misurava {STR_VAR_3} cm!$"

SixIsland_WaterPath_House1_Text_ThisWontDo_IT::
    .string "Ehi, ma questo non è HERACROSS!\n"
    .string "HERACROSS è molto bello, con quel\l"
    .string "suo corno imponente!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull_IT::
    .string "Il tuo ZAINO è pieno. Non\n"
    .string "posso darti il premio che\l"
    .string "ti spetta!$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches_IT::
    .string "L'HERACROSS più grande che ho\n"
    .string "visto finora misurava:\p"
    .string "{STR_VAR_3} cm!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort_IT::
    .string "Sembra una specie di\n"
    .string "tabella.\p"
    .string "Vi sono spazi per registrare\n"
    .string "delle cifre, pare.$"

