SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross_ES::
    .string "¡Hera, hera, HERACROSS!\n"
    .string "¡Es muy grande, es el mejor!\l"
    .string "¡Hera, hera, HERACROSS!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross_ES::
    .string "¡Aaaaaaah!\n"
    .string "¡Tienes un HERACROSS!\p"
    .string "Porfa, porfa, ¿puedo ver cuánto\n"
    .string "mide?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward_ES::
    .string "¡Guau, {STR_VAR_2} cm!\n"
    .string "¡Nunca he visto nada igual!\l"
    .string "¡Toma, te mereces este premio!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne_ES::
    .string "Me encantaría ver un HERACROSS\n"
    .string "mucho más grande que ése.\p"
    .string "¡Es que me alucinan los HERACROSS\n"
    .string "grandes!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore_ES::
    .string "¿Mmm? {STR_VAR_2} cm...\n"
    .string "¡Pero si es lo mismo que antes!$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest_ES::
    .string "Vaya, {STR_VAR_2} cm sólo...\n"
    .string "El HERACROSS de antes era mayor.\p"
    .string "Medía {STR_VAR_3} cm, ése ha sido el\n"
    .string "HERACROSS más grande que me\l"
    .string "has traído hasta ahora.$"

SixIsland_WaterPath_House1_Text_ThisWontDo_ES::
    .string "¡No, no y no!\p"
    .string "HERACROSS es mucho mejor,\n"
    .string "es más guay y se ve más fuerte.\l"
    .string "¡Y tiene un cuerno chulísimo!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull_ES::
    .string "Tienes la MOCHILA hasta arriba.\n"
    .string "No hay sitio para mi premio.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches_ES::
    .string "El mayor HERACROSS que he\n"
    .string "medido hasta ahora alcanzaba:\p"
    .string "¡{STR_VAR_3} cm!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort_ES::
    .string "Es una especie de cuadro y\n"
    .string "está en blanco.\p"
    .string "Tiene casillas para anotar cosas.$"
