ViridianCity_Gym_Text_GiovanniIntro_ES::
    .string "¡Je, je, je!\n"
    .string "¡Ésta es mi guarida!\p"
    .string "¡Quería volver a formar al TEAM\n"
    .string "ROCKET desde aquí!\p"
    .string "¡Pero has vuelto a encontrarme!\n"
    .string "¡Estoy que me subo por las\l"
    .string "paredes! ¡Esta vez, verás!\p"
    .string "¡Volverás a enfrentarte al gran\n"
    .string "GIOVANNI, al mejor de los\l"
    .string "ENTRENADORES!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat_ES::
    .string "¡Ja!\n"
    .string "¡Ha sido un duro combate!\l"
    .string "¡Y has ganado!\p"
    .string "¡Como premio, toma esta MEDALLA\n"
    .string "TIERRA!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle_ES::
    .string "¡He perdido, ya no soy digno\n"
    .string "de dirigir a mis secuaces!\p"
    .string "¡Se acabó el TEAM ROCKET!\p"
    .string "¡Dedicaré mi vida al estudio\n"
    .string "de los POKéMON!\p"
    .string "¡Espero que nos volvamos a ver!\n"
    .string "¡Adiós!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis_ES::
    .string "¡Con la MEDALLA TIERRA, todos\n"
    .string "los POKéMON te obedecerán!\p"
    .string "¡Es una prueba de tu maestría\n"
    .string "entrenando POKéMON!\p"
    .string "¡Con ella podrás acceder\n"
    .string "a la LIGA POKéMON!\p"
    .string "¡Es mi regalo por desafiar\n"
    .string "a la LIGA POKéMON!$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni_ES::
    .string "¡{PLAYER} obtuvo la MT26\n"
    .string "de manos de GIOVANNI!$"

ViridianCity_Gym_Text_ExplainTM26_ES::
    .string "¡La MT26 es TERREMOTO!\p"
    .string "¡Es muy potente, causa un\n"
    .string "temblor devastador!\p"
    .string "La inventé cuando dirigía este\n"
    .string "GIMNASIO, hace ya mucho tiempo...$"

ViridianCity_Gym_Text_YouDoNotHaveSpace_ES::
    .string "¡Llevas muchas cosas!$"

ViridianCity_Gym_Text_YujiIntro_ES::
    .string "¡Oye!\n"
    .string "Ya no debe de quedarte nada\l"
    .string "de energía, ¿no?$"

ViridianCity_Gym_Text_YujiDefeat_ES::
    .string "¡Me he quedado sin fuerza!$"

ViridianCity_Gym_Text_YujiPostBattle_ES::
    .string "¡Necesitas potencia para luchar\n"
    .string "contra el LÍDER del GIMNASIO!$"

ViridianCity_Gym_Text_AtsushiIntro_ES::
    .string "¡Groaar!\n"
    .string "¡Me estoy mosqueando!$"

ViridianCity_Gym_Text_AtsushiDefeat_ES::
    .string "¡Rargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle_ES::
    .string "¡No me merezco nada!$"

ViridianCity_Gym_Text_JasonIntro_ES::
    .string "¡Mis POKéMON y yo hacemos\n"
    .string "muy buena música!$"

ViridianCity_Gym_Text_JasonDefeat_ES::
    .string "¡Estás en perfecta armonía!$"

ViridianCity_Gym_Text_JasonPostBattle_ES::
    .string "¿Sabes quién es el LÍDER de\n"
    .string "nuestro GIMNASIO?$"

ViridianCity_Gym_Text_KiyoIntro_ES::
    .string "¡El karate es lo máximo en artes\n"
    .string "marciales!$"

ViridianCity_Gym_Text_KiyoDefeat_ES::
    .string "¡Ayyyy!$"

ViridianCity_Gym_Text_KiyoPostBattle_ES::
    .string "Si mis POKéMON fueran buenos\n"
    .string "karatekas...$"

ViridianCity_Gym_Text_WarrenIntro_ES::
    .string "¡Los más hábiles ganan con estilo!$"

ViridianCity_Gym_Text_WarrenDefeat_ES::
    .string "¡He perdido el control!$"

ViridianCity_Gym_Text_WarrenPostBattle_ES::
    .string "¡El LÍDER me va a reñir!$"

ViridianCity_Gym_Text_TakashiIntro_ES::
    .string "¡Soy el REY del KARATE!\n"
    .string "¡Te tengo en mis manos!$"

ViridianCity_Gym_Text_TakashiDefeat_ES::
    .string "¡Aaah!$"

ViridianCity_Gym_Text_TakashiPostBattle_ES::
    .string "¿La LIGA POKéMON? ¿Tú?\n"
    .string "¿Pero quién te crees que eres?$"

ViridianCity_Gym_Text_ColeIntro_ES::
    .string "¡Tus POKéMON se arrodillarán\n"
    .string "de un solo latigazo!$"

ViridianCity_Gym_Text_ColeDefeat_ES::
    .string "¡Auch!\n"
    .string "¡Vaya latigazo!$"

ViridianCity_Gym_Text_ColePostBattle_ES::
    .string "¡Espera!\n"
    .string "¡No he tenido ningún cuidado!$"

ViridianCity_Gym_Text_SamuelIntro_ES::
    .string "¡El GIMNASIO de VERDE estuvo\n"
    .string "cerrado mucho tiempo, pero nuestro\l"
    .string "LÍDER ha vuelto!$"

ViridianCity_Gym_Text_SamuelDefeat_ES::
    .string "¿Me has ganado?$"

ViridianCity_Gym_Text_SamuelPostBattle_ES::
    .string "¡Accederás a la LIGA POKéMON\n"
    .string "si ganas a nuestro LÍDER!$"

ViridianCity_Gym_Text_GymGuyAdvice_ES::
    .string "¡Hola, aspirante al título!\p"
    .string "¡Ni yo conozco la identidad del\n"
    .string "LÍDER de VERDE!\p"
    .string "¡Debe de ser el más duro de todos\n"
    .string "los LÍDERES de GIMNASIO!\p"
    .string "¡Dicen que estos ENTRENADORES usan\n"
    .string "los POKéMON del tipo TIERRA!$"

ViridianCity_Gym_Text_GymGuyPostVictory_ES::
    .string "¿Qué dices? ¿Que GIOVANNI era\n"
    .string "el LÍDER del GIMNASIO?$"

ViridianCity_Gym_Text_GymStatue_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CIUDAD VERDE: (?)\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CIUDAD VERDE: GIOVANNI\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
