RocketHideout_B1F_Text_Grunt1Intro_IT::
    .string "Chi sei?\n"
    .string "Come hai fatto ad\l"
    .string "arrivare fin qui?$"

RocketHideout_B1F_Text_Grunt1Defeat_IT::
    .string "Ahi!\n"
    .string "Colpito!$"

RocketHideout_B1F_Text_Grunt1PostBattle_IT::
    .string "Sfiderai TEAM ROCKET?$"

RocketHideout_B1F_Text_Grunt2Intro_IT::
    .string "Hai rovinato i nostri piani!$"

RocketHideout_B1F_Text_Grunt2Defeat_IT::
    .string "È finita!$"

RocketHideout_B1F_Text_Grunt2PostBattle_IT::
    .string "Non la passerai liscia, pulce!$"

RocketHideout_B1F_Text_Grunt3Intro_IT::
    .string "Allarme! Intrusione!$"

RocketHideout_B1F_Text_Grunt3Defeat_IT::
    .string "Non ce la faccio!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle_IT::
    .string "La SPETTROSONDA?\n"
    .string "Non so dove sia!$"

RocketHideout_B1F_Text_Grunt4Intro_IT::
    .string "Cosa fai qui?$"

RocketHideout_B1F_Text_Grunt4Defeat_IT::
    .string "Niente da fare!$"

RocketHideout_B1F_Text_Grunt4PostBattle_IT::
    .string "Bene, parlerò! Se vuoi vedere il\n"
    .string "CAPO, prendi l'ascensore!$"

RocketHideout_B1F_Text_Grunt5Intro_IT::
    .string "Hai perso la strada, piccola\n"
    .string "peste?$"

RocketHideout_B1F_Text_Grunt5Defeat_IT::
    .string "Perché?$"

RocketHideout_B1F_Text_Grunt5PostBattle_IT::
    .string "Oh! In qualche modo, sembra\n"
    .string "che il trambusto della lotta abbia\l"
    .string "aperto la porta!$"

