RocketHideout_B1F_Text_Grunt1Intro_DE::
	.string "Wie kommst du hierher?$"

RocketHideout_B1F_Text_Grunt1Defeat_DE::
	.string "Autsch!\n"
	.string "Geschlagen!$"

RocketHideout_B1F_Text_Grunt1PostBattle_DE::
	.string "Willst du dich mit dem TEAM ROCKET\n"
	.string "anlegen?$"

RocketHideout_B1F_Text_Grunt2Intro_DE::
	.string "Du hast Mut, hier hereinzuplatzen!$"

RocketHideout_B1F_Text_Grunt2Defeat_DE::
	.string "Mist! Versagt!$"

RocketHideout_B1F_Text_Grunt2PostBattle_DE::
	.string "Unsere Rache wird grauenvoll, du\n"
	.string "Rotzblag!$"

RocketHideout_B1F_Text_Grunt3Intro_DE::
	.string "Alarm!\n"
	.string "Eindringlinge!$"

RocketHideout_B1F_Text_Grunt3Defeat_DE::
	.string "Ich konnte ihn nicht stoppen!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle_DE::
	.string "SILPH SCOPE?\n"
	.string "Ich weiß nicht, wovon du redest!$"

RocketHideout_B1F_Text_Grunt4Intro_DE::
	.string "Was willst du überhaupt hier?$"

RocketHideout_B1F_Text_Grunt4Defeat_DE::
	.string "Das kann nicht funktionieren!$"

RocketHideout_B1F_Text_Grunt4PostBattle_DE::
	.string "O.K., O.K., ich packe aus!\n"
	.string "Benutze den Aufzug zum BOSS!$"

RocketHideout_B1F_Text_Grunt5Intro_DE::
	.string "Was hast du hier verloren?$"

RocketHideout_B1F_Text_Grunt5Defeat_DE::
	.string "Was ist passiert?$"

RocketHideout_B1F_Text_Grunt5PostBattle_DE::
	.string "Ups, die Tür ist aufgegangen!$"

