RocketHideout_B1F_Text_Grunt1Intro_ES::
    .string "¿Quién eres tú?\n"
    .string "¿Y cómo has llegado aquí?$"

RocketHideout_B1F_Text_Grunt1Defeat_ES::
    .string "¡Auuu!\n"
    .string "¡He perdido!$"

RocketHideout_B1F_Text_Grunt1PostBattle_ES::
    .string "¿Vas a luchar contra el TEAM\n"
    .string "ROCKET?$"

RocketHideout_B1F_Text_Grunt2Intro_ES::
    .string "¡Has destrozado nuestros planes!$"

RocketHideout_B1F_Text_Grunt2Defeat_ES::
    .string "¡Chamuscado!$"

RocketHideout_B1F_Text_Grunt2PostBattle_ES::
    .string "¡No te vas a salir con la tuya,\n"
    .string "impresentable!$"

RocketHideout_B1F_Text_Grunt3Intro_ES::
    .string "¡Alerta! ¡Nos invaden!$"

RocketHideout_B1F_Text_Grunt3Defeat_ES::
    .string "¡¡¡No lo he conseguido!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle_ES::
    .string "¿El SCOPE SILPH?\n"
    .string "¡No sé dónde está!$"

RocketHideout_B1F_Text_Grunt4Intro_ES::
    .string "¿Por qué has venido aquí?$"

RocketHideout_B1F_Text_Grunt4Defeat_ES::
    .string "¡Esto no funcionará!$"

RocketHideout_B1F_Text_Grunt4PostBattle_ES::
    .string "¡Vale, hablaré! ¡Toma el ascensor\n"
    .string "para ver a mi JEFE!$"

RocketHideout_B1F_Text_Grunt5Intro_ES::
    .string "¿Te has perdido? Pobre...$"

RocketHideout_B1F_Text_Grunt5Defeat_ES::
    .string "¿Por qué...?$"

RocketHideout_B1F_Text_Grunt5PostBattle_ES::
    .string "¡Con tanto lío se ha abierto\n"
    .string "la puerta!$"
