RocketHideout_B4F_Text_GiovanniIntro_ES::
    .string "¡Mmm! ¡Estoy muy impresionado\n"
    .string "de que hayas llegado hasta aquí!\p"
    .string "¡El TEAM ROCKET necesita los\n"
    .string "POKéMON para financiar sus\l"
    .string "malvados planes!\p"
    .string "¡Yo soy GIOVANNI, su líder!\p"
    .string "¡Y te las vas a tener que ver\n"
    .string "conmigo, metomentodo!$"

RocketHideout_B4F_Text_GiovanniDefeat_ES::
    .string "¿QUÉ?\n"
    .string "¡Esto es imposible!$"

RocketHideout_B4F_Text_GiovanniPostBattle_ES::
    .string "Ya veo que has entrenado a tus\n"
    .string "POKéMON con mucho cuidado.\p"
    .string "¡Pero jamás entenderías\n"
    .string "cuáles son mis planes!\p"
    .string "¡En esta ocasión te dejaré pasar!\p"
    .string "Espero que nos volvamos a ver.$"

RocketHideout_B4F_Text_Grunt2Intro_ES::
    .string "¡Te conozco! ¡Tú arruinaste\n"
    .string "nuestros planes en MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat_ES::
    .string "¡Me han vuelto a machacar!$"

RocketHideout_B4F_Text_Grunt2PostBattle_ES::
    .string "¿Tienes algo en contra del TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro_ES::
    .string "¿Acaso no ves la belleza de\n"
    .string "nuestros actos malvados?$"

RocketHideout_B4F_Text_Grunt3Defeat_ES::
    .string "¡Ayayay!$"

RocketHideout_B4F_Text_Grunt3PostBattle_ES::
    .string "¡JEFE!\n"
    .string "¡Siento haberle fallado!$"

RocketHideout_B4F_Text_Grunt1Intro_ES::
    .string "¿No funciona el ascensor? ¿Quién\n"
    .string "tiene la LLAVE del ASCENSOR?$"

RocketHideout_B4F_Text_Grunt1Defeat_ES::
    .string "¡No!$"

RocketHideout_B4F_Text_Grunt1PostBattle_ES::
    .string "¡Oh, no! ¡He perdido la LLAVE\n"
    .string "del ASCENSOR!$"
