RocketHideout_B4F_Text_GiovanniIntro_DE::
	.string "Ich bin schwer beeindruckt. Du\n"
	.string "bist tatsächlich weit gekommen!\p"
	.string "Das TEAM ROCKET finanziert mit\n"
	.string "POKéMON seine finsteren Pläne!\p"
	.string "Ich bin hier der Boss, GIOVANNI!\p"
	.string "Mach dich bereit, Höllenqualen zu\n"
	.string "erleiden, Wicht!$"

RocketHideout_B4F_Text_GiovanniDefeat_DE::
	.string "NEIN!\n"
	.string "Ich habe kläglich versagt!$"

RocketHideout_B4F_Text_GiovanniPostBattle_DE::
	.string "Offensichtlich trainierst du deine\n"
	.string "POKéMON sehr sorgfältig!\p"
	.string "Trotzdem würdest du meine Ziele\n"
	.string "und Beweggründe nie verstehen...\p"
	.string "Dieses Mal lasse ich dich noch von\n"
	.string "dannen ziehen...\p"
	.string "Doch wir werden uns wiedersehen!$"

RocketHideout_B4F_Text_Grunt2Intro_DE::
	.string "Du warst es, der unsere Pläne am\n"
	.string "MONDBERG zunichte gemacht hat!$"

RocketHideout_B4F_Text_Grunt2Defeat_DE::
	.string "Dieses Kind ist einfach\n"
	.string "unschlagbar!!!$"

RocketHideout_B4F_Text_Grunt2PostBattle_DE::
	.string "Willst du das TEAM ROCKET zu\n"
	.string "Grunde richten?$"

RocketHideout_B4F_Text_Grunt3Intro_DE::
	.string "Spürst du nicht die Schönheit der\n"
	.string "dunklen Seite der Macht?$"

RocketHideout_B4F_Text_Grunt3Defeat_DE::
	.string "Autsch!$"

RocketHideout_B4F_Text_Grunt3PostBattle_DE::
	.string "Gnade, BOSS!\n"
	.string "Ich habe versagt...$"

RocketHideout_B4F_Text_Grunt1Intro_DE::
	.string "Ich werde dir den LIFTÖFFNER\n"
	.string "niemals geben!$"

RocketHideout_B4F_Text_Grunt1Defeat_DE::
	.string "Oh nein!$"

RocketHideout_B4F_Text_Grunt1PostBattle_DE::
	.string "Mist!\n"
	.string "Ich habe den LIFTÖFFNER verloren!$"

