SixIsland_RuinValley_Text_CantFigureOutHowToGetInside_ES::
    .string "No tengo ni idea de cómo puedo\n"
    .string "entrar.$"

SixIsland_RuinValley_Text_IFoundThisPlace_ES::
    .string "Para tu información, fui yo quien\n"
    .string "encontró este lugar.\p"
    .string "Tampoco es para que pongas\n"
    .string "esa cara de envidia...$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly_ES::
    .string "La puerta no cede ni un milímetro.\n"
    .string "¿Quieres examinarla un poco?$"

SixIsland_RuinValley_Text_LeftDoorAlone_ES::
    .string "{PLAYER} dejó tranquila la puerta.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor_ES::
    .string "Tras mirarla con más detenimiento,\n"
    .string "vio que estaba punteada...$"

SixIsland_RuinValley_Text_DoorIsOpen_ES::
    .string "La puerta está abierta.$"

SixIsland_RuinValley_Text_StanlyIntro_ES::
    .string "Creo que en este mundo quedan\n"
    .string "misterios por resolver.$"

SixIsland_RuinValley_Text_StanlyDefeat_ES::
    .string "Mmmm...$"

SixIsland_RuinValley_Text_StanlyPostBattle_ES::
    .string "Creo que también deberías dedicar\n"
    .string "un tiempo a pensar en la cantidad\l"
    .string "de cosas que hay por averiguar.$"

SixIsland_RuinValley_Text_FosterIntro_ES::
    .string "Oye, ¿qué te trae hasta aquí?$"

SixIsland_RuinValley_Text_FosterDefeat_ES::
    .string "Llevo tanto sin luchar que no\n"
    .string "tengo reflejos...$"

SixIsland_RuinValley_Text_FosterPostBattle_ES::
    .string "Hay varias ruinas en ARCHI7.\p"
    .string "La mayoría datan de tiempos\n"
    .string "inmemoriales.$"

SixIsland_RuinValley_Text_LarryIntro_ES::
    .string "Dicen que hay misteriosas piedras\n"
    .string "en esta isla.\p"
    .string "Supongo que tendrán algo que ver\n"
    .string "con las ruinas de aquí.$"

SixIsland_RuinValley_Text_LarryDefeat_ES::
    .string "Eh... muy interesante.$"

SixIsland_RuinValley_Text_LarryPostBattle_ES::
    .string "Las ruinas de ahí...\p"
    .string "Son rarísimas, yo no he conseguido\n"
    .string "entrar todavía.$"

SixIsland_RuinValley_Text_DarylIntro_ES::
    .string "¿Luchar contigo?\n"
    .string "¡Ahora mismo!$"

SixIsland_RuinValley_Text_DarylDefeat_ES::
    .string "No soporto el sabor de la derrota\n"
    .string "ante ti...$"

SixIsland_RuinValley_Text_DarylPostBattle_ES::
    .string "Deberías hacer escalada.$"

SixIsland_RuinValley_Text_HectorIntro_ES::
    .string "Yo me conozco bien toda esta\n"
    .string "zona.$"

SixIsland_RuinValley_Text_HectorDefeat_ES::
    .string "Tampoco es para ponerse así.\n"
    .string "Puedes preguntarme lo que quieras.$"

SixIsland_RuinValley_Text_HectorPostBattle_ES::
    .string "La entrada a las ruinas...\n"
    .string "Tiene unos dibujos extrañísimos\l"
    .string "grabados.\p"
    .string "Y no tengo ni idea de lo que\n"
    .string "significan.$"
