SixIsland_RuinValley_Text_CantFigureOutHowToGetInside_DE::
	.string "Ich bin nicht in der Lage, heraus-\n"
	.string "zufinden, wie ich hineinkommen\l"
	.string "soll.$"

SixIsland_RuinValley_Text_IFoundThisPlace_DE::
	.string "Ich war es, der diesen Ort\n"
	.string "entdeckt hat.\p"
	.string "Guck nicht so neidisch!$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly_DE::
	.string "Die Tür bewegt sich nicht.\n"
	.string "Sorgfältiger untersuchen?$"

SixIsland_RuinValley_Text_LeftDoorAlone_DE::
	.string "{PLAYER} ging von der Tür weg.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor_DE::
	.string "Bei näherer Betrachtung sieht man,\n"
	.string "dass mehrere Punkte auf der\l"
	.string "Tür sind…$"

SixIsland_RuinValley_Text_DoorIsOpen_DE::
	.string "Die Tür ist offen.$"

SixIsland_RuinValley_Text_StanlyIntro_DE::
	.string "Es scheint, als ob es noch viele\n"
	.string "ungelöste Rätsel in dieser\l"
	.string "Welt gibt.$"

SixIsland_RuinValley_Text_StanlyDefeat_DE::
	.string "Hm…$"

SixIsland_RuinValley_Text_StanlyPostBattle_DE::
	.string "Ich rate dir, eines Tages auch\n"
	.string "über die Rätsel und Geheimnisse\l"
	.string "unserer Welt nachzudenken.$"

SixIsland_RuinValley_Text_FosterIntro_DE::
	.string "Ich bin neugierig, zu erfahren, was\n"
	.string "dich hierher gebracht hat!$"

SixIsland_RuinValley_Text_FosterDefeat_DE::
	.string "Es ist schon so lange her, dass\n"
	.string "ich gekämpft habe. Meine\l"
	.string "Instinkte sind schwach.$"

SixIsland_RuinValley_Text_FosterPostBattle_DE::
	.string "Es gibt einige Ruinen auf\n"
	.string "SEVII EILAND.\p"
	.string "Der Großteil von ihnen ist\n"
	.string "vor langer Zeit entstanden.$"

SixIsland_RuinValley_Text_LarryIntro_DE::
	.string "Man sagt, dass es auf dieser Insel\n"
	.string "geheimnisvolle Steine geben soll.\p"
	.string "Ich nehme an, dass es etwas mit\n"
	.string "den Ruinen hier zu tun hat.$"

SixIsland_RuinValley_Text_LarryDefeat_DE::
	.string "Oh, interessant.$"

SixIsland_RuinValley_Text_LarryPostBattle_DE::
	.string "Die Ruinen dort drüben…\p"
	.string "Ich hatte noch nicht das Glück,\n"
	.string "herauszufinden, wie man hinein-\l"
	.string "kommt.$"

SixIsland_RuinValley_Text_DarylIntro_DE::
	.string "Ein Kampf mit dir, hier oben?$"

SixIsland_RuinValley_Text_DarylDefeat_DE::
	.string "Oh, mein Herz zerbricht, da du\n"
	.string "so überlegen warst.$"

SixIsland_RuinValley_Text_DarylPostBattle_DE::
	.string "Genieße die Kletterfreude!$"

SixIsland_RuinValley_Text_HectorIntro_DE::
	.string "Ich kenne mich in dieser Gegend\n"
	.string "gut aus.$"

SixIsland_RuinValley_Text_HectorDefeat_DE::
	.string "Du musst nicht nachhaken.\n"
	.string "Ich verrate es dir gerne.$"

SixIsland_RuinValley_Text_HectorPostBattle_DE::
	.string "Die Türe zu den Ruinen…\n"
	.string "Sie ist mit diesen merkwürdigen\l"
	.string "Mustern übersät.\p"
	.string "Ich weiß allerdings nicht, was sie\n"
	.string "bedeuten.$"

