SixIsland_RuinValley_Text_CantFigureOutHowToGetInside_FR::
	.string "Je ne vois pas ce que je dois\n"
	.string "faire pour entrer dedans.$"

SixIsland_RuinValley_Text_IFoundThisPlace_FR::
	.string "C'est moi qui ai trouvé cet endroit.\n"
	.string "Pas de jalousie, d'accord?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly_FR::
	.string "La porte ne bouge pas d'un pouce.\n"
	.string "L'examiner plus attentivement?$"

SixIsland_RuinValley_Text_LeftDoorAlone_FR::
	.string "{PLAYER} s'éloigne de la porte.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor_FR::
	.string "En regardant de plus près, on peut\n"
	.string "voir plusieurs points sur la porte.$"

SixIsland_RuinValley_Text_DoorIsOpen_FR::
	.string "La porte est ouverte.$"

SixIsland_RuinValley_Text_StanlyIntro_FR::
	.string "Plusieurs énigmes semblent ne pas\n"
	.string "avoir été élucidées ici.$"

SixIsland_RuinValley_Text_StanlyDefeat_FR::
	.string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle_FR::
	.string "J'ai un conseil à te donner. Pense\n"
	.string "aux énigmes et secrets de ce monde\p"
	.string "au moins une fois par jour.$"

SixIsland_RuinValley_Text_FosterIntro_FR::
	.string "Je suis curieux, qu'est-ce qui a\n"
	.string "bien pu t'amener ici?$"

SixIsland_RuinValley_Text_FosterDefeat_FR::
	.string "Ça faisait longtemps que je ne\n"
	.string "m'étais pas battu.\p"
	.string "Mes instincts sont un peu rouillés.$"

SixIsland_RuinValley_Text_FosterPostBattle_FR::
	.string "Il y a plusieurs ruines sur les\n"
	.string "ILES SEVII.\p"
	.string "La majorité d'entre elles date\n"
	.string "de milliers d'années.$"

SixIsland_RuinValley_Text_LarryIntro_FR::
	.string "On raconte qu'il y a des pierres\n"
	.string "mystérieuses sur cette île.\p"
	.string "Je pense qu'elles ont un rapport\n"
	.string "avec ces ruines.$"

SixIsland_RuinValley_Text_LarryDefeat_FR::
	.string "Oh, intéressant.$"

SixIsland_RuinValley_Text_LarryPostBattle_FR::
	.string "A propos de ces ruines…\p"
	.string "Je n'ai jamais trouvé le moyen\n"
	.string "d'y pénétrer.$"

SixIsland_RuinValley_Text_DarylIntro_FR::
	.string "Un combat avec toi, c'est parti!$"

SixIsland_RuinValley_Text_DarylDefeat_FR::
	.string "Oh, ça me casse le moral d'avoir\n"
	.string "perdu si facilement contre toi.$"

SixIsland_RuinValley_Text_DarylPostBattle_FR::
	.string "A nous les joies de l'escalade!$"

SixIsland_RuinValley_Text_HectorIntro_FR::
	.string "Je connais bien le coin et ses\n"
	.string "mystères.$"

SixIsland_RuinValley_Text_HectorDefeat_FR::
	.string "Le prends pas comme ça, je vais\n"
	.string "parler, c'est bon.$"

SixIsland_RuinValley_Text_HectorPostBattle_FR::
	.string "La porte de ces ruines…\n"
	.string "Il y a des formes étranges dessus.\p"
	.string "Mais bon, je sais pas ce que ça\n"
	.string "veut dire.$"

