SafariZone_North_Text_RestHouse_ES::
    .string "CASA DE REPOSO$"

SafariZone_North_Text_SecretHouseStillAhead_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡La CASA SECRETA sigue estando\n"
    .string "justo delante!$"

SafariZone_North_Text_Area2_ES::
    .string "ZONA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Los POKéMON se ocultan entre la\n"
    .string "alta hierba!\p"
    .string "Zigzaguea por zonas de hierba para\n"
    .string "que salgan.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Encuentra la CASA SECRETA\n"
    .string "y ganarás una MO!$"
