VictoryRoad_2F_Text_DawsonIntro_ES::
    .string "¡Si puedes pasar por aquí, podrás\n"
    .string "enfrentarte al ALTO MANDO!$"

VictoryRoad_2F_Text_DawsonDefeat_ES::
    .string "¡No!\n"
    .string "¡Increíble!$"

VictoryRoad_2F_Text_DawsonPostBattle_ES::
    .string "¡Puedo vencerte en cuanto a\n"
    .string "conocimientos sobre los POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro_ES::
    .string "¡La CALLE VICTORIA es la prueba\n"
    .string "final de todo ENTRENADOR!$"

VictoryRoad_2F_Text_DaisukeDefeat_ES::
    .string "¡Ayyyy!$"

VictoryRoad_2F_Text_DaisukePostBattle_ES::
    .string "¡Prueba a mover las rocas\n"
    .string "si tienes el paso cortado!$"

VictoryRoad_2F_Text_NelsonIntro_ES::
    .string "¡Ah!\n"
    .string "¿Quieres desafiar al ALTO MANDO?$"

VictoryRoad_2F_Text_NelsonDefeat_ES::
    .string "¡Me has ganado!$"

VictoryRoad_2F_Text_NelsonPostBattle_ES::
    .string "¡{RIVAL} también vino por aquí!$"

VictoryRoad_2F_Text_VincentIntro_ES::
    .string "¡Adelante!\n"
    .string "¡Te daré una paliza!$"

VictoryRoad_2F_Text_VincentDefeat_ES::
    .string "¡Me has machacado!$"

VictoryRoad_2F_Text_VincentPostBattle_ES::
    .string "¡Ahora puedes recorrer la CALLE\n"
    .string "VICTORIA!$"

VictoryRoad_2F_Text_GregoryIntro_ES::
    .string "¿Es muy dura la CALLE VICTORIA?$"

VictoryRoad_2F_Text_GregoryDefeat_ES::
    .string "¡Bien hecho!$"

VictoryRoad_2F_Text_GregoryPostBattle_ES::
    .string "¡Muchos de los ENTRENADORES\n"
    .string "se rinden aquí!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo_ES::
    .string "ギヤーオ！$"
