VictoryRoad_2F_Text_DawsonIntro_IT::
    .string "Se puoi passare da qui, puoi anche\n"
    .string "affrontare i SUPERQUATTRO!$"

VictoryRoad_2F_Text_DawsonDefeat_IT::
    .string "No!\n"
    .string "Incredibile!$"

VictoryRoad_2F_Text_DawsonPostBattle_IT::
    .string "In fatto di POKéMON, ti batto di\n"
    .string "sicuro!$"

VictoryRoad_2F_Text_DaisukeIntro_IT::
    .string "La VIA VITTORIA è la prova finale\n"
    .string "per tutti gli ALLENATORI!$"

VictoryRoad_2F_Text_DaisukeDefeat_IT::
    .string "Ahiaia!$"

VictoryRoad_2F_Text_DaisukePostBattle_IT::
    .string "Se non puoi procedere, prova\n"
    .string "a spostare i massi!$"

VictoryRoad_2F_Text_NelsonIntro_IT::
    .string "Ah!\n"
    .string "Vuoi sfidare i SUPERQUATTRO?$"

VictoryRoad_2F_Text_NelsonDefeat_IT::
    .string "Mi hai sconfitto!$"

VictoryRoad_2F_Text_NelsonPostBattle_IT::
    .string "Anche {RIVAL} è passato da qui!$"

VictoryRoad_2F_Text_VincentIntro_IT::
    .string "Forza!\n"
    .string "Ti darò una bella lezione!$"

VictoryRoad_2F_Text_VincentDefeat_IT::
    .string "La lezione l'ho avuta io!$"

VictoryRoad_2F_Text_VincentPostBattle_IT::
    .string "Ora hai diritto di passare per la\n"
    .string "VIA VITTORIA!$"

VictoryRoad_2F_Text_GregoryIntro_IT::
    .string "È molto dura la VIA VITTORIA?$"

VictoryRoad_2F_Text_GregoryDefeat_IT::
    .string "Bel lavoro!$"

VictoryRoad_2F_Text_GregoryPostBattle_IT::
    .string "Molti ALLENATORI gettano la spugna\n"
    .string "proprio qua!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo_IT::
    .string "ギヤーオ！$"

