VictoryRoad_2F_Text_DawsonIntro_FR::
	.string "Si tu peux remporter ces épreuves,\n"
	.string "tu parviendras jusqu'au CONSEIL 4!$"

VictoryRoad_2F_Text_DawsonDefeat_FR::
	.string "Ha!\n"
	.string "J'y crois pas!$"

VictoryRoad_2F_Text_DawsonPostBattle_FR::
	.string "En ce qui concerne les POKéMON,\n"
	.string "j'suis le plus fort!\l"
	.string "… … …\l"
	.string "Du mooooonde!$"

VictoryRoad_2F_Text_DaisukeIntro_FR::
	.string "La ROUTE VICTOIRE est l'épreuve\n"
	.string "finale de tout DRESSEUR!$"

VictoryRoad_2F_Text_DaisukeDefeat_FR::
	.string "Ouargh!$"

VictoryRoad_2F_Text_DaisukePostBattle_FR::
	.string "Si tu sais pas comment continuer,\n"
	.string "essaie de bouger les rochers!$"

VictoryRoad_2F_Text_NelsonIntro_FR::
	.string "Alors comme ça, tu cherches à\n"
	.string "défier le CONSEIL 4?$"

VictoryRoad_2F_Text_NelsonDefeat_FR::
	.string "Argh!\n"
	.string "T'as gagné!$"

VictoryRoad_2F_Text_NelsonPostBattle_FR::
	.string "{RIVAL} est aussi passé par ici!$"

VictoryRoad_2F_Text_VincentIntro_FR::
	.string "Allez, viens manger ta claque!$"

VictoryRoad_2F_Text_VincentDefeat_FR::
	.string "Beuh!\n"
	.string "J'me suis pris une claque!$"

VictoryRoad_2F_Text_VincentPostBattle_FR::
	.string "Tu as le droit de parcourir la\n"
	.string "ROUTE VICTOIRE!$"

VictoryRoad_2F_Text_GregoryIntro_FR::
	.string "La ROUTE VICTOIRE est\n"
	.string "trop dure pour toi?$"

VictoryRoad_2F_Text_GregoryDefeat_FR::
	.string "Bon…\n"
	.string "J'ai perdu, non?$"

VictoryRoad_2F_Text_GregoryPostBattle_FR::
	.string "De nombreux DRESSEURS ont\n"
	.string "abandonné ici!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo_FR::
	.string "ギヤーオ！$"

