SafariZone_West_Text_KogaPatrolsSafariEverySoOften_DE::
	.string "Die SAFARI-ZONE ist riesig, nicht?\p"
	.string "Der ARENALEITER von FUCHSANIA\n"
	.string "CITY, KOGA, hält hier gelegentlich\l"
	.string "Wache.\p"
	.string "Dank ihm können wir hier in\n"
	.string "Sicherheit spielen.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch_DE::
	.string "Wenn du STEINE auf POKéMON\n"
	.string "wirfst, fliehen sie meist. Aber sie\l"
	.string "sind dann leichter zu fangen!$"

SafariZone_West_Text_BaitMakesMonStickAround_DE::
	.string "Wenn du ihnen KÖDER zuwirfst,\n"
	.string "bleiben die POKéMON eher an\l"
	.string "einem Ort, da sie mit dem Fressen\l"
	.string "beschäftigt sind!$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted_DE::
	.string "Ich habe lange gesucht, aber keine\n"
	.string "neuen POKéMON gefunden.$"

