SafariZone_West_Text_KogaPatrolsSafariEverySoOften_IT::
    .string "Visto quanto è grande la ZONA\n"
    .string "SAFARI?\p"
    .string "Ogni tanto passa di qui KOGA,\n"
    .string "CAPOPALESTRA di FUCSIAPOLI.\p"
    .string "Grazie a lui, tutti possono giocare\n"
    .string "senza correre nessun pericolo.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch_IT::
    .string "Tirare SASSI ai POKéMON rende\n"
    .string "più facile catturarli, ma aumenta\l"
    .string "il rischio che scappino.$"

SafariZone_West_Text_BaitMakesMonStickAround_IT::
    .string "L'ESCA rende più difficile la\n"
    .string "fuga ai POKéMON.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted_IT::
    .string "Ho camminato molto, ma non ho\n"
    .string "visto i POKéMON che\l"
    .string "m'interessavano.$"

