SafariZone_West_Text_KogaPatrolsSafariEverySoOften_ES::
    .string "La ZONA del SAFARI es gigante,\n"
    .string "¿no te parece?\p"
    .string "El LÍDER del GIMNASIO de FUCSIA,\n"
    .string "KOGA, viene con mucha frecuencia\l"
    .string "por esta zona.\p"
    .string "Gracias a él, podemos jugar aquí\n"
    .string "sin miedo.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch_ES::
    .string "Tirar PIEDRAS a los POKéMON\n"
    .string "podría hacerles huir, pero hará\l"
    .string "que sean más fáciles de atrapar.$"

SafariZone_West_Text_BaitMakesMonStickAround_ES::
    .string "Utilizar CEBO te permitirá atrapar\n"
    .string "más fácilmente a los POKéMON.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted_ES::
    .string "Caminé mucho, pero no he visto\n"
    .string "a los POKéMON que quería.$"
