SafariZone_West_Text_KogaPatrolsSafariEverySoOften_FR::
	.string "Le PARC SAFARI est immense,\n"
	.string "tu trouves pas?\p"
	.string "KOGA, le CHAMPION d'ARENE de\n"
	.string "PARMANIE vient souvent ici.\p"
	.string "Grâce à lui, on peut se promener\n"
	.string "en sécurité.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch_FR::
	.string "Une PIERRE peut faire fuir les\n"
	.string "POKéMON mais ils seront plus\l"
	.string "faciles à capturer.$"

SafariZone_West_Text_BaitMakesMonStickAround_FR::
	.string "Un APPAT peut faciliter vos\n"
	.string "captures.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted_FR::
	.string "J'ai cherché toute la sainte\n"
	.string "journée mais j'ai rien capturé.$"

