@ The text here is a copy/paste from Hoenn's various berry NPCs, all unused and untranslated

PetalburgCity_Gym_Text_GiveEnigmaBerry_DE::
	.string "パパ“やあ　{PLAYER}！\p"
	.string "めずらしい　きのみを　てに　いれたから\n"
	.string "プレゼント　するよ！$"

Route104_Text_PlantBerriesInSoilTakeThis_DE::
	.string "ふかふかの　つちに　はえている　きのみは\n"
	.string "じゆうに　とっても　よいのじゃが‥\p"
	.string "1つだけ　きのみを　おなじ　ばしょに　うめる\n"
	.string "それが　れいぎと　いうものじゃ\p"
	.string "ほれ　これを　わけてやろう$"

Route104_Text_TrainersOftenMakeMonHoldBerries_DE::
	.string "あんた　みたところ　トレーナーじゃろ？\p"
	.string "トレーナーは　よく　きのみを　ポケモンに\n"
	.string "もたせとるわい\p"
	.string "ふやすも　つかうも　あんた　しだいじゃ$"

Route111_Text_WateredPlantsEveryDayTakeBerry_DE::
	.string "いつも　みずを　あげてたら\n"
	.string "たくさん　はなが　さいたんだ\p"
	.string "そしたら　きのみも　たくさん　できた！\p"
	.string "はい！\n"
	.string "これ　あげる$"

Route111_Text_TryToMakeRedPokeblock_DE::
	.string "がんばって　あかいポロック　つくるんだ！\n"
	.string "{STR_VAR_1}も　がんばってね！$"

Route111_Text_WhatColorBerriesToLookForToday_DE::
	.string "きょうは　なにいろの　きのみを\n"
	.string "さがそっかなー$"

Route114_Text_GatheringBerriesForContest_DE::
	.string "ポケモンコンテストの　ゆうしょうを　めざして\n"
	.string "きのみを　あつめているんだ\p"
	.string "よかったら　きみにも　わけて　あげるよ！$"

Route114_Text_GoodLuckToYouToo_DE::
	.string "きみも　がんばれ！$"

Route114_Text_WhatBerriesShouldIPlantToday_DE::
	.string "きょうは　どの　きのみを　うめるか‥\n"
	.string "そして　なにいろの　ポロックを　つくるか‥\p"
	.string "なやむのも　また　たのしいよ$"

Route120_Text_PokeblocksExpressionOfLove_DE::
	.string "ケースを　ふると　でてくる　ポロック‥\p"
	.string "そして　それを　キャッチして\n"
	.string "たべてくれる　ポケモン‥\p"
	.string "これって　あい　だよね？$"

Route120_Text_YouUnderstandTakeThis_DE::
	.string "うん　うん！\n"
	.string "やっぱ　わかるひとには　わかるよね\p"
	.string "これ　あげる$"

Route120_Text_OwnImpressionsImportantTakeThis_DE::
	.string "そっか‥‥\n"
	.string "でも　ちがうと　かんじることも　たいせつだね\p"
	.string "これ　あげる$"

Route120_Text_BerryIsRareRaiseItWithCare_DE::
	.string "その　きのみは　めずらしいもの　らしいから\n"
	.string "たいせつに　そだててね！$"

Route120_Text_IllGetMoreBerriesFromBerryMaster_DE::
	.string "また　きのみめいじんに　もらって　こようっと$"

LilycoveCity_Text_BerrySuitsYou_DE::
	.string "やっぱり\p"
	.string "わたしに　スーツが　にあうように\n"
	.string "うみには　しおかぜが　にあうな\l"
	.string "そして　きみには　きのみが　にあいそうだ‥‥\p"
	.string "なんでだろうね？$"

LilycoveCity_Text_BecauseYoureTrainer_DE::
	.string "やっぱり　それは‥‥‥‥\p"
	.string "きみが　トレーナーだからだ！$"

LilycoveCity_Text_PokeblocksSuitPokemon_DE::
	.string "やっぱり\p"
	.string "わたしに　シンプルさが　にあうように\n"
	.string "ポケモンには　ポロックが　にあうな$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry_DE::
	.string "わしは　きのみめいじんと　よばれておる\p"
	.string "わしは　せかいじゅうを　うつくしい　はなで\n"
	.string "うめつくそうと　きのみを　そだてて\l"
	.string "そして　くばり　まくって　おるのじゃ\p"
	.string "きみにも　きのみを　わけて　あげよう！$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother_DE::
	.string "ほれ　えんりょ　せずに　もう　ひとつ！$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop_DE::
	.string "カナズミの　ちかくにある　サン·トウカという\n"
	.string "フラワーショップも　よろしくの\p"
	.string "せかいに　はなを　さかせましょう！$"

Route123_BerryMastersHouse_Text_DoneForToday_DE::
	.string "きょうは　もう　おしまいじゃ\n"
	.string "また　おいで\p"
	.string "せかいに　はなを　さかせましょう！$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately_DE::
	.string "じいさんの　きのみの　そだてかたは\n"
	.string "そりゃあ　せかいいちじゃ\p"
	.string "わしも　はなが　たかいわい\p"
	.string "ところで　あんた\n"
	.string "いい　ことばを　きいたことが　ないかい？$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis_DE::
	.string "おお！　とても　よい　ことばじゃ！\n"
	.string "かんどう　したわい\p"
	.string "ほれ　これを　もっていきなされ$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis_DE::
	.string "おお！　なかなか　よい　ことばじゃ\n"
	.string "あんたも　たいしたもんじゃ\p"
	.string "ほれ　これを　もっていきなされ$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife_DE::
	.string "まごたち　4にんも　じいさんを　しのぐ\n"
	.string "おおものに　なるじゃろうて\p"
	.string "じんせい　たのしいことが　つきんのう！$"

Route123_BerryMastersHouse_Text_Ah_DE::
	.string "ほう‥‥$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop_DE::
	.string "こんにちは！\p"
	.string "はなを　せかいに　ひろめる\n"
	.string "フラワーショップ　サン·トウカです！$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries_DE::
	.string "{PLAYER}{KUN}　きのみの　こと　しりたい？$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries_DE::
	.string "あなたの　なまえは‥‥\p"
	.string "{PLAYER}{KUN}ね！\n"
	.string "とっても　いい　なまえだね！\l"
	.string "{PLAYER}{KUN}　きのみのこと　しりたい？$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation_DE::
	.string "きのみはね　くろい　ふかふかの　つちの\n"
	.string "ところで　たまに　とれるの\l"
	.string "でね‥‥\p"
	.string "とったら　その1つを　また　うめるの！\p"
	.string "そうすると　その　きのみ　から\n"
	.string "めがでて　みきが　できて　はながさいて\l"
	.string "また　きのみ　が　できるの\p"
	.string "そうやって　はなを　ふやして\n"
	.string "せかいじゅうを　はなに　するのが\l"
	.string "わたしの　ゆめ　なんだ！\p"
	.string "だから　{PLAYER}{KUN}も　きのみを　うめて\n"
	.string "せかいに　はなを　ふやしてね！$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness_DE::
	.string "おはなって　とっても　しあわせな　きぶんに\n"
	.string "してくれるよね$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis_DE::
	.string "こんにちは！\p"
	.string "おはなは　せわを　すれば　するほど\n"
	.string "たくさん　きれいに　さいて　くれるの\p"
	.string "あなたも　せわを　したく　なった　でしょ？\n"
	.string "これ　あげるわ$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation_DE::
	.string "きのみが　そだつ　たびに\n"
	.string "じょうろで　みずを　あげてね！\p"
	.string "あとね\p"
	.string "きのみは　ずっと　ずっと　ほうっておくと\n"
	.string "じめんに　おちてしまうの\l"
	.string "でもね　そこから　また　めがでて　くるの！\p"
	.string "すごいよね！\n"
	.string "いきものの　ちからを　かんじるよね$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers_DE::
	.string "おねーちゃんたちを　みならって\n"
	.string "がんばって　おはなを　そだててるの\p"
	.string "はい！　これあげる！$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries_DE::
	.string "きのみは　うめて　おおきく　したり\n"
	.string "ポケモンに　もたせたり　できるの\p"
	.string "でも　さいきん　きのみを　いくつか　まぜると\n"
	.string "ポケモンの　おかしになる　きかいが\l"
	.string "ある　らしいんだ\p"
	.string "あたしも　おかし　ほしー$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese_DE::
	.string "{STR_VAR_1}　なまえ　なんていうの？\p"
	.string "‥‥‥　‥‥‥　‥‥‥\n"
	.string "へー　いいねー\p"
	.string "わたしは　キリ　っていう　なまえなの\p"
	.string "パパと　ママが　すくすくと　そだって\n"
	.string "こころの　あたたかい　おんなのこに　なって\l"
	.string "ほしいっていう　ねがいを　こめたんだって！\p"
	.string "{STR_VAR_1}にも　これ　あげる$"

SootopolisCity_Text_GiveYouThisBerryToo_DE::
	.string "あと　{STR_VAR_1}には　キリの　だいすきな\n"
	.string "この　きのみも　あげちゃう！$"

SootopolisCity_Text_WhatKindOfWishInYourName_DE::
	.string "{STR_VAR_1}の　なまえには\n"
	.string "どんな　ねがいが　こめられてるの？$"

SootopolisCity_Text_LikeSeasonBornIn_DE::
	.string "はる　なつ　あき　ふゆ\n"
	.string "はるに　うまれると　はるが　すきで\l"
	.string "なつに　うまれると　なつが　すきなのかな？$"

SootopolisCity_Text_ThenILoveAutumn_DE::
	.string "じゃあ　キリは　あきに　うまれたから\n"
	.string "あきが　だいすき！\p"
	.string "{STR_VAR_1}は　いつが　すき？$"

SootopolisCity_Text_OhDoesntMatter_DE::
	.string "そっか‥\n"
	.string "かんけいないのか‥\p"
	.string "しりたいことって　たくさんあるなー$"
