Braille_Text_Up_DE::
	.braille "HINAUF$"

Braille_Text_Down_DE::
	.braille "HINUNTER$"

Braille_Text_Right_DE::
	.braille "RECHTS$"

Braille_Text_Left_DE::
	.braille "LINKS$"

Braille_Text_Cut_DE::
	.braille "ZERSCHNEIDER$"

Braille_Text_ABC_DE::
	.braille "ABC$"

Braille_Text_GHI_DE::
	.braille "GHI$"

Braille_Text_MNO_DE::
	.braille "MNO$"

Braille_Text_TUV_DE::
	.braille "TUV$"

Braille_Text_DEF_DE::
	.braille "DEF$"

Braille_Text_JKL_DE::
	.braille "JKL$"

Braille_Text_PQRS_DE::
	.braille "PQRS$"

Braille_Text_WXYZ_DE::
	.braille "WXYZ$"

Braille_Text_Period_DE::
	.braille "=*$"

Braille_Text_Comma_DE::
	.braille "=,$"

Braille_Text_Everything_DE::
	.braille "ALLES$"

Braille_Text_HasMeaning1_DE::
	.braille "MACHT SINN$"

Braille_Text_Existence_DE::
	.braille "EXISTENZ$"

Braille_Text_HasMeaning2_DE::
	.braille "MACHT SINN$"

Braille_Text_BeingAlive_DE::
	.braille "LEBENDIG$"

Braille_Text_HasMeaning3_DE::
	.braille "MACHT SINN$"

Braille_Text_HaveDreams_DE::
	.braille "TR@UMT$"

Braille_Text_UsePower_DE::
	.braille "KRAFTEINSATZ$"

Braille_Text_LetTheTwo_DE::
	.braille "LASS ZWEI$"

Braille_Text_Glittering_DE::
	.braille "SCHIMMERND$"

Braille_Text_Stones_DE::
	.braille "STEINE$"

Braille_Text_OneInRed_DE::
	.braille "EINS IN ROT$"

Braille_Text_OneInBlue_DE::
	.braille "EINS IN BLAU$"

Braille_Text_ConnectThe_DE::
	.braille "VERBINDE$"

Braille_Text_Past_DE::
	.braille "GESCHICHTE$"

Braille_Text_TwoFriends_DE::
	.braille "ZWEI FREUNDE$"

Braille_Text_Sharing_DE::
	.braille "TEILEN$"

Braille_Text_PowerOpen_DE::
	.braille "KRAFT DA$"

Braille_Text_AWindowTo_DE::
	.braille "EIN FENSTER$"

Braille_Text_ANewWorld_DE::
	.braille "NEUE WELT$"

Braille_Text_ThatGlows_DE::
	.braille "DIE GL^HT$"

Braille_Text_TheNext_DE::
	.braille "ALS N@CHSTES$"

Braille_Text_WorldWaits_DE::
	.braille "WELT WARTET$"

Braille_Text_ForYou_DE::
	.braille "AUF DICH$"
