@ Unused
Text_WelcomeTradeCenter_DE::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "HANDELSCENTER.$"

@ Unused
Text_WelcomeColosseum_DE::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "KOLOSSEUM.$"

@ Unused
Text_WelcomeTimeCapsule_DE::
	.string "Willkommen in der POKéMON KABEL-\n"
	.string "CLUB-ZEITKAPSEL.$"

Text_PleaseComeAgain_DE::
	.string "Bitte komm bald wieder!$"

@ Unused
Text_HavingDiscountSaleToday_DE::
	.string "Willkommen!\p"
	.string "Wir bieten heute Sonderangebote\n"
	.string "an!$"

@ Unused
Text_PlayerWhatCanIDoForYou_DE::
	.string "{PLAYER}{KUN}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"

CableClub_Text_WelcomeWhichCableClubService_DE::
	.string "Willkommen im POKéMON\n"
	.string "KABEL-CLUB!\p"
	.string "Welchen Service möchtest du\n"
	.string "nutzen?$"

CableClub_Text_WhichService_DE::
	.string "Welchen Service möchtest du\n"
	.string "nutzen?$"

CableClub_Text_TradeMonsUsingLinkCable_DE::
	.string "Tausche POKéMON mit einem\n"
	.string "Mitspieler via GBA Game Link-Kabel.$"

CableClub_Text_BattleUsingLinkCable_DE::
	.string "Tritt gegen einen anderen TRAINER\n"
	.string "via GBA Game Link-Kabel an.$"

@ Unused, translated in Emerald
CableClub_Text_CloseThisMenu_DE::
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle_DE::
	.string "Für einen DOPPELKAMPF brauchst du\n"
	.string "mindestens zwei POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade_DE::
	.string "Für einen Tausch musst du\n"
	.string "mindestens zwei POKéMON bei dir\l"
	.string "haben.$"

CableClub_Text_CantTradeEnigmaBerry_DE::
	.string "Ein POKéMON, das eine {STR_VAR_1}BEERE\n"
	.string "hält, kann nicht getauscht werden.$"

CableClub_Text_PleaseWaitBCancel_DE::
	.string "Bitte warten. Drücke den B-Knopf,\n"
	.string "um abzubrechen...$"

CableClub_Text_WhenAllPlayersReadyAConfirmBCancel_DE::
	.string "Wenn die Spieler bereit sind...\n"
	.string "A-Knopf: Bestätigen\l"
	.string "B-Knopf: Abbruch$"

CableClub_Text_StartLinkWithXPlayersAConfirmBCancel_DE::
	.string "Verbindung für {STR_VAR_1} Spieler aufbauen.\n"
	.string "A-Knopf: Bestätigen\l"
	.string "B-Knopf: Abbruch$"

CableClub_Text_AwaitingLinkupBCancel_DE::
	.string "Verbindungsaufbau...\n"
	.string "... ... B-Knopf: Abbruch$"

@ Unused, translated in Emerald
CableClub_Text_OkayToSaveProgress_DE::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter_DE::
	.string "Bitte eintreten.$"

CableClub_Text_DirectYouToYourRoom_DE::
	.string "Bitte eintreten.$"

CableClub_Text_SomeoneIsNotReadyToLink_DE::
	.string "Ein Spieler ist noch nicht bereit\n"
	.string "für die Verbindung.\p"
	.string "Bitte kommt wieder, wenn jeder\n"
	.string "seine Vorbereitungen getroffen hat.$"

CableClub_Text_LinkErrorPleaseReset_DE::
	.string "Verbindungsfehler...\n"
	.string "Die Kabelverbindungen überprüfen\l"
	.string "und die Geräte aus- und wieder\l"
	.string "einschalten.$"

CableClub_Text_PlayersMadeDifferentSelections_DE::
	.string "Die Link-Partner haben eine unter-\n"
	.string "schiedliche Auswahl getroffen.$"

CableClub_Text_PleaseVisitAgain_DE::
	.string "Bitte komm bald wieder.$"

CableClub_Text_IncorrectNumberOfParticipants_DE::
	.string "Die Anzahl der Teilnehmer ist nicht\n"
	.string "korrekt.$"

CableClub_Text_CantSingleBattleWithXPlayers_DE::
	.string "Ein EINZELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_CantDoubleBattleWithXPlayers_DE::
	.string "Ein DOPPELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_NeedFourPlayers_DE::
	.string "Für diesen Kampfmodus werden vier\n"
	.string "Spieler benötigt.$"

CableClub_Text_PleaseConfirmNumberAndRestart_DE::
	.string "Bitte überprüfe die Anzahl der\n"
	.string "Spieler und fange nochmals an.$"

Text_TerminateLinkIfYouLeaveRoom_DE::
	.string "Wenn du den Raum verlässt, wird die\n"
	.string "Verbindung abgebrochen.\l"
	.string "Einverstanden?$"

Text_TerminateLinkConfirmation_DE::
	.string "Verbindung wird abgebrochen...\n"
	.string "Du wirst aus dem Raum begleitet.\l"
	.string "Bitte warten.$"

Text_TrainerTooBusyToNotice_DE::
	.string "Dieser TRAINER ist zu\n"
	.string "beschäftigt...$"

Text_LookedAtPlayersTrainerCard_DE::
	.string "Heh! Schau dir den\n"
	.string "TRAINERPASS von {STR_VAR_1} an!$"

Text_LookedAtPlayersTrainerCardColored_DE::
	.string "Heh! Schau dir den\n"
	.string "TRAINERPASS von {STR_VAR_1} an!\p"
	.string "Es ist ein {STR_VAR_2}PASS.$"

Text_TakeSeatStartBattle_DE::
	.string "Bitte geh in Position und beginne\n"
	.string "mit dem Kampf.$"

Text_TakeSeatStartTrade_DE::
	.string "Bitte geh in Position und beginne\n"
	.string "mit dem Tausch.$"

@ Unused, leftover from RS
RecordCorner_Text_ThanksForComing_DE::
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten_DE::
	.string "Der Eintrag auf dem TRAINERPASS\n"
	.string "wird geändert.$"

CableClub_Text_HopeToSeeYouAgain_DE::
	.string "Ich hoffe, du kommst bald wieder\n"
	.string "vorbei.$"

CableClub_Text_NotSetUpForFarAwayRegion_DE::
	.string "Es tut mir schrecklich Leid.\p"
	.string "Wir sind noch nicht auf einen\n"
	.string "Tausch mit TRAINERn aus\l"
	.string "entfernten Gebieten vorbereitet…$"

CableClub_Text_OtherTrainerNotReady_DE::
	.string "Der andere TRAINER ist noch\n"
	.string "nicht bereit!$"

CableClub_Text_YouHaveAMonThatCantBeTaken_DE::
	.string "Du besitzt mindestens ein POKéMON,\n"
	.string "das nicht mitgenommen werden kann.$"

CableClub_Text_AdapterNotConnected_DE::
	.string "Der Drahtlose Game Boy\n"
	.string "Advance-Adapter ist nicht\l"
	.string "ordnungsgemäß angeschlossen.$"

CableClub_Text_ParticipantsStepUpToCounter_DE::
	.string "Die Teilnehmer werden gebeten,\n"
	.string "zur Rezeption zu gehen.$"

@ Unused, translated in Emerald
CableClub_Text_Hello_DE::
	.string "こんにちは！$"

@ Unused, translated in Emerald
CableClub_Text_PleaseWait_DE::
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere_DE::
	.string "Hier kannst du mit deinen Freunden\n"
	.string "POKéMON tauschen.$"

CableClub_Text_YouMayBattleHere_DE::
	.string "Hier kannst du mit deinen Freunden\n"
	.string "kämpfen.$"

CableClub_Text_CanMakeBerryPowder_DE::
	.string "Zwei bis fünf TRAINER können\n"
	.string "zusammen BEERENPUDER herstellen.$"

@ Unused, Record Mix nopped
CableClub_Text_CanMixRecords_DE::
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem_DE::
	.string "Widerruft das ausgewählte\n"
	.string "Item vom MENÜ.$"

@ Unused, translated in Emerald
CableClub_Text_WhichBattleMode_DE::
	.string "どちらの　しょうぶに　しますか？$"

@ Unused, translated in Emerald
CableClub_Text_ReturnsToPreviousStep_DE::
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush_DE::
	.string "Um die BEERENMÜHLE benutzen\n"
	.string "zu können, musst du mindestens\l"
	.string "eine BEERE besitzen.$"

CableClub_Text_NeedTwoMonsForUnionRoom_DE::
	.string "Um den KONNEX-KLUB betreten zu\n"
	.string "dürfen, musst du mindestens zwei\l"
	.string "POKéMON besitzen.$"

CableClub_Text_NoEnigmaBerryInUnionRoom_DE::
	.string "Ein POKéMON, das eine {STR_VAR_1}BEERE\n"
	.string "hält, darf den KONNEX-KLUB nicht\l"
	.string "betreten.$"

CableClub_Text_UnionRoomAdapterNotConnected_DE::
	.string "Das ist der DRAHTLOSE POKéMON\n"
	.string "KONNEX-KLUB.\p"
	.string "Leider ist dein Drahtloser Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "ordnungsgemäß angeschlossen.\l"
	.string "Bitte komme später wieder!$"

@ Unused, translated in Emerald
CableClub_Text_OhExcuseMe_DE::
	.string "あ‥‥\n"
	.string "おきゃくさま！$"

Text_PlayerIsPlayingRightNowGoForIt_DE::
	.string "Es scheint, als ob {STR_VAR_1} gerade\n"
	.string "spielt.\l"
	.string "Los!$"

Text_DescribeWhichGame_DE::
	.string "Ich kann dir die Spielregeln\n"
	.string "erklären, wenn du möchtest.\p"
	.string "Welches Spiel möchtest du erklärt\n"
	.string "bekommen?$"

Text_PokemonJumpInfo_DE::
	.string "“POKéMON-SPRUNG”\p"
	.string "Springe mit deinem POKéMON durch\n"
	.string "Drücken des A-Knopfs über den\l"
	.string "RANKENHIEB.\l"
	.string "Es dürfen nur kleine, circa\l"
	.string "70 cm große POKéMON\l"
	.string "teilnehmen.\l"
	.string "POKéMON, die ausschließlich\l"
	.string "schwimmen, graben oder fliegen,\l"
	.string "können nicht gut springen.\l"
	.string "Daher dürfen diese POKéMON auch\l"
	.string "nicht teilnehmen.\p"
	.string "Etwas Schönes passiert, wenn alle\n"
	.string "rechtzeitig springen.$"

Text_DodrioBerryPickingInfo_DE::
	.string "“BEERENERNTE MIT DODRI”\p"
	.string "Bewege DODRIs drei Köpfe, um die\n"
	.string "fallenden BEEREN zu fangen.\p"
	.string "Drücke das {PLUS} Steuerkreuz nach\n"
	.string "rechts, oben oder links, um die\l"
	.string "Köpfe zu bewegen.\l"
	.string "Um an diesem Spiel teilnehmen zu\l"
	.string "dürfen, benötigst du ein DODRI.$"

Text_TalkToManToPlay_DE::
	.string "Wenn du an einem Spiel teilnehmen\n"
	.string "möchtest, sage dem Mann neben\l"
	.string "mir Bescheid.$"

Text_WelcomeCanYouWait_DE::
	.string "Hallo! Herzlich willkommen!\p"
	.string "Du kannst via Drahtlosem\n"
	.string "Kommunikations-System spielen.\p"
	.string "Bitte gedulde dich noch ein wenig!$"

CableClub_Text_ComeAgain_DE::
	.string "In Ordnung! Komme wieder!$"

Text_AdapterNotConnectedMinigame_DE::
	.string "Der Drahtlose Game Boy\n"
	.string "Advance-Adapter ist nicht\l"
	.string "angeschlossen.\p"
	.string "Komm wieder, wenn er\n"
	.string "angeschlossen ist!$"

Text_PlayWhichGame_DE::
	.string "O.K., was wolltest du spielen?$"

Text_EnterWhichPokemon_DE::
	.string "Welches POKéMON soll teilnehmen?$"

Text_AllGoodToGo_DE::
	.string "Gut, du kannst loslegen!\n"
	.string "Lass nicht zu, dass dich die\l"
	.string "anderen besiegen!$"

@ Unused, translated in Emerald
Text_LeavingDoComeAgain_DE::
	.string "きょうは　けえるのか？\n"
	.string "またこいよ！$"

EventScript_ExplainPokemonJumpRequirements_DE::
	.string "Es scheint, dass keines deiner\n"
	.string "POKéMON teilnehmen kann…\p"
	.string "Soll ich dir erklären, welche\n"
	.string "POKéMON teilnehmen dürfen?$"

Text_ShortJumpingPokemonAllowed_DE::
	.string "Am “POKéMON-SPRUNG”\n"
	.string "dürfen POKéMON, die 70 cm oder\l"
	.string "kleiner sind, teilnehmen.\p"
	.string "POKéMON, die nicht springen können,\n"
	.string "dürfen nicht teilnehmen.\p"
	.string "Zum Beispiel POKéMON, die nur\n"
	.string "schwimmen, graben oder fliegen.\p"
	.string "Das ist schon alles!$"

Text_OnlyDodrioAllowed_DE::
	.string "“BEERENERNTE MIT DODRI”…\n"
	.string "Nun, der Name sagt alles!\p"
	.string "Du musst ein DODRI besitzen, um\n"
	.string "teilnehmen zu dürfen.$"

@ Unused, translated in Emerald
Text_RetryFromStartPlease_DE::
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれ$"

CableClub_Text_WelcomeWhichDirectCornerRoom_DE::
	.string "Willkommen im POKéMON\n"
	.string "DRAHTLOSEN DIREKTKLUB.\p"
	.string "Welchen KLUB möchtest du betreten?$"

CableClub_Text_TradePokemon_DE::
	.string "Möchtest du jetzt POKéMON\n"
	.string "tauschen?$"

CableClub_Text_PlayWhichBattleMode_DE::
	.string "Welche Art des Kampfes?$"

CableClub_Text_UseBerryCrush_DE::
	.string "Möchtest du die BEERENMÜHLE\n"
	.string "benutzen?$"

CableClub_Text_ExplainBattleModes_DE::
	.string "Es gibt drei Kampfarten.\p"
	.string "EINZELKAMPF ist für zwei TRAINER,\n"
	.string "mit je einem oder\l"
	.string "mehreren POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.\p"
	.string "DOPPELKAMPF ist für zwei TRAINER\n"
	.string "mit je zwei oder mehr PKMN.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "zwei POKéMON in den Kampf.\p"
	.string "MULTIKÄMPFE sind für vier TRAINER\n"
	.string "mit je einem oder mehreren PKMN.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.$"

CableClub_Text_ChooseGroupLeaderOfTwo_DE::
	.string "Bitte legt fest, wer von euch der\n"
	.string "LEITER ist.\p"
	.string "Der andere Spieler wählt\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_ChooseGroupLeaderOfFour_DE::
	.string "Bitte legt fest, wer in eurem TEAM\n"
	.string "der LEITER ist.\p"
	.string "Die anderen Spieler wählen\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_ChooseGroupLeader_DE::
	.string "Bitte legt fest, wer in eurem TEAM\n"
	.string "der LEITER ist.\p"
	.string "Die anderen Spieler wählen\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_WelcomeUnionRoomEnter_DE::
	.string "Willkommen im POKéMON DRAHTLOSEN\n"
	.string "KONNEX-KLUB.\p"
	.string "Du kannst hier direkt mit anderen\n"
	.string "TRAINERn interagieren, sogar\l"
	.string "mit unbekannten.\l"
	.string "Möchtest du den KLUB betreten?$"

CableClub_Text_UnionRoomInfo_DE::
	.string "Die TRAINER im KONNEX-KLUB, sind\n"
	.string "die Spieler, die ebenfalls den KLUB\l"
	.string "betreten haben.\p"
	.string "Hier kannst du alles Mögliche\n"
	.string "machen, z.B. Grußformeln\l"
	.string "austauschen!\l"
	.string "Du darfst zwei POKéMON bis\l"
	.string "Level 30 für einen Einzelkampf\l"
	.string "mitnehmen.\l"
	.string "Du kannst eine Unterhaltung mit\l"
	.string "zwei bis fünf Teilnehmern führen.\p"
	.string "Oder du meldest ein POKéMON zum\n"
	.string "Tausch an.\p"
	.string "Möchtest du den Klub betreten?$"

CableClub_Text_EnjoyUnionRoom_DE::
	.string "Ich hoffe, du genießt deinen\n"
	.string "Aufenthalt im KONNEX-KLUB.$"

CableClub_Text_FirstTimeRightThisWay_DE::
	.string "Hallo!\n"
	.string "Ich bin TEALA.\p"
	.string "Dies scheint dein erstes Mal hier\n"
	.string "zu sein.\p"
	.string "Ich zeige dir, wie das Drahtlose\n"
	.string "Kommunikations-System funktioniert.\p"
	.string "Zunächst zeige ich dir dieses\n"
	.string "Stockwerk unseres POKéMON-\l"
	.string "CENTERs.\p"
	.string "Hier entlang bitte!$"

CableClub_Text_ExplainWirelessClubFirstTime_DE::
	.string "Im Obergeschoss gibt es zwei\n"
	.string "KLUBs.\p"
	.string "Zum Einen den KLUB links.\n"
	.string "Das ist der KONNEX-KLUB.\p"
	.string "Hier kannst du TRAINER treffen, die\n"
	.string "ebenfalls den KONNEX-KLUB\l"
	.string "betreten haben.\p"
	.string "Du kannst mit ihnen sprechen,\n"
	.string "kämpfen und tauschen.\p"
	.string "Zum Zweiten den KLUB rechts.\n"
	.string "Das ist der DIREKTKLUB.\p"
	.string "Hier kannst du mit POKéMON gegen\n"
	.string "Freunde kämpfen oder sie tauschen.\p"
	.string "Falls der Drahtlose Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "eingesteckt ist, kannst du das\l"
	.string "GBA Game Link-Kabel benutzen.\p"
	.string "In diesem Fall musst du den\n"
	.string "DIREKTKLUB betreten.\p"
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"

CableClub_Text_AskAboutLinking_DE::
	.string "Hallo, {PLAYER}!\p"
	.string "Ich bin es, TEALA, die Angestellte\n"
	.string "vom 1. Stock im POKéMON-CENTER.\p"
	.string "Möchtest du mich etwas über das\n"
	.string "Herstellen einer Verbindung fragen?$"

CableClub_Text_ExplainWirelessClub_DE::
	.string "Ich erkläre dir, wie der POKéMON\n"
	.string "DRAHTLOS-KLUB funktioniert.\p"
	.string "Im Obergeschoss gibt es zwei\n"
	.string "KLUBs.\p"
	.string "Zum Einen den linken KLUB.\n"
	.string "Das ist der KONNEX-KLUB.\p"
	.string "Hier kannst du TRAINER treffen, die\n"
	.string "ebenfalls den KONNEX-KLUB\l"
	.string "betreten haben.\p"
	.string "Du kannst mit ihnen sprechen,\n"
	.string "kämpfen und tauschen.\p"
	.string "Zum Zweiten den KLUB rechts.\n"
	.string "Das ist der DIREKTKLUB.\p"
	.string "Hier kannst du mit POKéMON gegen\n"
	.string "Freunde kämpfen oder sie tauschen.\p"
	.string "Manchmal kannst du deine\n"
	.string "Freunde in keinem der KLUBs\l"
	.string "treffen.\p"
	.string "In diesem Fall musst du näher\n"
	.string "zu deinen Freunden rücken.\p"
	.string "Falls der Drahtlose Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "benutzt wird, kannst\l"
	.string "du via Game Boy Advance\l"
	.string "Game Link-Kabel eine\l"
	.string "Verbindung herstellen.\p"
	.string "In diesem Fall musst du in\n"
	.string "den DIREKTKLUB gehen.\p"
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem_DE::
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"
