@ Unused
Text_WelcomeTradeCenter_DE::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "HANDELSCENTER.$"

@ Unused
Text_WelcomeColosseum_DE::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "KOLOSSEUM.$"

@ Unused
Text_WelcomeTimeCapsule_DE::
	.string "Willkommen in der POKéMON KABEL-\n"
	.string "CLUB-ZEITKAPSEL.$"

Text_PleaseComeAgain_DE::
	.string "Bitte komm bald wieder!$"

@ Unused
Text_HavingDiscountSaleToday_DE::
	.string "Willkommen!\p"
	.string "Wir bieten heute Sonderangebote\n"
	.string "an!$"

@ Unused
Text_PlayerWhatCanIDoForYou_DE::
	.string "{PLAYER}{KUN}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"
