@ The text here is a copy/paste from Hoenn's Eon Ticket event, all unused and untranslated

Text_DadLetterArrivedForYouPlayer_DE::
	.string "パパ“{PLAYER}！　よく　きたな！\n"
	.string "{PLAYER}あての　てがみが　とどけられたぞ$"

Text_DadPassForShipNeverSeenBefore_DE::
	.string "パパ“わたしも　みたことのない\n"
	.string "ふねの　チケット　だな‥‥\l"
	.string "ミナモに　いってみると　いいだろう$"

Text_FerryToSlateportOhThatPass_DE::
	.string "カイナいき　れんらくせん‥‥\p"
	.string "あら？\n"
	.string "その　チケットは‥‥！$"

Text_YoureOneWhoBroughtOddPass_DE::
	.string "ヘンテコな　チケットを\n"
	.string "もってきたのは　おまえさんか？\p"
	.string "おまえが　いこうと　しているのは\n"
	.string "みなみの　はての　ちっぽけな　しま‥‥\p"
	.string "そこでは　なにが　おこるのか\n"
	.string "だれも　わからねえ‥‥\l"
	.string "ううむ　ふなのりの　ちが　さわぐぜ！\p"
	.string "さあ　のりな！$"

Text_NothingHereSailBackToLilycove_DE::
	.string "なにもねえ　ちんけな　しま　だな‥‥\n"
	.string "ミナモへ　かえるか？$"

Text_SailHomeWeWill_DE::
	.string "よし！　かえると　するか！$"

Text_AsYouLikeThen_DE::
	.string "そうかい\n"
	.string "まあ　すきにするが　いいさ$"

SouthernIsland_Interior_Text_Sign_DE::
	.string "すべての　ゆめは　もうひとつの　げんじつ\n"
	.string "それを　わすれるべからず‥‥$"

SouthernIsland_Exterior_Text_Sign_DE::
	.string "きおく　かすみし　ものは\n"
	.string "こころに　きざみつける　ことを　のぞむ‥‥$"
