gFameCheckerFlavorText_ProfOak0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} EICH POKéMON-LABOR$"

gFameCheckerFlavorText_ProfOak1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Einen Führer mit allen\n"
	.string "POKéMON der Welt zu erstellen…\p"
	.string "Das war mein Traum!$"

gFameCheckerFlavorText_ProfOak2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PROF. EICH hört das nicht\n"
	.string "gerne, aber er ist eine\l"
	.string "POKéMON-Kapazität.\p"
	.string "Viele POKéMON TRAINER schätzen\n"
	.string "ihn sehr.$"

gFameCheckerFlavorText_ProfOak3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es wird berichtet, dass PROF.\n"
	.string "EICH mit seinen Enkeln SARAH\l"
	.string "und {RIVAL} zusammenlebt.$"

gFameCheckerFlavorText_ProfOak4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass sich\n"
	.string "EICH sehr für dich interessiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.$"

gFameCheckerFlavorText_ProfOak5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PROF. EICH wird bald seine\n"
	.string "eigene Radiosendung haben.\p"
	.string "Die Sendung heißt, PROF. \n"
	.string "EICHs POKéMON-SEMINAR.$"

gFameCheckerFlavorText_Daisy0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wenn du SARAH deine\n"
	.string "POKéMON zeigst, sagt sie dir\l"
	.string "wie sehr sie dich mögen.\p"
	.string "Manchmal pflegt sie auch deine\n"
	.string "POKéMON für dich!$"

gFameCheckerFlavorText_Daisy1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Dennoch ist die Person,\n"
	.string "die von den POKéMON am meisten\l"
	.string "geliebt wird, immer noch SARAH.$"

gFameCheckerFlavorText_Daisy2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sie hat sich rührend um\n"
	.string "POKéMON gekümmert…\l"
	.string "Sie war ein kleiner Engel.\p"
	.string "Der Name des Mädchens…\n"
	.string "Ich glaube, er lautete SARAH.$"

gFameCheckerFlavorText_Daisy3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  Es wird berichtet, dass PROF.\n"
	.string "EICH mit seinen Enkeln SARAH\l"
	.string "und {RIVAL} zusammenlebt.$"

gFameCheckerFlavorText_Daisy4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} SARAH, ein Mädchen aus\n"
	.string "ALABASTIA, das täglich TEE trinkt.\p"
	.string "Sie kauft den TEE im EINKAUFS-\n"
	.string "ZENTRUM von PRISMANIA CITY.$"

gFameCheckerFlavorText_Daisy5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Der Frühlingsmeister im\n"
	.string "POKéMON-WETTKAMPF ist\l"
	.string "SARAH EICH aus ALABASTIA!$"

gFameCheckerFlavorText_Brock0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} ROCKO, ARENALEITER von MARMORIA\n"
	.string "CITY.\l"
	.string "Der Steinharte POKéMON TRAINER!$"

gFameCheckerFlavorText_Brock1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine felsenstarke Willenskraft\n"
	.string "manifestiert sich in jedem\l"
	.string "meiner POKéMON.\l"
	.string "Meine POKéMON sind hart wie Stein\l"
	.string "und felsenfest entschlossen.\p"
	.string "Das stimmt! Meine POKéMON gehören\n"
	.string "alle der Elementklasse GESTEIN an!$"

gFameCheckerFlavorText_Brock2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt hier nicht viele\n"
	.string "POKéMON TRAINER, die es\l"
	.string "ernst meinen.\l"
	.string "Sie sind wie KÄFERSAMMLER, \l"
	.string "einfach nur Hobby-TRAINER.\p"
	.string "Aber ROCKO, der ARENALEITER\n"
	.string "von MARMORIA CITY, ist nicht so!$"

gFameCheckerFlavorText_Brock3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} ROCKO ist cool. Er ist nicht\n"
	.string "nur stark. Die Leute mögen und\l"
	.string "respektieren ihn.\p"
	.string "Ich möchte auch ein ARENALEITER\n"
	.string "wie er werden.$"

gFameCheckerFlavorText_Brock4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Hallo, ich grabe hier am\n"
	.string "MONDBERG Fossilien aus.\p"
	.string "Manchmal hilft mir ROCKO von\n"
	.string "der ARENA aus MARMORIA CITY.$"

gFameCheckerFlavorText_Brock5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} ROCKO lacht nur selten, wenn er\n"
	.string "aber doch lacht, kann er angeblich\l"
	.string "nicht mehr damit aufhören.$"

gFameCheckerFlavorText_Misty0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} MISTY, ARENALEITERIN aus\n"
	.string "AZURIA CITY.\l"
	.string "Die Burschikose Meerjungfrau!$"

gFameCheckerFlavorText_Misty1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine Strategie basiert\n"
	.string "auf der totalen Offensive meiner\l"
	.string "WASSER-POKéMON.$"

gFameCheckerFlavorText_Misty2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} MISTY gehört zu der\n"
	.string "Kategorie TRAINER, die sich\l"
	.string "ständig verbessern möchten.\l"
	.string "Sie würde gegen dich nie verlieren!$"

gFameCheckerFlavorText_Misty3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Starke TRAINER und\n"
	.string "WASSER-POKéMON kommen\l"
	.string "hier häufig vor.\l"
	.string "Man sagt, dass MISTY von der\l"
	.string "ARENA aus AZURIA CITY hier\l"
	.string "trainiert.$"

gFameCheckerFlavorText_Misty4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das Kap ist beliebt bei\n"
	.string "Pärchen.\p"
	.string "Die ARENALEITERIN MISTY\n"
	.string "hat hohe Erwartungen an\l"
	.string "diesen Ort.$"

gFameCheckerFlavorText_Misty5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass MISTY,\n"
	.string "LORELEI von den TOP VIER\l"
	.string "verehrt.$"

gFameCheckerFlavorText_LtSurge0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} MAJOR BOB, der ARENA-\n"
	.string "LEITER von ORANIA CITY.\l"
	.string "Der Blitzende Amerikaner!$"

gFameCheckerFlavorText_LtSurge1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Mein Kind, im Krieg haben\n"
	.string "mir ELEKTRO-POKéMON das\l"
	.string "LEBEN gerettet!$"

gFameCheckerFlavorText_LtSurge2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Während meiner Zeit beim\n"
	.string "Militär war MAJOR BOB mein\l"
	.string "Vorgesetzter.\p"
	.string "Er war ein zäher Befehlshaber.$"

gFameCheckerFlavorText_LtSurge3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Beim Militär war MAJOR\n"
	.string "BOB für seine vorsichtige Art\l"
	.string "bekannt.$"

gFameCheckerFlavorText_LtSurge4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} MAJOR BOB hat die Fallen\n"
	.string "in seiner ARENA selbst aufgestellt.\p"
	.string "Er hat überall Doppelschlösser\n"
	.string "einbauen lassen.$"

gFameCheckerFlavorText_LtSurge5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} MAJOR BOB soll während seiner\n"
	.string "Zeit in Amerika ein Pilot\l"
	.string "gewesen sein.\l"
	.string "Er setzte die Elektrizität seiner\l"
	.string "POKéMON als Antrieb für\l"
	.string "sein Flugzeug ein.$"

gFameCheckerFlavorText_Erika0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PRISMANIA CITY POKéMON-ARENA\n"
	.string "ARENALEITERIN: ERIKA\l"
	.string "Die Naturliebende Prinzessin!$"

gFameCheckerFlavorText_Erika1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich lerne die Kunst des\n"
	.string "Blumenanrichtens.\p"
	.string "Meine POKéMON gehören\n"
	.string "ausschließlich der Elementklasse\l"
	.string "PFLANZE an.$"

gFameCheckerFlavorText_Erika2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Unsere ARENALEITERIN\n"
	.string "ERIKA mag still sein, aber\l"
	.string "sie ist hier auch berühmt.$"

gFameCheckerFlavorText_Erika3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} In unserer ARENA werden\n"
	.string "ausschließlich POKéMON der\l"
	.string "Elementklasse PFLANZE eingesetzt.$"

gFameCheckerFlavorText_Erika4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich würde nie POKéMON\n"
	.string "sammeln, wenn sie nicht so\l"
	.string "hübsch wären.$"

gFameCheckerFlavorText_Erika5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass ERIKA in der\n"
	.string "ARENA öfters ein Nickerchen macht.$"

gFameCheckerFlavorText_Koga0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} KOGA, ARENALEITER von\n"
	.string "FUCHSANIA CITY.\l"
	.string "Der Giftige Ninja-Meister.$"

gFameCheckerFlavorText_Koga1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Verzweifle am Gänsehaut\n"
	.string "verursachenden Horror der GIFT-\l"
	.string "POKéMON.$"

gFameCheckerFlavorText_Koga2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Auch wenn ich verliere,\n"
	.string "trainiere ich gemäß der Lehre\l"
	.string "meines Ninja-Meisters KOGA.$"

gFameCheckerFlavorText_Koga3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Mein Vater ist der ARENA-\n"
	.string "LEITER dieser Stadt.\p"
	.string "Ich trainiere auch den Einsatz\n"
	.string "von GIFT-POKéMON wie\l"
	.string "mein Vater.$"

gFameCheckerFlavorText_Koga4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} KOGA verfügt über fundiertes\n"
	.string "Wissen im Bereich der Medizin.\p"
	.string "Er stellt sogar Medizin selbst her,\n"
	.string "um seine POKéMON damit zu\l"
	.string "heilen.$"

gFameCheckerFlavorText_Koga5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die SAFARI-ZONE ist riesig,\n"
	.string "oder nicht?\p"
	.string "Der ARENALEITER von FUCHSANIA\n"
	.string "CITY, KOGA, hält hier gelegentlich\l"
	.string "Wache.\p"
	.string "Dank ihm können wir hier in\n"
	.string "Sicherheit spielen.$"

gFameCheckerFlavorText_Sabrina0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} SABRINA, ARENALEITERIN aus\n"
	.string "SAFFRONIA CITY.\l"
	.string "Die Meisterin der PSYCHO-POKéMON!$"

gFameCheckerFlavorText_Sabrina1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Kennst du ein Mädchen, das\n"
	.string "in SAFFRONIA CITY ARENALEITERIN\l"
	.string "ist?\l"
	.string "Sie setzt PSYCHO-POKéMON ein,\l"
	.string "wenn ich mich nicht irre?$"

gFameCheckerFlavorText_Sabrina2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich beherrsche die PSYCHOKINESE,\n"
	.string "seit ich ein Kind war.\p"
	.string "Zunächst habe ich gelernt, mit\n"
	.string "PSYCHOKINESE Löffel zu verbiegen.$"

gFameCheckerFlavorText_Sabrina3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich verabscheue den Kampf!\n"
	.string "Aber wenn du es wünschst, beweise\l"
	.string "ich dir meine Kräfte!$"

gFameCheckerFlavorText_Sabrina4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass SABRINA im Kampf\n"
	.string "mit ihren POKéMON, ohne zu\l"
	.string "sprechen kommunizieren kann.$"

gFameCheckerFlavorText_Sabrina5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} SABRINA hat gerade mit dem\n"
	.string "KARATE-MEISTER von nebenan\l"
	.string "den Boden gewischt.$"

gFameCheckerFlavorText_Blaine0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PYRO, ARENALEITER von der\n"
	.string "ZINNOBERINSEL.\l"
	.string "Der Hitzköpfige Quizmaster!$"

gFameCheckerFlavorText_Blaine1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine feurigen POKéMON sind\n"
	.string "stark, und brennen nur\l"
	.string "darauf loszulegen.\l"
	.string "Sie verbrennen alle Herausforderer!$"

gFameCheckerFlavorText_Blaine2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Unser ARENALEITER PYRO hat sich\n"
	.string "einmal im Gebirge verlaufen, aber\l"
	.string "alles ging gut.\p"
	.string "Bei Einbruch der Nacht erschien\n"
	.string "ein POKéMON, das einem\l"
	.string "Feuervogel ähnelte.\l"
	.string "Sein Licht ermöglichte PYRO sicher\l"
	.string "nach Hause zurückzufinden.$"

gFameCheckerFlavorText_Blaine3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PYRO, der ARENALEITER der\n"
	.string "ZINNOBERINSEL, ist ein seltsamer\l"
	.string "Mann. \p"
	.string "Er lebte schon hier, bevor das\n"
	.string "LABOR errichtet wurde.$"

gFameCheckerFlavorText_Blaine4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein Foto von PYRO und MR. FUJI!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

gFameCheckerFlavorText_Blaine5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} PYRO nimmt seine Sonnenbrille\n"
	.string "angeblich nur ab, wenn er sich\l"
	.string "neue Quizfragen ausdenkt.$"

gFameCheckerFlavorText_Lorelei0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin LORELEI von den\n"
	.string "TOP VIER.$"

gFameCheckerFlavorText_Lorelei1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin die Nummer Eins, wenn es\n"
	.string "um EIS-POKéMON geht.$"

gFameCheckerFlavorText_Lorelei2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wo wurde diese Person geboren?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein wunderbarer, starker TRAINER\n"
	.string "ist hier aufgewachsen.\p"
	.string "Ich wette, du kennst sie auch. Es\n"
	.string "ist LORELEI von den TOP VIER.$"

gFameCheckerFlavorText_Lorelei3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die für ihren logischen, coolen\n"
	.string "und berechnenden Kampfstil\l"
	.string "bekannte LORELEI hat ein\l"
	.string "überraschendes Geheimnis!$"

gFameCheckerFlavorText_Lorelei4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wusstest du, dass LORELEI eine\n"
	.string "ganze Menge Plüschpuppen besitzt?\p"
	.string "Bei jedem Besuch auf EILAND VIER\n"
	.string "wächst ihre Sammlung!$"

gFameCheckerFlavorText_Lorelei5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sie hat immer noch das LAPRAS,\n"
	.string "das sie in ihrer Kindheit traf.\p"
	.string "Ich erinnere mich, dass sie es\n"
	.string "in der EISKASKADENHÖHLE\l"
	.string "gefangen hatte.\l"
	.string "Vermutlich ist dieses POKéMON\l"
	.string "seither nicht von ihrer Seite\l"
	.string "gewichen.$"

gFameCheckerFlavorText_Bruno0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin BRUNO von den TOP VIER!$"

gFameCheckerFlavorText_Bruno1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich lebe und trainiere mit meinen\n"
	.string "KAMPF-POKéMON!$"

gFameCheckerFlavorText_Bruno2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BRUNO hat sich offensichtlich den\n"
	.string "TOP VIER angeschlossen, um sein\l"
	.string "Verlangen, nur gegen die besten\l"
	.string "TRAINER zu kämpfen, zu stillen.$"

gFameCheckerFlavorText_Bruno3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BRUNO, der mir voransteht,\n"
	.string "kommt gelegentlich auch\l"
	.string "in diesen KURORT.\l"
	.string "Er kommt hierher, um seine\l"
	.string "Gebrechen und die seiner\l"
	.string "POKéMON zu lindern.$"

gFameCheckerFlavorText_Bruno4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist einer der TOP VIER!\n"
	.string "Sein Name ist BRUNO!\p"
	.string "Er ist gegangen, weil er enttäuscht\n"
	.string "war, dass alle WUTKEKSE\l"
	.string "ausverkauft waren.$"

gFameCheckerFlavorText_Bruno5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Auch BRUNO…\n"
	.string "Er hat zuvor mit einem Kumpel\l"
	.string "namens KAMILLO trainiert.$"

gFameCheckerFlavorText_Agatha0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin AGATHE von den TOP VIER!$"

gFameCheckerFlavorText_Agatha1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHEs GEIST-POKéMON\n"
	.string "sind erschreckend hartnäckig.$"

gFameCheckerFlavorText_Agatha2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die alte Dame ist auch leicht\n"
	.string "zu verärgern.\p"
	.string "Es bedarf nur einer Bagatelle und\n"
	.string "die Angst einflößende Dame\l"
	.string "legt los.$"

gFameCheckerFlavorText_Agatha3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In ihrer Jugend war AGATHE eine\n"
	.string "Rivalin von PROF. EICH und hat\l"
	.string "mit ihm um die Vorherrschaft\l"
	.string "als TRAINER gekämpft.$"

gFameCheckerFlavorText_Agatha4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass sich\n"
	.string "EICH sehr für dich interessiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.$"

gFameCheckerFlavorText_Agatha5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Nimm z.B. AGATHE!\p"
	.string "Sie hält den Rekord als ältestes\n"
	.string "Mitglied der TOP VIER.$"

gFameCheckerFlavorText_Lance0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin SIEGFRIED,\n"
	.string "Drachen-TRAINER\l"
	.string "und Oberhaupt der TOP VIER!$"

gFameCheckerFlavorText_Lance1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wusstest du, dass\n"
	.string "Drachen mystische POKéMON sind?\p"
	.string "Sie sind schwer zu fangen und zu\n"
	.string "zähmen! Doch die Mühe lohnt sich!\p"
	.string "Sie sind beinahe unbesiegbar!$"

gFameCheckerFlavorText_Lance2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er verkörpert Gerechtigkeit!\n"
	.string "Er ist cool und leidenschaftlich!\l"
	.string "SIEGFRIED ist der Größte!$"

gFameCheckerFlavorText_Lance3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt einen Kunden namens\n"
	.string "SIEGFRIED, der gelegentlich\l"
	.string "vorbeikommt.\l"
	.string "Er kauft stets Umhänge.\p"
	.string "Ich frage mich, ob er\n"
	.string "viele gleiche Umhänge zu\l"
	.string "Hause hat.$"

gFameCheckerFlavorText_Lance4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass der Großvater von\n"
	.string "SIEGFRIED der Älteste in einem\l"
	.string "berühmten Drachenklan ist.$"

gFameCheckerFlavorText_Lance5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass SIEGFRIED\n"
	.string "einen Cousin hat, der irgendwo\l"
	.string "weit weg ARENALEITER ist.$"

gFameCheckerFlavorText_Bill0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BILL ist weltweit als POKéMANIAC\n"
	.string "bekannt!\p"
	.string "Er hat das POKéMON-Lagerungs-\n"
	.string "System für den PC entwickelt!$"

gFameCheckerFlavorText_Bill1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BILL besitzt viele POKéMON!\p"
	.string "Er hat einige sehr seltene in\n"
	.string "seiner Sammlung!$"

gFameCheckerFlavorText_Bill2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist mein Enkel!\p"
	.string "Schon als kleines Kind hat er gerne\n"
	.string "alles Mögliche gesammelt!$"

gFameCheckerFlavorText_Bill3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BILL ist ein POKéMANIAC, also mag\n"
	.string "er alle POKéMON.\p"
	.string "Es scheint, dass ABRA sein erstes\n"
	.string "POKéMON war!$"

gFameCheckerFlavorText_Bill4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BILL kommt aus DUKATIA CITY,\n"
	.string "wo seine Familie noch lebt.\p"
	.string "Das ist eine eher geschäftige,\n"
	.string "lebhafte Stadt.$"

gFameCheckerFlavorText_Bill5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} BILL kann offensichtlich\n"
	.string "Milch nicht leiden!$"

gFameCheckerFlavorText_MrFuji0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist sehr fürsorglich!\p"
	.string "Er kümmert sich um ausgesetzte\n"
	.string "und verwaiste POKéMON!$"

gFameCheckerFlavorText_MrFuji1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Da war so ein alter Knacker, der\n"
	.string "behauptet hat, wir würden POKéMON\l"
	.string "quälen!\p"
	.string "Willst Du meine Meinung hören?$"

gFameCheckerFlavorText_MrFuji2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} GROSSES POKéMON-GEWINNSPIEL!\p"
	.string "Es sind keine Teilnahmekarten mehr\n"
	.string "vorhanden!\p"
	.string "Sie wurden alle abgeschickt!$"

gFameCheckerFlavorText_MrFuji3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich hörte, dass MR. FUJI auch\n"
	.string "nicht von hier stammt!$"

gFameCheckerFlavorText_MrFuji4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein Foto von PYRO und MR. FUJI!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

gFameCheckerFlavorText_MrFuji5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Redakteur: Der publikumsscheue\n"
	.string "MR. FUJI hat unsere Interview-\l"
	.string "anfragen zurückgewiesen.\p"
	.string "Er ist ein freundlicher Mann, der\n"
	.string "in LAVANDIA verehrt und respektiert\l"
	.string "wird.$"

gFameCheckerFlavorText_Giovanni0_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das TEAM ROCKET finanziert mit\n"
	.string "POKéMON seine finsteren Pläne!\p"
	.string "Ich bin hier der Boss, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Diese Rüpel haben die Kontrolle in\n"
	.string "diesem Gebäude übernommen…\p"
	.string "Der BOSS sagte, dass er nach\n"
	.string "starken POKéMON sucht.$"

gFameCheckerFlavorText_Giovanni2_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Der BOSS von TEAM ROCKET ist\n"
	.string "unheimlich grausam!\p"
	.string "Für ihn sind POKéMON schlicht\n"
	.string "Mittel zum Zweck.$"

gFameCheckerFlavorText_Giovanni3_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Willkommen in meinem\n"
	.string "Geheimversteck!\p"
	.string "Hier wollte ich das TEAM ROCKET\n"
	.string "wiederauferstehen lassen!$"

gFameCheckerFlavorText_Giovanni4_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das gibt es nicht!\n"
	.string "GIOVANNI war hier ARENALEITER?$"

gFameCheckerFlavorText_Giovanni5_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Du… du bist nicht das Kind von\n"
	.string "GIOVANNI! Sein Kind ist rothaarig.$"

gFameCheckerPersonName_ProfOak_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. EICH$"

gFameCheckerPersonQuote_ProfOak_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: PROF. EICH\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Warum strengen sich POKéMON\n"
	.string "im Kampf so für dich an?\p"
	.string "Weil sie deine Liebe und\n"
	.string "Hingabe ihnen gegenüber\l"
	.string "spüren!\p"
	.string "Das darfst du nie vergessen!$"

gFameCheckerPersonName_Daisy_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SARAH$"

gFameCheckerPersonQuote_Daisy_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: SARAH\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Während ich meine Teepausen\n"
	.string "genoss, bist du stark und\l"
	.string "geschickt geworden.\p"
	.string "Ich hoffe, du bist auch in\n"
	.string "Zukunft ein guter\l"
	.string "Rivale für meinen Bruder!$"

gFameCheckerPersonName_Brock_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ROCKO$"

gFameCheckerPersonQuote_Brock_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: ROCKO\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} In unserer großen Welt muss\n"
	.string "es viele starke TRAINER geben.\p"
	.string "Lass uns weiterhin hart\n"
	.string "trainieren, um noch\l"
	.string "stärker zu werden.$"

gFameCheckerPersonName_Misty_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: MISTY\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich möchte hier in dieser ARENA\n"
	.string "trainieren.\p"
	.string "Wenn ich besser bin, möchte ich\n"
	.string "hinaus in die weite Welt.$"

gFameCheckerPersonName_LtSurge_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MAJOR BOB$"

gFameCheckerPersonQuote_LtSurge_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: MAJOR BOB\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Heh, Kiddie!\n"
	.string "Du hast mich in unserem Kampf\l"
	.string "gefrizzelt!\p"
	.string "Ich wusste nicht, dass es so\n"
	.string "mutige TRAINER wie dich gibt!\p"
	.string "Dadurch habe ich meine\n"
	.string "Meinung über dich geändert!$"

gFameCheckerPersonName_Erika_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: ERIKA\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin so froh, dass es solch\n"
	.string "starke TRAINER wie dich gibt.\p"
	.string "Allein diese Tatsache inspiriert\n"
	.string "und motiviert mich,\l"
	.string "noch mehr zu trainieren.\p"
	.string "Bitte komme wieder!\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: KOGA\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Du und ich, wir beide müssen\n"
	.string "unsere Ziele höher stecken und\l"
	.string "an unseren Herausforderungen\l"
	.string "arbeiten.\l"
	.string "Nun muss ich meine Tochter\l"
	.string "trainieren.$"

gFameCheckerPersonName_Sabrina_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: SABRINA\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die Liebe, die du für deine\n"
	.string "POKéMON empfindest…\p"
	.string "Diese Kraft wurde nie von\n"
	.string "meiner PSYKRAFT besiegt.$"

gFameCheckerPersonName_Blaine_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PYRO$"

gFameCheckerPersonQuote_Blaine_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: PYRO\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine FEUER-POKéMON!\n"
	.string "Sie werden noch stärker!\p"
	.string "Und nun ein Quiz! Wie viele\n"
	.string "unterschiedliche FEUER-POKéMON\l"
	.string "gibt es?$"

gFameCheckerPersonName_Lorelei_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: LORELEI\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich musste dir für deine\n"
	.string "Hilfe danken.\p"
	.string "Aber das hat mit unseren Kämpfen\n"
	.string "nichts zu tun.\p"
	.string "Nimm dich beim nächsten Mal\n"
	.string "gefälligst in Acht!$"

gFameCheckerPersonName_Bruno_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: BRUNO\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die unbändige Kraft\n"
	.string "von dir und deinen POKéMON\l"
	.string "habe ich bereits kennen gelernt.\p"
	.string "Beim nächsten Mal sollte ich\n"
	.string "dir vielleicht zeigen, wie du\l"
	.string "dein Training gestalten solltest.$"

gFameCheckerPersonName_Agatha_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHE$"

gFameCheckerPersonQuote_Agatha_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: AGATHE\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wenn du älter wirst, darfst du\n"
	.string "nicht so ein Weichei wie dieser\l"
	.string "Knacker EICH werden!\p"
	.string "Sei wie ich und kämpfe weiter!$"

gFameCheckerPersonName_Lance_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SIEGFRIED$"

gFameCheckerPersonQuote_Lance_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: SIEGFRIED\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich denke darüber nach,\n"
	.string "in meine Heimatstadt\l"
	.string "zurückzukehren.\p"
	.string "Ich möchte meine DRACHEN-\n"
	.string "POKéMON wieder trainieren\l"
	.string "und sie verbessern.\p"
	.string "Ich möchte, dass du mich\n"
	.string "auch einmal in meiner\l"
	.string "Heimatstadt besuchst.$"

gFameCheckerPersonName_Bill_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: BILL\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Heh! CELIO hat dich in den\n"
	.string "höchsten Tönen gelobt.\p"
	.string "Das macht mich glücklich.\p"
	.string "Zeigst du mir seltene POKéMON,\n"
	.string "wenn du welche gefangen\l"
	.string "hast?$"

gFameCheckerPersonName_MrFuji_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: MR. FUJI\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Anstatt ausschließlich an das\n"
	.string "Wohlbefinden deiner POKéMON\l"
	.string "zu denken…\p"
	.string "… kann ich dich überzeugen,\n"
	.string "an das Glück aller POKéMON\l"
	.string "zu denken?$"

gFameCheckerPersonName_Giovanni_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni_DE::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: GIOVANNI\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt nichts, was ich dir sagen\n"
	.string "möchte!\p"
	.string "Ich konzentriere mich\n"
	.string "ausschließlich darauf,\l"
	.string "mich zu verbessern\l"
	.string "und niemanden sonst!$"

gFameCheckerFlavorTextOriginLocation_ProfOak0_DE::
	.string "ALABASTIA$"

gFameCheckerFlavorTextOriginLocation_ProfOak1_DE::
	.string "POKéMON-LABOR$"

gFameCheckerFlavorTextOriginLocation_ProfOak2_DE::
	.string "POKéMON-LABOR$"

gFameCheckerFlavorTextOriginLocation_ProfOak3_DE::
	.string "VERTANIA CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_ProfOak5_DE::
	.string "POKéMON-LABOR$"

gFameCheckerFlavorTextOriginLocation_Daisy0_DE::
	.string "POKéMON-LABOR$"

gFameCheckerFlavorTextOriginLocation_Daisy1_DE::
	.string "ORANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2_DE::
	.string "WASSERIRRGARTEN$"

gFameCheckerFlavorTextOriginLocation_Daisy3_DE::
	.string "VERTANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4_DE::
	.string "PRISMANIA-VILLA$"

gFameCheckerFlavorTextOriginLocation_Daisy5_DE::
	.string "EILAND VIER$"

gFameCheckerFlavorTextOriginLocation_Brock0_DE::
	.string "MARMORIA CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1_DE::
	.string "ARENA MARMORIA$"

gFameCheckerFlavorTextOriginLocation_Brock2_DE::
	.string "MARMORIA CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3_DE::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4_DE::
	.string "MONDBERG$"

gFameCheckerFlavorTextOriginLocation_Brock5_DE::
	.string "MUSEUM MARMORIA$"

gFameCheckerFlavorTextOriginLocation_Misty0_DE::
	.string "AZURIA CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1_DE::
	.string "ARENA AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty2_DE::
	.string "ARENA AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty3_DE::
	.string "SEESCHAUMINSELN$"

gFameCheckerFlavorTextOriginLocation_Misty4_DE::
	.string "AZURIA KAP$"

gFameCheckerFlavorTextOriginLocation_Misty5_DE::
	.string "AZURIA CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0_DE::
	.string "ORANIA CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1_DE::
	.string "ARENA ORANIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge2_DE::
	.string "ARENA ORANIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge3_DE::
	.string "ARENA ORANIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge4_DE::
	.string "ARENA ORANIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge5_DE::
	.string "ORANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0_DE::
	.string "PRISMANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1_DE::
	.string "ARENA PRISMANIA$"

gFameCheckerFlavorTextOriginLocation_Erika2_DE::
	.string "ARENA PRISMANIA$"

gFameCheckerFlavorTextOriginLocation_Erika3_DE::
	.string "ARENA PRISMANIA$"

gFameCheckerFlavorTextOriginLocation_Erika4_DE::
	.string "ARENA PRISMANIA$"

gFameCheckerFlavorTextOriginLocation_Erika5_DE::
	.string "PRISMANIA-VILLA$"

gFameCheckerFlavorTextOriginLocation_Koga0_DE::
	.string "FUCHSANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1_DE::
	.string "ARENA FUCHSANIA$"

gFameCheckerFlavorTextOriginLocation_Koga2_DE::
	.string "ARENA FUCHSANIA$"

gFameCheckerFlavorTextOriginLocation_Koga3_DE::
	.string "FUCHSANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4_DE::
	.string "FUCHSANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5_DE::
	.string "SAFARI-ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0_DE::
	.string "SAFFRONIA CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1_DE::
	.string "EILAND DREI$"

gFameCheckerFlavorTextOriginLocation_Sabrina2_DE::
	.string "ARENA SAFFRONIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina3_DE::
	.string "ARENA SAFFRONIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina4_DE::
	.string "SAFFRONIA CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5_DE::
	.string "ARENA SAFFRONIA$"

gFameCheckerFlavorTextOriginLocation_Blaine0_DE::
	.string "ZINNOBERINSEL$"

gFameCheckerFlavorTextOriginLocation_Blaine1_DE::
	.string "ARENA ZINNOBER.$"

gFameCheckerFlavorTextOriginLocation_Blaine2_DE::
	.string "ARENA ZINNOBER.$"

gFameCheckerFlavorTextOriginLocation_Blaine3_DE::
	.string "ZINNOBERINSEL$"

gFameCheckerFlavorTextOriginLocation_Blaine4_DE::
	.string "ARENA ZINNOBER.$"

gFameCheckerFlavorTextOriginLocation_Blaine5_DE::
	.string "FERIENPARADIES$"

gFameCheckerFlavorTextOriginLocation_Lorelei0_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Lorelei1_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Lorelei2_DE::
	.string "EILAND VIER$"

gFameCheckerFlavorTextOriginLocation_Lorelei3_DE::
	.string "EILAND FÜNF$"

gFameCheckerFlavorTextOriginLocation_Lorelei4_DE::
	.string "EILAND VIER$"

gFameCheckerFlavorTextOriginLocation_Lorelei5_DE::
	.string "EILAND VIER$"

gFameCheckerFlavorTextOriginLocation_Bruno0_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Bruno1_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Bruno2_DE::
	.string "SAFFRONIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3_DE::
	.string "GLUTTHERME$"

gFameCheckerFlavorTextOriginLocation_Bruno4_DE::
	.string "EILAND ZWEI$"

gFameCheckerFlavorTextOriginLocation_Bruno5_DE::
	.string "7-SCHATZSCHLUCHT$"

gFameCheckerFlavorTextOriginLocation_Agatha0_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Agatha1_DE::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2_DE::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3_DE::
	.string "EILAND SIEBEN$"

gFameCheckerFlavorTextOriginLocation_Agatha4_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Agatha5_DE::
	.string "EILAND SECHS$"

gFameCheckerFlavorTextOriginLocation_Lance0_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Lance1_DE::
	.string "POKéMON LIGA$"

gFameCheckerFlavorTextOriginLocation_Lance2_DE::
	.string "SAFFRONIA CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3_DE::
	.string "PRISMANIA EINK.$"

gFameCheckerFlavorTextOriginLocation_Lance4_DE::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5_DE::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0_DE::
	.string "AZURIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1_DE::
	.string "AZURIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2_DE::
	.string "FUCHSANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3_DE::
	.string "EILAND EINS$"

gFameCheckerFlavorTextOriginLocation_Bill4_DE::
	.string "EILAND EINS$"

gFameCheckerFlavorTextOriginLocation_Bill5_DE::
	.string "EILAND EINS$"

gFameCheckerFlavorTextOriginLocation_MrFuji0_DE::
	.string "LAVANDIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji1_DE::
	.string "POKéMON TURM$"

gFameCheckerFlavorTextOriginLocation_MrFuji2_DE::
	.string "LAVANDIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji3_DE::
	.string "LAVANDIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji4_DE::
	.string "ARENA ZINNOBER.$"

gFameCheckerFlavorTextOriginLocation_MrFuji5_DE::
	.string "ZINNOBERINSEL$"

gFameCheckerFlavorTextOriginLocation_Giovanni0_DE::
	.string "ROCKET HQ$"

gFameCheckerFlavorTextOriginLocation_Giovanni1_DE::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2_DE::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3_DE::
	.string "ARENA VERTANIA$"

gFameCheckerFlavorTextOriginLocation_Giovanni4_DE::
	.string "ARENA VERTANIA$"

gFameCheckerFlavorTextOriginLocation_Giovanni5_DE::
	.string "ROCKET-LAGER$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1_DE::
	.string "PROF. EICH$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2_DE::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4_DE::
	.string "AGATHE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5_DE::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_Daisy0_DE::
	.string "ASSISTENT$"

gFameCheckerFlavorTextOriginObjectName_Daisy1_DE::
	.string "FRAU$"

gFameCheckerFlavorTextOriginObjectName_Daisy2_DE::
	.string "MANN$"

gFameCheckerFlavorTextOriginObjectName_Daisy3_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4_DE::
	.string "ALTE DAME$"

gFameCheckerFlavorTextOriginObjectName_Daisy5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Brock1_DE::
	.string "ROCKO$"

gFameCheckerFlavorTextOriginObjectName_Brock2_DE::
	.string "JUNGER MANN$"

gFameCheckerFlavorTextOriginObjectName_Brock3_DE::
	.string "JUNGE$"

gFameCheckerFlavorTextOriginObjectName_Brock4_DE::
	.string "MANN$"

gFameCheckerFlavorTextOriginObjectName_Brock5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Misty1_DE::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2_DE::
	.string "KONSTANTIN$"

gFameCheckerFlavorTextOriginObjectName_Misty3_DE::
	.string "JUNGER MANN$"

gFameCheckerFlavorTextOriginObjectName_Misty4_DE::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1_DE::
	.string "MAJOR BOB$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2_DE::
	.string "CLAUDIO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3_DE::
	.string "CLAUDIO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4_DE::
	.string "RETO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Erika1_DE::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2_DE::
	.string "BEA$"

gFameCheckerFlavorTextOriginObjectName_Erika3_DE::
	.string "ROBERTA$"

gFameCheckerFlavorTextOriginObjectName_Erika4_DE::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Koga1_DE::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2_DE::
	.string "CHUCK$"

gFameCheckerFlavorTextOriginObjectName_Koga3_DE::
	.string "JANINA$"

gFameCheckerFlavorTextOriginObjectName_Koga4_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5_DE::
	.string "MANN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1_DE::
	.string "JUNGER MANN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2_DE::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3_DE::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5_DE::
	.string "BERTOLD$"

gFameCheckerFlavorTextOriginObjectName_Blaine0_DE::
	.string "SCHILD$"

gFameCheckerFlavorTextOriginObjectName_Blaine1_DE::
	.string "PYRO$"

gFameCheckerFlavorTextOriginObjectName_Blaine2_DE::
	.string "BURKARD$"

gFameCheckerFlavorTextOriginObjectName_Blaine3_DE::
	.string "FRAU$"

gFameCheckerFlavorTextOriginObjectName_Blaine4_DE::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0_DE::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1_DE::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2_DE::
	.string "ALTER MANN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4_DE::
	.string "KLEINES MÄDCHEN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5_DE::
	.string "ALTE DAME$"

gFameCheckerFlavorTextOriginObjectName_Bruno0_DE::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1_DE::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3_DE::
	.string "MÜLLER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4_DE::
	.string "FRAU$"

gFameCheckerFlavorTextOriginObjectName_Bruno5_DE::
	.string "MÜLLER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0_DE::
	.string "AGATHE$"

gFameCheckerFlavorTextOriginObjectName_Agatha1_DE::
	.string "MÜLLER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2_DE::
	.string "MÜLLER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4_DE::
	.string "AGATHE$"

gFameCheckerFlavorTextOriginObjectName_Agatha5_DE::
	.string "ALTE DAME$"

gFameCheckerFlavorTextOriginObjectName_Lance0_DE::
	.string "SIEGFRIED$"

gFameCheckerFlavorTextOriginObjectName_Lance1_DE::
	.string "SIEGFRIED$"

gFameCheckerFlavorTextOriginObjectName_Lance2_DE::
	.string "FRAU$"

gFameCheckerFlavorTextOriginObjectName_Lance3_DE::
	.string "KLEINES MÄDCHEN$"

gFameCheckerFlavorTextOriginObjectName_Lance4_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5_DE::
	.string "JUNGER MANN$"

gFameCheckerFlavorTextOriginObjectName_Bill0_DE::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1_DE::
	.string "KLEINER JUNGE$"

gFameCheckerFlavorTextOriginObjectName_Bill2_DE::
	.string "ALTER MANN$"

gFameCheckerFlavorTextOriginObjectName_Bill3_DE::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4_DE::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5_DE::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0_DE::
	.string "KLEINES MÄDCHEN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1_DE::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2_DE::
	.string "MAGAZIN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3_DE::
	.string "MANN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4_DE::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5_DE::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0_DE::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1_DE::
	.string "FORSCHER$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2_DE::
	.string "FORSCHER$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3_DE::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4_DE::
	.string "MANN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5_DE::
	.string "INGO$"

PokemonJournal_Text_SpecialFeatureBrock_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITER\n"
	.string "ROCKO aus MARMORIA CITY!\p"
	.string "ROCKO lacht selten, aber er kann\n"
	.string "nicht aufhören, wenn er\l"
	.string "angefangen hat.$"

PokemonJournal_Text_SpecialFeatureMisty_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITERIN\n"
	.string "MISTY aus AZURIA CITY!\p"
	.string "MISTY vergöttert angeblich\n"
	.string "LORELEI von den TOP VIER.$"

PokemonJournal_Text_SpecialFeatureLtSurge_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITER\n"
	.string "MAJOR BOB aus ORANIA CITY!\p"
	.string "MAJOR BOB war angeblich PILOT\n"
	.string "in seiner Heimat Amerika.\p"
	.string "Sein Flugzeug ist mittels der\n"
	.string "elektrischen Energie von\l"
	.string "POKéMON geflogen.$"

PokemonJournal_Text_SpecialFeatureErika_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITERIN\n"
	.string "ERIKA aus PRISMANIA CITY!\p"
	.string "Man sagt, dass man bei einer\n"
	.string "Stippvisite in der ARENA von\l"
	.string "PRISMANIA CITY, ERIKA bei\l"
	.string "einem Nickerchen beobachten kann.$"

PokemonJournal_Text_SpecialFeatureKoga_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITER\n"
	.string "KOGA aus FUCHSANIA CITY!\p"
	.string "Man sagt, dass KOGA fundiertes\n"
	.string "Wissen auf dem Gebiet der\l"
	.string "Medizin besitzt.\l"
	.string "Er stellt seine eigene Medizin her,\l"
	.string "um seine POKéMON zu heilen.$"

PokemonJournal_Text_SpecialFeatureSabrina_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITERIN\n"
	.string "SABRINA aus SAFFRONIA CITY!\p"
	.string "Man sagt, dass SABRINA mit\n"
	.string "ihren POKéMON im Kampf\l"
	.string "wortlos kommunizieren kann.$"

PokemonJournal_Text_SpecialFeatureBlaine_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: ARENALEITER\n"
	.string "PYRO von der ZINNOBERINSEL!\p"
	.string "PYRO nimmt seine Sonnenbrille\n"
	.string "angeblich nur ab, wenn er sich\l"
	.string "neue Quizfragen ausdenkt.$"

PokemonJournal_Text_SpecialFeatureLorelei_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: LORELEI von den\n"
	.string "TOP VIER!\p"
	.string "Die für ihren logischen, coolen\n"
	.string "und berechnenden Kampfstil\l"
	.string "bekannte LORELEI hat ein\l"
	.string "überraschendes Geheimnis.$"

PokemonJournal_Text_SpecialFeatureBruno_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: BRUNO von den\n"
	.string "TOP VIER!\p"
	.string "BRUNO hat sich offensichtlich den\n"
	.string "TOP VIER angeschlossen, um sein\l"
	.string "Verlangen, nur gegen die besten\l"
	.string "TRAINER zu kämpfen, zu stillen.$"

PokemonJournal_Text_SpecialFeatureAgatha_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: AGATHE von den\n"
	.string "TOP VIER!\p"
	.string "In ihrer Jugend war AGATHE eine\n"
	.string "Rivalin von PROF. EICH und hat\l"
	.string "mit ihm um die Vorherrschaft\l"
	.string "als TRAINER gekämpft.$"

PokemonJournal_Text_SpecialFeatureLance_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: SIEGFRIED von\n"
	.string "den TOP VIER!\p"
	.string "Man sagt, dass der Großvater von\n"
	.string "SIEGFRIED der Älteste in einem\l"
	.string "berühmten Drachenklan ist.$"

PokemonJournal_Text_SpecialFeatureProfOak_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: PROF. EICH, der\n"
	.string "POKéMON-Forscher!\p"
	.string "Berichten zufolge lebt PROF. EICH\n"
	.string "mit seinen Enkeln SARAH und\l"
	.string "{RIVAL} zusammen.$"

PokemonJournal_Text_SpecialFeatureDaisyOak_DE::
	.string "Dies ist ein Jahre altes POKéMON\n"
	.string "JOURNAL…\p"
	.string "POKéMON JOURNAL\n"
	.string "WETTKAMPF-Sonderbericht!\p"
	.string "Der Frühlingsmeister im\n"
	.string "POKéMON-WETTKAMPF ist\l"
	.string "SARAH EICH aus ALABASTIA!$"

PokemonJournal_Text_SpecialFeatureMrFuji_DE::
	.string "POKéMON JOURNAL\p"
	.string "Sonderreportage: MR. FUJI vom\n"
	.string "PKMN-CLUBHAUS!\p"
	.string "Redakteur: Der publikumsscheue\n"
	.string "MR. FUJI hat unsere Interview-\l"
	.string "anfragen zurückgewiesen.\p"
	.string "Er ist ein freundlicher Mann, der\n"
	.string "in LAVANDIA verehrt und respektiert\l"
	.string "wird.$"
