Text_CutTreeDown_DE::
	.string "Du kannst den ZERSCHNEIDER hier\n"
	.string "einsetzen!\p"
	.string "Möchtest du den ZERSCHNEIDER\n"
	.string "einsetzen?$"

Text_MonUsedMove_DE::
	.string "{STR_VAR_1} setzt\n"
	.string "{STR_VAR_2} ein.$"

Text_TreeCanBeCutDown_DE::
	.string "Der ZERSCHNEIDER kann hier\n"
	.string "eingesetzt werden.$"

Text_UseRockSmash_DE::
	.string "Dieser Fels ist zerbrechlich. Soll\n"
	.string "ZERTRÜMMERER eingesetzt werden?$"

Text_MonMaySmashRock_DE::
	.string "Ein großer Felsen. Ein POKéMON\n"
	.string "könnte ihn vielleicht zertrümmern.$"

Text_UseStrength_DE::
	.string "Ein POKéMON kann diesen Felsen\n"
	.string "vielleicht bewegen.\p"
	.string "Möchtest du STÄRKE einsetzen?$"

Text_MonUsedStrengthCanMoveBoulders_DE::
	.string "{STR_VAR_1} setzt STÄRKE ein.\p"
	.string "STÄRKE von {STR_VAR_1} ermöglicht\n"
	.string "es, den Felsen zu bewegen.$"

Text_MonMayPushBoulder_DE::
	.string "Ein POKéMON kann diesen Felsen\n"
	.string "vielleicht bewegen.$"

Text_StrengthMadeMovingBouldersPossible_DE::
	.string "STÄRKE ermöglicht es, Felsen zu\n"
	.string "bewegen.$"

Text_WallOfWaterCrashingDown_DE::
	.string "Das Wasser fällt steil wie eine\n"
	.string "Wand brüllend in die Tiefe.$"

Text_UseWaterfall_DE::
	.string "Ein riesiger Wasserfall.\n"
	.string "Möchtest du KASKADE einsetzen?$"

Text_MonUsedWaterfall_DE::
	.string "{STR_VAR_1} setzt KASKADE ein.$"

Text_MonMayGoUnderwater_DE::
	.string "Das Wasser ist hier tief. Ein\n"
	.string "POKéMON könnte hier\l"
	.string "vielleicht tauchen.$"

Text_SeaIsDeepUseDive_DE::
	.string "Das Meer ist an dieser Stelle\n"
	.string "sehr tief. Möchtest du\l"
	.string "TAUCHER einsetzen?$"

Text_MonUsedDive_DE::
	.string "{STR_VAR_1} setzt TAUCHER ein.$"

Text_MonMaySurface_DE::
	.string "Licht schimmert von oben herab. Ein\n"
	.string "POKéMON könnte hier auftauchen.$"

Text_LightFilteringUseDive_DE::
	.string "Licht schimmert von oben herab.\n"
	.string "Möchtest du TAUCHER einsetzen?$"

Text_DiveCantBeUsedHere_DE::
	.string "An der Oberfläche ist irgendetwas\n"
	.string "im Weg. TAUCHER kann nicht\l"
	.string "eingesetzt werden.$"

Text_LooksLikeNothingHere_DE::
	.string "Hier scheint nichts zu sein...$"
