@ Flavor text for interacting with various background objects 
 
Text_Bookshelf_DE::
	.string "Wow!\n"
	.string "Unmengen Bücher über POKéMON!$"

Text_NothingButPokemonBooks_DE::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap_DE::
	.string "Eine KARTE!$"

Text_PokeMartShelf_DE::
	.string "Wow!\n"
	.string "Jede Menge POKéMON-Gegenstände!$"

Text_DishesPlatesNeatlyLinedUp_DE::
	.string "Die Teller sind ordentlich\n"
	.string "aufgeräumt.$"

Text_Kitchen_DE::
	.string "Es riecht lecker!\n"
	.string "Jemand hier muss gekocht haben!$"

Text_Dresser_DE::
	.string "Das ist eine schön gefertigte\n"
	.string "Anrichte. Es passen eine Menge\l"
	.string "Sachen hinein.$"

Text_Snacks_DE::
	.string "Hier ist ein Stapel Snacks!$"

Text_PokemartSign_DE::
	.string "Wir erfüllen alle Item-Wünsche!\n"
	.string "POKéMON-SUPERMARKT$"

Text_PokecenterSign_DE::
	.string "Erfrische deine POKéMON!\n"
	.string "POKéMON-CENTER$"

Text_Indigo_UltimateGoal_DE::
	.string "INDIGO PLATEAU\p"
	.string "Das große Ziel aller TRAINER ist\n"
	.string "die POKéMON LIGA!$"

Text_Indigo_HighestAuthority_DE::
	.string "INDIGO PLATEAU\p"
	.string "Das POKéMON LIGA-HAUPTQUARTIER\n"
	.string "ist die höchste POKéMON-AUTORITÄT!$"

Text_Food_DE::
	.string "Darin sollten viele verschiedene\n"
	.string "leckere Dinge zum Essen sein.$"

Text_Blueprints_DE::
	.string "Es ist eine Blaupause mit vielen\n"
	.string "Diagrammen und Text.$"

Text_Painting_DE::
	.string "Ein schönes Bild eines POKéMON.\n"
	.string "Es scheint sich wohl zu fühlen.$"

Text_PowerPlantMachine_DE::
	.string "Was ist das für eine Maschine?\n"
	.string "Es ist besser, nicht daran herum-\l"
	.string "zuspielen!$"

Text_Telephone_DE::
	.string "Ein Telefon! Es ist besser,\n"
	.string "es nicht zu benutzen!$"

Text_Computer_DE::
	.string "Es sind nur komplizierte Worte\n"
	.string "und Zahlen, die keinen Sinn\l"
	.string "ergeben…$"

Text_AdvertisingPoster_DE::
	.string "Es ist ein Werbeplakat für\n"
	.string "verschiedene Produkte.$"

Text_TastyFood_DE::
	.string "Hmm, das riecht lecker! Mir läuft\n"
	.string "das Wasser im Mund zusammen.$"

Text_TrashBin_DE::
	.string "Hier drinnen ist…\n"
	.string "……\p"
	.string "Hier ist nichts!$"

Text_Cup_DE::
	.string "Eine Tasse mit einem\n"
	.string "POKéMON-Zeichen.$"

Text_PolishedWindow_DE::
	.string "Das Fenster ist gut geputzt.$"

Text_BeautifulSkyWindow_DE::
	.string "Vor dem Fenster…\p"
	.string "Der Himmel sieht wunderschön aus.$"

Text_BlinkingLights_DE::
	.string "Verschiedenfarbige Lichter blinken.$"

Text_NeatlyLinedUpTools_DE::
	.string "Die ganzen Artikel sind\n"
	.string "ordentlich aufgereiht.$"

Text_ImpressiveMachine_DE::
	.string "Es ist eine Art Maschine. Sie ist\n"
	.string "gewiss beeindruckend.$"

Text_VideoGame_DE::
	.string "Das neueste Videospiel! Es macht\n"
	.string "bestimmt Spaß!$"

Text_Burglary_DE::
	.string "Die Indizien hier sprechen für\n"
	.string "einen Einbruch…$"

Text_PlayerFacingTVScreen_DE::
	.string "Ein POKéMON ist im Fernsehen!\n"
	.string "Es scheint Spaß zu haben!$"
