Trade_Text_LookingForMonWannaTradeForMon_DE::
	.string "Ich suche nach {STR_VAR_1}!\p"
	.string "Tauschst du es gegen {STR_VAR_2}?$"

Trade_Text_AwwOhWell_DE::
	.string "Oje!\n"
	.string "Wenn das so ist...$"

Trade_Text_WhatThatsNoMon_DE::
	.string "Was?\n"
	.string "Das ist aber kein {STR_VAR_1}!$"

Trade_Text_HeyThanks_DE::
	.string "Vielen Dank!$"

Trade_Text_IsntMyOldMonGreat_DE::
	.string "Ist {STR_VAR_2} nicht cool?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon_DE::
	.string "Hallo!\p"
	.string "Willst du dein {STR_VAR_1} nicht\n"
	.string "gegen ein {STR_VAR_2} tauschen?$"

Trade_Text_WellIfYouDontWantTo_DE::
	.string "Wenn du nicht magst, kann man\n"
	.string "nichts machen!$"

Trade_Text_ThisIsntMon_DE::
	.string "Hm?\n"
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Denk an mich, wenn du eins\n"
	.string "gefangen hast!$"

Trade_Text_Thanks_DE::
	.string "Danke!$"

Trade_Text_HasTradedMonGrownStronger_DE::
	.string "Das {STR_VAR_2}, das ich\n"
	.string "mit dir getauscht habe -\l"
	.string "ist es stärker geworden?$"

Trade_Text_DoYouHaveMonWantToTradeForMon_DE::
	.string "Besitzt du ein {STR_VAR_1}?\p"
	.string "Willst du es gegen {STR_VAR_2}\n"
	.string "tauschen?$"

Trade_Text_ThatsTooBad_DE::
	.string "Schade!$"

Trade_Text_ThisIsNoMon_DE::
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Komm wieder, wenn du eines besitzt!$"

Trade_Text_ThanksYoureAPal_DE::
	.string "Vielen Dank!$"

Trade_Text_HowIsMyOldMon_DE::
	.string "Wie geht es {STR_VAR_2}?\p"
	.string "Mein {STR_VAR_1} fühlt sich super!$"
