Text_IdLoveToHearYourProfile_DE:
	.string "Hallo! Schön dich zu sehen!\p"
	.string "… du bist unhöflich!\n"
	.string "Du könntest mich auch begrüßen!\p"
	.string "Also, erzähl mir ein wenig von dir!\p"
	.string "Sag mir dein Profil!$"

Text_TellMeWhatsYourProfile_DE:
	.string "Erzähl mir etwas Gutes über\n"
	.string "dich! Wie lautet dein Profil?$"

Text_ExplainProfile_DE:
	.string "Ein Profil besteht aus vier\n"
	.string "Wörtern oder Phrasen.\p"
	.string "Es gibt unzählige Wörter, um\n"
	.string "ein Profil zusammenzustellen.\p"
	.string "Die Wörter und Phrasen sind in\n"
	.string "praktische Gruppen unterteilt.\p"
	.string "Wähle zunächst eine Gruppe\n"
	.string "und anschließend das Wort.\p"
	.string "… es ist leichter, als es sich\n"
	.string "anhört. Probier es doch einmal!$"

Text_WhatsYourProfile_DE:
	.string "Wie lautet dein Profil?$"

Text_DontBeLikeThat_DE:
	.string "Argh! Sei nicht so! Du kannst\n"
	.string "mir dein Profil sagen!$"

Text_DecidedNotTo_DE:
	.string "Oh, du willst also nicht!\n"
	.string "Du bist wankelmütig, oder?$"

Text_HiWeMeetAgain_DE:
	.string "Hallo!\n"
	.string "Wir treffen uns wieder!$"

Text_ChangeYourProfile_DE:
	.string "Möchtest du dein Profil ändern?$"

Text_WhatAreYouLikeNow_DE:
	.string "Wie bist du jetzt?\n"
	.string "Ich möchte das wissen!$"

Text_LikeProfileWayItIs_DE:
	.string "O.K.! Du magst dein Profil\n"
	.string "so wie es ist.\p"
	.string "Das ist gut!$"

Text_ProfileSaysSomethingAboutYou_DE:
	.string "Hmm…\p"
	.string "Dein Profil sagt wirklich etwas\n"
	.string "über dich aus.\p"
	.string "Da ich dich jetzt besser kenne,\n"
	.string "sind wir noch enger als zuvor\l"
	.string "befreundet.$"

Text_HeardThatBefore_DE:
	.string "Oh, das habe ich schon \n"
	.string "einmal gehört!\p"
	.string "Mein Cousin, der weit weg wohnt,\n"
	.string "pflegte das zu sagen!$"

Text_TellMoreNextTime_DE:
	.string "Erzähl mir beim nächsten\n"
	.string "Mal mehr über dich!$"
