Text_ObtainedTheX_DE::
	.string "{STR_VAR_2} erhalten!$"

Text_BagIsFull_DE::
	.string "Der BEUTEL ist voll...$"

Text_PutItemAway_DE::
	.string "{PLAYER} packt {STR_VAR_2} in\n"
	.string "{STR_VAR_3}.$"

Text_FoundOneItem_DE::
	.string "{PLAYER} hat {STR_VAR_2}\n"
	.string "gefunden!$"

Text_TooBadBagFull_DE::
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll...$"

Text_FoundXCoins_DE::
	.string "{PLAYER} findet\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase_DE::
	.string "{PLAYER} legt die MÜNZEN in den\n"
	.string "MÜNZKORB.$"

Text_CoinCaseIsFull_DE::
	.string "Dein MÜNZKORB ist voll.$"

Text_NothingToPutThemIn_DE::
	.string "Schade! Es gibt nichts,\n"
	.string "wo sie aufbewahrt werden können!$"

Text_FoundXItems_DE::
	.string "{PLAYER} hat {STR_VAR_1}-mal\n"
	.string "{STR_VAR_2} gefunden!$"

Text_ObtainedTheDecor_DE::
	.string "{STR_VAR_2} erhalten!$"

Text_NoRoomForAnotherDecor_DE::
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}...$"

Text_DecorTransferredToPC_DE::
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"
