Text_BootedUpPC_DE::
	.string "{PLAYER} schaltet den PC ein.$"

Text_AccessWhichPC_DE::
	.string "Zugriff auf wessen PC?$"

Text_AccessedSomeonesPC_DE::
	.string "Verbindung zu JEMANDES PC\n"
	.string "hergestellt.$"

Text_OpenedPkmnStorage_DE::
	.string "POKéMON-Lagerungs-System geöffnet.$"

Text_AccessedPlayersPC_DE::
	.string "Verbindung mit PC von {PLAYER}.$"

Text_AccessedBillsPC_DE::
	.string "Verbindung zu BILLs PC\n"
	.string "hergestellt.$"
