Text_MakingPreparations_DE::
	.string "じゅんびちゅうです！$"

Text_WantWhichFloor_DE::
	.string "Wähle ein Stockwerk aus:$"

Text_BagItemCanBeRegistered_DE::
	.string "Ein BASIS-ITEM aus dem BEUTEL\n"
	.string "kann auf SELECT gelegt werden.$"

@ Unused (email from R/S Rivals computer)
Text_TrainerSchoolEmail_DE::
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

Text_PlayerBootedUpPC_DE::
	.string "{PLAYER} schaltet den PC ein.$"

@ Unused
Text_LinkWasCanceled_DE::
	.string "つうしんは　キャンセルされました$"

@ Unused
Text_GiveNicknameToReceivedMon_DE::
	.string "Möchtest du {STR_VAR_2} einen\n"
	.string "Kosenamen geben?$"

gText_PkmnFainted3_DE::
	.string "{STR_VAR_1} wurde besiegt...\p"
	.string "$"

Text_WelcomeWantToHealPkmn_DE::
	.string "Willkommen im POKéMON-CENTER!\p"
	.string "Wir heilen deine POKéMON und\n"
	.string "machen sie wieder fit!$"

Text_TakeYourPkmnForFewSeconds_DE::
	.string "Okay, ich nehme deine POKéMON für\n"
	.string "einen Moment in meine Obhut.$"

Text_WeHopeToSeeYouAgain_DE::
	.string "Komm jederzeit wieder vorbei!$"

Text_RestoredPkmnToFullHealth_DE::
	.string "Danke!\n"
	.string "Deine POKéMON sind wieder topfit!$"
