Pokedude_Text_SpeedierBattlerGoesFirst_DE::
	.string "POKéKUMPEL: Der schnellere\n"
	.string "von beiden darf zuerst angreifen!$"

Pokedude_Text_MyRattataFasterThanPidgey_DE::
	.string "Mein RATTFRATZ war\n"
	.string "schneller als das TAUBSI!$"

Pokedude_Text_BattlersTakeTurnsAttacking_DE::
	.string "Die Kämpfer versuchen jede\n"
	.string "Runde, sich gegenseitig\l"
	.string "KP abzuziehen.$"

Pokedude_Text_MyRattataWonGetsEXP_DE::
	.string "Mein RATTFRATZ hat dem\n"
	.string "Gegner alle KP entzogen und\l"
	.string "so gewonnen!\l"
	.string "Die POKéMON, die am Kampf\l"
	.string "teilnehmen, erhalten\l"
	.string "E.-PUNKTE.\l"
	.string "Hat ein POKéMON genügend\l"
	.string "E.-PUNKTE erhalten, steigt\l"
	.string "sein Level.\l"
	.string "Dadurch wird dein POKéMON\l"
	.string "stärker.$"

Pokedude_Text_UhOhRattataPoisoned_DE::
	.string "POKéKUMPEL: Uh…\n"
	.string "Mein RATTFRATZ wurde\l"
	.string "vergiftet…\l"
	.string "Ein vergiftetes POKéMON\l"
	.string "verliert ständig KP.$"

Pokedude_Text_HealStatusRightAway_DE::
	.string "Falls ein POKéMON unter\n"
	.string "einem Statusproblem leidet,\l"
	.string "solltest du es sofort heilen.$"

Pokedude_Text_UsingItemTakesTurn_DE::
	.string "Allerdings kostet dich der Ein-\n"
	.string "satz eines Items eine Spielrunde.\p"
	.string "Jetzt ist der Gegner an der Reihe!$"

Pokedude_Text_YayWeManagedToWin_DE::
	.string "Yippie!\n"
	.string "Wir haben gewonnen!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass_DE::
	.string "POKéKUMPEL: BLUBBER ist eine\n"
	.string "WASSER-Attacke.\p"
	.string "Das Ziel, MYRAPLA, gehört der\n"
	.string "Elementklasse PFLANZE/GIFT an.\p"
	.string "Die WASSER-Attacke wird von der\n"
	.string "Elementklasse PFLANZE absorbiert…\p"
	.string "Daher ist die Attacke nicht sehr\n"
	.string "effektiv und richtet nur die Hälfte\l"
	.string "des eigentlichen Schadens an.$"

Pokedude_Text_GrassEffectiveAgainstWater_DE::
	.string "Oh, oh! Das ist nicht gut!\p"
	.string "Die eben gezeigte Attacke\n"
	.string "ABSORBER ist eine\l"
	.string "PFLANZEn-Attacke!\l"
	.string "QUAPSEL ist ein WASSER-POKéMON.\l"
	.string "ABSORBER ist also sehr effektiv\l"
	.string "und richtet daher den doppelten\l"
	.string "Schaden an.$"

Pokedude_Text_LetsTryShiftingMons_DE::
	.string "Mit dieser Konstellation der\n"
	.string "Elementklassen wird ein\l"
	.string "Sieg schwierig…\l"
	.string "Daher tauschen wir die POKéMON!$"

Pokedude_Text_ShiftingUsesTurn_DE::
	.string "Der Wechsel des POKéMON\n"
	.string "kostet eine Spielrunde.\p"
	.string "Jetzt ist der Gegner an der Reihe.$"

Pokedude_Text_ButterfreeDoubleResistsGrass_DE::
	.string "SMETTBO gehört der Elementklasse\n"
	.string "KÄFER/FLUG an.\p"
	.string "Gegen ein KÄFER-POKéMON\n"
	.string "richtet eine PFLANZEn-Attacke…\p"
	.string "… nur die Hälfte des\n"
	.string "Schadens an.\p"
	.string "… und auch gegen FLUG-\n"
	.string "POKéMON wird nur die Hälfte\l"
	.string "des Schadens angerichtet.\p"
	.string "Weil SMETTBO ein KÄFER-/\n"
	.string "FLUG-POKéMON ist, nimmt\l"
	.string "es nur ein Viertel des eigentlichen\l"
	.string "Schadens.$"

Pokedude_Text_ButterfreeGoodAgainstOddish_DE::
	.string "MYRAPLA ist ein POKéMON der\n"
	.string "Elementklasse PFLANZE/GIFT.\p"
	.string "Ein POKéMON der Elementklasse\n"
	.string "FLUG oder PSYCHO ist dagegen\l"
	.string "sehr effektiv.\l"
	.string "Eine Attacke einer der beiden\l"
	.string "Elementklassen, richtet den\l"
	.string "doppelten Schaden an.\p"
	.string "Dann mal los!$"

Pokedude_Text_YeahWeWon_DE::
	.string "Yippie!\n"
	.string "Wir haben gewonnen!$"

Pokedude_Text_WeakenMonBeforeCatching_DE::
	.string "POKéKUMPEL: Wenn du versuchst,\n"
	.string "ein POKéMON zu fangen, dann\l"
	.string "wirf nicht gleich POKéBÄLLE!\l"
	.string "Zunächst solltest du das\l"
	.string "POKéMON schwächen, indem\l"
	.string "du seine KP reduzierst.$"

Pokedude_Text_BestIfTargetStatused_DE::
	.string "Das sollte reichen!\p"
	.string "Besser noch wäre es, wenn\n"
	.string "das Ziel ein Statusproblem hat.\p"
	.string "Zum Beispiel wäre es einfacher\n"
	.string "zu fangen, wenn es in Schlaf\l"
	.string "versetzt oder paralysiert wäre.$"

Pokedude_Text_CantDoubleUpOnStatus_DE::
	.string "Dadurch wird es viel leichter\n"
	.string "das POKéMON zu fangen!\p"
	.string "Oh, ja! Falls ein POKéMON\n"
	.string "paralysiert ist, kann es zusätzlich\l"
	.string "nicht mehr in Schlaf versetzt\l"
	.string "werden.\l"
	.string "Mit anderen Worten: Du kannst\l"
	.string "Statusprobleme nicht verdoppeln!$"

Pokedude_Text_LetMeThrowBall_DE::
	.string "O.K.!\n"
	.string "Ich werfe jetzt einen POKéBALL!$"

Pokedude_Text_PickBestKindOfBall_DE::
	.string "Ziehe die Bedingungen und\n"
	.string "die Elementklasse des POKéMON\l"
	.string "in Betracht, ehe du einen\l"
	.string "POKéBALL wirfst.\l"
	.string "Wähle den BALL, der am\l"
	.string "besten geeignet ist.$"
