Text_CardKeyOpenedDoor_DE::
	.string "Bingo!\n"
	.string "Der TÜRÖFFNER hat die Tür\l"
	.string "entriegelt!$"

Text_ItNeedsCardKey_DE::
	.string "Mist! Die Tür geht nur mit dem\n"
	.string "TÜRÖFFNER auf!$"

Text_AccessedProfOaksPC_DE::
	.string "Die Verbindung zu PROF. EICHs PC\n"
	.string "wurde hergestellt.\p"
	.string "Du hast Zugriff auf die POKéDEX-\n"
	.string "BEWERTUNG.$"

Text_HavePokedexRated_DE::
	.string "Soll dein POKéDEX bewertet werden?$"

Text_ClosedLinkToProfOaksPC_DE::
	.string "Die Verbindung zu PROF. EICHs PC\n"
	.string "wurde getrennt.$"

Text_VoiceRangOutDontRunAway_DE::
	.string "EINE STIMME: Lauf nicht davon!$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest_DE::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe_DE::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight_DE::
	.string "それっ　ちがうよー！$"

Text_ISee_DE::
	.string "そっか‥$"

Text_TheDoorIsClosed_DE::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen_DE::
	.string "Die Türe ist offen…$"
