Text_MayIHelpYou_DE::
	.string "Hallo!\n"
	.string "Kann ich dir behilflich sein?$"

Text_FillOutQuestionnaire_DE::
	.string "Dort liegt ein Fragebogen.\n"
	.string "Möchtest du ihn ausfüllen?$"

Text_QuestionnaireThankYou_DE::
	.string "Danke, dass du dir die Zeit\n"
	.string "genommen hast, den\l"
	.string "Fragebogen auszufüllen.\l"
	.string "Deine Antworten werden ausgewertet\l"
	.string "und zukünftig berücksichtigt.$"

Text_YouKnowThoseWords_DE::
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "GEHEIMGESCHEHEN Bescheid.\p"
	.string "Von nun an kannst du\n"
	.string "GEHEIMGESCHEHEN empfangen.$"

Text_YouCanAccessMysteryGift_DE::
	.string "Sobald du dein Spiel gesichert\n"
	.string "hast, kannst du GEHEIMGESCHEHEN\l"
	.string "auswählen.$"

Text_ThankYouForAccessingMysteryGift_DE::
	.string "Danke, dass du das GEHEIM-\n"
	.string "GESCHEHEN-System benutzt hast.$"
