Text_OnlySkilledTrainersAllowedThrough_DE::
	.string "Hier dürfen nur erfahrene TRAINER\n"
	.string "passieren!\p"
	.string "Und du besitzt den {STR_VAR_1}\n"
	.string "noch nicht!$"

Text_CantLetYouPass_DE::
	.string "Befehl ist Befehl! Ich darf dich\n"
	.string "nicht durchlassen!$"

Text_OhThatsBadgeGoRightAhead_DE::
	.string "Oh! Du trägst den {STR_VAR_1}!\n"
	.string "Dann darfst du weitergehen!$"

Text_OnlyPassWithBadgeDontHaveYet_DE::
	.string "Du darfst nur mit dem {STR_VAR_1}\n"
	.string "passieren!\p"
	.string "Du besitzt den {STR_VAR_1} noch\n"
	.string "nicht!\p"
	.string "Nur wer ihn trägt, darf in die\n"
	.string "POKéMON LIGA!$"

Text_OnlyPassWithBadgeOhGoAhead_DE::
	.string "Du darfst nur passieren, wenn du\n"
	.string "bereits den {STR_VAR_1} hast!\p"
	.string "Wunderbar! Du trägst den\n"
	.string "{STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "O.K., setze deinen Weg fort!$"
