@ The text here is a copy/paste from Hoenn's Safari Zone, and any unused text was left untranslated

SafariZone_Text_WouldYouLikeToExit_DE::
	.string "Möchtest du die SAFARI-ZONE jetzt\n"
	.string "verlassen?$"

SafariZone_Text_TimesUp_DE::
	.string "DURCHSAGE: Gong!\p"
	.string "Die Zeit ist um!\p"
	.string "DURCHSAGE: Deine SAFARI-TOUR ist\n"
	.string "vorüber!$"

SafariZone_Text_OutOfBalls_DE::
	.string "DURCHSAGE: Gong!\p"
	.string "Du hast keine SAFARIBÄLLE mehr.\p"
	.string "DURCHSAGE: Deine SAFARI-TOUR ist\n"
	.string "vorüber!$"

SafariZone_Text_WelcomeToSafariZone_DE::
	.string "サファリゾーンへ　ようこそ！\p"
	.string "ここでは　ホウエンでは　なかなか\n"
	.string "みることの　できない　ポケモンを\p"
	.string "しぜんの　すがたの　まま\n"
	.string "めに　することが　できます\p"
	.string "また　ポケモントレーナーの\n"
	.string "ようぼうに　おこたえ　して\p"
	.string "ポケモンを\n"
	.string "つかまえる　ことも　できます！\p"
	.string "サファリゾーンを　たのしんで　いってね！$"

SafariZone_Text_WelcomeFirstTime_DE::
	.string "サファリゾーンへ　ようこそ！\n"
	.string "サファリゾーンは　はじめて　ですか？$"

SafariZone_Text_ComeInAndEnjoy_DE::
	.string "サファリゾーンを　たのしんで　いってね！$"

SafariZone_Text_FirstTimeInfo_DE::
	.string "サファリゾーンでは\n"
	.string "30この　サファリボールを　つかって\l"
	.string "ポケモンを　つかまえる　ことが　できます\p"
	.string "サファリボールを　つかいきるか\n"
	.string "500ぽ　あるくと\p"
	.string "ゲームは　しゅうりょう　です\p"
	.string "サファリゾーンを　たのしんで　いってね！$"

SafariZone_Text_WouldYouLikeToPlay_DE::
	.string "サファリゾーンへ　ようこそ！\p"
	.string "500えんで　ポケモン　つかまえほうだい！\n"
	.string "サファリゲームに　さんか　しますか？$"

SafariZone_Text_PlayAnotherTime_DE::
	.string "そうですか\n"
	.string "こんど　ぜひ　さんか　してください！$"

SafariZone_Text_NotEnoughMoney_DE::
	.string "おかねが　たりませんよ！$"

SafariZone_Text_ThatWillBe500Please_DE::
	.string "それでは　500えん　いただきます$"

SafariZone_Text_HereAreYourSafariBalls_DE::
	.string "では　サファリボールを　どうぞ！$"

SafariZone_Text_Received30SafariBalls_DE::
	.string "{PLAYER}は　サファリボールを\n"
	.string "30こ　うけとった！$"

SafariZone_Text_PleaseEnjoyYourself_DE::
	.string "じかんに　なりましたら\n"
	.string "こちらから　おしらせ　しますので\p"
	.string "ぞんぶんに　おたのしみ　ください！\n"
	.string "では　いってらっしゃい！$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull_DE::
	.string "Entschuldigung!\n"
	.string "Deine PC-BOXEN sind voll.$"

SafariZone_Text_YouNeedPokeblockCase_DE::
	.string "あ！　おきゃくさん\n"
	.string "ポロックケースを　おもちで　ないですね？\p"
	.string "サファリゾーンは　ポロックを　つかうと\n"
	.string "より　おたのしみ　いただけますので\p"
	.string "ぜひ　ポロックケースを\n"
	.string "おもちに　なって　おこし　ください！$"

SafariZone_South_Text_StillHaveTimeExit_DE::
	.string "まだ　じかんが　のこっていますが\n"
	.string "サファリゾーンを　やめますか？$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure_DE::
	.string "では　ひきつづき　おたのしみ　ください！$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying_DE::
	.string "わかりました\p"
	.string "それでは　のこりの　サファリボールを\n"
	.string "おあずかり　します\p"
	.string "おつかれさまでした\n"
	.string "また　ごりよう　ください$"

SafariZone_South_Text_GoodLuck_DE::
	.string "それでは　いってらっしゃい！\l"
	.string "なにか　ありましたら\n"
	.string "わたしに　こえを　かけて　くださいね$"

SafariZone_South_Text_Boy_DE::
	.string "しってた？\p"
	.string "あの　しかくい　はこに　ポロックを　おくと\n"
	.string "ポケモンが　あつまって　くるんだよ！$"

SafariZone_South_Text_Man_DE::
	.string "この　さきに　いきたい　けど\n"
	.string "じてんしゃ　もって　くるの　わすれた‥‥\p"
	.string "おくに　めずらしい　ポケモンが\n"
	.string "いそうな　きが　するのに！$"

SafariZone_Southwest_Text_Woman_DE::
	.string "ポケモンに　ポロックを　なげても\n"
	.string "しらんぷり　される　ときが　あるのよ\p"
	.string "ポケモンにも　すききらいが　あるのかしら？$"

SafariZone_Northwest_Text_Man_DE::
	.string "ぜぇ‥‥　ぜぇ‥‥\n"
	.string "やっと　ここまで　きたけど‥‥\p"
	.string "つかれちゃって　ポケモン　つかまえる\n"
	.string "げんきも　のこって　ないよ‥‥$"

SafariZone_North_Text_Fisherman_DE::
	.string "ホウエンに　いない　みずポケモンを\n"
	.string "さがしに　きたんだけど‥‥\p"
	.string "みずうみは　どこにあるのか\n"
	.string "きみ　しってるかい？$"

SafariZone_North_Text_Man_DE::
	.string "ここで　めずらしい　ポケモンを\n"
	.string "たくさん　つかまえて\l"
	.string "ともだちと　こうかん　するんだ！$"

SafariZone_South_Text_Youngster_DE::
	.string "ポロックおきばに　おいた　ポロックが\n"
	.string "いつのまにか　なくなっていた‥‥\p"
	.string "しらない　うちに\n"
	.string "ポケモンが　たべちゃったのかな？$"

Route121_SafariZoneEntrance_Text_TrainerTip_DE::
	.string "サファリゾーンの　おとくな　じょうほう！\p"
	.string "であった　ポケモンに\n"
	.string "ポロックを　なげると　にげにくく　なります！$"

SafariZone_Southwest_Text_RestHouseSign_DE::
	.string "あるき　つかれたら　ちょっと　ひといき！\n"
	.string "‘みんなの　きゅうけいじょ'$"

SafariZone_RestHouse_Text_Youngster_DE::
	.string "おれ　ポロック　もってないけど\n"
	.string "ポケモン　たくさん　つかまえたよ\p"
	.string "ちかづいて　ボールを　なげる　だけで\n"
	.string "けっこう　つかまえられる　もんだよ！$"

SafariZone_RestHouse_Text_PsychicM_DE::
	.string "ポロックを　つかうと　いつもより\n"
	.string "ちょっぴり　にげにくく　なるみたい\p"
	.string "だから　にげにくい　ポケモンに　つかっても\n"
	.string "あんまり　いみが　ないかもね$"

SafariZone_RestHouse_Text_FatMan_DE::
	.string "ポロックおきばに　ポロック　おいて\n"
	.string "ポケモンを　つかまえると\p"
	.string "おなじ　ような　せいかくの　ポケモンが\n"
	.string "あつまる　きが　するなあ$"
