gText_WouldYouLikeToSaveTheGame_DE::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySaveFile_WouldLikeToOverwrite_DE::
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Spielstand überschreiben?$"

gText_SavingDontTurnOffThePower_DE::
	.string "SPEICHERN... BITTE DAS GERÄT\n"
	.string "NICHT AUSSCHALTEN.$"

gText_PlayerSavedTheGame_DE::
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_SaveFailed2_DE::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile_DE::
	.string "ACHTUNG!\p"
	.string "Es gibt bereits einen Spielstand.\p"
	.string "Wenn jetzt gesichert wird, geht\n"
	.string "der andere Spielstand mit allen\l"
	.string "Items und POKéMON für immer\l"
	.string "verloren.\l"
	.string "Bist du sicher, dass du sichern\l"
	.string "und den anderen Spielstand\l"
	.string "überschreiben möchtest?$"
