Text_FirstShouldRestoreMonsHealth_DE::
	.string "Zunächst solltest du deine POKéMON\n"
	.string "vollständig heilen.$"

Text_MonsHealedShouldBuyPotions_DE::
	.string "Deine POKéMON wurden vollständig\n"
	.string "geheilt.\p"
	.string "Falls die KP deiner POKéMON niedrig\n"
	.string "sind, kannst du uns jederzeit\l"
	.string "aufsuchen.\p"
	.string "Wenn du vorhast, große Ausflüge\n"
	.string "ins hohe Gras zu unternehmen,\l"
	.string "solltest du einige TRÄNKE im\l"
	.string "POKéMON-SUPERMARKT\l"
	.string "kaufen.\p"
	.string "Wir hoffen, du kommst groß raus!$"

Text_MonsHealed_DE::
	.string "Deine POKéMON wurden vollständig\n"
	.string "geheilt.\p"
	.string "Wir hoffen, du kommst groß raus!$"

Text_HadQuiteAnExperienceTakeRest_DE::
	.string "MUTTER: {PLAYER}! \p"
	.string "Das hört sich an, als hättest du\n"
	.string "eine Menge erlebt!\p"
	.string "Du solltest eine\n"
	.string "kurze Pause einlegen.$"

Text_MomExplainHPGetPotions_DE::
	.string "MUTTER: Sehr gut! Du und deine\n"
	.string "POKéMON sehen großartig aus!\p"
	.string "PROF. EICH hat sich soeben\n"
	.string "bei mir gemeldet.\p"
	.string "Er erklärte mir, dass die Energie\n"
	.string "der POKéMON in KP gemessen wird.\p"
	.string "Falls deine POKéMON ihre KP\n"
	.string "verlieren, kannst du sie in einem\l"
	.string "POKéMON-CENTER auffüllen lassen.\l"
	.string "Falls du dich auf lange Reisen\l"
	.string "begibst, solltest du deinen Vorrat\l"
	.string "mit TRÄNKEN vom POKéMON-\l"
	.string "SUPERMARKT auffüllen.\p"
	.string "Lass mich stolz auf dich sein!\p"
	.string "Achte auf dich!$"

Text_WhitedOutLostMoney_DE::
	.string "{PLAYER} hat keine einsatzbereiten\n"
	.string "POKéMON mehr!\p"
	.string "{PLAYER} gerät in Panik und\n"
	.string "verliert {STR_VAR_1}¥…\p"
	.string "{PLAYER} fällt in Ohnmacht!$"

Text_WhitedOut_DE::
	.string "{PLAYER} hat keine einsatzbereiten\n"
	.string "POKéMON mehr!\p"
	.string "{PLAYER} fällt in Ohnmacht!$"
