
@ Unused, from R/S
Text_DoorOpenedFarAway_DE::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall_DE::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments_DE::
	.string "Es tut mir Leid.\n"
	.string "Der POKéMON DRAHTLOSKLUB\l"
	.string "wird gerade gewartet.$"

Text_AppearsToBeUndergoingAdjustments_DE::
	.string "Es scheint, dass gerade\n"
	.string "Wartungsarbeiten vorgenommen\l"
	.string "werden…$"

Text_HandedOverItem_DE::
	.string "{PLAYER} übergibt\n"
	.string "{STR_VAR_1}.$"

Text_GiveNicknameToThisMon_DE::
	.string "Möchtest du {STR_VAR_1} einen\n"
	.string "Spitznamen geben?$"
