SSAnne_Deck_Text_ShipDepartingSoon_DE::
	.string "Sperrstunde! Die Party ist vorbei!\n"
	.string "Das Schiff sticht bald in See!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork_DE::
	.string "Puh! Ich werde das Deck wohl nie\n"
	.string "sauber bekommen!$"

SSAnne_Deck_Text_FeelSeasick_DE::
	.string "Brrr, ich fühle mich elend...\p"
	.string "An der frischen Luft fühle ich mich\n"
	.string "besser...$"

SSAnne_Deck_Text_EdmondIntro_DE::
	.string "Heh!\p"
	.string "Wie wäre es mit einem Tänzchen?$"

SSAnne_Deck_Text_EdmondDefeat_DE::
	.string "Ich bin beeindruckt!$"

SSAnne_Deck_Text_EdmondPostBattle_DE::
	.string "Hast du eine Ahnung, wie viele\n"
	.string "unterschiedliche POKéMON es gibt?$"

SSAnne_Deck_Text_TrevorIntro_DE::
	.string "Ahoi!\n"
	.string "Bist du seekrank?$"

SSAnne_Deck_Text_TrevorDefeat_DE::
	.string "Du hast Glück gehabt!$"

SSAnne_Deck_Text_TrevorPostBattle_DE::
	.string "Mein Vater sagt, es gäbe 100\n"
	.string "verschiedene POKéMON. Ich denke,\l"
	.string "es gibt mehr...$"

