SSAnne_Deck_Text_ShipDepartingSoon_FR::
	.string "La fête est finie! Nous allons\n"
	.string "bientôt lever l'ancre!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork_FR::
	.string "Nyah! Briquer le pont, c'est un\n"
	.string "travail épuisant!$"

SSAnne_Deck_Text_FeelSeasick_FR::
	.string "Gueuh! J'suis malaaaaade…\p"
	.string "Je vais bientôt vom…$"

SSAnne_Deck_Text_EdmondIntro_FR::
	.string "Hé! Toi, là!\p"
	.string "Tu danses?\n"
	.string "Un tango?$"

SSAnne_Deck_Text_EdmondDefeat_FR::
	.string "…\n"
	.string "Belle technique!$"

SSAnne_Deck_Text_EdmondPostBattle_FR::
	.string "Tu sais combien il y a de POKéMON\n"
	.string "différents? Hein, tu l'sais, hein?$"

SSAnne_Deck_Text_TrevorIntro_FR::
	.string "Hoï!\n"
	.string "T'as le mal de mer?$"

SSAnne_Deck_Text_TrevorDefeat_FR::
	.string "Oh!\n"
	.string "Beau combat!$"

SSAnne_Deck_Text_TrevorPostBattle_FR::
	.string "Mon pôpa, y dit qu'y a 100 POKéMON\n"
	.string "différents. J'suis sûr qu'y en a\l"
	.string "plus…$"

