SSAnne_Deck_Text_ShipDepartingSoon_ES::
    .string "¡Se acabó la fiesta!\n"
    .string "¡El barco zarpará pronto!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork_ES::
    .string "¡Limpiar las cubiertas es\n"
    .string "un trabajo duro!$"

SSAnne_Deck_Text_FeelSeasick_ES::
    .string "¡Uff! Me siento fatal...\p"
    .string "He salido a tomar el aire.$"

SSAnne_Deck_Text_EdmondIntro_ES::
    .string "¡Eh, colega!\p"
    .string "¡Bailemos una jota!$"

SSAnne_Deck_Text_EdmondDefeat_ES::
    .string "¡Eres impresionante!$"

SSAnne_Deck_Text_EdmondPostBattle_ES::
    .string "¿Cuántos tipos de POKéMON crees\n"
    .string "que hay?$"

SSAnne_Deck_Text_TrevorIntro_ES::
    .string "¡Eh, hola!\n"
    .string "¿Tienes mareo?$"

SSAnne_Deck_Text_TrevorDefeat_ES::
    .string "¡No he estado muy atento!$"

SSAnne_Deck_Text_TrevorPostBattle_ES::
    .string "Mi papá decía que hay 100 tipos\n"
    .string "de POKéMON. Pero yo creo que\l"
    .string "hay más.$"
