FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons_FR::
	.string "OLGA: Ne pozez pas vos mains zur\n"
	.string "les POKéMON de zette grotte.\p"
	.string "Faites ze que ze dis, ou vous\n"
	.string "zallez avoir affaire à moi!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe_FR::
	.string "Pour qui tu te prends?\p"
	.string "Laisse-nous tranquilles et\n"
	.string "occupe-toi de tes affaires.$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut_FR::
	.string "OLGA: {PLAYER}?!\n"
	.string "Qu'est-ze que tu fais là?\p"
	.string "Non, on verra za plus tard.\n"
	.string "J'ai bezoin de toi maintenant.\p"
	.string "Aide-moi à me débarazzer de\n"
	.string "zes voleurs.\p"
	.string "Ils zattrapent les POKéMON\n"
	.string "et les revendent après!\p"
	.string "A mon zignal!\n"
	.string "Tu prends zelui-là, ya?$"

FourIsland_IcefallCave_Back_Text_GruntIntro_FR::
	.string "Qu-Quoi??\p"
	.string "Qui vous êtes pour nous dire ce\n"
	.string "qu'on doit faire avec nos POKéMON?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat_FR::
	.string "On avait pas prévu ça!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons_FR::
	.string "OLGA: Humph.\n"
	.string "Espèze de mizérable.\p"
	.string "Toi!\n"
	.string "Dis-moi!\p"
	.string "Où avez-vous zemporté les\n"
	.string "POKéMON capturés?\p"
	.string "Dites-moi tout zou bien…$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat_FR::
	.string "Ja-jamais!\n"
	.string "Je ne dirai rien!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou_FR::
	.string "OLGA: Zi vous ne parlez pas,\n"
	.string "nous zallons vous congeler.\p"
	.string "Mon LOKHLASS est furieux de\n"
	.string "ze que vous zavez fait.\p"
	.string "Go, LOKHLASS!\n"
	.string "LAZER GLACE…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland_FR::
	.string "OK, OK, je vais parler!\p"
	.string "Les POKéMON sont dans l'ENTREPOT\n"
	.string "ROCKET sur l'ILE 5.\p"
	.string "Voilà, je l'ai dit!\n"
	.string "Laissez-nous maintenant!\p"
	.string "… Mais je suis sûr que vous\n"
	.string "arriverez jamais à l'ENTREPOT!\p"
	.string "Hehehehehe!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful_FR::
	.string "{PLAYER}, merzi beaucoup.\n"
	.string "Mais z'est vraiment affreux…\p"
	.string "Je zuis née et j'ai grandi sur\n"
	.string "zes ILES.\p"
	.string "Je ne me doutais pas que zes\n"
	.string "bandits étaient izi…$"

