CeruleanCity_House2_Text_RocketsStoleTMForDig_ES::
    .string "¡Esos dichosos ROCKET!\p"
    .string "¡Mira lo que hicieron aquí!\p"
    .string "¡Robaron una MT para enseñar a\n"
    .string "los POKéMON cómo EXCAVAR hoyos!\p"
    .string "Yo que quería enseñárselo a\n"
    .string "MANKEY o a SANDSHREW... \p"
    .string "¡Menuda faena!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM_ES::
    .string "¡Lo perdido, perdido está!\p"
    .string "¡He decidido enseñar a DIGLETT\n"
    .string "cómo EXCAVAR sin tener una MT!$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood_ES::
    .string "¡El TEAM ROCKET estará intentando\n"
    .string "EXCAVAR para hacer alguna de las\l"
    .string "suyas!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut_ES::
    .string "¡El TEAM ROCKET abrió una nueva\n"
    .string "salida!$"
