CeruleanCity_House2_Text_RocketsStoleTMForDig_IT::
    .string "Quei maledetti ROCKET!\p"
    .string "Guarda cosa hanno fatto qui!\p"
    .string "Hanno rubato una MT per insegnare\n"
    .string "ai POKéMON a scavare una FOSSA!\p"
    .string "Mi era costata una vera fortuna!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM_IT::
    .string "Io dico: quel che è perso è perso!\p"
    .string "Così ho insegnato a DIGLETT a\n"
    .string "scavare fosse senza MT!$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood_IT::
    .string "TEAM ROCKET cerca di scavare la\n"
    .string "strada verso il male!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut_IT::
    .string "TEAM ROCKET si è aperto una via\n"
    .string "d'uscita!$"

