CeruleanCity_House2_Text_RocketsStoleTMForDig_DE::
	.string "Dieses gemeine TEAM ROCKET!\p"
	.string "Hör dir an, was sie wieder\n"
	.string "verbrochen haben!\p"
	.string "Sie haben den SCHAUFLER gestohlen,\n"
	.string "eine TM, mit der POKéMON Löcher\l"
	.string "graben können!\p"
	.string "Der SCHAUFLER war sündhaft teuer!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM_DE::
	.string "Was weg ist, ist weg!\p"
	.string "Ich werde DIGDA beibringen, ohne\n"
	.string "den SCHAUFLER zu graben!$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood_DE::
	.string "Das TEAM ROCKET braucht den\n"
	.string "SCHAUFLER sicher für irgendeine\l"
	.string "Schandtat!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut_DE::
	.string "Das TEAM ROCKET hat Spuren\n"
	.string "hinterlassen!$"

