SilphCo_1F_Text_WelcomePresidentInBoardroom_ES::
    .string "¡Hola!\p"
    .string "¡El PRESIDENTE está en la sala\n"
    .string "de reuniones del P10!$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile_ES::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "PB$"
