SilphCo_1F_Text_WelcomePresidentInBoardroom_IT::
    .string "Eccoti qui!\p"
    .string "Il PRESIDENTE è in sala riunioni al\n"
    .string "10º piano!$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile_IT::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "PT$"

