LavenderTown_House1_Text_Cubone_IT::
    .string "CUBONE: Cuuboon!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother_IT::
    .string "Odio quei terribili ROCKET!\p"
    .string "La povera madre di CUBONE…\p"
    .string "L'hanno uccisa mentre fuggiva dai\n"
    .string "ROCKET!$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone_IT::
    .string "Lo spettro della TORRE POKéMON se\n"
    .string "n'è andato!\p"
    .string "Qualcuno deve aver calmato la sua\n"
    .string "anima in pena!$"

