LavenderTown_House1_Text_Cubone_DE::
	.string "TRAGOSSO: Kiajahuu!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother_DE::
	.string "Ich hasse dieses furchtbare TEAM\n"
	.string "ROCKET!\p"
	.string "Die arme Mutter des TRAGOSSO!\p"
	.string "Sie konnte dem TEAM ROCKET nicht\n"
	.string "entkommen!$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone_DE::
	.string "Der GEIST im POKéMON-TURM ist\n"
	.string "verschwunden!\p"
	.string "Jemand muss seine rastlose Seele\n"
	.string "erlöst haben!$"

