LavenderTown_House1_Text_Cubone_FR::
	.string "OSSELAIT: Lailaii!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother_FR::
	.string "Je déteste ces méchants ROCKET!\p"
	.string "La pauvre mère d'OSSELAIT…\p"
	.string "Elle a disparu en essayant\n"
	.string "d'échapper à la TEAM ROCKET!$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone_FR::
	.string "Le SPECTRE de la TOUR POKéMON\n"
	.string "est parti!\p"
	.string "Quelqu'un a dû apaiser son âme\n"
	.string "tourmentée!$"

