LavenderTown_House1_Text_Cubone_ES::
    .string "CUBONE: ¡Cubon!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother_ES::
    .string "¡Odio a esos horribles ROCKET!\p"
    .string "La pobre madre de CUBONE...\p"
    .string "¡Intentó escapar del TEAM ROCKET,\n"
    .string "pero no lo consiguió!...$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone_ES::
    .string "¡El GHOST de la TORRE POKéMON\n"
    .string "se ha ido!\p"
    .string "¡Alguien debe de haber calmado\n"
    .string "su atormentada alma!$"
