SaffronCity_House_Text_DontLookAtMyLetter_FR::
	.string "Merci pour cette belle lettre, à\n"
	.string "bientôt!\p"
	.string "Hé! R'garde pas c'que j'écris!\n"
	.string "J'suis amoureuse!$"

SaffronCity_House_Text_Pidgey_FR::
	.string "ROUCOOL: Rourou!$"

SaffronCity_House_Text_GettingCopycatPokeDoll_FR::
	.string "La COPIEUSE est mignonne! Je vais\n"
	.string "lui offrir une POKéPOUPEE!$"

SaffronCity_House_Text_ExplainPPUp_FR::
	.string "J'ai reçu comme récompense\n"
	.string "un PP PLUS.\p"
	.string "Il sert à augmenter les PP d'une\n"
	.string "attaque d'un POKéMON.\p"
	.string "Je devrais choisir une attaque\n"
	.string "avec peu de PP.$"

