SaffronCity_House_Text_DontLookAtMyLetter_IT::
    .string "Grazie per avermi scritto.\n"
    .string "Spero di vederti presto!\p"
    .string "Ehi!\n"
    .string "Non leggere la mia lettera!$"

SaffronCity_House_Text_Pidgey_IT::
    .string "PIDGEY: Grugrù!$"

SaffronCity_House_Text_GettingCopycatPokeDoll_IT::
    .string "COPIONA è forte!\n"
    .string "Le porto una POKé BAMBOLA!$"

SaffronCity_House_Text_ExplainPPUp_IT::
    .string "Mi hanno regalato un PP-SU.\p"
    .string "Aumenta i PP degli attacchi!$"

