SaffronCity_House_Text_DontLookAtMyLetter_ES::
    .string "Gracias por escribir.\n"
    .string "¡Espero verte pronto!\p"
    .string "¡Oye!\n"
    .string "¡No mires mi carta!$"

SaffronCity_House_Text_Pidgey_ES::
    .string "PIDGEY: ¡Pid, pid!$"

SaffronCity_House_Text_GettingCopycatPokeDoll_ES::
    .string "¡La COPIONA es muy mona!\n"
    .string "¡Voy a darle un POKé MUÑECO!$"

SaffronCity_House_Text_ExplainPPUp_ES::
    .string "Recibí MÁS PP como regalo.\p"
    .string "¡Sirve para aumentar los PP de\n"
    .string "un movimiento de un POKéMON!\p"
    .string "Creo que voy a usarlo con un\n"
    .string "movimiento potente, que tenga\l"
    .string "pocos PP.$"
