SSAnne_2F_Room2_Text_BrooksIntro_IT::
    .string "Lottare contro i giovani mi tiene\n"
    .string "in forma!$"

SSAnne_2F_Room2_Text_BrooksDefeat_IT::
    .string "Bella lotta!\n"
    .string "Sono ringiovanito!!!$"

SSAnne_2F_Room2_Text_BrooksPostBattle_IT::
    .string "15 anni fa avrei vinto!!!$"

SSAnne_2F_Room2_Text_DaleIntro_IT::
    .string "Guarda cosa ho pescato!$"

SSAnne_2F_Room2_Text_DaleDefeat_IT::
    .string "Sono distrutto!!!$"

SSAnne_2F_Room2_Text_DalePostBattle_IT::
    .string "Una festa?\p"
    .string "La festa sulla nave dovrebbe\n"
    .string "essere già finita!$"

