SSAnne_2F_Room2_Text_BrooksIntro_ES::
    .string "¡Competir contra los jóvenes\n"
    .string "me mantiene como un chaval!$"

SSAnne_2F_Room2_Text_BrooksDefeat_ES::
    .string "¡Buena pelea!\n"
    .string "¡Vuelvo a sentirme joven!$"

SSAnne_2F_Room2_Text_BrooksPostBattle_ES::
    .string "¡Hace 15 años, yo habría ganado!$"

SSAnne_2F_Room2_Text_DaleIntro_ES::
    .string "¡Mira lo que he pescado!$"

SSAnne_2F_Room2_Text_DaleDefeat_ES::
    .string "¡Estoy acabado!$"

SSAnne_2F_Room2_Text_DalePostBattle_ES::
    .string "¿Una fiesta?\p"
    .string "La fiesta del crucero debe de\n"
    .string "haber terminado.$"
