FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland_FR::
	.string "OLGA: Je n'arrête pas de penzer\n"
	.string "à quelque choze.\p"
	.string "Z'il devait arriver malheur zur mon\n"
	.string "île natale pendant que je zuis\p"
	.string "à la LIGUE POKéMON…\p"
	.string "Je n'aurais aucun moyen de le\n"
	.string "zavoir…\p"
	.string "Est-ce que za fait de moi\n"
	.string "quelqu'un d'irresponzable?$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile_FR::
	.string "OLGA: Zo, alors tu as réuzzi à\n"
	.string "régler les problèmes?\p"
	.string "Z'est fantaztique!\p"
	.string "Za veut dire que je peux repartir\n"
	.string "l'ezprit tranquille.\p"
	.string "Merci…\p"
	.string "Je vais bientôt repartir pour la\n"
	.string "LIGUE POKéMON.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow_FR::
	.string "Je ne zais pas ze qui peut se\n"
	.string "pazzer dans le futur, mais…\p"
	.string "Tant que je zerai là, je\n"
	.string "protégerai zette île.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore_FR::
	.string "Il y a plein de poupées POKéMON.$"

