VermilionCity_Text_GrimerMultipliesInSludge_IT::
    .string "Noi teniamo molto all'ambiente!\p"
    .string "Pare che GRIMER si riproduca nel\n"
    .string "liquame tossico! Se fosse vero, non\l"
    .string "ne sarei affatto contenta!$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor_IT::
    .string "Hai visto la M/N ANNA ancorata al\n"
    .string "porto?$"

VermilionCity_Text_SSAnneHasDepartedForYear_IT::
    .string "La M/N ANNA è salpata!\n"
    .string "Tornerà tra un anno.$"

VermilionCity_Text_BuildingOnThisLand_IT::
    .string "Su questo terreno costruisco\n"
    .string "un edificio.\p"
    .string "I miei POKéMON stanno livellando\n"
    .string "la terra.$"

VermilionCity_Text_Machop_IT::
    .string "MACHOP: Ciop! Ciop!$"

VermilionCity_Text_MachopStompingLandFlat_IT::
    .string "Un MACHOP sta spianando la terra!$"

VermilionCity_Text_SSAnneVisitsOnceAYear_IT::
    .string "La M/N ANNA è una famosa nave di\n"
    .string "lusso.\p"
    .string "Approdiamo ad ARANCIOPOLI una\n"
    .string "volta l'anno.$"

VermilionCity_Text_CitySign_IT::
    .string "ARANCIOPOLI\n"
    .string "Porto dagli squisiti tramonti$"

VermilionCity_Text_SnorlaxBlockingRoute12_IT::
    .string "AVVISO:\p"
    .string "Il PERCORSO 12 può essere\n"
    .string "bloccato da un POKéMON\l"
    .string "addormentato.\p"
    .string "Deviazione per LAVANDONIA\n"
    .string "tramite il TUNNEL ROCCIOSO.\p"
    .string "POLIZIA di ARANCIOPOLI$"

VermilionCity_Text_PokemonFanClubSign_IT::
    .string "POKéMON FAN CLUB\n"
    .string "Tutti i fan POKéMON\l"
    .string "sono benvenuti!$"

VermilionCity_Text_GymSign_IT::
    .string "CAPOPALESTRA di ARANCIOPOLI:\n"
    .string "LT. SURGE\l"
    .string "L'americano fulminante!$"

VermilionCity_Text_VermilionHarbor_IT::
    .string "PORTO DI ARANCIOPOLI$"

VermilionCity_Text_WelcomeToTheSSAnne_IT::
    .string "Ti do il benvenuto sulla M/N ANNA!$"

VermilionCity_Text_DoYouHaveATicket_IT::
    .string "Ti do il benvenuto sulla M/N ANNA!\p"
    .string "Scusa, hai il biglietto?$"

VermilionCity_Text_FlashedSSTicket_IT::
    .string "{FONT_NORMAL}{PLAYER} mostra il BIGLIETTO per\n"
    .string "la NAVE!\p"
    .string "{FONT_MALE}Bene!\n"
    .string "Accomodati a bordo!$"

VermilionCity_Text_DontHaveNeededSSTicket_IT::
    .string "{FONT_NORMAL}{PLAYER} non ha il BIGLIETTO per\n"
    .string "la NAVE.\p"
    .string "{FONT_MALE}Mi dispiace!\p"
    .string "Serve un biglietto per imbarcarsi.$"

VermilionCity_Text_TheShipSetSail_IT::
    .string "La nave è salpata.$"

VermilionCity_Text_BoardSeagallopTriPass_IT::
    .string "Ah, vedo che hai il TRIS PASS.\p"
    .string "Vuoi imbarcarti sul POKéSCAFO?\n"
    .string "Dove vuoi andare?$"

VermilionCity_Text_Seagallop7Departing_IT::
    .string "Perfetto.\p"
    .string "Il POKéSCAFO 7 sta per partire.\n"
    .string "Sali a bordo!$"

VermilionCity_Text_BoardSeagallopRainbowPass_IT::
    .string "Ah, vedo che hai il SETTE PASS.\p"
    .string "Vuoi imbarcarti sul POKéSCAFO?\n"
    .string "Scegli la destinazione!$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock_IT::
    .string "Uh! Hai il BIGLIETTO MAGICO! Non\n"
    .string "mi capita spesso di vederne uno!\p"
    .string "Con quello, possiamo trasportarti\n"
    .string "fino al MONTE CORDONE, in qualsiasi\l"
    .string "momento!$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland_IT::
    .string "Hai il BIGLIETTO AURORA!\n"
    .string "È molto raro, sai?\p"
    .string "Con quello, possiamo trasportarti\n"
    .string "fino all'ISOLA MATERNA, in\l"
    .string "qualsiasi momento!$"

VermilionCity_Text_BoardSeagallopFerry_IT::
    .string "Vuoi imbarcarti su un POKéSCAFO?$"

VermilionCity_Text_Seagallop10Departing_IT::
    .string "Bene! Hai tutti i requisiti per\n"
    .string "salire a bordo di un'imbarcazione\l"
    .string "speciale.\p"
    .string "Il POKéSCAFO 10 sta per partire!$"

VermilionCity_Text_Seagallop12Departing_IT::
    .string "Bene! Hai tutti i requisiti per\n"
    .string "salire su un'imbarcazione\l"
    .string "speciale.\p"
    .string "Il POKéSCAFO 12 sta per partire!$"

VermilionCity_Text_Route2AideHasPackageForYou_IT::
    .string "Ciao, {PLAYER}!\n"
    .string "Come te la passi?\p"
    .string "Sono un ASSISTENTE del\n"
    .string "PROF. OAK.\p"
    .string "Hai già incontrato l'altro\n"
    .string "ASSISTENTE?\p"
    .string "Aveva un pacco per te, da parte\n"
    .string "del PROF. OAK!\p"
    .string "Ha detto che ti avrebbe\n"
    .string "aspettato al PERCORSO 2.\p"
    .string "Se capiti da quelle parti, ti\n"
    .string "consiglio di cercarlo.$"

