VermilionCity_Text_GrimerMultipliesInSludge_ES::
    .string "¡Nos preocupa la contaminación!\p"
    .string "¡Dicen que GRIMER se convierte\n"
    .string "en cantidades enormes de residuos\l"
    .string "tóxicos!$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor_ES::
    .string "¿Viste al S.S. ANNE anclado en el\n"
    .string "puerto?$"

VermilionCity_Text_SSAnneHasDepartedForYear_ES::
    .string "¡El S.S. ANNE ha zarpado!\n"
    .string "Volverá a CARMÍN en un año.$"

VermilionCity_Text_BuildingOnThisLand_ES::
    .string "Voy a construir un edificio en este\n"
    .string "trozo de tierra.\p"
    .string "Mi POKéMON está apisonando\n"
    .string "el terreno.$"

VermilionCity_Text_Machop_ES::
    .string "MACHOP: ¡Chop! ¡Chop!$"

VermilionCity_Text_MachopStompingLandFlat_ES::
    .string "¡Un MACHOP está apisonando\n"
    .string "el terreno!$"

VermilionCity_Text_SSAnneVisitsOnceAYear_ES::
    .string "El S.S. ANNE es un famoso y lujoso\n"
    .string "crucero.\p"
    .string "Visitamos CARMÍN una vez al año.$"

VermilionCity_Text_CitySign_ES::
    .string "CIUDAD CARMÍN\n"
    .string "El puerto de los ocasos exquisitos.$"

VermilionCity_Text_SnorlaxBlockingRoute12_ES::
    .string "¡AVISO!\p"
    .string "La RUTA 12 podría estar bloqueada\n"
    .string "por un POKéMON dormido.\p"
    .string "Desvíate a través del TÚNEL ROCA\n"
    .string "a PUEBLO LAVANDA.\p"
    .string "POLICÍA de CARMÍN$"

VermilionCity_Text_PokemonFanClubSign_ES::
    .string "CLUB DE FANS DE POKéMON\n"
    .string "¡Bienvenidos todos!$"

VermilionCity_Text_GymSign_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\l"
    .string "¡El Rayo americano!$"

VermilionCity_Text_VermilionHarbor_ES::
    .string "PUERTO CARMÍN$"

VermilionCity_Text_WelcomeToTheSSAnne_ES::
    .string "¡Éste es el S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket_ES::
    .string "¡Éste es el S.S. ANNE!\p"
    .string "Disculpe, ¿tiene su ticket?$"

VermilionCity_Text_FlashedSSTicket_ES::
    .string "{FONT_NORMAL}¡{PLAYER} enseñó el TICKET\n"
    .string "del BARCO!\p"
    .string "{FONT_MALE}¡OK!\n"
    .string "¡Adelante!$"

VermilionCity_Text_DontHaveNeededSSTicket_ES::
    .string "{FONT_NORMAL}{PLAYER} no tiene el TICKET del\n"
    .string "BARCO.\p"
    .string "{FONT_MALE}¡Lo siento!\p"
    .string "Necesita un ticket para subir a\n"
    .string "bordo.$"

VermilionCity_Text_TheShipSetSail_ES::
    .string "El barco zarpó.$"

VermilionCity_Text_BoardSeagallopTriPass_ES::
    .string "Ah, tienes el TRI-TICKET.\p"
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"

VermilionCity_Text_Seagallop7Departing_ES::
    .string "Estupendo, todo en regla.\p"
    .string "El SURCAMAR VELOCE 7\n"
    .string "va a zarpar en breve.$"

VermilionCity_Text_BoardSeagallopRainbowPass_ES::
    .string "Ah, tienes el IRIS-TICKET.\p"
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock_ES::
    .string "¡Anda, el MISTI-TICKET!\n"
    .string "¡Qué curioso!\p"
    .string "Estaremos encantados de llevarte\n"
    .string "a ROCA OMBLIGO cuando quieras.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland_ES::
    .string "¡Anda, el ORI-TICKET!\n"
    .string "¡Qué curioso!\p"
    .string "Estaremos encantados de llevarte\n"
    .string "a ISLA ORIGEN cuando quieras.$"

VermilionCity_Text_BoardSeagallopFerry_ES::
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"

VermilionCity_Text_Seagallop10Departing_ES::
    .string "Estupendo, todo está listo para\n"
    .string "que subas a bordo de un ferry\l"
    .string "muy especial.\p"
    .string "El SURCAMAR VELOCE 10\n"
    .string "va a zarpar en breve.$"

VermilionCity_Text_Seagallop12Departing_ES::
    .string "Estupendo, todo está listo para\n"
    .string "que subas a bordo de un ferry\l"
    .string "muy especial.\p"
    .string "El SURCAMAR VELOCE 12\n"
    .string "va a zarpar en breve.$"

VermilionCity_Text_Route2AideHasPackageForYou_ES::
    .string "¡Hola, {PLAYER}!\n"
    .string "¿Qué tal lo llevas?\p"
    .string "Soy uno de los AYUDANTES\n"
    .string "del PROF. OAK.\p"
    .string "¿Has visto ya al otro AYUDANTE?\p"
    .string "Tenía algo que entregarte de parte\n"
    .string "del PROF. OAK, {PLAYER}.\p"
    .string "Comentó que iría a buscarte por\n"
    .string "la RUTA 2, {PLAYER}.\p"
    .string "Si pasas por la RUTA 2, búscalo.$"
