VermilionCity_Text_GrimerMultipliesInSludge_FR::
	.string "On fait attention à l'environnement!\p"
	.string "On dit que les TADMORV se\n"
	.string "multiplient en zone toxique!$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor_FR::
	.string "As-tu vu L'OCEANE au port?$"

VermilionCity_Text_SSAnneHasDepartedForYear_FR::
	.string "L'OCEANE a levé l'ancre!\p"
	.string "Il reviendra l'an prochain.$"

VermilionCity_Text_BuildingOnThisLand_FR::
	.string "Je construis un immeuble sur ce\n"
	.string "terrain.\p"
	.string "Mes POKéMON dament le sol\n"
	.string "pour faire les fondations.$"

VermilionCity_Text_Machop_FR::
	.string "MACHOC: Maaaaa! Machoooo!$"

VermilionCity_Text_MachopStompingLandFlat_FR::
	.string "Un MACHOC pilonne le sol.$"

VermilionCity_Text_SSAnneVisitsOnceAYear_FR::
	.string "L'OCEANE est un paquebot de luxe.\p"
	.string "Nous nous rendons à CARMIN SUR\n"
	.string "MER une fois par an.$"

VermilionCity_Text_CitySign_FR::
	.string "CARMIN SUR MER\p"
	.string "Le port aux crépuscules\n"
	.string "flamboyants$"

VermilionCity_Text_SnorlaxBlockingRoute12_FR::
	.string "AVIS!\p"
	.string "La ROUTE 12 peut être bloquée par\n"
	.string "un POKéMON endormi.\p"
	.string "Prendre la GROTTE pour rejoindre\n"
	.string "LAVANVILLE.\p"
	.string "POLICE DE CARMIN SUR MER$"

VermilionCity_Text_PokemonFanClubSign_FR::
	.string "FAN CLUB POKéMON\p"
	.string "Tous les dingues de POKéMON\n"
	.string "sont bienvenus!$"

VermilionCity_Text_GymSign_FR::
	.string "ARENE POKéMON de CARMIN SUR MER\n"
	.string "CHAMPION: MAJOR BOB\l"
	.string "L'Américain Survolté!$"

VermilionCity_Text_VermilionHarbor_FR::
	.string "PORT DE CARMIN SUR MER$"

VermilionCity_Text_WelcomeToTheSSAnne_FR::
	.string "Bienvenue à bord de L'OCEANE!$"

VermilionCity_Text_DoYouHaveATicket_FR::
	.string "Bienvenue à bord de L'OCEANE!\p"
	.string "Puis-je voir votre passe?$"

VermilionCity_Text_FlashedSSTicket_FR::
	.string "{FONT_NORMAL}{PLAYER} montre le\n"
	.string "PASSE BATEAU en frimant.\p"
	.string "{FONT_MALE}Heu… merci!\n"
	.string "Bienvenue à bord!$"

VermilionCity_Text_DontHaveNeededSSTicket_FR::
	.string "{FONT_NORMAL}{PLAYER} n'a pas de passe!\p"
	.string "{FONT_MALE}Désolé!\p"
	.string "Il vous faut un passe pour monter\n"
	.string "à bord.$"

VermilionCity_Text_TheShipSetSail_FR::
	.string "L'OCEANE a levé l'ancre.$"

VermilionCity_Text_BoardSeagallopTriPass_FR::
	.string "Ah, vous avez le TRI-PASSE.\p"
	.string "Voulez-vous monter à bord\n"
	.string "d'un FERRY FLECHE DES MERS?$"

VermilionCity_Text_Seagallop7Departing_FR::
	.string "OK, tout est en ordre.\p"
	.string "Préparez-vous au départ de\n"
	.string "la FLECHE DES MERS 7.$"

VermilionCity_Text_BoardSeagallopRainbowPass_FR::
	.string "Ah, vous avez le PASSE PRISME.\p"
	.string "Voulez-vous monter à bord\n"
	.string "d'un FERRY FLECHE DES MERS?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock_FR::
	.string "Oh, c'est le TICKETMYSTIK!\n"
	.string "C'est un ticket très rare.\p"
	.string "Nous serons heureux de vous\n"
	.string "amener au ROC NOMBRI.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland_FR::
	.string "Oh, c'est le TICKETAURORA!\n"
	.string "C'est un ticket très rare.\p"
	.string "Nous serons heureux de vous\n"
	.string "amener à l'ILE AURORE.$"

VermilionCity_Text_BoardSeagallopFerry_FR::
	.string "Voulez-vous monter à bord\n"
	.string "d'un FERRY FLECHE DES MERS?$"

VermilionCity_Text_Seagallop10Departing_FR::
	.string "Très bien, tout est en ordre.\n"
	.string "Vous pouvez monter à bord.\p"
	.string "Préparez-vous au départ de\n"
	.string "la FLECHE DES MERS 10.$"

VermilionCity_Text_Seagallop12Departing_FR::
	.string "Très bien, tout est en ordre.\n"
	.string "Vous pouvez monter à bord.\p"
	.string "Préparez-vous au départ de\n"
	.string "la FLECHE DES MERS 12.$"

VermilionCity_Text_Route2AideHasPackageForYou_FR::
	.string "Tiens, bonjour {PLAYER}!\n"
	.string "Comment vas-tu?\p"
	.string "Je suis un des ASSISTANTS du\n"
	.string "PROF. CHEN.\p"
	.string "Tu as déjà rencontré un autre\n"
	.string "assistant?\p"
	.string "Il avait un paquet pour toi de la\n"
	.string "part du PROFESSEUR.\p"
	.string "Il a dit qu'il partait à ta\n"
	.string "rencontre vers la ROUTE 2.\p"
	.string "Si tu vas par là, essaie de le\n"
	.string "trouver, {PLAYER}.$"

