@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower_DE::
	.string "Hallo!\p"
	.string "Willkommen im TRAINERTURM,\n"
	.string "wo sich TRAINER von nah und\l"
	.string "fern versammeln.$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum_DE::
	.string "TRAINER aus aller Herren Länder\n"
	.string "kommen hierher, um zu kämpfen.\p"
	.string "Lass mich mal sehen…\p"
	.string "Momentan findest du TRAINER\n"
	.string "bis in Stockwerk {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor_DE::
	.string "Bis zum achten Stock erwarten\n"
	.string "TRAINER deine Herausforderung.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers_DE::
	.string "Möchtest du die wartenden\n"
	.string "TRAINER herausfordern?$"

TrainerTower_Lobby_Text_StartClockGetSetGo_DE::
	.string "O.K.! Ich stelle die Uhr! Gib\n"
	.string "dein Bestes!\p"
	.string "Auf die Plätze…\p"
	.string "Fertig…\p"
	.string "Los!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain_DE::
	.string "Bitte besuche uns wieder!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain_DE::
	.string "Das war nicht gut!\p"
	.string "Ich glaube, du hast dich beim\n"
	.string "Kampf richtig angestrengt.\p"
	.string "Bitte komme wieder und\n"
	.string "probiere es erneut!$"

TrainerTower_Lobby_Text_GiveItYourBest_DE::
	.string "Ich hoffe, du strengst dich\n"
	.string "wirklich an!$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch_DE::
	.string "Tauschen die TRAINER ihre\n"
	.string "Plätze, kann es hektisch werden.\p"
	.string "Um eine Panik zu vermeiden,\n"
	.string "haben wir die Rezeption hierher\l"
	.string "verlegt.\l"
	.string "Wir bitten um dein Verständnis!$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly_DE::
	.string "Hallo…\p"
	.string "Mir gehört dieser TURM…\p"
	.string "Wie der Himmel über dem Dach\n"
	.string "emporsteigt…\p"
	.string "Die Macht des Windes hier oben…\p"
	.string "Es ist so stimmig…\p"
	.string "Dein Kampfstil…\n"
	.string "Auch er war stimmig…$"

TrainerTower_Roof_Text_ThisIsForYou_DE::
	.string "Dies ist für dich…$"

TrainerTower_Roof_Text_DoneItInRecordTime_DE::
	.string "Oh!\n"
	.string "Fantastisch!\p"
	.string "Es ist bewundernswert, wie schnell\n"
	.string "du hier hochgekommen bist.\p"
	.string "Tatsächlich hast du einen neuen\n"
	.string "Rekord aufgestellt…\p"
	.string "Du kannst ihn an der Rezeption\n"
	.string "einsehen.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere_DE::
	.string "Es scheint, du hast dir ganz\n"
	.string "schön Zeit gelassen…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime_DE::
	.string "Ich will von dir eine bessere\n"
	.string "Zeit sehen…\p"
	.string "Ich verlasse mich auf dich!\p"
	.string "Bis demnächst, mach es gut…$"

TrainerTower_Text_XMinYZSec_DE::
	.string "{STR_VAR_1} Min. {STR_VAR_2},{STR_VAR_3} Sek.$"

TrainerTower_Lobby_Text_HereAreTheResults_DE::
	.string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble_DE::
	.string "Dies ist ein Zwei-gegen-Zwei-Kampf!\p"
	.string "Du musst mindestens zwei\n"
	.string "POKéMON mitbringen.$"

TrainerTower_Lobby_Text_ExplainTrainerTower_DE::
	.string "Hier im TRAINERTURM gibt es\n"
	.string "unter anderem den BESTZEIT-Modus.\l"
	.string "Es wird gestoppt, wie lange du von\l"
	.string "der Rezeption zum EIGENTÜMER\l"
	.string "auf dem Dach brauchst.\l"
	.string "Die besten Zeiten werden an der\l"
	.string "Rekordtafel präsentiert.\l"
	.string "Tritt gegen Freunde an, um zu\l"
	.string "sehen, wer der Schnellste ist.\l"
	.string "Hier gibt es keine E.-Punkte oder\l"
	.string "Geld zu gewinnen.$"

TrainerTower_Lobby_Text_ThanksForCompeting_DE::
	.string "Danke fürs Mitmachen!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers_DE::
	.string "Ich möchte herausfinden, wie gut\n"
	.string "ich bin.\p"
	.string "Ich bin gespannt, welche TRAINER\n"
	.string "auf mich warten.\p"
	.string "Das ist nervenaufreibend!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle_DE::
	.string "Schnauf, schnauf…\n"
	.string "Schnauf…\p"
	.string "Kämpfen macht mir nichts aus!\n"
	.string "Aber diese Treppen…\l"
	.string "Die sind härter als jeder Kampf…$"

