@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower_IT::
    .string "Ciao!\p"
    .string "Ti do il benvenuto nella TORRE\n"
    .string "ALLENATORI, dove si incontrano\l"
    .string "ALLENATORI da tutto il mondo!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum_IT::
    .string "ALLENATORI provenienti da tutto il\n"
    .string "mondo si incontrano qui per\l"
    .string "combattere!\p"
    .string "Vediamo…\p"
    .string "In questo momento, soltanto fino al\n"
    .string "piano {STR_VAR_1} si trovano ALLENATORI.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor_IT::
    .string "Ci sono ALLENATORI fino all'ottavo\n"
    .string "piano, tutti pronti a sfidarti!$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers_IT::
    .string "Desideri sfidare gli ALLENATORI\n"
    .string "in attesa?$"

TrainerTower_Lobby_Text_StartClockGetSetGo_IT::
    .string "Bene. Sto per azionare l'orologio.\n"
    .string "Metticela tutta!\p"
    .string "Pronti…\p"
    .string "Ai posti…\p"
    .string "Via!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain_IT::
    .string "Torna a trovarci!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain_IT::
    .string "Mi spiace molto.\p"
    .string "So che hai lottato con il\n"
    .string "massimo impegno!\p"
    .string "Beh, quando vuoi riprovare,\n"
    .string "torna a trovarci!$"

TrainerTower_Lobby_Text_GiveItYourBest_IT::
    .string "Mi raccomando, metticela tutta!$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch_IT::
    .string "A volte il via vai di ALLENATORI è\n"
    .string "davvero intenso.\p"
    .string "Così abbiamo dovuto spostare qui\n"
    .string "il banco di accettazione.\p"
    .string "Scusa per l'inconveniente.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly_IT::
    .string "Ciao…\p"
    .string "Sono il proprietario della TORRE…\p"
    .string "Il tetto che si staglia contro\n"
    .string "l'azzurro intenso del cielo…\p"
    .string "La brezza carezzevole…\p"
    .string "Che atmosfera perfetta…\p"
    .string "La stessa perfezione che ho\n"
    .string "visto nel tuo stile di lotta.$"

TrainerTower_Roof_Text_ThisIsForYou_IT::
    .string "Ecco, questo è per te.$"

TrainerTower_Roof_Text_DoneItInRecordTime_IT::
    .string "Perfetto!\p"
    .string "Ci hai messo davvero poco\n"
    .string "ad arrivare fin quassù!\p"
    .string "Hai stabilito un record,\n"
    .string "sai?\p"
    .string "Affiggerò un cartello con il\n"
    .string "tuo record al banco di\l"
    .string "accettazione.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere_IT::
    .string "Ci hai messo un po' troppo tempo\n"
    .string "ad arrivare qui.$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime_IT::
    .string "Sai cosa vorrei da te? Un tempo\n"
    .string "ancora migliore!\p"
    .string "Conto su di te!\p"
    .string "Beh, ci vediamo…$"

TrainerTower_Text_XMinYZSec_IT::
    .string "{STR_VAR_1} min. e {STR_VAR_2},{STR_VAR_3} sec.$"

TrainerTower_Lobby_Text_HereAreTheResults_IT::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble_IT::
    .string "Questa è una lotta 2 contro 2. \n"
    .string "Significa che per combattere devi\l"
    .string "avere almeno due POKéMON con te.$"

TrainerTower_Lobby_Text_ExplainTrainerTower_IT::
    .string "Alla TORRE ALLENATORI c'è una\n"
    .string "competizione chiamata CRONOLOTTA.\p"
    .string "Il tempo che impieghi per giungere\n"
    .string "fino al PROPRIETARIO, sul tetto,\l"
    .string "viene cronometrato.\p"
    .string "Il miglior tempo viene scritto sulla\n"
    .string "Lavagna Record!\p"
    .string "Battere gli ALLENATORI qui non ti\n"
    .string "fa guadagnare né punti ESP. né\l"
    .string "soldi.$"

TrainerTower_Lobby_Text_ThanksForCompeting_IT::
    .string "Grazie per aver partecipato!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers_IT::
    .string "Sono venuta qui per mettermi alla\n"
    .string "prova! Chissà quali ALLENATORI\l"
    .string "mi attendono!\p"
    .string "Sono elettrizzata!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle_IT::
    .string "Gasp, gasp…\n"
    .string "Gasp…\p"
    .string "Queste scale… sono più stancanti\n"
    .string "di cinquanta lotte!$"

