@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower_ES::
    .string "¡Hola!\p"
    .string "¡Ésta es la TORRE DESAFÍO, punto\n"
    .string "de encuentro de ENTRENADORES\l"
    .string "de todos sitios!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum_ES::
    .string "Aquí vienen ENTRENADORES de todo\n"
    .string "el mundo para luchar.\p"
    .string "A ver, ahora mismo...\p"
    .string "Hay ENTRENADORES hasta\n"
    .string "el piso {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor_ES::
    .string "Hay ENTRENADORES esperándote\n"
    .string "para luchar hasta el octavo piso.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers_ES::
    .string "¿Quieres enfrentarte a ellos?$"

TrainerTower_Lobby_Text_StartClockGetSetGo_ES::
    .string "Muy bien, voy a poner el reloj\n"
    .string "en hora. ¡A por todas!\p"
    .string "A sus puestos...\p"
    .string "Preparados..., listos...\p"
    .string "¡Ya!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain_ES::
    .string "¡Vuelve cuando quieras!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain_ES::
    .string "Qué pena...\p"
    .string "La verdad es que te has esforzado\n"
    .string "mucho.\p"
    .string "¡Bueno, otra vez será!$"

TrainerTower_Lobby_Text_GiveItYourBest_ES::
    .string "¡Demuestra lo que sabes!$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch_ES::
    .string "Cuando los ENTRENADORES se\n"
    .string "cambian de sitio, organizan una...\l"
    .string "tremenda.\p"
    .string "Para evitar tanto follón pusimos\n"
    .string "la recepción aquí.\p"
    .string "Disculpa las molestias.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly_ES::
    .string "Hola.\p"
    .string "Soy el dueño de esta TORRE.\p"
    .string "La forma en que el cielo se\n"
    .string "extiende por encima de nosotros...\p"
    .string "La manera en que nos acaricia\n"
    .string "el viento...\p"
    .string "¡Es una maravilla!...\p"
    .string "Y la forma en que has luchado...\n"
    .string "es también espectacular...$"

TrainerTower_Roof_Text_ThisIsForYou_ES::
    .string "Esto es para ti...$"

TrainerTower_Roof_Text_DoneItInRecordTime_ES::
    .string "¡Estupendo!\n"
    .string "¡Maravilloso!\p"
    .string "¡Es extraordinario que hayas\n"
    .string "llegado tan rápido!\p"
    .string "La cosa es que lo has conseguido\n"
    .string "en tiempo récord...\p"
    .string "Voy a ponerlo junto a uno de los\n"
    .string "mostradores de la recepción.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere_ES::
    .string "Se ve que no te has dado mucha\n"
    .string "prisa en llegar hasta aquí...$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime_ES::
    .string "Me gustaría ver que consigues\n"
    .string "un tiempo mejor...\p"
    .string "Espero que no me defraudes.\p"
    .string "Nos vemos.$"

TrainerTower_Text_XMinYZSec_ES::
    .string "{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s$"

TrainerTower_Lobby_Text_HereAreTheResults_ES::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble_ES::
    .string "Esto es un combate doble.\p"
    .string "Si no tienes dos POKéMON,\n"
    .string "no podrás participar.$"

TrainerTower_Lobby_Text_ExplainTrainerTower_ES::
    .string "En la TORRE DESAFÍO, se lucha\n"
    .string "a CONTRARRELOJ.\p"
    .string "Cronometraremos lo que tardes\n"
    .string "en alcanzar al DUEÑO en el último\l"
    .string "piso, en cuanto dejes la recepción.\p"
    .string "Los mejores tiempos podrán verse\n"
    .string "en el marcador.\p"
    .string "Compite con tus amigos para ver\n"
    .string "quién tarda menos.\p"
    .string "¡Ah, piensa que aquí no se ganan\n"
    .string "puntos de EXP. ni dinero!$"

TrainerTower_Lobby_Text_ThanksForCompeting_ES::
    .string "¡Gracias por participar!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers_ES::
    .string "Yo he venido para ver lo fuerte\n"
    .string "que soy.\p"
    .string "¿Cómo serán los ENTRENADORES con\n"
    .string "los que me tendré que enfrentar?\p"
    .string "¡Qué nervios!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle_ES::
    .string "Uffffff...\n"
    .string "Estoy agotado...\p"
    .string "¡No por los combates, no!\n"
    .string "¡Es por las escaleras!...\l"
    .string "¡Son peores que las peleas!$"
