PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow_FR::
	.string "Un POKéMON apprend des attaques\n"
	.string "en gagnant des niveaux!\p"
	.string "Mais certaines attaques ne sont\n"
	.string "enseignées que par certaines\l"
	.string "personnes!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused_FR::
	.string "Les POKéMON sont plus faciles à\n"
	.string "capturer s'ils ont un problème\l"
	.string "de statut!\p"
	.string "Sommeil, poison, brûlure ou\n"
	.string "paralysie sont très efficaces. \p"
	.string "Mais attraper un POKéMON, c'est\n"
	.string "jamais du tout cuit!$"

