PokemonLeague_LoreleisRoom_Text_Intro_DE::
	.string "Willkommen in der POKéMON LIGA!\p"
	.string "Ich bin LORELEI und gehöre zu den\n"
	.string "TOP VIER!\p"
	.string "Niemand kann sich mit mir messen,\n"
	.string "wenn es um EIS-POKéMON geht!\p"
	.string "Die Kraft von EIS-Attacken ist\n"
	.string "unglaublich!\p"
	.string "Du wirst um Gnade winseln, wenn ich\n"
	.string "deine POKéMON eingefroren habe!\p"
	.string "Hahaha!\n"
	.string "Bist du bereit?{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro_DE::
	.string "Willkommen in der POKéMON LIGA!\p"
	.string "Ich, LORELEI von den TOP\n"
	.string "VIER, bin zurückgekehrt!\p"
	.string "Du weißt ja Bescheid! Niemand\n"
	.string "kann sich mit mir messen,\l"
	.string "wenn es um EIS-POKéMON geht!\l"
	.string "Die Kraft von EIS-Attacken ist\l"
	.string "unglaublich!\p"
	.string "Du wirst um Gnade winseln, wenn ich\n"
	.string "deine POKéMON eingefroren habe!\p"
	.string "Hahaha!\n"
	.string "Bist du bereit?{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat_DE::
	.string "… es sollte nicht so laufen!$"

PokemonLeague_LoreleisRoom_Text_PostBattle_DE::
	.string "Du bist besser,\n"
	.string "als ich dachte!\l"
	.string "Geh ruhig weiter!\p"
	.string "Das hier war nur\n"
	.string "ein Vorgeschmack\l"
	.string "auf die Dinge,\l"
	.string "die dich noch\l"
	.string "erwarten...$"

