CeladonCity_Gym_Text_ErikaIntro_ES::
    .string "¡Hola! ¡Qué buen tiempo hace!\n"
    .string "Es tan agradable.\p"
    .string "¡Ah, hola!... ¡Debo de haberme\n"
    .string "dormido! ¿Qué tal?\p"
    .string "Me llamo ERIKA. Soy la LÍDER del\n"
    .string "GIMNASIO de CIUDAD AZULONA.\p"
    .string "Enseño el arte de las flores.\n"
    .string "Mis POKéMON son del tipo PLANTA.\p"
    .string "¡Oh, perdona! ¡No tenía ni idea de\n"
    .string "que quisieras desafiarme!\p"
    .string "¡Como quieras! ¡No pienso perder!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat_ES::
    .string "¡Reconozco mi derrota!\p"
    .string "Eres muy fuerte.\p"
    .string "Te voy a dar la MEDALLA ARCOIRIS.$"

CeladonCity_Gym_Text_ErikaPostBattle_ES::
    .string "¿Estás estudiando a los POKéMON?\n"
    .string "Admito que me has impresionado.\p"
    .string "No coleccionaría POKéMON si\n"
    .string "fueran feos.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis_ES::
    .string "La MEDALLA ARCOIRIS hará que los\n"
    .string "POKéMON de nivel inferior a 50 te\l"
    .string "obedezcan.\p"
    .string "Y permitirá que los POKéMON usen\n"
    .string "FUERZA siempre que quieras.\p"
    .string "¡Ah, llévate esto también!$"

CeladonCity_Gym_Text_ReceivedTM19FromErika_ES::
    .string "¡{PLAYER} recibió la MT19\n"
    .string "de manos de ERIKA!$"

CeladonCity_Gym_Text_ExplainTM19_ES::
    .string "La MT19 contiene GIGADRENADO.\p"
    .string "La mitad del daño que produce es\n"
    .string "usado para curar a tus POKéMON.\p"
    .string "No me digas que no es estupenda.$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis_ES::
    .string "Deberías hacerle sitio a esto.$"

CeladonCity_Gym_Text_KayIntro_ES::
    .string "¿Sabes una cosa de este GIMNASIO?\p"
    .string "¡Es sólo para chicas!$"

CeladonCity_Gym_Text_KayDefeat_ES::
    .string "¡Eres demasiado fuerte!$"

CeladonCity_Gym_Text_KayPostBattle_ES::
    .string "¡Eeeh!\n"
    .string "¡Espero que ERIKA acabe contigo!$"

CeladonCity_Gym_Text_BridgetIntro_ES::
    .string "Ah, hola.\n"
    .string "Estaba empezando a aburrirme.$"

CeladonCity_Gym_Text_BridgetDefeat_ES::
    .string "¡Oh! ¡Mi maquillaje!$"

CeladonCity_Gym_Text_BridgetPostBattle_ES::
    .string "¡Los POKéMON del tipo PLANTA\n"
    .string "son difíciles para los acuáticos!\p"
    .string "¡Y tienen ventaja sobre los del\n"
    .string "tipo ROCA y los del tipo TIERRA!$"

CeladonCity_Gym_Text_TinaIntro_ES::
    .string "Pero ¿tú no has estado ya por\n"
    .string "aquí?$"

CeladonCity_Gym_Text_TinaDefeat_ES::
    .string "¡Estoy impresionada!$"

CeladonCity_Gym_Text_TinaPostBattle_ES::
    .string "Ah, estabas buscando a ERIKA,\n"
    .string "no a mí.$"

CeladonCity_Gym_Text_TamiaIntro_ES::
    .string "¡Mira mis POKéMON del tipo\n"
    .string "PLANTA!\p"
    .string "¡Son tan fáciles de entrenar!...$"

CeladonCity_Gym_Text_TamiaDefeat_ES::
    .string "¡No!$"

CeladonCity_Gym_Text_TamiaPostBattle_ES::
    .string "¡En nuestro GIMNASIO sólo luchamos\n"
    .string "con POKéMON del tipo PLANTA!\p"
    .string "¡Y también los usamos para hacer\n"
    .string "adornos florales!$"

CeladonCity_Gym_Text_LisaIntro_ES::
    .string "¡Aquí no pueden entrar los POKéMON\n"
    .string "del tipo FUEGO o del tipo BICHO!$"

CeladonCity_Gym_Text_LisaDefeat_ES::
    .string "¡Oh!\n"
    .string "¡Cómo eres!$"

CeladonCity_Gym_Text_LisaPostBattle_ES::
    .string "¡ERIKA, nuestra LÍDER, puede\n"
    .string "parecer muy tranquila, pero es muy\l"
    .string "hábil!$"

CeladonCity_Gym_Text_LoriIntro_ES::
    .string "Encantada de conocerte. A mí\n"
    .string "me encanta entrenar POKéMON.$"

CeladonCity_Gym_Text_LoriDefeat_ES::
    .string "¡Oh!\n"
    .string "¡Espléndido!$"

CeladonCity_Gym_Text_LoriPostBattle_ES::
    .string "Voy a tener una cita a ciegas.\n"
    .string "¡Y debo aprender buenos modales!$"

CeladonCity_Gym_Text_MaryIntro_ES::
    .string "¡Éste es el GIMNASIO de AZULONA!\p"
    .string "¡Las encantadoras chicas que hay\n"
    .string "aquí son muy fuertes!$"

CeladonCity_Gym_Text_MaryDefeat_ES::
    .string "¡Me has ganado!$"

CeladonCity_Gym_Text_MaryPostBattle_ES::
    .string "¡No he traído a mis mejores\n"
    .string "POKéMON! ¡Ya verás la próxima\l"
    .string "vez!$"

CeladonCity_Gym_Text_GymStatue_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
