CeladonCity_Gym_Text_ErikaIntro_DE::
	.string "Ist das Wetter nicht wundervoll?\n"
	.string "Einfach herrlich!\p"
	.string "Du meine Güte... ich muss kurz\n"
	.string "eingenickt sein! Willkommen!\p"
	.string "Ich bin ERIKA, die ARENALEITERIN\n"
	.string "von PRISMANIA CITY!\p"
	.string "Ich liebe die Kräfte der Natur!\n"
	.string "Deshalb trainiere ich PFLANZEN-\l"
	.string "POKéMON.\p"
	.string "Du möchtest gegen mich antreten?\n"
	.string "Also gut!\p"
	.string "Ich werde ohnehin nicht verlieren!$"

CeladonCity_Gym_Text_ErikaDefeat_DE::
	.string "Ich muss meine Niederlage\n"
	.string "eingestehen!\p"
	.string "Deine Stärke ist beachtlich!\n"
	.string "Ich übergebe dir den FARBORDEN!$"

CeladonCity_Gym_Text_ErikaPostBattle_DE::
	.string "Du katalogisierst POKéMON?\n"
	.string "Ich bin beeindruckt!\p"
	.string "Ich würde niemals POKéMON sammeln,\n"
	.string "die mich nicht interessieren!$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis_DE::
	.string "Der FARBORDEN lässt POKéMON bis\n"
	.string "Level 50 deinen Befehlen folgen!\p"
	.string "Außerdem können deine POKéMON nun\n"
	.string "STÄRKE außerhalb von Kämpfen\l"
	.string "anwenden.\p"
	.string "Nimm bitte noch dieses Geschenk:$"

CeladonCity_Gym_Text_ReceivedTM19FromErika_DE::
	.string "{PLAYER} erhält\n"
	.string "TM19!$"

CeladonCity_Gym_Text_ExplainTM19_DE::
	.string "TM19 ist GIGASAUGER.\p"
	.string "Dein POKéMON erhält die Hälfte der\n"
	.string "KP, die diese Attacke dem Gegner\l"
	.string "abzieht!$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis_DE::
	.string "Du solltest etwas Platz schaffen!$"

CeladonCity_Gym_Text_KayIntro_DE::
	.string "Ich sollte dir etwas über diese\n"
	.string "ARENA erzählen.\l"
	.string "Nur echte Damen sind hier\l"
	.string "zugelassen!$"

CeladonCity_Gym_Text_KayDefeat_DE::
	.string "Sei nicht so grob zu mir!$"

CeladonCity_Gym_Text_KayPostBattle_DE::
	.string "Buääh!\n"
	.string "Das wird ERIKA dir heimzahlen!$"

CeladonCity_Gym_Text_BridgetIntro_DE::
	.string "Mir wurde es schon langweilig!$"

CeladonCity_Gym_Text_BridgetDefeat_DE::
	.string "Meine Frisur!\n"
	.string "Ganz zerzaust!$"

CeladonCity_Gym_Text_BridgetPostBattle_DE::
	.string "PFLANZEN-POKéMON sind gegenüber\n"
	.string "WASSER-POKéMON im Vorteil!\p"
	.string "Ebenso sind sie STEIN- und\n"
	.string "BODEN-POKéMON überlegen!$"

CeladonCity_Gym_Text_TinaIntro_DE::
	.string "… hast du nicht schon\n"
	.string "einmal hier herein geschaut?$"

CeladonCity_Gym_Text_TinaDefeat_DE::
	.string "Ich bin schockiert!$"

CeladonCity_Gym_Text_TinaPostBattle_DE::
	.string "Oh, du hast ERIKA angesehen…\n"
	.string "und nicht mich…$"

CeladonCity_Gym_Text_TamiaIntro_DE::
	.string "Schau dir meine PFLANZEN-POKéMON\n"
	.string "an!\p"
	.string "Man kann sie ohne Mühe trainieren!$"

CeladonCity_Gym_Text_TamiaDefeat_DE::
	.string "Nein!$"

CeladonCity_Gym_Text_TamiaPostBattle_DE::
	.string "Wir trainieren ausschließlich\n"
	.string "PFLANZEN-POKéMON in unserer\l"
	.string "ARENA!\p"
	.string "Wir lieben die Kräfte der Natur!$"

CeladonCity_Gym_Text_LisaIntro_DE::
	.string "Bringe bloß keine KÄFER- oder\n"
	.string "FEUER-POKéMON hierher!$"

CeladonCity_Gym_Text_LisaDefeat_DE::
	.string "Oh!\n"
	.string "Du Grobian!$"

CeladonCity_Gym_Text_LisaPostBattle_DE::
	.string "Wenngleich ERIKA schüchtern wirkt,\n"
	.string "ist sie eine sehr begabte\l"
	.string "ARENALEITERIN!$"

CeladonCity_Gym_Text_LoriIntro_DE::
	.string "Ich habe die Ehre... ich liebe\n"
	.string "POKéMON-Kämpfe!$"

CeladonCity_Gym_Text_LoriDefeat_DE::
	.string "Oh!\n"
	.string "Ausgezeichnet!$"

CeladonCity_Gym_Text_LoriPostBattle_DE::
	.string "Es war mir eine Ehre! Wunderbar!\n"
	.string "Mein Benimm-Kurs zeigt Wirkung!$"

CeladonCity_Gym_Text_MaryIntro_DE::
	.string "Willkommen in der POKéMON-ARENA\n"
	.string "von PRISMANIA CITY!\p"
	.string "Unterschätze niemals die Girl-\n"
	.string "Power!$"

CeladonCity_Gym_Text_MaryDefeat_DE::
	.string "Ich habe verloren!$"

CeladonCity_Gym_Text_MaryPostBattle_DE::
	.string "Meine besten POKéMON hatte ich\n"
	.string "nicht dabei!\p"
	.string "Warte nur, beim nächsten Mal…$"

CeladonCity_Gym_Text_GymStatue_DE::
	.string "PRISMANIA POKéMON-ARENA\n"
	.string "LEITUNG: ERIKA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon_DE::
	.string "PRISMANIA POKéMON-ARENA\n"
	.string "LEITUNG: ERIKA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

