CeladonCity_Gym_Text_ErikaIntro_IT::
    .string "Ciao!\n"
    .string "Che tempo magnifico, vero?\l"
    .string "Si sta benissimo.\p"
    .string "…Oh, accidenti!…\n"
    .string "Devo essermi addormentata!\l"
    .string "Accomodati!\p"
    .string "Mi chiamo ERIKA.\n"
    .string "Sono il CAPOPALESTRA di\l"
    .string "AZZURROPOLI.\p"
    .string "Studio l'arte delle composizioni\n"
    .string "floreali. I miei POKéMON sono\l"
    .string "di tipo ERBA.\p"
    .string "Oh, scusa! Non avevo capito che\n"
    .string "volevi sfidarmi!\p"
    .string "Come desideri!\n"
    .string "Ma io non perderò!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat_IT::
    .string "Ammetto la sconfitta!\n"
    .string "Sei veramente molto forte.\p"
    .string "Ti darò la MEDAGLIA ARCOBALENO.$"

CeladonCity_Gym_Text_ErikaPostBattle_IT::
    .string "Stai catalogando i POKéMON?\n"
    .string "Sono colpita!\p"
    .string "Non collezionerei mai POKéMON\n"
    .string "bruttini.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis_IT::
    .string "La MEDAGLIA ARCOBALENO farà\n"
    .string "obbedire tutti i POKéMON fino al\l"
    .string "livello 50.\p"
    .string "Inoltre i POKéMON potranno usare\n"
    .string "FORZA anche quando non stanno\l"
    .string "lottando.\p"
    .string "Ah! Porta anche questo con te.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika_IT::
    .string "{PLAYER} riceve\n"
    .string "la MT19!$"

CeladonCity_Gym_Text_ExplainTM19_IT::
    .string "La MT19 contiene GIGASSORBIMENTO.\p"
    .string "La metà del danno inflitto tornerà\n"
    .string "al tuo POKéMON come energia.$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis_IT::
    .string "Non hai abbastanza spazio.$"

CeladonCity_Gym_Text_KayIntro_IT::
    .string "Solo le vere signore possono\n"
    .string "diventare membri di questa\l"
    .string "PALESTRA.$"

CeladonCity_Gym_Text_KayDefeat_IT::
    .string "Sei troppo forte!$"

CeladonCity_Gym_Text_KayPostBattle_IT::
    .string "Bleeh!\n"
    .string "Spero che ERIKA ti spazzi via!$"

CeladonCity_Gym_Text_BridgetIntro_IT::
    .string "Mi stavo proprio annoiando.$"

CeladonCity_Gym_Text_BridgetDefeat_IT::
    .string "Oh!\n"
    .string "Il mio trucco!$"

CeladonCity_Gym_Text_BridgetPostBattle_IT::
    .string "I POKéMON di tipo ERBA sono\n"
    .string "efficaci contro quelli di tipo\l"
    .string "ACQUA!\p"
    .string "Hanno anche un certo vantaggio su\n"
    .string "quelli di tipo ROCCIA e TERRA!$"

CeladonCity_Gym_Text_TinaIntro_IT::
    .string "Non stavi sbirciando, prima?$"

CeladonCity_Gym_Text_TinaDefeat_IT::
    .string "Sconvolgente!$"

CeladonCity_Gym_Text_TinaPostBattle_IT::
    .string "Ah, ma stavi osservando ERIKA,\n"
    .string "non me!$"

CeladonCity_Gym_Text_TamiaIntro_IT::
    .string "Guarda i miei POKéMON di tipo\n"
    .string "ERBA!\p"
    .string "Sono molto facili da allenare!$"

CeladonCity_Gym_Text_TamiaDefeat_IT::
    .string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle_IT::
    .string "In questa PALESTRA usiamo solo\n"
    .string "POKéMON di tipo ERBA!\p"
    .string "Li usiamo persino per le nostre\n"
    .string "composizioni floreali!$"

CeladonCity_Gym_Text_LisaIntro_IT::
    .string "Niente POKéMON di tipo FUOCO,\n"
    .string "né di tipo COLEOTTERO, qui!$"

CeladonCity_Gym_Text_LisaDefeat_IT::
    .string "Ehi tu!\n"
    .string "Insolente!$"

CeladonCity_Gym_Text_LisaPostBattle_IT::
    .string "ERIKA, il nostro CAPOPALESTRA,\n"
    .string "è molto tranquilla, ma altrettanto\l"
    .string "capace!$"

CeladonCity_Gym_Text_LoriIntro_IT::
    .string "Piacere di conoscerti.\n"
    .string "Per hobby alleno i POKéMON.$"

CeladonCity_Gym_Text_LoriDefeat_IT::
    .string "Oh!\n"
    .string "Splendido!$"

CeladonCity_Gym_Text_LoriPostBattle_IT::
    .string "Ho un appuntamento al buio. È\n"
    .string "meglio che impari le buone maniere.$"

CeladonCity_Gym_Text_MaryIntro_IT::
    .string "Questa è la PALESTRA di\n"
    .string "AZZURROPOLI!\p"
    .string "Non sottovalutare il potere\n"
    .string "femminile!$"

CeladonCity_Gym_Text_MaryDefeat_IT::
    .string "Oh!\n"
    .string "Hai vinto!$"

CeladonCity_Gym_Text_MaryPostBattle_IT::
    .string "Non ho usato il mio migliore\n"
    .string "POKéMON!\p"
    .string "Vedrai la prossima volta!$"

CeladonCity_Gym_Text_GymStatue_IT::
    .string "PALESTRA di AZZURROPOLI:\n"
    .string "ERIKA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon_IT::
    .string "PALESTRA di AZZURROPOLI:\n"
    .string "ERIKA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

