CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink_FR::
	.string "J'ai soif!\n"
	.string "Je voudrais boire un truc!\p"
	.string "{FONT_NORMAL}Lui offrir à boire?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink_FR::
	.string "Quelle boisson lui offrir?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis_FR::
	.string "Ouais ouais!\p"
	.string "De l'EAU FRAICHE!\p"
	.string "C'est cool!\n"
	.string "Tiens… c'est pour toi!$"

Text_ReceivedItemFromLittleGirl_FR::
	.string "{PLAYER} reçoit\n"
	.string "la {STR_VAR_2}!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16_FR::
	.string "CT16:\n"
	.string "MUR LUMIERE!\p"
	.string "C'est une capacité qui affaiblit\n"
	.string "l'attaque spéciale de l'ennemi.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis_FR::
	.string "Ouaiiis!\p"
	.string "Du SODA COOL!\p"
	.string "Merciiii!\n"
	.string "Tiens, prends ça!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20_FR::
	.string "CT20:\n"
	.string "RUNE PROTECT!\p"
	.string "C'est une capacité qui empêche\n"
	.string "les problèmes de statut.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis_FR::
	.string "Ouaiiis!\p"
	.string "D'la LIMONADE!\p"
	.string "Merci beaucoup!\n"
	.string "V'là pour toi!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33_FR::
	.string "CT33:\n"
	.string "PROTECTION!\p"
	.string "C'est une capacité qui affaiblit les\n"
	.string "attaques physiques de l'ennemi.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis_FR::
	.string "Plus de place!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll_FR::
	.string "Heu… Non merci.\n"
	.string "J'ai plus soif en fait!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature_FR::
	.string "Ma sœur est DRESSEUR.\n"
	.string "Tu le crois, ça?\p"
	.string "Mais c'est une p'tite peste!\n"
	.string "Elle m'agace!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink_FR::
	.string "J'ai soif!\n"
	.string "Je veux boire!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign_FR::
	.string "TOIT:\n"
	.string "DISTRIBUTEURS$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave_FR::
	.string "Un distributeur!\n"
	.string "Que choisir?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney_FR::
	.string "Oups! Pas assez d'argent!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut_FR::
	.string "Et hop! {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff_FR::
	.string "L'inventaire est plein!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty_FR::
	.string "Pas soif!$"

