CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink_IT::
    .string "Ho sete!\n"
    .string "Vorrei qualcosa da bere!\p"
    .string "{FONT_NORMAL}Le dai da bere?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink_IT::
    .string "Quale bibita le dai?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis_IT::
    .string "Ehi!\p"
    .string "ACQUA FRESCA!\p"
    .string "Grazie!\n"
    .string "Prendila, è per te!$"

Text_ReceivedItemFromLittleGirl_IT::
    .string "{PLAYER} riceve\n"
    .string "{STR_VAR_2}!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16_IT::
    .string "MT16 contiene SCHERMOLUCE!\p"
    .string "Indebolisce gli attacchi SPECIALI\n"
    .string "del tuo nemico.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis_IT::
    .string "Fantastico!\p"
    .string "GASSOSA!\p"
    .string "Grazie!\n"
    .string "Prendila, è per te!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20_IT::
    .string "MT20 contiene SALVAGUARDIA!\p"
    .string "Serve ad evitare ai tuoi POKéMON\n"
    .string "problemi di stato.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis_IT::
    .string "Forte!\p"
    .string "LEMONSUCCO!\p"
    .string "Grazie!\n"
    .string "Prendilo, è per te!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33_IT::
    .string "MT33 contiene RIFLESSO!\p"
    .string "Indebolisce gli attacchi fisici\n"
    .string "dell'avversario.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis_IT::
    .string "Non hai più spazio per questo!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll_IT::
    .string "No, grazie!\n"
    .string "Tanto non ho molta sete!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature_IT::
    .string "Mia sorella è un ALLENATORE, che\n"
    .string "tu ci creda o no!\p"
    .string "Ma è così immatura che mi fa\n"
    .string "perdere le staffe!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink_IT::
    .string "Ho sete!\n"
    .string "Vorrei qualcosa da bere!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign_IT::
    .string "TETTO:\n"
    .string "DISTRIBUTORI AUTOMATICI$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave_IT::
    .string "Un distributore!\n"
    .string "Ecco i prodotti!$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney_IT::
    .string "Caspita, non ho abbastanza soldi!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut_IT::
    .string "È uscita una lattina di\n"
    .string "{STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff_IT::
    .string "Non hai più spazio per nient'altro!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty_IT::
    .string "Non ho sete!$"

