CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink_ES::
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!\p"
    .string "{FONT_NORMAL}¿Le das algo de beber?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink_ES::
    .string "¿Qué bebida quieres darle?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis_ES::
    .string "¡Yay!\p"
    .string "¡AGUA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

Text_ReceivedItemFromLittleGirl_ES::
    .string "¡{PLAYER} recibió la {STR_VAR_2}\n"
    .string "de manos de la chica!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16_ES::
    .string "¡MT16 contiene PANTALLA LUZ!\p"
    .string "Reduce la fuerza de los AT. ESP.\n"
    .string "del rival.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis_ES::
    .string "¡Genial!\p"
    .string "¡Un REFRESCO!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20_ES::
    .string "¡MT20 contiene VELO SAGRADO!\p"
    .string "Evita los problemas de estado\n"
    .string "a tus POKéMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis_ES::
    .string "¡Genial!\p"
    .string "¡LIMONADA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33_ES::
    .string "¡La MT33 contiene REFLEJO!\p"
    .string "Reduce la fuerza de los ataques\n"
    .string "físicos del rival.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis_ES::
    .string "¡No tienes sitio para esto!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll_ES::
    .string "¡No, gracias!\n"
    .string "¡Ya no tengo tanta sed!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature_ES::
    .string "Mi hermana es ENTRENADORA,\n"
    .string "¡de verdad!\p"
    .string "¡Pero es tan infantil que me vuelve\n"
    .string "loco!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink_ES::
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign_ES::
    .string "ÚLTIMO PISO:\n"
    .string "DISTRIBUIDORES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave_ES::
    .string "¡Un distribuidor!\n"
    .string "¡A ver el menú!$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney_ES::
    .string "¡Vaya, no tengo suficiente dinero!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut_ES::
    .string "¡Una lata de {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff_ES::
    .string "¡No tienes sitio para más cosas!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty_ES::
    .string "¡No tengo sed!$"
