SSAnne_1F_Room2_Text_TylerIntro_FR::
	.string "J'aime les POKéMON! Et toi?$"

SSAnne_1F_Room2_Text_TylerDefeat_FR::
	.string "Woo!\n"
	.string "T'es cool, toi!$"

SSAnne_1F_Room2_Text_TylerPostBattle_FR::
	.string "Soyons amis, OK?\p"
	.string "Comme ça, on pourra\n"
	.string "échanger nos POKéMON!$"

SSAnne_1F_Room2_Text_AnnIntro_FR::
	.string "J'ai déniché ces POKéMON un peu\n"
	.string "partout dans le monde!$"

SSAnne_1F_Room2_Text_AnnDefeat_FR::
	.string "Quoi! Un tour du monde pour ce\n"
	.string "résultat! C'est nul!$"

SSAnne_1F_Room2_Text_AnnPostBattle_FR::
	.string "Tu as fait mal à mes POKéMON!\p"
	.string "Il faut que tu les soignes dans un\n"
	.string "CENTRE POKéMON!!!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld_FR::
	.string "Nous parcourons les mers du\n"
	.string "monde entier!$"

