FuchsiaCity_House2_Text_DoYouLikeToFish_FR::
	.string "Je suis le grand frère du MAITRE\n"
	.string "PECHEUR!\p"
	.string "Moi, mon truc, c'est la pêche!\p"
	.string "T'aimes la pêche?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis_FR::
	.string "T'as l'air de quelqu'un de bien!\p"
	.string "Prends ça! Que la Grand' Pêche\n"
	.string "soit avec toi!$"

FuchsiaCity_House2_Text_ReceivedGoodRod_FR::
	.string "{PLAYER} reçoit la SUPER CANNE!$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons_FR::
	.string "Pêcher, c'est la vie!\n"
	.string "Et la vie, c'est la pêche!\p"
	.string "Avec cette SUPER CANNE, tu vas\n"
	.string "pouvoir attraper des\l"
	.string "SUPER POKéMON.$"

FuchsiaCity_House2_Text_OhThatsDisappointing_FR::
	.string "Oh… Je suis très déçu…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting_FR::
	.string "B'jour à toi, {PLAYER}!\p"
	.string "Ça mord? Hein? Hein?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift_FR::
	.string "Ha ben non!\p"
	.string "J'avais un cadeau pour toi, mais\n"
	.string "t'as plus de place!$"

