IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice_DE::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "In der POKéMON LIGA trittst du\n"
	.string "gegen die TOP VIER nacheinander\l"
	.string "an.\p"
	.string "Wenn du einen Kampf verlierst,\n"
	.string "musst du ganz von vorne beginnen!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck_DE::
	.string "Ab jetzt triffst du nacheinander\n"
	.string "auf die TOP VIER!\p"
	.string "Wenn du einen Kampf gewinnst, wird\n"
	.string "der Weg zum nächsten TRAINER\l"
	.string "freigegeben! Viel Glück!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing_DE::
	.string "Es tut mir Leid, aber du hast deine\n"
	.string "Zeit verschwendet, hier\l"
	.string "herzukommen.\l"
	.string "LORELEI von den TOP VIER ist\l"
	.string "nicht zugegen, weißt du!\p"
	.string "Daher ist die POKéMON LIGA\n"
	.string "vorübergehend geschlossen.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs_DE::
	.string "AGATHEs GEIST-POKéMON\n"
	.string "sind erschreckend hartnäckig.\p"
	.string "Ich habe meine KAMPF-POKéMON\n"
	.string "bis zum Äußersten trainiert.\p"
	.string "Ich bin selbstbewusst zu AGATHE\n"
	.string "gegangen, aber sie hat uns mit\l"
	.string "Leichtigkeit besiegt.\l"
	.string "Die alte Dame ist auch leicht\l"
	.string "zu verärgern.\p"
	.string "Es bedarf nur einer Bagatelle und\n"
	.string "die Angst einflößende Dame\l"
	.string "legt los.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway_DE::
	.string "Vielleicht liegt eine Mitgliedschaft\n"
	.string "bei den TOP VIER in den Genen.\p"
	.string "Ich habe gehört, dass SIEGFRIED\n"
	.string "einen Cousin hat, der irgendwo\l"
	.string "weit weg ARENALEITER ist.$"

