IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice_IT::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "Alla LEGA POKéMON dovrai\n"
    .string "affrontare uno dopo l'altro i\l"
    .string "SUPERQUATTRO.\p"
    .string "Se perdi, dovrai iniziare da capo!\n"
    .string "Fai attenzione!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck_IT::
    .string "Qui ha inizio la sfida contro i\n"
    .string "SUPERQUATTRO, uno dopo l'altro!\p"
    .string "Se vinci si aprirà una porta per\n"
    .string "l'ALLENATORE successivo!\l"
    .string "Buona fortuna!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing_IT::
    .string "Mi dispiace, ma hai fatto tutta\n"
    .string "questa strada per niente.\p"
    .string "LORELEI dei SUPERQUATTRO è\n"
    .string "assente.\p"
    .string "Pertanto, la LEGA POKéMON è\n"
    .string "chiusa fino al suo ritorno.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs_IT::
    .string "I POKéMON di tipo SPETTRO di\n"
    .string "AGATHA sono orribilmente forti!\p"
    .string "Ho potenziato al massimo i miei\n"
    .string "POKéMON di tipo LOTTA, ma sono\l"
    .string "stati tutti battuti!\p"
    .string "Quella vecchietta è potentissima,\n"
    .string "ed è anche una testa calda!\p"
    .string "Niente la spaventa!$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway_IT::
    .string "Ho sentito dire che il cugino di\n"
    .string "LANCE, dei SUPERQUATTRO,\l"
    .string "è CAPOPALESTRA da qualche parte.\p"
    .string "Proprio una famiglia di grandi\n"
    .string "ALLENATORI!$"

