IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice_ES::
    .string "¡Hola, aspirante al título!\p"
    .string "En la LIGA POKéMON tendrás que\n"
    .string "luchar contra todos los miembros\l"
    .string "del ALTO MANDO, uno tras otro.\p"
    .string "¡Si pierdes, tendrás que volver\n"
    .string "a empezar!\p"
    .string "¡Eso es todo!\n"
    .string "¡A por ellos!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck_ES::
    .string "¡Ahora lucharás contra todos los\n"
    .string "del ALTO MANDO, sin excepción!\p"
    .string "¡Si ganas, se abrirá una puerta\n"
    .string "y pasarás al siguiente ENTRENADOR!\l"
    .string "¡Buena suerte!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing_ES::
    .string "Lo siento, pero has perdido\n"
    .string "el tiempo viniendo hasta aquí.\p"
    .string "LORELEI, del ALTO MANDO,\n"
    .string "no está, como puedes comprobar.\p"
    .string "Así que la LIGA POKéMON está\n"
    .string "cerrada de momento.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs_ES::
    .string "Los POKéMON de tipo FANTASMA\n"
    .string "de AGATHA son escalofriantemente\l"
    .string "fuertes.\p"
    .string "Yo me puse a criar a mis POKéMON\n"
    .string "del tipo LUCHA con todas las ganas\l"
    .string "del mundo...\p"
    .string "Y me planté ante AGATHA convencido\n"
    .string "de que podría ganar... y no quiero\l"
    .string "ni contarte la paliza que me dio.\p"
    .string "Además, ¡no sabes el genio que\n"
    .string "tiene la señora!\p"
    .string "¡Como empiece a gritar, lo llevas\n"
    .string "claro!$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway_ES::
    .string "Yo creo que lo de ser del ALTO\n"
    .string "MANDO se lleva en la sangre.\p"
    .string "Por lo que sé, un primo de LANCE\n"
    .string "es también LÍDER de un GIMNASIO\l"
    .string "de por ahí.$"
