IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice_FR::
	.string "Salut,\n"
	.string "CHAMPION en herbe!\p"
	.string "Tu vas devoir affronter le CONSEIL\n"
	.string "4 dans l'ordre pour triompher\l"
	.string "de la LIGUE POKéMON.\p"
	.string "Si tu perds, d'abord tu auras\n"
	.string "honte, et ensuite tu devras tout\l"
	.string "recommencer!\p"
	.string "Alors fais bien attention et…\n"
	.string "Ecrase-les!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck_FR::
	.string "A partir d'ici, tu affronteras les\n"
	.string "quatre membres du…\l"
	.string "CONSEIL 4!\p"
	.string "Remporte la victoire et une porte\n"
	.string "s'ouvrira vers le prochain\l"
	.string "DRESSEUR. Bonne chance!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing_FR::
	.string "Désolée. Tu perds ton temps en\n"
	.string "venant ici.\p"
	.string "OLGA du CONSEIL 4 s'est absentée.\p"
	.string "La LIGUE POKéMON est fermée\n"
	.string "jusqu'à son retour.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs_FR::
	.string "Les POKéMON SPECTRE\n"
	.string "d'AGATHA sont terrifiants.\p"
	.string "J'avais entraîné mes POKéMON\n"
	.string "COMBAT comme un malade.\p"
	.string "J'suis allé affronter AGATHA tout\n"
	.string "sûr de moi, mais elle m'a éclaté.\p"
	.string "En plus, elle se met facilement\n"
	.string "en rogne. J'te raconte pas.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway_FR::
	.string "C'est peut-être héréditaire de\n"
	.string "faire partie du CONSEIL 4.\p"
	.string "Y'a un copain d'un cousin d'une\n"
	.string "amie qui dit que PETER\p"
	.string "a un cousin CHAMPION D'ARENE\n"
	.string "quelque part.$"

