Text_MetronomeTeach_ES::
    .string "¡Tac-tac-tac! Voy a enseñarte\n"
    .string "un movimiento estupendo.\p"
    .string "Enséñaselo a un POKéMON,\n"
    .string "verás qué guay es.\p"
    .string "Se llama METRÓNOMO, no me\n"
    .string "digas que no suena bien...$"

Text_MetronomeDeclined_ES::
    .string "Te lo digo, es el no va más.$"

Text_MetronomeWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe METRÓNOMO?$"

Text_MetronomeTaught_ES::
    .string "¡Tac-tac-tac!\n"
    .string "¡Ése es el sonido de un METRÓNOMO!\p"
    .string "¡Lleva al POKéMON a usar ataques\n"
    .string "que no conoce!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe_ES::
    .string "¡Hola!\p"
    .string "¡Soy un científico muy importante!\n"
    .string "Mucho, sí, sí.\p"
    .string "¡Y me dedico a estudiar fósiles\n"
    .string "de POKéMON raros!\p"
    .string "¿Tienes algún fósil para mí?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad_ES::
    .string "¡No!\n"
    .string "¡Qué pena!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP_ES::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife_ES::
    .string "¿Dónde estabas?\p"
    .string "¡Tu fósil ha revivido!\n"
    .string "¡Sabía que era un {STR_VAR_1}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor_ES::
    .string "¡{PLAYER} recibió {STR_VAR_1}\n"
    .string "de manos del científico!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon_ES::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain_ES::
    .string "¡Oh! ¡Es un {STR_VAR_2}!\p"
    .string "¡Es un fósil de {STR_VAR_1},\n"
    .string "un POKéMON ya extinto!\p"
    .string "¡Mi máquina recuperadora\n"
    .string "hará que este POKéMON reviva!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor_ES::
    .string "¡Date prisa y dame eso!\p"
    .string "{FONT_NORMAL}¡{PLAYER} le dio {STR_VAR_2}\n"
    .string "al extraño científico!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk_ES::
    .string "¡Tardaré un poco!\p"
    .string "¡Date un paseo mientras tanto!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain_ES::
    .string "¡Eh!\n"
    .string "¡Has venido a molestarme!$"
