Text_MetronomeTeach_DE::
	.string "Tak-tak-tak!\n"
	.string "Ich kann einem POKéMON eine\l"
	.string "tolle Attacke beibringen!\p"
	.string "Die Attacke heißt METRONOM!\n"
	.string "Könnte sie dir gefallen?$"

Text_MetronomeDeclined_DE::
	.string "Ich sage dir, es macht viel Spaß!$"

Text_MetronomeWhichMon_DE::
	.string "O.K.! Welches POKéMON\n"
	.string "soll sie erlernen?$"

Text_MetronomeTaught_DE::
	.string "Tak-tak-tak!\n"
	.string "So klingt ein METRONOM!\p"
	.string "Damit setzt dein POKéMON Attacken\n"
	.string "ein, die es gar nicht kennt!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe_DE::
	.string "Hallo!\p"
	.string "Ich leite hier die Forschungen!\p"
	.string "Wir erforschen Fossilien von\n"
	.string "URZEIT-POKéMON!\p"
	.string "Hast du ein Fossil für mich?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad_DE::
	.string "Nein?\n"
	.string "Zu schade!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP_DE::
	.string "ちょっと　じかん　かかるよ！\p"
	.string "そこらへんを　すこし\n"
	.string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife_DE::
	.string "Wo warst du? Wir haben\n"
	.string "dein Fossil wieder belebt!\p"
	.string "Ein {STR_VAR_1}, ganz wie ich es\n"
	.string "vermutet habe!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor_DE::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon_DE::
	.string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain_DE::
	.string "Oh!\n"
	.string "Das ist ein {STR_VAR_2}!\p"
	.string "Es ist ein Fossil von {STR_VAR_1},\n"
	.string "einem schon lange ausgestorbenen\l"
	.string "POKéMON!\p"
	.string "Dank modernster Technik können wir\n"
	.string "POKéMON aus Fossilien\l"
	.string "wieder beleben!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor_DE::
	.string "Gib es schnell her, damit ich\n"
	.string "fortfahren kann!\p"
	.string "{FONT_NORMAL}{PLAYER} übergibt das\n"
	.string "{STR_VAR_2}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk_DE::
	.string "Es wird einige Zeit dauern!\n"
	.string "Komm einfach später wieder vorbei!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain_DE::
	.string "Du bist jederzeit willkommen!$"

