Text_MetronomeTeach_IT::
    .string "Tac-tac-tac!\n"
    .string "Posso insegnarti una mossa\l"
    .string "divertentissima!\p"
    .string "Si chiama METRONOMO!\n"
    .string "Il nome non stuzzica la tua\l"
    .string "fantasia?$"

Text_MetronomeDeclined_IT::
    .string "Ah davvero?\n"
    .string "Ti assicuro che è proprio\l"
    .string "divertente!$"

Text_MetronomeWhichMon_IT::
    .string "OK!\n"
    .string "A quale POKéMON vuoi che la\l"
    .string "insegni?$"

Text_MetronomeTaught_IT::
    .string "Tac-tac-tac!\n"
    .string "È il suono di un METRONOMO!\p"
    .string "Il cervello dei tuoi POKéMON\n"
    .string "userà tecniche che non conosce!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe_IT::
    .string "Salve!\p"
    .string "Sono un dottore molto importante!\p"
    .string "Studio i fossili di POKéMON rari!\p"
    .string "Hai qualche fossile per me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad_IT::
    .string "No! Che sfortuna!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP_IT::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife_IT::
    .string "Che fine avevi fatto?\p"
    .string "Il tuo fossile è tornato in vita!\n"
    .string "È {STR_VAR_1} come pensavo!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor_IT::
    .string "{PLAYER} riceve\n"
    .string "{STR_VAR_1}.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon_IT::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain_IT::
    .string "Oh!\n"
    .string "È un frammento di {STR_VAR_2}!\p"
    .string "È un fossile di {STR_VAR_1},\n"
    .string "un POKéMON già estinto!\p"
    .string "Lo farò tornare in vita con la mia\n"
    .string "Macchina Risuscita-POKéMON!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor_IT::
    .string "Presto dammelo!\p"
    .string "{FONT_NORMAL}{PLAYER} dà\n"
    .string "{STR_VAR_2}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk_IT::
    .string "Ci metterò un po'!\p"
    .string "Fatti un giretto nel frattempo!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain_IT::
    .string "Vabbè… torna quando vuoi!$"

