Route21_North_Text_RonaldIntro_ES::
    .string "¿Quieres saber si los peces pican?$"

Route21_North_Text_RonaldDefeat_ES::
    .string "¡Vale, vale!$"

Route21_North_Text_RonaldPostBattle_ES::
    .string "¡No puedo pescar nada bueno!\n"
    .string "¡No hay ni un POKéMON bueno!$"

Route21_North_Text_WadeIntro_ES::
    .string "¡Tengo una gran red!\n"
    .string "¿Quieres probarla?$"

Route21_North_Text_WadeDefeat_ES::
    .string "¡MAGIKARP, qué bochorno!$"

Route21_North_Text_WadePostBattle_ES::
    .string "¡Se ve que sólo pesco MAGIKARP!$"

Route21_North_Text_SpencerIntro_ES::
    .string "¡El mar limpia mi cuerpo y mi\n"
    .string "alma!$"

Route21_North_Text_SpencerDefeat_ES::
    .string "¡Aaayyy!$"

Route21_North_Text_SpencerPostBattle_ES::
    .string "¡A mí también me gusta la montaña!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro_ES::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat_ES::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle_ES::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
