Route21_North_Text_RonaldIntro_DE::
	.string "Möchtest du wissen, ob die Fische\n"
	.string "beißen?$"

Route21_North_Text_RonaldDefeat_DE::
	.string "Mist!$"

Route21_North_Text_RonaldPostBattle_DE::
	.string "Bisher habe ich noch nichts\n"
	.string "gefangen!$"

Route21_North_Text_WadeIntro_DE::
	.string "Ich habe einen guten Fang\n"
	.string "gemacht! Möchtest du ihn sehen?$"

Route21_North_Text_WadeDefeat_DE::
	.string "NEIN!\n"
	.string "KARPADOR!$"

Route21_North_Text_WadePostBattle_DE::
	.string "Oh nein! Ich habe schon wieder\n"
	.string "ein KARPADOR gefangen!$"

Route21_North_Text_SpencerIntro_DE::
	.string "Die See reinigt Körper und Seele!$"

Route21_North_Text_SpencerDefeat_DE::
	.string "Nein!$"

Route21_North_Text_SpencerPostBattle_DE::
	.string "Aber ich mag die Berge genauso\n"
	.string "gern!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro_DE::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat_DE::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle_DE::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"

