Route21_North_Text_RonaldIntro_IT::
    .string "Vuoi sapere se i pesci abboccano?$"

Route21_North_Text_RonaldDefeat_IT::
    .string "Che botta!$"

Route21_North_Text_RonaldPostBattle_IT::
    .string "Non pesco niente di buono!$"

Route21_North_Text_WadeIntro_IT::
    .string "Ho preso un bel po' di POKéMON!\n"
    .string "Guarda!$"

Route21_North_Text_WadeDefeat_IT::
    .string "Che noia, questi MAGIKARP!$"

Route21_North_Text_WadePostBattle_IT::
    .string "Pesco solo MAGIKARP!$"

Route21_North_Text_SpencerIntro_IT::
    .string "Il mare pulisce il corpo e l'anima!$"

Route21_North_Text_SpencerDefeat_IT::
    .string "Ahiahi!$"

Route21_North_Text_SpencerPostBattle_IT::
    .string "Mi piace anche la montagna!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro_IT::
    .string "おれだって　たまには\n"
    .string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat_IT::
    .string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle_IT::
    .string "うきやすそう　だと？\n"
    .string "うるせー　おおきな　おせわだッ！$"

