Route15_Text_KindraIntro_IT::
    .string "Voglio provare i POKéMON che ho\n"
    .string "appena scambiato!$"

Route15_Text_KindraDefeat_IT::
    .string "Ancora non va!$"

Route15_Text_KindraPostBattle_IT::
    .string "Non puoi cambiare il soprannome dei\n"
    .string "POKéMON che hai scambiato.\p"
    .string "Può farlo solo l'ALLENATORE\n"
    .string "Originario!$"

Route15_Text_BeckyIntro_IT::
    .string "Sembri debole!\n"
    .string "Penso di poterti battere!$"

Route15_Text_BeckyDefeat_IT::
    .string "No, mi sbagliavo!$"

Route15_Text_BeckyPostBattle_IT::
    .string "I CENTAURI mi fanno paura, sono\n"
    .string "brutti e cattivi!$"

Route15_Text_EdwinIntro_IT::
    .string "Quando fischio i POKéMON uccello\n"
    .string "vengono da me!$"

Route15_Text_EdwinDefeat_IT::
    .string "Ooh!\n"
    .string "Che tragedia!$"

Route15_Text_EdwinPostBattle_IT::
    .string "Forse la lotta non fa per me!$"

Route15_Text_ChesterIntro_IT::
    .string "I miei uccellini tremano di paura!\n"
    .string "Sei forte, vero?$"

Route15_Text_ChesterDefeat_IT::
    .string "Sì, proprio come pensavo!$"

Route15_Text_ChesterPostBattle_IT::
    .string "Sapevi che mosse come TERREMOTO\n"
    .string "non hanno effetto sui POKéMON di\l"
    .string "tipo uccello?$"

Route15_Text_GraceIntro_IT::
    .string "Oh!\n"
    .string "Sei un tipo simpatico!$"

Route15_Text_GraceDefeat_IT::
    .string "Sembravi un tipo così simpatico!$"

Route15_Text_GracePostBattle_IT::
    .string "Ti perdono!\n"
    .string "Non me la prendo!$"

Route15_Text_OliviaIntro_IT::
    .string "Allevo POKéMON per non sentirmi\n"
    .string "sola.$"

Route15_Text_OliviaDefeat_IT::
    .string "Non ci voleva proprio!$"

Route15_Text_OliviaPostBattle_IT::
    .string "Voglio andare a casa per stare coi\n"
    .string "miei POKéMON!$"

Route15_Text_ErnestIntro_IT::
    .string "Ehi tu! Coraggio!\n"
    .string "Guarda cos'ho!$"

Route15_Text_ErnestDefeat_IT::
    .string "Spazzato via!$"

Route15_Text_ErnestPostBattle_IT::
    .string "Si vive una volta sola e io vivo\n"
    .string "da fuorilegge!\l"
    .string "È lo spirito di TEAM ROCKET!$"

Route15_Text_AlexIntro_IT::
    .string "O la borsa, o la vita!$"

Route15_Text_AlexDefeat_IT::
    .string "Non può essere!$"

Route15_Text_AlexPostBattle_IT::
    .string "Quella sulla borsa era una\n"
    .string "battuta!$"

Route15_Text_CeliaIntro_IT::
    .string "Cosa c'è di più bello che\n"
    .string "scambiare POKéMON?!$"

Route15_Text_CeliaDefeat_IT::
    .string "Ho detto scambiare, non lottare!$"

Route15_Text_CeliaPostBattle_IT::
    .string "Scambio POKéMON con gli amici!$"

Route15_Text_YazminIntro_IT::
    .string "Vuoi giocare con i miei POKéMON?$"

Route15_Text_YazminDefeat_IT::
    .string "Ho avuto poca pazienza!$"

Route15_Text_YazminPostBattle_IT::
    .string "Dovrò sfidare ALLENATORI più\n"
    .string "deboli!$"

Route15_Text_RouteSign_IT::
    .string "PERCORSO 15\n"
    .string "FUCSIAPOLI a ovest$"

Route15_Text_MyaIntro_IT::
    .string "MYA: Tu sei la persona giusta per\n"
    .string "aiutarmi ad allenare mio fratello.$"

Route15_Text_MyaDefeat_IT::
    .string "MYA: RON, concentrati! Fissa\n"
    .string "l'attenzione su quello che fai!$"

Route15_Text_MyaPostBattle_IT::
    .string "MYA: OK, dovrò intensificare\n"
    .string "l'allenamento.$"

Route15_Text_MyaNotEnoughMons_IT::
    .string "MYA: Vuoi sfidarci? Allora ti\n"
    .string "servono due POKéMON.$"

Route15_Text_RonIntro_IT::
    .string "RON: Quando perdiamo, mia\n"
    .string "sorella s'infuria!$"

Route15_Text_RonDefeat_IT::
    .string "RON: Oh, no! Ora mia sorella\n"
    .string "è fuori di sé!$"

Route15_Text_RonPostBattle_IT::
    .string "RON: A volte mia sorella è\n"
    .string "proprio intrattabile.$"

Route15_Text_RonNotEnoughMons_IT::
    .string "RON: Volevi lottare con me e\n"
    .string "mia sorella?\p"
    .string "Allora ti servono almeno due\n"
    .string "POKéMON in squadra.$"

