Route15_Text_KindraIntro_ES::
    .string "¡Déjame probar los POKéMON\n"
    .string "que acabo de cambiar!$"

Route15_Text_KindraDefeat_ES::
    .string "¡No ha sido suficiente!$"

Route15_Text_KindraPostBattle_ES::
    .string "No puedes variar el mote de ningún\n"
    .string "POKéMON que hayas cambiado.\p"
    .string "¡El ENTRENADOR original es el\n"
    .string "único que puede!$"

Route15_Text_BeckyIntro_ES::
    .string "¡Pareces manejable!\n"
    .string "¡Creo que podría vencerte!\p"
    .string "¡Voy a intentarlo!$"

Route15_Text_BeckyDefeat_ES::
    .string "No, ¡muy mal!$"

Route15_Text_BeckyPostBattle_ES::
    .string "¡Me dan miedo los MOTORISTAS,\n"
    .string "son gamberros, horribles!$"

Route15_Text_EdwinIntro_ES::
    .string "¡Silbando puedo llamar a los\n"
    .string "pájaros POKéMON!$"

Route15_Text_EdwinDefeat_ES::
    .string "¡Ooh!\n"
    .string "¡Qué tragedia!$"

Route15_Text_EdwinPostBattle_ES::
    .string "Puede que no esté hecho para\n"
    .string "luchar contra otros.$"

Route15_Text_ChesterIntro_ES::
    .string "Mis pájaros están temblando.\n"
    .string "Eres muy fuerte, ¿no?$"

Route15_Text_ChesterDefeat_ES::
    .string "¡Lo que pensaba!$"

Route15_Text_ChesterPostBattle_ES::
    .string "No sé si decirte esto, supongo\n"
    .string "que ya lo sabes...\p"
    .string "¿Sabías que los movimientos\n"
    .string "como TERREMOTO o FISURA\l"
    .string "no afectan a los pájaros?$"

Route15_Text_GraceIntro_ES::
    .string "¡Oh!\n"
    .string "¡Mira qué encanto!$"

Route15_Text_GraceDefeat_ES::
    .string "¡Pensaba que eras un encanto!$"

Route15_Text_GracePostBattle_ES::
    .string "¡Te perdono!\n"
    .string "¡Eres adorable!$"

Route15_Text_OliviaIntro_ES::
    .string "¡Cuido POKéMON porque vivo sola\n"
    .string "y hacen que me sienta segura!$"

Route15_Text_OliviaDefeat_ES::
    .string "¡Yo no quería un final así!$"

Route15_Text_OliviaPostBattle_ES::
    .string "¡Me gusta ir a casa para estar\n"
    .string "con mis POKéMON!\p"
    .string "Es una tranquilidad...$"

Route15_Text_ErnestIntro_ES::
    .string "¡Oye! ¡Ven aquí!\n"
    .string "¡Mira esto!$"

Route15_Text_ErnestDefeat_ES::
    .string "¡No sé qué decir!$"

Route15_Text_ErnestPostBattle_ES::
    .string "¡Sólo se vive una vez, y yo vivo\n"
    .string "como un forajido!\l"
    .string "¡NORMAS del TEAM ROCKET!$"

Route15_Text_AlexIntro_ES::
    .string "¡Mira, colega, si pierdes contra\n"
    .string "mí, todo tu dinero será mío!$"

Route15_Text_AlexDefeat_ES::
    .string "¡No puede ser!$"

Route15_Text_AlexPostBattle_ES::
    .string "¡Oye, que lo del dinero era broma!\n"
    .string "¡No me hagas caso!$"

Route15_Text_CeliaIntro_ES::
    .string "¿Qué mola?\n"
    .string "¡Cambiar POKéMON!$"

Route15_Text_CeliaDefeat_ES::
    .string "¡He dicho cambiar!$"

Route15_Text_CeliaPostBattle_ES::
    .string "¡Cambio POKéMON con mis amigos!$"

Route15_Text_YazminIntro_ES::
    .string "¿Quieres jugar con mis POKéMON?$"

Route15_Text_YazminDefeat_ES::
    .string "¡Estaba demasiado impaciente!$"

Route15_Text_YazminPostBattle_ES::
    .string "¡Me entrenaré con gente más débil!$"

Route15_Text_RouteSign_ES::
    .string "RUTA 15:\n"
    .string "CIUDAD FUCSIA, al oeste$"

Route15_Text_MyaIntro_ES::
    .string "TINA: Eres genial. ¿Luchamos para\n"
    .string "que aprenda mi hermano?$"

Route15_Text_MyaDefeat_ES::
    .string "TINA: ¡TIN, concéntrate! ¡Hay que\n"
    .string "concentrarse en lo que se hace!$"

Route15_Text_MyaPostBattle_ES::
    .string "TINA: Tenemos que hacer algo,\n"
    .string "¡debemos entrenarnos más!$"

Route15_Text_MyaNotEnoughMons_ES::
    .string "TINA: ¿Quieres desafiarnos?\n"
    .string "¡Pues necesitas dos POKéMON!$"

Route15_Text_RonIntro_ES::
    .string "TIN: Mi hermana se asusta cuando\n"
    .string "perdemos.$"

Route15_Text_RonDefeat_ES::
    .string "TIN: Vaya, hermanita, lo siento...$"

Route15_Text_RonPostBattle_ES::
    .string "TIN: Mi hermana se pone un poco\n"
    .string "pesada...$"

Route15_Text_RonNotEnoughMons_ES::
    .string "TIN: ¿Te gustaría luchar\n"
    .string "con nosotros?\p"
    .string "¡Pues vente con dos POKéMON!$"
