Route15_Text_KindraIntro_FR::
	.string "Je vais tester les POKéMON que\n"
	.string "j'ai échangés!$"

Route15_Text_KindraDefeat_FR::
	.string "Oh!\n"
	.string "Perdu!$"

Route15_Text_KindraPostBattle_FR::
	.string "Tu ne peux pas renommer un\n"
	.string "POKéMON échangé.\p"
	.string "Seul son premier DRESSEUR\n"
	.string "peut le faire.$"

Route15_Text_BeckyIntro_FR::
	.string "T'as l'air stupide, je devrais\n"
	.string "pouvoir te battre!$"

Route15_Text_BeckyDefeat_FR::
	.string "Pas si stupide en fait!$"

Route15_Text_BeckyPostBattle_FR::
	.string "Les MOTARDS me font peur, ils sont\n"
	.string "si méchants!$"

Route15_Text_EdwinIntro_FR::
	.string "Je peux appeler des POKéMON\n"
	.string "oiseau rien qu'en sifflant!$"

Route15_Text_EdwinDefeat_FR::
	.string "Oh!\n"
	.string "J'le crois pas!$"

Route15_Text_EdwinPostBattle_FR::
	.string "Je ne suis pas doué pour les\n"
	.string "bastons.$"

Route15_Text_ChesterIntro_FR::
	.string "Hmm? Mes oiseaux ont peur!\n"
	.string "T'es fortiche, toi?$"

Route15_Text_ChesterDefeat_FR::
	.string "…\n"
	.string "C'est bien ce que je pensais!$"

Route15_Text_ChesterPostBattle_FR::
	.string "Les attaques comme SEISME ou\n"
	.string "ABIME ne font rien aux oiseaux.\p"
	.string "Tu l'savais?$"

Route15_Text_GraceIntro_FR::
	.string "Oh! T'es bien jeune, toi!$"

Route15_Text_GraceDefeat_FR::
	.string "T'étais adorable, pourtant!$"

Route15_Text_GracePostBattle_FR::
	.string "Je te pardonne!\n"
	.string "T'es trop adorable!$"

Route15_Text_OliviaIntro_FR::
	.string "J'ai des POKéMON pour me protéger\n"
	.string "comme je vis toute seule!$"

Route15_Text_OliviaDefeat_FR::
	.string "Pour moi, les POKéMON ce n'est\n"
	.string "pas juste gagner ou perdre.$"

Route15_Text_OliviaPostBattle_FR::
	.string "Je rentre chez moi pour être avec\n"
	.string "mes POKéMON!$"

Route15_Text_ErnestIntro_FR::
	.string "Hé, toi!\n"
	.string "Regarde ça!$"

Route15_Text_ErnestDefeat_FR::
	.string "Pourquoi pas?$"

Route15_Text_ErnestPostBattle_FR::
	.string "On ne vit qu'une fois! C'est pour\n"
	.string "ça que je suis méchant, nyark!$"

Route15_Text_AlexIntro_FR::
	.string "La bourse ou la vie!$"

Route15_Text_AlexDefeat_FR::
	.string "C'est pas possible!$"

Route15_Text_AlexPostBattle_FR::
	.string "Heu…\n"
	.string "Pour l'argent, je plaisantais!$"

Route15_Text_CeliaIntro_FR::
	.string "Quoi? Echanger des POKéMON\n"
	.string "c'est cool?$"

Route15_Text_CeliaDefeat_FR::
	.string "Hé! Je parlais d'échanges, pas de\n"
	.string "bastons!$"

Route15_Text_CeliaPostBattle_FR::
	.string "J'échange des POKéMON avec\n"
	.string "mes amis!$"

Route15_Text_YazminIntro_FR::
	.string "Je veux me battre avec mes\n"
	.string "POKéMON!$"

Route15_Text_YazminDefeat_FR::
	.string "…\n"
	.string "J'étais trop impatiente!$"

Route15_Text_YazminPostBattle_FR::
	.string "Je vais me battre avec des\n"
	.string "DRESSEURS moins forts!$"

Route15_Text_RouteSign_FR::
	.string "ROUTE 15\n"
	.string "PARMANIE à l'Ouest$"

Route15_Text_MyaIntro_FR::
	.string "MYA: On dirait que tu sais\n"
	.string "te battre.\p"
	.string "Tu aurais un instant pour qu'on\n"
	.string "entraîne mon petit frère?$"

Route15_Text_MyaDefeat_FR::
	.string "MYA: RON, tu dois te concentrer!\n"
	.string "Pense à ce que tu fais!$"

Route15_Text_MyaPostBattle_FR::
	.string "MYA: OK, il va falloir revoir mon\n"
	.string "programme d'entraînement.$"

Route15_Text_MyaNotEnoughMons_FR::
	.string "MYA: Tu veux vraiment nous\n"
	.string "affronter?\p"
	.string "Et tu ne sais pas qu'il te faut\n"
	.string "deux POKéMON pour ça?$"

Route15_Text_RonIntro_FR::
	.string "RON: Ma sœur me fait peur quand\n"
	.string "on perd.$"

Route15_Text_RonDefeat_FR::
	.string "RON: Oh non…\n"
	.string "Désolé grande sœur.$"

Route15_Text_RonPostBattle_FR::
	.string "RON: … Elle me\n"
	.string "traite comme un gamin.$"

Route15_Text_RonNotEnoughMons_FR::
	.string "RON: Tu veux te battre contre nous\n"
	.string "deux? Avec un seul POKéMON?$"

