Route15_Text_KindraIntro_DE::
	.string "Wunderbar! Dann kann ich gleich\n"
	.string "ausprobieren, wie gut die POKéMON\l"
	.string "sind, die ich getauscht habe!$"

Route15_Text_KindraDefeat_DE::
	.string "Nicht gut genug!$"

Route15_Text_KindraPostBattle_DE::
	.string "Man kann den Spitznamen eines\n"
	.string "POKéMON, das man getauscht hat,\l"
	.string "nicht ändern.\p"
	.string "Nur der Original-TRAINER kann den\n"
	.string "Namen verändern.$"

Route15_Text_BeckyIntro_DE::
	.string "Du siehst lammfromm aus!\n"
	.string "Dann habe ich eine Chance!$"

Route15_Text_BeckyDefeat_DE::
	.string "Du bist ein Wolf im Schafspelz!$"

Route15_Text_BeckyPostBattle_DE::
	.string "Ich habe Angst vor BIKERn, sie\n"
	.string "sind so hässlich und brutal!$"

Route15_Text_EdwinIntro_DE::
	.string "Wenn ich pfeife, kann ich Vogel-\n"
	.string "POKéMON herbeirufen!$"

Route15_Text_EdwinDefeat_DE::
	.string "Au!\n"
	.string "Das ist tragisch!$"

Route15_Text_EdwinPostBattle_DE::
	.string "Vielleicht bin ich keine\n"
	.string "Kämpfernatur...$"

Route15_Text_ChesterIntro_DE::
	.string "Hmm? Meine Vögel erschaudern?\n"
	.string "Du musst wirklich sehr gut sein!$"

Route15_Text_ChesterDefeat_DE::
	.string "Ich lag also richtig!$"

Route15_Text_ChesterPostBattle_DE::
	.string "Wusstest du, dass manche Attacken,\n"
	.string "wie ERDBEBEN, keine Wirkung auf\l"
	.string "Vögel haben?$"

Route15_Text_GraceIntro_DE::
	.string "Du bist ein schlaues Kind!$"

Route15_Text_GraceDefeat_DE::
	.string "Und du siehst so süß aus!$"

Route15_Text_GracePostBattle_DE::
	.string "O.K., du hast mich besiegt.\n"
	.string "Es macht mir nichts aus!$"

Route15_Text_OliviaIntro_DE::
	.string "Ich trainiere POKéMON, weil ich\n"
	.string "alleine lebe!$"

Route15_Text_OliviaDefeat_DE::
	.string "So habe ich es mir aber nicht\n"
	.string "vorgestellt!$"

Route15_Text_OliviaPostBattle_DE::
	.string "Ich verbringe zu Hause sehr viel\n"
	.string "Zeit mit meinen POKéMON!$"

Route15_Text_ErnestIntro_DE::
	.string "Heh, Kiddie!\n"
	.string "Lass uns kämpfen!$"

Route15_Text_ErnestDefeat_DE::
	.string "Voll\n"
	.string "erwischt!$"

Route15_Text_ErnestPostBattle_DE::
	.string "Man lebt nur einmal!\n"
	.string "Daher bin ich ein Bandit!\l"
	.string "Das TEAM ROCKET ist cool!$"

Route15_Text_AlexIntro_DE::
	.string "Her mit deinen Moneten! Wenn du\n"
	.string "verlierst, gibst du mir dein Geld!$"

Route15_Text_AlexDefeat_DE::
	.string "Das darf nicht wahr sein!$"

Route15_Text_AlexPostBattle_DE::
	.string "Vergiss die Sache mit dem Geld,\n"
	.string "das war ein Scherz!$"

Route15_Text_CeliaIntro_DE::
	.string "POKéMON zu tauschen, ist wirklich\n"
	.string "cool!$"

Route15_Text_CeliaDefeat_DE::
	.string "Ich sagte tauschen!$"

Route15_Text_CeliaPostBattle_DE::
	.string "Ich tausche mit meinen Freunden\n"
	.string "POKéMON!$"

Route15_Text_YazminIntro_DE::
	.string "Möchtest du mit meinen POKéMON\n"
	.string "spielen?$"

Route15_Text_YazminDefeat_DE::
	.string "Ich war zu ungestüm!$"

Route15_Text_YazminPostBattle_DE::
	.string "Ich muss ein wenig mit schwächeren\n"
	.string "TRAINERn üben...$"

Route15_Text_RouteSign_DE::
	.string "ROUTE 15\n"
	.string "WESTEN: FUCHSANIA CITY$"

Route15_Text_MyaIntro_DE::
	.string "EVA: Du bist perfekt!\n"
	.string "Hilfst du mir, meinen kleinen\l"
	.string "Bruder zu trainieren?$"

Route15_Text_MyaDefeat_DE::
	.string "EVA: Konzentriere dich, SERGIO!\n"
	.string "Achte auf deine Taten!$"

Route15_Text_MyaPostBattle_DE::
	.string "EVA: O.K.! Wir haben es vergeigt!\n"
	.string "Ich füge unserem Trainingsprogramm\l"
	.string "einige Lektionen hinzu.$"

Route15_Text_MyaNotEnoughMons_DE::
	.string "EVA: Möchtest du uns\n"
	.string "herausfordern? Du brauchst\l"
	.string "allerdings zwei POKéMON!$"

Route15_Text_RonIntro_DE::
	.string "SERGIO: Meine Schwester bekommt\n"
	.string "Angst, wenn wir verlieren.$"

Route15_Text_RonDefeat_DE::
	.string "SERGIO: Oh, nein…\n"
	.string "Es tut mir Leid, Schwesterherz!$"

Route15_Text_RonPostBattle_DE::
	.string "SERGIO: Oh, Mist…\n"
	.string "Ich wünschte, ich hätte eine\l"
	.string "nette Schwester…$"

Route15_Text_RonNotEnoughMons_DE::
	.string "SERGIO: Wolltest du gegen meine\n"
	.string "Schwester und mich antreten?\p"
	.string "Dann brauchst du zwei POKéMON!$"

