CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor_IT::
    .string "Salve!\p"
    .string "Alla porta accanto puoi cambiare i\n"
    .string "tuoi GETTONI in premi favolosi.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins_IT::
    .string "Prego, questo è il CASINÒ ROCKET!\p"
    .string "Hai bisogno di GETTONI?$"

CeladonCity_GameCorner_Text_ComePlaySometime_IT::
    .string "No?\n"
    .string "Vieni qualche volta a giocare!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase_IT::
    .string "Non hai un SALVADANAIO!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull_IT::
    .string "Oh!\n"
    .string "Il SALVADANAIO è pieno!$"

CeladonCity_GameCorner_Text_CantAffordCoins_IT::
    .string "Non hai abbastanza soldi per\n"
    .string "ottenere lo scambio dei GETTONI!$"

CeladonCity_GameCorner_Text_HereAreYourCoins_IT::
    .string "Grazie!\n"
    .string "Eccoti i tuoi GETTONI!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace_IT::
    .string "Non dirlo in giro!\p"
    .string "Ma si dice che qui comandi TEAM\n"
    .string "ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds_IT::
    .string "Queste macchine sono impostate\n"
    .string "diversamente!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay_IT::
    .string "Ehi! Ti piacerebbe giocare?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan_IT::
    .string "{PLAYER} riceve\n"
    .string "10 GETTONI!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins_IT::
    .string "Non hai bisogno dei miei GETTONI!$"

CeladonCity_GameCorner_Text_WinsComeAndGo_IT::
    .string "La fortuna va e viene.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck_IT::
    .string "Mi sto divertendo un mondo!$"

CeladonCity_GameCorner_Text_GymGuyAdvice_IT::
    .string "Ehi!\p"
    .string "Non hai di meglio da fare,\n"
    .string "aspirante CAMPIONE?\p"
    .string "ERIKA è il CAPOPALESTRA di\n"
    .string "AZZURROPOLI! Usa POKéMON di\l"
    .string "tipo ERBA!\p"
    .string "Può sembrare molto tranquilla, ma\n"
    .string "non sottovalutarla!$"

CeladonCity_GameCorner_Text_RareMonsForCoins_IT::
    .string "Puoi scambiare i tuoi GETTONI per\n"
    .string "dei POKéMON rari!\p"
    .string "Ma proprio non riesco a vincere!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked_IT::
    .string "I giochi sono pericolosi, è facile\n"
    .string "cascarci!$"

CeladonCity_GameCorner_Text_WantSomeCoins_IT::
    .string "Che c'è, vuoi dei GETTONI?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy_IT::
    .string "{PLAYER} riceve\n"
    .string "20 GETTONI!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins_IT::
    .string "Hai un sacco di GETTONI!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant_IT::
    .string "Uffa! Mi servono più GETTONI per\n"
    .string "i POKéMON che voglio!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo_IT::
    .string "Cosa? Mi buttate fuori! Ecco qui\n"
    .string "dei GETTONI!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan_IT::
    .string "{PLAYER} riceve\n"
    .string "20 GETTONI!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins_IT::
    .string "Ehi, vedo che ne hai già\n"
    .string "a sufficienza!$"

CeladonCity_GameCorner_Text_WatchReelsClosely_IT::
    .string "Il trucco è osservare bene le\n"
    .string "figure!$"

CeladonCity_GameCorner_Text_GruntIntro_IT::
    .string "Faccio la guardia a questo poster,\n"
    .string "smamma di qua!$"

CeladonCity_GameCorner_Text_GruntDefeat_IT::
    .string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle_IT::
    .string "Il RIFUGIO di TEAM ROCKET\n"
    .string "potrebbe essere scoperto!\p"
    .string "Meglio dirlo al CAPO!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt_IT::
    .string "Ehi!\p"
    .string "Un pulsante dietro al poster!\n"
    .string "Premiamolo!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired_IT::
    .string "È necessario un SALVADANAIO!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase_IT::
    .string "Ups!\n"
    .string "Non vedo il SALVADANAIO!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay_IT::
    .string "Una slot machine!\n"
    .string "Vuoi giocare?$"

CeladonCity_GameCorner_Text_OutOfOrder_IT::
    .string "NON FUNZIONA\n"
    .string "È guasta.$"

CeladonCity_GameCorner_Text_OutToLunch_IT::
    .string "TORNO SUBITO\n"
    .string "Dev'essere occupata.$"

CeladonCity_GameCorner_Text_SomeonesKeys_IT::
    .string "Una borsa!\n"
    .string "Dev'essere occupata.$"

