CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor_DE::
	.string "Willkommen!\p"
	.string "Nebenan kannst du deine\n"
	.string "MÜNZEN gegen Preise tauschen.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins_DE::
	.string "Willkommen in der ROCKET\n"
	.string "SPIELHALLE!\p"
	.string "Benötigst du Spiel-MÜNZEN?$"

CeladonCity_GameCorner_Text_ComePlaySometime_DE::
	.string "Nein? Dann komm vorbei, wenn du\n"
	.string "spielen möchtest!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase_DE::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull_DE::
	.string "Dein MÜNZKORB ist voll!$"

CeladonCity_GameCorner_Text_CantAffordCoins_DE::
	.string "Du hast nicht genug Geld!$"

CeladonCity_GameCorner_Text_HereAreYourCoins_DE::
	.string "Danke!\n"
	.string "Hier sind deine MÜNZEN!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace_DE::
	.string "Pst! Höre mir zu!\p"
	.string "Man sagt, diese SPIELHALLE gehöre\n"
	.string "dem TEAM ROCKET!$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds_DE::
	.string "Ich glaube, jeder Spielautomat hat\n"
	.string "eine andere Gewinnchance!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay_DE::
	.string "Möchtest du auch spielen?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan_DE::
	.string "{PLAYER} erhält\n"
	.string "10 MÜNZEN!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins_DE::
	.string "Du brauchst meine MÜNZEN nicht!$"

CeladonCity_GameCorner_Text_WinsComeAndGo_DE::
	.string "Man gewinnt, man verliert!$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck_DE::
	.string "Herrlich!\n"
	.string "Das macht Spaß!$"

CeladonCity_GameCorner_Text_GymGuyAdvice_DE::
	.string "Heh!\p"
	.string "Du hast Wichtigeres zu tun,\n"
	.string "Champion in spe!\p"
	.string "Die ARENALEITERIN von PRISMANIA\n"
	.string "CITY heißt ERIKA.\p"
	.string "Sie trainiert PFLANZEN-POKéMON!\p"
	.string "Sie wirkt sanft, doch man sollte\n"
	.string "sie nicht unterschätzen!$"

CeladonCity_GameCorner_Text_RareMonsForCoins_DE::
	.string "Man kann die MÜNZEN gegen seltene\n"
	.string "POKéMON eintauschen.\p"
	.string "Aber ich habe kein Glück im Spiel!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked_DE::
	.string "Glücksspiele sind unheimlich!\n"
	.string "Man wird schnell davon abhängig!$"

CeladonCity_GameCorner_Text_WantSomeCoins_DE::
	.string "Wie geht es dir?\n"
	.string "Brauchst du ein paar MÜNZEN?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy_DE::
	.string "{PLAYER} erhält\n"
	.string "20 MÜNZEN!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins_DE::
	.string "Heh, du besitzt genug MÜNZEN!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant_DE::
	.string "Mist! Ich habe noch immer nicht\n"
	.string "genug MÜNZEN für das POKéMON!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo_DE::
	.string "Heh! Willst du mich ablenken?\n"
	.string "Hier, nimm ein paar MÜNZEN!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan_DE::
	.string "{PLAYER} erhält\n"
	.string "20 MÜNZEN!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins_DE::
	.string "Du hast deine eigenen MÜNZEN!$"

CeladonCity_GameCorner_Text_WatchReelsClosely_DE::
	.string "Du musst die Walzen genau im Auge\n"
	.string "behalten!$"

CeladonCity_GameCorner_Text_GruntIntro_DE::
	.string "Verschwinde von dem Poster, oder\n"
	.string "ich muss...$"

CeladonCity_GameCorner_Text_GruntDefeat_DE::
	.string "Mist!$"

CeladonCity_GameCorner_Text_GruntPostBattle_DE::
	.string "Ich muss dem BOSS sagen, dass\n"
	.string "unser Versteck entdeckt werden\l"
	.string "könnte!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt_DE::
	.string "Seltsam!\p"
	.string "Hinter dem Poster ist ein Schalter!\n"
	.string "Tja…$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired_DE::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase_DE::
	.string "Ups!\n"
	.string "Ich habe den MÜNZKORB vergessen!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay_DE::
	.string "Ein einarmiger Bandit!\n"
	.string "Möchtest du spielen?$"

CeladonCity_GameCorner_Text_OutOfOrder_DE::
	.string "AUSSER BETRIEB!$"

CeladonCity_GameCorner_Text_OutToLunch_DE::
	.string "BIN ZU TISCH!\n"
	.string "Oh, dieser Platz ist besetzt.$"

CeladonCity_GameCorner_Text_SomeonesKeys_DE::
	.string "Da liegt ein Schlüsselbund.\n"
	.string "Der Platz scheint besetzt zu sein.$"

