CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor_ES::
    .string "¡Hola!\p"
    .string "En la puerta de al lado puedes\n"
    .string "cambiar tus FICHAS por grandes\l"
    .string "premios.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins_ES::
    .string "¡Éste es el CASINO ROCKET!\p"
    .string "¿Necesitas FICHAS?\n"
    .string "¿Quieres comprar más?$"

CeladonCity_GameCorner_Text_ComePlaySometime_ES::
    .string "¿No?\n"
    .string "¡Ven a jugar cuando quieras!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase_ES::
    .string "¡No tienes MONEDERO!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull_ES::
    .string "¡Vaya!\n"
    .string "Tu MONEDERO está lleno.$"

CeladonCity_GameCorner_Text_CantAffordCoins_ES::
    .string "¡No tienes dinero para las FICHAS!$"

CeladonCity_GameCorner_Text_HereAreYourCoins_ES::
    .string "¡Gracias!\n"
    .string "¡Toma las FICHAS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace_ES::
    .string "Escucha y calla.\p"
    .string "Dicen que este lugar lo dirige\n"
    .string "el TEAM ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds_ES::
    .string "¡Creo que estas máquinas están\n"
    .string "trucadas!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay_ES::
    .string "¡Oye!\n"
    .string "¿Quieres jugar?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan_ES::
    .string "¡{PLAYER} obtuvo 10 FICHAS\n"
    .string "de manos del hombre!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins_ES::
    .string "¡No necesitas mis FICHAS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo_ES::
    .string "La suerte viene y se va.\n"
    .string "Hay pocas cosas seguras.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck_ES::
    .string "¡Me lo estoy pasando genial!\n"
    .string "Aunque pierda, las tragaperras\l"
    .string "son estupendas.$"

CeladonCity_GameCorner_Text_GymGuyAdvice_ES::
    .string "¡Oye!\p"
    .string "¡Aún te queda mucho por hacer,\n"
    .string "aspirante al título!\p"
    .string "¡ERIKA es la LÍDER del GIMNASIO\n"
    .string "de AZULONA!\p"
    .string "¡Y usa POKéMON del tipo PLANTA!\p"
    .string "Puede parecer muy dócil, ¡pero ten\n"
    .string "mucho cuidado!\p"
    .string "¡No te confíes!$"

CeladonCity_GameCorner_Text_RareMonsForCoins_ES::
    .string "¡Te ofrecen raros POKéMON que\n"
    .string "pueden ser cambiados por tus\l"
    .string "FICHAS!\p"
    .string "¡Y yo aquí, sin ganar!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked_ES::
    .string "¡Los juegos dan miedo!\n"
    .string "¡Es tan fácil enviciarse!$"

CeladonCity_GameCorner_Text_WantSomeCoins_ES::
    .string "¿Qué?\n"
    .string "¿Quieres algunas FICHAS?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy_ES::
    .string "¡{PLAYER} obtuvo 20 FICHAS\n"
    .string "de manos del chico encantador!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins_ES::
    .string "¡Tienes muchas FICHAS!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant_ES::
    .string "¡Vaya! ¡Necesito más FICHAS\n"
    .string "para los POKéMON que quiero!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo_ES::
    .string "¿Qué? ¿Me estás echando?\n"
    .string "¡Aquí tienes algunas FICHAS!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan_ES::
    .string "¡{PLAYER} obtuvo 20 FICHAS\n"
    .string "de manos del hombre!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins_ES::
    .string "¡Ya tienes tus propias FICHAS!$"

CeladonCity_GameCorner_Text_WatchReelsClosely_ES::
    .string "¡El truco está en mirar atentamente\n"
    .string "las pantallas!$"

CeladonCity_GameCorner_Text_GruntIntro_ES::
    .string "¡Yo protejo este cartel!\n"
    .string "¡Lárgate de aquí!$"

CeladonCity_GameCorner_Text_GruntDefeat_ES::
    .string "¡Auuu!$"

CeladonCity_GameCorner_Text_GruntPostBattle_ES::
    .string "¡Nuestra GUARIDA podría ser\n"
    .string "descubierta!\p"
    .string "¡Voy a decírselo al JEFE!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt_ES::
    .string "¡Oye!\p"
    .string "¿¡Hay un botón detrás del cartel!?\n"
    .string "¡Vamos a pulsarlo!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired_ES::
    .string "¡Se requiere un MONEDERO!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase_ES::
    .string "¡Vaya!\n"
    .string "¡Olvidé el MONEDERO!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay_ES::
    .string "¡Una máquina tragaperras!\n"
    .string "¿Quieres jugar?$"

CeladonCity_GameCorner_Text_OutOfOrder_ES::
    .string "NO FUNCIONA\n"
    .string "Está rota.$"

CeladonCity_GameCorner_Text_OutToLunch_ES::
    .string "ESTAMOS COMIENDO\n"
    .string "Máquina reservada.$"

CeladonCity_GameCorner_Text_SomeonesKeys_ES::
    .string "¡Unas llaves!\n"
    .string "Ya vendrán a por ellas.$"
