SixIsland_WaterPath_Text_RoseIntro_DE::
	.string "Ich wurde von einer angenehmen\n"
	.string "Brise hierher gebracht.$"

SixIsland_WaterPath_Text_RoseDefeat_DE::
	.string "Kicher… du bist süß, wenn\n"
	.string "du so entschlossen bist.$"

SixIsland_WaterPath_Text_RosePostBattle_DE::
	.string "Ich möchte dort drüben in den\n"
	.string "Wald, aber…\p"
	.string "Es gibt dort eine Menge KÄFER-\n"
	.string "POKéMON. Das macht mir ein\l"
	.string "wenig Angst.$"

SixIsland_WaterPath_Text_EdwardIntro_DE::
	.string "Ich trainiere heimlich, damit mich\n"
	.string "niemand sieht.$"

SixIsland_WaterPath_Text_EdwardDefeat_DE::
	.string "Niemand hat gesehen, wie ich\n"
	.string "verloren habe, oder?$"

SixIsland_WaterPath_Text_EdwardPostBattle_DE::
	.string "Da ich ein Artist bin, möchte ich\n"
	.string "nicht, dass die Leute sehen, wie\l"
	.string "sehr ich mich anstrenge.$"

SixIsland_WaterPath_Text_SamirIntro_DE::
	.string "Wie, du behauptest, du hättest\n"
	.string "genug von SCHWIMMERn wie\l"
	.string "mir?\l"
	.string "Argh, sei nicht so abweisend!$"

SixIsland_WaterPath_Text_SamirDefeat_DE::
	.string "Oh, nein!$"

SixIsland_WaterPath_Text_SamirPostBattle_DE::
	.string "Ich konnte nicht widerlegen,\n"
	.string "dass ich ein SCHWIMMER\l"
	.string "bin…$"

SixIsland_WaterPath_Text_DeniseIntro_DE::
	.string "Mein Freund ist stets sehr\n"
	.string "beschäftigt, daher schwimme ich\l"
	.string "alleine.$"

SixIsland_WaterPath_Text_DeniseDefeat_DE::
	.string "Ich wusste, das würde passieren!$"

SixIsland_WaterPath_Text_DenisePostBattle_DE::
	.string "Wenn ich nicht bei meinem Freund\n"
	.string "sein kann, bin ich mit den POKéMON\l"
	.string "zusammen, die er mir gegeben hat.$"

SixIsland_WaterPath_Text_EarlIntro_DE::
	.string "Sag mir, wo hier in der Gegend\n"
	.string "die Berge sind.$"

SixIsland_WaterPath_Text_EarlDefeat_DE::
	.string "Ich habe mich verlaufen, als ich\n"
	.string "gekämpft habe.$"

SixIsland_WaterPath_Text_EarlPostBattle_DE::
	.string "Gibt es in dieser Gegend keine\n"
	.string "Berge?$"

SixIsland_WaterPath_Text_MiuIntro_DE::
	.string "LEA: Hallo, POKéMON!\n"
	.string "Zeit zum Spielen!$"

SixIsland_WaterPath_Text_MiuDefeat_DE::
	.string "LEA: Oh, nein!\n"
	.string "Mamsi!$"

SixIsland_WaterPath_Text_MiuPostBattle_DE::
	.string "LEA: Eine Niederlage erfüllt mich\n"
	.string "mit Trauer…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons_DE::
	.string "LEA: MIA und ich sind ZWILLINGE.\n"
	.string "Wir wollen gemeinsam kämpfen.$"

SixIsland_WaterPath_Text_MiaIntro_DE::
	.string "MIA: Hallo, POKéMON!\n"
	.string "Zeit zum Kämpfen!$"

SixIsland_WaterPath_Text_MiaDefeat_DE::
	.string "MIA: Du bist fies!\n"
	.string "Ein schlechter Gewinner!$"

SixIsland_WaterPath_Text_MiaPostBattle_DE::
	.string "MIA: Oh…\n"
	.string "Es tut mir Leid, meine POKéMON…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons_DE::
	.string "MIA: Oh, du hast nur ein POKéMON?\p"
	.string "Bist du nicht einsam?$"

SixIsland_WaterPath_Text_WantedUltimateHorn_DE::
	.string "Gesucht!\n"
	.string "Das Ultimative Horn!$"

SixIsland_WaterPath_Text_RouteSign_DE::
	.string "WASSERWEG\n"
	.string "Führt ins RUINENTAL$"

