SixIsland_WaterPath_Text_RoseIntro_FR::
	.string "J'ai laissé une légère brise me\n"
	.string "conduire jusqu'ici.$"

SixIsland_WaterPath_Text_RoseDefeat_FR::
	.string "Haha, c'est si mignon de voir\n"
	.string "quelqu'un d'aussi déterminé.$"

SixIsland_WaterPath_Text_RosePostBattle_FR::
	.string "Je voudrais traverser les bois\n"
	.string "qui sont plus loin, mais…\p"
	.string "C'est plein de POKéMON INSECTE\n"
	.string "qui me fichent la trouille.$"

SixIsland_WaterPath_Text_EdwardIntro_FR::
	.string "Je m'entraîne en secret pour que\n"
	.string "personne ne puisse me voir.$"

SixIsland_WaterPath_Text_EdwardDefeat_FR::
	.string "Personne ne m'a vu perdre, hein?$"

SixIsland_WaterPath_Text_EdwardPostBattle_FR::
	.string "Comme je suis un artiste…\p"
	.string "je ne veux pas que les gens voient\n"
	.string "les efforts que je fais.$"

SixIsland_WaterPath_Text_SamirIntro_FR::
	.string "Quoi, tu insinues en avoir marre\n"
	.string "de croiser des nageurs comme moi?\p"
	.string "Allez, ne sois pas si désagréable.$"

SixIsland_WaterPath_Text_SamirDefeat_FR::
	.string "Oh, non, non, non.$"

SixIsland_WaterPath_Text_SamirPostBattle_FR::
	.string "A part nager, qu'est-ce que\n"
	.string "je pourrais faire d'autre?$"

SixIsland_WaterPath_Text_DeniseIntro_FR::
	.string "Mon copain est toujours occupé,\n"
	.string "alors je viens nager seule.$"

SixIsland_WaterPath_Text_DeniseDefeat_FR::
	.string "Ouille, je savais que ça devait\n"
	.string "arriver!$"

SixIsland_WaterPath_Text_DenisePostBattle_FR::
	.string "Quand je ne suis pas avec mon\n"
	.string "copain, je m'occupe des POKéMON\p"
	.string "qu'il m'a donnés.$"

SixIsland_WaterPath_Text_EarlIntro_FR::
	.string "Dis-moi, c'est quoi le plus court\n"
	.string "chemin pour aller à la montagne?$"

SixIsland_WaterPath_Text_EarlDefeat_FR::
	.string "J'ai perdu mon chemin pendant que\n"
	.string "j'étais occupé à combattre.$"

SixIsland_WaterPath_Text_EarlPostBattle_FR::
	.string "C'est bien des montagnes par là?$"

SixIsland_WaterPath_Text_MiuIntro_FR::
	.string "MIU: Salut, on joue ensemble?$"

SixIsland_WaterPath_Text_MiuDefeat_FR::
	.string "MIU: Mamannnn!$"

SixIsland_WaterPath_Text_MiuPostBattle_FR::
	.string "MIU: Bah moi, perdre, ça me rend\n"
	.string "toute triste.$"

SixIsland_WaterPath_Text_MiuNotEnoughMons_FR::
	.string "MIU: MIA et moi, on est jumelles.\n"
	.string "On veut se battre ensemble.$"

SixIsland_WaterPath_Text_MiaIntro_FR::
	.string "MIA: Salut, on joue ensemble?$"

SixIsland_WaterPath_Text_MiaDefeat_FR::
	.string "MIA: C'est vraiment pas gentil!$"

SixIsland_WaterPath_Text_MiaPostBattle_FR::
	.string "MIA: Ohh…\n"
	.string "Mes pauvres POKéMON…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons_FR::
	.string "MIA: Tu n'as qu'un POKéMON?\n"
	.string "T'en veux pas d'autres?$"

SixIsland_WaterPath_Text_WantedUltimateHorn_FR::
	.string "Attention!\n"
	.string "Dernier avertissement!$"

SixIsland_WaterPath_Text_RouteSign_FR::
	.string "AGUALCANAL\n"
	.string "Conduit à la VALLEE RUINE$"

