CinnabarIsland_Text_DoorIsLocked_DE::
	.string "Die Tür ist verschlossen...$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab_DE::
	.string "PYRO, der ARENALEITER der\n"
	.string "ZINNOBERINSEL, ist ein seltsamer\l"
	.string "Mann. Er lebt hier seit Jahren.$"

CinnabarIsland_Text_ScientistsExperimentInMansion_DE::
	.string "Forscher experimentieren in dem\n"
	.string "ausgebrannten Gebäude.$"

CinnabarIsland_Text_IslandSign_DE::
	.string "ZINNOBERINSEL\n"
	.string "Die Stadt brennender Leidenschaft!$"

CinnabarIsland_Text_PokemonLab_DE::
	.string "POKéMON-LABOR$"

CinnabarIsland_Text_GymSign_DE::
	.string "ZINNOBERINSEL POKéMON-ARENA\n"
	.string "ARENALEITER: PYRO\l"
	.string "Der Hitzköpfige Quizmaster!$"

CinnabarIsland_Text_HeyIfItIsntPlayer_DE::
	.string "Häh?\n"
	.string "Wenn das nicht {PLAYER} ist!$"

CinnabarIsland_Text_ComeWithMeToOneIsland_DE::
	.string "Ich bin es, BILL.\n"
	.string "Lange nicht gesehen!\p"
	.string "Ich hoffe, du benutzt noch mein\n"
	.string "PC-System.\p"
	.string "Nun, hör zu, da wir uns hier\n"
	.string "treffen, wie wäre es, wenn du\l"
	.string "mit mir kommst?\l"
	.string "Es gibt eine kleine Insel tief im\l"
	.string "Süden, die EILAND EINS genannt\l"
	.string "wird.\l"
	.string "Ein Freund hat mich eingeladen und\l"
	.string "ich bin auf dem Weg dorthin.\p"
	.string "Wie wär es?\n"
	.string "Hast du Lust mitzukommen?$"

CinnabarIsland_Text_AllRightLetsGo_DE::
	.string "Einverstanden!\n"
	.string "Und los!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter_DE::
	.string "Wie, du bist zu beschäftigt?\p"
	.string "Nun gut.\n"
	.string "Das Schiff hat noch nicht angelegt.\p"
	.string "Ich warte am POKéMON-CENTER\n"
	.string "dort drüben auf dich.\p"
	.string "Hol mich ab, wenn du deine\n"
	.string "Geschäfte erledigt hast.$"

CinnabarIsland_Text_MyPalsBoatArrived_DE::
	.string "Scheint, dass das Schiff von\n"
	.string "meinem Freund auch angekommen\l"
	.string "ist.\l"
	.string "Er hat es extra zur ZINNOBERINSEL\l"
	.string "geschickt, um mich abzuholen.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain_DE::
	.string "Das war eine lange Fahrt, oder?\p"
	.string "Mein Kamerad CELIO scheint deine\n"
	.string "Gegenwart genossen zu haben.\p"
	.string "Ich bin sicher, er würde dich gerne\n"
	.string "erneut willkommen heißen.\p"
	.string "Wenn du den TRI-PASS hast, kannst\n"
	.string "du jederzeit mit der Fähre von\l"
	.string "ORANIA CITY zu ihm fahren.\p"
	.string "Danke für die Begleitung!$"

