OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore_DE::
	.string "Hm!\n"
	.string "Hah!\l"
	.string "Argh! Das ist himmlisch!\l"
	.string "Das Wasser wärmt mich überall!\p"
	.string "Spring auch rein!\p"
	.string "Schwimm in die Mitte, entspanne\n"
	.string "und dir wird ganz wohlig warm.$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder_DE::
	.string "Mein Lieblingsteil vom Baden\n"
	.string "kommt jetzt gleich.\p"
	.string "Ich genehmige mir eine sämige\n"
	.string "Fischsuppe, um mich auch von\l"
	.string "innen aufzuwärmen!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed_DE::
	.string "Das Wasser ist schön warm!\n"
	.string "Genau richtig! Klasse…\p"
	.string "{PLAYER} und das Team fühlen sich\n"
	.string "erfrischt!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic_DE::
	.string "Ein Thermalbad soll heilende\n"
	.string "Wirkung haben, sagt man.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs_DE::
	.string "Sieh in mein Gesicht! Siehst du,\n"
	.string "wie glatt meine Haut ist?\p"
	.string "Das Wasser vom Thermalbad\n"
	.string "hält meine Haut so jung und straff.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion_DE::
	.string "Nach einem harten Trainingstag\n"
	.string "kann einem entspannenden\l"
	.string "Aufenthalt in einem Thermalbad\l"
	.string "nichts das Wasser reichen.\l"
	.string "BRUNO, der mir voransteht,\l"
	.string "kommt gelegentlich auch\l"
	.string "in diesen KURORT.\l"
	.string "Er kommt hierher, um seine\l"
	.string "Gebrechen und die seiner\l"
	.string "POKéMON zu lindern.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa_DE::
	.string "Thermalbäder und Vulkane\n"
	.string "gehören zusammen.\p"
	.string "Die GLUTTHERME hier habe\n"
	.string "ich vor Jahren errichtet.\p"
	.string "Ich habe das Becken mit meinen\n"
	.string "Händen aus einem riesigen\l"
	.string "Stein geformt.\l"
	.string "Damals habe ich dies benutzt. Ich\l"
	.string "denke, ich kann mich davon trennen.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06_DE::
	.string "Damit pulverisierst du Felsen,\n"
	.string "als wären sie aus Pappe.$"

