SilphCo_6F_Text_RocketsTookOverBuilding_FR::
	.string "La TEAM ROCKET a investi tout\n"
	.string "l'immeuble!$"

SilphCo_6F_Text_BetterGetBackToWork_FR::
	.string "Allez, hop! \n"
	.string "Au boulot!$"

SilphCo_6F_Text_HelpMePlease_FR::
	.string "Pitié, pitié…\n"
	.string "Aidez-moi!$"

SilphCo_6F_Text_WeGotEngaged_FR::
	.string "On va s'marier!\n"
	.string "Haha!$"

SilphCo_6F_Text_ThatManIsSuchACoward_FR::
	.string "Regarde-moi ça!\n"
	.string "Quel froussard celui-là!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim_FR::
	.string "Il a besoin de quelqu'un…\n"
	.string "Alors je vais l'épouser!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld_FR::
	.string "La TEAM ROCKET veut dominer le\n"
	.string "monde avec des POKéMON!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou_FR::
	.string "Tu as fait fuir la TEAM ROCKET!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts_FR::
	.string "Les produits POKéMON de la SYLPHE\n"
	.string "devaient les intéresser.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder_FR::
	.string "Travaille donc pour la SYLPHE\n"
	.string "quand tu auras l'âge!$"

SilphCo_6F_Text_Grunt1Intro_FR::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat_FR::
	.string "Oups…\n"
	.string "Dans le vent!$"

SilphCo_6F_Text_Grunt1PostBattle_FR::
	.string "Pas grave!\n"
	.string "Mes frères me vengeront!$"

SilphCo_6F_Text_TaylorIntro_FR::
	.string "Quel pourri ce PDG!\p"
	.string "Il a décidé de me muter au siège\n"
	.string "de TRIFOUILLI!$"

SilphCo_6F_Text_TaylorDefeat_FR::
	.string "Zut!$"

SilphCo_6F_Text_TaylorPostBattle_FR::
	.string "TRIFOUILLI?\n"
	.string "C'est au beau milieu de nulle part!$"

SilphCo_6F_Text_Grunt2Intro_FR::
	.string "Tu oses défier la TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat_FR::
	.string "C'est pas juste.$"

SilphCo_6F_Text_Grunt2PostBattle_FR::
	.string "Si t'es gentil, t'es pas méchant!$"

SilphCo_6F_Text_FloorSign_FR::
	.string "SYLPHE SARL.\n"
	.string "5ème étage.$"

