SilphCo_6F_Text_RocketsTookOverBuilding_ES::
    .string "¡Los ROCKET vinieron y se\n"
    .string "apoderaron de todo el edificio!$"

SilphCo_6F_Text_BetterGetBackToWork_ES::
    .string "¡Más vale que vuelva al trabajo!$"

SilphCo_6F_Text_HelpMePlease_ES::
    .string "¡Oh, por favor!\n"
    .string "¡Ayúdame!$"

SilphCo_6F_Text_WeGotEngaged_ES::
    .string "¡Somos novios!\n"
    .string "¡Jaja!$"

SilphCo_6F_Text_ThatManIsSuchACoward_ES::
    .string "¡Míralo!\n"
    .string "¡Es tan cobarde!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim_ES::
    .string "¡Me daba tanta pena, que decidí\n"
    .string "ocuparme de él!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld_ES::
    .string "¡El TEAM ROCKET quiere conquistar\n"
    .string "el mundo con sus POKéMON!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou_ES::
    .string "¡El TEAM ROCKET se escapó\n"
    .string "por tu culpa!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts_ES::
    .string "Deben de haber elegido SILPH\n"
    .string "por nuestros productos POKéMON.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder_ES::
    .string "¡Ven a trabajar para SILPH cuando\n"
    .string "seas mayor!$"

SilphCo_6F_Text_Grunt1Intro_ES::
    .string "¡Soy uno de los 4 HERMANOS\n"
    .string "ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat_ES::
    .string "¡Qué paliza!$"

SilphCo_6F_Text_Grunt1PostBattle_ES::
    .string "¡No importa!\n"
    .string "¡Mis hermanos me vengarán!$"

SilphCo_6F_Text_TaylorIntro_ES::
    .string "No puedo con el PRESIDENTE...\p"
    .string "¡No debía haberme enviado a la\n"
    .string "SUCURSAL TIKSI!\p"
    .string "¡Seguro que el TEAM ROCKET\n"
    .string "nos habría dejado en paz!$"

SilphCo_6F_Text_TaylorDefeat_ES::
    .string "¡Estoy acabado!$"

SilphCo_6F_Text_TaylorPostBattle_ES::
    .string "¿La SUCURSAL TIKSI?\n"
    .string "¡Está en medio de la nada!$"

SilphCo_6F_Text_Grunt2Intro_ES::
    .string "¿Te atreves a traicionar al TEAM\n"
    .string "ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat_ES::
    .string "¡Debería darte vergüenza!$"

SilphCo_6F_Text_Grunt2PostBattle_ES::
    .string "¡Si apoyas la justicia, traicionarás\n"
    .string "al malvado!$"

SilphCo_6F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P5$"
