SilphCo_6F_Text_RocketsTookOverBuilding_DE::
	.string "Das TEAM ROCKET hat die Kontrolle\n"
	.string "über das Gebäude übernommen!$"

SilphCo_6F_Text_BetterGetBackToWork_DE::
	.string "O.K., die Arbeit ruft!\n"
	.string "Los geht's!$"

SilphCo_6F_Text_HelpMePlease_DE::
	.string "Oje, ojemine!\n"
	.string "Bitte hilf mir!$"

SilphCo_6F_Text_WeGotEngaged_DE::
	.string "Wir sind verlobt!$"

SilphCo_6F_Text_ThatManIsSuchACoward_DE::
	.string "Schau ihn dir an, den Feigling!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim_DE::
	.string "Ich glaube, ich werde ihn aus\n"
	.string "Mitleid heiraten!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld_DE::
	.string "Das TEAM ROCKET benutzt die\n"
	.string "POKéMON bei dem Versuch, die Welt\l"
	.string "zu erobern!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou_DE::
	.string "Du hast das TEAM ROCKET in die\n"
	.string "Flucht geschlagen!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts_DE::
	.string "Sie müssen es wegen unserer\n"
	.string "POKéMON-Produkte auf die SILPH\l"
	.string "CO. abgesehen haben!$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder_DE::
	.string "Wir würden uns sehr freuen, wenn\n"
	.string "du später einmal für die\l"
	.string "SILPH CO. arbeiten würdest!$"

SilphCo_6F_Text_Grunt1Intro_DE::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_6F_Text_Grunt1Defeat_DE::
	.string "Nein!\n"
	.string "Ich bin raus!$"

SilphCo_6F_Text_Grunt1PostBattle_DE::
	.string "Egal!\n"
	.string "Meine Brüder werden mich rächen!$"

SilphCo_6F_Text_TaylorIntro_DE::
	.string "Dieser verdammte PRÄSIDENT!\p"
	.string "Warum will er ausgerechnet mich\n"
	.string "nach TIKSI schicken?$"

SilphCo_6F_Text_TaylorDefeat_DE::
	.string "Mist!$"

SilphCo_6F_Text_TaylorPostBattle_DE::
	.string "TIKSI?\n"
	.string "Das liegt tief im Niemandsland!$"

SilphCo_6F_Text_Grunt2Intro_DE::
	.string "Du wagst es, dich dem TEAM\n"
	.string "ROCKET zu widersetzen?$"

SilphCo_6F_Text_Grunt2Defeat_DE::
	.string "Du elender Verräter!$"

SilphCo_6F_Text_Grunt2PostBattle_DE::
	.string "Wenn du ehrlich und rechtschaffen\n"
	.string "bist, bekämpfst du das Böse!$"

SilphCo_6F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "5 OG$"

