ThreeIsland_House2_Text_CantMakeThisSpoonBend_IT::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…È inutile! Non riuscirò\n"
    .string "mai a piegare questo cucchiaio\l"
    .string "con la forza del pensiero!\p"
    .string "Comincio a credere di non avere\n"
    .string "nessun potere psichico…$"

ThreeIsland_House2_Text_IAdmireSabrina_IT::
    .string "Conosci la ragazza che è\n"
    .string "CAPOPALESTRA a ZAFFERANOPOLI?\p"
    .string "Usa POKéMON di tipo PSICO, vero?\p"
    .string "Oltre a essere bella, è anche\n"
    .string "molto forte. La ammiro tantissimo.$"

