ThreeIsland_House2_Text_CantMakeThisSpoonBend_FR::
	.string "Ouarrrrgh…\n"
	.string "Gniiiiiiiiiiiiiii…\p"
	.string "Impossible… J'arrive pas à plier\n"
	.string "cette cuillère avec mon esprit.$"

ThreeIsland_House2_Text_IAdmireSabrina_FR::
	.string "T'as entendu parler d'une fille\n"
	.string "CHAMPION d'ARENE de SAFRANIA?\p"
	.string "Elle utilise des POKéMON PSY,\n"
	.string "c'est bien ça?\p"
	.string "C'est le genre de personne que\n"
	.string "j'admire vraiment.\p"
	.string "Et en plus, elle est super\n"
	.string "mignonne.$"

