ThreeIsland_House2_Text_CantMakeThisSpoonBend_DE::
	.string "Urgh!\n"
	.string "Kiah!\p"
	.string "… es ist unnütz! Ich kann\n"
	.string "diesen Löffel nicht mit meiner\l"
	.string "Willenskraft verbiegen.\p"
	.string "Vielleicht habe ich keine\n"
	.string "Psychokräfte!$"

ThreeIsland_House2_Text_IAdmireSabrina_DE::
	.string "Kennst du ein Mädchen, das in\n"
	.string "SAFFRONIA CITY\l"
	.string "ARENALEITERIN ist?\l"
	.string "Sie setzt POKéMON der Element-\l"
	.string "klasse PSYCHO ein, nicht wahr?\p"
	.string "Ich bewundere sie wirklich!\p"
	.string "Ich hörte, dass sie ein cooles\n"
	.string "Mädchen ist und sie soll schön\l"
	.string "sein!$"

