@ Text for this file was split weirdly, and is instead in FourIsland_PokemonCenter_1F/text.inc
@ Theres also an unused JP version of that text in this file instead

JPText_BodySlamTeach_DE::
	.string "そーれ　ぼよーん！\n"
	.string "どっちが　さきに　へたばるか？\l"
	.string "のしかかり　しょうぶ　してるんだ\p"
	.string "きみは　なかまに　はいったら\n"
	.string "つぶれそうだな‥\l"
	.string "かわりに　きみの　ポケモンに\l"
	.string "のしかかり　おしえて　やろっか？$"

JPText_BodySlamDeclined_DE::
	.string "また　おいで　ぼよーん！$"

JPText_BodySlamWhichMon_DE::
	.string "どの　ポケモンに\n"
	.string "おしえたい　かい？$"

JPText_BodySlamTaught_DE::
	.string "ぼよよーん！$"

FourIsland_House1_Text_YoureAwfullyHeavy_DE::
	.string "Hier! Boing!\n"
	.string "Du bist schwer!$"

