FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon_IT::
    .string "Non puoi vincere con un solo\n"
    .string "POKéMON forte.\p"
    .string "È difficile, ma li devi allenare\n"
    .string "tutti in modo uniforme.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian_IT::
    .string "C'è un passaggio stretto ad ovest\n"
    .string "di SMERALDOPOLI.\p"
    .string "Porta alla SEDE CENTRALE della\n"
    .string "LEGA POKéMON che comanda\l"
    .string "tutti gli ALLENATORI.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex_IT::
    .string "Visita la ZONA SAFARI, se stai\n"
    .string "cercando di ampliare il tuo\l"
    .string "POKéDEX.\p"
    .string "Lì incontrerai tutti i tipi di\n"
    .string "POKéMON rari!$"

