FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon_FR::
	.string "Un seul POKéMON puissant n'est pas\n"
	.string "suffisant.\p"
	.string "Mais tous les faire évoluer de\n"
	.string "façon égale n'est pas facile.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian_FR::
	.string "Il y a un petit passage à l'Ouest\n"
	.string "de JADIELLE.\p"
	.string "Il mène au quartier général de la\n"
	.string "LIGUE POKéMON. Ce QG est la plus\l"
	.string "haute autorité des DRESSEURS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex_FR::
	.string "LE PARC SAFARI regorge de\n"
	.string "POKéMON.\p"
	.string "On peut y trouver plein\n"
	.string "de POKéMON très rares!$"

