FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon_DE::
	.string "Man kann nicht mit nur einem starken\n"
	.string "POKéMON gewinnen!\p"
	.string "Es ist mühsam, doch alle POKéMON\n"
	.string "sollten ungefähr den gleichen Level\l"
	.string "haben.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian_DE::
	.string "Westlich von VERTANIA CITY liegt\n"
	.string "ein Pfad.\p"
	.string "Er führt zum Hauptquartier der\n"
	.string "POKéMON LIGA, der höchsten Instanz\l"
	.string "für TRAINER.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex_DE::
	.string "Du studierst die POKéMON?\n"
	.string "Dann gehe in die SAFARI-ZONE.\p"
	.string "Dort gibt es viele seltene POKéMON.$"

