CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons_IT::
    .string "Ah, quel BILL!\p"
    .string "Farebbe di tutto pur di avere dei\n"
    .string "POKéMON rari!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac_IT::
    .string "Hai sentito parlare di BILL?\p"
    .string "Tutti lo chiamano POKéFANATICO!\p"
    .string "Ma credo che la gente sia solo\n"
    .string "gelosa di lui.\p"
    .string "Certo, si vanta un po' dei suoi\n"
    .string "POKéMON, ma chi non lo\l"
    .string "farebbe?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons_IT::
    .string "BILL ha moltissimi POKéMON!\p"
    .string "E alcuni sono rarissimi!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs_IT::
    .string "Perché non vai al piano di sopra\n"
    .string "per scambiare POKéMON con i\l"
    .string "tuoi amici?\p"
    .string "Lo scambio ti fa ottenere molte\n"
    .string "specie di POKéMON.\p"
    .string "Inoltre, lo sapevi che i POKéMON\n"
    .string "ricevuti con uno scambio crescono\l"
    .string "più rapidamente?$"

