CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons_FR::
	.string "Sacré LEO!\p"
	.string "Il donnerait n'importe quoi pour\n"
	.string "mettre la main sur un POKéMON\l"
	.string "rare!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac_FR::
	.string "Tu connais LEO?\p"
	.string "On raconte que c'est un vrai\n"
	.string "POKéMANIAC!\p"
	.string "Les gens sont juste jaloux\n"
	.string "de LEO.\p"
	.string "Nous sommes tous un peu \n"
	.string "POKéMANIAC, non?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons_FR::
	.string "LEO a une sacrée collection de\n"
	.string "POKéMON!\p"
	.string "Et des rares, en plus…$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs_FR::
	.string "Tu devrais aller à l'étage pour\n"
	.string "faire des échanges avec tes amis.\p"
	.string "Tu peux avoir plus de POKéMON\n"
	.string "en faisant des échanges.\p"
	.string "En plus, les POKéMON échangés\n"
	.string "grandissent plus rapidement.$"

