TwoIsland_Text_IslandSign_FR::
	.string "ILE 2\n"
	.string "Le bonheur à deux$"

TwoIsland_Text_JoyfulGameCornerSign_FR::
	.string "SALLE DE JEU\n"
	.string "Affrontez vos adversaires$"

TwoIsland_Text_DangerFastCurrent_FR::
	.string "DANGER! RAPIDES!\n"
	.string "Surf et pêche interdits!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited_FR::
	.string "Oh, bienvenue dans ma boutique!\p"
	.string "Nous n'avons ouvert que très\n"
	.string "récemment.\p"
	.string "Nos stocks sont limités mais\n"
	.string "j'espère vous servir au mieux.$"

TwoIsland_Text_AddedMerchandiseForLostelle_FR::
	.string "Je ne trouve pas les mots pour\n"
	.string "vous remercier d'avoir sauvé\p"
	.string "LOSTELLE. Grâce à vos exploits,\n"
	.string "les habitants de l'ILE 3 ont\p"
	.string "changé leurs idées reçues sur\n"
	.string "les gens de KANTO.\p"
	.string "Je suis de KANTO, vous savez.\p"
	.string "Les gens de l'ILE 3 m'ont aidé à\n"
	.string "monter mon STAND.$"

TwoIsland_Text_HopeYouGiveItYourBest_FR::
	.string "Je donne le meilleur de moi-même.\n"
	.string "J'espère que vous aussi, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands_FR::
	.string "Oh, bonjour, {PLAYER}!\n"
	.string "Bienvenue!\p"
	.string "J'ai commencé à rapporter des\n"
	.string "objets des îles aux alentours.\p"
	.string "J'en ai de très rares, vous devriez\n"
	.string "venir voir.$"

TwoIsland_Text_FellowMovedFromCeladonCity_FR::
	.string "Ce type là, il est venu de\n"
	.string "CELADOPOLE pour s'installer ici.\p"
	.string "Il a ouvert un STAND avec son\n"
	.string "jeune frère.\p"
	.string "Je me demande s'il sait dans quoi\n"
	.string "il s'est embarqué.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner_FR::
	.string "Le frère du vendeur du STAND\n"
	.string "a un job à la SALLE DE JEU.\p"
	.string "Ils essaient d'économiser à deux\n"
	.string "pour acheter plus de marchandises.$"

TwoIsland_Text_BrunoCameToIslandWhileBack_FR::
	.string "Ecoute, écoute.\p"
	.string "Un DRESSEUR célèbre est venu\n"
	.string "sur l'ILE il y a quelque temps.\p"
	.string "Il fait partie du CONSEIL 4,\n"
	.string "il s'appelle ALDO.\p"
	.string "Il est reparti très déçu quand\n"
	.string "il a vu que les SUPER BONBONS\p"
	.string "étaient en rupture de stock\n"
	.string "partout.$"

TwoIsland_Text_BuyRareItemsHere_FR::
	.string "Les DRESSEURS futés savent que\n"
	.string "les objets rares se trouvent ici.$"

TwoIsland_Text_OldWomanLivesOutOnCape_FR::
	.string "Il y a une femme qui vit au bout\n"
	.string "du cap.\p"
	.string "Elle fait des commentaires sur\n"
	.string "les POKéMON.\p"
	.string "C'est super troublant.$"

TwoIsland_Text_HaveYouTriedJumpingGame_FR::
	.string "Boing, boing!\n"
	.string "T'as essayé le jeu de saut?\p"
	.string "Il te faut des POKéMON qui\n"
	.string "peuvent… boing, boing!\p"
	.string "Y'en a qui font boing!\n"
	.string "Et d'autres boiiiiiing!\p"
	.string "Tu savais pas, hein?$"

