TwoIsland_Text_IslandSign_DE::
	.string "EILAND ZWEI\n"
	.string "Ein Paradies für Zwei$"

TwoIsland_Text_JoyfulGameCornerSign_DE::
	.string "Entertainment & Snacks!\n"
	.string "Action pur in der SPIELHALLE$"

TwoIsland_Text_DangerFastCurrent_DE::
	.string "ACHTUNG! STARKE STRÖMUNG!\n"
	.string "Angeln und Surfen verboten!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited_DE::
	.string "OH!\n"
	.string "Hallo, willkommen in meinem Laden!\p"
	.string "Wir hatten erst vor kurzem unsere\n"
	.string "Eröffnung!\p"
	.string "Das Angebot ist klein, aber ich\n"
	.string "hoffe, du findest etwas für dich!$"

TwoIsland_Text_AddedMerchandiseForLostelle_DE::
	.string "Ich kann dir gar nicht sagen, wie\n"
	.string "dankbar ich dir für die Rettung\l"
	.string "von IRRMA bin.\l"
	.string "Dank dir haben die Einwohner von\l"
	.string "TRI-EILAND ihre Meinung über die\l"
	.string "Menschen aus KANTO geändert.\l"
	.string "Und ich komme aus KANTO.\p"
	.string "Die Bewohner von TRI-EILAND haben\n"
	.string "mir bei der Warenzusammenstellung\l"
	.string "geholfen.$"

TwoIsland_Text_HopeYouGiveItYourBest_DE::
	.string "Hallo! Ich gebe hier mein Bestes!\n"
	.string "Ich hoffe, du auch {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands_DE::
	.string "Oh, hallo, {PLAYER}!\n"
	.string "Willkommen!\p"
	.string "Ich bringe Items von fernen Inseln\n"
	.string "hierher.\p"
	.string "Ich habe auch einige seltene\n"
	.string "Items. Sieh dich in Ruhe um!$"

TwoIsland_Text_FellowMovedFromCeladonCity_DE::
	.string "Dieser Mann dort ist von PRISMANIA\n"
	.string "CITY hergezogen.\p"
	.string "Er hat mit seinem kleinen Bruder\n"
	.string "einen Laden aufgemacht.\p"
	.string "Ich weiß nicht, ob er sich bewusst\n"
	.string "war, worauf er sich einlässt.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner_DE::
	.string "Der Bruder des Ladenbesitzers hat\n"
	.string "einen Job in der SPIELHALLE\l"
	.string "angenommen.\l"
	.string "Er versucht, mehr Geld zu\l"
	.string "verdienen, damit sie ihr Waren-\l"
	.string "angebot vergrößern können.$"

TwoIsland_Text_BrunoCameToIslandWhileBack_DE::
	.string "Hör zu!\n"
	.string "Wusstest du…\p"
	.string "Ein berühmter TRAINER ist vor\n"
	.string "geraumer Zeit auf das EILAND\l"
	.string "gekommen.\l"
	.string "Er ist einer der TOP VIER!\l"
	.string "Sein Name ist BRUNO!\p"
	.string "Er ist gegangen, weil er enttäuscht\n"
	.string "war, dass alle WUTKEKSE\l"
	.string "ausverkauft waren.$"

TwoIsland_Text_BuyRareItemsHere_DE::
	.string "Der anspruchsvolle TRAINER\n"
	.string "kauft hier seltene Items!$"

TwoIsland_Text_OldWomanLivesOutOnCape_DE::
	.string "Am Kap lebt eine alte Frau in einer\n"
	.string "Hütte.\p"
	.string "Sie begutachtet POKéMON ganz\n"
	.string "genau. Es ist ein wenig\l"
	.string "merkwürdig.$"

TwoIsland_Text_HaveYouTriedJumpingGame_DE::
	.string "Boing! Boing!\n"
	.string "Hast du schon das Sprungspiel\l"
	.string "ausprobiert?\l"
	.string "Die POKéMON, die daran teilnehmen…\l"
	.string "Boing!\p"
	.string "Einige machen boing!\p"
	.string "Und andere machen boooooooing!\p"
	.string "Wusstest du das?\n"
	.string "Boing!$"

