TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner_DE::
	.string "Warst du schon in der SPIELHALLE?\p"
	.string "Du solltest nicht allein dorthin\n"
	.string "gehen! Nimm einen Freund mit!$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape_DE::
	.string "Auf EILAND ZWEI leben nicht\n"
	.string "viele Menschen!\p"
	.string "Es gibt da eine alte Dame, die\n"
	.string "draußen am Kap wohnt!\p"
	.string "Sie ist schon immer da gewesen!$"

