TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner_ES::
    .string "¿Conoces ya los RECREATIVOS?\p"
    .string "Lo suyo es ir al menos con\n"
    .string "un amigo. Si no, es un rollo.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape_ES::
    .string "ISLA SECUNDA tiene muy pocos\n"
    .string "habitantes.\p"
    .string "En el mismo cabo vive una señora\n"
    .string "mayor.\p"
    .string "Lleva allí ni se sabe...$"
