FiveIsland_LostCave_Room4_Text_LauraIntro_ES::
    .string "A mí me parece que en esta cueva\n"
    .string "se está cociendo algo.$"

FiveIsland_LostCave_Room4_Text_LauraDefeat_ES::
    .string "Como no tomes el túnel adecuado,\n"
    .string "no conseguirás avanzar.$"

FiveIsland_LostCave_Room4_Text_LauraPostBattle_ES::
    .string "Hace poco entró una señora\n"
    .string "en las cuevas de ahí.$"
