FiveIsland_LostCave_Room4_Text_LauraIntro_FR::
	.string "Il doit y avoir une puissance\n"
	.string "étrange dans cette grotte.$"

FiveIsland_LostCave_Room4_Text_LauraDefeat_FR::
	.string "Si tu ne vas pas dans le bon\n"
	.string "tunnel, tu ne pourras jamais sortir.$"

FiveIsland_LostCave_Room4_Text_LauraPostBattle_FR::
	.string "Une femme est venue dans les\n"
	.string "grottes il y a quelque temps.$"

