Route16_Text_LaoIntro_IT::
    .string "Che vuoi?$"

Route16_Text_LaoDefeat_IT::
    .string "Non osare ridere!$"

Route16_Text_LaoPostBattle_IT::
    .string "Ci piace stare qui!\n"
    .string "E a te, che t'importa?$"

Route16_Text_KojiIntro_IT::
    .string "Bella BICICLETTA!\n"
    .string "Dà qua!$"

Route16_Text_KojiDefeat_IT::
    .string "Sono KO!$"

Route16_Text_KojiPostBattle_IT::
    .string "Lascia stare.\n"
    .string "Non mi serve la BICICLETTA!$"

Route16_Text_LukeIntro_IT::
    .string "Vieni a giocare, pulce!$"

Route16_Text_LukeDefeat_IT::
    .string "Sei una pulce vincente!$"

Route16_Text_LukePostBattle_IT::
    .string "Odio perdere!\n"
    .string "Sparisci da qui!$"

Route16_Text_HideoIntro_IT::
    .string "Ehi!\n"
    .string "Mi hai urtato!$"

Route16_Text_HideoDefeat_IT::
    .string "Tombola!$"

Route16_Text_HideoPostBattle_IT::
    .string "Seguendo la costa da ARANCIOPOLI\n"
    .string "puoi raggiungere FUCSIAPOLI.$"

Route16_Text_CamronIntro_IT::
    .string "Ho fame e mi sto arrabbiando!$"

Route16_Text_CamronDefeat_IT::
    .string "Male, molto molto male!$"

Route16_Text_CamronPostBattle_IT::
    .string "Mi piacciono i POKéMON feroci!\n"
    .string "Sbranano i nemici, anche se solo\l"
    .string "in senso figurato.$"

Route16_Text_RubenIntro_IT::
    .string "Ehi, divertiamoci con una bella\n"
    .string "lotta!$"

Route16_Text_RubenDefeat_IT::
    .string "Non farmi arrabbiare!$"

Route16_Text_RubenPostBattle_IT::
    .string "Mi piace molestare la gente con il\n"
    .string "fetore dei miei POKéMON!$"

Route16_Text_MonSprawledOutInSlumber_IT::
    .string "Un POKéMON addormentato blocca la\n"
    .string "strada!$"

Route16_Text_CyclingRoadSign_IT::
    .string "Buona discesa!\n"
    .string "PISTA CICLABILE$"

Route16_Text_RouteSign_IT::
    .string "PERCORSO 16\n"
    .string "AZZURROPOLI - FUCSIAPOLI$"

Route16_Text_JedIntro_IT::
    .string "JED: Il nostro amore è senza\n"
    .string "confini, e senza rivali!$"

Route16_Text_JedDefeat_IT::
    .string "JED: Oh, no! Ora LEA crederà che\n"
    .string "sono un perdente!$"

Route16_Text_JedPostBattle_IT::
    .string "JED: A volte credo che LEA si\n"
    .string "aspetti un po' troppo da me.$"

Route16_Text_JedNotEnoughMons_IT::
    .string "JED: Hai solo un POKéMON?\n"
    .string "Ma non hai proprio cuore!$"

Route16_Text_LeaIntro_IT::
    .string "LEA: A volte ho paura di amare\n"
    .string "troppo JED.$"

Route16_Text_LeaDefeat_IT::
    .string "LEA: Ho perso, ma il mio amore per\n"
    .string "JED è imbattibile.$"

Route16_Text_LeaPostBattle_IT::
    .string "LEA: Non credi anche tu che il\n"
    .string "mio ragazzo sia meraviglioso?$"

Route16_Text_LeaNotEnoughMons_IT::
    .string "LEA: Ah, non hai con te due\n"
    .string "POKéMON?\p"
    .string "Non vi sentite soli tu e il tuo\n"
    .string "POKéMON?$"

