Route16_Text_LaoIntro_FR::
	.string "Kess t'as ta?$"

Route16_Text_LaoDefeat_FR::
	.string "…\n"
	.string "Galère!$"

Route16_Text_LaoPostBattle_FR::
	.string "Nous? On squatte ici…\n"
	.string "Et toi?$"

Route16_Text_KojiIntro_FR::
	.string "Joli VELO!\n"
	.string "Donne-le moi!$"

Route16_Text_KojiDefeat_FR::
	.string "Tu peux garder ton VELO!$"

Route16_Text_KojiPostBattle_FR::
	.string "Je le veux pas ton VELO!$"

Route16_Text_LukeIntro_FR::
	.string "Viens t'battre!\n"
	.string "Sale fouine!$"

Route16_Text_LukeDefeat_FR::
	.string "Toi!!\n"
	.string "Espèce de fennec!$"

Route16_Text_LukePostBattle_FR::
	.string "Je déteste perdre…\n"
	.string "Surtout dans ces conditions!$"

Route16_Text_HideoIntro_FR::
	.string "Hé!\n"
	.string "Tu viens de me rentrer dedans, là?$"

Route16_Text_HideoDefeat_FR::
	.string "Schplaff!$"

Route16_Text_HideoPostBattle_FR::
	.string "On restera là, que ça te plaise\n"
	.string "ou pas!\p"
	.string "Tu peux aussi aller de CARMIN\n"
	.string "SUR MER à PARMANIE par la côte.$"

Route16_Text_CamronIntro_FR::
	.string "J'ai faim, j'suis furax et j'vais\n"
	.string "t'exploser!$"

Route16_Text_CamronDefeat_FR::
	.string "Grrr!\n"
	.string "J'suis encore plus furax!$"

Route16_Text_CamronPostBattle_FR::
	.string "Mes POKéMON sont féroces!\n"
	.string "Ils déchirent mes ennemis!$"

Route16_Text_RubenIntro_FR::
	.string "BASTOONNNN!$"

Route16_Text_RubenDefeat_FR::
	.string "Bah!\n"
	.string "M'énerve pas!$"

Route16_Text_RubenPostBattle_FR::
	.string "Je terrorise mes adversaires avec\n"
	.string "mes POKéMON super vicieux!\p"
	.string "Ils sont super pour faire flipper.\n"
	.string "Et en plus ils mordent!$"

Route16_Text_MonSprawledOutInSlumber_FR::
	.string "Un gros POKéMON endormi bloque\n"
	.string "le chemin!$"

Route16_Text_CyclingRoadSign_FR::
	.string "Bonne descente!\n"
	.string "PISTE CYCLABLE$"

Route16_Text_RouteSign_FR::
	.string "ROUTE 16\n"
	.string "CELADOPOLE - PARMANIE$"

Route16_Text_JedIntro_FR::
	.string "ALI: Notre amour n'a pas de limite.\n"
	.string "On s'aime et on le montre!$"

Route16_Text_JedDefeat_FR::
	.string "ALI: Noon, mon amour va me\n"
	.string "prendre pour un perdant.$"

Route16_Text_JedPostBattle_FR::
	.string "ALI: Ecoute LISE, c'est au combat\n"
	.string "que tu dois penser, pas à moi.$"

Route16_Text_JedNotEnoughMons_FR::
	.string "ALI: Tu n'as qu'un POKéMON?\p"
	.string "N'y a-t-il pas de place dans\n"
	.string "ton cœur?$"

Route16_Text_LeaIntro_FR::
	.string "LISE: Je suis parfois effrayée par\n"
	.string "la force de notre amour.$"

Route16_Text_LeaDefeat_FR::
	.string "LISE: Mais je le trouve beau même\n"
	.string "quand il perd.$"

Route16_Text_LeaPostBattle_FR::
	.string "LISE: Je suis désolée.\n"
	.string "Je pensais à ALI.$"

Route16_Text_LeaNotEnoughMons_FR::
	.string "LISE: Tu n'as qu'un POKéMON?\p"
	.string "Tu n'as pas peur qu'il se sente\n"
	.string "un peu seul?$"

