Route16_Text_LaoIntro_DE::
	.string "Was willst du?$"

Route16_Text_LaoDefeat_DE::
	.string "Wage ja nicht zu lachen!$"

Route16_Text_LaoPostBattle_DE::
	.string "Wir lungern hier herum!\n"
	.string "Wie sieht es bei dir aus?$"

Route16_Text_KojiIntro_DE::
	.string "Du besitzt ein schönes FAHRRAD!\n"
	.string "Her damit!$"

Route16_Text_KojiDefeat_DE::
	.string "K.O.!$"

Route16_Text_KojiPostBattle_DE::
	.string "Na ja, vergiss es!\n"
	.string "Wer braucht schon ein FAHRRAD?$"

Route16_Text_LukeIntro_DE::
	.string "Lass uns spielen, Hasenfuß!$"

Route16_Text_LukeDefeat_DE::
	.string "Du kleine Ratte!$"

Route16_Text_LukePostBattle_DE::
	.string "Ich hasse es, zu verlieren!\n"
	.string "Mach, dass du wegkommst!$"

Route16_Text_HideoIntro_DE::
	.string "Heh! Du hast mich angerempelt!$"

Route16_Text_HideoDefeat_DE::
	.string "Rumms! Überrumpelt!$"

Route16_Text_HideoPostBattle_DE::
	.string "Man kann über eine Küstenstraße\n"
	.string "von ORANIA CITY nach FUCHSANIA\l"
	.string "CITY gelangen.$"

Route16_Text_CamronIntro_DE::
	.string "Ich bin furchtbar gemein und\n"
	.string "erfolgssüchtig!$"

Route16_Text_CamronDefeat_DE::
	.string "Nein, nein, nein!$"

Route16_Text_CamronPostBattle_DE::
	.string "Ich mag wilde POKéMON!\n"
	.string "Sie strotzen nur so vor Kraft!$"

Route16_Text_RubenIntro_DE::
	.string "Ja, sicher!\n"
	.string "Ich mache dir Platz!$"

Route16_Text_RubenDefeat_DE::
	.string "Treibe mich nicht in den Wahnsinn!$"

Route16_Text_RubenPostBattle_DE::
	.string "Ich liebe es, andere mit meinen\n"
	.string "bissigen POKéMON zu schikanieren!$"

Route16_Text_MonSprawledOutInSlumber_DE::
	.string "Ein schlafendes POKéMON versperrt\n"
	.string "den Weg!$"

Route16_Text_CyclingRoadSign_DE::
	.string "RADWEG\n"
	.string "Gute Abfahrt!$"

Route16_Text_RouteSign_DE::
	.string "ROUTE 16\n"
	.string "PRISMANIA CITY - FUCHSANIA CITY$"

Route16_Text_JedIntro_DE::
	.string "UWE: Unsere Liebe kennt keine\n"
	.string "Grenzen. Wir lieben uns und\l"
	.string "zeigen das!$"

Route16_Text_JedDefeat_DE::
	.string "UWE: Oh, nein! Meine Geliebte hat\n"
	.string "mich verlieren sehen.$"

Route16_Text_JedPostBattle_DE::
	.string "UWE: Hör zu, LENA! Du solltest\n"
	.string "dich weniger auf mich\l"
	.string "konzentrieren.$"

Route16_Text_JedNotEnoughMons_DE::
	.string "UWE: Du hast nur ein POKéMON?\n"
	.string "Gibt es in deinem Herzen\l"
	.string "keine Liebe?$"

Route16_Text_LeaIntro_DE::
	.string "LENA: Manchmal erschreckt es mich,\n"
	.string "wie intensiv unsere Liebe ist.$"

Route16_Text_LeaDefeat_DE::
	.string "LENA: Oh! Aber UWE sieht auch bei\n"
	.string "einer Niederlage cool aus!$"

Route16_Text_LeaPostBattle_DE::
	.string "LENA: Äh, es tut mir Leid.\n"
	.string "UWE ist so cool.$"

Route16_Text_LeaNotEnoughMons_DE::
	.string "LENA: Oh, du hast keine zwei\n"
	.string "POKéMON bei dir?\p"
	.string "Fühlst du dich oder fühlt sich\n"
	.string "dein POKéMON nicht einsam?$"

