Route6_Text_RickyIntro_IT::
    .string "Chi va là?\n"
    .string "Smetti di origliare!$"

Route6_Text_RickyDefeat_IT::
    .string "Elementare, non riesco a vincere!$"

Route6_Text_RickyPostBattle_IT::
    .string "Bla bla bla…\n"
    .string "Bla bla bla…$"

Route6_Text_NancyIntro_IT::
    .string "Scusa, ma è una conversazione\n"
    .string "privata!$"

Route6_Text_NancyDefeat_IT::
    .string "Grr!\n"
    .string "Odio perdere!$"

Route6_Text_NancyPostBattle_IT::
    .string "Bla bla bla…\n"
    .string "Bla bla bla…$"

Route6_Text_KeigoIntro_IT::
    .string "Non ci sono molti insetti qui.$"

Route6_Text_KeigoDefeat_IT::
    .string "No!\n"
    .string "Scherzi?!$"

Route6_Text_KeigoPostBattle_IT::
    .string "Mi piacciono gli insetti! Tornerò\n"
    .string "al BOSCO SMERALDO a cercare\l"
    .string "POKéMON di tipo COLEOTTERO!$"

Route6_Text_JeffIntro_IT::
    .string "Eh?\n"
    .string "Volevi parlarmi?$"

Route6_Text_JeffDefeat_IT::
    .string "Non ho cominciato io!$"

Route6_Text_JeffPostBattle_IT::
    .string "Per sicurezza dovrei portare più\n"
    .string "POKéMON con me.$"

Route6_Text_IsabelleIntro_IT::
    .string "Dici a me?\n"
    .string "Bene! Giochiamo!$"

Route6_Text_IsabelleDefeat_IT::
    .string "Non ha funzionato!$"

Route6_Text_IsabellePostBattle_IT::
    .string "Devo rafforzarmi!\n"
    .string "Qual è il tuo segreto?$"

Route6_Text_ElijahIntro_IT::
    .string "Non ti ho mai visto in giro!\n"
    .string "Sei in gamba?$"

Route6_Text_ElijahDefeat_IT::
    .string "Sei troppo in gamba!$"

Route6_Text_ElijahPostBattle_IT::
    .string "Il mio POKéMON è debole, o sono\n"
    .string "un disastro io?$"

Route6_Text_UndergroundPathSign_IT::
    .string "VIA SOTTERRANEA\n"
    .string "CELESTOPOLI - ARANCIOPOLI$"

