Route6_Text_RickyIntro_DE::
	.string "Wer da? Heh, hör auf, uns heimlich\n"
	.string "zu belauschen!$"

Route6_Text_RickyDefeat_DE::
	.string "Ich kann einfach nie siegen!$"

Route6_Text_RickyPostBattle_DE::
	.string "Flüster...\n"
	.string "Tuschel...$"

Route6_Text_NancyIntro_DE::
	.string "Entschuldige, aber das hier ist\n"
	.string "Privatsache!$"

Route6_Text_NancyDefeat_DE::
	.string "Grr!\n"
	.string "Ich hasse es, zu verlieren!$"

Route6_Text_NancyPostBattle_DE::
	.string "Flüster...\n"
	.string "Tuschel...$"

Route6_Text_KeigoIntro_DE::
	.string "Man findet hier draußen nicht viele\n"
	.string "Käfer...$"

Route6_Text_KeigoDefeat_DE::
	.string "Du beliebst zu scherzen, oder?$"

Route6_Text_KeigoPostBattle_DE::
	.string "Ich gehe in den VERTANIA-WALD\n"
	.string "zurück. Dort gibt es mehr Käfer!$"

Route6_Text_JeffIntro_DE::
	.string "Hörte ich da jemanden vom Kämpfen\n"
	.string "sprechen?$"

Route6_Text_JeffDefeat_DE::
	.string "Hmm, ich hätte es besser überhört!$"

Route6_Text_JeffPostBattle_DE::
	.string "Zu meiner eigenen Sicherheit sollte\n"
	.string "ich mehr POKéMON bei mir tragen!$"

Route6_Text_IsabelleIntro_DE::
	.string "Kämpfen? Meinst du mich?\n"
	.string "Na gut!$"

Route6_Text_IsabelleDefeat_DE::
	.string "Das hat nicht ganz geklappt!$"

Route6_Text_IsabellePostBattle_DE::
	.string "Verrätst du mir dein Geheimnis?\n"
	.string "Ich möchte auch stärker werden!$"

Route6_Text_ElijahIntro_DE::
	.string "Dich habe ich noch nie gesehen!\n"
	.string "Bist du ein guter TRAINER?$"

Route6_Text_ElijahDefeat_DE::
	.string "Du bist ein zu guter TRAINER!$"

Route6_Text_ElijahPostBattle_DE::
	.string "Ist mein POKéMON zu schwach,\n"
	.string "oder bin ich etwa nicht gut genug?$"

Route6_Text_UndergroundPathSign_DE::
	.string "TUNNELPFAD\n"
	.string "AZURIA CITY - ORANIA CITY$"

