Route6_Text_RickyIntro_ES::
    .string "¿Quién está ahí?\n"
    .string "¡Deja de espiarnos!$"

Route6_Text_RickyDefeat_ES::
    .string "¡Sencillamente, no puedo ganar!$"

Route6_Text_RickyPostBattle_ES::
    .string "(Pues sí que...)$"

Route6_Text_NancyIntro_ES::
    .string "¡Perdona!\n"
    .string "¡Esta conversación es privada!$"

Route6_Text_NancyDefeat_ES::
    .string "¡Odio perder!$"

Route6_Text_NancyPostBattle_ES::
    .string "(Pues sí que...)$"

Route6_Text_KeigoIntro_ES::
    .string "No hay muchos bichos por aquí.$"

Route6_Text_KeigoDefeat_ES::
    .string "¡No!\n"
    .string "¿Estás de broma?$"

Route6_Text_KeigoPostBattle_ES::
    .string "Me gustan los bichos. Voy a\n"
    .string "regresar al BOSQUE VERDE.$"

Route6_Text_JeffIntro_ES::
    .string "¿Qué?\n"
    .string "¿Quieres hablar conmigo?$"

Route6_Text_JeffDefeat_ES::
    .string "¡Has empezado tú!$"

Route6_Text_JeffPostBattle_ES::
    .string "Debería llevar más POKéMON\n"
    .string "para protegerme.$"

Route6_Text_IsabelleIntro_ES::
    .string "¿Yo?\n"
    .string "Pues vale. ¡Jugaré!$"

Route6_Text_IsabelleDefeat_ES::
    .string "¡No ha podido ser!$"

Route6_Text_IsabellePostBattle_ES::
    .string "¡Quiero ser más fuerte!\n"
    .string "¿Cuál es tu secreto?$"

Route6_Text_ElijahIntro_ES::
    .string "¡Jamás te había visto por aquí!\n"
    .string "¿Eres fuerte?$"

Route6_Text_ElijahDefeat_ES::
    .string "¡Eres demasiado fuerte!$"

Route6_Text_ElijahPostBattle_ES::
    .string "¿Es débil mi POKéMON o soy yo\n"
    .string "muy malo?$"

Route6_Text_UndergroundPathSign_ES::
    .string "VÍA SUBTERRÁNEA:\n"
    .string "CIUDAD CELESTE - CIUDAD CARMÍN$"
