Route6_Text_RickyIntro_FR::
	.string "Qui est là?\n"
	.string "Arrête de nous espionner!$"

Route6_Text_RickyDefeat_FR::
	.string "…\n"
	.string "J'suis nul!$"

Route6_Text_RickyPostBattle_FR::
	.string "Soupirs…\n"
	.string "Gros soupirs…$"

Route6_Text_NancyIntro_FR::
	.string "Heu, c'est une conversation privée,\n"
	.string "DEGAGE!$"

Route6_Text_NancyDefeat_FR::
	.string "Non!\n"
	.string "Je déteste perdre!$"

Route6_Text_NancyPostBattle_FR::
	.string "Soupirs…\n"
	.string "Gros soupirs…$"

Route6_Text_KeigoIntro_FR::
	.string "C'est plein d'insectes, ici.$"

Route6_Text_KeigoDefeat_FR::
	.string "Non!\n"
	.string "C'est une blague!$"

Route6_Text_KeigoPostBattle_FR::
	.string "Les insectes j'aime ça, je\n"
	.string "retourne dans la FORET DE JADE.$"

Route6_Text_JeffIntro_FR::
	.string "Hein?\n"
	.string "Tu veux me causer?$"

Route6_Text_JeffDefeat_FR::
	.string "…\n"
	.string "J'ai rien fait!$"

Route6_Text_JeffPostBattle_FR::
	.string "Il me faut plus de POKéMON pour\n"
	.string "me protéger.$"

Route6_Text_IsabelleIntro_FR::
	.string "Qui ça? Moi?\n"
	.string "OK. Attaque!$"

Route6_Text_IsabelleDefeat_FR::
	.string "Oh!\n"
	.string "J'avais pas prévu ça!$"

Route6_Text_IsabellePostBattle_FR::
	.string "Je veux être forte! Comme toi!\n"
	.string "C'est quoi ton secret?$"

Route6_Text_ElijahIntro_FR::
	.string "J't'ai jamais vu dans le coin!\n"
	.string "T'es balèze?$"

Route6_Text_ElijahDefeat_FR::
	.string "Whaa!\n"
	.string "Trop puissant!$"

Route6_Text_ElijahPostBattle_FR::
	.string "Mes POKéMON sont nuls ou je suis\n"
	.string "très mauvais?$"

Route6_Text_UndergroundPathSign_FR::
	.string "SOUTERRAIN\n"
	.string "AZURIA - CARMIN SUR MER$"

