CeruleanCity_House1_Text_BadgesHaveAmazingSecrets_FR::
	.string "Les BADGES sont portés par des\n"
	.string "DRESSEURS de haut niveau.\p"
	.string "Mmm… Tu en as au moins un.\p"
	.string "Ces BADGES ont d'étranges pouvoirs!$"

CeruleanCity_House1_Text_DescribeWhichBadge_FR::
	.string "Dis-moi…\p"
	.string "Lequel des 8 BADGES veux-tu que\n"
	.string "je décrive?$"

CeruleanCity_House1_Text_ComeVisitAnytime_FR::
	.string "Reviens me voir quand tu veux.$"

CeruleanCity_House1_Text_AttackStatFlash_FR::
	.string "L'ATTAQUE de tous tes POKéMON est\n"
	.string "augmentée.\p"
	.string "Il permet aussi d'utiliser la CS\n"
	.string "FLASH hors des combats.$"

CeruleanCity_House1_Text_ObeyLv30Cut_FR::
	.string "Les POKéMON d'un niveau inférieur\n"
	.string "à 30 t'obéiront.\p"
	.string "Cela comprend aussi les POKéMON\n"
	.string "obtenus pendant un échange.\p"
	.string "S'ils sont d'un niveau supérieur,\n"
	.string "ils seront incontrôlables!\p"
	.string "Tu pourras aussi utiliser la CS\n"
	.string "COUPE hors des combats.$"

CeruleanCity_House1_Text_SpeedStatFly_FR::
	.string "La VITESSE de tous tes POKéMON\n"
	.string "sera un peu augmentée.\p"
	.string "Tu pourras aussi utiliser la CS VOL\n"
	.string "hors des combats.$"

CeruleanCity_House1_Text_ObeyLv50Strength_FR::
	.string "Les POKéMON jusqu'au niveau 50\n"
	.string "t'obéiront.\p"
	.string "Cela comprend aussi les POKéMON\n"
	.string "obtenus pendant un échange.\p"
	.string "Ceux d'un niveau supérieur seront\n"
	.string "incontrôlables!\p"
	.string "Tu pourras aussi utiliser la CS\n"
	.string "FORCE hors des combats.$"

CeruleanCity_House1_Text_DefenseStatSurf_FR::
	.string "La DEFENSE de tous tes POKéMON\n"
	.string "sera augmentée.\p"
	.string "Tu pourras aussi utiliser la CS\n"
	.string "SURF hors des combats.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash_FR::
	.string "Les POKéMON de niveau 70 ou moins\n"
	.string "t'obéiront.\p"
	.string "Cela comprend aussi les POKéMON\n"
	.string "obtenus pendant un échange.\p"
	.string "S'ils sont d'un niveau supérieur, ils\n"
	.string "seront incontrôlables!\p"
	.string "Tu pourras aussi utiliser la CS\n"
	.string "ECLATE-ROC hors des combats.$"

CeruleanCity_House1_Text_SpStatsWaterfall_FR::
	.string "Les stats des ATQ. SPE. et\n"
	.string "DEF. SPE. augmentent un peu. \p"
	.string "Tu pourras aussi utiliser\n"
	.string "CASCADE hors des combats.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou_FR::
	.string "Tous les POKéMON obéiront à tes\n"
	.string "ordres!$"

