CeruleanCity_House1_Text_BadgesHaveAmazingSecrets_DE::
	.string "Nur sehr begabte TRAINER tragen\n"
	.string "POKéMON-ORDEN.\p"
	.string "Wie ich sehe, bist du bereits\n"
	.string "Träger eines ORDENs.\p"
	.string "Die ORDEN sind geheimnisumwoben!$"

CeruleanCity_House1_Text_DescribeWhichBadge_DE::
	.string "Also dann...\p"
	.string "Über welchen der acht ORDEN soll\n"
	.string "ich dir etwas erzählen?$"

CeruleanCity_House1_Text_ComeVisitAnytime_DE::
	.string "Besuche mich, wann immer du\n"
	.string "möchtest.$"

CeruleanCity_House1_Text_AttackStatFlash_DE::
	.string "Die ANGRIFFE deiner POKéMON\n"
	.string "werden ein wenig verstärkt.\p"
	.string "Außerdem kannst du jederzeit BLITZ\n"
	.string "einsetzen.$"

CeruleanCity_House1_Text_ObeyLv30Cut_DE::
	.string "POKéMON bis Level 30 folgen deinen\n"
	.string "Befehlen!\p"
	.string "POKéMON höherer Level gehorchen\n"
	.string "dir jedoch nicht!\p"
	.string "Ferner kannst du den ZERSCHNEIDER\n"
	.string "außerhalb von Kämpfen nutzen!$"

CeruleanCity_House1_Text_SpeedStatFly_DE::
	.string "Die INITIATIVE deiner POKéMON\n"
	.string "nimmt zu.\p"
	.string "Des Weiteren ist es dir möglich,\n"
	.string "FLIEGEN außerhalb von Kämpfen\l"
	.string "einzusetzen.$"

CeruleanCity_House1_Text_ObeyLv50Strength_DE::
	.string "POKéMON bis Level 50 folgen deinen\n"
	.string "Befehlen.\p"
	.string "POKéMON höherer Level gehorchen\n"
	.string "dir jedoch nicht!\p"
	.string "Zusätzlich kannst du außerhalb von\n"
	.string "Kämpfen STÄRKE einsetzen.$"

CeruleanCity_House1_Text_DefenseStatSurf_DE::
	.string "Die VERTEIDIGUNG deiner POKéMON\n"
	.string "wird verbessert.\p"
	.string "Ferner kannst du außerhalb von\n"
	.string "Kämpfen SURFER verwenden.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash_DE::
	.string "POKéMON bis Level 70 folgen deinen\n"
	.string "Befehlen.\p"
	.string "Das gilt auch für getauschte\n"
	.string "POKéMON!\p"
	.string "POKéMON höherer Level gehorchen\n"
	.string "dir jedoch nicht!\p"
	.string "Du kannst den ZERSCHMETTERER\n"
	.string "nun auch außerhalb eines Kampfes\l"
	.string "anwenden.$"

CeruleanCity_House1_Text_SpStatsWaterfall_DE::
	.string "Der SP. ANG.- und SP. VER.-Wert\n"
	.string "deiner POKéMON steigt geringfügig.\p"
	.string "Du kannst die Attacke KASKADE\n"
	.string "außerhalb eines Kampfes anwenden.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou_DE::
	.string "Jegliches POKéMON gehorcht dir!$"

