ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC_IT::
    .string "Si può usare il PC là nell'angolo.\p"
    .string "Me l'hanno detto al banco di\n"
    .string "accettazione, che gentili!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown_IT::
    .string "Troverai un CENTRO POKéMON in ogni\n"
    .string "città.\p"
    .string "I servizi che offrono sono tutti\n"
    .string "gratuiti!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons_IT::
    .string "I CENTRI POKéMON ricaricano i tuoi\n"
    .string "POKéMON stanchi, feriti o esausti!$"

