ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC_FR::
	.string "Tu peux utiliser le PC.\p"
	.string "C'est l'hôtesse qui me l'a dit!\n"
	.string "Elle est mignonne en plus!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown_FR::
	.string "Il y a un CENTRE POKéMON dans\n"
	.string "chaque grande ville.\p"
	.string "Tu peux y soigner gratuitement tes\n"
	.string "POKéMON!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons_FR::
	.string "Les CENTRES POKéMON soignent tous\n"
	.string "les POKéMON blessés ou KO!$"

