Route3_Text_TunnelFromCeruleanTiring_IT::
    .string "Uffa… Meglio riposarsi un po'!\n"
    .string "Che stanchezza!!!\p"
    .string "Questo tunnel per CELESTOPOLI è\n"
    .string "impegnativo!$"

Route3_Text_ColtonIntro_IT::
    .string "Ci siamo già visti al\n"
    .string "BOSCO SMERALDO!$"

Route3_Text_ColtonDefeat_IT::
    .string "Battuto ancora!$"

Route3_Text_ColtonPostBattle_IT::
    .string "Ci sono altre specie di POKéMON\n"
    .string "oltre a quelle che si trovano nel\l"
    .string "bosco!$"

Route3_Text_BenIntro_IT::
    .string "Ciao!\n"
    .string "Mi piacciono i pantaloncini corti!\p"
    .string "Sono molto comodi!$"

Route3_Text_BenDefeat_IT::
    .string "Non ci posso credere!$"

Route3_Text_BenPostBattle_IT::
    .string "Stai depositando i tuoi POKéMON nel\n"
    .string "PC?\p"
    .string "Ogni BOX può contenere 30\n"
    .string "POKéMON!$"

Route3_Text_JaniceIntro_IT::
    .string "Mi stavi guardando, vero?$"

Route3_Text_JaniceDefeat_IT::
    .string "Non brilli certo per la statura!$"

Route3_Text_JanicePostBattle_IT::
    .string "Smetti di fissarmi, se non vuoi\n"
    .string "guai!$"

Route3_Text_GregIntro_IT::
    .string "Sei un ALLENATORE?\n"
    .string "Lottiamo, forza!$"

Route3_Text_GregDefeat_IT::
    .string "Con altri POKéMON ti avrei\n"
    .string "battuto!$"

Route3_Text_GregPostBattle_IT::
    .string "Se un POKéMON BOX del PC è pieno,\n"
    .string "passa a un altro!$"

Route3_Text_SallyIntro_IT::
    .string "Quel tuo sguardo è così intrigante!$"

Route3_Text_SallyDefeat_IT::
    .string "Sii gentile!$"

Route3_Text_SallyPostBattle_IT::
    .string "Evita le lotte nascondendoti da\n"
    .string "certa gente!$"

Route3_Text_CalvinIntro_IT::
    .string "Ehi!\n"
    .string "Non indossi pantaloncini!$"

Route3_Text_CalvinDefeat_IT::
    .string "Ho perso!\n"
    .string "Perso! Perso!$"

Route3_Text_CalvinPostBattle_IT::
    .string "Porto sempre i pantaloncini, anche\n"
    .string "d'inverno!$"

Route3_Text_JamesIntro_IT::
    .string "Puoi lottare contro i miei nuovi\n"
    .string "POKéMON!$"

Route3_Text_JamesDefeat_IT::
    .string "Sono distrutto!$"

Route3_Text_JamesPostBattle_IT::
    .string "I POKéMON allenati sono più forti\n"
    .string "di quelli selvatici!$"

Route3_Text_RobinIntro_IT::
    .string "Ehi!\n"
    .string "Mi hai urtato?$"

Route3_Text_RobinDefeat_IT::
    .string "Tutto qui?$"

Route3_Text_RobinPostBattle_IT::
    .string "Il PERCORSO 4 è ai piedi del\n"
    .string "MONTE LUNA.$"

Route3_Text_RouteSign_IT::
    .string "PERCORSO 3 - Per il MONTE LUNA$"

