Route3_Text_TunnelFromCeruleanTiring_ES::
    .string "¡Uff!... Voy a descansar.\n"
    .string "Ufff...\p"
    .string "¡Ese túnel a CELESTE es agotador!$"

Route3_Text_ColtonIntro_ES::
    .string "¡Nos vimos en el BOSQUE VERDE!$"

Route3_Text_ColtonDefeat_ES::
    .string "¡Has ganado otra vez!$"

Route3_Text_ColtonPostBattle_ES::
    .string "¡Hay otros tipos de POKéMON\n"
    .string "diferentes a los del bosque!$"

Route3_Text_BenIntro_ES::
    .string "¡Hola!\n"
    .string "¡Me gustan los pantalones cortos!\p"
    .string "¡Son muy cómodos!$"

Route3_Text_BenDefeat_ES::
    .string "¡No me lo puedo creer!$"

Route3_Text_BenPostBattle_ES::
    .string "¿Estás guardando a tus POKéMON\n"
    .string "en el PC?\p"
    .string "¡Cada CAJA puede tener 30\n"
    .string "POKéMON!$"

Route3_Text_JaniceIntro_ES::
    .string "Estabas mirándome, ¿verdad?$"

Route3_Text_JaniceDefeat_ES::
    .string "¡Eres de lo que no hay!$"

Route3_Text_JanicePostBattle_ES::
    .string "¡Deja de mirarme si no quieres\n"
    .string "luchar!$"

Route3_Text_GregIntro_ES::
    .string "¿Entrenas POKéMON?\n"
    .string "¡Pues luchemos!$"

Route3_Text_GregDefeat_ES::
    .string "¡Con nuevos POKéMON te habría\n"
    .string "ganado!$"

Route3_Text_GregPostBattle_ES::
    .string "¡Si una CAJA de POKéMON del PC\n"
    .string "está llena, cambia a otra CAJA!$"

Route3_Text_SallyIntro_ES::
    .string "¡Esa mirada tuya fue de lo más\n"
    .string "misteriosa!$"

Route3_Text_SallyDefeat_ES::
    .string "¡Sé amable!$"

Route3_Text_SallyPostBattle_ES::
    .string "¡Para evitar luchar, procura que\n"
    .string "no te vean!$"

Route3_Text_CalvinIntro_ES::
    .string "¡Oye!\n"
    .string "¡No llevas pantalón corto!$"

Route3_Text_CalvinDefeat_ES::
    .string "¡He perdido!\n"
    .string "¡He perdido!$"

Route3_Text_CalvinPostBattle_ES::
    .string "Llevo pantalones cortos hasta\n"
    .string "en invierno.$"

Route3_Text_JamesIntro_ES::
    .string "¡Puedes luchar contra mis nuevos\n"
    .string "POKéMON!$"

Route3_Text_JamesDefeat_ES::
    .string "¡Estoy acabado!$"

Route3_Text_JamesPostBattle_ES::
    .string "¡Los POKéMON entrenados son más\n"
    .string "fuertes que los salvajes!$"

Route3_Text_RobinIntro_ES::
    .string "¡Oye!\n"
    .string "¿Por qué me has tocado?$"

Route3_Text_RobinDefeat_ES::
    .string "¿Eso es todo?$"

Route3_Text_RobinPostBattle_ES::
    .string "La RUTA 4 está debajo del MT.\n"
    .string "MOON.$"

Route3_Text_RouteSign_ES::
    .string "RUTA 3:\n"
    .string "HACIA EL MT. MOON$"
