Route3_Text_TunnelFromCeruleanTiring_DE::
	.string "Puh! Ich muss eine Pause machen!\p"
	.string "Der Weg durch den Tunnel aus\n"
	.string "AZURIA CITY ist sehr beschwerlich!$"

Route3_Text_ColtonIntro_DE::
	.string "Heh! Ich kenne dich aus dem\n"
	.string "VERTANIA-WALD!$"

Route3_Text_ColtonDefeat_DE::
	.string "Du hast mich wieder besiegt!$"

Route3_Text_ColtonPostBattle_DE::
	.string "Neben den POKéMON hier im Wald,\n"
	.string "gibt es noch Unmengen anderer\l"
	.string "POKéMON zu entdecken!$"

Route3_Text_BenIntro_DE::
	.string "Überall sind Brennnesseln! Und ich\n"
	.string "trage Shorts! So ein MIST!$"

Route3_Text_BenDefeat_DE::
	.string "Wäre ich heute doch nur daheim\n"
	.string "geblieben!$"

Route3_Text_BenPostBattle_DE::
	.string "Du kannst POKéMON via PC in Boxen\n"
	.string "ablegen.\p"
	.string "Jede BOX fasst 30 POKéMON!$"

Route3_Text_JaniceIntro_DE::
	.string "Was starrst du mich so an?$"

Route3_Text_JaniceDefeat_DE::
	.string "Du bist gefährlich!$"

Route3_Text_JanicePostBattle_DE::
	.string "Hör auf, Leute anzustarren!\n"
	.string "Dann musst du auch nicht kämpfen!$"

Route3_Text_GregIntro_DE::
	.string "Bist du auch ein TRAINER?\n"
	.string "Lass uns kämpfen!$"

Route3_Text_GregDefeat_DE::
	.string "Mit diesen POKéMON hätte ich auch\n"
	.string "leicht gewonnen!$"

Route3_Text_GregPostBattle_DE::
	.string "Wenn auf dem PC eine POKéMON-BOX\n"
	.string "voll ist, wechsle einfach zu einer\l"
	.string "anderen BOX!$"

Route3_Text_SallyIntro_DE::
	.string "Warum schaust du mich so fasziniert\n"
	.string "an?$"

Route3_Text_SallyDefeat_DE::
	.string "Bleib immer nett!$"

Route3_Text_SallyPostBattle_DE::
	.string "Vermeide Kämpfe, indem du anderen\n"
	.string "TRAINERn aus dem Weg gehst!$"

Route3_Text_CalvinIntro_DE::
	.string "Hehe! Ich habe meinem Bruder\n"
	.string "gesagt, er soll Shorts anziehen!$"

Route3_Text_CalvinDefeat_DE::
	.string "Nein!\n"
	.string "Verloren!$"

Route3_Text_CalvinPostBattle_DE::
	.string "Man sollte nicht alles machen, was\n"
	.string "der große Bruder verlangt! Hehe!$"

Route3_Text_JamesIntro_DE::
	.string "Meine neuen POKéMON wollen\n"
	.string "kämpfen!$"

Route3_Text_JamesDefeat_DE::
	.string "Du hast meine POKéMON besiegt!$"

Route3_Text_JamesPostBattle_DE::
	.string "Die POKéMON eines TRAINERs sind\n"
	.string "stärker als wildlebende!$"

Route3_Text_RobinIntro_DE::
	.string "Huch! Sollen das etwa\n"
	.string "Annäherungsversuche sein?$"

Route3_Text_RobinDefeat_DE::
	.string "Bleib mir fern!$"

Route3_Text_RobinPostBattle_DE::
	.string "Die ROUTE 4 liegt am Fuße des\n"
	.string "MONDBERGES.$"

Route3_Text_RouteSign_DE::
	.string "ROUTE 3\n"
	.string "ZUM MONDBERG$"

