SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn_IT::
    .string "I POKéMON hanno una loro\n"
    .string "personalità, come le persone.\p"
    .string "Il mio PIKACHU, per esempio,\n"
    .string "ha una natura LESTA.\p"
    .string "Quindi, crescendo, è diventato\n"
    .string "particolarmente veloce.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins_IT::
    .string "Bene, dopo i preparativi, posso\n"
    .string "andare ad esplorare le ROVINE.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland_IT::
    .string "Sono venuto a pescare\n"
    .string "a SETTIMISOLA.\p"
    .string "Così, avrò concluso il mio tour\n"
    .string "di pesca nel SETTIPELAGO.\p"
    .string "Prima però devo farmi una\n"
    .string "buona scorta di POKé BALL.$"

