SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn_FR::
	.string "Les POKéMON ont leur propre\n"
	.string "personnalité, comme les gens.\p"
	.string "Mon PIKACHU est PRESSE. C'est\n"
	.string "un POKéMON très rapide.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins_FR::
	.string "OK, je suis enfin prêt pour partir\n"
	.string "explorer les RUINES.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland_FR::
	.string "Il ne me reste plus qu'à aller\n"
	.string "pêcher sur l'ILE 7.\p"
	.string "Comme ça, je les aurai toutes\n"
	.string "explorées au moins une fois.\p"
	.string "Mais je devrais quand même\n"
	.string "mettre des POKé BALLS de côté.$"

