Text_DoubleEdgeTeach_DE::
	.string "Du kannst stolz auf dich sein, weil\n"
	.string "du dich so wacker auf der\l"
	.string "SIEGESSTRASSE geschlagen hast.\p"
	.string "Als Anerkennung deiner Leistung\n"
	.string "möchte ich einem deiner POKéMON\l"
	.string "RISIKOTACKLE beibringen.\p"
	.string "Soll ich einem POKéMON diese\n"
	.string "Attacke beibringen?$"

Text_DoubleEdgeDeclined_DE::
	.string "Ich bringe diese Attacke einem\n"
	.string "deiner POKéMON jederzeit bei.$"

Text_DoubleEdgeWhichMon_DE::
	.string "Welches POKéMON soll\n"
	.string "RISIKOTACKLE erlernen?$"

Text_DoubleEdgeTaught_DE::
	.string "Mach in der POKéMON LIGA so\n"
	.string "weiter!\p"
	.string "Überrumple sie und mach sie fertig!$"

VictoryRoad_3F_Text_GeorgeIntro_DE::
	.string "Man erzählt von einem Wunderkind!$"

VictoryRoad_3F_Text_GeorgeDefeat_DE::
	.string "Du bist das Wunderkind!$"

VictoryRoad_3F_Text_GeorgePostBattle_DE::
	.string "Hast du wirklich GIOVANNI vom TEAM\n"
	.string "ROCKET besiegt?$"

VictoryRoad_3F_Text_AlexaIntro_DE::
	.string "TRAINER sind geborene Kämpfer,\n"
	.string "immer auf der Suche nach starken\l"
	.string "Gegnern!$"

VictoryRoad_3F_Text_AlexaDefeat_DE::
	.string "Cool!\n"
	.string "Du bist wirklich stark!$"

VictoryRoad_3F_Text_AlexaPostBattle_DE::
	.string "Je härter die Kämpfe sind, desto\n"
	.string "stärker wirst du!$"

VictoryRoad_3F_Text_CarolineIntro_DE::
	.string "Gleich siehst du, wie gut du bist!$"

VictoryRoad_3F_Text_CarolineDefeat_DE::
	.string "Das darf doch nicht wahr sein!\n"
	.string "Grrr!$"

VictoryRoad_3F_Text_CarolinePostBattle_DE::
	.string "Du hast mich in die Schranken\n"
	.string "verwiesen!$"

VictoryRoad_3F_Text_ColbyIntro_DE::
	.string "Nur Auserwählte dürfen passieren!$"

VictoryRoad_3F_Text_ColbyDefeat_DE::
	.string "Ich fasse es nicht!$"

VictoryRoad_3F_Text_ColbyPostBattle_DE::
	.string "Die TRAINER hier sind auf dem Weg\n"
	.string "zur POKéMON LIGA! Sei vorsichtig!$"

VictoryRoad_3F_Text_RayIntro_DE::
	.string "TYRO: Unser beider Bestimmung\n"
	.string "ist etwas Großes zu erreichen!$"

VictoryRoad_3F_Text_RayDefeat_DE::
	.string "TYRO: Lächerlich! Es kann nicht\n"
	.string "sein, was nicht sein darf!$"

VictoryRoad_3F_Text_RayPostBattle_DE::
	.string "TYRO: Du hast uns besiegt! Großes\n"
	.string "ist nicht leicht zu vollbringen!$"

VictoryRoad_3F_Text_RayNotEnoughMons_DE::
	.string "TYRO: Zusammen streben wir beide\n"
	.string "nach dem Gipfel.\p"
	.string "Du musst zwei POKéMON gegen\n"
	.string "uns einsetzen!$"

VictoryRoad_3F_Text_TyraIntro_DE::
	.string "LORE: Wir versuchen, gemeinsam\n"
	.string "Champs zu werden!$"

VictoryRoad_3F_Text_TyraDefeat_DE::
	.string "LORE: Oh, aber…!$"

VictoryRoad_3F_Text_TyraPostBattle_DE::
	.string "LORE: Du hast mir gezeigt, dass\n"
	.string "Kraft grenzenlose Formen haben\l"
	.string "kann.$"

VictoryRoad_3F_Text_TyraNotEnoughMons_DE::
	.string "LORE: Mit nur einem POKéMON\n"
	.string "kannst du nicht gegen uns antreten!$"

