Text_DoubleEdgeTeach_IT::
    .string "Ottimo! Non è da tutti giungere\n"
    .string "fin qui lungo la VIA VITTORIA!\p"
    .string "Per festeggiare, ti regalo\n"
    .string "SDOPPIATORE!\p"
    .string "Vuoi che lo insegni ad uno dei\n"
    .string "tuoi POKéMON?$"

Text_DoubleEdgeDeclined_IT::
    .string "Come preferisci. Se cambi idea,\n"
    .string "mi trovi sempre qui.$"

Text_DoubleEdgeWhichMon_IT::
    .string "A quale POKéMON vuoi che insegni\n"
    .string "SDOPPIATORE?$"

Text_DoubleEdgeTaught_IT::
    .string "Continua così fino alla\n"
    .string "LEGA POKéMON!\p"
    .string "Stendili, mi raccomando!$"

VictoryRoad_3F_Text_GeorgeIntro_IT::
    .string "Ci sono voci che narrano di un\n"
    .string "giovane ALLENATORE\l"
    .string "prodigioso!$"

VictoryRoad_3F_Text_GeorgeDefeat_IT::
    .string "Le voci erano vere!$"

VictoryRoad_3F_Text_GeorgePostBattle_IT::
    .string "Hai battuto GIOVANNI di TEAM\n"
    .string "ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro_IT::
    .string "Gli ALLENATORI vivono per trovare\n"
    .string "sfidanti sempre più forti!$"

VictoryRoad_3F_Text_AlexaDefeat_IT::
    .string "Oh!\n"
    .string "Sei un portento!$"

VictoryRoad_3F_Text_AlexaPostBattle_IT::
    .string "Affrontando lotte sempre più dure,\n"
    .string "diventerai sempre più forte!$"

VictoryRoad_3F_Text_CarolineIntro_IT::
    .string "Ti mostrerò quanto poco\n"
    .string "vali!$"

VictoryRoad_3F_Text_CarolineDefeat_IT::
    .string "Sono furiosa!!!$"

VictoryRoad_3F_Text_CarolinePostBattle_IT::
    .string "Sei tu che mi hai mostrato quanto\n"
    .string "poco valgo!$"

VictoryRoad_3F_Text_ColbyIntro_IT::
    .string "Solo i prescelti possono passare!$"

VictoryRoad_3F_Text_ColbyDefeat_IT::
    .string "Non ci posso credere!$"

VictoryRoad_3F_Text_ColbyPostBattle_IT::
    .string "Tutti gli ALLENATORI che vedi qui\n"
    .string "sono diretti alla LEGA POKéMON!\p"
    .string "Sono forti! Fai attenzione!$"

VictoryRoad_3F_Text_RayIntro_IT::
    .string "RAY: Insieme, siamo destinati a\n"
    .string "fare grandi cose!$"

VictoryRoad_3F_Text_RayDefeat_IT::
    .string "RAY: Ma questo è ridicolo!$"

VictoryRoad_3F_Text_RayPostBattle_IT::
    .string "RAY: Ci hai battuti! Com'è\n"
    .string "difficile misurare la grandezza…$"

VictoryRoad_3F_Text_RayNotEnoughMons_IT::
    .string "RAY: Insieme, siamo destinati a\n"
    .string "fare grandi cose!\p"
    .string "Per lottare con noi devi avere\n"
    .string "almeno due POKéMON da\l"
    .string "mandare in campo!$"

VictoryRoad_3F_Text_TyraIntro_IT::
    .string "IVA: Io e il mio amico, insieme,\n"
    .string "diventeremo grandi campioni!$"

VictoryRoad_3F_Text_TyraDefeat_IT::
    .string "IVA: Ehi, ma…$"

VictoryRoad_3F_Text_TyraPostBattle_IT::
    .string "IVA: Tu mi hai insegnato che la\n"
    .string "potenza può avere infinite forme!$"

VictoryRoad_3F_Text_TyraNotEnoughMons_IT::
    .string "IVA: Se hai solo un POKéMON\n"
    .string "non puoi lottare con noi!$"

