Text_DoubleEdgeTeach_ES::
    .string "Has conseguido abrirte paso por\n"
    .string "la CALLE VICTORIA con mucho\l"
    .string "valor; es para alegrarse.\p"
    .string "Como reconocimiento a tu hazaña,\n"
    .string "te enseñaré DOBLE FILO.\p"
    .string "¿Quieres?$"

Text_DoubleEdgeDeclined_ES::
    .string "Bueno, otra vez será.$"

Text_DoubleEdgeWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe DOBLE FILO?$"

Text_DoubleEdgeTaught_ES::
    .string "¡No bajes la guardia para la LIGA\n"
    .string "POKéMON!\p"
    .string "¡A por ella, acaba con todos!$"

VictoryRoad_3F_Text_GeorgeIntro_ES::
    .string "¡Los rumores hablan de un\n"
    .string "ENTRENADOR espectacular!$"

VictoryRoad_3F_Text_GeorgeDefeat_ES::
    .string "¡Los rumores eran ciertos!$"

VictoryRoad_3F_Text_GeorgePostBattle_ES::
    .string "¿Derrotaste a GIOVANNI\n"
    .string "del TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro_ES::
    .string "¡Los ENTRENADORES sólo viven para\n"
    .string "buscar enemigos más fuertes!$"

VictoryRoad_3F_Text_AlexaDefeat_ES::
    .string "¡Oooooh!\n"
    .string "¡Eres tan fuerte!$"

VictoryRoad_3F_Text_AlexaPostBattle_ES::
    .string "¡Librar duros combates te hará\n"
    .string "más fuerte!$"

VictoryRoad_3F_Text_CarolineIntro_ES::
    .string "¡Te demostraré lo fuerte que eres\n"
    .string "de verdad!$"

VictoryRoad_3F_Text_CarolineDefeat_ES::
    .string "¡Argh! ¡Eres increíble!$"

VictoryRoad_3F_Text_CarolinePostBattle_ES::
    .string "¡Yo soy la que ha aprendido\n"
    .string "la lección!$"

VictoryRoad_3F_Text_ColbyIntro_ES::
    .string "¡Aquí sólo pueden pasar\n"
    .string "los elegidos!$"

VictoryRoad_3F_Text_ColbyDefeat_ES::
    .string "¡No me lo puedo creer!$"

VictoryRoad_3F_Text_ColbyPostBattle_ES::
    .string "¡Todos estos ENTRENADORES van a\n"
    .string "participar en la LIGA POKéMON!\p"
    .string "¡Ten cuidado!$"

VictoryRoad_3F_Text_RayIntro_ES::
    .string "DESI: ¡Juntos lucharemos contra\n"
    .string "quien sea!$"

VictoryRoad_3F_Text_RayDefeat_ES::
    .string "DESI: ¡No me lo puedo creer!$"

VictoryRoad_3F_Text_RayPostBattle_ES::
    .string "DESI: ¡Has acabado con nosotros!$"

VictoryRoad_3F_Text_RayNotEnoughMons_ES::
    .string "DESI: Acabaríamos contigo\n"
    .string "en un abrir y cerrar de ojos.\p"
    .string "Para luchar con nosotros, hay\n"
    .string "que tener dos POKéMON.$"

VictoryRoad_3F_Text_TyraIntro_ES::
    .string "TULA: ¡Tenemos intención de\n"
    .string "convertirnos en campeones!$"

VictoryRoad_3F_Text_TyraDefeat_ES::
    .string "TULA: Eh..., en fin...$"

VictoryRoad_3F_Text_TyraPostBattle_ES::
    .string "TULA: De ti he aprendido la\n"
    .string "verdadera dimensión de la fuerza.$"

VictoryRoad_3F_Text_TyraNotEnoughMons_ES::
    .string "TULA: No podrás con nosotros\n"
    .string "si no tienes dos POKéMON.$"
