FiveIsland_Text_IslandSign_DE::
	.string "EILAND FÜNF\n"
	.string "Chrono-Insel: Wo die Zeit rennt$"

FiveIsland_Text_WeirdBuildingInMeadow_DE::
	.string "Igitt, das stinkt! Ich wollte auf\n"
	.string "der WEIDE spielen.\p"
	.string "Aber sie haben dort ein merk-\n"
	.string "würdiges Gebäude errichtet und\l"
	.string "ich kann dort nicht spielen.$"

FiveIsland_Text_BeenGettingBusierAroundHere_DE::
	.string "Hier wurde es in letzter Zeit\n"
	.string "geschäftiger.\p"
	.string "Ich habe auch in letzter Zeit\n"
	.string "nicht viele gute Fische gefangen.$"

