FiveIsland_Text_IslandSign_IT::
    .string "QUINTISOLA\n"
    .string "L'isola del tempo che passa$"

FiveIsland_Text_WeirdBuildingInMeadow_IT::
    .string "Ehi, non vale! Qualcuno ha avuto\n"
    .string "la brillante idea di costruire un\l"
    .string "palazzo in mezzo al PRATO!\p"
    .string "Così, non posso più andarci a\n"
    .string "giocare!$"

FiveIsland_Text_BeenGettingBusierAroundHere_IT::
    .string "Com'è che ci sono sempre più\n"
    .string "pescatori e sempre meno pesci\l"
    .string "da queste parti?!$"

