ViridianForest_Text_FriendsItchingToBattle_DE::
	.string "Meine Freunde und ich wollten hier\n"
	.string "KÄFER-POKéMON fangen…\p"
	.string "Unsere POKéMON wollen kämpfen!!!$"

ViridianForest_Text_RickIntro_DE::
	.string "Heh! Du hast auch POKéMON! Los!\n"
	.string "Lass uns kämpfen!$"

ViridianForest_Text_RickDefeat_DE::
	.string "Ah!\n"
	.string "RAUPY hat es nicht geschafft!$"

ViridianForest_Text_RickPostBattle_DE::
	.string "Psst! Sei leise!\n"
	.string "Du verjagst alle Käfer...$"

ViridianForest_Text_DougIntro_DE::
	.string "Heh!\n"
	.string "Ein POKéMON TRAINER stiehlt sich\l"
	.string "nicht so einfach davon!!!$"

ViridianForest_Text_DougDefeat_DE::
	.string "Oh! Ich habe kein kampfbereites\n"
	.string "POKéMON mehr!$"

ViridianForest_Text_DougPostBattle_DE::
	.string "So ein Mist! Ich muss ein paar\n"
	.string "Stärkere fangen!$"

ViridianForest_Text_SammyIntro_DE::
	.string "Heh, warte!\n"
	.string "Warum die Eile?$"

ViridianForest_Text_SammyDefeat_DE::
	.string "Uff!\n"
	.string "Du bist zu gut! Ich gebe auf!$"

ViridianForest_Text_SammyPostBattle_DE::
	.string "Mit ein bisschen Glück findet man\n"
	.string "unterwegs Items!\p"
	.string "Ich muss hier irgendwo etwas\n"
	.string "verloren haben...$"

ViridianForest_Text_AnthonyIntro_DE::
	.string "Ich bin zwar klein, aber ich will\n"
	.string "nicht, dass du mich deswegen\l"
	.string "gewinnen lässt!$"

ViridianForest_Text_AnthonyDefeat_DE::
	.string "Oh, nein! Alles ist schief\n"
	.string "gegangen!$"

ViridianForest_Text_AnthonyPostBattle_DE::
	.string "Ich habe meinen Kredit\n"
	.string "verspielt…$"

ViridianForest_Text_CharlieIntro_DE::
	.string "Weißt du, dass POKéMON sich\n"
	.string "entwickeln?$"

ViridianForest_Text_CharlieDefeat_DE::
	.string "Oh!\n"
	.string "Ich hab verloren!$"

ViridianForest_Text_CharliePostBattle_DE::
	.string "KÄFER-POKéMON entwickeln sich\n"
	.string "schnell. Sie sind einfach toll!$"

ViridianForest_Text_RanOutOfPokeBalls_DE::
	.string "Verdammt! Mir sind die POKéBÄLLE\n"
	.string "ausgegangen! Wie fange ich nun\l"
	.string "bloß POKéMON?\p"
	.string "Du solltest immer genug POKéBÄLLE\n"
	.string "bei dir haben!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Wenn du Kämpfe meiden möchtest,\n"
	.string "bleibe hohem Gras fern!$"

ViridianForest_Text_UseAntidoteForPoison_DE::
	.string "Bei Vergiftungen hat sich das\n"
	.string "GEGENGIFT aus dem POKéMON-\l"
	.string "SUPERMARKT bewährt.$"

ViridianForest_Text_ContactOakViaPCToRatePokedex_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Du kannst deinen POKéDEX jederzeit\n"
	.string "von PROF. EICH via PC bewerten\l"
	.string "lassen!$"

ViridianForest_Text_CantCatchOwnedMons_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Es ist verboten, anderen TRAINERn\n"
	.string "POKéMON zu stehlen! Fang nur wilde\l"
	.string "POKéMON!$"

ViridianForest_Text_WeakenMonsBeforeCapture_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Geschwächte POKéMON sind leichter\n"
	.string "zu fangen!\p"
	.string "Sind sie bei Kräften, könnten sie\n"
	.string "fliehen!$"

ViridianForest_Text_LeavingViridianForest_DE::
	.string "AUF WIEDERSEHEN IM VERTANIA-WALD\n"
	.string "DER NÄCHSTE ORT IST MARMORIA\l"
	.string "CITY.$"

