ViridianForest_Text_FriendsItchingToBattle_ES::
    .string "¡Vine aquí con unos amigos!\p"
    .string "¡Van en busca de combates\n"
    .string "POKéMON!$"

ViridianForest_Text_RickIntro_ES::
    .string "¡Eh! ¡Tienes POKéMON!\n"
    .string "¡Sí!\l"
    .string "¡Al ataque!$"

ViridianForest_Text_RickDefeat_ES::
    .string "¡No!\n¡Mi CATERPIE no pudo más!$"

ViridianForest_Text_RickPostBattle_ES::
    .string "¡Ssh!\n"
    .string "¡Vas a espantar a los bichos!...$"

ViridianForest_Text_DougIntro_ES::
    .string "¡Eh!\n"
    .string "¡Hay que tener disciplina para ser\l"
    .string "ENTRENADOR POKéMON!$"

ViridianForest_Text_DougDefeat_ES::
    .string "¿Será posible?\n"
    .string "¡No me quedan más POKéMON!$"

ViridianForest_Text_DougPostBattle_ES::
    .string "¡Vaya!\n"
    .string "¡Voy a atrapar unos más fuertes!$"

ViridianForest_Text_SammyIntro_ES::
    .string "¡Eh, espera!\n"
    .string "¿Por qué tienes tanta prisa?$"

ViridianForest_Text_SammyDefeat_ES::
    .string "¡Me rindo!\n"
    .string "¡Eres demasiado fuerte!$"

ViridianForest_Text_SammyPostBattle_ES::
    .string "¡A veces puedes encontrar cosas\n"
    .string "en el suelo!\p"
    .string "¡Estoy buscando los objetos\n"
    .string "que se me cayeron!$"

ViridianForest_Text_AnthonyIntro_ES::
    .string "No soy especialmente grande, ¡pero\n"
    .string "tampoco soy ningún enclenque!$"

ViridianForest_Text_AnthonyDefeat_ES::
    .string "Vaya, pues se ve que tampoco\n"
    .string "soy demasiado fuerte...$"

ViridianForest_Text_AnthonyPostBattle_ES::
    .string "Así no hay forma de ahorrar...$"

ViridianForest_Text_CharlieIntro_ES::
    .string "¿Sabes que los POKéMON\n"
    .string "evolucionan?$"

ViridianForest_Text_CharlieDefeat_ES::
    .string "¡Oh! ¡He perdido!$"

ViridianForest_Text_CharliePostBattle_ES::
    .string "Los POKéMON evolucionan\n"
    .string "muy rápido. ¡Son geniales!$"

ViridianForest_Text_RanOutOfPokeBalls_ES::
    .string "¡Me quedé sin POKé BALLS con\n"
    .string "las que atrapar a los POKéMON!\p"
    .string "¡Deberías llevar algunas extra!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "Si quieres evitar los combates,\n"
    .string "¡aléjate de las zonas de hierba!$"

ViridianForest_Text_UseAntidoteForPoison_ES::
    .string "¡Usa ANTÍDOTO contra el veneno!\n"
    .string "¡Lo conseguirás en las TIENDAS\l"
    .string "POKéMON!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Para evaluar tu POKéDEX, llama\n"
    .string "al PROF. OAK vía PC!$"

ViridianForest_Text_CantCatchOwnedMons_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡No robes los POKéMON de otros\n"
    .string "ENTRENADORES!\p"
    .string "¡Captura sólo POKéMON salvajes\n"
    .string "con las POKé BALLS!$"

ViridianForest_Text_WeakenMonsBeforeCapture_ES::
    .string "PISTAS ENTRENADOR\p¡Debilita a los POKéMON antes\n"
    .string "de intentar capturarlos!\p"
    .string "¡Si están fuertes, podrían escapar!$"

ViridianForest_Text_LeavingViridianForest_ES::
    .string "SALIENDO DEL BOSQUE VERDE,\n"
    .string "SE ENCUENTRA CIUDAD PLATEADA$"
