ViridianForest_Text_FriendsItchingToBattle_FR::
	.string "Je suis venu avec des amis pour\n"
	.string "attraper des POKéMON INSECTE!\p"
	.string "Ils sont tous ici pour faire des\n"
	.string "combats de POKéMON!$"

ViridianForest_Text_RickIntro_FR::
	.string "Hé! Mais tu as des POKéMON!\n"
	.string "Yah! A l'attaque!$"

ViridianForest_Text_RickDefeat_FR::
	.string "NON!\n"
	.string "CHENIPAN n'est pas assez fort!$"

ViridianForest_Text_RickPostBattle_FR::
	.string "Chut!\n"
	.string "Tu fais peur aux insectes…$"

ViridianForest_Text_DougIntro_FR::
	.string "Haha!\n"
	.string "Un DRESSEUR de POKéMON,\l"
	.string "un vrai, ne se débine jamais!!!$"

ViridianForest_Text_DougDefeat_FR::
	.string "Oups!\n"
	.string "J'ai plus de POKéMON, moi!$"

ViridianForest_Text_DougPostBattle_FR::
	.string "Ça craint complètement.\n"
	.string "J'vais en choper des plus balèzes!$"

ViridianForest_Text_SammyIntro_FR::
	.string "Hop, hop! Minute!\n"
	.string "On est pas pressés!$"

ViridianForest_Text_SammyDefeat_FR::
	.string "Houlà!\n"
	.string "J'abandonne! T'es trop fort!$"

ViridianForest_Text_SammyPostBattle_FR::
	.string "Tu trouveras peut-être des objets\n"
	.string "par terre!\p"
	.string "Je cherche les objets que j'ai\n"
	.string "laissés tomber…$"

ViridianForest_Text_AnthonyIntro_FR::
	.string "Je suis peut-être petit, mais faut\n"
	.string "pas me sous-estimer.$"

ViridianForest_Text_AnthonyDefeat_FR::
	.string "Oh bah non.\n"
	.string "Tout va de travers.$"

ViridianForest_Text_AnthonyPostBattle_FR::
	.string "J'oublierai pas cette défaite.$"

ViridianForest_Text_CharlieIntro_FR::
	.string "Tu sais que les POKéMON\n"
	.string "peuvent évoluer?$"

ViridianForest_Text_CharlieDefeat_FR::
	.string "Oh!\n"
	.string "Perdu!$"

ViridianForest_Text_CharliePostBattle_FR::
	.string "Les POKéMON INSECTE évoluent\n"
	.string "vite. Je les adore!$"

ViridianForest_Text_RanOutOfPokeBalls_FR::
	.string "J'suis à court de POKé BALL! Je ne\n"
	.string "peux plus attraper de POKéMON!\p"
	.string "Il faut toujours en avoir un max!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak_FR::
	.string "ASTUCE\p"
	.string "Pour éviter les combats, ne\n"
	.string "marchez pas dans les hautes\l"
	.string "herbes!$"

ViridianForest_Text_UseAntidoteForPoison_FR::
	.string "L'ANTIDOTE vendu dans les\n"
	.string "BOUTIQUES POKéMON guérit du\l"
	.string "poison.$"

ViridianForest_Text_ContactOakViaPCToRatePokedex_FR::
	.string "ASTUCE\p"
	.string "Pour évaluer votre POKéDEX,\n"
	.string "appelez le PROF. CHEN via un PC!$"

ViridianForest_Text_CantCatchOwnedMons_FR::
	.string "ASTUCE\p"
	.string "Interdiction de capturer les\n"
	.string "POKéMON d'un autre DRESSEUR!\p"
	.string "La capture se fait à l'état\n"
	.string "sauvage!$"

ViridianForest_Text_WeakenMonsBeforeCapture_FR::
	.string "ASTUCE\p"
	.string "Un POKéMON blessé se capture\n"
	.string "plus facilement!\p"
	.string "En pleine forme, il peut s'enfuir!$"

ViridianForest_Text_LeavingViridianForest_FR::
	.string "VOUS QUITTEZ LA FORET DE JADE.\n"
	.string "VOUS ALLEZ VERS ARGENTA.$"

