ViridianForest_Text_FriendsItchingToBattle_IT::
    .string "Sono qui con alcuni amici!\p"
    .string "Stiamo catturando POKéMON di\n"
    .string "tipo COLEOTTERO, per lottare!$"

ViridianForest_Text_RickIntro_IT::
    .string "Ehi! Anche tu hai dei POKéMON!\n"
    .string "Dai!\l"
    .string "Lottiamo!$"

ViridianForest_Text_RickDefeat_IT::
    .string "Noo!\n"
    .string "CATERPIE non può perdere!$"

ViridianForest_Text_RickPostBattle_IT::
    .string "Ssh! Piano, o fai scappare tutti\n"
    .string "gli insetti!$"

ViridianForest_Text_DougIntro_IT::
    .string "Ehi!\n"
    .string "Un ALLENATORE di POKéMON non può\l"
    .string "svignarsela!$"

ViridianForest_Text_DougDefeat_IT::
    .string "Non ho più POKéMON per lottare!$"

ViridianForest_Text_DougPostBattle_IT::
    .string "Maledizione!\n"
    .string "Devo catturarne di più forti!$"

ViridianForest_Text_SammyIntro_IT::
    .string "Ehi, aspetta!\n"
    .string "Cos'è questa fretta?$"

ViridianForest_Text_SammyDefeat_IT::
    .string "Mi arrendo!\n"
    .string "Sei proprio forte!$"

ViridianForest_Text_SammyPostBattle_IT::
    .string "Qualche volta si trovano delle\n"
    .string "cose per terra!\p"
    .string "Sto cercando ciò che ho perso!\n"
    .string "Mi aiuti?$"

ViridianForest_Text_AnthonyIntro_IT::
    .string "Sono piccolino, ma ti consiglio di\n"
    .string "non sottovalutarmi.$"

ViridianForest_Text_AnthonyDefeat_IT::
    .string "Oh no! Mi sono andate tutte storte!$"

ViridianForest_Text_AnthonyPostBattle_IT::
    .string "Ho anche perso un po' di soldi…$"

ViridianForest_Text_CharlieIntro_IT::
    .string "Lo sapevi che i POKéMON si\n"
    .string "evolvono?$"

ViridianForest_Text_CharlieDefeat_IT::
    .string "Oh!\n"
    .string "Ho perso!$"

ViridianForest_Text_CharliePostBattle_IT::
    .string "I POKéMON di tipo COLEOTTERO si\n"
    .string "evolvono facilmente. Comodo, no?$"

ViridianForest_Text_RanOutOfPokeBalls_IT::
    .string "Accidenti! Non ho più POKé BALL\n"
    .string "per prendere POKéMON!\p"
    .string "Dovresti averne sempre alcune di\n"
    .string "scorta!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak_IT::
    .string "CONSIGLI UTILI\p"
    .string "Se non vuoi lottare, evita\n"
    .string "l'erba alta!$"

ViridianForest_Text_UseAntidoteForPoison_IT::
    .string "Usa l'ANTIDOTO contro il veleno!\n"
    .string "Lo troverai ai POKéMON-MARKET!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex_IT::
    .string "CONSIGLI UTILI\p"
    .string "Contatta il PROF. OAK via PC per\n"
    .string "avere la valutazione del tuo\l"
    .string "POKéDEX!$"

ViridianForest_Text_CantCatchOwnedMons_IT::
    .string "CONSIGLI UTILI\p"
    .string "Non puoi rubare i POKéMON di\n"
    .string "altri ALLENATORI.\p"
    .string "Solo i POKéMON selvatici possono\n"
    .string "essere catturati!$"

ViridianForest_Text_WeakenMonsBeforeCapture_IT::
    .string "CONSIGLI UTILI\p"
    .string "Indebolisci i POKéMON prima di\n"
    .string "tentare di catturarli!\p"
    .string "Se ancora forti, scappano!$"

ViridianForest_Text_LeavingViridianForest_IT::
    .string "ARRIVEDERCI NEL BOSCO SMERALDO\n"
    .string "PROSSIMA CITTÀ PLUMBEOPOLI$"

