SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles_IT::
    .string "A vedermi così non si direbbe, ma…\p"
    .string "…da giovane, ho viaggiato ovunque,\n"
    .string "sfidando tutti gli ALLENATORI che\l"
    .string "incontravo.\p"
    .string "Ora, il mio unico passatempo è\n"
    .string "pensare a quel passato glorioso,\l"
    .string "osservando le lotte tra i POKéMON.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox_IT::
    .string "Intorno alla scatola soffia una\n"
    .string "brezza leggera.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer_IT::
    .string "Ah, ciao!\p"
    .string "Ho una cosa da dirti. Al piano\n"
    .string "inferiore c'è una porta segreta.\p"
    .string "Dietro quella porta ti attende\n"
    .string "un ALLENATORE di nome {STR_VAR_1}.\p"
    .string "Sei qui per sfidare {STR_VAR_1},\n"
    .string "giusto?$"

SevenIsland_House_Room1_Text_OhYouWontBattle_IT::
    .string "Ah, non vuoi combattere…\p"
    .string "Beh, se cambi idea, sai dove\n"
    .string "trovarmi.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide_IT::
    .string "Ah!\n"
    .string "Allora lotterai per me?\p"
    .string "Quindi spostare in giro quella\n"
    .string "scatola non è stata una perdita di\l"
    .string "tempo!\p"
    .string "C'è un altro problema, però.\p"
    .string "Le pareti della stanza segreta non\n"
    .string "sono molto solide.\p"
    .string "Posso chiederti di limitarti a lotte\n"
    .string "con tre POKéMON per parte?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle_IT::
    .string "Bene!\n"
    .string "Prima di lottare, vuoi salvare il\l"
    .string "gioco?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack_IT::
    .string "Ottimo!\n"
    .string "Metticela tutta, mi raccomando!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1_IT::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw_IT::
    .string "L'incontro è finito in parità.$"

SevenIsland_House_Room1_Text_DrawWasIt_IT::
    .string "Avete pareggiato?\p"
    .string "Beh, è stato comunque un grande\n"
    .string "spettacolo.\p"
    .string "Una lotta vera, sentita.$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2_IT::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle_IT::
    .string "Grande! Eccezionale!\p"
    .string "Una lotta davvero emozionante!\p"
    .string "Così emozionante che ho le lacrime\n"
    .string "agli occhi, pensa un po'!\p"
    .string "Che uso sapiente e misurato delle\n"
    .string "mosse!\p"
    .string "Uno scontro titanico, uno\n"
    .string "spettacolo di pura potenza!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3_IT::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment_IT::
    .string "Che peccato!\p"
    .string "Le sconfitte bruciano, lo so!\p"
    .string "Ora però, devi prendere questa\n"
    .string "delusione come uno stimolo per\l"
    .string "crescere e migliorarti.\p"
    .string "Raddoppiando l'allenamento potrai\n"
    .string "dimenticare questa sconfitta e\l"
    .string "preparare la rivincita!$"

