SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles_ES::
    .string "Ahora no lo aparento, pero cuando\n"
    .string "era más joven...\p"
    .string "Iba volando de aquí para allá,\n"
    .string "desafiando a los ENTRENADORES\l"
    .string "con los que me encontraba.\p"
    .string "Ahora, me conformo recordando\n"
    .string "viejos tiempos y viendo combates.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox_ES::
    .string "Alrededor de la caja hay\n"
    .string "corriente...$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer_ES::
    .string "¡Hola!\n"
    .string "¿Qué tal?\p"
    .string "¿Sabes una cosa? En el sótano\n"
    .string "hay una sala secreta.\p"
    .string "Y te está esperando {STR_VAR_1}.\p"
    .string "Tú querías luchar con {STR_VAR_1},\n"
    .string "¿no?$"

SevenIsland_House_Room1_Text_OhYouWontBattle_ES::
    .string "Oh...\n"
    .string "No vas a luchar...\p"
    .string "Vale, vale...\p"
    .string "Bueno, vuelve si cambias\n"
    .string "de opinión.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide_ES::
    .string "¡Hola!\n"
    .string "¿Vas a luchar por mí?\p"
    .string "Entonces ha merecido la pena\n"
    .string "mover la caja.\p"
    .string "Pero... hay un pequeño\n"
    .string "problema.\p"
    .string "La construcción de esta sala\n"
    .string "deja un poco que desear.\p"
    .string "¿Te parece que sólo participen\n"
    .string "tres POKéMON por cada lado?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle_ES::
    .string "¡Bien! ¿Quieres guardar la partida\n"
    .string "antes de luchar?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack_ES::
    .string "¡Muy bien!\n"
    .string "¡Pues a por todas!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1_ES::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw_ES::
    .string "El combate ha acabado en empate.$"

SevenIsland_House_Room1_Text_DrawWasIt_ES::
    .string "¿Habéis empatado?\p"
    .string "Con todo, ha sido un espectáculo\n"
    .string "apasionante.\p"
    .string "¿Qué digo?\n"
    .string "¡Apasionante y con mucha miga!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2_ES::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle_ES::
    .string "¡Bravo!\p"
    .string "¡Bravo, bravísimo!\n"
    .string "¡Qué combate, señores!\p"
    .string "¡Me he emocionado y todo!\p"
    .string "¡Qué manera de usar las técnicas,\n"
    .string "con qué seguridad y destreza!\p"
    .string "¡Qué pulso!\n"
    .string "¡Fuerza contra fuerza!\p"
    .string "¡Sí, señor!\n"
    .string "¡Magnífico, colosal, apoteósico!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3_ES::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment_ES::
    .string "Vaya...\n"
    .string "Sé que estás triste...\p"
    .string "Pero no te desanimes, esa tristeza\n"
    .string "te hará más fuerte.\p"
    .string "Úsala, aprende de ella, ¡apóyate\n"
    .string "en ella para seguir adelante!\p"
    .string "¡No te olvides de esta derrota\n"
    .string "y entrénate el doble!$"
