SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles_DE::
	.string "Ich stelle momentan nichts mehr\n"
	.string "dar, aber als ich jünger war…\p"
	.string "Ich bin überall hingeflogen und\n"
	.string "habe jeden TRAINER heraus-\l"
	.string "gefordert.\l"
	.string "Jetzt besteht meine einzige\l"
	.string "Lebensfreude darin, mich an\l"
	.string "die Vergangenheit zu erinnern\l"
	.string "und Kämpfe zu beobachten.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox_DE::
	.string "Es weht ein laues Lüftchen!$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer_DE::
	.string "Ah!\n"
	.string "Willkommen mein Freund!\p"
	.string "Ich will dir etwas erzählen. Im\n"
	.string "Keller gibt es ein geheimes\l"
	.string "Zimmer.\l"
	.string "Ein TRAINER namens {STR_VAR_1}\l"
	.string "wartet dort.\p"
	.string "Du bist bestimmt gekommen, um\n"
	.string "{STR_VAR_1} herauszufordern, oder?$"

SevenIsland_House_Room1_Text_OhYouWontBattle_DE::
	.string "Oh…\n"
	.string "Du willst nicht kämpfen…\p"
	.string "Ich verstehe!\n"
	.string "……\p"
	.string "Wenn du deine Meinung änderst,\n"
	.string "kannst du gerne wiederkommen!$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide_DE::
	.string "Ah!\n"
	.string "Du willst also kämpfen?\p"
	.string "Dann hat es sich gelohnt, die\n"
	.string "Box aus dem Weg zu räumen.\p"
	.string "……\n"
	.string "Aber es gibt ein kleines Problem.\p"
	.string "Dieses geheime Zimmer ist nicht\n"
	.string "sehr stabil gebaut.\p"
	.string "Können wir uns auf den Einsatz\n"
	.string "von maximal drei POKéMON\l"
	.string "beschränken?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle_DE::
	.string "Schön! Möchtest du dein Spiel\n"
	.string "vor dem Kampf sichern?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack_DE::
	.string "Sehr gut!\n"
	.string "Nimm keine Rücksicht!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1_DE::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw_DE::
	.string "Der Kampf endet unentschieden.$"

SevenIsland_House_Room1_Text_DrawWasIt_DE::
	.string "Unentschieden?!?\n"
	.string "Dieses Spektakel hat sich\l"
	.string "dennoch gelohnt.\p"
	.string "Ich würde sagen, dass es ein\n"
	.string "wundervoller Kampf mit\l"
	.string "Tiefgang war!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2_DE::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle_DE::
	.string "Bravo!\p"
	.string "Wirklich super!\n"
	.string "Was für ein faszinierender Kampf!\p"
	.string "Er war so faszinierend, dass mir\n"
	.string "jetzt noch die Tränen in den Augen\l"
	.string "stehen!\l"
	.string "Die perfekte Verschmelzung von\l"
	.string "Angriff und Verteidigung!\p"
	.string "Das Aufeinandertreffen von\n"
	.string "kongenialen Kräften!\p"
	.string "Ja!\n"
	.string "Es war schlicht bombastisch!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3_DE::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment_DE::
	.string "Zu schade!\n"
	.string "Ich spüre deine Enttäuschung!\p"
	.string "Du wirst aus dieser Enttäuschung\n"
	.string "lernen und stärker werden.\p"
	.string "Lerne daraus und ziehe aus ihr\n"
	.string "deine Motivation, um nach\l"
	.string "Großem zu streben.\l"
	.string "Verdränge diese Niederlage und\l"
	.string "Enttäuschung nicht, sondern\l"
	.string "verdopple dein Training.$"

