FiveIsland_House1_JPText_HusbandWentOffFishing_ES::
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing_ES::
    .string "Que no comprara nada de cena hoy,\n"
    .string "que no me preocupara.\p"
    .string "Eso fue lo que me dijo mi marido\n"
    .string "al irse a pescar esta mañana.\p"
    .string "No sé yo si me puedo fiar mucho\n"
    .string "teniendo en cuenta la hora\l"
    .string "que es...$"
