FiveIsland_House1_JPText_HusbandWentOffFishing_DE::
	.string "こんばんの　おかずは\n"
	.string "ようい　しなくて　いいぞ！\p"
	.string "って　だんなが\n"
	.string "つりに　いったん　だけど‥\l"
	.string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing_DE::
	.string "Du brauchst für das Abendessen\n"
	.string "heute nichts einkaufen!\p"
	.string "… das hat mein Gatte gesagt,\n"
	.string "als er heute zum Angeln ging.\p"
	.string "Ich weiß nicht, ob ich mich auf\n"
	.string "seine große Ankündigung\l"
	.string "verlassen kann.$"

