MtMoon_B2F_Text_MiguelIntro_ES::
    .string "¡No toques nada!\p"
    .string "¡Yo encontré estos fósiles!\n"
    .string "¡Son míos!$"

MtMoon_B2F_Text_MiguelDefeat_ES::
    .string "¡De acuerdo!\n"
    .string "¡Los compartiré!$"

MtMoon_B2F_Text_WellEachTakeAFossil_ES::
    .string "¡Uno para cada!\n"
    .string "¡No hay que ser avaricioso!$"

MtMoon_B2F_Text_ThenThisFossilIsMine_ES::
    .string "Muy bien.\n"
    .string "¡Pues éste es el mío!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils_ES::
    .string "Muy lejos, en ISLA CANELA, hay\n"
    .string "un LABORATORIO de POKéMON.\p"
    .string "En él estudian cómo regenerar\n"
    .string "los fósiles de POKéMON.$"

MtMoon_B2F_Text_Grunt1Intro_ES::
    .string "El TEAM ROCKET encontrará\n"
    .string "los fósiles, los revivirá ¡y los\l"
    .string "venderá!$"

MtMoon_B2F_Text_Grunt1Defeat_ES::
    .string "¡Argh!\n"
    .string "¡Eres lo peor!$"

MtMoon_B2F_Text_Grunt1PostBattle_ES::
    .string "¡Eres un fastidio! ¡El TEAM ROCKET\n"
    .string "te pondrá en la lista negra!$"

MtMoon_B2F_Text_Grunt2Intro_ES::
    .string "¡Nosotros, el TEAM ROCKET,\n"
    .string "somos los bandidos POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat_ES::
    .string "¡Lo he hecho fatal!$"

MtMoon_B2F_Text_Grunt2PostBattle_ES::
    .string "¿Será posible?\n"
    .string "¡Mis compañeros me vengarán!$"

MtMoon_B2F_Text_Grunt3Intro_ES::
    .string "¡Nuestro trabajo aquí es muy\n"
    .string "importante! ¡Lárgate, enclenque!$"

MtMoon_B2F_Text_Grunt3Defeat_ES::
    .string "Pues eres muy fuerte...$"

MtMoon_B2F_Text_Grunt3PostBattle_ES::
    .string "Si encuentras un fósil, ¡dámelo\n"
    .string "y lárgate!$"

MtMoon_B2F_Text_Grunt4Intro_ES::
    .string "¡Los niños no deberían molestar\n"
    .string "a los adultos!$"

MtMoon_B2F_Text_Grunt4Defeat_ES::
    .string "¡Estoy muy enfadado!$"

MtMoon_B2F_Text_Grunt4PostBattle_ES::
    .string "Los POKéMON vivían aquí mucho\n"
    .string "antes de que llegara la gente.$"

MtMoon_B2F_Text_YouWantDomeFossil_ES::
    .string "¿Quieres el FÓSIL DOMO?$"

MtMoon_B2F_Text_YouWantHelixFossil_ES::
    .string "¿Quieres el FÓSIL HELIX?$"

MtMoon_B2F_Text_ObtainedHelixFossil_ES::
    .string "¡Obtuviste el FÓSIL HELIX!$"

MtMoon_B2F_Text_ObtainedDomeFossil_ES::
    .string "¡Obtuviste el FÓSIL DOMO!$"
