MtMoon_B2F_Text_MiguelIntro_IT::
    .string "Ehi! Giù le zampe!\p"
    .string "Questi due fossili li ho trovati io!\n"
    .string "Sono miei!$"

MtMoon_B2F_Text_MiguelDefeat_IT::
    .string "Bene!\n"
    .string "Ce li divideremo!$"

MtMoon_B2F_Text_WellEachTakeAFossil_IT::
    .string "Uno a testa!\n"
    .string "Non bisogna essere avidi!$"

MtMoon_B2F_Text_ThenThisFossilIsMine_IT::
    .string "OK!\n"
    .string "Allora questo è mio!!!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils_IT::
    .string "Sull'ISOLA CANNELLA c'è un\n"
    .string "LABORATORIO POKéMON.\p"
    .string "Si studia come rigenerare i\n"
    .string "POKéMON dai fossili!$"

MtMoon_B2F_Text_Grunt1Intro_IT::
    .string "TEAM ROCKET troverà i fossili, li\n"
    .string "rivitalizzerà e li venderà a caro\l"
    .string "prezzo!$"

MtMoon_B2F_Text_Grunt1Defeat_IT::
    .string "Grrr!\n"
    .string "Sono furioso!$"

MtMoon_B2F_Text_Grunt1PostBattle_IT::
    .string "Mi fai infuriare! TEAM ROCKET ti\n"
    .string "metterà nella lista nera!$"

MtMoon_B2F_Text_Grunt2Intro_IT::
    .string "Noi, TEAM ROCKET, siamo i gangster\n"
    .string "dei POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat_IT::
    .string "No!\n"
    .string "Che duro colpo!$"

MtMoon_B2F_Text_Grunt2PostBattle_IT::
    .string "Maledizione!\n"
    .string "Ai miei compagni non piacerà!!!$"

MtMoon_B2F_Text_Grunt3Intro_IT::
    .string "Stiamo lavorando!\n"
    .string "Roba che scotta! Vattene, pulce!$"

MtMoon_B2F_Text_Grunt3Defeat_IT::
    .string "Allora sei forte!$"

MtMoon_B2F_Text_Grunt3PostBattle_IT::
    .string "Se trovi un fossile, dammelo e\n"
    .string "smamma!$"

MtMoon_B2F_Text_Grunt4Intro_IT::
    .string "I mocciosi devono lasciare in pace\n"
    .string "gli adulti!$"

MtMoon_B2F_Text_Grunt4Defeat_IT::
    .string "Sono completamente KO!$"

MtMoon_B2F_Text_Grunt4PostBattle_IT::
    .string "I POKéMON vivevano qui molto prima\n"
    .string "dell'uomo.$"

MtMoon_B2F_Text_YouWantDomeFossil_IT::
    .string "Vuoi il DOMOFOSSILE?$"

MtMoon_B2F_Text_YouWantHelixFossil_IT::
    .string "Vuoi l'HELIXFOSSILE?$"

MtMoon_B2F_Text_ObtainedHelixFossil_IT::
    .string "Hai ottenuto l'HELIXFOSSILE.$"

MtMoon_B2F_Text_ObtainedDomeFossil_IT::
    .string "Hai ottenuto il DOMOFOSSILE.$"

