FiveIsland_LostCave_Room1_Text_LawsonIntro_DE::
	.string "Oh!\p"
	.string "Ich dachte, dies sei eine alte\n"
	.string "Ruine. Aber es wimmelt hier\l"
	.string "nur so vor Geistern!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat_DE::
	.string "Kreeeiiisch!\n"
	.string "Gnade!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle_DE::
	.string "Ich versuche, hier heraus-\n"
	.string "zufinden, aber ich lande\l"
	.string "immer wieder hier.\l"
	.string "Vielleicht ist die Anzahl der\l"
	.string "Felsen ein Hinweis?$"

