TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo_DE::
	.string "Wo ist IRRMA heute?\p"
	.string "Genau um diese Zeit bringt\n"
	.string "sie mir immer mein Mittagessen…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle_DE::
	.string "Hm? Du da!\n"
	.string "Bist du ein Freund von IRRMA?\p"
	.string "Hast du IRRMA hier gesehen?\n"
	.string "Ich weiß nicht, wo sie ist. Sie\l"
	.string "sollte hier vor langer Zeit vorbei\l"
	.string "gekommen sein.\l"
	.string "IRRMA ist süß - sie sieht\l"
	.string "mir ähnlich - was ist, wenn…\p"
	.string "Was wäre, wenn meiner IRRMA\n"
	.string "etwas zugestoßen ist?!?\p"
	.string "Bitte hilf mir, sie zu finden!\n"
	.string "Bitte suche auf EILAND DREI\l"
	.string "nach ihr!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland_DE::
	.string "Häh? Das ist die SPIELHALLE?\n"
	.string "Wie tief kann man noch sinken?\p"
	.string "Diese Narren…\p"
	.string "Sie sagten, sie würden auf der\n"
	.string "Insel warten, also, wo sind sie?\p"
	.string "Heh du! Ist das hier das einzige\n"
	.string "EILAND DREI?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt_DE::
	.string "Versuch aufzuwachen, bevor du aus\n"
	.string "dem Bett kriechst, du Hallodri!\p"
	.string "Das ist EILAND ZWEI!\p"
	.string "Beweg dich und nimm\n"
	.string "deine Dreckschleuder von\l"
	.string "Motorrad mit!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing_DE::
	.string "Häh…\n"
	.string "Oh, oh, hab dich!\p"
	.string "Tss…\n"
	.string "Diese Inseln sind verwirrend…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor_DE::
	.string "Sieh dir das nur an!\n"
	.string "Dieser Hallodri hat meinen\l"
	.string "Teppich abgenutzt!$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland_DE::
	.string "Heh! Hör zu! Ich flehe dich an!\n"
	.string "Geh nach EILAND DREI!\p"
	.string "Falls meiner IRRMA etwas\n"
	.string "zustößt…\p"
	.string "Mein Haus auf EILAND DREI hat\n"
	.string "ein rotes Dach!\p"
	.string "Vielleicht taucht sie hier noch\n"
	.string "auf, daher kann ich nicht weg!\p"
	.string "Daher muss ich dich darum bitten!$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday_DE::
	.string "Es tut mir Leid!\n"
	.string "Heute gibt es hier keine Spiele!$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon_DE::
	.string "Wir haben aber bald einige\n"
	.string "Spielchen für dich!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle_DE::
	.string "Du hast also IRRMA gerettet?\n"
	.string "Wie kann ich dir danken?\p"
	.string "IRRMA, Schnuckepuck,\n"
	.string "verzeih mir!\l"
	.string "Papsi wusste nicht, dass du Angst\l"
	.string "und Probleme hattest!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy_DE::
	.string "IRRMA: Ist schon gut, Papsi!\n"
	.string "Ich habe mich mit {PLAYER}\l"
	.string "angefreundet!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe_DE::
	.string "Oh, was ist das?\n"
	.string "Das ist für mich?\p"
	.string "Woher wusstest du, dass ich seltene\n"
	.string "Gesteine liebe?\p"
	.string "Du weißt, wie man einen Kerl\n"
	.string "glücklich macht!$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy_DE::
	.string "{PLAYER} gibt dem Vater von\n"
	.string "IRRMA den METEORITEN!$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill_DE::
	.string "Oh, das ist von BILL!\n"
	.string "Richte ihm meinen Dank aus!\p"
	.string "Du warst einfach fantastisch!\n"
	.string "Das ist für dich!$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy_DE::
	.string "{PLAYER} erhält einen MONDSTEIN\n"
	.string "von IRRMAs Vater!$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag_DE::
	.string "In deinem BEUTEL ist leider\n"
	.string "kein Platz mehr…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning_DE::
	.string "O.K. Die Spielhalle ist gleich\n"
	.string "geöffnet.\p"
	.string "Bringe einen Freund zum\n"
	.string "Spielen mit!$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool_DE::
	.string "Hör zu!\p"
	.string "Bitte zeig mir erneut, wie cool\n"
	.string "du bist!$"

