TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo_FR::
	.string "Bon, où est-ce que LOSTELLE\n"
	.string "est encore passée?\p"
	.string "Elle devrait déjà être là\n"
	.string "avec mon repas…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle_FR::
	.string "Hm? Bonjour!\n"
	.string "Tu connais LOSTELLE?\p"
	.string "Est-ce que tu l'as vue? Elle\n"
	.string "devrait déjà être là.\p"
	.string "Elle est si mignonne…\n"
	.string "J'espère que…\p"
	.string "J'espère qu'il ne lui est rien\n"
	.string "arrivé… …\p"
	.string "LOSTELLE!\p"
	.string "Je t'en prie, aide-moi à la\n"
	.string "chercher, va voir sur l'ILE 3!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland_FR::
	.string "Hein? C'est quoi cette SALLE DE\n"
	.string "JEU? Ça craint vraiment ici!\p"
	.string "Les imbéciles, ils disaient qu'ils\n"
	.string "m'attendraient sur l'île…\p"
	.string "Et où est-ce qu'ils sont?\p"
	.string "Eh, toi! C'est bien la seule ILE 3\n"
	.string "ici, non?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt_FR::
	.string "Ouvre les yeux avant de sortir\n"
	.string "du lit, crétin!\p"
	.string "Tu es sur l'ILE 2!\p"
	.string "Allez, pars d'ici et emmène ta\n"
	.string "fichue moto avec toi!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing_FR::
	.string "Hein? …\n"
	.string "Oh, j'ai compris…\p"
	.string "Tss…\n"
	.string "Quelle idée d'appeler ces îles\l"
	.string "comme ça aussi…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor_FR::
	.string "Regarde ça!\n"
	.string "Ce voyou a rayé tout le sol.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland_FR::
	.string "Mais écoute, je t'en conjure, tu\n"
	.string "dois aller sur l'ILE 3.\p"
	.string "Si quelque chose devait arriver\n"
	.string "à LOSTELLE…\p"
	.string "J'habite la maison au toit rouge\n"
	.string "sur l'ILE 3.\p"
	.string "Elle est peut-être juste en retard,\n"
	.string "alors je dois encore rester ici.\p"
	.string "C'est pour ça que j'ai besoin que\n"
	.string "tu ailles là-bas.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday_FR::
	.string "Désolé. Les jeux ne fonctionnent\n"
	.string "pas aujourd'hui.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon_FR::
	.string "Promis, les jeux fonctionneront\n"
	.string "bientôt pour toi!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle_FR::
	.string "Alors c'est vrai, LOSTELLE a été\n"
	.string "sauvée grâce à toi?\p"
	.string "Comment te remercier?\p"
	.string "LOSTELLE ma chérie, pardonne-moi!\p"
	.string "Papa ne savait pas que tu étais\n"
	.string "en danger!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy_FR::
	.string "LOSTELLE: Tout va bien, papa!\n"
	.string "Grâce à {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe_FR::
	.string "Oh, qu'est-ce que c'est?\n"
	.string "Tu dis que c'est pour moi?\p"
	.string "Comment sais-tu que j'aime\n"
	.string "les pierres rares?\p"
	.string "On peut dire que tu sais comment\n"
	.string "rendre les gens heureux!$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy_FR::
	.string "{PLAYER} tend le METEORITE au père\n"
	.string "de LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill_FR::
	.string "Oh, je vois, ça vient de LEO!\n"
	.string "Remercie-le de ma part!\p"
	.string "Au fait, j'ai moi aussi quelque\n"
	.string "chose pour toi, pour te remercier.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy_FR::
	.string "{PLAYER} reçoit la PIERRE LUNE\n"
	.string "du père de LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag_FR::
	.string "Il n'y a plus de place dans\n"
	.string "ton sac.$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning_FR::
	.string "Très bien, je vais ouvrir la SALLE\n"
	.string "DE JEU tout de suite.\p"
	.string "Viens me voir avec des amis.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool_FR::
	.string "J'suis sûre qu'on se reverra!$"

