Route22_Text_EarlyRivalIntro_ES::
    .string "{RIVAL}: ¡Eh! ¡{PLAYER}!\p"
    .string "¿Vas a la LIGA POKéMON?\p"
    .string "¡Olvídalo! ¡Seguro que no tienes\n"
    .string "ninguna MEDALLA!\p"
    .string "¡El guardia no te dejará pasar!\p"
    .string "Dime, ¿ya son más fuertes tus\n"
    .string "POKéMON?$"

Route22_Text_EarlyRivalDefeat_ES::
    .string "¡Auuu!\n"
    .string "¡Has tenido mucha suerte!$"

Route22_Text_EarlyRivalPostBattle_ES::
    .string "¡Dicen que los ENTRENADORES de la\n"
    .string "LIGA POKéMON son muy fuertes!\p"
    .string "¡Tengo que buscar una forma de\n"
    .string "vencerles!\p"
    .string "¡Deja de perder el tiempo y\n"
    .string "muévete!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons_ES::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro_ES::
    .string "{RIVAL}: ¿Qué? ¡{PLAYER}!\n"
    .string "¡Qué sorpresa verte aquí!\p"
    .string "¿Vas a ir a la LIGA POKéMON?\p"
    .string "¿Y tienes todas las MEDALLAS?\n"
    .string "¡Genial!\p"
    .string "¡Lucharé contra ti, {PLAYER}, como\n"
    .string "preparación para la LIGA POKéMON!\p"
    .string "¡Vamos allá!$"

Route22_Text_LateRivalDefeat_ES::
    .string "¿¡Qué!?\p"
    .string "¡Es que no he tenido cuidado!$"

Route22_Text_LateRivalPostBattle_ES::
    .string "¡Qué buen calentamiento!\n"
    .string "¡Listo para la LIGA POKéMON!\p"
    .string "¡{PLAYER}, necesitas más práctica!\p"
    .string "¡Ya lo sabes! ¡Yo me largo!\n"
    .string "¡Hasta luego!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory_ES::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign_ES::
    .string "LIGA POKéMON\n"
    .string "Puerta delantera$"
