Route22_Text_EarlyRivalIntro_DE::
	.string "{RIVAL}: Heh! {PLAYER}!\p"
	.string "Bist du auf dem Weg zur POKéMON\n"
	.string "LIGA? Vergiss es!\p"
	.string "Wahrscheinlich besitzt du nicht\n"
	.string "einmal einen ORDEN!\p"
	.string "Die Wache wird dich gar nicht erst\n"
	.string "durchlassen!\p"
	.string "Ach, sind deine POKéMON\n"
	.string "eigentlich stärker geworden?$"

Route22_Text_EarlyRivalDefeat_DE::
	.string "Oh nein! So viel Glück wie du kann\n"
	.string "man nicht haben!$"

Route22_Text_EarlyRivalPostBattle_DE::
	.string "In der POKéMON LIGA gibt es viele\n"
	.string "starke TRAINER!\p"
	.string "Ich muss einen Weg finden, an ihnen\n"
	.string "vorbeizukommen.\p"
	.string "Du solltest aufhören zu bummeln\n"
	.string "und dich in Bewegung setzen!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons_DE::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro_DE::
	.string "{RIVAL}: Was?! {PLAYER}!\n"
	.string "Was für eine Überraschung!\p"
	.string "Du bist also auch auf dem Weg zur\n"
	.string "POKéMON LIGA, oder?\p"
	.string "Du besitzt auch alle ORDEN?\n"
	.string "Das ist cool!\p"
	.string "{PLAYER}, ich werde mich für die\n"
	.string "POKéMON LIGA aufwärmen, indem\l"
	.string "ich dich besiege!\p"
	.string "Also, los geht es!$"

Route22_Text_LateRivalDefeat_DE::
	.string "Was!?\p"
	.string "Ich war zu unvorsichtig!$"

Route22_Text_LateRivalPostBattle_DE::
	.string "Das war ein gutes Aufwärmtraining!\n"
	.string "Ich bin gut auf die POKéMON LIGA\l"
	.string "vorbereitet!\p"
	.string "{PLAYER}, auch wenn du gewonnen\n"
	.string "hast, musst du mehr trainieren!\p"
	.string "Ich glaube, du bist dir dessen\n"
	.string "bewusst! Bis dann!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory_DE::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign_DE::
	.string "POKéMON LIGA\n"
	.string "Haupteingang$"

