OneIsland_TreasureBeach_Text_AmaraIntro_DE::
	.string "Sich zurücklehnen und von den\n"
	.string "Wellen treiben lassen…\l"
	.string "Das ist wunderbar!$"

OneIsland_TreasureBeach_Text_AmaraDefeat_DE::
	.string "Ich habe verloren…\n"
	.string "Es tut so weh!$"

OneIsland_TreasureBeach_Text_AmaraPostBattle_DE::
	.string "Das Wasser ist hier angenehm\n"
	.string "warm.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach_DE::
	.string "Die Strömung spült einige brauch-\n"
	.string "bare Dinge hier an den Strand.\p"
	.string "Daher durchkämme ich den Strand\n"
	.string "hier regelmäßig.$"

