SilphCo_11F_Text_ThanksForSavingMeDearBoy_DE::
	.string "PRÄSIDENT: Ich danke dir für die\n"
	.string "Rettung der SILPH CO.\p"
	.string "Ich werde niemals vergessen, wie\n"
	.string "du uns trotz größter Gefahren\l"
	.string "tapfer gerettet hast!\p"
	.string "Wie kann ich dir bloß meinen Dank\n"
	.string "aussprechen?\p"
	.string "Ich bin reich, ich könnte dir\n"
	.string "alles geben!\p"
	.string "Aber vielleicht ist das hier eher\n"
	.string "etwas für dich!$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl_DE::
	.string "PRÄSIDENT: Ich danke dir für die\n"
	.string "Rettung der SILPH CO.\p"
	.string "Ich werde niemals vergessen, wie\n"
	.string "du uns trotz größter Gefahren\l"
	.string "tapfer gerettet hast!\p"
	.string "Wie kann ich dir bloß meinen Dank\n"
	.string "aussprechen?\p"
	.string "Ich bin reich, ich könnte dir\n"
	.string "alles geben!\p"
	.string "Aber vielleicht ist das hier eher\n"
	.string "etwas für dich!$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident_DE::
	.string "{PLAYER} erhält\n"
	.string "MEISTERBALL!$"

SilphCo_11F_Text_ThatsOurSecretPrototype_DE::
	.string "PRÄSIDENT: Man kann das nirgends\n"
	.string "kaufen!\p"
	.string "Es ist der streng geheime Prototyp\n"
	.string "des MEISTERBALLs!\p"
	.string "Du kannst mit ihm JEDES POKéMON\n"
	.string "BEIM 1. VERSUCH einfangen!\p"
	.string "Wäge jedoch sorgfältig ab, wann du\n"
	.string "ihn einsetzt!$"

SilphCo_11F_Text_YouHaveNoRoomForThis_DE::
	.string "Du hast keinen Platz mehr!$"

SilphCo_11F_Text_ThanksForRescuingUs_DE::
	.string "SEKRETÄRIN: Wir danken dir für\n"
	.string "deinen Heldenmut!\p"
	.string "Du hast uns alle gerettet!\n"
	.string "Danke!$"

SilphCo_11F_Text_GiovanniIntro_DE::
	.string "Ah, {PLAYER}!\n"
	.string "So trifft man sich wieder!\p"
	.string "Ich führe gerade äußerst wichtige\n"
	.string "Verhandlungen mit dem PRÄSIDENTEN.\p"
	.string "Halte dich ein für allemal aus den\n"
	.string "Geschäften Erwachsener heraus!\p"
	.string "Oder du lernst eine Welt voller\n"
	.string "Schmerzen kennen!$"

SilphCo_11F_Text_GiovanniDefeat_DE::
	.string "Arrgh!\n"
	.string "Wieder verloren!$"

SilphCo_11F_Text_GiovanniPostBattle_DE::
	.string "Verdammter Mist!\n"
	.string "Du hast unsere Übernahme der SILPH\l"
	.string "CO. vereitelt!\p"
	.string "Aber das TEAM ROCKET wird niemals\n"
	.string "aufgeben!\p"
	.string "{PLAYER}! Vergiss nicht, dass alle\n"
	.string "POKéMON nur zum Nutzen des TEAM\l"
	.string "ROCKET da sind!\p"
	.string "Ich muss gehen, aber meine Zeit\n"
	.string "wird kommen!$"

SilphCo_11F_Text_Grunt2Intro_DE::
	.string "Halt!\n"
	.string "Keinen Schritt weiter!$"

SilphCo_11F_Text_Grunt2Defeat_DE::
	.string "Bitte!\n"
	.string "Verschone mich...$"

SilphCo_11F_Text_Grunt2PostBattle_DE::
	.string "Du willst also zum BOSS?$"

SilphCo_11F_Text_Grunt1Intro_DE::
	.string "Stopp!\n"
	.string "Hast du einen Termin beim BOSS?$"

SilphCo_11F_Text_Grunt1Defeat_DE::
	.string "O.K.!\n"
	.string "Ich lasse dich durch!$"

SilphCo_11F_Text_Grunt1PostBattle_DE::
	.string "Die POKéMON von unserem BOSS\n"
	.string "werden dich fertig machen!$"

SilphCo_11F_Text_MonitorHasMonsOnIt_DE::
	.string "Auf dem Monitor sind POKéMON zu\n"
	.string "sehen!$"

SilphCo_11F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "10 OG$"

