PokemonMansion_Text_PressSecretSwitch_IT::
    .string "Un pulsante segreto!\p"
    .string "Devo premerlo?$"

PokemonMansion_Text_WhoWouldnt_IT::
    .string "Chi non lo farebbe?$"

PokemonMansion_Text_NotQuiteYet_IT::
    .string "Non ancora!$"

PokemonMansion_1F_Text_ArnieIntro_IT::
    .string "Non riesco ad uscire! Questo posto\n"
    .string "è come un enorme labirinto!$"

PokemonMansion_1F_Text_ArnieDefeat_IT::
    .string "No!\n"
    .string "Il mio bottino!$"

PokemonMansion_1F_Text_ArniePostBattle_IT::
    .string "I pulsanti aprono e chiudono\n"
    .string "alternativamente gruppi di porte!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle_IT::
    .string "Diario: 5 luglio\n"
    .string "Guyana, Sudamerica.\p"
    .string "È stato scoperto un nuovo POKéMON\n"
    .string "nel cuore della giungla.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew_IT::
    .string "Diario: 10 luglio\n"
    .string "Abbiamo chiamato MEW il\l"
    .string "POKéMON appena scoperto.$"

