PokemonMansion_Text_PressSecretSwitch_DE::
	.string "Ein versteckter Schalter!\p"
	.string "Schalter drücken?$"

PokemonMansion_Text_WhoWouldnt_DE::
	.string "Wer würde es nicht tun?$"

PokemonMansion_Text_NotQuiteYet_DE::
	.string "Lieber nicht!$"

PokemonMansion_1F_Text_ArnieIntro_DE::
	.string "Ich finde keinen Weg nach draußen!\n"
	.string "Der reinste Irrgarten!$"

PokemonMansion_1F_Text_ArnieDefeat_DE::
	.string "Oh nein!\n"
	.string "Meine Beute!$"

PokemonMansion_1F_Text_ArniePostBattle_DE::
	.string "Die Türen kannst du mittels\n"
	.string "Schalter schließen oder öffnen!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle_DE::
	.string "TAGEBUCH: 5. JULI\n"
	.string "Der Dschungel im Niemandsland.\p"
	.string "Wir haben tief im Dschungel ein\n"
	.string "völlig neues POKéMON gefunden.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew_DE::
	.string "TAGEBUCH: 10. JULI\n"
	.string "Wir nennen das neu entdeckte\l"
	.string "POKéMON MEW.$"

