PokemonMansion_Text_PressSecretSwitch_ES::
    .string "Un botón secreto.\p"
    .string "¿Lo pulso?$"

PokemonMansion_Text_WhoWouldnt_ES::
    .string "¿Y quién no lo haría?$"

PokemonMansion_Text_NotQuiteYet_ES::
    .string "¡Todavía no!$"

PokemonMansion_1F_Text_ArnieIntro_ES::
    .string "¡No sé salir! ¡Este viejo lugar\n"
    .string "es un enorme laberinto!$"

PokemonMansion_1F_Text_ArnieDefeat_ES::
    .string "¡Oh, no!\n"
    .string "¡Mi botín!$"

PokemonMansion_1F_Text_ArniePostBattle_ES::
    .string "¡Los botones abren y cierran\n"
    .string "alternativamente los grupos\l"
    .string "de puertas!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle_ES::
    .string "Diario: 5 de julio.\n"
    .string "Guyana, Suramérica.\p"
    .string "Un nuevo tipo de POKéMON fue\n"
    .string "descubierto en el interior de la\l"
    .string "selva.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew_ES::
    .string "Diario: 10 de julio.\n"
    .string "Hemos llamado a este nuevo\l"
    .string "POKéMON, MEW.$"
