PokemonMansion_Text_PressSecretSwitch_FR::
	.string "Un bouton secret!\p"
	.string "Appuyer dessus?$"

PokemonMansion_Text_WhoWouldnt_FR::
	.string "Qui ne le ferait pas?$"

PokemonMansion_Text_NotQuiteYet_FR::
	.string "Pas vraiment!$"

PokemonMansion_1F_Text_ArnieIntro_FR::
	.string "Mais…\n"
	.string "J'suis complètement paumé!$"

PokemonMansion_1F_Text_ArnieDefeat_FR::
	.string "Non!\n"
	.string "Mon butin!$"

PokemonMansion_1F_Text_ArniePostBattle_FR::
	.string "Les interrupteurs ouvrent et\n"
	.string "ferment alternativement les portes!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle_FR::
	.string "Rapport: 5 Juillet.\n"
	.string "Jungle X.\p"
	.string "Un nouveau type de POKéMON\n"
	.string "a été découvert.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew_FR::
	.string "Rapport: 10 Juillet.\n"
	.string "Le POKéMON a été baptisé MEW.$"

