CinnabarIsland_Gym_Text_BlaineIntro_IT::
    .string "Ehi!\p"
    .string "Sono BLAINE, il CAPOPALESTRA\n"
    .string "dell'ISOLA CANNELLA!\p"
    .string "I miei POKéMON inceneriranno ogni\n"
    .string "sfidante!\p"
    .string "Procurati l'ANTISCOTTATURA!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat_IT::
    .string "Mi hai incenerito!\p"
    .string "Hai meritato la MEDAGLIA\n"
    .string "VULCANO!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove_IT::
    .string "FUOCOBOMBA è la massima tecnica\n"
    .string "del fuoco!\p"
    .string "Non sprecarla sui POKéMON di\n"
    .string "tipo ACQUA.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge_IT::
    .string "Ehi!\p"
    .string "La MEDAGLIA VULCANO migliora le\n"
    .string "statistiche SPECIALI dei tuoi\l"
    .string "POKéMON!\p"
    .string "Prendi anche questo!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine_IT::
    .string "{PLAYER} riceve\n"
    .string "la MT38!$"

CinnabarIsland_Gym_Text_BlainePostBattle_IT::
    .string "La MT38 contiene FUOCOBOMBA!\p"
    .string "Insegnala ai POKéMON di tipo\n"
    .string "FUOCO!\p"
    .string "CHARMELEON e VULPIX sono i più\n"
    .string "adatti!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis_IT::
    .string "Non hai abbastanza spazio!$"

CinnabarIsland_Gym_Text_ErikIntro_IT::
    .string "Sai quanto caldo può diventare il\n"
    .string "fiato dei POKéMON di tipo FUOCO?$"

CinnabarIsland_Gym_Text_ErikDefeat_IT::
    .string "Caldo!\n"
    .string "Caldissimo!$"

CinnabarIsland_Gym_Text_ErikPostBattle_IT::
    .string "Fuoco, o per la precisione,\n"
    .string "combustione…\p"
    .string "Bla, bla, bla, bla…$"

CinnabarIsland_Gym_Text_QuinnIntro_IT::
    .string "Ero un ladro ma sono diventato un\n"
    .string "bravo ALLENATORE!$"

CinnabarIsland_Gym_Text_QuinnDefeat_IT::
    .string "Mi arrendo!$"

CinnabarIsland_Gym_Text_QuinnPostBattle_IT::
    .string "Non posso fare a meno di rubare i\n"
    .string "POKéMON altrui!$"

CinnabarIsland_Gym_Text_AveryIntro_IT::
    .string "Non puoi vincere!\n"
    .string "Ho studiato molto i POKéMON!$"

CinnabarIsland_Gym_Text_AveryDefeat_IT::
    .string "Bleeh!\n"
    .string "I miei studi…$"

CinnabarIsland_Gym_Text_AveryPostBattle_IT::
    .string "Le mie teorie sono troppo\n"
    .string "complicate per te!$"

CinnabarIsland_Gym_Text_RamonIntro_IT::
    .string "Mi piace usare i POKéMON di tipo\n"
    .string "FUOCO!$"

CinnabarIsland_Gym_Text_RamonDefeat_IT::
    .string "Che patata bollente!$"

CinnabarIsland_Gym_Text_RamonPostBattle_IT::
    .string "Userei volentieri un POKéMON ladro\n"
    .string "se ce ne fossero!$"

CinnabarIsland_Gym_Text_DerekIntro_IT::
    .string "So perché BLAINE è diventato un\n"
    .string "ALLENATORE!$"

CinnabarIsland_Gym_Text_DerekDefeat_IT::
    .string "Ahia!$"

CinnabarIsland_Gym_Text_DerekPostBattle_IT::
    .string "BLAINE si era perso in montagna\n"
    .string "quando apparve uno spaventoso\l"
    .string "POKéMON uccello!\p"
    .string "Grazie alla sua luce, BLAINE poté\n"
    .string "ritrovare la via.$"

CinnabarIsland_Gym_Text_DustyIntro_IT::
    .string "Conosco molte PALESTRE, ma la mia\n"
    .string "preferita è questa!$"

CinnabarIsland_Gym_Text_DustyDefeat_IT::
    .string "È troppo caldo!$"

CinnabarIsland_Gym_Text_DustyPostBattle_IT::
    .string "A noi fan dei POKéMON di tipo\n"
    .string "FUOCO piacciono PONYTA e\l"
    .string "NINETALES!$"

CinnabarIsland_Gym_Text_ZacIntro_IT::
    .string "Il fuoco è debole contro l'acqua!$"

CinnabarIsland_Gym_Text_ZacDefeat_IT::
    .string "Perso miseramente!$"

CinnabarIsland_Gym_Text_ZacPostBattle_IT::
    .string "L'acqua batte il fuoco!\p"
    .string "Il fuoco però scioglie i POKéMON\n"
    .string "di tipo GHIACCIO!$"

CinnabarIsland_Gym_Text_GymGuyAdvice_IT::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "Quella testa calda di BLAINE è un\n"
    .string "maestro con i POKéMON di tipo\l"
    .string "FUOCO! \p"
    .string "Usa l'acqua per calmare i suoi\n"
    .string "bollenti spiriti!\p"
    .string "Ti consiglio degli ANTISCOTTATURA!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory_IT::
    .string "{PLAYER}!\n"
    .string "Hai spento quel braciere!$"

CinnabarIsland_Gym_Text_GymStatue_IT::
    .string "CAPOPALESTRA dell'ISOLA CANNELLA:\n"
    .string "BLAINE\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon_IT::
    .string "CAPOPALESTRA dell'ISOLA CANNELLA:\n"
    .string "BLAINE\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules_IT::
    .string "Quiz POKéMON!\p"
    .string "Rispondi giusto e si aprirà la porta\n"
    .string "della prossima stanza!\p"
    .string "Ma se la risposta è sbagliata,\n"
    .string "dovrai vedertela con l'ALLENATORE!\p"
    .string "Se vuoi tenerti i POKéMON per il\n"
    .string "CAPOPALESTRA…\p"
    .string "…allora rispondi bene!\n"
    .string "Su, forza!$"

CinnabarIsland_Gym_Text_QuizQuestion1_IT::
    .string "CATERPIE diventa METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2_IT::
    .string "Sono 9 le MEDAGLIE ufficiali della\n"
    .string "LEGA POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3_IT::
    .string "POLIWAG si evolve tre volte?$"

CinnabarIsland_Gym_Text_QuizQuestion4_IT::
    .string "Le mosse elettriche sono efficaci\n"
    .string "contro i POKéMON tipo TERRA?$"

CinnabarIsland_Gym_Text_QuizQuestion5_IT::
    .string "È vero che POKéMON dello stesso\n"
    .string "livello non sono comunque identici?$"

CinnabarIsland_Gym_Text_QuizQuestion6_IT::
    .string "La MT28 contiene PIETRA TOMBALE?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough_IT::
    .string "Risposta esatta!\p"
    .string "Avanti!$"

CinnabarIsland_Gym_Text_SorryBadCall_IT::
    .string "Peccato!\n"
    .string "Hai toppato!$"

