CinnabarIsland_Gym_Text_BlaineIntro_ES::
    .string "¡Ja!\p"
    .string "¡Soy BLAINE! ¡LÍDER del GIMNASIO\n"
    .string "de CANELA!\p"
    .string "¡Mis feroces POKéMON de FUEGO\n"
    .string "quemarán a quien me desafíe!\p"
    .string "¡Ja! ¡Más vale que tengas\n"
    .string "ANTIQUEMAR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat_ES::
    .string "¡Me has machacado!\n"
    .string "¡He quedado reducido a nada!\p"
    .string "¡Has ganado la MEDALLA VOLCÁN!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove_ES::
    .string "¡LLAMARADA es lo máximo en la\n"
    .string "técnica de las quemaduras!\p"
    .string "¡No la malgastes con los POKéMON\n"
    .string "acuáticos!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge_ES::
    .string "¡Ja!\p"
    .string "¡La MEDALLA VOLCÁN mejora las\n"
    .string "habilidades ESPECIALES de tus\l"
    .string "POKéMON!\p"
    .string "¡Mira, también te daré esto!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine_ES::
    .string "¡{PLAYER} recibió la MT38\n"
    .string "de manos de BLAINE!$"

CinnabarIsland_Gym_Text_BlainePostBattle_ES::
    .string "¡La MT38 contiene LLAMARADA!\p"
    .string "¡Enseña este ataque a los POKéMON\n"
    .string "del tipo FUEGO!\p"
    .string "¡CHARMELEON o PONYTA serían\n"
    .string "las mejores apuestas!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis_ES::
    .string "¡Hazle sitio a esto, anda!$"

CinnabarIsland_Gym_Text_ErikIntro_ES::
    .string "¿Sabes el calor que puede dar el\n"
    .string "aliento de fuego de un POKéMON?$"

CinnabarIsland_Gym_Text_ErikDefeat_ES::
    .string "¡Ay!\n"
    .string "¡Quema, quema!$"

CinnabarIsland_Gym_Text_ErikPostBattle_ES::
    .string "Fuego o, para ser más preciso,\n"
    .string "combustión...\p"
    .string "¡Bla, bla, bla, bla!...$"

CinnabarIsland_Gym_Text_QuinnIntro_ES::
    .string "Yo era ladrón, pero me hice\n"
    .string "honrado cuando me convertí\l"
    .string "en ENTRENADOR.$"

CinnabarIsland_Gym_Text_QuinnDefeat_ES::
    .string "¡Me rindo!$"

CinnabarIsland_Gym_Text_QuinnPostBattle_ES::
    .string "¡No puedo evitar robar los POKéMON\n"
    .string "de otras personas!$"

CinnabarIsland_Gym_Text_AveryIntro_ES::
    .string "¡No puedes ganar!\n"
    .string "¡Soy un experto en POKéMON!$"

CinnabarIsland_Gym_Text_AveryDefeat_ES::
    .string "¡Au!\n"
    .string "¡Tanta teoría para nada!$"

CinnabarIsland_Gym_Text_AveryPostBattle_ES::
    .string "¡Mis teorías son muy complicadas\n"
    .string "para ti!$"

CinnabarIsland_Gym_Text_RamonIntro_ES::
    .string "¡Me encanta usar POKéMON\n"
    .string "del tipo FUEGO!$"

CinnabarIsland_Gym_Text_RamonDefeat_ES::
    .string "¡No hay quien pueda contigo!$"

CinnabarIsland_Gym_Text_RamonPostBattle_ES::
    .string "¡Ojalá hubiera un POKéMON ladrón!\n"
    .string "¡Me encantaría utilizarlo!$"

CinnabarIsland_Gym_Text_DerekIntro_ES::
    .string "¡Ya sé por qué BLAINE se hizo\n"
    .string "ENTRENADOR!$"

CinnabarIsland_Gym_Text_DerekDefeat_ES::
    .string "¡Auuuuuuuuuu!$"

CinnabarIsland_Gym_Text_DerekPostBattle_ES::
    .string "BLAINE se perdió en la montaña,\n"
    .string "y se hizo de noche...\p"
    .string "¡Pero apareció un feroz pájaro\n"
    .string "POKéMON...!\p"
    .string "¡E iluminó el camino a BLAINE\n"
    .string "para que pudiera bajar!$"

CinnabarIsland_Gym_Text_DustyIntro_ES::
    .string "¡He estado en muchos GIMNASIOS,\n"
    .string "pero éste es mi preferido!$"

CinnabarIsland_Gym_Text_DustyDefeat_ES::
    .string "¡Vaya!\n"
    .string "¡Eso quema!$"

CinnabarIsland_Gym_Text_DustyPostBattle_ES::
    .string "¡A nosotros, los seguidores de los\n"
    .string "POKéMON de fuego, nos gustan\l"
    .string "PONYTA y NINETALES!$"

CinnabarIsland_Gym_Text_ZacIntro_ES::
    .string "El fuego es débil contra el H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat_ES::
    .string "¡Oh!\n"
    .string "¡Esto se acabó!$"

CinnabarIsland_Gym_Text_ZacPostBattle_ES::
    .string "¡El agua apaga el fuego!\p"
    .string "¡Pero el fuego derrite a los\n"
    .string "POKéMON de hielo!$"

CinnabarIsland_Gym_Text_GymGuyAdvice_ES::
    .string "¡Hola, aspirante al título!\p"
    .string "¡BLAINE es un profesional\n"
    .string "de los POKéMON de fuego!\p"
    .string "¡Bájale los humos con agua!\p"
    .string "¡Más vale que lleves\n"
    .string "ANTIQUEMAR!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory_ES::
    .string "¡{PLAYER}, has ganado a esa\n"
    .string "antorcha con patas!$"

CinnabarIsland_Gym_Text_GymStatue_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules_ES::
    .string "¡POKéACERTIJO!\p"
    .string "¡Responde bien y abrirás la puerta\n"
    .string "a la siguiente habitación!\p"
    .string "¡Responde mal y lucharás contra\n"
    .string "un ENTRENADOR!\p"
    .string "Si prefieres reservar tus POKéMON\n"
    .string "para el LÍDER del GIMNASIO...\p"
    .string "¡Hazlo bien!\n"
    .string "¡Vamos allá!$"

CinnabarIsland_Gym_Text_QuizQuestion1_ES::
    .string "¿Evoluciona CATERPIE y\n"
    .string "se transforma en METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2_ES::
    .string "¿Hay 9 MEDALLAS oficiales\n"
    .string "de la LIGA POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3_ES::
    .string "¿Evoluciona POLIWAG 3 veces?$"

CinnabarIsland_Gym_Text_QuizQuestion4_ES::
    .string "¿Afectan los movimientos del tipo\n"
    .string "ELÉCTRICO a los POKéMON\l"
    .string "del tipo TIERRA?$"

CinnabarIsland_Gym_Text_QuizQuestion5_ES::
    .string "¿Son distintos los POKéMON del\n"
    .string "mismo tipo y del mismo nivel?$"

CinnabarIsland_Gym_Text_QuizQuestion6_ES::
    .string "¿Contiene la MT28 TUMBAPIEDRA?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough_ES::
    .string "¡Respuesta correcta!\p"
    .string "¡Adelante!$"

CinnabarIsland_Gym_Text_SorryBadCall_ES::
    .string "¡Mal!\n"
    .string "¡Lo siento!$"
