PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone_FR::
	.string "Quoi!?\p"
	.string "La TEAM ROCKET est au MONT\n"
	.string "SELENITE!\p"
	.string "Damnation!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff_FR::
	.string "RONDOUDOU: Dou! Doudouuuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy_FR::
	.string "(Bâille)\p"
	.string "Lorsque RONDOUDOU chante, tous les\n"
	.string "POKéMON piquent du nez…\p"
	.string "… Moi aussi…\n"
	.string "(Ronfl)…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu_FR::
	.string "Je veux vraiment un PIKACHU.\n"
	.string "Ça te dit un MELOFEE en échange?$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid_FR::
	.string "J'échange des POKéMON avec\n"
	.string "ce gamin.\p"
	.string "Comme j'avais deux PIKACHU,\n"
	.string "j'en ai échangé un!$"

