PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone_ES::
    .string "¿¡Qué!?\p"
    .string "¿Que el TEAM ROCKET está en el\n"
    .string "MT. MOON?\p"
    .string "¡Estoy hablando por teléfono!\n"
    .string "¿Será posible?$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff_ES::
    .string "JIGGLYPUFF: ¡Puf! ¡Puuuff!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy_ES::
    .string "Aaah..., qué sueño...\p"
    .string "Cuando JIGGLYPUFF canta, los\n"
    .string "POKéMON se duermen...\p"
    .string "Y yo también...\n"
    .string "Qué sueño...$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu_ES::
    .string "¡Yo quiero un PIKACHU, así que\n"
    .string "voy a intercambiar a mi CLEFAIRY\l"
    .string "por uno!$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid_ES::
    .string "Voy a intercambiar mi POKéMON\n"
    .string "con ese chico de ahí.\p"
    .string "Como tengo dos PIKACHU,\n"
    .string "voy a pasarle uno.$"
