PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone_IT::
    .string "Cosa?\p"
    .string "TEAM ROCKET è al MONTE LUNA?\p"
    .string "Sono al telefono!\n"
    .string "Vattene!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff_IT::
    .string "JIGGLYPUFF: Puf! Puuuff!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy_IT::
    .string "Uaho!\p"
    .string "Quando JIGGLYPUFF canta, i\n"
    .string "POKéMON si addormentano!\p"
    .string "…Anch'io…\n"
    .string "Ronf… ronf…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu_IT::
    .string "Sto scambiando il mio\n"
    .string "CLEFAIRY per un PIKACHU.\p"
    .string "Mi piacciono i PIKACHU!$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid_IT::
    .string "Sto scambiando un POKéMON con\n"
    .string "quel bambino.\p"
    .string "Ho due PIKACHU, così ho pensato\n"
    .string "di scambiarne uno.$"

