SSAnne_B1F_Room1_Text_PhillipIntro_DE::
	.string "Der Verlierer wird kielgeholt!\n"
	.string "Los!$"

SSAnne_B1F_Room1_Text_PhillipDefeat_DE::
	.string "Argh!\n"
	.string "Von einem Kind besiegt...$"

SSAnne_B1F_Room1_Text_PhillipPostBattle_DE::
	.string "Manchmal treiben Quallen an das\n"
	.string "Schiff. Der Koch fängt sie dann...$"

SSAnne_B1F_Room1_Text_BarnyIntro_DE::
	.string "Warte doch!\n"
	.string "Lass uns plaudern!\p"
	.string "Ich besitze nur WASSER-POKéMON!$"

SSAnne_B1F_Room1_Text_BarnyDefeat_DE::
	.string "Mist!\n"
	.string "Der ist mir entwischt!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle_DE::
	.string "Ich hätte dich fast zum Assistenten\n"
	.string "gemacht!$"

