Route25_SeaCottage_Text_ImBillHelpMeOutPal_IT::
    .string "Ehi tu! Sono un POKéMON…\n"
    .string "…no anzi!\p"
    .string "Chiamami BILL!\n"
    .string "Sono un autentico POKéFANATICO!\p"
    .string "Cos'è quella faccia scettica?\p"
    .string "Non scherzo!\p"
    .string "Ho sbagliato un esperimento e mi\n"
    .string "sono combinato con un POKéMON!\p"
    .string "E ora come faccio?\n"
    .string "Aiutami, ti prego!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady_IT::
    .string "Ehi tu! Sono un POKéMON…\n"
    .string "…no anzi!\p"
    .string "Chiamami BILL!\n"
    .string "Sono un autentico POKéFANATICO!\p"
    .string "Cos'è quella faccia scettica?\p"
    .string "Non scherzo!\p"
    .string "Ho sbagliato un esperimento e mi\n"
    .string "sono combinato con un POKéMON!\p"
    .string "E ora come faccio?\n"
    .string "Aiutami ti prego!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC_IT::
    .string "Quando entro nel\n"
    .string "TELETRASPORTATORE, vai al mio PC\l"
    .string "e avvia la Separazione Cellulare!$"

Route25_SeaCottage_Text_NoPleaseChief_IT::
    .string "No!?\n"
    .string "E dai!\p"
    .string "Aiuta un povero diavolo in\n"
    .string "difficoltà!\p"
    .string "Che ne dici, giovanotto?\n"
    .string "Per favore?\l"
    .string "OK?\l"
    .string "Benissimo!$"

Route25_SeaCottage_Text_NoPleaseBeautiful_IT::
    .string "No!?\n"
    .string "E dai!\p"
    .string "Aiuta un povero diavolo in\n"
    .string "difficoltà!\p"
    .string "Che ne dici, signorina?\n"
    .string "Per favore?\l"
    .string "OK?\l"
    .string "Benissimo!$"

Route25_SeaCottage_Text_ThanksBudTakeThis_IT::
    .string "BILL: Evviva! Ti devo un favore!\n"
    .string "Grazie infinite!\p"
    .string "Sei qui per vedere la mia\n"
    .string "collezione di POKéMON?\p"
    .string "No?\n"
    .string "Che peccato!\p"
    .string "Sono in debito con te…\n"
    .string "Ecco la tua ricompensa!$"

Route25_SeaCottage_Text_ThanksLadyTakeThis_IT::
    .string "BILL: Evviva! Ti devo un favore!\n"
    .string "Grazie infinite!\p"
    .string "Sei qui per vedere la mia\n"
    .string "collezione di POKéMON?\p"
    .string "No?\n"
    .string "Che peccato!\p"
    .string "Sono in debito con te…\n"
    .string "Ecco la tua ricompensa!$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill_IT::
    .string "{PLAYER} riceve\n"
    .string "il BIGL. NAVE!$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff_IT::
    .string "Hai troppa roba addosso, lo sai?!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead_IT::
    .string "La nave M/N ANNA è ad\n"
    .string "ARANCIOPOLI.\p"
    .string "I suoi passeggeri sono ALLENATORI!\p"
    .string "Mi hanno invitato alla festa, ma io\n"
    .string "le odio.\p"
    .string "Perché non ci vai tu al posto mio?$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC_IT::
    .string "BILL: Guarda, ho dei POKéMON\n"
    .string "molto rari nel PC!$"

Route25_SeaCottage_Text_TeleporterIsDisplayed_IT::
    .string "Sul video del PC appare\n"
    .string "TELETRASPORTATORE!$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator_IT::
    .string "{PLAYER} avvia il Separatore\n"
    .string "Cellulare del TELETRASPORTATORE!$"

Route25_SeaCottage_Text_BillsFavoriteMonList_IT::
    .string "Lista dei POKéMON preferiti da\n"
    .string "BILL!$"

Route25_SeaCottage_Text_SeeWhichMon_IT::
    .string "Che POKéMON vuoi vedere?$"

