Route25_SeaCottage_Text_ImBillHelpMeOutPal_DE::
	.string "Hallo! Ich bin ein POKéMON!\n"
	.string "Spaß beiseite, ich bin keines!\p"
	.string "Nenn mich einfach BILL! Ich bin ein\n"
	.string "waschechter POKéMANIAC!\p"
	.string "Glaubst du mir nicht?\p"
	.string "Mir ist ein Experiment missglückt!\n"
	.string "Dabei wurden meine Zellen mit denen\l"
	.string "eines POKéMON kombiniert!\p"
	.string "Wie sieht es aus?\n"
	.string "Hilfst du mir?$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady_DE::
	.string "Hallo! Ich bin ein POKéMON!\n"
	.string "Spaß beiseite, ich bin keines!\p"
	.string "Nenn mich einfach BILL! Ich bin ein\n"
	.string "waschechter POKéMANIAC!\p"
	.string "Glaubst du mir nicht?\p"
	.string "Mir ist ein Experiment missglückt!\n"
	.string "Dabei wurden meine Zellen mit denen\l"
	.string "eines POKéMON kombiniert!\p"
	.string "Wie sieht es aus?\n"
	.string "Hilfst du mir?$"

Route25_SeaCottage_Text_RunCellSeparationOnPC_DE::
	.string "Ich gehe in den TELEPORTER, und\n"
	.string "du startest von meinem PC aus das\l"
	.string "ZELLTEILUNGS-PROGRAMM.$"

Route25_SeaCottage_Text_NoPleaseChief_DE::
	.string "Nein? Komm schon, ich stecke in\n"
	.string "wirklich ernsten Schwierigkeiten!\p"
	.string "Also, hilfst du mir? Bitte!\n"
	.string "O.K.? Alles klar!$"

Route25_SeaCottage_Text_NoPleaseBeautiful_DE::
	.string "Nein? Komm schon, ich stecke in\n"
	.string "wirklich ernsten Schwierigkeiten!\p"
	.string "Also, hilfst du mir? Bitte!\n"
	.string "O.K.? Alles klar!$"

Route25_SeaCottage_Text_ThanksBudTakeThis_DE::
	.string "BILL: Klasse! Danke, Kumpel!\n"
	.string "Du hast bei mir etwas gut!\p"
	.string "Bist du hier, um dir meine POKéMON-\n"
	.string "SAMMLUNG anzusehen?\p"
	.string "Nein?\n"
	.string "Das ist schade!\p"
	.string "Wie kann ich dir nur danken?\n"
	.string "Nimm einfach das hier...$"

Route25_SeaCottage_Text_ThanksLadyTakeThis_DE::
	.string "BILL: Klasse! Danke, Kleine!\n"
	.string "Du hast bei mir etwas gut!\p"
	.string "Bist du hier, um dir meine POKéMON-\n"
	.string "SAMMLUNG anzusehen?\p"
	.string "Nein?\n"
	.string "Das ist schade!\p"
	.string "Wie kann ich dir nur danken?\n"
	.string "Nimm einfach das hier...$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill_DE::
	.string "{PLAYER} erhält\n"
	.string "ein BOOTSTICKET!$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff_DE::
	.string "Heh Kiddie! Du trägst zu viel mit\n"
	.string "dir herum!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead_DE::
	.string "In ORANIA CITY ankert ein großes\n"
	.string "Kreuzfahrtschiff, die M.S. ANNE!\p"
	.string "An Bord befinden sich nur TRAINER!\p"
	.string "Sie haben mich zu einer Party\n"
	.string "eingeladen, aber ich mag so viel\l"
	.string "Trubel nicht.\p"
	.string "Hättest du Lust, hinzugehen?$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC_DE::
	.string "BILL: Schau dir doch einfach auf\n"
	.string "dem PC ein paar meiner seltenen\l"
	.string "POKéMON an!$"

Route25_SeaCottage_Text_TeleporterIsDisplayed_DE::
	.string "Auf dem PC läuft ein Programm zur\n"
	.string "Steuerung des TELEPORTERs.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator_DE::
	.string "{PLAYER} hat den\n"
	.string "ZELL-SEPARATOR in Gang gesetzt!$"

Route25_SeaCottage_Text_BillsFavoriteMonList_DE::
	.string "Eine Liste von BILLs LIEBLINGS-\n"
	.string "POKéMON!$"

Route25_SeaCottage_Text_SeeWhichMon_DE::
	.string "Welches POKéMON möchtest du\n"
	.string "betrachten?$"

