@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale_DE::
	.string "Meine POKéMON wurden im POKéMON-\n"
	.string "TURM zur letzten Ruhe gebettet.\p"
	.string "Ich gebe dir diese TM. Ich\n"
	.string "benötige sie nicht länger...$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale_DE::
	.string "Meine POKéMON wurden im POKéMON-\n"
	.string "TURM zur letzten Ruhe gebettet.\p"
	.string "Ich gebe dir diese TM. Ich\n"
	.string "benötige sie nicht länger...$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl_DE::
	.string "{PLAYER} erhält\n"
	.string "TM27!$"

Route12_NorthEntrance_2F_Text_ExplainTM27_DE::
	.string "TM27 ist RÜCKKEHR.\p"
	.string "Behandelst du deine POKéMON\n"
	.string "gut, geben sie Liebe zurück, indem\l"
	.string "sie sich im Kampf besonders\l"
	.string "anstrengen.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis_DE::
	.string "Oh, du kannst sie im Moment nicht\n"
	.string "tragen.$"

Route12_NorthEntrance_2F_Text_TheresManFishing_DE::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Du siehst einen angelnden Mann!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower_DE::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Du siehst den POKéMON-TURM!$"

