@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale_ES::
    .string "Las cenizas de mis POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes quedarte con mi MT. Ya no\n"
    .string "la necesito...$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale_ES::
    .string "Las cenizas de mis POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes quedarte con mi MT. Ya no\n"
    .string "la necesito...$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl_ES::
    .string "¡{PLAYER} obtuvo la MT27\n"
    .string "de manos de la chica!$"

Route12_NorthEntrance_2F_Text_ExplainTM27_ES::
    .string "¡La MT27 es un ataque que se\n"
    .string "llama RETROCESO!\p"
    .string "Si tratas bien a tus POKéMON,\n"
    .string "aumentará sus efectos en\l"
    .string "combate.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis_ES::
    .string "¡No tienes sitio para esto!$"

Route12_NorthEntrance_2F_Text_TheresManFishing_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Un hombre está pescando!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Es la TORRE POKéMON!$"
