CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked_IT::
    .string "Sono venuta fino all'ISOLA\n"
    .string "CANNELLA per vedere la PALESTRA,\l"
    .string "ma è chiusa!\p"
    .string "Da qualche parte dovrebbe esserci\n"
    .string "una chiave per aprire la PALESTRA.\p"
    .string "Che non sia nella villa bruciata?\p"
    .string "Pare che ci vivesse un amico del\n"
    .string "CAPOPALESTRA.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom_IT::
    .string "Hai tanti amici?\p"
    .string "Certo, collegarsi con quelli che\n"
    .string "già conosci è divertente.\p"
    .string "Ma hai mai provato ad entrare\n"
    .string "nella SALA CONTATTO?\p"
    .string "Potresti fare nuove conoscenze!$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves_IT::
    .string "I POKéMON possono imparare altre\n"
    .string "tecniche, anche se l'evoluzione\l"
    .string "viene interrotta.\p"
    .string "L'evoluzione può avvenire dopo\n"
    .string "l'apprendimento di nuove mosse.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland_IT::
    .string "Ehi, mi hai fatto aspettare!\n"
    .string "Allora, siamo pronti per andare\l"
    .string "a PRIMISOLA?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet_IT::
    .string "Ah, non ancora?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo_IT::
    .string "Andiamo, allora!$"

