CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked_ES::
    .string "Quería entrar en el GIMNASIO\n"
    .string "de CANELA, pero la puerta\l"
    .string "está cerrada a cal y canto.\p"
    .string "Debe de haber una llave por\n"
    .string "algún sitio.\p"
    .string "¿Estará en la mansión quemada\n"
    .string "esa?\p"
    .string "Dicen que está habitada por un\n"
    .string "amigo del LÍDER del GIMNASIO.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom_ES::
    .string "¿Tienes muchos amigos?\p"
    .string "Está muy bien que te conectes\n"
    .string "con ellos, por supuesto.\p"
    .string "Pero si visitas la SALA UNIÓN\n"
    .string "de vez en cuando, puede que\l"
    .string "hagas nuevos amigos.\p"
    .string "Creo que merecería la pena que\n"
    .string "fueras a la SALA UNIÓN.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves_ES::
    .string "Los POKéMON pueden seguir\n"
    .string "aprendiendo técnicas aunque hayas\l"
    .string "cancelado su evolución.\p"
    .string "La evolución puede esperar hasta\n"
    .string "que hayan aprendido nuevos\l"
    .string "movimientos.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland_ES::
    .string "BILL: ¡Eh, llevo la tira\n"
    .string "esperando!\l"
    .string "¿Nos vamos a ISLA PRIMA?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet_ES::
    .string "¿Todavía no?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo_ES::
    .string "Venga, pues vamos.$"
