CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked_FR::
	.string "Je suis venue visiter l'ARENE de\n"
	.string "CRAMOIS'ILE, mais c'est fermé.\p"
	.string "Il doit bien y avoir une clé\n"
	.string "quelque part.\p"
	.string "Dans ce vieux manoir peut-être.\p"
	.string "Il paraît qu'un ami du CHAMPION\n"
	.string "d'ARENE vivait là-bas.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom_FR::
	.string "T'as beaucoup d'amis?\p"
	.string "C'est sympa de se connecter\n"
	.string "avec ses copains.\p"
	.string "Mais qui sait? En visitant souvent\n"
	.string "la SALLE UNION, tu pourrais\p"
	.string "peut-être tomber sur de nouveaux\n"
	.string "DRESSEURS et t'en faire des amis.\p"
	.string "Je pense vraiment que ça vaut le\n"
	.string "coup d'y aller souvent.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves_FR::
	.string "Les POKéMON peuvent apprendre des\n"
	.string "techniques même après avoir annulé\l"
	.string "une évolution.\p"
	.string "On peut lancer une évolution après\n"
	.string "avoir appris une technique!!!$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland_FR::
	.string "LEO: Hé, tu m'as fait attendre!\n"
	.string "On part pour l'ILE 1?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet_FR::
	.string "Non? Toujours pas?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo_FR::
	.string "Allez, c'est parti!$"

