CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked_DE::
	.string "Ich wollte die ARENA der\n"
	.string "ZINNOBERINSEL besuchen,\l"
	.string "aber die Türen sind verschlossen.\l"
	.string "Es muss irgendwo einen\l"
	.string "Schlüssel geben.\p"
	.string "Vielleicht in dieser abgebrannten\n"
	.string "Villa?\p"
	.string "Der Freund des ARENALEITERs\n"
	.string "hat dort gewohnt.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom_DE::
	.string "Hast du viele Freunde?\p"
	.string "Sich mit seinen nahen Freunden\n"
	.string "via Link-Kabel treffen macht\l"
	.string "Spaß!\l"
	.string "Aber warst du schon im\l"
	.string "KONNEX-KLUB?\p"
	.string "Wer weiß, vielleicht schließt du\n"
	.string "dort neue Freundschaften?\p"
	.string "Ich denke ein Besuch im\n"
	.string "KONNEX-KLUB ist seine\l"
	.string "Zeit wert.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves_DE::
	.string "Brichst du ihre Entwicklung ab,\n"
	.string "dann können deine POKéMON\l"
	.string "dennoch weitere Attacken lernen.\p"
	.string "Die weitere Entwicklung kann warten,\n"
	.string "bis sie neue Attacken gelernt\l"
	.string "haben!$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland_DE::
	.string "BILL: Du hast mich warten lassen!\n"
	.string "Bist du bereit, nach EILAND EINS\l"
	.string "aufzubrechen?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet_DE::
	.string "Oh, du bist noch nicht bereit?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo_DE::
	.string "Nun gut!\n"
	.string "Leinen los!$"

