PokemonTower_2F_Text_RivalIntro_FR::
	.string "{RIVAL}: Hé, {PLAYER}!\n"
	.string "Qu'est-ce que tu fais là?\l"
	.string "Tes POKéMON sont pas morts?\p"
	.string "Je peux quand même les mettre\n"
	.string "KO! Aucun problème!$"

PokemonTower_2F_Text_RivalDefeat_FR::
	.string "Hein?\n"
	.string "Saleté, va!\p"
	.string "Je ne jouais pas sérieusement!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory_FR::
	.string "{RIVAL}“あーあ‥！\n"
	.string "ほんとに　くたばっちまったぞ！\l"
	.string "よわいなー！\l"
	.string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle_FR::
	.string "Où en est ton POKéDEX?\n"
	.string "Je viens de capturer un OSSELAIT!\p"
	.string "Je n'ai pas encore trouvé\n"
	.string "d'OSSATUEUR!\p"
	.string "Je crois qu'il n'en reste plus!\p"
	.string "Je dois y aller! J'ai du\n"
	.string "pain sur la planche!\p"
	.string "Tchao!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts_FR::
	.string "Nous ne pouvons pas identifier\n"
	.string "les SPECTRES!\p"
	.string "Un SCOPE SYLPHE pourrait les\n"
	.string "démasquer.$"

