PokemonTower_2F_Text_RivalIntro_IT::
    .string "{RIVAL}: Ehi che fai qui, {PLAYER}!\n"
    .string "I tuoi POKéMON non sono morti!\p"
    .string "Però li posso sconfiggere!\n"
    .string "In guardia!$"

PokemonTower_2F_Text_RivalDefeat_IT::
    .string "Cosa?\n"
    .string "Brutta puzzola!\p"
    .string "Ti ho sottovalutato!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory_IT::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle_IT::
    .string "Com'è messo il tuo POKéDEX?\n"
    .string "Io ho un CUBONE!\p"
    .string "Ma non ho ancora trovato un\n"
    .string "MAROWAK!\p"
    .string "Credo non ce ne siano più! Beh,\n"
    .string "meglio che vada, ho un sacco di\l"
    .string "cose da fare!\p"
    .string "Ci becchiamo in giro!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts_IT::
    .string "Non siamo riusciti a identificare\n"
    .string "gli spettri!\p"
    .string "Ci vorrebbe una SPETTROSONDA!\n"
    .string "Le producono alla SILPH.$"

