SSAnne_1F_Corridor_Text_LeStrongSilentType_ES::
    .string "¡Bonjour!\n"
    .string "¡Soy el camarero de este barco!\p"
    .string "¡Encantado de servirte en todo\n"
    .string "lo que quieras!\p"
    .string "Tienes cara de ser una persona\n"
    .string "fuerte y discreta.$"

SSAnne_1F_Corridor_Text_PassengersAreRestless_ES::
    .string "¡Los pasajeros se están\n"
    .string "impacientando!\p"
    .string "¡Los que están más aburridos\n"
    .string "podrían retarte!$"
