SSAnne_1F_Corridor_Text_LeStrongSilentType_IT::
    .string "Bonjour! Je suis il cameriere di\n"
    .string "questa nave!\p"
    .string "Sarò molto lieto di servirle\n"
    .string "qualunque cosa!\p"
    .string "Ah!\n"
    .string "Très bien!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless_IT::
    .string "I passeggeri sono instancabili!\p"
    .string "Qualcuno tra i più annoiati\n"
    .string "potrebbe sfidarti!$"

