CeruleanCity_Gym_Text_MistyIntro_DE::
	.string "Du musst neu sein, ich habe dich\n"
	.string "noch nie gesehen!\p"
	.string "Wenn ein TRAINER zum Profi werden\n"
	.string "möchte, muss er sich eine POKéMON-\l"
	.string "TAKTIK erarbeiten!\p"
	.string "Auf welche Weise fängst du deine\n"
	.string "POKéMON?\p"
	.string "Meine Strategie basiert auf dem\n"
	.string "gnadenlosen Offensiv-Einsatz von\l"
	.string "WASSER-POKéMON!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03_DE::
	.string "TM03 ist die AQUAWELLE!\p"
	.string "WASSER-POKéMON können diese\n"
	.string "Attacke erlernen!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge_DE::
	.string "Der QUELLORDEN lässt alle POKéMON\n"
	.string "bis Level 30 deinen Befehlen\l"
	.string "gehorchen!\p"
	.string "Sogar Außenseiter gehorchen dir!\p"
	.string "Deine POKéMON können den\n"
	.string "ZERSCHNEIDER nun jederzeit \l"
	.string "einsetzen!\p"
	.string "Du kannst kleine Büsche zerhacken\n"
	.string "und so neue Wege freilegen!\p"
	.string "Zu guter Letzt schenke ich dir\n"
	.string "noch meine Lieblings-TM!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty_DE::
	.string "{PLAYER} erhält\n"
	.string "TM03!$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis_DE::
	.string "Du hast momentan keinen Platz für\n"
	.string "mein Geschenk!$"

CeruleanCity_Gym_Text_MistyDefeat_DE::
	.string "Wow!\n"
	.string "Du bist sehr gut!\p"
	.string "Alles klar!\p"
	.string "Ich überlasse dir den QUELLORDEN\n"
	.string "als Zeichen deines Triumphes!$"

CeruleanCity_Gym_Text_DianaIntro_DE::
	.string "Wie? Du?\n"
	.string "Ich bin schon zu gut für dich!\p"
	.string "MISTY muss sich nicht mit dir\n"
	.string "abgeben!$"

CeruleanCity_Gym_Text_DianaDefeat_DE::
	.string "Ich bin überwältigt!$"

CeruleanCity_Gym_Text_DianaPostBattle_DE::
	.string "Du musst dich anderen TRAINERn\n"
	.string "stellen, um herauszufinden, wie gut\l"
	.string "du bist.$"

CeruleanCity_Gym_Text_LuisIntro_DE::
	.string "Platsch!\p"
	.string "Ich bin dein erster Gegner!\n"
	.string "Es geht los!$"

CeruleanCity_Gym_Text_LuisDefeat_DE::
	.string "Das darf nicht wahr sein!$"

CeruleanCity_Gym_Text_LuisPostBattle_DE::
	.string "MISTY verbessert stets ihr Können!\p"
	.string "Jemand wie du hat keine Chance,\n"
	.string "sie zu besiegen!$"

CeruleanCity_Gym_Text_GymGuyAdvice_DE::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Ich habe einen Tipp für dich!\p"
	.string "MISTY, die ARENALEITERIN, kämpft\n"
	.string "mit WASSER-POKéMON!\p"
	.string "Du kannst ihnen das Wasser mit\n"
	.string "PFLANZEN-POKéMON entziehen!\p"
	.string "ELEKTRO-POKéMON dürften sich auch\n"
	.string "als nützlich erweisen!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam_DE::
	.string "Du hast MISTY besiegt! Habe ich es\n"
	.string "nicht gesagt?\p"
	.string "Glaub mir, wir beide bilden ein\n"
	.string "sehr gutes Team!$"

CeruleanCity_Gym_Text_GymStatue_DE::
	.string "AZURIA POKéMON-ARENA\n"
	.string "LEITUNG: MISTY\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon_DE::
	.string "AZURIA POKéMON-ARENA\n"
	.string "LEITUNG: MISTY\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

