CeruleanCity_Gym_Text_MistyIntro_IT::
    .string "Ciao! Non t'ho mai visto da queste\n"
    .string "parti!\p"
    .string "Gli ALLENATORI professionisti\n"
    .string "devono avere una strategia per\l"
    .string "i loro POKéMON!\p"
    .string "Come ti comporti quando catturi i\n"
    .string "POKéMON?\p"
    .string "La mia tattica è di attacco\n"
    .string "totale con POKéMON di tipo\l"
    .string "ACQUA!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03_IT::
    .string "La MT03 insegna IDROPULSAR!\p"
    .string "Usala sui POKéMON di tipo ACQUA!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge_IT::
    .string "Con la MEDAGLIA CASCATA tutti i\n"
    .string "POKéMON fino al livello 30 ti\l"
    .string "obbediranno…\p"
    .string "…anche quelli ottenuti\n"
    .string "negli scambi!\p"
    .string "Inoltre potrai usare TAGLIO anche\n"
    .string "fuori dalla lotta!\p"
    .string "Puoi tagliare i piccoli arbusti per\n"
    .string "aprire nuovi passaggi!\p"
    .string "Ti do anche la mia MT preferita!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty_IT::
    .string "{PLAYER} riceve\n"
    .string "la MT03!$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis_IT::
    .string "Fai spazio per questo!$"

CeruleanCity_Gym_Text_MistyDefeat_IT::
    .string "Wow!\n"
    .string "Sei troppo forte!\p"
    .string "Molto bene!\p"
    .string "La MEDAGLIA CASCATA indicherà che\n"
    .string "mi hai sconfitto!$"

CeruleanCity_Gym_Text_DianaIntro_IT::
    .string "Sono troppo forte per te!\p"
    .string "MISTY non si dovrà neppure\n"
    .string "scomodare!$"

CeruleanCity_Gym_Text_DianaDefeat_IT::
    .string "Mi hai sconfitto!$"

CeruleanCity_Gym_Text_DianaPostBattle_IT::
    .string "Devi misurarti con altri ALLENATORI\n"
    .string "per vedere quanto vali davvero.$"

CeruleanCity_Gym_Text_LuisIntro_IT::
    .string "Splash!\p"
    .string "Sono il primo!\n"
    .string "In guardia!$"

CeruleanCity_Gym_Text_LuisDefeat_IT::
    .string "Non può essere!$"

CeruleanCity_Gym_Text_LuisPostBattle_IT::
    .string "MISTY migliora continuamente!\p"
    .string "Non perderà certo contro di te!$"

CeruleanCity_Gym_Text_GymGuyAdvice_IT::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "Un consiglio!\p"
    .string "Il CAPOPALESTRA, MISTY, usa\n"
    .string "POKéMON di tipo ACQUA ed è\l"
    .string "infallibile!\p"
    .string "Ma puoi assorbire l'acqua usando\n"
    .string "POKéMON di tipo ERBA!\p"
    .string "O fulminarli con l'elettricità!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam_IT::
    .string "Hai battuto MISTY!\n"
    .string "Te l'avevo detto!\p"
    .string "Tu e io insieme facciamo una bella\n"
    .string "squadra!$"

CeruleanCity_Gym_Text_GymStatue_IT::
    .string "PALESTRA di CELESTOPOLI:\n"
    .string "MISTY\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon_IT::
    .string "PALESTRA di CELESTOPOLI:\n"
    .string "MISTY\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

