Text_DreamEaterTeach_DE::
	.string "Gäääähn!\n"
	.string "Ich bin wohl eingenickt!\p"
	.string "Ich habe geträumt, dass TRAUMATO\n"
	.string "meine Träume fressen wollte!\p"
	.string "Und…\n"
	.string "Ich erlernte das Fressen von\l"
	.string "Träumen…\p"
	.string "Das ist unheimlich!\p"
	.string "Lass mich einem deiner POKéMON\n"
	.string "TRAUMFRESSER beibringen,\l"
	.string "damit ich es vergessen kann.$"

Text_DreamEaterDeclined_DE::
	.string "… schnarch…$"

Text_DreamEaterWhichMon_DE::
	.string "Welches POKéMON soll\n"
	.string "TRAUMFRESSER erlernen?$"

Text_DreamEaterTaught_DE::
	.string "… ZZZ…\n"
	.string "Ich… kann nicht mehr… essen$"

PewterCity_Text_ClefairyCameFromMoon_DE::
	.string "Gerüchten zufolge sollen die\n"
	.string "PIEPI vom Mond stammen!\p"
	.string "Nachdem der MONDSTEIN auf den\n"
	.string "MONDBERG fiel, sind sie erstmals\l"
	.string "aufgetaucht!$"

PewterCity_Text_BrockOnlySeriousTrainerHere_DE::
	.string "Hier gibt es nur wenige ernsthafte\n"
	.string "POKéMON TRAINER!\p"
	.string "Aber ROCKO, der ARENALEITER von\n"
	.string "MARMORIA CITY, versteht sein\l"
	.string "Geschäft!$"

PewterCity_Text_DidYouCheckOutMuseum_DE::
	.string "Warst du schon im MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing_DE::
	.string "Waren die Fossilien vom MONDBERG\n"
	.string "nicht einmalig?$"

PewterCity_Text_ReallyYouHaveToGo_DE::
	.string "Wirklich nicht?\n"
	.string "Es ist aber einen Besuch wert!$"

PewterCity_Text_ThisIsTheMuseum_DE::
	.string "Es ist gleich da drüben!\p"
	.string "Man muss zwar Eintritt bezahlen,\n"
	.string "aber das ist es wert!$"

PewterCity_Text_DoYouKnowWhatImDoing_DE::
	.string "Pst!\n"
	.string "Weißt du, was ich hier mache?$"

PewterCity_Text_ThatsRightItsHardWork_DE::
	.string "Stimmt!\n"
	.string "Es ist harte Arbeit!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut_DE::
	.string "Ich versprühe SCHUTZ, um POKéMON\n"
	.string "von meinem Garten fernzuhalten!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe_DE::
	.string "Du bist TRAINER?\p"
	.string "ROCKO ist ständig auf der Suche\n"
	.string "nach neuen Herausforderern!\l"
	.string "Folge mir!$"

PewterCity_Text_GoTakeOnBrock_DE::
	.string "Wenn du genug Mumm hast, dann\n"
	.string "versuche dich an ROCKO!$"

PewterCity_Text_TrainerTipsEarningEXP_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "Unabhängig von der Dauer seines\n"
	.string "Einsatzes erhält jedes POKéMON für\l"
	.string "die Teilnahme an einem Kampf\l"
	.string "Erfahrungspunkte, E.-Punkte! $"

PewterCity_Text_CallPoliceIfInfoOnThieves_DE::
	.string "ACHTUNG!\p"
	.string "Diebe haben POKéMON-Fossilien vom\n"
	.string "MONDBERG gestohlen!\p"
	.string "Wenn Sie sachdienliche Hinweise\n"
	.string "haben, wenden Sie sich bitte an die\l"
	.string "Polizei in MARMORIA CITY!$"

PewterCity_Text_MuseumOfScience_DE::
	.string "MARMORIA CITY\n"
	.string "WISSENSCHAFTS-MUSEUM$"

PewterCity_Text_GymSign_DE::
	.string "MARMORIA CITY POKéMON-ARENA\n"
	.string "ARENALEITER: ROCKO\l"
	.string "Der Steinharte POKéMON TRAINER!$"

PewterCity_Text_CitySign_DE::
	.string "MARMORIA CITY\n"
	.string "Die steingraue Stadt!$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure_DE::
	.string "あッれー！\n"
	.string "その　ジムバッジ‥‥\l"
	.string "すげえな　タケシに　かったのかよ！\p"
	.string "かんどう　したから\n"
	.string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully_DE::
	.string "なかには　きのみが　はいってるぜ\p"
	.string "やくに　たつ　きのみも\n"
	.string "はいって　いるから\l"
	.string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn_DE::
	.string "ポケモンに　きのみを\n"
	.string "もたせて　おけば\l"
	.string "たたかっている　ときに\l"
	.string "かってに　つかって　くれるんだ\p"
	.string "キズぐすり　とか　どくけし　より\n"
	.string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer_DE::
	.string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis_DE::
	.string "Ich bin froh, dass ich dich\n"
	.string "erwische. Ich bin der\l"
	.string "ASSISTENT von PROF. EICH.\p"
	.string "Ich wurde gebeten, dir das hier zu\n"
	.string "bringen, also nimm es bitte.$"

PewterCity_Text_ReceivedRunningShoesFromAide_DE::
	.string "{PLAYER} hat die TURBOTRETER\n"
	.string "vom ASSISTENTEN erhalten.$"

PewterCity_Text_SwitchedShoesWithRunningShoes_DE::
	.string "{PLAYER} zieht die TURBOTRETER an.$"

PewterCity_Text_ExplainRunningShoes_DE::
	.string "Drücke den B-Knopf, um zu\n"
	.string "rennen. Aber nur, wenn Platz ist!$"

PewterCity_Text_MustBeGoingBackToLab_DE::
	.string "Nun, ich muss ins LABOR zurück.\p"
	.string "Bis die Tage!$"

PewterCity_Text_RunningShoesLetterFromMom_DE::
	.string "Ein Brief ist dabei…\p"
	.string "Hallo {PLAYER}!\p"
	.string "Hier ein Paar TURBOTRETER für\n"
	.string "meinen geliebten TRAINER.\p"
	.string "Denk daran, ich drücke dir stets\n"
	.string "die Daumen! Gib nie auf!\p"
	.string "Deine Mama!$"

