Text_DreamEaterTeach_FR::
	.string "(Bâiiiille)\n"
	.string "J'ai dû m'endormir au soleil.\p"
	.string "J'ai rêvé qu'un SOPORIFIK\n"
	.string "dévorait mes rêves…\p"
	.string "Et j'ai appris comment\n"
	.string "dévorer les rêves…\p"
	.string "C'est dingue ça!\p"
	.string "Laisse-moi l'apprendre aussi\n"
	.string "à un POKéMON.$"

Text_DreamEaterDeclined_FR::
	.string "… Ronfl…$"

Text_DreamEaterWhichMon_FR::
	.string "A quel POKéMON enseigner\n"
	.string "DEVOREVE?$"

Text_DreamEaterTaught_FR::
	.string "… Zzz… Peux…\n"
	.string "plus… rien… manger…$"

PewterCity_Text_ClefairyCameFromMoon_FR::
	.string "On raconte que les MELOFEE sont\n"
	.string "des habitants de la lune!\p"
	.string "Ils sont apparus après la chute\n"
	.string "de la PIERRE LUNE sur le MONT\l"
	.string "SELENITE.$"

PewterCity_Text_BrockOnlySeriousTrainerHere_FR::
	.string "Il n'y a pas vraiment de\n"
	.string "DRESSEURS sérieux par ici.\p"
	.string "Ils s'intéressent surtout aux\n"
	.string "INSECTES, rien de passionnant.\p"
	.string "Mais PIERRE d'ARGENTA n'est\n"
	.string "pas comme ça, pas du tout.$"

PewterCity_Text_DidYouCheckOutMuseum_FR::
	.string "T'as déjà visité le MUSEE?$"

PewterCity_Text_WerentThoseFossilsAmazing_FR::
	.string "Les fossiles du MONT SELENITE sont\n"
	.string "intéressants, hein?$"

PewterCity_Text_ReallyYouHaveToGo_FR::
	.string "Non?\n"
	.string "Mais il faut y aller, voyons!$"

PewterCity_Text_ThisIsTheMuseum_FR::
	.string "C'est par là! L'entrée est\n"
	.string "payante mais ça vaut l'coup!$"

PewterCity_Text_DoYouKnowWhatImDoing_FR::
	.string "Psssst!\n"
	.string "Tu sais c'que j'fais?$"

PewterCity_Text_ThatsRightItsHardWork_FR::
	.string "Ah bon?\n"
	.string "OK.$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut_FR::
	.string "Je vaporise du REPOUSSE\n"
	.string "pour éloigner les POKéMON\p"
	.string "de mon jardin!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe_FR::
	.string "T'es DRESSEUR?\p"
	.string "PIERRE cherche un adversaire!\n"
	.string "Suis-moi!$"

PewterCity_Text_GoTakeOnBrock_FR::
	.string "Si tu t'en sens capable, tu devrais\n"
	.string "aller affronter PIERRE!$"

PewterCity_Text_TrainerTipsEarningEXP_FR::
	.string "ASTUCE\p"
	.string "Chaque POKéMON prenant part au\n"
	.string "combat, même pendant une seconde,\p"
	.string "gagne des points EXP.$"

PewterCity_Text_CallPoliceIfInfoOnThieves_FR::
	.string "AVIS!\p"
	.string "On nous signale des voleurs de\n"
	.string "fossiles de POKéMON au\p"
	.string "MONT SELENITE.\p"
	.string "N'hésitez pas à contacter la\n"
	.string "POLICE d'ARGENTA!$"

PewterCity_Text_MuseumOfScience_FR::
	.string "MUSEE DES SCIENCES d'ARGENTA$"

PewterCity_Text_GymSign_FR::
	.string "ARENE POKéMON d'ARGENTA\n"
	.string "CHAMPION: PIERRE\l"
	.string "Le DRESSEUR dur comme la pierre!$"

PewterCity_Text_CitySign_FR::
	.string "ARGENTA\n"
	.string "Le mat et le gris de la roche$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure_FR::
	.string "あッれー！\n"
	.string "その　ジムバッジ‥‥\l"
	.string "すげえな　タケシに　かったのかよ！\p"
	.string "かんどう　したから\n"
	.string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully_FR::
	.string "なかには　きのみが　はいってるぜ\p"
	.string "やくに　たつ　きのみも\n"
	.string "はいって　いるから\l"
	.string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn_FR::
	.string "ポケモンに　きのみを\n"
	.string "もたせて　おけば\l"
	.string "たたかっている　ときに\l"
	.string "かってに　つかって　くれるんだ\p"
	.string "キズぐすり　とか　どくけし　より\n"
	.string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer_FR::
	.string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis_FR::
	.string "Content de te voir. Je suis\n"
	.string "l'ASSISTANT du PROF. CHEN.\p"
	.string "On m'a demandé de te donner\n"
	.string "ça, alors voilà…$"

PewterCity_Text_ReceivedRunningShoesFromAide_FR::
	.string "{PLAYER} reçoit les CHAUSSURES DE\n"
	.string "SPORT de l'ASSISTANT.$"

PewterCity_Text_SwitchedShoesWithRunningShoes_FR::
	.string "{PLAYER} enlève ses chaussures pour\n"
	.string "mettre les CHAUSSURES DE SPORT.$"

PewterCity_Text_ExplainRunningShoes_FR::
	.string "Appuie sur le bouton B\n"
	.string "pour courir.\p"
	.string "Mais seulement où tu as la place\n"
	.string "pour ça!$"

PewterCity_Text_MustBeGoingBackToLab_FR::
	.string "Bon, je dois retourner au LABO.\p"
	.string "Au revoir.$"

PewterCity_Text_RunningShoesLetterFromMom_FR::
	.string "Il y a un mot avec:\p"
	.string "{PLAYER},\p"
	.string "Voilà une paire de CHAUSSURES\n"
	.string "DE SPORT mon petit bouchon.\p"
	.string "Bon courage, \n"
	.string "ta maman.$"

