Text_DreamEaterTeach_ES::
    .string "¡Uaaaahuuh...!\n"
    .string "Debo de haberme dormido al sol...\p"
    .string "He soñado que un DROWZEE\n"
    .string "se comía mi sueño.\p"
    .string "¡¡Y he aprendido a comer sueños!!\n"
    .string "¡¡¡Qué miedo!!!\p"
    .string "¿Quieres que se lo enseñe\n"
    .string "a un POKéMON?$"

Text_DreamEaterDeclined_ES::
    .string "Pues vaya... Zz... Zzzzzz...$"

Text_DreamEaterWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe COME SUEÑOS?$"

Text_DreamEaterTaught_ES::
    .string "Yo... Ya no puedo comer más...\n"
    .string "Zz... Zzzzz...$"

PewterCity_Text_ClefairyCameFromMoon_ES::
    .string "¡Dicen que los CLEFAIRY vinieron\n"
    .string "de la Luna!\p"
    .string "¡Aparecieron tras la caída de\n"
    .string "varias PIEDRAS LUNARES\l"
    .string "en el MT. MOON!$"

PewterCity_Text_BrockOnlySeriousTrainerHere_ES::
    .string "¡No hay muchos ENTRENADORES\n"
    .string "de POKéMON por aquí!\p"
    .string "¡Todos parecen CAZABICHOS, salvo\n"
    .string "BROCK, del GIMNASIO de PLATEADA!$"

PewterCity_Text_DidYouCheckOutMuseum_ES::
    .string "¿Has estado en el MUSEO?$"

PewterCity_Text_WerentThoseFossilsAmazing_ES::
    .string "¿No eran geniales esos fósiles\n"
    .string "del MT. MOON?$"

PewterCity_Text_ReallyYouHaveToGo_ES::
    .string "¿De verdad?\n"
    .string "¡Pues tienes que ir!$"

PewterCity_Text_ThisIsTheMuseum_ES::
    .string "¡Está aquí mismo!\p"
    .string "¡Hay que pagar para entrar, pero\n"
    .string "vale la pena! ¡Hasta luego!$"

PewterCity_Text_DoYouKnowWhatImDoing_ES::
    .string "¡Pssss!\n"
    .string "¿Sabes lo que estoy haciendo?$"

PewterCity_Text_ThatsRightItsHardWork_ES::
    .string "¡Eso es!\n"
    .string "¡Un trabajo tremendo!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut_ES::
    .string "¡Utilizo el REPELENTE para echar\n"
    .string "de mi jardín a los POKéMON!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe_ES::
    .string "¿Entrenas POKéMON?\p"
    .string "¡BROCK está buscando a nuevos\n"
    .string "adversarios! ¡Sígueme!$"

PewterCity_Text_GoTakeOnBrock_ES::
    .string "¡Si eres valiente, pelearás contra\n"
    .string "BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Todo POKéMON que luche en un\n"
    .string "combate ganará EXPERIENCIA!$"

PewterCity_Text_CallPoliceIfInfoOnThieves_ES::
    .string "¡AVISO!\p"
    .string "¡Unos ladrones han robado fósiles\n"
    .string "de POKéMON del MT. MOON!\p"
    .string "¡Avisad a la POLICÍA de CIUDAD\n"
    .string "PLATEADA si sabéis algo!$"

PewterCity_Text_MuseumOfScience_ES::
    .string "MUSEO DE LA CIENCIA DE\n"
    .string "CIUDAD PLATEADA$"

PewterCity_Text_GymSign_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de PLATEADA: BROCK\l"
    .string "¡Es fuerte como una roca!$"

PewterCity_Text_CitySign_ES::
    .string "CIUDAD PLATEADA\n"
    .string "Una ciudad de roca grisácea.$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure_ES::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully_ES::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn_ES::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer_ES::
    .string "¡Hola, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis_ES::
    .string "Menos mal que te pillo, soy\n"
    .string "AYUDANTE del PROF. OAK.\p"
    .string "Me han pedido que te diera una\n"
    .string "cosa, aquí tienes.$"

PewterCity_Text_ReceivedRunningShoesFromAide_ES::
    .string "¡{PLAYER} recibió las DEPORTIVAS\n"
    .string "de manos del AYUDANTE!$"

PewterCity_Text_SwitchedShoesWithRunningShoes_ES::
    .string "{PLAYER} se ha puesto las\n"
    .string "DEPORTIVAS.$"

PewterCity_Text_ExplainRunningShoes_ES::
    .string "Para correr, pulsa el Botón B,\n"
    .string "¡pero sólo donde haya sitio!$"

PewterCity_Text_MustBeGoingBackToLab_ES::
    .string "Bueno, tengo que volver al\n"
    .string "LABORATORIO.\p"
    .string "Hasta luego.$"

PewterCity_Text_RunningShoesLetterFromMom_ES::
    .string "Vienen con una notita...\p"
    .string "{PLAYER}, cielo:\p"
    .string "Aquí tienes un par de DEPORTIVAS,\n"
    .string "adorable valiente.\p"
    .string "Piensa que siempre voy a estar\n"
    .string "aquí para apoyarte, ¡ánimo!\p"
    .string "Mamá$"
