Text_DreamEaterTeach_IT::
    .string "Ahou!\n"
    .string "Devo essermi addormentato al sole.\p"
    .string "Ho sognato che un DROWZEE si\n"
    .string "mangiava i miei sogni.\p"
    .string "E… ho imparato anch'io a\n"
    .string "mangiare i sogni!\p"
    .string "Mi faccio paura da solo!\p"
    .string "Vuoi che insegni questa capacità\n"
    .string "ad uno dei tuoi POKéMON?$"

Text_DreamEaterDeclined_IT::
    .string "…Ronf ronf…$"

Text_DreamEaterWhichMon_IT::
    .string "A quale POKéMON vuoi che insegni\n"
    .string "MANGIASOGNI?$"

Text_DreamEaterTaught_IT::
    .string "…ZZZ…\n"
    .string "…Sono… sazio…$"

PewterCity_Text_ClefairyCameFromMoon_IT::
    .string "Pare che CLEFAIRY venga dalla\n"
    .string "luna!\p"
    .string "È apparso quando la PIETRALUNARE\n"
    .string "è caduta sul MONTE LUNA!$"

PewterCity_Text_BrockOnlySeriousTrainerHere_IT::
    .string "Non ci sono tanti ALLENATORI di\n"
    .string "POKéMON seri qui!\p"
    .string "Sono tutti dei PIGLIAMOSCHE!\p"
    .string "Si salva solo BROCK della PALESTRA\n"
    .string "di PLUMBEOPOLI!$"

PewterCity_Text_DidYouCheckOutMuseum_IT::
    .string "Hai già visitato il MUSEO?$"

PewterCity_Text_WerentThoseFossilsAmazing_IT::
    .string "Interessanti i fossili trovati sul\n"
    .string "MONTE LUNA, no?$"

PewterCity_Text_ReallyYouHaveToGo_IT::
    .string "No?\n"
    .string "Devi andarci assolutamente!$"

PewterCity_Text_ThisIsTheMuseum_IT::
    .string "Questo è il MUSEO!\p"
    .string "Si paga per entrare, ma ne vale la\n"
    .string "pena! Ciao!$"

PewterCity_Text_DoYouKnowWhatImDoing_IT::
    .string "Pssss!\n"
    .string "Sai cosa faccio?$"

PewterCity_Text_ThatsRightItsHardWork_IT::
    .string "Esatto!\n"
    .string "È un lavoro duro!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut_IT::
    .string "Spruzzo il REPELLENTE per tenere\n"
    .string "lontano i POKéMON dal mio giardino!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe_IT::
    .string "Sei un ALLENATORE, vero?\p"
    .string "BROCK sta cercando nuovi sfidanti.\n"
    .string "Vieni!$"

PewterCity_Text_GoTakeOnBrock_IT::
    .string "Se hai stoffa, allora vai a\n"
    .string "sfidare BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP_IT::
    .string "CONSIGLI UTILI\p"
    .string "Tutti i POKéMON impegnati in una\n"
    .string "lotta, seppure breve, crescono in\l"
    .string "ESPERIENZA!$"

PewterCity_Text_CallPoliceIfInfoOnThieves_IT::
    .string "AVVISO:\p"
    .string "Sono stati rubati i fossili POKéMON\n"
    .string "dal MONTE LUNA!\p"
    .string "Chiunque abbia informazioni chiami\n"
    .string "la POLIZIA di PLUMBEOPOLI!$"

PewterCity_Text_MuseumOfScience_IT::
    .string "MUSEO della SCIENZA di\n"
    .string "PLUMBEOPOLI$"

PewterCity_Text_GymSign_IT::
    .string "CAPOPALESTRA di PLUMBEOPOLI:\n"
    .string "BROCK\p"
    .string "L'ALLENATORE di POKéMON più forte\n"
    .string "di una roccia!$"

PewterCity_Text_CitySign_IT::
    .string "PLUMBEOPOLI\n"
    .string "Città grigia come il piombo$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure_IT::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully_IT::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn_IT::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer_IT::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis_IT::
    .string "Finalmente ti ho trovato!\n"
    .string "Sono l'ASSISTENTE del PROF. OAK.\p"
    .string "Ho qualcosa da consegnarti. Tieni!$"

PewterCity_Text_ReceivedRunningShoesFromAide_IT::
    .string "{PLAYER} riceve\n"
    .string "le SCARPE da CORSA.$"

PewterCity_Text_SwitchedShoesWithRunningShoes_IT::
    .string "{PLAYER} si cambia le scarpe e\n"
    .string "mette le SCARPE da CORSA.$"

PewterCity_Text_ExplainRunningShoes_IT::
    .string "Dove c'è abbastanza spazio, puoi\n"
    .string "correre premendo il pulsante B!$"

PewterCity_Text_MustBeGoingBackToLab_IT::
    .string "Beh, ora devo tornare al\n"
    .string "LABORATORIO.\p"
    .string "Ci vediamo!$"

PewterCity_Text_RunningShoesLetterFromMom_IT::
    .string "C'è un biglietto…\p"
    .string "{PLAYER}, pulcino mio!\p"
    .string "Ti ho mandato un paio di SCARPE\n"
    .string "da CORSA.\p"
    .string "Sono lontana, ma ti penso sempre.\n"
    .string "E non smetto un minuto di fare il\l"
    .string "tifo per te!\p"
    .string "Baci,\n"
    .string "la tua mamma$"

