PokemonTower_3F_Text_HopeIntro_FR::
	.string "Urrg… Awaa…\n"
	.string "Huhu… graa…$"

PokemonTower_3F_Text_HopeDefeat_FR::
	.string "Ha!\n"
	.string "Je suis sauvée!$"

PokemonTower_3F_Text_HopePostBattle_FR::
	.string "Un SPECTRE est identifiable avec\n"
	.string "un SCOPE SYLPHE.$"

PokemonTower_3F_Text_CarlyIntro_FR::
	.string "Kekeke…\n"
	.string "Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat_FR::
	.string "Hmm?\n"
	.string "Qu'est-ce que je fais là?$"

PokemonTower_3F_Text_CarlyPostBattle_FR::
	.string "Pardon!\n"
	.string "J'étais possédée!$"

PokemonTower_3F_Text_PatriciaIntro_FR::
	.string "VADE RETRO!\n"
	.string "Esprit infernal!$"

PokemonTower_3F_Text_PatriciaDefeat_FR::
	.string "Pfiou!\n"
	.string "L'esprit s'en est allé!$"

PokemonTower_3F_Text_PatriciaPostBattle_FR::
	.string "Mes amies étaient aussi possédées!$"

