PokemonTower_3F_Text_HopeIntro_ES::
    .string "Urrg... aaa...\n"
    .string "Uuuu... graa...$"

PokemonTower_3F_Text_HopeDefeat_ES::
    .string "¡Uauu!\n"
    .string "¡Estoy salvada!$"

PokemonTower_3F_Text_HopePostBattle_ES::
    .string "Los GHOST son identificados con\n"
    .string "el SCOPE SILPH.$"

PokemonTower_3F_Text_CarlyIntro_ES::
    .string "Gaaaa...\n"
    .string "¡Gaaah!$"

PokemonTower_3F_Text_CarlyDefeat_ES::
    .string "¿Mmm?\n"
    .string "¿Pero qué hago?$"

PokemonTower_3F_Text_CarlyPostBattle_ES::
    .string "¡Perdona!\n"
    .string "¡Estaba fuera de mí!$"

PokemonTower_3F_Text_PatriciaIntro_ES::
    .string "¡Fuera, espíritu malvado!$"

PokemonTower_3F_Text_PatriciaDefeat_ES::
    .string "¡El espíritu se fue!$"

PokemonTower_3F_Text_PatriciaPostBattle_ES::
    .string "¡Mis amigos también estaban\n"
    .string "fuera de sí!$"
