PokemonTower_3F_Text_HopeIntro_DE::
	.string "Buu... huhu...\n"
	.string "Huhu... buu...$"

PokemonTower_3F_Text_HopeDefeat_DE::
	.string "Buu!\n"
	.string "Ich wurde erlöst!$"

PokemonTower_3F_Text_HopePostBattle_DE::
	.string "Das SILPH SCOPE kann GEISTER\n"
	.string "identifizieren!$"

PokemonTower_3F_Text_CarlyIntro_DE::
	.string "Buhuhuhu...\n"
	.string "Hui... buuh!$"

PokemonTower_3F_Text_CarlyDefeat_DE::
	.string "Hmm?\n"
	.string "Was mache ich hier?$"

PokemonTower_3F_Text_CarlyPostBattle_DE::
	.string "Tut mir Leid!\n"
	.string "Ich war besessen!$"

PokemonTower_3F_Text_PatriciaIntro_DE::
	.string "Verschwinde, böser Geist!$"

PokemonTower_3F_Text_PatriciaDefeat_DE::
	.string "Puh!\n"
	.string "Der Geist ist verschwunden!$"

PokemonTower_3F_Text_PatriciaPostBattle_DE::
	.string "Auch meine Freunde waren besessen!$"

