PokemonTower_3F_Text_HopeIntro_IT::
    .string "Urrg… Aaa…\n"
    .string "Uuuu… graa…$"

PokemonTower_3F_Text_HopeDefeat_IT::
    .string "Ah!\n"
    .string "Sono in salvo!$"

PokemonTower_3F_Text_HopePostBattle_IT::
    .string "Gli spettri si identificano con la\n"
    .string "SPETTROSONDA.$"

PokemonTower_3F_Text_CarlyIntro_IT::
    .string "Kikiki…\n"
    .string "Gaaah!$"

PokemonTower_3F_Text_CarlyDefeat_IT::
    .string "Mmm?\n"
    .string "Che sto facendo?$"

PokemonTower_3F_Text_CarlyPostBattle_IT::
    .string "Scusa!\n"
    .string "Ero posseduta!$"

PokemonTower_3F_Text_PatriciaIntro_IT::
    .string "Vattene, spirito maligno!$"

PokemonTower_3F_Text_PatriciaDefeat_IT::
    .string "Lo spirito se n'è andato!$"

PokemonTower_3F_Text_PatriciaPostBattle_IT::
    .string "Anche le altre persone\n"
    .string "erano possedute!$"

