Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough_FR::
	.string "Salut! Tu te rappelles?\n"
	.string "Je suis un assistant du PROF. CHEN!\p"
	.string "Si tu attrapes {STR_VAR_1} POKéMON\n"
	.string "différents, je suis censé t'offrir…\l"
	.string "{STR_VAR_2}!\p"
	.string "Alors {PLAYER}, as-tu attrapé au\n"
	.string "moins {STR_VAR_1} POKéMON différents?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo_FR::
	.string "Super! Tu as {STR_VAR_3} POKéMON\n"
	.string "différents!\p"
	.string "Félicitations!\n"
	.string "Voici ta récompense!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide_FR::
	.string "{PLAYER} obtient\n"
	.string "{STR_VAR_2}!$"

Route15_WestEntrance_2F_Text_ExplainExpShare_FR::
	.string "MULTI EXP est un objet qui\n"
	.string "doit être porté par un POKéMON.\p"
	.string "Les POKéMON de ton équipe se\n"
	.string "partageront les points d'EXP.\p"
	.string "après un combat. Même ceux\n"
	.string "qui n'ont pas combattu.$"

Route15_WestEntrance_2F_Text_LargeShiningBird_FR::
	.string "Vous regardez dans les jumelles…\p"
	.string "Un grand et bel oiseau vole vers\n"
	.string "la mer.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon_FR::
	.string "Vous regardez dans les jumelles…\p"
	.string "Vous voyez une petite île!$"

