SilphCo_9F_Text_YouShouldTakeQuickNap_DE::
	.string "Du siehst müde aus!\n"
	.string "Komm, ruhe dich kurz aus!$"

SilphCo_9F_Text_DontGiveUp_DE::
	.string "Gib nicht auf!$"

SilphCo_9F_Text_ThankYouSoMuch_DE::
	.string "Vielen, vielen Dank!$"

SilphCo_9F_Text_Grunt1Intro_DE::
	.string "Deine POKéMON scheinen dich sehr\n"
	.string "zu mögen!$"

SilphCo_9F_Text_Grunt1Defeat_DE::
	.string "Waaah!$"

SilphCo_9F_Text_Grunt1PostBattle_DE::
	.string "Hätte ich doch auch schon in\n"
	.string "deinem Alter als TRAINER begonnen!$"

SilphCo_9F_Text_EdIntro_DE::
	.string "Ich finde die Schwachstellen\n"
	.string "deiner POKéMON und besiege sie!$"

SilphCo_9F_Text_EdDefeat_DE::
	.string "Du hast mich besiegt!$"

SilphCo_9F_Text_EdPostBattle_DE::
	.string "Mach dir die Schwachstellen zu\n"
	.string "Nutze! Denke an die Elementklassen!$"

SilphCo_9F_Text_Grunt2Intro_DE::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_9F_Text_Grunt2Defeat_DE::
	.string "Oje!\n"
	.string "Ich wurde besiegt!$"

SilphCo_9F_Text_Grunt2PostBattle_DE::
	.string "Aber meine Brüder rächen mich!$"

SilphCo_9F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "8 OG$"

