SilphCo_9F_Text_YouShouldTakeQuickNap_ES::
    .string "¡Tienes cara de cansancio!\n"
    .string "¡Deberías echarte una siestecita!$"

SilphCo_9F_Text_DontGiveUp_ES::
    .string "¡No te rindas!$"

SilphCo_9F_Text_ThankYouSoMuch_ES::
    .string "¡Muchísimas gracias!$"

SilphCo_9F_Text_Grunt1Intro_ES::
    .string "¡Tus POKéMON parecen adorarte!$"

SilphCo_9F_Text_Grunt1Defeat_ES::
    .string "¡Buaah!$"

SilphCo_9F_Text_Grunt1PostBattle_ES::
    .string "Si yo hubiera empezado como\n"
    .string "ENTRENADOR a tu edad...$"

SilphCo_9F_Text_EdIntro_ES::
    .string "¡Tus POKéMON tienen puntos\n"
    .string "débiles! ¡Yo puedo verlos!$"

SilphCo_9F_Text_EdDefeat_ES::
    .string "¡Me has machacado!$"

SilphCo_9F_Text_EdPostBattle_ES::
    .string "¡Aprovechar sus puntos débiles\n"
    .string "funciona! ¡Piensa en los tipos!$"

SilphCo_9F_Text_Grunt2Intro_ES::
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat_ES::
    .string "¡Hermanos!\n"
    .string "¡He perdido!$"

SilphCo_9F_Text_Grunt2PostBattle_ES::
    .string "¡Mis hermanos me vengarán!$"

SilphCo_9F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P8$"
