SilphCo_9F_Text_YouShouldTakeQuickNap_IT::
    .string "Sembri a terra!\n"
    .string "Dovresti fare un pisolino!$"

SilphCo_9F_Text_DontGiveUp_IT::
    .string "Non arrenderti!$"

SilphCo_9F_Text_ThankYouSoMuch_IT::
    .string "Grazie infinite!$"

SilphCo_9F_Text_Grunt1Intro_IT::
    .string "I tuoi POKéMON ti adorano!$"

SilphCo_9F_Text_Grunt1Defeat_IT::
    .string "Bleeeh!$"

SilphCo_9F_Text_Grunt1PostBattle_IT::
    .string "Se solo avessi iniziato la carriera\n"
    .string "di ALLENATORE alla tua età…$"

SilphCo_9F_Text_EdIntro_IT::
    .string "I tuoi POKéMON hanno dei punti\n"
    .string "deboli! Li vedo!$"

SilphCo_9F_Text_EdDefeat_IT::
    .string "Mi hai abbattuto!$"

SilphCo_9F_Text_EdPostBattle_IT::
    .string "Sfruttare i punti deboli funziona!\n"
    .string "Cerca sempre di usare i POKéMON\l"
    .string "avvantaggiati contro i vari tipi!$"

SilphCo_9F_Text_Grunt2Intro_IT::
    .string "Sono uno dei 4 FRATELLI ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat_IT::
    .string "Fratelli!\n"
    .string "Ho perso!$"

SilphCo_9F_Text_Grunt2PostBattle_IT::
    .string "I miei fratelli mi vendicheranno!$"

SilphCo_9F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "8ºP$"

