SilphCo_9F_Text_YouShouldTakeQuickNap_FR::
	.string "Après tant d'efforts, tu\n"
	.string "devrais faire une sieste!$"

SilphCo_9F_Text_DontGiveUp_FR::
	.string "Courage!$"

SilphCo_9F_Text_ThankYouSoMuch_FR::
	.string "Merci mille fois!$"

SilphCo_9F_Text_Grunt1Intro_FR::
	.string "Tes POKéMON ont l'air de t'aimer!$"

SilphCo_9F_Text_Grunt1Defeat_FR::
	.string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle_FR::
	.string "Si j'avais commencé avec les\n"
	.string "POKéMON à ton âge…$"

SilphCo_9F_Text_EdIntro_FR::
	.string "Tes POKéMON ont des points faibles!\n"
	.string "Ah-ah!$"

SilphCo_9F_Text_EdDefeat_FR::
	.string "Non!\n"
	.string "J'ai perdu!$"

SilphCo_9F_Text_EdPostBattle_FR::
	.string "Jouer sur les points faibles est\n"
	.string "la clé! Pense aux différents types!$"

SilphCo_9F_Text_Grunt2Intro_FR::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat_FR::
	.string "Frères!\n"
	.string "J'suis nul!$"

SilphCo_9F_Text_Grunt2PostBattle_FR::
	.string "Mes frères me vengeront!$"

SilphCo_9F_Text_FloorSign_FR::
	.string "SYLPHE SARL.\n"
	.string "8ème étage.$"

