SSAnne_2F_Room3_Text_SeenMonsFerryPeople_ES::
    .string "¡Ah, sí! ¡Vi a unos POKéMON\n"
    .string "transportando a gente por el agua!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown_ES::
    .string "Los POKéMON pueden CORTAR\n"
    .string "pequeños arbustos.\p"
    .string "Pero ten en cuenta que CORTE\n"
    .string "es una técnica de MO.\p"
    .string "Una vez aprendida, cuesta mucho\n"
    .string "olvidarla.$"
