SSAnne_2F_Room3_Text_SeenMonsFerryPeople_FR::
	.string "Tiens! J'ai vu des POKéMON\n"
	.string "transporter des gens sur l'eau!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown_FR::
	.string "Les POKéMON peuvent couper des\n"
	.string "petits buissons avec COUPE.\p"
	.string "Mais n'oublie pas! COUPE est\n"
	.string "une CS.\p"
	.string "Une fois apprise, on ne peut pas\n"
	.string "facilement l'oublier.$"

