Route25_Text_JoeyIntro_DE::
	.string "Die TRAINER der Gegend kommen zum\n"
	.string "Üben hierher!$"

Route25_Text_JoeyDefeat_DE::
	.string "Du bist richtig gut!$"

Route25_Text_JoeyPostBattle_DE::
	.string "Jedes POKéMON hat seine\n"
	.string "Schwächen!\p"
	.string "Man sollte daher unterschiedliche\n"
	.string "POKéMON trainieren.$"

Route25_Text_DanIntro_DE::
	.string "Ich habe in ORANIA CITY mit\n"
	.string "meinem Papa auf der M.S. ANNE eine\l"
	.string "Party besucht!$"

Route25_Text_DanDefeat_DE::
	.string "Ich bin nicht sauer!$"

Route25_Text_DanPostBattle_DE::
	.string "Auf der M.S. ANNE habe ich\n"
	.string "TRAINER aus aller Welt gesehen!$"

Route25_Text_FlintIntro_DE::
	.string "Ich bin richtig cool!\n"
	.string "Ich habe eine Freundin!$"

Route25_Text_FlintDefeat_DE::
	.string "Ach, so ein Mist...$"

Route25_Text_FlintPostBattle_DE::
	.string "Na ja, meine Freundin wird mich\n"
	.string "aufheitern!$"

Route25_Text_KelseyIntro_DE::
	.string "Hallo!\n"
	.string "Mein Freund ist cool!$"

Route25_Text_KelseyDefeat_DE::
	.string "Ich war nicht in Form!$"

Route25_Text_KelseyPostBattle_DE::
	.string "Ach, wäre mein Freund doch auch\n"
	.string "so toll wie du!$"

Route25_Text_ChadIntro_DE::
	.string "Ich wusste, dass wir miteinander\n"
	.string "kämpfen würden!$"

Route25_Text_ChadDefeat_DE::
	.string "Ich wusste auch, dass ich verlieren\n"
	.string "würde!$"

Route25_Text_ChadPostBattle_DE::
	.string "Wenn eines deiner POKéMON verwirrt\n"
	.string "ist, wechsle es aus!\p"
	.string "Das ist eine gute Taktik!$"

Route25_Text_HaleyIntro_DE::
	.string "Meine Freundin hat so ein süßes\n"
	.string "POKéMON! Ich bin furchtbar\l"
	.string "neidisch!$"

Route25_Text_HaleyDefeat_DE::
	.string "Ich bin nicht sauer!$"

Route25_Text_HaleyPostBattle_DE::
	.string "Du warst auf dem MONDBERG?\n"
	.string "Hast du ein PIEPI gefunden?$"

Route25_Text_FranklinIntro_DE::
	.string "Ich komme gerade vom MONDBERG und\n"
	.string "bin topfit!$"

Route25_Text_FranklinDefeat_DE::
	.string "Du hast schwer gekämpft!$"

Route25_Text_FranklinPostBattle_DE::
	.string "Mist!\n"
	.string "Mich hat ein ZUBAT gebissen!$"

Route25_Text_NobIntro_DE::
	.string "Ich bin auf dem Weg zu einem\n"
	.string "POKéMON-Sammler!$"

Route25_Text_NobDefeat_DE::
	.string "Du hast mich besiegt.$"

Route25_Text_NobPostBattle_DE::
	.string "Dieser Sammler besitzt viele\n"
	.string "seltene POKéMON.$"

Route25_Text_WayneIntro_DE::
	.string "Du möchtest zu BILL?\n"
	.string "Aber erst wird gekämpft!$"

Route25_Text_WayneDefeat_DE::
	.string "Ich gebe auf!$"

Route25_Text_WaynePostBattle_DE::
	.string "Der Pfad dort unten ist eine\n"
	.string "Abkürzung nach AZURIA CITY.$"

Route25_Text_SeaCottageSign_DE::
	.string "KÜSTENHAUS\n"
	.string "Hier wohnt BILL!$"

Route25_Text_MistyHighHopesAboutThisPlace_DE::
	.string "Das Kap ist beliebt bei Pärchen.\p"
	.string "Die ARENALEITERIN MISTY hat hohe\n"
	.string "Erwartungen an diesen Ort.$"

Route25_Text_AreYouHereAlone_DE::
	.string "Hallo! Bist du alleine hier?\p"
	.string "Wenn du am Kap von AZURIA CITY\n"
	.string "bist, solltest du jemanden dabei\l"
	.string "haben.$"

