Route25_Text_JoeyIntro_FR::
	.string "Les DRESSEURS du coin viennent\n"
	.string "ici pour s'entraîner!$"

Route25_Text_JoeyDefeat_FR::
	.string "Bien joué.$"

Route25_Text_JoeyPostBattle_FR::
	.string "Tous les POKéMON ont des\n"
	.string "faiblesses, même les plus forts.\p"
	.string "Il vaut donc mieux dresser des\n"
	.string "POKéMON de types différents.$"

Route25_Text_DanIntro_FR::
	.string "Je suis allé à une super fête.\n"
	.string "C'était sur L'OCEANE, à\l"
	.string "CARMIN SUR MER!$"

Route25_Text_DanDefeat_FR::
	.string "Yaha!\n"
	.string "J'suis pas fou!$"

Route25_Text_DanPostBattle_FR::
	.string "Sur L'OCEANE, j'ai vu des\n"
	.string "DRESSEURS du monde entier.$"

Route25_Text_FlintIntro_FR::
	.string "J'suis cool.\n"
	.string "Et j'ai une copine aussi!$"

Route25_Text_FlintDefeat_FR::
	.string "Zut!\n"
	.string "Zut, zut et zut!$"

Route25_Text_FlintPostBattle_FR::
	.string "Ma copine va m'encourager.$"

Route25_Text_KelseyIntro_FR::
	.string "Mon p'tit copain, c'est le plus\n"
	.string "beau de tous!$"

Route25_Text_KelseyDefeat_FR::
	.string "Hmm…\n"
	.string "Je ne suis pas au top!$"

Route25_Text_KelseyPostBattle_FR::
	.string "J'aimerais que mon copain\n"
	.string "soit aussi fort que toi!$"

Route25_Text_ChadIntro_FR::
	.string "Y'a un DRESSEUR de trop ici!$"

Route25_Text_ChadDefeat_FR::
	.string "Ben…\n"
	.string "Je me sens de trop!$"

Route25_Text_ChadPostBattle_FR::
	.string "Si ton POKéMON est confus,\n"
	.string "rappelle-le!\p"
	.string "C'est une bonne tactique.$"

Route25_Text_HaleyIntro_FR::
	.string "Mon copain a des POKéMON trognons!\n"
	.string "Je suis jalouse!$"

Route25_Text_HaleyDefeat_FR::
	.string "Je ne suis pas si jalouse.$"

Route25_Text_HaleyPostBattle_FR::
	.string "Tu viens du MONT SELENITE?\n"
	.string "Tu as un MELOFEE?$"

Route25_Text_FranklinIntro_FR::
	.string "J'arrive du MONT SELENITE, et je\n"
	.string "suis prêt!$"

Route25_Text_FranklinDefeat_FR::
	.string "Pfiou!\n"
	.string "T'as dû travailler dur!$"

Route25_Text_FranklinPostBattle_FR::
	.string "Aaaaaaargh! Je me suis fait mordre\n"
	.string "par un NOSFERAPTI.$"

Route25_Text_NobIntro_FR::
	.string "Je cherche le collectionneur de\n"
	.string "POKéMON!$"

Route25_Text_NobDefeat_FR::
	.string "Heu! Tu m'as eu!\n"
	.string "Et facilement en plus.$"

Route25_Text_NobPostBattle_FR::
	.string "Le collectionneur a plein de\n"
	.string "POKéMON rares.$"

Route25_Text_WayneIntro_FR::
	.string "Tu vas voir LEO?\n"
	.string "Ok, mais d'abord, BASTOONNN!$"

Route25_Text_WayneDefeat_FR::
	.string "Perdu!$"

Route25_Text_WaynePostBattle_FR::
	.string "La route, en bas, est un raccourci\n"
	.string "vers AZURIA.$"

Route25_Text_SeaCottageSign_FR::
	.string "VILLA\n"
	.string "LEO habite ici!$"

Route25_Text_MistyHighHopesAboutThisPlace_FR::
	.string "Ce cap sert souvent de\n"
	.string "point de rencontre aux amoureux.\p"
	.string "On dit qu'ONDINE y aurait de\n"
	.string "grands espoirs.$"

Route25_Text_AreYouHereAlone_FR::
	.string "Salut, y'a personne avec toi? \p"
	.string "Si tu viens au cap d'AZURIA, autant\n"
	.string "que ce soit avec quelqu'un.$"

