Route25_Text_JoeyIntro_IT::
    .string "Gli ALLENATORI del luogo vengono\n"
    .string "qui a fare pratica!$"

Route25_Text_JoeyDefeat_IT::
    .string "Fantastico!\n"
    .string "Sei in gamba!$"

Route25_Text_JoeyPostBattle_IT::
    .string "Ogni POKéMON ha dei punti deboli.\n"
    .string "Devi addestrarne vari tipi.$"

Route25_Text_DanIntro_IT::
    .string "Papà mi ha portato a una bella\n"
    .string "festa sulla M/N ANNA ad\l"
    .string "ARANCIOPOLI!$"

Route25_Text_DanDefeat_IT::
    .string "Non ho perso la calma!$"

Route25_Text_DanPostBattle_IT::
    .string "Sulla M/N ANNA ho incontrato\n"
    .string "ALLENATORI di tutto il mondo!$"

Route25_Text_FlintIntro_IT::
    .string "Sono un tipo giusto, io!\n"
    .string "Ho la ragazza!$"

Route25_Text_FlintDefeat_IT::
    .string "Ah, accidenti…$"

Route25_Text_FlintPostBattle_IT::
    .string "Pazienza, la mia ragazza mi\n"
    .string "consolerà!$"

Route25_Text_KelseyIntro_IT::
    .string "Ciao!\n"
    .string "Il mio ragazzo è forte!$"

Route25_Text_KelseyDefeat_IT::
    .string "Non ero proprio in forma!$"

Route25_Text_KelseyPostBattle_IT::
    .string "Ah, vorrei che anche il mio\n"
    .string "ragazzo fosse come te!$"

Route25_Text_ChadIntro_IT::
    .string "Lo sapevo che ci saremmo\n"
    .string "scontrati!$"

Route25_Text_ChadDefeat_IT::
    .string "Sapevo pure che avrei perso!$"

Route25_Text_ChadPostBattle_IT::
    .string "Se il tuo POKéMON è confuso,\n"
    .string "sostituiscilo!$"

Route25_Text_HaleyIntro_IT::
    .string "Il mio amico ha un POKéMON così\n"
    .string "dolce… Che invidia!$"

Route25_Text_HaleyDefeat_IT::
    .string "Non ti invidio mica!$"

Route25_Text_HaleyPostBattle_IT::
    .string "Vieni dal MONTE LUNA?\n"
    .string "Mi dai un CLEFAIRY?$"

Route25_Text_FranklinIntro_IT::
    .string "Torno adesso dal MONTE LUNA ma\n"
    .string "posso farcela!$"

Route25_Text_FranklinDefeat_IT::
    .string "Ottimo lavoro!$"

Route25_Text_FranklinPostBattle_IT::
    .string "Accidentaccio!\n"
    .string "Un forte ZUBAT ha aggredito i miei\l"
    .string "POKéMON!$"

Route25_Text_NobIntro_IT::
    .string "Vado al capo a trovare un\n"
    .string "collezionista di POKéMON!$"

Route25_Text_NobDefeat_IT::
    .string "Hai vinto tu!$"

Route25_Text_NobPostBattle_IT::
    .string "Il collezionista ha molti POKéMON\n"
    .string "rari.$"

Route25_Text_WayneIntro_IT::
    .string "Stai andando da BILL?\n"
    .string "Prima però in guardia!$"

Route25_Text_WayneDefeat_IT::
    .string "Mi arrendo!$"

Route25_Text_WaynePostBattle_IT::
    .string "Il percorso là in basso è una\n"
    .string "scorciatoia per CELESTOPOLI.$"

Route25_Text_SeaCottageSign_IT::
    .string "MIRAMARE\n"
    .string "Qui vive BILL!$"

Route25_Text_MistyHighHopesAboutThisPlace_IT::
    .string "Questo capo è famoso per gli\n"
    .string "appuntamenti fra innamorati.\p"
    .string "MISTY, la nostra CAPOPALESTRA, è\n"
    .string "molto legata a questo luogo.$"

Route25_Text_AreYouHereAlone_IT::
    .string "Stai andando al capo di\n"
    .string "CELESTOPOLI?\p"
    .string "Sai che è un posto per coppiette,\n"
    .string "vero?$"

