Route25_Text_JoeyIntro_ES::
    .string "¡Los ENTRENADORES de la zona\n"
    .string "vienen aquí a practicar!$"

Route25_Text_JoeyDefeat_ES::
    .string "Eres espectacular.$"

Route25_Text_JoeyPostBattle_ES::
    .string "Todo POKéMON tiene sus puntos\n"
    .string "débiles.\p"
    .string "Lo suyo es entrenar varios tipos.$"

Route25_Text_DanIntro_ES::
    .string "¡Mi padre me llevó a una gran\n"
    .string "fiesta en el S.S. ANNE, en\l"
    .string "CIUDAD CARMÍN!$"

Route25_Text_DanDefeat_ES::
    .string "¡No estoy enfadado!$"

Route25_Text_DanPostBattle_ES::
    .string "En el S.S. ANNE vi a ENTRENADORES\n"
    .string "de todo el mundo.$"

Route25_Text_FlintIntro_ES::
    .string "Soy un buen chico.\n"
    .string "¡Y tengo novia!$"

Route25_Text_FlintDefeat_ES::
    .string "Vaya...$"

Route25_Text_FlintPostBattle_ES::
    .string "Bueno, mi chica me animará.$"

Route25_Text_KelseyIntro_ES::
    .string "¡Hola!\n"
    .string "¡Mi chico es genial!$"

Route25_Text_KelseyDefeat_ES::
    .string "¡No estaba en muy buena forma!$"

Route25_Text_KelseyPostBattle_ES::
    .string "¡Ojalá mi chico fuera tan bueno\n"
    .string "como tú!$"

Route25_Text_ChadIntro_ES::
    .string "¡Sabía que tendría que luchar\n"
    .string "contigo!$"

Route25_Text_ChadDefeat_ES::
    .string "¡Sabía que iba a perder!$"

Route25_Text_ChadPostBattle_ES::
    .string "Si tu POKéMON sufre confusión, lo\n"
    .string "mejor es que lo cambies por otro.\p"
    .string "Es la mejor táctica.$"

Route25_Text_HaleyIntro_ES::
    .string "Mi amigo tiene unos POKéMON\n"
    .string "muy monos. ¡Qué envidia!$"

Route25_Text_HaleyDefeat_ES::
    .string "¡No estoy enfadada!$"

Route25_Text_HaleyPostBattle_ES::
    .string "¿Vienes del MT. MOON?\n"
    .string "¿Me das un CLEFAIRY?$"

Route25_Text_FranklinIntro_ES::
    .string "¡Acabo de bajar del MT. MOON,\n"
    .string "pero estoy listo!$"

Route25_Text_FranklinDefeat_ES::
    .string "¡Te has esforzado mucho!$"

Route25_Text_FranklinPostBattle_ES::
    .string "¡Aaaaaaargh!\n"
    .string "Me ha mordido un ZUBAT.$"

Route25_Text_NobIntro_ES::
    .string "¡Estoy buscando a un coleccionista\n"
    .string "de POKéMON en el cabo!$"

Route25_Text_NobDefeat_ES::
    .string "¡Me has ganado!$"

Route25_Text_NobPostBattle_ES::
    .string "El coleccionista tiene muchos\n"
    .string "POKéMON raros.$"

Route25_Text_WayneIntro_ES::
    .string "¿Vas a ver a BILL?\n"
    .string "¡Pues luchemos primero!$"

Route25_Text_WayneDefeat_ES::
    .string "¡Me rindo!$"

Route25_Text_WaynePostBattle_ES::
    .string "La ruta de abajo es un atajo\n"
    .string "a CIUDAD CELESTE.$"

Route25_Text_SeaCottageSign_ES::
    .string "LA CASA del MAR\n"
    .string "¡BILL vive aquí!$"

Route25_Text_MistyHighHopesAboutThisPlace_ES::
    .string "En este cabo queda mucha gente.\p"
    .string "MISTY, la LÍDER del GIMNASIO,\n"
    .string "suele venir por aquí.$"

Route25_Text_AreYouHereAlone_ES::
    .string "¿Has venido sin nadie\n"
    .string "que te acompañe?\p"
    .string "Si estás en el cabo de CELESTE,\n"
    .string "¡deberías aprovechar para buscar\l"
    .string "compañía!...$"
