ThreeIsland_Port_Text_WereKantoRiderFederation_IT::
    .string "Siamo della FEDERAZIONE\n"
    .string "CENTAURI di KANTO.\p"
    .string "Vrum vrum! Vrum vrum! Mi piace\n"
    .string "imitare il rumore della mia moto!$"

ThreeIsland_Port_Text_ForkOverMoney_IT::
    .string "Ehi, nonnetta! Scucimi qualche\n"
    .string "spicciolo!$"

ThreeIsland_Port_Text_IllCallThePolice_IT::
    .string "Eh?!?!\p"
    .string "E tu chi sei?!\n"
    .string "Ora chiamo la polizia!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone_IT::
    .string "Quei CENTAURI, se ne sono andati?\p"
    .string "Grazie al cielo!\n"
    .string "Mi avevano terrorizzato!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest_IT::
    .string "Quei CENTAURI se ne sono andati e\n"
    .string "LISETTA è stata ritrovata.\p"
    .string "Insomma, va tutto per il meglio!$"

