ThreeIsland_Port_Text_WereKantoRiderFederation_DE::
	.string "Wir sind der MOTORRADKLUB aus\n"
	.string "KANTO! Töff! Töfftööööfff! Töff!\p"
	.string "Mein Motorrad hat einen kleinen\n"
	.string "Motor, daher muss ich die\l"
	.string "Geräusche selbst machen!$"

ThreeIsland_Port_Text_ForkOverMoney_DE::
	.string "Heh, Lady!\n"
	.string "Haste mal einen POKéDOLLAR?$"

ThreeIsland_Port_Text_IllCallThePolice_DE::
	.string "Heija!\p"
	.string "W-wer bist du?\n"
	.string "Ich… ich rufe die Polizei!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone_DE::
	.string "Diese BIKER…\n"
	.string "Sind sie weg?\p"
	.string "Oh, Gott sei Dank!\n"
	.string "Die haben mir Angst eingejagt!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest_DE::
	.string "Die BIKER sind verduftet und\n"
	.string "IRRMA war in Sicherheit.\p"
	.string "Jetzt ist alles gut!$"

