ThreeIsland_Port_Text_WereKantoRiderFederation_FR::
	.string "On est les KANTO ANGELS!\n"
	.string "Vroom! Vavavavooom! Vroom!\p"
	.string "La honte, je dois faire le bruit de\n"
	.string "ma bécane tout seul.$"

ThreeIsland_Port_Text_ForkOverMoney_FR::
	.string "Hey! Madame,\n"
	.string "t'aurais pas du liquide sur toi?$"

ThreeIsland_Port_Text_IllCallThePolice_FR::
	.string "Aaaah.\p"
	.string "Qu-qui êtes-vous? Je vais appeler\n"
	.string "la police moi, voyous!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone_FR::
	.string "Ces MOTARDS…\n"
	.string "Ils sont vraiment partis?\p"
	.string "Oh, merci mon dieu!\n"
	.string "Ils m'ont fait une peur bleue.$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest_FR::
	.string "Ces MOTARDS sont partis et\n"
	.string "LOSTELLE est saine et sauve.\p"
	.string "Tout est bien qui finit bien.$"

