PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround_DE::
	.string "{RIVAL}: Hallo {PLAYER}!\n"
	.string "Opa ist gerade nicht da!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting_DE::
	.string "{RIVAL}: Opa!\n"
	.string "Ich will nicht länger warten!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe_DE::
	.string "{RIVAL}: Halt!\n"
	.string "Opa! Und was ist mit mir?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer_DE::
	.string "{RIVAL}: Ich bin nicht so\n"
	.string "ungeduldig wie du!\p"
	.string "Du darfst zuerst wählen, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen_DE::
	.string "{RIVAL}: Ich nehme dieses hier.$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak_DE::
	.string "{RIVAL} erhält\n"
	.string "{STR_VAR_1}!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher_DE::
	.string "{RIVAL}: Mein POKéMON sieht viel\n"
	.string "stärker aus!$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons_DE::
	.string "{RIVAL}: Warte, {PLAYER}!\n"
	.string "Lass uns unsere POKéMON testen!\p"
	.string "Komm schon!\n"
	.string "Ich fordere dich heraus!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat_DE::
	.string "WAS? Unmöglich!\n"
	.string "Ich habe mir das falsche POKéMON\l"
	.string "ausgesucht!$"

@ Also used for early Route 22 battle
Text_RivalVictory_DE::
	.string "{RIVAL}: Ja!\n"
	.string "Ich bin der Größte!$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon_DE::
	.string "{RIVAL}: O.K.! Ich werde meine\n"
	.string "POKéMON trainieren, damit sie\l"
	.string "stärker werden!\p"
	.string "{PLAYER}! Opa!\n"
	.string "Wir sehen uns später!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps_DE::
	.string "{RIVAL}: Opa!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor_DE::
	.string "{RIVAL}: Warum hast du mich\n"
	.string "hierher bestellt?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps_DE::
	.string "{RIVAL}: Alles klar, Opa!\n"
	.string "Überlass es ruhig mir!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap_DE::
	.string "{PLAYER}, es tut mir Leid, aber ich\n"
	.string "brauche deine Hilfe nicht!\p"
	.string "Genau! Ich leihe mir von\n"
	.string "meiner Schwester eine KARTE!\p"
	.string "Und dir soll sie keine geben,\n"
	.string "{PLAYER}! Hahaha!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne_DE::
	.string "PROF. EICH: {RIVAL}?\n"
	.string "Lass mich nachdenken...\p"
	.string "Ach richtig! Ihr solltet ja zu mir\n"
	.string "kommen! Wartet einen Moment!\p"
	.string "Hier, {PLAYER}!\p"
	.string "Dort liegen drei POKéMON!\p"
	.string "Haha!\p"
	.string "Sie befinden sich in den\n"
	.string "POKéBÄLLEN.\l"
	.string "In meiner Jugend war ich ein\l"
	.string "engagierter POKéMON TRAINER!\p"
	.string "Jetzt, da ich alt bin, habe ich nur\n"
	.string "drei POKéMON übrig.\p"
	.string "Aber ich gebe dir eines ab! Wähle!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival_DE::
	.string "PROF. EICH: Habe ein wenig Geduld,\n"
	.string "{RIVAL}!\l"
	.string "Auch du sollst eines bekommen!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose_DE::
	.string "EICH: Also {PLAYER}!\p"
	.string "In diesen POKéBÄLLEN sind\n"
	.string "POKéMON.\p"
	.string "Welches möchtest du haben?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet_DE::
	.string "PROF. EICH: Warte noch einen\n"
	.string "Moment, bevor du gehst!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander_DE::
	.string "Ah! GLUMANDA soll es sein!\n"
	.string "Trainiere es geduldig!\p"
	.string "{PLAYER}, du möchtest also das\n"
	.string "FEUER-POKéMON GLUMANDA?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle_DE::
	.string "Ah! SCHIGGY soll es sein!\n"
	.string "Es ist das Training wert!\p"
	.string "{PLAYER}, du möchtest also das\n"
	.string "WASSER-POKéMON SCHIGGY?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur_DE::
	.string "Ah! BISASAM soll es sein!\n"
	.string "Es ist leicht zu trainieren!\p"
	.string "{PLAYER}, du möchtest also das\n"
	.string "PFLANZEN-POKéMON BISASAM?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic_DE::
	.string "Dieses POKéMON ist wirklich\n"
	.string "energiegeladen!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak_DE::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon_DE::
	.string "PROF. EICH: Wenn du auf ein wildes\n"
	.string "POKéMON triffst, dann kann dein\l"
	.string "POKéMON dagegen kämpfen!$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow_DE::
	.string "PROF. EICH: {PLAYER}, wenn du dein\n"
	.string "POKéMON kämpfen lässt, wird es\l"
	.string "stärker!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe_DE::
	.string "PROF. EICH: Hallo, {PLAYER}!\p"
	.string "Wie geht es dem POKéMON?\p"
	.string "Es scheint dich sehr zu mögen!\p"
	.string "Du musst als POKéMON TRAINER sehr\n"
	.string "talentiert sein!\p"
	.string "Du hast etwas für mich?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel_DE::
	.string "{PLAYER} übergibt\n"
	.string "PROF. EICH das PAKET.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered_DE::
	.string "Ah! Auf diesen SPEZIAL-POKéBALL\n"
	.string "warte ich schon lange! \p"
	.string "Vielen Dank!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo_DE::
	.string "PROF. EICH: Ach ja! Ich habe eine\n"
	.string "große Aufgabe für euch!$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk_DE::
	.string "Auf dem Tisch dort seht ihr eine\n"
	.string "Erfindung von mir, den POKéDEX!\p"
	.string "Er erfasst automatisch Daten über\n"
	.string "POKéMON, die man gefangen oder\l"
	.string "gesehen hat!\p"
	.string "Er ist eine Art Hi-Tech-Lexikon!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou_DE::
	.string "PROF. EICH: {PLAYER}! {RIVAL}!\n"
	.string "Diese beiden sind für euch!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak_DE::
	.string "{PLAYER} erhält einen POKéDEX von\n"
	.string "PROF. EICH!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese_DE::
	.string "PROF. EICH: Es reicht nicht, \n"
	.string "POKéMON zu sehen, um detaillierte\l"
	.string "Informationen über sie zu sammeln!\p"
	.string "Du musst sie fangen! Benutze das\n"
	.string "hier, um wilde POKéMON\l"
	.string "einzufangen.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls_DE::
	.string "{PLAYER} erhält\n"
	.string "fünf POKéBÄLLE!$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching_DE::
	.string "Taucht ein wildes POKéMON auf, so\n"
	.string "kannst du es fangen.\p"
	.string "Wirf einfach einen POKéBALL und\n"
	.string "versuche es!\p"
	.string "Doch du wirst oftmals keinen Erfolg\n"
	.string "haben.\p"
	.string "Ein gesundes POKéMON entkommt\n"
	.string "schnell! Man muss schon etwas\l"
	.string "Glück haben!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream_DE::
	.string "Ein Lexikon über alle POKéMON der\n"
	.string "Welt...\p"
	.string "Das war immer mein Traum!\p"
	.string "Aber ich bin zu alt!\n"
	.string "Ich schaffe es nicht mehr!\p"
	.string "Also bitte ich euch, meinen Traum\n"
	.string "zu verwirklichen!\p"
	.string "Macht euch auf den Weg!\p"
	.string "Dies ist eines der bedeutendsten\n"
	.string "Projekte in der Geschichte der\l"
	.string "POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait_DE::
	.string "{PLAYER}, überall in dieser Welt\n"
	.string "erwarten dich POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex_DE::
	.string "Ah, {PLAYER}!\n"
	.string "Was macht dein POKéDEX?\p"
	.string "{RIVAL} hat bereits einige POKéMON\n"
	.string "gefangen und die Infos erhalten.\p"
	.string "Zeig mir deinen POKéDEX,\n"
	.string "{PLAYER}!\p"
	.string "… was ist los?\n"
	.string "Du hast keine neuen Infos!\p"
	.string "Ich gebe dir das, damit du dich\n"
	.string "ein wenig mehr bemühst.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime_DE::
	.string "PROF. EICH: Besuche mich von Zeit\n"
	.string "zu Zeit.\p"
	.string "Es interessiert mich, wie du mit\n"
	.string "deinem POKéDEX voranschreitest.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia_DE::
	.string "Es sieht wie ein Lexikon aus! Aber\n"
	.string "die Seiten sind unbeschrieben!$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls_DE::
	.string "Dies hier sind POKéBÄLLE.\n"
	.string "Sie enthalten POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon_DE::
	.string "Das ist PROF. EICHs letztes\n"
	.string "POKéMON!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu_DE::
	.string "Drücke START, um das MENÜ\n"
	.string "aufzurufen!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu_DE::
	.string "Im MENÜ kannst du unter SICHERN\n"
	.string "deinen Spielstand abspeichern.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints_DE::
	.string "POKéMON besitzen unterschiedliche\n"
	.string "Attacken, deren Wirkung je nach\l"
	.string "Gegner variiert.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage_DE::
	.string "Im Briefkasten ist eine E-Mail!\p"
	.string "...\p"
	.string "An alle POKéMON TRAINER!\n"
	.string "Die TRAINER-ELITE der POKéMON\l"
	.string "LIGA wartet auf mutige\l"
	.string "Herausforderer!\p"
	.string "Bringt eure stärksten POKéMON mit\n"
	.string "und zeigt, wie gut ihr seid!\p"
	.string "POKéMON LIGA-LEITUNG\n"
	.string "INDIGO-PLATEAU\p"
	.string "PS.: PROF. EICH, bitte melden sie\n"
	.string "sich bei uns! ...$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide_DE::
	.string "Ich bin PROF. EICHs ASSISTENT.\n"
	.string "Ich studiere mit ihm die POKéMON!$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons_DE::
	.string "Hallo {PLAYER}! Ich wette, du hast\n"
	.string "mit deinen POKéMON\l"
	.string "Freundschaft geschlossen.\l"
	.string "Kennst du eigentlich SARAH?\p"
	.string "Zeigst du SARAH deine POKéMON,\n"
	.string "sagt sie dir, wie sehr sie dich\l"
	.string "mögen.\l"
	.string "Manchmal pflegt sie auch ein\l"
	.string "POKéMON für dich.\p"
	.string "Das ist aber ein Geheimnis,\n"
	.string "verrate es also nicht!$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow_DE::
	.string "PROF. EICH wird bald seine eigene\n"
	.string "Radiosendung haben.\p"
	.string "Die Sendung heißt PROF. EICHs\n"
	.string "POKéMON-SEMINAR!$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons_DE::
	.string "PROF. EICH ist eine Kapazität auf\n"
	.string "dem Gebiet der POKéMON!\p"
	.string "Unter POKéMON TRAINERn genießt er\n"
	.string "ein sehr hohes Ansehen!$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer_DE::
	.string "Ah, das ist fantastisch!\p"
	.string "{PLAYER}, ich muss dich um noch\n"
	.string "einen wichtigen Gefallen bitten.\p"
	.string "Bitte höre genau zu!$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons_DE::
	.string "In letzter Zeit wurden viele\n"
	.string "seltene POKéMON gesichtet.\p"
	.string "Ich spreche von POKéMON, die nie\n"
	.string "zuvor in KANTO aufgetaucht sind.\p"
	.string "Ich würde mir das gerne selbst\n"
	.string "ansehen, aber ich bin zu alt!\p"
	.string "Da ich nicht kann, möchte ich\n"
	.string "dich, {PLAYER}, bitten, an meiner\l"
	.string "statt zu gehen.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything_DE::
	.string "{RIVAL}: Das habe ich gehört!\p"
	.string "Opsi, warum gibst du immer\n"
	.string "{PLAYER} den Vorzug gegenüber mir?\p"
	.string "Ich habe mehr POKéMON gefangen\n"
	.string "und auch noch schneller!\p"
	.string "Ich sollte mich also um alles\n"
	.string "kümmern!$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes_DE::
	.string "EICH: Ich weiß, ich weiß! Ich\n"
	.string "brauche natürlich auch deine Hilfe!\p"
	.string "Lasst mich eure beiden POKéDEX\n"
	.string "sehen!$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits_DE::
	.string "PROF. EICH nahm beide POKéDEX!$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData_DE::
	.string "… … …  … … …\p"
	.string "… … …  … … …\p"
	.string "… und erledigt!\p"
	.string "Nun können sie noch mehr Infos\n"
	.string "über POKéMON sichern.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded_DE::
	.string "Der POKéDEX von {PLAYER} wurde\n"
	.string "erweitert!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex_DE::
	.string "Also, {PLAYER} und {RIVAL}!\p"
	.string "Dieses Mal müsst ihr den POKéDEX\n"
	.string "wirklich vervollständigen.\p"
	.string "Es soll der beste und voll-\n"
	.string "ständigste POKéDEX aller\l"
	.string "Zeiten werden!\l"
	.string "Das ist wahrhaft ein großes\l"
	.string "Unterfangen in der Geschichte\l"
	.string "der POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex_DE::
	.string "{RIVAL}: Ruhig, Opsi! Keine\n"
	.string "Aufregung!\p"
	.string "Ich vervollständige den POKéDEX!\n"
	.string "Mach dir keine Gedanken!\p"
	.string "Ich denke, ich werde mich zunächst\n"
	.string "auf EILAND EINS umsehen…\p"
	.string "Wie dem auch sei! Ich muss weg!$"

