PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround_FR::
	.string "{RIVAL}: Yo! {PLAYER}!\n"
	.string "Pépé n'est pas là!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting_FR::
	.string "{RIVAL}: Pépé!\n"
	.string "J'en ai marre d'attendre!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe_FR::
	.string "{RIVAL}: Ben! Pépé! Mon pépé!\n"
	.string "Et moi?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer_FR::
	.string "{RIVAL}: Je ne suis pas avide\n"
	.string "comme toi!\p"
	.string "Allez, choisis, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen_FR::
	.string "{RIVAL}: Je prends celui-ci!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak_FR::
	.string "{RIVAL} obtient\n"
	.string "{STR_VAR_1}.$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher_FR::
	.string "{RIVAL}: Mon POKéMON est\n"
	.string "plus fort.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons_FR::
	.string "{RIVAL}: Minute, {PLAYER}!\n"
	.string "Voyons lequel de nos POKéMON est\l"
	.string "le plus fort!\p"
	.string "Allez viens te battre, minable!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat_FR::
	.string "QUOI???\n"
	.string "Incroyable!\l"
	.string "J'ai pas pris le bon POKéMON!$"

@ Also used for early Route 22 battle
Text_RivalVictory_FR::
	.string "{RIVAL}: Yeah!\n"
	.string "Je suis fort, hein?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon_FR::
	.string "{RIVAL}: OK!\n"
	.string "Je vais entraîner mon POKéMON!\p"
	.string "{PLAYER}! Pépé!\n"
	.string "A plus tard!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps_FR::
	.string "{RIVAL}: Pépé!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor_FR::
	.string "{RIVAL}: Pourquoi tu m'as appelé?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps_FR::
	.string "{RIVAL}: OK, pépé!\n"
	.string "Laisse-moi faire!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap_FR::
	.string "{PLAYER}, c'est clair, j'ai pas\n"
	.string "besoin de toi pour ça.\p"
	.string "Je sais! Je vais prendre une CARTE\n"
	.string "à ma sœur!\p"
	.string "Et je lui dirai de ne pas t'en\n"
	.string "donner une! Yark!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne_FR::
	.string "CHEN: {RIVAL}?\n"
	.string "Heu…\p"
	.string "Ah, c'est vrai!\n"
	.string "Je t'ai dit de venir…\p"
	.string "Tiens, {PLAYER}!\p"
	.string "Il y a trois POKéMON ici!\p"
	.string "Ils sont dans ces POKé BALLS.\p"
	.string "Plus jeune, j'étais un sacré\n"
	.string "DRESSEUR de POKéMON! Eh oui!\p"
	.string "Mais à cause de mon âge,\n"
	.string "je n'en ai gardé que trois!\p"
	.string "Il y en a un pour toi.\n"
	.string "Allez! Choisis-en un!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival_FR::
	.string "CHEN: Patience, {RIVAL}!\n"
	.string "Tu en auras un aussi!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose_FR::
	.string "CHEN: Alors, {PLAYER}.\p"
	.string "Dans ces trois POKé BALLS, \n"
	.string "il y a des POKéMON.\p"
	.string "Laquelle vas-tu choisir?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet_FR::
	.string "CHEN: Hé! Ne pars pas tout\n"
	.string "de suite!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander_FR::
	.string "SALAMECHE? C'est un bon choix.\n"
	.string "Tu vas devoir t'occuper de lui\p"
	.string "avec beaucoup de patience.\p"
	.string "Alors, tu as fait ton choix?\n"
	.string "Tu veux ce POKéMON FEU?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle_FR::
	.string "CARAPUCE? Il est facile à dresser,\n"
	.string "tu ne le regretteras pas.\p"
	.string "Alors, {PLAYER}, tu as choisi\n"
	.string "ce POKéMON EAU?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur_FR::
	.string "BULBIZARRE? Il est très facile\n"
	.string "à dresser.\p"
	.string "Alors, {PLAYER}, tu veux prendre\n"
	.string "ce POKéMON PLANTE?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic_FR::
	.string "Ce POKéMON est très énergique!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak_FR::
	.string "{PLAYER} obtient\n"
	.string "{STR_VAR_1}!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon_FR::
	.string "CHEN: Ton POKéMON te protègera\n"
	.string "des POKéMON sauvages!\p"
	.string "Avec lui, tu pourras sûrement\n"
	.string "atteindre la ville voisine.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow_FR::
	.string "CHEN: {PLAYER}, entraîne ton\n"
	.string "POKéMON au combat pour qu'il\l"
	.string "devienne fort!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe_FR::
	.string "CHEN: {PLAYER}!\p"
	.string "Comment va ton POKéMON?\p"
	.string "Je crois qu'il t'aime de\n"
	.string "plus en plus!\p"
	.string "Tu m'as l'air de savoir t'y prendre\n"
	.string "pour entraîner les POKéMON!\p"
	.string "Comment? Tu as quelque chose à\n"
	.string "me donner?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel_FR::
	.string "{PLAYER} donne le COLIS à CHEN.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered_FR::
	.string "Ah! C'est la POKé BALL que j'ai\n"
	.string "commandée!\p"
	.string "Merci!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo_FR::
	.string "CHEN: Ah oui!\n"
	.string "J'ai une faveur à vous demander.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk_FR::
	.string "Sur ce bureau, se trouve mon\n"
	.string "invention… Le POKéDEX!\p"
	.string "Il enregistre les informations sur\n"
	.string "les POKéMON rencontrés ou\l"
	.string "capturés!\p"
	.string "C'est comme une encyclopédie!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou_FR::
	.string "CHEN: {PLAYER} et {RIVAL}!\n"
	.string "Prenez ces POKéDEX!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak_FR::
	.string "{PLAYER} obtient le POKéDEX!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese_FR::
	.string "CHEN: Il ne te suffit pas de voir\n"
	.string "un POKéMON pour tout savoir\l"
	.string "sur lui!\p"
	.string "Il te faut aussi l'attraper! Voici\n"
	.string "des POKé BALLS pour en capturer.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls_FR::
	.string "{PLAYER} obtient 5 POKé BALLS!$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching_FR::
	.string "Quand un POKéMON sauvage\n"
	.string "apparaît, il faut jouer serré.\p"
	.string "Lance-lui une POKé BALL pour le\n"
	.string "capturer!\p"
	.string "Mais ça ne marchera pas à tous les\n"
	.string "coups!\p"
	.string "Un POKéMON en pleine forme peut\n"
	.string "s'échapper! Il faut aussi beaucoup\l"
	.string "de chance.$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream_FR::
	.string "Faire un guide complet sur les\n"
	.string "POKéMON du monde entier…\p"
	.string "C'est mon rêve!\p"
	.string "Mais je suis trop vieux maintenant!\p"
	.string "C'est pourquoi je veux que vous\n"
	.string "terminiez mon travail!\p"
	.string "Allez, roulez jeunesse!\p"
	.string "Que la grande quête des POKéMON\n"
	.string "commence!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait_FR::
	.string "Les POKéMON du monde entier sont\n"
	.string "à toi, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex_FR::
	.string "Ah, {PLAYER}!\p"
	.string "Alors, ton POKéDEX prend\n"
	.string "forme?\p"
	.string "{RIVAL} a déjà attrapé plusieurs\n"
	.string "POKéMON et réuni leurs\l"
	.string "informations.\p"
	.string "{PLAYER}, tu me laisses jeter un\n"
	.string "œil à ton POKéDEX?\p"
	.string "Quel est le problème?\p"
	.string "Ton POKéDEX est comme\n"
	.string "avant.\p"
	.string "Je vais te donner ça, alors essaie\n"
	.string "de faire des efforts.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime_FR::
	.string "CHEN: Reviens me voir de temps en\n"
	.string "temps.\p"
	.string "Tiens-moi informé du niveau de ton\n"
	.string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia_FR::
	.string "C'est comme une encyclopédie mais\n"
	.string "les pages sont vierges!$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls_FR::
	.string "Ces POKé BALLS contiennent\n"
	.string "des POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon_FR::
	.string "C'est le dernier POKéMON du\n"
	.string "PROF. CHEN!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu_FR::
	.string "START pour ouvrir le MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu_FR::
	.string "L'option SAUVER est sur l'écran du\n"
	.string "MENU.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints_FR::
	.string "Tous les POKéMON ont des points\n"
	.string "faibles!\p"
	.string "Ils sont également tous puissants\n"
	.string "face à un certain élément.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage_FR::
	.string "Il y a un e-mail!\p"
	.string "…\p"
	.string "Avis à tous les DRESSEURS de\n"
	.string "POKéMON!\l"
	.string "Le CONSEIL 4 est prêt à affronter\l"
	.string "tout concurrent!\p"
	.string "Présentez vos meilleurs POKéMON\n"
	.string "et découvrez votre niveau en tant\l"
	.string "que DRESSEUR!\p"
	.string "LIGUE POKéMON, PLATEAU INDIGO\p"
	.string "PS: PROF. CHEN, votre visite est\n"
	.string "attendue…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide_FR::
	.string "J'assiste le PROF. CHEN. Je suis\n"
	.string "donc son… ASSISTANT!$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons_FR::
	.string "Salut {PLAYER}. Je suis sûr que tu\n"
	.string "t'entends bien avec tes POKéMON!\p"
	.string "Au fait, est-ce que tu as entendu\n"
	.string "parler de NINA?\p"
	.string "Si tu lui montres tes POKéMON,\n"
	.string "elle peut te dire s'ils t'aiment\p"
	.string "ou pas. Il arrive même qu'elle\n"
	.string "s'en occupe pour toi.\p"
	.string "C'est un secret, n'en parle à\n"
	.string "personne.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow_FR::
	.string "Le PROF. CHEN va bientôt avoir\n"
	.string "sa propre émission de radio.\p"
	.string "Elle s'appellera le SEMINAIRE\n"
	.string "DU PROF. CHEN.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons_FR::
	.string "Le PROF. CHEN est une célébrité\n"
	.string "dans le monde des POKéMON.\p"
	.string "Nombreux sont les DRESSEURS qui\n"
	.string "lui portent un grand respect.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer_FR::
	.string "Ah, c'est parfait!\p"
	.string "{PLAYER}, j'ai une faveur à te\n"
	.string "demander.\p"
	.string "Ecoute-moi attentivement.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons_FR::
	.string "Récemment, des POKéMON rares\n"
	.string "ont été aperçus.\p"
	.string "Je parle de POKéMON inconnus\n"
	.string "à KANTO.\p"
	.string "J'aimerais tant aller voir par\n"
	.string "moi-même, mais je suis trop vieux!\p"
	.string "{PLAYER}, tu veux bien aller voir\n"
	.string "à ma place?$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything_FR::
	.string "{RIVAL}: Hé, j'ai entendu!\p"
	.string "Pépé, pourquoi tu favorises tout\n"
	.string "le temps {PLAYER}?\p"
	.string "J'ai attrapé plus de POKéMON\n"
	.string "pourtant.\p"
	.string "Tu devrais me laisser m'en\n"
	.string "occuper!$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes_FR::
	.string "CHEN: Je sais, je sais. J'ai \n"
	.string "bien sûr aussi besoin de toi!\p"
	.string "Laissez-moi voir vos POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits_FR::
	.string "Le PROF. CHEN prend les\n"
	.string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData_FR::
	.string "… … …  … … …\p"
	.string "… … …  … … …\p"
	.string "… Et voilà!\p"
	.string "Maintenant, ces POKéDEX\n"
	.string "peuvent enregistrer des infos\p"
	.string "sur beaucoup plus de\n"
	.string "POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded_FR::
	.string "Le POKéDEX de {PLAYER} a été\n"
	.string "mis à jour!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex_FR::
	.string "Bon, {PLAYER} et {RIVAL}!\n"
	.string "Cette fois, vous devrez vraiment\p"
	.string "vous donner du mal pour remplir\n"
	.string "vos POKéDEX.\p"
	.string "Je compte sur vous pour réunir\n"
	.string "toutes les infos possibles!\p"
	.string "Ensemble, nous allons réaliser\n"
	.string "le POKéDEX le plus complet\p"
	.string "de tous les temps! C'est un grand\n"
	.string "moment dans l'histoire des POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex_FR::
	.string "{RIVAL}: Holà, t'énerve pas pépé.\p"
	.string "Je vais remplir le POKéDEX,\n"
	.string "t'inquiète pas pour ça.\p"
	.string "Je vais commencer en allant\n"
	.string "sur l'ILE 1…\p"
	.string "Allez, j'suis plus là!$"

