FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland_FR::
	.string "Un DRESSEUR très fort et très\n"
	.string "connu a grandi sur cette île.\p"
	.string "Je suis sûr que même toi tu\n"
	.string "connais son nom.\p"
	.string "C'est OLGA, du CONSEIL 4.\p"
	.string "C'est moi qui lui ai tout appris sur\n"
	.string "les POKéMON il y a des années.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid_FR::
	.string "Les ILES SEVII se trouvent dans\n"
	.string "une région plutôt chaude.\p"
	.string "Mais il y a une exception que tu\n"
	.string "dois connaître.\p"
	.string "La GROTTE DE GLACE est ainsi\n"
	.string "à cause du POKéMON qui y vit.$"

