FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland_DE::
	.string "Ein wunderbarer, starker TRAINER\n"
	.string "ist hier aufgewachsen.\p"
	.string "Ich wette, du kennst sie auch. Es\n"
	.string "ist LORELEI von den TOP VIER.\p"
	.string "Als LORELEI noch klein war, habe\n"
	.string "ich ihr viel über POKéMON\l"
	.string "beigebracht!$"

FourIsland_Mart_Text_IcefallCaveIsFrigid_DE::
	.string "SEVII EILAND liegt in \n"
	.string "warmen Gefilden.\p"
	.string "Aber es gibt eine Ausnahme, die\n"
	.string "du kennen solltest.\p"
	.string "Die EISKASKADENHÖHLE ist\n"
	.string "aufgrund der POKéMON,\l"
	.string "die dort leben, kalt.$"

