FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland_IT::
    .string "Su quest'isola è nata e cresciuta\n"
    .string "una ragazza che è diventata un\l"
    .string "grande ALLENATORE.\p"
    .string "È LORELEI dei SUPERQUATTRO.\p"
    .string "La conosco bene.\n"
    .string "Quando era solo una ragazzina,\l"
    .string "le ho insegnato tutto sui POKéMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid_IT::
    .string "In generale, le isole del\n"
    .string "SETTIPELAGO godono di un clima\l"
    .string "piuttosto mite.\p"
    .string "C'è un'eccezione, però:\n"
    .string "la GROTTA GELATA.\p"
    .string "La GROTTA GELATA è freddissima\n"
    .string "a causa del POKéMON che ci vive.$"

