@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull_IT::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames_IT::
    .string "Quando catturi molti POKéMON, è\n"
    .string "duro inventare nomi per tutti!\p"
    .string "A LAVANDONIA c'è un uomo che\n"
    .string "giudica i nomi dei POKéMON.\p"
    .string "Ti aiuterà anche a dare nuovi\n"
    .string "nomi ai tuoi POKéMON!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender_IT::
    .string "Per LAVANDONIA, procedi\n"
    .string "lungo il TUNNEL ROCCIOSO.\p"
    .string "Come si arriva al TUNNEL ROCCIOSO?\n"
    .string "Da CELESTOPOLI, naturalmente!$"

