@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull_ES::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames_ES::
    .string "Cuando atrapas a muchos POKéMON,\n"
    .string "¿A que es difícil darles motes?\p"
    .string "En PUEBLO LAVANDA hay un hombre\n"
    .string "que evalúa los motes de los\l"
    .string "POKéMON.\p"
    .string "¡Y te ayudará a renombrarlos!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender_ES::
    .string "Si quieres ir a PUEBLO LAVANDA,\n"
    .string "ve por el TÚNEL ROCA.\p"
    .string "Podrás tomar el TÚNEL ROCA desde\n"
    .string "CIUDAD CELESTE.$"
