@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull_DE::
	.string "{PLAYER}{KUN}の　バッグ\n"
	.string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames_DE::
	.string "Je mehr POKéMON man fängt, desto\n"
	.string "schwieriger wird es, ihnen allen\l"
	.string "Spitznamen zu geben!\p"
	.string "In LAVANDIA lebt ein Mann, der\n"
	.string "Spitznamen von POKéMON bewertet.\p"
	.string "Er nimmt auch Namensänderungen\n"
	.string "vor!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender_DE::
	.string "Falls du nach LAVANDIA möchtest,\n"
	.string "empfehle ich dir den FELSTUNNEL.\p"
	.string "Du kannst den FELSTUNNEL von\n"
	.string "AZURIA CITY aus erreichen.$"

