Route9_Text_AliciaIntro_FR::
	.string "T'as des POKéMON avec toi!\n"
	.string "En garde!$"

Route9_Text_AliciaDefeat_FR::
	.string "Ah!\n"
	.string "Bien défendu!$"

Route9_Text_AliciaPostBattle_FR::
	.string "On n'y voit rien du tout dans ce\n"
	.string "tunnel.\p"
	.string "Il te faudrait FLASH pour le\n"
	.string "traverser.$"

Route9_Text_ChrisIntro_FR::
	.string "Mais qui voilà, les bras chargés de\n"
	.string "POKéMON?$"

Route9_Text_ChrisDefeat_FR::
	.string "Paf!\n"
	.string "J'suis fini!$"

Route9_Text_ChrisPostBattle_FR::
	.string "Passe ton chemin!$"

Route9_Text_DrewIntro_FR::
	.string "Je passe par la GROTTE pour\n"
	.string "aller à LAVANVILLE!$"

Route9_Text_DrewDefeat_FR::
	.string "…\n"
	.string "J'suis pas bon!$"

Route9_Text_DrewPostBattle_FR::
	.string "Tu vas dans la GROTTE, toi aussi?$"

Route9_Text_CaitlinIntro_FR::
	.string "Traite-moi avec respect!$"

Route9_Text_CaitlinDefeat_FR::
	.string "…\n"
	.string "Je ne mérite que ton dédain!$"

Route9_Text_CaitlinPostBattle_FR::
	.string "Tu iras loin!\n"
	.string "Bonne chance à toi!$"

Route9_Text_JeremyIntro_FR::
	.string "Bwahaha! Allez…\n"
	.string "Viens prendre ta pâtée…$"

Route9_Text_JeremyDefeat_FR::
	.string "Ha!\n"
	.string "Viens, viens!\p"
	.string "Heu, j'ai plus de POKéMON!$"

Route9_Text_JeremyPostBattle_FR::
	.string "T'as du courage, toi!$"

Route9_Text_BriceIntro_FR::
	.string "Hahaha!\n"
	.string "T'as l'air coriace, toi!$"

Route9_Text_BriceDefeat_FR::
	.string "Dur, très dur!$"

Route9_Text_BricePostBattle_FR::
	.string "Les gosses, c'est pas assez fort!$"

Route9_Text_BrentIntro_FR::
	.string "Mes cocons de POKéMON me\n"
	.string "prennent beaucoup de temps!$"

Route9_Text_BrentDefeat_FR::
	.string "Nyargh?\p"
	.string "Quelle perte de temps!$"

Route9_Text_BrentPostBattle_FR::
	.string "Il me faut autre chose que\n"
	.string "des insectes pour être plus fort…$"

Route9_Text_AlanIntro_FR::
	.string "Viens t'battre, si tu oses!$"

Route9_Text_AlanDefeat_FR::
	.string "Ha!\n"
	.string "Tu m'as bien eu!$"

Route9_Text_AlanPostBattle_FR::
	.string "Hahahaha!\n"
	.string "Quand j'perds, j'me marre!$"

Route9_Text_ConnerIntro_FR::
	.string "En avant mes POKéMON INSECTE!$"

Route9_Text_ConnerDefeat_FR::
	.string "Mes POKéMON!$"

Route9_Text_ConnerPostBattle_FR::
	.string "T'aimes pas les POKéMON INSECTE?\n"
	.string "T'es pas chouette!$"

Route9_Text_RouteSign_FR::
	.string "ROUTE 9\n"
	.string "AZURIA - GROTTE$"

