Route9_Text_AliciaIntro_IT::
    .string "Hai dei POKéMON?!\n"
    .string "In guardia!$"

Route9_Text_AliciaDefeat_IT::
    .string "Hai giocato sporco!$"

Route9_Text_AliciaPostBattle_IT::
    .string "Ti serve la luce di un FLASH per\n"
    .string "attraversare quel tunnel buio.$"

Route9_Text_ChrisIntro_IT::
    .string "Chi è quella persona con quella\n"
    .string "bella squadra di POKéMON?$"

Route9_Text_ChrisDefeat_IT::
    .string "Fuori combattimento!$"

Route9_Text_ChrisPostBattle_IT::
    .string "Continua per la tua strada!$"

Route9_Text_DrewIntro_IT::
    .string "Prendo il TUNNEL ROCCIOSO per\n"
    .string "LAVANDONIA!$"

Route9_Text_DrewDefeat_IT::
    .string "Puah!\n"
    .string "Non sono all'altezza!$"

Route9_Text_DrewPostBattle_IT::
    .string "Vai verso il TUNNEL ROCCIOSO?$"

Route9_Text_CaitlinIntro_IT::
    .string "Non fare l'arrogante!$"

Route9_Text_CaitlinDefeat_IT::
    .string "No!\n"
    .string "Sei troppo forte!?$"

Route9_Text_CaitlinPostBattle_IT::
    .string "È palese che hai talento!\n"
    .string "In bocca al lupo!$"

Route9_Text_JeremyIntro_IT::
    .string "Ahaha! Che bello!\n"
    .string "Stavo iniziando ad annoiarmi!$"

Route9_Text_JeremyDefeat_IT::
    .string "Non sarò io a fermarti! Va'!\p"
    .string "Hai fortuna!\n"
    .string "Ho finito i POKéMON!$"

Route9_Text_JeremyPostBattle_IT::
    .string "Hai avuto fegato per sfidarmi\n"
    .string "così!$"

Route9_Text_BriceIntro_IT::
    .string "Ahaha!\n"
    .string "Ma chi ti credi di essere?!$"

Route9_Text_BriceDefeat_IT::
    .string "Cosa è stato?$"

Route9_Text_BricePostBattle_IT::
    .string "Ahaha!\n"
    .string "E così tu saresti forte!$"

Route9_Text_BrentIntro_IT::
    .string "Mi alzo presto ogni giorno per\n"
    .string "allenare i miei POKéMON\l"
    .string "COLEOTTERO!$"

Route9_Text_BrentDefeat_IT::
    .string "Che gran perdita di tempo!$"

Route9_Text_BrentPostBattle_IT::
    .string "Forse dovrei indirizzarmi su\n"
    .string "altri POKéMON…$"

Route9_Text_AlanIntro_IT::
    .string "Ahaha!\n"
    .string "Andiamo, pulce!$"

Route9_Text_AlanDefeat_IT::
    .string "Ah!\n"
    .string "Mi hai battuto onestamente!$"

Route9_Text_AlanPostBattle_IT::
    .string "Ahaha!\n"
    .string "I tipi vivaci come noi ridono\l"
    .string "sempre!$"

Route9_Text_ConnerIntro_IT::
    .string "Forza, miei POKéMON COLEOTTERO!$"

Route9_Text_ConnerDefeat_IT::
    .string "Oh, miei cari POKéMON di tipo\n"
    .string "COLEOTTERO!$"

Route9_Text_ConnerPostBattle_IT::
    .string "Adoro i POKéMON COLEOTTERO!\n"
    .string "Tu no? Vattene!$"

Route9_Text_RouteSign_IT::
    .string "PERCORSO 9\n"
    .string "CELESTOPOLI - TUNNEL ROCCIOSO$"

