Route9_Text_AliciaIntro_DE::
	.string "Du trägst POKéMON bei dir! Lass\n"
	.string "uns kämpfen!$"

Route9_Text_AliciaDefeat_DE::
	.string "Du hast gewonnen!$"

Route9_Text_AliciaPostBattle_DE::
	.string "Du benötigst eine Lichtquelle, um\n"
	.string "den Tunnel zu durchqueren!$"

Route9_Text_ChrisIntro_DE::
	.string "Heh, wer bist du?\n"
	.string "Deine POKéMON sehen fit aus!$"

Route9_Text_ChrisDefeat_DE::
	.string "Schnell und präzise besiegt!$"

Route9_Text_ChrisPostBattle_DE::
	.string "O.K., geh einfach weiter!$"

Route9_Text_DrewIntro_DE::
	.string "Ich gehe durch den FELSTUNNEL\n"
	.string "nach LAVANDIA...$"

Route9_Text_DrewDefeat_DE::
	.string "Mit dir habe ich mich übernommen!$"

Route9_Text_DrewPostBattle_DE::
	.string "Möchtest du auch den FELSTUNNEL\n"
	.string "benutzen?$"

Route9_Text_CaitlinIntro_DE::
	.string "Trau dich ruhig, mit mir zu\n"
	.string "kämpfen!$"

Route9_Text_CaitlinDefeat_DE::
	.string "Das war zu viel des Guten!$"

Route9_Text_CaitlinPostBattle_DE::
	.string "Du hast sehr viel Talent! Viel\n"
	.string "Glück auf deinem weiteren Weg!$"

Route9_Text_JeremyIntro_DE::
	.string "Endlich kommt jemand!\n"
	.string "Mir war richtig langweilig!$"

Route9_Text_JeremyDefeat_DE::
	.string "War das etwa schon alles?\p"
	.string "Oh! Ich habe kein einsatzbereites\n"
	.string "POKéMON übrig!$"

Route9_Text_JeremyPostBattle_DE::
	.string "Deine Knie haben ganz schön\n"
	.string "geschlackert, oder?$"

Route9_Text_BriceIntro_DE::
	.string "Du hast keine Chance, du nerviges\n"
	.string "Balg!$"

Route9_Text_BriceDefeat_DE::
	.string "Was ist passiert?$"

Route9_Text_BricePostBattle_DE::
	.string "Haha!\n"
	.string "Kinder sollten Hallodris sein!$"

Route9_Text_BrentIntro_DE::
	.string "Ich stehe jeden Tag früh auf, um\n"
	.string "meine POKéMON in ihren Kokons zu\l"
	.string "pflegen!$"

Route9_Text_BrentDefeat_DE::
	.string "WAS?\p"
	.string "Das war die reinste\n"
	.string "Zeitverschwendung!$"

Route9_Text_BrentPostBattle_DE::
	.string "Ich sollte nicht nur Käfer sammeln,\n"
	.string "um stärker zu werden...$"

Route9_Text_AlanIntro_DE::
	.string "Ha!\n"
	.string "Wie wäre es mit einem Kampf?$"

Route9_Text_AlanDefeat_DE::
	.string "Haha!\n"
	.string "Ein fairer Kampf!$"

Route9_Text_AlanPostBattle_DE::
	.string "Haha!\n"
	.string "Wir Scherzbolde lachen ständig!$"

Route9_Text_ConnerIntro_DE::
	.string "Du hast keine Chance gegen meine\n"
	.string "KÄFER-POKéMON!$"

Route9_Text_ConnerDefeat_DE::
	.string "Meine KÄFER-POKéMON...$"

Route9_Text_ConnerPostBattle_DE::
	.string "Wer keine Käfer mag, den mag ich\n"
	.string "auch nicht!$"

Route9_Text_RouteSign_DE::
	.string "ROUTE 9\n"
	.string "AZURIA CITY - FELSTUNNEL$"

