Route9_Text_AliciaIntro_ES::
    .string "¡Tienes algunos POKéMON!\n"
    .string "¡En guardia!$"

Route9_Text_AliciaDefeat_ES::
    .string "¡Me has dejado...!$"

Route9_Text_AliciaPostBattle_ES::
    .string "El túnel que hay cerca de aquí\n"
    .string "está muy oscuro.\p"
    .string "Necesitarás DESTELLO para poder\n"
    .string "cruzarlo sin problemas.$"

Route9_Text_ChrisIntro_ES::
    .string "¿Quién anda por ahí con esos\n"
    .string "POKéMON con tan buen aspecto?$"

Route9_Text_ChrisDefeat_ES::
    .string "¡Esto se acabó!$"

Route9_Text_ChrisPostBattle_ES::
    .string "¡Sigue caminando!$"

Route9_Text_DrewIntro_ES::
    .string "¡Tomaré el TÚNEL ROCA para ir\n"
    .string "a PUEBLO LAVANDA!$"

Route9_Text_DrewDefeat_ES::
    .string "¡Soy muy malo! ¡Buaaa!$"

Route9_Text_DrewPostBattle_ES::
    .string "¿Vas a ir también al TÚNEL ROCA?$"

Route9_Text_CaitlinIntro_ES::
    .string "¡No te andes con contemplaciones!$"

Route9_Text_CaitlinDefeat_ES::
    .string "¡Eres demasiado!$"

Route9_Text_CaitlinPostBattle_ES::
    .string "¡Tienes madera!\n"
    .string "¡Buena suerte!$"

Route9_Text_JeremyIntro_ES::
    .string "¡Ja!\n"
    .string "¡Qué bien! ¡Me estaba aburriendo!$"

Route9_Text_JeremyDefeat_ES::
    .string "¡Sigue luchando!\p"
    .string "Espera, ¡si no tengo más POKéMON!$"

Route9_Text_JeremyPostBattle_ES::
    .string "¡Debes de ser muy valiente para\n"
    .string "desafiarme!$"

Route9_Text_BriceIntro_ES::
    .string "¡Eh!\n"
    .string "¿Me enseñas la fuerza que tienes?$"

Route9_Text_BriceDefeat_ES::
    .string "¿Qué ha pasado?$"

Route9_Text_BricePostBattle_ES::
    .string "¡Vaya, sí que tienen fuerza\n"
    .string "los niños de hoy!$"

Route9_Text_BrentIntro_ES::
    .string "¡Madrugo todos los días para\n"
    .string "cuidar a mis POKéMON CAPULLO!$"

Route9_Text_BrentDefeat_ES::
    .string "¿QUÉ?\p"
    .string "¡Qué gran pérdida de tiempo!$"

Route9_Text_BrentPostBattle_ES::
    .string "Tengo que recoger algo más que\n"
    .string "bichos para ser más fuerte...$"

Route9_Text_AlanIntro_ES::
    .string "¡Jajajaja!\n"
    .string "¡Vamos, adelante!$"

Route9_Text_AlanDefeat_ES::
    .string "¡Jajajaja!\n"
    .string "¡Me has ganado!$"

Route9_Text_AlanPostBattle_ES::
    .string "¡Jajaja!\n"
    .string "¡Los más fuertes siempre reímos!$"

Route9_Text_ConnerIntro_ES::
    .string "¡Adelante mis geniales POKéMON\n"
    .string "BICHO!$"

Route9_Text_ConnerDefeat_ES::
    .string "Mis bichos...$"

Route9_Text_ConnerPostBattle_ES::
    .string "Desde luego a ti no te gustan\n"
    .string "los POKéMON BICHO...$"

Route9_Text_RouteSign_ES::
    .string "RUTA 9:\n"
    .string "CIUDAD CELESTE - TÚNEL ROCA$"
