FiveIsland_PokemonCenter_1F_Text_OnMyWayToPrepareMeal_DE::
	.string "Ich bin gerade dabei, ein Essen für\n"
	.string "eine gewisse Berühmtheit\l"
	.string "zuzubereiten.$"

FiveIsland_PokemonCenter_1F_Text_YoureOnQuestToCatchEveryMon_DE::
	.string "Du bestreitest ein Abenteuer, auf\n"
	.string "dem du jedes POKéMON fangen\l"
	.string "willst?\l"
	.string "… unglaublich! Gib mir bitte\l"
	.string "Bescheid, wenn du ein Starkes\l"
	.string "gefangen hast!$"

