Route24_Text_JustEarnedFabulousPrize_DE::
	.string "Herzlichen Glückwunsch!\n"
	.string "Du hast alle fünf TRAINER besiegt!\p"
	.string "Du hast einen großartigen Preis\n"
	.string "gewonnen!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer_DE::
	.string "{PLAYER} erhält\n"
	.string "ein NUGGET!$"

Route24_Text_YouDontHaveAnyRoom_DE::
	.string "Du hast keinen Platz für weitere\n"
	.string "Items!$"

Route24_Text_JoinTeamRocket_DE::
	.string "Möchtest du auch Mitglied des TEAM\n"
	.string "ROCKET werden?\p"
	.string "Unsere Gruppierung benutzt POKéMON\n"
	.string "für teuflische Zwecke!\p"
	.string "Möchtest du beitreten?\p"
	.string "Wirklich nicht?\p"
	.string "Komm schon, werde Mitglied!\p"
	.string "Ich empfehle dir, ein Mitglied zu\n"
	.string "werden!\p"
	.string "Ich glaube, ich sollte ein wenig\n"
	.string "Überzeugungsarbeit leisten!\p"
	.string "Dieses Angebot kannst du nicht\n"
	.string "ablehnen!$"

Route24_Text_RocketDefeat_DE::
	.string "Arrgh!\n"
	.string "Du bist gut!$"

Route24_Text_YoudBecomeTopRocketLeader_DE::
	.string "Bei deinem Können wärst du im\n"
	.string "TEAM ROCKET leicht die rechte Hand\l"
	.string "vom Boss!\p"
	.string "Denke darüber nach! Lass dir\n"
	.string "diese Chance nicht entgehen!$"

Route24_Text_ShaneIntro_DE::
	.string "Ich habe deine Vorstellung aus dem\n"
	.string "Gras heraus beobachtet!$"

Route24_Text_ShaneDefeat_DE::
	.string "Ich habe wohl doch nichts gesehen!$"

Route24_Text_ShanePostBattle_DE::
	.string "Ich habe mich versteckt, weil mir\n"
	.string "die Leute auf der Brücke Angst\l"
	.string "gemacht haben!$"

Route24_Text_EthanIntro_DE::
	.string "Ich bin Nr. 5!\n"
	.string "Dich mache ich platt!$"

Route24_Text_EthanDefeat_DE::
	.string "Das war zu viel des Guten!$"

Route24_Text_EthanPostBattle_DE::
	.string "Ich habe alles gegeben, ich schäme\n"
	.string "mich nicht!$"

Route24_Text_ReliIntro_DE::
	.string "Ich bin Nr. 4!\n"
	.string "Wirst du müde?$"

Route24_Text_ReliDefeat_DE::
	.string "Ich habe auch verloren!$"

Route24_Text_ReliPostBattle_DE::
	.string "Ich habe alles gegeben, ich schäme\n"
	.string "mich nicht!$"

Route24_Text_TimmyIntro_DE::
	.string "Hier kommt Nr. 3!\n"
	.string "Ich mache dir das Leben schwer!$"

Route24_Text_TimmyDefeat_DE::
	.string "Ah!\n"
	.string "Eiskalt erwischt!$"

Route24_Text_TimmyPostBattle_DE::
	.string "Ich habe alles gegeben, ich schäme\n"
	.string "mich nicht!$"

Route24_Text_AliIntro_DE::
	.string "Ich bin Nr. 2!\n"
	.string "Nun wird es ernst!$"

Route24_Text_AliDefeat_DE::
	.string "Wie konnte ich verlieren?$"

Route24_Text_AliPostBattle_DE::
	.string "Ich habe alles gegeben, ich schäme\n"
	.string "mich nicht!$"

Route24_Text_CaleIntro_DE::
	.string "Das hier ist die NUGGET-BRÜCKE!\n"
	.string "Wenn du uns fünf TRAINER besiegst,\l"
	.string "erhältst du einen wertvollen Preis!\p"
	.string "Willst du dein Glück versuchen?$"

Route24_Text_CaleDefeat_DE::
	.string "Wow!\n"
	.string "Du bist gut!$"

Route24_Text_CalePostBattle_DE::
	.string "Ich habe alles gegeben, ich schäme\n"
	.string "mich nicht!$"

