Route24_Text_JustEarnedFabulousPrize_FR::
	.string "Félicitations!\n"
	.string "Tu as battu les 5 DRESSEURS!\p"
	.string "Tu as gagné un fabuleux prix!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer_FR::
	.string "{PLAYER} obtient:\n"
	.string "PEPITE!$"

Route24_Text_YouDontHaveAnyRoom_FR::
	.string "Ton inventaire est plein!$"

Route24_Text_JoinTeamRocket_FR::
	.string "Veux-tu rejoindre les rangs de la\n"
	.string "TEAM ROCKET?\p"
	.string "Nous sommes un groupe de\n"
	.string "criminels spécialisés en POKéMON!\p"
	.string "Ça t'intéresse?\p"
	.string "Vraiment?\p"
	.string "Allez, viens!\p"
	.string "Bon, je t'ai dit de venir avec\n"
	.string "nous!\p"
	.string "Je vois…\p"
	.string "Je vais devoir me montrer plus\n"
	.string "persuasif!$"

Route24_Text_RocketDefeat_FR::
	.string "Arrgh!\n"
	.string "Pas mal!$"

Route24_Text_YoudBecomeTopRocketLeader_FR::
	.string "Tu pourrais vite devenir un chef\n"
	.string "au sein de la TEAM ROCKET!\p"
	.string "Allez, je te laisse y penser, ne\n"
	.string "laisse pas passer cette chance.$"

Route24_Text_ShaneIntro_FR::
	.string "Je suis au courant de tes exploits!$"

Route24_Text_ShaneDefeat_FR::
	.string "Oh, je pensais avoir une chance.$"

Route24_Text_ShanePostBattle_FR::
	.string "Je me cache, les gens sur le pont\n"
	.string "me font peur!$"

Route24_Text_EthanIntro_FR::
	.string "OK! J'suis le numéro 5!\n"
	.string "Je vais t'écraser!$"

Route24_Text_EthanDefeat_FR::
	.string "Ah!\n"
	.string "Purée!$"

Route24_Text_EthanPostBattle_FR::
	.string "Pas de regret, j'ai fait de mon\n"
	.string "mieux!$"

Route24_Text_ReliIntro_FR::
	.string "Je suis le numéro 4!\n"
	.string "T'en as pas eu assez?$"

Route24_Text_ReliDefeat_FR::
	.string "Tu…\n"
	.string "… m'as battue!$"

Route24_Text_ReliPostBattle_FR::
	.string "J'ai participé, et j'ai perdu!$"

Route24_Text_TimmyIntro_FR::
	.string "Je suis le numéro 3!\n"
	.string "C'est pas gagné!$"

Route24_Text_TimmyDefeat_FR::
	.string "Oh!\n"
	.string "Tu m'as écrasé!$"

Route24_Text_TimmyPostBattle_FR::
	.string "J'ai fait de mon mieux!$"

Route24_Text_AliIntro_FR::
	.string "Je suis le numéro 2!\n"
	.string "Ça rigole plus!$"

Route24_Text_AliDefeat_FR::
	.string "Ben…\n"
	.string "Tu m'as battue?$"

Route24_Text_AliPostBattle_FR::
	.string "J'ai fait de mon mieux,\n"
	.string "j'ai pas de regret!$"

Route24_Text_CaleIntro_FR::
	.string "Voici le PONT PEPITE!\n"
	.string "5 DRESSEURS le défendent!\p"
	.string "Bats-les tous pour remporter\n"
	.string "un prix fabuleux!\p"
	.string "Tu crois pouvoir y arriver?$"

Route24_Text_CaleDefeat_FR::
	.string "Haha!\n"
	.string "Bien joué!$"

Route24_Text_CalePostBattle_FR::
	.string "J'ai fait de mon mieux.\n"
	.string "Si si! C'est vrai!$"

