Route24_Text_JustEarnedFabulousPrize_ES::
    .string "¡Enhorabuena! ¡Has ganado\n"
    .string "a nuestros 5 ENTRENADORES!\p"
    .string "¡Has ganado un premio fabuloso!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer_ES::
    .string "¡{PLAYER} obtuvo una PEPITA\n"
    .string "de manos del ENTRENADOR\l"
    .string "misterioso!$"

Route24_Text_YouDontHaveAnyRoom_ES::
    .string "¡No te queda sitio!$"

Route24_Text_JoinTeamRocket_ES::
    .string "¿Te gustaría unirte al TEAM\n"
    .string "ROCKET?\p"
    .string "¡Somos un grupo dedicado a hacer\n"
    .string "maldades con los POKéMON!\p"
    .string "¿Te interesa?\p"
    .string "¿Seguro?\p"
    .string "Únete a nosotros.\p"
    .string "¡Ya te he dicho que te unas\n"
    .string "a nosotros!\p"
    .string "Necesitas que te convenza.\p"
    .string "¡Te haré una oferta que no podrás\n"
    .string "rechazar!$"

Route24_Text_RocketDefeat_ES::
    .string "¡Arrgh!\n"
    .string "¡Eres genial!$"

Route24_Text_YoudBecomeTopRocketLeader_ES::
    .string "¡Con tu capacidad podrías ser\n"
    .string "líder del TEAM ROCKET!\p"
    .string "¡Piénsatelo, sería una buena\n"
    .string "oportunidad para ti!$"

Route24_Text_ShaneIntro_ES::
    .string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_ShaneDefeat_ES::
    .string "¡Creía que no me ibas a ganar!$"

Route24_Text_ShanePostBattle_ES::
    .string "¡Me oculté porque me asustaron\n"
    .string "los del puente!$"

Route24_Text_EthanIntro_ES::
    .string "¡Yo soy el 5.º!\n"
    .string "¡Voy a acabar contigo!$"

Route24_Text_EthanDefeat_ES::
    .string "¡Uauu!\n"
    .string "¡Ha sido mucha tela!$"

Route24_Text_EthanPostBattle_ES::
    .string "¡He hecho lo que he podido!$"

Route24_Text_ReliIntro_ES::
    .string "¡Yo soy la 4.ª!\n"
    .string "¿Te quedan fuerzas?$"

Route24_Text_ReliDefeat_ES::
    .string "¡También he perdido!$"

Route24_Text_ReliPostBattle_ES::
    .string "¡He hecho lo que he podido!$"

Route24_Text_TimmyIntro_ES::
    .string "¡Yo soy el 3.º!\n"
    .string "¡Te va a costar!$"

Route24_Text_TimmyDefeat_ES::
    .string "¡Oye!\n"
    .string "¡Me has machacado!$"

Route24_Text_TimmyPostBattle_ES::
    .string "¡He hecho lo que he podido!$"

Route24_Text_AliIntro_ES::
    .string "¡Yo soy la 2.ª!\n"
    .string "¡En guardia!$"

Route24_Text_AliDefeat_ES::
    .string "¿Cómo he podido perder?$"

Route24_Text_AliPostBattle_ES::
    .string "¡He hecho lo que he podido!$"

Route24_Text_CaleIntro_ES::
    .string "¡Éste es el PUENTE PEPITA!\n"
    .string "¡Derrótanos a los 5 y gana un\l"
    .string "fabuloso premio!\p"
    .string "¿Crees que puedes hacerlo?$"

Route24_Text_CaleDefeat_ES::
    .string "¡Uau!\n"
    .string "¡Bien hecho!$"

Route24_Text_CalePostBattle_ES::
    .string "¡He hecho lo que he podido!$"
