Route24_Text_JustEarnedFabulousPrize_IT::
    .string "Congratulazioni!\n"
    .string "Hai battuto i nostri 5 ALLENATORI!\p"
    .string "Hai vinto un premio favoloso!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer_IT::
    .string "{PLAYER} riceve la PEPITA dal\n"
    .string "misterioso ALLENATORE!$"

Route24_Text_YouDontHaveAnyRoom_IT::
    .string "Non hai più spazio!$"

Route24_Text_JoinTeamRocket_IT::
    .string "A proposito, che ne dici di unirti a\n"
    .string "TEAM ROCKET?\p"
    .string "Siamo una banda che sfrutta i\n"
    .string "POKéMON per scopi malvagi!\p"
    .string "Vuoi diventare dei nostri?\p"
    .string "No, davvero?\p"
    .string "Dai, stai con noi!\p"
    .string "Ti dico di unirti a noi!\p"
    .string "Bene, sarò più convincente!\p"
    .string "Ti farò un'offerta che non potrai\n"
    .string "rifiutare!$"

Route24_Text_RocketDefeat_IT::
    .string "Grrr!\n"
    .string "Hai stoffa!$"

Route24_Text_YoudBecomeTopRocketLeader_IT::
    .string "Con le capacità che hai saresti un\n"
    .string "capo perfetto per TEAM ROCKET!$"

Route24_Text_ShaneIntro_IT::
    .string "Ti ho visto tra l'erba!$"

Route24_Text_ShaneDefeat_IT::
    .string "Non l'avrei detto!$"

Route24_Text_ShanePostBattle_IT::
    .string "Mi nascondo perché ho fifa di\n"
    .string "quella gente sul ponte!$"

Route24_Text_EthanIntro_IT::
    .string "Sono il nº5!\n"
    .string "Ti polverizzerò!$"

Route24_Text_EthanDefeat_IT::
    .string "Wow!\n"
    .string "Questo è troppo!$"

Route24_Text_EthanPostBattle_IT::
    .string "Ho fatto del mio meglio!\n"
    .string "Non ho rimpianti!$"

Route24_Text_ReliIntro_IT::
    .string "Sono la nº4!\n"
    .string "Ce la fai?$"

Route24_Text_ReliDefeat_IT::
    .string "Acc…\n"
    .string "ho perso anch'io!$"

Route24_Text_ReliPostBattle_IT::
    .string "Ho fatto del mio meglio!\n"
    .string "Non ho rimpianti!$"

Route24_Text_TimmyIntro_IT::
    .string "Sono il nº3!\n"
    .string "Sarà dura per te!$"

Route24_Text_TimmyDefeat_IT::
    .string "Ehi!\n"
    .string "Mi hai steso!$"

Route24_Text_TimmyPostBattle_IT::
    .string "Ho fatto del mio meglio!\n"
    .string "Non ho rimpianti!$"

Route24_Text_AliIntro_IT::
    .string "Sono la nº2!\n"
    .string "In guardia!$"

Route24_Text_AliDefeat_IT::
    .string "Come ho potuto perdere?$"

Route24_Text_AliPostBattle_IT::
    .string "Ho fatto del mio meglio!\n"
    .string "Non ho rimpianti!$"

Route24_Text_CaleIntro_IT::
    .string "Questo è il PONTE PEPITA!\p"
    .string "Se batti noi 5 ALLENATORI, vinci un\n"
    .string "premio favoloso!\p"
    .string "Pensi di avere la stoffa per\n"
    .string "vincere?$"

Route24_Text_CaleDefeat_IT::
    .string "Wow!\n"
    .string "Bel lavoro!$"

Route24_Text_CalePostBattle_IT::
    .string "Ho fatto del mio meglio!\n"
    .string "Non ho rimpianti!$"

