ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger_FR::
	.string "C'est vrai?\p"
	.string "Le CENTRE COMMERCIAL de\n"
	.string "CELADOPOLE est bien\p"
	.string "plus grand que cette boutique?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest_FR::
	.string "J'achète parfois des\n"
	.string "médicaments ici.\p"
	.string "Mais beaucoup de gens utilisent\n"
	.string "aussi les BAIES des BOIS BAIES.\p"
	.string "Après tout, les BAIES sont\n"
	.string "gratuites et poussent en quantité.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart_FR::
	.string "Ces MOTARDS allaient détruire\n"
	.string "la BOUTIQUE POKéMON.\p"
	.string "J'suis bien content qu'ils soient\n"
	.string "enfin partis!$"

