ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger_ES::
    .string "¿De verdad?\p"
    .string "¿Seguro que el CENTRO COMERCIAL\n"
    .string "de AZULONA es mucho mayor que\l"
    .string "esta tienda?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest_ES::
    .string "A veces compro medicinas aquí.\p"
    .string "Pero hay mucha gente que cura a\n"
    .string "los POKéMON con BAYAS del BOSQUE\l"
    .string "BAYA.\p"
    .string "Hombre, yo lo entiendo; las BAYAS\n"
    .string "son gratis y nunca se acaban.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart_ES::
    .string "Los MOTORISTAS han estado a punto\n"
    .string "de destrozar la TIENDA POKéMON.\p"
    .string "Menos mal que se han ido.$"
