ThreeIsland_BondBridge_Text_NikkiIntro_IT::
    .string "Mi piace il profumo dell'acqua\n"
    .string "marina.$"

ThreeIsland_BondBridge_Text_NikkiDefeat_IT::
    .string "…Sniff, sniff…\n"
    .string "Ehi, che strano odore!$"

ThreeIsland_BondBridge_Text_NikkiPostBattle_IT::
    .string "Non sarai mica tu che hai addosso\n"
    .string "quel profumo dolciastro?!$"

ThreeIsland_BondBridge_Text_VioletIntro_IT::
    .string "Dove vai così di corsa?$"

ThreeIsland_BondBridge_Text_VioletDefeat_IT::
    .string "La tua squadra è davvero\n"
    .string "notevole.$"

ThreeIsland_BondBridge_Text_VioletPostBattle_IT::
    .string "Per questa strada si raggiunge\n"
    .string "il BOSCO BACCOSO.$"

ThreeIsland_BondBridge_Text_AmiraIntro_IT::
    .string "Mia mamma non vuole che nuoti\n"
    .string "senza salvagente.$"

ThreeIsland_BondBridge_Text_AmiraDefeat_IT::
    .string "Oh, nooo!!!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle_IT::
    .string "Quest'anno voglio finalmente\n"
    .string "imparare a nuotare!$"

ThreeIsland_BondBridge_Text_AlexisIntro_IT::
    .string "Vai così!\n"
    .string "POKéMON, POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat_IT::
    .string "Vai così! Hai vinto tu?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle_IT::
    .string "Vai così! Hai vinto tu,\n"
    .string "oppure ho perso io?$"

ThreeIsland_BondBridge_Text_TishaIntro_IT::
    .string "Oh, no! Stai alla larga da\n"
    .string "me!$"

ThreeIsland_BondBridge_Text_TishaDefeat_IT::
    .string "Ora che hai vinto, vattene,\n"
    .string "ti prego!$"

ThreeIsland_BondBridge_Text_TishaPostBattle_IT::
    .string "Che tragedia! Ho perso il costume\n"
    .string "e non posso uscire dall'acqua!$"

ThreeIsland_BondBridge_Text_JoyIntro_IT::
    .string "JOY: Vuoi vedere qual è il nostro\n"
    .string "POKéMON preferito?$"

ThreeIsland_BondBridge_Text_JoyDefeat_IT::
    .string "JOY: Oooh…\n"
    .string "IDA!$"

ThreeIsland_BondBridge_Text_JoyPostBattle_IT::
    .string "JOY: Che divertimento! Spero di\n"
    .string "lottare ancora con te!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons_IT::
    .string "JOY: Io e IDA siamo una squadra\n"
    .string "fissa.\p"
    .string "Se non hai due POKéMON, non\n"
    .string "puoi lottare con noi.$"

ThreeIsland_BondBridge_Text_MegIntro_IT::
    .string "IDA: Vuoi vedere qual è il nostro\n"
    .string "POKéMON preferito?$"

ThreeIsland_BondBridge_Text_MegDefeat_IT::
    .string "IDA: Oooh…\n"
    .string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle_IT::
    .string "IDA: È stato divertente. Vero,\n"
    .string "JOY?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons_IT::
    .string "IDA: Io e JOY siamo una squadra\n"
    .string "fissa.\p"
    .string "Se non hai due POKéMON, non\n"
    .string "puoi lottare con noi.$"

ThreeIsland_BondBridge_Text_BerryForestAhead_IT::
    .string "Per BOSCO BACCOSO$"

ThreeIsland_BondBridge_Text_BondBridgeSign_IT::
    .string "PONTE ABBRACCIO\n"
    .string "Si prega di fare silenzio.\p"
    .string "Per BOSCO BACCOSO$"

