ThreeIsland_BondBridge_Text_NikkiIntro_DE::
	.string "Der salzige Geruch des Wassers…\n"
	.string "Er erfüllt mein Herz mit Freude.$"

ThreeIsland_BondBridge_Text_NikkiDefeat_DE::
	.string "… schnief, schnief…\n"
	.string "Irgendetwas riecht unangenehm…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle_DE::
	.string "Vielleicht ist es der verschwitzte\n"
	.string "Körper eines deiner POKéMON,\l"
	.string "der hier so riecht…$"

ThreeIsland_BondBridge_Text_VioletIntro_DE::
	.string "Wo willst du so eilig hin?$"

ThreeIsland_BondBridge_Text_VioletDefeat_DE::
	.string "Du trainierst einige eindrucks-\n"
	.string "volle POKéMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle_DE::
	.string "Wenn du hier weiterläufst, kommst\n"
	.string "du in den BEERENFORST.$"

ThreeIsland_BondBridge_Text_AmiraIntro_DE::
	.string "Meine Mutter sagt, dass ich ohne\n"
	.string "meinen Schwimmreif nicht\l"
	.string "schwimmen kann.$"

ThreeIsland_BondBridge_Text_AmiraDefeat_DE::
	.string "Wah!\n"
	.string "Wah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle_DE::
	.string "Dieses Jahr werde ich endlich\n"
	.string "das Schwimmen lernen!$"

ThreeIsland_BondBridge_Text_AlexisIntro_DE::
	.string "Jo, jo!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat_DE::
	.string "Was geschieht jetzt?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle_DE::
	.string "Habe ich gerade gewonnen?\n"
	.string "Oder verloren?$"

ThreeIsland_BondBridge_Text_TishaIntro_DE::
	.string "Oh, nein, komm nicht näher!\n"
	.string "Bleib mir bitte vom Leib!$"

ThreeIsland_BondBridge_Text_TishaDefeat_DE::
	.string "O.K., du hast gewonnen!\n"
	.string "Gehst du jetzt bitte weg?$"

ThreeIsland_BondBridge_Text_TishaPostBattle_DE::
	.string "Ein POKéMON hat durch meinen\n"
	.string "Badeanzug gebissen.\p"
	.string "Ich kann nicht aus dem Wasser!$"

ThreeIsland_BondBridge_Text_JoyIntro_DE::
	.string "UTE: Wir zeigen dir unser\n"
	.string "Lieblings-POKéMON!$"

ThreeIsland_BondBridge_Text_JoyDefeat_DE::
	.string "UTE: Oh…\n"
	.string "IDA!$"

ThreeIsland_BondBridge_Text_JoyPostBattle_DE::
	.string "UTE: Hat das nicht Spaß gemacht?\n"
	.string "Ich hoffe, wir wiederholen das!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons_DE::
	.string "UTE: Ich wollte wirklich mit IDA\n"
	.string "kämpfen.\p"
	.string "Ein POKéMON reicht nicht aus!$"

ThreeIsland_BondBridge_Text_MegIntro_DE::
	.string "IDA: Wir zeigen dir unsere\n"
	.string "Lieblings-POKéMON.$"

ThreeIsland_BondBridge_Text_MegDefeat_DE::
	.string "IDA: Oh…\n"
	.string "UTE!$"

ThreeIsland_BondBridge_Text_MegPostBattle_DE::
	.string "IDA: UTE, das war ein Spaß!$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons_DE::
	.string "IDA: Ich möchte mit UTE\n"
	.string "kämpfen.\p"
	.string "Ein POKéMON ist nicht genug.$"

ThreeIsland_BondBridge_Text_BerryForestAhead_DE::
	.string "BEERENFORST VORAUS$"

ThreeIsland_BondBridge_Text_BondBridgeSign_DE::
	.string "BUNDBRÜCKE\n"
	.string "Beim Überqueren bitte Ruhe!\p"
	.string "BEERENFORST VORAUS$"

