ThreeIsland_BondBridge_Text_NikkiIntro_ES::
    .string "El intenso olor a sal del mar,\n"
    .string "aaaah... me llega al corazón.$"

ThreeIsland_BondBridge_Text_NikkiDefeat_ES::
    .string "Pero ahora me huele... ¡a derrota!$"

ThreeIsland_BondBridge_Text_NikkiPostBattle_ES::
    .string "¿No serán tus POKéMON los que\n"
    .string "huelen mal?$"

ThreeIsland_BondBridge_Text_VioletIntro_ES::
    .string "¿Por qué vas con tanta prisa?$"

ThreeIsland_BondBridge_Text_VioletDefeat_ES::
    .string "¡Estás entrenando a tus POKéMON\n"
    .string "de maravilla!$"

ThreeIsland_BondBridge_Text_VioletPostBattle_ES::
    .string "Si sigues el camino que llevas,\n"
    .string "llegarás al BOSQUE BAYA.$"

ThreeIsland_BondBridge_Text_AmiraIntro_ES::
    .string "Mi mami me ha dicho que no debo\n"
    .string "nadar sin flotador.$"

ThreeIsland_BondBridge_Text_AmiraDefeat_ES::
    .string "¡Buaaaaa!\n"
    .string "¡Buaaaaaaaaaaa!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle_ES::
    .string "Este año, seguro que aprendo\n"
    .string "a nadar sola.$"

ThreeIsland_BondBridge_Text_AlexisIntro_ES::
    .string "¡POKéMON, POKéMON!\n"
    .string "¡A mí me gustan los POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat_ES::
    .string "¿Qué ha pasado?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle_ES::
    .string "¿Mis POKéMON me han fallado?$"

ThreeIsland_BondBridge_Text_TishaIntro_ES::
    .string "¡No, no, déjame, por favor!\n"
    .string "¡Déjame en paz!$"

ThreeIsland_BondBridge_Text_TishaDefeat_ES::
    .string "Vale, has ganado, ¿te irás ahora?$"

ThreeIsland_BondBridge_Text_TishaPostBattle_ES::
    .string "¡Un POKéMON me ha enganchado\n"
    .string "por el bañador!\p"
    .string "¡No me puedo mover!$"

ThreeIsland_BondBridge_Text_JoyIntro_ES::
    .string "FELI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON preferido.$"

ThreeIsland_BondBridge_Text_JoyDefeat_ES::
    .string "FELI: Oh..., MATI...$"

ThreeIsland_BondBridge_Text_JoyPostBattle_ES::
    .string "FELI: Bueno, me lo he pasado bien.\n"
    .string "Espero que podamos repetirlo.$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons_ES::
    .string "FELI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con MATI.$"

ThreeIsland_BondBridge_Text_MegIntro_ES::
    .string "MATI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON favorito.$"

ThreeIsland_BondBridge_Text_MegDefeat_ES::
    .string "MATI: Oh..., FELI...$"

ThreeIsland_BondBridge_Text_MegPostBattle_ES::
    .string "MATI: FELI, ¿te lo has pasado\n"
    .string "bien?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons_ES::
    .string "MATI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con FELI.$"

ThreeIsland_BondBridge_Text_BerryForestAhead_ES::
    .string "HACIA EL BOSQUE BAYA$"

ThreeIsland_BondBridge_Text_BondBridgeSign_ES::
    .string "PUENTE UNIÓN\n"
    .string "Crucen con cuidado.\p"
    .string "HACIA EL BOSQUE BAYA$"
