ThreeIsland_BondBridge_Text_NikkiIntro_FR::
	.string "L'odeur de la mer, le sel sur ma\n"
	.string "peau… Ça me donne la pêche!$"

ThreeIsland_BondBridge_Text_NikkiDefeat_FR::
	.string "Y'a comme une odeur bizarre…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle_FR::
	.string "Tu laves jamais tes POKéMON?\n"
	.string "Ça sent vraiment pas bon…$"

ThreeIsland_BondBridge_Text_VioletIntro_FR::
	.string "Où est-ce que tu cours si vite?$"

ThreeIsland_BondBridge_Text_VioletDefeat_FR::
	.string "Tu t'occupes vraiment bien de\n"
	.string "tes POKéMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle_FR::
	.string "Si tu continues ton chemin, tu\n"
	.string "vas tomber sur les BOIS BAIES.$"

ThreeIsland_BondBridge_Text_AmiraIntro_FR::
	.string "Ma maman elle dit que j'ai pas le\n"
	.string "droit de nager sans ma bouée.$"

ThreeIsland_BondBridge_Text_AmiraDefeat_FR::
	.string "Waaah!\n"
	.string "Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle_FR::
	.string "Juré craché, cette année\n"
	.string "j'apprendrai à nager!$"

ThreeIsland_BondBridge_Text_AlexisIntro_FR::
	.string "Yeah, yeah!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat_FR::
	.string "Qu'est-ce qui s'est passé?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle_FR::
	.string "J'ai gagné ou… ?\n"
	.string "Je viens de perdre là!$"

ThreeIsland_BondBridge_Text_TishaIntro_FR::
	.string "Oh non, ne viens pas là!\n"
	.string "Reste loin de moi!$"

ThreeIsland_BondBridge_Text_TishaDefeat_FR::
	.string "OK, t'as gagné!\n"
	.string "Tu veux bien me laisser maintenant?$"

ThreeIsland_BondBridge_Text_TishaPostBattle_FR::
	.string "Un POKéMON a mordu ma combi.\n"
	.string "J'arrive pas à sortir de l'eau!$"

ThreeIsland_BondBridge_Text_JoyIntro_FR::
	.string "BEA: Tu vas vite comprendre quel\n"
	.string "est notre POKéMON favori!$"

ThreeIsland_BondBridge_Text_JoyDefeat_FR::
	.string "BEA: Ohh…\n"
	.string "EVA!!$"

ThreeIsland_BondBridge_Text_JoyPostBattle_FR::
	.string "BEA: C'était marrant, hein?\n"
	.string "J'espère qu'on se reverra.$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons_FR::
	.string "BEA: J'aimerais beaucoup que tu\n"
	.string "nous affrontes, EVA et moi.\p"
	.string "Mais il te faudra plus d'un\n"
	.string "POKéMON.$"

ThreeIsland_BondBridge_Text_MegIntro_FR::
	.string "EVA: Tu vas vite comprendre quel\n"
	.string "est notre POKéMON favori!$"

ThreeIsland_BondBridge_Text_MegDefeat_FR::
	.string "EVA: Ohh…\n"
	.string "BEA!!$"

ThreeIsland_BondBridge_Text_MegPostBattle_FR::
	.string "EVA: C'était marrant, hein?\n"
	.string "J'espère qu'on se reverra.$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons_FR::
	.string "EVA: J'aimerais beaucoup que tu\n"
	.string "nous affrontes BEA et moi.\p"
	.string "Mais il te faudra plus d'un\n"
	.string "POKéMON.$"

ThreeIsland_BondBridge_Text_BerryForestAhead_FR::
	.string "BOIS BAIES\n"
	.string "DROIT DEVANT$"

ThreeIsland_BondBridge_Text_BondBridgeSign_FR::
	.string "PONT DU LIEN\n"
	.string "Silence en traversant.\p"
	.string "BOIS BAIES DROIT DEVANT$"

