FiveIsland_ResortGorgeous_Text_DaisyIntro_IT::
    .string "Sto dipingendo un quadro per\n"
    .string "celebrare la mia prossima vittoria.$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat_IT::
    .string "Ecco, ora sono diventata tutta\n"
    .string "rossa per la vergogna!$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle_IT::
    .string "Tutti i miei pennelli, e i colori,\n"
    .string "spazzati via!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro_IT::
    .string "Come vedi, sto provando a\n"
    .string "dipingere, e tu non sei di certo un\l"
    .string "buon soggetto. Smamma, su!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat_IT::
    .string "Invece di lottare, era meglio se ti\n"
    .string "facevo un ritratto…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle_IT::
    .string "GIANNA, gira un po' la testa!\n"
    .string "Così, perfetto! Che ritratto!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro_IT::
    .string "Forse è un problema di\n"
    .string "prospettiva…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat_IT::
    .string "Mi sento spenta, come i colori\n"
    .string "dei miei quadri!$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle_IT::
    .string "Il cielo e il mare hanno colori\n"
    .string "così cangianti!\p"
    .string "Per questo è difficile catturarne\n"
    .string "lo splendore.$"

FiveIsland_ResortGorgeous_Text_JackiIntro_IT::
    .string "Sono venuta a trovare una mia\n"
    .string "amica che è qui per riposarsi.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat_IT::
    .string "Ehi, sei proprio forte!$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle_IT::
    .string "È bello lottare con questa fresca\n"
    .string "brezza che ci accarezza!$"

FiveIsland_ResortGorgeous_Text_GillianIntro_IT::
    .string "Pensavo di farmi costruire una\n"
    .string "piscina speciale per i POKéMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat_IT::
    .string "Ho perso? Devo essermi distratta!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle_IT::
    .string "Una piscina sarebbe fantastica,\n"
    .string "ma forse è meglio un solarium.$"

FiveIsland_ResortGorgeous_Text_DestinIntro_IT::
    .string "Corro veloce, sai? Sono una\n"
    .string "scheggia.$"

FiveIsland_ResortGorgeous_Text_DestinDefeat_IT::
    .string "Forse ho corso troppo!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle_IT::
    .string "Quando corro sospinto dal vento,\n"
    .string "mi sembra di volare!$"

FiveIsland_ResortGorgeous_Text_TobyIntro_IT::
    .string "Mi piace l'atmosfera rilassata che\n"
    .string "regna su quest'isola.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat_IT::
    .string "Ecco, ora mi hai fatto tornare\n"
    .string "l'ansia!$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle_IT::
    .string "Rilassati! Tu prendi tutto troppo\n"
    .string "sul serio!$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow_IT::
    .string "NOIANNA: Grazie, puoi andare ora.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse_IT::
    .string "CASA di NOIANNA$"

