FiveIsland_ResortGorgeous_Text_DaisyIntro_DE::
	.string "Mit diesen Händen werde ich\n"
	.string "den Sieg herbeiführen.$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat_DE::
	.string "Diese Schande…\n"
	.string "Ich werde rot…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle_DE::
	.string "Ugh! Meine Farbeimer sind\n"
	.string "überall verstreut.$"

FiveIsland_ResortGorgeous_Text_CelinaIntro_DE::
	.string "Entschuldigung!\n"
	.string "Ich versuche zu malen.\l"
	.string "Geh mir bitte aus der Sicht!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat_DE::
	.string "Diese Niederlage…\n"
	.string "Mir wird so schwindlig…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle_DE::
	.string "GILLIAN?\n"
	.string "Bitte beweg deinen Kopf ein wenig…\l"
	.string "Genau! Dieser Blick ist es!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro_DE::
	.string "Hmm…\n"
	.string "Der Winkel ist noch nicht perfekt…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat_DE::
	.string "Oh…\n"
	.string "Meine Emotionen sind blau…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle_DE::
	.string "Der Himmel und das Meer…\n"
	.string "Sie sind so wankelmütig.\p"
	.string "Ihr ständig wechselnder Ausdruck\n"
	.string "macht es nicht leicht, sie\l"
	.string "malerisch einzufangen.$"

FiveIsland_ResortGorgeous_Text_JackiIntro_DE::
	.string "Ich besuche das Sommerhaus\n"
	.string "meines Freundes, wenn\l"
	.string "du fragst.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat_DE::
	.string "Oh, du bist stark!$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle_DE::
	.string "Ich finde es angenehm, bei einer\n"
	.string "sanften Meeresbrise zum\l"
	.string "Spaß zu kämpfen.$"

FiveIsland_ResortGorgeous_Text_GillianIntro_DE::
	.string "Ich denke darüber nach, einen\n"
	.string "Pool nur für POKéMON\l"
	.string "einzurichten.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat_DE::
	.string "Oh, meine Güte!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle_DE::
	.string "Ein Pool wäre cool, aber ein\n"
	.string "Solarium wäre noch besser.$"

FiveIsland_ResortGorgeous_Text_DestinIntro_DE::
	.string "Ich bin ein starker Sprinter.\n"
	.string "Ich bin wirklich schnell!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat_DE::
	.string "Ups!\n"
	.string "Ich war zu schnell!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle_DE::
	.string "Wenn ich mit dem Wind renne,\n"
	.string "fühlt es sich an, als ob ich\l"
	.string "fliegen würde…$"

FiveIsland_ResortGorgeous_Text_TobyIntro_DE::
	.string "Das maritime Leben hier sagt\n"
	.string "mir zu!$"

FiveIsland_ResortGorgeous_Text_TobyDefeat_DE::
	.string "Das ist Wahnsinn!\n"
	.string "Du machst Witze!$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle_DE::
	.string "Das so ernst zu nehmen…\n"
	.string "Wie unsensibel.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow_DE::
	.string "KEA: Danke!\p"
	.string "Du darfst jetzt gehen!$"

FiveIsland_ResortGorgeous_Text_SelphysHouse_DE::
	.string "KEAs HAUS$"

