CeruleanCity_Mart_Text_RepelWorksOnWeakMons_ES::
    .string "Usa el REPELENTE para evitar a los\n"
    .string "bichos y a los POKéMON débiles.\p"
    .string "¡Pon a tu POKéMON más fuerte el\n"
    .string "primero de la lista para conseguir\l"
    .string "mejores resultados!\p"
    .string "Si tu primer POKéMON es fuerte,\n"
    .string "el REPELENTE tendrá mayor efecto.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy_ES::
    .string "¿Has visto algún CARAMELORARO?\p"
    .string "¡Dicen que los POKéMON suben\n"
    .string "un nivel si se comen uno!$"
