CeruleanCity_Mart_Text_RepelWorksOnWeakMons_FR::
	.string "Le REPOUSSE tient les POKéMON\n"
	.string "sauvages à l'écart.\p"
	.string "Mets tes POKéMON les plus costauds\n"
	.string "en premier pour une plus grande\p"
	.string "efficacité! Si ton premier POKéMON\n"
	.string "est fort, l'effet est boosté.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy_FR::
	.string "Tu connais les SUPER BONBONS? On\n"
	.string "ne les trouve pas à la vente.\p"
	.string "Quand un POKéMON en mange un, il\n"
	.string "gagne un niveau!$"

