CeruleanCity_Mart_Text_RepelWorksOnWeakMons_DE::
	.string "Benutze einen SCHUTZ, um Käfer und\n"
	.string "schwächere POKéMON von dir\l"
	.string "fernzuhalten!\p"
	.string "Für optimalen Schutz solltest du\n"
	.string "das stärkste POKéMON an die Spitze\l"
	.string "der Liste setzen!\p"
	.string "Wenn das POKéMON, das an erster\n"
	.string "Stelle steht stark ist, wirkt SCHUTZ\l"
	.string "noch besser!$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy_DE::
	.string "Besitzt du SONDERBONBONs?\p"
	.string "Gibt man einem POKéMON ein solches\n"
	.string "BONBON, dann erreicht es den\l"
	.string "nächsten Level!$"

