Route11_Text_HugoIntro_FR::
	.string "Tu veux gagner ou perdre?$"

Route11_Text_HugoDefeat_FR::
	.string "OK.\n"
	.string "T'as gagné!$"

Route11_Text_HugoPostBattle_FR::
	.string "Les POKéMON c'est la vie!\n"
	.string "Et la vie c'est le jeu!$"

Route11_Text_JasperIntro_FR::
	.string "J'adore les défis!$"

Route11_Text_JasperDefeat_FR::
	.string "J'ai eu ma chance!$"

Route11_Text_JasperPostBattle_FR::
	.string "Dans le monde merveilleux des\n"
	.string "POKéMON, y'a pas de lâches!$"

Route11_Text_EddieIntro_FR::
	.string "On y va!\n"
	.string "Mais triche pas!$"

Route11_Text_EddieDefeat_FR::
	.string "Rha!\n"
	.string "C'est pas vrai!$"

Route11_Text_EddiePostBattle_FR::
	.string "J'ai fait de mon mieux! Pas ma\n"
	.string "faute si j'suis nul!$"

Route11_Text_BraxtonIntro_FR::
	.string "Attention!\n"
	.string "Je pose des câbles!$"

Route11_Text_BraxtonDefeat_FR::
	.string "J'me suis pris du jus!$"

Route11_Text_BraxtonPostBattle_FR::
	.string "Il faut économiser l'énergie!$"

Route11_Text_DillonIntro_FR::
	.string "Je suis nouveau, mais je sais que\n"
	.string "je peux gagner!$"

Route11_Text_DillonDefeat_FR::
	.string "Mes POKéMON sont nuls!\n"
	.string "Beuh…\p"
	.string "J'ai pas dû les faire assez\n"
	.string "progresser.$"

Route11_Text_DillonPostBattle_FR::
	.string "Quoi encore?\n"
	.string "Laisse-moi!$"

Route11_Text_DirkIntro_FR::
	.string "HAHAHA!\n"
	.string "J'ai jamais perdu!$"

Route11_Text_DirkDefeat_FR::
	.string "Heu?\n"
	.string "Ma première défaite!$"

Route11_Text_DirkPostBattle_FR::
	.string "Tu as la chance des débutants!$"

Route11_Text_DarianIntro_FR::
	.string "Je n'ai encore jamais gagné…$"

Route11_Text_DarianDefeat_FR::
	.string "Je m'y attendais…$"

Route11_Text_DarianPostBattle_FR::
	.string "J'suis maudit, je crois!$"

Route11_Text_YasuIntro_FR::
	.string "Je suis le plus fort de ma classe!$"

Route11_Text_YasuDefeat_FR::
	.string "Argh!\n"
	.string "Tu veux être le chef de classe?$"

Route11_Text_YasuPostBattle_FR::
	.string "Il y a un gros POKéMON qui vient\n"
	.string "de la montagne.\p"
	.string "Si t'es fort, tu pourrais l'attraper.$"

Route11_Text_BernieIntro_FR::
	.string "Fais attention aux câbles!$"

Route11_Text_BernieDefeat_FR::
	.string "Whoa!\n"
	.string "Tu fais des étincelles!$"

Route11_Text_BerniePostBattle_FR::
	.string "Bon, j'ai du boulot, moi!$"

Route11_Text_DaveIntro_FR::
	.string "Mes POKéMON sont prêts!$"

Route11_Text_DaveDefeat_FR::
	.string "Trop, trop balèze!$"

Route11_Text_DavePostBattle_FR::
	.string "Faut que j'en chope des\n"
	.string "plus forts!$"

Route11_Text_DiglettsCave_FR::
	.string "CAVE TAUPIQUEUR$"

