Route11_Text_HugoIntro_ES::
    .string "¡Gana, pierde o empata!$"

Route11_Text_HugoDefeat_ES::
    .string "¡Vale!\n"
    .string "¡Has ganado!$"

Route11_Text_HugoPostBattle_ES::
    .string "¡Los POKéMON son vida!\n"
    .string "¡Y vivir es jugar!$"

Route11_Text_JasperIntro_ES::
    .string "¡Competición!\n"
    .string "¡No me canso de competir!$"

Route11_Text_JasperDefeat_ES::
    .string "¡He perdido la oportunidad!$"

Route11_Text_JasperPostBattle_ES::
    .string "¡No se puede ser cobarde\n"
    .string "en el mundo de los POKéMON!$"

Route11_Text_EddieIntro_ES::
    .string "¡Vamos allá, pero no hagas\n"
    .string "trampas!$"

Route11_Text_EddieDefeat_ES::
    .string "¿Qué?\n"
    .string "¡No puede ser!$"

Route11_Text_EddiePostBattle_ES::
    .string "¡He hecho lo que he podido!\n"
    .string "¡Y no me arrepiento!$"

Route11_Text_BraxtonIntro_ES::
    .string "¡Cuidado!\n"
    .string "¡Estoy colocando unos cables!$"

Route11_Text_BraxtonDefeat_ES::
    .string "¡Electrizante!$"

Route11_Text_BraxtonPostBattle_ES::
    .string "¡Di a todos que ahorren energía!$"

Route11_Text_DillonIntro_ES::
    .string "¡Me acabo de hacer ENTRENADOR!\n"
    .string "¡Pero creo que puedo ganar!$"

Route11_Text_DillonDefeat_ES::
    .string "¡Mis POKéMON han perdido!$"

Route11_Text_DillonPostBattle_ES::
    .string "¿Qué quieres?\n"
    .string "¡Déjame en paz!$"

Route11_Text_DirkIntro_ES::
    .string "¡Ja, ja, ja!\n"
    .string "¡No he perdido nunca!$"

Route11_Text_DirkDefeat_ES::
    .string "¡La primera vez que pierdo!$"

Route11_Text_DirkPostBattle_ES::
    .string "¡Has tenido mucha suerte!$"

Route11_Text_DarianIntro_ES::
    .string "Nunca he ganado...$"

Route11_Text_DarianDefeat_ES::
    .string "Lo veía venir...$"

Route11_Text_DarianPostBattle_ES::
    .string "Has tenido mucha suerte.$"

Route11_Text_YasuIntro_ES::
    .string "¡Soy el mejor de mi clase!$"

Route11_Text_YasuDefeat_ES::
    .string "¡Vaya! ¡Mis POKéMON deberían\n"
    .string "ser más fuertes!$"

Route11_Text_YasuPostBattle_ES::
    .string "Hay un POKéMON muy gordo\n"
    .string "que baja de las montañas.\p"
    .string "Seguro que es muy fuerte.$"

Route11_Text_BernieIntro_ES::
    .string "¡Cuidado con esos cables!$"

Route11_Text_BernieDefeat_ES::
    .string "¡Uaauu!\n"
    .string "¡Vaya chispazo!$"

Route11_Text_BerniePostBattle_ES::
    .string "¡Más vale que vuelva al trabajo!$"

Route11_Text_DaveIntro_ES::
    .string "¡Mis POKéMON ya deberían\n"
    .string "estar listos!$"

Route11_Text_DaveDefeat_ES::
    .string "¡Soy demasiado joven!$"

Route11_Text_DavePostBattle_ES::
    .string "¡Voy a buscarme unos más fuertes!$"

Route11_Text_DiglettsCave_ES::
    .string "CUEVA DE DIGLETT$"
