Route11_Text_HugoIntro_IT::
    .string "Scommettiamo sulla tua\n"
    .string "sconfitta?$"

Route11_Text_HugoDefeat_IT::
    .string "Accidenti!\n"
    .string "Mi è andata male!$"

Route11_Text_HugoPostBattle_IT::
    .string "I POKéMON sono vita!\n"
    .string "E vivere è giocare!$"

Route11_Text_JasperIntro_IT::
    .string "Sfide?!\n"
    .string "Non ne ho mai abbastanza!$"

Route11_Text_JasperDefeat_IT::
    .string "Ho avuto la mia occasione!$"

Route11_Text_JasperPostBattle_IT::
    .string "Non puoi essere un codardo nel\n"
    .string "mondo dei POKéMON!$"

Route11_Text_EddieIntro_IT::
    .string "OK, lottiamo!\n"
    .string "Ma non imbrogliare!$"

Route11_Text_EddieDefeat_IT::
    .string "Cosa?\n"
    .string "Non può essere!$"

Route11_Text_EddiePostBattle_IT::
    .string "Ho fatto tutto il possibile!\n"
    .string "Non ho rimpianti!$"

Route11_Text_BraxtonIntro_IT::
    .string "Attenzione!\n"
    .string "Sto posando dei cavi!$"

Route11_Text_BraxtonDefeat_IT::
    .string "La tua è elettricità pura!$"

Route11_Text_BraxtonPostBattle_IT::
    .string "Bisogna risparmiare elettricità!\n"
    .string "Mi raccomando, spargi la voce!$"

Route11_Text_DillonIntro_IT::
    .string "Sono ALLENATORE da poco!\n"
    .string "Ma penso di poter vincere!$"

Route11_Text_DillonDefeat_IT::
    .string "I miei POKéMON hanno perso!$"

Route11_Text_DillonPostBattle_IT::
    .string "Che vuoi?\n"
    .string "Lasciami in pace!$"

Route11_Text_DirkIntro_IT::
    .string "Ihaha!\n"
    .string "Non ho mai perso!$"

Route11_Text_DirkDefeat_IT::
    .string "C'è sempre una prima volta!$"

Route11_Text_DirkPostBattle_IT::
    .string "La fortuna del principiante!$"

Route11_Text_DarianIntro_IT::
    .string "Non ho ancora mai vinto…$"

Route11_Text_DarianDefeat_IT::
    .string "Me l'immaginavo…$"

Route11_Text_DarianPostBattle_IT::
    .string "Chissà quando riuscirò a vincere\n"
    .string "una lotta!$"

Route11_Text_YasuIntro_IT::
    .string "Sono il primo della classe!$"

Route11_Text_YasuDefeat_IT::
    .string "Accidenti!\n"
    .string "Devo rinforzare i miei POKéMON!$"

Route11_Text_YasuPostBattle_IT::
    .string "C'è un POKéMON grasso che è sceso\n"
    .string "dai monti!\p"
    .string "È forte!\n"
    .string "Catturalo!$"

Route11_Text_BernieIntro_IT::
    .string "Attenzione ai cavi scoperti!$"

Route11_Text_BernieDefeat_IT::
    .string "Wow!\n"
    .string "Sei una scheggia!$"

Route11_Text_BerniePostBattle_IT::
    .string "Meglio tornare al lavoro!$"

Route11_Text_DaveIntro_IT::
    .string "I miei POKéMON dovrebbero essere\n"
    .string "pronti ormai!$"

Route11_Text_DaveDefeat_IT::
    .string "No, i miei POKéMON non sono\n"
    .string "ancora all'altezza.$"

Route11_Text_DavePostBattle_IT::
    .string "Meglio cercarne di più forti!$"

Route11_Text_DiglettsCave_IT::
    .string "GROTTA DIGLETT$"

