Route11_Text_HugoIntro_DE::
	.string "Versuche dein Glück gegen mich!$"

Route11_Text_HugoDefeat_DE::
	.string "Das Glück hat mich verlassen!$"

Route11_Text_HugoPostBattle_DE::
	.string "Das ganze Leben ist ein\n"
	.string "Glücksspiel!$"

Route11_Text_JasperIntro_DE::
	.string "Wettkämpfe!\n"
	.string "Ich kann ihnen nicht widerstehen!$"

Route11_Text_JasperDefeat_DE::
	.string "Immerhin hatte ich eine Chance!$"

Route11_Text_JasperPostBattle_DE::
	.string "Feiglinge haben in der Welt der\n"
	.string "POKéMON keine Chance!$"

Route11_Text_EddieIntro_DE::
	.string "Hast du Lust mit mir zu kämpfen?$"

Route11_Text_EddieDefeat_DE::
	.string "Hä?\n"
	.string "Das ist gemein!$"

Route11_Text_EddiePostBattle_DE::
	.string "Immerhin habe ich es versucht!\n"
	.string "Ich schäme mich nicht!$"

Route11_Text_BraxtonIntro_DE::
	.string "Vorsicht!\n"
	.string "Ich verlege hier gerade Kabel!$"

Route11_Text_BraxtonDefeat_DE::
	.string "Das war ein Stromschlag!$"

Route11_Text_BraxtonPostBattle_DE::
	.string "Schone die Umwelt und spare\n"
	.string "Energie!$"

Route11_Text_DillonIntro_DE::
	.string "Ich habe gerade erst angefangen,\n"
	.string "POKéMON zu trainieren!$"

Route11_Text_DillonDefeat_DE::
	.string "Mist!\n"
	.string "Ich hasse schwache POKéMON!$"

Route11_Text_DillonPostBattle_DE::
	.string "Was willst du noch?\n"
	.string "Lass mich endlich allein!$"

Route11_Text_DirkIntro_DE::
	.string "Haha!\n"
	.string "Bisher habe ich noch nie verloren!$"

Route11_Text_DirkDefeat_DE::
	.string "Es gibt immer ein erstes Mal...$"

Route11_Text_DirkPostBattle_DE::
	.string "Das war purer Zufall!\n"
	.string "Nichts als Glück!$"

Route11_Text_DarianIntro_DE::
	.string "Ich habe noch nie gewonnen...$"

Route11_Text_DarianDefeat_DE::
	.string "Das habe ich kommen sehen!$"

Route11_Text_DarianPostBattle_DE::
	.string "Das war nichts als Glück.\n"
	.string "Purer Zufall!$"

Route11_Text_YasuIntro_DE::
	.string "In meiner Klasse bin ich der Beste!$"

Route11_Text_YasuDefeat_DE::
	.string "Ich muss meine POKéMON mehr\n"
	.string "trainieren!$"

Route11_Text_YasuPostBattle_DE::
	.string "Aus den Bergen steigt manchmal ein\n"
	.string "dickes POKéMON herab.\p"
	.string "Es ist sehr stark!\n"
	.string "Versuche es zu fangen!$"

Route11_Text_BernieIntro_DE::
	.string "Nimm dich vor Hochspannung in\n"
	.string "Acht!$"

Route11_Text_BernieDefeat_DE::
	.string "Au!\n"
	.string "Der Funke ist übergesprungen!$"

Route11_Text_BerniePostBattle_DE::
	.string "Ich mache mich besser wieder an\n"
	.string "die Arbeit.$"

Route11_Text_DaveIntro_DE::
	.string "Meine POKéMON müssten bereit sein!$"

Route11_Text_DaveDefeat_DE::
	.string "Das war schwach!$"

Route11_Text_DavePostBattle_DE::
	.string "Ich muss ein paar stärkere fangen!$"

Route11_Text_DiglettsCave_DE::
	.string "DIGDAs HÖHLE$"

