CeladonCity_House1_Text_SlotsReelInTheDough_ES::
    .string "¡Jejeje!\p"
    .string "¡He ganado una pasta!\n"
    .string "¡Bravo!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes_ES::
    .string "¡JEFE!\p"
    .string "¡Acabamos de enviar 2.000\n"
    .string "POKéMON a modo de premio!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster_ES::
    .string "¡No toques el cartel del CASINO!\p"
    .string "¡No hay ningún botón secreto\n"
    .string "detrás!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar_ES::
    .string "ぶつだん　だ‥$"
