CeladonCity_House1_Text_SlotsReelInTheDough_FR::
	.string "Yahahaha!\n"
	.string "Triple 7!!!\l"
	.string "Par ici l'pognon!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes_FR::
	.string "CHEF!\p"
	.string "2000 POKéMON ont été envoyés\n"
	.string "comme prix au casino!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster_FR::
	.string "Ne touche pas au bouton derrière\n"
	.string "le poster du CASINO!\p"
	.string "Hein?\n"
	.string "Mais non j'l'ai pas dit!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar_FR::
	.string "ぶつだん　だ‥$"

