CeladonCity_House1_Text_SlotsReelInTheDough_IT::
    .string "Wow!\p"
    .string "Ho vinto della grana alle slot!\n"
    .string "Bel colpo!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes_IT::
    .string "CAPO!\p"
    .string "Abbiamo spedito 2.000 POKéMON\n"
    .string "come premi!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster_IT::
    .string "Non toccare il poster al CASINÒ!\p"
    .string "Non c'è nessun pulsante segreto\n"
    .string "dietro!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar_IT::
    .string "ぶつだん　だ‥$"

