SixIsland_OutcastIsland_Text_RocketIntro_DE::
	.string "Hier gibt es keine seltenen\n"
	.string "POKéMON! Nicht eines!\p"
	.string "Das ärgert mich, Kiddie! Daher\n"
	.string "kämpfe ich jetzt mit dir!$"

SixIsland_OutcastIsland_Text_RocketDefeat_DE::
	.string "… HÄH?$"

SixIsland_OutcastIsland_Text_RocketPostBattle_DE::
	.string "Hast du ein seltenes POKéMON\n"
	.string "gesehen? Sag es mir!$"

SixIsland_OutcastIsland_Text_TylorIntro_DE::
	.string "Ich habe kein Glück!\n"
	.string "Ein Kampf wäre ein willkommener\l"
	.string "Rhythmuswechsel.$"

SixIsland_OutcastIsland_Text_TylorDefeat_DE::
	.string "Nein, überhaupt kein Glück…$"

SixIsland_OutcastIsland_Text_TylorPostBattle_DE::
	.string "Ich kann nicht nach Hause, ohne\n"
	.string "etwas gefangen zu haben!$"

SixIsland_OutcastIsland_Text_MymoIntro_DE::
	.string "Schnauf… schnauf…\p"
	.string "Ich bin hier auf einmal vom\n"
	.string "HAFEN auf EILAND SECHS\l"
	.string "her geschwommen.$"

SixIsland_OutcastIsland_Text_MymoDefeat_DE::
	.string "Schnauf…\n"
	.string "Schnauf…$"

SixIsland_OutcastIsland_Text_MymoPostBattle_DE::
	.string "Ich bin erst bei der Hälfte…\n"
	.string "Ich wurde besiegt…$"

SixIsland_OutcastIsland_Text_NicoleIntro_DE::
	.string "Es ist nicht leicht, beim Schwimmen\n"
	.string "POKéMON in den Kampf zu\l"
	.string "schicken.$"

SixIsland_OutcastIsland_Text_NicoleDefeat_DE::
	.string "Du hast mich nicht im Schwimmen\n"
	.string "geschlagen. Der Rest ist egal.$"

SixIsland_OutcastIsland_Text_NicolePostBattle_DE::
	.string "Bist du auf dem Weg zu der Insel\n"
	.string "dort oben?\p"
	.string "Ich habe dort nichts Interessantes\n"
	.string "gesehen!$"

SixIsland_OutcastIsland_Text_AvaIntro_DE::
	.string "TINA: Lass uns einen Zwei-gegen-\n"
	.string "Zwei Marinekampf bestreiten!$"

SixIsland_OutcastIsland_Text_AvaDefeat_DE::
	.string "TINA: Oh, du überraschst mich!\n"
	.string "Noch besser, du bist allein!$"

SixIsland_OutcastIsland_Text_AvaPostBattle_DE::
	.string "TINA: Ich bevorzuge das Meer\n"
	.string "gegenüber jedem Pool.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons_DE::
	.string "TINA: Du forderst uns zu einem\n"
	.string "Kampf heraus?\p"
	.string "Du benötigst dafür allerdings\n"
	.string "mindestens zwei POKéMON.$"

SixIsland_OutcastIsland_Text_GebIntro_DE::
	.string "TINO: Hilf mir, große Schwester!\n"
	.string "Bitte kämpfe mit mir!$"

SixIsland_OutcastIsland_Text_GebDefeat_DE::
	.string "TINO: Wow, große Schwester, diese\n"
	.string "Person ist richtig gut!$"

SixIsland_OutcastIsland_Text_GebPostBattle_DE::
	.string "TINO: Ich bin auf meine Schwester\n"
	.string "angewiesen, da ich den Boden\l"
	.string "nicht berühren kann.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons_DE::
	.string "TINO: Bitte kämpfe gegen mich und\n"
	.string "meine Schwester!\p"
	.string "… oh, du hast keine zwei POKéMON?$"

