SixIsland_OutcastIsland_Text_RocketIntro_ES::
    .string "Por aquí no hay ni un sólo\n"
    .string "POKéMON raro. ¡Ni uno!\p"
    .string "¡Estoy hasta el gorro de buscar!\n"
    .string "¡Te ha tocado pagar el mosqueo,\l"
    .string "lo siento!$"

SixIsland_OutcastIsland_Text_RocketDefeat_ES::
    .string "¡¿Qué?!$"

SixIsland_OutcastIsland_Text_RocketPostBattle_ES::
    .string "Tú no has visto ningún POKéMON\n"
    .string "raro, ¿no?$"

SixIsland_OutcastIsland_Text_TylorIntro_ES::
    .string "¡Qué mala suerte tengo hoy!\n"
    .string "¡Igual la cosa cambia si luchamos!$"

SixIsland_OutcastIsland_Text_TylorDefeat_ES::
    .string "Nada, hoy no es mi día.$"

SixIsland_OutcastIsland_Text_TylorPostBattle_ES::
    .string "¡Pero es que no puedo volver\n"
    .string "a casa con las manos vacías!$"

SixIsland_OutcastIsland_Text_MymoIntro_ES::
    .string "Ufff... Ufff...\p"
    .string "Vengo nadando desde el PUERTO\n"
    .string "de ISLA EXTA sin parar.$"

SixIsland_OutcastIsland_Text_MymoDefeat_ES::
    .string "Ufff...\n"
    .string "Ufff...$"

SixIsland_OutcastIsland_Text_MymoPostBattle_ES::
    .string "Voy por la mitad...\n"
    .string "Y ya no puedo más...$"

SixIsland_OutcastIsland_Text_NicoleIntro_ES::
    .string "No es fácil sacar POKéMON mientras\n"
    .string "se nada, ¿lo sabías?$"

SixIsland_OutcastIsland_Text_NicoleDefeat_ES::
    .string "He perdido, pero seguro que\n"
    .string "nadando no me ganas.$"

SixIsland_OutcastIsland_Text_NicolePostBattle_ES::
    .string "¿Vas a la isla que hay al norte?\n"
    .string "Yo no vi nada de interés.$"

SixIsland_OutcastIsland_Text_AvaIntro_ES::
    .string "ALI: ¡Vamos a echarnos un combate\n"
    .string "disfrutando de la brisa marina!$"

SixIsland_OutcastIsland_Text_AvaDefeat_ES::
    .string "ALI: ¡Eres increíble! ¡Además\n"
    .string "no te hace falta nadie de apoyo!$"

SixIsland_OutcastIsland_Text_AvaPostBattle_ES::
    .string "ALI: Prefiero mil veces el mar\n"
    .string "antes que la piscina.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons_ES::
    .string "ALI: ¿Quieres luchar con nosotros?\p"
    .string "Pues te hacen falta dos POKéMON\n"
    .string "por lo menos para luchar.$"

SixIsland_OutcastIsland_Text_GebIntro_ES::
    .string "ROS: Hermanita, ¡ayuda!\n"
    .string "¡Lucha conmigo!$"

SixIsland_OutcastIsland_Text_GebDefeat_ES::
    .string "ROS: Hermanita, ¡qué fuerte es!$"

SixIsland_OutcastIsland_Text_GebPostBattle_ES::
    .string "ROS: Yo me agarro a mi hermanita,\n"
    .string "porque no hago pie.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons_ES::
    .string "ROS: ¡Lucha con mi hermanita\n"
    .string "y conmigo!\p"
    .string "Ah..., ¿no tienes dos POKéMON?\n"
    .string "Entonces, no.$"
