Route14_Text_CarterIntro_ES::
    .string "¡Usa las MT para enseñar a tus\n"
    .string "POKéMON buenos movimientos!$"

Route14_Text_CarterDefeat_ES::
    .string "¡No lo he hecho muy bien!$"

Route14_Text_CarterPostBattle_ES::
    .string "Tienes MO, ¿no? Los POKéMON\n"
    .string "jamás olvidarán esos movimientos.$"

Route14_Text_MitchIntro_ES::
    .string "Mis pájaros POKéMON deberían\n"
    .string "poder luchar.$"

Route14_Text_MitchDefeat_ES::
    .string "¡No estoy listo!$"

Route14_Text_MitchPostBattle_ES::
    .string "Necesitan saber mejores ataques.$"

Route14_Text_BeckIntro_ES::
    .string "¡Se venden MT en AZULONA!\n"
    .string "¡Pero pocas personas tienen MO!$"

Route14_Text_BeckDefeat_ES::
    .string "¡Ayy! ¡Qué mal!$"

Route14_Text_BeckPostBattle_ES::
    .string "Enseña a tus POKéMON ataques\n"
    .string "de sus mismos tipos para conseguir\l"
    .string "más potencia.$"

Route14_Text_MarlonIntro_ES::
    .string "¿Has enseñado a VOLAR a tus\n"
    .string "pájaros POKéMON?\p"
    .string "¡Es genial para ir por el cielo!$"

Route14_Text_MarlonDefeat_ES::
    .string "¡Qué forma de perder!$"

Route14_Text_MarlonPostBattle_ES::
    .string "¡Adoro a los pájaros POKéMON!\n"
    .string "¡Son los que me gusta criar!$"

Route14_Text_DonaldIntro_ES::
    .string "¿Has oído hablar de los\n"
    .string "misteriosos seres alados?$"

Route14_Text_DonaldDefeat_ES::
    .string "¿Qué?\n"
    .string "¿Cómo he podido perder?$"

Route14_Text_DonaldPostBattle_ES::
    .string "Los misteriosos seres alados son\n"
    .string "legendarios pájaros POKéMON.\p"
    .string "Hay tres: ARTICUNO, ZAPDOS\n"
    .string "y MOLTRES.$"

Route14_Text_BennyIntro_ES::
    .string "¡No me apetece!\n"
    .string "Pero vale.$"

Route14_Text_BennyDefeat_ES::
    .string "¡Lo sabía!$"

Route14_Text_BennyPostBattle_ES::
    .string "¡No es que sea tan importante\n"
    .string "ganar o perder!$"

Route14_Text_LukasIntro_ES::
    .string "¡Venga, venga!\n"
    .string "¡Vamos, vamos! ¡Adelante!$"

Route14_Text_LukasDefeat_ES::
    .string "¡Arg!\n"
    .string "¡He perdido! ¡Lárgate!$"

Route14_Text_LukasPostBattle_ES::
    .string "¿Qué, qué, qué?\n"
    .string "¿Qué quieres?$"

Route14_Text_IsaacIntro_ES::
    .string "¡Perfecto!\n"
    .string "¡Así pasaré el rato!$"

Route14_Text_IsaacDefeat_ES::
    .string "¿Qué?\n"
    .string "¿¡Tú!?$"

Route14_Text_IsaacPostBattle_ES::
    .string "¡Entrenar POKéMON es un rollo!$"

Route14_Text_GeraldIntro_ES::
    .string "¡Salimos por aquí porque hay\n"
    .string "más espacio!$"

Route14_Text_GeraldDefeat_ES::
    .string "¡Descalificado!$"

Route14_Text_GeraldPostBattle_ES::
    .string "¡Muy bien!\n"
    .string "¡Tus POKéMON son superfuertes!\p"
    .string "¡La fuerza mola!\n"
    .string "¡Y tú lo sabes!$"

Route14_Text_MalikIntro_ES::
    .string "¿Quieres pelear con tus POKéMON?\n"
    .string "¡Pues vale!$"

Route14_Text_MalikDefeat_ES::
    .string "¡Pulverizado!$"

Route14_Text_MalikPostBattle_ES::
    .string "¡Ya sabes quién ganaría\n"
    .string "si peleáramos tú y yo!$"

Route14_Text_RouteSign_ES::
    .string "RUTA 14:\n"
    .string "CIUDAD FUCSIA, al oeste$"

Route14_Text_KiriIntro_ES::
    .string "LENA: TEA, vamos a poner todo\n"
    .string "de nuestra parte.$"

Route14_Text_KiriDefeat_ES::
    .string "LENA: Vaya, snif, snif...\n"
    .string "Hemos perdido, ¿verdad?$"

Route14_Text_KiriPostBattle_ES::
    .string "LENA: ¿Hemos perdido por mi culpa?$"

Route14_Text_KiriNotEnoughMons_ES::
    .string "LENA: Lucharemos cuando tengas\n"
    .string "dos POKéMON.$"

Route14_Text_JanIntro_ES::
    .string "TEA: LENA, ¡vamos allá!\n"
    .string "¡A por todas!$"

Route14_Text_JanDefeat_ES::
    .string "TEA: ¡Eeeh! ¡No es justo!$"

Route14_Text_JanPostBattle_ES::
    .string "TEA: ¡LENA, no llores! ¡Ya lo\n"
    .string "haremos mejor la próxima vez!$"

Route14_Text_JanNotEnoughMons_ES::
    .string "TEA: ¿Quieres luchar?\n"
    .string "¡Te hacen falta dos POKéMON!$"
