Route14_Text_CarterIntro_IT::
    .string "Usa le MT per insegnare buone\n"
    .string "mosse ai POKéMON!$"

Route14_Text_CarterDefeat_IT::
    .string "Ancora non va!$"

Route14_Text_CarterPostBattle_IT::
    .string "Hai delle MN, eh? I POKéMON non\n"
    .string "dimenticheranno mai quelle mosse.$"

Route14_Text_MitchIntro_IT::
    .string "I miei POKéMON uccello sono pronti\n"
    .string "a lottare.$"

Route14_Text_MitchDefeat_IT::
    .string "No! Non lo erano!$"

Route14_Text_MitchPostBattle_IT::
    .string "Devono imparare mosse migliori.$"

Route14_Text_BeckIntro_IT::
    .string "Si vendono MT ad AZZURROPOLI!\n"
    .string "Le MN invece sono rare!$"

Route14_Text_BeckDefeat_IT::
    .string "Ahi! Che dolore!$"

Route14_Text_BeckPostBattle_IT::
    .string "Insegna ai POKéMON mosse del\n"
    .string "loro stesso tipo perché siano più\l"
    .string "potenti.$"

Route14_Text_MarlonIntro_IT::
    .string "Hai insegnato il VOLO ai tuoi\n"
    .string "POKéMON uccello?$"

Route14_Text_MarlonDefeat_IT::
    .string "Mi hai bruciato!$"

Route14_Text_MarlonPostBattle_IT::
    .string "Adoro i POKéMON uccello!$"

Route14_Text_DonaldIntro_IT::
    .string "Hai mai sentito parlare della\n"
    .string "leggenda dei miraggi alati?$"

Route14_Text_DonaldDefeat_IT::
    .string "Ho perso?\n"
    .string "Perché? Perché?$"

Route14_Text_DonaldPostBattle_IT::
    .string "I miraggi alati non sono altro che\n"
    .string "i POKéMON uccelli leggendari.\p"
    .string "Sono tre: ZAPDOS, ARTICUNO\n"
    .string "e MOLTRES.$"

Route14_Text_BennyIntro_IT::
    .string "Non sono un grande esperto,\n"
    .string "però lottare mi piace!$"

Route14_Text_BennyDefeat_IT::
    .string "Lo sapevo!$"

Route14_Text_BennyPostBattle_IT::
    .string "Vincere o perdere che importanza\n"
    .string "ha, in fondo?!$"

Route14_Text_LukasIntro_IT::
    .string "Forza! Forza!\n"
    .string "Avanti, andiamo, sottoooo!$"

Route14_Text_LukasDefeat_IT::
    .string "Grr!\n"
    .string "Ho perso! Smamma!$"

Route14_Text_LukasPostBattle_IT::
    .string "Che? Che? Che?\n"
    .string "Che vuoi?$"

Route14_Text_IsaacIntro_IT::
    .string "Devo ingannare il tempo, a volte!$"

Route14_Text_IsaacDefeat_IT::
    .string "Cosa?\n"
    .string "Tu?!$"

Route14_Text_IsaacPostBattle_IT::
    .string "Allenare i POKéMON è una\n"
    .string "faticaccia!$"

Route14_Text_GeraldIntro_IT::
    .string "Veniamo qui con la moto perché c'è\n"
    .string "più spazio!$"

Route14_Text_GeraldDefeat_IT::
    .string "Smamma!$"

Route14_Text_GeraldPostBattle_IT::
    .string "Fooorte!\n"
    .string "I tuoi POKéMON sono potentissimi!\p"
    .string "La forza è tutto!\n"
    .string "E tu lo sai!$"

Route14_Text_MalikIntro_IT::
    .string "Lotta POKéMON?\n"
    .string "Come no!$"

Route14_Text_MalikDefeat_IT::
    .string "Spazzato via!$"

Route14_Text_MalikPostBattle_IT::
    .string "Sapevi chi avrebbe vinto!\n"
    .string "Che sfida!$"

Route14_Text_RouteSign_IT::
    .string "PERCORSO 14\n"
    .string "FUCSIAPOLI a ovest$"

Route14_Text_KiriIntro_IT::
    .string "KIRI: Dai, JAN!\n"
    .string "Non possiamo perdere!$"

Route14_Text_KiriDefeat_IT::
    .string "KIRI: Abbiamo perso, vero?$"

Route14_Text_KiriPostBattle_IT::
    .string "KIRI: Abbiamo perso a\n"
    .string "causa mia?$"

Route14_Text_KiriNotEnoughMons_IT::
    .string "KIRI: Quando avrai due POKéMON,\n"
    .string "potrai tornare qui a sfidarci.$"

Route14_Text_JanIntro_IT::
    .string "JAN: Dai, KIRI! Possiamo\n"
    .string "farcela!$"

Route14_Text_JanDefeat_IT::
    .string "JAN: Eh, no! Non ce l'abbiamo\n"
    .string "fatta!$"

Route14_Text_JanPostBattle_IT::
    .string "JAN: Non piangere, KIRI!\n"
    .string "La prossima volta andrà meglio!$"

Route14_Text_JanNotEnoughMons_IT::
    .string "JAN: Vuoi combattere? Ti manca\n"
    .string "un POKéMON. Te ne servono due.$"

