Route14_Text_CarterIntro_DE::
	.string "Damit POKéMON starke Attacken\n"
	.string "erlernen, muss man TM einsetzen!$"

Route14_Text_CarterDefeat_DE::
	.string "Ich war zu schlecht!$"

Route14_Text_CarterPostBattle_DE::
	.string "Eine durch eine VM erlernte Attacke\n"
	.string "können POKéMON nicht so leicht\l"
	.string "wieder vergessen!$"

Route14_Text_MitchIntro_DE::
	.string "Meine Vogel-POKéMON sind gut auf\n"
	.string "Kämpfe vorbereitet!$"

Route14_Text_MitchDefeat_DE::
	.string "Sie waren nicht stark genug...$"

Route14_Text_MitchPostBattle_DE::
	.string "Sie müssen stärkere Attacken\n"
	.string "lernen!$"

Route14_Text_BeckIntro_DE::
	.string "In PRISMANIA CITY kann man TMs\n"
	.string "kaufen.\p"
	.string "VMs besitzen allerdings nur wenige\n"
	.string "Personen.$"

Route14_Text_BeckDefeat_DE::
	.string "Ohh! So ein Mist!$"

Route14_Text_BeckPostBattle_DE::
	.string "Bringe POKéMON ihrem Element\n"
	.string "entsprechende Attacken bei, um ihre\l"
	.string "volle Stärke auszunutzen!$"

Route14_Text_MarlonIntro_DE::
	.string "Hast du einem Vogel-POKéMON\n"
	.string "schon das FLIEGEN beigebracht?$"

Route14_Text_MarlonDefeat_DE::
	.string "War das eine Bruchlandung!$"

Route14_Text_MarlonPostBattle_DE::
	.string "Meine Leidenschaft sind Vogel-\n"
	.string "POKéMON!$"

Route14_Text_DonaldIntro_DE::
	.string "Hast du die Legende von den\n"
	.string "Illusionen mit Flügeln gehört?$"

Route14_Text_DonaldDefeat_DE::
	.string "Warum hab ich verloren?$"

Route14_Text_DonaldPostBattle_DE::
	.string "Nun, die Illusionen mit Flügeln sind\n"
	.string "die legendären Vogel-POKéMON.\p"
	.string "Es gibt drei: ARKTOS, ZAPDOS\n"
	.string "und LAVADOS.$"

Route14_Text_BennyIntro_DE::
	.string "Ich will nicht unbedingt, aber lass\n"
	.string "uns dennoch kämpfen!$"

Route14_Text_BennyDefeat_DE::
	.string "Ich wusste, ich würde verlieren!$"

Route14_Text_BennyPostBattle_DE::
	.string "Längerfristig ist es egal, ob man\n"
	.string "gewinnt oder verliert!$"

Route14_Text_LukasIntro_DE::
	.string "Los, los! Lass uns kämpfen. Auf in\n"
	.string "den Kampf! Los!$"

Route14_Text_LukasDefeat_DE::
	.string "Arrgh!\n"
	.string "Hau bloß ab!$"

Route14_Text_LukasPostBattle_DE::
	.string "Was, was, was?\n"
	.string "Was willst du?$"

Route14_Text_IsaacIntro_DE::
	.string "Sehr gut!\n"
	.string "Ich brauche einen Zeitvertreib!$"

Route14_Text_IsaacDefeat_DE::
	.string "Du hast mich besiegt?\n"
	.string "Oh Mann!$"

Route14_Text_IsaacPostBattle_DE::
	.string "Es ist ganz schön mühselig,\n"
	.string "POKéMON zu trainieren!$"

Route14_Text_GeraldIntro_DE::
	.string "Wir kommen öfter her, weil es hier\n"
	.string "so unglaublich viel Platz gibt!$"

Route14_Text_GeraldDefeat_DE::
	.string "Kurz und schmerzlos!$"

Route14_Text_GeraldPostBattle_DE::
	.string "Cool!\n"
	.string "Deine POKéMON sind wirklich stark!\p"
	.string "Macht geht vor Recht!\n"
	.string "Du hast es begriffen!$"

Route14_Text_MalikIntro_DE::
	.string "Ein POKéMON-KAMPF?\n"
	.string "Cool! Leg los, Balg!$"

Route14_Text_MalikDefeat_DE::
	.string "Voll erwischt!$"

Route14_Text_MalikPostBattle_DE::
	.string "Du gegen mich!\n"
	.string "Du weißt, wer gewinnt!$"

Route14_Text_RouteSign_DE::
	.string "ROUTE 14\n"
	.string "WESTEN: FUCHSANIA CITY$"

Route14_Text_KiriIntro_DE::
	.string "BERTA: ENKE, lass es uns\n"
	.string "wirklich zusammen versuchen.$"

Route14_Text_KiriDefeat_DE::
	.string "BERTA: Wimmer…\n"
	.string "Wir haben verloren, oder?$"

Route14_Text_KiriPostBattle_DE::
	.string "BERTA: Haben wir\n"
	.string "meinetwegen verloren?$"

Route14_Text_KiriNotEnoughMons_DE::
	.string "BERTA: Wir können kämpfen, wenn\n"
	.string "du zwei POKéMON hast.$"

Route14_Text_JanIntro_DE::
	.string "ENKE: BERTA, los jetzt!\n"
	.string "Wir müssen uns anstrengen!$"

Route14_Text_JanDefeat_DE::
	.string "ENKE: Argh!\n"
	.string "Oh, nein!$"

Route14_Text_JanPostBattle_DE::
	.string "ENKE: Weine nicht, BERTA!\n"
	.string "Wir strengen uns beim nächsten\l"
	.string "Mal noch mehr an!$"

Route14_Text_JanNotEnoughMons_DE::
	.string "ENKE: Du möchtest kämpfen?\n"
	.string "Du hast nicht genug POKéMON!$"

