Route14_Text_CarterIntro_FR::
	.string "Utilise des CT pour apprendre de\n"
	.string "bonnes attaques à tes POKéMON!$"

Route14_Text_CarterDefeat_FR::
	.string "…\n"
	.string "Pas encore assez bon!$"

Route14_Text_CarterPostBattle_FR::
	.string "Tu as des CS?\n"
	.string "Les POKéMON ne peuvent pas\l"
	.string "les oublier.$"

Route14_Text_MitchIntro_FR::
	.string "Mes POKéMON oiseau veulent\n"
	.string "se battre.$"

Route14_Text_MitchDefeat_FR::
	.string "…\n"
	.string "Y veulent plus!$"

Route14_Text_MitchPostBattle_FR::
	.string "Il leur faut de bonnes attaques.$"

Route14_Text_BeckIntro_FR::
	.string "On vend des CT au CENTRE\n"
	.string "COMMERCIAL de CELADOPOLE!\p"
	.string "Mais, seuls quelques élus ont\n"
	.string "des CS!$"

Route14_Text_BeckDefeat_FR::
	.string "Ah!\n"
	.string "Fiasco complet!$"

Route14_Text_BeckPostBattle_FR::
	.string "Apprends à tes POKéMON des\n"
	.string "attaques de leur type.\p"
	.string "Apparemment, ça booste la\n"
	.string "puissance de l'attaque.$"

Route14_Text_MarlonIntro_FR::
	.string "As-tu appris VOL à tes POKéMON\n"
	.string "oiseau?\p"
	.string "Grâce à ça, tu pourras voyager\n"
	.string "dans le ciel sur leur dos.$"

Route14_Text_MarlonDefeat_FR::
	.string "Ah!\n"
	.string "Je me suis brûlé les ailes!$"

Route14_Text_MarlonPostBattle_FR::
	.string "J'adore les POKéMON oiseau,\n"
	.string "je ne m'intéresse qu'à eux!$"

Route14_Text_DonaldIntro_FR::
	.string "Connais-tu la légende des\n"
	.string "mirages ailés?$"

Route14_Text_DonaldDefeat_FR::
	.string "Ah?\n"
	.string "J'ai perdu?$"

Route14_Text_DonaldPostBattle_FR::
	.string "Les mirages ailés seraient les\n"
	.string "POKéMON oiseau légendaires.\p"
	.string "Ils sont trois: ARTIKODIN,\n"
	.string "ELECTHOR et SULFURA.$"

Route14_Text_BennyIntro_FR::
	.string "J'suis pas d'humeur! Mais bon…$"

Route14_Text_BennyDefeat_FR::
	.string "Ben, t'as gagné, non?$"

Route14_Text_BennyPostBattle_FR::
	.string "Perdre ou gagner, c'est pas le plus\n"
	.string "important!$"

Route14_Text_LukasIntro_FR::
	.string "Allez, viens! Tu vas voir la tête\n"
	.string "de tes POKéMON!$"

Route14_Text_LukasDefeat_FR::
	.string "Arrg!\n"
	.string "Hors de ma vue!$"

Route14_Text_LukasPostBattle_FR::
	.string "Quoi? Quoi?\n"
	.string "Tu veux quoi?$"

Route14_Text_IsaacIntro_FR::
	.string "Parfait!\n"
	.string "Je m'ennuyais!$"

Route14_Text_IsaacDefeat_FR::
	.string "Quoi?\n"
	.string "Me faire battre par toi?$"

Route14_Text_IsaacPostBattle_FR::
	.string "Elever des POKéMON, c'est crevant!$"

Route14_Text_GeraldIntro_FR::
	.string "Y'a plein de place pour les\n"
	.string "balades ici!$"

Route14_Text_GeraldDefeat_FR::
	.string "Balayé!$"

Route14_Text_GeraldPostBattle_FR::
	.string "Cool, tes POKéMON sont super\n"
	.string "balèzes!\p"
	.string "La force, c'est important, mais\n"
	.string "tu le sais, non?$"

Route14_Text_MalikIntro_FR::
	.string "Un combat de POKéMON?\n"
	.string "Tremble, minable!$"

Route14_Text_MalikDefeat_FR::
	.string "J'suis dans l'vent!$"

Route14_Text_MalikPostBattle_FR::
	.string "Tu sais que sans tes POKéMON,\n"
	.string "je te pulvérise!$"

Route14_Text_RouteSign_FR::
	.string "ROUTE 14\n"
	.string "PARMANIE à l'Ouest$"

Route14_Text_KiriIntro_FR::
	.string "JOY: KATE, essayons ensemble!$"

Route14_Text_KiriDefeat_FR::
	.string "JOY: …\n"
	.string "On a perdu, hein?$"

Route14_Text_KiriPostBattle_FR::
	.string "JOY: On a perdu à cause de moi?$"

Route14_Text_KiriNotEnoughMons_FR::
	.string "JOY: On pourra se battre si tu\n"
	.string "viens avec deux POKéMON.$"

Route14_Text_JanIntro_FR::
	.string "KATE: Allons-y!\n"
	.string "Faisons de notre mieux!$"

Route14_Text_JanDefeat_FR::
	.string "KATE: Aaaah!\n"
	.string "C'est pas juste!$"

Route14_Text_JanPostBattle_FR::
	.string "KATE: Ne pleure pas JOY!\n"
	.string "On fera mieux la prochaine fois.$"

Route14_Text_JanNotEnoughMons_FR::
	.string "KATE: Tu veux te battre?\n"
	.string "Mais t'as pas assez de POKéMON!$"

