ViridianCity_School_Text_TryingToMemorizeNotes_ES::
    .string "Estoy intentando memorizar todos\n"
    .string "mis apuntes.$"

ViridianCity_School_Text_ReadBlackboardCarefully_ES::
    .string "¡Muy bien!\p"
    .string "¡No olvides leer la pizarra con\n"
    .string "mucha atención!$"

ViridianCity_School_Text_NotebookFirstPage_ES::
    .string "A ver qué pone en el cuaderno...\p"
    .string "Primera página...\p"
    .string "Las POKé BALLS son para atrapar\n"
    .string "a los POKéMON.\p"
    .string "Puedes llevar hasta 6 POKéMON.\p"
    .string "Los ENTRENADORES son la gente\n"
    .string "que entrena y hace pelear a sus\l"
    .string "POKéMON.$"

ViridianCity_School_Text_NotebookSecondPage_ES::
    .string "Segunda página...\p"
    .string "¡Un POKéMON sano no es tan fácil\n"
    .string "de atrapar, conviene debilitarlo\l"
    .string "primero!\p"
    .string "¡Los venenos, las quemaduras y\n"
    .string "otros daños son muy efectivos!$"

ViridianCity_School_Text_NotebookThirdPage_ES::
    .string "Tercera página...\p"
    .string "Los ENTRENADORES POKéMON luchan\n"
    .string "contra otros, en combates POKéMON.\p"
    .string "Lo cierto es que la victoria tiene\n"
    .string "un sabor muy dulce.\p"
    .string "En los GIMNASIOS siempre se están\n"
    .string "librando combates POKéMON.$"

ViridianCity_School_Text_NotebookFourthPage_ES::
    .string "Cuarta página...\p"
    .string "El objetivo de todo ENTRENADOR\n"
    .string "es derrotar a los 8 mejores\l"
    .string "LÍDERES de GIMNASIO.\p"
    .string "Si lo consigue, podrá desafiar...\p"
    .string "¡Al ALTO MANDO de la LIGA\n"
    .string "POKéMON!$"

ViridianCity_School_Text_TurnThePage_ES::
    .string "¿Paso la página?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes_ES::
    .string "NIÑA: ¡Oye!\n"
    .string "¡No mires mis apuntes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems_ES::
    .string "La pizarra indica los cambios de\n"
    .string "las CARACTERÍSTICAS de los\l"
    .string "POKéMON durante los combates.$"

ViridianCity_School_Text_ReadWhichTopic_ES::
    .string "¿Sobre qué tema te gustaría leer?$"

ViridianCity_School_Text_ExplainSleep_ES::
    .string "¡Un POKéMON no puede atacar si\n"
    .string "está dormido!\p"
    .string "¡Los POKéMON seguirán dormidos\n"
    .string "incluso después de pelear!\p"
    .string "¡Usa DESPERTAR y se despertarán!$"

ViridianCity_School_Text_ExplainBurn_ES::
    .string "Toda quemadura reduce la fuerza\n"
    .string "del ATAQUE y va restando PS.\p"
    .string "Las quemaduras permanecerán tras\n"
    .string "el combate.\p"
    .string "¡ANTIQUEMAR curará las\n"
    .string "quemaduras!$"

ViridianCity_School_Text_ExplainPoison_ES::
    .string "Todo POKéMON envenenado\n"
    .string "seguirá perdiendo energía.\p"
    .string "El veneno sigue haciendo efecto\n"
    .string "tras el combate.\p"
    .string "¡Usa un ANTÍDOTO para curar\n"
    .string "el envenenamiento!$"

ViridianCity_School_Text_ExplainFreeze_ES::
    .string "¡Todo POKéMON congelado no podrá\n"
    .string "moverse!\p"
    .string "Y permanecerá congelado tras el\n"
    .string "combate.\p"
    .string "¡Usa el ANTIHIELO para\n"
    .string "descongelar a los POKéMON!$"

ViridianCity_School_Text_ExplainParalysis_ES::
    .string "¡La parálisis podría anular ciertos\n"
    .string "movimientos!\p"
    .string "Y permanece tras el combate.\p"
    .string "Usa ANTIPARALIZAR para liberar a\n"
    .string "los POKéMON que estén paralizados.$"
