ViridianCity_School_Text_TryingToMemorizeNotes_IT::
    .string "Sto cercando di memorizzare tutti\n"
    .string "gli appunti.$"

ViridianCity_School_Text_ReadBlackboardCarefully_IT::
    .string "Va bene!\p"
    .string "Leggi molto attentamente la\n"
    .string "lavagna!$"

ViridianCity_School_Text_NotebookFirstPage_IT::
    .string "Guarda il quaderno!\p"
    .string "Pagina uno…\p"
    .string "Le POKé BALL servono per\n"
    .string "catturare i POKéMON.\p"
    .string "Si possono portare fino a sei\n"
    .string "POKéMON.\p"
    .string "L'ALLENATORE è chi addestra e fa\n"
    .string "lottare i suoi POKéMON.$"

ViridianCity_School_Text_NotebookSecondPage_IT::
    .string "Pagina due…\p"
    .string "È dura catturare i POKéMON nel\n"
    .string "pieno delle forze!\p"
    .string "Prima, quindi, è meglio indebolirli.\p"
    .string "Anche causare scottature,\n"
    .string "avvelenamenti e simili problemi\l"
    .string "di stato è molto utile.$"

ViridianCity_School_Text_NotebookThirdPage_IT::
    .string "Pagina tre…\p"
    .string "Ogni ALLENATORE di POKéMON ne\n"
    .string "cerca altri con cui lottare.\p"
    .string "Nelle PALESTRE sono sempre\n"
    .string "in corso lotte con i POKéMON.$"

ViridianCity_School_Text_NotebookFourthPage_IT::
    .string "Pagina quattro…\p"
    .string "Lo scopo di tutti gli ALLENATORI è\n"
    .string "battere gli 8 CAPOPALESTRA\l"
    .string "migliori.\p"
    .string "Solo così potrai sfidare…\p"
    .string "…i SUPERQUATTRO della LEGA\n"
    .string "POKéMON!$"

ViridianCity_School_Text_TurnThePage_IT::
    .string "Girare pagina?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes_IT::
    .string "RAGAZZA: Ehi!\n"
    .string "Spii i miei appunti?!$"

ViridianCity_School_Text_BlackboardListsStatusProblems_IT::
    .string "La lavagna indica i cambiamenti di\n"
    .string "STATO dei POKéMON durante le\l"
    .string "lotte.$"

ViridianCity_School_Text_ReadWhichTopic_IT::
    .string "Quale argomento vuoi leggere?$"

ViridianCity_School_Text_ExplainSleep_IT::
    .string "Un POKéMON non può attaccare se\n"
    .string "sta dormendo!\p"
    .string "I POKéMON continuano a dormire\n"
    .string "anche dopo la lotta!\p"
    .string "Usa la SVEGLIA per svegliarli!$"

ViridianCity_School_Text_ExplainBurn_IT::
    .string "Le scottature riducono l'ATTACCO,\n"
    .string "oltre a causare una progressiva\l"
    .string "perdita di PS.\p"
    .string "Le scottature persistono anche\n"
    .string "dopo la lotta.\p"
    .string "Il rimedio adatto è\n"
    .string "l'ANTISCOTTATURA!$"

ViridianCity_School_Text_ExplainPoison_IT::
    .string "Se avvelenati, i POKéMON perdono\n"
    .string "continuamente energia.\p"
    .string "Il veleno rimane nel loro corpo\n"
    .string "dopo la lotta.\p"
    .string "Usa un ANTIDOTO per curare i tuoi\n"
    .string "POKéMON!$"

ViridianCity_School_Text_ExplainFreeze_IT::
    .string "I POKéMON congelati sono\n"
    .string "immobilizzati!\p"
    .string "Il problema persiste anche dopo la\n"
    .string "lotta.\p"
    .string "Usa l'ANTIGELO per scongelarli!$"

ViridianCity_School_Text_ExplainParalysis_IT::
    .string "La paralisi riduce la VELOCITÀ e\n"
    .string "può impedire a un POKéMON di\l"
    .string "muoversi.\p"
    .string "La paralisi permane anche dopo la\n"
    .string "lotta. Usa l'ANTIPARALISI per\l"
    .string "curarla.$"

