ViridianCity_School_Text_TryingToMemorizeNotes_FR::
	.string "Pfouh!\n"
	.string "J'essaie d'apprendre mes leçons.$"

ViridianCity_School_Text_ReadBlackboardCarefully_FR::
	.string "OK!\p"
	.string "Lis attentivement le tableau\n"
	.string "avant de partir!$"

ViridianCity_School_Text_NotebookFirstPage_FR::
	.string "Vous examinez le journal!\p"
	.string "Première page…\p"
	.string "Les POKé BALLS peuvent capturer\n"
	.string "les POKéMON.\p"
	.string "Jusqu'à 6 POKéMON sont\n"
	.string "transportables.\p"
	.string "Les personnes s'occupant des\n"
	.string "POKéMON sont des DRESSEURS\l"
	.string "de POKéMON.$"

ViridianCity_School_Text_NotebookSecondPage_FR::
	.string "Deuxième page…\p"
	.string "Un POKéMON sauvage et en pleine\n"
	.string "forme est difficile à capturer,\l"
	.string "alors affaiblissez-le!\p"
	.string "Le poison, la brûlure et les autres\n"
	.string "types de dégâts sont aussi\l"
	.string "efficaces!$"

ViridianCity_School_Text_NotebookThirdPage_FR::
	.string "Troisième page…\p"
	.string "Le but de chaque DRESSEUR est\n"
	.string "d'affronter les autres DRESSEURS\l"
	.string "dans des combats de POKéMON.\p"
	.string "Les combats se tiennent en\n"
	.string "permanence dans les ARENES\l"
	.string "POKéMON.$"

ViridianCity_School_Text_NotebookFourthPage_FR::
	.string "Quatrième page…\p"
	.string "Le rêve de chaque DRESSEUR est de\n"
	.string "vaincre les 8 CHAMPIONS des\l"
	.string "différentes ARENES POKéMON.\p"
	.string "Ces victoires donnent le droit\n"
	.string "d'affronter…\p"
	.string "le CONSEIL 4 de la LIGUE\n"
	.string "POKéMON!$"

ViridianCity_School_Text_TurnThePage_FR::
	.string "Tourner la page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes_FR::
	.string "FILLE: Hé!\n"
	.string "Ne lis pas mon journal!$"

ViridianCity_School_Text_BlackboardListsStatusProblems_FR::
	.string "Le tableau décrit les changements\n"
	.string "de STATUT des POKéMON pendant\l"
	.string "un combat.$"

ViridianCity_School_Text_ReadWhichTopic_FR::
	.string "Lire quel sujet?$"

ViridianCity_School_Text_ExplainSleep_FR::
	.string "Un POKéMON ne peut attaquer\n"
	.string "s'il est endormi!\p"
	.string "Un POKéMON reste endormi même\n"
	.string "après un combat.\p"
	.string "Un REVEIL peut le remettre\n"
	.string "sur pied!$"

ViridianCity_School_Text_ExplainBurn_FR::
	.string "La BRULURE réduit la puissance.\n"
	.string "Elle inflige aussi des dégâts\l"
	.string "continus.\p"
	.string "La brûlure ne disparaît pas après\n"
	.string "un combat.\p"
	.string "L'ANTI-BRULE soigne les grands\n"
	.string "brûlés!$"

ViridianCity_School_Text_ExplainPoison_FR::
	.string "Un POKéMON empoisonné voit son\n"
	.string "énergie se vider doucement.\p"
	.string "Le poison ne disparaît pas après\n"
	.string "un combat.\p"
	.string "L'ANTIDOTE soigne le poison!$"

ViridianCity_School_Text_ExplainFreeze_FR::
	.string "Un POKéMON gelé reste\n"
	.string "immobile!\p"
	.string "Il reste gelé même après la fin du\n"
	.string "combat.\p"
	.string "Un ANTIGEL peut réchauffer un\n"
	.string "POKéMON!$"

ViridianCity_School_Text_ExplainParalysis_FR::
	.string "La paralysie peut annuler certaines\n"
	.string "attaques!\p"
	.string "La paralysie ne disparaît pas après\n"
	.string "un combat.\p"
	.string "L'ANTI-PARA soigne toute paralysie!$"

