SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner_ES::
    .string "¡Este lujoso barco es para\n"
    .string "los ENTRENADORES!\p"
    .string "¡En cada puerto celebramos\n"
    .string "una fiesta para los ENTRENADORES!$"

SSAnne_2F_Corridor_Text_RivalIntro_ES::
    .string "{RIVAL}:\n"
    .string "¡Bonjour, {PLAYER}!\p"
    .string "¡Ya sabía yo que te vería por\n"
    .string "aquí! ¿{PLAYER}, te han invitado?\p"
    .string "¿Y qué tal va tu POKéDEX?\p"
    .string "¡Yo ya tengo 40 POKéMON!\n"
    .string "¡Están por todas partes!\p"
    .string "¡Adéntrate en las zonas de hierba\n"
    .string "alta!$"

SSAnne_2F_Corridor_Text_RivalDefeat_ES::
    .string "¡Vaya!\p"
    .string "¡Parece que has entrenado bien\n"
    .string "a tus POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory_ES::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle_ES::
    .string "{RIVAL}: Decían que había un\n"
    .string "maestro del CORTE a bordo.\p"
    .string "¡Pero sólo era un viejo mareado!\p"
    .string "¡Sin embargo, la técnica del CORTE\n"
    .string "es muy útil!\p"
    .string "¡Deberías ir a verle!\n"
    .string "¡Hasta luego!$"
