SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner_IT::
    .string "Questa è una nave di lusso su cui\n"
    .string "viaggiano gli ALLENATORI!\p"
    .string "In ogni porto si tengono feste ad\n"
    .string "invito!$"

SSAnne_2F_Corridor_Text_RivalIntro_IT::
    .string "{RIVAL}: Ciao!\n"
    .string "{PLAYER}!\p"
    .string "Mi aspettavo di trovarti qui!\n"
    .string "{PLAYER}, ce l'hai l'invito?\p"
    .string "E come procede il tuo POKéDEX?\p"
    .string "Ho già catturato 40 specie di\n"
    .string "POKéMON, sai!\p"
    .string "Ce ne sono ovunque!\n"
    .string "Si aggirano nell'erba alta!$"

SSAnne_2F_Corridor_Text_RivalDefeat_IT::
    .string "Uffa!\p"
    .string "Almeno tu stai allenando i tuoi\n"
    .string "POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory_IT::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle_IT::
    .string "{RIVAL}: Si dice ci sia a bordo un\n"
    .string "maestro di TAGLIO.\p"
    .string "In realtà è solo un vecchio con il\n"
    .string "mal di mare!\p"
    .string "Ma il TAGLIO è davvero utile!\p"
    .string "Dovresti andare a trovarlo! Beh,\n"
    .string "ciao allora! Ci becchiamo in giro!$"

