Route10_Text_MarkIntro_DE::
	.string "Bist du auch ein POKéMANIAC?\n"
	.string "Möchtest du meine Sammlung sehen?$"

Route10_Text_MarkDefeat_DE::
	.string "Na ja, macht nichts!$"

Route10_Text_MarkPostBattle_DE::
	.string "Zu Hause habe ich noch mehr\n"
	.string "seltene POKéMON!$"

Route10_Text_ClarkIntro_DE::
	.string "Ha-ha-ha-ha!$"

Route10_Text_ClarkDefeat_DE::
	.string "Ha-ha!\n"
	.string "Haha-ha-tschi!$"

Route10_Text_ClarkPostBattle_DE::
	.string "Schnief...\n"
	.string "Diese verdammte Erkältung!$"

Route10_Text_HermanIntro_DE::
	.string "Heh du, möchtest du meine POKéMON\n"
	.string "sehen?$"

Route10_Text_HermanDefeat_DE::
	.string "Nein!\n"
	.string "Meine POKéMON!$"

Route10_Text_HermanPostBattle_DE::
	.string "Ich nehme dir übel, dass du mich\n"
	.string "besiegt hast!$"

Route10_Text_HeidiIntro_DE::
	.string "Jedes Mal, wenn ich in einer\n"
	.string "POKéMON-ARENA gekämpft habe,\l"
	.string "wurde ich besiegt!$"

Route10_Text_HeidiDefeat_DE::
	.string "Nein!\n"
	.string "Nicht schon wieder!$"

Route10_Text_HeidiPostBattle_DE::
	.string "Ich habe einige POKéMANIACS in\n"
	.string "dieser Gegend gesehen.$"

Route10_Text_TrentIntro_DE::
	.string "Ahh! Die Bergluft ist so wunderbar\n"
	.string "erfrischend!$"

Route10_Text_TrentDefeat_DE::
	.string "Ich kann wieder klar denken!$"

Route10_Text_TrentPostBattle_DE::
	.string "Ich habe von Bergluft die Nase\n"
	.string "gestrichen voll!$"

Route10_Text_CarolIntro_DE::
	.string "Ich fühle mich vom vielen Wandern\n"
	.string "erschöpft...$"

Route10_Text_CarolDefeat_DE::
	.string "Ich bin nicht fit!$"

Route10_Text_CarolPostBattle_DE::
	.string "Viele POKéMON in dieser Gegend\n"
	.string "sind grob!\p"
	.string "Ich wünschte, eines wäre rosa mit\n"
	.string "einem Blumenmuster!$"

Route10_Text_RockTunnelDetourToLavender_DE::
	.string "FELSTUNNEL\n"
	.string "Umleitung nach LAVANDIA$"

Route10_Text_RockTunnel_DE::
	.string "FELSTUNNEL$"

Route10_Text_PowerPlant_DE::
	.string "KRAFTWERK$"

