Route10_Text_MarkIntro_IT::
    .string "Sai che sono un POKéFANATICO?\n"
    .string "Vuoi vedere la mia collezione?$"

Route10_Text_MarkDefeat_IT::
    .string "Puh!\n"
    .string "Non sono arrabbiato!$"

Route10_Text_MarkPostBattle_IT::
    .string "A casa ho altri POKéMON rari!$"

Route10_Text_ClarkIntro_IT::
    .string "Ah-ahah-ah-ah!$"

Route10_Text_ClarkDefeat_IT::
    .string "Ah-ahah!\n"
    .string "Non sto ridendo!\l"
    .string "È ah-al-lergia! Ahah-ac-ciù!$"

Route10_Text_ClarkPostBattle_IT::
    .string "Ahah-ac-ciù!\n"
    .string "Ac-ciù!\l"
    .string "Snif, snif! Sigh, sigh!$"

Route10_Text_HermanIntro_IT::
    .string "Ehi!\n"
    .string "Ti mostro i miei POKéMON!$"

Route10_Text_HermanDefeat_IT::
    .string "Oh no!\n"
    .string "I miei poveri POKéMON!$"

Route10_Text_HermanPostBattle_IT::
    .string "Non mi piace essere battuto!$"

Route10_Text_HeidiIntro_IT::
    .string "Vado spesso alla PALESTRA\n"
    .string "POKéMON, ma perdo sempre!$"

Route10_Text_HeidiDefeat_IT::
    .string "Uff!\n"
    .string "Ho perso ancora!$"

Route10_Text_HeidiPostBattle_IT::
    .string "Ho visto dei POKéFANATICI da\n"
    .string "queste parti.$"

Route10_Text_TrentIntro_IT::
    .string "Ah!\n"
    .string "Quest'aria di montagna!$"

Route10_Text_TrentDefeat_IT::
    .string "Ora ho le idee più chiare!$"

Route10_Text_TrentPostBattle_IT::
    .string "L'aria di montagna mi confonde!$"

Route10_Text_CarolIntro_IT::
    .string "Questa gita mi ha stancato!$"

Route10_Text_CarolDefeat_IT::
    .string "Non ero allenata!$"

Route10_Text_CarolPostBattle_IT::
    .string "I POKéMON qui sono così grossi!\n"
    .string "Ce ne dev'essere uno rosa a fiori!$"

Route10_Text_RockTunnelDetourToLavender_IT::
    .string "TUNNEL ROCCIOSO\n"
    .string "Deviazione per LAVANDONIA$"

Route10_Text_RockTunnel_IT::
    .string "TUNNEL ROCCIOSO$"

Route10_Text_PowerPlant_IT::
    .string "CENTRALE ELETT.$"

