Route10_Text_MarkIntro_FR::
	.string "T'es dingue des POKéMON?\n"
	.string "Tu veux voir ma collec'?$"

Route10_Text_MarkDefeat_FR::
	.string "Nyan!\n"
	.string "Ma belle collec'!$"

Route10_Text_MarkPostBattle_FR::
	.string "A la maison, j'ai plein de POKéMON\n"
	.string "super rares!$"

Route10_Text_ClarkIntro_FR::
	.string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat_FR::
	.string "Ha!\n"
	.string "Je ris pas!\l"
	.string "C'est les nerfs!$"

Route10_Text_ClarkPostBattle_FR::
	.string "Haha-ha-ha!\n"
	.string "Nyahahahaha!\l"
	.string "Hohohoho!$"

Route10_Text_HermanIntro_FR::
	.string "Hé, toi!\n"
	.string "Tu veux voir mes POKéMON?$"

Route10_Text_HermanDefeat_FR::
	.string "Yah!\n"
	.string "Mes POKéMON!$"

Route10_Text_HermanPostBattle_FR::
	.string "Je t'aime pas et j'aime pas\n"
	.string "quand tu gagnes!$"

Route10_Text_HeidiIntro_FR::
	.string "Je reviens de l'ARENE POKéMON!\n"
	.string "Mais je perds tout le temps!$"

Route10_Text_HeidiDefeat_FR::
	.string "Ben, voilà!\n"
	.string "J'ai encore perdu!$"

Route10_Text_HeidiPostBattle_FR::
	.string "J'ai rencontré des POKéMANIACS\n"
	.string "dans le coin.$"

Route10_Text_TrentIntro_FR::
	.string "Ah! L'air de la montagne, c'est\n"
	.string "vivifiant!$"

Route10_Text_TrentDefeat_FR::
	.string "Ben…\n"
	.string "Me voilà tout vivifié!$"

Route10_Text_TrentPostBattle_FR::
	.string "J'en ai marre de la montagne!$"

Route10_Text_CarolIntro_FR::
	.string "Cette randonnée m'a épuisée!$"

Route10_Text_CarolDefeat_FR::
	.string "Trop fatiguée.\n"
	.string "J'laisse tomber!$"

Route10_Text_CarolPostBattle_FR::
	.string "Les POKéMON de la montagne\n"
	.string "sont trop trapus!\p"
	.string "Il en faudrait des roses en forme\n"
	.string "de jolies fleurs!$"

Route10_Text_RockTunnelDetourToLavender_FR::
	.string "GROTTE\n"
	.string "Détour pour LAVANVILLE$"

Route10_Text_RockTunnel_FR::
	.string "GROTTE$"

Route10_Text_PowerPlant_FR::
	.string "CENTRALE$"

