Route10_Text_MarkIntro_ES::
    .string "¿Eres como los POKéMANÍACOS?\n"
    .string "¿Quieres ver mi colección?$"

Route10_Text_MarkDefeat_ES::
    .string "¿Qué?\n"
    .string "¡No estoy enfadado!$"

Route10_Text_MarkPostBattle_ES::
    .string "¡En casa tengo más POKéMON\n"
    .string "superraros!$"

Route10_Text_ClarkIntro_ES::
    .string "¡A-aa-a-a!$"

Route10_Text_ClarkDefeat_ES::
    .string "¡A-aa!\n"
    .string "¡No me estoy riendo!\l"
    .string "¡Es a-a-a-lergia! ¡A-a-a-chús!$"

Route10_Text_ClarkPostBattle_ES::
    .string "¡A-a-a-chús!\n"
    .string "¡A-chús!\l"
    .string "Ufff...$"

Route10_Text_HermanIntro_ES::
    .string "¡Eh, hola!\n"
    .string "¿Quieres ver mis POKéMON?$"

Route10_Text_HermanDefeat_ES::
    .string "¡Oh, no!\n"
    .string "¡Mis POKéMON!$"

Route10_Text_HermanPostBattle_ES::
    .string "¡No me gustas cuando ganas!$"

Route10_Text_HeidiIntro_ES::
    .string "He estado varias veces en un\n"
    .string "GIMNASIO POKéMON.\p"
    .string "¡Y he perdido siempre!$"

Route10_Text_HeidiDefeat_ES::
    .string "¡Volví a perder!$"

Route10_Text_HeidiPostBattle_ES::
    .string "Hay algunos POKéMANÍACOS por ahí.\p"
    .string "Y la verdad, creo que no pintan\n"
    .string "nada en la montaña, ¿no?$"

Route10_Text_TrentIntro_ES::
    .string "¡Ah!\n"
    .string "¡Me encanta el aire de montaña!$"

Route10_Text_TrentDefeat_ES::
    .string "¡Me has espabilado!$"

Route10_Text_TrentPostBattle_ES::
    .string "A mí el aire de la montaña\n"
    .string "me atonta.$"

Route10_Text_CarolIntro_ES::
    .string "¡Me siento débil tras la escalada!$"

Route10_Text_CarolDefeat_ES::
    .string "No estaba lo suficientemente\n"
    .string "preparada...$"

Route10_Text_CarolPostBattle_ES::
    .string "¡Estos POKéMON son tan toscos!\p"
    .string "¡Debería haber alguno rosa con\n"
    .string "bonitas flores!$"

Route10_Text_RockTunnelDetourToLavender_ES::
    .string "TÚNEL ROCA\n"
    .string "Desvío hacia PUEBLO LAVANDA.$"

Route10_Text_RockTunnel_ES::
    .string "TÚNEL ROCA$"

Route10_Text_PowerPlant_ES::
    .string "CENTRAL ENERGÍA$"
