LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere_FR::
	.string "Je viens d'emménager ici.\p"
	.string "Il paraît que MR. FUJI n'est\n"
	.string "pas non plus du coin.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo_FR::
	.string "Ce sacré MR. FUJI n'est pas là.\n"
	.string "Où est-il?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother_FR::
	.string "MR. FUJI a prié pour le repos de\n"
	.string "la mère d'OSSELAIT.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons_FR::
	.string "Voici la maison de MR. FUJI.\p"
	.string "C'est vraiment un chic type!\p"
	.string "Il est à la recherche des POKéMON\n"
	.string "orphelins et abandonnés!$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug_FR::
	.string "C'est si doux! Faire un câlin à un\n"
	.string "POKéMON, c'est chou!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino_FR::
	.string "NIDORINO: Nido!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck_FR::
	.string "PSYKOKWAK: Kwak!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis_FR::
	.string "MR. FUJI: {PLAYER}.\p"
	.string "Ta quête pour compléter ton\n"
	.string "POKéDEX échouera si tu n'aimes pas\l"
	.string "tes POKéMON.\p"
	.string "Je crois que ceci te sera utile.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji_FR::
	.string "{PLAYER} obtient la\n"
	.string "POKéFLUTE!$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute_FR::
	.string "En jouant de la POKéFLUTE, les\n"
	.string "POKéMON endormis se réveilleront.\p"
	.string "Elle marche sur tous les POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis_FR::
	.string "Ton inventaire est plein!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou_FR::
	.string "MR. FUJI: Ma FLUTE t'a été utile?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped_FR::
	.string "Grand concours de dessin du\n"
	.string "magazine des fans de POKéMON!\p"
	.string "Le formulaire d'inscription est…\p"
	.string "Il a disparu! Quelqu'un a déjà dû\n"
	.string "l'utiliser.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf_FR::
	.string "Des magazines POKéMON!\p"
	.string "Des cahiers POKéMON!\p"
	.string "Des dessins POKéMON!$"

