LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere_IT::
    .string "Mi sono trasferito da poco da\n"
    .string "queste parti.\p"
    .string "Ho sentito dire che neanche\n"
    .string "MR. FUJI è originario di qui.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo_IT::
    .string "È strano, MR. FUJI non è qui.\n"
    .string "Dov'è?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother_IT::
    .string "MR. FUJI pregava per la madre di\n"
    .string "CUBONE.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons_IT::
    .string "Questa sarebbe la casa di\n"
    .string "MR. FUJI.\p"
    .string "Che cara persona!\p"
    .string "Si prende cura dei POKéMON orfani\n"
    .string "e abbandonati!$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug_IT::
    .string "È così caldo!\n"
    .string "Abbracciare i POKéMON è bello!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino_IT::
    .string "NIDORINO: Nidor!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck_IT::
    .string "PSYDUCK: Psidù!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis_IT::
    .string "MR. FUJI: {PLAYER}!\p"
    .string "Solo con l'amore per i tuoi\n"
    .string "POKéMON riuscirai a completare\l"
    .string "il tuo POKéDEX.\p"
    .string "Credo che questo ti sarà d'aiuto.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji_IT::
    .string "{PLAYER} riceve\n"
    .string "il POKé FLAUTO!$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute_IT::
    .string "Il suono del POKé FLAUTO desterà\n"
    .string "i POKéMON addormentati.\p"
    .string "Puoi provare ad usarlo su un\n"
    .string "POKéMON addormentato che ti\l"
    .string "blocca la strada!$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis_IT::
    .string "Devi fare spazio per questo!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou_IT::
    .string "MR. FUJI: È stato utile il POKé\n"
    .string "FLAUTO?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped_IT::
    .string "RIVISTA FAN DEI POKéMON\n"
    .string "Concorso Mensile di Disegno\l"
    .string "POKéMON!\p"
    .string "Il modulo di iscrizione è…\p"
    .string "…è scomparso!\n"
    .string "Qualcuno dev'essersi già iscritto.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf_IT::
    .string "Riviste POKéMON!\p"
    .string "Quaderni POKéMON!\p"
    .string "Foto POKéMON!$"

