RockTunnel_1F_Text_LennyIntro_IT::
    .string "Questo cunicolo è molto\n"
    .string "lungo, sai?!$"

RockTunnel_1F_Text_LennyDefeat_IT::
    .string "No!\n"
    .string "Hai vinto!$"

RockTunnel_1F_Text_LennyPostBattle_IT::
    .string "Attento a ONIX.\n"
    .string "Ogni tanto ne appaiono di molto\l"
    .string "forti e pericolosi!$"

RockTunnel_1F_Text_OliverIntro_IT::
    .string "Mhm.\n"
    .string "Forse mi sono perso…$"

RockTunnel_1F_Text_OliverDefeat_IT::
    .string "Stiamo calmi!\n"
    .string "Che sto facendo?\l"
    .string "Da dove si esce?$"

RockTunnel_1F_Text_OliverPostBattle_IT::
    .string "Quel POKéMON addormentato sul\n"
    .string "PERCORSO 12 mi ha fatto deviare.$"

RockTunnel_1F_Text_LucasIntro_IT::
    .string "I forestieri come te mi devono\n"
    .string "rispetto!$"

RockTunnel_1F_Text_LucasDefeat_IT::
    .string "Mi arrendo!$"

RockTunnel_1F_Text_LucasPostBattle_IT::
    .string "Dovresti venire a fare qualche\n"
    .string "escursione con me!$"

RockTunnel_1F_Text_AshtonIntro_IT::
    .string "Lotta POKéMON!\n"
    .string "Pronti… via!$"

RockTunnel_1F_Text_AshtonDefeat_IT::
    .string "Fine del gioco!$"

RockTunnel_1F_Text_AshtonPostBattle_IT::
    .string "Bene, catturerò uno ZUBAT durante\n"
    .string "il viaggio!$"

RockTunnel_1F_Text_LeahIntro_IT::
    .string "Ehi!\n"
    .string "Non fare scherzi stupidi al buio!$"

RockTunnel_1F_Text_LeahDefeat_IT::
    .string "Era troppo buio!$"

RockTunnel_1F_Text_LeahPostBattle_IT::
    .string "Ho visto un MACHOP in questo\n"
    .string "tunnel!$"

RockTunnel_1F_Text_DanaIntro_IT::
    .string "Sono giunta fin qui per i POKéMON!$"

RockTunnel_1F_Text_DanaDefeat_IT::
    .string "Non ho più POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle_IT::
    .string "Parevi un piccolo essere indifeso!$"

RockTunnel_1F_Text_ArianaIntro_IT::
    .string "Hai dei POKéMON?!\n"
    .string "Cominciamo!$"

RockTunnel_1F_Text_ArianaDefeat_IT::
    .string "Giochi duro!$"

RockTunnel_1F_Text_ArianaPostBattle_IT::
    .string "Uffa!\n"
    .string "Sono tutta sudata!$"

RockTunnel_1F_Text_RouteSign_IT::
    .string "TUNNEL ROCCIOSO\n"
    .string "CELESTOPOLI - LAVANDONIA$"

