RockTunnel_1F_Text_LennyIntro_FR::
	.string "Il est long ce tunnel, oh oui!$"

RockTunnel_1F_Text_LennyDefeat_FR::
	.string "Rôooh!\n"
	.string "T'as gagné!$"

RockTunnel_1F_Text_LennyPostBattle_FR::
	.string "Attention aux ONIX!\n"
	.string "Ils apparaissent souvent ici.\p"
	.string "Ils pourraient facilement \n"
	.string "t'écrabouiller, fais attention!$"

RockTunnel_1F_Text_OliverIntro_FR::
	.string "Bon, bon, bon, je suis perdu…$"

RockTunnel_1F_Text_OliverDefeat_FR::
	.string "Hein?\n"
	.string "Par où je sors maintenant?$"

RockTunnel_1F_Text_OliverPostBattle_FR::
	.string "Ce POKéMON endormi sur la route 12\n"
	.string "m'a obligé à faire un détour.$"

RockTunnel_1F_Text_LucasIntro_FR::
	.string "Un profane comme toi me doit le\n"
	.string "respect!$"

RockTunnel_1F_Text_LucasDefeat_FR::
	.string "Perdu!$"

RockTunnel_1F_Text_LucasPostBattle_FR::
	.string "Tu as le niveau des meilleurs\n"
	.string "montagnards!$"

RockTunnel_1F_Text_AshtonIntro_FR::
	.string "Baston POKéMON!\n"
	.string "C'est parti!$"

RockTunnel_1F_Text_AshtonDefeat_FR::
	.string "Game over!$"

RockTunnel_1F_Text_AshtonPostBattle_FR::
	.string "Bon, il me faut un NOSFERAPTI!$"

RockTunnel_1F_Text_LeahIntro_FR::
	.string "Hep!\p"
	.string "Dans le noir, fais gaffe où tu mets\n"
	.string "les pieds!$"

RockTunnel_1F_Text_LeahDefeat_FR::
	.string "J'ai rien compris!$"

RockTunnel_1F_Text_LeahPostBattle_FR::
	.string "J'ai vu un MACHOC dans ce tunnel!$"

RockTunnel_1F_Text_DanaIntro_FR::
	.string "Je viens de loin pour ces POKéMON\n"
	.string "sauvages!$"

RockTunnel_1F_Text_DanaDefeat_FR::
	.string "Oh!\n"
	.string "Plus de POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle_FR::
	.string "Dire que je pensais que tu ne\n"
	.string "savais pas te battre.$"

RockTunnel_1F_Text_ArianaIntro_FR::
	.string "T'as des POKéMON!\n"
	.string "OK, bastooonn!$"

RockTunnel_1F_Text_ArianaDefeat_FR::
	.string "T'es coriace toi!$"

RockTunnel_1F_Text_ArianaPostBattle_FR::
	.string "Hé ben!\n"
	.string "Me voilà en sueur!$"

RockTunnel_1F_Text_RouteSign_FR::
	.string "GROTTE\n"
	.string "AZURIA - LAVANVILLE$"

