RockTunnel_1F_Text_LennyIntro_DE::
	.string "Dieser Tunnel ist verdammt lang!$"

RockTunnel_1F_Text_LennyDefeat_DE::
	.string "Oha!\n"
	.string "Du hast gewonnen!$"

RockTunnel_1F_Text_LennyPostBattle_DE::
	.string "Nimm dich vor ONIX in Acht! Es\n"
	.string "quetscht dich wie eine Zitrone aus!$"

RockTunnel_1F_Text_OliverIntro_DE::
	.string "Könnte es sein, dass ich mich\n"
	.string "verlaufen habe?$"

RockTunnel_1F_Text_OliverDefeat_DE::
	.string "Sachte!\n"
	.string "Wo bin ich?\l"
	.string "Wo geht es nach draußen?$"

RockTunnel_1F_Text_OliverPostBattle_DE::
	.string "Diesen Umweg muss ich nur wegen\n"
	.string "des auf Route 12 schlafenden\l"
	.string "POKéMON machen.$"

RockTunnel_1F_Text_LucasIntro_DE::
	.string "Ein Möchtegern wie du sollte etwas\n"
	.string "mehr Respekt zeigen!$"

RockTunnel_1F_Text_LucasDefeat_DE::
	.string "Ich gebe auf!$"

RockTunnel_1F_Text_LucasPostBattle_DE::
	.string "Du hast Talent!\n"
	.string "Du kannst kein Möchtegern sein!$"

RockTunnel_1F_Text_AshtonIntro_DE::
	.string "Meine POKéMON wollen kämpfen!\n"
	.string "Los!$"

RockTunnel_1F_Text_AshtonDefeat_DE::
	.string "GAME OVER!$"

RockTunnel_1F_Text_AshtonPostBattle_DE::
	.string "Unterwegs werde ich mir ein ZUBAT\n"
	.string "fangen!$"

RockTunnel_1F_Text_LeahIntro_DE::
	.string "Huch!\p"
	.string "Komm mir im Dunkeln bloß nicht zu\n"
	.string "nahe!$"

RockTunnel_1F_Text_LeahDefeat_DE::
	.string "Es war zu dunkel!$"

RockTunnel_1F_Text_LeahPostBattle_DE::
	.string "Ich habe hier im Tunnel ein\n"
	.string "MASCHOCK gesehen!$"

RockTunnel_1F_Text_DanaIntro_DE::
	.string "Ich bin wegen der POKéMON hierher\n"
	.string "gekommen!$"

RockTunnel_1F_Text_DanaDefeat_DE::
	.string "Alle meine POKéMON wurden besiegt!$"

RockTunnel_1F_Text_DanaPostBattle_DE::
	.string "Dabei sahst du so süß und harmlos\n"
	.string "aus!$"

RockTunnel_1F_Text_ArianaIntro_DE::
	.string "Du besitzt POKéMON!\n"
	.string "Lass uns kämpfen!$"

RockTunnel_1F_Text_ArianaDefeat_DE::
	.string "Du bist ein harter Brocken!$"

RockTunnel_1F_Text_ArianaPostBattle_DE::
	.string "Puh!\n"
	.string "Ich bin ganz nass geschwitzt!$"

RockTunnel_1F_Text_RouteSign_DE::
	.string "FELSTUNNEL\n"
	.string "AZURIA CITY - LAVANDIA$"

