RockTunnel_1F_Text_LennyIntro_ES::
    .string "¡Este oscuro túnel recorre\n"
    .string "un largo camino!$"

RockTunnel_1F_Text_LennyDefeat_ES::
    .string "¡Uauu!\n"
    .string "¡Tú ganas!$"

RockTunnel_1F_Text_LennyPostBattle_ES::
    .string "Cuidado con ONIX.\n"
    .string "¡Podría apretarte las tuercas!$"

RockTunnel_1F_Text_OliverIntro_ES::
    .string "Mmm.\n"
    .string "Puede que me haya perdido...$"

RockTunnel_1F_Text_OliverDefeat_ES::
    .string "A ver, con calma. \n"
    .string "¿Qué hago?\l"
    .string "¿Por dónde salgo?$"

RockTunnel_1F_Text_OliverPostBattle_ES::
    .string "Ese POKéMON dormido de la RUTA 12\n"
    .string "me obligó a desviarme.$"

RockTunnel_1F_Text_LucasIntro_ES::
    .string "¡La gente de fuera como tú\n"
    .string "debería respetarme!$"

RockTunnel_1F_Text_LucasDefeat_ES::
    .string "¡Me rindo!$"

RockTunnel_1F_Text_LucasPostBattle_ES::
    .string "¡Tienes madera para escalar!$"

RockTunnel_1F_Text_AshtonIntro_ES::
    .string "¡Lucha POKéMON!\n"
    .string "¿Empezamos? ¡Pues venga!$"

RockTunnel_1F_Text_AshtonDefeat_ES::
    .string "¡Se acabó!$"

RockTunnel_1F_Text_AshtonPostBattle_ES::
    .string "¡Conseguiré un ZUBAT por el\n"
    .string "camino!$"

RockTunnel_1F_Text_LeahIntro_ES::
    .string "¡Oye!\p"
    .string "¡No hagas tonterías en la\n"
    .string "oscuridad!$"

RockTunnel_1F_Text_LeahDefeat_ES::
    .string "¡Estaba demasiado oscuro!$"

RockTunnel_1F_Text_LeahPostBattle_ES::
    .string "¡Vi a un MACHOP en este túnel!$"

RockTunnel_1F_Text_DanaIntro_ES::
    .string "¡Vine hasta aquí por los POKéMON!$"

RockTunnel_1F_Text_DanaDefeat_ES::
    .string "¡Me he quedado sin POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle_ES::
    .string "¡No parecía que tuvieras ni la\n"
    .string "más mínima agresividad!$"

RockTunnel_1F_Text_ArianaIntro_ES::
    .string "¡Tienes POKéMON!\n"
    .string "¡Empecemos!$"

RockTunnel_1F_Text_ArianaDefeat_ES::
    .string "¡No te andas con tonterías!$"

RockTunnel_1F_Text_ArianaPostBattle_ES::
    .string "¡Ufff!\n"
    .string "¡Estoy sudando!$"

RockTunnel_1F_Text_RouteSign_ES::
    .string "TÚNEL ROCA:\n"
    .string "CIUDAD CELESTE - PUEBLO LAVANDA$"
