CeladonCity_Restaurant_Text_TakingBreakRightNow_FR::
	.string "Salut!\p"
	.string "On fait une p'tite pause là.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore_FR::
	.string "Mes POKéMON sont faibles alors je\n"
	.string "vais souvent acheter des\l"
	.string "accélérateurs.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner_FR::
	.string "Pssst! Il y a un truc sous le\n"
	.string "CASINO.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots_FR::
	.string "Miam…\p"
	.string "Le type à cette table a tout\n"
	.string "perdu…$"

CeladonCity_Restaurant_Text_TakeThisImBusted_FR::
	.string "Vas-y! Rigole!\n"
	.string "J'ai plus une thune!\p"
	.string "C'est marrant, hein? Pfff…\n"
	.string "Je te hais!\p"
	.string "Prends ça tiens!\n"
	.string "Et surtout, perds tout ton blé!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan_FR::
	.string "{PLAYER} reçoit\n"
	.string "BOITE JETONS!$"

CeladonCity_Restaurant_Text_MakeRoomForThis_FR::
	.string "T'as plus de place!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack_FR::
	.string "Faut qu'j'me refasse…$"

