CeladonCity_Restaurant_Text_TakingBreakRightNow_IT::
    .string "Ciao!\p"
    .string "Stiamo facendo una pausa.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore_IT::
    .string "I miei POKéMON sono deboli, vado\n"
    .string "quindi spesso in FARMACIA.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner_IT::
    .string "Psss! C'è un interrato sotto il\n"
    .string "CASINÒ.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots_IT::
    .string "Ohi! Ohi!…\p"
    .string "Quell'uomo ha perso tutto alle\n"
    .string "slot machine.$"

CeladonCity_Restaurant_Text_TakeThisImBusted_IT::
    .string "Forza! Ridi pure!\n"
    .string "Sono rovinato!\p"
    .string "Niente più slot machine per me,\n"
    .string "sto alla larga!\p"
    .string "Prendi qua!\n"
    .string "Non ne ho più bisogno!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan_IT::
    .string "{PLAYER} riceve\n"
    .string "il SALVADANAIO!$"

CeladonCity_Restaurant_Text_MakeRoomForThis_IT::
    .string "Fai spazio per questo!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack_IT::
    .string "Pensavo di poter recuperare tutto!$"

