TwoIsland_House_Text_TeachMonMoveForMushroom_FR::
	.string "Je suis le DINGUE DES CAPACITES.\p"
	.string "Je connais chaque capacité que\n"
	.string "les POKéMON peuvent apprendre.\p"
	.string "J'adore aussi les champignons.\p"
	.string "Ramène-moi deux PETITS CHAMPIS\n"
	.string "ou un gros CHAMPI.\p"
	.string "Si tu fais ça, j'apprendrai une\n"
	.string "capacité à un POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove_FR::
	.string "Sniff, sniff…\n"
	.string "Hum, ça sent les CHAMPIS!\p"
	.string "Tu veux que j'enseigne une\n"
	.string "capacité à un de tes POKéMON?$"

TwoIsland_House_Text_TutorWhichMon_FR::
	.string "Quel POKéMON choisis-tu?$"

TwoIsland_House_Text_TeachWhichMove_FR::
	.string "Quelle attaque dois-je enseigner?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon_FR::
	.string "Désolé…\p"
	.string "Apparemment, il n'y a aucune\n"
	.string "attaque que je puisse apprendre à\l"
	.string "ce POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo_FR::
	.string "Alors j'aurais besoin d'un ou deux\n"
	.string "CHAMPIS. Qu'est-ce que tu as?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms_FR::
	.string "{PLAYER} donne deux PETITS CHAMPIS\n"
	.string "en échange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom_FR::
	.string "{PLAYER} donne un GROS CHAMPI en\n"
	.string "échange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove_FR::
	.string "Si tu veux que j'enseigne une\n"
	.string "attaque à ton POKéMON, reviens\l"
	.string "avec un champignon ou deux.$"

TwoIsland_House_Text_CantTeachAnEgg_FR::
	.string "Quoi? Mais je ne peux pas\n"
	.string "apprendre une attaque à un OEUF.$"

