SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire_ES::
    .string "¡{PLAYER} encontró un ZAFIRO!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou_ES::
    .string "Bien... Estupendo...\n"
    .string "Justo lo que pensaba.\p"
    .string "He hecho bien en seguirte.$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword_ES::
    .string "Sabía que había un ZAFIRO aquí,\n"
    .string "¡así que para mí!\p"
    .string "¡Se lo venderé al TEAM ROCKET\n"
    .string "por una buena cantidad!\p"
    .string "Eh... no me mi-mires así.\p"
    .string "Si lo quieres, ¿por qué no vas a\n"
    .string "por él cuando lo venda?\p"
    .string "Te diré una de las contraseñas\n"
    .string "del ALMACÉN ROCKET y todo...\p"
    .string "La contraseña que yo conozco es\n"
    .string "“HO-OH es ese HO-OH”.\p"
    .string "Hala, yo ya estoy.\n"
    .string "¡No te mosquees conmigo!$"
