SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire_DE::
	.string "{PLAYER} hat den SAPHIR gefunden!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou_DE::
	.string "Fufu… fufufufu…\n"
	.string "Ich habe richtig geraten.\p"
	.string "Ich tat gut daran, dir zu folgen!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword_DE::
	.string "Ich wusste, dass es hier einen\n"
	.string "SAPHIR gibt, also gehört er mir!\p"
	.string "Ich verkaufe ihn für viel Geld an\n"
	.string "TEAM ROCKET.\p"
	.string "… s-starr mich nicht so an!\p"
	.string "Wenn du ihn wieder haben möchtest,\n"
	.string "warum versuchst du es nicht,\l"
	.string "nachdem ich ihn verkauft habe?\l"
	.string "Ich verrate dir auch eines der\l"
	.string "Passwörter für das LAGER\l"
	.string "von TEAM ROCKET.\l"
	.string "Das Passwort, das ich kenne, lautet\l"
	.string "“MAKUHITA Atihu kam”.\p"
	.string "Vorbei.\n"
	.string "Nichts für ungut!$"

