SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire_IT::
    .string "{PLAYER} ha trovato ZAFFIRO!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou_IT::
    .string "Lo sapevo!\p"
    .string "Sapevo che facevo bene\n"
    .string "a seguirti!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword_IT::
    .string "Sapevo che avrei trovato uno\n"
    .string "ZAFFIRO qui, quindi è mio!\p"
    .string "Lo venderò a TEAM ROCKET\n"
    .string "ad un prezzo spaventoso!\p"
    .string "Ehi, smetti di fissarmi così!\p"
    .string "Se lo rivuoi, puoi riprendertelo\n"
    .string "dopo che l'ho venduto.\p"
    .string "Per aiutarti ti dico anche una\n"
    .string "delle parole d'ordine per il\l"
    .string "MAGAZZINO.\p"
    .string "La parola d'ordine che conosco è\n"
    .string "“Le SCARPATE di PARASECT”.\p"
    .string "Ci vediamo.\n"
    .string "E non avercela con me!$"

