SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire_FR::
	.string "{PLAYER} a trouvé un SAPHIR!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou_FR::
	.string "Fufu… Fufufufu…\n"
	.string "J'avais vu juste.\p"
	.string "J'ai bien fait de te suivre en\n"
	.string "cachette.$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword_FR::
	.string "Je savais qu'il y avait un SAPHIR\n"
	.string "ici, et il est pour moi!\p"
	.string "Je vais le vendre à la TEAM\n"
	.string "ROCKET pour gagner plein d'argent.\p"
	.string "Ne… ne me regarde pas\n"
	.string "comme ça!\p"
	.string "Si tu le veux tellement, tu n'auras\n"
	.string "qu'à le récupérer après.\p"
	.string "Je vais même te donner un des\n"
	.string "mots de passe de l'ENTREPOT.\p"
	.string "C'est: “TARSAL LA STAR”.\p"
	.string "Voilà, c'est fait. Et je t'ai dit\n"
	.string "de ne pas me regarder comme ça!$"

