FiveIsland_MemorialPillar_Text_MiloIntro_FR::
	.string "Je suis l'aîné des FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est le bec!$"

FiveIsland_MemorialPillar_Text_MiloDefeat_FR::
	.string "Aïe, ça pique!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle_FR::
	.string "A partir d'ici, tu peux voler\n"
	.string "jusqu'à l'ILE 4.$"

FiveIsland_MemorialPillar_Text_ChazIntro_FR::
	.string "Je suis le cadet des FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est les ailes!$"

FiveIsland_MemorialPillar_Text_ChazDefeat_FR::
	.string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle_FR::
	.string "Il y avait un type super maussade\n"
	.string "par là-bas.$"

FiveIsland_MemorialPillar_Text_HaroldIntro_FR::
	.string "Je suis le plus jeune des\n"
	.string "FRERES PIAF.\p"
	.string "Ce que je préfère chez les\n"
	.string "oiseaux, c'est le duvet!$"

FiveIsland_MemorialPillar_Text_HaroldDefeat_FR::
	.string "J'adore me blottir dans le duvet.\n"
	.string "Ça me donne envie de dormir.$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle_FR::
	.string "Je suis content quand je vois les\n"
	.string "POKéMON oiseau jouer ensemble.$"

FiveIsland_MemorialPillar_Text_ScrubScrub_FR::
	.string "Gratt, gratt…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy_FR::
	.string "Bonjour…\n"
	.string "Ils ont l'air en forme vos POKéMON.$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix_FR::
	.string "C'est ici qu'est enterré mon ONIX…\n"
	.string "Je l'appelais TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering_FR::
	.string "On peut lire sur une pierre:\n"
	.string "“Ici repose TECTONIX”.\p"
	.string "Il y a une LIMONADE placée ici\n"
	.string "en signe d'offrande.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering_FR::
	.string "Voulez-vous placer une autre\n"
	.string "LIMONADE en offrande?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade_FR::
	.string "{PLAYER} place une LIMONADE\n"
	.string "en face de la stèle.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis_FR::
	.string "M-Merci…\p"
	.string "C'était la boisson favorite de\n"
	.string "TECTONIX…\p"
	.string "Je ne vous connais pas, mais\n"
	.string "je suis très touché par\p"
	.string "votre bonté.\p"
	.string "Tenez, prenez ceci en\n"
	.string "remerciement.$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo_FR::
	.string "Soyez toujours aussi bon envers\n"
	.string "vos POKéMON.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt_FR::
	.string "Si vous n'avez plus de place,\n"
	.string "revenez me voir plus tard.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks_FR::
	.string "Oh, vous revoilà.\p"
	.string "J'ai toujours cet objet que je\n"
	.string "voulais vous donner l'autre fois.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix_FR::
	.string "Gratt, gratt…\p"
	.string "… … …\n"
	.string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix_FR::
	.string "Les rochers sont empilés devant\n"
	.string "une plaque.\p"
	.string "On peut y lire:\n"
	.string "“Ici repose TECTONIX”.$"

