FiveIsland_MemorialPillar_Text_MiloIntro_IT::
    .string "Sono il più anziano dei FRATELLI\n"
    .string "VOLANTI.\p"
    .string "La parte più importante negli\n"
    .string "uccelli è il becco.$"

FiveIsland_MemorialPillar_Text_MiloDefeat_IT::
    .string "Ehi, m'hai dato una bella beccata!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle_IT::
    .string "Da qui puoi volare fino\n"
    .string "a QUARTISOLA.$"

FiveIsland_MemorialPillar_Text_ChazIntro_IT::
    .string "Dei FRATELLI VOLANTI, sono quello\n"
    .string "di mezzo.\p"
    .string "La parte più importante negli\n"
    .string "uccelli sono le ali.$"

FiveIsland_MemorialPillar_Text_ChazDefeat_IT::
    .string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle_IT::
    .string "Da quella parte ho visto\n"
    .string "un ragazzo tristissimo!$"

FiveIsland_MemorialPillar_Text_HaroldIntro_IT::
    .string "Sono il più giovane dei FRATELLI\n"
    .string "VOLANTI.\p"
    .string "La parte più importante negli\n"
    .string "uccelli sono le piume.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat_IT::
    .string "Le piume sono così soffici\n"
    .string "che mi fanno venire sonno…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle_IT::
    .string "Vedere POKéMON uccello che\n"
    .string "giocano mi fa impazzire di gioia!$"

FiveIsland_MemorialPillar_Text_ScrubScrub_IT::
    .string "Oh, che tristezza!$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy_IT::
    .string "Ciao! La tua squadra sembra in\n"
    .string "piena salute!$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix_IT::
    .string "È qui che ho seppellito il mio\n"
    .string "ONIX. Si chiamava TECTONIX.$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering_IT::
    .string "Sulla roccia c'è scritto:\n"
    .string "“Qui giace TECTONIX”.\p"
    .string "C'è anche un LEMONSUCCO\n"
    .string "sulla tomba, come offerta.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering_IT::
    .string "Vuoi lasciare anche tu un\n"
    .string "LEMONSUCCO come offerta?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade_IT::
    .string "{PLAYER} mette un LEMONSUCCO\n"
    .string "davanti alla tomba.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis_IT::
    .string "Grazie! Era la bevanda preferita\n"
    .string "del mio TECTONIX!\p"
    .string "Non ti conosco neppure, ma il\n"
    .string "tuo gesto mi ha un po' risollevato.\p"
    .string "Per ringraziarti, vorrei darti\n"
    .string "questo.$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo_IT::
    .string "Cerca di trattare sempre bene i\n"
    .string "tuoi POKéMON, come ho fatto io.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt_IT::
    .string "Non hai spazio. Per il momento,\n"
    .string "te lo tengo io. Torna a trovarmi!$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks_IT::
    .string "Ah, mi ricordo di te!\p"
    .string "Ho ancora quella cosa che\n"
    .string "ti avevo promesso!$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix_IT::
    .string "Oh, che tristezza!\p"
    .string "… … …\n"
    .string "Il mio TECTONIX”$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix_IT::
    .string "Ci sono pietre impilate a formare\n"
    .string "un tumulo.\p"
    .string "Sulla roccia sono incise le parole:\n"
    .string "“Qui giace TECTONIX”.$"

