Text_UltimateMoveThatMon_ES::
    .string "He perfeccionado el último\n"
    .string "movimiento de este tipo...\p"
    .string "Bueno, y ahora, ¿a quién se lo\n"
    .string "enseño?\p"
    .string "Mmmm...\p"
    .string "Ese {STR_VAR_1} tuyo...$"

Text_JustMistaken_ES::
    .string "No, no...\n"
    .string "Me he equivocado...$"

Text_AllowMeToTeachMonUltimateMove_ES::
    .string "¡Anda, éste es!\n"
    .string "¡Éste es el POKéMON!\p"
    .string "¡Este {STR_VAR_1} se merece\n"
    .string "aprender mi último movimiento!\p"
    .string "¿Te parece bien?\p"
    .string "¿Quieres que le enseñe\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}?$"

Text_YouRejectIt_ES::
    .string "¿Cómo, que no?\n"
    .string "¡No me lo puedo creer!$"

Text_LetMeConferUltimateMove_ES::
    .string "¿Quieres?\p"
    .string "Pues voy a enseñarle\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}.\p"
    .string "¡Allá voy!$"

Text_TaughtMove_ES::
    .string "Qué emoción...\p"
    .string "No pensé que llegara a enseñar\n"
    .string "al final el movimiento...$"

Text_MakeBestUseOfMove_ES::
    .string "¡Espero que lo uses bien y\n"
    .string "le saques el mayor partido!$"

Text_PassedOnEverythingIKnow_ES::
    .string "Qué emoción...\p"
    .string "Qué tranquilidad.\n"
    .string "Ya he transmitido todo lo que sé.\p"
    .string "Qué satisfacción cumplir con el\n"
    .string "deber...$"

Text_FeelRejuvenated_ES::
    .string "Ahora que sabes lo que yo, siento\n"
    .string "una tranquilidad enorme.\p"
    .string "¡Me siento hasta más joven!\n"
    .string "¡Es como si me hubiera quitado\l"
    .string "años de encima!$"
