Text_UltimateMoveThatMon_IT::
    .string "Ho ultimato una mossa unica\n"
    .string "nel suo genere…\p"
    .string "Ma la insegnerò solo ad un POKéMON\n"
    .string "che ne sia degno!\p"
    .string "…Hmmm? Hmmm!\p"
    .string "Tu…\n"
    .string "…hai {STR_VAR_1}?!$"

Text_JustMistaken_IT::
    .string "…No…\n"
    .string "…non è quello che cerco.$"

Text_AllowMeToTeachMonUltimateMove_IT::
    .string "Sì! È lui!\n"
    .string "È questo il POKéMON che cerco!\p"
    .string "Questo {STR_VAR_1} è degno di\n"
    .string "apprendere la mia specialissima\l"
    .string "mossa!\p"
    .string "Posso?\p"
    .string "Posso insegnare {STR_VAR_2}\n"
    .string "al tuo {STR_VAR_1}?$"

Text_YouRejectIt_IT::
    .string "Come?! Non vuoi?!\n"
    .string "Guarda che mi offendo!$"

Text_LetMeConferUltimateMove_IT::
    .string "Posso?\p"
    .string "Bene, allora insegnerò\n"
    .string "{STR_VAR_2} al tuo {STR_VAR_1}!$"

Text_TaughtMove_IT::
    .string "Gasp, gasp, gasp…\p"
    .string "Pensavo che non avrei mai avuto\n"
    .string "l'occasione di insegnare questa\l"
    .string "mossa ad un POKéMON!$"

Text_MakeBestUseOfMove_IT::
    .string "Mi raccomando, fai buon uso\n"
    .string "della mia mossa!$"

Text_PassedOnEverythingIKnow_IT::
    .string "Gasp, gasp, gasp…\p"
    .string "Ora, finalmente, ho il cuore in\n"
    .string "pace.\p"
    .string "Potrò trascorrere il resto dei miei\n"
    .string "giorni sapendo di aver raggiunto il\l"
    .string "mio scopo nella vita.$"

Text_FeelRejuvenated_IT::
    .string "Dopo averti insegnato ciò che\n"
    .string "sapevo provo un senso di\l"
    .string "sollievo.\p"
    .string "È come se avessi trent'anni\n"
    .string "in meno sulle spalle!$"

