Route1_Text_WorkAtPokeMartTakeSample_FR::
	.string "Salut! Je travaille à la\n"
	.string "BOUTIQUE POKéMON.\p"
	.string "Nous avons plein d'articles! Viens\n"
	.string "nous voir à JADIELLE.\p"
	.string "Prends donc ceci comme\n"
	.string "échantillon!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls_FR::
	.string "Nous avons aussi des POKé BALLS\n"
	.string "pour capturer les POKéMON!$"

Route1_Text_PutPotionAway_FR::
	.string "{PLAYER} range la POTION dans la\n"
	.string "POCHE OBJETS du SAC.$"

Route1_Text_CanJumpFromLedges_FR::
	.string "Tu vois tous ces petits talus?\p"
	.string "Tu peux sauter par-dessus!\n"
	.string "C'est dingue, non?\p"
	.string "Tu peux revenir plus vite à\n"
	.string "BOURG PALETTE de cette façon!$"

Route1_Text_RouteSign_FR::
	.string "ROUTE 1\n"
	.string "BOURG PALETTE - JADIELLE$"

