PokemonTower_5F_Text_RestHereInPurifiedSpace_IT::
    .string "Vieni! Ho protetto questo luogo\n"
    .string "con la magia bianca!\p"
    .string "Riposati un po'!$"

PokemonTower_5F_Text_TammyIntro_IT::
    .string "Daaammi… la tuuua…\n"
    .string "aaanima…$"

PokemonTower_5F_Text_TammyDefeat_IT::
    .string "Gasp!$"

PokemonTower_5F_Text_TammyPostBattle_IT::
    .string "Ero posseduta!$"

PokemonTower_5F_Text_RuthIntro_IT::
    .string "Vieeeni… con…\n"
    .string "noooi…$"

PokemonTower_5F_Text_RuthDefeat_IT::
    .string "Che incubo!$"

PokemonTower_5F_Text_RuthPostBattle_IT::
    .string "Ero posseduta!$"

PokemonTower_5F_Text_KarinaIntro_IT::
    .string "Zombie!$"

PokemonTower_5F_Text_KarinaDefeat_IT::
    .string "Ah?$"

PokemonTower_5F_Text_KarinaPostBattle_IT::
    .string "Ho ripreso i sensi!$"

PokemonTower_5F_Text_JanaeIntro_IT::
    .string "Oooo…\n"
    .string "Uuuu…$"

PokemonTower_5F_Text_JanaeDefeat_IT::
    .string "Uhuuu!$"

PokemonTower_5F_Text_JanaePostBattle_IT::
    .string "Nonostante il mio allenamento gli\n"
    .string "spiriti maligni mi hanno preso!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed_IT::
    .string "Zona disinfestata e protetta!\p"
    .string "I POKéMON di {PLAYER} sono\n"
    .string "ricaricati!$"

