PokemonTower_5F_Text_RestHereInPurifiedSpace_FR::
	.string "Approche, enfant!\p"
	.string "J'ai scellé cet endroit grâce à\n"
	.string "ma sainte magie blanche!\p"
	.string "Tu peux te reposer ici!$"

PokemonTower_5F_Text_TammyIntro_FR::
	.string "Donne… moi…\n"
	.string "ton… âme…$"

PokemonTower_5F_Text_TammyDefeat_FR::
	.string "Glargh!$"

PokemonTower_5F_Text_TammyPostBattle_FR::
	.string "J'étais possédée!$"

PokemonTower_5F_Text_RuthIntro_FR::
	.string "Viens… avec…\n"
	.string "nous…$"

PokemonTower_5F_Text_RuthDefeat_FR::
	.string "Hein!\n"
	.string "J'ai fait un cauchemar!$"

PokemonTower_5F_Text_RuthPostBattle_FR::
	.string "J'étais possédée!$"

PokemonTower_5F_Text_KarinaIntro_FR::
	.string "Zombis!$"

PokemonTower_5F_Text_KarinaDefeat_FR::
	.string "Hein?$"

PokemonTower_5F_Text_KarinaPostBattle_FR::
	.string "Je suis revenue à la raison!$"

PokemonTower_5F_Text_JanaeIntro_FR::
	.string "Poyé Polomi!\n"
	.string "Le mal est parmi nous…$"

PokemonTower_5F_Text_JanaeDefeat_FR::
	.string "Quoi?\n"
	.string "Jeune taoïste, tu oses m'ôter le\l"
	.string "yang de la bouche!$"

PokemonTower_5F_Text_JanaePostBattle_FR::
	.string "Mon Tao à moi, c'est le plus beau\n"
	.string "des Taos!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed_FR::
	.string "Vous pénétrez dans une zone\n"
	.string "sanctuaire!\p"
	.string "Les POKéMON de {PLAYER} sont\n"
	.string "soignés!$"

