PokemonTower_5F_Text_RestHereInPurifiedSpace_DE::
	.string "Komm her! Ich habe diese Stelle\n"
	.string "mit weißer Magie versiegelt!\l"
	.string "Du kannst dich hier ausruhen!$"

PokemonTower_5F_Text_TammyIntro_DE::
	.string "Gib... mir...\n"
	.string "deine... Seele...$"

PokemonTower_5F_Text_TammyDefeat_DE::
	.string "Puh!$"

PokemonTower_5F_Text_TammyPostBattle_DE::
	.string "Etwas muss von mir Besitz ergriffen\n"
	.string "haben!$"

PokemonTower_5F_Text_RuthIntro_DE::
	.string "Es... gibt... kein...\n"
	.string "Entkommen...$"

PokemonTower_5F_Text_RuthDefeat_DE::
	.string "Welch ein Alptraum!$"

PokemonTower_5F_Text_RuthPostBattle_DE::
	.string "Ich war verhext!$"

PokemonTower_5F_Text_KarinaIntro_DE::
	.string "Zombies!$"

PokemonTower_5F_Text_KarinaDefeat_DE::
	.string "Was?$"

PokemonTower_5F_Text_KarinaPostBattle_DE::
	.string "So langsam komme ich wieder zu\n"
	.string "Sinnen!$"

PokemonTower_5F_Text_JanaeIntro_DE::
	.string "Buuh...\n"
	.string "Buhuhu...$"

PokemonTower_5F_Text_JanaeDefeat_DE::
	.string "Das war knapp!$"

PokemonTower_5F_Text_JanaePostBattle_DE::
	.string "Trotz meiner Erfahrung bin ich dem\n"
	.string "Bösen verfallen!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed_DE::
	.string "Du hast einen geschützten Bereich\n"
	.string "betreten!\p"
	.string "Die POKéMON von {PLAYER}\n"
	.string "wurden geheilt!$"

