PokemonTower_5F_Text_RestHereInPurifiedSpace_ES::
    .string "¡Ven, ven! ¡Sellé este lugar\n"
    .string "con magia blanca!\l"
    .string "¡Aquí puedes descansar!$"

PokemonTower_5F_Text_TammyIntro_ES::
    .string "Dame...\n"
    .string "tu... esencia...$"

PokemonTower_5F_Text_TammyDefeat_ES::
    .string "¿Uh?$"

PokemonTower_5F_Text_TammyPostBattle_ES::
    .string "¡Estaba fuera de mí!$"

PokemonTower_5F_Text_RuthIntro_ES::
    .string "Ven... con...\n"
    .string "nosotros...$"

PokemonTower_5F_Text_RuthDefeat_ES::
    .string "¡Vaya pesadilla!$"

PokemonTower_5F_Text_RuthPostBattle_ES::
    .string "¡Estaba fuera de mí!$"

PokemonTower_5F_Text_KarinaIntro_ES::
    .string "¡Zombis!$"

PokemonTower_5F_Text_KarinaDefeat_ES::
    .string "¿Ja?$"

PokemonTower_5F_Text_KarinaPostBattle_ES::
    .string "¡He recuperado la razón!$"

PokemonTower_5F_Text_JanaeIntro_ES::
    .string "¡Oooo!...\n"
    .string "¡Uuuu!...$"

PokemonTower_5F_Text_JanaeDefeat_ES::
    .string "¡Uuuu!$"

PokemonTower_5F_Text_JanaePostBattle_ES::
    .string "¡A pesar de mi entrenamiento\n"
    .string "me atraparon los espíritus!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed_ES::
    .string "¡Has entrado en una zona de pureza\n"
    .string "y seguridad!\p"
    .string "¡Los POKéMON de {PLAYER} están\n"
    .string "curados!$"
