Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad_FR::
	.string "Interdit aux piétons!\n"
	.string "PISTE CYCLABLE!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse_FR::
	.string "La PISTE CYCLABLE est une superbe\n"
	.string "route menant à la mer.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp_FR::
	.string "Pardon!\n"
	.string "Hé, pardon!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort_FR::
	.string "Comment t'as fait pour arriver\n"
	.string "jusqu'ici?$"

