Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad_ES::
    .string "¡Los peatones no pueden andar\n"
    .string "por el CAMINO de BICIS!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse_ES::
    .string "El CAMINO de BICIS va cuesta\n"
    .string "abajo junto al mar. ¡Es estupendo!$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp_ES::
    .string "¡Perdona!\n"
    .string "¡Espera!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort_ES::
    .string "¿Cómo has llegado hasta aquí?\n"
    .string "¡Bien hecho!$"
