Route12_FishingHouse_Text_DoYouLikeToFish_DE::
	.string "Mein Bruder ist der PROFI-ANGLER!\p"
	.string "Ich liebe den Angelsport!\p"
	.string "Möchtest du auch angeln?$"

Route12_FishingHouse_Text_TakeThisAndFish_DE::
	.string "Klasse!\n"
	.string "Du bist mir sympathisch!\p"
	.string "Nimm das hier und gehe angeln!$"

Route12_FishingHouse_Text_ReceivedSuperRod_DE::
	.string "{PLAYER} erhält\n"
	.string "eine SUPERANGEL!$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe_DE::
	.string "Angeln ist nicht nur ein Sport, es\n"
	.string "ist eine Kunst!\p"
	.string "Nun ziehe los, um den großen Fang\n"
	.string "zu landen!\p"
	.string "Ich habe eine Bitte:\p"
	.string "Fängst du mit dieser ANGEL\n"
	.string "ein großes KARPADOR, möchte\l"
	.string "ich es sehen.\p"
	.string "Meine Liebe zum Angeln steht\n"
	.string "meiner Liebe für große\l"
	.string "KARPADOR in nichts nach!$"

Route12_FishingHouse_Text_OhThatsDisappointing_DE::
	.string "Oh!\n"
	.string "Das ist so enttäuschend...$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp_DE::
	.string "Hallo, {PLAYER}!\p"
	.string "Benutze die SUPERANGEL in allen\n"
	.string "Gewässern.\p"
	.string "Du kannst die verschiedensten\n"
	.string "POKéMON damit fangen!\p"
	.string "Und vergiss nicht, ein großes\n"
	.string "KARPADOR für mich zu fangen.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee_DE::
	.string "Oh? {PLAYER}?\n"
	.string "Wenn das nicht KARPADOR ist!\p"
	.string "Darf ich es sehen, bitte!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis_DE::
	.string "……… Wow!\n"
	.string "{STR_VAR_2} cm!\p"
	.string "Du hast eine seltene, elitäre\n"
	.string "Affinität zu den poetischen\l"
	.string "Gesichtspunkten des Angelns!\l"
	.string "Du musst das haben!\l"
	.string "Ich bestehe darauf!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords_DE::
	.string "Ich freue mich schon auf noch\n"
	.string "bessere Rekorde von dir!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast_DE::
	.string "Häh!\n"
	.string "{STR_VAR_2} cm?\p"
	.string "Das ist genauso groß, wie zuvor!$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp_DE::
	.string "Hm…\n"
	.string "Dieses ist {STR_VAR_2} cm groß!\p"
	.string "Das ist weniger als die {STR_VAR_3} cm,\n"
	.string "die du mir zuvor gezeigt hast.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp_DE::
	.string "Uh… das sieht gar nicht\n"
	.string "wie ein KARPADOR aus!$"

Route12_FishingHouse_Text_NoRoomForGift_DE::
	.string "Oh nein!\p"
	.string "Ich habe ein Geschenk für dich!\n"
	.string "Aber du kannst nichts mehr tragen!$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches_DE::
	.string "Das größte KARPADOR, das\n"
	.string "ich je sah, hatte…\p"
	.string "{STR_VAR_3} cm!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort_DE::
	.string "Dies ist eine leere Tafel!\p"
	.string "Darauf können irgendwelche\n"
	.string "Rekorde geschrieben werden.$"

