Route12_FishingHouse_Text_DoYouLikeToFish_FR::
	.string "Je suis le frère du MAITRE\n"
	.string "PECHEUR!\p"
	.string "Moi, dans la vie, j'suis pêcheur!\n"
	.string "J'adore ça!\p"
	.string "T'aimes la pêche, toi?$"

Route12_FishingHouse_Text_TakeThisAndFish_FR::
	.string "Cool! T'as l'air de quelqu'un\n"
	.string "de bien!\p"
	.string "Prends ça! Et bonne pêche!$"

Route12_FishingHouse_Text_ReceivedSuperRod_FR::
	.string "{PLAYER} obtient la\n"
	.string "MEGA CANNE!$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe_FR::
	.string "La pêche, c'est comme la vie!\p"
	.string "Quand ça mord, ça va! \n"
	.string "Quand ça mord pas, ça va pas!\p"
	.string "J'ai un service à te demander.\n"
	.string "Si tu attrapes un gros MAGICARPE\p"
	.string "avec cette canne, j'aimerais\n"
	.string "beaucoup que tu me le montres.\p"
	.string "J'adore voir les gros MAGICARPE,\n"
	.string "presque autant que la pêche.$"

Route12_FishingHouse_Text_OhThatsDisappointing_FR::
	.string "Oh…\n"
	.string "Je suis très déçu…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp_FR::
	.string "Salut, {PLAYER}!\p"
	.string "Avec cette MEGA CANNE, tu vas\n"
	.string "vider les océans de tous leurs\p"
	.string "POKéMON. Selon les endroits, tu\n"
	.string "en trouveras des différents.\p"
	.string "Et n'oublie pas de me montrer\n"
	.string "un gros MAGICARPE!$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee_FR::
	.string "{PLAYER}?\p"
	.string "Tu m'as ramené un MAGICARPE?\n"
	.string "Vite vite, je veux le voir!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis_FR::
	.string "… Waouh! {STR_VAR_2}cm!\n"
	.string "Il est gigantesque!\p"
	.string "La pêche n'a plus de secret\n"
	.string "pour toi.\p"
	.string "Prends ça, j'insiste!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords_FR::
	.string "J'ai hâte de voir tes prochaines\n"
	.string "prises!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast_FR::
	.string "Hein?\n"
	.string "{STR_VAR_2} cm?\p"
	.string "C'est la même taille que la\n"
	.string "dernière fois.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp_FR::
	.string "Hmmm…\n"
	.string "Celui-là fait {STR_VAR_2} cm de long.\p"
	.string "Rien à voir avec celui de {STR_VAR_3} cm\n"
	.string "que tu avais ramené.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp_FR::
	.string "Hmmm…\p"
	.string "Ça ressemble pas à\n"
	.string "un MAGICARPE.$"

Route12_FishingHouse_Text_NoRoomForGift_FR::
	.string "Ah ben non!\p"
	.string "J'avais un cadeau pour toi, mais\n"
	.string "t'as plus de place!$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches_FR::
	.string "Le plus gros MAGICARPE que\n"
	.string "j'ai vu!\p"
	.string "{STR_VAR_3} cm!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort_FR::
	.string "C'est un classement vierge.\p"
	.string "Il y a de la place pour inscrire\n"
	.string "des records.$"

