Route12_FishingHouse_Text_DoYouLikeToFish_IT::
    .string "Sono il fratello minore del\n"
    .string "GURU PESCATORE!\p"
    .string "Adoooro pescare!\p"
    .string "E a te piace la pesca?$"

Route12_FishingHouse_Text_TakeThisAndFish_IT::
    .string "Bene!\n"
    .string "Mi piace il tuo stile!\p"
    .string "Prendi questo e pesca, coraggio!$"

Route12_FishingHouse_Text_ReceivedSuperRod_IT::
    .string "{PLAYER} riceve\n"
    .string "il SUPER AMO!$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe_IT::
    .string "La pesca è uno stile di vita!\p"
    .string "Dai fiumi al mare, pesca il pesce\n"
    .string "più grosso!\p"
    .string "Senti, devo chiederti un piacere.\n"
    .string "Se catturi dei MAGIKARP enormi,\l"
    .string "puoi portarli a farmeli vedere?$"

Route12_FishingHouse_Text_OhThatsDisappointing_IT::
    .string "Oh!…\n"
    .string "Ma che delusione…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp_IT::
    .string "Salve, {PLAYER}!\n"
    .string "Come va?\p"
    .string "Utilizza il SUPER AMO in tutte le\n"
    .string "acque! Potrai pescare varie specie\l"
    .string "di POKéMON.\p"
    .string "Ah, non dimenticare di portarmi\n"
    .string "un MAGIKARP gigantesco!$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee_IT::
    .string "Oh? {PLAYER}?\p"
    .string "E quello è MAGIKARP!\n"
    .string "Fammi un po' vedere!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis_IT::
    .string "… … …Wow!\n"
    .string "{STR_VAR_2} cm!\p"
    .string "Hai mostrato una grande passione\n"
    .string "per la nobile arte della pesca!\p"
    .string "Tieni, questo è il mio premio!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords_IT::
    .string "Mi aspetto grandi record da te!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast_IT::
    .string "Huh?\n"
    .string "{STR_VAR_2} cm?\p"
    .string "Sbaglio o ne ho già visto uno\n"
    .string "esattamente della stessa\l"
    .string "dimensione?$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp_IT::
    .string "Questo misura {STR_VAR_2} cm.\p"
    .string "Non può competere con\n"
    .string "quello che misurava {STR_VAR_3} cm!$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp_IT::
    .string "Questo non è un MAGIKARP!$"

Route12_FishingHouse_Text_NoRoomForGift_IT::
    .string "Oh no!\p"
    .string "Avevo un regalo per te, ma non\n"
    .string "hai più spazio!$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches_IT::
    .string "Questo è il MAGIKARP più grande\n"
    .string "che abbia mai visto…\p"
    .string "{STR_VAR_3} cm!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort_IT::
    .string "Sembra una specie di\n"
    .string "tabella.\p"
    .string "Vi sono spazi per registrare\n"
    .string "delle cifre, pare.$"

