CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow_DE::
	.string "Ich kenne jedes Detail der\n"
	.string "POKéMON-WELT in deinem GAME BOY\l"
	.string "ADVANCE!\p"
	.string "Triff dich mit Freunden und tausche\n"
	.string "POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee_DE::
	.string "{PLAYER} erhält ein EVOLI!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull_DE::
	.string "ポケモンが　いっぱいだ\n"
	.string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture_DE::
	.string "POKéMON Lektüre\p"
	.string "Spielen mit dem Drahtlosen Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading_DE::
	.string "Wähle bitte ein Themengebiet aus.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub_DE::
	.string "Der POKéMON DRAHTLOSKLUB\n"
	.string "befindet sich im oberen Stockwerk\l"
	.string "jedes POKéMON-CENTERs.\l"
	.string "Tritt dem Klub bei, um Freunde\l"
	.string "via Drahtlosem Adapter zu treffen.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner_DE::
	.string "Um nur einen Freund zu treffen,\n"
	.string "kannst du in den DIREKTKLUB\l"
	.string "gehen.\l"
	.string "Das ist der rechte Schalter im\l"
	.string "POKéMON DRAHTLOSKLUB.\p"
	.string "Triff deinen Freund in der\n"
	.string "TAUSCHBÖRSE oder im\l"
	.string "KOLOSSEUM!$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom_DE::
	.string "Um dich mit vielen Freunden zu\n"
	.string "treffen, kannst du in den\l"
	.string "KONNEX-KLUB gehen.\l"
	.string "Das ist der linke Schalter im\l"
	.string "POKéMON DRAHTLOSKLUB.\p"
	.string "Im KONNEX-KLUB triffst\n"
	.string "du andere TRAINER.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs_DE::
	.string "Ein INFOBLATT über TM.\p"
	.string "……\p"
	.string "Es gibt insgesamt 50 TM.\p"
	.string "Außerdem gibt es sieben VM, die\n"
	.string "mehrfach nutzbar sind.\p"
	.string "SILPH CO.$"

