CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon_DE::
	.string "Ich hätte gerne ein PORYGON!\p"
	.string "Aber ich habe kein Glück an den\n"
	.string "einarmigen Banditen!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday_DE::
	.string "Ich hatte heute eine\n"
	.string "Glückssträhne!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired_DE::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes_DE::
	.string "Wir tauschen MÜNZEN gegen Preise\n"
	.string "ein.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize_DE::
	.string "Welcher Preis soll es sein?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo_DE::
	.string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize_DE::
	.string "Du möchtest also {STR_VAR_1}\n"
	.string "haben?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM_DE::
	.string "O.K.! Du willst eine\n"
	.string "TM von {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins_DE::
	.string "Schade. Du hast zu wenig MÜNZEN!$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom_DE::
	.string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen_DE::
	.string "あっ そう$"

