CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon_ES::
    .string "¡Quiero el PORYGON tan mono\n"
    .string "que tienen!\p"
    .string "¡Pero es difícil ganar a las\n"
    .string "tragaperras!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday_ES::
    .string "¡He ganado mucho hoy!\n"
    .string "¡Ojalá fuera todos los días igual!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired_ES::
    .string "¡Se requiere un MONEDERO!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes_ES::
    .string "Canjea tus FICHAS por premios.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize_ES::
    .string "¿Qué premio quieres?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo_ES::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize_ES::
    .string "Bien, ¿quieres {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM_ES::
    .string "Muy bien, ¿entonces quieres\n"
    .string "una MT de {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins_ES::
    .string "Perdón, necesitas más FICHAS.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom_ES::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen_ES::
    .string "あっ そう$"
