CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon_FR::
	.string "JE VEUX LE JOLI PORYGON!\p"
	.string "Mais c'est dur de gagner avec\n"
	.string "ces machines à sous!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday_FR::
	.string "La chance…\n"
	.string "C'est mon truc!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired_FR::
	.string "Vous n'avez pas de BOITE JETON!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes_FR::
	.string "Nous échangeons des prix contre\n"
	.string "des JETONS.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize_FR::
	.string "Quel prix désirez-vous?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo_FR::
	.string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize_FR::
	.string "{STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM_FR::
	.string "OK, une CT {STR_VAR_2}.\n"
	.string "C'est ce que vous voulez?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins_FR::
	.string "Vous n'avez pas assez de JETONS.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom_FR::
	.string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen_FR::
	.string "あっ そう$"

