CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon_IT::
    .string "Mi piace quel PORYGON!\n"
    .string "Ma è difficile vincere con le slot\l"
    .string "machine!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday_IT::
    .string "Ho vinto molto oggi!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired_IT::
    .string "È necessario un SALVADANAIO!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes_IT::
    .string "Cambiamo i tuoi GETTONI in premi.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize_IT::
    .string "Che premio vuoi?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo_IT::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize_IT::
    .string "Allora, vuoi {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM_IT::
    .string "OK, allora vuoi una MT\n"
    .string "contenente {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins_IT::
    .string "Ci vogliono altri GETTONI!$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom_IT::
    .string "ÈÊ{LV}ËÎ+ óÂ óÛßÁù$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen_IT::
    .string "あっ そう$"

