SixIsland_PatternBush_Text_BethanyIntro_DE::
	.string "Ich bin neugierig, wie du deine\n"
	.string "POKéMON trainierst?$"

SixIsland_PatternBush_Text_BethanyDefeat_DE::
	.string "Du trainierst deine POKéMON mit\n"
	.string "sehr viel Hingabe!$"

SixIsland_PatternBush_Text_BethanyPostBattle_DE::
	.string "Wie deine Mutter dich mit Liebe\n"
	.string "aufgezogen hat, so sollst du deine\l"
	.string "POKéMON mit Liebe trainieren.$"

SixIsland_PatternBush_Text_AllisonIntro_DE::
	.string "Ich arbeite, um die natürliche\n"
	.string "Ökologie der POKéMON hier\l"
	.string "zu bewahren.$"

SixIsland_PatternBush_Text_AllisonDefeat_DE::
	.string "Oh, für dein Alter bist du wirklich\n"
	.string "überwältigend!$"

SixIsland_PatternBush_Text_AllisonPostBattle_DE::
	.string "Ich sage nicht, dass du keine\n"
	.string "POKéMON fangen sollst.\p"
	.string "Ich möchte nur, dass die Menschen\n"
	.string "ihre POKéMON mit Verantwortungs-\l"
	.string "gefühl aufziehen.$"

SixIsland_PatternBush_Text_GarretIntro_DE::
	.string "Ich habe ein KÄFER-POKéMON\n"
	.string "gefangen, das nur hier vorkommt.$"

SixIsland_PatternBush_Text_GarretDefeat_DE::
	.string "Heheh…\n"
	.string "Ist mein POKéMON nicht toll?$"

SixIsland_PatternBush_Text_GarretPostBattle_DE::
	.string "Neben dem BUSCH gibt es ein\n"
	.string "Mädchen, das SKARABORN\l"
	.string "für TRAINER misst.$"

SixIsland_PatternBush_Text_JonahIntro_DE::
	.string "Weißt du, wenn ich keine KÄFER-\n"
	.string "POKéMON einsetze, fühle ich\l"
	.string "mich nicht wohl.$"

SixIsland_PatternBush_Text_JonahDefeat_DE::
	.string "Ist in Ordnung! Niederlagen machen\n"
	.string "auch den Reiz von POKéMON aus.$"

SixIsland_PatternBush_Text_JonahPostBattle_DE::
	.string "Apropos, “Reiz” ist ein\n"
	.string "merkwürdiges Wort, wenn man\l"
	.string "darüber nachdenkt.\p"
	.string "Wie, wie eine Orangenschale?\n"
	.string "Oder wie eine läutende Glocke?$"

SixIsland_PatternBush_Text_VanceIntro_DE::
	.string "Ja, ja, ja!\n"
	.string "Sieh nur die vielen KÄFER-POKéMON!$"

SixIsland_PatternBush_Text_VanceDefeat_DE::
	.string "Ich wurde besiegt, als ich noch\n"
	.string "feierte!$"

SixIsland_PatternBush_Text_VancePostBattle_DE::
	.string "Beim nächsten Mal nehme ich\n"
	.string "meinen kleinen Bruder mit.$"

SixIsland_PatternBush_Text_NashIntro_DE::
	.string "Sieh nur! Da sind lustige Muster\n"
	.string "am Boden.$"

SixIsland_PatternBush_Text_NashDefeat_DE::
	.string "Supertoll!$"

SixIsland_PatternBush_Text_NashPostBattle_DE::
	.string "Die komischen Muster auf dem\n"
	.string "Boden…\p"
	.string "Sie ähneln den Mustern auf der\n"
	.string "Kleidung meines Großvaters.$"

SixIsland_PatternBush_Text_CordellIntro_DE::
	.string "Ich wette, du denkst, ich sei\n"
	.string "irgend so ein Kerl, oder?$"

SixIsland_PatternBush_Text_CordellDefeat_DE::
	.string "Ich wette, du denkst, ich sei\n"
	.string "schwach, oder?$"

SixIsland_PatternBush_Text_CordellPostBattle_DE::
	.string "Ihr Stadtmenschen kommt immer so\n"
	.string "hip daher mit euren trendy Hüten…\p"
	.string "Wie wärs, wenn du ihn mir gibst?$"

SixIsland_PatternBush_Text_DaliaIntro_DE::
	.string "Nimm einen tiefen Atemzug.\n"
	.string "Ist die Luft nicht köstlich?$"

SixIsland_PatternBush_Text_DaliaDefeat_DE::
	.string "Wenn du möchtest, kann ich dir\n"
	.string "beibringen, wie man richtig atmet.$"

SixIsland_PatternBush_Text_DaliaPostBattle_DE::
	.string "Zunächst, ausatmen.\n"
	.string "Atme ganz tief aus.\p"
	.string "Wenn du nicht mehr ausatmen kannst,\n"
	.string "atme die saubere Luft ein!\p"
	.string "Ist das nicht erfrischend?$"

SixIsland_PatternBush_Text_JoanaIntro_DE::
	.string "Ich liebe KÄFER-POKéMON!\n"
	.string "Deswegen bin ich immer hier.\p"
	.string "Bin ich das einzige Mädchen, das\n"
	.string "so denkt?$"

SixIsland_PatternBush_Text_JoanaDefeat_DE::
	.string "Ich habe verloren, aber ich kann\n"
	.string "noch lachen! Bin ich das einzige\l"
	.string "Mädchen, welches das kann?$"

SixIsland_PatternBush_Text_JoanaPostBattle_DE::
	.string "Ich werde weiterhin KÄFER-POKéMON\n"
	.string "fangen.\p"
	.string "Bin ich das einzige Mädchen, das\n"
	.string "dies so macht?$"

SixIsland_PatternBush_Text_RileyIntro_DE::
	.string "Das ist ein guter Platz.\n"
	.string "Ich schlage hier mein Zelt auf.$"

SixIsland_PatternBush_Text_RileyDefeat_DE::
	.string "Ausgeschaltet…$"

SixIsland_PatternBush_Text_RileyPostBattle_DE::
	.string "Ich werde hier den Nachthimmel\n"
	.string "beobachten.$"

SixIsland_PatternBush_Text_MarcyIntro_DE::
	.string "Oh, pfui!\p"
	.string "Ein Käfer hat mich gestochen!$"

SixIsland_PatternBush_Text_MarcyDefeat_DE::
	.string "Es war kein Käfer. Ich habe mein\n"
	.string "Schienbein am Gras aufgeschnitten.$"

SixIsland_PatternBush_Text_MarcyPostBattle_DE::
	.string "Ein kleiner Schnitt wie dieser…\n"
	.string "ist mit ein wenig Spucke geheilt.$"

SixIsland_PatternBush_Text_LaytonIntro_DE::
	.string "Ist dir irgendetwas Merkwürdiges\n"
	.string "in dieser Gegend aufgefallen?$"

SixIsland_PatternBush_Text_LaytonDefeat_DE::
	.string "Hast du den Boden neben deinen\n"
	.string "Füßen genau betrachtet?$"

SixIsland_PatternBush_Text_LaytonPostBattle_DE::
	.string "Es gibt Stellen hier im\n"
	.string "MUSTERBUSCH, an denen\l"
	.string "kein Gras wächst.\l"
	.string "Was könnte die Ursache für\l"
	.string "solch ein Phänomen sein?$"

