SixIsland_PatternBush_Text_BethanyIntro_ES::
    .string "Oye, que me pica la curiosidad,\n"
    .string "¿cómo crías a tus POKéMON?$"

SixIsland_PatternBush_Text_BethanyDefeat_ES::
    .string "¡Veo que con mucho cariño!$"

SixIsland_PatternBush_Text_BethanyPostBattle_ES::
    .string "Hay que criarlos con el mismo\n"
    .string "cariño con el que una madre cría\l"
    .string "a sus pequeños.$"

SixIsland_PatternBush_Text_AllisonIntro_ES::
    .string "Yo me encargo de preservar el\n"
    .string "entorno natural de los POKéMON.$"

SixIsland_PatternBush_Text_AllisonDefeat_ES::
    .string "¡Para la edad que tienes,\n"
    .string "eres increíble!$"

SixIsland_PatternBush_Text_AllisonPostBattle_ES::
    .string "¡Yo no he dicho que no debas\n"
    .string "atrapar POKéMON!\p"
    .string "Sólo quiero que la gente los críe\n"
    .string "de forma responsable.$"

SixIsland_PatternBush_Text_GarretIntro_ES::
    .string "He atrapado un POKéMON del tipo\n"
    .string "BICHO que sólo vive por aquí.$"

SixIsland_PatternBush_Text_GarretDefeat_ES::
    .string "Je, je, je...\n"
    .string "¿No es impresionante mi POKéMON?$"

SixIsland_PatternBush_Text_GarretPostBattle_ES::
    .string "Hay una chica cerca del arbusto,\n"
    .string "que mide las fuerzas de HERACROSS.$"

SixIsland_PatternBush_Text_JonahIntro_ES::
    .string "¿Sabes? Si no uso POKéMON del tipo\n"
    .string "BICHO, no disfruto los combates.$"

SixIsland_PatternBush_Text_JonahDefeat_ES::
    .string "No pasa nada, perder tiene también\n"
    .string "su encanto.$"

SixIsland_PatternBush_Text_JonahPostBattle_ES::
    .string "A todo esto, lo del “encanto”\n"
    .string "lo digo porque hay que saber\l"
    .string "ganar y perder.\p"
    .string "Es como el blanco y el negro,\n"
    .string "como el día y la noche. ¿No?$"

SixIsland_PatternBush_Text_VanceIntro_ES::
    .string "¡Mira qué POKéMON del tipo BICHO\n"
    .string "tengo! ¡Sí, señor!$"

SixIsland_PatternBush_Text_VanceDefeat_ES::
    .string "¡Me han ganado en plena euforia!$"

SixIsland_PatternBush_Text_VancePostBattle_ES::
    .string "La próxima vez, me vengo con mi\n"
    .string "hermano pequeño.$"

SixIsland_PatternBush_Text_NashIntro_ES::
    .string "¡Mira al suelo!\n"
    .string "Qué dibujos más raros... ¿verdad?$"

SixIsland_PatternBush_Text_NashDefeat_ES::
    .string "¡Increíble!$"

SixIsland_PatternBush_Text_NashPostBattle_ES::
    .string "Los dibujos tan raros del suelo...\p"
    .string "¡Se parecen al estampado de\n"
    .string "la ropa de mi abuelo!$"

SixIsland_PatternBush_Text_CordellIntro_ES::
    .string "Crees que soy inofensivo, ¿eh?$"

SixIsland_PatternBush_Text_CordellDefeat_ES::
    .string "Crees que soy débil, ¿no?$"

SixIsland_PatternBush_Text_CordellPostBattle_ES::
    .string "La gente de ciudad siempre viene\n"
    .string "dándose demasiados aires...\p"
    .string "Aunque a mí no me vendrían\n"
    .string "mal unos pocos...$"

SixIsland_PatternBush_Text_DaliaIntro_ES::
    .string "¡Mmmm, respira hondo!\n"
    .string "Qué aire tan puro...$"

SixIsland_PatternBush_Text_DaliaDefeat_ES::
    .string "Si quieres, puedo enseñarte\n"
    .string "técnicas de respiración.$"

SixIsland_PatternBush_Text_DaliaPostBattle_ES::
    .string "Espira...\n"
    .string "Hasta que no te quede aire...\p"
    .string "Cuando no puedas espirar más,\n"
    .string "¡inspira!\p"
    .string "¿No es una sensación de frescor\n"
    .string "fantástica?$"

SixIsland_PatternBush_Text_JoanaIntro_ES::
    .string "Me encantan los POKéMON del tipo\n"
    .string "BICHO. Por eso estoy siempre aquí.\p"
    .string "Supongo que no seré la única...$"

SixIsland_PatternBush_Text_JoanaDefeat_ES::
    .string "No pienso perder la sonrisa.\n"
    .string "Supongo que no soy la única...$"

SixIsland_PatternBush_Text_JoanaPostBattle_ES::
    .string "Voy a seguir coleccionando\n"
    .string "POKéMON del tipo BICHO.\p"
    .string "Supongo que no soy la única...$"

SixIsland_PatternBush_Text_RileyIntro_ES::
    .string "Este sitio es estupendo.\n"
    .string "Voy a colocar la tienda aquí.$"

SixIsland_PatternBush_Text_RileyDefeat_ES::
    .string "Qué paliza...$"

SixIsland_PatternBush_Text_RileyPostBattle_ES::
    .string "Me quedaré aquí para observar\n"
    .string "las estrellas.$"

SixIsland_PatternBush_Text_MarcyIntro_ES::
    .string "¡Ay!\n"
    .string "Creo que me ha picado algo...$"

SixIsland_PatternBush_Text_MarcyDefeat_ES::
    .string "No ha sido ningún bicho, me he\n"
    .string "cortado con el césped.$"

SixIsland_PatternBush_Text_MarcyPostBattle_ES::
    .string "Un cortecillo así...\n"
    .string "Se cura con un poco de saliva.$"

SixIsland_PatternBush_Text_LaytonIntro_ES::
    .string "¿Has visto algo raro por aquí?$"

SixIsland_PatternBush_Text_LaytonDefeat_ES::
    .string "Yo que tú, miraría bien\n"
    .string "por el suelo.$"

SixIsland_PatternBush_Text_LaytonPostBattle_ES::
    .string "Hay sitios en el BOSQUEJO,\n"
    .string "en los que no crece la hierba.\p"
    .string "¿Por qué será?$"
