SilphCo_10F_Text_GruntIntro_ES::
    .string "¡Hola, éste es el noveno piso!\n"
    .string "¡Me alegra que hayas venido!$"

SilphCo_10F_Text_GruntDefeat_ES::
    .string "¡Estoy aturdido!$"

SilphCo_10F_Text_GruntPostBattle_ES::
    .string "¡Bien hecho, pero la sala del\n"
    .string "consejo está un piso más arriba!$"

SilphCo_10F_Text_TravisIntro_ES::
    .string "¡Ya está bien de tonterías!$"

SilphCo_10F_Text_TravisDefeat_ES::
    .string "¡Se acabó lo que se daba!$"

SilphCo_10F_Text_TravisPostBattle_ES::
    .string "¿Te alegra haberme ganado?\n"
    .string "¡Pues vete a casa!$"

SilphCo_10F_Text_WaaaImScared_ES::
    .string "¡Buaaaa!\n"
    .string "¡Tengo miedo!$"

SilphCo_10F_Text_KeepMeCryingASecret_ES::
    .string "¡Por favor, no le digas a nadie\n"
    .string "que he llorado!$"

SilphCo_10F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P9$"
