SilphCo_10F_Text_GruntIntro_FR::
	.string "Bienvenue au 9ème étage!\n"
	.string "C'est sympa de passer!$"

SilphCo_10F_Text_GruntDefeat_FR::
	.string "Aïe!\n"
	.string "Bobo!$"

SilphCo_10F_Text_GruntPostBattle_FR::
	.string "Bien joué, mais la salle du\n"
	.string "conseil est au-dessus!$"

SilphCo_10F_Text_TravisIntro_FR::
	.string "Maintenant…\n"
	.string "Fini de jouer!$"

SilphCo_10F_Text_TravisDefeat_FR::
	.string "Oh!\n"
	.string "Game Over!$"

SilphCo_10F_Text_TravisPostBattle_FR::
	.string "T'as gagné!\n"
	.string "Alors retourne chez toi!$"

SilphCo_10F_Text_WaaaImScared_FR::
	.string "Waaaaa!\n"
	.string "Mamaaaan!$"

SilphCo_10F_Text_KeepMeCryingASecret_FR::
	.string "Ne raconte à personne que j'ai\n"
	.string "pleuré!$"

SilphCo_10F_Text_FloorSign_FR::
	.string "SYLPHE SARL.\n"
	.string "9ème étage.$"

