SilphCo_10F_Text_GruntIntro_IT::
    .string "Ti do il benvenuto al 9º piano!\n"
    .string "Felice di vederti!$"

SilphCo_10F_Text_GruntDefeat_IT::
    .string "Resto di stucco!$"

SilphCo_10F_Text_GruntPostBattle_IT::
    .string "Bel colpo, ma la sala consiliare è\n"
    .string "al piano superiore!$"

SilphCo_10F_Text_TravisIntro_IT::
    .string "Ora basta con i giochetti!$"

SilphCo_10F_Text_TravisDefeat_IT::
    .string "Non c'è più speranza!$"

SilphCo_10F_Text_TravisPostBattle_IT::
    .string "Ecco, mi hai battuto!\n"
    .string "Tornatene a casa!$"

SilphCo_10F_Text_WaaaImScared_IT::
    .string "Wow!\n"
    .string "Che paura!$"

SilphCo_10F_Text_KeepMeCryingASecret_IT::
    .string "Per favore, non dire a nessuno che\n"
    .string "ho pianto!$"

SilphCo_10F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "9ºP$"

