SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale_IT::
    .string "{PLAYER}: Ciao!\n"
    .string "Ti piacciono i POKéMON?\p"
    .string "{PLAYER}: Eh?\n"
    .string "Te l'ho appena chiesto io.\p"
    .string "{PLAYER}: Eh?\n"
    .string "Sei molto strana!\p"
    .string "COPIONA: Smettere di imitare?\n"
    .string "Ma è il mio hobby preferito!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale_IT::
    .string "{PLAYER}: Ciao!\n"
    .string "Ti piacciono i POKéMON?\p"
    .string "{PLAYER}: Eh?\n"
    .string "Te l'ho appena chiesto io.\p"
    .string "{PLAYER}: Eh?\n"
    .string "Sei molto strana!\p"
    .string "COPIONA: Smettere di imitare?\n"
    .string "Ma è il mio hobby preferito!$"

Text_MimicTeach_IT::
    .string "Wow!\n"
    .string "Una POKé BAMBOLA!\p"
    .string "Per me?\n"
    .string "Grazie!\p"
    .string "Sai cosa ti dico? Se vuoi posso\n"
    .string "insegnare MIMICA ad uno dei\l"
    .string "tuoi POKéMON.$"

Text_MimicDeclined_IT::
    .string "Non ti piace MIMICA?$"

Text_MimicWhichMon_IT::
    .string "Adoro MIMICA.\n"
    .string "A quale POKéMON vuoi che la\l"
    .string "insegni?$"

Text_MimicTaughtMale_IT::
    .string "{PLAYER}: Grazie ancora per prima!\p"
    .string "{PLAYER}: Come?\p"
    .string "{PLAYER}: È così bello imitare ogni\n"
    .string "mia mossa?\p"
    .string "COPIONA: Bello?\n"
    .string "È favoloso!$"

Text_MimicTaughtFemale_IT::
    .string "{PLAYER}:Grazie per quello che\n"
    .string "hai fatto per noi!\p"
    .string "{PLAYER}: Come?\p"
    .string "{PLAYER}: È così bello imitare ogni\n"
    .string "mia mossa?\p"
    .string "COPIONA: Bello?\n"
    .string "È favoloso!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag_IT::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP_IT::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP_IT::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo_IT::
    .string "DODUO: Dododù!\p"
    .string "SPECCHIO DELLE MIE BRAME CHI È\n"
    .string "LA PIÙ BELLA DEL REAME?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll_IT::
    .string "Un POKéMON raro!\n"
    .string "No, è solo una bambola!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket_IT::
    .string "Un gioco in cui MARIO ha un secchio\n"
    .string "sulla testa!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets_IT::
    .string "…\p"
    .string "I miei segreti!\p"
    .string "Capacità: Imitazione.\n"
    .string "Hobby: Collezioni di bambole.\l"
    .string "POKéMON favorito: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee_IT::
    .string "？　みえないぞ‥$"

