SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale_ES::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¿Te gustan los POKéMON?\p"
    .string "{PLAYER}: ¿No?\n"
    .string "Oye, te he hecho una pregunta.\p"
    .string "{PLAYER}: ¿Eh?\n"
    .string "Eres un poquito raro, ¿no?\p"
    .string "COPIONA: ¿Qué? ¿Que deje\n"
    .string "de imitar? ¡Es mi hobby favorito!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale_ES::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¿Te gustan los POKéMON?\p"
    .string "{PLAYER}: ¿No?\n"
    .string "Oye, te he hecho una pregunta.\p"
    .string "{PLAYER}: ¿Eh?\n"
    .string "Eres un poquito rara, ¿no?\p"
    .string "COPIONA: ¿Qué? ¿Que deje\n"
    .string "de imitar? ¡Es mi hobby favorito!$"

Text_MimicTeach_ES::
    .string "¡Uauuu!\n"
    .string "¡Un POKé MUÑECO!\p"
    .string "¿Es para mí?\n"
    .string "¡Gracias!\p"
    .string "¿Sabes una cosa? Podría\n"
    .string "enseñarte el movimiento MIMÉTICO.$"

Text_MimicDeclined_ES::
    .string "¿No tienes interés en MIMÉTICO?$"

Text_MimicWhichMon_ES::
    .string "¡Bien, a mí me encanta!\n"
    .string "¿A qué POKéMON quieres que\l"
    .string "le enseñe MIMÉTICO?$"

Text_MimicTaughtMale_ES::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¡Gracias por lo de antes!\p"
    .string "{PLAYER}: ¿Sí?\p"
    .string "{PLAYER}: ¿Te divierte imitar cada\n"
    .string "uno de mis movimientos?\p"
    .string "COPIONA: ¿Verdad?\n"
    .string "¡Es muy divertido!$"

Text_MimicTaughtFemale_ES::
    .string "{PLAYER}: ¡Hola!\n"
    .string "¡Gracias por lo de antes!\p"
    .string "{PLAYER}: ¿Sí?\p"
    .string "{PLAYER}: ¿Te divierte imitar cada\n"
    .string "uno de mis movimientos?\p"
    .string "COPIONA: ¿Verdad?\n"
    .string "¡Es muy divertido!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag_ES::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP_ES::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP_ES::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo_ES::
    .string "DODUO: ¡Dodu!\p"
    .string "¡ESPEJO, ESPEJITO! ¿QUIÉN ES\n"
    .string "LA MÁS BELLA DE TODAS?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll_ES::
    .string "¡Éste es un POKéMON raro!\n"
    .string "¿Eh? ¡Pero si es un muñeco!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket_ES::
    .string "¡Un juego de MARIO con un cubo\n"
    .string "en la cabeza!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets_ES::
    .string "...\p"
    .string "¡Éstos son mis secretos!\p"
    .string "Habilidad: imitar.\n"
    .string "Hobby: coleccionar muñecos.\l"
    .string "POKéMON favorito: ¡CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee_ES::
    .string "？　みえないぞ‥$"
