SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale_FR::
	.string "{PLAYER}: Salut!\n"
	.string "Tu aimes les POKéMON?\p"
	.string "{PLAYER}: Heu, non\n"
	.string "Je demandais juste!\p"
	.string "{PLAYER}: Hein?\n"
	.string "T'es bizarre toi!\p"
	.string "COPIEUSE: Hmm?\n"
	.string "Arrêter de mimer?\p"
	.string "Mais je ne sais faire que ça!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale_FR::
	.string "{PLAYER}: Salut! Tu dois aimer\n"
	.string "les POKéMON, non?\p"
	.string "{PLAYER}: Heu, non\n"
	.string "Je demandais juste!\p"
	.string "{PLAYER}: Hein?\n"
	.string "T'es bizarre toi!\p"
	.string "COPIEUSE: Hmm?\n"
	.string "Arrêter de mimer?\p"
	.string "Mais je ne sais faire que ça!$"

Text_MimicTeach_FR::
	.string "Whaaaaaa!\n"
	.string "Une POKéPOUPEE!\p"
	.string "C'est pour moi?\n"
	.string "Merci!\p"
	.string "Tiens, prends ça en échange!$"

Text_MimicDeclined_FR::
	.string "T'aimes pas COPIE?$"

Text_MimicWhichMon_FR::
	.string "Moi aussi j'adore! Alors, qui\n"
	.string "va l'apprendre?$"

Text_MimicTaughtMale_FR::
	.string "{PLAYER}: Salut!\n"
	.string "Merci pour la CT31!\p"
	.string "{PLAYER}: Pardon?\p"
	.string "{PLAYER}: Heu…\n"
	.string "C'est aussi cool que ça de\l"
	.string "m'imiter?\p"
	.string "COPIEUSE: Ah non! C'est vraiment la\n"
	.string "galère, t'arrêtes pas d'bouger!$"

Text_MimicTaughtFemale_FR::
	.string "{PLAYER}: Salut!\n"
	.string "Merci pour la CT31!\p"
	.string "{PLAYER}: Pardon?\p"
	.string "{PLAYER}: Heu…\n"
	.string "C'est aussi marrant que ça de\l"
	.string "m'imiter?\p"
	.string "COPIEUSE: Ah non! C'est vraiment la\n"
	.string "galère, t'arrêtes pas d'bouger!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag_FR::
	.string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP_FR::
	.string "{PLAYER}“やあ！　こんにちは！\n"
	.string "きみ　ポケモン　すきかい？\p"
	.string "{PLAYER}“ぼく　じゃなくって\n"
	.string "きみに　きいてるんだ　けど\p"
	.string "{PLAYER}“‥‥　えー　なんだよ！\n"
	.string "ヘンな　やつ　だなあ！\p"
	.string "モノマネむすめ“‥‥　なに？\n"
	.string "ひとの　マネ　すんなって？\p"
	.string "だって　あたし　\n"
	.string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP_FR::
	.string "{PLAYER}“こんにちは！\n"
	.string "ポケモン　すきなのね？\p"
	.string "{PLAYER}“わたし　じゃなくって\n"
	.string "あなたに　きいてるんだ　けど\p"
	.string "{PLAYER}“‥　えー　なんなの！\n"
	.string "おかしなこ　ねー！\p"
	.string "モノマネむすめ“‥　なに？\n"
	.string "ひとの　マネ　すんなって？\p"
	.string "だって　あたし\n"
	.string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo_FR::
	.string "DODUO: Doduuu!\p"
	.string "JOLI MIROIR, DIS-MOI QUI EST\n"
	.string "LA PLUS BELLE!$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll_FR::
	.string "Ça, un POKéMON rare? Tu t'moques\n"
	.string "de moi! C'est rien qu'une poupée!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket_FR::
	.string "Un plombier? Mais…\n"
	.string "Ça a l'air sympa.$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets_FR::
	.string "…\p"
	.string "Mes secrets!\p"
	.string "Mon boulot: je mime!\n"
	.string "Ma passion: les poupées!\l"
	.string "Mon POKéMON préféré: MELOFEE!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee_FR::
	.string "？　みえないぞ‥$"

