SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale_DE::
	.string "{PLAYER}: Hallo!\n"
	.string "Magst du POKéMON?\p"
	.string "{PLAYER}: Halt, ich habe doch dich\n"
	.string "gefragt.\p"
	.string "{PLAYER}: Wie?\n"
	.string "Du bist komisch!\p"
	.string "NACHAHMERIN: Hmm? Ich soll die\n"
	.string "Nachahmerei aufgeben?\p"
	.string "Aber das ist doch mein Hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale_DE::
	.string "{PLAYER}: Hallo!\n"
	.string "Magst du POKéMON?\p"
	.string "{PLAYER}: Halt, ich habe doch dich\n"
	.string "gefragt.\p"
	.string "{PLAYER}: Wie?\n"
	.string "Du bist komisch!\p"
	.string "NACHAHMERIN: Hmm? Ich soll die\n"
	.string "Nachahmerei aufgeben?\p"
	.string "Aber das ist doch mein Hobby!$"

Text_MimicTeach_DE::
	.string "Wow!\n"
	.string "Das ist ja eine POKéPUPPE!\p"
	.string "Die ist für mich?\n"
	.string "Vielen Dank!\p"
	.string "Ich werde dafür einem deiner\n"
	.string "POKéMON die Attacke MIMIKRY\l"
	.string "beibringen!$"

Text_MimicDeclined_DE::
	.string "Magst du MIMIKRY nicht?$"

Text_MimicWhichMon_DE::
	.string "Ich liebe MIMIKRY!\n"
	.string "Wer soll es erlernen?$"

Text_MimicTaughtMale_DE::
	.string "{PLAYER}: Hallo!\n"
	.string "Vielen Dank!\p"
	.string "{PLAYER}: Entschuldigung?\p"
	.string "{PLAYER}: … macht es dir wirklich\n"
	.string "so viel Spaß, mich nachzuahmen?\p"
	.string "NACHAHMERIN: Darauf kannst du\n"
	.string "wetten! Es ist grandios!$"

Text_MimicTaughtFemale_DE::
	.string "{PLAYER}: Hallo!\n"
	.string "Vielen Dank!\p"
	.string "{PLAYER}: Entschuldigung?\p"
	.string "{PLAYER}: … macht es dir wirklich\n"
	.string "so viel Spaß, mich nachzuahmen?\p"
	.string "NACHAHMERIN: Darauf kannst du\n"
	.string "wetten! Es ist grandios!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag_DE::
	.string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP_DE::
	.string "{PLAYER}“やあ！　こんにちは！\n"
	.string "きみ　ポケモン　すきかい？\p"
	.string "{PLAYER}“ぼく　じゃなくって\n"
	.string "きみに　きいてるんだ　けど\p"
	.string "{PLAYER}“‥‥　えー　なんだよ！\n"
	.string "ヘンな　やつ　だなあ！\p"
	.string "モノマネむすめ“‥‥　なに？\n"
	.string "ひとの　マネ　すんなって？\p"
	.string "だって　あたし　\n"
	.string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP_DE::
	.string "{PLAYER}“こんにちは！\n"
	.string "ポケモン　すきなのね？\p"
	.string "{PLAYER}“わたし　じゃなくって\n"
	.string "あなたに　きいてるんだ　けど\p"
	.string "{PLAYER}“‥　えー　なんなの！\n"
	.string "おかしなこ　ねー！\p"
	.string "モノマネむすめ“‥　なに？\n"
	.string "ひとの　マネ　すんなって？\p"
	.string "だって　あたし\n"
	.string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo_DE::
	.string "DODU: Giegie!\p"
	.string "SPIEGLEIN, SPIEGLEIN AN DER\n"
	.string "WAND, WER IST DIE SCHÖNSTE IM\l"
	.string "GANZEN LAND?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll_DE::
	.string "Ein seltenes POKéMON! Hmm?\n"
	.string "Es ist nur eine Puppe!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket_DE::
	.string "Ein Spiel mit MARIO!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets_DE::
	.string "...\p"
	.string "Meine Geheimnisse!\p"
	.string "Zeitvertreib: Mienenspiel\n"
	.string "Hobby: Puppen sammeln\l"
	.string "Lieblings-POKéMON: PIEPI!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee_DE::
	.string "？　みえないぞ‥$"

