PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou_DE::
	.string "MUTTER: Richtig. Irgendwann gehen\n"
	.string "alle Kinder fort, um ein Abenteuer\l"
	.string "zu erleben!\p"
	.string "PROF. EICH von nebenan hat nach\n"
	.string "dir gefragt.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou_DE::
	.string "MUTTER: … genau!\n"
	.string "Jedes Mädchen träumt vom Reisen.\l"
	.string "Das sieht man im Fernsehen.\p"
	.string "Oh, ja, PROF. EICH von nebenan\n"
	.string "hat nach dir gesucht!$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest_DE::
	.string "MUTTER: {PLAYER}! Du solltest eine\n"
	.string "kurze Pause einlegen.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare_DE::
	.string "MUTTER: Sehr gut! Du und deine\n"
	.string "POKéMON sehen großartig aus!\l"
	.string "Achte auf dich!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad_DE::
	.string "Im Fernsehen läuft ein Film.\n"
	.string "Vier Jungen laufen ein Bahngleis\l"
	.string "entlang!\p"
	.string "Den Film kenne ich schon! Ich\n"
	.string "mache mich besser auf den Weg!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad_DE::
	.string "Es läuft ein Film im TV.\n"
	.string "Ein bezopftes Mädchen läuft\l"
	.string "einen gelben Steinweg entlang.\p"
	.string "… ich breche auch besser auf!$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide_DE::
	.string "Ups, falsche Richtung!$"

