PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou_FR::
	.string "MAMAN: Bon…\p"
	.string "Tous les garçons quittent\n"
	.string "un jour la maison. C'est la vie!\p"
	.string "Le PROF. CHEN te cherche. Il est\n"
	.string "dans la maison voisine.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou_FR::
	.string "MAMAN: Bon…\p"
	.string "Il paraît que c'est le rêve de\n"
	.string "toutes les filles de voyager.\p"
	.string "Le PROF. CHEN te cherche. Il est\n"
	.string "dans la maison voisine.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest_FR::
	.string "MAMAN: {PLAYER}!\n"
	.string "Tu devrais faire une sieste.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare_FR::
	.string "MAMAN: Ah, bien! Tes POKéMON et\n"
	.string "toi êtes en pleine forme!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad_FR::
	.string "Il y a un film à la télé.\p"
	.string "Y'a un gars cool dans un taxi.\p"
	.string "Bon…\n"
	.string "Je ferais bien d'y aller.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad_FR::
	.string "Il y a un film à la télé.\p"
	.string "C'est le Seigneur des Agneaux.\p"
	.string "Bon…\n"
	.string "Je ferais bien d'y aller.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide_FR::
	.string "Oups, mauvais côté.$"

