PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou_IT::
    .string "MAMMA: …Bene!\n"
    .string "Prima o poi tutti i ragazzi vanno\l"
    .string "via di casa. Lo dice anche la TV!\p"
    .string "Il nostro vicino, il PROF. OAK, ti\n"
    .string "sta cercando.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou_IT::
    .string "MAMMA: …Bene!\n"
    .string "Prima o poi tutti i ragazzi vanno\l"
    .string "via di casa. Lo dice anche la TV!\p"
    .string "Il nostro vicino, il PROF. OAK, ti\n"
    .string "sta cercando.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest_IT::
    .string "MAMMA: {PLAYER}!\n"
    .string "Dovresti riposarti un po'.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare_IT::
    .string "MAMMA: Perfetto! Ora tu e i tuoi\n"
    .string "POKéMON siete in gran forma!\l"
    .string "Fai attenzione!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad_IT::
    .string "C'è un film in TV. Quattro ragazzi\n"
    .string "camminano sui binari!\p"
    .string "Ora però è meglio che ti metta\n"
    .string "in viaggio anche tu!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad_IT::
    .string "C'è un film in TV. Una ragazza\n"
    .string "con le trecce cammina su una\l"
    .string "strada lastricata!\p"
    .string "Ora però è meglio che ti metta\n"
    .string "in viaggio anche tu!$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide_IT::
    .string "Oh! È il lato sbagliato!$"

