LavenderTown_House2_Text_WantMeToRateNicknames_IT::
    .string "Salve! Sono il GIUDICE\n"
    .string "ONOMASTICO!\p"
    .string "Vuoi che valuti i soprannomi dei\n"
    .string "tuoi POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname_IT::
    .string "Di quale soprannome di POKéMON\n"
    .string "devo presagire il futuro?$"

LavenderTown_House2_Text_GiveItANicerName_IT::
    .string "{STR_VAR_1}?\n"
    .string "Non è male!\p"
    .string "Ti suggerisco un altro soprannome?\p"
    .string "Sei d'accordo?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe_IT::
    .string "Bene! Quale nuovo soprannome vuoi\n"
    .string "dare?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName_IT::
    .string "Fatto! D'ora in poi, questo POKéMON\n"
    .string "si chiamerà {STR_VAR_1}!\p"
    .string "È un nome migliore del primo!\n"
    .string "Proprio una bella fortuna!$"

LavenderTown_House2_Text_ISeeComeVisitAgain_IT::
    .string "Capisco…\n"
    .string "Torna a farmi visita.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName_IT::
    .string "Fatto! D'ora in poi, questo POKéMON\n"
    .string "si chiamerà {STR_VAR_1}!\p"
    .string "D'aspetto non è cambiato, ma il\n"
    .string "nuovo soprannome lo rende\l"
    .string "immensamente superiore!$"

LavenderTown_House2_Text_TrulyImpeccableName_IT::
    .string "Fatto! D'ora in poi, questo POKéMON\n"
    .string "si chiamerà {STR_VAR_1}!\p"
    .string "D'aspetto non è cambiato, però è\n"
    .string "immensamente superiore!\l"
    .string "Proprio una bella fortuna!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg_IT::
    .string "Suvvia!\n"
    .string "È soltanto un UOVO!$"

