LavenderTown_House2_Text_WantMeToRateNicknames_ES::
    .string "¡Je, je! ¡Hola!\n"
    .string "¡Soy el INSPECTOR de los MOTES!\l"
    .string "¡El adivinador de nombres!\p"
    .string "Estaré encantado de evaluar\n"
    .string "el nombre de tu POKéMON, je, je.$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname_ES::
    .string "¿Qué nombre de POKéMON\n"
    .string "quieres que adivine y evalúe?$"

LavenderTown_House2_Text_GiveItANicerName_ES::
    .string "Mmmmm... {STR_VAR_1}, ¿a que sí?\n"
    .string "No está mal, no está mal...\p"
    .string "Pero ¿no crees que podríamos\n"
    .string "encontrar un nombre aún mejor?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe_ES::
    .string "Así me gusta. A ver... \n"
    .string "¿Cuál será el nuevo nombre?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName_ES::
    .string "¡Ya está! ¡A partir de ahora,\n"
    .string "el nombre de este POKéMON\l"
    .string "será {STR_VAR_1}!\p"
    .string "Es un nombre mucho mejor que\n"
    .string "el anterior, ¡qué suerte tienes!$"

LavenderTown_House2_Text_ISeeComeVisitAgain_ES::
    .string "Muy bien...\n"
    .string "Entonces vuelve cuando quieras.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName_ES::
    .string "¡Ya está! ¡A partir de ahora,\n"
    .string "el nombre de este POKéMON\l"
    .string "será {STR_VAR_1}!\p"
    .string "No parece muy diferente\n"
    .string "del anterior y, sin embargo,\l"
    .string "es muchísimo mejor.\p"
    .string "¡Qué suerte tienes!$"

LavenderTown_House2_Text_TrulyImpeccableName_ES::
    .string "¿{STR_VAR_1}?\n"
    .string "¡Ese nombre es perfecto!\p"
    .string "¡Cuida bien de {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg_ES::
    .string "Pero vamos a ver...\n"
    .string "¡Esto es sólo un HUEVO!$"
