RocketHideout_B3F_Text_Grunt1Intro_DE::
	.string "Halte dich aus TEAM ROCKETs\n"
	.string "Angelegenheiten raus!$"

RocketHideout_B3F_Text_Grunt1Defeat_DE::
	.string "Uff!\n"
	.string "Ich bin am Boden!$"

RocketHideout_B3F_Text_Grunt1PostBattle_DE::
	.string "Das SILPH SCOPE? Das Gerät, das\n"
	.string "der BOSS geraubt hat?\p"
	.string "Das ist hier irgendwo...$"

RocketHideout_B3F_Text_Grunt2Intro_DE::
	.string "Wir hörten schon, dass du im\n"
	.string "Anmarsch bist!$"

RocketHideout_B3F_Text_Grunt2Defeat_DE::
	.string "Was?\n"
	.string "Ich hab verloren? Ah!$"

RocketHideout_B3F_Text_Grunt2PostBattle_DE::
	.string "Geh ruhig weiter!\p"
	.string "Du benötigst den LIFTÖFFNER und\n"
	.string "der fehlt dir!$"

