RocketHideout_B3F_Text_Grunt1Intro_IT::
    .string "Non immischiarti negli affari di\n"
    .string "TEAM ROCKET!$"

RocketHideout_B3F_Text_Grunt1Defeat_IT::
    .string "Uff!\n"
    .string "Sono al tappeto!$"

RocketHideout_B3F_Text_Grunt1PostBattle_IT::
    .string "La SPETTROSONDA? Ah,\n"
    .string "la macchina rubata dal CAPO!\p"
    .string "Dev'essere qui da qualche parte…$"

RocketHideout_B3F_Text_Grunt2Intro_IT::
    .string "Abbiamo già avuto notizia del tuo\n"
    .string "arrivo!$"

RocketHideout_B3F_Text_Grunt2Defeat_IT::
    .string "Ho perso?\n"
    .string "Impossibile!!!$"

RocketHideout_B3F_Text_Grunt2PostBattle_IT::
    .string "Vai avanti, dai!\p"
    .string "Ma ti serve la CHIAVE\n"
    .string "dell'ASCENSORE!$"

