SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies_ES::
    .string "La velocidad de crecimiento de los\n"
    .string "POKéMON varía de una especie a\l"
    .string "otra.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame_ES::
    .string "SILPH S.A. es muy famosa.\p"
    .string "¡Por eso el TEAM ROCKET tiene\n"
    .string "tanto interés en ella!$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets_ES::
    .string "¡Sería estupendo que el ALTO\n"
    .string "MANDO viniera y machacara al TEAM\l"
    .string "ROCKET!$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff_ES::
    .string "¡El TEAM ROCKET se ha ido!\n"
    .string "¡Ahora podemos salir sin peligro!\l"
    .string "¡Bien!$"
