SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies_FR::
	.string "Les POKéMON grandissent\n"
	.string "différemment selon les espèces.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame_FR::
	.string "La SYLPHE SARL est très connue.\p"
	.string "C'est pourquoi la TEAM ROCKET l'a\n"
	.string "investie!$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets_FR::
	.string "Pourquoi le CONSEIL 4 ne vient\n"
	.string "pas chasser la TEAM ROCKET?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff_FR::
	.string "La TEAM ROCKET est partie!\n"
	.string "Alors c'est la fête! Youpi!$"

