SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies_IT::
    .string "Il ritmo di crescita dei POKéMON\n"
    .string "varia da specie a specie.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame_IT::
    .string "SILPH SpA è molto famosa, perciò\n"
    .string "TEAM ROCKET ha deciso di\l"
    .string "impadronirsene!$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets_IT::
    .string "Non sarebbe fantastico se\n"
    .string "arrivassero i SUPERQUATTRO e\l"
    .string "annientassero TEAM ROCKET?!$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff_IT::
    .string "TEAM ROCKET se n'è andato!\n"
    .string "Ora si può uscire senza pericolo!\l"
    .string "Ottimo!$"

