Route16_House_Text_FoundMySecretRetreat_FR::
	.string "Oh!\n"
	.string "Tu as trouvé ma cache secrète!\p"
	.string "Prends ceci. En échange, ne dis\n"
	.string "à personne que tu m'as vue!$"

Route16_House_Text_ReceivedHM02FromGirl_FR::
	.string "{PLAYER} obtient la\n"
	.string "CS02!$"

Route16_House_Text_ExplainHM02_FR::
	.string "CS02: VOL. C'est une capacité\n"
	.string "très pratique.\p"
	.string "Fais-en bon usage!$"

Route16_House_Text_DontHaveAnyRoomForThis_FR::
	.string "Ton inventaire est plein.$"

Route16_House_Text_Fearow_FR::
	.string "RAPASDEPIC: Piiiiiik!$"

