Route16_House_Text_FoundMySecretRetreat_IT::
    .string "Hai scovato il mio rifugio segreto!\p"
    .string "Ti prego, non dire a nessuno che\n"
    .string "sono qui e ti ricambierò!$"

Route16_House_Text_ReceivedHM02FromGirl_IT::
    .string "{PLAYER} riceve\n"
    .string "la MN02!$"

Route16_House_Text_ExplainHM02_IT::
    .string "La MN02 è VOLO.\n"
    .string "Ti riporterà in qualsiasi città.\p"
    .string "Fanne buon uso!$"

Route16_House_Text_DontHaveAnyRoomForThis_IT::
    .string "Non hai più spazio per questo.$"

Route16_House_Text_Fearow_IT::
    .string "FEAROW: Row Row!$"

