Route16_House_Text_FoundMySecretRetreat_DE::
	.string "Du hast meinen geheimen\n"
	.string "Unterschlupf gefunden!\p"
	.string "Bitte erzähle niemandem davon.\n"
	.string "Du bekommst auch etwas von mir!$"

Route16_House_Text_ReceivedHM02FromGirl_DE::
	.string "{PLAYER} erhält\n"
	.string "VM02!$"

Route16_House_Text_ExplainHM02_DE::
	.string "VM02 ist FLIEGEN. Damit kannst du\n"
	.string "in jede Stadt zurückfliegen.\p"
	.string "Sie wird dir von Nutzen sein!$"

Route16_House_Text_DontHaveAnyRoomForThis_DE::
	.string "Du hast keinen Platz mehr, um sie\n"
	.string "mitzunehmen!$"

Route16_House_Text_Fearow_DE::
	.string "IBITAK: IBITAK!$"

