PokemonTower_1F_Text_ErectedInMemoryOfDeadMons_FR::
	.string "La TOUR POKéMON a été érigée en\n"
	.string "mémoire des braves POKéMON\l"
	.string "disparus au combat.$"

PokemonTower_1F_Text_ComeToPayRespectsSon_FR::
	.string "Tu es venu leur rendre hommage?\p"
	.string "C'est tout à ton honneur,\n"
	.string "mon petit!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl_FR::
	.string "Tu es venu leur rendre hommage?\p"
	.string "C'est tout à ton honneur,\n"
	.string "ma petite!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy_FR::
	.string "Je suis venu prier pour mon\n"
	.string "MELOFEE.\p"
	.string "Sniff!\n"
	.string "J'arrête pas de pleurer…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie_FR::
	.string "Mon CANINOS…\n"
	.string "Tu me manques…$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief_FR::
	.string "Je suis une EXORCISTE!\n"
	.string "Je chasse les esprits!$"

