PokemonTower_1F_Text_ErectedInMemoryOfDeadMons_IT::
    .string "La TORRE POKéMON fu eretta in\n"
    .string "memoria dei POKéMON scomparsi.$"

PokemonTower_1F_Text_ComeToPayRespectsSon_IT::
    .string "Sei qui per rendere omaggio?\n"
    .string "Che bel gesto, figliolo!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl_IT::
    .string "Sei qui per rendere omaggio?\n"
    .string "Che bel gesto, figliola!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy_IT::
    .string "Prego per il mio CLEFAIRY.\p"
    .string "Sigh!\n"
    .string "Non faccio che piangere…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie_IT::
    .string "Il mio GROWLITHE…\n"
    .string "Perché sei morto?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief_IT::
    .string "Sono una MEDIUM!\n"
    .string "Ci sono spiriti molto inquieti\l"
    .string "in questo posto!$"

