PokemonTower_1F_Text_ErectedInMemoryOfDeadMons_DE::
	.string "Der POKéMON-TURM wurde im Andenken\n"
	.string "an verblichene POKéMON errichtet.$"

PokemonTower_1F_Text_ComeToPayRespectsSon_DE::
	.string "Bist du hier, um dein Mitgefühl\n"
	.string "auszudrücken? Sei gesegnet!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl_DE::
	.string "Bist du hier, um dein Mitgefühl\n"
	.string "auszudrücken? Sei gesegnet!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy_DE::
	.string "Ich bete für PIEPI...\p"
	.string "Schluchz! Ich kann nicht aufhören\n"
	.string "zu weinen...$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie_DE::
	.string "FUKANO...\n"
	.string "Warum hast du mich verlassen?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief_DE::
	.string "Ich bin eine EXORZISTIN!\n"
	.string "Die Geister hier stiften Unruhe!$"

