FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke_FR::
	.string "Nous avons surnommé le GARDIEN,\n"
	.string "RAMOLOSS.\p"
	.string "Ben, oui! Il ressemble à un\n"
	.string "RAMOLOSS!$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable_FR::
	.string "RAMOLOSS s'y connaît beaucoup\n"
	.string "en POKéMON!\p"
	.string "Il a même des fossiles de POKéMON\n"
	.string "rares et anciens!$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden_FR::
	.string "RAMOLOSS m'a parlé, mais je ne\n"
	.string "comprends rien à c'qu'il m'dit.\p"
	.string "Je crois qu'il a un problème pour\n"
	.string "parler!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone_FR::
	.string "RAMOLOSS vient de lancer une\n"
	.string "campagne de promotion.\p"
	.string "Essaie d'aller dans le coin le\n"
	.string "plus éloigné du PARC SAFARI.\p"
	.string "Si tu y arrives, tu recevras un\n"
	.string "prix.$"

