Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers_IT::
    .string "Un tuo POKéMON è più o meno\n"
    .string "efficace a seconda del tipo a cui\l"
    .string "appartiene l'avversario.\p"
    .string "Questa si chiama combinazione tra i\n"
    .string "tipi.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000_IT::
    .string "Ho venduto un'inutile PEPITA per\n"
    .string "¥5.000!$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender_IT::
    .string "Si dice che LAVANDONIA sia\n"
    .string "infestata dagli spettri!$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons_IT::
    .string "Ciao! Sono l'ASSISTENTE del\n"
    .string "PROF. OAK! Ti stavo cercando!\p"
    .string "Se nel POKéDEX hai i dati di\n"
    .string "almeno 20 specie di POKéMON ti do\l"
    .string "PIETRASTANTE!\p"
    .string "Allora, {PLAYER}, hai raccolto dati\n"
    .string "su almeno 20 specie di\l"
    .string "POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo_IT::
    .string "Bene! Hai raccolto dati su {STR_VAR_3}\n"
    .string "specie di POKéMON!\p"
    .string "Congratulazioni!\n"
    .string "Tieni! Te lo sei meritato!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide_IT::
    .string "{PLAYER} riceve\n"
    .string "PIETRASTANTE!$"

Route10_PokemonCenter_1F_Text_ExplainEverstone_IT::
    .string "Fare evolvere i POKéMON può\n"
    .string "senz'altro aiutare a completare il\l"
    .string "POKéDEX.\p"
    .string "A volte, però, può essere utile\n"
    .string "impedire l'evoluzione.\p"
    .string "In quel caso, puoi dare\n"
    .string "PIETRASTANTE ad un POKéMON.\p"
    .string "Quando tiene quello strumento,\n"
    .string "il POKéMON non può evolversi.$"

