Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers_ES::
    .string "¡Los POKéMON de ciertos elementos\n"
    .string "son más o menos fuertes que otros!$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000_ES::
    .string "¡Vendí una inútil PEPITA\n"
    .string "por 5.000¥!$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender_ES::
    .string "¡Dicen que hay fantasmas en\n"
    .string "PUEBLO LAVANDA!$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons_ES::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes 20 tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "PIEDRAETERNA!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "20 tipos de POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo_ES::
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide_ES::
    .string "¡{PLAYER} obtuvo la\n"
    .string "PIEDRAETERNA de manos\l"
    .string "del AYUDANTE!$"

Route10_PokemonCenter_1F_Text_ExplainEverstone_ES::
    .string "Si dejas evolucionar a los\n"
    .string "POKéMON, tu POKéDEX\l"
    .string "se verá beneficiada.\p"
    .string "Aunque habrá algún caso en el\n"
    .string "que no quieras que evolucionen.\p"
    .string "Para evitarlo, dale al POKéMON\n"
    .string "que quieras una PIEDRAETERNA.\p"
    .string "Según dice el PROFESOR,\n"
    .string "el POKéMON que la lleve,\l"
    .string "no evolucionará.$"
