SixIsland_Mart_Text_AgathaOldestEverEliteFourMember_DE::
	.string "Spiele viel mit POKéMON und\n"
	.string "führe ein langes Leben!\p"
	.string "Nimm z.B. AGATHE!\p"
	.string "Sie hält den Rekord als ältestes\n"
	.string "Mitglied der TOP VIER.\p"
	.string "Sie ist mein Ansporn nach\n"
	.string "Größerem zu streben.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter_DE::
	.string "Ich sollte Briefpapier kaufen und\n"
	.string "ihm schreiben…$"

