SixIsland_Mart_Text_AgathaOldestEverEliteFourMember_ES::
    .string "¡Juega con los POKéMON y vivirás\n"
    .string "mucho tiempo!\p"
    .string "Mira a AGATHA, por ejemplo.\p"
    .string "Es el miembro de más edad\n"
    .string "del ALTO MANDO.\p"
    .string "¡A mí me anima a superarme\n"
    .string "día a día!$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter_ES::
    .string "Debería escribir alguna CARTA...$"
