CeruleanCity_Text_RivalIntro_IT::
    .string "{RIVAL}: Ciao {PLAYER}!\p"
    .string "Bazzichi ancora da queste parti,\n"
    .string "pappamolle?!\p"
    .string "Io vado forte! Ho preso un mucchio\n"
    .string "di POKéMON furbi e potenti!\p"
    .string "{PLAYER}, fammi un po' vedere cosa\n"
    .string "hai catturato!$"

CeruleanCity_Text_RivalDefeat_IT::
    .string "Ehi!\n"
    .string "Rilassati!\l"
    .string "Hai vinto!$"

CeruleanCity_Text_RivalPostBattle_IT::
    .string "{RIVAL}: Ehi, la sai una cosa?\p"
    .string "Sono stato da BILL e mi sono fatto\n"
    .string "mostrare i suoi POKéMON rari!\p"
    .string "Così ho aggiunto molte pagine al\n"
    .string "mio POKéDEX!\p"
    .string "BILL è noto a tutti come\n"
    .string "POKéFANATICO!\p"
    .string "Ha inventato il Sistema Memoria\n"
    .string "POKéMON per il PC!\p"
    .string "Visto che usi il suo sistema, vai a\n"
    .string "ringraziarlo!\p"
    .string "Beh, meglio che mi dia una mossa!\n"
    .string "Ci becchiamo in giro!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor_IT::
    .string "Ah, dimenticavo.\p"
    .string "Provo un po' di compassione per te.\n"
    .string "Dico davvero! Sei sempre lì che\l"
    .string "cerchi di essere alla mia altezza.\p"
    .string "Tieni, voglio farti un regalo.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa_IT::
    .string "Te lo regalo perché so che ti\n"
    .string "piace spettegolare.\p"
    .string "A me non serve, visto che della\n"
    .string "gente non m'importa un fico secco.\p"
    .string "Vabbè, questa volta me ne vado\n"
    .string "davvero. Ci becchiamo in giro!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory_IT::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro_IT::
    .string "Ehi! Fuori!\n"
    .string "Non ti è permesso stare qui…\p"
    .string "Chi?\n"
    .string "Io?\p"
    .string "Sono un semplice passante!\n"
    .string "Non mi credi?{PLAY_BGM MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat_IT::
    .string "RECLUTA: Stop! Mi arrendo!\n"
    .string "Me ne vado in silenzio!$"

CeruleanCity_Text_OkayIllReturnStolenTM_IT::
    .string "OK!\n"
    .string "Restituirò la MT che ho rubato!$"

CeruleanCity_Text_RecoveredTM28FromGrunt_IT::
    .string "{PLAYER} recupera\n"
    .string "la MT28!$"

CeruleanCity_Text_BetterGetMovingBye_IT::
    .string "Meglio che mi sbrighi!\n"
    .string "Ciao!$"

CeruleanCity_Text_MakeRoomForThisCantRun_IT::
    .string "Fai spazio per questa cosa!\p"
    .string "Non posso andare finché non te l'ho\n"
    .string "data!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt_IT::
    .string "Anche tu un ALLENATORE, eh?\p"
    .string "Collezionare, lottare… che vita\n"
    .string "dura!$"

CeruleanCity_Text_YouCanCutDownSmallTrees_IT::
    .string "Lo sapevi che con TAGLIO\n"
    .string "puoi abbattere piccoli alberi?\p"
    .string "Quell'alberello di fronte al\n"
    .string "negozio, per esempio.\p"
    .string "Forse puoi anche passare per\n"
    .string "un'altra strada, comunque.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree_IT::
    .string "Se non fosse per quello SLOWBRO,\n"
    .string "potresti usare TAGLIO per\l"
    .string "abbattere l'alberello.\p"
    .string "In quel modo potresti arrivare\n"
    .string "dall'altra parte.\p"
    .string "Forse puoi anche passare per\n"
    .string "un'altra strada, comunque.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing_IT::
    .string "Stai creando un'enciclopedia sui\n"
    .string "POKéMON? Interessante!$"

CeruleanCity_Text_PeopleHereWereRobbed_IT::
    .string "Questa gente è stata derubata.\p"
    .string "C'è sicuramente lo zampino di TEAM\n"
    .string "ROCKET in questo atroce crimine!\p"
    .string "La POLIZIA avrà senz'altro un\n"
    .string "bel da fare con quei ROCKET!$"

CeruleanCity_Text_SlowbroUseSonicboom_IT::
    .string "OK! SLOWBRO!\n"
    .string "Usa SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention_IT::
    .string "Forza SLOWBRO, fai attenzione!$"

CeruleanCity_Text_SlowbroPunch_IT::
    .string "SLOWBRO, sferra un pugno!$"

CeruleanCity_Text_NoYouBlewItAgain_IT::
    .string "No!\n"
    .string "Hai mancato ancora!$"

CeruleanCity_Text_SlowbroWithdraw_IT::
    .string "SLOWBRO, RITIRATA!$"

CeruleanCity_Text_HardToControlMonsObedience_IT::
    .string "No! Non va bene!\p"
    .string "È così difficile controllare i\n"
    .string "POKéMON!\p"
    .string "L'obbedienza dei tuoi POKéMON\n"
    .string "dipende dalla tua abilità di\l"
    .string "ALLENATORE!$"

CeruleanCity_Text_SlowbroTookSnooze_IT::
    .string "SLOWBRO fa un pisolino…$"

CeruleanCity_Text_SlowbroLoafingAround_IT::
    .string "SLOWBRO fa il pigrone…$"

CeruleanCity_Text_SlowbroTurnedAway_IT::
    .string "SLOWBRO se n'è andato…$"

CeruleanCity_Text_SlowbroIgnoredOrders_IT::
    .string "SLOWBRO ignora gli ordini…$"

CeruleanCity_Text_WantBrightRedBicycle_IT::
    .string "Voglio una BICICLETTA rossa\n"
    .string "fiammante.\p"
    .string "La terrò in casa così non si\n"
    .string "sporcherà!$"

CeruleanCity_Text_ThisIsCeruleanCave_IT::
    .string "Questa è la GROTTA CELESTE!\n"
    .string "Ci vivono POKéMON fortissimi!\p"
    .string "Può entrarci solo il CAMPIONE\n"
    .string "della LEGA POKéMON!\p"
    .string "Non prima di aver ottenuto un altro\n"
    .string "importante risultato, però.$"

CeruleanCity_Text_CitySign_IT::
    .string "CELESTOPOLI\n"
    .string "Circondata da una misteriosa aura\l"
    .string "celeste$"

CeruleanCity_Text_TrainerTipsHeldItems_IT::
    .string "CONSIGLI UTILI\p"
    .string "Puoi dare ad un POKéMON\n"
    .string "uno strumento da tenere.\p"
    .string "Alcuni strumenti tenuti possono\n"
    .string "anche essere usati nella lotta.$"

CeruleanCity_Text_BikeShopSign_IT::
    .string "NEGOZIO di BICI\n"
    .string "Per ben andar per prati e grotte!$"

CeruleanCity_Text_GymSign_IT::
    .string "CAPOPALESTRA di CELESTOPOLI:\n"
    .string "MISTY\l"
    .string "La sirena maschiaccio!$"

