CeruleanCity_BikeShop_Text_WelcomeToBikeShop_IT::
    .string "Salve, questo è il NEGOZIO di\n"
    .string "BICI!\p"
    .string "Abbiamo la BICICLETTA che\n"
    .string "fa per te!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt_IT::
    .string "Mi dispiace, è cara per te!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo_IT::
    .string "Oh! È un…\p"
    .string "BUONO BICI!\p"
    .string "Bene, è tua!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle_IT::
    .string "{PLAYER} scambia il BUONO per una\n"
    .string "BICICLETTA.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain_IT::
    .string "Torna a servirti qui!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle_IT::
    .string "Ti piace la tua nuova BICICLETTA?\p"
    .string "La puoi usare su PISTE CICLABILI\n"
    .string "e nelle grotte!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle_IT::
    .string "Fai spazio per questo!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe_IT::
    .string "Per me, una normale BICICLETTA\n"
    .string "basta e avanza!\p"
    .string "Le mountain bike non mi piacciono:\n"
    .string "non ci si può mettere il cestino!$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive_IT::
    .string "Queste BICICLETTE sono belle\n"
    .string "ma care!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool_IT::
    .string "Wow!\n"
    .string "La tua BICICLETTA è un mito!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket_IT::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle_IT::
    .string "Una BICICLETTA nuova di zecca!$"

