CeruleanCity_BikeShop_Text_WelcomeToBikeShop_DE::
	.string "Hallo!\n"
	.string "Willkommen im FAHRRADLADEN!\p"
	.string "Wir haben garantiert das richtige\n"
	.string "FAHRRAD für dich!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt_DE::
	.string "Es tut mir Leid, du kannst es dir\n"
	.string "nicht leisten!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo_DE::
	.string "Oh, das ist ein...\p"
	.string "... RAD-COUPON!\p"
	.string "O.K.!\n"
	.string "Es gehört dir!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle_DE::
	.string "{PLAYER} tauscht den RAD-COUPON\n"
	.string "gegen das FAHRRAD.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain_DE::
	.string "Besuch uns doch wieder!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle_DE::
	.string "Wie gefällt dir dein neues FAHRRAD?\p"
	.string "Du kannst damit auf dem RADWEG und\n"
	.string "in Höhlen fahren!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle_DE::
	.string "Du kannst es momentan nicht\n"
	.string "mitnehmen!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe_DE::
	.string "Ich möchte ein HOLLANDRAD kaufen!\p"
	.string "Ein MOUNTAINBIKE hat keinen\n"
	.string "Gepäckträger!$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive_DE::
	.string "Die FAHRRÄDER sind ziemlich cool,\n"
	.string "aber unheimlich teuer!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool_DE::
	.string "Wow!\n"
	.string "Du hast ein cooles FAHRRAD!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket_DE::
	.string "ついに　はつばい！\p"
	.string "ドイツ　せい　さいこうきゅう\n"
	.string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle_DE::
	.string "Ein brandneues FAHRRAD!$"

