CeruleanCity_BikeShop_Text_WelcomeToBikeShop_FR::
	.string "Bienvenue aux CYCLES A GOGO.\p"
	.string "Nous avons justement une belle\n"
	.string "bicyclette!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt_FR::
	.string "Oh!\n"
	.string "Tu n'as pas assez d'argent!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo_FR::
	.string "Oh! Mais c'est…\p"
	.string "Un BON pour une BICYCLETTE!\p"
	.string "OK!\n"
	.string "Voilà ta BICYCLETTE!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle_FR::
	.string "{PLAYER} échange le BON contre une\n"
	.string "BICYCLETTE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain_FR::
	.string "Reviens quand tu veux!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle_FR::
	.string "Ça va comme tu veux\n"
	.string "avec ta BICYCLETTE?\p"
	.string "Avec, tu peux aller sur la PISTE\n"
	.string "CYCLABLE et dans les GROTTES!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle_FR::
	.string "Ton inventaire est plein!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe_FR::
	.string "Un vélo de ville, c'est ce qu'il y\n"
	.string "a de mieux!\p"
	.string "Il n'y a pas de porte-bagages sur\n"
	.string "un VTT!$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive_FR::
	.string "Ces vélos sont super mais ils sont\n"
	.string "très chers!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool_FR::
	.string "Waouh! \n"
	.string "Ta BICYCLETTE est super cool!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket_FR::
	.string "ついに　はつばい！\p"
	.string "ドイツ　せい　さいこうきゅう\n"
	.string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle_FR::
	.string "Une BICYCLETTE toute neuve! Top!$"

