FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen_FR::
	.string "Il y a beaucoup de POKéMON\n"
	.string "enfermés dans leur cachot…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled_FR::
	.string "La porte du cachot est ouverte.\n"
	.string "Les POKéMON se sont enfuis.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro_FR::
	.string "Tu savais que c'était l'ENTREPOT\n"
	.string "ROCKET en venant ici?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat_FR::
	.string "Qu'est-ce que tu crois faire?$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle_FR::
	.string "La TEAM ROCKET? Perdre?\n"
	.string "De quelle planète tu viens?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro_FR::
	.string "Oh, tes POKéMON sont balèzes.\n"
	.string "Tu voudrais pas les vendre?\p"
	.string "Oh?\n"
	.string "Tu veux te battre?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat_FR::
	.string "Oh, mais…\n"
	.string "C'est trop!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle_FR::
	.string "On peut te faire un super prix\n"
	.string "si tu nous vends tes POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro_FR::
	.string "Les autres m'ont déjà parlé de toi.\p"
	.string "Mais quelqu'un comme toi ne\n"
	.string "peut pas connaître GIOVANNI.$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat_FR::
	.string "Ne te moque pas.$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle_FR::
	.string "Ne te mêle pas des affaires\n"
	.string "des adultes, tu n'es pas de taille.$"

FiveIsland_RocketWarehouse_Text_Admin1Intro_FR::
	.string "Je me moque de savoir si ce que\n"
	.string "je fais est bien ou mal…\p"
	.string "J'obéis aveuglément aux ordres\n"
	.string "de GIOVANNI.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat_FR::
	.string "Je…\n"
	.string "Je suis à bout de forces…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle_FR::
	.string "Il faut toujours agir selon sa\n"
	.string "conscience.\p"
	.string "Je comprends maintenant…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough_FR::
	.string "Je viens de faire en sorte que tu\n"
	.string "puisses repasser par ici.\p"
	.string "Pourquoi n'irais-tu pas te reposer\n"
	.string "un peu avant de continuer?\p"
	.string "L'ADMIN juste après est un bien\n"
	.string "meilleur DRESSEUR que moi.\p"
	.string "Tu dois t'attendre à un combat\n"
	.string "très difficile.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro_FR::
	.string "Nous en avons assez que tu\n"
	.string "viennes gêner nos plans.\p"
	.string "Faire courir la rumeur que la\n"
	.string "TEAM ROCKET a été démantelée.\p"
	.string "Il est évident que tu cherches à\n"
	.string "semer la confusion dans nos rangs.\p"
	.string "Mais nous ne sommes pas stupides\n"
	.string "au point de croire ces mensonges.\p"
	.string "Je vais te montrer pourquoi il ne\n"
	.string "faut pas se mêler de nos affaires!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat_FR::
	.string "Urgh…\n"
	.string "Comment as-tu pu?\p"
	.string "…\n"
	.string "C'est le badge de GIOVANNI!\p"
	.string "Alors c'est vrai?\p"
	.string "La TEAM ROCKET a vraiment\n"
	.string "été démantelée?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle_FR::
	.string "Nous allons quitter cet ENTREPOT.\p"
	.string "Mais ne crois pas que tout\n"
	.string "soit fini.\p"
	.string "Je vais trouver GIOVANNI.\n"
	.string "Et je vais faire renaître la\l"
	.string "TEAM ROCKET.\p"
	.string "On se reverra!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText_FR::
	.string "Des graphiques et du texte sont\n"
	.string "affichés sur l'ordinateur.\p"
	.string "“Influence des ondes magnétiques\n"
	.string "sur l'évolution des POKéMON”…\p"
	.string "C'est trop compliqué…$"

FiveIsland_RocketWarehouse_Text_GideonIntro_FR::
	.string "J'avais presque réussi à vendre le\n"
	.string "SAPHIR pour une très belle somme…\p"
	.string "Et il fallait que tu arrives et\n"
	.string "viennes gâcher mon affaire!\p"
	.string "Hin hin hin…\n"
	.string "Pas de pitié pour toi!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat_FR::
	.string "Non, non et non!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle_FR::
	.string "Si je ne peux pas le vendre, il\n"
	.string "ne me sert plus à rien. Prends-le!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe_FR::
	.string "Quoi encore?\n"
	.string "Va-t-en, laisse-moi.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair_FR::
	.string "Quoi, encore toi?\p"
	.string "Tu n'es pas le gamin de GIOVANNI,\n"
	.string "n'est-ce pas?\p"
	.string "Non, impossible! Son gamin a\n"
	.string "les cheveux rouges.\p"
	.string "Tu n'as aucune raison de venir\n"
	.string "encore m'importuner.$"

