FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen_DE::
	.string "Viele POKéMON sind in diesem\n"
	.string "Schuppen eingesperrt…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled_DE::
	.string "Die Tür ist unverschlossen.\n"
	.string "Die POKéMON sind geflohen.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro_DE::
	.string "Wusstest du, dass dies das LAGER\n"
	.string "von TEAM ROCKET ist, ehe du\l"
	.string "hierher kamst?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat_DE::
	.string "Was glaubst du, was du tust?$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle_DE::
	.string "TEAM ROCKET wurde zerschlagen?\n"
	.string "Auf welchem Planeten lebst du?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro_DE::
	.string "Nun sehen deine POKéMON stark aus.\n"
	.string "Möchtest du sie verkaufen?\p"
	.string "Oh?\n"
	.string "Du möchtest kämpfen?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat_DE::
	.string "Oh, aber…\n"
	.string "Zu viel für mich!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle_DE::
	.string "Wir machen dir einen guten Preis.\n"
	.string "Verkaufe uns deine POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro_DE::
	.string "Die anderen haben mir bereits\n"
	.string "von dir erzählt.\l"
	.string "Aber es kann nicht sein, dass ein\l"
	.string "Kind wie du unseren BOSS\l"
	.string "GIOVANNI kennt!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat_DE::
	.string "Wage… es… nicht… zu… lachen…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle_DE::
	.string "Misch dich nicht in die\n"
	.string "Angelegenheiten von\l"
	.string "Erwachsenen ein, du Plage!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro_DE::
	.string "Ich weiß nicht und es kümmert mich\n"
	.string "auch nicht, ob das, was ich tue,\l"
	.string "recht oder unrecht ist…\l"
	.string "Ich vertraue GIOVANNI und befolge\l"
	.string "seine Anweisungen.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat_DE::
	.string "Ich…\n"
	.string "Ich bin am Boden…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle_DE::
	.string "Du handelst nach bestem Wissen\n"
	.string "und Gewissen.\p"
	.string "Jetzt verstehe ich es…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough_DE::
	.string "Ich habe es so eingerichtet, dass\n"
	.string "du hier durchkannst, wenn du\l"
	.string "wieder kommst.\l"
	.string "Warum erholst und erfrischst du\l"
	.string "dich nicht, um gewappnet zu sein?\p"
	.string "Der VORS. nach mir ist ein viel\n"
	.string "gewissenhafterer TRAINER als ich.\p"
	.string "Mach dich lieber auf einen harten\n"
	.string "Kampf bereit.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro_DE::
	.string "Du stirbst jetzt den Heldentod,\n"
	.string "Youngster! Dafür sorge ich!\p"
	.string "Das Verbreiten von Lügen über TEAM\n"
	.string "ROCKETs Auflösung…\p"
	.string "Das ist so ein offensichtlicher\n"
	.string "Versuch, Unordnung in unsere\l"
	.string "Organisation zu bringen.\l"
	.string "Glücklicherweise schenken wir den\l"
	.string "Lügen eines Kindes keinen Glauben!\p"
	.string "Und nun zeige ich dir, wie grausam\n"
	.string "und wütend ein Erwachsener sein\l"
	.string "kann!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat_DE::
	.string "Argh…\n"
	.string "Du warst zu stark…\p"
	.string "…\n"
	.string "D-das ist der ORDEN von GIOVANNI!\p"
	.string "Es ist also wahr?\n"
	.string "TEAM ROCKET ist Geschichte?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle_DE::
	.string "Wir werden dieses LAGER verlassen…\p"
	.string "Aber denke bloß nicht, es wäre\n"
	.string "erledigt. Ich lasse nicht zu, dass\l"
	.string "dies das Ende ist.\l"
	.string "Ich werde GIOVANNI finden. Und\l"
	.string "ich werde TEAM ROCKET aufer-\l"
	.string "stehen lassen! Das werde ich…\p"
	.string "Bis dahin! Leb wohl!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText_DE::
	.string "Ein mit Grafiken und Text aus-\n"
	.string "gestatteter Bericht ist auf dem\l"
	.string "PC-Monitor.\l"
	.string "“Der Einfluss von Magnet-\l"
	.string "wellen bei der POKéMON-\l"
	.string "Entwicklung”…\l"
	.string "…………\l"
	.string "……\p"
	.string "Es ist zu schwierig, zu verstehen…$"

FiveIsland_RocketWarehouse_Text_GideonIntro_DE::
	.string "Fast hätte ich den SAPHIR für viel\n"
	.string "Geld verkaufen können…\p"
	.string "Dann musstest du kommen und alles\n"
	.string "kaputtmachen!\p"
	.string "Fufu… fufufufu…\n"
	.string "Es gibt kein Erbarmen für dich!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat_DE::
	.string "Argh! Mist!\n"
	.string "Mist! Blöder Mist!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle_DE::
	.string "Wenn ich ihn nicht verkaufen\n"
	.string "kann, ist er wertlos!\l"
	.string "Nimm ihn und lass mich in Ruhe!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe_DE::
	.string "Was willst du jetzt?\n"
	.string "Mach schon, hau ab, lass mich!$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair_DE::
	.string "Was, du schon wieder?\p"
	.string "Du… du bist nicht das Kind von\n"
	.string "GIOVANNI! Sein Kind ist rothaarig.\p"
	.string "Du hast keinen Grund, mich zu\n"
	.string "ärgern. Lass mich in Frieden!$"

