FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen_ES::
    .string "Hay un montón de POKéMON\n"
    .string "encerrados en el cobertizo...$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled_ES::
    .string "La puerta está abierta.\n"
    .string "Se ve que los POKéMON han huido.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro_ES::
    .string "¿Has venido hasta aquí sabiendo\n"
    .string "que era el ALMACÉN ROCKET?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat_ES::
    .string "Pero bueno, ¿tú qué te crees?$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle_ES::
    .string "¿Que si el TEAM ROCKET se ha\n"
    .string "separado?\l"
    .string "Pero ¿tú de qué planeta vienes?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro_ES::
    .string "Tus POKéMON parecen muy fuertes.\n"
    .string "¿No te gustaría venderlos?\p"
    .string "¡Ah, que quieres luchar!$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat_ES::
    .string "Ufff...\n"
    .string "Ha sido mucha paliza...$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle_ES::
    .string "¡Oye, te podemos pagar mucho\n"
    .string "por tus POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro_ES::
    .string "Me han hablado mucho de ti.\p"
    .string "¡Ante nuestro JEFE GIOVANNI\n"
    .string "no vas a poder hacer nada!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat_ES::
    .string "No... te... rías... Grrr...$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle_ES::
    .string "¡No deberías meter las narices en\n"
    .string "las cosas de los mayores, cotilla!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro_ES::
    .string "Ni sé ni me importa si lo que hago\n"
    .string "está bien o no...\p"
    .string "Yo confío en GIOVANNI y cumplo\n"
    .string "con lo que se me dice.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat_ES::
    .string "Es-estoy... sin aliento...$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle_ES::
    .string "Entiendo que lo que haces responde\n"
    .string "a tus principios.\p"
    .string "Ahora lo entiendo.$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough_ES::
    .string "He dejado esto así para que\n"
    .string "puedas volver a entrar.\p"
    .string "¿No quieres descansar antes de\n"
    .string "continuar con lo que te queda?\p"
    .string "El ADMINISTRADOR que me sigue\n"
    .string "es mejor ENTRENADOR que yo.\p"
    .string "Más vale que te prepares para\n"
    .string "un difícil encuentro.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro_ES::
    .string "Ya está bien de ir de guay.\p"
    .string "Lo de contar que el TEAM ROCKET\n"
    .string "se ha separado es...\p"
    .string "un intento descarado de causar\n"
    .string "el desconcierto entre nosotros.\p"
    .string "Pero afortunadamente no somos\n"
    .string "lelos y no nos tragamos semejantes\l"
    .string "chorradas.\p"
    .string "¡Te vas a enterar de lo que llegan\n"
    .string "a molestar estas cosas!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat_ES::
    .string "Grrrrrr...\n"
    .string "¡Eres demasiado fuerte!...\p"
    .string "¡Eh!...\n"
    .string "¡Ésa es la MEDALLA de GIOVANNI!\p"
    .string "Entonces, ¿es verdad que el TEAM\n"
    .string "ROCKET se ha disuelto?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle_ES::
    .string "¡Nos iremos del ALMACÉN!...\p"
    .string "Pero no te pienses que la cosa\n"
    .string "se queda ahí. ¡Ya me ocuparé yo!\p"
    .string "Iré a buscar a GIOVANNI y reuniré\n"
    .string "al TEAM ROCKET. ¡Ya lo verás!\p"
    .string "¡Hasta entonces, ya nos veremos!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText_ES::
    .string "Hay un informe con gráficos\n"
    .string "y anotaciones en el monitor del PC.\p"
    .string "“La influencia de las ondas\n"
    .string "magnéticas en la evolución de los\l"
    .string "POKéMON”...\p"
    .string "... ... ... ... ... ...\p"
    .string "Cualquiera entiende esto...$"

FiveIsland_RocketWarehouse_Text_GideonIntro_ES::
    .string "He estado a punto de vender\n"
    .string "el ZAFIRO por un buen pellizco...\p"
    .string "¡Y vas tú y apareces justo cuando\n"
    .string "iba a cerrar el trato!\p"
    .string "¡Grrrrrrrrrrrrrrrrr...!\n"
    .string "¡No tienes perdón!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat_ES::
    .string "¡Ufff! ¿Será posible?\n"
    .string "¡Grrrrrrr!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle_ES::
    .string "Si no voy a poder venderlo, no lo\n"
    .string "quiero para nada. ¡Quédatelo tú!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe_ES::
    .string "¿Y ahora qué?\n"
    .string "¿Quieres dejarme ya en paz?$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair_ES::
    .string "Pero ¿otra vez tú?\p"
    .string "Tú... tú no eres el retoño\n"
    .string "de GIOVANNI, ¿verdad?\p"
    .string "No, no puede ser, el retoño\n"
    .string "de GIOVANNI es pelirrojo.\p"
    .string "Bueno, ¿y por qué me incordias?\n"
    .string "Déjame, anda.$"
