CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore_DE::
	.string "Willkommen im EINKAUFSZENTRUM von\n"
	.string "PRISMANIA CITY!\p"
	.string "Auf der Tafel rechts findest du\n"
	.string "eine Übersicht.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions_DE::
	.string "EG: KUNDENINFORMATION\p"
	.string "1S: ZUBEHÖR FÜR TRAINER\p"
	.string "2S: VIDEOSPIELE-SHOP\p"
	.string "3S: GESCHENKARTIKEL\p"
	.string "4S: DROGERIE\p"
	.string "DACHGARTEN: AUTOMATEN$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter_DE::
	.string "EG: KUNDENINFORMATION$"

