@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords_FR::
	.string "とびらを　あけるには\n"
	.string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded_FR::
	.string "{PLAYER} entre le mot de passe.\p"
	.string "“ICI, GIRAFARIG, ICI”.\p"
	.string "… …  … …  … …\p"
	.string "Il faut un autre mot de passe\n"
	.string "pour ouvrir la porte…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened_FR::
	.string "{PLAYER} entre les mots de passe.\p"
	.string "“ICI, GIRAFARIG, ICI”.\n"
	.string "“TARSAL LA STAR”.\p"
	.string "… …  … …  … …\p"
	.string "La porte de l'ENTREPOT\n"
	.string "est ouverte!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen_FR::
	.string "La porte de l'ENTREPOT est\n"
	.string "déjà ouverte.$"

FiveIsland_Meadow_Text_Rocket1Intro_FR::
	.string "L'accès à cette zone est interdit!\n"
	.string "Dehors!$"

FiveIsland_Meadow_Text_Rocket1Defeat_FR::
	.string "Non, j'ai vraiment perdu, là?$"

FiveIsland_Meadow_Text_Rocket1PostBattle_FR::
	.string "Tu n'as rien à faire ici!\n"
	.string "Rentre chez toi!$"

FiveIsland_Meadow_Text_Rocket2Intro_FR::
	.string "A part notre ENTREPOT, il n'y\n"
	.string "a rien dans le coin.\p"
	.string "Alors qu'est-ce que tu fais ici?$"

FiveIsland_Meadow_Text_Rocket2Defeat_FR::
	.string "Ça devait pas se passer\n"
	.string "comme ça…$"

FiveIsland_Meadow_Text_Rocket2PostBattle_FR::
	.string "Tu veux savoir ce qui se\n"
	.string "passe dans l'ENTREPOT?\p"
	.string "Crois-moi, pour ta sécurité, il\n"
	.string "vaut mieux que tu le saches pas.$"

FiveIsland_Meadow_Text_Rocket3Intro_FR::
	.string "Tu perds ton temps à essayer\n"
	.string "de me battre.$"

FiveIsland_Meadow_Text_Rocket3Defeat_FR::
	.string "Arrh, ça me rend furieuse!$"

FiveIsland_Meadow_Text_Rocket3PostBattle_FR::
	.string "De toute façon, tu ne pourras pas\n"
	.string "continuer sans mot de passe.$"

