@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords_DE::
	.string "とびらを　あけるには\n"
	.string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded_DE::
	.string "{PLAYER} gab ein Passwort ein.\p"
	.string "“ARBOK Kobra”\p"
	.string "…………\n"
	.string "……\p"
	.string "Um die Türe zu öffnen, wird ein\n"
	.string "weiteres Passwort benötigt!$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened_DE::
	.string "{PLAYER} gab zwei Passwörter ein.\p"
	.string "“ARBOK Kobra”\n"
	.string "“MAKUHITA Atihu kam”\p"
	.string "…………\n"
	.string "……\p"
	.string "Die Türe zum LAGER ist offen!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen_DE::
	.string "Die Türe zum LAGER ist bereits\n"
	.string "offen.$"

FiveIsland_Meadow_Text_Rocket1Intro_DE::
	.string "Zutritt zu diesem Gebiet untersagt!\n"
	.string "Raus, raus!$"

FiveIsland_Meadow_Text_Rocket1Defeat_DE::
	.string "Ist das wahr?$"

FiveIsland_Meadow_Text_Rocket1PostBattle_DE::
	.string "Du hast hier nichts verloren!\n"
	.string "Geh nach Hause!$"

FiveIsland_Meadow_Text_Rocket2Intro_DE::
	.string "Hier gibt es nichts weiter, außer\n"
	.string "unserem LAGER.\p"
	.string "Also, was hast du hier zu suchen?$"

FiveIsland_Meadow_Text_Rocket2Defeat_DE::
	.string "Das sollte nicht geschehen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle_DE::
	.string "Du möchtest wissen, was im\n"
	.string "LAGER ist?\p"
	.string "Es ist besser, du weißt das nicht.\n"
	.string "Zu deinem Besten, versteht sich!$"

FiveIsland_Meadow_Text_Rocket3Intro_DE::
	.string "Du verschwendest Zeit, auch\n"
	.string "wenn du an mir vorbei kommst.$"

FiveIsland_Meadow_Text_Rocket3Defeat_DE::
	.string "Oh, das macht mich wütend!$"

FiveIsland_Meadow_Text_Rocket3PostBattle_DE::
	.string "Du kommst ohne die Passwörter\n"
	.string "ohnehin nicht hinein.$"

