CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer_ES::
    .string "¡Los POKéMON capturados tienen un\n"
    .string "N.º IDENTIDAD y un EO, el nombre\p"
    .string "del ENTRENADOR ORIGINAL\n"
    .string "que lo atrapó!$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter_ES::
    .string "¡Muy bien!\p"
    .string "¡Mi compañero va a cambiarme su\n"
    .string "KANGASKHAN por mi GRAVELER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade_ES::
    .string "¡Un GRAVELER!\p"
    .string "¡Me gustan los GRAVELER!\n"
    .string "¡Los colecciono!\p"
    .string "¿Qué?\p"
    .string "¡GRAVELER se transformó en otro\n"
    .string "POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID_ES::
    .string "¡Puedes identificar a los POKéMON\n"
    .string "que hayas cambiado por su N.º ID!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES_ES::
    .string "¡Es una SUPER NINTENDO!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG_ES::
    .string "Un juego de rol.\n"
    .string "¡Genial! ¡Pero no tengo tiempo!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame_ES::
    .string "¡Un juego de deportes!\n"
    .string "¡A mi padre le gustan!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame_ES::
    .string "¡Un juego de puzzles!\n"
    .string "¡Parece muy adictivo!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame_ES::
    .string "¡Un juego de lucha!\n"
    .string "¡Parece muy difícil!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop_ES::
    .string "P2: VIDEOJUEGOS$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon_ES::
    .string "¡Rojo y Verde!\n"
    .string "¡Dos juegos de POKéMON!$"

Text_CounterTeach_ES::
    .string "¡Hola! ¡Ya me he acabado\n"
    .string "POKéMON!\p"
    .string "¿Tú no? ¿Quieres que te enseñe\n"
    .string "un movimiento?\p"
    .string "He pensado en CONTADOR.\p"
    .string "¡No te voy a enseñar el que acabo\n"
    .string "de aprender, claro!$"

Text_CounterDeclined_ES::
    .string "¿No te interesa? Bueno, vuelve\n"
    .string "si cambias de opinión.$"

Text_CounterWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe CONTADOR?$"

Text_CounterTaught_ES::
    .string "¿Estás usando el movimiento\n"
    .string "CONTADOR que le enseñé\l"
    .string "a tu POKéMON?$"
