CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer_IT::
    .string "Tutti i POKéMON catturati sono\n"
    .string "registrati con un NºID.\p"
    .string "Inoltre per ciascuno è indicato\n"
    .string "l'AO, cioè il nome del primo\l"
    .string "ALLENATORE che l'ha avuto.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter_IT::
    .string "Benissimo!\p"
    .string "Il mio amico mi dà un KANGASKHAN\n"
    .string "in cambio di un HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade_IT::
    .string "Avanti HAUNTER!\p"
    .string "Mi piacciono gli HAUNTER, li\n"
    .string "colleziono!\p"
    .string "Cosa succede?\p"
    .string "HAUNTER si è evoluto in un\n"
    .string "altro POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID_IT::
    .string "Puoi identificare\n"
    .string "i POKéMON che hai\l"
    .string "scambiato grazie\l"
    .string "al nº d'identità!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES_IT::
    .string "È un SUPER NINTENDO!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG_IT::
    .string "Un gioco di ruolo.\n"
    .string "Ma non ho tempo!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame_IT::
    .string "Un gioco sportivo!\n"
    .string "Piacciono molto a papà!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame_IT::
    .string "Un puzzle!\n"
    .string "Sembra irresistibile!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame_IT::
    .string "Un gioco di lotta!\n"
    .string "Sembra difficile!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop_IT::
    .string "2ºP: VIDEOGIOCHI$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon_IT::
    .string "Rosso Fuoco e Verde Foglia!\n"
    .string "Sono due giochi POKéMON!$"

Text_CounterTeach_IT::
    .string "Wow!\n"
    .string "Ho finito il gioco!\p"
    .string "Tu ancora no?\p"
    .string "Vuoi che ti insegni una buona\n"
    .string "mossa? Si chiama CONTATORE.$"

Text_CounterDeclined_IT::
    .string "No? Beh, se cambi idea, sai dove\n"
    .string "trovarmi.$"

Text_CounterWhichMon_IT::
    .string "A che POKéMON vuoi che la insegni?$"

Text_CounterTaught_IT::
    .string "Stai usando CONTATORE che ho\n"
    .string "insegnato al tuo POKéMON?$"

