Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30_IT::
    .string "Ciao! Ti ricordi di me?\n"
    .string "Sono l'ASSISTENTE del PROF. OAK!\p"
    .string "Se nel POKéDEX hai i dati di\n"
    .string "almeno {STR_VAR_1} specie di POKéMON ti do\l"
    .string "{STR_VAR_2}!\p"
    .string "Allora, {PLAYER}, hai raccolto dati\n"
    .string "su almeno {STR_VAR_1} specie di\l"
    .string "POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo_IT::
    .string "Bene! Hai raccolto dati su {STR_VAR_3}\n"
    .string "specie di POKéMON!\p"
    .string "Congratulazioni!\n"
    .string "Tieni! Te lo sei meritato!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide_IT::
    .string "{PLAYER} riceve\n"
    .string "{STR_VAR_2}!$"

Route11_EastEntrance_2F_Text_ExplainItemfinder_IT::
    .string "Ci sono strumenti invisibili per\n"
    .string "terra.\p"
    .string "Il DETECTOR ti aiuterà a scovarli.\p"
    .string "Però non può indicarteli con\n"
    .string "esattezza, ma solo la direzione.\p"
    .string "La ricerca vera e propria devi\n"
    .string "farla tu!$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad_IT::
    .string "Guardo con il binocolo…\p"
    .string "Un enorme POKéMON\n"
    .string "dorme in mezzo\l"
    .string "alla strada!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView_IT::
    .string "Guardo con il binocolo…\p"
    .string "C'è un magnifico panorama da qui!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender_IT::
    .string "Guardo con il binocolo…\p"
    .string "Per andare da CELESTOPOLI a\n"
    .string "LAVANDONIA la sola via è il\l"
    .string "TUNNEL ROCCIOSO!$"

