Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30_ES::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes {STR_VAR_1} tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "{STR_VAR_2}!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "{STR_VAR_1} tipos de POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo_ES::
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide_ES::
    .string "¡{PLAYER} obtuvo {STR_VAR_2}\n"
    .string "de manos del AYUDANTE!$"

Route11_EastEntrance_2F_Text_ExplainItemfinder_ES::
    .string "En el suelo hay objetos que no se\n"
    .string "pueden ver.\p"
    .string "El BUSCAOBJETOS detectará\n"
    .string "los objetos que tengas cerca.\p"
    .string "¡Pero no puede señalar dónde están\n"
    .string "exactamente!\p"
    .string "¡Tú tendrás que encontrarlos!$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Un gran POKéMON está durmiendo\n"
    .string "en el camino!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Qué vista tan bonita!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender_ES::
    .string "Has usado los prismáticos...\p"
    .string "¡Puedes ir de CIUDAD CELESTE\n"
    .string "a PUEBLO LAVANDA por el TÚNEL\l"
    .string "ROCA!$"
