PewterCity_House1_Text_Nidoran_DE::
	.string "NIDORAN♂: NIDORAN!$"

PewterCity_House1_Text_NidoranSit_DE::
	.string "NIDORAN, sitz!$"

PewterCity_House1_Text_TradeMonsAreFinicky_DE::
	.string "Unser POKéMON ist ein Außenseiter,\n"
	.string "deshalb ist es schwer zu erziehen!\p"
	.string "Ein Außenseiter ist ein POKéMON,\n"
	.string "das man in einem Tausch erhält.\p"
	.string "Es entwickelt sich rasch, doch im\n"
	.string "Kampf kann es vorkommen, dass es\l"
	.string "unerfahrenen TRAINERn nicht\l"
	.string "gehorcht!\p"
	.string "Wenn wir doch nur ein paar ORDEN\n"
	.string "hätten...$"

