PewterCity_House1_Text_Nidoran_IT::
    .string "NIDORAN♂: Nidoor!$"

PewterCity_House1_Text_NidoranSit_IT::
    .string "NIDORAN, cuccia!$"

PewterCity_House1_Text_TradeMonsAreFinicky_IT::
    .string "Questo è un POKéMON acquisito ed\n"
    .string "è difficile da trattare.\p"
    .string "Acquisito è un POKéMON scambiato\n"
    .string "con un altro giocatore.\p"
    .string "Cresce in fretta, ma a volte ignora\n"
    .string "gli ALLENATORI inesperti!\p"
    .string "Se solo avessimo delle MEDAGLIE!$"

