Route13_Text_SebastianIntro_IT::
    .string "I miei POKéMON uccello vogliono\n"
    .string "divertirsi!$"

Route13_Text_SebastianDefeat_IT::
    .string "I miei prodi hanno perso?$"

Route13_Text_SebastianPostBattle_IT::
    .string "I miei POKéMON sono felici anche se\n"
    .string "hanno perso.$"

Route13_Text_SusieIntro_IT::
    .string "Dicono che sono brava anche se\n"
    .string "sono una bambina!$"

Route13_Text_SusieDefeat_IT::
    .string "Oh!\n"
    .string "Ho perso!$"

Route13_Text_SusiePostBattle_IT::
    .string "Lavorerò sodo per diventare un\n"
    .string "buon ALLENATORE.$"

Route13_Text_ValerieIntro_IT::
    .string "Che belle MEDAGLIE che hai!$"

Route13_Text_ValerieDefeat_IT::
    .string "Non mi sono impegnata abbastanza!$"

Route13_Text_ValeriePostBattle_IT::
    .string "Te le hanno date i CAPOPALESTRA\n"
    .string "quelle MEDAGLIE, lo so!$"

Route13_Text_GwenIntro_IT::
    .string "I miei cari POKéMON vogliono\n"
    .string "rivederti.$"

Route13_Text_GwenDefeat_IT::
    .string "Mi hai annientato!$"

Route13_Text_GwenPostBattle_IT::
    .string "Bisogna fare lottare i POKéMON per\n"
    .string "rafforzarli!$"

Route13_Text_AlmaIntro_IT::
    .string "Ho trovato del CARBURANTE in una\n"
    .string "grotta!$"

Route13_Text_AlmaDefeat_IT::
    .string "Ho fatto confusione!$"

Route13_Text_AlmaPostBattle_IT::
    .string "Il CARBURANTE ha aumentato la\n"
    .string "VELOCITÀ dei miei POKéMON.$"

Route13_Text_PerryIntro_IT::
    .string "Ho il vento a favore!$"

Route13_Text_PerryDefeat_IT::
    .string "È cambiato il vento!$"

Route13_Text_PerryPostBattle_IT::
    .string "Ho perso.\n"
    .string "Me ne VOLO a casa.$"

Route13_Text_LolaIntro_IT::
    .string "Certo che giocherò con te!$"

Route13_Text_LolaDefeat_IT::
    .string "Essere spregevole!$"

Route13_Text_LolaPostBattle_IT::
    .string "Sono più forti i POKéMON maschio o\n"
    .string "femmina?$"

Route13_Text_SheilaIntro_IT::
    .string "Vuoi giocare a POKéMON con me?$"

Route13_Text_SheilaDefeat_IT::
    .string "È già finito?$"

Route13_Text_SheilaPostBattle_IT::
    .string "Non so nulla dei POKéMON!\p"
    .string "Li scelgo solo in base alla\n"
    .string "bellezza!$"

Route13_Text_JaredIntro_IT::
    .string "Cosa stai guardando?$"

Route13_Text_JaredDefeat_IT::
    .string "Ho sbagliato tutto!$"

Route13_Text_JaredPostBattle_IT::
    .string "Sparisci!$"

Route13_Text_RobertIntro_IT::
    .string "Tengo i POKéMON uccello sempre con\n"
    .string "me!$"

Route13_Text_RobertDefeat_IT::
    .string "Ho le pile scariche!$"

Route13_Text_RobertPostBattle_IT::
    .string "Oh! Se solo potessi volare\n"
    .string "come PIDGEY e PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost_IT::
    .string "CONSIGLI UTILI\p"
    .string "Guarda a sinistra del cartello!$"

Route13_Text_SelectToSwitchItems_IT::
    .string "CONSIGLI UTILI\p"
    .string "Usa SELECT per spostare\n"
    .string "gli strumenti nelle liste.$"

Route13_Text_RouteSign_IT::
    .string "PERCORSO 13\n"
    .string "PONTE SILENZIO a nord$"

