Route13_Text_SebastianIntro_ES::
    .string "¡Mis pájaros POKéMON quieren\n"
    .string "pelear!$"

Route13_Text_SebastianDefeat_ES::
    .string "¿Perdió mi combinación de pájaros?$"

Route13_Text_SebastianPostBattle_ES::
    .string "Mis POKéMON parecen felices\n"
    .string "aunque hayan perdido.$"

Route13_Text_SusieIntro_ES::
    .string "¡Dicen que soy muy buena\n"
    .string "para ser tan pequeña!$"

Route13_Text_SusieDefeat_ES::
    .string "¡Oh!\n"
    .string "¡He perdido!$"

Route13_Text_SusiePostBattle_ES::
    .string "Quiero ser una gran ENTRENADORA.\n"
    .string "Voy a entrenarme mucho.$"

Route13_Text_ValerieIntro_ES::
    .string "¡Qué chulas son tus MEDALLAS!$"

Route13_Text_ValerieDefeat_ES::
    .string "¡No he estado a la altura!$"

Route13_Text_ValeriePostBattle_ES::
    .string "¡Sé que lograste esas MEDALLAS\n"
    .string "de los LÍDERES del GIMNASIO!$"

Route13_Text_GwenIntro_ES::
    .string "Mis simpáticos POKéMON quieren\n"
    .string "conocerte.$"

Route13_Text_GwenDefeat_ES::
    .string "¡Uauu!\n"
    .string "¡Me has machacado!$"

Route13_Text_GwenPostBattle_ES::
    .string "¡Tienes que hacer luchar a tus\n"
    .string "POKéMON para fortalecerlos!$"

Route13_Text_AlmaIntro_ES::
    .string "¡Una vez encontré CARBURANTE\n"
    .string "en una cueva!$"

Route13_Text_AlmaDefeat_ES::
    .string "¡Lo he hecho fatal!$"

Route13_Text_AlmaPostBattle_ES::
    .string "El CARBURANTE aumentó la\n"
    .string "VELOCIDAD de mis POKéMON.$"

Route13_Text_PerryIntro_ES::
    .string "No voy a perder.\n"
    .string "¡El viento sopla en mi dirección!$"

Route13_Text_PerryDefeat_ES::
    .string "¡El viento ha cambiado!$"

Route13_Text_PerryPostBattle_ES::
    .string "He perdido. Creo que usaré\n"
    .string "VOLAR para ir a casa.$"

Route13_Text_LolaIntro_ES::
    .string "¡Claro que jugaré contigo!$"

Route13_Text_LolaDefeat_ES::
    .string "¡Oh!\n"
    .string "¡Qué salvaje eres!$"

Route13_Text_LolaPostBattle_ES::
    .string "¿Cuál es más fuerte, un POKéMON\n"
    .string "macho o hembra?$"

Route13_Text_SheilaIntro_ES::
    .string "¿Quieres jugar conmigo\n"
    .string "a POKéMON?$"

Route13_Text_SheilaDefeat_ES::
    .string "¿Ya se ha terminado?$"

Route13_Text_SheilaPostBattle_ES::
    .string "¡No sé nada sobre los POKéMON!\n"
    .string "¡Me gustan los más chulos!$"

Route13_Text_JaredIntro_ES::
    .string "¿Y tú qué miras?$"

Route13_Text_JaredDefeat_ES::
    .string "¡Vaya!\n"
    .string "¡Qué patinazo!$"

Route13_Text_JaredPostBattle_ES::
    .string "¡Olvídame!$"

Route13_Text_RobertIntro_ES::
    .string "¡Me encantan los pájaros POKéMON!$"

Route13_Text_RobertDefeat_ES::
    .string "¡Me he quedado sin energía!$"

Route13_Text_RobertPostBattle_ES::
    .string "Ojalá pudiera volar como PIDGEY\n"
    .string "y PIDGEOTTO...$"

Route13_Text_LookToLeftOfThatPost_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Mira a la izquierda de ese poste!$"

Route13_Text_SelectToSwitchItems_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Usa SELECT para cambiar objetos\n"
    .string "en la ventana OBJETOS!$"

Route13_Text_RouteSign_ES::
    .string "RUTA 13:\n"
    .string "PUENTE SILENCIO, al norte$"
