Route13_Text_SebastianIntro_FR::
	.string "Mes POKéMON oiseau cherchent la\n"
	.string "baston!$"

Route13_Text_SebastianDefeat_FR::
	.string "Tu m'as volé dans les plumes!$"

Route13_Text_SebastianPostBattle_FR::
	.string "Mes POKéMON ont l'air contents,\n"
	.string "même s'ils ont perdu.$"

Route13_Text_SusieIntro_FR::
	.string "Pas mal pour une fille, hein?$"

Route13_Text_SusieDefeat_FR::
	.string "Oh!\n"
	.string "Perdu!$"

Route13_Text_SusiePostBattle_FR::
	.string "Je veux être un bon DRESSEUR.\n"
	.string "Je travaille dur.$"

Route13_Text_ValerieIntro_FR::
	.string "Woaa!\n"
	.string "Tes BADGES sont trop cool!$"

Route13_Text_ValerieDefeat_FR::
	.string "…\n"
	.string "J'en ai assez!$"

Route13_Text_ValeriePostBattle_FR::
	.string "Tu as gagné ces BADGES chez les\n"
	.string "CHAMPIONS!$"

Route13_Text_GwenIntro_FR::
	.string "Mes POKéMON tout mignons veulent\n"
	.string "te connaître.$"

Route13_Text_GwenDefeat_FR::
	.string "Wow!\n"
	.string "J'suis morte!$"

Route13_Text_GwenPostBattle_FR::
	.string "Tu dois faire combattre tes\n"
	.string "POKéMON pour les entraîner!$"

Route13_Text_AlmaIntro_FR::
	.string "J'ai trouvé du CARBONE dans une\n"
	.string "grotte en faisant de la spéléo.$"

Route13_Text_AlmaDefeat_FR::
	.string "J'ai tout raté!$"

Route13_Text_AlmaPostBattle_FR::
	.string "Le CARBONE a augmenté la vitesse\n"
	.string "de mon POKéMON.$"

Route13_Text_PerryIntro_FR::
	.string "Le vent souffle par là. Cool!$"

Route13_Text_PerryDefeat_FR::
	.string "Le vent a tourné!$"

Route13_Text_PerryPostBattle_FR::
	.string "J'ai perdu.\n"
	.string "Je rentre chez moi avec VOL.$"

Route13_Text_LolaIntro_FR::
	.string "Tu veux te mesurer à moi?$"

Route13_Text_LolaDefeat_FR::
	.string "Oh!\n"
	.string "Sale teigne!$"

Route13_Text_LolaPostBattle_FR::
	.string "C'est quoi le plus fort, un POKéMON\n"
	.string "mâle ou femelle?$"

Route13_Text_SheilaIntro_FR::
	.string "Et si on se battait?$"

Route13_Text_SheilaDefeat_FR::
	.string "Fini?\n"
	.string "Déjà?$"

Route13_Text_SheilaPostBattle_FR::
	.string "J'y connais rien aux POKéMON!\n"
	.string "Je les trouve juste cool!$"

Route13_Text_JaredIntro_FR::
	.string "Qu'est-ce que tu regardes, toi!?$"

Route13_Text_JaredDefeat_FR::
	.string "Zipp!\n"
	.string "J'ai glissé!$"

Route13_Text_JaredPostBattle_FR::
	.string "Du balai!$"

Route13_Text_RobertIntro_FR::
	.string "J'aime bien mes POKéMON oiseau!\n"
	.string "Je leur consacre tout mon temps.$"

Route13_Text_RobertDefeat_FR::
	.string "Oh!\n"
	.string "Ma cage!$"

Route13_Text_RobertPostBattle_FR::
	.string "J'aimerais voler comme ROUCOOL ou\n"
	.string "ROUCOUPS…$"

Route13_Text_LookToLeftOfThatPost_FR::
	.string "ASTUCE\p"
	.string "Regardez à gauche!$"

Route13_Text_SelectToSwitchItems_FR::
	.string "ASTUCE\p"
	.string "Utilisez SELECT pour organiser\n"
	.string "votre inventaire!$"

Route13_Text_RouteSign_FR::
	.string "ROUTE 13\n"
	.string "PONT DU SILENCE au Nord$"

