VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild_ES::
    .string "Aunque sean del mismo nivel, los\n"
    .string "POKéMON pueden tener diferentes\l"
    .string "habilidades.\p"
    .string "Un POKéMON entrenado es más fuerte\n"
    .string "que uno salvaje.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking_ES::
    .string "¡Mi POKéMON fue envenenado y\n"
    .string "se debilitó mientras caminábamos!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes_ES::
    .string "Es cierto que un POKéMON de un\n"
    .string "nivel superior es más fuerte.\p"
    .string "Pero todos los POKéMON son\n"
    .string "vulnerables ante ciertos tipos.\p"
    .string "Es decir, que no hay POKéMON\n"
    .string "invulnerables.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain_ES::
    .string "Esa necesidad de luchar de nuevo\n"
    .string "con gente a la que ya te has\l"
    .string "enfrentado...\p"
    .string "¿Sabes a lo que me refiero?\n"
    .string "Seguro que la has sentido alguna\l"
    .string "vez.\p"
    .string "Yo quería luchar una y otra vez\n"
    .string "con mis antiguos rivales.\p"
    .string "Y me dieron esto.\n"
    .string "¡Toma uno para ti!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches_ES::
    .string "Usa este dispositivo para ver qué\n"
    .string "ENTRENADOR quiere luchar de\l"
    .string "nuevo contigo.\p"
    .string "Ten en cuenta que debes cargar\n"
    .string "la batería.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker_ES::
    .string "¿Que cómo se usa el BUSCAPELEA?\n"
    .string "No tiene mayor misterio.\p"
    .string "Al usarlo, emitirá un ruidito que\n"
    .string "alertará a los ENTRENADORES\l"
    .string "que haya por la zona.\p"
    .string "Si alguno quisiera luchar otra\n"
    .string "vez contigo, te lo hará saber\l"
    .string "de inmediato.\p"
    .string "Carga la batería y úsalo cuando\n"
    .string "vayas por ahí.$"
