VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild_IT::
    .string "Anche se di pari livello, i POKéMON\n"
    .string "possono avere abilità diverse.\p"
    .string "Un POKéMON addomesticato è più\n"
    .string "forte di uno selvatico.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking_IT::
    .string "Il mio POKéMON avvelenato è\n"
    .string "svenuto mentre camminavamo!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes_IT::
    .string "È vero che un POKéMON di un\n"
    .string "livello superiore è più forte…\p"
    .string "…però, a parità di livello,\n"
    .string "ci sono POKéMON più forti contro\l"
    .string "certi tipi e deboli contro altri.\p"
    .string "Dunque, non ci sono POKéMON\n"
    .string "invulnerabili.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain_IT::
    .string "Non hai mai avuto il desiderio\n"
    .string "bruciante di lottare di nuovo con\l"
    .string "un ALLENATORE già incontrato?\p"
    .string "Io sì, molto spesso.\p"
    .string "Così, ho creato questi apparecchi:\n"
    .string "prendine uno!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches_IT::
    .string "Con questo, puoi trovare gli\n"
    .string "ALLENATORI che vogliono una\l"
    .string "rivincita.\p"
    .string "Per usarlo, però, devi ricaricarne\n"
    .string "le batterie.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker_IT::
    .string "Continui ad usare il CERCASFIDE?\p"
    .string "Caricane le batterie e usalo mentre\n"
    .string "vai in giro.\p"
    .string "Appena rileva un ALLENATORE che\n"
    .string "vuole una rivincita, ti avverte!$"

