ViridianCity_Text_CanCarryMonsAnywhere_IT::
    .string "Nella cintura hai delle POKé BALL!\n"
    .string "Ci tieni i POKéMON, vero?\p"
    .string "È una gran cosa poter portare i\n"
    .string "POKéMON ovunque!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs_IT::
    .string "Questa PALESTRA POKéMON è sempre\n"
    .string "chiusa.\p"
    .string "Mi domando chi ne sia il CAPO.$"

ViridianCity_Text_ViridiansGymLeaderReturned_IT::
    .string "È tornato il CAPOPALESTRA di\n"
    .string "SMERALDOPOLI!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons_IT::
    .string "Vuoi informazioni sulle due specie\n"
    .string "di POKéMON simili a bruchi?$"

ViridianCity_Text_OhOkayThen_IT::
    .string "Oh, va bene!$"

ViridianCity_Text_ExplainCaterpieWeedle_IT::
    .string "CATERPIE non ha veleno, WEEDLE\n"
    .string "però sì!\p"
    .string "Attenzione alla sua VELENOSPINA!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet_IT::
    .string "Oh nonno!\n"
    .string "Non essere sgarbato!\p"
    .string "Scusalo, sai!\n"
    .string "Non ha ancora preso il caffè!$"

ViridianCity_Text_GoShoppingInPewterOccasionally_IT::
    .string "Spesso vado a fare spese a\n"
    .string "PLUMBEOPOLI.\p"
    .string "Percorro il tortuoso sentiero del\n"
    .string "BOSCO SMERALDO!$"

ViridianCity_Text_ThisIsPrivateProperty_IT::
    .string "Non puoi passare da qui!\p"
    .string "È proprietà privata!$"

ViridianCity_Text_ShowYouHowToCatchMons_IT::
    .string "Oh! Dopo il caffè mi sento meglio!\p"
    .string "Ehi, cos'è quella scatolina rossa?\p"
    .string "Ah, hai un POKéDEX.\p"
    .string "Beh, allora voglio darti una\n"
    .string "dritta.\p"
    .string "Tutte le volte che catturi un\n"
    .string "POKéMON, il POKéDEX viene\l"
    .string "aggiornato automaticamente.\p"
    .string "Ma se non sai come si cattura un\n"
    .string "POKéMON…\p"
    .string "…allora dovrei iniziare\n"
    .string "da lì…$"

ViridianCity_Text_ThatWasEducationalTakeThis_IT::
    .string "Ti sono serviti i miei consigli?\p"
    .string "Allora ti do qualcosa che potrà\n"
    .string "esserti molto utile.$"

ViridianCity_Text_WatchThatToLearnBasics_IT::
    .string "Si chiama POKéTIVÙ.\p"
    .string "È una sorta di guida filmata per\n"
    .string "gli ALLENATORI di POKéMON.$"

ViridianCity_Text_WeakenMonsFirstToCatch_IT::
    .string "Oh! Dopo il caffè mi sento meglio!\p"
    .string "Ma l'ho fatto troppo forte: mi è\n"
    .string "venuto il mal di testa!\p"
    .string "Stai lavorando al completamento\n"
    .string "del POKéDEX?\p"
    .string "Prima di cercare di catturare un\n"
    .string "POKéMON, cerca di indebolirlo.$"

ViridianCity_Text_HowsTeachyTVHelping_IT::
    .string "Oh! Dopo il caffè mi sento meglio!\p"
    .string "Ma l'ho fatto troppo forte: mi è\n"
    .string "venuto il mal di testa!\p"
    .string "Stai usando la mia POKéTIVÙ?\n"
    .string "Ti sta tornando utile?$"

ViridianCity_Text_MyGrandsonOnTheShow_IT::
    .string "Il ragazzo nel video è mio nipote.\p"
    .string "Per questo mi fa così piacere che\n"
    .string "tu usi la POKéTIVÙ!$"

ViridianCity_Text_TooBusyForTeachyTV_IT::
    .string "Non mi dire che non hai tempo\n"
    .string "di usare la POKéTIVÙ?!\p"
    .string "Vedi di trovarlo, il tempo!\n"
    .string "Altrimenti, cosa te l'ho regalata\l"
    .string "a fare?$"

ViridianCity_Text_CitySign_IT::
    .string "SMERALDOPOLI\n"
    .string "Eterno paradiso verde$"

ViridianCity_Text_CatchMonsForEasierBattles_IT::
    .string "CONSIGLI UTILI\p"
    .string "Cattura i POKéMON e amplia la tua\n"
    .string "collezione!\p"
    .string "Più ne hai, più facile sarà\n"
    .string "combattere!$"

ViridianCity_Text_MovesLimitedByPP_IT::
    .string "CONSIGLI UTILI\p"
    .string "Le mosse dei POKéMON dipendono dai\n"
    .string "loro PUNTI POTENZA: PP.\p"
    .string "Per recuperare PP fai riposare i\n"
    .string "tuoi POKéMON al CENTRO POKéMON!$"

ViridianCity_Text_GymSign_IT::
    .string "PALESTRA POKéMON di SMERALDOPOLI$"

ViridianCity_Text_GymDoorsAreLocked_IT::
    .string "Le porte della PALESTRA sono\n"
    .string "chiuse…$"

