@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach_DE::
	.string "Fertig?\n"
	.string "Boing!\p"
	.string "Wir tragen einen BODYSLAM-Kampf\n"
	.string "aus, um herauszufinden, wer als\l"
	.string "Erster umfällt.\l"
	.string "Wenn du mitmachst, wirst du\l"
	.string "allerdings wie ein Käfer\l"
	.string "zerquetscht…\l"
	.string "Soll ich BODYSLAM einem deiner\l"
	.string "POKéMON beibringen?$"

Text_BodySlamDeclined_DE::
	.string "Komme wieder!\n"
	.string "Boing!$"

Text_BodySlamWhichMon_DE::
	.string "Welches POKéMON soll\n"
	.string "BODYSLAM erlernen?$"

Text_BodySlamTaught_DE::
	.string "Hoho!$"

FourIsland_House1_Text_FatMan_DE::
	.string "それ　ぼよーん！\n"
	.string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave_DE::
	.string "Dort gibt es eine seltene Art\n"
	.string "EIS-POKéMON in der Höhle.\p"
	.string "Viele Besucher kommen nur,\n"
	.string "um dieses POKéMON zu sehen.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore_DE::
	.string "Oh! Ein POKéMON-EI?\n"
	.string "… ich habe keine Ahnung!\p"
	.string "… oh, Moment, in der\n"
	.string "PENSION habe ich etwas darüber\l"
	.string "gehört.\l"
	.string "Sie sagten, sie haben früher\l"
	.string "schon EIER auf ihrem\l"
	.string "Grundstück gefunden!$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived_DE::
	.string "Was ist los?\p"
	.string "Die letzte Ausgabe vom POKéMON\n"
	.string "JOURNAL ist noch nicht auf dieser\l"
	.string "Insel angekommen?$"

