@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach_FR::
	.string "Prêts?\n"
	.string "Go!\p"
	.string "On fait un concours de PLAQUAGE.\p"
	.string "Si tu veux essayer, tu vas te faire\n"
	.string "écraser comme un insecte!\p"
	.string "Et si j'apprenais plutôt cette\n"
	.string "capacité à un de tes POKéMON?$"

Text_BodySlamDeclined_FR::
	.string "Allez!\n"
	.string "Go!$"

Text_BodySlamWhichMon_FR::
	.string "A quel POKéMON vais-je\n"
	.string "enseigner PLAQUAGE?$"

Text_BodySlamTaught_FR::
	.string "Whoua!$"

FourIsland_House1_Text_FatMan_FR::
	.string "それ　ぼよーん！\n"
	.string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave_FR::
	.string "Il y a un POKéMON GLACE très\n"
	.string "rare qui vit dans cette grotte.\p"
	.string "Y'a plein de monde qui vient ici\n"
	.string "en espérant le voir.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore_FR::
	.string "Oh? Un OEUF POKéMON?\n"
	.string "… Aucune idée.\p"
	.string "Oh, attends, il me semble que les\n"
	.string "gens de la PENSION en parlaient.\p"
	.string "Ils disaient en avoir déjà eu\n"
	.string "chez eux.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived_FR::
	.string "Quoi?\p"
	.string "Le nouveau JOURNAL POKéMON\n"
	.string "n'est pas encore arrivé sur l'île?$"

