@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach_ES::
    .string "¿Ya?\n"
    .string "¡Toma!\p"
    .string "Estamos usando GOLPE CUERPO para\n"
    .string "ver quién machaca antes a quién.\p"
    .string "Si te metieras en la pelea, no\n"
    .string "tendrías nada que hacer...\p"
    .string "¿Quieres que le enseñe GOLPE\n"
    .string "CUERPO a alguno de tus POKéMON?$"

Text_BodySlamDeclined_ES::
    .string "¡Venga, otra vez!\n"
    .string "¡Toma!$"

Text_BodySlamWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe GOLPE CUERPO?$"

Text_BodySlamTaught_ES::
    .string "¡Uauuu!$"

FourIsland_House1_Text_FatMan_ES::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave_ES::
    .string "En la CUEVA GLACIADA hay un\n"
    .string "POKéMON raro del tipo HIELO.\p"
    .string "Aquí viene mucha gente para\n"
    .string "verlo.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore_ES::
    .string "¿Cómo? ¿Un HUEVO POKéMON?\n"
    .string "Ni idea...\p"
    .string "Eh..., sí, espera, los ENCARGADOS\n"
    .string "de la GUARDERÍA comentaron algo\l"
    .string "sobre eso.\p"
    .string "Dijeron que habían encontrado\n"
    .string "HUEVOS en la propia GUARDERÍA.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived_ES::
    .string "¡Pero bueno!\p"
    .string "¿Que aún no ha llegado el nuevo\n"
    .string "DIARIO POKéMON a esta isla?$"
