CeruleanCity_House4_Text_NothingEntertaining_FR::
	.string "… Aaah…\n"
	.string "Tellement de temps et rien à faire…\p"
	.string "Y'aurait pas un truc amusant à\n"
	.string "faire dans le coin?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis_FR::
	.string "Ah!\n"
	.string "C'est l'heure des infos!\p"
	.string "Hmm…\n"
	.string "Je vois. C'était très intéressant.\p"
	.string "Et bravo pour t'intéresser aux\n"
	.string "infos à ton âge.\p"
	.string "Pour te remercier, je voudrais\n"
	.string "te donner ceci.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries_FR::
	.string "Oh oh!\n"
	.string "Des nouvelles fraîches!\p"
	.string "Hm…\p"
	.string "Incroyable, pour des nouvelles,\n"
	.string "ça c'est des nouvelles!\p"
	.string "J'avais pas entendu quelque\n"
	.string "chose comme ça depuis des lustres!\p"
	.string "Tiens, prends ces BAIES en\n"
	.string "remerciement!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers_FR::
	.string "Cette nouvelle est trop incroyable\n"
	.string "pour la garder pour nous…\p"
	.string "Je voudrais la raconter à tout le\n"
	.string "monde…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis_FR::
	.string "Tu as fait suivre l'info pour moi?\p"
	.string "L'important avec l'information, c'est\n"
	.string "de la partager.\p"
	.string "En remerciement, je voudrais te\n"
	.string "donner ceci.$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries_FR::
	.string "Tu as encore fait suivre\n"
	.string "l'information? Formidable!\p"
	.string "Il faut que le plus de monde\n"
	.string "possible soit au courant.\p"
	.string "Tu sais quoi?\p"
	.string "Pour te remercier, je vais te\n"
	.string "donner encore plus de BAIES.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews_FR::
	.string "Avec toutes ces nouvelles,\n"
	.string "je risque plus de m'ennuyer!$"

CeruleanCity_House4_Text_YourBerryPouchIsFull_FR::
	.string "Hmm? Ta POCHE A BAIES est pleine.\n"
	.string "Dommage pour le cadeau alors.$"

