CeruleanCity_House4_Text_NothingEntertaining_ES::
    .string "Uff... Tengo tanto tiempo\n"
    .string "y tan poco que hacer...\p"
    .string "¿No hay nada divertido cociéndose\n"
    .string "por ahí?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis_ES::
    .string "¡Anda, hay novedades!\n"
    .string "¡Un boletín informativo!\p"
    .string "A ver, a ver...\p"
    .string "¡Interesante!\n"
    .string "¡Interesantísimo!\p"
    .string "Muy bien, me encanta que la gente\n"
    .string "joven como tú se interese por las\l"
    .string "noticias.\p"
    .string "Quiero agradecerte el haberme\n"
    .string "traído estas noticias, toma.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries_ES::
    .string "¡Por fin!\n"
    .string "¡Un boletín informativo!\p"
    .string "A ver, a ver...\p"
    .string "¡Maravilloso!\n"
    .string "¡Maravillosísimo!\p"
    .string "Hacía tiempo que no leía nada\n"
    .string "igual.\p"
    .string "Gracias por traerme semejantes\n"
    .string "noticias, toma, unas BAYITAS.$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers_ES::
    .string "Sería una pena no compartir estas\n"
    .string "noticias...\p"
    .string "Me encantaría poder pasárselas\n"
    .string "a alguien...\l"
    .string "Compártelas con más gente...$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis_ES::
    .string "¿Has pasado las noticias\n"
    .string "a más gente?\p"
    .string "¡Las buenas noticias hay que\n"
    .string "compartirlas con quien se pueda!\p"
    .string "Gracias por pasárselas a otras\n"
    .string "personas, toma, anda.$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries_ES::
    .string "¿Has pasado las noticias\n"
    .string "a más gente todavía?\p"
    .string "¡Las propias noticias deben\n"
    .string "de estar encantadas de la vida!\p"
    .string "¡Lo que yo te diga!\p"
    .string "¡En mi nombre y en nombre\n"
    .string "de las propias noticias, toma!\p"
    .string "¡Voy a darte más BAYITAS\n"
    .string "que de costumbre!$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews_ES::
    .string "Yo me lo paso pipa leyendo\n"
    .string "noticias. Todas me gustan, todas.\p"
    .string "¡Ya estoy contento! ¡Voy a estar\n"
    .string "entretenido para rato!$"

CeruleanCity_House4_Text_YourBerryPouchIsFull_ES::
    .string "Vaya, tienes el SACO de las BAYAS\n"
    .string "hasta arriba. Vuelve a por ellas\l"
    .string "cuando tengas sitio.$"
