CeruleanCity_House4_Text_NothingEntertaining_DE::
	.string "Seufz…\n"
	.string "Zu viel Zeit und zu wenig zu tun…\p"
	.string "Passiert nirgendwo etwas, das mich\n"
	.string "unterhalten könnte?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis_DE::
	.string "Ah!\n"
	.string "Eine Nachrichtensendung!\p"
	.string "Hm…\p"
	.string "Ich verstehe!\n"
	.string "Das war sehr informativ!\p"
	.string "Ich freue mich, dass selbst junge\n"
	.string "Menschen wie du ein Interesse\l"
	.string "an Nachrichten zeigen.\l"
	.string "Als Zeichen meines Dankes möchte\l"
	.string "ich dir dies geben!$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries_DE::
	.string "Oh, oh!\n"
	.string "D-die Nachrichtensendung!\p"
	.string "Hm…\p"
	.string "Aufregend!\n"
	.string "Das sind unglaubliche Neuigkeiten!\p"
	.string "Solch eine unglaubliche Nachricht\n"
	.string "habe ich lange nicht mehr gehört!\p"
	.string "Danke, dass du mit mir diese\n"
	.string "Nachricht geteilt hast. Nimm\l"
	.string "ein paar BEEREN.$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers_DE::
	.string "Es ist so traurig, diese Nachricht\n"
	.string "nicht mit anderen zu teilen…\p"
	.string "Ich wünschte, ich könnte jemandem\n"
	.string "davon erzählen…\l"
	.string "Erzähl du den anderen davon…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis_DE::
	.string "Ah, du hast den anderen die\n"
	.string "Nachricht für mich übermittelt?\p"
	.string "Es lohnt sich, gute Nachrichten mit\n"
	.string "anderen Menschen zu teilen.\p"
	.string "Als Zeichen meines Dankes möchte\n"
	.string "ich dir dies geben!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries_DE::
	.string "Du hast die Nachricht noch weiter\n"
	.string "verbreitet? Wunderbar!\p"
	.string "Es wird der Nachricht gefallen,\n"
	.string "wenn sie alle erreicht!\p"
	.string "Ja, wirklich!\p"
	.string "Die Nachricht und ich wissen\n"
	.string "das zu schätzen und möchten dir\l"
	.string "mehr BEEREN als sonst geben.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews_DE::
	.string "Ich amüsiere mich mit allen Arten\n"
	.string "von Neuigkeiten.\p"
	.string "Ja, ich bin zufrieden!\n"
	.string "Ich werde mich eine Zeit lang nicht\l"
	.string "langweilen!$"

CeruleanCity_House4_Text_YourBerryPouchIsFull_DE::
	.string "Hm? Deine BEERENTÜTE ist voll.\n"
	.string "Mein Geschenk kommt nicht an!$"

