PokemonLeague_AgathasRoom_Text_Intro_ES::
    .string "¡Yo soy AGATHA, del ALTO MANDO!\p"
    .string "He oído que OAK te tiene\n"
    .string "mucha admiración, criatura.\p"
    .string "Ese carcamal era fuerte y guapote,\n"
    .string "pero ya hace mucho de eso.\p"
    .string "Han pasado muchos años, sí.\n"
    .string "Es la sombra de lo que fue.\p"
    .string "¡Ahora sólo juguetea con su\n"
    .string "POKéDEX! ¡Pero está equivocado!\l"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Yo te enseñaré cómo\n"
    .string "lucha un gran ENTRENADOR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro_ES::
    .string "¡Yo soy AGATHA, del ALTO MANDO!\p"
    .string "He oído que eres el ojito derecho\n"
    .string "de OAK, ¿eh?\p"
    .string "Ese carcamal era fuerte y guapote,\n"
    .string "pero ya hace mucho de eso.\p"
    .string "Han pasado muchos años, sí.\n"
    .string "Es la sombra de lo que fue.\p"
    .string "¡Ahora sólo juguetea con su\n"
    .string "POKéDEX! ¡Pero está equivocado!\l"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Yo te enseñaré cómo\n"
    .string "lucha un gran ENTRENADOR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat_ES::
    .string "¡Oh, oh!\n¡Eres bastante especial!$"

PokemonLeague_AgathasRoom_Text_PostBattle_ES::
    .string "¡Tú ganas!\p"
    .string "¡Ya sé por qué ese viejo\n"
    .string "inútil te aprecia tanto!\p"
    .string "¡No tengo nada más que decir!\n"
    .string "¡Vete ya!$"
