PokemonLeague_AgathasRoom_Text_Intro_FR::
	.string "Je suis AGATHA du CONSEIL 4!\p"
	.string "CHEN mise de grands espoirs\n"
	.string "sur toi!\p"
	.string "Sais-tu que ce vieux machin\n"
	.string "était jadis beau garçon? Enfin…\l"
	.string "Il y a très longtemps!\p"
	.string "Il veut juste frimer avec son\n"
	.string "POKéDEX! Mais c'est stupide! Les\l"
	.string "POKéMON servent à combattre!\p"
	.string "{PLAYER}! Je vais te montrer\n"
	.string "comment les grands DRESSEURS\l"
	.string "combattent!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro_FR::
	.string "Je suis AGATHA du CONSEIL 4!\p"
	.string "Tu es le DRESSEUR que CHEN\n"
	.string "a pris sous son aile, non?\p"
	.string "Sais-tu que ce vieux machin\n"
	.string "était jadis beau garçon? Enfin…\l"
	.string "Il y a très longtemps!\p"
	.string "Il veut juste frimer avec son\n"
	.string "POKéDEX! Mais c'est débile! Les\l"
	.string "POKéMON servent à combattre!\p"
	.string "{PLAYER}! Je vais te montrer\n"
	.string "comment les grands DRESSEURS\l"
	.string "combattent!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat_FR::
	.string "Oh ho!\n"
	.string "Pas mal, tu as du talent!$"

PokemonLeague_AgathasRoom_Text_PostBattle_FR::
	.string "Mmmm…\p"
	.string "Je vois pourquoi le vieux CHEN\n"
	.string "t'apprécie autant!\p"
	.string "Je n'ai rien à ajouter.\n"
	.string "Tu peux passer.$"

