PokemonLeague_AgathasRoom_Text_Intro_IT::
    .string "Sono AGATHA dei SUPERQUATTRO!\p"
    .string "OAK sembra molto interessato a te!\p"
    .string "Molti anni fa quel vecchietto\n"
    .string "era forte e affascinante!\p"
    .string "Ora vuole solo sistemare il suo\n"
    .string "POKéDEX! Ma ha torto!\l"
    .string "I POKéMON devono lottare!\p"
    .string "{PLAYER}! Ti farò vedere io come\n"
    .string "lotta un vero ALLENATORE!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro_IT::
    .string "Sono AGATHA dei SUPERQUATTRO!\p"
    .string "Tu sei {PLAYER}, la persona a cui\n"
    .string "OAK tiene così tanto! Mi ricordo\l"
    .string "di te!\p"
    .string "Molti anni fa quel vecchietto\n"
    .string "era forte e affascinante!\p"
    .string "Ora vuole solo sistemare il suo\n"
    .string "POKéDEX! Ma ha torto!\l"
    .string "I POKéMON devono lottare!\p"
    .string "{PLAYER}! Ti farò vedere io come\n"
    .string "lotta un vero ALLENATORE!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat_IT::
    .string "Oh oh!\n"
    .string "Tu sì che sei davvero speciale!$"

PokemonLeague_AgathasRoom_Text_PostBattle_IT::
    .string "Hai vinto!\p"
    .string "Ora capisco cosa ha visto in te\n"
    .string "quel vecchietto!\p"
    .string "Non ho altro da dirti!\n"
    .string "Vai avanti ora, e continua così!$"

