PokemonLeague_AgathasRoom_Text_Intro_DE::
	.string "Ich bin AGATHE aus dem Team der\n"
	.string "TOP VIER!\p"
	.string "Ich habe gehört, dass sich\n"
	.string "EICH sehr für dich interessiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.\p"
	.string "Heute kümmert er sich nur noch um\n"
	.string "seinen POKéDEX! Aber POKéMON\l"
	.string "wollen ja kämpfen!\p"
	.string "{PLAYER}! Ich zeige dir, wie ein\n"
	.string "richtiger TRAINER kämpft!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro_DE::
	.string "Ich bin AGATHE aus dem Team der\n"
	.string "TOP VIER!\p"
	.string "Ich habe gehört, dass EICH\n"
	.string "dich protegiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.\p"
	.string "Heute kümmert er sich nur noch um\n"
	.string "seinen POKéDEX! Aber POKéMON\l"
	.string "wollen ja kämpfen!\p"
	.string "{PLAYER}! Ich zeige dir, wie ein\n"
	.string "richtiger TRAINER kämpft!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat_DE::
	.string "Wirklich!\n"
	.string "Du bist ein ganz besonderes Kind!$"

PokemonLeague_AgathasRoom_Text_PostBattle_DE::
	.string "Du hast gewonnen!\p"
	.string "Nun verstehe ich, was der Professor\n"
	.string "meinte...\p"
	.string "Ich stimme ihm voll und ganz zu!\n"
	.string "Setze deinen Weg fort!$"

