VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon_ES::
    .string "¡Hola! ¿Tienes un {STR_VAR_1}?\p"
    .string "¿Quieres cambiarlo por\n"
    .string "mi {STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad_ES::
    .string "¡Qué pena!$"

VermilionCity_House2_Text_ThisIsNoMon_ES::
    .string "Éste no es un {STR_VAR_1}.\p"
    .string "¡Si consigues uno, cámbiamelo!$"

VermilionCity_House2_Text_ThankYou_ES::
    .string "¡Gracias!$"

VermilionCity_House2_Text_HowIsMyOldMon_ES::
    .string "¿Cómo está mi viejo {STR_VAR_2}?\p"
    .string "¡Mi {STR_VAR_1} está fenomenal!$"
