VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon_DE::
	.string "Besitzt du ein {STR_VAR_1}?\p"
	.string "Willst du es gegen {STR_VAR_2}\n"
	.string "tauschen?$"

VermilionCity_House2_Text_ThatsTooBad_DE::
	.string "Schade!$"

VermilionCity_House2_Text_ThisIsNoMon_DE::
	.string "Das ist kein {STR_VAR_1}!\p"
	.string "Komm wieder, wenn du eines besitzt!$"

VermilionCity_House2_Text_ThankYou_DE::
	.string "Vielen Dank!$"

VermilionCity_House2_Text_HowIsMyOldMon_DE::
	.string "Wie geht es {STR_VAR_2}?\p"
	.string "Mein {STR_VAR_1} fühlt sich super!$"

