VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon_IT::
    .string "Ciao!\n"
    .string "Hai {STR_VAR_1}?\p"
    .string "Vuoi scambiarlo con {STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad_IT::
    .string "Che sfortuna!$"

VermilionCity_House2_Text_ThisIsNoMon_IT::
    .string "Questo non è {STR_VAR_1}.\p"
    .string "Quando ne hai uno, scambialo con\n"
    .string "me!$"

VermilionCity_House2_Text_ThankYou_IT::
    .string "Grazie mille!$"

VermilionCity_House2_Text_HowIsMyOldMon_IT::
    .string "Come sta il mio vecchio\n"
    .string "{STR_VAR_2}?\p"
    .string "Il mio caro {STR_VAR_1} sta\n"
    .string "divinamente!$"

