CeladonCity_Text_GotMyKoffingInCinnabar_ES::
    .string "¡Conseguí a mi KOFFING en\n"
    .string "CIUDAD CANELA!\p"
    .string "¡Es muy simpático, pero echa\n"
    .string "veneno cuando se enfada!$"

CeladonCity_Text_GymIsGreatFullOfWomen_ES::
    .string "¡Jeje! ¡Este GIMNASIO es genial!\n"
    .string "¡Está lleno de chicas!$"

CeladonCity_Text_GameCornerIsBadForCitysImage_ES::
    .string "AZULONA presume de estar bonita\n"
    .string "y cuidada.\p"
    .string "¡El CASINO no es bueno para la\n"
    .string "imagen de nuestra ciudad!$"

CeladonCity_Text_BlewItAllAtSlots_ES::
    .string "¡Ayyy! ¡Lo he perdido todo\n"
    .string "en las tragaperras!\p"
    .string "¡Debería haber cambiado todas\n"
    .string "mis fichas por premios!$"

CeladonCity_Text_MyTrustedPalPoliwrath_ES::
    .string "¡Éste es mi fiel compañero,\n"
    .string "POLIWRATH!\p"
    .string "¡Evolucionó del POLIWHIRL al usar\n"
    .string "la PIEDRA AGUA!$"

CeladonCity_Text_Poliwrath_ES::
    .string "POLIWRATH: ¡Poli, poli!$"

CeladonCity_Text_GetLostOrIllPunchYou_ES::
    .string "¿Qué estás mirando?$"

CeladonCity_Text_KeepOutOfTeamRocketsWay_ES::
    .string "¡No te cruces en el camino del\n"
    .string "TEAM ROCKET!$"

CeladonCity_Text_ExplainXAccuracyDireHit_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡PRECISIÓN X aumenta la precisión\n"
    .string "de los ataques!\p"
    .string "¡El DIRECTO aumenta la posibilidad\n"
    .string "de golpes críticos!\p"
    .string "¡Compra tus objetos en el\n"
    .string "CENTRO COMERCIAL de AZULONA!$"

CeladonCity_Text_CitySign_ES::
    .string "CIUDAD AZULONA\n"
    .string "La ciudad de los sueños de\l"
    .string "arco iris.$"

CeladonCity_Text_GymSign_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\l"
    .string "¡Princesa amante de la Naturaleza!$"

CeladonCity_Text_MansionSign_ES::
    .string "MANSIÓN AZULONA$"

CeladonCity_Text_DeptStoreSign_ES::
    .string "¡Compra lo que necesites en el\n"
    .string "CENTRO COMERCIAL de AZULONA!$"

CeladonCity_Text_GuardSpecProtectsFromStatus_ES::
    .string "PISTAS ENTRENADOR\p"
    .string "¡PROTECCIÓN ESP. protege a tus\n"
    .string "POKéMON de ataques como el agua y\l"
    .string "el fuego!\p"
    .string "¡Compra tus objetos en el CENTRO\n"
    .string "COMERCIAL de AZULONA!$"

CeladonCity_Text_PrizeExchangeSign_ES::
    .string "CAMBIO DE PREMIOS\n"
    .string "¡Se cambian fichas por premios!$"

CeladonCity_Text_GameCornerSign_ES::
    .string "CASINO ROCKET\n"
    .string "¡El parque de los adultos!$"

CeladonCity_Text_ScaldedTongueOnTea_ES::
    .string "¡Aaaagh, ayyyy...!\n"
    .string "¡Me he achicharrado la lengua!\p"
    .string "La ancianita tan agradable que hay\n"
    .string "en la MANSIÓN, me ha dado un TÉ.\p"
    .string "¡Pero está hirviendo!\n"
    .string "Voy a esperar a ver si se enfría...$"

Text_SoftboiledTeach_ES::
    .string "¡Hola!\p"
    .string "¡Te había visto, pero nunca había\n"
    .string "podido hablar contigo!\p"
    .string "Yo creo que ha sido la suerte\n"
    .string "la que nos ha vuelto a reunir.\p"
    .string "Para celebrarlo, me gustaría\n"
    .string "enseñarte AMORTIGUADOR.$"

Text_SoftboiledDeclined_ES::
    .string "Bueno, aquí me tienes para cuando\n"
    .string "te haga falta.$"

Text_SoftboiledWhichMon_ES::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe AMORTIGUADOR?$"

Text_SoftboiledTaught_ES::
    .string "¡Que te vaya muy bien!$"

CeladonCity_Text_SomeoneStoleSilphScope_ES::
    .string "¿Qué voy a hacer ahora?...\p"
    .string "¡Nos han robado el SILPH SCOPE!\p"
    .string "Quien haya sido, vino por aquí.\n"
    .string "De eso no me cabe duda.\p"
    .string "¡Pero no sé por dónde se fue!\n"
    .string "¡No tengo ni idea!$"
