CeladonCity_Text_GotMyKoffingInCinnabar_IT::
    .string "Ho preso KOFFING sull'ISOLA\n"
    .string "CANNELLA.\p"
    .string "È simpaticissimo, ma se s'arrabbia,\n"
    .string "alita veleno!$"

CeladonCity_Text_GymIsGreatFullOfWomen_IT::
    .string "Questa PALESTRA è forte!\n"
    .string "È piena di ragazze!$"

CeladonCity_Text_GameCornerIsBadForCitysImage_IT::
    .string "Il CASINÒ rovina l'immagine della\n"
    .string "nostra città!$"

CeladonCity_Text_BlewItAllAtSlots_IT::
    .string "Ohiohi!\n"
    .string "Ho perso tutto alle slot machine!\p"
    .string "Avrei dovuto cambiare tutti i\n"
    .string "GETTONI in premi!$"

CeladonCity_Text_MyTrustedPalPoliwrath_IT::
    .string "Questo è il mio fedele amico\n"
    .string "POLIWRATH!\p"
    .string "Si è evoluto da POLIWHIRL usando\n"
    .string "la PIETRAIDRICA!$"

CeladonCity_Text_Poliwrath_IT::
    .string "POLIWRATH: Polì polì!$"

CeladonCity_Text_GetLostOrIllPunchYou_IT::
    .string "Cosa stai fissando?$"

CeladonCity_Text_KeepOutOfTeamRocketsWay_IT::
    .string "Tieniti fuori dagli affari di TEAM\n"
    .string "ROCKET!$"

CeladonCity_Text_ExplainXAccuracyDireHit_IT::
    .string "CONSIGLI UTILI\p"
    .string "PRECISIONE X aumenta la precisione\n"
    .string "delle tecniche!\p"
    .string "SUPERCOLPO aumenta la probabilità\n"
    .string "di brutti colpi!\p"
    .string "Fai i tuoi acquisti al CENTRO\n"
    .string "COMMERCIALE di AZZURROPOLI!$"

CeladonCity_Text_CitySign_IT::
    .string "AZZURROPOLI\n"
    .string "Città dei sogni arcobaleno$"

CeladonCity_Text_GymSign_IT::
    .string "CAPOPALESTRA di AZZURROPOLI:\n"
    .string "ERIKA\l"
    .string "La principessa amante della natura!$"

CeladonCity_Text_MansionSign_IT::
    .string "VILLAZZURRA$"

CeladonCity_Text_DeptStoreSign_IT::
    .string "Fai i tuoi acquisti al CENTRO\n"
    .string "COMMERCIALE di AZZURROPOLI!$"

CeladonCity_Text_GuardSpecProtectsFromStatus_IT::
    .string "CONSIGLI UTILI\p"
    .string "SUPERGUARDIA protegge i tuoi\n"
    .string "POKéMON da mosse che causano\l"
    .string "problemi di stato.\p"
    .string "Fai i tuoi acquisti al CENTRO\n"
    .string "COMMERCIALE di AZZURROPOLI!$"

CeladonCity_Text_PrizeExchangeSign_IT::
    .string "Si cambiano i GETTONI in premi!\n"
    .string "RITIRO PREMI$"

CeladonCity_Text_GameCornerSign_IT::
    .string "CASINÒ ROCKET\n"
    .string "Parco Giochi per Esperti!$"

CeladonCity_Text_ScaldedTongueOnTea_IT::
    .string "Aaargh!\n"
    .string "Mi sono scottato la lingua!\p"
    .string "Quest'anziana signora mi ha\n"
    .string "offerto del TÈ.\p"
    .string "Ma era bollente! Avrei dovuto\n"
    .string "aspettare che si raffreddasse!$"

Text_SoftboiledTeach_IT::
    .string "Saaalve!!\p"
    .string "Ci siamo già visti prima, ma non\n"
    .string "ci siamo mai parlati!\p"
    .string "Sono così contento di poter\n"
    .string "conversare con te, che voglio\l"
    .string "farti un regalo!\p"
    .string "Ti do la mossa COVAUOVA, la\n"
    .string "vuoi?$"

Text_SoftboiledDeclined_IT::
    .string "Come vuoi.\n"
    .string "Spero di rincontrarti.\p"
    .string "E se nel frattempo cambi idea,\n"
    .string "la mia offerta è sempre valida.$"

Text_SoftboiledWhichMon_IT::
    .string "Ottimo! A quale POKéMON vuoi che\n"
    .string "insegni COVAUOVA?$"

Text_SoftboiledTaught_IT::
    .string "Beh, in bocca al lupo!$"

CeladonCity_Text_SomeoneStoleSilphScope_IT::
    .string "E adesso, che faccio?!\p"
    .string "Qualcuno mi ha rubato la\n"
    .string "SPETTROSONDA!\p"
    .string "Il ladro veniva da questa\n"
    .string "direzione, l'ho visto bene!\p"
    .string "Ma ho perduto le sue tracce!$"

