CeladonCity_Text_GotMyKoffingInCinnabar_FR::
	.string "J'ai eu mon SMOGO à CRAMOIS'ILE!\p"
	.string "Il est gentil mais il crache du\n"
	.string "poison pour un rien!$"

CeladonCity_Text_GymIsGreatFullOfWomen_FR::
	.string "Héhé! Cette ARENE est terrible!\n"
	.string "Y'a plein de jolies filles!$"

CeladonCity_Text_GameCornerIsBadForCitysImage_FR::
	.string "Nous faisons tout pour que la\n"
	.string "sécurité règne à CELADOPOLE.\p"
	.string "C'est pour ça que ce CASINO n'est\n"
	.string "pas bon pour notre image!$"

CeladonCity_Text_BlewItAllAtSlots_FR::
	.string "Pfff…\n"
	.string "J'ai tout perdu au CASINO!\p"
	.string "J'aurais dû acheter un prix avec\n"
	.string "mes JETONS avant de tout dépenser!$"

CeladonCity_Text_MyTrustedPalPoliwrath_FR::
	.string "C'est mon copain: TARTARD!\p"
	.string "Ce n'était qu'un TETARTE avant\n"
	.string "d'utiliser une PIERRE EAU!$"

CeladonCity_Text_Poliwrath_FR::
	.string "TARTARD: Tarta! Taaaar!$"

CeladonCity_Text_GetLostOrIllPunchYou_FR::
	.string "Kess tu mates?$"

CeladonCity_Text_KeepOutOfTeamRocketsWay_FR::
	.string "Laisse la TEAM tranquille!$"

CeladonCity_Text_ExplainXAccuracyDireHit_FR::
	.string "ASTUCE\p"
	.string "PRECISION + augmente la précision\n"
	.string "des attaques!\p"
	.string "MUSCLE + augmente les chances\n"
	.string "d'effectuer des coups critiques!\p"
	.string "Les meilleurs objets sont en vente\n"
	.string "au CENTRE COMMERCIAL de\l"
	.string "CELADOPOLE!$"

CeladonCity_Text_CitySign_FR::
	.string "CELADOPOLE\n"
	.string "Ville aux rêves arc-en-ciel$"

CeladonCity_Text_GymSign_FR::
	.string "CELADOPOLE ARENE POKéMON\n"
	.string "CHAMPION: ERIKA\l"
	.string "Le combat par les plantes!$"

CeladonCity_Text_MansionSign_FR::
	.string "MANOIR CELADON$"

CeladonCity_Text_DeptStoreSign_FR::
	.string "Au CENTRE COMMERCIAL de\n"
	.string "CELADOPOLE on trouve de tout!$"

CeladonCity_Text_GuardSpecProtectsFromStatus_FR::
	.string "ASTUCE\p"
	.string "DEFENSE SPEC protège les POKéMON\n"
	.string "des changements de statut\l"
	.string "pendant un combat.\p"
	.string "Y'a tout c'qui faut au CENTRE\n"
	.string "COMMERCIAL de CELADOPOLE!$"

CeladonCity_Text_PrizeExchangeSign_FR::
	.string "CHANGE des JETONS contre de\n"
	.string "super prix!$"

CeladonCity_Text_GameCornerSign_FR::
	.string "CASINO ROCKET\n"
	.string "Club de jeu pour adultes!$"

CeladonCity_Text_ScaldedTongueOnTea_FR::
	.string "Aaaah!\n"
	.string "je me suis brûlé la langue!\p"
	.string "La gentille dame de la PENSION\n"
	.string "m'a donné du THE.\p"
	.string "Mais c'était brûlant! J'aurais dû\n"
	.string "souffler un peu dessus avant.$"

Text_SoftboiledTeach_FR::
	.string "Enfin! Depuis le temps que\n"
	.string "je voulais te parler!\p"
	.string "Ça doit être la chance qui nous\n"
	.string "a enfin réunis.\p"
	.string "Je voudrais fêter ça en\n"
	.string "t'apprenant E-COQUE.$"

Text_SoftboiledDeclined_FR::
	.string "Je serai toujours là si tu\n"
	.string "as besoin.\p"
	.string "J'espère qu'on se reverra\n"
	.string "bientôt.$"

Text_SoftboiledWhichMon_FR::
	.string "Alors, quel POKéMON aura la\n"
	.string "chance d'apprendre E-COQUE?$"

Text_SoftboiledTaught_FR::
	.string "Je te souhaite bonne chance!$"

CeladonCity_Text_SomeoneStoleSilphScope_FR::
	.string "Aaaah! Qu'est-ce que je peux\n"
	.string "faire?\p"
	.string "Quelqu'un a volé le SCOPE SYLPHE.\p"
	.string "Le voleur est parti en courant par\n"
	.string "là mais je l'ai perdu de vue.\p"
	.string "Où est-ce qu'il peut bien\n"
	.string "être maintenant?$"

