CeladonCity_Text_GotMyKoffingInCinnabar_DE::
	.string "Ich habe SMOGON auf der\n"
	.string "ZINNOBERINSEL gefangen!\p"
	.string "Es ist nett, doch wenn man es\n"
	.string "ärgert, atmet es Gift aus!$"

CeladonCity_Text_GymIsGreatFullOfWomen_DE::
	.string "Hehe!\n"
	.string "Diese ARENA ist voller Frauen...$"

CeladonCity_Text_GameCornerIsBadForCitysImage_DE::
	.string "Die SPIELHALLE schadet dem Ruf\n"
	.string "unserer Stadt!$"

CeladonCity_Text_BlewItAllAtSlots_DE::
	.string "Mist!\n"
	.string "Ich habe alles verspielt!\p"
	.string "Hätte ich doch meine MÜNZEN\n"
	.string "rechtzeitig gegen einen Preis\l"
	.string "eingetauscht!$"

CeladonCity_Text_MyTrustedPalPoliwrath_DE::
	.string "QUAPPO ist mein bester Freund!\p"
	.string "Es entwickelte sich, als ich einem\n"
	.string "QUAPUTZI einen WASSERSTEIN gab!$"

CeladonCity_Text_Poliwrath_DE::
	.string "QUAPPO: Quappo! Quappo!$"

CeladonCity_Text_GetLostOrIllPunchYou_DE::
	.string "Was starrst du mich so an?$"

CeladonCity_Text_KeepOutOfTeamRocketsWay_DE::
	.string "Halte dich aus TEAM ROCKETs\n"
	.string "Angelegenheiten heraus!$"

CeladonCity_Text_ExplainXAccuracyDireHit_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "X-TREFFER erhöht die Genauigkeit\n"
	.string "von Attacken!\p"
	.string "ANGRIFFPLUS erhöht die\n"
	.string "Wahrscheinlichkeit, einen\l"
	.string "Volltreffer zu landen!\p"
	.string "Diese Items kannst du im\n"
	.string "EINKAUFSZENTRUM von PRISMANIA\l"
	.string "CITY kaufen!$"

CeladonCity_Text_CitySign_DE::
	.string "PRISMANIA CITY\n"
	.string "Die Stadt der Regenbogen-Träume!$"

CeladonCity_Text_GymSign_DE::
	.string "PRISMANIA CITY POKéMON-ARENA\n"
	.string "ARENALEITERIN: ERIKA\l"
	.string "Die Naturliebende Prinzessin!$"

CeladonCity_Text_MansionSign_DE::
	.string "PRISMANIA-VILLA$"

CeladonCity_Text_DeptStoreSign_DE::
	.string "Im PRISMANIA CITY\n"
	.string "EINKAUFSZENTRUM\l"
	.string "findest du alles, was du brauchst!$"

CeladonCity_Text_GuardSpecProtectsFromStatus_DE::
	.string "TIPPS FÜR TRAINER\p"
	.string "MEGABLOCK schützt POKéMON vor \n"
	.string "Statusverschlechterungen im Kampf.\p"
	.string "Dieses Item kannst du im\n"
	.string "EINKAUFSZENTRUM von PRISMANIA\l"
	.string "CITY erstehen!$"

CeladonCity_Text_PrizeExchangeSign_DE::
	.string "WECHSELSTUBE\n"
	.string "Tausche MÜNZEN gegen Preise!$"

CeladonCity_Text_GameCornerSign_DE::
	.string "ROCKET SPIELHALLE\n"
	.string "Ein Spielplatz für Erwachsene!$"

CeladonCity_Text_ScaldedTongueOnTea_DE::
	.string "Argh, oh…\n"
	.string "Ich habe meine Zunge verbrüht!\p"
	.string "Die nette, alte Dame in der VILLA\n"
	.string "gab mir TEE.\p"
	.string "Aber er war kochend heiß!\n"
	.string "Ich muss ihn erst abkühlen, ehe\l"
	.string "ich ihn trinke!$"

Text_SoftboiledTeach_DE::
	.string "Hallo!\p"
	.string "Ich kenne dich vom Sehen! Aber ich\n"
	.string "hatte bisher keine Zeit, dich\l"
	.string "anzusprechen!\p"
	.string "Glück hat uns scheinbar zusammen-\n"
	.string "gebracht.\p"
	.string "Das möchte ich feiern, indem ich\n"
	.string "einem deiner POKéMON\l"
	.string "WEICHEI beibringe.$"

Text_SoftboiledDeclined_DE::
	.string "Ich habe immer ein Auge auf dich\n"
	.string "geworfen.\p"
	.string "Hoffentlich können wir erneut\n"
	.string "plaudern.$"

Text_SoftboiledWhichMon_DE::
	.string "Also, wie heißt das POKéMON,\n"
	.string "das WEICHEI erlernen soll?$"

Text_SoftboiledTaught_DE::
	.string "Ich wünsche dir viel Glück!$"

CeladonCity_Text_SomeoneStoleSilphScope_DE::
	.string "Oh, was soll ich tun…\p"
	.string "Jemand hat unser SILPH SCOPE\n"
	.string "gestohlen.\p"
	.string "Der Dieb kam aus dieser Richtung.\n"
	.string "Da bin ich mir sicher.\p"
	.string "Aber ich habe ihn verloren!\n"
	.string "Wo ist er nur hin?$"

