ViridianCity_Mart_Text_YouCameFromPallet_FR::
	.string "Hé! Tu viens de BOURG PALETTE?$"

ViridianCity_Mart_Text_TakeThisToProfOak_FR::
	.string "Tu connais le PROF. CHEN?\p"
	.string "Sa commande vient d'arriver.\n"
	.string "Peux-tu la lui porter?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk_FR::
	.string "{PLAYER} obtient\n"
	.string "le COLIS DE CHEN!$"

ViridianCity_Mart_Text_SayHiToOakForMe_FR::
	.string "Cool! Tu diras bonjour au PROF.\n"
	.string "CHEN de ma part!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes_FR::
	.string "On vend des ANTIDOTES dans cette\n"
	.string "boutique.$"

ViridianCity_Mart_Text_GotToBuySomePotions_FR::
	.string "Je dois acheter des POTIONS.\p"
	.string "On ne sait jamais quand un\n"
	.string "POKéMON peut en avoir besoin!$"

