ViridianCity_Mart_Text_YouCameFromPallet_DE::
	.string "Heh!\n"
	.string "Kommst du aus ALABASTIA?$"

ViridianCity_Mart_Text_TakeThisToProfOak_DE::
	.string "PROF. EICH schickt dich, oder?\p"
	.string "Seine Bestellung ist angekommen!\n"
	.string "Holst du das Paket für ihn ab?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk_DE::
	.string "{PLAYER} erhält\n"
	.string "EICHs PAKET!$"

ViridianCity_Mart_Text_SayHiToOakForMe_DE::
	.string "O.K.! Grüße PROF. EICH von mir!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes_DE::
	.string "Dieser Laden führt viele\n"
	.string "GEGENGIFTE.$"

ViridianCity_Mart_Text_GotToBuySomePotions_DE::
	.string "Ich muss TRÄNKE kaufen!\p"
	.string "Man weiß nie, wann ein POKéMON\n"
	.string "schnell geheilt werden muss.$"

