ViridianCity_Mart_Text_YouCameFromPallet_IT::
    .string "Ehi!\n"
    .string "Arrivi da BIANCAVILLA, vero?$"

ViridianCity_Mart_Text_TakeThisToProfOak_IT::
    .string "E conosci il PROF. OAK, vero?\p"
    .string "È arrivato quello che aspettava!\n"
    .string "Glielo puoi portare tu?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk_IT::
    .string "{PLAYER} riceve\n"
    .string "il PACCO di OAK!$"

ViridianCity_Mart_Text_SayHiToOakForMe_IT::
    .string "OK!\n"
    .string "Saluta il PROF. OAK da parte mia!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes_IT::
    .string "Qui si vendono molti ANTIDOTI.$"

ViridianCity_Mart_Text_GotToBuySomePotions_IT::
    .string "Devo comprare delle POZIONI.\p"
    .string "Non si sa mai, i POKéMON\n"
    .string "potrebbero sempre averne\l"
    .string "bisogno.$"

