VermilionCity_Gym_Text_LtSurgeIntro_DE::
	.string "Heh, Kiddie!\n"
	.string "Was hast du hier verloren?\p"
	.string "Im Kampf hast du keine große\n"
	.string "Chance, so viel ist sicher!\p"
	.string "Lass mich dir etwas erzählen: \n"
	.string "Während der POKéMON-FELDZÜGE\l"
	.string "haben mich meine ELEKTRO-POKéMON\l"
	.string "gerettet!\p"
	.string "Sie haben meine Gegner mit Strom\n"
	.string "paralysiert!\p"
	.string "Das Gleiche steht dir nun bevor!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle_DE::
	.string "Ich gebe dir noch einen Tipp!\p"
	.string "Die Elektrizität ist enorm\n"
	.string "kraftvoll!\p"
	.string "Doch sie hat keine Wirkung auf\n"
	.string "BODEN-POKéMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis_DE::
	.string "Der DONNERORDEN erhöht die\n"
	.string "INITIATIVE deiner POKéMON!\p"
	.string "Außerdem können deine POKéMON nun\n"
	.string "jederzeit FLIEGEN einsetzen!\p"
	.string "Du bist ein besonderes Kind!\n"
	.string "Nimm das hier!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge_DE::
	.string "{PLAYER} erhält\n"
	.string "TM34!$"

VermilionCity_Gym_Text_ExplainTM34_DE::
	.string "TM34 ist SCHOCKWELLE!\p"
	.string "ELEKTRO-POKéMON können diese\n"
	.string "Attacke erlernen!$"

VermilionCity_Gym_Text_MakeRoomInYourBag_DE::
	.string "Dein Rucksack ist voll!$"

VermilionCity_Gym_Text_LtSurgeDefeat_DE::
	.string "Wow!\p"
	.string "Du weißt, wie man kämpft, Kiddie!\p"
	.string "Als Auszeichnung verleihe ich dir\n"
	.string "den DONNERORDEN!$"

VermilionCity_Gym_Text_TuckerIntro_DE::
	.string "MAJOR BOB war mein Ausbilder!$"

VermilionCity_Gym_Text_TuckerDefeat_DE::
	.string "Stopp!\n"
	.string "Du bist zu gut!$"

VermilionCity_Gym_Text_TuckerPostBattle_DE::
	.string "Die Barriere verschwindet nicht?\p"
	.string "MAJOR BOB war immer sehr\n"
	.string "vorsichtig!$"

VermilionCity_Gym_Text_BailyIntro_DE::
	.string "Ich bin ein Fliegengewicht, aber im\n"
	.string "Umgang mit Elektrizität bin ich\l"
	.string "Profi!$"

VermilionCity_Gym_Text_BailyDefeat_DE::
	.string "Ein Kurzschluss!$"

VermilionCity_Gym_Text_BailyPostBattle_DE::
	.string "O.K., ich rede!\p"
	.string "MAJOR BOB hat hier irgendwo\n"
	.string "Schalter versteckt!$"

VermilionCity_Gym_Text_DwayneIntro_DE::
	.string "Das hier ist kein Spielplatz!$"

VermilionCity_Gym_Text_DwayneDefeat_DE::
	.string "Wow!\n"
	.string "Du hast mich überrascht!$"

VermilionCity_Gym_Text_DwaynePostBattle_DE::
	.string "MAJOR BOB hat die Tür doppelt\n"
	.string "abgesichert!\p"
	.string "Ein Tipp?\p"
	.string "Der zweite Schalter befindet sich\n"
	.string "direkt neben dem ersten!$"

VermilionCity_Gym_Text_GymGuyAdvice_DE::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "MAJOR BOB hat einen Spitznamen.\n"
	.string "Man nennt ihn den BLITZSCHNELLEN\l"
	.string "ARENALEITER!\p"
	.string "Er ist ein Experte für ELEKTRO-\n"
	.string "POKéMON!\p"
	.string "FLUG- und WASSER-POKéMON sind\n"
	.string "ihm hilflos ausgeliefert! Er nutzt\l"
	.string "auch gern PARALYSE!\p"
	.string "MAJOR BOB ist sehr vorsichtig!\p"
	.string "Du musst ein Rätsel lösen, um ihn\n"
	.string "zu treffen!$"

VermilionCity_Gym_Text_GymGuyPostVictory_DE::
	.string "Puh!\n"
	.string "Ein elektrisierender Kampf!$"

VermilionCity_Gym_Text_GymStatue_DE::
	.string "ORANIA POKéMON-ARENA\n"
	.string "LEITUNG: MAJOR BOB\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon_DE::
	.string "ORANIA POKéMON-ARENA\n"
	.string "LEITUNG: MAJOR BOB\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere_DE::
	.string "Hier ist nichts, bloß Abfall.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened_DE::
	.string "Heh! Hier ist ein Hebel versteckt!\n"
	.string "Ich werde ihn betätigen!\p"
	.string "Das erste Schloss wurde entriegelt!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash_DE::
	.string "ガサゴソ‥！\n"
	.string "おっと！　ゴミばこの　そこに\l"
	.string "また　スイッチが　あった！\l"
	.string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened_DE::
	.string "Das zweite Schloss wurde\n"
	.string "entriegelt!\p"
	.string "Die mechanische Tür hat sich\n"
	.string "geöffnet!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset_DE::
	.string "Hier ist nichts, bloß Abfall.\p"
	.string "Heh! Das Schloss wurde wieder\n"
	.string "verriegelt!$"

