VermilionCity_Gym_Text_LtSurgeIntro_FR::
	.string "Hé!\n"
	.string "Tu fais quoi là?\p"
	.string "Tu ne résisterais pas longtemps en\n"
	.string "temps de guerre!\p"
	.string "Je vais t'avouer quelque\n"
	.string "chose, les POKéMON ELECTRIK\p"
	.string "m'ont sauvé pendant la guerre.\p"
	.string "Ils ont paralysé mes ennemis avec\n"
	.string "leurs éclairs! Comme je te le dis!\p"
	.string "Et y va t'arriver la même chose!\n"
	.string "Compte tes dents! Tu vas morfler!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle_FR::
	.string "Un p'tit conseil!\p"
	.string "L'électricité est très puissante!\p"
	.string "Mais elle est inutile face à des\n"
	.string "POKéMON SOL!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis_FR::
	.string "Le BADGEFOUDRE augmente la\n"
	.string "VITESSE de tes POKéMON!\p"
	.string "Il permet aussi à tes POKéMON\n"
	.string "d'utiliser VOL!\p"
	.string "T'es quelqu'un de pas ordinaire!\n"
	.string "Prends ça!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge_FR::
	.string "{PLAYER} reçoit\n"
	.string "la CT34!$"

VermilionCity_Gym_Text_ExplainTM34_FR::
	.string "CT34 : ONDE DE CHOC!\p"
	.string "Enseigne-la à un\n"
	.string "POKéMON ELECTRIK!$"

VermilionCity_Gym_Text_MakeRoomInYourBag_FR::
	.string "Revue d'paquetage la bleusaille,\n"
	.string "ton inventaire est plein!$"

VermilionCity_Gym_Text_LtSurgeDefeat_FR::
	.string "Whoo!\p"
	.string "T'iras loin toi.\p"
	.string "Très bien, prends le BADGEFOUDRE!$"

VermilionCity_Gym_Text_TuckerIntro_FR::
	.string "A l'armée, MAJOR BOB\n"
	.string "était mon supérieur.\p"
	.string "C'était très instructif d'être sous\n"
	.string "ses ordres.$"

VermilionCity_Gym_Text_TuckerDefeat_FR::
	.string "Stop!\n"
	.string "J'en peux plus!$"

VermilionCity_Gym_Text_TuckerPostBattle_FR::
	.string "Tu ne trouves pas les\n"
	.string "interrupteurs?\p"
	.string "Le MAJOR BOB a toujours été\n"
	.string "reconnu pour sa nature prudente.$"

VermilionCity_Gym_Text_BailyIntro_FR::
	.string "J'suis un poids plume, mais j'suis\n"
	.string "bon avec l'électricité!$"

VermilionCity_Gym_Text_BailyDefeat_FR::
	.string "Argh!\n"
	.string "J'suis grillé!$"

VermilionCity_Gym_Text_BailyPostBattle_FR::
	.string "OK, je parle!\p"
	.string "Le MAJOR BOB a caché des boutons\n"
	.string "pour ouvrir les portes…\l"
	.string "… Quelque part!$"

VermilionCity_Gym_Text_DwayneIntro_FR::
	.string "C'est pas un endroit pour les\n"
	.string "gamins, ici!$"

VermilionCity_Gym_Text_DwayneDefeat_FR::
	.string "Argh!\n"
	.string "Tu m'as eu par surprise!$"

VermilionCity_Gym_Text_DwaynePostBattle_FR::
	.string "C'est le MAJOR BOB lui-même\n"
	.string "qui a installé les pièges de cette\p"
	.string "ARENE. Il a mis des double verrous\n"
	.string "partout. Voici un indice!\p"
	.string "Appuie sur le premier bouton,\n"
	.string "le deuxième est juste à côté!$"

VermilionCity_Gym_Text_GymGuyAdvice_FR::
	.string "Salut,\n"
	.string "CHAMPION en herbe!\p"
	.string "Le MAJOR BOB a un surnom. On\n"
	.string "l'appelle… L'Américain Survolté!\p"
	.string "Il est expert en POKéMON\n"
	.string "ELECTRIK!\p"
	.string "C'est pas bon pour les POKéMON\n"
	.string "VOL et EAU! \p"
	.string "Fais aussi attention à la\n"
	.string "paralysie.\p"
	.string "Le MAJOR BOB est très prudent!\p"
	.string "Ça sera pas facile du tout\n"
	.string "d'arriver jusqu'à lui!$"

VermilionCity_Gym_Text_GymGuyPostVictory_FR::
	.string "Wouh!\n"
	.string "Ce match était survolté!$"

VermilionCity_Gym_Text_GymStatue_FR::
	.string "ARENE POKéMON de CARMIN SUR MER\n"
	.string "CHAMPION: MAJOR BOB\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon_FR::
	.string "ARENE POKéMON de CARMIN SUR MER\n"
	.string "CHAMPION: MAJOR BOB\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere_FR::
	.string "Non!\n"
	.string "Il y a juste une poubelle ici.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened_FR::
	.string "Oh! Un bouton sous la poubelle!\n"
	.string "Dingue!\p"
	.string "Le premier verrou est levé!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash_FR::
	.string "ガサゴソ‥！\n"
	.string "おっと！　ゴミばこの　そこに\l"
	.string "また　スイッチが　あった！\l"
	.string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened_FR::
	.string "Le deuxième verrou est levé!\n"
	.string "La porte s'ouvre!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset_FR::
	.string "Non!\n"
	.string "Il y a juste une poubelle ici.\p"
	.string "Oups… Les verrous sont en place!$"

