VermilionCity_Gym_Text_LtSurgeIntro_ES::
    .string "¡Oye!\n"
    .string "¿Pero qué haces?\p"
    .string "¡No resistirás mucho luchando!\n"
    .string "¡Seguro!\p"
    .string "¡Los POKéMON ELÉCTRICOS\n"
    .string "me salvaron en combate!\p"
    .string "¡Paralizaron a mis enemigos!\p"
    .string "¡Y eso mismo voy a hacer yo\n"
    .string "contigo!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle_ES::
    .string "¡Te daré un pequeño consejo!\p"
    .string "¡La electricidad es muy potente!\p"
    .string "¡Pero no afecta a los POKéMON\n"
    .string "del tipo TIERRA!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis_ES::
    .string "¡La MEDALLA TRUENO aumenta la\n"
    .string "VELOCIDAD de tus POKéMON!\p"
    .string "¡Y permite volar a tus POKéMON\n"
    .string "cuando quieran!\p"
    .string "¡Tú eres muy especial!\n"
    .string "¡Toma esto!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge_ES::
    .string "¡{PLAYER} recibió la MT34\n"
    .string "de manos de LT. SURGE!$"

VermilionCity_Gym_Text_ExplainTM34_ES::
    .string "¡MT34 contiene ONDA VOLTIO!\p"
    .string "¡Enséñaselo a un POKéMON\n"
    .string "eléctrico!$"

VermilionCity_Gym_Text_MakeRoomInYourBag_ES::
    .string "¡Más vale que le hagas sitio!$"

VermilionCity_Gym_Text_LtSurgeDefeat_ES::
    .string "¡Guau!\p"
    .string "¡Tú sí que eres fuerte!\p"
    .string "¡Anda, toma la MEDALLA TRUENO!$"

VermilionCity_Gym_Text_TuckerIntro_ES::
    .string "¡Cuando estaba en el ejército,\n"
    .string "el LT. SURGE era muy estricto!$"

VermilionCity_Gym_Text_TuckerDefeat_ES::
    .string "¡Alto!\n"
    .string "¡Eres genial!$"

VermilionCity_Gym_Text_TuckerPostBattle_ES::
    .string "No es fácil abrir esta puerta...\p"
    .string "¡El LT. SURGE siempre fue muy\n"
    .string "cauteloso en el ejército!$"

VermilionCity_Gym_Text_BailyIntro_ES::
    .string "¡No es que yo sea muy fuerte,\n"
    .string "pero soy muy bueno con la\l"
    .string "electricidad!$"

VermilionCity_Gym_Text_BailyDefeat_ES::
    .string "¡Qué paliza!$"

VermilionCity_Gym_Text_BailyPostBattle_ES::
    .string "¡Vale, hablaré!\p"
    .string "¡LT. SURGE dijo que ocultaría los\n"
    .string "botones de la puerta dentro de\l"
    .string "algo!$"

VermilionCity_Gym_Text_DwayneIntro_ES::
    .string "¡Este lugar no es para niños!\n"
    .string "¡Por muy fuerte que seas!$"

VermilionCity_Gym_Text_DwayneDefeat_ES::
    .string "¡Uuuaa!\n"
    .string "¡Me dejas a cuadros!$"

VermilionCity_Gym_Text_DwaynePostBattle_ES::
    .string "LT. SURGE colocó cerraduras\n"
    .string "dobles en el GIMNASIO.\p"
    .string "¡Las puso por todos sitios!\n"
    .string "¡Te daré una pista!\p"
    .string "¡Tras abrir la 1.ª cerradura, la\n"
    .string "2.ª está al lado!$"

VermilionCity_Gym_Text_GymGuyAdvice_ES::
    .string "¡Hola, aspirante al título!\p"
    .string "El LT. SURGE tiene un mote. La\n"
    .string "gente le llama: ¡Rayo americano!\p"
    .string "¡Es un experto en POKéMON\n"
    .string "eléctricos!\p"
    .string "¡Los POKéMON voladores y los\n"
    .string "acuáticos están en peligro! ¡Ten\l"
    .string "cuidado con la parálisis!\p"
    .string "¡El LT. SURGE es muy cuidadoso!\p"
    .string "¡Descifra un código y llegarás a\n"
    .string "él!$"

VermilionCity_Gym_Text_GymGuyPostVictory_ES::
    .string "¡Uau!\n"
    .string "¡Vaya pelea tan eléctrica!$"

VermilionCity_Gym_Text_GymStatue_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon_ES::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere_ES::
    .string "¡No, aquí sólo hay basura!$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened_ES::
    .string "¡Oye! ¡Hay un botón debajo de la\n"
    .string "basura!\p"
    .string "¡Púlsalo!\n"
    .string "Abierto primer cierre eléctrico.$"

VermilionCity_Gym_Text_AnotherSwitchInTrash_ES::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened_ES::
    .string "Abierto segundo cierre eléctrico.\p"
    .string "¡Abierta la puerta mecánica!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset_ES::
    .string "¡No! Aquí sólo hay basura.\p"
    .string "¡Las cerraduras eléctricas fueron\n"
    .string "reajustadas!$"
