FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone_DE::
	.string "Willkommen in der SAFARI-ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500_DE::
	.string "Für nur 500¥ darfst du im Park so\n"
	.string "viele POKéMON fangen, wie du\l"
	.string "möchtest!\p"
	.string "Möchtest du auf die Jagd gehen?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls_DE::
	.string "Das kostet 500¥!\p"
	.string "Wir verwenden hier spezielle\n"
	.string "POKéBÄLLE.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls_DE::
	.string "{PLAYER} erhält\n"
	.string "30 SAFARIBÄLLE!$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut_DE::
	.string "Wir rufen dich über Lautsprecher\n"
	.string "aus, wenn deine Fangzeit abgelaufen\l"
	.string "oder dein Vorrat an SAFARIBÄLLEN\l"
	.string "erschöpft ist!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain_DE::
	.string "O.K.!\n"
	.string "Besuche uns bald wieder!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney_DE::
	.string "Ups!\n"
	.string "Du hast nicht genug Geld!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly_DE::
	.string "Hast du keine Lust mehr?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls_DE::
	.string "Gib bitte die restlichen\n"
	.string "SAFARIBÄLLE zurück.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck_DE::
	.string "Viel Glück!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain_DE::
	.string "War die Jagd erfolgreich?\n"
	.string "Besuche uns bald wieder!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone_DE::
	.string "Hi!\n"
	.string "Bist du zum ersten Mal hier?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone_DE::
	.string "Die SAFARI-ZONE besteht aus vier\n"
	.string "Abschnitten.\p"
	.string "In jedem Abschnitt findet man\n"
	.string "verschiedene POKéMON. Versuche,\l"
	.string "sie mit SAFARIBÄLLEN zu fangen.\p"
	.string "Du kannst auch KÖDER oder\n"
	.string "STEINE werfen.\p"
	.string "Bei einem KÖDER flieht das\n"
	.string "POKéMON nicht so schnell,\l"
	.string "ist aber schwieriger zu fangen.\p"
	.string "Bei einem STEIN flieht das\n"
	.string "POKéMON eher, ist aber\l"
	.string "einfacher zu fangen.\p"
	.string "Wenn du keine SAFARIBÄLLE mehr\n"
	.string "hast oder wenn die Zeit abgelaufen\l"
	.string "ist, endet das Spiel!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere_DE::
	.string "Heh, du bist ein Stammkunde!$"

