SaffronCity_PokemonTrainerFanClub_Text_HuhYou_FR::
	.string "Hein?\n"
	.string "C'est toi?…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow_FR::
	.string "Tu es peut-être…\n"
	.string "… …\p"
	.string "Tu es…\n"
	.string "C'est toi, {PLAYER}!\p"
	.string "On parlait justement de toi!\p"
	.string "On parlait de ce nouveau DRESSEUR\n"
	.string "super fort.\p"
	.string "Et cette personne c'est toi!\n"
	.string "C'est trop fort!\p"
	.string "Alors on va créer ton FAN CLUB!\p"
	.string "En continuant à te battre comme\n"
	.string "ça, je suis sûre que tu vas\p"
	.string "avoir de plus en plus de fans!$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou_FR::
	.string "Je te soutiendrai toujours!\p"
	.string "Go, {PLAYER}, go!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou_FR::
	.string "Je croirai toujours en toi,\n"
	.string "{PLAYER}.\p"
	.string "Montre aux autres ce que c'est\n"
	.string "un super DRESSEUR!$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore_FR::
	.string "Désolée.\n"
	.string "J'étais une de tes fans avant.\p"
	.string "Mais on dirait que t'as plus\n"
	.string "l'énergie que t'avais avant.\p"
	.string "D'ailleurs, je trouve que {STR_VAR_1}\n"
	.string "est carrément plus cool!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe_FR::
	.string "Oh!\n"
	.string "{PLAYER}!\p"
	.string "Tout le monde parle de toi\n"
	.string "en ce moment.\p"
	.string "Je vois très bien pourquoi!\n"
	.string "C'est vrai que t'es fortiche.\p"
	.string "Mais tu sais quoi?\p"
	.string "J'suis aussi fan de {STR_VAR_1}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling_FR::
	.string "Les DRESSEURS sont siiiii cool\n"
	.string "quand ils se battent!\p"
	.string "Tu crois pas?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts_FR::
	.string "Oh! C'est {PLAYER}!\n"
	.string "Trop cool!\p"
	.string "Je peux avoir ton autographe?\n"
	.string "Allez, s'te plaît, sur mon short!$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou_FR::
	.string "Qu'il fasse super chaud…\p"
	.string "Ou qu'il fasse super froid…\p"
	.string "Une chose est sûre, je garderai\n"
	.string "mon short!\p"
	.string "Allez, continue de gagner, je crois\n"
	.string "en toi comme dans mes shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero_FR::
	.string "PIERRE est mon héros!\n"
	.string "C'est un vrai mec!\p"
	.string "Hehehe, t'as vu ça, ma mère\n"
	.string "m'a brodé le nom de PIERRE\p"
	.string "sur mon short. Trop classe!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd_FR::
	.string "… …\p"
	.string "Je suis fan de PIERRE!\p"
	.string "Et je le resterai quoi qu'il\n"
	.string "arrive!\p"
	.string "J'le jure sur mon short!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool_FR::
	.string "PIERRE, c'est le plus cool,\n"
	.string "point à la ligne!\p"
	.string "Si je lui ressemblais, j'aurais\n"
	.string "trop de succès avec les filles.$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle_FR::
	.string "{PLAYER}, j'ai eu le plaisir de te\n"
	.string "voir combattre.\p"
	.string "D'ailleurs, cela m'a rappelé les\n"
	.string "grands moments de ma jeunesse.\p"
	.string "En tout cas, sache que tu as tout\n"
	.string "mon soutien.$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence_FR::
	.string "J'ai voyagé par-delà les océans.\p"
	.string "Mais jamais, je n'avais vu un\n"
	.string "DRESSEUR comme toi.\p"
	.string "Prends conscience de ta force\n"
	.string "et ne perds pas espoir!\p"
	.string "Fais-moi cette promesse!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre_FR::
	.string "Hmm…\n"
	.string "Et tu es?\p"
	.string "Tu comptais vraiment entrer\n"
	.string "au FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo_FR::
	.string "Ah, tu es la personne dont tout le\n"
	.string "monde parle en ce moment.\p"
	.string "Effectivement, je décèle un\n"
	.string "certain quelque chose en toi.\p"
	.string "Mais tu as encore beaucoup de\n"
	.string "chemin à parcourir pour que je\p"
	.string "te considère comme un grand\n"
	.string "DRESSEUR.$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning_FR::
	.string "Nous sommes tous des fans\n"
	.string "de DRESSEURS POKéMON.\p"
	.string "Rien de plus impressionnant qu'un\n"
	.string "DRESSEUR en plein combat.\p"
	.string "Qui sait, si tu continues comme\n"
	.string "ça, le jour viendra peut-être\p"
	.string "où l'on parlera aussi de toi.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay_FR::
	.string "C'est {PLAYER}!\n"
	.string "C'est {PLAYER}!\p"
	.string "Un jour, je serai comme {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan_FR::
	.string "{PLAYER} a perdu tous ses fans.\p"
	.string "Ça veut dire que je peux l'avoir\n"
	.string "rien que pour moi!\p"
	.string "Allez, {PLAYER}!\n"
	.string "Epate-moi!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina_FR::
	.string "T'sais quoi?\n"
	.string "J'adorerais être comme MORGANE!\p"
	.string "Mais je vais devoir développer\n"
	.string "mes pouvoirs PSY pour ça.$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan_FR::
	.string "Même si je dois être la dernière,\n"
	.string "je serai toujours fan de MORGANE!\p"
	.string "Mon rêve, c'est d'être aussi belle\n"
	.string "et cool qu'elle!\p"
	.string "Mais je vais devoir développer\n"
	.string "mes pouvoirs PSY pour ça.$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay_FR::
	.string "Tu crois qu'un jour je pourrai\n"
	.string "être un DRESSEUR cool?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool_FR::
	.string "Waouh, c'est trop coool!\n"
	.string "Trooop cool!\p"
	.string "Hein? Non…\n"
	.string "Pas toi…\p"
	.string "J'adore ta façon de combattre.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans_FR::
	.string "Tiens, {PLAYER}!\p"
	.string "On dirait bien que je suis ton\n"
	.string "dernier fan.\p"
	.string "Mais ça me plaît assez d'être\n"
	.string "le seul, c'est moins stressant.\p"
	.string "Continue comme ça!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks_FR::
	.string "{STR_VAR_1} est cool, hein?\n"
	.string "J'adore sa façon de parler.\p"
	.string "Si seulement je pouvais lui\n"
	.string "parler en personne.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan_FR::
	.string "Tu le crois ça?\n"
	.string "Ils sont tous fans de toi.\p"
	.string "Comment ça se fait que je sois\n"
	.string "le seul fan de {STR_VAR_1}?$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle_FR::
	.string "Oh mon dieu, c'est toi?\n"
	.string "C'est bien toi, {PLAYER}?\p"
	.string "Je dois te dire, j'adore ta\n"
	.string "façon de combattre.\p"
	.string "Continue comme ça et ne\n"
	.string "nous déçois pas!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan_FR::
	.string "Oh mon dieu, c'est toi?\n"
	.string "C'est bien toi, {PLAYER}?\p"
	.string "Je suis déçue… Je viens de\n"
	.string "réaliser que je suis ta seule fan!\p"
	.string "Bon, on ne peut rien y faire…\n"
	.string "Laisse-moi au moins t'encourager!\p"
	.string "Allez {PLAYER}, allez {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire_FR::
	.string "Ces derniers temps, rien ne peut\n"
	.string "arrêter {STR_VAR_1}.\p"
	.string "La façon dont il combat…\n"
	.string "C'est à couper le souffle!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou_FR::
	.string "Bonjour {PLAYER}!\p"
	.string "Tout le monde parle de toi en\n"
	.string "ce moment.\p"
	.string "Je me sens un peu seule comme\n"
	.string "je suis fan de {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing_FR::
	.string "Incroyable! Tu es vraiment\n"
	.string "incroyable, {PLAYER}!\p"
	.string "Tu me donnes même envie\n"
	.string "de devenir DRESSEUR!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan_FR::
	.string "Je suis ta seule et unique fan…\n"
	.string "C'est frustrant…\p"
	.string "Tu veux pas te donner un peu de\n"
	.string "mal pour te faire remarquer?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity_FR::
	.string "Pour moi, le plus grand c'est\n"
	.string "{STR_VAR_1}!\p"
	.string "Pourquoi est-ce que je suis la\n"
	.string "seule à penser ça?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart_FR::
	.string "Je crois en {STR_VAR_1} de tout mon\n"
	.string "cœur.\p"
	.string "Même si je suis la seule à\n"
	.string "penser ça.\p"
	.string "Si seulement je pouvais le\n"
	.string "rencontrer, \p"
	.string "je me sentirais moins seule.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational_FR::
	.string "Hiyah!\p"
	.string "Ta façon de combattre est\n"
	.string "géniale.\p"
	.string "Je suis sûr que tu iras super\n"
	.string "loin!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan_FR::
	.string "Au lieu de juste regarder les\n"
	.string "autres se battre, \p"
	.string "il faut parfois aussi se jeter dans\n"
	.string "l'action.\p"
	.string "C'est le MAITRE de mon DOJO\n"
	.string "qui m'a appris ça.\p"
	.string "Mais ça ne m'empêchera pas\n"
	.string "de rester ton fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect_FR::
	.string "Je n'admire qu'un seul DRESSEUR!\n"
	.string "Et c'est le MAITRE de mon DOJO.\p"
	.string "Toi aussi, tu devrais lui montrer\n"
	.string "du respect!\p"
	.string "Hiyaaah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster_FR::
	.string "Hiyaah!\p"
	.string "Je respecte le MAITRE de \n"
	.string "mon DOJO comme personne.\p"
	.string "Je vais parcourir la région en\n"
	.string "parlant de lui pour que tout\p"
	.string "le monde reconnaisse sa\n"
	.string "valeur!$"

