SaffronCity_PokemonTrainerFanClub_Text_HuhYou_ES::
    .string "¿Mm?\n"
    .string "Tú...$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow_ES::
    .string "¿Tú no eras...?\p"
    .string "¡Sí!\n"
    .string "¡Tú eres {PLAYER}!\p"
    .string "¡Estábamos hablando de ti\n"
    .string "ahora mismo!\p"
    .string "¡Estábamos diciendo que había\n"
    .string "alguien que se salía ENTRENANDO\l"
    .string "POKéMON!\p"
    .string "¡Y ese alguien eres tú!\n"
    .string "¡Eres guay!\p"
    .string "¡Nos ha entrado tanta emoción\n"
    .string "que hemos decidido crear tu CLUB\l"
    .string "de FANS!\p"
    .string "¡Esperamos que sigas luchando\n"
    .string "y enseñándonos lo guay que eres!\p"
    .string "¡Así seguro que te salen muchos\n"
    .string "más fans como yo!$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou_ES::
    .string "¡Pienso animarte siempre!\p"
    .string "¡A la bim, a la bam, a la bim,\n"
    .string "bom, bam! ¡{PLAYER}, {PLAYER}, y\l"
    .string "nadie más! ¡A la bim, bom, bam!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou_ES::
    .string "¡Pienso apoyarte siempre, {PLAYER}!\p"
    .string "¡Enséñale al mundo de lo que\n"
    .string "eres capaz cuando te lo propones!$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore_ES::
    .string "Lo siento.\n"
    .string "Yo era tu fan...\p"
    .string "Pero has perdido mucho tirón...\p"
    .string "Últimamente, quien parte la pana\n"
    .string "es {STR_VAR_1}, la verdad...$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe_ES::
    .string "¡Hola, {PLAYER}!\p"
    .string "¡Últimamente todo el mundo está\n"
    .string "revolucionado contigo!\p"
    .string "Y lo entiendo, eres muy fuerte...\p"
    .string "Pero ¿sabes qué pasa?\p"
    .string "Que me hice fan de {STR_VAR_1}\n"
    .string "y no es plan de echarme atrás\l"
    .string "ahora, ¿no?$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling_ES::
    .string "A mí me parece que no hay nada\n"
    .string "más guay que ver luchar a los\l"
    .string "ENTRENADORES.\p"
    .string "¿No te parece?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts_ES::
    .string "¡Madre mía, pero si es {PLAYER}!\n"
    .string "¡Guau, qué pasada!\p"
    .string "¡Qué guay, qué guay!\n"
    .string "¡Qué emoción!\p"
    .string "¿Me firmas un autógrafo?\n"
    .string "¡Fírmame en los pantalones,\l"
    .string "no pasa nada!$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou_ES::
    .string "¡Yo siempre llevo pantalones\n"
    .string "cortos, como tú!\p"
    .string "¡Ya llueva, nieve, o ventee!\p"
    .string "¡Yo iré con pantalón corto,\n"
    .string "como tú!\p"
    .string "¡Venga, debes ir a por todas!\p"
    .string "¡Yo confío en ti y no me pienso\n"
    .string "quitar los pantalones cortos!\l"
    .string "¡Pantalones cortos al poder!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero_ES::
    .string "¡BROCK es mi héroe!\n"
    .string "No hay otro como él.\p"
    .string "¡Lo admiro tanto que le he\n"
    .string "pedido a mi madre que me borde\l"
    .string "su nombre en los pantalones, je!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd_ES::
    .string "Eh... Yo soy fan de BROCK.\p"
    .string "Y aunque fuera su único seguidor,\n"
    .string "no lo abandonaría nunca.\p"
    .string "¡Pongo a mis pantalones cortos\n"
    .string "como testigo!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool_ES::
    .string "BROCK es la caña, punto.\p"
    .string "¡Ya me gustaría a mí ser como él!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle_ES::
    .string "{PLAYER}, he tenido el placer\n"
    .string "de verte luchar.\p"
    .string "Y me he visto de joven. Ah, qué\n"
    .string "dulces y lejanos recuerdos...\p"
    .string "Sigue por el camino que llevas.\n"
    .string "Pienso seguirte siempre.$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence_ES::
    .string "He viajado por mil sitios y puedo\n"
    .string "decir que ningún ENTRENADOR\l"
    .string "te llega a la suela del zapato.\p"
    .string "¡Confía en tus posibilidades\n"
    .string "y sigue luchando!\p"
    .string "¡Di que vas a seguir luchando!\n"
    .string "¡Muy bien, joven!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre_ES::
    .string "¿Mm?\n"
    .string "¿Y tú quién eres?\p"
    .string "¿Vienes a apuntarte al CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo_ES::
    .string "Anda, así que eres {PLAYER}...\n"
    .string "Todo el mundo habla de ti\l"
    .string "últimamente.\p"
    .string "La verdad es que tienes pinta\n"
    .string "de ser fuerte, sí, sí.\p"
    .string "Pero para mí..., no sé,\n"
    .string "te veo un poco verde todavía.$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning_ES::
    .string "Todos los que estamos aquí somos\n"
    .string "fans de ENTRENADORES POKéMON.\p"
    .string "La imagen que dan cuando luchan...\n"
    .string "¡Son supercarismáticos!\p"
    .string "No sé, si ganas más combates,\n"
    .string "¡igual acabamos hablando todos\l"
    .string "de ti!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay_ES::
    .string "¡Eh, que es {PLAYER}!\n"
    .string "¡Es {PLAYER}!\p"
    .string "¡Yo quiero llegar a ser como\n"
    .string "{PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan_ES::
    .string "Todo el mundo ha dejado de ser\n"
    .string "fan de {PLAYER}...\p"
    .string "¡Me da igual, así me tiene sólo\n"
    .string "a mí!\p"
    .string "¡{PLAYER}, {PLAYER}, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina_ES::
    .string "¿Sabes qué?\n"
    .string "¡Me encantaría ser como SABRINA!\p"
    .string "¡Y dominar los poderes psíquicos,\n"
    .string "como ella!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan_ES::
    .string "No pienso dejar nunca a SABRINA.\n"
    .string "¡Aunque sea su única fan!.\p"
    .string "Mi sueño es llegar a ser como\n"
    .string "ella; dulce, pero guay a la vez.\p"
    .string "¡Y dominar los poderes psíquicos,\n"
    .string "como ella!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay_ES::
    .string "¿Llegaré a ser buena ENTRENADORA\n"
    .string "algún día?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool_ES::
    .string "¡Qué pasada, qué pasada!\n"
    .string "¡Qué guay, qué guay!\p"
    .string "¿Mm?...\n"
    .string "No, no lo digo por ti.\p"
    .string "Lo digo por tu forma de luchar.\n"
    .string "Es guay.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans_ES::
    .string "¡Eh, {PLAYER}!\p"
    .string "Creo que soy el único fan que\n"
    .string "tienes.\p"
    .string "Pero oye, tiene su lado positivo,\n"
    .string "te evitas mucho estrés.\p"
    .string "¡Sigue como hasta ahora!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks_ES::
    .string "Qué guay es {STR_VAR_1}, ¿verdad?\n"
    .string "Me gusta hasta su forma de hablar.\p"
    .string "¡Me encantaría que viniera alguna\n"
    .string "vez por aquí!$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan_ES::
    .string "¿Será posible?\n"
    .string "¡Todo el mundo es fan tuyo!\p"
    .string "O sea, ¿que soy el único fan\n"
    .string "de {STR_VAR_1}?\p"
    .string "Bueno, en realidad, ¿qué más\n"
    .string "me da?$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle_ES::
    .string "¡No me lo puedo creer!\n"
    .string "¿Eres {PLAYER}, en serio?\p"
    .string "Tengo que decirte que me encanta\n"
    .string "la forma de luchar que tienes.\p"
    .string "Espero que no cambies nunca.\n"
    .string "¡Soy tu fan más fan!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan_ES::
    .string "¡No me lo puedo creer!\n"
    .string "¡Pero si es {PLAYER}!\p"
    .string "Quería decirte que estoy un poco\n"
    .string "chafada, porque soy tu única fan.\p"
    .string "Pero bueno, pienso animarte\n"
    .string "de todas formas.\p"
    .string "¡Viva {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire_ES::
    .string "Quien ha estado en boca de todos\n"
    .string "últimamente es {STR_VAR_1}.\p"
    .string "Lucha de una manera...\n"
    .string "Como a mí me gusta, vaya.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou_ES::
    .string "¡Anda, pero si es {PLAYER}!\p"
    .string "Se ve que está de moda hablar\n"
    .string "de ti.\p"
    .string "¡Yo me he quedado más sola\n"
    .string "que la una animando a {STR_VAR_1}!$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing_ES::
    .string "¡Guay, guay y guay!\n"
    .string "¡{PLAYER}, eres realmente guay!\p"
    .string "¡De tanto verte, he decidido\n"
    .string "convertirme en ENTRENADORA!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan_ES::
    .string "Soy tu única fan...\n"
    .string "Y... me encuentro tan sola...\p"
    .string "¿Por qué no te esfuerzas un poco\n"
    .string "para que se fijen en ti?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity_ES::
    .string "La verdad es que {STR_VAR_1}\n"
    .string "impone... A mí me encanta.\p"
    .string "¿Soy yo la única que percibe el\n"
    .string "aura de solemnidad que le rodea?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart_ES::
    .string "Yo confío profundamente\n"
    .string "en {STR_VAR_1}.\p"
    .string "Me da igual ser la única.\p"
    .string "Mientras tenga a mi ídolo\n"
    .string "{STR_VAR_1}, no me sentiré sola.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational_ES::
    .string "¡Guau!\p"
    .string "¡Tu forma de luchar es ejemplar!\p"
    .string "¡Espero que nunca dejes de tener\n"
    .string "éxito! ¡Ánimo!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan_ES::
    .string "¡No te entretengas mirando cómo\n"
    .string "lucha el resto! ¡Lucha tú!\p"
    .string "Mi MAESTRO me echó del DOJO\n"
    .string "como el que no quiere la cosa...\p"
    .string "Pero, me da igual, yo voy a seguir\n"
    .string "siendo tu fan.\p"
    .string "¡No pienso dejar de serlo!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect_ES::
    .string "¡Hiyah! Sólo tengo respeto por\n"
    .string "un ENTRENADOR.\p"
    .string "Por mi MAESTRO. No hay nadie\n"
    .string "como él sobre el DOJO.\p"
    .string "Deberías hacerte su fan, como yo.\n"
    .string "¡Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster_ES::
    .string "¡Hiyah! Tengo un respeto enorme\n"
    .string "por mi MAESTRO.\l"
    .string "Es el mejor sobre el DOJO.\p"
    .string "No pienso ser fan de nadie más.\p"
    .string "Voy a ir diciendo por ahí lo bueno\n"
    .string "que es.\p"
    .string "¡Hiyah!$"
