SaffronCity_PokemonTrainerFanClub_Text_HuhYou_IT::
    .string "Ehi, ma…\p"
    .string "…tu non sei…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow_IT::
    .string "Ma certo che sei tu!\p"
    .string "{PLAYER}!\p"
    .string "Stavamo proprio parlando di te!\p"
    .string "Tutti pensiamo che tu sia un\n"
    .string "grande ALLENATORE!\p"
    .string "Anzi, abbiamo deciso di\n"
    .string "fondare il tuo FAN CLUB!\p"
    .string "Continua a lottare e a\n"
    .string "mostrarci la tua grandezza!\p"
    .string "Così, molte altre persone\n"
    .string "si iscriveranno al FAN CLUB!$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou_IT::
    .string "Non mi stancherò mai di fare il tifo\n"
    .string "per te!\p"
    .string "Forza {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou_IT::
    .string "Io credo in te, {PLAYER}.\p"
    .string "Sei il mio faro nella notte!\p"
    .string "Mostra anche a tutti gli altri\n"
    .string "ciò che sai fare!$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore_IT::
    .string "Prima ero una tua fan.\p"
    .string "Ora, però, hai perso la classe\n"
    .string "di un tempo.\p"
    .string "Non offenderti, ma credo che\n"
    .string "ora {STR_VAR_1} abbia molto più\l"
    .string "stile di te.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe_IT::
    .string "Ehi, {PLAYER}!\p"
    .string "Qui sono tutti pazzi per te!\p"
    .string "E credo proprio di sapere\n"
    .string "perché: sei troppo forte!\p"
    .string "Essere fan è davvero fantastico!\p"
    .string "Da quando sono diventata una fan\n"
    .string "di {STR_VAR_1}, per me fare il tifo per\l"
    .string "un ALLENATORE è una missione!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling_IT::
    .string "Quando combattono, gli ALLENATORI\n"
    .string "sembrano così forti, sicuri di sé!\p"
    .string "Sei d'accordo?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts_IT::
    .string "Ehi, ma tu sei {PLAYER}!\n"
    .string "Non ci posso credere!\p"
    .string "Mi fai un autografo?\n"
    .string "Ti piacciono i miei pantaloncini?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou_IT::
    .string "D'estate, d'inverno, nella neve o\n"
    .string "sotto il sole…\p"
    .string "…io indosso sempre i miei\n"
    .string "pantaloncini.\p"
    .string "Io credo nei miei pantaloncini,\n"
    .string "capisci? Proprio come credo in te!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero_IT::
    .string "Il mio eroe è BROCK!\n"
    .string "È il più grande di tutti!\p"
    .string "Sai che mia mamma mi ha cucito la\n"
    .string "scritta “BROCK” sui pantaloncini?$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd_IT::
    .string "Sono un fan di BROCK!\p"
    .string "Anche se fossi l'unica persona sulla\n"
    .string "terra a fare il tifo per lui, non\l"
    .string "smetterei mai di sostenerlo!\p"
    .string "Se stessimo tutti dalla stessa\n"
    .string "parte, che gusto ci sarebbe?$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool_IT::
    .string "BROCK è la classe in persona.\n"
    .string "Non c'è nient'altro da aggiungere.\p"
    .string "Non so cosa farei per poter essere\n"
    .string "come lui!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle_IT::
    .string "{PLAYER}, ho avuto il\n"
    .string "piacere di vederti lottare.\p"
    .string "Mi hai riportato alla mente la mia\n"
    .string "gioventù, da così tanto tempo\l"
    .string "perduta.\p"
    .string "Ti auguro ancora tanti successi!\n"
    .string "Non smetterò mai di fare il tifo\l"
    .string "per te!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence_IT::
    .string "Ho viaggiato molto nella mia vita.\p"
    .string "Eppure, non ho mai trovato un\n"
    .string "ALLENATORE della tua classe.\p"
    .string "Continua così!\p"
    .string "Combatti e vinci per me, mio\n"
    .string "giovane idolo!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre_IT::
    .string "…E tu chi sei?\p"
    .string "Vuoi per caso iscriverti al nostro\n"
    .string "FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo_IT::
    .string "Ma tu sei {PLAYER}!\n"
    .string "Ho sentito molto parlare di te!\p"
    .string "Hai lo sguardo di un vincente,\n"
    .string "non c'è dubbio.\p"
    .string "Però, vedi, prima che mi convinca a\n"
    .string "diventare un tuo fan, ce ne vuole.$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning_IT::
    .string "Noi qui siamo tutti fan di\n"
    .string "ALLENATORI di POKéMON.\p"
    .string "Siamo affascinati dalla loro\n"
    .string "classe, dalla loro forza.\p"
    .string "Chissà, magari un giorno si parlerà\n"
    .string "anche di te!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay_IT::
    .string "C'è {PLAYER}!\n"
    .string "C'è {PLAYER}!\p"
    .string "Voglio diventare come {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan_IT::
    .string "Ormai sono rimasta l'unica fan\n"
    .string "di {PLAYER}.\p"
    .string "In un certo senso, però non mi\n"
    .string "dispiace. È un po' come avere\l"
    .string "l'esclusiva!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina_IT::
    .string "Voglio diventare come SABRINA!\p"
    .string "Voglio avere i suoi poteri psichici,\n"
    .string "il magnetismo dei suoi occhi…$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan_IT::
    .string "Anche se sono rimasta l'ultima a\n"
    .string "tifare per SABRINA, non cambierò\l"
    .string "mai idea!\p"
    .string "Voglio diventare dolce e forte\n"
    .string "come lei, con i suoi stessi poteri\l"
    .string "psichici!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay_IT::
    .string "Chissà se diventerò mai un grande\n"
    .string "ALLENATORE!$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool_IT::
    .string "Grande! Davvero stupefacente!\p"
    .string "No, non parlavo di te, ma soltanto\n"
    .string "del tuo modo di combattere.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans_IT::
    .string "Ciao, {PLAYER}!\p"
    .string "Credo di essere rimasto il tuo\n"
    .string "unico fan.\p"
    .string "Ma, sai, in un certo senso, essere\n"
    .string "rimasto l'unico mi tranquillizza.\p"
    .string "Continua a farti valere!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks_IT::
    .string "{STR_VAR_1} è grande!\p"
    .string "Mi piace il modo in cui\n"
    .string "parla.\p"
    .string "Non so cosa darei per poterlo\n"
    .string "incontrare!$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan_IT::
    .string "Non ci crederai, ma sono diventati\n"
    .string "tutti tuoi fan!\p"
    .string "Non posso credere di essere rimasto\n"
    .string "l'unico a tifare per {STR_VAR_1}!\p"
    .string "Comunque, in fin dei conti, devo\n"
    .string "dire che l'idea di essere l'unico\l"
    .string "fan di {STR_VAR_1} non mi dispiace.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle_IT::
    .string "{PLAYER}? Sei proprio tu?\p"
    .string "Devo proprio ammetterlo, sono\n"
    .string "estasiata dal modo in cui\l"
    .string "combatti!\p"
    .string "Continua così! Sarò sempre la\n"
    .string "tua fan più accanita!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan_IT::
    .string "Ah, ma tu sei {PLAYER}!\p"
    .string "Che tristezza! Ho scoperto di\n"
    .string "essere la tua unica fan!\p"
    .string "E vabbè, cosa ci vuoi fare!\n"
    .string "Cantiamo, dai!\p"
    .string "Viva {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire_IT::
    .string "Recentemente {STR_VAR_1} ha fatto\n"
    .string "grandi cose!\p"
    .string "Il modo in cui combatte è davvero\n"
    .string "esaltante!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou_IT::
    .string "Ah, ma tu sei {PLAYER}!\n"
    .string "Ma sai che negli ultimi tempi\l"
    .string "parlano tutti di te!\p"
    .string "Credo di essere rimasta l'unica a\n"
    .string "fare il tifo per {STR_VAR_1}!$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing_IT::
    .string "Incredibile! {PLAYER}, sei davvero\n"
    .string "incredibile!\p"
    .string "Sai cosa ti dico? Vederti mi ha\n"
    .string "fatto venire voglia di diventare\l"
    .string "ALLENATORE anch'io!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan_IT::
    .string "Sono rimasta la tua unica fan.\n"
    .string "È deprimente…\p"
    .string "Perché non ti metti un po' più\n"
    .string "in mostra? Così attirerai altri fan!$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity_IT::
    .string "{STR_VAR_1} è il mio idolo! \p"
    .string "Non capisco perché ci siano persone\n"
    .string "che non riconoscono la profonda\l"
    .string "dignità di questa persona!$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart_IT::
    .string "Credo ciecamente in {STR_VAR_1}!\p"
    .string "So di essere rimasta l'unica, ma non\n"
    .string "mi importa!\p"
    .string "Scusa, ora lasciami in pace.\n"
    .string "Devo meditare sulla grandezza\l"
    .string "di {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational_IT::
    .string "Ehi!\p"
    .string "Il tuo stile di lotta è… da\n"
    .string "manuale!\p"
    .string "Ti auguro di continuare a\n"
    .string "collezionare successi!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan_IT::
    .string "Lotta tu stesso, invece di\n"
    .string "restare soltanto a guardare!\p"
    .string "È questo che mi ha detto il\n"
    .string "MAESTRO del mio DOJO KARATE!\p"
    .string "Comunque, ciò non mi impedirà di\n"
    .string "essere tuo fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect_IT::
    .string "C'è soltanto un ALLENATORE che\n"
    .string "merita il mio rispetto.\p"
    .string "È il MAESTRO del DOJO KARATE.\p"
    .string "Dovresti diventare anche tu fan\n"
    .string "del MAESTRO.$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster_IT::
    .string "Ho profondo rispetto per il\n"
    .string "MAESTRO del DOJO KARATE.\p"
    .string "Non diventerò mai fan di nessun\n"
    .string "altro!\p"
    .string "E lo griderò a tutti! Il MAESTRO\n"
    .string "del DOJO KARATE è un grande!$"

