Route8_Text_AidanIntro_DE::
	.string "Du weißt viel über POKéMON!\n"
	.string "Doch wie sieht es mit Chemie aus?$"

Route8_Text_AidanDefeat_DE::
	.string "Au!\n"
	.string "Eine Kernschmelze!$"

Route8_Text_AidanPostBattle_DE::
	.string "Meine schulischen Leistungen sind\n"
	.string "besser!$"

Route8_Text_StanIntro_DE::
	.string "O.K.!\n"
	.string "Die Spiele mögen beginnen!$"

Route8_Text_StanDefeat_DE::
	.string "Knapp vorbei ist auch daneben!$"

Route8_Text_StanPostBattle_DE::
	.string "Man kann nicht immer gewinnen!$"

Route8_Text_GlennIntro_DE::
	.string "Um zu gewinnen, benötigst du eine\n"
	.string "gute Strategie!$"

Route8_Text_GlennDefeat_DE::
	.string "Ich habe verloren!\n"
	.string "Das ist nicht logisch!$"

Route8_Text_GlennPostBattle_DE::
	.string "SLEIMA kämpft als Erstes... und...\n"
	.string "und... dann...$"

Route8_Text_PaigeIntro_DE::
	.string "Ich mag alle NIDORAN sehr gerne!\n"
	.string "Deshalb sammle ich sie!$"

Route8_Text_PaigeDefeat_DE::
	.string "Warum?\n"
	.string "Warum nur?$"

Route8_Text_PaigePostBattle_DE::
	.string "Wenn POKéMON sich entwickeln,\n"
	.string "werden sie groß und hässlich! Sie\l"
	.string "sollten klein und goldig bleiben!$"

Route8_Text_LeslieIntro_DE::
	.string "Die Schule macht Spaß! POKéMON zu\n"
	.string "trainieren aber auch!$"

Route8_Text_LeslieDefeat_DE::
	.string "O.K., ich gehe lieber zur Schule!$"

Route8_Text_LesliePostBattle_DE::
	.string "Wir sitzen hier fest, weil\n"
	.string "SAFFRONIA CITY abgeriegelt wird.$"

Route8_Text_AndreaIntro_DE::
	.string "MAUZI ist so süß!\n"
	.string "Miau, miauz!$"

Route8_Text_AndreaDefeat_DE::
	.string "Miauz!$"

Route8_Text_AndreaPostBattle_DE::
	.string "Aber TAUBSI und RATTFRATZ sind\n"
	.string "auch niedlich!$"

Route8_Text_MeganIntro_DE::
	.string "Es muss ziemlich blöd aussehen, wie\n"
	.string "wir hier herumstehen!$"

Route8_Text_MeganDefeat_DE::
	.string "Schau was du getan hast!$"

Route8_Text_MeganPostBattle_DE::
	.string "Der Wachtposten von SAFFRONIA\n"
	.string "CITY ist so gemein!\p"
	.string "Er lässt uns nicht in die Stadt!$"

Route8_Text_RichIntro_DE::
	.string "Ich bin ein weit herumgekommener\n"
	.string "Glücksspieler!$"

Route8_Text_RichDefeat_DE::
	.string "Den Jackpot habe ich noch nicht\n"
	.string "geknackt...$"

Route8_Text_RichPostBattle_DE::
	.string "Glücksspiele und POKéMON haben\n"
	.string "eines gemeinsam: Man kann nicht\l"
	.string "damit aufhören!$"

Route8_Text_JuliaIntro_DE::
	.string "Welches POKéMON ist süß, pummelig\n"
	.string "und kuschlig?$"

Route8_Text_JuliaDefeat_DE::
	.string "Hör auf!\p"
	.string "Sei nicht so gemein zu PIEPI!$"

Route8_Text_JuliaPostBattle_DE::
	.string "Ich habe gehört, PIEPI entwickelt\n"
	.string "sich, wenn man ihm einen MONDSTEIN\l"
	.string "gibt.$"

Route8_Text_UndergroundPathSign_DE::
	.string "TUNNELPFAD\n"
	.string "PRISMANIA CITY - LAVANDIA$"

Route8_Text_EliIntro_DE::
	.string "NORA: Die Kraft von Zwillingen ist\n"
	.string "fantastisch. Wusstest du das?$"

Route8_Text_EliDefeat_DE::
	.string "NORA: Aber…\n"
	.string "Wir nutzten unsere Zwillings-Kraft.$"

Route8_Text_EliPostBattle_DE::
	.string "NORA: Ich habe mein POKéMON mit\n"
	.string "JO gefangen!$"

Route8_Text_EliNotEnoughMons_DE::
	.string "NORA: Wir können nicht kämpfen,\n"
	.string "wenn du keine zwei POKéMON hast.$"

Route8_Text_AnneIntro_DE::
	.string "JO: Wir überrumpeln dich mit\n"
	.string "unserer Zwillings-Kraft.$"

Route8_Text_AnneDefeat_DE::
	.string "JO: Unsere Zwillings-Kraft…$"

Route8_Text_AnnePostBattle_DE::
	.string "JO: Ich trainiere POKéMON mit\n"
	.string "NORA!$"

Route8_Text_AnneNotEnoughMons_DE::
	.string "JO: Hallo! Lass uns kämpfen!\n"
	.string "Aber bring zwei POKéMON mit!$"

Route8_Text_RicardoIntro_DE::
	.string "Mein Motorrad spielt verrückt!$"

Route8_Text_RicardoDefeat_DE::
	.string "Argh!\n"
	.string "Das kann ich einfach nicht!$"

Route8_Text_RicardoPostBattle_DE::
	.string "Mir ist Gras in die Speichen\n"
	.string "gekommen.$"

Route8_Text_JarenIntro_DE::
	.string "Mach den Weg frei oder ich über-\n"
	.string "fahre dich!$"

Route8_Text_JarenDefeat_DE::
	.string "Du hast es drauf, Kiddie!$"

Route8_Text_JarenPostBattle_DE::
	.string "Denk bloß nicht, dass du etwas\n"
	.string "Besonderes bist, nur weil du\l"
	.string "gewonnen hast.$"

