Route8_Text_AidanIntro_IT::
    .string "Sembri forte con i POKéMON, ma\n"
    .string "come vai in chimica?$"

Route8_Text_AidanDefeat_IT::
    .string "Ahi!\n"
    .string "Fusione totale!$"

Route8_Text_AidanPostBattle_IT::
    .string "Sono più bravo a scuola che qui!$"

Route8_Text_StanIntro_IT::
    .string "Benissimo!\n"
    .string "Il dado è tratto!$"

Route8_Text_StanDefeat_IT::
    .string "Maledizione!\n"
    .string "M'è mancato un pizzico di fortuna!$"

Route8_Text_StanPostBattle_IT::
    .string "La dea bendata oggi non mi ha\n"
    .string "assistito!$"

Route8_Text_GlennIntro_IT::
    .string "Ti serve una tattica migliore!$"

Route8_Text_GlennDefeat_IT::
    .string "Non ha senso!$"

Route8_Text_GlennPostBattle_IT::
    .string "Prima usa GRIMER e poi… poi…$"

Route8_Text_PaigeIntro_IT::
    .string "Mi piacciono i NIDORAN, li\n"
    .string "colleziono!$"

Route8_Text_PaigeDefeat_IT::
    .string "Perché?\n"
    .string "Perché?$"

Route8_Text_PaigePostBattle_IT::
    .string "I POKéMON crescono e\n"
    .string "si imbruttiscono!\l"
    .string "Non dovrebbero evolversi!$"

Route8_Text_LeslieIntro_IT::
    .string "Mi piace la scuola, ma anche i\n"
    .string "POKéMON!$"

Route8_Text_LeslieDefeat_IT::
    .string "È meglio la scuola.$"

Route8_Text_LesliePostBattle_IT::
    .string "I cancelli di ZAFFERANOPOLI ci\n"
    .string "tengono bloccati!$"

Route8_Text_AndreaIntro_IT::
    .string "MEOWTH è così carino!\n"
    .string "Miao!$"

Route8_Text_AndreaDefeat_IT::
    .string "Miao!$"

Route8_Text_AndreaPostBattle_IT::
    .string "Anche PIDGEY e RATTATA sono\n"
    .string "bellini!$"

Route8_Text_MeganIntro_IT::
    .string "Cosa facciamo qui impalati?!$"

Route8_Text_MeganDefeat_IT::
    .string "Guarda cosa hai fatto!$"

Route8_Text_MeganPostBattle_IT::
    .string "Il guardiano di ZAFFERANOPOLI non\n"
    .string "ci fa passare. È proprio cattivo!$"

Route8_Text_RichIntro_IT::
    .string "Sono un errante RISCHIATUTTO!$"

Route8_Text_RichDefeat_IT::
    .string "Mi hai soffiato la vittoria!$"

Route8_Text_RichPostBattle_IT::
    .string "Questi giochi e i POKéMON sono\n"
    .string "come le ciliegie! Una tira l'altra!$"

Route8_Text_JuliaIntro_IT::
    .string "Qual è il POKéMON tondo e morbido?$"

Route8_Text_JuliaDefeat_IT::
    .string "Fermati!\p"
    .string "Non essere così crudele con il mio\n"
    .string "CLEFAIRY!$"

Route8_Text_JuliaPostBattle_IT::
    .string "CLEFAIRY si evolve se esposto\n"
    .string "alla PIETRALUNARE.\p"
    .string "L'ho letto sul POKéGIORNALE.\n"
    .string "Chissà se è vero!$"

Route8_Text_UndergroundPathSign_IT::
    .string "VIA SOTTERRANEA\n"
    .string "AZZURROPOLI - LAVANDONIA$"

Route8_Text_EliIntro_IT::
    .string "ELI: Mai sottovalutare la forza\n"
    .string "di due gemelle!$"

Route8_Text_EliDefeat_IT::
    .string "ELI: La forza di due gemelle non\n"
    .string "è bastata!$"

Route8_Text_EliPostBattle_IT::
    .string "ELI: Ho catturato i miei POKéMON\n"
    .string "insieme ad ANNE!$"

Route8_Text_EliNotEnoughMons_IT::
    .string "ELI: Se non hai almeno due\n"
    .string "POKéMON, non possiamo lottare.$"

Route8_Text_AnneIntro_IT::
    .string "ANNE: La forza di due gemelle ti\n"
    .string "stupirà!$"

Route8_Text_AnneDefeat_IT::
    .string "ANNE: Credevamo che la forza di\n"
    .string "due gemelle fosse imbattibile!$"

Route8_Text_AnnePostBattle_IT::
    .string "ANNE: Alleno i miei POKéMON insieme\n"
    .string "ad ELI.$"

Route8_Text_AnneNotEnoughMons_IT::
    .string "ANNE: Certo che vogliamo lottare!\n"
    .string "Ma devi portare due POKéMON!$"

Route8_Text_RicardoIntro_IT::
    .string "Alla mia moto manca la parola!$"

Route8_Text_RicardoDefeat_IT::
    .string "Oggi sono giù di giri.$"

Route8_Text_RicardoPostBattle_IT::
    .string "Mi dev'essere finita dell'erba\n"
    .string "nei raggi.$"

Route8_Text_JarenIntro_IT::
    .string "Togliti di mezzo, o ti investo!$"

Route8_Text_JarenDefeat_IT::
    .string "Stai scherzando?!$"

Route8_Text_JarenPostBattle_IT::
    .string "Ora non gasarti perché\n"
    .string "hai vinto una lotta.$"

