Route8_Text_AidanIntro_FR::
	.string "T'es habile avec tes POKéMON.\n"
	.string "Mais les maths, tu connais?$"

Route8_Text_AidanDefeat_FR::
	.string "Ouch!\n"
	.string "Mauvais calcul.$"

Route8_Text_AidanPostBattle_FR::
	.string "Je suis meilleur à l'école!$"

Route8_Text_StanIntro_FR::
	.string "Le sort en est jeté!$"

Route8_Text_StanDefeat_FR::
	.string "Haaa!\n"
	.string "Le hasard…$"

Route8_Text_StanPostBattle_FR::
	.string "Dame chance n'est pas avec moi!$"

Route8_Text_GlennIntro_FR::
	.string "Il te faut une bonne stratégie!$"

Route8_Text_GlennDefeat_FR::
	.string "Hé!\n"
	.string "Pas logique!$"

Route8_Text_GlennPostBattle_FR::
	.string "D'abord TADMORV, et après…\n"
	.string "Et puis…$"

Route8_Text_PaigeIntro_FR::
	.string "Moi, j'aime les NIDORAN! Yaha!$"

Route8_Text_PaigeDefeat_FR::
	.string "Hein?$"

Route8_Text_PaigePostBattle_FR::
	.string "Quand un POKéMON grandit,\n"
	.string "il devient gros et moche.\p"
	.string "Je les préfère tout petits!$"

Route8_Text_LeslieIntro_FR::
	.string "L'école c'est cool, comme les\n"
	.string "POKéMON!$"

Route8_Text_LeslieDefeat_FR::
	.string "Ben…\n"
	.string "L'école c'est plus facile!$"

Route8_Text_LesliePostBattle_FR::
	.string "On est bloqués ici, aux portes de\n"
	.string "SAFRANIA.$"

Route8_Text_AndreaIntro_FR::
	.string "MIAOUSS est si mignon. Miaou!$"

Route8_Text_AndreaDefeat_FR::
	.string "Miaou!$"

Route8_Text_AndreaPostBattle_FR::
	.string "Je trouve que ROUCOOL et RATTATA\n"
	.string "sont trop cool!$"

Route8_Text_MeganIntro_FR::
	.string "Je sais, on a l'air idiot à rester\n"
	.string "debout comme ça!$"

Route8_Text_MeganDefeat_FR::
	.string "Ben…\n"
	.string "C'est malin ça!$"

Route8_Text_MeganPostBattle_FR::
	.string "Le gardien de SAFRANIA ne nous\n"
	.string "laissera pas passer!\p"
	.string "Je sais que c'est son boulot, mais\n"
	.string "je ne l'aime pas beaucoup.$"

Route8_Text_RichIntro_FR::
	.string "Je suis un joueur errant!$"

Route8_Text_RichDefeat_FR::
	.string "J'ai raté le jackpot!$"

Route8_Text_RichPostBattle_FR::
	.string "Le jeu et les POKéMON, c'est comme\n"
	.string "les cacahuètes. \p"
	.string "Tu commences et tu peux plus\n"
	.string "t'arrêter! C'est fou!$"

Route8_Text_JuliaIntro_FR::
	.string "Qu'il est mimi, gentil et trognon\n"
	.string "ce POKéMON! Il est à qui?\l"
	.string "Hein? A qui?$"

Route8_Text_JuliaDefeat_FR::
	.string "Arrête!\p"
	.string "T'es pas gentil avec MELOFEE!$"

Route8_Text_JuliaPostBattle_FR::
	.string "Il paraît que MELOFEE peut\n"
	.string "évoluer grâce à une PIERRE LUNE.\p"
	.string "J'ai lu ça quelque part, je me\n"
	.string "demande si c'est vrai.$"

Route8_Text_UndergroundPathSign_FR::
	.string "SOUTERRAIN\n"
	.string "CELADOPOLE - LAVANVILLE$"

Route8_Text_EliIntro_FR::
	.string "ELI: La puissance des jumeaux est\n"
	.string "fantastique, tu le savais pas?$"

Route8_Text_EliDefeat_FR::
	.string "ELI: Mais…\n"
	.string "On a utilisé notre puissance…$"

Route8_Text_EliPostBattle_FR::
	.string "ELI: J'ai attrapé mes POKéMON\n"
	.string "avec ANNE.$"

Route8_Text_EliNotEnoughMons_FR::
	.string "ELI: On ne pourra pas se battre\n"
	.string "ensemble si tu n'as qu'un POKéMON.$"

Route8_Text_AnneIntro_FR::
	.string "ANNE: On va te montrer notre\n"
	.string "puissance!$"

Route8_Text_AnneDefeat_FR::
	.string "ANNE: Notre force de jumelles…$"

Route8_Text_AnnePostBattle_FR::
	.string "ANNE: Je dresse mes POKéMON\n"
	.string "avec ELI.$"

Route8_Text_AnneNotEnoughMons_FR::
	.string "ANNE: Hi, hi. Si tu veux combattre,\n"
	.string "il te faut deux POKéMON.$"

Route8_Text_RicardoIntro_FR::
	.string "Je ne crains personne sur ma\n"
	.string "bécane.$"

Route8_Text_RicardoDefeat_FR::
	.string "Aaah, non!\n"
	.string "J'suis à sec.$"

Route8_Text_RicardoPostBattle_FR::
	.string "Le terrain était mauvais pour moi.$"

Route8_Text_JarenIntro_FR::
	.string "Pousse-toi de là, ou je te\n"
	.string "roule dessus.$"

Route8_Text_JarenDefeat_FR::
	.string "Tu rigoles pas toi…$"

Route8_Text_JarenPostBattle_FR::
	.string "Ne prends pas la grosse tête\n"
	.string "juste pour ça…$"

