Route8_Text_AidanIntro_ES::
    .string "Parece que sabes mucho sobre\n"
    .string "POKéMON, pero...\l"
    .string "¿Qué tal en química?$"

Route8_Text_AidanDefeat_ES::
    .string "¡Ah!\n"
    .string "¡Fusión nuclear!$"

Route8_Text_AidanPostBattle_ES::
    .string "¡Se me da mejor en el cole!$"

Route8_Text_StanIntro_ES::
    .string "¡Muy bien!\n"
    .string "¡Echemos los dados!$"

Route8_Text_StanDefeat_ES::
    .string "¡Vaya!\n"
    .string "¡Me he quedado corto!$"

Route8_Text_StanPostBattle_ES::
    .string "¡Hoy no es mi día de suerte!$"

Route8_Text_GlennIntro_ES::
    .string "¡Necesitas una buena estrategia!$"

Route8_Text_GlennDefeat_ES::
    .string "¡No es lógico!$"

Route8_Text_GlennPostBattle_ES::
    .string "Usa a GRIMER primero... y...\n"
    .string "y... después...$"

Route8_Text_PaigeIntro_ES::
    .string "¡Me gustan los NIDORAN\n"
    .string "y por eso los colecciono!$"

Route8_Text_PaigeDefeat_ES::
    .string "Pero ¿por qué?$"

Route8_Text_PaigePostBattle_ES::
    .string "¡Cuando los POKéMON crecen\n"
    .string "se vuelven muy feos!\l"
    .string "¡No me gustan cuando evolucionan!$"

Route8_Text_LeslieIntro_ES::
    .string "¡Me gusta el colegio, y los\n"
    .string "POKéMON!$"

Route8_Text_LeslieDefeat_ES::
    .string "Prefiero el colegio, está claro\n"
    .string "que se me da mucho mejor.$"

Route8_Text_LesliePostBattle_ES::
    .string "Querría darme una vuelta, pero...\p"
    .string "La entrada a AZAFRÁN está\n"
    .string "bloqueada...$"

Route8_Text_AndreaIntro_ES::
    .string "¡MEOWTH es muy mono, meow, meow!$"

Route8_Text_AndreaDefeat_ES::
    .string "¡Meow!$"

Route8_Text_AndreaPostBattle_ES::
    .string "¡Creo que PIDGEY y RATTATA\n"
    .string "también son muy monos!$"

Route8_Text_MeganIntro_ES::
    .string "¡Debemos de tener un aspecto muy\n"
    .string "tonto!$"

Route8_Text_MeganDefeat_ES::
    .string "¡Mira lo que has hecho!$"

Route8_Text_MeganPostBattle_ES::
    .string "El guardián de la entrada a\n"
    .string "AZAFRÁN no nos dejará pasar.\p"
    .string "¡Sé que hace su trabajo,\n"
    .string "pero es que es lo peor!$"

Route8_Text_RichIntro_ES::
    .string "¡Soy un jugón errante!$"

Route8_Text_RichDefeat_ES::
    .string "¡He perdido el gran premio!$"

Route8_Text_RichPostBattle_ES::
    .string "¡Cuando juego y entreno POKéMON\n"
    .string "no puedo parar!$"

Route8_Text_JuliaIntro_ES::
    .string "¿Qué POKéMON es mono, redondo\n"
    .string "y blando?$"

Route8_Text_JuliaDefeat_ES::
    .string "¡Ya basta!\p"
    .string "¡No seas cruel con mis CLEFAIRY!$"

Route8_Text_JuliaPostBattle_ES::
    .string "He leído que CLEFAIRY evoluciona\n"
    .string "cuando es expuesto a una PIEDRA\l"
    .string "LUNAR.\p"
    .string "Lo leí en el DIARIO POKéMON.\n"
    .string "¿Será verdad?$"

Route8_Text_UndergroundPathSign_ES::
    .string "VÍA SUBTERRÁNEA:\n"
    .string "CIUDAD AZULONA - PUEBLO LAVANDA$"

Route8_Text_EliIntro_ES::
    .string "TITA: La fuerza que tienen los\n"
    .string "hermanos gemelos es enorme,\l"
    .string "¿lo sabías?$"

Route8_Text_EliDefeat_ES::
    .string "TITA: Pero si hemos unido nuestras\n"
    .string "fuerzas...$"

Route8_Text_EliPostBattle_ES::
    .string "TITA: Yo atrapé mi POKéMON\n"
    .string "con LIN.$"

Route8_Text_EliNotEnoughMons_ES::
    .string "TITA: Si no tienes dos POKéMON,\n"
    .string "no podemos luchar contigo.$"

Route8_Text_AnneIntro_ES::
    .string "LIN: ¡No vas a poder con estas\n"
    .string "gemelas!$"

Route8_Text_AnneDefeat_ES::
    .string "LIN: Pues sí que has podido...$"

Route8_Text_AnnePostBattle_ES::
    .string "LIN: Yo crío a mi POKéMON\n"
    .string "con TITA.$"

Route8_Text_AnneNotEnoughMons_ES::
    .string "LIN: Nos gustaría luchar contigo,\n"
    .string "pero necesitas dos POKéMON.$"

Route8_Text_RicardoIntro_ES::
    .string "¡Mi moto está como una moto!$"

Route8_Text_RicardoDefeat_ES::
    .string "No sé qué me ha pasado...$"

Route8_Text_RicardoPostBattle_ES::
    .string "Se me ha enganchado césped\n"
    .string "en los radios de las ruedas...$"

Route8_Text_JarenIntro_ES::
    .string "Apártate si no quieres que te pase\n"
    .string "por encima.$"

Route8_Text_JarenDefeat_ES::
    .string "Tú vas en serio, ¿no?$"

Route8_Text_JarenPostBattle_ES::
    .string "Tampoco te pongas en plan tonto\n"
    .string "por haber ganado.$"
