FiveIsland_LostCave_Room10_Text_SelphyIntro_FR::
	.string "Qu-qu'est-ce que tu essaies\n"
	.string "de faire?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat_FR::
	.string "Oh, je croyais que tu voulais me\n"
	.string "faire du mal!$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome_FR::
	.string "Je suis heureuse que tu sois là.\p"
	.string "Je commençais à en avoir assez\n"
	.string "de marcher seule.\p"
	.string "Tu me raccompagnes jusqu'à\n"
	.string "chez moi?$"

