CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent_ES::
    .string "¡Compraré un POKé MUÑECO\n"
    .string "para mi novia!\p"
    .string "Seguro que es el último grito\n"
    .string "en regalos.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll_ES::
    .string "¡Me han contado una cosa!\p"
    .string "¡Puedes huir de un POKéMON\n"
    .string "salvaje si le distraes con un\l"
    .string "POKé MUÑECO!$"

CeladonCity_DepartmentStore_4F_Text_FloorSign_ES::
    .string "¡Dilo con un regalo!\p"
    .string "P3: REGALOS\p"
    .string "¡Evolución Especial!\n"
    .string "¡Diversas PIEDRAS elementales\l"
    .string "en venta!$"
