CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent_FR::
	.string "Je cherche un cadeau pour ma\n"
	.string "copine.\p"
	.string "Une belle POKéPOUPEE devrait\n"
	.string "faire l'affaire!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll_FR::
	.string "Ecoute donc…\p"
	.string "Tu peux fuir face aux POKéMON\n"
	.string "sauvages en les occupant avec une\l"
	.string "POKéPOUPEE!$"

CeladonCity_DepartmentStore_4F_Text_FloorSign_FR::
	.string "Un cadeau… L'amour… La vie!\n"
	.string "3ème: CADEAUX\p"
	.string "Vive les évolutions!\n"
	.string "Les PIERRES sont en vente!$"

