ViridianCity_House_Text_NicknamingIsFun_ES::
    .string "Inventarse motes es divertido, pero\n"
    .string "difícil.\p"
    .string "Es más fácil recordar nombres\n"
    .string "sencillos.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo_ES::
    .string "¡A mi padre también le gustan los\n"
    .string "POKéMON!$"

ViridianCity_House_Text_Speary_ES::
    .string "SPEARY: ¡Spe-pe-peeary!$"

ViridianCity_House_Text_SpearowNameSpeary_ES::
    .string "SPEAROW\n"
    .string "Nombre: SPEARY$"
