ViridianCity_House_Text_NicknamingIsFun_FR::
	.string "Trouver des noms, c'est rigolo mais\n"
	.string "c'est dur!\p"
	.string "Les noms les plus simples sont les\n"
	.string "plus faciles à retenir.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo_FR::
	.string "Mon papa aime les POKéMON aussi.$"

ViridianCity_House_Text_Speary_FR::
	.string "PIAFFY: Cui-cui!$"

ViridianCity_House_Text_SpearowNameSpeary_FR::
	.string "PIAFABEC\n"
	.string "Nom: PIAFFY$"

