SilphCo_3F_Text_WhatAmIToDo_ES::
    .string "Trabajo para SILPH S.A.\n"
    .string "¿Qué debería hacer?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs_ES::
    .string "¡{PLAYER}! ¡Tú y tus POKéMON\n"
    .string "nos habéis salvado!$"

SilphCo_3F_Text_GruntIntro_ES::
    .string "¡Eh, no nos molestes más!$"

SilphCo_3F_Text_GruntDefeat_ES::
    .string "¡Me rindo!$"

SilphCo_3F_Text_GruntPostBattle_ES::
    .string "¿Una pista? ¡Para abrir las puertas\n"
    .string "utiliza una LLAVE MAGNÉTICA!$"

SilphCo_3F_Text_JoseIntro_ES::
    .string "¡¡¡Apoyo más al TEAM ROCKET\n"
    .string "que a SILPH S.A.!!!$"

SilphCo_3F_Text_JoseDefeat_ES::
    .string "¡Me has derrotado!$"

SilphCo_3F_Text_JosePostBattle_ES::
    .string "Mmmm...\p"
    .string "¡El TEAM ROCKET me dijo que si\n"
    .string "les ayudaba, me dejarían estudiar\l"
    .string "a los POKéMON!$"

SilphCo_3F_Text_FloorSign_ES::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P2$"
