SilphCo_3F_Text_WhatAmIToDo_FR::
	.string "Je travaille pour la SYLPHE SARL.\n"
	.string "Que faire d'autre?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs_FR::
	.string "{PLAYER}!\p"
	.string "Toi et tes POKéMON, vous nous\n"
	.string "avez sauvés!$"

SilphCo_3F_Text_GruntIntro_FR::
	.string "T'occupe pas de nos affaires!$"

SilphCo_3F_Text_GruntDefeat_FR::
	.string "Yaha!\n"
	.string "T'es trop fort!$"

SilphCo_3F_Text_GruntPostBattle_FR::
	.string "Tu peux ouvrir les portes avec\n"
	.string "la CARTE MAGN.!$"

SilphCo_3F_Text_JoseIntro_FR::
	.string "Je préfère la TEAM ROCKET à\n"
	.string "la SYLPHE SARL!!!$"

SilphCo_3F_Text_JoseDefeat_FR::
	.string "!!!\n"
	.string "Tu m'as eu!$"

SilphCo_3F_Text_JosePostBattle_FR::
	.string "Hmmm…\p"
	.string "J'aide la TEAM ROCKET et ils me\n"
	.string "laissent étudier les POKéMON!$"

SilphCo_3F_Text_FloorSign_FR::
	.string "SYLPHE SARL.\n"
	.string "2ème étage.$"

