SilphCo_3F_Text_WhatAmIToDo_IT::
    .string "Lavoro per la SILPH SpA!\n"
    .string "Cosa devo fare?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs_IT::
    .string "{PLAYER}! Tu e i tuoi POKéMON ci\n"
    .string "avete salvato!$"

SilphCo_3F_Text_GruntIntro_IT::
    .string "Non devi scocciare più, chiaro?!$"

SilphCo_3F_Text_GruntDefeat_IT::
    .string "Mi arrendo!$"

SilphCo_3F_Text_GruntPostBattle_IT::
    .string "Un consiglio? Puoi aprire le porte\n"
    .string "con l'APRIPORTA!$"

SilphCo_3F_Text_JoseIntro_IT::
    .string "Sto dalla parte di TEAM ROCKET,\n"
    .string "più che da quella della SILPH\l"
    .string "SpA!!!$"

SilphCo_3F_Text_JoseDefeat_IT::
    .string "Mi hai sconfitto!$"

SilphCo_3F_Text_JosePostBattle_IT::
    .string "Accidenti!\p"
    .string "Quelli di TEAM ROCKET mi han detto\n"
    .string "che se li avessi aiutati avrei\l"
    .string "potuto studiare i POKéMON.$"

SilphCo_3F_Text_FloorSign_IT::
    .string "DIREZIONE della SILPH SpA\n"
    .string "2ºP$"

