SilphCo_3F_Text_WhatAmIToDo_DE::
	.string "Ich arbeite für die SILPH CO.!\n"
	.string "Was soll ich bloß machen?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs_DE::
	.string "{PLAYER}! Du hast uns mit Hilfe\n"
	.string "deiner POKéMON gerettet!$"

SilphCo_3F_Text_GruntIntro_DE::
	.string "Hör endlich auf, uns zu nerven!$"

SilphCo_3F_Text_GruntDefeat_DE::
	.string "Ich gebe auf!$"

SilphCo_3F_Text_GruntPostBattle_DE::
	.string "Ein Tipp? Du brauchst einen\n"
	.string "TÜRÖFFNER!$"

SilphCo_3F_Text_JoseIntro_DE::
	.string "Ich arbeite für das TEAM ROCKET,\n"
	.string "die SILPH CO. zahlt zu wenig!!!$"

SilphCo_3F_Text_JoseDefeat_DE::
	.string "Du hast mich erwischt!$"

SilphCo_3F_Text_JosePostBattle_DE::
	.string "Mist...\p"
	.string "Das TEAM ROCKET hätte mich für\n"
	.string "meine Hilfe die POKéMON studieren\l"
	.string "lassen!$"

SilphCo_3F_Text_FloorSign_DE::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "2 OG$"

