ThreeIsland_BerryForest_Text_HelpScaryPokemon_FR::
	.string "LOSTELLE: Sniff…\n"
	.string "Aidez-moiiii…\p"
	.string "Un méchant POKéMON arrête pas\n"
	.string "de m'embêteeer.\p"
	.string "Il me fait peur.\n"
	.string "Sniff… Je peux plus partir.\p"
	.string "Je veux rentrer chez moiiii… $"

ThreeIsland_BerryForest_Text_HereItComesAgain_FR::
	.string "Ohh! Il revient encore!\n"
	.string "Non, va-t-en! J'ai peuuur!\p"
	.string "Aaaaah!!\n"
	.string "Je veux mon papa!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis_FR::
	.string "Oh! J'ai eu trop peur!\n"
	.string "Merci beaucoup!\p"
	.string "Je voulais ramasser des BAIES.\n"
	.string "Tiens, c'est pour toi!$"

ThreeIsland_BerryForest_Text_LetsGoHome_FR::
	.string "Tu t'appelles comment?\p"
	.string "J'ai peur, tu veux bien venir avec\n"
	.string "moi jusque chez mon papa?\p"
	.string "Ouiii!\n"
	.string "On y va! Je rentre à ma maison.$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull_FR::
	.string "Ta POCHE A BAIES est pleine.\n"
	.string "Tu ne peux pas prendre ça.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest_FR::
	.string "Bienvenue aux BOIS BAIES\p"
	.string "Echangez vos BAIES pour régaler\n"
	.string "vos amis et vos POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons_FR::
	.string "Attention aux POKéMON sauvages\n"
	.string "attirés par les BAIES.$"

