ThreeIsland_BerryForest_Text_HelpScaryPokemon_IT::
    .string "LISETTA: Aiuto! Aiuto!\p"
    .string "Prima è arrivato un POKéMON\n"
    .string "spaventoso!\p"
    .string "Ora ho tanta paura che non posso\n"
    .string "muovermi! Ma voglio andare a casa!$"

ThreeIsland_BerryForest_Text_HereItComesAgain_IT::
    .string "Ecco! Ritorna!\n"
    .string "No! No! Via! Via!\p"
    .string "Voglio il mio papino!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis_IT::
    .string "Grazie! Mi hai salvata!\p"
    .string "Stavo cercando BACCHE.\p"
    .string "Ecco, prendi!$"

ThreeIsland_BerryForest_Text_LetsGoHome_IT::
    .string "Come ti chiami?\p"
    .string "Ho ancora paura! Puoi\n"
    .string "accompagnarmi dal mio papino?\p"
    .string "Grazie!\n"
    .string "LISETTA torna a casa!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull_IT::
    .string "Il PORTABACCHE è pieno.\n"
    .string "Non posso darti il mio regalo.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest_IT::
    .string "Benvenuti nel BOSCO\n"
    .string "BACCOSO!\p"
    .string "Condividete le BACCHE con i\n"
    .string "POKéMON e gli altri ALLENATORI!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons_IT::
    .string "Guardati dai POKéMON selvatici\n"
    .string "ghiotti di BACCHE!$"

