ThreeIsland_BerryForest_Text_HelpScaryPokemon_DE::
	.string "IRRMA: Wimmer… schnief…\n"
	.string "Oh! Hilf mir bitte!\p"
	.string "Ein Angst einflößendes POKéMON ist\n"
	.string "dort vor kurzem aufgetaucht.\p"
	.string "Es war so gruselig.\n"
	.string "Es hat IRRMA Angst gemacht.\p"
	.string "Ich bin zu verängstigt, um mich\n"
	.string "zu bewegen! Aber ich möchte\l"
	.string "nach Hause gehen…$"

ThreeIsland_BerryForest_Text_HereItComesAgain_DE::
	.string "Oh! Hier ist es wieder! Nein!\n"
	.string "Verschwinde! Es macht mir Angst!\p"
	.string "Wahhhhhhhhhhh!\n"
	.string "Ich will zu meinem Papa!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis_DE::
	.string "Oh! Das war so gruselig!\n"
	.string "Dankeschön!\p"
	.string "IRRMA wollte hier BEEREN\n"
	.string "pflücken.\p"
	.string "Das ist für dich!$"

ThreeIsland_BerryForest_Text_LetsGoHome_DE::
	.string "Wie heißt du?\p"
	.string "IRRMA ist so verängstigt!\n"
	.string "Bringst du mich nach Hause?\p"
	.string "O.K.!\n"
	.string "Lass uns nach Hause gehen!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull_DE::
	.string "Deine BEERENTÜTE ist voll.\n"
	.string "Ich denke, du willst das nicht.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest_DE::
	.string "Willkommen im BEERENFORST!\p"
	.string "Sei freundlich und teile die BEEREN\n"
	.string "mit Anderen und POKéMON!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons_DE::
	.string "Nimm dich vor wilden POKéMON,\n"
	.string "die BEEREN lieben, in Acht!$"

