CeladonCity_Hotel_Text_ThisHotelIsForPeople_ES::
    .string "¿POKéMON?\n"
    .string "No, éste es un hotel para gente.\p"
    .string "¡Está completo!$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend_ES::
    .string "Estoy de vacaciones con mi\n"
    .string "hermano y con mi novio.\p"
    .string "¡AZULONA es una bonita ciudad!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother_ES::
    .string "¿Por qué trajo a su hermano?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation_ES::
    .string "¡Mi hermana me trajo de\n"
    .string "vacaciones!$"
