FourIsland_Text_IslandSign_FR::
	.string "ILE 4\n"
	.string "La chaleureuse île glacée$"

FourIsland_Text_LoreleiHasReturned_FR::
	.string "OLGA est de retour.\p"
	.string "Elle a dû trouver la vie en ville\n"
	.string "trop stressante.$"

FourIsland_Text_LoreleiMetLaprasAsChild_FR::
	.string "OLGA est revenue.\p"
	.string "Son LOKHLASS, ça doit être\n"
	.string "celui qu'elle a depuis son enfance.\p"
	.string "Je crois qu'elle l'avait attrapé\n"
	.string "dans la GROTTE DE GLACE.\p"
	.string "Ce POKéMON a dû passer des\n"
	.string "années avec elle.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa_FR::
	.string "{RIVAL}: Hey!\n"
	.string "{PLAYER}!\p"
	.string "Qu'est-ce que tu fais aux\n"
	.string "ILES SEVII?\p"
	.string "Tu devrais arrêter de me suivre,\n"
	.string "tu crois pas?\p"
	.string "De toute façon, j'ai plus rien à\n"
	.string "faire ici, depuis que\p"
	.string "j'ai reçu mon OEUF POKéMON.\p"
	.string "Pff, je suis sûr que tu sais\n"
	.string "rien sur les OEUFS POKéMON.\p"
	.string "C'est pas comme ça que tu vas\n"
	.string "remplir ton POKéDEX NATIONAL.\p"
	.string "Au fait, j'ai ramené une vieille\n"
	.string "connaissance avec moi.\p"
	.string "Va chercher un peu si tu veux\n"
	.string "savoir qui c'est.\p"
	.string "Moi, j'ai pas de temps à perdre\n"
	.string "avec toi.\p"
	.string "Allez, tchao!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls_FR::
	.string "Oh, tu m'as trouvée!\n"
	.string "Mais ne dis rien à OLGA!\p"
	.string "Tu savais qu'elle a une collection\n"
	.string "de poupées?\p"
	.string "Sa collection grandit à chaque fois\n"
	.string "qu'elle revient sur l'ILE 4.$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce_FR::
	.string "Oooh, c'est frais!\p"
	.string "J'me suis fait un cornet avec ce\n"
	.string "que j'ai ramassé dans la GROTTE\l"
	.string "DE GLACE.$"

FourIsland_Text_LoreleisHouse_FR::
	.string "MAISON D'OLGA$"

