FourIsland_Text_IslandSign_ES::
    .string "ISLA QUARTA\n"
    .string "La isla cálida, azul y rara.$"

FourIsland_Text_LoreleiHasReturned_ES::
    .string "LORELEI ha vuelto.\p"
    .string "Creo que la vida de la ciudad le\n"
    .string "resultaba demasiado estresante...$"

FourIsland_Text_LoreleiMetLaprasAsChild_ES::
    .string "LORELEI ha vuelto.\p"
    .string "Creo que el LAPRAS que tiene,\n"
    .string "es el mismo que atrapó de pequeña.\p"
    .string "Yo creo que se hizo con él\n"
    .string "en la CUEVA GLACIADA...\p"
    .string "Me parece que lo tiene desde\n"
    .string "entonces.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa_ES::
    .string "{RIVAL}: ¡Eh, {PLAYER}!\p"
    .string "¿Qué estás haciendo en\n"
    .string "ARCHI7?\p"
    .string "Deberías dejar de copiarte de todo\n"
    .string "lo que hago.\p"
    .string "Bueno, yo ya tengo mi HUEVO\n"
    .string "POKéMON, así que no me queda\l"
    .string "nada más que hacer en esta isla.\p"
    .string "No sé ni para qué te cuento esto,\n"
    .string "seguro que no tienes ni idea de\l"
    .string "lo que es un HUEVO POKéMON.\p"
    .string "Así no vas a completar la POKéDEX\n"
    .string "NACIONAL en la vida.\p"
    .string "Por cierto, he visto a alguien a\n"
    .string "quien conocemos en la isla.\p"
    .string "¿No te das una vuelta a ver\n"
    .string "quién es?\l"
    .string "¿No te pica la curiosidad?\p"
    .string "Yo me largo, no tengo tiempo.\p"
    .string "¡Nos vemos!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls_ES::
    .string "¡Me has encontrado!\n"
    .string "¡No se lo digas a LORELEI!\p"
    .string "¿Sabías que LORELEI tiene un\n"
    .string "montón de muñecos de peluche?\p"
    .string "¡Cada vez que vuelve a ISLA\n"
    .string "QUARTA, aumenta la colección!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce_ES::
    .string "¡Uyyy, qué fresquito!\p"
    .string "Me he hecho un granizado con\n"
    .string "hielo de la CUEVA GLACIADA.\p"
    .string "¡Está fresquito y riquísimo!$"

FourIsland_Text_LoreleisHouse_ES::
    .string "CASA DE LORELEI$"
