FourIsland_Text_IslandSign_IT::
    .string "QUARTISOLA\n"
    .string "La calda isola blu$"

FourIsland_Text_LoreleiHasReturned_IT::
    .string "LORELEI è tornata.\p"
    .string "Forse la vita di città era troppo\n"
    .string "stressante per lei.$"

FourIsland_Text_LoreleiMetLaprasAsChild_IT::
    .string "LORELEI è tornata.\p"
    .string "Il suo LAPRAS, credo che sia lo\n"
    .string "stesso che ha da quando era\l"
    .string "bambina.\p"
    .string "Credo che l'abbia catturato nella\n"
    .string "GROTTA GELATA.\p"
    .string "E da allora, non se ne è mai\n"
    .string "separata.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa_IT::
    .string "{RIVAL}: Ehi!\n"
    .string "{PLAYER}!\p"
    .string "Che ci fai qui sulle isole\n"
    .string "del SETTIPELAGO?\p"
    .string "La devi smettere di\n"
    .string "copiarmi, sai?\p"
    .string "Comunque, ho già preso il mio\n"
    .string "UOVO POKéMON, quindi\l"
    .string "me ne sto andando.\p"
    .string "Scommetto che non sai\n"
    .string "neppure cosa sia un UOVO\l"
    .string "POKéMON!\p"
    .string "E come credi di completare il\n"
    .string "POKéDEX NAZIONALE, senza\l"
    .string "un UOVO?\p"
    .string "Ah, dimenticavo: ho visto una\n"
    .string "nostra comune conoscenza su\l"
    .string "quest'isola.\p"
    .string "T'ho incuriosito? Beh, allora\n"
    .string "fatti un giro sull'isola, la\l"
    .string "troverai anche tu.\p"
    .string "Io non ho proprio altro tempo\n"
    .string "da perdere.\p"
    .string "Ci becchiamo in giro!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls_IT::
    .string "Mi hai trovato!\n"
    .string "Non dirlo a LORELEI, ti prego!\p"
    .string "A proposito di LORELEI: sapevi che\n"
    .string "ha centinaia di bambole di pezza?\p"
    .string "Ogni volta che torna a QUARTISOLA,\n"
    .string "aggiunge qualche bambola alla\l"
    .string "collezione!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce_IT::
    .string "Che delizia!\p"
    .string "Mi sono fatto una granita al caffè\n"
    .string "con il ghiaccio della GROTTA\l"
    .string "GELATA!\p"
    .string "È così rinfrescante!$"

FourIsland_Text_LoreleisHouse_IT::
    .string "CASA di LORELEI$"

