FourIsland_Text_IslandSign_DE::
	.string "EILAND VIER\n"
	.string "Warmes, blaues Eisschollen-Eiland$"

FourIsland_Text_LoreleiHasReturned_DE::
	.string "LORELEI ist zurückgekehrt.\p"
	.string "War das Leben in der Stadt\n"
	.string "etwa zu stressig?$"

FourIsland_Text_LoreleiMetLaprasAsChild_DE::
	.string "LORELEI ist zurück.\p"
	.string "Sie hat immer noch das LAPRAS,\n"
	.string "das sie in ihrer Kindheit traf.\p"
	.string "Ich erinnere mich, dass sie es\n"
	.string "in der EISKASKADENHÖHLE\l"
	.string "gefangen hatte.\l"
	.string "Womöglich ist dieses POKéMON\l"
	.string "seither nicht von ihrer Seite\l"
	.string "gewichen.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa_DE::
	.string "{RIVAL}: Heh!\n"
	.string "{PLAYER}!\p"
	.string "Was machst du hier auf\n"
	.string "SEVII EILAND?\p"
	.string "Du solltest aufhören, mich\n"
	.string "nachzuahmen!\p"
	.string "Egal, ich habe mein POKéMON-EI\n"
	.string "bereits, also hält mich nichts mehr\l"
	.string "hier.\l"
	.string "Heh, ich glaube, du weißt nichts\l"
	.string "über POKéMON-EIER.\p"
	.string "Du wirst nie deinen NATIONALEN\n"
	.string "POKéDEX vervollständigen.\p"
	.string "Apropos, ich sah jemanden auf\n"
	.string "dieser Insel, den wir beide kennen.\p"
	.string "Warum siehst du dich nicht um, wenn\n"
	.string "ich dich neugierig gemacht habe?\p"
	.string "Ich? Ich habe keine Zeit zu\n"
	.string "verlieren!\p"
	.string "Wir sehen uns!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls_DE::
	.string "Oh, du hast mich gefunden!\n"
	.string "Bitte verrate LORELEI nichts.\p"
	.string "Wusstest du, dass LORELEI eine\n"
	.string "ganze Menge Plüschpuppen besitzt?\p"
	.string "Bei jedem Besuch auf EILAND VIER\n"
	.string "wächst ihre Sammlung!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce_DE::
	.string "Oh, fröstel!\p"
	.string "Ich habe aus dem Eis, das ich in\n"
	.string "der EISKASKADENHÖHLE abgetragen\l"
	.string "habe, einen Eis-Drink zubereitet.\p"
	.string "Frostig und lecker!$"

FourIsland_Text_LoreleisHouse_DE::
	.string "HAUS von LORELEI$"

